### ISSUE TITLE
[IE 11] Box with full={"horizontal"} is not working as expected inside a Layer

### ISSUE THREAD

**Issue by gustahrodrigues** [grommet/grommet#1003]
On IE 11, a Box with full={"horizontal"} inside a Layer is not working as expected.

```
<App>
    <Layer>
        <Box full={"horizontal"}>
            <span>Text</span>
            <span>Text</span>
            <span>Text</span>
            <span>Text</span>
        </Box>
     </Layer>
</App>
```
### Expected Behavior

Box should fill the entire horizontal space available
### Actual Behavior

Box width is filling only the content width
### URL, screen shot, or Codepen exhibiting the issue

Codepen [avalilable here](https://codepen.io/gustahrodrigues/pen/KgJEGm).

### Steps to Reproduce
1. Open [this CodePen](https://codepen.io/gustahrodrigues/pen/KgJEGm) on Chrome/Firefox and IE.
2. Check the Layer size.
### Your Environment

- Grommet version: Latest (Codepen)
- Browser Name and version: IE 11
- Operating System and version (desktop or mobile): Windows 7 Profissional

**Comment by davidcalhoun** [comment]
Thanks for submitting this issue and creating a Codepen to go along with it!

Looks like it's the IE11 flex bug described here: https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items

I'll write up a PR with an IE11-specific fix soon.

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/5cb373ffa51c0216d85a2a58b1e07f83f3934a06
