### ISSUE TITLE
Pulse component: Usage text correction

### ISSUE THREAD

**Issue by hetmann** [grommet/grommet#1011]
Docs for Pulse component must be updated with correct Usage instructions.

### Expected Behavior
<code>
import Pulse from 'grommet/components/icons/Pulse';
</code>

### Actual Behavior
<code>
import Pulse from 'grommet/components/Pulse';
</code>
```bash
Module not found: Error: Cannot resolve module 'grommet/components/Pulse'
```

### Steps to Reproduce
 1. Use the Pulse docs to import the component in a new project
 2. Will get an error explained in "Actual Behavior"
 3. You can fix it by import the correct path `grommet/components/icons/Pulse`

### Your Environment

* Grommet version: 1.0.0
* Browser Name and version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
* Operating System and version (desktop or mobile): Mac OS X 10.11.6 (notebook)

**Comment by davidcalhoun** [comment]
Thanks for submitting this issue!  Looks like this was an issue for the docs, which is in another repo, so I've created a PR over there.

**Comment by alansouzati** [comment]
Thanks @davidcalhoun
