### ISSUE TITLE
Request: Optionally Pin Table Title Row

### ISSUE THREAD

**Issue by ToddBarkalowHPE** [grommet/grommet#1015]
As per the Slack discussion:

We have a requirement for showing a table, with the title pinned so scrolling a table that has more rows than screen real estate would only scroll the rows, not the title. Currently, the entire page content scrolls. The request is to optionally allow the top table title line to be pinned and not scroll with the data (rows).

It would be great if this were an option so title row can scroll with entire page, or be pinned to top and not scroll.

**Comment by mcwebb** [comment]
I think this is what is intended by Table's `scrollable` property, however I'm having some issues with it at the moment (see #793).

**Comment by dgennetten** [comment]
This is fixed with #793
