### ISSUE TITLE
Request: Text Control for Large Strings

### ISSUE THREAD

**Issue by ToddBarkalowHPE** [grommet/grommet#1016]
As discussed in Slack: 

We have a requirement for showing information in a Tile (or even just a Box) where some of the data is too long or titles are too long to display.  

An example of titles could be a name of an array, volume, etc. that is 256 characters.  

In Piano, there was the construct of ellipses.  We can certainly create a component for this, but we thought many could benefit from such a control, or pattern, or construct.

**Comment by ericsoderberghp** [comment]
In grommet terms, I was thinking we'd add an option to Heading, Label, and Title to limit it to a single line and truncate that line with an ellipses if the content is too long for the container.

**Comment by ericsoderberghp** [comment]
Added in 41d054341abe5fd20adfc4c29979e089d3d04f3f.

**Comment by ToddBarkalowHPE** [comment]
Thank you.  Great option!
