### ISSUE TITLE
Anchor onClick handler Event processing code broken after 1.0.0 upgrade

### ISSUE THREAD

**Issue by mars76** [grommet/grommet#1017]
Hi,

  I was using 0.6.11 version before and my app was working fine. I recently saw that version 1.0.0 is available and upgraded it and now my Anchors are not working (Event Handlers are not working).

### Expected Behavior
I was getting the Id attribute on the Anchor earlier with e.currentTarget.id

### Actual Behavior
now when the event Object i am getting has a Handler Object, Target which is SyntheticMouseEvent whose _targetInst is null and a property called IsRevoked which has false boolean value.

I can get the Native Event using e.nativeEvent how ever i cannot get custom props i have defined (like Id and key) on Anchor Element.

Here is the code that i am using

```js
clickHandler(e){
    e.preventDefault();
    alert(e.currentTarget.id);
  }
  
  render () {
    var that = this;
    return (
      <App>
        <Title>Hello World</Title>
        <p>Hello from a Grommet page!</p>
        <Anchor
            id='1234'
            key="8888"
            primary={false}
            label='My Anchor'
            onClick={that.clickHandler}
        />  
      </App>
    );
  }
```

### Your Environment
* Grommet version: 1.0.0
* Browser Name and version: Chrome (Version 53.0.2785.143) , Firefox (49.0.2)
* Operating System and version (desktop or mobile): Mac OS, Ubuntu

**Comment by davidcalhoun** [comment]
Thanks for filing this issue!  I made this Codepen from your code and it does seem to be a bug: http://codepen.io/franksvalli/pen/YGbVoV?editors=0010

Note that for some reason `data-*` attributes are preserved, so that might be a short term workaround you could use.

I'll look into this a bit later today.

**Comment by alansouzati** [comment]
we are releasing grommet 1.0.1. I will quickly take a look on that.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/f86d86664c17417dbd281bb59bc58103f4e7dc8e
