### ISSUE TITLE
DateTimedrop rendered outside react-content

### ISSUE THREAD

**Issue by maple10001** [grommet/grommet#1022]
When use DateTime component , the DateTimeDrop will rendered outside react-content

### Expected Behavior
DateTimeDrop will rendered as a child of react-content

### Actual Behavior
DateTimeDrop will rendered as sibling of react-content

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/8744187/19874314/75a9097e-9f81-11e6-8bed-ec8c66886da4.png)

### Your Environment

* Grommet version: stable
* Browser Name and version: chrome
* Operating System and version (desktop or mobile): win7

**Comment by alansouzati** [comment]
The issue with that is when you close the DateTime drop it is also closing the layer. I will investigate this.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/464c033be9473ac98e051e392af4a5b9d4b8f282
