### ISSUE TITLE
Support using grommet inside create-react-app

### ISSUE THREAD

**Issue by skurfuerst** [grommet/grommet#1023]
Create-React-App is an extremely popular way to run/bootstrap react applications as of now. It would be great if we could use Grommet inside it.

### Expected Behavior

The build shall not break when adding grommet as dependency

### Actual Behavior

The build breaks weirdly, with webpack issues and not-found babel dependencies.

### Steps to Reproduce

 1. Create a minimal app using create-react-app
 2. add "grommet" as dependency
 3. import grommet
 4. watch it break :)

Would be awesome if this was fixed :-) Grommet looks like a great library, can't wait to use it!

All the best,
Sebastian

**Comment by orditeck** [comment]
@skurfuerst I'm using grommet with create-react-app. 

What is breaking on your side?

In my package.json:
```
"grommet": "^0.6.11",
"react-scripts": "0.4.1"
```

**Comment by skurfuerst** [comment]
ok, I'll try to publish an example, one sec 👍

**Comment by skurfuerst** [comment]
Hey @orditeck,

## Variant  1: Just require grommet 1.0.1 as-is:

Code-Example: https://github.com/skurfuerst/grommet-test/tree/master

The system breaks with:

```
Failed to compile.

Error in ./~/grommet/components/App.js
Module not found: 'babel-runtime/helpers/extends' in /Users/sebastian/src/grommet-test/node_modules/grommet/components
```


## Second try

Code example: https://github.com/skurfuerst/grommet-test/tree/second-variant

Try to directly reference the source tree instead of the compiled version over NPM

System breaks with:

```
Failed to compile.

Error in ./~/grommet/src/js/components/App.js
Module parse failed: /Users/sebastian/src/grommet-test/node_modules/grommet/src/js/components/App.js Unexpected token (48:51)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (48:51)
 @ ./src/App.js 20:11-51
```


## Conclusion

I feel something is wrong / incompatible / ... with the webpack / babel / ... setup. Quite hard to debug though.

Any hints would be appreciated 👍 

Thanks,
Sebastian

**Comment by orditeck** [comment]
@skurfuerst 

`npm install babel-runtime --save` should fix your issue 😃

**Comment by skurfuerst** [comment]
@orditeck OK, that really fixes it 👍  THANKS!

I don't really understand why this is needed; as from my understanding, actually this package should be part of create-react-app... But well. NPM weirdnesses.

Thanks a lot ☀️ 

All the best,
Sebastian

**Comment by alansouzati** [comment]
Thank you guys for the great engagement here 👍

**Comment by mcwebb** [comment]
When installing an identical package.json this issue occurred to my colleague but not for me. Is Grommet simply missing that `babel-runtime` dependency or is there a deeper reason?
He's on Windows with v2 NPM, whilst I'm on Mac with v3 NPM if that helps.

**Comment by alansouzati** [comment]
Interesting. We do only support NPM v3+.

We describe the requirements here: https://grommet.github.io/docs/get-started

Can he try to upgrade and validate if he is facing this issue?

**Comment by mcwebb** [comment]
He's now up and running with NPM v2, just needed the explicit install of `babel-runtime` plus the configuring of sass-loader to dig deep into Grommet's dependencies e.g.
```
sassLoader: {
    includePaths: [
      path.resolve('./node_modules'),
      path.resolve('./node_modules/grommet/node_modules'),
    ],
  },
```
I'm unlikely to be able to convince him to upgrade to v3 to confirm the hypothesis I'm afraid.

But since you explicitly only target v3 I think this issue can be considered closed, I only include the further details above in the hopes that it'll help someone else facing the same issue.

**Comment by alansouzati** [comment]
Thanks for sharing your experience. I'm sure it will benefit folks that are facing issues with NPM v2. 

I recently upgraded our support pipeline following the NodeJS recommendations.

**Comment by shai32** [comment]
there is another problem using grommet with create-react-app

https://github.com/facebookincubator/create-react-app/issues/1639

any idea what to do?

of course with not using eject

**Comment by mvanlonden** [comment]
@shai32 Just created [grommet-css](https://github.com/mvanlonden/grommet-css) to make it a bit easier

**Comment by alansouzati** [comment]
hey @mvanlonden thanks for working on this. This looks like a great solution for folks that would be ok with using the vanilla theme. I think eventually you will want to change colors/fonts, then you may need to use SASS again.

**Comment by shai32** [comment]
@mvanlonden
why its better then just importing 'grommet/grommet.min.css'?

**Comment by mvanlonden** [comment]
@shai32  Oh wow! Didn't released there was a compiled version of the css in grommet (was it always there?). I guess the only advantage is if you'd like to have a separate repo with custom sass styling.
