### ISSUE TITLE
Select renders CheckBoxes/RadioButtons

### ISSUE THREAD

**Issue by kctpradeep** [grommet/grommet#1024]
The "Select" component renders CheckBoxes when the "multiple" property is set, if or not "inline". It renders RadioButtons when "inline" is set. Is this the supposed behaviour of the Select component?

### Expected Behavior
The "Select" field should always render a selection Dropdown. 

### Actual Behavior
https://grommet.github.io/docs/select/examples/#4
https://grommet.github.io/docs/select/examples/#3

### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/docs/select/examples/#4
https://grommet.github.io/docs/select/examples/#3

### Your Environment

* Grommet version: 1.0.1
* Browser Name and version: Chrome 54.0.2840.71 m
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by ericsoderberghp** [comment]
This is intentional behavior. Semantically, the Select is used to select something. `inline` gives them a way to do that without a dropdown.

**Comment by kctpradeep** [comment]
Thanks for the reply. When not "inline", I was expecting "multiple" to behave like this:
http://instructure-react.github.io/react-tokeninput/

Is there any other Input component that allows multiple values (something like above)? 

Grommet is awesome by the way. Many thanks and congrats on hitting 1.0.

**Comment by ericsoderberghp** [comment]
At this time, Grommet does not have a tokenized input like the one referenced.

**Comment by alansouzati** [comment]
We are closing this issue for now as it appears there is no issue.

Token input seems like an interesting component, we will discuss if we want to support it in Grommet core. Feel free to create a separate issue requesting this component.
