### ISSUE TITLE
Button Child Renders Button As Plain

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#1025]
### Expected Behavior

Buttons with `string` children props should render as button labels. We could add a conditional to check for a node or a string if rendering as `plain` is necessary for some circumstances.

### Actual Behavior

Buttons with strings as children are rendered with the `plain` style.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/karatechops/pen/edqXwY?editors=0010

### Your Environment

* Grommet version: 1.0.1
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Mac

**Comment by ericsoderberghp** [comment]
I changed Button recently to distinguish the label= property from string children. So, label= and icon= are used to drive formalized/stylized buttons and children are left to be styled as those elements/components would. So this is intentional behavior. Do you see any issues with that?

**Comment by karatechops** [comment]
Nope, this makes sense. Thanks for clarifying.

**Comment by nickjvm** [comment]
@ericsoderberghp is there a reason this breaking change was introduced in a patch release? or merely an oversight?

**Comment by alansouzati** [comment]
hi @nickjvm if I'm not mistaken this change was introduced before 1.0.0. But I may be missing something here.

**Comment by nickjvm** [comment]
@alansouzati It looks like the change was tagged to v1.0.1

https://github.com/grommet/grommet/commit/7a2042f97deb7522400c8b8cfb903bf2dcccb4cf#diff-0839403ed3b1e347ea49e70ab82abca5R106

**Comment by alansouzati** [comment]
I see sorry about that, we need to pay more attention to semantic versioning. I keep failing on that one, I did the same in toolbox recently. 😢
