### ISSUE TITLE
AnnotatedMeter is not able to display series value that is comma formatted

### ISSUE THREAD

**Issue by benedictdelfierro** [grommet/grommet#1026]
### Expected Behavior

AnnotatedMeter is not able to display series value that is comma formatted. If you have huge value to display, it's hard to read without comma

### Actual Behavior

It just display the actual value without comma

### Steps to Reproduce
 1. Just simple AnnotatedMeter with series props
 2. 
 3. 

### Your Environment

* Grommet version:  1.0.1
* Browser Name and version: chrome 54.0.2840.71 (64-bit)
* Operating System and version (desktop or mobile): imac

**Comment by ericsoderberghp** [comment]
Should use the `intl` library to format the number with correct delimiters for the locale.

**Comment by tracybarmore** [comment]
We are closing this issue. If you have any further concerns, feel free to reopen. Thanks!
