### ISSUE TITLE
StatusIcon Behavior Inconsistent in Chrome

### ISSUE THREAD

**Issue by bastanle** [grommet/grommet#1027]
### Expected Behavior
The following codepen can be used to see the issue. The codepen is using Grommet 1.0.0, if you switch to Grommet 1.0.1 the table will go into column-mode and the StatusIcon will be visible.

In addition, the StatusIcon will be visible if you go to IE or Firefox.

http://codepen.io/anon/pen/bwXKep

### Actual Behavior
Nothing shows up in Chrome. 

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/anon/pen/bwXKep

### Steps to Reproduce
 1. Create a StatusIcon in a table
 2. Open in Chrome
 3. Open in ie or firefox

### Your Environment

* Grommet version: 1.0.0, 
* Browser Name and version: Chrome 54
* Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
Fixed.

**Comment by bastanle** [comment]
Great - I am guessing this will be out for Grommet 1.0.2? Is there an ETA for that? 

Thanks!

**Comment by alansouzati** [comment]
Yeah, it will be in the next release.

Here is the milestone: https://github.com/grommet/grommet/milestones

In the meantime you can use the stable branch:

https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F
