### ISSUE TITLE
Cannot click checkbox label to trigger state change

### ISSUE THREAD

**Issue by nickjvm** [grommet/grommet#1029]
When a checkbox is within a `FormField`, a user cannot toggle a `CheckBox` by clicking directly on its label.

### Expected Behavior

Clicking on the label beside a checkbox icon should toggle a state change

### Actual Behavior

Checkbox state does not change when clicking on the label.
### URL, screen shot, or Codepen exhibiting the issue
Codepen: http://codepen.io/nickjvm/pen/eBYgPx
You can click on the icon itself, or to the white space on the right of the label, but clicking on the text does not toggle the checkbox.

### Your Environment

* Grommet version: 1.0.1
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): OS X

**Comment by ericsoderberghp** [comment]
Just some further information, this doesn't reproduce on Safari but it does on Firefox.

**Comment by ericsoderberghp** [comment]
This is caused by not passing an `id` property to the CheckBox. The label text needs an id property to connect with. Giving the CheckBox an `id` makes clicking on the label text work as expected.

**Comment by nickjvm** [comment]
Thanks @ericsoderberghp, that fixed it.

Looks like `id` needs to be added as a required prop on Checkbox, https://github.com/grommet/grommet/blob/master/src/js/components/CheckBox.js#L69

**Comment by alansouzati** [comment]
Generally speaking I guess it makes sense to make id required for every input field inside a FormField element.

This means that the validate code would live inside FormField, not CheckBox. Thoughts?

**Comment by nickjvm** [comment]
Wouldn't an ID still be required if a `CheckBox` is outside of a `FormField`?

Either way, I think it would be useful to set `id` prop to match `name` if `id` is not defined.

**Comment by ericsoderberghp** [comment]
We never set the `id` property implicitly. The caller is always in control of that. If we set it implicitly and there were two forms on the page with fields having the same name, they would have duplicate ids.

**Comment by nickjvm** [comment]
@ericsoderberghp, regardless of how the id is set, there is still an issue that the id is not set as a required prop (or a prop at all currently), which should be addressed since it is necessary for the checkbox to function properly. 

https://github.com/grommet/grommet/blob/master/src/js/components/CheckBox.js#L69

**Comment by alansouzati** [comment]
I was chatting with Eric and we will update the documentation to include instructions on the side effect of not setting the id. We don't want to make it required as you can have a checkbox without a label and not need the id at all. Does it make sense?

**Comment by nickjvm** [comment]
I hadn't considered the use case of a checkbox without the label. I would still expect `id` to be listed in the component's `propTypes` definition, if it's not required.

**Comment by alansouzati** [comment]
Correct. I will make sure to update the documentation and prop types for id. Thanks for the heads up
