### ISSUE TITLE
Issue with displaying data at the near ends of grahp

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#103]
Data at the near ends is either missing, or the space between them are not the same:
![image](https://cloud.githubusercontent.com/assets/13039669/8863746/3a528b16-3150-11e5-99f0-030cec90051f.png)

**Comment by bryanjacquot** [comment]
Handled by the new chart axis component http://grommet.github.io/docs/chart-axis.  Ferret isn't using this new component but it's available for apps to use.
