### ISSUE TITLE
Buttons will render as plain even if explicit told to not be plain

### ISSUE THREAD

**Issue by ibiBgOR** [grommet/grommet#1030]
### Expected Behavior
If I use the Button element like:
`<Button plain={ false } primary onClick={ func }>Text</Button>`
I expect that the button is told to be not plain.

### Actual Behavior
Actually the button gets rendered with the grommetux-button--plain css class.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/anon/pen/pNorYo?&editors=0010
The plain attribute seems to have no impact when using it with children (as it stands in the code).

### Steps to Reproduce
 1. Button with plain attribute
 2. Button without plain attribute

### Your Environment
* Grommet version: 1.0.1
* Browser Name and version: Chrome 54.0.2840.71 m
* Operating System and version (desktop or mobile): Windows 7

**Comment by karatechops** [comment]
@ibiBgOR this is intended, I just recently filed an issue regarding the same thing. Please refer to issue #1025.

**Comment by ibiBgOR** [comment]
@karatechops I'm not sure if this is intended, because it's completetly irrelevant to tell the button to render as plain or not. The relevant code snippet:
`plain || Children.count(children) > 0 || (icon && ! label)`
If plain is explicitly told to be false it will still get rendered as plain if some element is child of the button. That just seems wrong.

**Comment by karatechops** [comment]
Your example uses a string as a child for Button, with the latest Grommet version you would use the Button label prop. If you need a string button why not use Anchor instead?

It's my understanding this functionality was added to extend Button's flexibility by allowing custom components to be nested in Button without Button styles. It, however, seems if you're explicitly setting plain to false the plain class name should not render. In that same vein, it would also make sense if none of the normal styling Button classes are rendered in a Button with nested children if the intention is to create a wrapper.

**Comment by ericsoderberghp** [comment]
My inclination is to deprecate the `plain` property all together. The Button controls styling if `icon` or `label` are set and doesn't touch the styling if there are child components.

**Comment by ibiBgOR** [comment]
I think you guys are right. Deprecating the `plain` property sounds pretty logical. If the Button component takes all the style work from me I will not moan. :D
Thank you for your help
