### ISSUE TITLE
Mobile menu links don't work

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#1033]
In mobile mode, menu selections can be made.  Specifically, when touch events hit the menu, the menu closes and the selection isn't made.

### Expected Behavior

Link should work.

### Actual Behavior

Menu closes and link selection is ignored.

### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/mcwagner10/pen/EgdaNg

Be sure to be in touch mode.
![image](https://cloud.githubusercontent.com/assets/14231471/20051492/249f0238-a484-11e6-97d1-eb84a22cc908.png)

The issue appears to be on the line with addEventListener('touchstart') in Menu.js.  However, that line solved the issue of menus not closing on mobile when user makes a selection outside of them.

### Steps to Reproduce
 1. Make a menu with a Anchor that links to Google
 2. Press F12, then click the "toggle device toolbar" (go into touch mode)
 3. Try to make a link select.

### Your Environment

* Grommet version: 1.0.1
* Browser Name and version: Chrome Win10 in touch mode
* Operating System and version (desktop or mobile): mobile

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/881954ff221a9d4de427f8c0ce8b30ddfe195184
