### ISSUE TITLE
Notification component doesn't wrap its content in IE

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#1035]
The content of a notification doesn't wrap in IE.  The message appears to be working in Chrome.  Also, notification text has different colors across browsers.

### Expected Behavior

Wrapping should occur.

### Actual Behavior

A horizontal scroll bar is created.

### URL, screen shot, or Codepen exhibiting the issue
View in IE
http://codepen.io/mcwagner10/pen/vXmAEE?editors=1010

The issue appears to be caused by the "flex-basis: auto" rule.

### Your Environment

* Grommet version: 1.0.1
* Browser Name and version: IE
* Operating System and version (desktop or mobile): Win10, smaller window sizes

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/fecbcb2851362acd7d3bc4d7898b07f6e6975c4b
