### ISSUE TITLE
Can Show and Hide Split in Mobile View?

### ISSUE THREAD

**Issue by salztorte** [grommet/grommet#1036]
i used the spilt for seperate the sidebar and the content.
My navtigation is in the sidebar.

But in the mobile view the sidebar is hide and i want to show it up on a button click.

Have someone a idea how to make this?

grommet 1.0.1",

**Comment by mcwebb** [comment]
Use the `priority` property of `<Split />` to prioritize the sidebar side when the button is clicked.
e.g.

```js
<Split priority={this.state.showNav ? 'left' : 'right'}>
  <Sidebar>
    Sidebar content
  </Sidebar>
  <Article>
    <button onClick={() => this.setState({showNav: true})}>Nav</button>
  </Article>
</Split>
```

**Comment by salztorte** [comment]
thanks. 
Your solutioin works, but i the Layer for my Sidemenu.

**Comment by alansouzati** [comment]
Thanks for your help @mcwebb
