### ISSUE TITLE
IE11: Select's dropdown doesn't stay connected to Select when scrolling

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#1043]
In IE11: If there's a long page and a Select component with options, if the user clicks the dropdown, the Drop is not aligned with the Select.

### Expected Behavior

Drop should always be aligned with Select

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/mcwagner10/pen/EgdaNg?editors=1010

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: Stable (and 1.0.1)
* Browser Name and version: IE11 and Firefox
* Operating System and version (desktop or mobile): Desktop

**Comment by mcwagner10** [comment]
I submitted a PR for this here: https://github.com/grommet/grommet/pull/1049

**Comment by mcwagner10** [comment]
Feel free to close this.  I submitted a PR: https://github.com/grommet/grommet/pull/1049

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/pull/1049
