### ISSUE TITLE
Anchor component not navigating properly

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#1044]
### Expected Behavior
Anchor component should seamlessly navigate paths within react router/react app.

### Actual Behavior
Anchor component will navigate in the browser and the app if there is an absolute url like `/my-page`

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/karatechops/pen/GNoqrw?editors=0010

### Your Environment

* Grommet version: 1.0.1
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): macOS Sierra

**Comment by rualatngua** [comment]
Confirmed! We have the same issue.

**Comment by ericsoderberghp** [comment]
Fixed.
