### ISSUE TITLE
[IE] Box with flex not flexing

### ISSUE THREAD

**Issue by ckjackson** [grommet/grommet#1045]
This can be seen in https://grommet.github.io/hpe/docs/box/examples/#3.

In Internet Explorer 11, at a browser width of 800 - 1200 px or so, you will see that the boxes on the row run off the right side of the page, rather than resizing to fit the space.

### Expected Behavior
A better browser will resize the boxes so that they shrink in width to fit the width of the browser.

### Actual Behavior
Instead or resizing, the boxes stay large and a horizontal scrollbar appears at the bottom.

### URL, screen shot, or Codepen exhibiting the issue

![ie-grommet-boxes](https://cloud.githubusercontent.com/assets/4047386/20190630/17d3abc0-a737-11e6-9556-701f6e9bc14e.jpg)

### Steps to Reproduce
 1. Open IE 11 (I am running 11.0.9600.18449)
 2. Navigate to Grommet Box Example #3 (https://grommet.github.io/hpe/docs/box/examples/#3)
 

### Your Environment

* Grommet version:  Version on Grommet Docs site
* Browser Name and version:  IE 11, v 11.0.9600.18449)
* Operating System and version (desktop or mobile): Windows 7 SP1

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/fecbcb2851362acd7d3bc4d7898b07f6e6975c4b
