### ISSUE TITLE
Drop utility not functioning properly in Firefox.

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#1046]
I've found the drop utility does not work in Firefox when below the fold. 

### Expected Behavior

The drop menu should align to the button which triggers it. 

### Actual Behavior

The drop utility is not aligning properly in Firefox. Additionally, when the user scrolls the dropped component will move around the page.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/karatechops/pen/bBEWGY?editors=0010
Scroll down and click the menu button, Firefox will bump the user back to the top, upon scrolling down again the drop utility will be moving vertically on the screen.

### Your Environment

* Grommet version: 1.0.1
* Browser Name and version: Firefox 49.0.2
* Operating System and version (desktop or mobile): macOS Sierra

**Comment by tracybarmore** [comment]
Also see #1071

**Comment by tracybarmore** [comment]
#1071 closed with commit [e9c434a](https://github.com/grommet/grommet/commit/e9c434ae56f9bf133fd93a4867400a78ba2d1449)
