### ISSUE TITLE
Grommet Card throwing errors.

### ISSUE THREAD

**Issue by jhawthor** [grommet/grommet#1047]
### Expected Behavior
Should resemble example in Grommet documentation here: 
https://grommet.github.io/hpe/docs/card/examples/#0 

### Actual Behavior
Not rendering.  Console contains a long error message complaining about missing files:
```
ERROR in ./~/remark-parse/lib/defaults.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./block-elements in /Users/jhawthor/prod/dsfw3.5/node_modules/remark-parse/lib
 @ ./~/remark-parse/lib/defaults.js 19:10-37
ERROR in ./~/character-entities-legacy/index.json
Module parse failed: /Users/jhawthor/prod/dsfw3.5/node_modules/character-entities-legacy/index.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
ERROR in ./~/character-entities/index.json
Module parse failed: /Users/jhawthor/prod/dsfw3.5/node_modules/character-entities/index.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
```
I have lots of grommet components in my app and Card is the only one that give this issue thus far.

![image](https://cloud.githubusercontent.com/assets/12467142/20194534/0b6bc296-a769-11e6-9488-b78acf4be2c3.png)

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/jhawthor/pen/PbZbxa?editors=0010

### Steps to Reproduce
 1.  Add Grommet Card to an Empty Grommet App

### Your Environment
* Grommet version: https://github.com/grommet/grommet/tarball/stable
* Browser Name and version: 
      Safari 10.0.1 (12602.2.14.0.7)
      Chrome 54.0.2840.71 (64-bit)
* Operating System and version (desktop or mobile): 
    MacBook Pro (Retina, 15-inch, Mid 2015)
    macOS Sierra 10.12.1 (16B2555)

**Comment by sorin-davidoi** [comment]
Workaround: https://github.com/grommet/grommet/issues/1018#issuecomment-256805982

**Comment by alansouzati** [comment]
I cannot reproduce this with grommet docs. are you still able to reproduce this?!

**Comment by jhawthor** [comment]
My apologies, I forgot to close this issue. It this was fixed by Eric on the 12th: Erick's Slack Comment: "Card issue on CodePen. One of the pens it depends on didn’t have the Card variable as a global. I’ve fixed it and your pen is working now.
