### ISSUE TITLE
What is the preferred method of styling an individual component? Any reason why className isn't passed down?

### ISSUE THREAD

**Issue by RyanFDev** [grommet/grommet#1048]
I understand that the philosophy is to define custom themes for overriding the default SASS. However, I was wondering what the best way to style a component individually.

In my current app I'd like for the tabs in my left sidebar to be styled differently than those in the right.

Currently I am just injecting a SCSS file in my component and overriding the defaults which does style the component properly. But I noticed this is global and was affecting my styling in other areas using those components.

I've tried embedding them in a named div to localize the styling but that didn't work.

So is there any preferred way to customize components?

It seems as if allowing for className to be passed down the chain or style would help alleviate this issue and would allow for a bit more flexibility. Not to mention allowing for these components to be named for other purposes.

Love your UI and no urgency on this matter. Still mocking up the UI at the moment but was just thrown off by this little hiccup.

Thanks much for any insight!

**Comment by karatechops** [comment]
@RyanFDev can you provide an example where className is not being passed down to the class list in the DOM? We put a lot of effort into making sure classNames propagate to the DOM to allow flexibility. You can use our [Codepen](http://codepen.io/pen?template=gaEGPY&editors=0010) if you'd like to provide something specific.

Personally, with the apps I build in Grommet I rarely need to override Grommet's core styling. If you do need to override styles here's a great example of how we handle our [HPE theme](https://github.com/grommet/grommet/tree/master/src/scss/hpe). Take note of the`index.scss` file where the color variables are loaded first, then grommet core styles, then any component that's being extended. Generally my projects `index.scss` will look like the following:

```
@import 'my-app.defaults';
@import '~grommet/scss/grommet-core/index';

@import 'objects.carousel';
@import 'objects.mobile-menu';
@import 'objects.layer';

@import 'pages.about';
@import 'pages.news';
```

It sounds like you may not explicit enough in you style declarations if the component is not receiving your styles. a Codepen will be helpful to give you some more guidance. 

As an aside - after working on Grommet core I picked up BEM and love it for naming my styles. If you're not already familiar with BEM I highly suggest [taking a look](https://8thlight.com/blog/nelsol-batalla/2014/08/01/bem-basics.html).

**Comment by RyanFDev** [comment]
@karatechops thanks for the advice! After looking at your HPE theme example I was able to get things working properly! className is now being passed down properly as well and likely always was. My SASS just wasn't recognizing it using imports in the component itself.

I've since extracted everything to the SCSS folder and it appears to be working as intended.
