### ISSUE TITLE
IndexQuery wrong if colon is used in search box

### ISSUE THREAD

**Issue by ickedude** [grommet/grommet#105]
1. using a Index component
2. add onQuery callback
3. console.log query argument
4. type a search term with colon in the search box

Result:
```javascript
Query {fullText: "foo:b foo:ba foo:bar", text: "  ", tokens: Array[3], error: false}
```

Expected:
```javascript
Query {fullText: "foo:bar", text: "foo:bar", tokens: Array[1], error: false}
```

Fast fix: To differentiate filter selection and search text colons, you can define that search text colons are translated to two colons:
```javascript
Query {fullText: "foo::bar", text: "foo:bar", tokens: Array[1], error: false}
```

Better fix: Use two query parameter: q for search terms and f for filter selection.

**Comment by ericsoderberghp** [comment]
This issue really belongs in grommet-index. Fixed there.
