### ISSUE TITLE
IE11: Window size (width) changes after clicks it

### ISSUE THREAD

**Issue by fwang113** [grommet/grommet#1050]
On IE11, a form insider layer with header and footer. The form size is only filling the content size, after clicks it, it expands. 

### Expected Behavior
The window size(width) shall not be changed after clicks it. 

### Actual Behavior
Window size (width) changes after clicks it.

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/feiw/pen/MbyRyb

### Steps to Reproduce
 1. Open [this codepen](https://codepen.io/feiw/pen/MbyRyb) on IE11 and chrome
 2. Click the layer window to check the size

### Your Environment
* Grommet version: 1.0.0
* Browser Name and version: IE11
* Operating System and version (desktop or mobile): Windows 7 Enterprise

**Comment by alansouzati** [comment]
This has been fixed in https://github.com/grommet/grommet/commit/cf51c2cb2ef0589fe47cf2cc59f1bfe289a0d697
