### ISSUE TITLE
IE 11, User icon is floating, it should be at the bottom of navigator panel

### ISSUE THREAD

**Issue by wutaosh** [grommet/grommet#1051]
A Menu with UserIcon is inside a Footer which is inside a SideBar. The User icon is at the bottom in Chrome but is floating in IE 11.

### Expected Behavior

![image](https://cloud.githubusercontent.com/assets/20078913/20256439/8e7de642-aa7e-11e6-9955-047f99508dda.png)

### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/20078913/20256330/bff22770-aa7d-11e6-9c1f-a084458c9abb.png)
### URL, screen shot, or Codepen exhibiting the issue

Part of the code is as below:
![image](https://cloud.githubusercontent.com/assets/20078913/20256465/ba4bb1e6-aa7e-11e6-9e03-b0715d4a0bd5.png)

### Steps to Reproduce
 1. Create a Menu with UserIcon is inside a Footer which is inside a SideBar.
 

### Your Environment

* Grommet version:1.0.0
* Browser Name and version: IE 11
* Operating System and version (desktop or mobile):Windows 7 Enterprise

**Comment by ericsoderberghp** [comment]
Can you please create a CodePen illustrating this issue?

**Comment by alansouzati** [comment]
We recently added property fill to Menu that will make sure it will take the available space in the sidebar.

https://grommet.github.io/docs/menu

It will be part of the next grommet 1.1.0 release
