### ISSUE TITLE
Use Layer to build page has different width in Chrom and IE11

### ISSUE THREAD

**Issue by RodHPE** [grommet/grommet#1053]
Use Layer to build page has different width between Chrom and IE11
In  IE 11
some page is too narrow

### Expected Behavior
have a normal width

### Actual Behavior
too narrow

### URL, screen shot, or Codepen exhibiting the issue
chrom is ok:
![image](https://cloud.githubusercontent.com/assets/20080920/20257320/cf5b1158-aa83-11e6-993e-288aaa7b5d59.png)

IE11 is too narrow
![image](https://cloud.githubusercontent.com/assets/20080920/20257331/e4da0da4-aa83-11e6-85e1-e154affa3155.png)

### Your Environment
grommet 1.0

**Comment by RodHPE** [comment]
codePen
  <div>
      {...}
      <Layer align="right" closer={...} onClose={...}>
       <Box direction='row'>
        <Form>
          {...}
          <FormFields>
          <Section>
            <h3>...</h3>
              <FormField>
               ...
              </FormField>
          </Section>
          <Section>
            <h3>...</h3>
              <FormField>
               ....
              </FormField>
              <FormField >
             ...
              </FormField>
           ...
          </Section>
          <Section>
            <h3>DNS</h3>
              {dnsOption}
              <FormField ...>
                ...
              </FormField>
              <FormField ...>
                ...
              </FormField>
          </Section>
          </FormFields>
          ....
        </Form>
       </Box>
      </Layer>
</div>

**Comment by RodHPE** [comment]
###   <div>
      {...}
      <Layer align="right" closer={...} onClose={...}>
       <Box direction='row'>
        <Form>
          {...}
          <FormFields>
          <Section>
            <h3>...</h3>
              <FormField>
               ...
              </FormField>
          </Section>
          <Section>
            <h3>...</h3>
              <FormField>
               ....
              </FormField>
              <FormField >
             ...
              </FormField>
           ...
          </Section>
          <Section>
            <h3>DNS</h3>
              {dnsOption}
              <FormField ...>
                ...
              </FormField>
              <FormField ...>
                ...
              </FormField>
          </Section>
          </FormFields>
          ....
        </Form>
       </Box>
      </Layer>
	</div>

**Comment by RodHPE** [comment]
``    <div>
      {...}
      <Layer align="right" closer={...} onClose={...}>
       <Box direction='row'>
        <Form>
          {...}
          <FormFields>
          <Section>
            <h3>...</h3>
              <FormField>
               ...
              </FormField>
          </Section>
          <Section>
            <h3>...</h3>
              <FormField>
               ....
              </FormField>
              <FormField >
             ...
              </FormField>
           ...
          </Section>
          <Section>
            <h3>DNS</h3>
              {dnsOption}
              <FormField ...>
                ...
              </FormField>
              <FormField ...>
                ...
              </FormField>
          </Section>
          </FormFields>
          ....
        </Form>
       </Box>
      </Layer>
	</div>

**Comment by RodHPE** [comment]
`    <div>
      {...}
      <Layer align="right" closer={...} onClose={...}>
       <Box direction='row'>
        <Form>
          {...}
          <FormFields>
          <Section>
            <h3>...</h3>
              <FormField>
               ...
              </FormField>
          </Section>
          <Section>
            <h3>...</h3>
              <FormField>
               ....
              </FormField>
              <FormField >
             ...
              </FormField>
           ...
          </Section>
          <Section>
            <h3>DNS</h3>
              {dnsOption}
              <FormField ...>
                ...
              </FormField>
              <FormField ...>
                ...
              </FormField>
          </Section>
          </FormFields>
          ....
        </Form>
       </Box>
      </Layer>
	</div>`

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/4df75b59f462cdc79fd5a504f358048e4eea8375
