### ISSUE TITLE
Size of all elements

### ISSUE THREAD

**Issue by Stalso** [grommet/grommet#1055]
Hello. Grommet is cool. But all controls are huge. Is there some way to make everything smaller?

**Comment by Waize** [comment]
You can add at every single Component a size attribute (i.e check the icon-doc: https://grommet.github.io/docs/icon/).
If this is not enough you can override the grommet-default values for "small", "medium" and so on in your very own sass file.

**Comment by alansouzati** [comment]
Thanks @Waize this was going to be my response. I'm closing the issue for now. Feel free to reopen if you still feel that this is a bug.

Would love to hear more details on which controls you think it is huge.

**Comment by Stalso** [comment]
Select is huge.  Also text input with label is very big.  Accordion.  In fact almost all controls of grommet  are  big.  But framework  is still the best.

**Comment by Stalso** [comment]
@Waize you said, that I can  add at every single Component a size attribute. But how can I do it? If I write ` <GrommetButton label="Добавить в список" size="small" />` nothing happens. Do you mean, that I have to redefine grommet components and add `size` attribute?

**Comment by Waize** [comment]
@Stalso for Buttons you can use the "plain" attribute (see https://grommet.github.io/docs/button). 
Using this will take the size from the containing element. 

But feel free to use SASS-files to define css-attributes for all your components.

**Comment by karthickselvendran** [comment]
How to resize the select component in Grommet?

**Comment by oorestisime** [comment]
Have a look at the props https://v2.grommet.io/select#size

**Comment by karthickselvendran** [comment]
> Have a look at the props https://v2.grommet.io/select#size

![project](https://user-images.githubusercontent.com/52481101/66272696-aef60380-e88a-11e9-891b-c78a514886a3.png)

See above image in that I mention the difference between the text Input components of input and the select component

I need all the components look like in same sizes.'

If any doubt in question please ask me.

**Comment by oorestisime** [comment]
Please share a codesandbox with the behaviour. are you using the size prop both in select and textinput? its difficult to help without more information.

**Comment by karthickselvendran** [comment]
> Please share a codesandbox with the behaviour. are you using the size prop both in select and textinput? its difficult to help without more information.

import React, { Component } from 'react';
import { TextInput, Button, Box, RadioButtonGroup, Select, Clock } from 'grommet';
import { Container, Row, Col } from 'react-bootstrap';
import { Link } from 'react-router-dom';


class Bangalore extends Component {
    constructor(props) {
        super(props)
        this.state = {
            radio1: ''
        }
    }
    setValue(e) {
        this.setState({
            radio1: e
        })
    }
    render() {

        return (
            <div>
                <Box flex={false} tag="header" align="center" background="#0091ea" pad="small" >
                    Student Registration Form
          </Box>
                <Container style={{ padding: "5%" }}>

                    <div className="form">
                        <Row>
                            <Col>

                                <Row>
                                    <Col xs={6} sm={12}>
                                        <TextInput
                                            id="registernumber"
                                            placeholder="University Register Number"
                                        />
                                    </Col>
                                </Row>
                                <br />
                                <Row>
                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="firstname"
                                            placeholder="First Name"
                                        /></Col>
                                    <br />
                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="lastname"
                                            placeholder="Last Name"
                                        />
                                    </Col>
                                </Row>
                                <br />
                                <Row>
                                    <Col>

                                        <RadioButtonGroup
                                            name="radio1"
                                            id="radio1"
                                            options={['Male', 'Female']}
                                            value={this.state.radio1}
                                            onChange={(event) => this.setValue(event.target.value)}
                                        />
                                    </Col>
                                </Row>
                                <br />
                                <Row>
                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="email"
                                            placeholder="Email"
                                        />
                                    </Col>

                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="aemail"
                                            placeholder="Alternate Email"
                                        />
                                    </Col>
                                </Row>
                                <br />
                                <Row>
                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="mobilenumber"
                                            placeholder="Mobile Number"
                                        />
                                    </Col>

                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="amobilenumber"
                                            placeholder="Alternate Mobile Number"
                                        />
                                    </Col>
                                </Row>

                                <br />
                                <Row>
                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="nationality"
                                            placeholder="Nationality"
                                        />
                                    </Col>
                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="caste"
                                            placeholder="Caste"
                                        />
                                    </Col>
                                </Row>
                                <br />
                                <Row>
                                    <Col xs={12} sm={12}>
                                        <TextInput
                                            id="college"
                                            placeholder="College"
                                        />
                                    </Col>
                                </Row>
                                <br />

                                <Row>
                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="university"
                                            placeholder="University"
                                        />
                                    </Col>

                                    <Col xs={6} sm={6} style={{ width: '100%' }}>

                                        <Select
                                            placeholder="University State"
                                            options={["Tamil Nadu", "Bengaluru", "Kerala", "Maharastra"]}


                                        />
                                    </Col>
                                </Row>
                                <br />
                                <Row>
                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="tenthpercentage"
                                            placeholder="Tenth Percentage"
                                        />
                                    </Col>

                                    <Col xs={6} sm={6}>
                                        <Select
                                            placeholder="Tenth Passing Year"
                                            options={["2012", "2013", "2014", "2015", "2016"]}
                                        // style={{ width: '1225px' }}
                                        />
                                    </Col>
                                </Row>
                                <br />
                                <Row>
                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="twelfthpercentage"
                                            placeholder="Twelfth Percentage"
                                        />
                                    </Col>

                                    <Col xs={6} sm={6}>
                                        <Select
                                            placeholder="Twelfth Passing Year"
                                            options={["2014", "2015", "2016", "2017", "2018"]}
                                        // style={{ width: '1225px' }}
                                        />
                                    </Col>
                                </Row>
                                <br />
                                <Row>
                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="gcollege"
                                            placeholder="Graduation College"
                                        />
                                    </Col>

                                    <Col xs={6} sm={6}>

                                        <Select
                                            id="gspecialization"

                                            placeholder="Graduation Specialization"
                                            options={["CSE", "ECE", "EEE", "MECH", "CIVIL"]}
                                            style={{ alignSelf: 'stretch',size:'large' }}
                                        />
                                    </Col>
                                </Row>
                                <br />
                                <Row>
                                    <Col xs={6} sm={6}>
                                        <TextInput
                                            id="percentage"
                                            placeholder="Aggregate Percentage in Graduation Degree"
                                        />
                                    </Col>

                                    <Col xs={6} sm={6}>
                                        <Select
                                            placeholder="Graduation Passing Year"
                                            options={["2016", "2017", "2018", "2019", "2020", "2021", "2022"]}
                                        // style={{ width: '1225px' }}
                                        />
                                    </Col>
                                </Row>
                                <br />
                                <Row>
                                    <Col>
                                        <Box align="center" >
                                            <Link to="/New">

                                                <Button
                                                    label="Submit"
                                                    color="orange"
                                                    primary={true}
                                                />
                                            </Link>

                                        </Box>
                                    </Col>
                                </Row>
                                <Row>
                                    <Col>
                                        <Clock type="digital" align="center" justify='front' />
                                    </Col>
                                </Row>
                            </Col>
                        </Row>
                    </div>
                </Container>
                <Box flex={false} tag="footer" align="center" background="#0091ea" pad="small" border={{ side: 'top' }}
                >
                    Management Information System
                </Box>
            </div >
        );
    }
}
export default Bangalore;
