### ISSUE TITLE
Set backgroundImg

### ISSUE THREAD

**Issue by salztorte** [grommet/grommet#1057]
How can i set a background image? I tried it with 
`style="background-image: url(img.jpg);"`

but than the backgroundImg only apears as background in the <Box> where are text and not on the hole background.
 
Is there a methode to do this?

**Comment by alansouzati** [comment]
You can you texture in a box. See this codepen:

http://codepen.io/alansouzati/pen/GNjKRR?editors=0010

I'm closing this issue for now. feel free to reopen if you still think this is an issue.

**Comment by salztorte** [comment]
Thank you for the quick help.
