### ISSUE TITLE
Errors w/ fresh install post-React 0.15.4

### ISSUE THREAD

**Issue by brandonmp** [grommet/grommet#1059]
React 0.15.4 was released today, and there are breaking changes for code that accesses non-public APIs in React:

> However, there is a possibility that you imported private APIs from react/lib/*, or that a package you rely on might use them. 
[Release announcement for 0.15.4](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html)

After installing `grommet` for the first time, running `npm install`, and running `gulp dev`, I'm thrown this:

```
ERROR in ./src/js/index.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /home/bmp/code/wayhome/agent-app/src/js
 @ ./src/js/index.js 1:298-329

ERROR in ./src/js/components/TodoAppDashboard.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /home/bmp/code/wayhome/agent-app/src/js/components
 @ ./src/js/components/TodoAppDashboard.js 1:298-329
webpack: bundle is now VALID.
```

**Comment by alansouzati** [comment]
https://github.com/facebook/react/issues/8312

I'm going to update grommet-toolbox to use react hot loader version 3+

For now please add the following to your package.json:

```
  dependencies: {
    "react": "15.3.2",
    "react-addons-transition-group": "15.3.2",
    "react-dom": "15.3.2"
  }
```

**Comment by alansouzati** [comment]
Fixed with the latest latest version of toolbox.
