### ISSUE TITLE
grommet Icon title(tooltip) not coming in chrome

### ISSUE THREAD

**Issue by vaibhavbhargav** [grommet/grommet#1060]
Grommet Icon not showing title(tooltip) while hovering on them in chrome. It works fine in firefox.

### Expected Behavior

On hovering grommet icons, icons should show tooltip in chrome as well
### Actual Behavior

icon is not showing any tooltip text on hovering in chrome

### Steps to Reproduce
1. Need to hover on grommet icons such as Close icon in chrome.

### Your Environment

* Grommet version: latest
* Browser Name and version: chrome
* Operating System and version (desktop or mobile):
![hoverchrome](https://cloud.githubusercontent.com/assets/11418179/20379342/c9266478-acc1-11e6-9bc8-fe344b266518.png)
![hoveronfirefox](https://cloud.githubusercontent.com/assets/11418179/20379343/c9298e00-acc1-11e6-9e11-fcbed6c16a61.png)

**Comment by alansouzati** [comment]
There are differences on how browsers deal with labels for SVG and we can't control it.

Are you using the icon as an svg only? Or are you wrapping it with an Anchor or Button?

If you have one of these controls the behavior is consistent across browsers for the tooltip.

Anyways, I'm closing this issue as I believe there is nothing we can do on our end to fix it.

Feel free to reopen if you have an idea how to fix it.
