### ISSUE TITLE
[IE 11] Layer appears from browser left side to right side

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#1061]
I am from HPE OVGD project.

This issue only exists in IE 11, Chrome and Firefox has no such issue.

While open a Layer dialog in IE 11, it will slide from browser left side to right side.
While open a Layer dialog in Chrome or Firefox, it will slide from browser right side.

The appearance in IE 11 is different with Chrome and Firefox.

![image](https://cloud.githubusercontent.com/assets/16797825/20383222/e04281dc-ace9-11e6-8404-46d2219b1365.png)

![image](https://cloud.githubusercontent.com/assets/16797825/20383159/a07436fe-ace9-11e6-8252-bfbee4000e7c.png)

import Layer from 'grommet/components/Layer';

      <div>
        {...}
        <Layer align="right" closer={...} onClose={...}>
         <Box direction='row'>
          <Form>
            {header}
            <FormFields>
            <Section>
              <h3>General</h3>
                <FormField ...>
                  <input .../>
                </FormField>
            </Section>
            <Section>
              <h3>...</h3>
                <FormField>
                  <RadioButton .../>
                  <RadioButton .../>
                </FormField>
                <FormField ...>
                  <input .../>
                </FormField>
                {...}
                {...}
            </Section>
            <Section>
              <h3>...</h3>
                {...}
                <FormField ...>
                  <input .../>
                </FormField>
                <FormField ...>
                  <input .../>
                </FormField>
            </Section>
            </FormFields>
            {...}
            {...}
          </Form>
         </Box>
        </Layer>
      </div>

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/ba1dffe8371475adedd57e6d167f6792c6ab0381
