### ISSUE TITLE
SVGIcon size 'medium' is not working

### ISSUE THREAD

**Issue by kadinwu** [grommet/grommet#1063]
### Steps to Reproduce
 1. Set SVGIcon size property to 'medium'
 2. it render as 'small' size style.
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by L0ZZI** [comment]
"Medium" icon size is displaying properly. The "small" icon size does not have any styling behind it. We need to enhance the small size to handle icons less than the "Medium" size's 20px core (24px view box). This will be cleaned up along with other enhancements found on issue, https://github.com/grommet/grommet-design/issues/33

**Comment by tracybarmore** [comment]
linking to #1144

**Comment by MarcoMedrano** [comment]
I would like to have medium icons 36x36 the currrent one looks like small 24x24 I guess xsmall would be 12x12.
Not sure if you have plans for 36x36 icons but I see the need, 24 is small and 48 too big.

**Comment by alansouzati** [comment]
This is still a working in progress. Please stay tuned for updates in this issue.

**Comment by MarcoMedrano** [comment]
Yeah np, I was just wondering myself if we were going to have the 36x36 icons.

**Comment by alansouzati** [comment]
36 medium icons are now available, https://grommet.github.io/docs/icon

**Comment by MarcoMedrano** [comment]
Yeah, I updated to grommet 1.3, and I am playing with the new icon sizes. Appreciated man!!
