### ISSUE TITLE
Request release of new version with TableHeader

### ISSUE THREAD

**Issue by natomato** [grommet/grommet#1064]
From the docs I learned about the [TableHeader](https://grommet.github.io/hpinc/docs/table-header) and was hoping to use it.

### Expected Behavior
When I try to import TableHeader, I can't.
### Actual Behavior
It appears the module hasn't yet been released.

### Your Environment
* Grommet version: 1.0.1

**Comment by alansouzati** [comment]
Thanks for your issue. You can see our upcoming releases here:

https://github.com/grommet/grommet/milestones

In the meantime you can use the stable branch and it will include the TableHeader component.

https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F

I'm sorry we should make it more clear in the site that TableHeader is only available in the stable branch.
