### ISSUE TITLE
Grommet should provide a component to upload a file

### ISSUE THREAD

**Issue by sandeepnamburu** [grommet/grommet#1066]
## **Summary of the Issue:**
Grommet does not provide Component to upload a file. When using <input type="file"... > ,  different browsers like Chrome, Firefox and IE11 are displaying different text on Button., So in our application not able to localize the text.

### Expected Behavior
Need to display same text on the button across all browsers if Grommet  provides any File Upload component so that the text can be localized.
wanted to know if Grommet has any plans to provide a File upload component.

### Actual Behavior
URL 
https://grommet.github.io/docs/form/examples/#3
In the above url , to upload a file..below code is used
"\<FormField label="Item 12" htmlFor="ffitem12">
        "\<input type="file" id="ffitem12" name="item-12"  />
 "\</FormField>
In Chrome , Choose File text is displayed on the button and No file chosen is displayed as label.
If same url is accessed in Firefox., Browse is displayed on the button and No file selected as label.
So in this case  since common text is not getting displayed, finding an issue in localization.

### Your Environment
* Grommet version: 0.6.9 and the latest
* Browser Name and version:  Chrome, Fire Fox and ie11
* Operating System and version (desktop or mobile): Windows, Linux

**Comment by ericsoderberghp** [comment]
It is too complicated to style the file input browse button and file path indicator. Localization of the button label should be handled by the browser/OS.

**Comment by jaitaiwan** [comment]
@sandeepnamburu its possible to be done but something probably best handled by a custom component like so: https://codepen.io/wallaceerick/pen/fEdrz

**Comment by ericsoderberghp** [comment]
That's a fair amount of customization. Thanks for the reference though.

**Comment by L0ZZI** [comment]
Alternate community solution, #1191
