### ISSUE TITLE
Tip's drop doesn't center on icons

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#1067]
If a Tip component targets a Grommet icon, then the resulting drop is centered.  See codepen.

### Expected Behavior

Tip's drop should be centered.

### Actual Behavior

Tip's drop is right aligned.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/mcwagner10/pen/EgdaNg

### Steps to Reproduce
See codepen

### Your Environment

* Grommet version: Stable
* Browser Name and version: Win10 Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by alansouzati** [comment]
Thanks for this issue.

Currently Tip does not center the placement. The padding in the menu gives a false impression that it centers it.

I believe we should extend the Tip component with align option. I will add that in our backlog. This is most likely be in 1.2.0 unless someone in the community is up for a pull request on that.

**Comment by tracybarmore** [comment]
Thanks for the collaboration! Opened new issue in backlog #1097.
