### ISSUE TITLE
Search filters and search input do not coordinate

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#107]
Set filters to "Error" and "Warning", 10 items are displayed as expected, and the search input does not show any filters.  Should it also display the search terms?
![image](https://cloud.githubusercontent.com/assets/13039669/8912908/8f35f7ce-344a-11e5-86e3-83a7b1926394.png)

Type 'ok' into the search input.  The filter is still '2', but the result displayed 4 errors
![image](https://cloud.githubusercontent.com/assets/13039669/8912959/dc6538b6-344a-11e5-97e9-3aeae0438da9.png)

**Comment by bryanjacquot** [comment]
This is a different behavior from piano, but is by design.  The filters are being kept independent of the search field.
