### ISSUE TITLE
Disabled Anchor still invoke onClick

### ISSUE THREAD

**Issue by ido-ran** [grommet/grommet#1072]
I've notice that when using Anchor component that has disabled={true} the link still activate the onClick prop.

### Expected Behavior
When the disabled prop is true the click should not be activated.

### Actual Behavior
The onClick is actiavted even when disabled is true.

See the code of [Anchor](https://github.com/grommet/grommet/blob/80d3a8c647698436cf31304dd3c1ea4021757224/src/js/components/Anchor.js#L32)

**Comment by alansouzati** [comment]
Thanks for identifying this. Since you've spotted where the issue is, would you mind sending a pull request to fix it ? :)

**Comment by ido-ran** [comment]
I've create a PR. I was not sure how to write unit test to test events with React.

**Comment by tracybarmore** [comment]
PR #1087 merged. Thanks!

**Comment by Thuranel** [comment]
Seems like this is still an issue

https://codepen.io/Thuranel/pen/vJOqxa

Also, clicking on a disabled anchor with a href still redirect to the url. Path seems to be correctly disabled though.

**Comment by alansouzati** [comment]
re-fixed by https://github.com/grommet/grommet/commit/c5e5c75b008604de38414ff9671f233cc747b7ec

thanks for catching this @Thuranel
