### ISSUE TITLE
Message Icon Catalog Updates

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet#1075]
grommet/src/js/messages/icons/en-US.js needs to be aligned with 1.0 icons.

**Comment by RyanCCollins** [comment]
I will take care of this one this coming week.

**Comment by RyanCCollins** [comment]
I've added a gulp script to automate this and will push it later today.

**Comment by RyanCCollins** [comment]
See #1150

**Comment by alansouzati** [comment]
Fixed by @RyanCCollins
