### ISSUE TITLE
Disable form while processing or loading

### ISSUE THREAD

**Issue by aldofunes** [grommet/grommet#1082]
### Expected Behavior
Disable form, or button when processing a form input. For example a user submits a login form and waits for 1 second for it to complete. In the meantime, the form should be disabled to prevent re-submits.

It should work by passing a prop disabled={this.state.status === 'LOADING'} to the Form component.

### Actual Behavior
The form, fields nor the button can be disabled by passing a disabled={true} prop

It is possible to emulate disabled behaviour for the button by undefining the onClick prop, like so: 
```javascript
 onClick={status !== 'LOADING' ? this.onSubmit : undefined}
```
However, it would be better to have a simple disabled prop for the Form or the Button itself

### Code
Here is the relevant `render()`function of my component:
```javascript
  render() {
    const { email, firstName, lastName, status } = this.state;
    return (
      <Form disabled={status: status === 'LOADING'}>
        <FormFields>
          <FormField label="Email">
            <TextInput
              name="email"
              type="text"
              value={email}
              onDOMChange={this.onChangeEmail}
            />
          </FormField>
          <FormField label="First Name">
            <TextInput
              name="firstName"
              type="text"
              value={firstName}
              onDOMChange={this.onChangeFirstName}
            />
          </FormField>
          <FormField label="Last Name">
            <TextInput
              name="lastName"
              type="text"
              value={lastName}
              onDOMChange={this.onChangeLastName}
            />
          </FormField>
        </FormFields>

        <Footer pad={{ 'vertical': 'medium' }} direction="column" align="end">
          <Button
            label="Save"
            type="submit"
            primary
            fill
            onClick={this.onSubmit}
          />
        </Footer>
      </Form>
    );
  }
```

### Your Environment

* Grommet version: 1.0.1
* Browser Name and version: Chrome 54.0.2840.98
* Operating System and version (desktop or mobile): OS X 10.12 (macOS Sierra)

**Comment by chandrakantnitt** [comment]
+1

**Comment by ericsoderberghp** [comment]
Thanks for the detailed description. Our general strategy with form interaction is to have quick response time and leave the user in control of his experience. For some products using Grommet, if the form cannot be validated within a couple hundred milliseconds, the form submittal is tracked via a separate 'task' mechanism. When the task completes, the user can see any details of the results and proceed as they want. So, we prefer not to disable controls.

I would recommend both providing some feedback to the user that the form is being processed and handling preventing double submit in your onClick or onSubmit handlers. One possibility for displaying the processing of the form would be to remove the Form component entirely and replace it with a message indicating that the form is being processed.

**Comment by tracybarmore** [comment]
Hi aldofunes. Thanks for your collaboration with us. I'm closing this issue since guidance was given. Please let us know if this is still an issue for you. Thanks!
