### ISSUE TITLE
Show icon by name

### ISSUE THREAD

**Issue by ido-ran** [grommet/grommet#1084]
We have a use-case in which we use the icons in navigation menu. The navigation menu data is loaded from the server and one of the fields is the icon to present in the menu.  
The Icon components do not allow to use something like `<Icon type="users" />` to get the users icon by getting the actual name from a variable - more specifically `<Icon type={menuItem.iconType} />`.

We've worked around this issue by have a script that run during build that walk on the Icons directory and create such "Icon" component that has a huge switch on the name of the icon.

**Comment by alansouzati** [comment]
The issue with this approach is that you will end up having the entire 400 icons in your final bundle, which will drive the size of your script a lot.

I understand the requirement of dynamic menu item and icons. I'm sure you are already making the connection with the icon name somewhere, so I would assume this list of menu items is short. This means that you are probably not going to use 400 icons. 

My recommendation is to create a switch/if in your client-side component, something like this:

```
switch (menuItem.iconType) {
  'users': 
      icon = <Users />
      break;
}
```

**Comment by ido-ran** [comment]
Thanks for the details.
Since we allow to choose any icon from the Grommet icons it means we'll be have to include all the icons in our build. I've created an automated script that create exactly the kind of switch case code you suggested here.
Having such component inside Grommet means users will inclulde all the icons only if they use it.

What do you think?

**Comment by tracybarmore** [comment]
@ido-ran, thanks for your collaboration with us. We are going to be investigating in to this more in the near future, but wanted to let you know that this will most likely be a post v2.0.0 release item. We will keep you posted. Thanks!

**Comment by L0ZZI** [comment]
This is possible in v2 now!
