### ISSUE TITLE
Topology not displaying wires on v1.0.1

### ISSUE THREAD

**Issue by harshithjv** [grommet/grommet#1085]
### Expected Behavior
Topology should display with connections provided on _links_ attribute passed to _Topology_ component.

### Actual Behavior
Links or wires are missing

### Empty topology on browser
![image](https://cloud.githubusercontent.com/assets/809278/21049406/aba9150a-be3a-11e6-92f9-cabb9ce7b798.png)

### Error thrown on browser developer console
![image](https://cloud.githubusercontent.com/assets/809278/21049382/90dc5bce-be3a-11e6-8278-9271c5569887.png)

### Code throwing on Topology.js
Check line 423 :
![image](https://cloud.githubusercontent.com/assets/809278/21049554/8588060a-be3b-11e6-91d1-4b709ae7f214.png)

### Environment

* Grommet version: 1.0.1
* Browser Name and version: Chrome v54.xx
* Operating System and version (desktop or mobile): Windows 10

Currently I am using below workaround which works nicely:
`window.top.width = 1;`

**Comment by harshithjv** [comment]
The code throwing error on Topology.js :

![image](https://cloud.githubusercontent.com/assets/809278/21049554/8588060a-be3b-11e6-91d1-4b709ae7f214.png)

**Comment by ericsoderberghp** [comment]
Can you provide a CodePen demonstrating this issue? Also, we did fix some issues with Topology in grommet 1.1.0. Can you verify whether you are still seeing the issue if you use grommet 1.1.0?

**Comment by harshithjv** [comment]
@ericsoderberghp Thanks for suggestion. The problem is fixed after migrating to new verion. 

Closing the issue.
