### ISSUE TITLE
Menu is "leaking" a click to the component underneath it.

### ISSUE THREAD

**Issue by okada** [grommet/grommet#1086]
When a user clicks in a Menu item, the dropdown box closes and the click is "leaked" to the component underneath it. If the click was on a text field for example, it may get the focus. If it as a checkbox, it may get checked.
### Expected Behavior

The dropdown should close and the click should be consumed by the Menu component and not be seen by the component underneath.
### Actual Behavior

The component underneath the dropdown gets clicked.
### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by jaitaiwan** [comment]
@okada when you say "The component underneath" are you meaning the Menu's children or one of the components the menu wraps?

**Comment by okada** [comment]
The menu's dropdown is absolute positioned with a z-index:20. When I say component underneath I mean the component rendered at the same position but lower z-index.

**Comment by okada** [comment]
This have been solved on 1.10
