### ISSUE TITLE
The docs for Spinning have the wrong component path

### ISSUE THREAD

**Issue by ido-ran** [grommet/grommet#1088]
In the docs the [Spinning](https://grommet.github.io/docs/spinning) component is listed to have path of `import Spinning from 'grommet/components/Spinning';` when in fact it should be `import Spinning from 'grommet/components/icons/Spinning';`

The copmonent is actually under the icon folder.

**Comment by tracybarmore** [comment]
Thanks for your pull request! grommet/grommet-docs#217 merged. For any future grommet-doc issues, please enter these in to our grommet-docs repo. Thanks!
