### ISSUE TITLE
There is no clear way to disable a button

### ISSUE THREAD

**Issue by ido-ran** [grommet/grommet#1089]
I have a form with button and when submitting the form I'll like to disable all the components because there might be an error return from the server in which can I'll re-enable the components to allow the user to correct the input and submit it again.

Currently I don't see any way to disable to button except of removing the onClick which does not seem like the right way.

### Expected Behavior
I think it will be better to have the `disabled` attribute be settable so we could disable the button.

**Comment by ericsoderberghp** [comment]
Our preferred pattern of form interaction is to keep the submit button enabled all the time. If the user attempts to submit the form in an invalid state, the FormFields are decorated with appropriate error messages.

There are many other components in Grommet where behavior and styling is controlled via presence of a handler, such as 'onSearch' on Select.

**Comment by ido-ran** [comment]
The usecase I have is a form that when submit takes up-to several seconds to complete and might result in an error. So we want to disable the form while the request is pending results and if an error occur we re-enable the form to allow the user to fix the form input and if the result complete successfully we continue to a new page.
Leaving the button enabled during the request seem like poor UX as the user migh click the button again and the button continue to seem "clickable".

How do you suggest go about this usecase?

**Comment by tracybarmore** [comment]
Hi @ido-ran,
Grommet has a showcase app that uses a pattern for a processing/validating state of a form. 
- Go to http://ferret.grommet.io/settings/edit
- Click 'Connect' next to Directory
- Type in anything in Directory Server input field, Click Connect
- Button is replaced by spinner and verb of action

![bitmap](https://cloud.githubusercontent.com/assets/13038855/21792861/942af810-d6a1-11e6-85cf-f0302c3a2c0c.png)

Let us know if this answers your question and if we can close this issue. Thanks!

**Comment by ido-ran** [comment]
Hi,
Thanks for the update. Yes, this does seem like a good solution for our scenario.

**Comment by vladblindu** [comment]
I bow before the HOR (higher order reason) that prevents the Button component to have a simple **disabled** property,, but for everyone that isn't that enlightend in UX philosopy, the following wrapper might come in handy:

```
import React from 'react'
import Button from 'grommet/components/Button'
import _ from 'underscore'

export default (props) => {
    const newProps = props.disabled ? Object.assign({}, _.omit(props, 'onClick')) : props
    return (
        <Button {...newProps} />
    )
}
```
