### ISSUE TITLE
There is no max-length of the search input in the 'Select' component and other components.Because the caller could not validate and change it..

### ISSUE THREAD

**Issue by lichao-HP** [grommet/grommet#1092]
User can input too many letters to the search input of 'Select' component. When they 'ctrl+c' and 'ctrl+v' to this search input endlessly, the browser will be slower and slower, and even crash at last. Same cases existed where there is a search input in the components like 'Index' and 'Table' and so on.

### Expected Behavior

I think there should be a limitation of max-length of the search input in the 'Select' component and other components.

### Steps to Reproduce
 1. Use the select components in the UI
 2. 'ctrl+c' large texts , and 'ctrl+v' to the search input 
 3. repeat step 2 again and again

### Your Environment

* Grommet version:  grommet 1.0.0
* Browser Name and version: Chrome Version 55.0.2883.75 m (64-bit)
* Operating System and version (desktop or mobile): Windows 8, desktop

**Comment by ericsoderberghp** [comment]
Since different context will have different maximum length requirements, and because it is the caller's job to manage displaying any validation messages. We recommend detecting when the input text is 'too long' and adding an error message in the FormField when appropriate.

**Comment by lichao-HP** [comment]
I agree with you that the caller do the validation. However, let's take the 'Select' component for example, 
            <Select
              value={this.state.inputValue}
              onSearch={this._onDOMChange}
              onChange={this._onSelect}
              placeHolder='Search'
              options={this.state.suggestions} />
This is not the problem to validate the 'value' of the 'Select'. Because we do not input the 'value', we only search and then select one in the drop-down list. But when we search, we input something has no limitation and could not be validated as far as I know.

**Comment by lichao-HP** [comment]
@ericsoderberghp  Would you be so kind to varify if this is a issue again?
[select validate.docx](https://github.com/grommet/grommet/files/662668/select.validate.docx)

**Comment by ericsoderberghp** [comment]
So, is the issue that a user is able to bring their own browser to its knees by typing a very long text sequence into the search input in the Select drop down? Is this a malicious user, or is it a user who needs some extra protection to prevent him from doing it?

**Comment by tracybarmore** [comment]
Hey @lichao-HP, sorry to be 'that guy', but we will be cleaning up our backlog next week by closing unresponsive issues that haven't been active for at least 30 days. If you would like this issue to remain open in our backlog, please comment to let us know. Thanks!

**Comment by tracybarmore** [comment]
March 14, 2017 - Backlog grooming resulted in the closure of this issue. Please feel free to reopen to continue the conversation. Thanks!
