### ISSUE TITLE
Show grommet version information on the website

### ISSUE THREAD

**Issue by avgovind** [grommet/grommet#1094]
Grommet is regularly updated and the documentation in grommet.io is also updated. We are developing an application using Grommet. Before upgrading grommet module I would like to look for what is the current version of grommet and what changes had gone into it. 
It would be nice to show the current grommet version in grommet.io site along with 'whats new'.

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by tracybarmore** [comment]
Thanks for the suggested enhancement. Grommet.io is actually using the [grommet/grommet stable](https://github.com/grommet/grommet/tree/stable) branch (branch committed to multiple times a day). If you are working off a specific grommet release, our release notes indicated the framework's changes and enhancements: https://github.com/grommet/grommet/releases

If you have further questions about our release process, we're happy to fill you in. Contact us quick on [Slack](https://grommet.slack.com/)! Thanks!
