### ISSUE TITLE
Add Align option on TIP

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet#1097]
Currently Tip does not center the placement. The padding in the menu gives a false impression that it centers it.

Tip component needs to be extended with align option.

**Comment by tracybarmore** [comment]
No option, implement change in behavior.

**Comment by dgennetten** [comment]
Current appears is as follows:
1) Tip body is right-aligned with parent body
2) Tip pointer (24px triangle) is right-aligned with parent body - 12px.
3) Tip body width is max( parent.width,  tipText.width+padding) 

The net result is: Top aligns just fine, so long as parent width >= 48px.  When this width falls below 48px, the tip needs to shift right by  (48 - parent.width)/2 .

**Comment by dgennetten** [comment]
Codepen showing problem: http://codepen.io/dgennetten/pen/KagbYo?editors=1010
I will do a PR in Drop.js to fix.

**Comment by dgennetten** [comment]
@alansouzati this is fixed with PR1290, April 5.

**Comment by alansouzati** [comment]
I believe the fix will be to add an align option to the Tip something like:

`<Tip target='elementId' align='center' />`

`<Tip target='elementId' align='start' />` 

`<Tip target='elementId' align='end' />`

**Comment by alansouzati** [comment]
Let's target this for Grommet 2.0

**Comment by karatechops** [comment]
tagging #1495 / #1518

**Comment by L0ZZI** [comment]
Box should be able to handle this in v2. We might need a Tip Example to make sure it covers the use case.
