### ISSUE TITLE
Hand should be rendered instead of a pointer when onClick is available on Meter chart

### ISSUE THREAD

**Issue by ishwark7** [grommet/grommet#1098]
The mouse cursor/pointer doesn't change to hand when onClick is present on Meter chart, while it does change for the other charts.

### Expected Behavior
The cursor should change to hand when onClick is available

### Your Environment
* Grommet version: latest as of 17th Dec 2016
* Browser Name and version: Chrome 54.x
* Operating System and version (desktop or mobile): Windows 7

**Comment by alansouzati** [comment]
Thanks for reporting this issue.

I was able to reproduce this issue in this codepen:

http://codepen.io/alansouzati/pen/dOaQBN?editors=0010

This is fixed in: https://github.com/grommet/grommet/commit/350900f960bdb218818ad467a4ff8eb22b2f898f

**Comment by ishwark7** [comment]
Thank you :)
