### ISSUE TITLE
Font-color setting to 'transparent' in Google Chrome browser

### ISSUE THREAD

**Issue by harshithjv** [grommet/grommet#1101]
### Expected Behavior
Font color should have default instead of 'transparent.

### Actual Behavior
On Google Chrome browser, the most texts have disappeared. On inspecting, found that there are texts but the css 'color' property has been set to transparent through scss scripts. This problem is not found on firefox browser.

**_Note:_** This issue only occurs while testing webapp through 'gulp dev' command. The transpiled file, i.e., through 'gulp dist' command, served on Apache server is rendering properly.

### Screen shot

In below screenshot, you can see the Circle meter looking  blank, when in fact it has some text. Also in sidbar alinged to left has some menu items which are not visible.

At bottom right on the developer console, the css color has been set to 'transparent' is visible.

![image](https://cloud.githubusercontent.com/assets/809278/21336781/bd59d87e-c68d-11e6-8674-5187dd2bed1f.png)

### Your Environment
* Grommet version: 1.1.0
* Browser Name and version: Google Chrome v55.0.x
* Operating System and version: Windows 10 Enterprise

**Comment by ericsoderberghp** [comment]
We are unable to reproduce this: https://grommet.github.io/docs/meter/examples?type=circle&i-value=true&c-background=dark%20on%20light

**Comment by harshithjv** [comment]
Hey @ericsoderberghp 

Please forgive me for long delay in reply, as I had been long vacation and then busy with some project work after reporting to duty. The problem still persists.

I have imported SCSS in root JS (src/js/index.js) like this:
`import '../scss/index.scss';`

**Comment by harshithjv** [comment]
The import statement was not changed even after migrating from old grommet and grommet-toolbox to new version.

**Comment by harshithjv** [comment]
Hey @ericsoderberghp and @alansouzati 

Can you please check this issue again?

**Comment by ericsoderberghp** [comment]
We have not been able to reproduce this. Can you please provide a CodePen illustrating the issue? If you cannot reproduce it with a CodePen, you could send an archive with a small project that reproduces the we could run locally.

**Comment by harshithjv** [comment]
Hi @ericsoderberghp ,

I am attaching file here:
[grommet-chrome-transparency-problem.zip](https://github.com/grommet/grommet/files/729534/grommet-chrome-transparency-problem.zip)

I have created toned down and dummy version of our project. I have tested thoroughly and it's font is not visible. Please have a look.

**Comment by mdbishop** [comment]
I've also got a possibly related issue myself ( @ericsoderberghp pls advise if you'd prefer this as a new issue. ).  In Chrome, several elements appear to never have their

```css
.grommetux-background-color-index--pending
```

style replaced.  On occasion, a reload or changing code (running in dev mode also) will get all previously invisible items to appear.  For me, the issue is not deterministic and I've not been able to reproduce in a dead simple project.

While the screen overall is low-medium in nesting/complexity, a typical area in question would be:

```
<box>
   <section>
       <Card>
         heading={some text}
         description={<Paragraph />} />
   </section>
</box>
```

So, nothing terribly involved.  In any event, not sure if these two are related issues but wanted to start here before opening a new issue.

Thanks much!

**Comment by phazor** [comment]
I've noticed this issue as well. It is consistent in our app but like the others I'm unable to make a codepen that reproduces it.

I'm curious - what purpose does the `background-color-index--pending` class serve?
