### ISSUE TITLE
header + split

### ISSUE THREAD

**Issue by raphi011** [grommet/grommet#1102]
Is there any way to make `<Split />` take only the available height? 

I want to use a `<Header />`  above `<Split />`  but then a scrollbar appears because split is taking the hole browser height and with the Header component thats more than 100% of the height.

**Comment by alansouzati** [comment]
Split is designed to take the full viewport. I would recommend using native boxes if you want a different behavior.

Check out this codepen, I believe this is close to what you are looking for:

http://codepen.io/alansouzati/pen/MbxoyG?editors=0010

I'm going to close the issue as I believe there is nothing to be fixed. Feel free to reopen if you still think there is something to fix.

**Comment by jcuenod** [comment]
You lose the responsiveness of `<Sidebar />` in this approach.
