### ISSUE TITLE
There are errors in browser console when using 'Select' component

### ISSUE THREAD

**Issue by lichao-HP** [grommet/grommet#1105]
There are error messages like "Uncaught TypeError: Cannot read property 'select' of undefined" in the browser console when we using the 'Select' component.
### Expected Behavior

There should be no error messages
### Actual Behavior

The code below is in componentDidUpdate in Select.js
        if (this._searchRef) {
          this._searchRef.focus();
          this._searchRef.inputRef.select();
        }
The errors message came from the last line when the select first used, nothing is selected.
However, this error does not impact any function of the 'Select' component.
### Steps to Reproduce
 1. Create a select which have onSearch() property
 2. click the component, when onSearch first triggered
 3. open the console of the browser will see the error

### Your Environment

* Grommet version: 1.0.0
* Browser Name and version: Chrome Version 55.0.2883.75 m (64-bit)
* Operating System and version (desktop or mobile): Windows8 desktop

**Comment by alansouzati** [comment]
This is fixed in the latest version of grommet. Please upgrade to 1.1.0.

See this codepen which uses the latest Grommet

http://codepen.io/alansouzati/pen/qqwEBd?editors=0010
