### ISSUE TITLE
Small design for checkbox

### ISSUE THREAD

**Issue by ido-ran** [grommet/grommet#1106]
In an application we build that uses Grommet we need  small design for the checkbox component as showen bellow.

### Expected Behavior
![image001](https://cloud.githubusercontent.com/assets/187938/21381691/82b45464-c765-11e6-84d6-d0787c51d759.jpg) --> 
![image002](https://cloud.githubusercontent.com/assets/187938/21381754/d66918b0-c765-11e6-9a48-a065b48b5509.jpg)

**Comment by ericsoderberghp** [comment]
We tend to have minimum sizes for controls to provide enough hit target on touch devices. Can you provide more context for the entire screen illustrating why the smaller size is needed?

**Comment by tracybarmore** [comment]
Hey @ido-ran, thanks for all your collaboration with us. We will be cleaning up our backlog last week of Feb 2017 by closing unresponsive issues that haven't been active for at least 30 days.

If you would like this issue to remain open in our backlog, please comment to let us know. Thanks!

**Comment by tracybarmore** [comment]
Closing issue as indicated in previous comment to clean up backlog. Feel free to reopen to bring it back to our attention. Thanks!
