### ISSUE TITLE
Select component when has multiple=true not displaying value

### ISSUE THREAD

**Issue by moizhb** [grommet/grommet#1109]
### Expected Behavior
In the example of Select component when multiple option is selected and when you try to select a value, it should update the UI as a feedback to the user that a value has been selected.

### Actual Behavior
In the examples of Select when multiple option is selected and when you select a value it does not show the selected value(UI is not updated).

### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/docs/select/examples?placeHolder=true&multiple=true
![image](https://cloud.githubusercontent.com/assets/5599736/21467779/c65e493c-c9ad-11e6-9545-83acf33b998a.png)

### Notes
Notice in the screenshot, the console shows the value as an array but nothing is being shown in the UI.

### Steps to Reproduce
 1. Goto the example page
 2. Select multiple option
 3. Select one of the option from the list
 4. Nothing will be shown in the Select component although the value field of the component is updated correctly with the correct value.

### Your Environment

* Grommet version: Not sure
* Browser Name and version: Google Chrome  55.0.2883.95 (64-bit) and Safari 10.0.2 (12602.3.12.0.1)
* Operating System and version (desktop or mobile): MacOS 10.12.2 (16C67)

**Comment by ericsoderberghp** [comment]
Fixed. https://grommet.github.io/docs/select/examples?placeHolder=true&multiple=true
