### ISSUE TITLE
colorIndex

### ISSUE THREAD

**Issue by josephalhamad** [grommet/grommet#111]
The colorIndex attribute in Section and Box attribute doesn't work with all the colors that are on http://grommet.io/docs/hpe/design/basics#color. Only neutral colors worked with indexes 1 to 3 and graph colors but the order was not the same as the one on the Docs. Also, I think there should be 5 colors in neutral colors, the HPE-styling shows that there is HPE gray and white. 

![neutralcolors](https://cloud.githubusercontent.com/assets/8975095/8942896/ed97cb48-3545-11e5-9456-5210721d5f3c.JPG)

The colors in status, accent and primary don't work with any index. The first image is produced using colorIndex="status-1". 
![nocolor](https://cloud.githubusercontent.com/assets/8975095/8942648/8697afd6-3544-11e5-920b-271be7fc02ec.JPG)

And the second one is with using  colorIndex="neutral-1"
![withcolor](https://cloud.githubusercontent.com/assets/8975095/8942649/86aa0672-3544-11e5-9ec6-55ac3bccb494.JPG)

**Comment by maple10001** [comment]
Same issue appears when I trying to use colorIndex in <Header> component. 

More if setting fixed={true} in Header, some working colorIndexs like "grey-3" is not working in large viewport, eg: when the width is larger than 700px.

**Comment by ericsoderberghp** [comment]
@maple10001: Can you clarify what your width issue is, perhaps with a screenshot? The bulk of this issue has been fixed for many months. I've just added the brand color to round it out. You can now see all of the colorIndex values be example here: http://www.grommet.io/docs/hpe/develop/box

**Comment by maple10001** [comment]
I am trying to use `<Header colorIndex='brand' fixed={true}>hello</Header>`. The colorIndex works fine. screenshot:
![image](https://cloud.githubusercontent.com/assets/8744187/12662974/c7c00ab0-c5d8-11e5-93ae-a2010659d32c.png)
After I added `[fixed={true}` to the code `<Header colorIndex='brand' fixed={true}>hello</Header>,` the color is gone. screenshot:
![image](https://cloud.githubusercontent.com/assets/8744187/12662988/e20fafd8-c5d8-11e5-8c09-0a0118248e2f.png)
But when you shirk the window width under 700px, the color is back, attached with screenshot:
![image](https://cloud.githubusercontent.com/assets/8744187/12663018/4898cbfe-c5d9-11e5-8286-d5dab0a93224.png)
