### ISSUE TITLE
Menu example code broken in docs

### ISSUE THREAD

**Issue by aldofunes** [grommet/grommet#1110]
The example page for [Menu](https://grommet.github.io/docs/menu/examples) is broken. When I click the `</>` button, nothing happens and the console logs `Uncaught TypeError: Cannot read property 'displayName' of undefined`.

**Comment by ericsoderberghp** [comment]
This is due to a defect in jsx-to-string. Awaiting approval of the pull request for the fix: https://github.com/grommet/jsx-to-string/pull/17

**Comment by alansouzati** [comment]
Thanks @ericsoderberghp released 0.3.1 of jsx-to-string with the fix for this!
