### ISSUE TITLE
HPE theme's primary Anchors color stays green when mouse hover on it for visited link

### ISSUE THREAD

**Issue by fwang113** [grommet/grommet#1111]
### Expected Behavior

HPE theme's primary Anchors label text color shall change to black when mouse hover on it no matter it has been visited or not, just like in other themes. 
### Actual Behavior

For the visited links, HPE theme's primary Anchors label text color stays green when mouse hover on it.

### Steps to Reproduce
 1. On the [Anchor doc page ](https://grommet.github.io/hpe/docs/anchor/), click the primary Anchor (the green "Label").
 2. Move mouse hover on and off the green "label". 

### Your Environment

* Grommet version: Grommet version: 1.0.0
* Browser Name and version: IE11, Firefox 50.1.0
* Operating System and version (desktop or mobile): Windows 7 Enterprise

**Comment by dgennetten** [comment]
BTW, works as expected on Chrome and Edge.

**Comment by tracybarmore** [comment]
Replicated issue. Inconsistent in behavior in anchor examples:

https://grommet.github.io/hpe/docs/anchor/
vs
https://grommet.github.io/hpe/docs/anchor/examples?label=true&animateIcon=true&href=true&primary=true

**Comment by dgennetten** [comment]
@tracybarmore Can you please confirm the expected behavior?  The stated expected behavior doesn't seem to be present "in other themes" (e.g. grommet themed primary anchor doesn't 'change to black'). I see the inconsistency you mention, but it's not clear what is correct.
