### ISSUE TITLE
user Layer component to creat a confirm box, the border is jagged line not aligned

### ISSUE THREAD

**Issue by RodHPE** [grommet/grommet#1112]
use Layer component to creat a confirm box, the border is jagged line not aligned in firefox
### URL, screen shot, or Codepen exhibiting the issue
    

![image](https://cloud.githubusercontent.com/assets/20080920/21515749/5545bcc2-cd0d-11e6-856f-38f4e6c24940.png)

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: 1.0.0
* Browser Name and version:  firefox 50.1

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/6916e2677ab561ab3e4fba8a68870991c668367d
