### ISSUE TITLE
"Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Box component."

### ISSUE THREAD

**Issue by ezzatron** [grommet/grommet#1115]
### Expected Behavior

Use of the Box component should not result in JavaScript errors.

### Actual Behavior

Intermittently, Grommet causes batches of JavaScript errors to appear in the console, with this description:

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Box component.

The stack trace indicates that [this line in Box.js](https://github.com/grommet/grommet/blob/5c3a038/src/js/components/Box.js#L71) is responsible, but there are similar lines in other Grommet components also.

### URL, screen shot, or Codepen exhibiting the issue

<img width="657" alt="screen shot 2017-01-01 at 1 53 16 am" src="https://cloud.githubusercontent.com/assets/100152/21578265/338e7bea-cfc5-11e6-8d42-fe48758a546d.png">

### Steps to Reproduce
 1. Use Box component.
 2. ???
 3. Errors.

Sorry, I have no idea what's causing it beyond that. I do have some boxes whose background color changes dynamically, which may be relevant as the error occurs in a function named `_setDarkBackground`.

### Your Environment

* Grommet version: 1.1.0
* Browser Name and version: Chrome 55.0.2883.95
* Operating System and version (desktop or mobile): OS X El Capitan

**Comment by ericsoderberghp** [comment]
I believe this is fixed. Just waiting for a few more things to test.
