### ISSUE TITLE
Enhance Grommet Bot - needs attention label

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet#1117]
Enhance grommet bot to label issues that need attention. 
- Issues and Pull Requests that have new comments that are not from a Grommet Core team member.
- If issue or pull request has "waiting" label and new comment from a non-Grommet core team member is submitted, remove "waiting" label, add "needs attention" label.

**Comment by alansouzati** [comment]
we will not add support for the bot as we changed the way we are handling the issues.
