### ISSUE TITLE
Enhance Grommet Bot - new repo default labels

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet#1118]
Enhance the grommet bot to automatically remove the default github label and add grommet's labels when a new repo is created. 

	• suggestion - #00CCEB
	• help wanted - #8CC800
	• entry level - #865CD6
	• no change - #FFFFFF
	• waiting - #DBDBDB
	• BOT needs attention - #FFD602

**Comment by alansouzati** [comment]
we will not add support for the bot as we changed the way we are handling the issues.
