### ISSUE TITLE
Issue installing grommet on centos

### ISSUE THREAD

**Issue by antoine-voiry** [grommet/grommet#112]
All
I am getting following issues using grommet
npm install -g gulp
npm install -g grommet
grommet init sample-app

The last command fails with beloz error in /home/centos/sample-app/npm-debug.log
		 info it worked if it ends with ok
		1 verbose cli [ 'node', '/usr/bin/npm', 'install' ]
		2 info using npm@1.3.6
		3 info using node@v0.10.36
		4 error install Couldn't read dependencies
		5 error Failed to parse json
		5 error Unexpected end of input
		6 error File: /home/centos/sample-app/package.json
		7 error Failed to parse package.json data.
		7 error package.json must be actual JSON, not just JavaScript.
		7 error
		7 error This is not a bug in npm.
		7 error Tell the package author to fix their package.json file. JSON.parse
		8 error System Linux 3.10.0-229.el7.x86_64
		9 error command "node" "/usr/bin/npm" "install"
		10 error cwd /home/centos/sample-app
		11 error node -v v0.10.36
		12 error npm -v 1.3.6
		13 error file /home/centos/sample-app/package.json

**Comment by alansouzati** [comment]
Can you try to update your node and npm? I'm using Node 0.12 and NPM 2.7.5. Npm 1.3.x seems not to be supported.

**Comment by bryanjacquot** [comment]
@antoine-voiry is this still an issue with the latest version of Grommet, Node, NPM on CentOS?

**Comment by antoine-voiry** [comment]
This was solved in a recent version, I simply forgot to get back and update github.
