### ISSUE TITLE
OnMore Lazy Loading issue on Table and Tiles Component when it is on Layer

### ISSUE THREAD

**Issue by avadhutkhavare** [grommet/grommet#1121]
It is observed that onMore event is trigger anytime we scroll (up or down) and it is not just triggering when we scroll down and release.
Table component onMore is triggering correctly when we scroll at the bottom of page and release, but it works until there is an enough space left at the bottom after that it stops triggering onMore event, we are trying to implement Lazy loading with this.
Please let me know if there is any settings which will trigger onMore only in case we scroll at the bottom of page and release???
Find code pen for the same
http://codepen.io/avadhutk/pen/BQebrj?editors=0010

I am using 1.0.1 grommet version.

**Comment by ericsoderberghp** [comment]
That CodePen has Tables as a child of Tiles, which isn't a supported composition. You should either have a Table containing a table body and rows or a Tiles containing Tile components.

**Comment by avadhutkhavare** [comment]
Hi Eric,
Even though we remove Tiles and keep only tables it is also not working.

Find updated code pen for the same...
http://codepen.io/avadhutk/pen/BQebrj?editors=0010

Thanks,
Avadhut Khavare

**Comment by avadhutkhavare** [comment]
Hi Eric,
Could you please suggest the workaround for this, we need this onMore to be implemented on layer and we can run away with the table component. As I said we tried adding tiles onMore which did not work, I kept only table and there is no tiles component used but then also it is not working.

Thanks,
Avadhut Khavare

**Comment by alansouzati** [comment]
hey @avadhutkhavare can you please validate this with the latest grommet? we believe this is fixed.

**Comment by tracybarmore** [comment]
Closing issue since it hasn't been active for at least 30 days. Feel free to reopen this issue if it has not been fixed. Thanks!
