### ISSUE TITLE
Opensource showcase website

### ISSUE THREAD

**Issue by acpower7** [grommet/grommet#1124]
Hi

I really like the website (www.hpe.com) that is displayed as a showcase for Grommet UI.
Is there any chance the code to this website be published? I think it will help a lot of people understand how to build really good websites using Grommet.

regards

**Comment by RyanCCollins** [comment]
Hey @acpower7!

I can't answer regarding the hpe.com website, but I can offer to share some of the sites that I've built with Grommet that are open source.  They may not be as good as the HPE site, but might be helpful nonetheless.

Portfolio
- Live (https://www.ryancollins.io)
- Code (https://github.com/RyanCCollins/ryancollinsio)

Udacity Alumni Community
- (Not yet live)
- Code (https://github.com/RyanCCollins/udacity-alumni-fe)

Cheers!

**Comment by alansouzati** [comment]
I don't think hpe.com is built using grommet. The current open source apps using Grommet are:

**Ferret**:

http://ferret.grommet.io
https://github.com/grommet/grommet-ferret

**Blog**:

https://blog.grommet.io
https://github.com/grommet/grommet-blog

**Grommet docs**
https://grommet.github.io
https://github.com/grommet/grommet-docs

We are currently working to add more rich examples to the `grommet init` command in our CLI. Stay tuned for that.
