### ISSUE TITLE
AnnotatedMeter doesn't exist anymore?

### ISSUE THREAD

**Issue by arabold** [grommet/grommet#1125]
Hi,

Thanks for this beautiful framework. I'm still quite new to React and played with a couple of other libs but quickly found Grommet to be my library of choice.

### Expected Behavior
The documentation refers to a component called `AnnotatedMeter`: https://grommet.github.io/aruba/docs/annotated-meter

<img src="https://cloud.githubusercontent.com/assets/1548229/21755188/4b9c711a-d5c4-11e6-81f0-3b753740e057.png" width="150" />

```html
<AnnotatedMeter type='circle'
  series={[{"label": "First", "value": 20, "colorIndex": "graph-1"}, {"label": "Second", "value": 50, "colorIndex": "graph-2"}]}
  legend={true} />
```

### Actual Behavior
This component doesn't seem to exist. There's `Meter` but it's not clear how to use a regular meter to have the same effect as demoed on the documentation page.

### My Environment
* Grommet version: 1.1.0

### Workaround
Based on the Infographic example it seems I have to use the regular Meter component and do some additional coding to get the expected behavior: https://github.com/grommet/grommet-infographic/blob/master/src/js/components/CircleMeter.js

**Comment by RyanCCollins** [comment]
Hi @arabold,

It looks like the import statement for the docs for AnnotatedMeter is incorrect.  

The AnnotatedMeter component is located in the [grommet-addons library](https://github.com/grommet/grommet-addons/blob/master/src/js/components/AnnotatedMeter.js), which is an adjunct lib that contains several add-on components.

**Comment by RyanCCollins** [comment]
Should be fixed by #[221](https://github.com/grommet/grommet-docs/pull/221) on grommet-docs

**Comment by arabold** [comment]
Nice! Didn't even know this library yet. Thank you.
