### ISSUE TITLE
Header fixed attribute not working if used inside split tag with Table component

### ISSUE THREAD

**Issue by vaibhavbhargav** [grommet/grommet#1126]
Inside split, above table (having onMore attribute) component Header component with fixed property to true is not scrolling along with scrollbar.

### Expected Behavior
If Header's fixed property is set to true it should be fixed to its initial position.

### Actual Behavior
If we use Header Tag in split with Table (having onMore attribute for lazy loading), header fixed property is not working and.while scrolling down, header is not visible. Header content should stayed at the same position while scrolling down.

### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/vaibhavbhargav/pen/ggawVq

### Your Environment

* Grommet version: 1.1.0

**Comment by mossjm** [comment]
It seems that the issue only appears when the viewport is narrow (mobile).
Also this issue appears to apply across the board to Header elements (not specific to ones within Split or Table)
