### ISSUE TITLE
Layers fixed heading scrolling up when layer is positioned center

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet#1129]
Opened issue by @rushi2
Moving issue to grommet/grommet repo.
Closing issue grommet/grommet-docs#222

A fixed header is added to the layer and layer had vertical scroll. When the layer is positioned center (align="center"), then heading is scrolling up. But if the layer is positioned right, the heading is fixed and it is not scrolling up when layer is scrolled.

### Expected Behavior

Even when the layer is positioned center, the FIXED header should not scroll up with the layer.

### Actual Behavior

The fixed header is scrolling up and disappearing when the layer is  aligned to center (align="center").
### URL or screen shot exhibiting the issue
[Provided]

**When layer is positioned center**
![image](https://cloud.githubusercontent.com/assets/8565174/21843058/89da9fae-d80f-11e6-948a-24babc1d7f2e.png)

**When layer is positioned right:**
![image](https://cloud.githubusercontent.com/assets/8565174/21843012/45f551d0-d80f-11e6-903b-090f9c5e3db2.png)

### Steps to Reproduce
Code snippet

```
<Layer align="center" closer={true} onClose={this._onCreatePolicyCancel}>
      <Header fixed={true}>
        <Heading strong={true} tag="h3" align="center" margin="none">Create New Policy</Heading>
      </Header>
      <Form onSubmit={this._onSubmit}>
        <fieldset>
        <Box>....
```

### Your Environment
* Browser Name and version:
Chrome Version 55.0.2883.87 m
* Operating System and version (desktop or mobile):
Windows 7(desktop)
*Grommet Version
1.1.0

**Comment by tracybarmore** [comment]
Opened issue by @rushi2
Moving issue to grommet/grommet repo.
Closing issue grommet/grommet-docs#222

**Comment by L0ZZI** [comment]
@tracybarmore is this still occurring. I couldn't reproduce.

**Comment by L0ZZI** [comment]
Closing at 2 week mark.
