### ISSUE TITLE
Primary Inline Horizontal <Menu> components are WAY too wide.

### ISSUE THREAD

**Issue by woodm1979** [grommet/grommet#1136]
If you create a <Menu> component with <Anchor> children, that's Primary, Inline, and HOrizontal, the child <Anchor> tags are somehow WAY too wide.  (They're given a width of 100%, but I still don't understand why that's so bad.)

### Expected Behavior

A horizontal, primary, inline menu should display on the page in a way that looks very similar to the same menu that's NOT primary (which seems to work correctly).

### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/hpe/docs/menu/examples?responsive=true&inline=true&direction=row&primary=true&label=false&icon=false&size=medium&i-anchors=true

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: 1.1.0
* Browser Name and version:  Chrome 55.0.2883.95
* Operating System and version (desktop or mobile):  OS-X Sierra

**Comment by alansouzati** [comment]
Thanks for identifying this. We will look into it.

**Comment by RyanCCollins** [comment]
I'm looking at resolving this, but am honestly not sure what the proper behavior is for a primary row menu.  

Is the menu meant to span the full width of its container with the menu items evenly spaced?

![screen shot 2017-09-14 at 4 04 25 pm](https://user-images.githubusercontent.com/13810084/30453294-6a7c7894-9966-11e7-8fb3-72cf0222a163.png)

**Comment by RyanCCollins** [comment]
I've added a fix for this, but honestly don't know if it will break anything else.  See [here](https://github.com/grommet/grommet/compare/fix_rc_inline_menu_bug?expand=1).

**Comment by L0ZZI** [comment]
@woodm1979 did this resolve your issue?

**Comment by L0ZZI** [comment]
No reply. Closing.

**Comment by hgezim** [comment]
The link posted above ( http://grommet.io/hpe/docs/menu/examples/?responsive=true&inline=true&direction=row&primary=true&label=false&icon=false&size=medium&i-anchors=true ), still shows a huge amount of space between items in Firefox 58.0.2.

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/124675/36702212-57cb64ce-1b13-11e8-80a2-3cf00536f191.png">
