### ISSUE TITLE
Strange CSS rules for common markup

### ISSUE THREAD

**Issue by ido-ran** [grommet/grommet#1139]
We are building a project with Grommet and we've notice there are unexplained CSS behaviors.  
We track it down and found that `_generic.shared.scss` which comes from `inuit-shared/_generic.shared.scss` have margin set that cause the problem.

### Expected Behavior
No special CSS for common elements such as ul as you can see in the picture.

### Actual Behavior
Strange CSS that cause wrong placement of elements.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/187938/22098569/aade6070-de2f-11e6-9c21-555fd20afb34.png)

### Steps to Reproduce
 1. Create a project with Grommet and use ul tag

### Your Environment

* Grommet version: 1.1.0
* Browser Name and version: Both Chrome and IE
* Operating System and version (desktop or mobile): Windows 10

**Comment by tracybarmore** [comment]
Issue should be resolved with #1154

**Comment by dgennetten** [comment]
Verified fixed.
