### ISSUE TITLE
Responsive sidebar on doc site

### ISSUE THREAD

**Issue by dustingraves** [grommet/grommet#1140]
I would like to implement a responsive sidebar/header as seen on the doc site. I cannot find any way of easily recreating this just through existing components.

### Expected Behavior

I would like to find docs or a way to do this.
### Actual Behavior

I cannot find docs or a way to do this
### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: 1.1.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): OS X and iOS

**Comment by allcentury** [comment]
The website is open source here: https://github.com/grommet/grommet-docs

**Comment by alansouzati** [comment]
Let me work on a codepen so that you guys can easily grab it

**Comment by alansouzati** [comment]
I believe this is what you are looking for:

http://codepen.io/alansouzati/pen/pRevaE?editors=0010

Feel free to reopen the issue if you think otherwise.

**Comment by dustingraves** [comment]
@alansouzati I can make the sidebar just fine, I want to have the responsive header like on the docs site. If you shrink it down or go on mobile the header of the sidebar "basically" appears as the new page header with a link to popout the sidebar. The only way I can actually think of doing this in a react way is getting the media screen size and adding/removing component each time the screen size matches the trigger.

![image](https://cloud.githubusercontent.com/assets/6600627/22121251/23665946-de38-11e6-8120-aeeba2bd89cf.png)


![image](https://cloud.githubusercontent.com/assets/6600627/22121256/28687974-de38-11e6-8335-04e550de4a4c.png)

**Comment by alansouzati** [comment]
cool let me work on updating the codepen to accommodate that.

**Comment by dustingraves** [comment]
Thanks

**Comment by alansouzati** [comment]
There you go http://codepen.io/alansouzati/pen/pRevaE?editors=0010
