### ISSUE TITLE
Add 'disable' prop to LoginForm

### ISSUE THREAD

**Issue by ziflex** [grommet/grommet#1142]
Hi guys,

thanks for these great components, I really like them.

I'm wondering whether there are any plans to add ```disable``` prop to ```LoginForm```  in order to not allow users to edit the form during authentication process (when ```submit``` button was called). It would be very helpful.

### Expected Behavior
Pass ```disable``` property in order to disable the entire form.

### Actual Behavior
Lack of required property.

### Your Environment

* Grommet version: 1.2.0
* Browser Name and version: Chrome 55
* Operating System and version (desktop or mobile): Fedora 25

**Comment by alansouzati** [comment]
Hey, thanks for the kind words.

Yeah this is a current limitation of the LoginForm. Moving forward we will be moving LoginForm to Grommet-addons project as this component is a combination of other Grommet core components.

In other products I had a chance to participate, we replaced the button with a spinning icon plus the help text, something like `[icon] Saving...`. Unfortunately today it is not possible to do that with the LoginForm.

We are currently working/thinking in a good pattern for this, we believe this goes behind than just the LoginForm.

In the meantime, I would recommend copying over the Login Form, and use this intermittent solution of replacing the button.

**Comment by tracybarmore** [comment]
Issue should be fixed by #1155

**Comment by L0ZZI** [comment]
Can you confirm fix @ziflex?

**Comment by L0ZZI** [comment]
Closing at 2 week mark.

**Comment by ziflex** [comment]
Hey guys, I'm sorry for the late response.
Unfortunately, I do not have an access to the app to test this fix.
