### ISSUE TITLE
Table onMore not working in Internet Explorer 11

### ISSUE THREAD

**Issue by ishwark7** [grommet/grommet#1151]
Table onMore is not working as expected in Internet Explorer (IE 11) while it works fine in other browsers

### Expected Behavior

It should also work in IE 11

### URL, screen shot, or Codepen exhibiting the issue
URL to reproduce the issue (open in IE and Chrome to see the different behavior): https://grommet.github.io/docs/table/examples/?onMore=func&i-header=true

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/9c9b16dd77202a87d98958186894db729a1e1848
