### ISSUE TITLE
Table OnMore not working in IE 11 when Table is inside a Box

### ISSUE THREAD

**Issue by insane07** [grommet/grommet#1153]
Table onMore is not working as expected in Internet Explorer (IE 11) while it works fine in other browsers.
This issue is seen when table component is used inside Box/Section comnponent.

### Expected Behavior
It should also work in IE 11

### Codepen exhibiting the issue
open in IE and Chrome to see the different behavior: 
http://codepen.io/shitij07/pen/XpgyGw

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/8254e7e2b0a9a771c1fa7d4753483c051b777d67
