### ISSUE TITLE
Missing 24-hour time format in Timestamp

### ISSUE THREAD

**Issue by mjasnikovs** [grommet/grommet#1157]
Missing 24-hour time format in Timestamp. 12-hour clock is generally used in British colonies.
Globally, required all functionality witch is available in toLocaleDateString. To format time properly accordingly to local standards.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

**Comment by dgennetten** [comment]
@mjasnikovs, as indicated in the link you provided, the Date object (which Timestamp uses) provides 24-hour time format as a default in locales where that is standard. I just verified this is true noting that https://grommet.github.io/docs/timestamp shows "15" for  <Timestamp value='2017-05-08T19:48:16.098Z'  fields='hours' /> operating in es-ES (Spain), where in the US ('en-US') it shows "10 am".
