### ISSUE TITLE
Table responsive prop doesn't work

### ISSUE THREAD

**Issue by przytrzask** [grommet/grommet#1158]
There is a responsive option in table according to docs. 
https://grommet.github.io/docs/table
Whern  the display area narrows table is switching to column mode even when property responsive is set as false

### Expected Behavior
When responsive on table is false. Table shouldn't swich to column layout

### Actual Behavior
table is switching to column mode even when property responsive is set to false

###### before
![Before](http://i.imgur.com/x7NCMrW.png)
###### after
![After](http://i.imgur.com/QAPaVvU.png)
###### issue
![issue](http://i.imgur.com/WcMP6YK.png)

### Proposed solution
 If the space is too short, the table is displayed in a responsive manner and this is very nice faeture but in  some cases (when you have more data) it is desired to decrease table cells padding or font-size.
 

### Your Environment

* Grommet version: v1.2.0

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/1c455132a7d5ddf51ab9da0303f03d5430383db3
