### ISSUE TITLE
grommet-hpe-icons.ai organization

### ISSUE THREAD

**Issue by cssberries** [grommet/grommet#116]
It would be great if we could have each icon in separate, named group or layer.
Or, even better, to have them in separate SVG files.

I tried to extract all the icons with this script: https://github.com/iconic/illustrator-svg-exporter but it requires the icons to be grouped and named in specific way.

**Comment by bryanjacquot** [comment]
All icons are available as SVG (and have been for a while).  https://github.com/grommet/grommet/tree/master/src/img/icons
