### ISSUE TITLE
Styling for <Anchor> changes radically depending upon the presence of "icon"

### ISSUE THREAD

**Issue by woodm1979** [grommet/grommet#1161]
The styling for an <Anchor> changes radically depending on the presence of the "icon" property.

### Expected Behavior

I'd expect the anchor to look the same (+/- the presence of an icon) regardless of the presence of an icon.

### Actual Behavior

In the "grommet theme", the anchor changes from black+strong to purple+(not strong).
In the "HPE theme", the anchor changes from strong+(not-underlined) to (not strong) + underlined.

### URL, screen shot, or Codepen exhibiting the issue

https://grommet.github.io/hpe/docs/anchor/examples?icon=false&label=true&animateIcon=true&href=true

### Steps to Reproduce
 1. Toggle the "Icon" option in the upper left menu.
 2. Note the change if formatting.
 3. 

### Your Environment

* Grommet version: 1.2.1
* Browser Name and version: Chrome 55.0.2883.95
* Operating System and version (desktop or mobile): Mac OS-X, Sierra

**Comment by ericsoderberghp** [comment]
It is part of the design to have different styling with or without an icon. But, we should review the implementation again to see that it matches the design.

**Comment by L0ZZI** [comment]
We're doing some evaluation of the design of button's with icon, label and anchors with icon for better alignment. This is more of design enhancement than a defect. I'll close if there isn't any other feedback.

**Comment by gitdistill** [comment]
did it change even more in the most recent update 1.3.0? 

Seems weird to me that it changes, at the very least it should inherit the link color.

![screenshot 2017-03-16 11 31 16](https://cloud.githubusercontent.com/assets/2692764/24012711/38bb06d6-0a3c-11e7-8932-c69dd6464216.png)
