### ISSUE TITLE
TableHeader.onSort doesn't work with Table.scrollable=true

### ISSUE THREAD

**Issue by dioklecijan** [grommet/grommet#1162]
Adding scrollable={true} to the Table component stops executing TableHeader onSort callback.

This works as expected:

```js
<Table>
  <TableHeader labels={['Name', 'Note']}
    sortIndex={0}
    sortAscending={true}
    onSort={this.onSort}
 /><tbody>...</tbody></Table>
```

After adding scrollable={true}, callback this.onSort is not called anymore:

```js
<Table scrollable={true}>
  <TableHeader labels={['Name', 'Note']}
    sortIndex={0}
    sortAscending={true}
    onSort={this.onSort}
 /><tbody>...</tbody></Table>
```

### Your Environment
* Grommet version: 1.2.0.
* Browser Name and version: Google Chrome 55.0.2883.95 (64-bit)
* Operating System and version (desktop or mobile): macSierra 10.12.2

**Comment by dakt** [comment]
Well this is still the case even in 1.3.4.
I really don't understand how can this problem persist for so long. Just don't tell me it's by design.
This makes <Table /> component useless.

**Comment by bammmmmmmmm** [comment]
I agree with @dakt

**Comment by adamroldfield** [comment]
The mirror element created when scrollable = true is cloning the header, but it doesn't copy the click events. The real header with the click events assigned is hidden behind it and the thead is set to hidden.

**Comment by adamroldfield** [comment]
This will fix it. Replace the for loop in build mirror with:

`for (let i = 0; i < cells.length; i++) {
          const cell = cells[i];
          const cloneCell = cell.cloneNode(true);
          if (cell.children.length)    
            cloneCell.onclick = () => cell.children[0].click();
          mirrorRow.appendChild(cloneCell);
        }`

**Comment by dgennetten** [comment]
Seems fine now on grommet 1.7.0, chrome 60.0.3112.113
