### ISSUE TITLE
Split component does not have independent scrolling when in a view less than `100vh`

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet#1164]
### Expected Behavior
The Split component should allow independent scrolling no matter what container it is rendered in. 

### Actual Behavior
As it stands, the Split component will only allow independent scrolling when it is located inside a dom element that takes up 100vh (full height of web browser).  In my example codepen, you will see that the the scroll is not working independently because I have placed a fixed Header above it.  If I change the scss in grommet-core to be `100vh - <header_height>`, the scroll works as expected.

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/ryancollins/pen/vgeboQ

### Steps to Reproduce
 1. Go to the above codepen
 2. Try to scroll the split children independently

### Your Environment

* Grommet version: 1.2.1
* Browser Name and version: Chrome, Safari
* Operating System and version (desktop or mobile): Ubuntu / Mac

**Comment by RyanCCollins** [comment]
I would be happy to try to implement a solution for this, btw.  Perhaps the height of the surrounding container can be calculated dynamically rather than being hard-coded at 100vh?

**Comment by ericsoderberghp** [comment]
Can we do it in a way that works with a `<Box direction="row" align="stretch">` container and rely on flexbox to take care of it, rather than doing any calculations dynamically?

**Comment by RyanCCollins** [comment]
Yeah, that sounds like the grommet way to do it!  Sounds good, thanks @ericsoderberghp
