### ISSUE TITLE
Table Row Background color attribute

### ISSUE THREAD

**Issue by avadhutkhavare** [grommet/grommet#1165]
### Expected Behavior

Developer should able to highlight any Table row background color based on condition
TableRow/TR should allow colorIndex attribute and highlight the specified row

### Actual Behavior

TableRow/TR component do not support colorIndex attribute.
  
### Your Environment

* Grommet version: v1.0.1
* Browser Name and version: CHROME/IE
* Operating System and version (desktop or mobile): Windows

**Comment by L0ZZI** [comment]
We don't have any plans on adding customization to the table styling in the near future as we try to keep the component styling to a minimum in keeping with Grommet's ethos. Changes to the table component styling could turn into a large area for enhancement. 

Would you have a use case that this change would support? What type of pattern/interaction would the color change make a meaningful impact?

**Comment by tracybarmore** [comment]
Hey @avadhutkhavare, sorry to be 'that guy', but we will be cleaning up our backlog next week by closing unresponsive issues that haven't been active for at least 30 days. If you would like this issue to remain open in our backlog, please comment to let us know. Thanks!

**Comment by tracybarmore** [comment]
March 14, 2017 - Backlog grooming resulted in the closure of this issue. Please feel free to reopen to continue the conversation. Thanks!
