### ISSUE TITLE
datetime css on mobile fix needed

### ISSUE THREAD

**Issue by crobinson42** [grommet/grommet#1169]
### Expected Behavior
The datetime component should be visible and 'pretty' on a mobile display, filling no more than 100% height/width of viewport

### Actual Behavior
z-index of input is too low and height/width is not adjusted correctly

### URL, screen shot, or Codepen exhibiting the issue
https://www.dropbox.com/s/p5hiixt454m4s2o/Screenshot%202017-01-29%2023.49.28.png?dl=0
https://www.dropbox.com/s/mt6q0dcodhlcdst/Screenshot%202017-01-29%2023.49.18.png?dl=0

### Steps to Reproduce
Chrome dev tools on the github pages for components

**Comment by ericsoderberghp** [comment]
Agreed. Looking into it.

**Comment by karatechops** [comment]
@ThanosDi, thanks for filing this issue. I agree DateTime could use some mobile cleaning up. This late in 1.x I don't think any drastic changes will be made to DateTime component. I'll tag 2.0's DateTime card (#1460) so we can get this worked out.
