### ISSUE TITLE
Accordion Control

### ISSUE THREAD

**Issue by novecento** [grommet/grommet#117]
Hi guys,
thank you for all your work.

I'm designing three concept based on Accordion Menu functionality and when I talked about Grommet to my manager he was very interested so: have you planned the implementation of this control?

**Comment by ericsoderberghp** [comment]
We do not currently have an accordion style Menu in plan. Can you share a sketch showing the context of where and how you would use it? I ask because we might have existing components that could work in a slightly different way.

**Comment by novecento** [comment]
Hi Eric, this is my general idea:
![untitled-1](https://cloud.githubusercontent.com/assets/1419568/9056403/1c873b80-3a93-11e5-8d22-d826bc19c71f.jpg)
I'd like dynamic resizing as well.. :-P

**Comment by ericsoderberghp** [comment]
Thanks for the graphic. Can you send an entire page/screen context showing where this would be used?

**Comment by bryanjacquot** [comment]
In the stable branch of grommet, there is now and Accordion http://www.grommet.io/docs/hpe/develop/accordion which will be in the next release of grommet.
