### ISSUE TITLE
Cannot execute npm development server following get started page

### ISSUE THREAD

**Issue by mauleyzaola** [grommet/grommet#1170]
### Expected Behavior
I should have been able to login with any combination of username/password

### Actual Behavior
The browser displays the error `Gateway Timeout`. Also npm in the terminal has more information, probably is relevant.
```
Mauricios-iMac:sample-app mleyzaola$ npm run dev

> sample-app@0.1.0 dev /Users/mleyzaola/Downloads/sample-app
> cross-env NODE_ENV=development grommet pack

[grommet:pack]: Deleting previously generated distribution folder...
[grommet:pack]: Copying public folder...
[grommet:pack]: Running webpack...
[grommet:pack]: Starting dev server...
[HPM] Proxy created: /api  ->  http://localhost:8102
Hash: bf6de7f5492894e66a96
Version: webpack 1.14.0
Time: 4410ms
       Asset     Size  Chunks             Chunk Names
   index.css   388 kB          [emitted]
    index.js  2.46 MB       0  [emitted]  main
index.js.map  2.88 MB       0  [emitted]  main
[grommet:pack]: success
[grommet:pack]: Opening the browser at http://localhost:3000
[HPM] Error occurred while trying to proxy request /api/sessions from localhost:3000 to http://localhost:8102 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

### URL, screen shot, or Codepen exhibiting the issue
`http://localhost:3000/login`

![image](https://cloud.githubusercontent.com/assets/1648558/22436209/d1f5e6bc-e6e8-11e6-8214-5fa8c6280d39.png)

### Steps to Reproduce
 1. `npm install -g grommet-cli`
 2. `grommet new sample-app`
 3. `cd sample-app`
 4. `npm run dev`

### Your Environment

* Grommet version: `grommet-cli@2.1.6`
* Browser Name and version: Google Chrome 55.0.2883.95
* Operating System and version (desktop or mobile): Mac OS El Capitan Desktop

My env
```
Mauricios-iMac:sample-app mleyzaola$ node -v && npm -v
v7.4.0
4.0.5
```
Thanks!

**Comment by alansouzati** [comment]
I believe you are missing to run the back-end server `npm run dev-server` ?

**Comment by mauleyzaola** [comment]
Next time I'll have a coffee before reading lol. Thanks @alansouzati

**Comment by alansouzati** [comment]
no problem glad you are up and running now

**Comment by toelapiut** [comment]
I had the same problem and I solved by running ` npm start` and it destroyed and built  a new dist which allowed me to log in
