### ISSUE TITLE
Legend has 9999999 in the total

### ISSUE THREAD

**Issue by coltonw** [grommet/grommet#1174]
### Expected Behavior
The total should come from the sum of the series data

### Actual Behavior
Javascript floating point errors are creeping in under certain circumstances.

### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/coltonw/pen/PWaENd?editors=0010#0

### Your Environment

* Grommet version: 1.2.1
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Reproduced on Windows or Mac

### Also...
I am working on a pull request but in case I don't get to it for a few days, I wanted to make sure to have a codepen of the issue so I don't forget about it when the data changes and I am no longer seeing the issue.

**Comment by alansouzati** [comment]
looking forward for a PR 🎉

**Comment by ericsoderberghp** [comment]
I can't seem to reproduce this. The CodePen on Opera, Chrome, and Firefox is always showing "4.54" for the total, which seems correct.

**Comment by coltonw** [comment]
That is because my pull request already fixed it!  This can be closed.
