### ISSUE TITLE
TableHeader should allow sorting capability on selective columns

### ISSUE THREAD

**Issue by vaibhavbhargav** [grommet/grommet#1176]
TableHeader component should provide attributes so that we can choose which column can have sortable capability.

### Expected Behavior
There should be way to provide sortable capability on selective  columns.

### Actual Behavior
Currently if we pass 'onSort' function, all table header becomes sortable. Currently there is a hand icon shows an each column.

### Your Environment

* Grommet version:latest 
* Browser Name and version: 
* Operating System and version (desktop or mobile):

**Comment by tracybarmore** [comment]
Hi @vaibhavbhargav. Thanks for opening this issue. Can you give us an example of what you are trying to achieve? There may be something interesting we can address here based on what you are currently working on. Thanks!

**Comment by tracybarmore** [comment]
Closing issue as indicated in previous comment to clean up backlog. Feel free to reopen to bring it back to our attention. Thanks!

**Comment by pho3nixf1re** [comment]
I too am interested in this feature. I have several columns in my dataset but only 2 need to be sortable. The other data is impractical to sort due to the way it is related across services. Therefore I need a way to exclude some of these columns from sorting in the header.

**Comment by pho3nixf1re** [comment]
Perhaps something as simple as this:

```jsx
<TableHeader
  labels={['Name', { label: 'Note', sortable: false }]}
/>
```

Where the default is to allow sorting but if there is an object of the shape `{ label, sortable }` it would then pick up the `sortable` boolean.

**Comment by pho3nixf1re** [comment]
Is there any chance a PR to support this would be accepted?
