### ISSUE TITLE
Columns with masonry on throws opaque errors when there is no DOM

### ISSUE THREAD

**Issue by coltonw** [grommet/grommet#1177]
### Expected Behavior
The Columns would have some sort of fallback that would not throw errors when it cannot access DOM elements.

### Actual Behavior
It throws errors. This is frustrating for jest testing any component that use columns with masonry as their layout because they cannot use snapshot testing for any ancestor of the columns.

### URL, screen shot, or Codepen exhibiting the issue

```
it('has correct default options', () => {
  const component = renderer.create(
    <Columns masonry>
      <span>test1</span>
      <span>test2</span>
    </Columns>
  );
  let tree = component.toJSON();
  expect(tree).toMatchSnapshot();
});
```

### Your Environment

* Grommet version: 1.2.1
* Browser Name and version: Nodejs v6.9.4
* Operating System and version (desktop or mobile): Mac

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/6024dcd34e4b23df4c673abaf4ccd1e482178102
