### ISSUE TITLE
Dropdowns not 100% clickable in Firefox

### ISSUE THREAD

**Issue by hdehal** [grommet/grommet#1180]
https://grommet.github.io/docs/select

Dropdowns are not clickable unless you click the arrow itself – issue only in Firefox. It appears clickable in Safari/Chrome.

### Your Environment
* Firefox
* Mac OS X

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/a957c942e68fb73a1e9c8a4d5c76e129ee40aadc
