### ISSUE TITLE
Close Layer by clicking outside it

### ISSUE THREAD

**Issue by alanpilloud** [grommet/grommet#1183]
Hello,

I hope the Grommet team is fine today.

I saw in the release notes this line : 

 - Changed Layer to not close when the user clicks outside it

However, I used to prefer when we were able to click outside the Layer to close it. Would it be possible to make it a prop ?

### Expected Behavior
Close a Layer by clicking outside it

### Actual Behavior
The Layer do not close by clicking outside it

### Steps to Reproduce
 1. Add a Layer to your app
 2. Open the Layer
 3. Try to close the Layer by clicking outside of it

### Your Environment
* Grommet version: 1.2.1
* Browser Name and version: Chrome 56.0.2924.87
* Operating System and version (desktop or mobile): Windows 10

**Comment by tracybarmore** [comment]
linking with #1209

**Comment by alansouzati** [comment]
Hey @alanpilloud thanks for this issue and sorry for taking such a long time to get back to you on this.

I see problems with both solutions (closing and not closing when clicking outside).

For example, let's say you have a form inside a layer, you entered all the data and accidentally clicked outside. With the previous behavior we would close the layer and the user would have to enter the form all over again.

With the close being activated only when the user clicks in the `X` icon we have a lower chance of problems like that to happen.

Let's explore another scenario: a layer with an agreement form that we want to enforce the user to scroll to the bottom, closing by clicking outside the layer would be problematic as well.

I'm trying to think about a scenario where closing by outside the layer will bring benefits to the user. Can you help me here?

I'm not against adding a prop to make it flexible, but I guess we need to think more about the bigger picture on this problem. It seems like an easy one, but it brings interesting challenges in terms of User Experience.

**Comment by alanpilloud** [comment]
Hello,
No problem for the delay.

I totally understand your scnarios, here's mine : 

I have a list in a table of ~3000 elements and you can filter each column.
The most used filters fields are directly visible on this interface while other fields can be found on an advanced search which is a Layer.

So, this Layer holds filters fields that are filtering the list live. So in this case, it makes it quicker to click on the overlay. It's just easier not having to manipulate the mouse with precision, it's about lazyness :)

But this usage may not be optimal, do you have a better idea ?

Anyway, thanks for your hard work, I'm really glad I've found Grommet for my projects !

Have a nice day

**Comment by bsoutham** [comment]
As another example, we have a Layer becomes visible with links to help and documentation.  However, if they decide they don't want to use the help links - they should be able to just click back to the 75% of the screen that is still visible and close the "help" layer.  This is one example, where our current usage would benefit from having the layer close by clicking outside of it, rather than forcing them to click the close X

**Comment by jzillmann** [comment]
Missing that too!

**Comment by ramyhardan** [comment]
I use https://github.com/boblauer/react-onclickout for this:
```
import * as ClickOut from "react-onclickout";
...
<Layer>
  <ClickOut onClickOut={this.closeHandler}>
    <MyFancyLayerContent>
  </ClickOut>
</Layer>
```

**Comment by jzillmann** [comment]
Tried react-onclickout. At first it seems to work fine, however i now realized that if i have a selection input on my layer, selecting an item will close the layer... Not what i want ;)

**Comment by ramyhardan** [comment]
If you can live with a fragile hack, add something like
```
if (e.srcElement.className.contains("grommetux-select__option")) {
  return;
}
```
to react-onclickout's `___windowListener` before it calls the handler.

**Comment by ramyhardan** [comment]
You could do something hacky like `if (e.srcElement.className.includes("grommetux-select__option")) return` in your handler every time or use a HOF for this or modify react-onclickout's `__windowListener` accordingly. Doesn't get prettier, though. ;)

**Comment by twelve17** [comment]
@alansouzati I completely see the use cases where clicking outside the "X" would lead to unwanted behavior.  That being said, I also see use cases where it is helpful.  Would it be possible to have it be a prop, as the OP suggested?

Many thanks.
