### ISSUE TITLE
Carousel does not interact neither has events

### ISSUE THREAD

**Issue by MarcoMedrano** [grommet/grommet#1187]
It would be very helpful to be able to select the item to display by code. Also have events when a page has selected.
Something like:

`<Carousel selectedIndex={this.state.index} onSelectedIndex={index=>this.setState({index:index})}>`

The idea is be able to manage it by code and be reported when an item is changed so we can execute changes according that.

**Comment by tracybarmore** [comment]
Hey @MarcoMedrano, we're loving this idea. Pull requests are gladly accepted. Thanks for your continued collaboration!

**Comment by MarcoMedrano** [comment]
Added pull request :) https://github.com/grommet/grommet/pull/1239
