### ISSUE TITLE
404 Error: rawgit.com/grommet/grommet/stable/grommet.min.js

### ISSUE THREAD

**Issue by eniyan** [grommet/grommet#1188]
404 Error:
https://rawgit.com/grommet/grommet/stable/grommet.min.js

### Expected Behavior
Expected to show results and no broken links

### Actual Behavior
Page not available

### URL, screen shot, or Codepen exhibiting the issue
https://rawgit.com/grommet/grommet/stable/grommet.min.js
http://codepen.io/grommet/pen/gaEGPY

### Steps to Reproduce
1. Click on https://rawgit.com/grommet/grommet/stable/grommet.min.js
2. Click on http://codepen.io/grommet/pen/gaEGPY

### Your Environment
Chrome | Firefox | IE11
Codepen

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/0a47b645bc9e861f643a947b4c790d393cdbc55d
