### ISSUE TITLE
List onSelect argument type

### ISSUE THREAD

**Issue by dioklecijan** [grommet/grommet#1190]
IMHO, for the List component, the argument for the onSelect callback handler should always be an array when multiple rows may be selected. Besides semantic improvement, the code looks more elegant:

`<List selectable="multiple" onSelect={this.onSelect}>`

Instead:

```
  onSelect = (indexes) => {
    if (Array.isArray(indexes))
      indexes.forEach(idx => console.log(this.props.items[idx]));
    else
      console.log(this.props.items[indexes]);
  }
```

we could write:

```
  onSelect = (indexes) => indexes.forEach(idx => console.log(this.props.items[idx]));
```

### Your Environment
* Grommet version: 1.2

**Comment by tracybarmore** [comment]
Hey @dioklecijan, we agree. We just need to work through how to manage and communicate this change since it would mean a breaking change.

**Comment by karatechops** [comment]
Tagging 2.x List (#1472)
