### ISSUE TITLE
File Dropzone

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet#1191]
As discussed, I'd like to introduce a feature / enhancement for a component that allows for drag and drop of one or more files to upload.  

I've started outside of the Grommet repo in the brand-central-cms repo to develop a prototype for use in that project.  In the future, I'd like to transfer it into the grommet repo and would like to take this as an opportunity to discuss the functionality.

**Comment by RyanCCollins** [comment]
So far, what I am thinking is that we use a Box as the main component with a bit of default styling.  The File input will be hidden.  This will give the user the control over changing the default style in a familiar manner.

For example
```
  render() {
    const boxProps = Props.pick(this.props, Object.keys(Box.propTypes));
    const { className, label } = omit(this.props, Object.keys(Box.propTypes));
    const classes = classnames(
      CLASS_ROOT,
      className
    );
    return (
      <Box {...boxProps} onDrop={this._onDrop}
        onClick={this._onClick} className={classes}>
        {Dropzone.renderLabel(label)}
        <input ref="fileInput"
          type="file" className={`${CLASS_ROOT}__input`} />
      </Box>
    );
  }
```

**Comment by RyanCCollins** [comment]
A couple of things to consider for the design. 
1. The various states of the component
- Inactive
- On drag start (when the user is hovering over the component with one or more files. 
- On drop (when the user has dropped one or more files)
  - On file upload accepted
  - On file upload rejected

**Comment by alansouzati** [comment]
Nice interesting. 

Does this component have a fallback to the regular upload for users that cannot drag and drop?

**Comment by RyanCCollins** [comment]
Hey @alansouzati, it does, although I've yet to handle the case where a user tries to drop and html5 drag and drop is not available. 

That said,  it does have a hidden html5 file upload that's accessible by clicking the drop zone.

**Comment by RyanCCollins** [comment]
Also, here is a demo of the component in use in grommet-cms

![file-upload](http://g.recordit.co/HrE49BdkFp.gif)

**Comment by RyanCCollins** [comment]
Btw, sourcecode for the component is [here](https://github.com/grommet/brand-central-cms/blob/master/src/js/components/Dropzone/index.js).  I'll wait until we get some feedback on this from CMS users and the UX/Design team before submitting into core.

**Comment by arabold** [comment]
@RyanCCollins , I'm interested in this as well. Could you update the link?

**Comment by RyanCCollins** [comment]
Hey @arabold, sorry about that.  The link that I shared goes to a private repository.  We intend to move this into grommet, or into its own repository at some point but not right away.  I will post when I have more details.

**Comment by RyanCCollins** [comment]
I'm back to working on this, but no telling when it will be ready.  Hopefully after delivery of brand-central, I can get it done 😄

**Comment by arabold** [comment]
Currently I'm using [react-dropzone](https://www.npmjs.com/package/react-dropzone) which can be integrated pretty nicely.

**Comment by nomadus** [comment]
I am looking forward to see this feature in the nearest release of grommet. Our projects heavily depend on availability of file upload feature, if you could prioritize the resolution of the issue it would be great!

**Comment by RyanCCollins** [comment]
Cool thanks @nomadus!  There is a PR open for this. As soon as a grommet core member has some free time, we can get it reviewed and into the next releas.

**Comment by nomadus** [comment]
@RyanCCollins  I could not have it working, I have created a new project using create-react-app and added grommet from this branch.
`npm install git://github.com/grommet/grommet.git#feat_rc_dropzone --save`
When I issued `yarn start`, it errors with 
Module not found: Can't resolve 'grommet/components/Article' in 'C:\src\no-main-file\src'
The same works when I install `npm install grommet@1.4.0 --save`,

What could be an issue and how could I test these changes?

**Comment by nomadus** [comment]
Any news on this one?

**Comment by L0ZZI** [comment]
@RyanCCollins any chance this is a V2 feature?

**Comment by RyanCCollins** [comment]
I've closed this since the stalebot was going to.  Happen to re-open in the future if we find the right spot for this.
