### ISSUE TITLE
Need an easy and reliable way to locate the Grommet generated controls in the DOM tree

### ISSUE THREAD

**Issue by huiwang-hpe** [grommet/grommet#1193]
Currently, we are using WebDriver and Page Object for automating web application testing.
We found it difficult to locate the controls in the DOM with selectors.

Because controls are rendered by Grommet / Grommet-Index, and neither they have unique class name or ID, nor we could customize them.
Some controls are encapsulated in the hierarchical DOM structure, which makes the selector complex.

Thinking about when we upgrading to a new version of Grommet / Grommet-Index, will there be a lot of failed test cases caused by DOM pathes changing?

So here comes my ideas:

1. Set key controls with unique IDs or class names
2. Make the IDs and class names fixed and don't change them in the new version
3. Keep the DOM structure (path) inside encapsulated controls (e.g. "Index" component)
4. Provide interfaces to customize IDs or class names of encapsulated controls

What's your ideas or suggestions on this?

**Comment by alansouzati** [comment]
Thanks for bringing this up. This is an interesting topic to discuss.

Recently, we removed all the internal ids from our elements, this is mainly to avoid unnecessary complexity to maintain a valid HTML structure. We kept facing "duplicated id" issues when folks were using multiple Meters, for example.

Another thing we did to simplify was to deprecate grommet-index. The structure has too many abstractions which makes it hard to customize and as you pointed out, to test. We offer grommet-addons which has less abstractions than grommet-index, but brings the benefit of combining things and test things independently.

Inside grommet-core the only component that still has a "complex" interaction is the LoginForm. We are planning to move login form out of grommet-core very soon.

Exposing internal structure for testing purposes is not an ideal solution as it defeats the purposes of abstraction IMHO. I prefer to use the [query selector](queryselector javascript) capabilities to make sure I'm being as specific as I can to grab the desired DOM node.

For example, here is how I would test LoginForm:

```
<LoginForm className='my-app-login' ... />
```

```
document.querySelector(".my-app-login input=[type=password]")
```

So, the above code safely grabs the input for the password, as it is pretty unlikely that you will need to change this code any time soon.

I'm curious to hear more about your testing strategies and how you are testing the Grommet components. So let's keep the discussion going ;)

**Comment by huiwang-hpe** [comment]
Thanks Alan for the feedback.

Exactly as you said, grommet-index has too many abstractions. 
Unfortunately, our project was created from the template of "Ferret" which uses grommet-index.

For example, this is how we are getting the row count in the page object:

`get itemsCount() {`
`    let items = browser.elements('.index__items > .grommetux-list.grommetux-list--selectable.index-list > li').value;`
`    return items ? items.length : 0;`
`}`

The selector seems to be totally depends on what grommet-index rendered.
I am not quite confident on whether it will still work when I upgrade grommet-index.

**Comment by alansouzati** [comment]
Can you add a child of the LI with a classname? Assuming that you can do this, I would change my selector to only include that.

```
let items = browser.elements('.childelements-li').value;
return items ? items.length : 0;
```

I'm closing this issue for now, as I don't think there is anything to change in Grommet core.

Please feel free to open the issue again if you still feel something should be done.
