### ISSUE TITLE
Enhancements : request for editor control

### ISSUE THREAD

**Issue by devdil** [grommet/grommet#1196]
An editor area to upload source code which would provide features like auto-suggestion, indentation, line numbers, syntax highlighting, etc. 

Integration with https://ace.c9.io/ or https://codemirror.net/ would look good.

**Comment by nomadus** [comment]
Hi, is this only for a source code? Could we ask for more generalized solution, like a rich text editor which is capable to edit source code as well?

**Comment by RyanCCollins** [comment]
Hey @devdil, I can't speak for the entire Grommet team, but I think think a rich text editor or source code editor would be outside the scope of the Grommet Project.  The grommet library is more a collection of component primitives.  

That said, this might be a great project for another repository, for example [Grommet-Addons](https://github.com/grommet/grommet-addons), which is a repository the grommet team maintains for components that are a bit more complex.  I'd also encourage you to experiment making a component like this.  I know that I'd use it!  It could definitely be made with existing grommet components.  For example, a Rich Text Editor toolbar could easily be made with a combination of icons, Boxes and a Menu perhaps.  

I was actually just talking the other day about how this would be a fantastic feature for the [Grommet-cms](https://github.com/grommet/grommet-cms-boilerplate) project.  We might eventually develop a Rich Text Editor for this project, so I'll definitely share it when we do.

**Comment by nomadus** [comment]
@RyanCCollins, Hi, thanks for the pointers. What would be a good starting point for this project? Should this be based on an existing tool, such as draft-js? Or would this be a completely new component?

**Comment by RyanCCollins** [comment]
Hey @nomadus 

I've used Draft-JS with Grommet before and it was a great experience.  You can see the sourcecode for that project [here](https://github.com/udacityalumni/udacity-alumni-fe/blob/master/app/src/components/CmsEditor/index.js#L21).

In the case of the grommet-cms, I believe we plan to make a draft-js-like toolbar from scratch.  We haven't gotten to that point yet, however, and are waiting on some design feedback.  I'll definitely share some code and screenshots when we get to working on it.

**Comment by alansouzati** [comment]
thanks @RyanCCollins I agree with you. this would definitely be a component/feature to live outside grommet core.

I'm closing the issue for now. but feel free to keep the discussion going here.

**Comment by RyanCCollins** [comment]
Hey @nomadus, I have been toying with this idea over the weekend.  

I would love to have a rich text editor that we could use in the grommet-cms.  I think before I go past the protyping stage, I would like to get designs of this and I have no clue when that will be possible.

If you are interested in seeing the progress, there is a [repo here](https://github.com/RyanCCollins/grommet-rte/blob/master/src/components/Editor/index.js).  No promises that anything will come of this, but I'd still like to explore it and would welcome any contributions.

**Comment by nomadus** [comment]
Thanks Ryan, that was quick!:) I surely look at it and send my feedbacks
