### ISSUE TITLE
Tab expects label to be a string

### ISSUE THREAD

**Issue by sorin-davidoi** [grommet/grommet#1199]
`Tab` throws errors in development when label is a React element.

### Expected Behavior

It should not throw any errors.

### Actual Behavior

It complains that label is not a string.

### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/anon/pen/RKmvaO?editors=0011

### Steps to Reproduce
 1. Open Codepen
 2. Open console
 3. Observe error

**Comment by sorin-davidoi** [comment]
I want to localize the string using the `react-intl` library (e.g. pass `<FormattedMessage {...messages.tabname} />`).

**Comment by ericsoderberghp** [comment]
Fixed in 3c0d4b0de91bfd0e35e80981242be7c201d9d5a7
