### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of null in Article Component

### ISSUE THREAD

**Issue by mvanlonden** [grommet/grommet#1201]
https://github.com/grommet/grommet/blob/09589df5b119e4db53d95f91f8288de62dedc072/src/js/components/Article.js#L177

### Expected Behavior

Error should not appear in console. Not sure if effecting the UI

### URL, screen shot, or Codepen exhibiting the issue
![Debugging Screenshot](https://puu.sh/udD9a/d06266ec1b.png)
![Stack Trace](https://puu.sh/udG1N/6649e1fba8.png)
Notice how the children in the scope pan (on right) have null ref.

### Steps to Reproduce
 1. Create article component with stateless children (ie no ref)
 2. Scale down viewport to mobile size
 3. Scroll and errors should appear

### Your Environment

* Grommet version: 1.2.1
* Browser Name and version: Chrome 56.0.2924.87
* Operating System and version (desktop or mobile): OSX 10.11.6 Desktop

**Comment by mvanlonden** [comment]
Thank you!

**Comment by breakds** [comment]
I am seeing the same issue in 1.3.2. Is this fix included in it? Thanks!
