### ISSUE TITLE
Search is not using updated value

### ISSUE THREAD

**Issue by Catx7** [grommet/grommet#1203]
Hello,

The problem appear in every browser usint last grommet update.
I use: 
`import Search from 'grommet/components/Search';`
`<Search
              defaultValue={searchValue}
              fill={true}
              inline={true}
              placeHolder={searchInputPlaceholder}
              onDOMChange={searchHandler}
            />`
The searchValue is updated by store or by user input.
If the searchValue is updated by store in the UI SearchBar doesn`t update according searchValue.

Search component is contained by Container A.If container A is mounting ,Seach updated the value acording seachValue ,but if Container A just render ,the Seach is not updating the UI.

PS :If I do not use inline={true} it works fine.

**Comment by ericsoderberghp** [comment]
I think you need to use `value` and not `defaultValue`. Can you try that?

**Comment by gmeans** [comment]
@ericsoderberghp I came here due to the same reason. It doesn't appear to work on the docs examples either.

https://grommet.github.io/docs/search/examples?placeHolder=true&suggestions=true

**Comment by Catx7** [comment]
@ericsoderberghp  I tried ,but nothing good happends.

**Comment by ericsoderberghp** [comment]
We've enhanced the documentation to update the value from the selected suggestion.

**Comment by Catx7** [comment]
I will be available in the next grommet release?
