### ISSUE TITLE
Checkbox component does not expose an ID prop

### ISSUE THREAD

**Issue by Enaitz** [grommet/grommet#1204]
Checkbox component does not expose an ID prop. Can checkbox expose a property to give it an id? so that testing tools can target it with easy.

(*Radio buttons have this functionality)

### Expected Behavior

A custom ID should be able to be rendered

### Actual Behavior

No custom ID can be rendered

**Comment by ericsoderberghp** [comment]
If given an `id`, CheckBox will transfer this to the underlying input DOM element. We didn't document it because the `label` is not required in CheckBox where it is on RadioButton. I am adding it to the propTypes though, since we do reference it if a label is specified.

**Comment by Enaitz** [comment]
thanks, closing
