### ISSUE TITLE
Hover on Distribution charts hides the text in a tile. Also, sometime all the tiles are in hover state.

### ISSUE THREAD

**Issue by ishwark7** [grommet/grommet#1206]
1.When one hovers over a distribution chart, the tile expands to show complete text. In some cases, the tile is expanded behind the neighboring tile. 
 2. All tiles in distribution chart are sometimes in expanded(hover) state

### Expected Behavior

Text should be properly visible on hover and not get expanded behind some tile.
The tiles should not be in hover state always.

### Screen shot
![1](https://cloud.githubusercontent.com/assets/24618233/23294393/323e5372-fa91-11e6-947a-d6aae3a9d402.PNG)
![2](https://cloud.githubusercontent.com/assets/24618233/23294439/79bd25c0-fa91-11e6-8ab8-f037bb3db3dd.PNG)

**Comment by alansouzati** [comment]
I was able to validate this issue in Grommet.io. I'm reopening so that I can investigate it.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/fc6f5a2a5dfa168a121106b3b2d977b63c374f73
