### ISSUE TITLE
Menu content remains visible and floating on the page

### ISSUE THREAD

**Issue by baladr** [grommet/grommet#1208]
**Expected Behavior**
Menu content should remain attached to menu.

**Actual Behavior**
The problem is reproducible in every browser using grommet 1.2.1.
I use Menu with the following props:
`<Menu icon={<FilterIcon />}
          title="Filter by"
          inline={false}
          responsive={true}
          closeOnClick={true} dropAlign={{"right": "right"}}>`

Changing the filter value is causing the page to re-render and the page size might be modified (ex. width) and if the Menu is open when the page size changed then its content remains visible and floating on the page separately from the menu button when page scroll is available.

**Screen shot**

![floatingmenu](https://cloud.githubusercontent.com/assets/26006957/23307413/22ab238a-fab0-11e6-9ef1-3d528d2be3f2.PNG)

**Comment by dioklecijan** [comment]
Here is a problem demonstration: http://codepen.io/gimei/pen/ryVYEz

**Comment by tracybarmore** [comment]
Linking with #981
