### ISSUE TITLE
[Ipad Mini] Issues in charts and their axis

### ISSUE THREAD

**Issue by ishwark7** [grommet/grommet#1213]
There are issues in graphs in Ipad Mini:
1. Range chart
2. Distribution chart
3. Bar chart

### Expected Behavior

The graphs should behave normally on Ipad mini

### Actual Behavior

1. The X-axis in range chart, changes to vertical layout. Graph is also split in 2 lines
2. Distribution chart is skewed
3. The X-axis in bar chart, changes to vertical layout. The Y-axis is above the chart. (Refer screeshot)

### Screen shots exhibiting the issue
1. Range chart issue
![capture](https://cloud.githubusercontent.com/assets/24618233/23361128/13f08b20-fd15-11e6-9d39-1ec99fe44259.PNG)

2. Distribution chart skewed
![distributions-chart-skewed](https://cloud.githubusercontent.com/assets/24618233/23361033/91a627ba-fd14-11e6-9d8c-36e3263b0f01.jpg)

3. Bar chart issue
Y-axis:
![bar-chart-y-axis](https://cloud.githubusercontent.com/assets/24618233/23361061/b788b272-fd14-11e6-9cac-e5a37b722acf.jpg)

X-axis:
![2](https://cloud.githubusercontent.com/assets/24618233/23361160/40a47b18-fd15-11e6-8951-54ac7ec438f9.PNG)

Thanks,
Ishwar

**Comment by tracybarmore** [comment]
Hey @ishwark7, thanks for raising the issue. Can you specify which version of iOS you're currently using? Thanks!

**Comment by ishwark7** [comment]
iOS version we are using is 8.4
Thanks.

**Comment by ericsoderberghp** [comment]
We've updated the Grommet browser support page to clarify that iOS < 9.3 is not supported. https://grommet.github.io/docs/browser-support/
