### ISSUE TITLE
Hero banner in docs apparently broken

### ISSUE THREAD

**Issue by arabold** [grommet/grommet#1214]
When going through the latest docs I've noticed rendering errors for the Hero banner documentation here: https://grommet.github.io/docs/hero

Here's a screenshot with narrow screen:
![image](https://cloud.githubusercontent.com/assets/1548229/23366414/7d053ff2-fcbb-11e6-856e-8a660e9f4ae1.png)

With a wider screen the "Sample Heading" text doesn't even show up.

The "Examples" on that page do not work properly either. A few weeks ago (maybe 3?) this was still working as expected.

### Steps to Reproduce
This issue is visible on the official docs page: https://grommet.github.io/docs/hero

### Your Environment
* Browser Name and version: Chrome 56.0.2924.87
* Operating System and version: Mac OSX

**Comment by martinezguillaume** [comment]
Any workaround for this issue ? I tried to implement it on my project but I've the same rendering...
