### ISSUE TITLE
Login form width vs. button width differ

### ISSUE THREAD

**Issue by hdehal** [grommet/grommet#1215]
Login form width vs. button width differ (see screenshot):
<img width="637" alt="screen shot 2017-02-27 at 2 33 50 pm" src="https://cloud.githubusercontent.com/assets/21130143/23383153/e6c73c04-fcf9-11e6-9375-6a656218bda4.png">

### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/docs/login-form

### Your Environment
Mac OS X && Firefox

**Comment by tracybarmore** [comment]
Validated in Firefox. Thanks for raising this issue!

**Comment by dgennetten** [comment]
This issue seems to be gone with current OS & browser versions.
