### ISSUE TITLE
Menu component label prop

### ISSUE THREAD

**Issue by dioklecijan** [grommet/grommet#1217]
It looks that menu label prop is required and cannot be an empty string when using together with the icon prop:

These menus are not rendered:
`<Menu icon={<Actions />} >`
`<Menu icon={<Actions />} label="">`
`<Menu icon={<Actions /> inline={false} >`

while these are rendered correctly:
`<Menu icon={<Actions />} label=" ">`
`<Menu inline={false}>`

CodePen playground: https://codepen.io/gimei/pen/oZjKKO?editors=0010

### Your Environment

* Grommet version: 1.2
* Browser Name and version: Chrome,  56.0.2924.87 (64-bit)
* Operating System and version (desktop or mobile): MacOs 10.12.3

**Comment by ericsoderberghp** [comment]
I think the issue here is that the base icons aren't working in CodePen. We need to fix that.

**Comment by alansouzati** [comment]
@ericsoderberghp is right. We recently changed the minified js structure to have a better webpack2 support.

the base icons are now available as: `BaseIcons.ActionsIcon`  where BaseIcons is being read from `Grommet.Icons.Base`, the base object will have the icon name and the `Icon` suffix. I've fixed your codepen to reflect that.

https://codepen.io/alansouzati/pen/OpWXKR?editors=0010
