### ISSUE TITLE
Basis not working on IE11 when using separator on BOX or TILE

### ISSUE THREAD

**Issue by MarcoMedrano** [grommet/grommet#1218]
When adding a separator on a Box or Tile it is adding its separator size on IE which makes fail the basis.

### Expected Behavior
The 3 boxes should appear in a line as here (firefox):
![image](https://cloud.githubusercontent.com/assets/2736856/23522414/44be8be4-ff59-11e6-85fc-8b63e0863e0a.png)

### Actual Behavior
The last box gets down due separator added (IE11).
![image](https://cloud.githubusercontent.com/assets/2736856/23522460/717d6ca4-ff59-11e6-95cf-276cd846c65f.png)

### Codepen
http://codepen.io/MarcoMedrano/pen/oZxxVN?editors=0010

### Your Environment
* Grommet version: 1.2.1
* Browser Name and version: IE 11.713.10586
* Operating System and version (desktop or mobile):Win10

**Comment by alansouzati** [comment]
Good catch. Fixed by https://github.com/grommet/grommet/commit/a22243785532b5ca0e43915c761d88bce0ae911b

**Comment by alansouzati** [comment]
The fix for this broke other items. I'm reopening this and will investigate another solution.

**Comment by alansouzati** [comment]
Fixed again in https://github.com/grommet/grommet/commit/3de2781c849512235b5b65df549aa5974d82065b

Sorry about the back and forth

**Comment by MarcoMedrano** [comment]
Glad to know it is fixed!
