### ISSUE TITLE
Spinner rendering issue

### ISSUE THREAD

**Issue by daconcei472** [grommet/grommet#1219]
I created a grommet sample app using the grommet-cli, and added a spinner to the page. It's not rendering in the same way as in the current demo pages. 
### Expected Behavior

The spinner should be an uninterrupted circle with a smooth animation

### Actual Behavior
The animation is slow, and it's a circle with 4 separate parts instead of a single line. Each of the 4 white portions will slowly change to a black portion.

### URL, screen shot, or Codepen exhibiting the issue
<img width="38" alt="screen shot 2017-03-03 at 9 39 00 am" src="https://cloud.githubusercontent.com/assets/9203187/23555134/b6fe6c0a-fff5-11e6-8d7f-54639c4002da.png">

### Steps to Reproduce
 1.  Create a sample app with grommet-cli
2.  Add a `<Spinning />` element to any page

### Your Environment

* Grommet version: 1.2.1
* Browser Name and version: Chrome  56.0.2924.87, Firefox 51.0.1 
* Operating System and version (desktop or mobile): Mac OS 10.12.2

**Comment by ericsoderberghp** [comment]
The new Spinning component styling is currently available only on the #stable version of Grommet. We will likely be releasing a 1.2.2 version coming up though.
