### ISSUE TITLE
Re-sizing the DateTimeDrop component throws an unhandled exception

### ISSUE THREAD

**Issue by cherih** [grommet/grommet#1221]
### Expected Behavior
The browser console shouldn't have unhandled exceptions due to re-sizing components.

### Actual Behavior
Re-sizing the DateTimeDrop component generates uncaught TypeError exceptions.

### URL, screen shot, or Codepen exhibiting the issue
![datetimedrop-typeerror-exception](https://cloud.githubusercontent.com/assets/25066338/23564378/73c56bd4-0007-11e7-8115-234450f2a941.PNG)

### Steps to Reproduce
 1. Use the DateTime component in a page
 2. Browse to the page and click on the icon in the component to cause the calendar dropdown to be displayed.
 3. Re-size the page
4. Open the browser console using F12 and go to the Console tab

NOTE - I first noticed this in the grommet.io components area while playing around with the DateTime component there.

### Your Environment
* Grommet version: 2.2.0
* Browser Name and version: Chrome 56.0.2924.87
* Operating System and version (desktop or mobile): Windows 7 Enterprise SP1

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/016abd4adae01a90d85c7de744ce38e36db8a60c
