### ISSUE TITLE
Timestamp not working properly in IE and Edge

### ISSUE THREAD

**Issue by dgennetten** [grommet/grommet#1224]
### Expected Behavior

fields='minute' and fields='second' should produce 2-digit results
### Actual Behavior

fields='minute' and fields='second' both act as if fields is unset
### Steps to Reproduce
 1.  In IE/Edge go to https://grommet.github.io/docs/timestamp/examples?fields=minute
 2.  Observe full date/time rather than 2-digit minute
 3.  Switch to seconds and observer the same.

### Your Environment

* Grommet version:
* Browser Name and version:  IE 11.0.15046/Edge 40.15046
* Operating System and version (desktop or mobile): Win10

**Comment by tracybarmore** [comment]
Validated issue on Browser Stack Edge 15.
