### ISSUE TITLE
Production build propTypes question

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#1225]
How come this work for grommet in production build? 
```
const restProps = Props.omit(this.props, Object.keys(Icon.propTypes));
```
I guess grommet build does not remove propTypes.

Normally propTypes are removed in production when using babel - react-optimize presset. I noticed this when I made one custom icon using grommet template. What is the opinion on this?
Cheers

**Comment by alansouzati** [comment]
Yeah, currently we are not removing propTypes in production and you have a fair point, we need to evaluate this as keeping propTypes could lead to bigger bundles.

I don't have a fix in mind for this yet as we need to prune down the list of properties to pass down to child components. Do you have a suggestion?

**Comment by primozs** [comment]
@alansouzati I was trying couple of things but did not found good solution. I was thinking you might have some good idea. Currently not removing the propTypes in Grommet seams like the best one. But in my app code I don't have to do it like this.

**Comment by alansouzati** [comment]
Yeah, I don't think it is a big problem to leave a library with documentation for their documents in the production build. The grommet docs site will have to leave the propTypes in, but all the other sites I guess it is safe to remove it.

I'm closing to close the issue for now. We can always revisit it if we find a good fix for it, thanks for bringing this up.
