### ISSUE TITLE
MultiSelect: Make selected items visible only when selected

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet#1226]
Currently, the way the multiselect component works is not convenient. In case inline=false (default) a user has to click the arrow icon to see what specific items have been selected.
In case inline=true, the list of items is shown on the page, but when the list is big this may clutter the page.
### Expected Behavior

Ideally, it should show the selected items inline as anchors or buttons to see the selected items immediately and with the ability to remove items.
![image](https://cloud.githubusercontent.com/assets/3382143/23703147/a19a0e3c-0428-11e7-9c67-95bd455a0a3f.png)

### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/docs/select/examples?placeHolder=true&multiple=true

### Steps to Reproduce
 1.  Go to https://grommet.github.io/docs/select/examples?placeHolder=true&multiple=true
 2.  Play with inline and multiple attributes
 
### Your Environment

* Grommet version: current
* Browser Name and version: Any browsers
* Operating System and version (desktop or mobile): Windows 10

**Comment by L0ZZI** [comment]
Thanks for sharing! I wouldn't classify this as an issue, it's more of an enhancement or a new component as the existing menu component functions as intended. The enhancement you're asking for will run into issues as well when trying to show many selected items within the field,  masking multiple values or having to grow the size of the field. Either way there will be a cost to enhancing the design. 

If you could provide more context on the scenarios you're trying to support, tags, facets, etc please let us know what you're looking to achieve. We're happy to investigate and work with you.

**Comment by nomadus** [comment]
Hi,
Indeed this came out when I tried to add a tag cloud feature into the page. As of now to see the selected options 
1) one has to click the down arrow and the selected items are highlighted in different color 
2) or when using inline=true option, all the items are shown below with check boxes.

From visualization point of view, #1 is not acceptable for me as when it comes long lists, the user has to scroll all the way down to see that a particular item is selected or not.

The second one is better, as it visually more appealing, but when it comes to long lists it clutters the page and this single component could take a substantial amount of the page.

The enhancement allows to make the pages more compact and more visually appealing as it shows the selected items only, hiding the remaining items. In case the a person is selected a big number of items, this could be considered as an exceptional case. Usually only a few items are selected.

**Comment by mturley** [comment]
I'd like to add my +1 to this issue, currently the multi-select functionality of Select is a little crippled by the fact that it just displays "3 values" and you can't see which values without clicking and scrolling.  At a minimum, it would be nice if we could pass a custom function to render our own summary string instead of the "3 values".

To meet my needs for now, I'm using my own <Menu> with a <Select inline> inside it, so I can use the Menu's label property for this summary.  However this is presenting issues, so I may end up just directly using a <Search> and some <CheckBox>es inside my <Menu>, but I feel like I'm implementing my own <Select> unnecessarily.

For context, I'm trying to create a basic facets use case as part of a filter control.

**Comment by mturley** [comment]
For reference, I considered using something like this instead and just styling it to look like Grommet: http://jedwatson.github.io/react-select/.

**Comment by nomadus** [comment]
This is another critical feature which affects our projects. Currently, we have a big list of lookup items and showing them on page (inline=true) will take all the page, which is not good from UX point of view. But in case of inline=false, this also does not give better UX experience as user has to lookup to see which options are selected.

Could you please prioritize this issue as well? Thanks in advance!

**Comment by eoliphan** [comment]
+1 for this, was just about to add this myself.  As people have pointed out, there's probably no one good solution (e.g. tag cloud is great, up to a point), but perhaps a 'selectDisplay' or something option will allow this to be handled more flexibly.  
```
selectDisplay: default;
...
selectDisplay: tagCloud;

```

**Comment by alansouzati** [comment]
Please check this codepen where I show a recommendation of multi-select for a big list of items:

https://codepen.io/alansouzati/pen/GErJNm

**Comment by karatechops** [comment]
Awesome approach @alansouzati! I'll tag Select's 2.0 card ( #1484 ) but I think functionality like this would be better suited in grommet-addons.
