### ISSUE TITLE
Meter component threshold line is cropped on small resolution

### ISSUE THREAD

**Issue by mjasnikovs** [grommet/grommet#1227]
Meter component threshold line is cropped on small device resolution

Image, from google chrome, it looks same on actual Android device.

![capture](https://cloud.githubusercontent.com/assets/12757881/23752846/a1328598-04df-11e7-960a-94c9286b40c0.PNG)

You can replicate same issue if you take a look [here](https://grommet.github.io/docs/meter/examples?type=arc&threshold=true&size=small&i-value=true). 
If you look closely with Google Chrome mobile view. Arc threshold is cropped. 

It appears that issue is only with size="small"

**Comment by dgennetten** [comment]
As I'm looking into the source of this issue, I'm becoming aware that this needs to also include #1216

**Comment by dgennetten** [comment]
@JetLim did you have a chance to chat with @ericsoderberghp about this?
