### ISSUE TITLE
[BUG] Number-Input alpha characters

### ISSUE THREAD

**Issue by Catx7** [grommet/grommet#1228]
https://grommet.github.io/docs/number-input

Number input allows alphanumeric typing on Mozilla and IE.

On Chrome user can introduce only numeric characters.

The behaviour from chrome should be on Mozilla ad IE too.

**Comment by ericsoderberghp** [comment]
Grommet just uses the underlying browser's `<input type="number" />` element. We've tended to keep our changes to core elements like this tied as closely to the browser behavior as possible and only wrapping them to allow restyling a bit.

But, contemplating if this  warrants an exception to that approach.

**Comment by Catx7** [comment]
You are right problem is regarding Firefox .
close.
