### ISSUE TITLE
Internet Explorer 11: Range bar slider buttons are misaligned in the chart

### ISSUE THREAD

**Issue by ishwark7** [grommet/grommet#1233]
In IE11, slider buttons in range bar do not lie between the lines, but are a bit below the actual chart
Refer screenshot for better idea.

### Expected Behavior

The slider buttons should behave same way as in other browsers:Chrome/Firefox

### Actual Behavior

The buttons appear to be misaligned

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/ishwark7/pen/ZeEVEx

1. Slider buttons misalinged in IE
![ie-11](https://cloud.githubusercontent.com/assets/24618233/23788923/b976c37a-059e-11e7-88cf-82a065d8a23a.PNG)

2. Slider buttons properly aligned in Chrome
![chrome](https://cloud.githubusercontent.com/assets/24618233/23788924/b977ac36-059e-11e7-8c05-e25434d3f3ab.PNG)

Thanks,
Ishwar

**Comment by ericsoderberghp** [comment]
There is also a problem on Firefox at https://grommet.github.io/hpe/docs/chart/examples?height=xxsmall&i-Axis-time=false&i-Axis-value=false&i-Grid=false&i-Area=false&i-Line=false&i-Bar=true&i-Marker=false&i-HotSpots=false&i-Range=true.
