### ISSUE TITLE
Distribution in a Box gets NaN in render method

### ISSUE THREAD

**Issue by ablx** [grommet/grommet#1237]
If you put a Distribution in a Box (**with align='center'**), the render method throws an error:
```Warning: `NaN` is an invalid value for the `maxHeight` css style property. Check the render method of `Distribution`.``` and the Distribution is very small

### Expected Behavior
The Distribution should be layouted correctly in the Box / better error message if this behaviour is intended.

### Actual Behavior
It's to small

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/ablx/pen/zZzRdX

### Your Environment

* Grommet version: 1.2.1
* Browser Name and version: Firefox, latest
* Operating System and version (desktop or mobile): OSX El Capitan

**Comment by alansouzati** [comment]
Thanks for reporting this. Fixed in https://github.com/grommet/grommet/commit/6e35a69df7df5dfed03f2647fd9eca635130c98e
