### ISSUE TITLE
NumberInput controlled to uncontrolled

### ISSUE THREAD

**Issue by john-codeworx** [grommet/grommet#1241]
When setting the value of a NumberInput to a state variable, a warning is displayed in the conosle when updating the value of the control.

### Expected Behavior
No warning

### Actual Behavior
getting 
```
Warning: NumberInput is changing a controlled input of type number to be uncontrolled. Input elements should not switch from controlled to uncontrolled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.
```

### URL, screen shot, or Codepen exhibiting the issue

Codepen: https://codepen.io/john_codeworx/pen/wJrxve

**Comment by alansouzati** [comment]
You should use `e.target.value` instead of `e.value`
