### ISSUE TITLE
Error on Anchor component

### ISSUE THREAD

**Issue by shai32** [grommet/grommet#1246]
Getting an error when using Anchor, after updating react-router to version 4

### Expected Behavior
The Anchor should work and displayed on screen

### Actual Behavior
getting a console error after updating react-router to version 4:
Uncaught TypeError: router.isActive is not a function
    at new Anchor (Anchor.js:59)
all the component crashes and noting shown on screen

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/16700996/24076777/1d0c8d12-0c42-11e7-9359-f7a198a3a295.png)

### Steps to Reproduce
 1. integrate grommet with react-router-dom version 4
 2. add a page that contain Anchor component
 3. open browser and you will see an error on console

### Your Environment

* Grommet version: 1.3.1
* Browser Name and version: chorme 56
* Operating System and version (desktop or mobile): desktop mac 10.12.3

**Comment by alansouzati** [comment]
Thanks for bringing this up. Grommet does not support React router 4 yet. We should definitely look into this.

**Comment by alansouzati** [comment]
I spent a good amount of my day today trying to add support for React Router v4. It was somehow a frustrating experience. I really wanted to make that available in Grommet 1.3.2 but there is not much out there yet in terms of migrating from v3 to v4.

I was hoping it would be a simpler change, but it is not that simple.

Please see this issue I've created with react-router to understand better the reason why I'm postponing the support of react router v4:

https://github.com/ReactTraining/react-router/issues/4793

**Comment by alansouzati** [comment]
The support for react router v4 has been initially added in: https://github.com/grommet/grommet/commit/74ee5fe625e7777d30d6c49098b72863a4dfd1a6

It is supposed to be fully backwards compatible. Can you test it using grommet stable branch?

It would be a good idea if you could validate it works well before we release. I tested with a few apps but I would need more time to test with others.

If you don't know what is the grommet stable branch please refer to: 

https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F

Please wait this CI to pass before trying:

https://travis-ci.org/grommet/grommet/builds/213287572

**Comment by shai32** [comment]
I tested it and I confirm it works

**Comment by shai32** [comment]
will it be release in 1.3.3?

**Comment by alansouzati** [comment]
1.3.3 released with this fix in it 👍
