### ISSUE TITLE
Selectable tiles with colorIndex do not display as selected until first component update

### ISSUE THREAD

**Issue by ezzatron** [grommet/grommet#1250]
### Expected Behavior

When supplying a set of indices to a `Tiles` component's `selected` property, the selected tiles should display with a background color indicating their selected status. If a child `Tile` component has a background color set via its `colorIndex` property, this should not affect the display of selected tiles.

### Actual Behavior

When supplying a set of indices to a `Tiles` component's `selected` property, selected tiles will, initially, not display the correct background color if the child `Tile` component has a background color set via its `colorIndex` property.

To be more specific; for a very brief moment, the child `Tile` elements will have the CSS class `grommetux-tile--selected`. Then, something that seems to be external to the `Tiles`/`Tile` component causes a React update, which removes the `grommetux-tile--selected` class from selected tiles with a `colorIndex` set. After this point, attempting to select a tile will cause another update, and the selected tiles will display correctly again.

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/ezzatron/pen/gmvKBE

<img width="986" alt="screen shot 2017-03-21 at 7 50 31 am" src="https://cloud.githubusercontent.com/assets/100152/24123567/c2b4eaaa-0e0b-11e7-82e0-6744ed25ce85.png">

### Steps to Reproduce
 1. Go to https://codepen.io/ezzatron/pen/gmvKBE
 2. Look at the incorrect display of selected tiles
 3. Click a tile
 4. Look at the correct display of selected tiles

### Your Environment

* Grommet version: stable
* Browser Name and version: Chrome/Firefox/Safari latest
* Operating System and version (desktop or mobile): Mac OS Sierra (10.12.3)

**Comment by ezzatron** [comment]
@john-codeworx FYI

**Comment by cherih** [comment]
Was able to reproduce this problem in my sandbox. Will work on debugging it.

**Comment by ezzatron** [comment]
Thanks for the fix ❤️
