### ISSUE TITLE
Full Article with List Items onClick scroll issue

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet#1252]
Since the grommet 1.3 release, a Full Article with selectable children (list or box) has an event handler issue where the article will hijack clicks and scroll the view to the top of the article.

### Expected Behavior
The list should not scroll after clicking a list item

### Actual Behavior
The list scrolls to the top of the page

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/ryancollins/pen/NpyewM
![gif](http://recordit.co/8Y6mRLCUHM.gif)

### Steps to Reproduce
 1. Open the code pen 
 2. Click a list item
 3. Watch the screen scroll up

### Your Environment

* Grommet version: Latest
* Browser Name and version: Any Browser (Tested in Chrome / Safari)
* Operating System and version (desktop or mobile): Desktop

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/2cb231b2d64464d7ef8641ca5365bb580c674b81

I've removed focus call to select an element. this seems wrong to me.
