### ISSUE TITLE
Anchor animateIcon ambiguity

### ISSUE THREAD

**Issue by jozsi** [grommet/grommet#1255]
The `animateIcon` prop of the `Anchor` component is working ambiguously.

### Expected Behavior
When set to `false`, I would expect no animation to happen.

### Actual Behavior
When set to `false`, it's still animating - only difference is the animation type.

### URL, screen shot, or Codepen exhibiting the issue
Codepen: http://codepen.io/anon/pen/rydjMG

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/7fee701ff457bb91692e898100e4410ef5432b50

It will be soon part of Grommet 1.3.3
