### ISSUE TITLE
Focus issue on Menu with Icon

### ISSUE THREAD

**Issue by arjunbm468** [grommet/grommet#1256]
We are migrating our project from Grommet v0.6.9 to v1.3.3

As part of this migration we found out that the focus event on Menu with icon does not show up.
It is hard to differentiate between header layout and the menu space.

### Expected Behavior

Focus event should show up green colored border
### Actual Behavior

Focus event does not show up green colored border
### URL, screen shot, or Codepen exhibiting the issue
With v0.6.9
![capture](https://cloud.githubusercontent.com/assets/18460656/24185594/fa938276-0ef9-11e7-9b04-868d364d16ff.PNG)
![menu](https://cloud.githubusercontent.com/assets/18460656/24034210/745cc2c6-0b16-11e7-831c-ae5b94ddc50f.png)

With v1.3.3
![capture1](https://cloud.githubusercontent.com/assets/18460656/24185636/363a6e20-0efa-11e7-9b0c-662f9ca0dd2e.PNG)
![capture3](https://cloud.githubusercontent.com/assets/18460656/24185885/816a7240-0efb-11e7-804f-d87e25071d93.PNG)

http://codepen.io/arjunbm/pen/JWOpZm?editors=0010
### Steps to Reproduce
 1. Visit the code pen.
 2.  Click on right top menu icon.
 3.  Observer the focus-in and focus-out events when the Menu is in closed and open state

### Your Environment

* Grommet version: v1.3.3
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile):desktop

**Comment by arjunbm468** [comment]
@alansouzati @ericsoderberghp 
Any thoughts on this issue...?

**Comment by arjunbm468** [comment]
@alansouzati @ericsoderberghp 
Do you feel this as an issue or is the design as expected?

**Comment by alansouzati** [comment]
I'm going to take a look on this issue soon. Sorry that this it is taking a long time.

**Comment by L0ZZI** [comment]
@alansouzati did we get a chance to look at this?
