### ISSUE TITLE
Font issue on plain anchor hovers inside Sidebar component

### ISSUE THREAD

**Issue by arjunbm468** [grommet/grommet#1257]
We are migrating our project from Grommet v0.6.9 to v1.3.3

As part of this migration we found out that the plain **a** tag hover styling is broken inside the sidebar component.

### Expected Behavior

Hover on anchor tag should display white color font. 
### Actual Behavior

Hover on anchor tag is displaying black color font. 
### URL, screen shot, or Codepen exhibiting the issue
![notifications](https://cloud.githubusercontent.com/assets/18460656/24034235/8eb8f414-0b16-11e7-8be0-8dafdd100c52.png)

http://codepen.io/arjunbm/pen/JWOpZm?editors=0010

### Steps to Reproduce
 1. Visit the codepen.
 2. Mouse hover on the **a** tag inside the sidebar component.
 3. Observe the hover styling. 

### Your Environment

* Grommet version: v1.3.3
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): desktop

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/1874cde5a9f7db741afd9c76fea22369c77a827d
