### ISSUE TITLE
Using Anchor in React Router 4 app require 'path' to be set.

### ISSUE THREAD

**Issue by okada** [grommet/grommet#1258]
### Expected Behavior
Using Anchor in React Router 4 app require that 'path' is set. If only 'onClick' is set, an error 'cannot access path of undefined' occurs (it tries to access path.path).

Setting path='' works.

### Actual Behavior
Should be possible to set only 'onClick'.

**Comment by zacksinclair** [comment]
Happened to come across this post and thought I'd mention - Grommet's Anchor component is incompatible with react router 4 for more reasons than just the onclick / path issue you described. 

The anchor component looks for router.isActive, which in react router 4 has been moved off of the router object and onto NavLink. I imagine there are other compatibility issues, too, but that's effectively breaking.

A workaround is roughly:

`
import { NavLink } from 'react-router-dom'
<NavLink
    className='grommetux-anchor'
    activeClassName="grommetux-anchor--active"
    to='/'
>
    Link example
</NavLink>
`

Note grommet's current package.json:  `"react-router": "2 - 3"`

**Comment by okada** [comment]
Hello zacksinclair

Thanks for caring to reply,

Actually the super fresh Grommet 1.3.3 implemented support for React Router
4 (backward compatible).

Best regards

**Comment by alansouzati** [comment]
yeah I added support for 4.0, but I guess it did not do a good job testing it with the entire Anchor combination. I'm working on that now. Sorry folks...

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/7d785d4d18f2f62bd4eab1dae9f25bef02f99392

**Comment by zacksinclair** [comment]
@okada gotcha, I might just have to swap from the release branch to 1.3.3, thanks for pointing it out

@alansouzati thank you for this library, it really is excellent.  while we're on a thread... i noticed the docs for Box don't mention that it has a margin prop that effectively matches pad, just fyi

**Comment by alansouzati** [comment]
good catch @zacksinclair can you file an issue against https://github.com/grommet/grommet-docs ?

this is an easy one to fix, so I would really appreciate if you can send a pull request for that.

There is where the BoxDoc component is: https://github.com/grommet/grommet-docs/blob/master/src/docs/components/box/BoxDoc.js#L35
