### ISSUE TITLE
Meter component expands outside the boundaries of the parent

### ISSUE THREAD

**Issue by tafelito** [grommet/grommet#1261]
When using a Meter component as the description of a Card component the meter expands outside the card boundaries

![image](https://cloud.githubusercontent.com/assets/5973652/24211974/2a6239d4-0f04-11e7-9bc4-4636cb52eedc.png)

You can reproduce it here
http://codepen.io/tafelito/pen/BWxoQX

**Comment by alansouzati** [comment]
Thanks for providing the codepen for this. It definitely helps us triage the problem

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/0cf51bbecd50603a89dcea98db1415c048604953
