### ISSUE TITLE
SunBurst throwing "Warning: flattenChildren(...): Encountered two children with the same key" when identical child values used

### ISSUE THREAD

**Issue by mamboitaliano** [grommet/grommet#1264]
SunBurst causes React to throw the following error: 
`Warning: flattenChildren(...): Encountered two children with the same key, `22.743055555555554100`. Child keys must be unique; when two children share a key, only the first child will be used.
    in g (created by SunBurst)
    in svg (created by SunBurst)
    in div (created by SunBurst)
    in SunBurst (created by EditProfileView)...`

As far as I can tell, this occurs when more than one sub node have identical `value`s. For instance, in Chrome this will produce the error pasted above. 
http://codepen.io/anon/pen/WpJZaW?editors=0010

![screen shot 2017-03-22 at 8 15 26 pm](https://cloud.githubusercontent.com/assets/11069047/24230818/4cd133f0-0f3e-11e7-8472-7cdf4ba1ffc2.png)

I suspect the `key` that react is talking about is defined in SunBurst.js between lines 304 and 309
`{ key: '' + radius + total, role: role || 'rowgroup',
          'aria-label': value || total },`

Not sure if I'm missing something or if I'm misunderstanding how the SunBurst works :/ I'm using Grommet 1.2.1 at the moment but I tried the same thing on 1.3.4 on a different branch but no luck. Would love to get this working, feel free to let me know how I can assist. Thanks!

### Your Environment

* Grommet version: ^1.2.1
* Browser Name and version: Chrome Version 56.0.2924.87 (64-bit)
* Operating System and version (desktop or mobile): OS X 10.10.5

**Comment by alansouzati** [comment]
Thanks for reporting this. Fixed in https://github.com/grommet/grommet/commit/53338188789e00d32ce9621331aa855c05f9447d
