### ISSUE TITLE
Toast reopening

### ISSUE THREAD

**Issue by oakmad** [grommet/grommet#1265]
For some reason my toasts are reopening after the close animation. They animate closed as expected but then jump back to being visible again but still have the --closing class. Theres also no close link showing.

I've reproduced it in this codpen [http://codepen.io/anon/pen/ZeoMdV?&editors=0010](http://codepen.io/anon/pen/ZeoMdV?&editors=0010)

Heres the rendered code I'm seeing.

```
<div class="grommetux-toast__container">
  <div data-reactroot="" class="grommetux-toast grommetux-toast--closing">
    <svg class="grommetux-status-icon grommetux-status-icon-ok grommetux-toast__status" viewBox="0 0 24 24" role="img" aria-label="OK" version="1.1">
      <g class="grommetux-status-icon__base">
        <circle cx="12" cy="12" r="12" stroke="none"></circle>
      </g>
      <g class="grommetux-status-icon__detail">
        <path d="M10,17.4 L5.3,12.7 L6.7,11.3 L10,14.6 L17.3,7.3 L18.7,8.7 L10,17.4 Z" stroke="none"></path>
      </g>
    </svg>
    <div class="grommetux-toast__contents">Toast test</div>
  </div>
</div>
```

I installed grommet (version 1.2.1) into a react-create project so I'm wondering if I might be missing something? 

Thanks!

**Comment by alansouzati** [comment]
this looks like a bug. let me look into this

**Comment by alansouzati** [comment]
A fix for this has been added here: https://github.com/grommet/grommet/commit/f4552b1bf9c3d5b99f6a7fdfbad4be3b3f6a0971

Although I would recommend removing the Toast for the virtual DOM when onClose is invoked, here is the codepen that we recommend:

http://codepen.io/alansouzati/pen/qrKZKa?editors=0010
