### ISSUE TITLE
Buttons with type "submit" should not disable by default if there is no onClick

### ISSUE THREAD

**Issue by glennflanagan** [grommet/grommet#1266]
### Expected Behavior
When a `Button` component is used in a form (type="submit") it should not be disabled if there is no `onClick` prop. This would allow the button to use the default HTML behaviour of submitting the form and allow developers to use the Forms `onSubmit`.

### Actual Behavior
Not supplying an `onClick` (or `path`) to a `Button` component disables the button by default.

### URL, screen shot, or Codepen exhibiting the issue
Codepen Example http://codepen.io/glennflanagan82/pen/BWVJOQ

### Your Environment
* Grommet version: 1.3.3
* Browser Name and version: All
* Operating System and version (desktop or mobile): All

**Comment by alansouzati** [comment]
Yeah this makes totally sense.

Can you work on a pull request for this?

I believe there are two places we need to check for type="submit", here:

https://github.com/grommet/grommet/blob/master/src/js/components/Button.js#L103

and here:

https://github.com/grommet/grommet/blob/master/src/js/components/Button.js#L127

**Comment by raphi011** [comment]
if @glennflanagan doesn't want to create a pull request i could jump in :)

**Comment by alansouzati** [comment]
that would be awesome @raphi011, thanks for volunteering

**Comment by raphi011** [comment]
ok, i'll try to fix it tomorrow, need this feature too

**Comment by alansouzati** [comment]
Fixed by the merged PR. thanks @raphi011
