### ISSUE TITLE
Sidebar in responsive state - incorrect location of checkbox

### ISSUE THREAD

**Issue by MarcelGeo** [grommet/grommet#1267]
### Expected Behavior
Checkbox´s input type="checkbox" is located in competent wrapping node.

### Actual Behavior
Described checkbox is outside of clicked checkbox. By clicking on the checkbox, blue rectangle is showing outside of clicked area. This state is occurring in the responsive mode of Sidebar.

### URL, screenshot, or Codepen exhibiting the issue
Here is a screenshot of the situation in Google chrome responsive mode. 
![sidebar](https://cloud.githubusercontent.com/assets/12643115/24295341/970a07e6-109a-11e7-856a-b700ae836b20.png)

### Your Environment

* Grommet version: Actual in npm
* Browser Name and version: Google Chrome Responsive mode
* Operating System and version (desktop or mobile): Windows 7

**Comment by alansouzati** [comment]
Can you provide a codepen reproducing this issue? You can fork Grommet's codepen from here:

http://codepen.io/grommet/pen/gaEGPY

**Comment by MarcelGeo** [comment]
Hello
http://codepen.io/MarcelGeo/pen/YZvORz

Give window to responsive mode in chrome and you will see blue rectangle over checkbox.

**Comment by alansouzati** [comment]
Thanks. I'm able to reproduce this. let me work on a fix for that.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/fcbf437e67e7e2f1010ab390606177d42defabe9
