### ISSUE TITLE
LoginForm does not layout properly on mobile when nested in a div/span

### ISSUE THREAD

**Issue by allenhartwig** [grommet/grommet#1271]
When the LoginForm component is wrapped in a div or span tag (potentially others) the form overflows the viewport on the mobile breakpoint.

### Expected Behavior
The LoginForm should render the same as if it were not nested.

### Actual Behavior
LoginForm renders improperly when nested

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/allenhartwig/pen/qrMppY

### Steps to Reproduce
 1. Run the Codepen
 2. View and a screen resolution below 400px wide

### Your Environment

* Grommet version: 1.3.4
* Browser Name and version: Chrome  56.0.2924.87 (64-bit)
* Operating System and version (desktop or mobile): OS X 10.12.3

**Comment by SuhairZain** [comment]
This is because the `LoginForm` sets a width of 480px by default. But you can easily work around this by either setting `max-width: 100%` or `width: 100vw` on the outer div. Or, if you can, you can use a `<Box/>` with `full={true}` as the outer component.

**Comment by tracybarmore** [comment]
Hi @allenhartwig, did @SuhairZain 's suggestion fix your problem?

**Comment by alansouzati** [comment]
thanks @SuhairZain, you are exactly right. your Div has to control its width. I would either remove the div wrapper, which seems unnecessary, or leave it and add a `max-width` to it.

I'm closing this issue. Feel free to reopen if you feel there is something to be fixed in grommet.
