### ISSUE TITLE
Button component react router 4 compatibility

### ISSUE THREAD

**Issue by zacksinclair** [grommet/grommet#1274]
The Button component's path prop is designed for use with react router, but is currently incompatible with RR4

### Expected Behavior
When path prop is passed to button, a click should transition route

### Actual Behavior
When mounting component, javascript error (router.createPath is not a function) on this line:
https://github.com/grommet/grommet/blob/master/src/js/components/Button.js#L94

### Steps to Reproduce
 1. have react router > 4 installed
 2. pass path to button
3. try to render button, get error

**Comment by alansouzati** [comment]
I've recently added support for react v4 on Anchor.

Would you be so kind to create a pull request to add the same support for button?

Checkout these commits:

https://github.com/grommet/grommet/commit/74ee5fe625e7777d30d6c49098b72863a4dfd1a6

https://github.com/grommet/grommet/commit/7d785d4d18f2f62bd4eab1dae9f25bef02f99392

**Comment by zacksinclair** [comment]
yep will do
