### ISSUE TITLE
RadioButton nested in Menu doesn't work properly

### ISSUE THREAD

**Issue by maxs15** [grommet/grommet#1276]
I've found the RadioButton onChange event isn't triggered when nested in a Menu.

### Expected Behavior
The radio onChange event should be triggered

### Actual Behavior
The event isn't triggered

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/maxs15/pen/aJRLZj

### Steps to Reproduce
 1. Open menu
 2. Click on the radio button
 3. It should display an alert if working properly

### Your Environment
* Grommet version: 1.3.4
* Browser Name and version: Chrome 56
* Operating System and version (desktop or mobile): MacOS

**Comment by alansouzati** [comment]
Take a look on the closeOnClick option here: https://grommet.github.io/docs/menu

I've forked your pen, and it works:

http://codepen.io/alansouzati/pen/rmaLZR?editors=0010

`<Menu closeOnClick={false}>`
