### ISSUE TITLE
On click on listItem component shows a boundary colour.

### ISSUE THREAD

**Issue by vaibhavbhargav** [grommet/grommet#1278]
on clicking on a list item shows green color boundary across the listItem always.

### Expected Behaviour
on clicking of the list item boundary color should be shown based on configuration.

### Actual Behavior
boundary color appeared if we click on the list item

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/vaibhavbhargav/pen/LWJGeJ

### Steps to Reproduce
 1. Click on the item
 2. Clicked item shows a colored boundary

### Your Environment

* Grommet version: latest
* Browser Name and version: all
* Operating System and version (desktop or mobile): Win

**Comment by RyanCCollins** [comment]
Hey @vaibhavbhargav.  
For a quick fix, you can override the styling for your specific use-case:

```
.grommetux-list-item:focus {
  outline: none;
}
```

Another option, of course, would be to add a property to control this behavior.  I will leave the issue open to see if that's a possibility in the future.  Also, we would happily review a pull request with that behavior if you are able.

**Comment by dgennetten** [comment]
@vaibhavbhargav, this is normal and expected behavior. HPE-themed Grommet components show the green border when they have focus. Your code leaves the component focused.
