### ISSUE TITLE
Webpack bundled Line chart returns null or undefined

### ISSUE THREAD

**Issue by BrianJVarley** [grommet/grommet#1283]
### Expected Behavior
Expected https://grommet.github.io/hpinc/docs/chart Line chart to render when bundled with webpack bundler and hosted on Github Pages.

### Actual Behavior
Rendering the Grommet Line chart on a local build shows the chart functioning as expected. But when the React.js site is bundled using webpack and `dist` files created. The Line chart doesn't render giving browser console error on Chrome: 

> cannot read property of null or undefined

All other gromet.io charts render when bundled except for this one Line chart.

### URL, screen shot, or Codepen exhibiting the issue

pending.

### Steps to Reproduce
 1.Create a grommet.io line chart in a React.js project and bundle with webpack.
 2. Publish dist file to a Github pages instance.
 3. Verify undefined error appears for the render of the grommet.io line chart.

### Your Environment

* Grommet version: #stable
* Browser Name and version: Google Chrome Version 56.0.2924.87
* Operating System and version (desktop or mobile): Windows 10

**Comment by alansouzati** [comment]
Can you paste here the source code for the Chart you are trying to render?

**Comment by alansouzati** [comment]
Where is an example of a chart in codepen:

https://codepen.io/alansouzati/pen/zzJQYZ?editors=0010

**Comment by alansouzati** [comment]
I'm closing this issue since I believe there is nothing to be changed on Grommet. feel free to keep the discussion going. we can always reopen if we feel there is something to be fixed.
