### ISSUE TITLE
DateTime component fails to identify capitalized AM/PM moment format identifier

### ISSUE THREAD

**Issue by viggyfresh** [grommet/grommet#1285]
According to the docs, the default date format for the `DateTime` component is `M/D/YYYY h:mm a`. According to the linked Moment.js docs, substituting the lowercase `a` with an uppercase `A` should yield AM/PM instead of am/pm. However, the component fails to parse the uppercase A and merely throws it on the screen as itself (see screenshot).

### Expected Behavior
AM/PM should show up in the popup datetime picker.

### Actual Behavior
"A" shows up and sits there.

### URL, screen shot, or Codepen exhibiting the issue

Lowercase am/pm (correct behavior):
![datetime correct](https://cloud.githubusercontent.com/assets/4701451/24646229/0af30f08-18d0-11e7-96f6-f3a2d731c075.png)

Uppercase AM/PM (incorrect behavior):
![datetime incorrect](https://cloud.githubusercontent.com/assets/4701451/24646247/155f6e8c-18d0-11e7-932a-f251f2d80f23.png)

### Steps to Reproduce
 1. Render a `DateTime` component with custom format `const DATE_FORMAT = 'M/D/YYYY h:mm A';`
 2. See incorrect behavior, as above.

### Your Environment
* Grommet version: 1.3.4
* Browser Name and version: Electron 1.6.0 (Chrome 50+, unsure exactly which)
* Operating System and version (desktop or mobile): Windows 10 Creators Update RC2

**Comment by SuhairZain** [comment]
The reason for this is that in [DateTimeDrop](https://github.com/grommet/grommet/blob/master/src/js/components/DateTimeDrop.js#L33), the format specifier for AM/PM is just the character 'a' (small case). I've created another key, for the same character 'a', but upper case ('A') to accept meridians in upper case as well.

**Comment by viggyfresh** [comment]
Awesome, thanks!
