### ISSUE TITLE
Question - Stacked Layers Possible?

### ISSUE THREAD

**Issue by Serexx** [grommet/grommet#1286]
This is my first Grommet use. I wanted to stack a modal - have a Layer open another Layer.

The hope was that the closer icon would be available with a simple <Layer hide={false} closer={true}>

Unfortunately the Layer opens regardless of the [hide] value and when open does not show the closer.

As this is my first use and I'm also still learning Redux it may well be my issue but before I go chasing it further I wanted to find out whether it should be possible to stack Layers ?

I looked but didn't see any related issues here or on SO.

Thanks!

EDIT - Just realized I was using [hide] instead of [hidden], so that problem solved however the closer still no appearing so the question stands - TIA.

**Comment by tracybarmore** [comment]
Hi @Serexx , we find that our community is fantastic (and sometimes quicker) at answering quick questions like these. I'm leaving this question in our backlog for one of our awesome sauce developers to take a look at, but feel free to post this question in Slack at [grommet.slack.com](grommet.slack.com) in the meantime. Thanks!

**Comment by alansouzati** [comment]
It is possible to have stacked layers. Grommet will render that. but this is not recommended for UX reasons.

**Comment by Serexx** [comment]
Thanks Alan, I'm converting an existing app with layered modals but as I've become more familiar with the Grommet framework I've realized that It's less intuitive that way, and is more complex as well so we're biting the bullet and redoing things. Thanks for the reply!
