### ISSUE TITLE
Icons bundle size

### ISSUE THREAD

**Issue by Slumber86** [grommet/grommet#1287]
I have a new project with webpack 2 and grommet, I noticed that my vendor bundle is 6 MB, so I started to digg the size. Grommet alone is 3,8 MB and the icon folder is 2,8 MB as you can see in the 

### Expected Behavior
Webpack tree-shaking algorithm is able to reduce the bundle size

### Actual Behavior
All the bundle is too big

<img width="870" alt="schermata 2017-04-04 alle 11 28 03" src="https://cloud.githubusercontent.com/assets/7034226/24650666/2f18a39c-192b-11e7-9ce5-ef441ec27da7.png">

### Steps to Reproduce
 1. Build with weback
 2. Analyze bundle with https://chrisbateman.github.io/webpack-visualizer/

### Your Environment
* Grommet version: 1.3.4
* Webpack version: 2.3.3
* Browser Name and version: all
* Operating System and version (desktop or mobile): all

**Comment by Slumber86** [comment]
Found the cause: 
i have a vendor bundle in my webpack config. I used 'grommet' as entry point, so `grommet/index.js` was imported. I think is not worth to splitt the app and the vendor part

**Comment by reflog** [comment]
had the same problem here, but resolved it by importing the components and icons correctly, instead of: `import {Button} from "grommet"`, write `import Button from "grommet/components/Button"` to reduce the bundle size

**Comment by Slumber86** [comment]
@reflog yeah, this is the way to do, but also keep attention on webpack entry points cofig
