### ISSUE TITLE
Select drop out depends on scroll position, wrong size of box

### ISSUE THREAD

**Issue by christofmuc** [grommet/grommet#1288]
With commit https://github.com/grommet/grommet/commit/939b80ce13973dd9fef83649e64964502dc40ea3 , the max-height of the Drop box depends on the scroll position. But sometimes, the drop boxes in our application suddenly have just e.g. 7 pixel height, despite having plenty of space on the page. This makes even the vertical scrollbar in the drop out unusable, as it is just too small. 

### Expected Behavior
The Select drop out box should use vertical space for its content if available. If the page is at an end, it should probably be possible to use the space to the top of the box in order to be display its values.

### Actual Behavior
Depending on scrollbar position, the size of the drop out box is suddenly limited. This does not even take into account that the page itself can be scrolled down. Reverting the aforementioned commit restores proper behavior, but probably breaks something else?

### URL, screen shot, or Codepen exhibiting the issue
I tried to setup a pen, but our application actually behaves worse (in that even select boxes that are fully visible and have plenty of space suddenly have just 7 pixel height available).

Try this and open the select boxes at the bottom, their drop out box size is reduced even though you could scroll down to see it:
https://codepen.io/cruc/pen/MpxLyM/

Here is a screenshot from the pen:

![image](https://cloud.githubusercontent.com/assets/5006524/24660082/df43d692-194e-11e7-818c-8df3d4b3fcea.png)

And if you scroll to the very end of the list, the last select boxes can't open a drop out at all or show one too small without a scrollbar

### Steps to Reproduce
See section before, use the codepen.

### Your Environment
* Grommet version: 1.3.4
* Browser Name and version: Chrome Version 57.0.2987.133
* Operating System and version (desktop or mobile): Windows 7, Desktop

**Comment by alansouzati** [comment]
Thanks for this issue.

Fixed in https://github.com/grommet/grommet/commit/6b7ec5c9bfc246e8f9d47d5d4450e6e99d3cbc9e
