### ISSUE TITLE
[Tool]Tip show on hover?

### ISSUE THREAD

**Issue by hdehal** [grommet/grommet#1289]
Can tips be shown on hover?
e.g. https://v4-alpha.getbootstrap.com/components/tooltips/#interactive-demo

I don't see anything in the documentation, and the properties seem pretty sparse:
https://grommet.github.io/docs/tip

**Comment by tracybarmore** [comment]
Hi @hdehal, which element or page component are you trying to invoke a "tool tip" on?

**Comment by alansouzati** [comment]
Showing tips on hover is not recommend and I don't think it is supported.

I'm closing this issue because I believe there is nothing to be changed on grommet.
