### ISSUE TITLE
Slider buttons in range graph don't work in Ipad and mobile devices

### ISSUE THREAD

**Issue by ishwark7** [grommet/grommet#1299]
The buttons in range graph don't work on Ipad and mobile devices.

### Expected Behavior

There should be a way to mae the slider buttons work in the range graph on these devices

### Actual Behavior

The buttons don't work as they work in WEB UI

### Codepen exhibiting the issue
http://codepen.io/ishwark7/pen/ZeEVEx

Thanks,
Ishwar

**Comment by dgennetten** [comment]
@ishark7 could you take a peek and your codepen and get it working again?

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/74c060d93543be4a67364f0371e9971691fdabbe

Also added keyboard operability and accessibility.

**Comment by alansouzati** [comment]
You should use `e.target.value` instead of `e.value`
