### ISSUE TITLE
Indside the grommet header menu alignment is not working.

### ISSUE THREAD

**Issue by sudesh-gama** [grommet/grommet#130]
![errormenu](https://cloud.githubusercontent.com/assets/13653637/9134338/d668253e-3d20-11e5-8489-cd34a26c25c2.png)

![jscript](https://cloud.githubusercontent.com/assets/13653637/9134428/acdd21aa-3d21-11e5-8c48-da85ec9e5862.png)

**Comment by bryanjacquot** [comment]
@sudesh-gama: it's been a while since you submitted this issue.  If you're still having issues, can you please create a CodePen to illustrate?  You can start with this Hello World pen: http://codepen.io/grommet/pen/gaEGPY

**Comment by alansouzati** [comment]
Closing as we cannot reproduce this issue and it is one week that we asked for follow-up
