### ISSUE TITLE
Meter stack behaviour is really an append

### ISSUE THREAD

**Issue by XuluWarrior** [grommet/grommet#1300]
I have a series of data and a known max.  I would like a meter to show each data point as a percentage of max stacked on top of each other.  Currently the behaviour when stacked=true is to append the values on the meter.

e.g. 
max = 100
series = [
  { label: "A", value: 25 } ,
  { label: "B", value: 50 }
]

In this case I would like a meter to show A taking up 25% of the meter and B taking up 50% of the meter but overlapping A so the meter is only 50% full.

The current behaviour is to show B after A and so the meter becomes 75% full.

I appreciate that the current behaviour is as desired but it would be helpful to have another option to result in the behaviour as I have indicated.

Currently I have added a hack to Meter/Bar to always behave as I would like as the normal stacked behaviour is no use to me.

**Comment by XuluWarrior** [comment]
### Current behaviour 
<img width="224" alt="current-appendbehaviour" src="https://cloud.githubusercontent.com/assets/7773288/24866221/6bfdb614-1e01-11e7-9619-fc3171c6b505.png">

### Desired stacked behaviour
<img width="225" alt="realstackedbehaviour" src="https://cloud.githubusercontent.com/assets/7773288/24866257/7e191410-1e01-11e7-94a5-4c25ef9cda26.png">

**Comment by dgennetten** [comment]
@XuluWarrior, were you intending to create a sort of bullet graph with a value displayed against a threshold?  (https://en.wikipedia.org/wiki/Bullet_graph)

**Comment by XuluWarrior** [comment]
@dgennetten No.  In this case I have two stats.  One is a subset of the other.  I want to stack them on one bar as this seems both intuitive and uses less space.  The side-by-side behaviour may make sense if you have independent values but that is not what I am trying to present.

**Comment by dgennetten** [comment]
@XuluWarrior I see the primary problem with this proposal is its imposed practical limitation a maximum of two stats (without widening bars beyond the current, long-established pattern and presenting design and usability issues).  This seems very limited in its application. Do you disagree?

I do believe a legitimate grommet Bullet graph (which might work for you since both values would still be under programmatic control) might present a more compelling case?

**Comment by XuluWarrior** [comment]
@dgennetten In my scenario, the number of stats does not affect the width of the bar.  In my example pictures the red bar is wider because it is highlighted due to mouseover.  Before mouseover the blue and the red lines are the same width.

**Comment by dgennetten** [comment]
@XuluWarrior What if you have two or more stats that are equal in value? It seems there would be no way for the user to know.

**Comment by XuluWarrior** [comment]
@dgennetten Valid point.  I am actually using the meter as part of the annotated meter and so would be able to see both values even if they were equal.
Without annotation, perhaps on mouseover, one stat expands, showing the other one on top at normal width.  Making it clear that both stats are being displayed but have the same length.

**Comment by dgennetten** [comment]
In grommet 2.0 (soon), meters and charts are getting a substantial makeover. Let's close this and perhaps re-open as an enhancement request on 2.0 if still needed.
