### ISSUE TITLE
React 15.5.x: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by ezzatron** [grommet/grommet#1303]
See https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

**Comment by SuhairZain** [comment]
I'm trying to spin up a script to do this. I'll update here on the progress shortly.

**Comment by SuhairZain** [comment]
Seems like there's a codemod already available for this. I somehow missed that. Trying it now. 😄

**Comment by ezzatron** [comment]
I'm still getting this error when using Grommet `1.4`, but it seems to be caused by an upstream package, namely `react-intl`.

See yahoo/react-intl#918 for the current status. It seems the `react-intl` package needs maintainers.

**Comment by MichaelDeBoey** [comment]
`react-intl v2.3.0` is [released](https://github.com/yahoo/react-intl/pull/940) 🙂

**Comment by adamroldfield** [comment]
Anchor causes this issue as well, because of the reference to react-desc

**Comment by alansouzati** [comment]
Yeah I've updated react-desc already.

**Comment by alansouzati** [comment]
this problem should now be gone. can some of you validate that so that I can close this issue?

**Comment by ezzatron** [comment]
I haven't seen the issue in a while. Safe to close AFAIC.

**Comment by alansouzati** [comment]
thanks @ezzatron
