### ISSUE TITLE
Layer closer not working

### ISSUE THREAD

**Issue by oakmad** [grommet/grommet#1308]
I've added a Layer with closer set to true to my page. The closer is neither showing and because of the change to remove the click outside to close I can not close the layer once it's active.

[Heres a codepen showing the issue](http://codepen.io/anon/pen/zwYVoy?&editors=0010)

It works on the docs site no problem, are they running a different version?
* Grommet version: 1.3.4
* Browser Name and version: Safari or Chrome

**Comment by oakmad** [comment]
Nevermind, this is a doc issue. If you have closer set to true make sure you also have onClose defined properly.

**Comment by RyanCCollins** [comment]
Great, thank you @oakmad!

We are always looking for contributions, especially to the docs.  If you're interested in helping out, checkout the [grommet-docs](https://github.com/grommet/grommet-docs) repo.

**Comment by bwheeler96** [comment]
This issue is still present in the docs http://grommet.io/docs/layer

I had no idea why the closer wasn't working, although this does sorta make sense
