### ISSUE TITLE
[Medium App]   box-shadow does not have top ele.

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#131]
![image](https://cloud.githubusercontent.com/assets/13039669/9141299/781c27d4-3cec-11e5-9577-9223b33ad836.png)

![image](https://cloud.githubusercontent.com/assets/13039669/9141347/e428646a-3cec-11e5-8502-580ff76c824e.png)

**Comment by bryanjacquot** [comment]
Menus now have a light grey background that avoids this issue.
