### ISSUE TITLE
Box wrap behavior is broken if padding != none and children have basis='1/2'

### ISSUE THREAD

**Issue by woodm1979** [grommet/grommet#1310]
Box wrap behavior appears broken if sub-components have a basis, and padding between != 'none'.

### Expected Behavior

In this code-pen:
http://codepen.io/anon/pen/WpqGgp?editors=0010
I'd expect the top box (labeled "Padding between: small" to have 2 columns of 3 sub boxes each.  Just like the box at the bottom labeled "Padding between: none".

### Actual Behavior

As you can see in http://codepen.io/anon/pen/WpqGgp?editors=0010
the top box does indeed have 2 columns, but the right column only contains the final element and it's pushed all the way to the bottom.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/anon/pen/WpqGgp?editors=0010

### Steps to Reproduce
 1. http://codepen.io/anon/pen/WpqGgp?editors=0010
 2. 
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by karatechops** [comment]
Hey @woodm1979, thanks for pointing out this bug. It looks like the bug stems from [these styles](https://github.com/grommet/grommet/blame/master/src/scss/grommet-core/_objects.box.scss#L3-L35) not calculating the pad properly. I'll take a closer look and see if there are any backward compatibility issues with posting a fix.

**Comment by karatechops** [comment]
This one is a doozy. If we could define the basis in the initial Box container we could accomplish something more fluid but currently a Box with `row` and `wrap` accepts all variations of basis mixed together there's not much we can do to fix this up.  For example if we appended the wrap styles with the following: 
```
.#{$grommet-namespace}box--wrap {
  flex-wrap: wrap;

  .#{$grommet-namespace}box.#{$grommet-namespace}box--basis-1-2 {
    &:nth-of-type(2) {
      margin-right: 0;
    }
  }
}
```
This would work for your use case but wouldn't solve the issue as the basis nested within wrap can be a mixed bag (IE four 1/4 basis Boxes with five 1/3 basis Boxes.). The alternative here is letting the Box rows render and having Grommet's Box programmatically remove the margin at the end of the rows. I generally steer clear from anything that renders and needs to adjust itself after -- I wouldn't classify this as an elegant solution.

For circumstances like this where I can't find an elegant solution in Grommet's core I generally reach for inline styles or styled-components. In this case I would use a Javascript's `map` on my data to trigger the removal of the right margin - check out this [Codepen](https://codepen.io/karatechops/pen/bobMVP?editors=0010) for an example.

Personally, I would like to remove the pad between prop from Box when a basis is set but introducing this change in 1.x will certainly break layouts. I'm going to tag 2.x's Box card ( #1457 ) to bring some light to this issue. Thanks for bringing this to our attention @woodm1979!
