### ISSUE TITLE
When unmounted, Layer component causes other elements to lose focus

### ISSUE THREAD

**Issue by rk1** [grommet/grommet#1316]
I have two routes, one containing a hidden `Layer` component and another containing an input which should be autofocused. When changing the routes the focus stays on the last clicked element instead of having the input focused.

I believe this is related to the way returning focus to the original focused element is done via `setTimeout`.
https://github.com/grommet/grommet/blob/master/src/js/components/Layer.js#L170

The only workaround I have found is using a ref and focusing on `componentDidMount` with another timeout which is far from ideal.

### Expected Behavior
The input with `autoFocus` prop should be focused.

### Actual Behavior
The Anchor is focused.

### URL, screen shot, or Codepen exhibiting the issue
Code: https://github.com/rk1/grommet-layer-issue/tree/master/src
Demo: http://grommet-layer-issue.surge.sh/

### Steps to Reproduce
 1. Navigate to About
 2. Navigate to Home
 3. Navigate to About again
 4. Home button is in focus, instead of the input

### Your Environment

* Grommet version: 1.3.4
* Browser Name and version: Google Chrome 57.0.2987.133, Firefox 52.0.2
* Operating System and version (desktop or mobile): macOs Sierra 10.12.4

**Comment by alansouzati** [comment]
Thanks for such a detailed information in this issue. I will be investigating this shortly.

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/2162e514f783f628a278d3720bbbe0f56f90f689
