### ISSUE TITLE
How to change the loading component ?

### ISSUE THREAD

**Issue by martinezguillaume** [grommet/grommet#1317]
I would like to change the loading component display at the start of grommet application

So I want to change this
![image](https://cloud.githubusercontent.com/assets/17292331/25303362/84aaddaa-2751-11e7-8d9d-15677ae60a51.png)

I tried to search in the docs but didn't find anything, thanks !

EDIT: Got it, it's on index.html

**Comment by MichaelHuy** [comment]
Hello, are there some ways to show it from a component loading of react?

**Comment by ShimiSun** [comment]
Not sure what you are asking, are you in search for loading component?
If yes, then take a look at this example with loading svg https://storybook.grommet.io/?selectedKind=Accordion&selectedStory=Rich&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
navigate to Highlight

**Comment by MichaelHuy** [comment]
@ShimiSun How to use it on index.html file?
