### ISSUE TITLE
[Medium App]   Width of the menu-drop log out item is too big

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#132]
Seen on phone screen as well as desktop screen:
![image](https://cloud.githubusercontent.com/assets/13039669/9141665/470b8fb0-3cef-11e5-9cd4-cb7839d8e2cb.png)

![image](https://cloud.githubusercontent.com/assets/13039669/9141676/58fc9156-3cef-11e5-911f-02f8df1c942c.png)

**Comment by bryanjacquot** [comment]
This is likely an issue with the Ferret application.  However, the menu example on the docs site also opens menus at full width so before closing this issue as a bug in Ferret, we want to be sure there's not a broader issue in Grommet.  http://grommet.github.io/hpe/docs/menu

**Comment by jwijay** [comment]
I tested the menu component in ferret.grommet.io in IE11 (Windows), Chrome (Windows/OSX), Firefox (Windows/OSX) and Safari (OSX). The issue appears resolved, as the mobile behavior for the menu has changed to be a smaller drop-down. In desktop (and on a Windows machine), the width of the menu seems appropriate.

Ferret app in IE11, desktop:
![ie-ferret-menu-desktop](https://cloud.githubusercontent.com/assets/10161095/17577128/f5f9e73a-5f15-11e6-989e-edecf5e764a7.PNG)

Ferret app in IE11, mobile:
![ie-ferret-menu-mobile](https://cloud.githubusercontent.com/assets/10161095/17577129/f6122480-5f15-11e6-9f97-8956adc91578.PNG)
