### ISSUE TITLE
Reorder tile or list

### ISSUE THREAD

**Issue by mvanlonden** [grommet/grommet#1320]
What is the recommended way to give the user the ability to reorder a collection? My specific use case is for a collection of image tiles. I would like to give the user the ability to change the order in which the images appear.

**Comment by mvanlonden** [comment]
FWIW I just added arrow to move items up or down
![screenshot](https://puu.sh/vvWwM/f2e8b5490f.png)

**Comment by alansouzati** [comment]
That's a good solution in my opinion. I was working on a similar project and implemented exactly as you did. I'm closing this issue since I believe there is nothing to change on grommet itself. thanks for reporting this.
