### ISSUE TITLE
Header float property messes up the header.

### ISSUE THREAD

**Issue by tobias-flitsch** [grommet/grommet#1322]
When float is set to true, header component stops working.

### Expected Behavior
Header spans entire page or parent element. 

### Actual Behavior
Header sits somewhere left on the page, not spanning anything, as seen in the examples. 

### URL, screen shot, or Codepen exhibiting the issue

https://grommet.github.io/docs/header/examples/?size=small&fixed=true&float=true&i-title=true&i-search=false&i-menu=true

![image](https://cloud.githubusercontent.com/assets/4466053/25371290/d3f8d700-2944-11e7-827f-b521d8f49de8.png)

**Comment by cherih** [comment]
@tobias-flitsch - This only seems to be a problem when both fixed and float are true. Does the fixed property alone provide the functionality you need?

The float property seems confusing and we are re-evaluating it for Grommet 2.0 to determine whether or not it can be deprecated. Do you have a specific use case that requires the float property?

**Comment by alansouzati** [comment]
I just had a chat with @ericsoderberghp and he explained me a scenario where the float is useful. It was confusing to me also, hopefully we will fix this confusion when we release the new site for Grommet 2.0 😄 

Here is a codepen for that:

https://codepen.io/alansouzati/pen/awPZpY?editors=0010

The align of `It is cool` is centered around the entire box, even though the header takes the top part.

Compare this with a regular header and you will see the difference in the alignment.

https://codepen.io/alansouzati/pen/zzyBzR?editors=0010

That said, float and fixed are not meant to be used together. We are closing this issue. Feel free to continue the discussion here.
