### ISSUE TITLE
Feature Request: Indeterminate CheckBox

### ISSUE THREAD

**Issue by mvanlonden** [grommet/grommet#1323]
The `CheckBox` component allows a `checked` or `unchecked` state but not an indeterminate state. Would be nice to have one. 
![example](https://puu.sh/vvWFh/e4c7413119.png)

**Comment by SuhairZain** [comment]
Hi @mvanlonden,
Just wondering, what would be the use case for an indeterminate CheckBox? Checkboxes are usually boolean.

**Comment by mvanlonden** [comment]
I have a nested set of checkboxes and if some but not all of the child boxes are checked I'd like to have the parent be indeterminate. Clicking on the parent checkbox would serve as a "check all" or "check none" for the children.

**Comment by SuhairZain** [comment]
This sounds like a valid use case.

@alansouzati What's your take on this?

**Comment by tracybarmore** [comment]
hey @mvanlonden, we had this suggestion opened back in September, but closed the issue since this tree structure is a pretty old style for selection. 

Here's the previous issue: https://github.com/grommet/grommet/issues/850

Do you have a screenshot or example of your product that we assist in consulting a different way of layout and/or selection? Thanks!

**Comment by mvanlonden** [comment]
Agreed. I've moved on to an alternative implementation and am much happier with the results. Thanks!

**Comment by alansouzati** [comment]
This indeterminate state is in the core HTML5 spec. we should definitely add support for this in grommet.

https://css-tricks.com/indeterminate-checkboxes/

**Comment by oorestisime** [comment]
i had a quick look at the code. it seems to do this there is a need of a new property and a new svg icon. i guess like the checked svg it should be in the theme so user can override.
I d like to tackle this if i got this right.

**Comment by alansouzati** [comment]
yes this seems right. it would be interesting to see how to solve the `toggle` type when dealing with that. I don't think there is an indeterminate state for toggle.
