### ISSUE TITLE
Creating an xsmall SVGIcon fails PropTypes

### ISSUE THREAD

**Issue by m4rcelofs** [grommet/grommet#1324]
### Expected Behavior
Creating an `SVGIcon` with xsmall as its size should not throw a PropTypes validation error 

### Actual Behavior
It works (the icon is rendered smaller than `small`), but fails validation.

```
Warning: Failed prop type: Invalid prop 'size' of value 'xsmall' supplied to 'SVGIcon', expected one of ["small","medium","large","xlarge","huge"].
```

### URL, screen shot, or Codepen exhibiting the issue
[Codepen](https://codepen.io/marcelofs/pen/oWYexo?editors=0010)

### Your Environment
* Grommet version: 1.3.4

**Comment by SuhairZain** [comment]
The PropTypes for SVGIcon includes only small, medium, large, x-large and huge even though the classes for x-small are generated. I've added x-small to the PropTypes list.

**Comment by m4rcelofs** [comment]
Seems to still be missing in [master](https://github.com/grommet/grommet/blob/master/src/js/components/SVGIcon.js#L59)/1.4.0

**Comment by SuhairZain** [comment]
I'm sorry. Was caught up at work. I made the commit but missed making it into a PR. I sincerely apologize. Will make one right away.

**Comment by m4rcelofs** [comment]
ping, should I open a PR for that?

**Comment by SuhairZain** [comment]
Hey Marcelo. I keep getting stuck at work that I haven't been able to make public commits for over a month. If it's possible for you to make the PR, I'd totally appreciate it. It'd be a great help. :)
