### ISSUE TITLE
Search is not working properly

### ISSUE THREAD

**Issue by ibhag** [grommet/grommet#1325]
### Expected Behavior
Search should update the results appropriately on list pages

### Actual Behavior
After some point of time search doesn't respond properly. Seems there is some problem with onDomChange. Though I am attaching example of ferret I am able to reproduce it in my application as well

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/17637919/25426563/3c0d2ab4-2a8d-11e7-83f4-e963f9065d22.png)

### Steps to Reproduce
 1. Open ferret http://ferret.grommet.io
 2. Under Virtual Machines Search type Proj (Results Internal Project 2, Internal Project 7, Internal Project 12, Internal Project 17)
 3. Type Project 1 in Search, results are not updated
 4. Type Project 12 in Search, results are updated to display only "Internal Project 12"

It's not a timing issue I waited for quite sometime still it is not updated

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by SuhairZain** [comment]
Hi @ibhag,
Would it be possible to provide a minimal example to reproduce the issue, such as on codepen?

**Comment by alansouzati** [comment]
I'm trying to reproduce this, can you provide a codepen for that @ibhag ? I don't think this is a grommet bug, but something where the request does not actually work. This is just an assumption.

That's why I believe a codepen is very important, it helps to isolate the issue.

**Comment by alansouzati** [comment]
Due to inactivity I'm going to close this issue. feel free to reopen if you still feel there is something wrong.
