### ISSUE TITLE
Carousel infinite set to false not working

### ISSUE THREAD

**Issue by hustlerism** [grommet/grommet#1327]
Carousel infinite set to false not working. 

Same issue with #1220.

Any fix for this?

### Your Environment

* Grommet version: 1.3.4
* Operating System and version (desktop or mobile): Android 6.0.1

**Comment by tracybarmore** [comment]
Hi @hustlerism, I created this codepen that I believe solves your problem: http://codepen.io/anon/pen/bWWPVV

By indicating both infinite and autoplay are false, this allows the carousel to stop swiping once it has reached the end of all your slides. Is this what you were looking for?

**Comment by hustlerism** [comment]
Hi @tracybarmore , from your example, I can still swipe the last image to the first image and vice versa. 

I would want it to stop swiping to the right at the last image and swiping to the left at the first image.

**Comment by tracybarmore** [comment]
Hey @hustlerism, I'm confused. the attached screenshot shows the last image in the carousel. There is an arrow to swipe backwards, but no arrow to the right to continue directly to the first image. Let me know if I'm misunderstanding somewhere. Thanks!

![group](https://cloud.githubusercontent.com/assets/13038855/25603105/fd423ff2-2ead-11e7-8391-64660061023e.png)

**Comment by hustlerism** [comment]
Hi @tracybarmore , apologies for the confusion. 

What i meant was, if you clicked on the last image in the carousel and swiped it to the right, it will go to the first image back. Same thing happened when u swipe the first image to the left, it will go to the last image. Don't use the arrow, just swipe it using the mouse cursor. 

Since i'm using grommet for mobile app, the users can swipe the carousel using their fingers to right and left or click on the arrows to navigate the carousel.

The problem is with the swiping, not with clicking the arrows.

**Comment by tracybarmore** [comment]
@hustlerism, ah, thanks for the clarification. I have replicated the issue on my android device. I will leave this open in our backlog to have a grommet developer take a look at. Thanks!

**Comment by hustlerism** [comment]
@tracybarmore Sure. Really appreciate your help. Thanks!
