### ISSUE TITLE
markdown-to-jsx error

### ISSUE THREAD

**Issue by andreaPortfolio** [grommet/grommet#1330]
For every new grommet installation when I tray to start the application with Webpack that return the following error:

/dealerSite/dealerSite/node_modules/markdown-to-jsx/index.js Unexpected token (149:20)
You may need an appropriate loader to handle this file type.
| 
|                 aggregator.footnotes.push(
|                     <div key={node.identifier} id={node.identifier}>
|                         {node.value || node.children.map(parser)}
|                     </div>

### Steps to Reproduce
 1. create new grommet install
 2. start application
 

### Your Environment

* Grommet version: 1.3.4
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): osx

**Comment by alansouzati** [comment]
yeah I just started experiencing that as well. let me see what is going on with markdown-to-jsx

**Comment by alansouzati** [comment]
Just to confirm, I'm assuming you've changed the App do use markdown component from Grommet?

I can only reproduce the issue if I try to use that.

**Comment by alansouzati** [comment]
I've filed the issue on markdown-to-jsx project. it seems they forgot to compile to es5 before releasing.

in the meantime you can update your package.json to use a specific version of markdown-to-jsx. 

I'm using 5.3.0 `"markdown-to-jsx": "5.3.0",`

**Comment by alansouzati** [comment]
Fixed they have released 5.3.3 with the fix included. Just make sure to delete your `node_modules` and run `yarn upgrade` or `npm install` again.
