### ISSUE TITLE
Any plans to add more components like badges and other ones ...

### ISSUE THREAD

**Issue by yackitotreeville** [grommet/grommet#1332]

**Comment by tracybarmore** [comment]
Hi @yackitotreeville, can you elaborate further or give us an example of what you're looking for?

**Comment by XuluWarrior** [comment]
I was also missing [badges](https://v4-alpha.getbootstrap.com/components/badge/#contextual-variations).  The only way I could see to do something similar was to use the Button component.

I decided that this wouldn't be suitable and changed my UI design instead.

**Comment by tracybarmore** [comment]
@XuluWarrior, thanks for the reference. I'll leave this in our backlog to bring up in our next grooming session. Thanks!

**Comment by alansouzati** [comment]
Badge is a rather simple component to live in grommet core. We recommend using Box to get the badge.

Check out this codepen:

https://codepen.io/alansouzati/pen/vZgOyy?editors=0110

**Comment by XuluWarrior** [comment]
I'm not sure I understand the argument that a component can be too simple to add to core.

I thought the focus of Grommet was components that were consistent in both design and behaviour.  If there is a "need" for Badges then developers will each have to play about with components and CSS to achieve this consistency.

Of course you could argue that there is no need for Badges or at least the need is marginal.  In which case it wouldn't be desirable to add them to core.  But I don't feel whether the component is "simple" or not should affect this decision.

I can't talk for the whole Grommet user base but other UI frameworks [[1](https://v4-alpha.getbootstrap.com/components/badge/), [2](http://www.material-ui.com/#/components/badge)] provide Badges so it would seem that there is a demand for them.

It may sound like I'm demanding that you add Badges.  But don't worry, my life will carry on quite happily if you choose to put your effort elsewhere :)

**Comment by XuluWarrior** [comment]
Also Badges have there own semantics that is made more obvious in [Material UI](http://www.material-ui.com/#/components/badge).  And so they are potentially more interesting than they look at first glance.

**Comment by alansouzati** [comment]
@XuluWarrior I'm not saying that there is not a place for Badges. I can see Badge as a component inside [grommet-addons](https://github.com/grommet/grommet-addons).

LoginForm is a similar example of a component that should live in the addons. We will be soon moving LoginForm from core to addons.

Hopefully it makes more sense now.

**Comment by XuluWarrior** [comment]
That does make more sense.  Thanks. :)
