### ISSUE TITLE
Negative values in Bar Charts

### ISSUE THREAD

**Issue by XuluWarrior** [grommet/grommet#1333]
It doesn't look like negative values are supported in the bar chart component.

I would expect to be able to set up a bar chart so that each bar goes above or below the 0 axis depending on the data point's value.  I can't currently see a way to do this.

**Comment by karatechops** [comment]
As I've documented this issue in Chart's 2.x card (#1447) I'm going to close this. Thanks for the feedback, @XuluWarrior!
