### ISSUE TITLE
Toasts should accept onClick

### ISSUE THREAD

**Issue by zekenie** [grommet/grommet#1339]
### Expected Behavior
Passing an `onClick` prop to toasts should be passed down to the relevant div.

### Actual Behavior
`onClick` is not called when toast is clicked

### URL, screen shot, or Codepen exhibiting the issue
[Here](https://codepen.io/anon/pen/NjvQag?&editors=0010) is a codepen demonstrating the issue

### Steps to Reproduce
 1. Make a toast with an `onClick` prop
 2. Click the toast

### Your Environment
Observed in chrome 58.0.3029.96

Thanks!! 😄

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/6299947ac8b7fa8c619226fc33035480cb6fdbfa
