### ISSUE TITLE
_renderActive for arc and bar meters with thresholds stacks on mouseover

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#134]
The  mouseover of non-zero index segments on a threshold arc graph result in a stack trace (Uncaught TypeError: Cannot read property 'value' of undefined).

You can see this on any bar or arc with thresholds if you mouse over the whole arc.
http://grommet.io/docs/develop/meter
Bar, Min, Max, Units, Threshold
Arc, Min, Max, Units, Thresholds

```javascript
_renderActive:function() {
//snip
            else {
//FIXME: in an arc/bar with thresholds, selecting the activeIndex segment results in 't' being undefined
                var t = this.state.series[this.state.activeIndex];
                e = {
                    value: t.value,
                    label: t.label
                }
            }
```

**Comment by jwijay** [comment]
Implementation has been updated in Meter.js to to check for active item in series before populating fields object with value/label. Mouseover issue seems resolved.
