### ISSUE TITLE
Select displays value instead of label when provided an object

### ISSUE THREAD

**Issue by jdiprizio** [grommet/grommet#1340]
### Expected Behavior
Select should display labels when they are provided a `{ label: '', value: '' }` object?

### Actual Behavior
Select displays object's value (unless they are provided a string with the label). This seems to be due to this commit: https://github.com/grommet/grommet/commit/c4593687ac09fe3834962b07a0fde33c59ad2ab8

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/anon/pen/RVLbgZ?&editors=0010

### Steps to Reproduce
 1. Create a select with a `{ label: '', value: '' }` value
 2. Select displays value instead of label

### Your Environment

* Grommet version: 1.4.0
* Browser Name and version: Chrome 58
* Operating System and version (desktop or mobile): Windows 10

**Comment by nsb** [comment]
:+1:

**Comment by karatechops** [comment]
Related to #1306

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/aa1a86d82bdd64a2aa3b05918d1718249e6dd7c7.

What is basically is rever of #1306

**Comment by morenoh149** [comment]
@alansouzati eta on a new release?
