### ISSUE TITLE
How do we use the toolbar as designed in the sketch file?

### ISSUE THREAD

**Issue by rardoz** [grommet/grommet#1342]
There is a toolbar in the sketch file that implies the ability to add a rich text editor, but there is no documentation or code that I could find to implement that.

Here is a screenshot with the description of the toolbar:
<img width="932" alt="screen shot 2017-05-04 at 9 59 52 am" src="https://cloud.githubusercontent.com/assets/1074768/25716051/8f93703c-30b2-11e7-8736-d28fbb82fc23.png">

Can anyone point me to how to use that?

**Comment by dgennetten** [comment]
@rardoz,  Apologies for the confusion caused by that sketch file.  It turns out that the toolbar shown is not something that has ever existed as a Grommet component. 

You could, however, build your own toolbar using ```<Header><Menu inline={true}><Button icons={...} /></Menu></Header>```  

Again, sorry for the misleading docs.
