### ISSUE TITLE
Severe performance issues due to new InfiniteScroll behavior.

### ISSUE THREAD

**Issue by frandr** [grommet/grommet#1345]
This relates to grommet checkins 9c9b16dd77202a87d98958186894db729a1e1848 and 8254e7e2b0a9a771c1fa7d4753483c051b777d67 in late January, which introduced this defect.

### Expected Behavior
When user pages down at the bottom of a paginated list, a single 'onMore' call will trigger retrieval of the next page of data.

### Actual Behavior
1) We now always get at least two 'onMore' calls for each page request.
2) Often we'll get 'onMore storms' with 5, 10, 100 + page data retrieval requests. In scale environments, this brings our global dashboard appliance to its knees.

### URL, screen shot, or Codepen exhibiting the issue
See below. I've got a couple appliances with unminified code deployed where you can investigate the issue.

### Steps to Reproduce
 1. In chrome or FF, open a paginated list
 2. Hit page down repeatedly
 3. Note the API calls to retrieve data

NOTE: I have two different GlobalDashboard appliances with some log statements that will illustrate this issue. To reproduce the issue, using chrome or FF, log in (Administrator/hpvse123) and navigate to the Server Hardware page. Then start paging down in the list.
  a) 16.125.106.60 includes grommet 1.40 with some log statements added. This appliance demonstrates the defect.
 b) 16.125.106.103 includes grommet 1.40, with grommet/src/js/utils/DOM.js modified to only add document if no other scroll parents found. This appliance does not demonstrate the defect.

### Your Environment

* Grommet version: 1.3+
* Browser Name and version: 
Chrome/FF

* Operating System and version (desktop or mobile):
Desktop client.

**Comment by dgennetten** [comment]
@alansouzati looks like https://github.com/grommet/grommet/commit/9c9b16dd77202a87d98958186894db729a1e1848 needs a second look...

**Comment by mcwebb** [comment]
We've also encountered this and hunted through the Grommet source code for the culprit, but couldn't find what was wrong.
Our workaround was to introduce request throttling in our stores, but obviously that's less than ideal.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/bfc03b1b18c4e579e997766d007ecd45a256ad72

**Comment by mcwebb** [comment]
brilliant, thanks for getting to the bottom of it! (pun intended) 👍
