### ISSUE TITLE
<Tiles selectable='multiple'> behaviour on mobile browsers

### ISSUE THREAD

**Issue by startupgurukul** [grommet/grommet#1348]
Hi Folks, 
Want to understand the behavior of <Tiles selectable='multiple'> on desktop/mobile

1). A desktop browser, we are able to select more than one.  but only if we select them while using  CTRL/Command...Now can we ask it to select multiple tiles when we just click them?

2). How can we select more than one on a mobile browser? 

Repro steps(right from the examples):
https://grommet.github.io/docs/tiles/examples?selectable=multiple

**Comment by alansouzati** [comment]
Good questions. I'm compiling a list of issues that will require some UX work from us and this item is there. You should hear back from us soon.

**Comment by alansouzati** [comment]
we will be re-evaluating the way we do multiple select for Tiles, specially in mobile. This work will be part of Grommet 2.0.

**Comment by karatechops** [comment]
Tagging 2.x Tiles #1494

**Comment by L0ZZI** [comment]
v2 Examplem, http://v2.grommet.io/selection let me know if this resolves your issue @startupgurukul
