### ISSUE TITLE
onEnter and onSearchIconClick events for Search and SearchInput components

### ISSUE THREAD

**Issue by emmanuelnk** [grommet/grommet#1349]
So I'm new to using Grommet but I can't find a way to register an onEnter event using Search and SearchInput components. Can't find it anywhere in the docs. The onSelect and onDOMchange events work fine but I feel like some props to register key events or on clicking the search icon event are needed.
### Expected Behavior

Search and SearchInput Components should have onEnter, onSearchIconClick or onKeyDown events
### Actual Behavior

Can't find a way to accomplish this easily. If there is, it would be much appreciated if someone can show me how (and possibly update the docs)

### URL, screen shot, or Codepen exhibiting the issue
--

### Steps to Reproduce
--

### Your Environment

* Grommet version: 1.4.0
* Browser Name and version: Chrome 58.0.3029.81
* Operating System and version (desktop or mobile): Win 8.1

**Comment by emmanuelnk** [comment]
After more research I realized that the SearchInput component is vastly different from the Search component. I made the mistake of assuming they had the same propType. I am now using the Search component and most of my problems have gone away. I still think a click handler for the search icon should be added in a future release.

On that note, I'll close this issue.

components/Search.js
```
Search.propTypes = {
  align: _propTypes2.default.string,
  defaultValue: _propTypes2.default.string,
  dropAlign: _Drop.dropAlignPropType,
  dropColorIndex: _propTypes2.default.string,
  fill: _propTypes2.default.bool,
  iconAlign: _propTypes2.default.oneOf(['start', 'end']),
  id: _propTypes2.default.string,
  initialFocus: _propTypes2.default.bool,
  inline: _propTypes2.default.bool,
  onDOMChange: _propTypes2.default.func,
  onSelect: _propTypes2.default.func,
  onKeyDown: _propTypes2.default.func,
  pad: _propTypes2.default.oneOf(['small', 'medium']),
  placeHolder: _propTypes2.default.string,
  responsive: _propTypes2.default.bool,
  size: _propTypes2.default.oneOf(['small', 'medium', 'large']),
  suggestions: _propTypes2.default.arrayOf(_propTypes2.default.oneOfType([_propTypes2.default.shape({
    label: _propTypes2.default.node,
    value: _propTypes2.default.any
  }), _propTypes2.default.string])),
  value: _propTypes2.default.string
};
```
components/SearchInput.js
```
SearchInput.propTypes = {
  defaultValue: _propTypes2.default.oneOfType([_propTypes2.default.shape({
    label: _propTypes2.default.string,
    value: _propTypes2.default.string
  }), _propTypes2.default.string]),
  id: _propTypes2.default.string,
  name: _propTypes2.default.string,
  onDOMChange: _propTypes2.default.func,
  onSelect: _propTypes2.default.func,
  placeHolder: _propTypes2.default.string,
  suggestions: _propTypes2.default.arrayOf(_propTypes2.default.oneOfType([_propTypes2.default.shape({
    label: _propTypes2.default.node,
    value: _propTypes2.default.any
  }), _propTypes2.default.string])),
  value: _propTypes2.default.oneOfType([_propTypes2.default.shape({
    label: _propTypes2.default.string,
    value: _propTypes2.default.string
  }), _propTypes2.default.string])
};
```

**Comment by drewlustro** [comment]
@emmanuelnk - how did you solve this? I'm looking for an `onEnter` event as well, or simply a means to trigger/force a search upon the enter keycode.

Thanks.

**Comment by drewlustro** [comment]
@emmanuelnk - nevermind, haha... I see you can attach a handler to `onKeyDown` and look for any code. Peace brah 💯

**Comment by prismm** [comment]
So there is really no click handler for the search icon? This seems like a big oversight to me -- that's a user expectation.
