### ISSUE TITLE
Color for bar and arc does not change as expected when threshold is singular

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#135]
Reproduction
http://grommet.io/docs/develop/meter

Set the value at the bottom of the page to 77, and look at
Bar, Min, Max, Units, Thresholds, Vertical
or
Arc, Min, Max, Units, Thresholds, Vertical

I would have expected the rest of the arc/bar to turn red. When thresholds={[]} is used the colors change, when threshold={} is used it does not.

As an aside, there doesn't seem to be a bar example of thresholds usage.

**Comment by ericsoderberghp** [comment]
Proposed behavior:

- Add `colorIndex` to Meter to allow callers to set the color without needing to use `series`.
- Support `threshold` taking an object value where `colorIndex` can be set for singular thresholds.
- Default threshold color is always `unset`, no matter how many thresholds are specified.
- value color matches threshold color only if threshold color is specified and value color is not.

**Comment by ericsoderberghp** [comment]
We have already enhanced Meter to take colorIndex directly.

We are waiting for a specific product example to enhance Meter further w.r.t. threshold behavior.
