### ISSUE TITLE
Select multiple enhancements: show checkboxes, leave Drop open, custom _renderValue

### ISSUE THREAD

**Issue by adamroldfield** [grommet/grommet#1350]
I've built some enhancements for Select and I want to socialize them before I submit a pull request.

The first change is to leave the drop open after a selection is made on a multiselect. It's a better user experience for selecting multiple items, but let me know if it needs to be an option or if it's acceptable default behavior.

The second change is to add checkboxes to the options in the multiple select.

The third change is to accept a function to call inside _renderValue for the display.

Proposed props:

> Select.propTypes = {
    inline: PropTypes.bool,
    multiple: PropTypes.oneOfType([
        PropTypes.shape({
            enabled: PropTypes.bool,
            useCheckBoxes: PropTypes.bool,
            customDisplayText: PropTypes.func
        }),
        PropTypes.bool
    ]),
...

Issues:
I couldn't use CheckBox directly because of the way labels bind to the onChange and onClick of other labels/controls. Clicking on the label, or it's margins, rendered by CheckBox caused the click event from the select option to fire twice. In my own code I've just embedded the check portion of the control, but I'm sure you don't want this duplication. Should I extract the checkbox from CheckBox somehow and then use it in both CheckBox and Select?

### Your Environment

* Grommet version:  1.4
* Browser Name and version: Chrome, latest
* Operating System and version (desktop or mobile): Windows 10

**Comment by nomadus** [comment]
+1, when you have many select items and you set inline=true, the options may take a substantial amount of the page, will any of these changes address this issue?

**Comment by adamroldfield** [comment]
Yes, @nomadus , this is what the multiselect looks like:
![multiselect](https://cloud.githubusercontent.com/assets/6673387/26515800/078d9110-4244-11e7-81e2-4cd77306e575.png)

**Comment by nomadus** [comment]
This is exactly what I was looking for, could I access to the source code, so I could test in my env?

**Comment by adamroldfield** [comment]
When I created this issue I had intended to submit my changes to the project, but I've made some extensive changes to multiple controls now, and I don't have them in github. I'm attaching my Select.js which is, IIRC, the only file you need for these features.
[Select.zip](https://github.com/grommet/grommet/files/1033662/Select.zip)

Usage:
```
<Select  multiple={{ enabled: true, useCheckBoxes: true, customDisplayText: this._displayTextFunction }}
                        ...
                    />
```

**Comment by alansouzati** [comment]
Good suggestions. I'm compiling a list of issues that will require some UX work from us and this item is there. You should hear back from us soon.

**Comment by nomadus** [comment]
@adamroldfield How could I include this changes to the grommet? Would it be just a simple replace of Select.js file?

**Comment by alansouzati** [comment]
Our team recently had a chat about multi-select. We want to avoid adding a lot of intelligence inside the dropdown. The example you provided is way better than what we have today for selecting multiple without being inline, but it still has problems. If you have 50+ items in your list and you want to select the 49th or 50th item, often times you will find yourself having to scroll all the way down to check/uncheck items.

We felt the need to separate the selected elements from the list of available options. We created a codepen with a recommendation for multi-select: https://codepen.io/alansouzati/full/GErJNm/.

![screen shot 2017-06-23 at 4 16 32 pm](https://user-images.githubusercontent.com/1207250/27503241-5778f6a0-582f-11e7-94a9-f87c5dcc3bfa.png)

You can notice that are two multi-select types:

1) An **inline** multi-select Select component.
2) A Search with suggestions and the list of selected elements outside.

This is our recommendation and we welcome feedback. Thanks for sharing your solution with us, it definitely helped us brainstorm about improvements. We will be soon removing `multiple` support for non-inline Select.

I'm going to close this issue for now.

**Comment by VenkaiahKagga** [comment]
Hello adamroldfield,
When this feature "Select multiple enhancements: show checkboxes, leave Drop open, custom _renderValue" will be available in grommet.io?
