### ISSUE TITLE
Missing styles for box height full

### ISSUE THREAD

**Issue by MarcelGeo** [grommet/grommet#1354]
### Expected Behavior
Style for full height size is expected.

### Actual Behavior
Missing style for size height full. Class named grommetux-box--height-full is added to div element right, but without expected style definition.

### URL, screen shot, or Codepen exhibiting the issue
`<Box size={{height: "full"}}>
          ...      
 </Box>`

### Steps to Reproduce
Define full height size to Box component.

**Comment by dgennetten** [comment]
@MarcelGeo  I think you need to use ```full={true]``` or ```full="vertical"```.   The reference to ```full``` in the Box ```size`` property is in error, I believe.

**Comment by dgennetten** [comment]
Docs fixed in PR267

**Comment by RyanCCollins** [comment]
@MarcelGeo 

Glad to see that this has been resolved!  I am going to close this issue to get it off of the backlog, but feel free to keep the conversation going if you have any further questions.
