### ISSUE TITLE
Disappearing icon in drop Search component

### ISSUE THREAD

**Issue by ianmartorell** [grommet/grommet#1358]
### Expected Behavior
When a Search component is not rendered inline because `inline={false}` has been specified or we're viewing it in a narrow screen, clicking on the icon opens a `.grommetux-drop` with the search input and an icon. This icon should always be visible.

### Actual Behavior
The icon inside the `.grommetux-search__drop` disappears after typing a single letter OR closing and opening the drop. This appears to happen only when the `dropAlign` prop is specified.

[Link to CodePen](https://codepen.io/ianmartorell/pen/gWKZbm).

**Comment by dgennetten** [comment]
@alansouzati I would like to turn this one into an alan-tutorial ...

**Comment by alansouzati** [comment]
That's a weird bug! Let me work on fixing that.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/bbe56fac80c8da451c390e11f76ee29fb20628f9

It will be soon part of grommet stable and for sure on the next grommet official release.

thanks for reporting this.

**Comment by ianmartorell** [comment]
No problem, thanks to you!
