### ISSUE TITLE
Add Google Analytics Tracking ID to Grommet.io

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet#1363]
Replace old Google Analytics tracker ID with new tracker ID provided from:
https://analytics.google.com/analytics/web/?authuser=0#management/Settings/a99690204w146378478p151134518/%3Fm.page%3DPropertySettings/

**Comment by dgennetten** [comment]
I'd like to take this on, but need creds.

**Comment by RyanCCollins** [comment]
I've got this :)

**Comment by alansouzati** [comment]
closing this, let's manage it in the grommet-docs project.
