### ISSUE TITLE
App content not scrolling back to original position after mounting and unmounting Layer on IE11

### ISSUE THREAD

**Issue by foolproofit** [grommet/grommet#1365]
On IE 11 the app content scrolls to top after mounting the Layer component but it doesn't scroll back after unmounting. On other browsers the content scrolls back.

### Expected Behavior
Content scrolls back to the original scroll position i.e. the scroll position before mounting the Layer component, on all supported browsers.

### Actual Behavior
Content doesn't' scroll back to the original scroll position i.e. the scroll position before mounting the Layer component, on IE11.

### URL, screen shot, or Codepen exhibiting the issue
Any Grommet app with visible scroll and a Layer showed from the "bottom" of the view.
The issue is similar to https://github.com/grommet/grommet/issues/1315 but related only to IE11.

### Steps to Reproduce
 1. Scroll the app below position 0,0;
 2. Open (mount) the Layer Component;
 3. The app scrolls to position 0,0 and shows the Layer;
 4. Close (unmount) the Layer Component;
 5. The app stays at scroll position 0,0 on IE11;

### Your Environment
* Grommet version: 1.4.0
* Browser Name and version: IE11 (11.296.15063.0)
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by foolproofit** [comment]
Workaround fix for the issues:
```javascript
import React from "react";
import {Layer} from "grommet";

/**
 * This HOC is a workaround for Grommet Layer component issue with not scrolling back to initial position on IE11.
 * https://github.com/grommet/grommet/issues/1365
 * This can be used for any other component - just add additional exports at the end of the file.
 * The code is a modified version of the Layer component code.
 * */
export default function withScrollBack(WrappedComponent) {

  class ScrollBackWrapper extends React.Component {

    constructor(props) {
      super(props);
      this._originalFocusedElement = document.activeElement;
      this._originalScrollPosition = {
        top: window.scrollY ? window.scrollY : window.pageYOffset,
        left: window.scrollX ? window.scrollX : window.pageXOffset
      };
    }

    componentWillUnmount() {
      if (this._originalFocusedElement) {
        if (this._originalFocusedElement.focus) {
          setTimeout(() => {
            this._originalFocusedElement.focus();
            window.scrollTo(this._originalScrollPosition.left, this._originalScrollPosition.top);
          }, 10);
        } else if (this._originalFocusedElement.parentNode && this._originalFocusedElement.parentNode.focus) {
          this._originalFocusedElement.parentNode.focus();
          window.scrollTo(this._originalScrollPosition.left, this._originalScrollPosition.top);
        }
      }
    }

    render() {
      const {...passThroughProps} = this.props;
      return (
        <WrappedComponent
          {...passThroughProps}
        />
      );
    }
  }

  ScrollBackWrapper.displayName = `ScrollBackWrapper(${getDisplayName(WrappedComponent)})`;
  return ScrollBackWrapper;
}

function getDisplayName(WrappedComponent) {
  return WrappedComponent.displayName || WrappedComponent.name || 'Component';
}

export const LayerWithScrollBack = withScrollBack(Layer);
```

**Comment by alansouzati** [comment]
Thanks for reporting this. Let me try to reproduce this on IE11.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/9f987ddaffffe3da28611336eb534da34549d2ce

It should be soon available on stable branch and for sure in the next Grommet official release.
