### ISSUE TITLE
Value: units on the left side

### ISSUE THREAD

**Issue by bjackson** [grommet/grommet#1366]
It would be useful to have Value be able to display units on the left side instead of the right, especially in the case of using it to display currencies.

**Comment by alansouzati** [comment]
agreed let me try and put something together for this.

**Comment by alansouzati** [comment]
Support added [here](https://github.com/grommet/grommet/commit/5af0ad403e73aaa96625f6304d1c82617e4ad076).

It should be soon available in the stable branch and for sure will be part of the next grommet release.

Thanks for the suggestion.
