### ISSUE TITLE
on screens with width less than 720 layer does not overlay

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#137]
When the screen is less than 720 in width the layers move to the top of the screen, and are not overlays.

This is in chrome
![layer overlay](https://cloud.githubusercontent.com/assets/13527666/9179307/d8b3f720-3f58-11e5-9c37-68c6194c3ed2.png)

Also has the same behavior on mobile device (nexus 5)

**Comment by jwijay** [comment]
Closing this issue, since it appears resolved when testing with screens < 720px in Chrome, Firefox, Safari, and Android.
