### ISSUE TITLE
Carousel animate on first rendering when activeIndex > 0

### ISSUE THREAD

**Issue by Slumber86** [grommet/grommet#1374]
### Expected Behavior
When the carousel is loading with `activeIndex` not zero, carusel should show the page without animation

### Actual Behavior
An animation is performed when the page is loaded

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/anon/pen/dRPNrd?&editors=0010

### Your Environment

* Grommet version: 1.4.1
* Browser Name and version: Chrome and Firefox (last)
* Operating System and version (desktop or mobile): MacOS and windows

**Comment by Slumber86** [comment]
I've created a pull request to solve the issue, please verify if it's good or not..

**Comment by alansouzati** [comment]
Thanks for your contribution and for going the extra mile to send the pull request.

I'm sorry I've just realized the Carousel docs is missing the description for `activeIndex` and `onActive`. I'm going to add documentation for it today.

That said, let me explain what is going on here. `activeIndex` should be used together with `onActive`. Basically if you pass `activeIndex` we will just assume that you want to control the index change. I've created a codepen that illustrates the correct usage of `activeIndex`.

https://codepen.io/alansouzati/pen/gRpmzJ?&editors=0010

Probably you are looking for something like `initialIndex` that will load the carousel in a given index. This property is not directly supported, but you can achieve that by the combination of both `activeIndex` and `onActive`.

Hope it makes sense.

**Comment by Slumber86** [comment]
Yeah this make sense, we use onActive exactly in this way to sync the carousel position with our redux store.
The problem is exactly that when we use this to set the state saved in redux to the carousel before first render, unwanted animation is performed (as is showed in your codepen)
My PR just changed the class until first state change to avoid starting animation.
Hope now there is better context for this

**Comment by alansouzati** [comment]
let me look into this.

**Comment by Slumber86** [comment]
Thanks 🙏

**Comment by alansouzati** [comment]
Fixed by the merged PR thanks again @Slumber86
