### ISSUE TITLE
Grommet not working with meteor 1.5

### ISSUE THREAD

**Issue by windgaucho** [grommet/grommet#1379]
Hello:

I am using meteor 1.5 and I want to try grommet for mi next app.

I install grommet with: 
meteor npm install grommet --save

Later import the scss file in my Index component but I am getting the following error:
`=> Errors prevented startup:
   
   While building for web.browser:
   /node_modules/grommet/scss/hpinc/index.scss: Scss compiler error: File to import:
   {}/node_modules/grommet/scss/grommet-core/inuit-defaults/settings.defaults not found in file:
   ../grommet-core/settings`

I already saw and try the solutions described in the issue of meteor 1.3 ( https://github.com/grommet/grommet/issues/632 ) but none el them is working with the 1.5 version.
Can any one point me in the right direction please?

Thanks

**Comment by RyanCCollins** [comment]
Hey @windgaucho this issue appears to be related to one that I had a while ago when I was getting up and running with Grommet.  I believe it comes down to the configuration of the `scss-loader`.  You might want to take a look at the [grommet-standalone](https://github.com/grommet/grommet-standalone) project, particularly the sass-loader configuration object.
```
        {
          loader: 'sass-loader', options: {
            includePaths: ['./node_modules', './node_modules/grommet/node_modules']
          }
        }
      ]
```

I am not familiar enough with meteor to comment on how it should be configured, but hopefully this will get you moving in the right direction.  Good luck!

**Comment by alansouzati** [comment]
Thanks @RyanCCollins this is exactly right. @windgaucho any updates?

I'm going to close this issue since I believe there is nothing to be fixed in grommet. feel free to continue the discussion here. we can always reopen if we identify something to be fixed in grommet.

**Comment by rkahle** [comment]
Sorry for reopening, I just wanted to help future people finding this and trying to use Grommet with Meteor... :)

According to your answer @RyanCCollins you have to use [meteor-scss](https://github.com/fourseven/meteor-scss) and create a **scss-config.json** file at the root of your project with following content:

```json
{
  "includePaths": [
    "{}/node_modules/grommet/node_modules"
  ]
}
```

**Comment by cristiandley** [comment]
@rkahle im getting this error doing the same

```bash
   While building for web.browser:
   /node_modules/grommet/scss/vanilla/index.scss: Scss compiler error: File to import: inuit defaults/settings.defaults not
   found in file: settings
```

**Comment by AaronVasquez** [comment]
I'm having no luck with this too. Has anyone been able to figure this out for meteor 1.5 ?

**Comment by alansouzati** [comment]
to get going quickly can you try to use the minified css instead of the Scss file?

**Comment by AaronVasquez** [comment]
How do I try that?

**Comment by alansouzati** [comment]
I'm not familiar with Meteor, but if you have access to an HTML file you can include grommet styles in the head with a script tag. you can use the path available in CDNJS:

https://cdnjs.cloudflare.com/ajax/libs/grommet/1.8.3/grommet.min.css

**Comment by AaronVasquez** [comment]
nice, using the minified CSS works! Any ideas on how to debug the scss issue?

**Comment by alansouzati** [comment]
Unfortunately I'm not familiar with Meteor, I think there is something that needs to be there if you want to use Meteor with SASS (or any other css pre-processors). But my recent recommendation is to have a separate project for your styles that you can publish somewhere (and the published version will have the minified css). That way you don't need to involve special SASS in any framework.

Take a look in this project: https://www.npmjs.com/package/zoo-grommet

They are overriding Grommet styles using SASS and publishing the result of that in NPM as a minified CSS.

**Comment by cristiandley** [comment]
Hi! i did it " **work** ".

- add [fourseven:scss](https://atmospherejs.com/fourseven/scss)

- create `scss-config.json` at your root with this

```
{
	"includePaths": ["{}/node_modules/", "{}/node_modules/grommet/node_modules"]
}
```

and (of course... import scss at your `main.js` client-side) 

`import "grommet/scss/hpe/index";`

if you struggle... i can upload a `grommet-meteor-example-kit`

**Comment by AaronVasquez** [comment]
@cristiandley you're a life saver! thanks!

**Comment by mvmsaikrishna** [comment]
Hey @cristiandley  I did exactly as you wrote. but I'm getting this error on client 
Uncaught Error: Cannot find module 'grommet/scss/hpe/index'
    at makeMissingError 

Can you please help?Thanks!

**Comment by cristiandley** [comment]
@mvmsaikrishna im sorry the late. Mmmm tested again. Are you sure you `npm install grommet` ?

**Comment by mvmsaikrishna** [comment]
@cristiandley My bad, i should have been clearer. I did according to your comment on oct 13th.

Yes, I installed grommet. As a temp fix, I imported the css file from cdnjs as mentioned by @alansouzati. Styles are working now.

**Comment by cristiandley** [comment]
@mvmsaikrishna  it should be working without importing the css

My `main.js`

```JavaScript
import React from "react";
import { render } from "react-dom";
import { Meteor } from "meteor/meteor";
import LexApp from "../imports/ui/LexApp";

import "grommet/scss/hpe/index";

Meteor.startup(() => {
	render(<LexApp />, document.getElementById("app"));
});
```

My `main.html`

```html
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Grommet Test</title>
</head>
<body>
  <div id="app"></div>
</body>
```

My `MainComponent.js`

```JavaScript
import React, { Component } from "react";

import App from "grommet/components/App";
import Box from "grommet/components/Box";
import Split from "grommet/components/Split";
import LexHeader from "./common/LexHeader";
import LexFooter from "./common/LexFooter";

import { BrowserRouter as Router } from "react-router-dom";

import Rutas from "../lib/Rutas";

class GrommetApp extends Component {
	render() {
		return (
			<Router>
				<App centered={false}>
					<Box colorIndex="light-2">
						<LexHeader />
						<Box>
							<Rutas />
						</Box>
						<LexFooter />
					</Box>
				</App>
			</Router>
		);
	}
}

export default GrommetApp;
```

scss-config.json

```
{
	"includePaths": ["{}/node_modules/", "{}/node_modules/grommet/node_modules"]
}
```

**Comment by mvmsaikrishna** [comment]
Nope.. did exactly like you posted.. still "Uncaught Error: Cannot find module 'grommet/scss/hpe/index'
at makeMissingError: 

Thanks for your patience though! I've decided to implement someother UI framework.

**Comment by alansouzati** [comment]
hey @mvmsaikrishna you probably installed Grommet 2 (which is in alpha mode right now).

To install Grommet 1.x you need to run `npm install grommet@1.9.0`

**Comment by mvmsaikrishna** [comment]
@alansouzati thank you!! that was the problem.. now it's fixed!
But I started playing with Material-UI v1 already :) 

@cristiandley

**Comment by alansouzati** [comment]
all good no problem ;)
