### ISSUE TITLE
resizing with layer up results in layer disappearing

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#138]
http://grommet.io/docs/develop/layer

Example 1
Start at over 720 pixels, resize to under 720, see layer still there (but no longer modal).
Go under 620, watch layer completely disappear.

Example 2
Start under 620px width, 
resize over 620px, watch layer completely disappear.

**Comment by bryanjacquot** [comment]
This has been fixed in Grommet.
