### ISSUE TITLE
Facing CSS Issue while Creating Grommet Components

### ISSUE THREAD

**Issue by nayaksud** [grommet/grommet#1380]
When we are Creating Grommet Components for some of the places we are unable to add CSS, because, grommet has own CSS I have attached here a **sample app** and one **screenshot** can anyone help on the, I want to create as per screenshot.

### Expected Behavior

Want to add custom CSS, so can change margin padding & height as per design below.

https://github.com/nayaksud/Facing-CSS-Issu-while-Creating-Grommet-Components/blob/master/Dummy%20Content.jpg

Input – custom class
check-box - custom class
Header - custom class
select_input - custom class
paragraph - custom class
accordion-panel - custom class
anchor - custom class
             - grommetux-anchor__icon
radio-button - custom class
                      - custom class : checked

### Actual Behavior

If I am adding custom CSS, It won't execute I am getting below CSS which come from grommet CSS.

Getting  grommetux css which is unexpected 
Input – .grommet input:not(.grommetux-input), .grommet select, .grommet textarea
check-box - grommetux-check-box__control-check
Header - grommetux-header 
select_input - grommetux-select__input
paragraph - grommetux-paragraph
accordion-panel - grommetux-accordion-panel__header
anchor - grommetux-anchor
             - grommetux-anchor__icon
radio-button - grommetux-radio-button
                      - grommetux-radio-button__control
                      - grommetux-radio-button__input:checked
grommetux-box--separator-bottom

### URL, screen shot, or Codepen exhibiting the issue

Here I have uploaded a **sample app** src file, Please check & let me know how can I modify CSS.

https://github.com/nayaksud/Facing-CSS-Issu-while-Creating-Grommet-Components/blob/fd4017bd78650b80f07c3f2cedf44a75336b591c/sample-app.zip
  -->

### Steps to Reproduce
 1.  Want to modify Padding through custom CSS
 2. Want to modify Margin through custom CSS
 3. Want to modify Height through custom CSS

### Your Environment

* Grommet version: 1.4.x
* Browser Name and Version: Chrome Edge.
* Operating System and version (desktop or mobile): Desktop, Windows 10.

**Comment by RyanCCollins** [comment]
@nayaksud Grommet does have css built into the library.  The components generate the `grommet-ux...` classnames, so there is really no way to shut that off.  Considering the fact that Grommet is a design language, it should make sense why a large portion of the codebase is built on css.   There are a few ways that you can customize styling of components, however.   

A. You can create your own theme by copying one of the pre-existing themes and making edits. You can find the pre-existing themes [here](https://github.com/grommet/grommet/tree/master/src/scss).
B. You can apply your own selectors that have a higher specificity than the grommet css selectors.

I hope this helps!

**Comment by RyanCCollins** [comment]
By the way, I am going to close this issue to get it off of the Grommet teams backlog.  That said, I'd be happy to keep the conversation going in this thread if you have any further questions!  Thanks!
