### ISSUE TITLE
Facing Problem while adding SVG Logo in Grommet

### ISSUE THREAD

**Issue by nayaksud** [grommet/grommet#1381]
Facing Problem while adding SVG Logo in Grommet

### Expected Behavior

It should render, how it is rendering in HTML

### Actual Behavior

It won't render when adding SVG Logo in Grommet

### URL, screen shot, or Codepen exhibiting the issue
Here I have attached, SVG & EPS file, Please help me on this.

https://github.com/nayaksud/Facing-CSS-Issu-while-Creating-Grommet-Components/blob/master/Api%20Central%20Logo%20Type%20svg.svg

https://github.com/nayaksud/Facing-CSS-Issu-while-Creating-Grommet-Components/blob/master/Api%20Central%20Logo%20Type.eps

### Steps to Reproduce
 1. It should render, how it is rendering in HTML

### Your Environment

* Grommet version: 1.4.x
* Browser Name and Version: Chrome Edge.
* Operating System and version (desktop or mobile): Desktop, Windows 10.

**Comment by alansouzati** [comment]
there are differences with the way JSX renders HTML elements.

Here is a codepen that renders your logo:

https://codepen.io/alansouzati/pen/PjEBwL?editors=0110
