### ISSUE TITLE
Table row cells do not match length of header cells.

### ISSUE THREAD

**Issue by raphi011** [grommet/grommet#1388]
This error message `Table row cells do not match length of header cells.` should not occur when cells with colspan in the body are used

### Expected Behavior
No error message when header and body columns mismatch because of colsspan > 1

### Actual Behavior
Error

### Your Environment
* Grommet version: 1.4.1

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/59b56e65de2bdb1632089e956be1ff95a5870c3e
