### ISSUE TITLE
Arrow Keys in TextInput have unexpected behavior with Distribution component loaded 

### ISSUE THREAD

**Issue by coccyx** [grommet/grommet#1390]
### Expected Behavior
Arrow keys should allow the user to move left and right through the text input

### Actual Behavior
Arrow keys behave erratically.  They do eventually work if you hit the down arrow first and then you can arrow through the text input like normal.

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/clintsharp/pen/qjRaNJ

### Steps to Reproduce
 1. Include `<Distribution>` and `<TextInput>` on the same page
 2. Try to use arrow keys in the TextInput

### Your Environment
* Grommet version: 1.4.1
* Browser Name and version: Chrome Latest
* Operating System and version (desktop or mobile): MacOS X, Windows, Linux

**Comment by alansouzati** [comment]
good catch. thanks for reporting this. I'm working on a fix for this

**Comment by alansouzati** [comment]
Fixed https://github.com/grommet/grommet/commit/03c333a3eb4e5e028b9a238b6248f70cff2b07b2
