### ISSUE TITLE
Copy paste not working for textInput on IE browsers.

### ISSUE THREAD

**Issue by jagatjeevan** [grommet/grommet#1391]
### Expected Behavior
TextInput should be able to accept copied text values from clipboard. 

### Actual Behavior
User should be able to copy and paste to the text values and text should be able to be captured ( in state ) or passed to the function. 

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/kanhajeevan/pen/RgGJyM

### Steps to Reproduce
 1. Copy and paste in the textInput component
 2. In Firefox and Chrome, it would work and update the state
 3. In IE, it would not update the state.

### Your Environment
* Grommet version: 1.4.1
* Browser Name and version: IE 11
* Operating System and version (desktop or mobile): Desktop

**Comment by alansouzati** [comment]
I just tested this with IE11 and I cannot reproduce this issue. :(

**Comment by alansouzati** [comment]
I'm thinking this could be related to some version of React. I will merge the PR though, I tested your change and it still works on all browsers. So I'm sure this is better than what we have.
