### ISSUE TITLE
Update get started docs.

### ISSUE THREAD

**Issue by sclanc** [grommet/grommet#1393]
As a first time user (first exposure within the last 20 minutes) I thought the grommet team might appreciate some feedback: 

It would be lovely if the grommet-cli had a lean option, I want to use the cli because it takes a care of things that I wouldn't want to worry about when implementing the standalone, and I prefer to use npm to install packages, however, I don't need or want all of the boilerplate content  that comes with  the project, I may not want to use react-router, or redux, and I don't need all of the pages. Thanks!

**Comment by alansouzati** [comment]
Good point. We have the type option in the cli. Type basic I believe is exactly what you are looking for. You can type `grommet new --help‘ to see all the available options.

We should probably update the get started page to say that the cli has the help task.

Welcome to our community

**Comment by sclanc** [comment]
Thanks a bunch! I am blown away by how amazing this framework is.
