### ISSUE TITLE
Few options of Select Drop down menu component icon and its label gets stacked to different line [IE specific]

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1394]
### Expected Behavior

Ideally all the menu in the dropdown should come in proper layout and not in broken state.
### Actual Behavior

In few menu icon and its label gets aligned on different line and looks very weird 
Also the code written works on chrome but not on IE
### URL, screen shot, or Codepen exhibiting the issue
Below is the codepen link for the same:
https://codepen.io/nikitam/pen/owWgpM?editors=0001

### Steps to Reproduce
 1. Just open this codepen in IE 
 2. 
 3. 

### Your Environment

* Grommet version: 1.3.4
* Browser Name and version: IE only (11.0.9600.18665IS)
* Operating System and version (desktop or mobile): Windows & linux (Desktop)

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/8121d85648b2f5ce6f1720e79f23b29c2c85f86b

**Comment by agrawalPratik** [comment]
In which version we will get this fix.

**Comment by agrawalPratik** [comment]
@alansouzati In which version we will get this fix.

**Comment by alansouzati** [comment]
this is already present in Grommet 1.5.0
