### ISSUE TITLE
Some FormField props aren't documented

### ISSUE THREAD

**Issue by XuluWarrior** [grommet/grommet#1395]
I can see in the code that FormField has the following props

- error
- help
- htmlFor
- label
- hidden
- size
- strong

However, the documentation at https://grommet.github.io/docs/form-field only describes the first four.

**Comment by alansouzati** [comment]
Thanks for reporting this. Are you up for a pull request to fix this?

The source code for the form-field in the docs is here: https://github.com/grommet/grommet-docs/blob/master/src/docs/components/form-field/FormFieldDoc.js

**Comment by XuluWarrior** [comment]
In principle I am happy to contribute but I didn't really get very far working out the intended semantics for "size" and "strong".  I can see that they have corresponding css to change the font size and weight.

This seemed a bit counter-intuitive to me as I expected size to affect the size of the field.  Which is what I was looking for (I was interested in creating a narrow TextField as it only needs to take a four digit number) .  But as it didn't do this I looked for other ways to do what I wanted and stopped looking through the FormField code/css.

**Comment by alansouzati** [comment]
fair enough. I will make sure to add documentation for these fields.

**Comment by cherih** [comment]
Added documentation for the hidden, size and strong properties to the grommet.io FormField component page.

See PR#276 in grommet-docs project.
