### ISSUE TITLE
Accordion component is using Number.isInteger call that is not supported in Internet Explorer 11

### ISSUE THREAD

**Issue by jrkirkwood** [grommet/grommet#1399]
Accordion component fails to load in Internet Explorer 11 due to Number.isInteger call
### Expected Behavior

Accordion should load without issue in IE11

### Actual Behavior

Page fails to load when Accordion is on it.  Gets error:
Line: 106
Error: Object doesn't support property or method 'isInteger'

I added a manual fix to Accordion.js for IE11:
replaced line 58 - "if (Number.isInteger(_this.props.active)) {"
with "if(_this.props.active === parseInt(_this.props.active, 10)){" to get around this issue.

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/jrkirkwood/pen/yXbEEK or just go to Grommet examples page using IE11: https://grommet.github.io/hpe/docs/accordion/examples/

### Steps to Reproduce
 1.  Add Accordion component to any page
 2. Try to open with IE11
 3. 

### Your Environment

* Grommet version: 1.4.1
* Browser Name and version: IE 11
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by cherih** [comment]
Was able to reproduce this and am working on the fix.

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/pull/1402
