### ISSUE TITLE
Form in layer leaves search dropDown behind

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#140]
http://grommet.io/docs/develop/layer
If you have a dropDown visible (from the search on say Edit, left) and then click outside the layer, the dropDown is left behind.

Furthermore, it isn't possible to get the dropDown to go away. By clicking one of the options or clicking outside of the option.

Reproduced in IE11 and chrome. Resizing the window moves it to the top-left.

Chrome
![dropdown visible](https://cloud.githubusercontent.com/assets/13527666/9181550/caeb96fc-3f62-11e5-914a-5703277d5acf.png)

IE11 (after resize of window)
![dropdown visible -ie11](https://cloud.githubusercontent.com/assets/13527666/9181674/71648598-3f63-11e5-81e3-eab26cb6751b.png)

**Comment by jwijay** [comment]
Closing this issue, since it appears resolved when testing in Chrome, Firefox, and Safari. Dropdown no longer lingers when clicking outside the Layer and resizing the window.
