### ISSUE TITLE
Text Box error alignment is inconsistent for different sizes

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1400]
It has been observed when we do form validation, error text in the textbox gets aligned in an improper fashion.
### Expected Behavior

Alignment of the error text should be maintained and should not vary with different textbox sizes
### Actual Behavior

Alignment of the error text is not maintained in different textbox sizes
### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/jaiswal/pen/MoopZj

### Steps to Reproduce
 1. gave one example in the codepen
 2. 
 3. 

### Your Environment

* Grommet version: 1.3.4
* Browser Name and version: all browsers
* Operating System and version (desktop or mobile): windows and linux [Desktop]

**Comment by dgennetten** [comment]
The pen shows the label left-justified and the error right-justified.  They stack when there's insufficient room.  This example alone, I believe, shows "expected behavior.  However, there is still an issue when the two elements wrap. Here is an example: https://codepen.io/dgennetten/pen/XggxVE?editors=0010

**Comment by alansouzati** [comment]
Well I believe we should not be wrapping the Form in a box size Small. it is pretty narrow and difficult to use.

Here is the codepen with the proper combination of FormFields and FormField

https://codepen.io/alansouzati/pen/vZJVaM?editors=0010

**Comment by alansouzati** [comment]
Notice the usage of compact in there.

**Comment by agrawalPratik** [comment]
@alansouzati In which version we will get this fix.

**Comment by alansouzati** [comment]
There was not fix for this. so your existing grommet should support this already.

**Comment by agrawalPratik** [comment]
hi @alansouzati sorry I didn't get it, is this issue rectified or do we need to change something from our end in the code to solve the issue.

**Comment by alansouzati** [comment]
Did you check the codepen ? https://codepen.io/alansouzati/pen/vZJVaM?editors=0010

You need to use compact prop.

**Comment by agrawalPratik** [comment]
HI @alansouzati,

I completely missed it as I thought you were in conversation with the other guy.

I will ask my team to use this as recommended by you.

Thanks for your help.

Regards,
Pratik Agrawal
