### ISSUE TITLE
[Question] How to change to dark theme

### ISSUE THREAD

**Issue by KenLeeKH** [grommet/grommet#1406]
Hi
I am exploring grommet and am wondering how I can change it to dark theme instead of the light theme? Is there any place I can check? Thanks.

**Comment by alansouzati** [comment]
Hi @KenLeeKH we don't have color themes but brand themes. For example you could use the HPInc theme as opposed as the HPE theme. Our theme capabilities is for a brand which will often have a different color palette.

For example, these are the colors for the Grommet theme: https://grommet.github.io/docs/color

On the other hand, there are the colors for the HPE theme: https://grommet.github.io/hpe/docs/color/

If you want your app to have a Dark context I would wrap a Box around your main Grommet App with a dark colorIndex, check this codepen:

https://codepen.io/alansouzati/pen/qjydKw?editors=0010
