### ISSUE TITLE
React & react-redux issues cause Grommet TextInput to lose caret position

### ISSUE THREAD

**Issue by linde12** [grommet/grommet#1409]
There are currently issues with React and react-redux regarding caret position within a text field. The issue appears when you update state(causing a re-render) in your controlled input component before new props are received from the parent component.

Let's look at an example with a `TextInput` component.

Normal flow is:
1. Change happened(e.g. `lind` -> `linde`), call parent's onDOMChange callback
2. Parent sends new props(`value`) to child
3. Child is re-rendered with new value prop and caret position is automatically kept unless transformations(e.g. number formatting) was made

Flow with setState _can_ be:
1. Change happened(e.g. `lind` -> `linde`), update some internal state(`setState`) & notify parent with onDOMChange callback
2. `setState` causes component to re-render with the old value(`lind`), assuming new value hasn't arrived via props yet(race condition, try using a setTimeout to reproduce)
3. Parent sends new props(e.g `linde`) to child
4. Since the value of actual node != the value in props, React think's that you've completely replaced the value with something new & loses caret position(it goes to the end of the input)

This is basically a setState race, and has been fixed on React master. React-redux worked around it but then replaced their fix with a more "neat" fix, that unfortunately didn't work.

You can read more about it over here https://github.com/reactjs/react-redux/issues/525 and i made two fiddles to show you how the problem in different  versions of react-redux:
`react-redux@5.0.5` (bug shows) - https://jsfiddle.net/hqoohq4b/
`react-redux@5.0.0-rc.1` (works) - https://jsfiddle.net/hqoohq4b/1/

The problem applies to Grommet because Grommet's `TextInput` calls `setState` in its `onDOMChange` handler. [See here](https://github.com/grommet/grommet/blob/master/src/js/components/TextInput.js#L127).

My suggestion is to temporarily only do the `setState` call if a user has passed suggestions to the `TextInput`, so that people who don't use suggestions for their `TextInput` won't get the jumping caret problem.

If more information is needed you can write here or on slack.

### Expected Behavior
`TextInput` caret position should be kept

### Actual Behavior
`TextInput` caret position is set to the end of the input, making it very hard to edit text.

### URL, screen shot, or Codepen exhibiting the issue

I don't have a codepen using the Grommet component, but it's the same principle with normal inputs.
`react-redux@5.0.5` (bug shows) - https://jsfiddle.net/hqoohq4b/
`react-redux@5.0.0-rc.1` (works) - https://jsfiddle.net/hqoohq4b/1/

### Your Environment

* Grommet version: 1.4.1
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Debian Jessie, desktop

**Comment by alansouzati** [comment]
Thanks for this issue. How about people who are using the `suggestions`? 

I would rather find a fix that fix the solution for both cases. Can you create a codepen that reproduces this problem in Grommet?

**Comment by alansouzati** [comment]
yeah that's weird I could not find a better solution :( I will merge your PR
