### ISSUE TITLE
Unwanted scroll bar presence is observed when side layer is opened [IE Specific]

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1410]
When you open a layer in IE, scroll of the main page is visible on the layer for few seconds which makes the UI very ugly.
### Expected Behavior

Main page scroll should not be shown on layer
### Actual Behavior

Main page scroll appears on the layer
### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/docs/layer/examples?align=left&closer=true&i-contents=form

https://grommet.github.io/docs/layer/examples?align=left&closer=true&i-contents=form
### Steps to Reproduce
 1.  just open this link in IE 11.0.9600.18697IS
 2. 
 3. 

### Your Environment

* Grommet version: current version
* Browser Name and version: IE 11.0.9600.18697IS
* Operating System and version (desktop or mobile): desktop windows & linux
![ie_scroll_issue](https://user-images.githubusercontent.com/23493164/27823839-1e8be162-60c8-11e7-8b55-12bbe014ca9d.png)

**Comment by alansouzati** [comment]
I cannot reproduce this

![Screen Shot 2017-07-06 at 1.17.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555234953a6a9e8f00e8ff55/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246454f56b7191a379f1132c4f5b5e5ecc3c4a4356bcbbd671f3e57862804e0eebd93b0a76ce3b14fdb9d31abb07b2208b48d3e4bdd819d2f42f67b6d5db1063474f4dcbed5727a39841c95cff42e24a57a7173e61e7732431.png)

**Comment by alansouzati** [comment]
can you update your IE11 ?

**Comment by agrawalPratik** [comment]
Hi Alan,

I can still reproduce on my IE my version is 11.0.9600.18697IS
![ie-issue](https://user-images.githubusercontent.com/23493164/28003294-44d420e6-655a-11e7-8b3c-f42328ed5943.png)


@alansouzati : Issue is very tricky follow below steps:
1 - First hover on the Options form of layer you will see a scrollbar , initially there is no scrollbar but once you hover on it you will see the scrollbar in the form
2- After seeing the scrollbar in the Options pane, quickly click on the show layer button and then you will be able to see the option pane scrollbar coming on the layer form, scrollbar will be there for very few seconds so you need to do it quick.

I hope this helps.

**Comment by alansouzati** [comment]
I still cannot reproduce it. Can you update to the latest IE11?

This can be and most likely is a browser issue. Check out this page, the supported browser version is always supposed to be the latest:

https://grommet.github.io/docs/browser-support

**Comment by bryanjacquot** [comment]
@alansouzati I've observed this as well in a different product, not using IE.  I'll send you a link to an internal site.

**Comment by agrawalPratik** [comment]
yes @alansouzati it is a browser issue and I have checked my browser version its updated and its IE 11.x as per your support docs.

**Comment by L0ZZI** [comment]
Need to validate on Grommet v2.
