### ISSUE TITLE
Extra drop-down caret icon is seen on the filter box [IE specific]

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1411]
When you open any filter box, in that if you open a dropdown user can see two dropdown caret icon
### Expected Behavior

When you open any filter box, in that if you open a dropdown user should see only one caret icon
### Actual Behavior

When you open any filter box, in that if you open a dropdown user can see two dropdown caret icon
### URL, screen shot, or Codepen exhibiting the issue
![ie_dropdown-caret-issue](https://user-images.githubusercontent.com/23493164/27824025-bccb9656-60c8-11e7-9e31-f8db5c15746b.PNG)
http://index.grommet.io/docs/grommet-index/filters

http://index.grommet.io/docs/grommet-index/filters
### Steps to Reproduce
 1. Just see the screenshot OR open the link in the IE
 2. 
 3. 

### Your Environment

* Grommet version: current version
* Browser Name and version: IE 11.0.9600.18697IS
* Operating System and version (desktop or mobile): Desktop: windows & linux

**Comment by alansouzati** [comment]
this seems to be a grommet-index filter which is a separate project.

The core grommet team does not maintain grommet index anymore. The reason we stopped maintaining it was the fact that it has too many abstractions  in place.

Could you please open an issue against [grommet-index](https://github.com/grommet/grommet-index)? We are relying in the community to jump in and fix any issues related to Grommet index project.

I'm closing this issue in Grommet core.

**Comment by agrawalPratik** [comment]
Yup I have added this in grommet-index page, thanks
