### ISSUE TITLE
Date Time Input box allows String/Characters entry issue 

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1415]
Date Time input box allows user to enter characters & strings which create issue for form validation 
### Expected Behavior

Date time input box should not allow characters & strings only numbers
### Actual Behavior

Date Time input box allows user to enter characters & strings which create issue for form validation 
### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/hpe/docs/date-time/examples/?format=H%3Amm%3Ass

### Steps to Reproduce
 1. Just use this link https://grommet.github.io/hpe/docs/date-time/examples/?format=H%3Amm%3Ass
 2. 
 3. 

### Your Environment

* Grommet version: current version
* Browser Name and version: All browsers
* Operating System and version (desktop or mobile): Desktop : Windows & linux

**Comment by alansouzati** [comment]
Thanks for reporting this, but this is not a bug.

Your form validation should let the user know that the date is invalid. I would not recommend removing string characters, for example this is a valid date: `12/20/1987 4:15pm` and it has a bunch of characters in it.

Take the Expedia site an example: https://www.expedia.com

**Comment by agrawalPratik** [comment]
Hi Alan, I am talking about only time input box, wherein user don't enter AM or PM, they just enter numeric value, also user should be able to enter time manually without colons. Can you please reopen this issue. @alansouzati

**Comment by alansouzati** [comment]
Even in that case we do not recommend removing characters. Our pattern is to let the user type the wrong input and validate when you submit the form. I would be happy to reopen the issue if we identify anything that needs to be changed in Grommet.

**Comment by alansouzati** [comment]
If you really want to remove the character you can listen to `onChange`. Grommet will not add that as a built-in solution as it is not a recommended pattern.

**Comment by agrawalPratik** [comment]
okk thank you @alansouzati I will assign this to my team and will check if that helps us or not. Thanks
