### ISSUE TITLE
`TextInput` highlights value on when tabbing back in

### ISSUE THREAD

**Issue by sotojuan** [grommet/grommet#1417]
### Expected Behavior

Tabbing back into an input doesn't do anything.

### Actual Behavior

Tabbing back into an input highlights/selects the text.

### Steps to Reproduce

 1.  https://grommet.github.io/docs/text-input
 2.  Type in text input
 3.  Go to another browser tab or app window
 4. Come back
 5. Text is highlighted/selected

### Your Environment

* Grommet version: (1.5.0)
* Browser Name and version: Chrome version 59.0.3071.115 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): macOS Sierra

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/d6858fd5577d34758d098b35c2b04a8ca8c45d71

**Comment by sotojuan** [comment]
Thanks!
