### ISSUE TITLE
When Layer opened from Menu it does not capture full keyboard focus

### ISSUE THREAD

**Issue by dunnock** [grommet/grommet#1419]
### Expected Behavior
Layer opened from Menu item should capture full keyboard focus

### Actual Behavior
Partially focus stays with Menu button, pressing `space` opens DropMenu

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/maximvorobjov/pen/rwqKjW

### Steps to Reproduce
 1. Open Menu drop down
 2. Click `Form in layer` action
 3. Put cursor in the TextInput inside Layer. Press `space`

### Your Environment
* Grommet version: 1.5.1
* Browser Name and version: Google Chrome 59
* Operating System and version (desktop or mobile): Mac OS X 10.12.4

**Comment by dunnock** [comment]
Just FYI there is workaround: when opening Layer do not display Menu

**Comment by alansouzati** [comment]
@dunnock and I identify the fix for this. he will be sending a PR soon
