### ISSUE TITLE
Form alignment is off for drop downs

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#142]
http://grommet.io/docs/develop/form

Alignment with a drop down is different than dates and input boxes. Same on IE, firefox, and mobile android.
![alignment](https://cloud.githubusercontent.com/assets/13527666/9182025/6632890c-3f65-11e5-9a94-a1e60996d392.png)

**Comment by kylebyerly-hp** [comment]
This may need a bigger fix than simple CSS to work on all browsers.

**Comment by bryanjacquot** [comment]
It seems Chrome and Safari are properly aligned.  Firefox is a bit off.  IE is tbd.

**Comment by jwijay** [comment]
PR pending: https://github.com/grommet/grommet/pull/753
