### ISSUE TITLE
Some colors are not being applied on Line component

### ISSUE THREAD

**Issue by gustahrodrigues** [grommet/grommet#1423]
I'm trying to set colorIndex from [color page](https://grommet.github.io/docs/color) of the [Line component](https://grommet.github.io/docs/chart/line), but some of them are not bein applied.

### Expected Behavior

Colors index available on [color page](https://grommet.github.io/docs/color) should be applied on Line component.

### Actual Behavior

Some colors are not being applied.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/2227228/28133806-832f4bea-6717-11e7-95ac-2fac7b1318a1.png)

https://codepen.io/gustahrodrigues/pen/NgeZBN?editors=0010

### Your Environment

* Grommet version: Codepen
* Browser Name and version: Chrome 59.0.3071
* Operating System and version (desktop or mobile): Desktop, Windows 10

**Comment by RyanCCollins** [comment]
Hey @gustahrodrigues you're right this is quite confusing.  Thank you for posting an issue about it.  I believe that the chart components have custom colorIndex options, i.e. `graph-1` and `graph-2` but I'm not sure of the reason for that and why the regular options do not work.  

Hopefully one of the other core team members can comment about this.

**Comment by cherih** [comment]
@gustahrodrigues - we currently don't support all colors for the Chart component. The graph-* colors can definitely be used.

We wanted to restrict the colors that are available to those that work well together.  For example, accessibility/contrast issues can arise from some color combinations. Also, we support fewer colors to keep the size of the CSS code down. 

We are considering re-evaluating this issue for grommet 2.0, as we work on modifying how colors are handled in grommet.

**Comment by karatechops** [comment]
I'm closing this as I've tagged our 2.x Chart card and documented the feedback there. From what I can tell from the next branch's code, 2.x Chart will fully support all color indexes.
