### ISSUE TITLE
Select does not render label JSX in selected value

### ISSUE THREAD

**Issue by drewlustro** [grommet/grommet#1425]
Since version `1.5.0`, Grommet's Select dropdown component can render rich JSX, as long as the JSX is passed into an option's `label`. For example, an option authored like this will render as a rich image in the select dropdown:

```js
const options = [
  { label: <img src="http://i.imgur.com/iZS0F7D.jpg" />, value: 2}
  // .. more options ...
];
```

However, Grommet's Select component **does not** support rendering the currently selected value's label as JSX in dropdown (non-inline) mode. The component only supports strings, which creates a mismatch of expectations.

Instead, the JSX renders as `[object Object]` upon selection.

---

### Expected Behavior

Grommet Select `value` should be able to render JSX labels as the selected `value`, as rich labels are supported on the dropdown options.

### Actual Behavior

Grommet renders the selected `value` as a string, resulting in a visual `[object Object]` when the `option.label` is JSX.

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/drewlustro/pen/zzeyxW

### Steps to Reproduce
 1. Create Grommet Select
 2. Provide rich JSX as the label in each option of the form `{ label: <span>somejsx</span>, value: 100}`
 3. Activate the dropdown and choose a rich JSX option. Upon selection, the active `value` renders as a string `[object Object]` instead of JSX.

### Your Environment

* Grommet version: 1.5.0
* Browser Name and version: Chrome 59.0.3071
* Operating System and version (desktop or mobile): macOS 10.12.5 / desktop

---

### In Action GIF

![screen recording 2017-07-13 at 02 36 pm](https://user-images.githubusercontent.com/194885/28182056-b1b52fa4-67d8-11e7-9c16-bb5b8761e1d3.gif)

**Comment by alansouzati** [comment]
Yeah this is a limitation of the Select component as of now. The underlying component behind the selected value is an `input` which does not allow anything but text. I will keep this open and evaluate other solutions for Grommet 2.0. Thanks for raising this issue.

**Comment by drewlustro** [comment]
Forgive me, but I guess I am not sure why this is a limitation when both `option.label` and `option.value` support rich assignment.

The `<input type="text" />` tag is `GrommetSelect`'s proxy of native `<select>`. It's already an abstract representation... why let the abstract representation impose limitations on its parent?

I cannot say I've dug into the code to find how straightforward it would be to echo `option.label` as JSX, but it surprises me that this is considered a `2.0` feature.

What is the point of having a JSX `option.label`?

**Comment by alansouzati** [comment]
if you look at this line: https://github.com/grommet/grommet/blob/master/src/js/components/Select.js#L441

You will see the input is used as a readonly element. Also if you search for `this.inputRef` you will see that we pass that to existing Grommet 1.X users. This is a 2.0 feature because we cannot remove support for that as it will be mostly likely a breaking change if you are using the input reference.

We will take your request into consideration when redesigning Grommet Select during 2.0. Grommet 2.0 is already in the works. If you can find a fix for that without having a breaking change I'm happy to review and approve your pull request.

We are using the Label with rich JSX today with Select but we don't hold the selected value in the Select itself. But I agree with you, if it a frustrating experience to have rich JSX support in the label but not in the selected value.

Hopefully it clarifies your questions 😃

**Comment by drewlustro** [comment]
Very clear, thank you!

>  If you can find a fix for that without having a breaking change I'm happy to review and approve your pull request.

💯

**Comment by RyanCCollins** [comment]
Woo, grommet 2.0!!! 🎉

**Comment by drewlustro** [comment]
:beers: Added React component support to Grommet Select's `render()` in #1426

I do not believe there are any regressions. All tests pass.

**Comment by alansouzati** [comment]
Nicely done. Just came back from a happy hour. I will merge this first thing tomorrow, cheers

**Comment by drewlustro** [comment]
Awesome!

**Comment by florianbepunkt** [comment]
Is there an example how to use this? I found nothing so far… using grommet@1.8.3 and when specifying options as object my `<Select />` component shows `'object object'`.

**Comment by drewlustro** [comment]
@florianbepunkt Your `options` object has two keys: `label` and `value`.

With my PR that was merged this summer, both `options.label` supports JSX (ex: another React component) instead of a plaintext label.

**Comment by florianbepunkt** [comment]
@drewlustro Thank you
