### ISSUE TITLE
Table#onMore callback does not get called on small display

### ISSUE THREAD

**Issue by tvojtech** [grommet/grommet#1427]
`Table#onMore` callback does not get called initially under some circumstances
- used in `Split`
- `Split`s left part is longer than browser window
- window width is small so `Split`s left part is not visible

### Expected Behavior
`onMore` callback gets called

### Actual Behavior
`onMore` callback does not get called. Table header and spinner icon is displayed forever. Resizing window causes immediate `onMore` call.

![image](https://user-images.githubusercontent.com/1427446/28218830-0e25e83c-68ba-11e7-825c-c9f6281b69dc.png)

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/blaf/pen/weOqvB

### Steps to Reproduce
 1. Reduce window width to see just right half containing table. Left half must be hidden.
 2. Click Run

### Your Environment

* Grommet version: 1.5.0
* Browser Name and version: Chrome Canary, Chrome 59.0.3071.115
* Operating System and version (desktop or mobile): Mac OS Sierra

**Comment by karatechops** [comment]
As I stated in #1428 I'm not able to replicate this in OSX / Chrome / Grommet 1.7.0, I presume it was fixed in 1.6.0.
