### ISSUE TITLE
Icon within Table isn't rendered in the center(vertically) of the TableRow

### ISSUE THREAD

**Issue by linde12** [grommet/grommet#1430]
If you have an `Icon` within a `Table` it isn't rendered in the center(vertically). This is due the the `display: inline-block;` property of the `Icon` which seems to add some extra padding.

It might be because the bottom of the text and the bottom of the icon should be aligned? But in our case we want the center of the icon to be in the center of the table row(because we have css to which adds lines between every table row, like in the codepen i submitted, otherwise it looks weird)

### Expected Behavior
Icon should be vertically centered, just like text is

### Actual Behavior
Icon is closed to the bottom border than the top border of the `TableRow`

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/anon/pen/vZwJMw?editors=0110

### Steps to Reproduce
 1. Create Table with a few rows
 2. Add the custom css(see codepen demo) to display lines(so it's easier to see)
 3. Add an icon to one of the tds
 4. Verify that the icon is not vertically centered, but instead it's bottom looks to be aligned with the text

### Your Environment

* Grommet version: 1.4.1, 1.5.0
* Browser Name and version: Google Chrome Beta 60
* Operating System and version (desktop or mobile): Debian Jessie

**Comment by dgennetten** [comment]
It appears this is fixed?  grommet 1.7.0, chrome 60.

**Comment by dgennetten** [comment]
I believe this is behaving correctly now. Please let us know if you're still having issues.

**Comment by Santiago8888** [comment]
In my case, it wasn't. 🤕
