### ISSUE TITLE
Allow to close a menu programmatically

### ISSUE THREAD

**Issue by Gehbrial** [grommet/grommet#1432]
The Menu component should possess a prop that dictates whether it should be open or not. This would allow us to close it programmtically.

### Expected Behavior
I have a menu with multiple checkboxes (you can select more than one before closing the menu). The menu also has an anchor that opens a modal (which allows to add more checkboxes to the menu). I should have the option to close the menu before opening the modal.

### Actual Behavior
Since I'm forced to set the 'closeOnClick' prop to true to allow multi-selection, the menu remains open when the modal pops.

### URL, screen shot, or Codepen exhibiting the issue
http://imgur.com/5Wzp3Ul

### Your Environment

* Grommet version: 1.4.0
* Browser Name and version: Google Chrome
* Operating System and version (desktop or mobile): Windows 10, 64 bits

**Comment by karatechops** [comment]
Hey @Gehbrial, thanks for filing this issue and providing great feedback. I do agree Menu should be able to programmatically be set. As we're approaching 2.x we're not currently implementing new features into 1.x. I'm going to tag 2.x's Menu card ( #1475 ) so we can be sure to include this featue as I think it is a great addition to Menu.

In the mean time if you still have not solved this in your app you could artificially trigger a click event on your menu. I've created a [Codepen](https://codepen.io/karatechops/pen/rGBMGz?editors=0010) which demonstrates how to trigger a click event on the menu using React's refs. While this is not a perfect solution it will work in your app while we work to create this feature in 2.x. Thanks again for your feedback!

**Comment by alansouzati** [comment]
Indeed a good suggestion. Today I'm working to add Menu to Grommet 2.0. I will make sure to incorporate this 👍

**Comment by drewlustro** [comment]
**+1 on this.**

Not sure why `<Menu closeOnClick={false} ...>` is provided as an API when `Menu` is not closable programmatically.

**Comment by blyefd** [comment]
Here's a little hack...

```
<Menu ref={(c)=>{this.menu = c;}} closeOnClick={false}>
...
</Menu>
```
when you want to close the menu programatically:
`this.menu._onClose();`
