### ISSUE TITLE
Annotated meter is not rounding off decimal values

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1433]
In Annotated Meter as shown below:
<AnnotatedMeter align='center' size='small' type='bar' stacked={true}
                    series={series}
                    units='GB'
                    max={max}
                    legend={{placement: 'bottom', total: false, align: 'center'}}
                  />
We pass max value to the Annotated Meter component. But inside the component it calculates this value without using our max value.

### Actual Behavior

Annotated meter should 
### URL, screen shot, or Codepen exhibiting the issue
Codepen - https://codepen.io/nikitam/pen/KqYBBP?editors=1010 
We also tried to create codepen with annotated meter but that wasn't working, below is the link:
https://codepen.io/nikitam/pen/VWOdLN?editors=0000

### Steps to Reproduce
 1. Please use codepen link
 2. 
 3. 

### Your Environment

* Grommet version: 1.3.4
* Browser Name and version: All browsers
* Operating System and version (desktop or mobile): Desktop , Windows

**Comment by karatechops** [comment]
Hey @agrawalPratik, thanks for filing this issue. This seems like it may be by design, you can always use Javascript's Math methods to round off the properties. Here's a [Codepen](https://codepen.io/karatechops/pen/BdXqgr?editors=0010) displaying rounding the values.

**Comment by agrawalPratik** [comment]
Hi @karatechops just had a discussion with my team and they said this change will be in grommet library file and they are not allowed to do that, looking forward for new resolution for this.
