### ISSUE TITLE
React PropTypes warnings

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#1434]
React 15.6.1 is giving warnings: 
"Accessing PropTypes via the main React package is deprecated, and will be removed"

For: 
https://github.com/grommet/grommet/blob/master/src/js/components/Anchor.js
import { schema, PropTypes } from 'react-desc';

### Expected Behavior
no warnings

### Your Environment
* Grommet version: 1.5.0

**Comment by karatechops** [comment]
Hey @primozs, thanks for filing this issue. I'm not able to reproduce this locally on React 15.6.1 / Grommet 1.7.0, I presume it to be fixed at this point. I've also reviewed react-desc and grommet which are both correctly using the PropTypes package.
