### ISSUE TITLE
Can't change the size of the DateTime box

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1437]
Can't change the size of the DateTime box to small/medium/large, by default it takes medium/full space available which doesn't provide flexibility in the look & feel
### Expected Behavior

there should be a provision to add sizes in the date time component like other components 
### Actual Behavior

Can't change the size of the DateTime box to small/medium/large
### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/docs/date-time

### Steps to Reproduce
 1. Use the link
 2. 
 3. 

### Your Environment

* Grommet version: current version
* Browser Name and version: all browsers
* Operating System and version (desktop or mobile): desktop : windows

**Comment by ThanosDi** [comment]
I have the same issue here and I sadly see that there is no update from this ticket 
https://github.com/grommet/grommet/issues/1169

**Comment by karatechops** [comment]
Hey @agrawalPratik, thanks for the feedback. I don't think we will provide size props but it's current form is probably too rigid. We'll look into it for 2.0.
