### ISSUE TITLE
Need default "Grommety" styling and option for required form fields

### ISSUE THREAD

**Issue by eoliphan** [grommet/grommet#1444]
Generally speaking Form UI's provide some sort of standard indicator for required fields as a visual aid to the user such that at least that requirement can be met prior to running pre-submission validations.

The current elements/FormField wrapper don't provide any way to express this

**Comment by dgennetten** [comment]
And established pattern with grommet is extreme simplicity. One aspect of that is the preference to push forms toward a state of only including required fields.  This is why they are not labelled 'required' as that is the assumption. 

Occasionally, we'll insert an optional field and specifically label it " xyzzy (optional)"

We're always trying to reduce enterprise form lengths for overall usability and clarity.
