### ISSUE TITLE
Add chart to grommet next

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#1447]
This card includes all the components inside the chart folder like Range, Line, Axis, Area...

**Comment by karatechops** [comment]
I see this is closed but I wanted to tag #1423 as it raises a good point of which color indexes Chart supports. Judging by the Chart code in the Next branch is looks like it supports all color indexes.

**Comment by karatechops** [comment]
Documenting #1333 and #1362 - Users would like the ability to include negative integers in their Charts. I believe it would function similar to the below image - 
![screen shot 2017-09-11 at 3 25 42 pm](https://user-images.githubusercontent.com/5983843/30292809-812f54fc-9705-11e7-94b6-68a7a080fc09.png)
