### ISSUE TITLE
Add Pulse to grommet next

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#1449]

**Comment by alansouzati** [comment]
Do we need this as a core Grommet component? We believe this should be in Grommet inspire.

**Comment by ericsoderberghp** [comment]
Agreed that I don't think it belongs in grommet 2.0. I'm not sure it belongs in grommet-inspire either. I think it's just some CSS decoration which seems a bit outside the scope of grommet.

**Comment by alansouzati** [comment]
cool. closing this issue.
