### ISSUE TITLE
Add Spinning to Grommet next

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#1450]

**Comment by karatechops** [comment]
#1600 raises a good point that the Spinning component starts hidden and animates itself in, for quick load times you barely get a glimpse of the loader. If we're using the same animation for 2.0 let's consider reversing it.

**Comment by iMerica** [comment]
What ended up happening to this? I'm not seeing it anywhere on the v2 site.

**Comment by leonardobork** [comment]
2020. Big issue

**Comment by YassienW** [comment]
Pretty basic component that should be added

**Comment by jjalonso** [comment]
+1 for spinning anim
