### ISSUE TITLE
Add List and ListItem to grommet next

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#1472]

**Comment by L0ZZI** [comment]
We don't support this now in v2?

**Comment by guillaumeLamanda** [comment]
It would be great to have this in v2 😄

**Comment by alansouzati** [comment]
Hey @guillaumeLamanda this is actually already possible in v2. We thought initially to explicitly add these components, but I think this is pretty straight forward in V2. Check this codesandbox:

https://codesandbox.io/s/9ljmy5xjoo

I'm closing this issue because I think our inclination at this point is not to add List and ListItem. Please let me know what you think of this codesandbox. We can revisit, but notice that List and ListItem is a only line component.
