### ISSUE TITLE
Add Map to grommet next

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#1473]

**Comment by karatechops** [comment]
PR #1369 attempted to introduce onHover/active color index swaps. I like this idea and discussed it yesterday with @ericsoderberghp, he likes the approach of tinting the existing color index which seems like a good suggestion. It would be helpful to be able to pass an object or a string to the colorIndex prop - `colorIndex={{ base: 'xyy', active: 'xyx' }}`

**Comment by ericsoderberghp** [comment]
For v2, we now have the `Diagram` component. It replaces Topology and Map from v1. The links can be colored more flexibly too, using an opacity strength.
