### ISSUE TITLE
Add Select to grommet next

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#1484]
This card also needs to evaluate the need for a SelectInput that uses the native input control.

**Comment by karatechops** [comment]
#1226 displays an interesting approach to multi select. It's my suggestion a multi select component either lives on its own or in grommet-addons.

**Comment by karatechops** [comment]
#1537 is a feature request for defaulting onEnter events to select the first suggestion. We could bubble up the onEnter event and let the user do what they want with it - this way we can maintain solid accessibility but provide users with the flexibility to add features like the requested feature.

**Comment by karatechops** [comment]
#1625 makes a great point, most of our form elements can exist in an app without being connected to a containers state. It may be worth giving Select some internal methods to track state if onChange is not passed in via a prop.

**Comment by panigrah** [comment]
@karatechops what is the reason for not having Select maintain its own state? The native select control maintains its state and Select should mirror that behavior.

**Comment by karatechops** [comment]
@panigrah that is why I've documented the feature request here. I'd like to see Select track it's own state unless an onChange prop is passed in. Retrieving the value of the Select which tracks its own state feels a bit wonky but some folks are traversing the DOM for form values.

**Comment by panigrah** [comment]
@karatechops  I am trying to learn more about how grommet is built so wanted to understand the rationale behind the current implementation. 

We retrieve the value of all other fields include the simple textfields so I dont see why people would find it wonky! For newbies its easier to assume all controls behave the same.

I can see `Select` fits into a category of components people use to dynamically update other parts of the page. And guessed thats why it was designed differently.
 
thanks for looking into my other problem.
