### ISSUE TITLE
[Medium App]  Unable to load all 150 resources

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#149]
Spinning for a couple of mins to load 150 server hardware and server profiles (all browsers)
Loading enclosure is fine.

![image](https://cloud.githubusercontent.com/assets/13039669/9205103/14689264-4015-11e5-9d68-db933ac4e2f6.png)

**Comment by bryanjacquot** [comment]
This has been addressed in http://ferret.grommet.io/
