### ISSUE TITLE
Add Toast to grommet next

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#1496]

**Comment by karatechops** [comment]
Has there been a discussion regarding keeping Toast/Layer in the app DOM node tree? I've run into issues a few times regarding how these two components render themselves in the DOM. What was the inherit issue that drove to rendering these components outside of the app?

**Comment by ericsoderberghp** [comment]
The trick with these are when the component initiating them is not the outermost component. Putting it in the DOM where the the component initiating it resides could result in the Toast or Layer to be eclipsed based on the element + styling hierarchy. For instance, if the component initiating the Toast is inside a Box inside a Split, it will not necessarily be able to span the entire width of the screen. Putting it inside the `<body/>` allows us to pin it appropriately.

**Comment by RyanCCollins** [comment]
One option would be to use something like [react-portal](https://github.com/tajo/react-portal).

**Comment by L0ZZI** [comment]
@RyanCCollins any chance you want to build an example of Toast in Grommet v2? Not the component, but try and use the new lib?

**Comment by RohitoOo** [comment]
Is anyone able to get Toast Messages working for v2.grommet ? The v1 .grommet has it working fine but the v2 does not have this functionality.

**Comment by oorestisime** [comment]
Here's a pattern for toasts notifications popovers https://codesandbox.io/s/9jpz0z2ym4

**Comment by RohitoOo** [comment]
@oorestisime Thanks for your Quick Response. I was able to use v2.grommet's <Layer/> component to fulfil the requirement of the notification.

**Comment by ShimiSun** [comment]
@RohitoOo feel free to share with us the example/codesandbox, I bet it will help more on the community.
