### ISSUE TITLE
Add Value to grommet next

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#1498]

**Comment by karatechops** [comment]
I can pick this up starting next week. It seems like this component could pretty much be removed and replaced with simple composition. 
```
<MyIcon />
<Heading level={1} size="small">
  <strong>
    My Heading
  </strong>
</Heading>
<MyTrendIcon />
<Label>
  My Label
</Label>
```
Let me know if this is worth picking up for next week.

**Comment by alansouzati** [comment]
based on a chat with @ericsoderberghp, I believe Value will be removed in 2.0.
