### ISSUE TITLE
NumberInput box is not allowing decimals

### ISSUE THREAD

**Issue by agrawalPratik** [grommet/grommet#1508]
Numberinput box is not allowing decimals when we parsefloat function, this issue is only observed in IE browser only
### Expected Behavior

NUmberinput box should allow decimals value
### Actual Behavior

Numberinput box is not allowing decimals when we parsefloat function
### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/anon/pen/yoLPQv?editors=0001

### Steps to Reproduce
 1. Please use this codepen
 2. 
 3. 

### Your Environment

* Grommet version: 1.5.0
* Browser Name and version: IE 11.0.9600.18697IS
* Operating System and version (desktop or mobile): Desktop, Windows

**Comment by dgennetten** [comment]
Your codepen produces the same result in Safari.

**Comment by alansouzati** [comment]
This is a problem with `parseFloat` and not with Grommet.

Here is a codepen that fixes your problem:

https://codepen.io/alansouzati/pen/vJMdMz?editors=1010
