### ISSUE TITLE
vertical scrollbar is not appearing if the content is more in the page using grommet.

### ISSUE THREAD

**Issue by sudesh-gama** [grommet/grommet#151]
i have created a login form using grommet library, but the problem is if the content is more in the page scroll bar is not appearing on the screen, please refer to the screen shot, i am using firefox browser to run the page, is there any other way to use it.
Please find the screen shots of js file and front screen for more details,
![scroll-issue](https://cloud.githubusercontent.com/assets/13653637/9241973/27a87752-4198-11e5-83fc-fa1654bbee0c.PNG)
![scroll-issue-code](https://cloud.githubusercontent.com/assets/13653637/9241975/2d8b2c96-4198-11e5-801e-92f3ff7ac674.png)

**Comment by ivandurst** [comment]
I believe this issue was fixed in https://github.com/grommet/grommet/pull/211.

**Comment by bryanjacquot** [comment]
Closing this as we believe this was addressed some time ago.
