### ISSUE TITLE
Investigate typescript definitions in grommet next

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#1512]

**Comment by stsrki** [comment]
I have just found about this project and it seems really great. Since I'm heavily using typescript in all of my projects it would be great if grommet would also have the support for typescript. Can you please tell are you working on this and if you are, do you plan to release it soon? Thanks

**Comment by BjornMelgaard** [comment]
Maybe its worth to rewrite grommet on typescript, cause its hard to maintain type definitions in non typescript projects

**Comment by RyanCCollins** [comment]
Hey @BjornMelgaard!  Great thought!  I agree with that sentiment, but the majority of the grommet team and user-base appreciates having a vanilla codebase.  

That said, I'd love to make it my mission to add typescript definitions to 2.0 and I would love your help!  @stsrki as well!

I've made a NEXT_TS branch to start work on adding TypeScript definitions.  Also, checkout the [Grommet 2.0 wiki](https://github.com/grommet/grommet/wiki/2.0-Migration-Guide) for more info on the release.

**Comment by RyanCCollins** [comment]
Bit of an an update, I've been doing some research into how other UI libraries handle type definitions.  I've found that libraries like react-toolbox and material-ui add flow and typescript types within their components.  I really like this approach because it allows you to write your components with vanilla javascript, while also supporting people who like to use static-type checking. 

Here are some examples:
- [Material UI](https://github.com/callemall/material-ui)
  -[FlowType Example](https://github.com/callemall/material-ui/blob/v1-beta/src/Paper/Paper.js)
  -[TypeScript Example](https://github.com/callemall/material-ui/blob/v1-beta/src/Paper/Paper.d.ts)
- [React Toolbox](https://github.com/react-toolbox/react-toolbox)
  - [TypeScript Example](https://github.com/react-toolbox/react-toolbox/blob/dev/components/avatar/Avatar.d.ts)

**Comment by BjornMelgaard** [comment]
@RyanCCollins You can generate pretty much whatever you like js using different `target`s. Use `target: esnext` with `jsx: react-native` to generate codebase indistinguishable from the present. 

Also it can facilitate flow typings generation using [flowgen](https://github.com/joarwilk/flowgen)

And ... grommet written on typescript ... you know, its better)

**Comment by RyanCCollins** [comment]
@BjornMelgaard, I totally agree!  Big fan of TypeScript. I'll work on the rest of the grommet team 😄

**Comment by RyanCCollins** [comment]
One thing that I'd love help with is devising build steps that will generate the definitions for both TypeScript and Flow from the React-desc proptypes that are currently included with components.  I've been playing with writing a simple script to help me quickly generate TS definitions, but my approach [is very crude](https://gist.github.com/RyanCCollins/7ca4062a270514d8d2080633a066e60b).

**Comment by ericsoderberghp** [comment]
Would it make sense to enhance react-desc to add some additional properties to make the Flow and TypeScript generation easier?

**Comment by RyanCCollins** [comment]
Hey @ericsoderberghp, yea that makes a lot of sense to me!  I'll see if I can dig in a bit this weekend.

**Comment by RyanCCollins** [comment]
I've got [TS definitions now for all the components](https://github.com/grommet/grommet/compare/NEXT...NEXT_TS?expand=1).  I still want to test this before merging, however.

**Comment by dgennetten** [comment]
Hey Ryan, how about throwing together a quick docs draft on "Using Typescript with Grommet"?

**Comment by RyanCCollins** [comment]
@dgennetten that sounds like a good idea, @dgennetten!

**Comment by dgennetten** [comment]
I'll review whatever you put together! I used to use an early version of Typescript back in the day when I was a .net dev. Would love to get some element of those days back.

**Comment by L0ZZI** [comment]
Anyone working this?

**Comment by RyanCCollins** [comment]
@L0ZZI I am, but I don't have much time to devote to it! Will let you know how it goes :)

**Comment by davidsoderberg** [comment]
@RyanCCollins, how is it going with this?
I need it for one of mine project 😄

**Comment by dennari** [comment]
Any news with this? What's the `NEXT_TS` branch?

**Comment by dennari** [comment]
Here's how they went about it incrementally in ReaKit: https://github.com/reakit/reakit/pull/146

**Comment by alansouzati** [comment]
I will take a stab at this. @RyanCCollins i will ping you to see how I can continue your work

**Comment by dennari** [comment]
g@alansouzati, I'd be happy to contribute as well. I know TypeScript and have some experience from a similar task in Gatsby.

**Comment by alansouzati** [comment]
moi @dennari. olen iloinen, että voit auttaa.

Please join our slack channel if you haven't already. https://slackin.grommet.io. let me know your id I will create a channel for you me and @RyanCCollins.

**Comment by thomschke** [comment]
Grommet is great stuff. We have to choose a React-UIFramework ASAP and TS is fixed.
This issue is set to milestone 2.1.0 which should be published on 7/17. Any good news?

**Comment by alansouzati** [comment]
I still haven't got the change to add the typescript bindings. But you can still use typescript without it right? This shouldn't stop you from choosing grommet 😄 

I'm wanting to start my investigation on this today. I will keep you posted.
