### ISSUE TITLE
Button with href should not add icon classes if it does not apply

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#1513]
When using Button with an href set, it behaves as an Anchor. If you set the icon prop, it will add a span with `.grommetux-anchor__icon` wrapping the svg icon regardless of the value of `plain`
 
### Expected Behavior

`.grommetux-anchor__icon` should not be added if the Button has `plain={true}` set.

### Actual Behavior

A span with `.grommetux-anchor__icon` wraps the svg icon when Button has `plain={true}` set.

### URL, screen shot, or Codepen exhibiting the issue
Here's a codepen that I believe demonstrates the issue. 
https://codepen.io/anon/pen/LjEmpK?editors=0010

Also note, it was discussed on the grommet slack channel: https://grommet.slack.com/archives/C04LMHN59/p1501015074313689

### Steps to Reproduce
 1. Set a Button to have an href and `plain={true}
 2. Add an icon prop to the Button
 3. Change `plain={false}` and no change to the application of `.grommetux-anchor__icon`

### Your Environment

* Grommet version: 1.5.0
* Browser Name and version: Chrome 59
* Operating System and version (desktop or mobile): OS X 10.12.5

**Comment by karatechops** [comment]
Hey @srallen thanks for filing this issue. I read through the Slack conversation and reviewed the Codepen. Just to clarify the issue - **when the `plain` prop is set to true in Button the icon should not be rendered**. I've posted a PR for this - #1604.

**Comment by karatechops** [comment]
We've decided to postpone this feature until 2.x as we believe this will break too many existing apps. Judging by the 2.x Button code it looks to already be implemented.

**Comment by srallen** [comment]
@karatechops thanks for taking a look at this. I look forward to version 2.
