### ISSUE TITLE
Button Text getting across box 

### ISSUE THREAD

**Issue by noorisunique** [grommet/grommet#1515]
### Expected Behavior
i want button text inside box in internet explorer  

### Actual Behavior
Button text is crossing Box in internet explorer working fine in other browser

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/anon/pen/XabpVa?editors=1010

![image](https://user-images.githubusercontent.com/15786752/28635762-5bea7288-7259-11e7-9ba1-c92dc324de84.png)

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: 
* Browser Name and version: i explorer 11
* Operating System and version (desktop or mobile): window10

**Comment by noorisunique** [comment]
Could any one solve it  ?

**Comment by alansouzati** [comment]
I don't think there is a generic solution for this. This is IE11 implementation bug. 

My recommendation is to add `max-width` in the containers you know are problematic. Here is a codepen that fixes your problem:

https://codepen.io/anon/pen/oeXZNV?editors=0110

Check this stackflow: https://stackoverflow.com/questions/19138107/ie11-flexbox-preventing-text-wrapping

The reason we cannot apply a generic fix for this is the fact that `Button` has a max-width of `384px` and it we apply `max-width: 100%` to all box children we will break Button max-width for when Box size is bigger then 384.
