### ISSUE TITLE
<Tip> is not centered on <Status> icon while targeting <Status> id

### ISSUE THREAD

**Issue by pawelpicur** [grommet/grommet#1518]
I found that [Status](https://grommet.github.io/docs/status) doesn't support id or [Tip ](https://grommet.github.io/docs/tip)can't read it properly
Really similar to [this ](https://github.com/grommet/grommet/issues/1032#issue-187481124) case

### Expected Behavior
Tip should be centered on the icon

### Actual Behavior
Tip appears on the left

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/28948842/28661650-aa7a9c58-72b7-11e7-8171-4fbc9764dfa4.png)

### Steps to Reproduce
 1. Create a Tip
 2. Target Status id
 3. Click on the icon to pop the tip, see it's not centered

### Your Environment
* Grommet version: 1.5 (newest)
* Browser Name and version: Chrome, newest
* Operating System and version (desktop or mobile): win 10

### PS
PS. I found a workaround to put status in a div and make that divs height the size of the icon (24px) and adding paddingLeft for half of the icon width, but still would be nice to target the icon, not the div

PPS. It would also be nice to be able to decide from which side is the tip pointing towards the target (similar to [react-bootstrap tooltip](https://react-bootstrap.github.io/components.html#tooltips)). Then for example i would be able to set the Tip on top (or on the right side) of my div and the responsibility on mobile wouldn't affect my tip at all.

PPPS. For some reason normal Tip doesn't work with Icons for me either (and according to [that ](https://github.com/grommet/grommet/issues/1041#issuecomment-259523312) it was fixed) despite having grommet 1.5.0
![image](https://user-images.githubusercontent.com/28948842/28671350-aa3f6776-72dc-11e7-95af-3227bfa98b8b.png)

**Comment by karatechops** [comment]
Hey @pawelpicur, thanks for filing this issue. I believe the intended way to use Icons and Tips is to wrap them in Buttons. Check out this [Codepen](https://codepen.io/karatechops/pen/eEwoMM?&editors=0010) displaying this behavior.

**Comment by karatechops** [comment]
@pawelpicur I've created a [second Codepen](https://codepen.io/karatechops/pen/WEVegg) which avoids using Button and simply uses Box instead. 

I've tagged Tip's 2.0 to fix this. I'm closing this for now as this is slated to be fixed in 2.0. Thanks for the feedback!
