### ISSUE TITLE
type=email for login form is causing invalidation error on firefox

### ISSUE THREAD

**Issue by Deklin** [grommet/grommet#152]
<input id="username" ref="username" type="email" /> is what is listed in LoginForm.js this is causing a validation error on firefox. This value either needs to be configurable, or back to text.

**Comment by ericsoderberghp** [comment]
Agreed. Configurable sounds good. Pull requests welcome, otherwise we'll add it to our backlog.

**Comment by ivandurst** [comment]
It looks like this may have been updated - you can now add ` usernameType="text"` or any other value directly to a `<LoginForm />` component.
