### ISSUE TITLE
Menu dropdown does not work in Safari

### ISSUE THREAD

**Issue by creeonix** [grommet/grommet#1525]
Sub Menu does not work in Safari. No console errors. No feedback at all.

### Expected Behavior
When clicked in folded menu, it show open

### Actual Behavior
It does not open in Safari, however works fine in Chrome

### URL, screen shot, or Codepen exhibiting the issue

![screen recording 2017-08-01 at 01 34 pm](https://user-images.githubusercontent.com/108764/28821628-d47e9f6c-76be-11e7-800e-cac3053ab77f.gif)

### Steps to Reproduce
 1. Open [https://grommet.github.io/docs/menu/examples/](https://grommet.github.io/docs/menu/examples/) in Safari (10.1.2)
 2. Switch off inline mode of menu
 3. Result: Menu can't be opened

### Your Environment

Project was generated with grommet-cli -> session button in the bottom didn't work.
At first I tried custom menu -> same thing
Then I went to grommet docs -> same result

It works in Chrome

* Grommet version: latest (1.3.4)
* Browser Name and version: Safari 10.1.2
* Operating System and version (desktop or mobile): macOS 10.12.6

**Comment by aldofunes** [comment]
I did quick tests in major browsers and found that:

## Works
- Chrome
- Opera

## Doesn't work
- Safari
- Firefox

**Comment by aldofunes** [comment]
I found a workaround. 

What I did was to provide an onClick function to update the state directly to `expanded`

Like this:
```javascript
<Menu
  ref={(node) => { this.menuNode = node; }}
  onClick={() => this.menuNode.setState({ status: 'expanded' })}
>
  {/* Anchor links here */}
</Menu>
```

I have not found any drawbacks with this, but have not done any serious unit testing.

Hope it helps

**Comment by alansouzati** [comment]
Yeah I'm able to reproduce this. let me investigate what is going on...

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/22ff8308e634829a519010826664ab6cf341a6ab
