### ISSUE TITLE
List of HOCs for 2.0

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#1530]
We'll use this issue to keep track of HOCs (higher order components) necessary for Grommet 2.0 context passing.

# Existing HOCs

### withFocus
Params:
- `WrappedComponent`: component for HOC to wrap.

This HOC binds to mouse down, mouse up, focus, and blur events of the `WrappedComponent` and passes the focus state along to the `WrappedComponent`.

Status:
- [x] complete (Initial commit a1dc887e1287783a5cbecedaae4f5322fb4ddc24)

### withTheme
Params:
- `WrappedComponent`: component for HOC to wrap.

This HOC passes our custom theme to components.

Status:
- [x] complete (Added recompose. Added ThemedComponent HOC fd7f7f71188939c12ae80ab47ce26f4dd67d5f44)

# Proposed HOCs

None yet.

**Comment by karatechops** [comment]
Has there been a discussion about background color context? Will Grommet 2.0 support adjusting elements `color` property so maintain readability? If this is an intended feature we can build an HOC to find the dominate color of a rendered DOM element or just dig into the components CSS. Perhaps the HOC can pass a prop of 'backgroundContext` to a wrapped component.

**Comment by ericsoderberghp** [comment]
I was thinking we'd put the background color context inside a `grommet` context property. So, we wouldn't need to interrogate the DOM.

**Comment by karatechops** [comment]
Closing this for now as I don't have time to maintain the list.
