### ISSUE TITLE
ToastContents: "Warning: Unknown props `store`, `intl`, `router`, `history` on <div> tag."

### ISSUE THREAD

**Issue by jlevesque** [grommet/grommet#1536]
Maybe I'm not using the Toast component correctly, but this warning always comes up when the Toast is render. Basically, I have a boolean in my state that tells to render or not the toast inside de App component.

```
let toast = null;
if(displayToast){
    toast = (<Toast status={status} onClose={onClose}>{message} </Toast>)
}

<BrowserRouter>
    <App centered={false} inline >
         {toast}
         <Switch>
             <Route exact path="/">
                 <Redirect to={PATHS.home} />
             </Route>
             <Route path={PATHS.home} component={HomePage}/>
          </Switch>
           .....
     </App>
</BrowserRouter>
``` 

### Expected Behavior
The Toast renders without warning.

### Actual Behavior
The parent component throws a warning.

### URL, screen shot, or Codepen exhibiting the issue
Link in the warning:
https://facebook.github.io/react/warnings/unknown-prop.html

![screen shot 2017-08-02 at 8 47 38 am](https://user-images.githubusercontent.com/6978875/28874301-4c5ea3e2-775f-11e7-84a9-77ef06fbf467.png)

### Your Environment
* Grommet version: 1.6.0
* Browser Name and version: Chrome

**Comment by Thuranel** [comment]
It seems like the last update to Grommet cause this issue. Here's the commit that I believe causes the issue: https://github.com/grommet/grommet/commit/6299947ac8b7fa8c619226fc33035480cb6fdbfa

Toast takes history, intl, etc. as props. The latest commit tried to pass every single props given to Toast as a props to the Toast contents. Because div can't have a props of history, the warning is thrown.

I believe the commit was made to be able to style Toast? I don't know. Anyway, reverting the latest commit should fix the issue. I don't really want to touch it because I am unsure of what that change was trying to accomplish.

**Comment by jlevesque** [comment]
@Thuranel You are right, I've made a really dumb and fast test to see if the warning was going to appear again. Basically, I removed the problematic props before passing the object to the div : 
```
const { children, onClose, size, status, ...rest } = this.props;
...
let restNoContext = Object.assign({}, {...rest});
delete restNoContext.history;
delete restNoContext.intl;
delete restNoContext.router;
delete restNoContext.store;

return (
   <div className={classNames} {...restNoContext}>
      ...
   </div>
);
``` 
And that removed the issue.

It looks like it was intended for a better customization. Maybe @alansouzati you can tell us more about that and give us an update that.

**Comment by alansouzati** [comment]
Yeah. are you using recompose with Higher Order Components? History, intl are usually present in the context, but I've seen cases where folks create HOCs to transfer that to props.

We have a lot of components that pass down props for various reasons. like adding and `id` prop to a container. or `data-*` properties. Initially we did not have the prop transfer capabilities and we are slowly adding it to other components.

Your test is actually the right way of doing it. But any reason why not using the context for these things?

I'm closing this issue for now but feel free to continue the discussion here.

**Comment by jstlaurent** [comment]
@alansouzati : If I'm reading the code right, the `Toast` component is explicitly extracting these four elements (`history`, `intl`, `router` and `store`) from the context and passing them as props to the `ToastContents` sub-component, which in turn now passes them on the `div` component (which can't handle them).

Per the comments, that's a way to carry along the rendering context into the layer. But these four elements should be removed from props and transformed back into a rendering context in `ToastContents` before the rest of the props can be passed down to the `div`.

That they are not is the origin of the problem.

**Comment by alansouzati** [comment]
@jstlaurent perfect interpretation. I should have looked into it more carefully. We should remove them in our end before passing it down. I'm going to work on a fix for this today.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/0b9795ba3285303015a336e8e2910de7b407ffb1

**Comment by jstlaurent** [comment]
@alansouzati : Thank you!
