### ISSUE TITLE
Pressing 'enter' key on Select component does not automatically select an item.

### ISSUE THREAD

**Issue by George-Aidonidis** [grommet/grommet#1537]
While having a [Select](https://grommet.github.io/docs/select/examples?placeHolder=true&onSearch=true) component and the drop down menu is active, pressing the 'enter' key (without selecting an item) causes the drop down menu to close without passing an item to Select's field.

### Expected Behavior

As a user when the drop down list is active and I haven't chosen an item from the list I expect to press enter and have the first item automatically selected. The existing functionality with arrow keys should continue to work.
### Actual Behavior

Pressing enter just closes the active dropdown menu without passing an item.
### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/Segovia/pen/zdBbex?&editors=0010

### Steps to Reproduce
 1. Open the drop down menu
 2. Press enter without choosing an item
 3. The active list closes without a selected item.

### Your Environment

* Grommet version: 1.4.1
* Browser Name and version: 60.0.3112.78 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): 4.12.3-1-ARCH

There is the `onEnter` function, that can be found [here](https://github.com/grommet/grommet/blob/master/src/js/components/Select.js#L271) that handles that specific behavior. I believe that pressing enter should:

* Select the item that the user selected (with arrow keys).
* Select the first item on the list/drop down menu if none was selected by the user.

**Comment by dgennetten** [comment]
@George-Aidonidis It seems the first bullet (select item that user has selected) works fine. The second, (Select first item on list if none selected...) seems unconventional and would be unexpected. Are there other places where this is the standard behavior?

**Comment by George-Aidonidis** [comment]
@dgennetten I am thinking that I did not make a good job on explaining the second bullet. Here is a more detailed explanation:
- User opens the drop down menu.
- User types an item in order to filter it from the list. The item comes up first to the list.
- User presses enter (without selecting it with arrow keys) and the item becomes selected.

This does not happen here (user presses enter and the item on top does not become selected). 

![peek 2017-08-09 10-40](https://user-images.githubusercontent.com/11461413/29110686-2929b592-7cf0-11e7-9a19-e656b944770c.gif)

**Comment by mariosant** [comment]
The kind of behaviour @George-Aidonidis is trying to explain, can be found on [Select2](https://select2.github.io).
Try typing something there and hit enter. It selects the first one of the available results.

https://select2.github.io/examples.html

**Comment by karatechops** [comment]
I've created a PR for this but I'm hesitant to post it just yet, I want to discuss with @alansouzati the accessibility implications. I'm leaning towards not implementing this as I'm not sure it makes a lot of sense to users using screen reader.

**Comment by mariosant** [comment]
@karatechops I understand your concerns. Maybe adding this as an optional behaviour, then?

**Comment by karatechops** [comment]
Hi @mariosant & @George-Aidonidis! I've discussed this feature with @alansouzati, our [accessibility guru](https://www.youtube.com/watch?v=Qo0BHIkKzqo), and he agreed that this feature enabled by default would lead to unintended selections when pressing enter.

I would lean towards allowing the onEnter event to bubble up to it's container component. This would allow the user to specify the enter key's behavior beyond Grommet's default behavior. I'm going to close this and document this feature request for the 2.x Select (#1484). 

Thanks for the feedback!

**Comment by mariosant** [comment]
Thank you for your response, @karatechops .
