### ISSUE TITLE
Search component doesn't call `onSelect` callback on enter when it's displayed inline without suggestions

### ISSUE THREAD

**Issue by linde12** [grommet/grommet#1544]
From michael.weinberger on grommet slack:

In our search we wanted, that the onSelect method is called after the onInputKeyDown method.
At this time we didn´t want to give the user suggestions and that was the reason why we didn´t fill this prop. But that ends in an error.
Now we filled the suggestions prop but the suggestions don´t appear if we select the search component. And that is exactly what we want.

### Expected Behavior
Shouldn't crash if there are no suggestions and the `<Search>` is has the `inline` prop set to true

### Actual Behavior
`<Search>` crashes & leaves a stacktrace.

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/anon/pen/OjREgL?editors=0010

### Steps to Reproduce
 1. Create a `<Search>` component with the `inline` prop set to true
 2. See how `onSelect` callback isn't called on enter

### Your Environment

* Grommet version: 1.6.0
* Browser Name and version: Chrome

**Comment by linde12** [comment]
I'm thinking that this might be by design(since there are no suggestions it might be weird for `onSelect` to be called) but i still think there should be an easy way to check if the user has pressed enter without using "onKeyDown" and checking the keycode. Maybe a `onSearch` or `onEnter` callback would be appropriate?

**Comment by karatechops** [comment]
@linde12 thanks for filing this issue. I've posted a PR which should fix the issue. I had trouble discerning what the author's original intent was here. For now when the enter key is pressed without any suggestions the call back returns the target ref and a second parameter of `false` letting the user know no suggestions were selected. According to the docs this is the appropriate behavior for the Search API.

**Comment by linde12** [comment]
Oh, great! Thanks!
