### ISSUE TITLE
TableHeader Size Should Be Consistent if Sortable or Not

### ISSUE THREAD

**Issue by bastanle** [grommet/grommet#1548]
### Expected Behavior
The TableHeader font is different when you have the header sortable or not. There is already a cursor change, so I don't think a different font size is necessary.

### Actual Behavior
See above

### URL, screen shot, or Codepen exhibiting the issue

In lieu of a codepen, check out your example here:
https://grommet.github.io/hpe/docs/table-header/examples?sortIndex=true

Switch onSort on/off and you'll see the issue.

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: I'm assuming latest since this is seen in the documentation
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by dgennetten** [comment]
This is as designed. When sortable, the TableHeader becomes a button and adheres to grommet button styles.
