### ISSUE TITLE
Card is very large due to first-class support for markdown in description prop

### ISSUE THREAD

**Issue by mikeplus64** [grommet/grommet#1550]
Unfortunately `Markdown` is a very heavy component due to its use of `remark-parse`, and `markdown-to-jsx`. In my fairly typical webpack/babel/uglifyjs2 build simply importing `Card` adds 177KB(!!) to my production bundle size.

I'd suggest just treating `description` as a plain React node (which also gives you support for plain strings, iterables, and numbers, at least according to the flowtype definition for React$Node), and noting on the docs that markdown is supported through explicit use of the `Markdown` component

**Comment by karatechops** [comment]
Hey @mikeplus64, thanks for filing this issue. I just ran some tests in a grommet/create-react-app and clocked the bundle with card at `110.77kb` and the bundle w/ card at `163.37k`. This is quite a substantial weight increase. I will take a look at removing Markdown from the Card component.

**Comment by karatechops** [comment]
Update: The deprecation notice regarding Markdown support in Card has been merged. I will post a PR after Grommet's next release so we can fully remove this. @mikeplus64 thanks for the feedback!
