### ISSUE TITLE
Distribution resize? 

### ISSUE THREAD

**Issue by afong94** [grommet/grommet#156]
Hi, I've developed a dashboard for our team with grommet, and I was wondering if there was a way to resize the Distribution, as the text doesn't seem to conform or affect the size of the distribution. I've already set the large flag to true as well. The problem can be seen at the bottom of this page: http://sdnreporter.rose.hp.com/flaredashboard.html.

Thanks so much!

**Comment by ericsoderberghp** [comment]
I think there are some things you can change to your page to get the Distribution to take the full width. It looks like the Distribution is inside a Tile, which is constraining its width. Can you try it without putting it in a Tile?
