### ISSUE TITLE
TextInput's 'onDOMChange' prop isn't considered as 'onChange' by React

### ISSUE THREAD

**Issue by Gehbrial** [grommet/grommet#1560]
### Expected Behavior
We shouldn't get a warning -> Adding a 'onChange' prop with an empty function value solves the problem.

### Actual Behavior
`Warning: Failed form propType: You provided a value prop to a form field without an onChange handler. This will render a read-only field. If the field should be mutable use defaultValue. Otherwise, set either onChange or readOnly. Check the render method of TextInput.`

### URL, screen shot, or Codepen exhibiting the issue
`<TextInput 
value={this.props.input} 
placeHolder={display.search + "..."} 
style={{width:"100%"}}
suggestions={this.props.suggestions}
onSelect={(e) => this.props.actions.updateSearchInput(e.suggestion)}
onDOMChange={this.onInputChange}
/>`

### Your Environment

* Grommet version: 1.6.0
* Browser Name and version: Chrome 60.0.3112.90 (Build officiel) (64 bits)
* Operating System and version (desktop or mobile): Windows 10 version 1703 (64 bits)

**Comment by alansouzati** [comment]
Thanks for reporting this.

Fixed in https://github.com/grommet/grommet/commit/dee17e1a12af5ec7f4e5a2abf8462b41d98d20ab
