### ISSUE TITLE
Allow Anchors and Buttons to set location.state

### ISSUE THREAD

**Issue by XuluWarrior** [grommet/grommet#1563]
history.{push|replace} allows a state object to be set as the second parameter.  It would be helpful, at least to me, to be able to set this on Anchor and Button components.

In my case I wanted to set previousTitle on the location so that a back link was easy to implement.

I accidentally created a pull request (https://github.com/grommet/grommet/pull/1562) for this earlier which I've closed for now.

**Comment by alansouzati** [comment]
I like the idea and thanks for having the initiative of sending the pull request. Does it make sense to put that information inside path object?

```
(router.history || router).push(path.path || path, path ? path.state :  undefined);
```

This avoid adding a generic `state` prop to Anchor or Button. Thoughts?

**Comment by XuluWarrior** [comment]
That's a possibility but I am unclear as to what path objects represent (compared to path strings).
How are they used elsewhere?

**Comment by L0ZZI** [comment]
Did this get tied to a PR?

**Comment by XuluWarrior** [comment]
I (accidentally) created a proof on concept PR #1562 for my own use but @alansouzati suggested an alternative.  I was waiting for more feedback before I revisited this issue.
I can reopen my PR if it is of any use.

**Comment by L0ZZI** [comment]
I'll assign @alansouzati  two
