### ISSUE TITLE
Grommet Table Fixed Header and Sorting

### ISSUE THREAD

**Issue by RajaKorada** [grommet/grommet#1567]
![sorting](https://user-images.githubusercontent.com/25481578/29611874-e094992c-881c-11e7-979e-934013bfbf94.png)

Hi ,
I am implementing Fixed table header with sorting  ,sorting is fine  when  **scrollable="false"**  . if i will use **scrollable="true"**   for fixed header  table  then header is moving to the  bottom of the Page..
like below image...
![fixed header](https://user-images.githubusercontent.com/25481578/29611707-3aea8676-881c-11e7-8562-29a8f3747ede.png)

**Comment by dgennetten** [comment]
@RajaKorada can you provide a little more information?  Environment?  I'm not seeing issue with current grommet/chrome.

**Comment by RajaKorada** [comment]
Thank you @dgennetten  for the response.

 I would like to implement fixed header table with vertical and horizontal scrollbar with sorting feature..
I am not facing any issue with sorting, untill **scrollable ="false"**  
Issue arises once i add **scrollable="true"** attribute to the table, then table header moves to the bottom of the page  and sorting is also not working.

I need table header to be fixed with vertical and horizontal scrollbar along with sorting feature..
Could you please help me..

**Comment by karatechops** [comment]
@RajaKorada does [this](https://codepen.io/karatechops/pen/zdXJQY?editors=0010) look like the issue you are encountering?

**Comment by RajaKorada** [comment]
Thank you @karatechops for the response.

Can you please visit this link  [a link](https://codepen.io/Rajakorada/pen/yoWJLe?editors=1111)

Please check in medium or Large Screens for getting clear view of the issue ,find attached screenshot .
Please write to me for further information... 
![issuesample](https://user-images.githubusercontent.com/25481578/30115218-afc5593c-9337-11e7-9be1-e7ceea3b78bd.png)

**Comment by karatechops** [comment]
Hey @RajaKorada, I met with the team yesterday to discuss this issue. The `scrollable` prop in Table is meant to be flush with the edges of your app, I believe the initial use case was placing it within the split component. After some thought I realized that maybe we could use the Box size property to contain the Table however it appears when setting `max-height` on a Box it does not overflow to scroll.

I'll meet with the team again and discuss our approach to fixing this. In the mean time if you'd like to fix this issue today in your app I've updated my [Codepen](https://codepen.io/karatechops/pen/zdXJQY?editors=0010) to display how you could hide the Table's overflow.

**Comment by karatechops** [comment]
I've opened #1606 in light of this issue. @RajaKorada thank you for bringing this to our attention, I believe the proper fix for this lies within resolving the Box bug.

**Comment by jornncc** [comment]
I know that this issue is closed, but there is an issue with not being able to click the column headers to sort when scrollable="true". That issue seems to be lost in issue #1606 . [using Grommet 1.6.0].
