### ISSUE TITLE
Can't open Menu component with keyboard on first keypress

### ISSUE THREAD

**Issue by Thuranel** [grommet/grommet#1569]
If you have a Menu component that is not inline and you try to use the 'space' key to open the Menu, on the first keypress the menu will open and immediately close after. On the next keypress, the Menu will open normally.

### Expected Behavior
Menu stay open when opening it with 'space' key

### Actual Behavior
Menu open and close immediately after.

### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/docs/menu/examples/?responsive=true&inline=false&i-anchors=false&i-buttons=true

### Steps to Reproduce
 1.  Press TAB until you highlight the Menu component
 2. Press 'space' to open the Menu

### Your Environment

* Grommet version: 1.6.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): W10

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/22ff8308e634829a519010826664ab6cf341a6ab
