### ISSUE TITLE
chart data must be reversed for data to work?

### ISSUE THREAD

**Issue by afong94** [grommet/grommet#157]
I am trying to create a chart and I assigned values to the x axis, however, it seems like the data values must be listed in reverse order, otherwise when hovering over the graph, it shows the reverse data point (e.g. when hovering over value 1, it shows value 16). 

With the values listed like this, it has the issue: 
xAxis={[
            {"label": "16 wks ago", "value": 1},
            {"label": "15 wks ago", "value": 2},
            {"label": "14 wks ago", "value": 3},
            {"label": "13 wks ago", "value": 4},
            {"label": "12 wks ago", "value": 5},
            {"label": "11 wks ago", "value": 6},
            {"label": "10 wks ago", "value": 7},
            {"label": "9 wks ago", "value": 8},
            {"label": "8 wks ago", "value": 9},
            {"label": "7 wks ago", "value": 10},
            {"label": "6 wks ago", "value": 11},
            {"label": "5 wks ago", "value": 12},
            {"label": "4 wks ago", "value": 13},
            {"label": "3 wks ago", "value": 14},
            {"label": "2 wks ago", "value": 15},
            {"label": "1 wk ago", "value": 16}
          ]}

with this, the issue is gone: 
xAxis={[
            {"label": "1 wk", "value": 16},
            {"label": "2 wks ago", "value": 15},
            {"label": "3 wks ago", "value": 14},
            {"label": "4 wks ago", "value": 13},
            {"label": "5 wks ago", "value": 12},
            {"label": "6 wks ago", "value": 11},
            {"label": "7 wks ago", "value": 10},
            {"label": "8 wks ago", "value": 9},
            {"label": "9 wks ago", "value": 8},
            {"label": "10 wks ago", "value": 7},
            {"label": "11 wks ago", "value": 6},
            {"label": "12 wks ago", "value": 5},
            {"label": "13 wks ago", "value": 4},
            {"label": "14 wks ago", "value": 3},
            {"label": "15 wks ago", "value": 2},
            {"label": "16 wks ago", "value": 1}
          ]}

**Comment by ericsoderberghp** [comment]
@afong94: can you include a sample of your actual data as well? I'm looking at the series and xAxis data at the top of ChartDoc.js for the examples and I can't see anything that looks incorrect.

**Comment by afong94** [comment]
hi @ericsoderberghp, my data is output in the format [[16,x],[15,x],[14,x]......], So i guess that currently the xaxis must be configured to follow that format as well. I was under the impression that the order shouldn't matter as much, that a user can enter data values in another order and that the data points could be properly mapped to the xaxis values as well.

**Comment by Abhijitforu** [comment]
I am new to grommet and i have created chart using it, and i run gulp dist after that i can see html and js pages in gulp dist directory now  i can use this chart but how i can make it dynamic from external java script or anything

**Comment by bryanjacquot** [comment]
The new Chart interface resolves this (the caller can specify the reverse property to control order of data with respect to layout order).  http://grommet.github.io/docs/chart-area
