### ISSUE TITLE
Anchor with href and no onClick

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1585]
Thank you very much for the great work, fantastic library

A small issue with the Anchor component will generate an exception if href is assigned and no onClick provided
<Anchor label='Google' href='http://google.com'' target='_blank' />

To reproduce: 
https://grommet.github.io/hpe/docs/anchor/examples/?label=true&animateIcon=true&href=true&target=true
Open devTools and click on the link and check the console.

The issue :
in Anchor.js:
let adjustedOnClick = (path && router ? this._onClick : onClick); <-- this is null, since no onClick event
...

Possible fix:
if (disabled) {
            event.preventDefault();
          } else if (adjustedOnClick) { <---- here you might want to check if  adjustedOnClick is assigned
            adjustedOnClick(event, ...args);
          }

**Comment by karatechops** [comment]
Thanks for filing the issue @atanasster! I've posted a PR with the fix so hopefully we can merge this for the next release.

**Comment by atanasster** [comment]
Thank you , fantastic
