### ISSUE TITLE
Cannot see options for Select components placed at the bottom of the page.

### ISSUE THREAD

**Issue by generalChaos** [grommet/grommet#1587]
If you have a Select component at the bottom of the page, the options open up below it without enough room to see the options.

### Expected Behavior
The options appear above the Select component or the page extends to allow the user to see part of the list.

### Actual Behavior
The list of options is shown w/ very little room or none at all.  This makes it difficult to select an option.

### Steps to Reproduce
 1. Add a Select component at the bottom of your page
 2. Add more than 5 optons
 3. Try selecting the bottom option

### Your Environment
* Grommet version: 1.5.0
* Browser Name and version: Chrome 60.0.3112.90
* Operating System and version (desktop or mobile): MacOS Sierra 10.12.3

**Comment by karatechops** [comment]
Hey @generalChaos thanks for filing this issue. I agree Select should handle window position better but would you mind providing a screen shot for your particular circumstance? It's possible there is a better way to handle this situation from a UX perspective. Off the top of my head I would say you could swap Select out for Menu. Menu will detect which direction to display the drop down, I've created an [example codepen](https://codepen.io/karatechops/pen/KvJZaJ?&editors=0010) displaying this behavior.

**Comment by generalChaos** [comment]
Thanks for the reply @karatechops.  Unfortunately, the UI needs a search w/ the Select component.  For now, I have added extra padding at the bottom of the page (not seen here) which has mitigated the issue.

![grommetselectbottomofpage](https://user-images.githubusercontent.com/3757358/29987901-50f334ae-8f1f-11e7-94bf-4904cdb46ee0.png)

**Comment by karatechops** [comment]
Tagging Grommet 2.0's Select component - #1484. @generalChaos we'll most likely be rolling out support for this in Grommet 2.0. I'm closing this for now as we have the new feature tagged for 2.0's Select.
