### ISSUE TITLE
Changing Carousel Step

### ISSUE THREAD

**Issue by camposcristianeze** [grommet/grommet#1594]
Hello, I was looking to change the step of the Carousel. At the moment I have 3 tiles containers with 4 tiles inside(12 items in total). Everytime I press the next button, the 4 tiles are moving. I just need to move 1 item of the 12 each time) Looked at the code of Carousel but it doesn't seem very easy. Any advice to obtain this behavior would be very appreciated.

Thanks!

**Comment by karatechops** [comment]
Hey @camposcristianeze, thanks for filing this issue. Can you provide a [codepen](http://codepen.io/pen?template=gaEGPY&editors=0010) displaying your example?

**Comment by camposcristianeze** [comment]
Of course!

https://codepen.io/anon/pen/rGavQW?&editors=0010

Everytime I'm clicking the arrow, I would like to scroll just one tile, instead of 4.

Thanks!

**Comment by karatechops** [comment]
Thanks for providing a Codepen, @camposcristianeze. Carousel does not support stepping nested children, only direct children. You would need to do something custom in this scenario - check out this [Codepen](https://codepen.io/karatechops/pen/qPELwV?editors=0010) for a basic example.

**Comment by camposcristianeze** [comment]
Thanks @karatechops! I was trying to replicate this with a more complex logic, but the animations are not working. Could you give me a hand?

https://codepen.io/anon/pen/QqKKyN?editors=0010

Thanks!

**Comment by karatechops** [comment]
The Animation algorithm checks the dif on the key prop to trigger an animation. In this [Codepen](https://codepen.io/karatechops/pen/qPROOd?editors=0010 I) I've updated BoxTile's `key` prop to adjust when changing slides. Its usually best practice to avoid using map indexes in keys as you run into issues like this.

**Comment by camposcristianeze** [comment]
Thanks so much! Would be nice to include that information in docs
