### ISSUE TITLE
Proposal: Add disabled prop for button for Grommet 2

### ISSUE THREAD

**Issue by linde12** [grommet/grommet#1595]
I'm proposing to add a separate prop for enabling/disabling a button. 

It just seems more intuitive to have `<Button label='Submit' disabled={isSubmitting} />` rather than `<Button label='Submit' onClick={isSubmitting ? null : this.handleClick} />`

There is also the use case where a HOC always injects a `onClick` value but we still want the button to be disabled.

E.g. a form library which always injects a function to the submit button of the form. I might want to disable the submit button until some requirements are met.

**Comment by karatechops** [comment]
This makes sense, the disabled property should propagate to the DOM as an HTML button would.

**Comment by karatechops** [comment]
Tagging #1455 here.

**Comment by karatechops** [comment]
Thanks for the feedback @linde12, I'm going to close this to keep the backlog clean. I've made a note of it in #1455.

**Comment by linde12** [comment]
This should solve #1558 in Grommet 2
