### ISSUE TITLE
Donut ignores CSS classes assigned to it

### ISSUE THREAD

**Issue by Thylossus** [grommet/grommet#16]
Hi,

the "Donut" component ignores CSS classes assigned to it, e.g. `<Donut className="my-donut-class" series={...} />` will be rendered without the CSS class "my-donut-class".

The Donut's render function doesn't check for CSS classes provided as a property. Most of grommet's components use the following code to take care of the `className` property in their render function:

    if (this.props.className) {
      classes.push(this.props.className);
    }

However, this is not the case for the Donut component. Is this intended?

**Comment by bryanjacquot** [comment]
Donut has been deprecated in favor of Meter (http://www.grommet.io/docs/hpe/develop/meter).  But in general, Grommet doesn't support providing classes to components.  Styling should be done via a custom theme, not by passing component-specific classes and styles.
