### ISSUE TITLE
Consider extending <Spinning/> element

### ISSUE THREAD

**Issue by jackjwilliams** [grommet/grommet#1600]
Talking in the slack channel, it would be nice if the spinner had options like color, speed, and visible.

Currently I noticed it doesnt even show until 300-800ms, which in some cases is the amount of time a network call / activity may take.

Love the framework! Keep up the good work.

**Comment by Gehbrial** [comment]
Would also love if it we could make it spin faster!

**Comment by karatechops** [comment]
It's unlikely that these sort of granular controls will be added to the Spinning component. There's a lot of effort going into Grommet 2.0 to streamline our components. I would say there's definitely potential for Spinning to accept a theme color index but that would be the extent of this.

In apps I've been working on recently we have a `WithLoading` component which either shows children or the Spinner if there's no children. If you'd like to delay the Spinning element so it doesn't flash you could use that sort of component with an offset to delay the Spinning removal. Personally I'd rather my apps be fast than worry about the loaders flashing.

Here's a [Codepen](https://codepen.io/karatechops/pen/GvayRg?editors=0010) displaying a WithLoading component I mentioned.

I'm going to close this for now and tag the 2.0 Spinning for discussion. #1450

**Comment by jackjwilliams** [comment]
Thanks for the response and the code snippet. I still disagree with the whole "you can just delay it's  removal." If the spinner showed when it started instead of 1 second later, that would make more sense to me.

But I understand your reasoning for the other requests.

**Comment by karatechops** [comment]
@jackjwilliams I see your point, the Spinning animation has it started hidden. I do agree that should be changed. I've tagged the 2.0 Spinning component where we can introduce this change. Thanks for the feedback!

**Comment by jackjwilliams** [comment]
No problem, thank you!

**Comment by iMerica** [comment]
Does this exist? I'm searching https://v2.grommet.io/ and not seeing any components related to loading or spinning.

**Comment by ShimiSun** [comment]
Hi @iMerica, @britt6612 is working on a pattern that will allow different types of loading functionality (spinning included), stay tuned on our slack community #announcements channel.

**Comment by iMerica** [comment]
Sounds good. Thank you.

**Comment by jackjwilliams** [comment]
Any updates on this? It seems this issue was closed and the <Spinning /> element was completely forgotten about.

**Comment by ShimiSun** [comment]
@jackjwilliams , Grommet is providing the building blocks to create modular different spinning elements, here are. some code examples https://codesandbox.io/s/loaders-and-spinners-4jltk

**Comment by jackjwilliams** [comment]
Very interesting, great examples, thank you!
