### ISSUE TITLE
Have Sort accept a {value: , label: } object

### ISSUE THREAD

**Issue by Primajin** [grommet/grommet#1601]
[Sort](https://grommet.github.io/docs/sort) does not highlight the current selected value in the `select` / "dropdown" when [Select](https://grommet.github.io/docs/select) does.

### Expected Behavior

Highlight current selected option.
![screen shot 2017-09-07 at 17 16 16](https://user-images.githubusercontent.com/1742115/30170779-51e43770-93f0-11e7-8ce2-99dabd6be787.png)

### Actual Behavior

No option is selected.
![screen shot 2017-09-07 at 17 16 26](https://user-images.githubusercontent.com/1742115/30170786-575dcfea-93f0-11e7-9831-652dd0dcf571.png)

### URL, screen shot, or Codepen exhibiting the issue
see above

### Steps to Reproduce
 1. Go to https://grommet.github.io/docs/sort
 2. Switch `Name` to `Modified`
 3. Open Dropdown again and see that nothing is selected.

### Your Environment

* Grommet version: 1.7
* Browser Name and version: Chrome Version 63.0.3208.0
* Operating System and version (desktop or mobile): OSX 10.12.6

### Steps to possibly fix it
Have Sort accept a `{value: , label: }` object like Select

**Comment by cherih** [comment]
Reproduced this issue in my sandbox.

**Comment by Primajin** [comment]
If the docs run on `1.8.3`, then this issue still exists in the latest version. ... btw. would be great if the docs show the version they run on ;)

**Comment by cherih** [comment]
Created PR #16 in the grommet-addons project for this issue.

Great suggestion about showing the grommet version in the docs! I created a new grommet-docs issue #297 for this.

**Comment by cherih** [comment]
Rolled in feedback from Alan and re-tested.

PR 16 in grommet-addons was merged to fix this issue.
