### ISSUE TITLE
Box size max property should cause overflow to scroll.

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#1606]
### Expected Behavior
A Box with the following shape `<Box size={{ height: { max: 'large' } }} />` should allow the Box to scroll any additional children overflow past the max height.  [This Codepen](https://codepen.io/karatechops/pen/qXeENM?editors=0010) exhibits what I would expect when setting a Box's max height prop.

### Actual Behavior
Box with max height displays overflow increasing the Box's height. There's two areas here which would need adjustment to complete this fix. 
-  Remove `max-height: 100%` from `.#{$grommet-namespace}box--size` class. This class effectively overwrites all of our max height properties. However I believe Accordion would need to be adjusted as according to the commit note it was added to fix an Accordion/Card bug. This style should be placed in the Accordion styles.
- Add `overflow: auto;` to the `.#{$grommet-namespace}box--size` class. I would assume whenever a user is setting a max height or width property to a Box this would imply overflow is to scroll within that Box.

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/karatechops/pen/MvNYym?editors=0010

### Your Environment

* Grommet version: 1.7.0
* Browser Name and version: Chrome latest
* Operating System and version (desktop or mobile): OSX latest

**Comment by L0ZZI** [comment]
Has this been fixed. The codepen example seems to work?

**Comment by L0ZZI** [comment]
@karatechops you got a lead as to why? @ericsoderberghp you?

**Comment by L0ZZI** [comment]
I'm gonna close it on the two of you if either of you don't respond....Hahahahahahaha ;-)

**Comment by karatechops** [comment]
@L0ZZI I believe the consensus we came to on Slack a good few months ago was - while `max` is broken fixing it would actually break too many apps. Maybe we consider removing it from the docs?
