### ISSUE TITLE
List onMore indicator - center aligned

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1618]
### Summary
For a List, the onMore loading indicator is not centered

### Expected behavior
I believe it looks better to have the indicator center aligned, especially for a heavy list with a lot of content, the eye is centered in the middle of the page

### Steps to Reproduce

https://grommet.github.io/hpe/docs/list/examples?onMore=func - scroll to bottom to have the list load more items, the indicator is in the left hand side bottom corner

### Suggested css change (my custom css file in this case): 
.grommetux-list__more{
  text-align:center;
}

**Comment by karatechops** [comment]
Hi @atanasster, thanks for filing this issue. If centering the Spinning component is your preference you can simply wrap your List in a Box which defines the text to be centered via the `textAlign` prop. I've created a [Codepen](https://codepen.io/karatechops/pen/gGbVYX?editors=0010) displaying this behavior.

**Comment by atanasster** [comment]
Thanks, that works for me, was just wondering if you guys might not prefer this to be the default behavior
