### ISSUE TITLE
Grommet Overriding Custom SCSS

### ISSUE THREAD

**Issue by jessegoraya** [grommet/grommet#1623]
I am using Grommet in my React site but have the need to style a web chat using my own custom css.  However when loading the page my chat component seems to be taking the styles of Grommet and not my custom scss.  

Can anyone point me in the right direction as to how best to fix this?

Here is my custom.scss file...

```
customstyle{

    body .wc-app, .wc-app button, .wc-app input, .wc-app textarea {
        font-family: 'Segoe UI', sans-serif;
        font-size: 15px;
    }
...
};

```

Here is my app.js
```

import webchatstyles from '../app/custom.scss';
...
 render() {
    return (
      <App centered={false}>
        <Article>
            <Split flex='right'>
              <Section>
                <Box margin='none' pad='none'>
                  <Chat className={webchatstyles.customstyle} directLine={{secret: 'GUID.Is.Here'}} user={{id:'test', name: 'test'}}/>
                </Box>
...
```

* Grommet version: 1.6
* Browser Name and version: Chrome Version 60.0.3112.113
* Operating System and version (desktop or mobile): Windows 10

**Comment by karatechops** [comment]
@jessegoraya have you considered [creating your own theme](https://github.com/grommet/grommet/issues/704#issuecomment-233392152) for your project? Take a look at how our [HPE theme](https://github.com/grommet/grommet/tree/master/src/scss/hpe) is structured.

```
@import 'hpe.defaults'; // import our theme default values specifying colors, fonts, etc.
@import '../grommet-core/index'; // import grommet's core theme which consumes these values
@import 'objects.button-hpe'; // import styles for any components we'd like to custom style
@import 'objects.anchor-hpe'; 
```

**Comment by jessegoraya** [comment]
@karatechops so if I  understand this correctly.  I would have my own index.scss (in my case custom.scss) which would make reference my defaults file (any custom colors), grommet's core theme which would use the default style from grommet for anything not specified in my custom file, and then any custom object files.  My custom objects would be any elements in chat component that I would like to uniquely style (e.g. wc-chatview-panel, wc-message, etc.)?

**Comment by karatechops** [comment]
@jessegoraya, yes that sounds correct. You will need to support loading scss files in your project, there's some example repos if you need a hand with that process.

Here's a file tree for reference:
```
src/
  js/
    index.js
  scss/
    _my-theme.defaults.scss
    index.scss
```

### index.js
```
import React from 'react';
import App from 'grommet/components/App';
import '../scss/index.scss';

export default class MyApp extends React.Component {
  render() {
    return (
      <App>
        {this.props.children}
      </App>
    );
  }
}
```

### index.scss
```
@import 'my-theme.defaults';
@import '~grommet/scss/grommet-core/index';

// Place any custom styles here or follow Grommet 1.x's pattern of placing styles
// in component specific .scss files.
// This is where the benefit of sass and theming comes into play.
body,
html {
  background: nth($brand-grey-colors, 2);
  
  @include media-query(lap-and-up) {
    background: nth($brand-grey-colors, 1);
  }
}

.wc-chatview-panel {
  background-color: nth($brand-accent-colors, 1);
}
```

You can check out the [HPE defaults file](https://github.com/grommet/grommet/blob/master/src/scss/hpe/_hpe.defaults.scss) to give you a good idea on how to structure your `_my-theme.defaults`.

**Comment by jessegoraya** [comment]
@karatechops thank you for the detailed explanation.  I'll definitely give this a shot.  Very helpful!
