### ISSUE TITLE
Support for xsmall progress bar;

### ISSUE THREAD

**Issue by panigrah** [grommet/grommet#1626]
I am working on an image uploader that needs to display upload progress. Upload progress needs to show up against the thumbnail of each image. Unfortunately the `Meter` component doesn't render in a small size that could work with the thumbnail size.

How do I manage small progress bars e.g. 48px wide?

thanks

**Comment by karatechops** [comment]
I believe @RyanCCollins was looking for a way to create a more flexible Meter width. Ryan, did you find anything for adjusting Meters width? From my experience Meter only supports select sizes.

As far as I know, Meter does not support this sort of customization. It sounds like for this sort of component you will need to build something custom. I've created a quick [Codepen](https://codepen.io/karatechops/pen/YrWqyG?editors=0010) displaying how you can pass your upload progress to a component.

I'd love to see more flexible widths in Grommet 2.x. Tagging 2.x's Meter card (#1452).
