### ISSUE TITLE
Pointing chrome to grommet.io sometimes redirects to grommet.io/LcWTz

### ISSUE THREAD

**Issue by dgennetten** [grommet/grommet#1629]
Browser responds with "Cannot GET /LcWTz/"

We've noticed this occur sporadically of late. Seems to clear itself.

**Comment by dgennetten** [comment]
guess this should have been in grommet-docs. oops.

**Comment by karatechops** [comment]
Looks like @alansouzati fixed this yesterday. Are you still seeing this behavior?

**Comment by dgennetten** [comment]
No. Will close.
