### ISSUE TITLE
Screen reader Chromevox crashes

### ISSUE THREAD

**Issue by alexxgathp** [grommet/grommet#1632]
It is not the most commonly used screen reader, but the Chromevox extension in Google Chrome crashes when visiting Grommet.io, as well as an earlier version of Grommet I have been using. I'm not sure how important this is, but it could shed light on another issue.
### Expected Behavior

Screen reader Chromevox reads elements on the page.
### Actual Behavior

Slowly loads the page, freezes, then crashes.
### Steps to Reproduce
 1. Install Chromevox in Google Chrome
 2. Go to Grommet.io
 3.  Or, create a Grommet website and visit it.

### Your Environment

* Grommet version: Grommet.io website, but also 0.6.10
* Browser Name and version: Google Chrome current plus Chromevox extension.
* Operating System and version (desktop or mobile):
Windows 7

**Comment by Thuranel** [comment]
Just wanted to say that I have the same issue in my project. It would be nice to find out what causes this.

**Comment by alansouzati** [comment]
I guess this issue it is better to be reported to Chromevox. We don't actively use it but we would be happy to fix anything that we identify on Grommet that needs fixing.
