### ISSUE TITLE
Mke onClick optional on Anchor elements with an href

### ISSUE THREAD

**Issue by anpieber** [grommet/grommet#1633]
The problem is, that there are situations like this:

```
<Anchor
            icon={<HelpIcon />}
            title="Help"
            target="_blank"
            href="/pdf/help.pdf"
/>
```

In this case Grommet correctly assumes the component as disabled executing the following code and going to the else branch. The adjustOnClick in the else branch though is not defined (since there is no onClick defined in the Anchor).

```
if (disabled) {
    event.preventDefault();
} else {
    adjustedOnClick.apply(undefined, [event].concat(args));
}
```

The link still works correctly, but produces a not-so-pretty error in the log. Using the following patch:

```
<Anchor
            icon={<HelpIcon />}
            title="Hilfe"
            target="_blank"
            onClick={() => { }}
            href="/pdf/help.pdf"
/>
```
"resolves" the problem. I think an easy if(adjustedOnClock) before calling on it would resolve the problem.

### Your Environment
* Grommet version: 1.7.0

**Comment by karatechops** [comment]
Hi @anpieber this was fixed in #1591 and will be available in the next release. For now you can use the [latest stable build](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F).
