### ISSUE TITLE
Using Theme To Augment Grommet Styling

### ISSUE THREAD

**Issue by jessegoraya** [grommet/grommet#1634]
Hello,
I am trying to augment the styling provided by Grommet with my own custom changes so that I may keep things like the font provided by Grommet but updating things such as spacing and placement.  As a result, I was able to successfully compile a custom theme but for some reason my custom styles still don't seem to be getting applied.

Any help would be much appreciated.  New to front end programming after being so focused on the back-end code for so many years so all of the help I have received is definitely appreciated.

**folder structure**
>app
|
|         
->js 
----app.js
->scss
---custom.scss
---_elu.defaults.scss

**app.js**

```
import  '../scss/custom.scss';
...
class PatientApp extends React.Component {
...
render
...
<Chat className='wc-app' directline='GUID_Entered_Here />
```

**custom.scss**

```
@import 'elu.defaults.scss';
@import '~grommet/scss/grommet-core/index.scss';

body .wc-app, .wc-app button, .wc-app input, .wc-app textarea {
    font-family: 'Segoe UI', sans-serif;
    font-size: 15px;
    background-color: #2AD2C9;
}
```
**webpack.config.js**

```
     {
        test: /\.scss$/,

        loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded&' +
        'includePaths[]=' +
        (encodeURIComponent(
            path.resolve(process.cwd(), './node_modules')
        )) +
        '&includePaths[]=' +
        (encodeURIComponent(
                path.resolve( process.cwd(),
                    './node_modules/grommet/node_modules'))
        )
        +
        '&includePaths[]=' +
        (encodeURIComponent(
                path.resolve( process.cwd(),
                    '../scss/'))
        )
      },
```

**My Environment**

Grommet version: 1.6
Browser Name and version: Chrome Version 60.0.3112.113
Operating System and version (desktop or mobile): Windows 10

**Comment by karatechops** [comment]
Hi @jessegoraya, this is a bit difficult to debug if I can't see the full project. Are you familiar with Chrome dev tools to make sure your styles are being compiled properly into the Project? Can we maybe isolate this to a single component in a project which you can share in a repo?

**Comment by jessegoraya** [comment]
Also I have created a Git repo for my code which can be found at the link below...

https://github.com/jessegoraya/Elu-Health-FrontEnd

**Comment by jessegoraya** [comment]
All thank you for all of the help but I was able to figure it out!  It had to do with the .wc-chatview-panel.  I set a width and height to that style and it now appears.  So now I can actually manipulate the look and feel.  @karatechops appreciate all of the guidance!
