### ISSUE TITLE
SSRender webpack server build IntlPolyfill issue in App component

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#1637]
I am experimenting with server side rendering and building shared server code with webpack.
Build is successful and it works except there is some issue with IntlPolyfill in App component.
By default if I am using grommet App component it fails at runtime.

```
from grommet App component: with the comments below it works
if (!localesSupported()) {
  require('intl');
  require('intl/locale-data/jsonp/en-US.js');
  require('intl/locale-data/jsonp/pt-BR.js');
  // Intl.NumberFormat = IntlPolyfill.NumberFormat;
  // Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
}
```

Error is strange but I guess I am not polyfilling intl with webpack correctly.
I am trying something like this on the server so webpack would pull it in but it does not work.

```
on the server
import areIntlLocalesSupported from 'intl-locales-supported';
const intlSetup = () => {
  const enabledLanguages = [
    'en',
    'sl'
  ];

  if (global.Intl) {
    if (!areIntlLocalesSupported(enabledLanguages)) {
      const IntlPolyfill = require('intl');
      Intl.NumberFormat = IntlPolyfill.NumberFormat;
      Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
    }
  } else {
    global.Intl = require('intl');
  }
};

export default intlSetup;

```
Error looks strange:

```
SyntaxError: Invalid regular expression: /[\s\S]{18}(((((((())))))))[\s\S]{34})/: Unmatched ')
at ...node_modules/intl/lib/core.js:590:20
at ...node_modules/intl/lib/core.js:3803:9)
at ..build/dist/server/webpack:/node_modules/grommet/components/App.js:51:1
at at localesSupported build/dist/server/webpack:/node_modules/grommet/components/App.js:50:1)
```
Webpack config is the usual and it works if I comment that part in App component.

### Your Environment
"grommet": "^1.7.0",
 node v8.3.0
 "webpack": "^3.6.0",

Anyone has idea how to fix this?

**Comment by karatechops** [comment]
This is a tough one. Is the goal to render in a specific language based on locale in the server render? I have not worked much with i11n and React but I have built many apps which use SSR. Would the initial render still work if you just check for window deferring the number/date polyfill until the first render? `if (typeof window !== 'undefined') mycode();`

**Comment by primozs** [comment]
Hi @karatechops 
Yes, locale gets selected and rendered also on the server. 
Yes, I guess I could always do this 
```
if (typeof window !== 'undefined') {
  Intl.NumberFormat = IntlPolyfill.NumberFormat;
  Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
} 
```
but I would need custom grommet App component implementation like I have now. I guess this is not an issue then. Somehow I thought this should be solved with webpack.
