### ISSUE TITLE
Defect : Search suggestion drop does not allow navigation

### ISSUE THREAD

**Issue by Catx7** [grommet/grommet#1640]
Add a Search with a big list of suggestions.
When you navigate using arrow keys between suggestions in the list the scrollbar does not move if the list is too big.

### Expected Behavior
When the list of  suggestions displayed on the screen reach at the end of visibility when arrow down key is pressed the scrollbar should move down and show other available suggestions.

### Actual Behavior
Scrollbar does not move down in sugestions list and you are not enable to  see where you navigate.

**Comment by karatechops** [comment]
Hey @Catx7, thanks for filing this issue. Would you mind providing a [Codepen](http://codepen.io/pen?template=gaEGPY&editors=0010) displaying the behavior so we can gain a better understanding of the issue.

**Comment by Catx7** [comment]
`import Search from "grommet/components/Search";
class HelloWorldApp extends React.Component {
  
  render () {
    let listOfSuggestions= ['element1' , 'element2, 'elemet3' ,.... 'element n'] //long list of suggestions

     let searchProps = {
      fill: true,
      inline: true,
      dropAlign: {"top": "bottom", "left": "left"},
      onDOMChange: (e) => changeSugegestionsList(e),
      suggestions: listOfSuggestions.toJSON(),
    };
    return (
      <App>
          <Box flex='grow'>
                <Box margin='none' pad='none'>
                  <Search
                    {...searchProps}
                  />
                </Box>
        </Box>
      
      </App>
    );
  }
};

var element = document.getElementById('content');
ReactDOM.render(<HelloWorldApp />, element);`

**Comment by L0ZZI** [comment]
Can you validate @karatechops ?

**Comment by karatechops** [comment]
@L0ZZI yes, I see the bug. Created a [codepen](https://codepen.io/karatechops/pen/GQgMjR?editors=0010) to display the behavior. When the user presses arrow down on the suggestions past the browser window the scroll bar does not update, the user will eventually be targeting elements below the fold.
