### ISSUE TITLE
Alignment is not proper using justification in Box 

### ISSUE THREAD

**Issue by noorisunique** [grommet/grommet#1641]
I am using Box Component here i want my parent Box should come in center so i am using justify='center'  but here justify  is not working properly because of it inner 4th Box is coming in center it should come below 1st Box 

### Expected Behavior
I want like this using justify='center' 
**With Three Box**
![alignment](https://user-images.githubusercontent.com/15786752/30908018-f75d94c2-a399-11e7-889a-6ff8cc190e8b.PNG)

**With Two Box**
![rowwithtwobox](https://user-images.githubusercontent.com/15786752/30951355-1f62c46e-a440-11e7-9b16-148f9ec44135.png)

### Actual Behavior
Here Box 4 is coming in center it should come below just Box1 
![rowlayoutcomponent](https://user-images.githubusercontent.com/15786752/30908055-184ea540-a39a-11e7-9bc5-6e1172f18ec9.PNG)

https://codepen.io/anon/pen/LzxVYM?editors=0010

### Steps to Reproduce
 1. 4th Box should come just below Box1

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by karatechops** [comment]
@noorisunique, I may need some more clarification on the layout you would like to see. Box's `justify` prop aligns the nested child depending on the Box's direction. When Boxes are set to row, the `justify` and `align` prop swap. Maybe you're looking for the `alignSelf` prop?

**Comment by noorisunique** [comment]
Hi thanks for response why i am using justify='center' because it makes my Main Box in center alignment that is correct but here nested child is coming in center also if i am using alignSelf or align prop not working i want like this 
![rowwithtwobox](https://user-images.githubusercontent.com/15786752/30951553-43f87b06-a441-11e7-8477-053dd82ead3c.png)
could you provide me any solution on this

**Comment by karatechops** [comment]
I believe in this scenario you could use the `basis` prop to keep the boxes centered properly in the nested element. Check out this [Codepen](https://codepen.io/karatechops/pen/EwbJgL?editors=0010) where I've swapped your box `size` prop for `basis`.

**Comment by noorisunique** [comment]
Hi This code is breaking in IE browser could you please check it once

**Comment by L0ZZI** [comment]
@noorisunique could you provide a codepen to validate what's happening in that image?

**Comment by L0ZZI** [comment]
We need a little more detail to validate @noorisunique. If you could create codepen or give a little more detail we're happy to look into it. If we don't hear back we'll close the issue 2 weeks from now.

**Comment by L0ZZI** [comment]
No reply. Closing.
