### ISSUE TITLE
Grommet Error with React v16.0.0

### ISSUE THREAD

**Issue by slipperypenguin** [grommet/grommet#1642]
When updating to React 16.0.0, a TypeError is produced. I've attached a screenshot of it below.

<img width="1030" alt="screen shot 2017-09-26 at 5 23 16 pm" src="https://user-images.githubusercontent.com/3655354/30885090-02faf3fc-a2e0-11e7-8c66-5cf2952f3be8.png">

### Your Environment
* Grommet version: 1.7.0
* Browser Name and version: Safari 11.0 (12604.1.38.1.7)
* Operating System and version (desktop or mobile): MacOS 10.12.6

**Comment by linde12** [comment]
Maybe this is because grommet isn't using React 16 yet, i get the same error.

It is because `this.setState({ routeChanged: false }, this._updateAnchors);` in SkipLinks.js which calls some React 15.3.x method internally. I will try with Grommet upgraded with React 16 and update with results.

**Comment by linde12** [comment]
Yep, after removing react 15 from `node_modules/grommet/node_modules/` and specifying `^16.0.0` in package.json (shouldn't have any impact, but i did it anyway) i can confirm that it works. My app works like before from what i've seen.

**Comment by slipperypenguin** [comment]
@linde12 Thanks for  looking into this!

I ended up specifying `^16.0.0` for both `react` and `react-dom` inside `node_modules/grommet/package.json` and removed react 15 from `node_modules/grommet/node_modules/`. 

It looks like that stopped the app from crashing, but resulted in another TypeError inside of `node_modules/grommet/components/icons/Header.js` that causes layout issues in my app. 

![screen shot 2017-09-27 at 10 01 37 am](https://user-images.githubusercontent.com/3655354/30918049-6bf4ac28-a36b-11e7-98e9-23213418fa9b.png)

**Comment by alansouzati** [comment]
I'm so glad to have community members trying out React 16 already. thanks for the effort here @linde12 and @slipperypenguin.

I'm in the process of updating Grommet 1.x to React 16. I will keep you guys posted.

**Comment by jamiepenney** [comment]
The `react-desc` package relies on React 15 directly, which is causing this issue.

**Comment by linde12** [comment]
@slipperypenguin I haven't used that icon, but the icons i use (AddIcon amongst other) work fine :confused:

I have a pretty complex app and just by upgrading the versions everything worked fine for me. I also didn't have any trouble regarding `react-desc`, i just installed grommet via yarn and then replaced the react & react-dom dependencies with version 16. Looking at the PR for react-desc it seems like it should only affect tests @slipperypenguin 

Maybe there's another issue causing this error?

**Comment by jamiepenney** [comment]
@linde12 the react-desc `package.json` had an explicit dependency on react 15.5.4, so it was pulling a second copy of react in and using that, which caused the error - see this issue on the react repo https://github.com/facebook/react/issues/10320

**Comment by linde12** [comment]
@jamiepenney I see, however the error occurred for me because of Grommet's `SkipLinks` component (which does something like `this.setState({ value }, this.doSomeMore );`) and not because of `react-desc`. Look over here: https://github.com/grommet/grommet/blob/master/src/js/components/SkipLinks.js#L45

Either way, it all boils down to different versions of react being bundled. So just upgrading all packages using react to react 16 should work! :+1:

**Comment by jamiepenney** [comment]
@alansouzati any chance we could get a release out with the new React dependencies?

**Comment by linde12** [comment]
I think we can close this due to 1.8.0 release? See: https://github.com/grommet/grommet/releases/tag/v1.8.0

**Comment by slipperypenguin** [comment]
Yep, just tested it out after updating to grommet v1.8.0 and everything looks good.
Thanks everyone for the help!
