### ISSUE TITLE
controlling the number of max component in row while rendering using BOX

### ISSUE THREAD

**Issue by noorisunique** [grommet/grommet#1644]
I am creating Row Layout Component here i want to control MaxCount in a row how can i control it
based on my requirement if i want two or three Box in a row it should come  and remaining should come in new Row

### Expected Behavior
I want like this only 
![rowlayout](https://user-images.githubusercontent.com/15786752/30900277-0634cf4c-a381-11e7-8e44-acb32dde95ef.png)

### Actual Behavior
https://codepen.io/anon/pen/PJpOvQ?editors=0010
![rowlayoutcomponent](https://user-images.githubusercontent.com/15786752/30900344-5252fdfe-a381-11e7-91e0-71edde86c7df.PNG)

here I want max two Box in a row, 3rd and 4th Box should come in new Row with having in same Horizontal line

### Steps to Reproduce
 1. i wan to control maximum no of count  in a row 
 2. i want horizontal alignment
 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by karatechops** [comment]
@noorisunique you can set the max width of the containing Box, check out this [codepen](https://codepen.io/karatechops/pen/KXWLdz?editors=0010) for an example. Alternatively you can checkout [Grommet's Column component](http://grommet.io/docs/columns).

**Comment by noorisunique** [comment]
Hi thanks for response but I don't want to use Column Component i want to achieve Row Layout only 
here what you have done is fix code for tow Box but  i don't want to fix two Box only suppose i want 3 Box  or 4 Box in a row then how can i control it , i want like this screen shot given below 
![rowwithtwobox](https://user-images.githubusercontent.com/15786752/30949941-15221094-a437-11e7-9b7f-0e443b98be7b.png)
![rowwiththreebox](https://user-images.githubusercontent.com/15786752/30949947-1e3aa0ec-a437-11e7-8ee6-4f8e1791ebe8.png)
