### ISSUE TITLE
Image Fit/Full Breaks in Safari

### ISSUE THREAD

**Issue by pochenwu** [grommet/grommet#1647]
The Image component, when set True with fit/full props, disappears in Safari. (Which also affects Carousel if used with the Image component)

### Expected Behavior

Image with fit/full set to be True should expand to the whole container.

### Actual Behavior

Image disappeared. With inspection, the problem seems to be resulted from the '.grommetux-image--full' class and the 'min-height' attribute. Once the attribute removed or overridden, Image appears again, but sometimes not filling the whole container (in Carousel).

### URL, screen shot, or Codepen exhibiting the issue
<img width="1355" alt="2017-09-28 10 40 15" src="https://user-images.githubusercontent.com/16420839/30976411-5681b0e6-a43a-11e7-8501-ef80be5a4c36.png">
http://grommet.io/docs/image/examples?fit=contain&size=large

### Steps to Reproduce
 1. Create Image component (or use the demo one from http://grommet.io/docs/image/examples/)
 2. Set fill to a value or full to True

### Your Environment

* Grommet version: 1.7.0 & current demo version on grommet.io
* Browser Name and version: Safari 10.1.1 (12603.2.4)
* Operating System and version (desktop or mobile): Desktop, macOS Sierra 10.12.5

**Comment by hashtonmartyn** [comment]
I'm having a similar problem with setting `fit='contain` on an Image component in a Carousel. On desktop chrome the images are visible but on ios 10 with chrome the images are not visible and the component to the right of the Carousel takes their place.

**Comment by dgennetten** [comment]
I am not seeing this issue. Could you check and verify that it is still occurring?
