### ISSUE TITLE
Incorrect color behavior for Status, icons when contained in Boxes with dark backgrounds

### ISSUE THREAD

**Issue by clarktlaugh** [grommet/grommet#1652]
### Expected Behavior
I am trying to make Status or an Icon colored ('warning') on a dark background.  I could understand by default maybe having the color be white-on-dark, but there should be a way to override to force the color to show.

### Actual Behavior
Depending on the colorIndex specified for the Boxes containing the icons, the resulting color is not as expected.  In one instance, the resulting output is a white icon on a white background.

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/clarktlaugh/pen/KXqoOR

### Your Environment
* Grommet version: 1.6.0
* Browser Name and version: Chrome 61
* Operating System and version (desktop or mobile): Windows 10

**Comment by dgennetten** [comment]
Fixed with PR #1709
