### ISSUE TITLE
Table Header is fixed to the page when scrollable is true

### ISSUE THREAD

**Issue by DheerajVecham** [grommet/grommet#1661]
### Expected Behavior
My expectation is to keep the table header fixed for the table and move along with the page as user scrolls up/down.

### Actual Behavior
The header is fixed at some position of the page. When the page is scrolled up or down the header is still fixed at the same position.

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/DheerajVecham/pen/BwwJem?editors=0010

### Steps to Reproduce
 1. Open the code pen link
 2. Scroll down to the bottom of the page, observe the table header at the middle of the page.
![header](https://user-images.githubusercontent.com/32483151/31122647-4526d6f4-a85a-11e7-9476-319138d3a145.png)

Please help me in fixing the issue.

Thanks in advance.

**Comment by karatechops** [comment]
This is the exact issue in #1567 (even with the same screenshot), correct? I posted a [workaround](https://codepen.io/karatechops/pen/zdXJQY?editors=0010) in that issue, this issue stems from a bigger issue with Box (#1606) which will most likely not be fixed in 1.x.

**Comment by jornncc** [comment]
There is an issue with not being able to click the column headers to sort when scrollable="true".

**Comment by karatechops** [comment]
@jornncc I'm able to pass the `onSort` property to the table header. Here's an [example](https://codepen.io/karatechops/pen/jZPQoQ?editors=0010).
