### ISSUE TITLE
Heading's margin applies to top and bottom

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#1668]
Previously the `margin` prop on Heading would only increase the bottom margin. As the docs state:
> margin      none|small|medium|large
> The vertical margin below the Heading. Defaults to medium. 

### Expected Behavior
Heading's margin prop should only apply to below the Heading element.

### Actual Behavior
Margin applies to top and bottom when `margin` prop is explicitly set.

### URL, screen shot, or Codepen exhibiting the issue
![screen shot 2017-10-04 at 4 41 47 pm](https://user-images.githubusercontent.com/5983843/31198630-f4d49532-a922-11e7-8f64-c73bdd12ddaa.png)

http://grommet.io/docs/heading/examples?margin=large

### Your Environment

* Grommet version: 1.8.2
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): N/A

**Comment by alansouzati** [comment]
Yeah this change was done [one year ago](https://github.com/grommet/grommet/commit/460e1b38edcc934d1c0ea1d3896e213bddf5511b#diff-a13a637acffab47d52682289b0c1ec16R27), and it was a planned change. Back in the days we did a minor release with this, so our apologies for releasing a break change in a minor increment.

The docs seems to be out of date, we should definitely fix this. @dgennetten as you are working on this, I believe we can fix it by updating the documentation.

Let's say you have the following structure:

```
<div>
  <Heading />
  <Paragraph />
  <Text />
  <Heading />
  <Text />
  <Paragraph />
</div>
```

you probably want margin top and bottom in all headings, expect the first one. You can anytime override the default settings by doing something like this (for grommet v2):

 ```
<div>
  <Heading margin={{ bottom: 'large' }} />
  <Paragraph />
  <Text />
  <Heading />
  <Text />
  <Paragraph />
</div>
```

**Comment by dgennetten** [comment]
Understand and agree. Docs updated. Will close if no objection.

**Comment by karatechops** [comment]
@alansouzati the example for V2 makes sense and I do agree that's the best approach. I was trying to point out the inconsistency of the default styling of only applying margin to bottom unless there's a margin prop set.
![screen shot 2017-11-15 at 3 40 41 pm](https://user-images.githubusercontent.com/5983843/32859070-6c604f4c-ca1b-11e7-9d58-c5bddce4cc38.png)
It seems the default margin for this component should be set to top and bottom to be congruent with Paragraph's default margins. However, Headline uses only bottom margin ... 😅

**Comment by dgennetten** [comment]
@karatechops I think this asymmetry might make sense for Headline over Heading. A doc can easily have Headings placed under other content, whereas a Headline tends to be a top-of-container element. At any rate, that would be a separate ticket, so I'm going to go ahead and close this one.
