### ISSUE TITLE
Conditional rendering of a Tile is broken

### ISSUE THREAD

**Issue by christianrank** [grommet/grommet#1669]
Since v1.8.0 you can't render a `<Tile>` conditionally anymore.
Before, it was possible like this, which we use a lot in our code:
```jsx
<Tiles>
...
{condition && <Tile>...</Tile>}
...
</Tiles>
```

### Expected Behavior

When the condition is false, the Tile should not be displayed, like it worked in v1.7.0 of Grommet: https://codepen.io/anon/pen/BwJXez

### Actual Behavior

The whole app crashes, saying `Uncaught TypeError: Cannot read property 'props' of null`

### URL, screen shot, or Codepen exhibiting the issue
https://codepen.io/anon/pen/OxQLRW

### Steps to Reproduce
1. Open the Codepen link
2. It doesn't render and throws an error

### Your Environment

* Grommet version: v1.8.2
* Browser Name and version: Chrome 61
* Operating System and version (desktop or mobile): MacOS

The Issue was introduced by this change:
https://github.com/grommet/grommet/commit/f670b4d05b2af35aa673dd1dd8b76032c79ed7c7#diff-a9a83a3db4ad0bfba2b6132b0fc87443R352

**Comment by alansouzati** [comment]
sorry about that folks. Let me look into this and release a patch (1.8.3) today

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/0002ee0a22573e8784a66b32fba85947bc9b2039

Let me release 1.8.3, I will put it here when we have the patch release available.
