### ISSUE TITLE
Variable Toast duration

### ISSUE THREAD

**Issue by fauricioRojas** [grommet/grommet#1671]
### Expected Behavior
Toast should use a variable duration received by props.

### Actual Behavior
Toast uses a default constant duration.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/14350470/31351257-9f84ea3c-ace7-11e7-9b61-ecefa72c02ca.png)

### Steps to Reproduce
N/A.

### Your Environment

* Grommet version: 1.8.3
* Browser Name and version: N/A.
* Operating System and version (desktop or mobile): N/A.

**Comment by alansouzati** [comment]
Fixed by the PR thanks again @fauricioRojas

**Comment by fauricioRojas** [comment]
Your welcome @alansouzati
