### ISSUE TITLE
Can't remove "Skip to" in heading?

### ISSUE THREAD

**Issue by AaronVasquez** [grommet/grommet#1675]
I have just 

```
<App>
</App>
```

"Skip to" is rendered at the top, and I can't find any docs on what's causing it or how to remove it.
[screenshot](https://drive.google.com/open?id=0B5uAlChUfRKHazN5QkpZZnRXZGM)

**Comment by alansouzati** [comment]
Hey this seems like a problem of missing CSS. Grommet 1.x does require you to manually include the styles or use SASS. if you installed using NPM we include the minified styles in there. Or if you prefer you can use CDNJS to get grommet styles applied to your app:

https://cdnjs.com/libraries/grommet

https://cdnjs.cloudflare.com/ajax/libs/grommet/1.8.3/grommet.min.css

I'm closing this issue, but feel free to continue the discussion here.

**Comment by sebasalvarado** [comment]
Having the same issue here, I installed using npm and I can't get rid of it. How can I fix this?
