### ISSUE TITLE
Layer.js should not process tab while hidden

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1678]
As reported on Slack by aaronvasquez 
### Expected Behavior
Layer.js should not handle tab events while hidden

### Proposed fix:
  _processTab (event) {
    const {hidden} = this.props
    if (hidden) return false;

**Comment by alansouzati** [comment]
makes total sense. can you send a PR for this? thanks for identifying this. you are the best!

**Comment by atanasster** [comment]
Great, thanks :) will do

**Comment by atanasster** [comment]
PR https://github.com/grommet/grommet/commit/8b2f95252053e8717779f48ccca528de5c0651a5, closing
