### ISSUE TITLE
Carousel animates entire page.

### ISSUE THREAD

**Issue by joeydebreuk** [grommet/grommet#1684]
### Expected Behavior
There should only be an animation upon clicking next image.

### Actual Behavior
Upon rendering carousel the width starts 3000px+ and animates to the needed with, moving the entire splitsection.

### URL, screen shot, or Codepen exhibiting the issue
https://grommet.slack.com/files/U7648JAE8/F7JSZ6BNV/whatsapp_video_2017-10-17_at_12.27.21.mp4

https://codepen.io/anon/pen/JreQBM?editors=0010

### Your Environment
* Grommet version: 1.7
* Browser Name and version: chrome, edge, firefox
* Operating System and version (desktop or mobile): windows

**Comment by karatechops** [comment]
This is resolved by adding the following style
```
.grommetux-split__column {
  overflow:auto;
}
```

Here's a [codepen](https://codepen.io/karatechops/pen/EQjGPV?editors=0110) displaying the fix.

@ericsoderberghp or @alansouzati any repercussions to adding this to our core styles? I have not used the Split component in any apps so my frame of reference here is pretty limited.

**Comment by L0ZZI** [comment]
@karatechops can you add a PR?
