### ISSUE TITLE
ie11 flex-basis is not calculated correctly

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet#1702]
### Expected Behavior
Flex-basis should calculate the same in ie11 as in chrome.

### Actual Behavior
ie11 does not calculate flex-basis properly, leading to overflow issues.

### URL, screen shot, or Codepen exhibiting the issue
None

### Steps to Reproduce
 1. Create a flex-box row layout with three children set to flex-basis: 1/3
 2. See that in ie11 the container is overflowing

### Your Environment

* Grommet version: Latest
* Browser Name and version: ie11
* Operating System and version (desktop or mobile): MacOSX

**Comment by RyanCCollins** [comment]
A proposed fix is to add the following to the grommet box scss (this needs to be repeated for each basis and for the basis with padding in between).

```
.grommetux-box--basis-1-3 {
  @media all and (-ms-high-contrast:none) {
    max-width: 33.3%;
  }
}
```

**Comment by RyanCCollins** [comment]
So I'm not exactly sure how to display this.  It is happening in a project that I'm unable to share publicly.  Therefore, I have taken screenshots to show the behavior.  Also, I am [linking to the corresponding flexbox bug](https://github.com/philipwalton/flexbugs#7-flex-basis-doesnt-account-for-box-sizingborder-box). 

IE11: children with flex-basis overflow their parent:
![screen shot 2017-10-27 at 10 18 42 am](https://user-images.githubusercontent.com/13810084/32108962-46d6dde6-bb01-11e7-924a-65dead1c4b84.png)

Chrome: children are rendered correctly
![screen shot 2017-10-27 at 10 15 16 am](https://user-images.githubusercontent.com/13810084/32109076-a0b85d30-bb01-11e7-9132-48cdc6bcb6d8.png)

**Comment by L0ZZI** [comment]
Good catch! I have it flagged, but we'll need to verify it in v2. V1 it's open to community.
