### ISSUE TITLE
Clicking Search icon in Mobile throwing error

### ISSUE THREAD

**Issue by idrakimuhamad** [grommet/grommet#1707]
I was using the Search component in header as one shown on http://grommet.io/docs/header/examples/, it works great in normal view, but when I tried it with mobile user agent, or on mobile, it throwing error

Even if you didn't use the user agent, by just resizing your window to a small size, it will then trigger the error

`TypeError: Cannot read property 'focus' of null`
### Expected Behavior

It should show the search input, something like in http://ferret.grommet.io site, which working fine in mobile

### Actual Behavior
It throw an error about the in-existence of the input thus it can't focus on it.

### URL, screen shot, or Codepen exhibiting the issue
http://grommet.io/docs/header/examples/
By using the Chrome device toolbar

### Steps to Reproduce
 1. Load the URL
 2. Open developer tool in Chrome, and toggle the device toolbar
 3. Select any mobile User agent. Tested on iPhone 6

### Your Environment
* Grommet version: I think the one use in the homepage was the stable version, probably 1.8.3
* Browser Name and version: Chrome 61.0.3163.100
* Operating System and version (desktop or mobile): MacOS High Sierra

**Comment by dgennetten** [comment]
Fixed with PR 1723
