### ISSUE TITLE
Clicking a Select that is inside a FormField makes the Select value text wiggle

### ISSUE THREAD

**Issue by Thuranel** [grommet/grommet#1715]
When you place a Select inside a FormField, clicking on the Select to show additionnal options makes the text inside the Select move slightly to the right before moving back to its original position.

### Expected Behavior

The text should stay in its position.

### Actual Behavior

The text wiggles.

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/Thuranel/pen/RjRWgP

### Steps to Reproduce
 1. Place a Select in a FormField
 2. Click on the Select
 3. Notice how the text wiggles

### Your Environment

* Grommet version: 1.8.3
* Browser Name and version: Chrome 
* Operating System and version (desktop or mobile): Windows 10

**Comment by atanasster** [comment]
Thuranel, can you try this css patch :
.grommetux-form-field__contents>.grommetux-select input{
  padding-left:22px;
 } 
If there are no side effects, I could submit a PR

**Comment by L0ZZI** [comment]
thanks @atanasster! Did work @Thuranel

**Comment by L0ZZI** [comment]
Closing at 2 week mark.

**Comment by L0ZZI** [comment]
No reply. Closing.
