### ISSUE TITLE
Extraneous scrollbars in FormFields in a Layer on Chrome v62 when browser zoom isn't 100%

### ISSUE THREAD

**Issue by jonrsawyer** [grommet/grommet#1716]
### Expected Behavior

We don't expect scrollbars on any FormField. This appears to be new with Chrome v62.

### Actual Behavior

Some of the FormFields get scrollbars.

### URL, screen shot, or Codepen exhibiting the issue

View the following Codepen in Chrome v62 on Windows with browser zoom at 90%
https://codepen.io/jsawyer/pen/MOyKbg

You'll see something like the following:

![image](https://user-images.githubusercontent.com/2525277/32451602-7345260a-c2d4-11e7-837e-f8dec52b8383.png)

### Steps to Reproduce
 1. https://codepen.io/jsawyer/pen/MOyKbg
 2. Change the browser zoom to 90%
 3. 

### Your Environment

* Grommet version: 1.8.3
* Browser Name and version: Chrome v62 
* Operating System and version (desktop or mobile): Windows 7

**Comment by karatechops** [comment]
I can confirm this bug. It looks like [this style](https://github.com/grommet/grommet/blob/master/src/scss/grommet-core/_objects.form-field.scss#L43) in FormField is causing it. @ericsoderberghp do you remember why this was needed?
