### ISSUE TITLE
ListPlaceholder doc not showing anything

### ISSUE THREAD

**Issue by clemmy** [grommet/grommet#1725]
I was browsing the [ListPlaceholder docs](http://grommet.io/docs/list-placeholder) and encountered an infinite spinning logo.

### Expected Behavior
I'm not sure what is expected.

### Actual Behavior
I see a spinning logo.

### URL, screen shot, or Codepen exhibiting the issue

<img width="935" alt="screen shot 2017-11-12 at 4 59 49 am" src="https://user-images.githubusercontent.com/3696934/32696093-5c8a729e-c766-11e7-90f6-fbf65597700f.png">

### Steps to Reproduce
 1. Visit http://grommet.io/docs/list-placeholder

### Your Environment

* Grommet version: n/a
* Browser Name and version: Chrome v62.0.3202.75 64-bit, Firefox 56.0 64-bit
* Operating System and version (desktop or mobile): Mac OSX 10.11.6

**Comment by L0ZZI** [comment]
Can you check it again? I can't reproduce.

**Comment by clemmy** [comment]
Now, I see this:

<img width="845" alt="screen shot 2018-01-30 at 2 34 32 pm" src="https://user-images.githubusercontent.com/3696934/35587083-b708cbe2-05ca-11e8-9fb2-9890b53aa2fa.png">

**Comment by L0ZZI** [comment]
That's what I see. @alansouzati is that what he's supposed to see?

**Comment by L0ZZI** [comment]
That is what you're supposed to see... @alansouzati is that what he's supposed to see?

**Comment by L0ZZI** [comment]
@alansouzati comment so we can close MR Add-on king!
