### ISSUE TITLE
Toast size large is showing small icon

### ISSUE THREAD

**Issue by shai32** [grommet/grommet#1733]
Toast size large is showing small icon
when rendering
` <Toast size="large" status="ok">my toast    </Toast>`
the status icon is not large

### Steps to Reproduce
 1. render  `<Toast size="large" status="ok">my toast    </Toast>`
 2. the status icon is not large

### Your Environment
* Grommet version: 1.9.0
* Browser Name and version: chrome 63
* Operating System and version (desktop or mobile): mac 10.12.6 desktop

**Comment by shai32** [comment]
?

**Comment by shai32** [comment]
?

**Comment by alansouzati** [comment]
This definitely looks like a bug. By a quick investigation, it seems that this [line](https://github.com/grommet/grommet/blob/master/src/js/components/Toast.js#L81) is the culprit. Are you up for a pull request to fix this?

Hopefully I will be faster reviewing your pull request (I remember you sent a pr that I took forever to review and approve).

**Comment by shai32** [comment]
I added a PR, please review
https://github.com/grommet/grommet/pull/1767

**Comment by shai32** [comment]
@alansouzati

**Comment by shai32** [comment]
?

**Comment by shai32** [comment]
?

**Comment by shai32** [comment]
?

**Comment by ericsoderberghp** [comment]
Fixed in https://github.com/grommet/grommet/pull/1782
