### ISSUE TITLE
Tables need a "onMoreAbove" function; possible "Top" link

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#1738]
When dealing with larger quantifies of data we need a way to handle large amounts of data above the current scroll position. In many cases we may link a user directly into a row that could have thousands of rows above. We can contribute to this.

Suggestions...
1) When scrolling to the top activate an "onMoreAbove" function similar to the "onMore" function that exist today. Spinner behavior, etc would also be modeled from "onMore"
2) Have a link (or icon) that allows a user to jump directly to the top of the table, discarding the current scroll position and any current table selections.

**Comment by L0ZZI** [comment]
Closing this, and adding an action item to next conversation.
