### ISSUE TITLE
Split fixed=true results in height of 100vh

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#1739]
If you set fixed=true to get the desired independent scroll behavior you get the side effect that height is set to 100vh. Normally in Grommet 100vh is only used if you set full=true. As a result its difficult to use a split when surrounded with other decarations. 

Perhaps we should introduce a full parameter that would set the height to 100vh rather than assume it when fixed is set.

_objects.split.scss
.#{$grommet-namespace}split__column--fixed {
  @include media-query(lap-and-up) {
    position: relative;
    height: 100vh; <<<<=== SHOULD NOT BE FULL SCREEN JUST BECAUSE FIXED=TRUE
    overflow: auto;
    -ms-overflow-style: -ms-autohiding-scrollbar;
  }
}

**Comment by L0ZZI** [comment]
Ditto. Captured and closed.
