### ISSUE TITLE
When a drop menu has a fixed header, clicking on that header while the menu is open does not close the menu

### ISSUE THREAD

**Issue by frandr** [grommet/grommet#1742]
This is a regression added with this commit: 22ff8308e634829a519010826664ab6cf341a6ab, on 8/24/17.

With that commit (which fixed an unrelated problem) we added the following logic in Menu.js, within _checkOnClose:

_if (drop && !drop.contains(event.target) && !control.contains(event.target)) {
    this._onClose();
}_

The second clause in this if statement (which was added with the above commit) is causing us to ignore the click on the menu header. This is incorrect:

If the user clicks outside the menu when the menu is open, then control.contains(event.target) is false, and we close the menu correctly. However the menu button is *within* the control, and so control.contains(event.target) is true in that case, and we don't close the menu in that case.

So the second clause of the if stmt is incorrect and should be removed.

### Expected Behavior

T

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by karatechops** [comment]
Hi @frandr, can you assemble a [Codepen](http://codepen.io/pen?template=gaEGPY&editors=0010) to display this behavior for us easily diagnose and fix? I tested in the [docs example](http://grommet.io/docs/menu/examples?closeOnClick=true&icon=true&i-anchors=true) and do not see the behavior you're describing.
