### ISSUE TITLE
Text box pop ups drift on iPhone

### ISSUE THREAD

**Issue by donkeybonks** [grommet/grommet#1752]
iPhone 6, latest software, safari.

They don’t line up with the bottom of the text boxes and randomly fly around the page when you scroll up and down. They scroll at a completely different rate to page scrolling. Sometimes they open off screen.

Might be a viewport scaling issue?

**Comment by L0ZZI** [comment]
Nice catch, we're seeing it in Grommet V1, and investigating this in V2. We'll tag it to see if anyone can take a pass at identifying and/or fixing it.
