### ISSUE TITLE
Select field onFocus

### ISSUE THREAD

**Issue by florianbepunkt** [grommet/grommet#1760]
This is a feature request regarding accessibility and/or ease of use.

When you have long forms it's best practice that you can tab through the form. This works quite well exept for the select field.

**Expected behaviour:**
When you tab through a form and reach a select field, the select field should be focused and when you start typing, you should get the option that best matches your input. This is the standard behaviour of the select tag (https://www.w3schools.com/tags/tag_select.asp)

Ideally the dropdown should open.

**Actual behaviour:**
Nothing happens. Instead you have to click on the dropdown and select an option.

**EDIT**
I got half there by adding an `onFocus` method to select fields input (https://github.com/grommet/grommet/blob/68fb633e9fcd2d7e571f2760e3414775cd4497ff/src/js/components/Select.js#L459)

```
return (
        <div ref={ref => this.componentRef = ref} className={classes}
          onClick={(event) => {
            (!disabled) ? this._onAddDrop(event) : null
          }}>
          {shouldRenderElement && renderedValue}
          <input {...restProps} ref={ref => this.inputRef = ref}
            type={shouldRenderElement ? 'hidden' : 'text'}
            className={`${INPUT} ${CLASS_ROOT}__input`}
            placeholder={placeHolder} readOnly={true}
            disabled={disabled}
            onFocus={(event) => {
              this._onAddDrop(event);

              if (this._searchRef) {
                this._searchRef.focus();
                this._searchRef._inputRef.select();
              }
            }}
            value={renderedValue || ''} />
          {!disabled && (
            <Button className={`${CLASS_ROOT}__control`}
              a11yTitle={Intl.getMessage(intl, 'Select Icon')}
              icon={<CaretDownIcon />}
              onClick={this._onAddDrop} />
          )}
        </div>
      );

```
But `this._searchRef.focus()` never gets called as `this._searchRef` is not set. I guess this is a bug as `this._searchRef` should have been set in `renderOptions()` method.

Anyway, if it would be possible to automatically focus the search input field I could put together a pr.

**Comment by L0ZZI** [comment]
We're putting a lot of effort in the Grommet v2, http://v2.grommet.io have you tried the components there to see that they work as expected?

If you or anyone has some cycles in the community  we'll tag this one as "help wanted" and work with them on the PR. Let us know if this works?
