### ISSUE TITLE
Barebones Grommet app with grommet new sample-app??

### ISSUE THREAD

**Issue by mjsevilla** [grommet/grommet#1770]
The sample app that's created with the `grommet` cmd from grommet-cli is WAY too much for my needs. Is there something similar along the lines of create-react-app? I don't need a server or users or any of that, just want a single page app I can start building on.

**Comment by ericsoderberghp** [comment]
Have you tried `grommet new basic`?

Also, I think this issue belongs in `grommet-cli` and not `grommet`.

**Comment by L0ZZI** [comment]
No response from owner, closing...
