### ISSUE TITLE
Add Ordering to List Component

### ISSUE THREAD

**Issue by mjsevilla** [grommet/grommet#1771]
That's pretty much it in the title. Can this feature be added? Or does anyone know a clean way of doing it? I'm just trying to place a simple and elegant step-by-step instruction list inside of an Accordion component.

**Comment by ericsoderberghp** [comment]
I'm not sure what you mean by "Ordering". Do you mean that the items in the list should be ordered, or sorted, a certain way? Or, do you mean that you'd like to see ordinal number prefixes for each item in the list, e.g. 1., 2., 3. ?

The former is controlled by how you populate the children of the List. For the latter, one simple idea would be to insert the numbers within the content of the list items themselves. For instance:

```
<List>
  {items.map((item, index) => `#{index}. #{item}`)}
</List>
```

**Comment by L0ZZI** [comment]
Hey @mjsevilla did this answer your question. it's been sitting in our backlog for bit, so in 2 weeks we'll close if we don't hear a response.

**Comment by mjsevilla** [comment]
Yes, apologies for the late response!
