### ISSUE TITLE
how to handle keypress event in react.js

### ISSUE THREAD

**Issue by cristyalex** [grommet/grommet#1772]
There is a textinput field. When I press spacebar key in that text field, it should not take it.

This is the code Iam giving-

const CertifyItemPopup = (props, state) => {
function AvoidSpace(e){
    e= e || window.event;
    var charCode= e.charCode || e.keyCode;
    var character= String.fromCharCode(charCode);
    console.log(charCode);
  
    if(e.charCode==32 || e.keyCode==32){
      e.preventDefault();
     console.log("space bar was clicked");
    }
  }

return(
       
![image](https://user-images.githubusercontent.com/34138120/34039881-55169cac-e1b7-11e7-8df8-a14b8d86c63e.png)

);
}

But the above code is not working.

**Comment by cristyalex** [comment]
I also tried,

function AvoidSpace() {
  
   var k = event ? event.keyCode: event.charCode;
  
   if (event.fromCharCode == 32) 
 
    { 
      event.preventDefault();
  
     console.log(String.fromCharCode(event.keyCode));
  
    }

  }
is there any alternative way for this? I need this to run in reactjs.

**Comment by webdeb** [comment]
This is not a grommet issue. You problem is, that you are calling the handler instead of passing it.
instead of `onKeyPress={AvoidSpace(event)}`
just `onKeyPress={AvoidSpace}`
