### ISSUE TITLE
2.0.0-alpha releases are being released to npm without next tag

### ISSUE THREAD

**Issue by XuluWarrior** [grommet/grommet#1773]
Currently running **npm install grommet** will install 2.0.0-alpha.5

I don't think that this is intended behaviour as I see in the release list that it alternates between 1.9.x and 2.0.0-alpha releases.

**Comment by alansouzati** [comment]
Yeah, that's a good idea. I'm sorry for that, I was not aware of the tagging capabilities of NPM (shame on me).

I will soon fix this by releasing a new version of 1.9.X. After this is done, I will make sure that all future v2 releases will have the proper `--tag next`.

Thanks for bringing this to our attention. I will leave this issue open while we don't release new stuff.

**Comment by ericsoderberghp** [comment]
This has been fixed with the releases of grommet 1.10.0 and 2.0.0-alpha.6.
