### ISSUE TITLE
Paragraph inherit width of parent component

### ISSUE THREAD

**Issue by mjsevilla** [grommet/grommet#1775]
I have a `<Paragraph>` component inside of an `<AccordionPanel>` component and the paragraph width is extremely smushed. Even when I set `width='large'` prop inside paragraph, there is so much extra whitespace within the accordion panel. How can I fix this?

**Comment by mjsevilla** [comment]
All that extra whitespace I want to use.
![capture](https://user-images.githubusercontent.com/7141345/34126404-4e41fc3a-e3ee-11e7-8c41-b47369f3ade4.PNG)

**Comment by ericsoderberghp** [comment]
The width of `Paragraph` is constrained in order to make the text more readable. See: https://en.wikipedia.org/wiki/Line_length#Electronic_text

If you wanted the text to fill the entire width, which I would not recommend from both design and usability perspectives, you could just use a `<div>`.

**Comment by L0ZZI** [comment]
@mjsevilla does this answer makes sense? Let us know if this needs further discussion.

**Comment by mjsevilla** [comment]
Yes, thanks for the clarification. Cheers.

**Comment by DavidUnzue** [comment]
I found this after wondering why the Paragraph component wouldn't stretch to full width and discovering it has a hard coded `max-width` property.

The reason provided by @ericsoderberghp (which by the way should probably be written in the documentation) is understandable. However, in my opinion, this behaviour is extremely opinionated and it should be left to the developer to decide how to present the text.

Is there maybe a way to override this from within a theme object?
