### ISSUE TITLE
In Date Time Component, icon is not customizable. I want to use different icon than default.

### ISSUE THREAD

**Issue by ankit-github** [grommet/grommet#1778]
I just want to use different icon for date and time component. But component doesn't have props though which i can change it,

Please help me to solve this issue.

**Comment by L0ZZI** [comment]
The grommet V1 implementation is a little less accessible and flexible a component. Checkout out the freshly minted Calendar in Grommert v2, http://v2.grommet.io/calendar

**Comment by L0ZZI** [comment]
Let me know if this fixes your issue.

**Comment by L0ZZI** [comment]
No reply. Closing.
