### ISSUE TITLE
I am using the Tiles component onMore function, how to close the spinning when the server does not have the data to be loaded

### ISSUE THREAD

**Issue by laoergege** [grommet/grommet#1787]
### Expected Behavior
When the server has no loadable data, I want to be able to destroy spinning

### Your Environment

* Grommet version: ` "grommet": "^1.9.0",`
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
Omit the `onMore` property from the Tiles component. You can see more detail in the description of `onMore` for the Table component. We will update the documentation to make it clearer.
