### ISSUE TITLE
Allow menu label to accept more complex html elements.

### ISSUE THREAD

**Issue by jcdavison** [grommet/grommet#1792]
```
      <Menu responsive={false}
        closeOnClick={false}
        inline={false}
        dropAlign={{left: 'left', top: 'top'}}
        label={<span className='some-class'>some text</span>}
      >
```
Grommet obv doesn't like the `<span>` supplied as a label but this is a very useful pattern, would be great to see the menu props relaxed to allow for styles span elements as labels.

**Comment by karatechops** [comment]
Hi @jcdavison! For this pattern I would suggest passing your custom label via the icon prop which expects a node. I've created an example in a [Codepen](https://codepen.io/karatechops/pen/ddGvdN?&editors=0010). Label is typed to string for localization and accessibility purposes. The label will eventually end up in the a11y title.
