### ISSUE TITLE
OSRB - Need to find an alternative to mozilla cookies.js for grommet 1.x

### ISSUE THREAD

**Issue by cherih** [grommet/grommet#1799]
The src/js/utils/Cookies.js file is a custom version of Mozilla cookies.js, which has a GPL 3.0 license. 

GPL requires that all source within a project also be open sourced, which we don't want to do in some cases of HPE proprietary software.

**Comment by ericsoderberghp** [comment]
This was fixed in https://github.com/grommet/grommet/commit/c5337762c1b891ad58caa57b4f3b352363c0eb57
