### ISSUE TITLE
can use with apollo client 2.0  

### ISSUE THREAD

**Issue by hari-mohan-choudhary** [grommet/grommet#1801]

**Comment by L0ZZI** [comment]
Thanks ror checking us out. We don't have a short term goal to support Apollo, https://www.apollographql.com/client

We welcome contributions from the community, please feel free to give a little more detail or provide a PR. We'll investigate further as well.

**Comment by atanasster** [comment]
I am using 2 with Apollo and grapql, there is nothing on the grommet side to be added, if you want to close this one

**Comment by L0ZZI** [comment]
Thanks @atanasster! Yup.
