### ISSUE TITLE
Toast shows an error in console

### ISSUE THREAD

**Issue by fauricioRojas** [grommet/grommet#1811]
### Expected Behavior
Toast should not show console errors related with duration property.

### Actual Behavior
Toast shows an error in console related with duration.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/14350470/35357840-5a12a174-011a-11e8-9fa8-d2bf55ceac53.png)

### Steps to Reproduce
 1. Access to this [codepen](https://codepen.io/alansouzati/pen/qrKZKa?editors=1010).
 2. See browser console.

### Your Environment

* Grommet version: 1.10.0
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): N/A

**Comment by L0ZZI** [comment]
Have you tried updating grommet to newer version to the see if this issue persists? Seeing as we've made many enhancements in recent releases this may have been fixed.  We've moved our efforts to the V2 release, http://v2.grommet.io/ . 

Contributions are welcomed and we've tagged this with needs help for community to take a stab at it. Keep us posted!
