### ISSUE TITLE
v2 broken with styled-components v3

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#1818]
### Expected Behavior
Version 2 should work with styled-components v3

### Actual Behavior
My app does not compile with Grommet version 2 and styled-components v3. This error is thrown:
`Module build failed: Error: Cannot find module 'styled-components/lib/models/ThemeProvider'`

### URL, screen shot, or Codepen exhibiting the issue
One of the listed breaking changes for styled-components version 3:

> Thanks to @Andarist we're now shipping flat bundles for each of our entries only. This means that the entire lib/ folder won’t be inside our npm package. While this might break a couple of third party libraries, it stands to reason that our internals should not have been exposed in this way before.

More information here: https://www.styled-components.com/releases

### Steps to Reproduce
 1. npm i grommet@next styled-components@3.0.2
 2. try to run app
 3. 

### Your Environment

* Grommet version: grommet@next
* Browser Name and version:
* Operating System and version (desktop or mobile): Mac OS 10.13.2

**Comment by Andarist** [comment]
Hi!
Do you import `styled-components` on your own? (I'm not familiar with this project)

**Comment by alansouzati** [comment]
Thanks for bringing this to your attention @srallen. I will take a look on this soon.

**Comment by ericsoderberghp** [comment]
This is no longer reproducible.

**Comment by limaAniceto** [comment]
Hello Eric,
I've managed to reproduce it from v2.1.1 to v3.4.9.

It's still happening

**Comment by ericsoderberghp** [comment]
From limaAniceto:

Hello Eric,
I've managed to reproduce it from v2.1.1 to v3.4.9.

It's still happening

**Comment by alansouzati** [comment]
we are on v4 now right ? is this still an  issue?

**Comment by srallen** [comment]
It hasn't been an issue for me with the latest releases.
