### ISSUE TITLE
Tab component should have an optional parameter of "full"

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#1822]
Like many other components, the tab component should have the option of using the entire width of the parent element. Otherwise as you navigate between tabs the width of the panel grows and shrinks.

### Expected Behavior
Tab's should have the option of using full available width
### Actual Behavior
same
### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by L0ZZI** [comment]
Layout should be driven by Box, http://v2.grommet.io/box. Have you tried wrapping the tab within a Box and use `responsive` property?
