### ISSUE TITLE
Fixed Header with Menu overlay bug

### ISSUE THREAD

**Issue by jozsi** [grommet/grommet#1823]
The first row of the menu doesn't appear on a fixed header.

### Expected Behavior
The menu dropdown should be visible.

### Actual Behavior
The menu dropdown has a lower z-index (20) than the header itself (50).

### URL, screen shot, or Codepen exhibiting the issue
http://grommet.io/docs/header/examples?fixed=true&i-title=true&i-search=false&i-menu=true&c-background=light
<img width="1091" alt="screen shot 2018-01-29 at 19 24 45" src="https://user-images.githubusercontent.com/840815/35524404-32624f6c-052a-11e8-8ad5-8270894519d6.png">

### Steps to Reproduce
 1. Click the menu icon on the right

### Your Environment
* Grommet version: 1.10.0

**Comment by L0ZZI** [comment]
Have you tried using a more recent version of Grommet? As we move to version 2 we'll be putting our efforts toward the newer releases. We welcome contributions and we'll put push this out to the community see anyone on the older releases has a patch.

**Comment by jozsi** [comment]
Dear @L0ZZI - I am using the most recent v1 version.
I know the cause ([this commit](https://github.com/grommet/grommet/commit/c7b3db501b5ba92742e043862b67b7812d731076)), and I guess the workaround could be to provide a higher `z-index` for `.grommetux-drop` classes inside the Header component. I've no SASS knowledge (CSS in JS for the win!), but will try to create a Pull Request for it, unless someone else beats me to it.

**Comment by L0ZZI** [comment]
Right on, thanks for the update. I'll throw this in slack and see if there are any takers.
