### ISSUE TITLE
Drop placement broken if Select value is JSX

### ISSUE THREAD

**Issue by cubeghost** [grommet/grommet#1824]
https://github.com/grommet/grommet/blob/4faf4898e2d1c7dcfb2c5760bfe23775e9964e81/src/js/components/Select.js#L95-L101

https://github.com/grommet/grommet/blob/4faf4898e2d1c7dcfb2c5760bfe23775e9964e81/src/js/components/Select.js#L445-L455

In Grommet 1.10.0, because `React.isValidElement` is used to determine whether to display a hidden input or text input, the `control` passed to Drop is a hidden input and therefore `getBoundingClientRect()` returns `{x: 0, y: 0, width: 0, height: 0, top: 0, bottom: 0}`. This causes the dropdown to be placed at the top left corner of the screen.

An example:
```js
const options = [
  {
    value: 'a_credit_card_id',
    label: <div>
      <img src="visa.svg" alt="Visa" />
      <span>last 4 digits</span>
      <span>a persons name</span>
    </div>
  }
];

return (
  <GrommetFormField>
    <GrommetSelect
      name="creditCard"
      onChange={onChangeCreditCard}
      value={options[0]}
      options={options}
    />
  </GrommetFormField>
);
```

**Comment by drewlustro** [comment]
## +1

I am affected by this breaking change.

**Comment by atanasster** [comment]
#1816 has been merged and should fix the issue. Can you please confirm

**Comment by cubeghost** [comment]
Thanks, that fixes it. My bad for not checking hard enough to see if someone had already reported this issue 🙌 

Any estimate on how soon a release with the fix will go out?
