### ISSUE TITLE
Select onSearch not working with redux-form

### ISSUE THREAD

**Issue by levantuong435** [grommet/grommet#1826]
Hi author!
Current I using select with redux-form, but when I customize onSearch then not working.
Here my code:
export const _renderSelectField = (field) => {
    const {meta : {touched,error}} = field;
    const className = `${touched && error ? 'is-invalid' : ''}`;

    return (
        <FormField label={field.label} error={touched ? error : ''}>
            <Select placeHolder={field.placeholder} 
                options={field.options}
                multiple={false}
                name={field.input.name}
                value={field.input.value}
                onSearch={(event) => {
                    const results =  _.filter(field.options,(option) =>{
                        return _.includes(option.label,event.target.value);
                    });
                    return results;
                }}
                onChange={(e)=>field.input.onChange(e.option)}
            />
        </FormField>
    );
}

thansk

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by L0ZZI** [comment]
Could you please provide the version of grommet and and details about the environment?

**Comment by L0ZZI** [comment]
No reply. Closing.
