### ISSUE TITLE
v2 RoutedAnchor - route is active

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1862]
in v1, Anchor would check if its route is the active one, making it possible to use Anchors in for example side menu bars, whore it would be visually clear that this is the current route.

In v2, not sure how we can make side menus with RoutedAnchor

**Comment by ericsoderberghp** [comment]
For use in situations like a menu, the v2 approach is to consider this as visually more like a Button. The underlying element will use an `<a>` tag but it will visually appear more button-ish and be rendered with RoutedButton. Currently, Button does take an `active` property but RoutedButton doesn't set this automatically.

**Comment by atanasster** [comment]
thanks, understood

**Comment by alansouzati** [comment]
let's keep this open so that we can work on adding support for `active` in both RoutedAnchor and RoutedButton

**Comment by ericsoderberghp** [comment]
@karatechops and I discussed this and agreed that this needs more attention.

**Comment by karatechops** [comment]
Any status update on `active` support?

**Comment by shai32** [comment]
Any status update on active support?

**Comment by ericsoderberghp** [comment]
It appears that RoutedButton already supports `active`. You can see it in action here: https://codesandbox.io/s/lp3y7rj1k9, in the MenuButton.js component.

**Comment by ShimiSun** [comment]
@ericsoderberghp can we close this issue? or is there any other action item from our end?

**Comment by ShimiSun** [comment]
An example to use the `active` prop from our patterns https://codesandbox.io/s/216vvpmlqj
