### ISSUE TITLE
grommet-icons - context

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1866]
`Warning: Failed context type: Icon: context type `undefined` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.`
```
    in Icon (created by Bitcoin)
    in Bitcoin
    in div (created by StyledBox)
```

**Comment by ericsoderberghp** [comment]
This should be an issue on https://github.com/grommet/grommet-icons.

**Comment by atanasster** [comment]
thanks, I will open it there
