### ISSUE TITLE
v2 - Filter

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1871]
Filter componnet in v1 was very useful for enterprise type applications. Since grommet is marketed as an enterprise type library, please re-introduce the Filter

**Comment by ericsoderberghp** [comment]
Is this referring to http://grommet.io/docs/filter-control.
If so, you can achieve this via:
```
<Button onClick={onClick}>
  <Box align='center'>
    <Text>{unfilteredTotal}</Text>
    <FilterIcon />
    <Text>{total}</Text>
  </Box>
</Button>
```

**Comment by atanasster** [comment]
Yes, thats the one i mean. I can make it like that, just meant its a great component to have built-in to amplify the enterprise image. Just my opinion
