### ISSUE TITLE
v2 - NumberInput

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1875]
A NumberInput is missing in v2

Screenshot from v1 NumberInput:
![screenshot666](https://user-images.githubusercontent.com/6075606/36221010-ae5ef306-118a-11e8-94ee-064a2f0986e6.jpg)

v2 TextInput with type='number
![screenshot667](https://user-images.githubusercontent.com/6075606/36221030-c7160254-118a-11e8-943b-47aa62a3ccd3.jpg)

**Comment by atanasster** [comment]
Closing, added a component myself to grommet-controls, probably ficus on more pressing issues

**Comment by SinHouse** [comment]
[grommet-controls](https://github.com/atanasster/grommet-controls)  @atanasster npm package
