### ISSUE TITLE
v2 Clock pulls in (huge) date-time-format-timezone dependency

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1892]
Including the `<Clock />` component pulls in a large (over 2MB size) library date-time-format-timezone

![screenshot678](https://user-images.githubusercontent.com/6075606/36364011-5f2cd770-150f-11e8-9926-67e353873eb3.jpg)

**Comment by alansouzati** [comment]
good point. I'm planning to remove that and let the callers add it if they need for a specific browser. `date-time-format-timezone` is a polyfill that will only be used if the browser does not support it.

Check here: https://www.npmjs.com/package/date-time-format-timezone

It is expected to have 2MB without gzip for all locales, so I guess it makes sense to let the caller decide the ones to include.

If you are curious about the browser compatibility check out this MDN page:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

I will also investigate if there is any better solution to this.

**Comment by atanasster** [comment]
Fixed with #1909
