### ISSUE TITLE
Meter - Arc labels and threshold reversed in svg

### ISSUE THREAD

**Issue by samogami** [grommet/grommet#190]
Looking at Grommet [Meter Doc](http://grommet.io/docs/hpe/develop/meter)  The meter that is under heading "Arc, Min, Max, Units, Thresholds, Vertical" The top and bottom labels are reversed.
[Screen Capture of meter component with arrows pointing to reversed labels](https://www.dropbox.com/s/b2cghpbq8p4syzx/2015-09-18_11-35-08-grommet-meter.png?dl=0)

**Comment by jwijay** [comment]
The latest [Grommet Meter](http://www.grommet.io/docs/hpe/develop/meter) example (Arc, Min, Max, Units, Thresholds, Vertical) has the correct labels applied to the min and max values.

<img width="798" alt="screen shot 2016-07-11 at 8 55 55 pm" src="https://cloud.githubusercontent.com/assets/10161095/16757876/3b72d9c6-47aa-11e6-8e37-bccbdb918e31.png">
