### ISSUE TITLE
v2 Chart - onHover, onClick

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1902]
Thanks for adding those events

Unfortunately, what I had in mind was to have similar to WorldMap where we can receive the object that is being hovered/clicked. 

As a use case - user hovers over the chart and we display the data that is being hovered / clicked on. 

It would also be useful for bar charts, so user can drill down on the data.

**Comment by ericsoderberghp** [comment]
To match WorldMap, `onClick` would pass the value object while `onHover` would still pass true| false. Does that work?

**Comment by atanasster** [comment]
Actually WorldMap onHover / onClick are part of the continents (it would be like having those for each point, which would be amazing if possible for Chart), so you can identify the item being hovered and display its information :
```
  onHover: hover => this.onContinentHover(hover, c.name),
```

**Comment by ericsoderberghp** [comment]
I think we should keep this but it isn't strictly necessary for v2.0.0
