### ISSUE TITLE
v2 Layer and flex

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1904]
Apparently absolute position doesn't play well with flex

Please consider the following examples:
1. Correct - square with size medium:
```
<Box direction='row' basis='medium'>
  <Box background='brand' basis='medium' />
</Box>
```
2. Incorrect
```
<Layer>
  <Box direction='row' basis='medium'>
    <Box background='brand' basis='medium' />
  </Box>
</Layer>
```

3. Incorrect (we would like the square box on the right side)
```
<Layer position='right'>
  <Box direction='row' basis='medium'>
    <Box background='brand' basis='medium' />
  </Box>
</Layer>
```

**Comment by ericsoderberghp** [comment]
@karatechops and I discussed. Would like to look into to verify if this is still an issue and either document how to overcome it or make a change to avoid it.

**Comment by ericsoderberghp** [comment]
For future reference, this can be achieved now with:
```
<Layer position='right'>
  <Box background='brand' width='medium' height='medium'>Hi</Box>
</Layer>
