### ISSUE TITLE
v2 colorIsDark slightly off

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1917]
Material UI brand color `#00BCD4` is treated as a 'light' color with black text:
![screenshot680](https://user-images.githubusercontent.com/6075606/36725595-c6f643c0-1b84-11e8-9684-40670d0f7167.jpg)

The text is rendered white on Material UI:
![screenshot681](https://user-images.githubusercontent.com/6075606/36725648-f3518934-1b84-11e8-9372-7e5d13964d58.jpg)

possibly increase the threshold to ~130?

**Comment by ericsoderberghp** [comment]
That color combination doesn't pass accessibility test:
http://leaverou.github.io/contrast-ratio/#%23FFFFFF-on-%2300BCD4

**Comment by atanasster** [comment]
I guess we can close it, but it was a real-life example.
At the end I had to adjust the default `#00BCD4` to `#00ABD4` to match the Material UI theme

**Comment by atanasster** [comment]
Another option - if possible make the threshold an option of the theme, so users can decide for each theme

**Comment by karatechops** [comment]
Discussing this with @L0ZZI, we can introduce a contrast level to the theme object.
