### ISSUE TITLE
v2 Anchor style on dark background

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1919]
When the anchor is displayed on a dark background, it is undistinguishable from regular text.
```
 color: ${props =>
    (props.grommet && props.grommet.dark ? props.theme.global.colors.darkBackground.text
      : props.theme.anchor.color)};
```
Possibly add a theme option for anchor on dark background.

**Comment by ericsoderberghp** [comment]
Can you provide a CodePen illustrating this issue? I am not able to reproduce it with:
```
<Box background='dark-2'><Anchor label='label' /></Box>

**Comment by atanasster** [comment]
https://codesandbox.io/s/94qvn9r31o :
```
<Box gap="large">
      <Box background="brand" direction="row" gap="large">
        <Text>Text</Text>
        <Anchor label="Follow" />
      </Box>
      <Box direction="row" gap="large">
        <Text>Text</Text>
        <Anchor label="Follow" />
      </Box>
    </Box>
```

**Comment by ericsoderberghp** [comment]
Ah, I missed the "regular text" part of the description. Thanks for the sandbox.

**Comment by L0ZZI** [comment]
Nice catch! I don't think color `brand` as a background fill constitutes a dark theme. I do think `black` or something in the darker end of the color spectrum would . That said, the easiest but least elegant suggestion would be to, underline `anchor` text at all times in white. An approach more aligned with the light theme would be to  use `brand` color along with `text-weight` to call out interaction—It might not work in all context but would be consistent.

There is no simple silver bullet here as each of these elements can all be customized through theme and user choice. I would suggest adjusting your definition of "dark background" and close.

**Comment by atanasster** [comment]
With the internal calculation, for the default vanilla.js theme, 'brand' is a dark color, I don't think changing the definition of dark has a role here.
If changes are to be made, maybe add a light and dark color to Anchor (and other components) to be selected based on the background. Possibly a global brandContrast color that the theme components can pick from

**Comment by atanasster** [comment]
With the internal calculation, for the default vanilla.js theme, 'brand' is considered a dark color, I don't think changing the definition of dark has a role here.
If changes are to be made, possibly add a light and dark color to Anchor (and other components) to be selected based on the background. Possibly a global brand-reverse color

**Comment by atanasster** [comment]
Just to make sure we are on the same page, brand or black makes no difference to the issue being present:
```
<Box background="black" direction="row" gap="large">
  <Text>Text</Text>
  <Anchor label="Follow" />
</Box>
```
