### ISSUE TITLE
v2 - getNewContainer breaks on SSR

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1925]
` const container = document.createElement('div');`

document is not defined
All code that relies on getNewContainer() without checking the return value probably breaks as well

**Comment by ericsoderberghp** [comment]
Can you describe a scenario where server side rendering should include an open Layer or Drop? We have been assuming those two components would not be rendered server side.

**Comment by atanasster** [comment]
My specific use case was to set a 'loading...' layer as initial prop and then the data is loaded/error at the client side (API had to be called client side) and the layer is closed.
Additionally I had this error when we had some default of <Select /> being open. 
Without having those use cases myself, I think other would include blocked content, data entry forms where the form is 'ready to type' with a list of selections already opened.

**Comment by karatechops** [comment]
Removing stale, this should be fixed before V2 launch.
