### ISSUE TITLE
Datepicker does not respect moment's locale startofweek setting… calender shows wrong dates

### ISSUE THREAD

**Issue by florianbepunkt** [grommet/grommet#1934]
Datepicker component does not respect moment locales start of week setting. Depending on the locale the start day of the week is sunday or monday (for example, in Germany it is monday). When you set the moment locale to 'de'. monday is the first day that is shown but the days do no render properly (see attached screenhots)

### Expected Behavior
Start of week setting should be respected.

### Actual Behavior
Monday is the first day in the datepicker header, but the dates are wrong. See attached screenshot. Today is Monday, 5th of March. The datepicker shows it's Tuesday.

<img width="526" alt="bildschirmfoto 2018-03-05 um 15 24 43" src="https://user-images.githubusercontent.com/8314202/36979980-5afcc748-2089-11e8-85b3-ca9555885651.png">

**Comment by froston** [comment]
Could you find a solution to this issue?

**Comment by ShimiSun** [comment]
Our next release will include an actual DateInput component of grommet v2. It could be tested on the [stable branch ](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F)if you want a sneak pick.

**Comment by froston** [comment]
Ok thanks! Yeah I can't afford the migration right now so I just had to find a solution to this with grommet v1.
The issue is happening because moment library does not have available locales. It is neccesary first import the locale and then grommet like this:
```javascript
import 'moment/locale/cs'
import { App } from 'grommet'
```
