### ISSUE TITLE
v2 Clock - SSR

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1949]
Under Next.js, Clock started giving a warning:
`Prop `style` did not match. Server: "transform:rotate(0deg);transform-origin:48px 48px" Client: "transform:rotate(6deg);transform-origin:48px 48px"`
Happened after the last Clock updates

**Comment by ericsoderberghp** [comment]
Are you passing the same `time` in both cases?

**Comment by atanasster** [comment]
This warning is from the samples on grommet-site, ported to nextjs.
If it can give a clue, Calendar also gives an error SSR when the minute changes between the time its rendered server side and client side.

I can investigate further if needed

**Comment by atanasster** [comment]
Cant reproduce with latest update. Possibly it was a timing issue like with Calendar, will close for now and re-open when I have exact reproducing steps
