### ISSUE TITLE
Consider StackBlitz instead of CodeSandbox for v2 examples

### ISSUE THREAD

**Issue by schettino** [grommet/grommet#1950]
[StackBlitz](https://stackblitz.com) provides a faster loading time, it is built on top of VSCode and thus many of us would be familiar using it (code format, shortcuts), but even if you not use vscode, the experience using a online code editor could be better. It already supports importing from Github, but requires the project to be bootstrapped with CRA, which I think it's the case with grommet-sandbox. So, the changes to get it working may be just a few.

Here it is a demo I made from the ground with only the Calendar component. 
https://stackblitz.com/edit/grommet-v2

If you guys decide towards using StackBlitz, I can contribute! I may missing some point about the reason to use CodeSandbox, but this is why I have opened this issue

**Comment by ericsoderberghp** [comment]
Thanks for the suggestions. I do like the improved load time. One possibility would be to enhance `react-desc` to allow `availableAt` to be an array and add StackBlitz links alongside the CodeSandbox ones. That would allow both to be shown in grommet-site. If this seems reasonable, we'd welcome a pull request.

**Comment by CompuIves** [comment]
Hey! Just wanted to quickly note that StackBlitz is not more built on top of VSCode than CodeSandbox is. We both use the [Monaco](https://github.com/Microsoft/monaco-editor) editor, which is the core editor of VSCode extracted to the browser, but that's as far as VSCode implementation goes.

The only editor that, I believe, uses VSCode directly in the browser is [SourceGraph](https://about.sourcegraph.com/). But I'm not sure of that too 😅.

**Comment by EricSimons** [comment]
Hey all- co-creator of StackBlitz here! Just seeing this thread now. That sounds like a great idea @ericsoderberghp- @schettino would you be willing to take lead on this integration? Super excited to see this happen!

PS @CompuIves- it sounds like you're a little confused about the level of integration StackBlitz has with VS Code. Feel free to ping me and/or our core team in the future w/ any tech questions (ideally before posting comments about us :)

**Comment by alansouzati** [comment]
hey @schettino let me know if you want help on that. it would be nice to have both codesandbox and stackblitz available on v2.grommet.io

**Comment by alansouzati** [comment]
@EricSimons do you know if StackBlitz supports github integration?

[This](https://github.com/grommet/grommet-sandbox) is the project we created to integrate with code sandbox. Any updates in this project, the codesandbox is also updated.

By a quick look in your site I could not find references for github integration

**Comment by EricSimons** [comment]
@alansouzati yup, we do! Here's the section in the docs about it: https://stackblitz.com/docs#import-from-github

Lmk if you have any q's/run into any troubles!

**Comment by EricSimons** [comment]
Ah gotchya, yeah this should be a super simple fix from our end. Will circle back tmrw morn once it’s online 👍

**Comment by alansouzati** [comment]
I still would like to keep this open. @EricSimons do you have any updates on this?
