### ISSUE TITLE
v2 Themes - enhance colors for text and icons

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1955]
A proposal to extend the theme colors, to include a few more variations of text and icons, so we can distinguish between control states (eg Buttons, Anchors etc):
```
darkText: {
  'primary': 'rgba(0, 0, 0, 0.87)', 'secondary': 'rgba(0, 0, 0, 0.54)', 'disabled': 'rgba(0, 0, 0, 0.38)',
},
lightText: {
  'primary': 'rgba(255, 255, 255, 1)', 'secondary': 'rgba(255, 255, 255, 0.7)', 'disabled': 'rgba(255, 255, 255, 0.5)'
},
darkIcon: { 'active': 'rgba(0, 0, 0, 0.54)', 'inactive': 'rgba(0, 0, 0, 0.38)' },
lightIcon: { 'active': 'rgba(255, 255, 255, 1)', 'inactive': 'rgba(255, 255, 255, 0.5)' },
```

**Comment by ericsoderberghp** [comment]
I like this idea. @L0ZZI and I will review as he shepherds the visual design details.

**Comment by L0ZZI** [comment]
I don't mind it either. I think it's an opportunity to add personality. I would just suggest that when looking at the text, we treat the naming similar to your controls, like `inactive`, `active` to be a little more consistent.

I don't understand the third state you have in there `secondary`. Please elaborate if I missing something.

**Comment by atanasster** [comment]
secondary is an additional state (to primary) that some themes have (ie material UI) for anchors and buttons.
