### ISSUE TITLE
v2 - 'grommet' theme

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1969]
Please keep the 'grommet' theme as compatible as possible with grommet v1 - sizes, spacing borders, if the goal is to ever convert v1 users to grommet-next. 
You can have the 'enhanced' new designs like rounded buttons, padding as a new theme eg 'grommet-next'.
Users of grommet v1 have spent weeks fine tuning their screens pixel-by-pixel and it will be a nightmare to convert them if the grommet theme is incompatible.

**Comment by Fig-R** [comment]
yes, he is absolutely right

**Comment by alansouzati** [comment]
Yeah one way or the other we should provide this. My inclination is to start with the v2 template as is and offer a grommet v1 theme. @ericsoderberghp thoughts?
