### ISSUE TITLE
dark theme - select on brand color

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1982]
The arrow of `<Select />` is not visible with the dark theme on a `brand` background:
The icons are also not very visible with grey over yellow

![screenshot687](https://user-images.githubusercontent.com/6075606/37909589-fbb4ded8-3113-11e8-8ffb-5b1eec7015d5.jpg)

example: https://grommet-nextjs.herokuapp.com/?theme=dark

**Comment by ericsoderberghp** [comment]
Agreed that we should fix this. Not strictly required for v2.0.0

**Comment by alansouzati** [comment]
this was actually fixed with my PR :)

**Comment by atanasster** [comment]
It was fixed by making the select background white, its ok although i preferred it when select was using by default the current background

**Comment by alansouzati** [comment]
i understand, having a transparent background is risky. since you may not be using Grommet to set the background colors. so, we would never be able to tell when something is dark or not. hopefully this makes sense.

**Comment by atanasster** [comment]
It makes a bit sense :) but check how Menu is styled 
https://grommet-nextjs.herokuapp.com/preview

**Comment by atanasster** [comment]
Also how select stands out and is different from all other controls :
https://grommet-nextjs.herokuapp.com/preview?theme=black

Imo, this is an issue, but at least the select arrow is visible, so less of an issue than previously

**Comment by ericsoderberghp** [comment]
I don't think Select should always set a background color. It should rely on whatever the theme puts for the overall background via Grommet. The theme creator can set the appropriate control color (when that PR merges ;) and allow the Select to have a transparent background.

**Comment by alansouzati** [comment]
agreed on the fact that Menu should have the same Select capabilities when it comes to changing the background color via theme.

also I agree that you can configure the theme to have a transparent background for the select. I think it is important to have that flexibility in the theme itself since it will vary from app to app.
