### ISSUE TITLE
Theme now forcing 'Zilla Slab' font for Heading

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1983]
The default grommet theme is recently forcing the 'Zilla Slab' font, if no font is provided for Heading in the theme.
If possible, Heading should use the current theme font if a font is not provided for Heading instead of falling back to the grommet font for Heading

**Comment by ericsoderberghp** [comment]
Agreed with the desire. Our current theme merging isn't aware of nuances like this. For now, you can set:
```
  heading: {
    font: false,
  },
```
in any custom theme to turn off the vanilla heading font.

**Comment by atanasster** [comment]
Thanks, yes i saw that and updated my themes
