### ISSUE TITLE
deepMerge slowing performance

### ISSUE THREAD

**Issue by SahidHernandez** [grommet/grommet#1985]
### Expected Behavior
Performance should be smooth when re-rendering child components

### Actual Behavior
When children components are re-rendering the performance of the app tends to be slow
UX is getting impacted due several invocations of deepMerge that flows into styled-components too

### URL, screen shot, or Codepen exhibiting the issue

![screen shot 2018-03-26 at 2 24 49 pm](https://user-images.githubusercontent.com/5847209/37934357-c447b0bc-3102-11e8-9ee7-f3a7f3e04d6a.png)

### Steps to Reproduce
 1. Select component with children components to select
 2. Re-render some of the children component

### Your Environment
* Grommet version:  2.0.0-alpha.13
* Browser Name and version: Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System and version: MacOS 10.13.3

**Comment by ericsoderberghp** [comment]
Can you provide a little more context for this? Particularly, how are you initializing your theme? Are you using `<Grommet>`?

**Comment by pepoospina** [comment]
This heavily affecting performance on our app.

We use theme just as it is described in the tutorial as shown here
https://github.com/Common-SenseMakers/sensemakers/blob/main/app/webapp/src/ui-components/ThemedApp.tsx

We tried memoizing the theme, but it does not has an effect (as expected).

This is the Performance track (performance it is 6x degraded to make it easier to debug)
![image](https://github.com/user-attachments/assets/0226fa50-9e39-4503-8417-a731725236a6)

**Comment by pepoospina** [comment]
This image includes the   expansion of the anonynomus function above
![image](https://github.com/user-attachments/assets/bec9d155-60ef-4b49-b279-e77309fb90e7)

**Comment by pepoospina** [comment]
This is fixed on latest versions now
