### ISSUE TITLE
dark theme shadow(elevation) not visible

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1988]
![screenshot691](https://user-images.githubusercontent.com/6075606/37940400-1677960e-3171-11e8-87d6-24c30b009d3f.jpg)

playground here: https://grommet-nextjs.herokuapp.com/preview?theme=dark

**Comment by atanasster** [comment]
Its slightly more visible, you can re-open if desired:
dark theme:
![screenshot693](https://user-images.githubusercontent.com/6075606/37993088-32c9de70-3216-11e8-9f0b-1faaa559f130.jpg)
black theme:
![screenshot692](https://user-images.githubusercontent.com/6075606/37993102-3b8eec8a-3216-11e8-840a-d26f6ce985d6.jpg)

**Comment by acheronfail** [comment]
Is there a way we can change the box-shadow color?
A white shadow on a dark background sometimes isn't the best look.

**Comment by acheronfail** [comment]
Nevermind, I found that you can do this by setting new values for the `elevation` property in the theme object:

```js
const customTheme = {
  global: {
    elevation: {
      dark: {
        none: 'none',
		// You can override the values for box-shadow here.
        xsmall: '0px 2px 2px rgba(255, 255, 255, 0.40)',
        small: '0px 4px 4px rgba(255, 255, 255, 0.40)',
        medium: '0px 6px 8px rgba(255, 255, 255, 0.40)',
        large: '0px 8px 16px rgba(255, 255, 255, 0.40)',
        xlarge: '0px 12px 24px rgba(255, 255, 255, 0.40)',
      },
    },
  }
};
```

**Comment by ShimiSun** [comment]
@acheronfail glad you figured it out :) join our slack channel for more prompt answers.
