### ISSUE TITLE
Theme context update broken with #1986

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#1990]
With #1986, when changing a theme the update is broken. I also tried adding withTheme on pages that were previously refreshing the theme without the need for a withTheme but did not work as well.

example: 
https://grommet-nextjs.herokuapp.com , then change the theme to dark in the `<Select />` - only the `<Grommet />` style is updated (background color) - Boxes with custom theme settings (ie color='brand'  are not updated until a full page refresh

**Comment by ericsoderberghp** [comment]
One question, are you changing the theme at the outermost `<Grommet theme={} />` level or on individual components?

We were having performance issues with the theme being rebuilt too much. The current implementation works for individual components if you change the theme to `undefined` and then change it to the newly desired one. Admittedly, this is not ideal. But, we thought the performance improvement outweighed the ability to update the `theme` property on the fly.

**Comment by atanasster** [comment]
I have two cases
1. https://grommet-nextjs.herokuapp.com - outermost <Grommet /> (does not work anymore) 
2. https://grommet-nextjs.herokuapp.com/theme - inner <Grommet /> (works when you change props of the theme)

Really not sure it can be acceptable not working changing the theme at the global <Grommet/> as that would be the most common use case

**Comment by alansouzati** [comment]
Let me take a look on this.

**Comment by ericsoderberghp** [comment]
Changing the theme at the outer `Grommet` level should be fixed in the latest NEXT-stable.

For the inner level, @alansouzati and I are having a vigorous debate about some of the details.

**Comment by rameshsunkara** [comment]
@ericsoderberghp @alansouzati 

Referring [Why Grommet2](https://github.com/grommet/grommet/wiki/Why-Grommet-2.0%3F)

``` javascript
const hpeTheme = {
    ....
    extend: 'letter-spacing: 0.04167em;',
  },
};
```

From Why Grommet2:
> *Notice the extend property inside button object that allows you to augment the button with additional styling for your theme.*

To facilitate customizations, any plans to expose `extend` as a prop on the components such a way that it will be deep merged with the base ThemeObject?

If not, is wrapping component in ThemeContext.Consumer and deep merging in my code an acceptable solution?
Looking at some issues on Github, I am concerned if this approach will trigger unnecessary re-renders.
