### ISSUE TITLE
Feature request: make components available with Bit

### ISSUE THREAD

**Issue by jonisar** [grommet/grommet#1999]
Hi Guys,

First thing's first - great work. Loved what u guys are doing!

Would it be possible to make your components available with Bit?
https://github.com/teambit/bit

Examples:
https://github.com/GSS-FED/vital-ui-kit  -> https://bitsrc.io/gssfed/vital-ui-kit-react (check out "card")
https://github.com/teambit/movie-app -> https://bitsrc.io/bit/movie-app (check out "hero")

It will:

1. Enable users  to install each component with NPM / Yarn
2. Enable users to develop these components from any project
3. Combine a design system with a component management platform for better component UI consistency and discoverability for anyone using these components

What do you think?
Thanks!

**Comment by alansouzati** [comment]
I'm unfamiliar with Bit. but I would love to explore it. I'm not sure how soon though. Most of my free time is to try to get grommet v2 out the door.

**Comment by Zeukkari** [comment]
bump

**Comment by RyanCCollins** [comment]
We are actively exploring using bit for our own component sharing at HPE and will report on that after we do more exploration.

**Comment by ShimiSun** [comment]
@RyanCCollins can you share your inputs on exploring Bit?

**Comment by RyanCCollins** [comment]
Hey @ShimiSun Bit seems like a great option for component sharing.  That being said, decisions were made at the OneSphere program level to instead go with a lerna repo and share our components through a private registry on npm.  Matt Borland was looking into this.  Considering we have 100s of components, this is going to be a longer term project, but I expect that I will be focusing on it soon.

**Comment by ShimiSun** [comment]
I sent a question to Matt to get some more inputs.

**Comment by jonisar** [comment]
Hi all.

So, we've been working on an example for Grommet with Bit.
Components are visually organized in the collections, each can be played-with online in the example playground and individually installed. We prepared examples for:

Grommet V2:https://bitsrc.io/grommet/grommet
Grommet V1: https://bitsrc.io/grommet/grommet-v1
Grommet Icons: https://bitsrc.io/grommet/grommet-icons

While V1 and the icons are perfectly ready, we have some final issues with V2 (circular dependencies etc) which I think we'll solve next week.

I would love to hear what you guys think of these examples!
If you like it we can continue to automatically maintain it ( +maybe add it to the grommet docs so that people can find it directly from the library and not only from Bit's community and Google) or hand over ownership and help implementing it to the library's release mechanism (or both) as you like :)

So what do you guys think?

**Comment by jonisar** [comment]
The Grommet (v2) collections is ready and fully working.
What do you think?

https://bitsrc.io/grommet/grommet

**Comment by ShimiSun** [comment]
@jonisar thanks! this looks really nice, we appreciate your work and suggestion.
@MikeWalrath let's discuss it on our meeting, not sure if we want to expose all of the utils for example.

**Comment by jonisar** [comment]
Sounds great.
If you'd prefer, I can hide the utils :)

**Comment by ShimiSun** [comment]
@jonisar can you hide the v1 components? is this something we can control and how?

**Comment by ShimiSun** [comment]
Thanks! I go by shimi, same account as my github

**Comment by ShimiSun** [comment]
How does the dependency management handle upgrading only one specific component when a theme is used globally for all the components?

**Comment by jonisar** [comment]
You've been added as an admin to the org :)

As for your question- If you modify a theme that several components require, Bit prompts a message saying it will bump all dependent components' versions. The new dependent versions will include the updated theme. Does that make sense?

**Comment by ShimiSun** [comment]
I think this issue can be closed, thank you for your collaboration!
