### ISSUE TITLE
v2 Layer causing unexpected Scrollbars upon being closed

### ISSUE THREAD

**Issue by Kithio** [grommet/grommet#2001]
### Expected Behavior
Layer closes without modifying page size.

### Actual Behavior
Upon Closing a Layer Component, `body` is given `style="overflow: scroll"` causing two scrollbars to appear on page no matter what size you have, thus modifying visible page size

### URL, screen shot, or Codepen exhibiting the issue
Problem found in Grommet Codesandbox (Fork with dependencies added) Layer.js -- https://codesandbox.io/s/mzjpq7w6lp (Direct Link : https://mzjpq7w6lp.codesandbox.io/layer)

Screenshots : https://imgur.com/a/lxtQK (Size of window doesn't matter)

### Steps to Reproduce
1. Open Codesandbox
2. Click Layer in View
3. Click Confirmation
4. Click Yes / No

### Your Environment
* Grommet version: 2.0.0-beta.1
* Browser Name and version: Firefox Quantum 59.0.2 (64-bit) + Google Chrom 65.0.3325.181 (64-bit) + Microsoft Edge 41.16299.248.0
* Operating System and version (desktop or mobile): Desktop

**Comment by alansouzati** [comment]
thanks for reporting this and for the codesandbox link. I will take a look on this later today!
