### ISSUE TITLE
Select drop is not aligned to dropTarget when it's first opened

### ISSUE THREAD

**Issue by ChrisRose** [grommet/grommet#2002]
When adding a dropTarget to the Select Component, the drop will not be aligned unless an option is selected, and it's re-opened.

### Expected Behavior
The drop should always be aligned

### Actual Behavior
The drop is not aligned initially

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/ykqmqn8kmj

### Steps to Reproduce
 1. Open the select (notice that the drop is not aligned to the "Align to Me" Box)
 2. Select an option, then re-open the select
 3. The drop is now aligned.

### Your Environment
Grommet v2.0.0-beta.1 , Chrome, Desktop

**Comment by alansouzati** [comment]
I cannot seems to find your example in the codesandbox. can you expand how can we get to it ?

The other day, I was showing grommet to a company in brazil and I experienced something similar. I just want to make sure this bug is the same as the one I'm about to fix.

**Comment by ChrisRose** [comment]
I just saved the example, so you should be able to see it now.

**Comment by elbotho** [comment]
I did another codesandbox:
https://6v96wo76ow.codesandbox.io/dropbutton

The same bug occurs on the DropButton component.
@alansouzati did you find a fix?

**Comment by inyono** [comment]
This is usually the case if the `ref` isn't set yet on the first render, e.g.
```.tsx
const myRef = React.createRef(undefined)

function Foo() {
  return (
    <div>
      <DropButton dropTarget={myRef.current}
      <div ref={myRef}
    </div>
  )
}
```
**won't** work since `myRef` is going to be set after (!) the first rendering (and updating a `ref` does not trigger a rerendering). To fix this, you need to force a rerendering when the `ref` is defined, e.g. by inserting the `ref` into the state.
