### ISSUE TITLE
v2 Select - multiple selected is required

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2007]
CodeSandbox: https://94qvn9r31o.codesandbox.io/select

1. Open the Select options - at first are shown as selected "First" and "Third"
2. Click on "Second"
3. Instead of adding "Second" to the selected values, now only "Select" is selected

Happens because on drawing selected elements, SelectContainer uses either the 'selected' property or the array of value. However on selecting an item (selectOption), only the selected prop is used. 

code: 
```
export default class extends Component {
  state = { value: ["First", "Third"] };

  render() {
    const { value } = this.state;
    return (
        <Select
          value={value}
          multiple={true}
          onChange={event => this.setState({ value: event.value })}
          options={["First", "Second", "Third"]}
        />
    );
  }
}
```

**Comment by alansouzati** [comment]
agreed this is a bug.
