### ISSUE TITLE
v2 Icons theme extend

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2010]
When specifying a color, multiple fill and stroke properties are added to icons, also lightBackground is not accounted for: 
`<FormDown color='brand' />`

![screenshot696](https://user-images.githubusercontent.com/6075606/38784454-03fbbbb2-40e0-11e8-84a9-f09ac846452a.jpg)

in vanilla.js:
```
icon: {
    extend: css`
      ${props => props.color && props.color !== 'plain' && `
        fill: ${colorForName(props.color, props.theme)};
        stroke: ${colorForName(props.color, props.theme)};
      `}
      ${props => props.dark && `
        fill: ${props.theme.global.colors.darkBackground.text};
        stroke: ${props.theme.global.colors.darkBackground.text};
      `}
    `,
  },
```

**Comment by atanasster** [comment]
https://github.com/atanasster/grommet/blob/f5354924fa1a9e6c2801950c851abbd368ba533c/src/js/themes/dark.js - icon extend updated for dark theme to account for color selected as well as if the color selected is dark/light on dark/light background:

**Comment by atanasster** [comment]
Mr Stale Bot has been busy closing issues :)

**Comment by alansouzati** [comment]
I will double check this tomorrow
but i believe this is fixed.

**Comment by ericsoderberghp** [comment]
I cannot reproduce this with the current grommet and grommet-icons.
