### ISSUE TITLE
Focus outline doesn't appear around active Select

### ISSUE THREAD

**Issue by ChrisRose** [grommet/grommet#2013]
When multiple Select components exist on a page, clicking between them causes the focus outline to lag, i.e. it appears around the previously opened Select.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/k5wjm1pn0o (View the "Select" page under "Input")

### Steps to Reproduce
 1. Click the 1st Select component in a row
 2. Click the 2nd Select component in a row
 3. The focus outline remains on the 1st Select component

### Your Environment
Grommet v2.0.0-beta.1 , Chrome, Desktop

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/issues/2013
