### ISSUE TITLE
v2 Select search input very small in Safari

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2014]
In v1, this is solved by adding css `-webkit-appearance: textfield;` for `<input type='search' />`

```
<Select
  value={selected}
  onSearch={() => {}}
  onChange={event => this.setState({selected: event.value})}
  options={options}
/>
```

in safari, padding is ignored :
![screenshot698](https://user-images.githubusercontent.com/6075606/38843188-d0a0325c-41bb-11e8-8357-c686034af89d.jpg)

in chrome:
![screenshot699](https://user-images.githubusercontent.com/6075606/38843203-e689b1b0-41bb-11e8-87ca-5b9c727300e8.jpg)

**Comment by karatechops** [comment]
Resolved by #2061
