### ISSUE TITLE
[v2] Document ref usage

### ISSUE THREAD

**Issue by nfantone** [grommet/grommet#2015]
Since components on v2 are all generated by `styled-components`, the use of `ref` on elements [does not work as expected](https://github.com/styled-components/styled-components/issues/102). Instead, the `innerRef` prop should be used.

The following pattern is widely used to give focus to an input, but doesn't work on `grommet`, since the actual `ref` being returned belongs to the ad-hoc `StyledComponent`.

```js
import { TextInput } from 'grommet';
<TextInput ref={input => input.focus()} />

// Throws 'TypeError: `focus` is not a function.'
```

As explained in [this issue](https://github.com/styled-components/styled-components/issues/102), the `innerRef` prop should be used instead:

```js
import { TextInput } from 'grommet';
<TextInput innerRef={input => input.focus()} />

// Works!
```

### Your Environment
* Grommet version: `2.0.0-beta.1`
* Browser Name and version: Any
* Operating System and version (desktop or mobile): macOS High Sierra 10.13.4

**Comment by ericsoderberghp** [comment]
Thanks for reporting this. Instead of an `innerRef` property, we will use the `forwardRef` capability from React: https://reactjs.org/docs/forwarding-refs.html.

**Comment by ericsoderberghp** [comment]
`ref` should be working on Grommet components. We use `React.forwardRef` internally to make this work.
