### ISSUE TITLE
v2 Box - width (size)

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2016]
v2 is lacking a size prop like v1 Box, that allows to set the width to a fixed size. Basis is not working the same when direction='row' as the child will not make the parent grow, unless the parent is already wide enough
```
          <Box align='center'>
            <Box direction='row' background='accent-1' basis='medium'>
              <Box background='brand' basis='small' />
            </Box>
          </Box>
```

**Comment by ericsoderberghp** [comment]
I'm just wanting to understand something to start with, can you set `<Box basis="medium" flex={false} />` to prevent the box from being shrunk?

**Comment by atanasster** [comment]
It works in some cases, however if you have multiple child that you want to adjust them at the center of their parent, setting flex=false does not adjust the size of the parent. 

with flex true - width is adjusted, but child are not center aligned:
```
    <Box fill={true} align='center'>
      <Box direction='row' basis='small' gap='small'>
        <Box background='brand' basis='small' flex={false}>
          Text
        </Box>
        <Box background='brand' basis='small' flex={false}>
          Text
        </Box>
      </Box>
    </Box>
```
![screenshot707](https://user-images.githubusercontent.com/6075606/39602700-f5f7c156-4ef3-11e8-8641-a69b334f2bee.jpg)

with flex = false, child are centered but basis is not taken into account:
```
    <Box fill={true} align='center'>
      <Box direction='row' basis='small' gap='small'>
        <Box background='brand' basis='small'>
          Text
        </Box>
        <Box background='brand' basis='small'>
          Text
        </Box>
      </Box>
    </Box>
```
![screenshot708](https://user-images.githubusercontent.com/6075606/39602750-1c713fba-4ef4-11e8-9aa4-9d45d4293c45.jpg)

**Comment by ericsoderberghp** [comment]
Was this fixed with https://github.com/grommet/grommet/pull/2072?
