### ISSUE TITLE
v2 Stack - forced overflow hidden

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2018]
Stack is forcing style `overflow: 'hidden',` on secondary children, however it is often desired to have `overflow: 'scroll'` 
https://github.com/grommet/grommet/blob/28d53a2e3a31bf530af51dd260b6b09851dcf490/src/js/components/Stack/Stack.js#L38

Please allow for the user overflow style to be used if specified

**Comment by ericsoderberghp** [comment]
Could you provide a concrete example of this? I'd like to make sure any solution addresses the specific need.

**Comment by atanasster** [comment]
Example:  https://grommet-nextjs.herokuapp.com/add-ons/card
The Card on the top - when you hover, flips and the back content is some long text. Fixing this issue will allow the long content on the back to scroll (currently overflow hidden does not scroll).

The source code for the use-case : https://github.com/atanasster/grommet-controls/blob/master/src/js/components/Card/Card.js

**Comment by ericsoderberghp** [comment]
Can you wrap the card back in `<Box fill={true} overflow='auto' />`?
