### ISSUE TITLE
v2 Button plain

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2019]
The documentation for v2 Button mentions plain Buttons : https://v2.grommet.io/button when explaining focusIndicator and hoverIndicator.
However the plain property does not exist anymore (only way is to add label as children). 
Please update the docs or add the plain property back into Button (preferred)

**Comment by ericsoderberghp** [comment]
When would you use the `plain` property without providing children? Or, perhaps I am not understanding the use.

**Comment by alansouzati** [comment]
plain prop is back :) 

https://github.com/grommet/grommet/pull/2074
