### ISSUE TITLE
v2 Drop: Center align option

### ISSUE THREAD

**Issue by ChrisRose** [grommet/grommet#2025]
This is a feature request to add a center align option to the Drop.  Currently, the Drop allows only left or right alignment to the target element on the horizontal axis.

**Comment by ericsoderberghp** [comment]
Could you provide an example, perhaps a sketch or screenshot, illustrating an example of when you would use this? I would like to make sure anything we add addresses the specific need.

**Comment by ChrisRose** [comment]
I'm looking to do something like the following, where the question mark is the target, and the tooltip is centered relative to it:

![image](https://user-images.githubusercontent.com/957281/39653398-bb060546-4fa5-11e8-9622-3db90ab9dbac.png)

**Comment by alansouzati** [comment]
this still need to be open
