### ISSUE TITLE
Login rest call in Actions is hardcoded to request /rest on the webserver

### ISSUE THREAD

**Issue by mirsilstan** [grommet/grommet#203]
I created a webapp deployed in Tomcat out of a Grommet app built with gulp dist . Unfortunately the REST call in Actions.js /rest/login-sessions does not work, as it does not include the webapp root context. 
A context should be added to all the REST calls in Actions.js and IndexActions.js, as not every Grommet app will be located in the webserver's root directory.

**Comment by bryanjacquot** [comment]
This is not a Grommet issue any longer (there is no Actions.js) and the application is expected to control the interaction with the REST APIs.
