### ISSUE TITLE
v2 Diagram start/end points customization

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2038]
In Diagram, the points always start/end at the center of the nodes, however it can be desired to have custom start/end points and the edges. 
If possible add a function parameter that can calculate the start/end of the connectors
```
const calcDiagramEdgePoints = ({ fromRect, toRect, containerRect }) => {
  const fromPoint = [
    (fromRect.x - containerRect.x) + (fromRect.width / 2),
    (fromRect.y - containerRect.y) + (fromRect.height),
  ];
  const toPoint = [
    (toRect.x - containerRect.x) + (toRect.width / 2),
    (toRect.y - containerRect.y),
  ];
  return [fromPoint, toPoint];
};
```
picture of desired UI:
![screenshot706](https://user-images.githubusercontent.com/6075606/39602147-4640b048-4ef2-11e8-821f-f1b2fe03fdce.jpg)

picture of current UI:
![screenshot704](https://user-images.githubusercontent.com/6075606/39602155-4f1fcea6-4ef2-11e8-9790-56622b0a4756.jpg)

**Comment by alansouzati** [comment]
I believe this issue should remain open

**Comment by ericsoderberghp** [comment]
This is provided via the `anchor` property of connections. https://v2.grommet.io/diagram
