### ISSUE TITLE
npm run dev - is not opening chrome browser

### ISSUE THREAD

**Issue by steranka** [grommet/grommet#2043]
When I start my application using "npm run dev", my firefox (default) browser is opened.
I would like to start chrome instead of firefox.  **Is there a way to open Chrome (I'm running Windows 10)?**

On a Linux environment app (created with create-react-app), I was able to get this working by creating a file called .env as shown below:
FILE: $TOP/.env 
```
BROWSER="/bin/chromium-browser"
```
On Windows, I've tried:
FILE: $TOP/.env 
```
BROWSER="chrome"
```

as well as the following list (each tried separately), all opening firefox.

```
BROWSER="/PROGRA~2/Google/Chrome/Application/chrome.exe"
BROWSER="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
BROWSER="C:\\Program Files (x86)\\Google\Chrome\\Application\\chrome.exe"
```

I also tried:

```
node_modules\.bin\cross-env NODE_ENV=development BROWSER=chrome grommet pack
```

So I'm guessing this is not supported in grommet.  Is there supported way to do this?

### Expected Behavior
The expected behavior is to open the Chrome browser instead of the default (firefox) browser.

### Actual Behavior
The firefox browser is opened.

### URL, screen shot, or Codepen exhibiting the issue
No screenshot is needed.

### Steps to Reproduce
 1.  echo BROWSER=chrome > .env
 2.  npm run dev
 3.  Observe that your default browser (in my case firefox) opens to display your application.

### Your Environment
* Grommet version: 5.1.2
* Browser Name and version: Chrome Version 66.0.3359.139 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 SurfacePro Laptop/Tablet

**Comment by XOSplicer** [comment]
Hi, as you have stated you are using the `grommet pack` command from the `grommet-cli` application in the npm dev script. The source code for it can be found here 
https://github.com/grommet/grommet-cli/blob/master/src/commands/pack.js 

`grommet pack` uses a library called `opener` (https://github.com/domenic/opener/blob/master/opener.js) which will always open files with their associated default application set by your operating system. 
There is currently no way to choose the application that is run independently for grommet.
