### ISSUE TITLE
v2 Box - justifySelf does not exist

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2045]
v2 `<Box />` documentation writes about `justifySelf` - however it is nowhere implemented

**Comment by alansouzati** [comment]
I don't think we have a prop for this. Since we have `alignSelf` I feel we should add `justifySelf` @ericsoderberghp

**Comment by dallas** [comment]
Just as an update, it looks like `justify-self` now has roughly the same browser compatibility support as `align-self` has: 

`justify-self` support: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self#Browser_compatibility

`align-self` support: https://developer.mozilla.org/en-US/docs/Web/CSS/align-self#Browser_compatibility

**Comment by dallas** [comment]
Hmm … might need to consider beefing up the support for `align-self` as well, actually. Looking at all of the [different values & situations](https://developer.mozilla.org/en-US/docs/Web/CSS/align-self#Syntax) it should allow for vs. the [quite limited values](https://github.com/grommet/grommet/blob/master/src/js/utils/styles.js#L238) that Grommet currently allows for. I’m not sure how to fix it, exactly, as it seems like it might need to be context-aware (if I’m reading the MDN version of the spec correctly), meaning it would have different sets of values depending on if it’s inside of a grid, inside of a flex-box, or as part of an absolutely positioned layout. 

Obviously Grommet doesn’t want to wholesale copy all possibilities from CSS – most people won’t ever need them all – but it does seem like if it supports `align-self` for grids it should also support `justify-self`, even if it does so in the same simplified 8-lines-of-code way.

**Comment by jjalonso** [comment]
It was not implemented at the end isn't?

Whats the way to go If i want to self position (main axis) an item in a flex container using Grommet? it require styled components?

Thanks.

**Comment by panoskouff** [comment]
when using Box in a grid you can align it towards but one Axis with `alignSelf` but not towards the other because `justifySelf` doesnt exist..  

seems quite arbitrary to have the one property but not the other..
