### ISSUE TITLE
v2 FormField - only 1 focusable control allowed

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2048]
In v2 FormField, if there are more than 1 focusable controls, no-one of the controls after the first can be selected (the focus is forced to the first control(
Example use case of FormField with multiple focusable children:
![screenshot713](https://user-images.githubusercontent.com/6075606/39931794-755d7fe4-550c-11e8-9b7d-893388fb597c.jpg)

**Comment by ericsoderberghp** [comment]
What is the rationale for putting these controls into a single field? The example seems to indicate four fields.

**Comment by atanasster** [comment]
The rationale is to have a single label, help hint. error for those related input controls (their are parameters of the same field).

**Comment by atanasster** [comment]
Here is a live page with the use case: https://crypto-grommet.com/models/playground (the optimizer, but also try click on "add layer" and edit the various parameters)

**Comment by ericsoderberghp** [comment]
I think it's the combination of multiple "parameters" for the same "field" that is causing confusion for me. Each of the parameters has a label and an input element, which are the key aspects of a form field. Conceptually, it sounds like a nested field, where there is an outer field with a label and help text that contains multiple fields, each with a label and input.

**Comment by ericsoderberghp** [comment]
Typically, we structure these as separate fields and use progressive disclosure to add and remove fields as needed. Any help text for a collection of fields would be provided via a Text or Paragraph above the set of fields or below a controlling field.

**Comment by atanasster** [comment]
True, those are field and parameters for the field. But visually, I have opted to have the subfields with a label next to them (not on top) as it would take too much space to have separate label, hint, error for each sub-parameters. Your solution also works, but bot sure if your suggestion wouldn't bee too much space on the screen.

**Comment by ericsoderberghp** [comment]
My inclination is to preserve the label+input combination for FormField and explore a property or theme capability to provide a more compact version.

**Comment by atanasster** [comment]
A compact FormField would be great, but allowing to have more than 1 focusable control inside of a FormField is still a good enhancement?

**Comment by ericsoderberghp** [comment]
If I have more than one input element inside a field, how are they labelled? I still think that sounds like multiple fields, where semantically a field is a label+input-element.

**Comment by atanasster** [comment]
It can be still a single field (composed of multiple focusable controls). ie a tags input: https://grommet-nextjs.herokuapp.com/add-ons/tags
