### ISSUE TITLE
Unique titles for Grommet documentation

### ISSUE THREAD

**Issue by samogami** [grommet/grommet#205]
In Grommets documentation all pages have the same title value. "Grommet - User Experience for the Enterprise".  Each page should have a unique / descriptive title. 

Examples:
For: http://grommet.io/docs/hpe/develop/accessibility
The `title` element could be: Accessibility - Grommet Development Documentation

For: http://grommet.io/docs/hpe/develop/layer
The `title` element could be: Layer - Grommet Development Documentation

This supports [WCAG 2.0 - 2.4.2 Page Titled: Web pages have descriptive titles](http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/G88)

**Comment by bryanjacquot** [comment]
Thanks for the feedback, @samogami.  Page titles are now unique for each page on grommet.io.
