### ISSUE TITLE
grommetux-button isssue on vivo phone (vivo browser)

### ISSUE THREAD

**Issue by bitshadow** [grommet/grommet#2071]
Login button is not showing text in LoginForm when rendering in Vivo phone default browser. Wildly popular phone in Asia and growing rapidly because of its price.

### Expected Behavior
Login button text should appear as well as it should be clickable. 

### Actual Behavior
Login button is not showing text

### screen shot exhibiting the issue
![vivo_login](https://user-images.githubusercontent.com/574802/41189122-678e6428-6be6-11e8-8689-c7c516e4521f.jpeg)

### Steps to Reproduce
 1. Get Vivo phone
 2. Open login form in their default (Vivo browser) 

### Your Environment
* Grommet version: 1.9.0
* Browser Name and version: Vivo Y51L
* Operating System and version (desktop or mobile): Android 5.0.2

**Comment by bitshadow** [comment]
issue seems to disappear if we remove `grommetux-button` class from button. I tried to figure it out couldn't find exact property which is causing it.

**Comment by alansouzati** [comment]
interesting issue. I'm afraid I cannot debug this since I don't have this device. Do any of you know if there is a way to virtually simulate it?
