### ISSUE TITLE
Grommet not working with material-ui

### ISSUE THREAD

**Issue by SaloniDesai** [grommet/grommet#2075]
I am trying to use dev-extreme react grid table that uses material-ui plugin.  My rest of the project uses grommet so when i added the dev-extreme table to it the styling of the table breaks. It is giving warning messages such as: 
**warning.js:33 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by GroupPanelEmptyMessageBase)
    in GroupPanelEmptyMessageBase (created by WithStyles(GroupPanelEmptyMessageBase))
    in WithStyles(GroupPanelEmptyMessageBase) (created by EmptyMessagePlaceholder)
    in EmptyMessagePlaceholder (created by GroupPanelLayout)
    in DropTarget (created by GroupPanelLayout)
    in GroupPanelLayout (created by TemplateConnector)
    in TemplateConnector (created by GroupingPanel)
    in TemplatePlaceholder (created by SearchPanel)
    in TemplatePlaceholder (created by ColumnChooser)
    in TemplatePlaceholder (created by Toolbar)**

### URL, screen shot, or Codepen exhibiting the issue
![screen shot 2018-06-14 at 3 30 42 pm](https://user-images.githubusercontent.com/6766619/41434519-0e1237aa-6fea-11e8-8c70-bb2a9d4246fc.png)

code-sandbox example: https://codesandbox.io/s/xl5m6w9744
### Your Environment

* Grommet version: ^1.10.1
* Browser Name and version: chrome
* devexpress: ^1.3.0
* material-ui: ^1.0.0-beta.47

**Comment by alansouzati** [comment]
would you have a codepen that reproduces this ?

you can fork ours here: https://codepen.io/grommet/pen/gaEGPY

**Comment by atanasster** [comment]
I have a CodeSandbox - its working with v2 - https://codesandbox.io/s/8kx5wlm058

**Comment by SaloniDesai** [comment]
I tried adding accordion in your codeSandbox example but it didn't work. Does v2 not support it yet ?

**Comment by atanasster** [comment]
Accordion was just added 6 days ago, hasn't made it yet into npm
