### ISSUE TITLE
Bizarre documentation user experience.

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#2084]
Hi,

I found this library in a Google search. Your home page says "A design system made for React.js", but the doc site is almost like a sales pitch for a design system, with no actual API docs.  

# Steps to Reproduce
- Visit website. Read website
- Attain an expectation that grommet is a design system for React with ready made components.
- Click "Components" link @ http://grommet.io/docs/components
- Not see any actual React components.
- Click the "Box" component to see if I can learn how to use a Box react component @ http://grommet.io/docs/box
- Not see any actual code for the Box component. No instructions for how to import and no example usage.

# Expected Results
I expect to visit your docs website and quickly see instructions for installing the library via NPM and a collection of components with accompanying code samples. Kinda like https://material-ui.com/ and every other design system + react component library.

# Actual Results
Confusion and frustration.

**Comment by alansouzati** [comment]
Thanks for your feedback. This is very timely as we are working on v2: http://v2.grommet.io.

With the new site I still feel that your feedback makes sense. 

We have done a better job with our icons library site: http://grommet.io/grommet-icons/.

I will chat with @L0ZZI on how to make the experience better for the v2 site.

**Comment by iMerica** [comment]
Thanks @alansouzati. I think I've figured it out. Very excited about V2 👍.

**Comment by alansouzati** [comment]
glad you found your way in. I definitely agree we need to make it easier for new folks to get started from minute one. join our slack channel if you haven't yet: http://slackin.grommet.io
