### ISSUE TITLE
GrommetV2 Grid is not working in IE11

### ISSUE THREAD

**Issue by rameshsunkara** [grommet/grommet#2090]
GrommetV2 Grid is not working in IE11

###  Codesandbox exhibiting the issue
https://codesandbox.io/s/xzr15op284

### Your Environment
* Grommet version: V2
* Browser Name and version: IE 11

**Comment by ericsoderberghp** [comment]
Unfortunately, IE11 does not support enough of the CSS grid specification to allow us to provide the Grid component in IE11. At a talk by https://rachelandrew.co.uk, one of the CSS advisors, she recommended against attempting to polyfill, which we concur with. Instead, you can use `Grid.available` to conditionally create a fallback implementation suitable for your design. This is approach is documented in https://v2.grommet.io/grid.

**Comment by rameshsunkara** [comment]
Thanks for the update, its disappointing. Given that Grommet is an enterprise design system and most of the enterprises still support IE11 ( or will support IE11 until at least 2019)

**Comment by ericsoderberghp** [comment]
You can typically achieve reasonable design goals using `Box` as a fallback, though it tends to be a bit more verbose.

**Comment by rameshsunkara** [comment]
yup just looking at :) StyledBox in grommet source code to understand how to leverage

`
const basisStyle = css
  flex-basis: ${props =>
    BASIS_MAP[props.basis] || props.theme.global.size[props.basis] || props.basis};
;
`

**Comment by atanasster** [comment]
Have you tried <table /> as a fallback? A javascript polyfill for grid css is probably too heavy anyway.

**Comment by brianbancroft** [comment]
@ericsoderberghp hi there, I just wanted to say hi and let you know that `Grid.Available` is no longer visible in the documentation. If someone else finds this as one of the first hits for a "Grommet Grid IE" search (as is my case), you can see it in the source code: https://github.com/grommet/grommet/blob/master/src/js/components/Grid/Grid.js#L32
