### ISSUE TITLE
V2 Table: It should be customizable via theme file 

### ISSUE THREAD

**Issue by ChrisRose** [grommet/grommet#2092]
I'd like to customize a Table, and struggled to add a bottom border to each TableRow. 

### Expected Behavior
The Table/TableRow should be themeable via a theme file, or accept more props to customize the appearance.

### Actual Behavior
N/A

### URL, screen shot, or Codepen exhibiting the issue

N/A

### Steps to Reproduce
N/A

### Your Environment
* Grommet version: NEXT
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by ChrisRose** [comment]
The solution I hit upon was wrapping the Table in a Box and doing

```
<Box
        theme={{
          box: {
            extend: `
                td {
                  border-bottom: 1px solid rebeccapurple;
                }`
          }
        }}
      >
```

**Comment by alansouzati** [comment]
this should not be closed

**Comment by ericsoderberghp** [comment]
Some aspects we should should cover:

header row: border, background
header cell: padding
body row: border, background, alternating, hover indicator
body cell: padding
footer row: border, background
footer cell: padding

**Comment by ericsoderberghp** [comment]
As far as the original request goes, you can supply props to the TableCell components in each row:
```
<Table><TableBody><TableRow><TableCell border={{ side: 'bottom' }} />
```
