### ISSUE TITLE
Theme undefined - withTheme not working as it should

### ISSUE THREAD

**Issue by develomark** [grommet/grommet#2094]
It seems that moving over to the latest Grommet with new Context provider/consumer api I am getting a bunch of errors. Including:

```
Cannot read property 'dark' of undefined
TypeError: Cannot read property 'dark' of undefined
    at getDerivedStateFromProps (/.../node_modules/grommet/components/Box/Box.js:151:22)
```

### Expected Behavior

The theme should propagate down to the components.

### Actual Behavior
Exploring further I can see that `theme` is `undefined` on a hot reload or when the props change.

We were getting similar errors in our own components when using grommet `withTheme` hoc. So this is a potential candidate for the location of the issue. After switching out the Grommet `withTheme` `import { withTheme } from '../../node_modules/grommet/es6/components/hocs'` to the following the issue went away:

```
import React, { Component } from 'react'
import { ThemeContext } from 'grommet'

export const withTheme = WrappedComponent => {
  class ThemedComponent extends Component {
    render() {
      return (
        <ThemeContext.Consumer>
          {theme => <WrappedComponent {...this.props} theme={theme} />}
        </ThemeContext.Consumer>
      )
    }
  }
  return ThemedComponent
}

export default withTheme
```

There appears to be something interesting going on.

### Steps to Reproduce
Unsure exactly. Perhaps this is an issue with SSR? It should be noted that Grommet has been working with no issue from v1 and all releases of v2 up until now.

### Your Environment

* Grommet version: 2.0.0-beta.4
* React: 16.4.1
* Nextjs: 6.1.1

**Comment by atanasster** [comment]
Hi, please try updating to  `"react": "^16.4.1"`

**Comment by develomark** [comment]
No joy. Already was on `16.4.1`.

**Comment by atanasster** [comment]
react-dom as well at `16.4.1` ?

**Comment by develomark** [comment]
Yes, indeed.

**Comment by atanasster** [comment]
sorry, no more ideas :) 
16.4.1 fixed it for me and SSR context API: https://github.com/atanasster/grommet-latest-nextjs

**Comment by develomark** [comment]
Actually, you've been a massive help. 

Deleted `node_modules` - something old must have stuck around.

Man, that was an afternoon wasted :-(

Appreciate the help!

**Comment by atanasster** [comment]
glad to hear, I also spent a day trying to isolate the issue and create a sample to reproduce it when the context API was introduced in v2 :)
