### ISSUE TITLE
V2 Select dropdown item broken in FireFox

### ISSUE THREAD

**Issue by nogever** [grommet/grommet#2095]
### Expected Behavior

V2 Select dropdown item button height is set around text/label.

### Actual Behavior

V2 Select dropdown item button height is extended to full.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/3888294/42331862-86895654-8044-11e8-94d9-6c9cb24ca54d.png)

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: V2 (Next-stable)
* Browser Name and version: latest FireFox
* Operating System and version (desktop or mobile): MacOs

**Comment by ericsoderberghp** [comment]
Can you provider a URL or CodePen demonstrating the issue? I am unable to reproduce it using storybook or https://ui-krupa.dev.hpedevops.net/service-catalog.

**Comment by skimcm** [comment]
@ericsoderberghp CodePen is here https://codesandbox.io/s/6zqkm4k7mr

Apparently the issue happens only when the list exceeds the height of the screen.

<img width="1272" alt="screen shot 2018-07-06 at 2 38 22 pm" src="https://user-images.githubusercontent.com/24554435/42395069-7178841a-812a-11e8-8688-96b49c7c8691.png">

**Comment by ericsoderberghp** [comment]
Thanks for triaging this. @alansouzati do you know why we have `fill={true}` for the Buttons inside the SelectContainer?
