### ISSUE TITLE
V2 Button label should be centered on 'Fill'

### ISSUE THREAD

**Issue by nogever** [grommet/grommet#2097]
### Expected Behavior

V2 Button's label should be aligned to center when `fill={true}` is applied. Or even better, give us an option to choose.

### Actual Behavior

The label is aligned to left.

### URL, screen shot, or Codepen exhibiting the issue
Codepen: https://codesandbox.io/s/8x3q589z9l
Screenshot:
<img width="1274" alt="screen shot 2018-07-06 at 12 46 34 pm" src="https://user-images.githubusercontent.com/3888294/42390762-02c5c6b8-811b-11e8-86a9-227d862fb7bd.png">

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
I believe this is a regression due to https://github.com/grommet/grommet/pull/2074. I think we need a `justify='center'` for the Box inside the Button.

**Comment by ericsoderberghp** [comment]
I don't think we want to add properties to Button to control this. If you want finer control over the appearance, you can always use layout components as children to control the visual appearance.
