### ISSUE TITLE
App css and flush property will bring up scroll bars.

### ISSUE THREAD

**Issue by tobias-flitsch** [grommet/grommet#21]
Hi,

the App component has a css property `overflow: auto;`, which will bring up the browser scroll bars if content is too large. As far as I experienced it, this is always the case when setting the `flush={true}` property, e.g. with the Tiles component.

Can we change the `overflow: auto;` to `overflow: hidden;`?

Sorry if this is negligible, I am new to this community.

**Comment by bryanjacquot** [comment]
@tobias-flitsch: the flush option has been depreciated and removed from the App component.  If you're having an issue, please provide a recent example with more details, including a CodePen.
