### ISSUE TITLE
v2 Select on dark background - arrow not visible

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2101]
The arrow icon for Select is not visible:

![screenshot720](https://user-images.githubusercontent.com/6075606/42410611-dfc87f68-81f4-11e8-8f9b-7e1bc617165e.jpg)

https://codesandbox.io/s/2x9656290y

**Comment by alansouzati** [comment]
I think if we want a different color for the Select we should do it in the theme. I've added a PR that allows a custom backgroundColor for Select.

**Comment by alansouzati** [comment]
you just reminded me that I should also add an option to change the icon color as well. let me update the PR.

**Comment by ericsoderberghp** [comment]
https://github.com/grommet/grommet/pull/2151 adds a `theme.global.control.color` to permit having a control color separate from the brand color.
