### ISSUE TITLE
Is there tag component in Grommet?

### ISSUE THREAD

**Issue by kaushalyap** [grommet/grommet#2102]
I really like Grommet, But I was not able to find a tag component (ex: [tag component in Ant Design](https://ant.design/components/tag/)). Is there any tag component or an alternative to that in Grommet?

**Comment by atanasster** [comment]
@kaushalyap would the v2 add-ons Tag work for you https://grommet-nextjs.herokuapp.com/add-ons/tag

**Comment by kaushalyap** [comment]
Thanks for the reply. It seems okay. Can I use this inside an auto suggest where tag is generated on completion(ex: like adding tags to StackOverflow questions)

**Comment by alansouzati** [comment]
Let me create a codesandbox for you that implements StackOverflow tag component. With v2 this should not take long :)

**Comment by alansouzati** [comment]
https://codesandbox.io/s/3y0wzv59om

**Comment by yairEO** [comment]
You can use my lightweight flexible React Tagify component:

https://github.com/yairEO/tagify

feel free to incorporate it into Grommet
