### ISSUE TITLE
The latest Select fix introduced a new regression

### ISSUE THREAD

**Issue by nogever** [grommet/grommet#2107]
### Expected Behavior

Select dropdown list items/buttons lose height.

### Actual Behavior

Select dropdown list items/buttons should maintain their height.

### URL, screen shot, or Codepen exhibiting the issue
<img width="1278" alt="screen shot 2018-07-09 at 9 27 22 am" src="https://user-images.githubusercontent.com/3888294/42597341-68ecbeba-8526-11e8-88b9-4971685f35c5.png">

### Steps to Reproduce
 1. Create Select component with enough number of items/options
 2. Should see the items/buttons lose height and stack on top of each other
 3. 

### Your Environment

* Grommet version: https://github.com/grommet/grommet/commit/123da8e4e63c7c1c0cfe865c79fb0d18824b2ab4
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): MacBook

**Comment by alansouzati** [comment]
This is fixed in this PR https://github.com/grommet/grommet/pull/2104
