### ISSUE TITLE
Grommet2 InfiniteScroll stops working with renderMarker

### ISSUE THREAD

**Issue by nogever** [grommet/grommet#2113]
### Expected Behavior

InfiniteScroll renders renderMarker briefly on scrolling down.

### Actual Behavior

InfiniteScroll stops working. It renders no more new items, hence can no longer scroll down.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/6l0kkk0nrw
<img width="1280" alt="screen shot 2018-07-12 at 1 24 48 am" src="https://user-images.githubusercontent.com/3888294/42614111-67f3255c-8572-11e8-9359-699dc9aa1795.png">

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by srockk** [comment]
@kentsalcedo did you add a renderMarker prop in the sandbox you shared? I don't see one and this issue is "InfiniteScroll stops working with renderMarker"

**Comment by ericsoderberghp** [comment]
I cannot reproduce this. I've added a story to demonstrate:

https://storybook.grommet.io/?selectedKind=InfiniteScroll&selectedStory=Marker&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
