### ISSUE TITLE
Layer is no longer scrollable with the latest patch

### ISSUE THREAD

**Issue by nogever** [grommet/grommet#2118]
### Expected Behavior

Layer should scroll when there's overflowed content.

### Actual Behavior

Layer is not scrollable when there's overflowed content. This happens with the latest patch/commit.

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: The latest Grommet2 commmit
* Browser Name and version: Latest Chrome
* Operating System and version (desktop or mobile): MacBook

**Comment by nogever** [comment]
Closing since I learned that now I have to do this
```
<Layer full='vertical'>
  <Box overflow='auto'>
  </Box>
</Layer>
```

**Comment by avin-kavish** [comment]
But this sets scroll in the inner component, not the page.
