### ISSUE TITLE
DropButton with Calendar display bug on IE11

### ISSUE THREAD

**Issue by nogever** [grommet/grommet#2125]
### URL, screen shot, or Codepen exhibiting the issue
<img width="219" alt="screen shot 2018-07-17 at 10 26 59 am" src="https://user-images.githubusercontent.com/3888294/42829943-63ccc68c-89b8-11e8-8a5a-9b7109e3975b.png">
No codepen but this is the code

```
<DropButton
      onClick={() => setOpen(!open)}
      open={open}
      onClose={() => setOpen(!open)}
      dropAlign={{
        top: 'bottom',
        left: 'left',
      }}
      dropContent={(
        <Box
          pad='small'
          round='medium'
        >
          <Calendar
            size='small'
            date={date}
            onSelect={onSelect}
            bounds={[
              moment().subtract(5, 'years').toISOString(),
              moment().toISOString(),
            ]}
            disabled={[[
              moment().toISOString(),
              moment().add(1, 'year').toISOString(),
            ]]}
          />
        </Box>
      )}
    >
```

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: The most latest V2 NEXT-STABLE
* Browser Name and version: IE11
* Operating System and version (desktop or mobile): desktop

**Comment by nogever** [comment]
Setting the `StyledDrop-`'s width to `'auto'` seems to be solving my issue.

**Comment by srockk** [comment]
One of the latest patches must have fixed this. Thanks! and closing.
