### ISSUE TITLE
Grommet v2 CheckBox's label cannot be styled using styled-components

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#2140]
### Expected Behavior

That I can style the CheckBox label with styled-components.

### Actual Behavior

The styles defined in the styled-components string literal is only applied to the input, not to the label.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/vykykly047

### Steps to Reproduce
 1. Write a styled-components HOC to style the CheckBox component: `styled(CheckBox)`
 2. Add a style like `color: blue;`
 3. Check the DOM and see the styles are applied to the `input` and not to a parent container or to the div including the label. 

### Your Environment

* Grommet version: 2.0.0-beta.4
* Browser Name and version: Chrome 67
* Operating System and version (desktop or mobile): OS X 10.13.5

**Comment by alansouzati** [comment]
I feel this is still an issue. reopening

**Comment by alansouzati** [comment]
I'm investigating this now.

**Comment by alansouzati** [comment]
To be honest, I feel this is a broader issue. We have other components that have internal nodes that we don't expose in the theme. My investigation will aim to fix this problem for CheckBox initially. I will add this as a note to our team to make sure we expose an extend to all internal nodes in Grommet v2.
