### ISSUE TITLE
v2 Anchor with Icon should use theme brand color

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#2141]
Using the v2 Anchor with a icon, the icon should use the brand color defined in the provided theme:
Note: I already reported this on the Grommet slack and confirmed to be a bug (https://grommet.slack.com/archives/C04LMHN59/p1532700147000477) Just making sure it is recorded here.

```
const myTheme = {
  global: {
    colors: {
      brand: "#007482"
    }
  }
}

<Grommet theme={myTheme}>
  <Anchor
    href="https://www.facebook.com/myfacebookaccount"
    a11yTitle="Facebook"
    icon={<FacebookOption color="brand" size="small" />}
  />
</Grommet>
```

### Expected Behavior

The icon should use the theme brand color provided to the `Grommet` wrapper component.

### Actual Behavior

The Icon remains the Grommet brand color.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/kwvqw4ry0v

### Steps to Reproduce
 1. Wrap an Anchor with a Grommet component, supplied with a theme with defined brand color
 2. Add an Icon to the Anchor's icon prop
 3. 

### Your Environment

* Grommet version: 2.0.0-beta.4
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by alansouzati** [comment]
yeah I think there is a bug with colors being ignored. I similar issue is that a custom color for the Anchor is not being used.

https://codesandbox.io/s/1o8jpwm3vq

**Comment by alansouzati** [comment]
by default Anchor will set a custom color for when Icon is present. you can customize it with the `theme.anchor.color` entry. There is a bug I'm fixing that will allow that to happen.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/pull/2151
