### ISSUE TITLE
Align center and SearchInput

### ISSUE THREAD

**Issue by josephalhamad** [grommet/grommet#215]
I need the text to be centered and the searchInput element to be stretched across (width: 960px just like appCentered). However, I think the align="center" attribute isn't working properly with SearchInput component. Align center shrinks the width of SearchInput. Same behavior in Section and Box components.

A screenshot before align="center" is applied. produced using this code:

       var Search = React.createClass({
          render: function() {
               return (
                        <Section>
                         <h1 strong={true}>Search search</h1>
                         <h2 strong={true}>Grommet Example example example example example example example example</h2>  
                         <SearchInput placeHolder="Search" ref="search"/> 
        
                        </Section>
                );
          }

     });

![before_align](https://cloud.githubusercontent.com/assets/8975095/10586685/59e78a66-766b-11e5-96b9-c4f8262b4ed5.JPG)

After adding align="center" to the section component.

![with_align](https://cloud.githubusercontent.com/assets/8975095/10586851/616937c0-766c-11e5-85d7-def22cc90a3e.JPG)

---------------------------------------------------------------

Using both appCentered={true} and align="center" in Section

![both_align_appcentered](https://cloud.githubusercontent.com/assets/8975095/10587160/e400a136-766d-11e5-9583-99a4b00cad53.JPG)

using appCentered={true} alone in Section

![with_appcentered](https://cloud.githubusercontent.com/assets/8975095/10587191/0a847eb8-766e-11e5-8e0c-61f13b409c1e.JPG)

**Comment by jwijay** [comment]
Hello @josephalhamad.

Are you trying to use SearchInput within a form, or standalone? If you want standalone search functionality, I would recommend using the Search component with the "fill" option set to true to get the desired appearance. See here for an example: http://www.grommet.io/docs/develop/Search

**Comment by bryanjacquot** [comment]
@josephalhamad did you have a chance to explore @jwijay suggestion?  Is this still an issue for you?

**Comment by bryanjacquot** [comment]
Closing until we hear more from submitter.
