### ISSUE TITLE
Strong={true} in header tags

### ISSUE THREAD

**Issue by josephalhamad** [grommet/grommet#216]
Making header tags bold using strong={true} isn't working. 

Without strong={true}. using 

             <h1>Search search</h1>

![without_strong](https://cloud.githubusercontent.com/assets/8975095/10589013/04a22e2e-7677-11e5-99ff-eaac57360c03.JPG)

With strong={true}.  using

              <h1 strong={true} >Search search</h1>

![with_strong](https://cloud.githubusercontent.com/assets/8975095/10589183/c64fd63e-7677-11e5-8011-8cfb2b1cfd46.JPG)

what it should look like. using 

              <h1 className="header--strong">Search search</h1>

![with_classname](https://cloud.githubusercontent.com/assets/8975095/10589223/fcd712c6-7677-11e5-8375-e567b704d8e8.JPG)

**Comment by ericsoderberghp** [comment]
The current guidance is to use a `<strong>` element within the `<h*>` element to achieve that.
