### ISSUE TITLE
Form Field Auto Focus on Input

### ISSUE THREAD

**Issue by matt-catellier** [grommet/grommet#2167]
I am in trying to use FormField, and passing in a custom component for the label. This custom component has a menu, which when clicked should show the menu items.  
i.e.  <FormField label={<Heading/>}>

Seems that the FormField has default behaviour to focus on the Input when you click anywhere in the form field, (i.e. FormField.js line 89).  I was wondering what the best practice to override the 'onClick' behaviour of this component may be.

### Expected Behavior
<FormField label={<Heading/>} onClick={null}> would allow you to override the onClick functionality for the FormField Componet

### Actual Behavior
<FormField label={<Heading/>} onClick={null}> does not allow you to override the onClick functionality for the FormField Componet

**Comment by alansouzati** [comment]
are you using v1 or v2?

**Comment by ShimiSun** [comment]
@matt-catellier are you still able to reproduce the issue after upgrading to v1.13.0?

**Comment by ShimiSun** [comment]
feel free to re-open if you still see the issue.
