### ISSUE TITLE
Drop dynamic placement

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2168]
We should support realigning the drop automatically if the `align` prop does not offer enough real state for the Drop to show in that location

### Expected Behavior
If we say drop should render at the bottom, and there is not enough space we should render at the top. same for left and right.

### Actual Behavior
current it stays where it is even if the space is limited

This is more like a feature request than a bug

**Comment by alansouzati** [comment]
It would be nice to fix this before officially rolling with v2

**Comment by ericsoderberghp** [comment]
Drop already does this. If there isn't room to fit it, it places it on the other side if there is more room there.
