### ISSUE TITLE
V2 Beta 5 Toggle Checkbox loses hover and checked state styles with custom theme

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#2193]
### Expected Behavior

I would expect that toggle checkboxes still have hover and checked state styles when a custom theme is defined.

### Actual Behavior

When a custom theme is defined, the toggle checkbox does not have styles for hover and checked state. 

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/32j9xl0zkq - demonstrates differences between base theme and custom theme. Also noted in this codesandbox is that the light/dark theme colors is also not applied, but I'm happy to keep this issue scoped to the hover and checked states issue.

It seems that the defined styles here: https://github.com/grommet/grommet/blob/NEXT/src/js/components/CheckBox/StyledCheckBox.js#L107-L117

And in the theme file for the toggle type: 
https://github.com/grommet/grommet/blob/NEXT/src/js/themes/base.js#L325-L331

needs expansion to support custom theming for the toggle type checkbox. 

### Steps to Reproduce
 1. Define custom theme following beta 5's theme conventions
 2. Wrap checkbox component set as toggle type with `Grommet` component and supply the theme
 3. Toggle checkbox between checked and hovered states to see no style differentiation.

### Your Environment

* Grommet version: 2.0.0-beta.5
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by alansouzati** [comment]
this is fixed in the latest grommet
