### ISSUE TITLE
Interesting behavior when using React.Fragment with responsive context

### ISSUE THREAD

**Issue by djalmaaraujo** [grommet/grommet#2194]
### Expected Behavior
![image](https://user-images.githubusercontent.com/3402/44481510-d87bad80-a63d-11e8-83bb-7469f13a248c.png)

The elements should have space between

### Actual Behavior
![image](https://user-images.githubusercontent.com/3402/44481476-c7cb3780-a63d-11e8-9dbb-c92a62f2df1f.png)

The elements are tied to each other and no space between

Codesandbox: https://codesandbox.io/s/n3po522lkj
Demo: https://n3po522lkj.codesandbox.io/button

### Steps to Reproduce
 1. Open https://codesandbox.io/s/n3po522lkj
 2. Check the error

### Your Environment

* Grommet version: v2.0.0-beta.5
* Browser Name and version: All
* Operating System and version (desktop or mobile): macos

**Comment by ShimiSun** [comment]
hi @djalmaaraujo, I wasn't able to reproduce the problem using the code sandbox example. is the issue still relevant? can you please provide an updated example?

**Comment by MikeWalrath** [comment]
Hi @djalmaaraujo just checking in. Were you able to validate the issue?

**Comment by djalmaaraujo** [comment]
@ShimiSun You can close, maybe new version fixed.
