### ISSUE TITLE
V2. Module not found error on the latest patch

### ISSUE THREAD

**Issue by srockk** [grommet/grommet#2197]
### Expected Behavior

The app should build

### Actual Behavior

The app fails to build

### URL, screen shot, or Codepen exhibiting the issue
```
./node_modules/grommet2/es6/themes/base.js
Module not found: Can't resolve 'grommet-icons/es6/components/icons/Actions' in 
'...../node_modules/grommet2/es6/themes'
```

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: https://github.com/grommet/grommet/commit/866835ffc11e75166a55b91815f6630542adc82a
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by alansouzati** [comment]
Yeah sorry about that regression. Fixing it now.

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/pull/2198
