### ISSUE TITLE
gulp dist should exit with errorcode on build error

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#220]
Found while changing node version.

Anytime that you change node version you have to rebuild any item with node-gyp.

Similar reproduction without having to change node-version for easy fix

```
npm i && rm -rf node_modules/node-sass && gulp dist
# should return non zero, returns 1
echo $?
```

**Comment by bryanjacquot** [comment]
Moving to Grommet Toolbox https://github.com/grommet/grommet-toolbox/issues/12
