### ISSUE TITLE
V2. Module not found error.

### ISSUE THREAD

**Issue by srockk** [grommet/grommet#2200]
### Expected Behavior

App should build

### Actual Behavior

App fails to build

### URL, screen shot, or Codepen exhibiting the issue
```
./node_modules/grommet2/es6/components/hocs.js
Module not found: Can't resolve 'grommet-icons/es6/icons/ThemeContext' in '.../node_modules/grommet2/es6/components'
```

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: https://github.com/grommet/grommet/commit/acb34e12c4ea361e056742d788dcc2a9cc4fb704
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by alansouzati** [comment]
This is so bad. sorry again. two regression in the same thing. I clear need to do a better job testing. I created this PR to fix this:

https://github.com/grommet/grommet/pull/2202

Let me test it more carefully.
