### ISSUE TITLE
V2. Regression on Select component with onSearch

### ISSUE THREAD

**Issue by srockk** [grommet/grommet#2201]
### Expected Behavior

Dropbox items should fill up the whole area

### Actual Behavior

The items doesn't fill up the whole area.

### URL, screen shot, or Codepen exhibiting the issue
Storybook example
```
<Grommet>
  <FormField label='Label' htmlFor='select' {...this.props}>
    <Select
      id='select'
      placeholder='placeholder'
      options={options}
      value={value}
      onChange={({ option }) => this.setState({ value: option })}
      onSearch={(text) => {
        const exp = new RegExp(text, 'i');
        this.setState({ options: allOptions.filter(o => exp.test(o)) });
      }}
    />
  </FormField>
</Grommet>
```
<img width="639" alt="44500617-7465e300-a657-11e8-914f-c3c8a87931b4" src="https://user-images.githubusercontent.com/8532807/44537830-c21d3280-a6cd-11e8-9234-80da5e91ebbd.png">

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: The latest patch
* Browser Name and version: IE11
* Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
It turns out our Storybook was out of date. I have re-published it with the latest NEXT-stable. I am unable to reproduce this issue with the latest https://storybook.grommet.io/?selectedKind=FormField&selectedStory=Select&full=0&addons=0&stories=1&panelRight=0. Can you re-verify that you are still seeing it?

**Comment by srockk** [comment]
The link has no `onSearch` prop. Can you try one with `onSearch`? Also, I see the issue on Select with the search without FormField now. 
http://storybook.grommet.io/?selectedKind=Select&selectedStory=Search%20Select&full=0&addons=1&stories=1&panelRight=0
<img width="867" alt="screen shot 2018-08-23 at 1 33 28 pm" src="https://user-images.githubusercontent.com/8532807/44541915-6d7fb480-a6d9-11e8-9116-933762d2fb6f.png">

**Comment by ericsoderberghp** [comment]
Here is what I'm seeing with that URL using IE11 via BrowserStack:

![screen shot 2018-08-23 at 10 57 47 am](https://user-images.githubusercontent.com/11637956/44543140-95fcb400-a6c3-11e8-9802-9a98e7623c22.png)

It is using this version of IE11:

![screen shot 2018-08-23 at 10 58 04 am](https://user-images.githubusercontent.com/11637956/44543150-a0b74900-a6c3-11e8-92b5-693ad66e7bd2.png)

How are you accessing it and which version of IE11 do you have?

**Comment by srockk** [comment]
Browserstack. IE11 on Windows 7
<img width="386" alt="screen shot 2018-08-23 at 2 17 57 pm" src="https://user-images.githubusercontent.com/8532807/44544155-73789400-a6df-11e8-93df-6e4c87c44edf.png">

**Comment by ericsoderberghp** [comment]
When I try with Windows 7 + IE11, I get:

![screen shot 2018-08-23 at 11 28 05 am](https://user-images.githubusercontent.com/11637956/44544664-b6c70880-a6c7-11e8-9c2b-5742075abab5.png)

which seems to be behaving correctly. What browser are you running BrowserStack in?

**Comment by srockk** [comment]
Wow that's interesting. Chrome MacOS Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by srockk** [comment]
Have you did FormField + Select + onSearch combination by the way?

**Comment by ericsoderberghp** [comment]
I am still unable to reproduce this issue using BrowserStack with Windows 7 and IE11.

**Comment by alansouzati** [comment]
No feedback received. feel free to reopen it if you think there is anything to fix on our end
