### ISSUE TITLE
Button should have disabled attribute and non-active state should be set

### ISSUE THREAD

**Issue by djalmaaraujo** [grommet/grommet#2206]
### Expected Behavior
When using `<Button>` component and `disabled` attribute, the button should stay in the disabled state, aka the same as not `active={true}`?

I feel very weird adding `onClick` as `undefined to have a disabled button. This is very strange as a pattern and every other framework and even default html has `disabled`.

### Actual Behavior
Adding `disabled` does nothing. I can still use/click in the button

### Steps to Reproduce
 1. import Button
 2. Add: `<Button disabled={true} />`
 3. Click Still works.

### Your Environment

* Grommet version: beta 5
* Browser Name and version: All
* Operating System and version (desktop or mobile): All

**Comment by alansouzati** [comment]
I agree with this. FYI @ericsoderberghp
