### ISSUE TITLE
v2 Select keyboard navigation highlight currently selected item

### ISSUE THREAD

**Issue by florianbepunkt** [grommet/grommet#2208]
### Expected Behavior

If you have a select component and you go through the available options with up and down keyboard keys the currently active option should be highlighted.

### Actual Behavior

Current active option (that you could use by pressing enter) is not selected. As far as I know this behaviour was introduced with the latest grommet theme changes. before the current active option in dropdown was properly highlighted.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=select&module=%2Fsrc%2FSelect.js

**Comment by alansouzati** [comment]
This has been fixed.
