### ISSUE TITLE
v2 Image - add `width` and `height` prop

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2210]
Currently there is no `width` or `height` props to Image. Although it could seem tempting to use `Box` with `background`, in some cases it is useful to rely on the `img` tag. For example, when you want to subscribe to `onError` and `onLoad` props.

`<Image width="small" height="small" src="/path/unexisting.jpg" onError={() => this.setState({ unexistingImage: true })} />`

### Your Environment

* Grommet version: v2
* Browser Name and version: any
* Operating System and version (desktop or mobile): any

**Comment by ericsoderberghp** [comment]
Why not put it in a Box?

**Comment by alansouzati** [comment]
this is how it looks inside a Box: https://codesandbox.io/s/oopzqq15n9

Am I doing something wrong?

**Comment by ericsoderberghp** [comment]
It seems to be working fine with Box, as illustrated here:
https://storybook.grommet.io/?selectedKind=Image&selectedStory=Fit&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
