### ISSUE TITLE
v2 Box - Add options to background other then 'cover'

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2211]
### Expected Behavior
Today background is always using `cover` as an option. We should add a property to background that allows it to be changed.

https://github.com/grommet/grommet/blob/NEXT/src/js/utils/background.js#L62

### Actual Behavior
Today it is hard to customize this.

### Your Environment

* Grommet version: v2
* Browser Name and version: any
* Operating System and version (desktop or mobile): any

**Comment by ericsoderberghp** [comment]
What's an example of where you'd want to use `contain`?

**Comment by ShimiSun** [comment]
@alansouzati do you still find this as a relevant issue? and if so, can you please share answer eric's question.
