### ISSUE TITLE
v2 add NavAnchor and NavButton 

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2216]
A common need for a UI app is a component that handles navigational links, where there is some built-in logic to handle the active route. A counterpart in react router is `NavLink`.

It seems to me that Grommet should have two extra components: NavAnchor and NavButton. These components will add some logic for detecting if the route is active, and add styling to it. this style would live in the theme object, something like:

```
const myCustomTheme = {
  navAnchor: {
    active: css`
      text-decoration: underline;
    `
  },
};
```

Thoughts?

**Comment by ericsoderberghp** [comment]
Why not extend RoutedAnchor and RoutedButton?

**Comment by alansouzati** [comment]
great question. Actually I thought about it, but you can totally have a RoutedAnchor alongside with a text (non-navigational). If we add that logic inside RoutedAnchor, it will set the active in that anchor. we could add a prop to RoutedAnchor to ask if it is navigational or not, but I prefer a separate component.

**Comment by ericsoderberghp** [comment]
I think we should not get tied to routing libraries, which would be required to "add some logic for detecting if the route is active". Instead, I think we should ensure that we support `active` on Button and Anchor, along with theme-ability of that. We could provide starters/patterns/templates showing how to integrate with various routing libraries, such as react-router, nextjs, etc. For example, see RoutedButton.js in https://codesandbox.io/s/216vvpmlqj.

**Comment by MikeWalrath** [comment]
@alansouzati have you had a chance to look at the above?

**Comment by alansouzati** [comment]
This is related to https://github.com/grommet/grommet/issues/2855.

I like your direction Soderberg! I think our button and anchor can have `active` prop.

**Comment by ericsoderberghp** [comment]
They do: https://v2.grommet.io/button#active

**Comment by alansouzati** [comment]
I don't think Anchor has active. Also I dont think they allow a custom style to be passed (through the theme).

**Comment by ericsoderberghp** [comment]
I was thinking Button is enough to have `active`, since Button has richer styling, like when used in a sidebar. To put it another way, I was thinking a control being used for navigation, like in a sidebar, would use Button, not Anchor.

Regarding custom styling, do you mean that we don't have `theme.button.active.*`? Or, that we don't pass the `active` state to `extend`?

**Comment by alansouzati** [comment]
> Regarding custom styling, do you mean that we don't have theme.button.active.*? Or, that we don't pass the active state to extend?

both

I think we should make the changes consistent in both Button and Anchor, specially because we have RoutedAnchor and RoutedButton. Any reason as to why not adding to Anchor as well?

**Comment by ericsoderberghp** [comment]
How would you style an anchor differently for `active`? I'm just wanting a tangible example for reference.

**Comment by alansouzati** [comment]
In anchor `label` prop can be an element and you have freedom to style it however you want. I've seen cases where active anchors change colors and font weight. You can always use a Button and render it as Anchor, but I feel we should be consistent here without making too many assumptions on how people would consume Anchor/Button.

**Comment by ericsoderberghp** [comment]
I'm just wondering if all of the styling would be more Button-ish. For example, I could see Anchor having active if the only indicator was underline. I tend to think of Anchor as being used for inline cases, like in Paragraph. But, Button used for navigation things like sidebars, top menus, tab-ish things, etc.

**Comment by alansouzati** [comment]
That's fine if you want to make that assumption, I don't have a strong opinion here.

Generally speaking I like to see Grommet as a middle ground where we don't make these kind of assumptions. Up to you though.

**Comment by ericsoderberghp** [comment]
I think what I'm trying to say is that `<Button href="" />` is an `<a />` DOM element, so from that standpoint, it is an "anchor". Because of that, we had said that the `Button` component was to be used to drive visual styling to look "button-ish", which I tend to think of as how `active` would be used. The `Anchor` component was to be used for inline text contexts, such as anchors in markdown. Perhaps we are getting confused by this separation of DOM element labels and grommet component labels, wouldn't be the first time. And, sorry if I'm not "getting it", or making things more confusing.

**Comment by ShimiSun** [comment]
I think we have decided to proceed with Button and Anchor w/o the suggested extension. 
Feel free to reopen if you strongly think this issue should still be prioritized.

**Comment by chloesun** [comment]
Hello , is this still under consideration? I think it would be nice to have NavAnchor and NavButton
