### ISSUE TITLE
v2 Calendar, hoverIndicator

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2218]
In Calendar, the hoverIndicator is assumed a boolean value: 
https://github.com/grommet/grommet/blob/3a9bf2c93699888a808df0db323e683a742d4dfc/src/js/components/Calendar/Calendar.js#L188

However that is not the expected type for Button:
```
hoverIndicator: PropTypes.oneOfType([
      PropTypes.oneOf(['background']),
      PropTypes.shape({
        background: PropTypes.oneOfType([
          PropTypes.bool,
          PropTypes.string,
        ]),
      }),
    ])
```

**Comment by ericsoderberghp** [comment]
Fixed in https://github.com/grommet/grommet/pull/2229
