### ISSUE TITLE
v2 Stack - fill prop bleeding

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2219]
https://stackblitz.com/edit/grommet-demo-vkglqc?file=index.js
```
<Stack fill={true} >
...
</Stack>
```
results in warning:
![screenshot732](https://user-images.githubusercontent.com/6075606/44701163-618a4e80-aa5b-11e8-8110-7de9d317a0b4.jpg)

**Comment by ericsoderberghp** [comment]
Fixed in https://github.com/grommet/grommet/pull/2229.
