### ISSUE TITLE
New named exports issues

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2222]
https://github.com/grommet/grommet/blob/NEXT/src/js/index.js

```
export * from './components';
export * from './contexts';
export * from './themes';
```

this will not work for the contexts and themes when using the transform-imports plugin since they are not located in the components folder.  It will however allow named imports `import { ThemeContext }  from 'grommet';` in development when the plugin is not used and this will cause a lot of confusion.
Please either move them to components, or remove them from the index.js file.

If contexts and themes are not moved to components, please remove the index.js files from those folders ie:
`import { ThemeContext } from 'grommet/contexts';` will  not work with tree shaking

and recommend users to import directly from the subfolders:
`import { ResponsiveContext } from 'grommet/contexts/ResponsiveContext';`

**Comment by ericsoderberghp** [comment]
Our plan on this is to allow this pattern for webpack 4:

**Comment by atanasster** [comment]
Webpack 4 - I cant comment as I am not using it (using nextjs and upgrading on their schedule) and I dont think webpack 4 can be a recommended or default setting. 

I dont see how it can work also for transform-imports, unless I am missing something.
For example 
`import { ThemeContext } form 'grommet'` will lookup for ThemeContext in a folder under the components folder according to the rule for transform-imports plugin. Allowing this import from the index.js will cause only confusion as it might work in dev mode (if the plugin is configured to work only in dev mode).

`import { ThemeContext } from 'grommet/contexts' ` can work if you also add a config for the path `grommet/contexts` but seems unnecessary complication of the configs?

**Comment by alansouzati** [comment]
we don't have a lot of `contexts` in there. and you are most likely using all of them. so I don't think you need a config for that in your babel transform plugin. makes sense ?

**Comment by atanasster** [comment]
Its ok for me, just saying that exporting them from index.js doesnt make sense and can introduce issues. I would suggest removing them from index.js as a safeguard and also make sure the docs are importing them from the respective sub-folders

**Comment by ericsoderberghp** [comment]
I think including them in the top level index.js makes sense for webpack 4, since it will "do the right thing" with respect to tree shaking. So, if you use webpack 4, you can do:

**Comment by atanasster** [comment]
Up to you, but i am pretty sure we will hear about that one from users.

**Comment by ericsoderberghp** [comment]
Ah, I re-read your initial comment about the fact that `import { ThemeContext } from 'grommet'` will work in development mode. So, the confusion will be that development mode will work but production won't. I get it now. I would prefer to allow for the future facing behavior, which seems cleaner to me. I am trying to think of a way we can document, warn, detect, etc. the issue to mitigate any confusion.

**Comment by atanasster** [comment]
Just to recap-
1. Webpack 4 is not a v2 requirement and cant really be since frameworks like nextjs and gatsby are on their own webpack update schedule and havent updated to webpack 4
2. Exporting from index.js would everualky work only with webpack 4 (still untested)
3. You can not use the index.js exports in any docs or examples as they would not run in anything besides webpack 4

I realy dont see any advantage of exporting from index.js, just potential bugs if a user imports from there

**Comment by alansouzati** [comment]
here is the configuration we would recommend for webpack < v4. 

```
["transform-imports", {
      "grommet$": {
        "transform": "grommet/es6/components/${member}",
        "preventFullImport": true,
        "skipDefaultConversion": true
      },
      "grommet/contexts": {
        "transform": "grommet/es6/contexts/${member}",
        "preventFullImport": true,
        "skipDefaultConversion": true
      },
      "grommet/themes": {
        "transform": "grommet/es6/themes/${member}",
        "preventFullImport": true,
        "skipDefaultConversion": true
      },
      "grommet/components/hocs": {
        "transform": "grommet/es6/components/hocs",
        "preventFullImport": true,
        "skipDefaultConversion": true
      }
    }]
```

We have tested and tree shaking works as expected with the latest grommet and webpack v4, so no need for a plugin.
