### ISSUE TITLE
grommet.io is gone

### ISSUE THREAD

**Issue by jornncc** [grommet/grommet#2239]
### Expected Behavior

the grommet.io website is no longer available. 

### Actual Behavior

you end up on a 

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/15808559/44864419-740bb000-ac34-11e8-826a-84cb6e8d20eb.png)

![image](https://user-images.githubusercontent.com/15808559/44864825-78849880-ac35-11e8-85ff-7ae2969ffaee.png)
![image](https://user-images.githubusercontent.com/15808559/44864846-7faba680-ac35-11e8-9933-9f105512483e.png)

### Steps to Reproduce
 1. use your browser and navigate to grommet.io
 2. 
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by alansouzati** [comment]
Please use the grommet github url for now https://grommet.github.io/

We are investigating what is going on with our godaddy configuration

**Comment by jornncc** [comment]
Yep, was able to get the grommet-docs running locally... 

Tx 

Will use the new grommet.github.io/ url.
