### ISSUE TITLE
How do I disable SkipLinks?

### ISSUE THREAD

**Issue by mingfang** [grommet/grommet#224]

**Comment by mingfang** [comment]
Nevermind.
It disappears after I included the grommet.css file properly.
But I think I would still love to see some documentation on SkipLinks

**Comment by alansouzati** [comment]
Hi @mingfang, we do touch a little bit on accessibility in the website, including SkipLinks.

Please refer to this link for more information: http://grommet.io/docs/develop/accessibility

But I agree with you, the content could be more extensive. We would love to see a PR for an enhanced version of that.

**Comment by noahehall** [comment]
@mingfang can you add your code for including the css properly? 

I included the scss as described in the docs and the skiplinks are showing

**Comment by noahehall** [comment]
@mingfang thanks for looking, I ended up displaying none
