### ISSUE TITLE
v2 Box basis wrong propTypes

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2242]
the basis prop for Box can be any string (ex. basis='200px'), 
```
const basisStyle = css`
  flex-basis: ${props =>
    BASIS_MAP[props.basis] || props.theme.global.size[props.basis] || props.basis};
`;
```

however the Box propTypes limit it to to list of sizes
https://github.com/grommet/grommet/blob/1de06c31d0cee92cf65f512228c4d6f87f81bccb/src/js/components/Box/doc.js#L67
```
 basis: PropTypes.oneOf([
      'xxsmall', 'xsmall', 'small', 'medium', 'large', 'xlarge', 'full',
      '1/2', '1/3', '2/3', '1/4', '3/4', 'auto',
    ])
```

Now that the propTypes warnings started showing up, this gets a warning
![screenshot746](https://user-images.githubusercontent.com/6075606/44887963-ac46d900-ac9c-11e8-9723-7c0a33403c03.jpg)

**Comment by ericsoderberghp** [comment]
I believe this was fixed in https://github.com/grommet/grommet/pull/2263.
