### ISSUE TITLE
v2 Box pad sizes limited

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2243]
const PAD_SIZES = ['xsmall', 'small', 'medium', 'large', 'xlarge'];

https://github.com/grommet/grommet/blob/1de06c31d0cee92cf65f512228c4d6f87f81bccb/src/js/components/Box/doc.js#L5

however the base theme defines also 'xxsmall' and 'hair' as possible values (you might also want to allow for custom pad names as well ie '2px') 
https://github.com/grommet/grommet/blob/1de06c31d0cee92cf65f512228c4d6f87f81bccb/src/js/themes/base.js#L136

**Comment by ericsoderberghp** [comment]
Custom pad sizes were added with https://github.com/grommet/grommet/pull/2263.

**Comment by alansouzati** [comment]
I think this is more like `PAD_SIZES` is not including `xxsmall`
