### ISSUE TITLE
react-desc removes static props from components

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2244]
Seems a react-desc issue, but all v2 components are wrapped with doc now and their static props are removed (it used to be that the component without doc(xxx) was exported):

https://stackblitz.com/edit/grommet-demo-unxafm?file=index.js

**Comment by alansouzati** [comment]
what are the static props from grommet you are trying to access? A solution would be to add your static props after calling `doc`. Internally in grommet we don't export any static stuff apart from the propTypes and defaultProps that are actually added by react-desc.

here is how I would do it: https://stackblitz.com/edit/grommet-demo-k3d3dq?file=index.js

But in grommet we don't export any of that, this is where I'm getting confused.

**Comment by atanasster** [comment]
I was actually exporting my own static props ie `<Card.CardTitle />` and when it broke with the new changes, moved to after the doc call : https://github.com/atanasster/grommet-controls/blob/2ccf66989ce0972d71a65dd55b8cda534b9353a8/src/js/components/Card/Card.js#L125

So it works for me now, just making sure you are aware of it and if you decide to look for a solution.

**Comment by alansouzati** [comment]
I don't think there is a solution actually 😢 Unless manually choosing static props to transfer over. 
Glad to see you are using compound components though, it is a great pattern. Also, glad to hear you are leveraging react-desc in your grommet-controls lib!

I'm closing this for now. I will add a note to react-desc README warning about this.

**Comment by atanasster** [comment]
sounds good, adding some docs. I am trying to use much the same patterns like react-desc etc. in grommet-controls as in grommet, so users dont have to learn different things (and me neither :)). 

The two places I differ from grommet are the compound components and the folders naming (ie -> withFormFields in its own folder, as are other utilities like color palettes). Will probably move themes as well, to reduce configurations
