### ISSUE TITLE
v2 Diagram - connections thickness propTypes

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2245]
thickness accepts only 'hair', 'xxsmall', 'xsmall', 'small', 'medium', 'large'

https://github.com/grommet/grommet/blob/1de06c31d0cee92cf65f512228c4d6f87f81bccb/src/js/components/Diagram/doc.js#L22

However, I am using `thickness: '2',` (2 pixels is the best look for my use case)

**Comment by ericsoderberghp** [comment]
I believe this was fixed in https://github.com/grommet/grommet/pull/2086.
