### ISSUE TITLE
Form Field Arrow color 

### ISSUE THREAD

**Issue by britt6612** [grommet/grommet#2246]
When doing a form field in a box the display of the drop down arrow is purple from grommet when it should be the brand HPE green. I had to write a separate styles in order to change the color to the brand green.  

### Expected Behavior
The arrow in the form field should be the brand color green when displayed.
The HPE theme is imported so the colors should be portrayed on the display.

### Actual Behavior
The arrow in the form field is the color purple from grommet instead of green. 

### URL, screen shot, or Codepen exhibiting the issue
https://github.hpe.com/CI-Lab/hackathon-signup/tree/add-new-homepage/src

### Steps to Reproduce
 1. Made separate styles sheet just for the arrow color 
![screen shot 2018-08-31 at 10 45 06 am](https://user-images.githubusercontent.com/42451602/44931717-e1483f80-ad1f-11e8-8c95-812f55003e37.png)
<img width="309" alt="screen shot 2018-08-31 at 10 45 31 am" src="https://user-images.githubusercontent.com/42451602/44931721-e2796c80-ad1f-11e8-904c-f1bf7dfc95ba.png">

### Your Environment

* Grommet version: V2
* Browser Name and version: Chrome Version 68.0.3440.106
* Operating System and version (desktop or mobile): Desktop

**Comment by alansouzati** [comment]
Are you passing the HPE theme to the grommet component?

I've created this: https://codesandbox.io/s/2x6w4j0q00 and it has the HPE green.

I'm closing this since I believe nothing needs to be changed on our end. please feel free to reopen it if you think otherwise.
