### ISSUE TITLE
TextInput (delayed) suggestions bug

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2247]
Just tested latest NEXT and this one is still not fixed, so made a sample to reproduce

https://codesandbox.io/s/znzmjj6k8x

Type one letter - and the suggestions will not open (it takes longer to retrieve the suggestions from a REST API than the 10ms delay in the resetSuggestions). 

Also supplying showDrop as a prop to manually manage the suggestions open does not work, as only the this.state.showDrop is used.

**Comment by atanasster** [comment]
#2295 is mostly fixing this (its the same fix that I had been using and submitted 5-6 months ago but didn't get much traction) by calling resetSuggestions if the length of the suggestions has changed. 
This fix works in 90% of the cases (except if the length is the same, yet the suggestions have changed) and on my end I am fine with closing this issue.

**Comment by alansouzati** [comment]
I see. thanks! I forgot about this contribution from @taleschaves
