### ISSUE TITLE
Select search input on Safari iOS

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2250]
- on an iPad tablet, go to https://v2.grommet.io/select
- go to the onSearch property and click on the Select so its open for searching the options
- focus the search field - and it becomes with rounded corners (before focusing, the search input is with regular borders as per the theme)

![image-1](https://user-images.githubusercontent.com/6075606/44980410-cf43e800-af3d-11e8-9ee1-16973e6ebfd7.jpg)

**Comment by atanasster** [comment]
also notice the jumping around of the select options container if you scroll the page up/down while the keyboard is open
This entire issue is to be tested on Safari / iPad

**Comment by alansouzati** [comment]
I'm taking a look at this now

**Comment by atanasster** [comment]
@alansouzati , it might be the `-webkit-appearance: none;` replaced with `-webkit-appearance: textfield;` (this is how I fixed it on my side)
I also read that some browsers require a `webkit-border-radius` in addition to the `border-radius`
