### ISSUE TITLE
v2 - more responsive breakpoints

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2251]
The current narrow/wide breakpoints are not enough for a more elaborate app design. For example, it limits apps to just a few menu items. 

Here is an example of an app with a top menu with more items - when resized, there is a point when we would like to have just some of the menus visible : https://stackblitz.com/edit/grommet-demo-mps8pm?file=index.js

Try resizing from large to small screen

1. Full size menus, all visible
![screenshot747](https://user-images.githubusercontent.com/6075606/44981391-6a3dc180-af40-11e8-89b9-af3f11ed2648.jpg)

2. Medium size menus - we would like to have some visible but instead the screen is garbled since there is no breakpoint for such 'medium' size
![screenshot748](https://user-images.githubusercontent.com/6075606/44981403-6f9b0c00-af40-11e8-8b33-2df1f2694028.jpg)

3. Narrow size menus, 
![screenshot749](https://user-images.githubusercontent.com/6075606/44981407-7295fc80-af40-11e8-9b69-fbc6612a4e38.jpg)

**Comment by alansouzati** [comment]
I'm taking a look at this now.
