### ISSUE TITLE
Theme colors for AccordionPanel icons

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2257]
Some color combinations are not visible :

https://stackblitz.com/edit/grommet-demo-tumfin?file=index.js

![screenshot750](https://user-images.githubusercontent.com/6075606/45054408-e5939600-b05a-11e8-96b3-8775f0a725fb.jpg)

**Comment by alansouzati** [comment]
Hey I'm not sure if this is a problem in grommet since you are manually setting this colors right ? can you clarify?

**Comment by atanasster** [comment]
I am setting the background colors to ie brand, however its the arrow icon in `AccordionPanel` that is not visible. I think we should be able to place Accordion on any background.

**Comment by alansouzati** [comment]
Fair, yeah I feel we should fix this before v2.

**Comment by ericsoderberghp** [comment]
With the latest color changes, the `control` color can be set separately from the `brand` color. You could still set the background of a control to be the `control` color, but this would render the control coloring invisible. We aren't planning to add detection of that condition and falling back to another accessible color. We suggest theme creators and users should not use `control` as a background color.
