### ISSUE TITLE
Installation via Bower is broken.

### ISSUE THREAD

**Issue by Dinesh-Ramakrishnan** [grommet/grommet#226]
Installation via Bower is Broken, 
It used to work earlier, but now it is not. Please find the log below

`
$ bower install grommet
bower                            retry Request to https://bower.herokuapp.com/packages/grommet failed with ECONNRESET, r
etrying in 1.7s
bower                            retry Request to https://bower.herokuapp.com/packages/grommet failed with ECONNRESET, r
etrying in 3.4s
bower                            retry Request to https://bower.herokuapp.com/packages/grommet failed with ECONNRESET, r
etrying in 5.1s
bower                            retry Request to https://bower.herokuapp.com/packages/grommet failed with ECONNRESET, r
etrying in 9.5s
`

**Comment by alansouzati** [comment]
This seems like a proxy issue for me. Could you please make sure to add the proxy settings if you are inside a corporate network?

**Comment by bryanjacquot** [comment]
@Dinesh-Ramakrishnan is this still an issue?

**Comment by bryanjacquot** [comment]
Closing with no response.
