### ISSUE TITLE
Unable to "re"-style using styled-component's <ThemeProvider> component

### ISSUE THREAD

**Issue by mvilrokx** [grommet/grommet#2261]
Since Grommet is using styled-components, I am trying to use the <ThemeProvider> component [as per the styled-component documentation](https://www.styled-components.com/docs/advanced#theming) to access (and slightly modify) one of the the provided Grommet themes.

### Expected Behavior
When I wrap my custom component with styled-components <ThemeProvider> I should be able to access the theme in the component.

### Actual Behavior
The theme seems to be empty (`undefined`).

### URL, screen shot, or Codepen exhibiting the issue

```
import React from 'react';
import { Grommet } from 'grommet';
import { hpe } from 'grommet/themes';
import { ThemeProvider as StyledComponentsThemeProvider} from 'styled-components'

const overwriteFontSize = ({ theme }) => {
    console.log('theme', theme); // <=== undefined
    theme.global.font.size = 16 // <=== So this errors out
};

const ThemeProvider = ({ children, ...props }) => (
    <Grommet theme={hpe} {...props} >
        <StyledComponentsThemeProvider theme={overwriteFontSize}>
            {children}
        </StyledComponentsThemeProvider>
    </Grommet>
);
```

### Steps to Reproduce
 1. See code

### Your Environment

* Grommet version: 2.0.0-beta.5
* Browser Name and version: Chrome 68.0.3440.106 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): MacOS High Sierra 10.13.6

**Comment by atanasster** [comment]
@mvilrokx v2 uses its own ThemeContext, but here is how you can extend the theme context or extend globally the hpe with a `<Grommet />` component:

https://stackblitz.com/edit/grommet-demo-l8b7vo?file=index.js

**Comment by mvilrokx** [comment]
Awesome, that works!  

Thanks @atanasster.
