### ISSUE TITLE
V2. prop validation warning is misleading

### ISSUE THREAD

**Issue by srockk** [grommet/grommet#2262]
It used to accept and still accepting custom prop values, for example, width prop of Box. However, the latest version is now writing console warning of wrong prop value, which is confusing/misleading.

### Expected Behavior

Either accept or reject the custom prop value.

### Actual Behavior

Accepting the custom prop value and working fine, but spits out wrong prop warning.

### Steps to Reproduce
 1. Add custom prop value, like `mid-large: 400px` in theme file
 2. Pass it to `Box` like `<Box width='mid-large' />`
 3. It writes the console warning of wrong prop value, however, the fixed width of 400px works as intended(?).

### Your Environment

* Grommet version: The latest V.2
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by alansouzati** [comment]
Yeah I agree this is an issue. let me fix it now
