### ISSUE TITLE
v2 Box - missing basis 2/4

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2265]
There are basis 1/4 and 3/4, but basis 2/4 is missing and is not working (it should map to 50%)

![screenshot752](https://user-images.githubusercontent.com/6075606/45242252-4e7a4880-b2bd-11e8-9d75-4631df34b410.jpg)

https://stackblitz.com/edit/grommet-demo-h3qhyg?file=index.js

**Comment by ericsoderberghp** [comment]
Box does support `basis="1/2"`. Is that not sufficient?

**Comment by atanasster** [comment]
1/2 also translates to 50%, I meant when going by quarters - 1/4, 2/4, 1/4 - in this scenario 1/2 is not the natural way

**Comment by alansouzati** [comment]
FYI we are adding `2/4` which is an alias to `1/2`
