### ISSUE TITLE
Box width='XXXXpx' does not work anymore

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2277]
`<Box width='250px' />` 
The Box doc now accepts any string for the `width` prop, however this is prevented in StyledBox

https://github.com/grommet/grommet/blob/d3003d7627428fbc6ac6022d7928ecdb900f5e4f/src/js/components/Box/StyledBox.js#L336-L337

![screenshot758](https://user-images.githubusercontent.com/6075606/45551096-d9e26500-b7fa-11e8-83ca-eef6f2e4c3d4.jpg)

**Comment by aetagahmad911-gif** [comment]
2277
