### ISSUE TITLE
v2 Mixed usage of text color theme prop

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2280]
Background style function uses `global.text.color.light` and `global.text.color.dark`, but Anchor, Drop, Grommet, and Layer uses `global.colors.text`. I think we should use only one, and it seems it makes sense to use `global.text.color.light` and `global.text.color.dark`

**Comment by alansouzati** [comment]
since we already have a `text` component I feel the right place should be `global.colors['text-dark']` and `global.colors[text-light]` following the same pattern for border.

**Comment by ericsoderberghp** [comment]
I'm contemplating having `border` and `text` in `global.colors` take an object, similar to what we do for:
```
anchor: {
    color: {
        dark: '#6194EB',
        light: '#6194EB',
      },
}
```
