### ISSUE TITLE
v2 Layer responsive broken

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2281]
### Expected Behavior
Layer in mobile show content underneath 

### Actual Behavior

Layer you only show the layer container on mobile

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/kmkv4oo785

### Steps to Reproduce

Keep resizing the live preview and you will see the body text showing on mobile

### Your Environment

* Grommet version: v2 beta 5
* Browser Name and version: any
* Operating System and version (desktop or mobile): any

**Comment by ShimiSun** [comment]
@robinmetral did your commit fix it? because it looks well to me ![Screen Shot 2019-03-08 at 1 14 59 PM](https://user-images.githubusercontent.com/6320236/54053361-35871d00-41a4-11e9-98b8-d39572df83c7.png)

**Comment by robinmetral** [comment]
It did @ShimiSun :tada: 

It's not fullscreen anymore now though, changes a bit.
