### ISSUE TITLE
V2 themes - conflicting naming for responsive properties

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2285]
In the themes, there are default sizes which names would be conflicting with same names for responsive breakpoints (for example we can have breakpoint names ‘medium’ ‘large’ which conflict with the ie border size names)
```
borderSize: {
        xsmall: '1px',
        small: '2px',
        medium: `${baseSpacing / 6}px`, // 4
        large: `${baseSpacing / 2}px`, // 12
        xlarge: `${baseSpacing}px`, // 24
        narrow: {
            ....
         }
```
https://github.com/grommet/grommet/blob/d3003d7627428fbc6ac6022d7928ecdb900f5e4f/src/js/themes/base.js#L93

**Comment by alansouzati** [comment]
correct. my recommendation is to not use the same names for now.

I had a chat with @ericsoderberghp about this and our inclination is to move the `narrow` and responsive breakpoints stuff to the `breakpoints` prop.

This change would allow an easier path for themes to disable the auto adjustments on mobile. We have a case at Netflix where we don't want to change padding when we are in "narrow" mode. Today I'm having to browser different entries in the theme to see where I have to disable it.

**Comment by atanasster** [comment]
Yes, for now i switched to using other breakpoint names, but they are a bit weird
https://github.com/atanasster/grommet-controls/blob/master/src/js/themes/base.js
