### ISSUE TITLE
V2 grommet theme issues

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2286]
- anchor light and dark color properties
- accent and neutral colors should not re-use the brand color (or displaying them on top of brand makes them invisible)

https://github.com/atanasster/grommet-controls/blob/master/src/js/themes/grommet.js

**Comment by ericsoderberghp** [comment]
Related to https://github.com/grommet/grommet/issues/2287

**Comment by ericsoderberghp** [comment]
I believe this is covered by #2287
