### ISSUE TITLE
V2 dark theme issues

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2287]
- anchor light and dark color properties
- accent and neutral colors should not re-use the brand color (or displaying them on top of brand makes them invisible)
- neutral colors should be length of 5
- icon color should be darkish rather than whitish

https://github.com/atanasster/grommet-controls/blob/master/src/js/themes/dark.js

**Comment by ericsoderberghp** [comment]
Need to coordinate on accessible Anchor color on dark backgrounds. Current color #6194EB fails.

**Comment by alansouzati** [comment]
correct. I think Anchor on dark backgrounds is always staying the same color. see the Box stories for an example.
