### ISSUE TITLE
Option to turn on/off show password option for <PasswordInput />

### ISSUE THREAD

**Issue by junjchen** [grommet/grommet#2291]
This is a feature request. It would be nice if user can control the display of the little eye icon next to password input component for mocking/unmocking password.

I can go and make a PR if there is no objection

**Comment by alansouzati** [comment]
Sorry for taking a long time to get back to you on this. yes it makes sense to make a prop for that. PRs gladly appreciated

**Comment by oorestisime** [comment]
Hello,

i d like to give it a go unless @junjchen is already at it

**Comment by junjchen** [comment]
@oorestisime nope go ahead 😉

**Comment by alansouzati** [comment]
sorry to clarify is this for grommet v1 or v2? and the feature request is to disable show/hide password? because we already have the eye there in v1. in v2 we don't have a password input component

**Comment by junjchen** [comment]
Hi @alansouzati this is targeted at grommet v1. The feature request is to have an "enablePasswordVisibilityToggle" option to show/hide the "eye" button in the password input.

**Comment by oorestisime** [comment]
right i didnt understand this at the beginning! i dont use the v1 so am sorry i won't give it a go

**Comment by ShimiSun** [comment]
The grommet team is not planning to enhance v1. we are open to accept PRs if someone else is willing to contribute.
