### ISSUE TITLE
Warning: Failed prop type: Invalid prop `pad` supplied to `Box`.

### ISSUE THREAD

**Issue by djalmaaraujo** [grommet/grommet#2297]
### Expected Behavior

`pad` should still work as expected accepting 'none' for specific parts (top, bottom, left, right)

### Actual Behavior

`pad` is giving me invalid props when I use `top: 'none'`

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/3402/45757544-89647080-bc1b-11e8-9771-cc37c1a2c5f2.png)

### Steps to Reproduce
 1. Update to beta 6
 2. Use this `pad={{top: 'none', bottom: 'large'}}` in any <Box>

### Your Environment

* Grommet version: beta 6
* Browser Name and version: latest Chrome
* Operating System and version (desktop or mobile): macOs desktop

### How to fix? I am not sure

Maybe we should accept here: https://github.com/grommet/grommet/blob/NEXT/src/js/components/Box/doc.js#L134 'none' just like the line: https://github.com/grommet/grommet/blob/NEXT/src/js/components/Box/doc.js#L131

**Comment by srockk** [comment]
@djalmaaraujo isn't the default value `'non`'? You could do `pad={{ bottom: 'large' }}`.

**Comment by alansouzati** [comment]
I'm taking a look at this now.

**Comment by alansouzati** [comment]
Yeah I agree with @srockk the default is undefined, which does not add any padding to the elements. I'm closing the issue for now. We can reopen if we identify things we want to fix.
