### ISSUE TITLE
What is FormFields and is it deprecated?

### ISSUE THREAD

**Issue by gopher-boye** [grommet/grommet#2301]
I noticed that there is a FormFields component, but in the docs there is only FormField.

I was curious so I searched and the Ferret example is actually using FormFields.  Should this component even be used considering it is not listed in the docs, and also considering the Ferret code is from 2016?

Thanks

**Comment by atanasster** [comment]
FormFields is actually just adding a div with a class name `grommetux-form-fields` without any css props in the default themes. You could eventually use this class name to add your own css props, but you really don't need to use it.

**Comment by Rastopyr** [comment]
i'm sorry, but this is confused, when example on main website showing not really view of components. i mean `TextInput` component in `FormField`. this is related with some refactoring or last release? how community could help improve that? thanks!

**Comment by atanasster** [comment]
@Rastopyr - this thread is about `FormFields`, not `FormField`. Which example do you have in mind - https://grommet.io/docs/form-field/examples ?

**Comment by Rastopyr** [comment]
oh, my fault. sorry. i mean example with `TextInput`. i just include scss `grommet-core` to my project, but as i see this scss without this styles:

![](https://uc6782a6233814c131f30e4405d0.previews.dropboxusercontent.com/p/thumb/AAPIsyxY1GoGKoZeyUlRIOm86k8GajPYti08T-8h6QcbWenPcfaV1nsZ4dSSRyO46h2xegb-Z38AutUQNJ_qpCKnlacOtv1a9EOIZlubMvrFmG7G6_o0Eo0-9iKVRjQoBLuLQEuZCJCdMyh8sN47CytAMLcyfnI4s6RFw5yCZ-wpEz-jMCIwh_75qvCvbCSZv1eRa3XSD1jmwH2fIPaq7OxqQhcxX9aVOSs3nBkIRvmXZA/p.png?size=2048x1536&size_mode=3)

**Comment by Rastopyr** [comment]
@atanasster thanks for example. im not added `App` component to root of my app. my question is resolved. thank you so much!
