### ISSUE TITLE
v2 Tabs - aria-label object

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2303]
If the title of a tab is a custom node, the aria-label is incorrect
https://github.com/grommet/grommet/blob/9bd618833bf012eed7037b5925f3d1d41e6ee282/src/js/components/Tabs/Tabs.js#L57

example: https://stackblitz.com/edit/grommet-demo-lmkygf?file=index.js

![screenshot759](https://user-images.githubusercontent.com/6075606/45867458-3100b080-bd8c-11e8-88de-1c2bc4de1404.jpg)

**Comment by alansouzati** [comment]
I'm looking at this now
