### ISSUE TITLE
v2 Tab title prop allow any react node

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2304]
The default formatting of the Tab title as a string is not enough 

https://github.com/grommet/grommet/blob/9bd618833bf012eed7037b5925f3d1d41e6ee282/src/js/components/Tab/doc.js#L12

example use case:
https://stackblitz.com/edit/grommet-demo-lmkygf?file=index.js

**Comment by alansouzati** [comment]
I'm looking at this now
