### ISSUE TITLE
v2 Tabs - not responsive

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2305]
Currently if you have several Tabs and the screen is resized to narrow, the tabs will squeeze each other.

The Tabs direction should be a parameter to allow for `column` direction. By default it would be nice to be `row-responsive`

https://github.com/grommet/grommet/blob/9bd618833bf012eed7037b5925f3d1d41e6ee282/src/js/components/Tabs/Tabs.js#L71  

![screenshot760](https://user-images.githubusercontent.com/6075606/45912488-f568f380-be2a-11e8-96a3-e94ef0f663d7.jpg)

**Comment by alansouzati** [comment]
agreed.

I'm looking at this now.
