### ISSUE TITLE
Input with type 'password' prints password on console

### ISSUE THREAD

**Issue by Waize** [grommet/grommet#2306]
We are using the grommet login-from. With the newest Chrome-Update we are now getting our password printed on the console if we have it saved in the browser:
` [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"grommetux-password_1537780821741" value=​"###HIER COMES MY PASSWORD###">`

### Expected Behavior
Investigate weather to follow the linked instuctions.

### Steps to Reproduce
 1. use Login-Form or passwort-input
 2. save credentials in the browser
 3. refresh

### Your Environment

* Grommet version: 1.9.0
* Browser Name and version: newest chrome version
* Operating System and version (desktop or mobile): windows

Further I have the question why the login-form does not use your password-field-component?

**Comment by prateekgoel** [comment]
This is not an issue with grommet. This issue exists for any form.
This is a Chrome Browser bug.
https://bugs.chromium.org/p/chromium/issues/detail?id=889780#c6

**Comment by Waize** [comment]
> This is what Vadym's intern implemented. 

...jesus 
okay I will close this issue.
