### ISSUE TITLE
New Social Share Icon Request - GitHub

### ISSUE THREAD

**Issue by alexlee-dev** [grommet/grommet#2307]
Request to add a new Social Share Icon - GitHub.

**Comment by alansouzati** [comment]
We do have the Github icon

http://grommet.io/grommet-icons/?s=github

I'm closing this issue since I feel there is nothing to be changed on our side. we can always reopen if we feel there is something to be changed.

**Comment by alexlee-dev** [comment]
@alansouzati I apologize, I think I made this issue before I dug deeper and found the GitHub icon.
