### ISSUE TITLE
V2. Accordion - Assignment to read only properties is not allowed in strict mode on IE11

### ISSUE THREAD

**Issue by srockk** [grommet/grommet#2309]
### URL, screen shot, or Codepen exhibiting the issue
<img width="1316" alt="screen shot 2018-09-28 at 12 17 11 am" src="https://user-images.githubusercontent.com/8532807/46187923-27a7a480-c2b4-11e8-9463-cae6e1e1120e.png">

### Steps to Reproduce
 1. Go to Storybook. storybook.grommet.io
 2. Accordion -> Multiple
 3. Click the accordion panel

### Your Environment

* Grommet version: V2
* Browser Name and version: IE11
* Operating System and version (desktop or mobile): Desktop

**Comment by alansouzati** [comment]
I'm taking a look at this now
