### ISSUE TITLE
Select box styling in IE

### ISSUE THREAD

**Issue by AngusMackHPE** [grommet/grommet#231]
Is anyone else seeing this issue on (tested on IE11, Windows 8.1) where the system drop down arrow is also showing as well as the background image?

![image](https://cloud.githubusercontent.com/assets/14290536/10969194/a8c3e732-83be-11e5-8b87-a89c89fdd441.png)

Works fine in latest Chrome on Windows 8.1.

![image](https://cloud.githubusercontent.com/assets/14290536/10969251/f7fae080-83be-11e5-909d-b8530de930ac.png)

It seems the style is being applied from grommet/scss/grommet-core/_base.input.scss for the select element.

**Comment by ericsoderberghp** [comment]
I cannot reproduce the behavior on my IE11 for the select box on this page: http://www.grommet.io/docs/hpe/develop/form

**Comment by kylebyerly-hp** [comment]
Formfield explicitly has
```
.form-field select::-ms-expand {
      display: none;
    }
```
in `_objects.form.field.scss`. If you are not in a formfield you won't get this currently.
This could be globally changed/fixed in relation to https://github.com/grommet/grommet/issues/251 and all the IE overrides moved to `_base.input.scss`.

**Comment by ericsoderberghp** [comment]
Thanks @kylebyerly-hp. What we really need is a page in the grommet docs showing the base DOM elements so we can see how they are styled when outside of a Grommet context.

**Comment by AngusMackHPE** [comment]
I am using it outside FormField and had a chance yesterday to confirm this behaviour. And thank you for highlighting the CSS that needs applying to fix this. I will confirm it is fixed using this style.

**Comment by AngusMackHPE** [comment]
For my current project I was able to set the appropriate styling for my select boxes and it works fine in IE and Chrome now.
Thank you for the assistance.

**Comment by AngusMackHPE** [comment]
Was using this outside a formfield element. Using it inside one resolves this issue.
