### ISSUE TITLE
v2 Menu button to open and close needs hover/focus styles

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#2310]
The v2 Menu toggle button to open and close needs hover and focus styles for accessibility

### Expected Behavior

The toggle button should inherit the standard button behavior for hover and focus styles and/or be able to configure it.

### Actual Behavior

The toggle button does not have hover and focus styles.

### URL, screen shot, or Codepen exhibiting the issue
This can be seen in the v2 docs: https://v2.grommet.io/menu

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: 2.0.0-beta.5
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by alansouzati** [comment]
I'm not sure I agree with that. Take the native select for example, it does not have any hover indicator. Same for the Grommet Select, it does not have hover background.

We do have focus highlight if you press tab.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

@ericsoderberghp @L0ZZI I would appreciate your thoughts here.

**Comment by srallen** [comment]
Ah, so the intended behavior is to be like a select? It renders in the DOM as a button, not a select, so I was expecting hover/focus states like the other buttons. You are correct that there's a focus style applied when tabbing, but the button does not have a hover/focus styles if that state is forced in Chrome dev tools.

**Comment by alansouzati** [comment]
Sorry I was not clear on that.

I mean the Menu and the Select should behave the same way when it comes to the UX for this.

Both the Select and the Menu are being rendered as buttons (for accessibility reasons).

But there is no hover effect by default. You could definitely add it on your end though. But my concern is how to make that the default behavior. This is more like a design question I feel. How to give feedback to the users that the Menu and the Select is actually clickable. Usually I refer to the native behavior to get help. And when I look at the native Select, there is not feedback there. Do you see my point?

**Comment by srallen** [comment]
Yes, I understand now. I'm ok with the default to behave like Select as long as there is a way to customize it. Right now, the closed menu can be customized with targeted CSS, though it would be better if it could be done with props. The open menu is not customizable except for the props for setting its background color and alignment. It would be helpful if I could target styles for the inner Box for the open menu especially for the font color and padding in addition to being able to add hover and focus styles for the button.

**Comment by alansouzati** [comment]
If you have an example of a Menu elsewhere that does what you are looking for, pleas share with me. It will help me understand better what you are trying to achieve.

**Comment by srallen** [comment]
Ok I can put together a codesandbox and share here.

**Comment by srallen** [comment]
Here's a codesandbox example: https://codesandbox.io/s/m39k907669

I have a logged in user menu that I'd like to add some focus and hover styling to the menu button. I can add focus and hover styles to the individual button label components for the drop icon and the text label, but not the button either open or closed. Adding the hover and focus styles to the individual button label components isn't really a solution for a hover and focus state for the whole button.

I thought about trying to track the open and closed state with a callback for the onClick event, but adding an onClick prop to the Menu component breaks the event entirely. If I could track the open and closed state, then I could at least vary the button styles depending that state. I'm not sure if this a better solution than adding more props like `dropBackground` to specify specific open menu styles.

In the menu design, the open/close toggle button should stay black and the open menu's background is teal. I can't do this at all at the moment, though I might have flexibility with that (Designer might be ok with a teal button when open), but the text color should change to white on the teal for legibility.

**Comment by ShimiSun** [comment]
I believe this issue is fixed. Thank you for reporting!
