### ISSUE TITLE
ResponsiveContext does not work with SSR

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2311]
the first ResponsiveContext.Consumer call is with size = undefined. 
When rendering server-side, the page does not know if it will be displayed for mobile or desktop - some components are visible or hidden while they shouldnt be and then on the first client-side render, the page updates with the correct screen size

One possible solution is to use `User-Agent` and make an educated guess as to the screen size server-side so the initial render is correct.

**Comment by stelian87** [comment]
any solution here? i'm getting this when i'm trying to use PagingTable:

Cannot read property 'Consumer' of undefined
TypeError: Cannot read property 'Consumer' of undefined
    at PagingTable (node_modules/grommet-controls/es6/components/PagingTable/PagingTable.js:45:0)
    at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:13380:0)
    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:13820:0)
    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:15863:0)
    at workLoop (node_modules/react-dom/cjs/react-dom.development.js:15902:0)
    at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:15942:0)
    at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:16560:0)
    at performWork (node_modules/react-dom/cjs/react-dom.development.js:16482:0)
    at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:16454:0)
    at requestWork (node_modules/react-dom/cjs/react-dom.development.js:16354:0)

**Comment by atanasster** [comment]
@stelian87 i think your issue is more about mismatched versions - you can clean up your node_modules and delete package.lock file and the install latest grommet and grommet-controls

**Comment by oorestisime** [comment]
I am not sure it is grommet job to make the educated guess on the breakpoint to use. OTOH may i suggest to add the ability for the user to set the breakpoint ? Doing so will be up to the user to guess the breakpoint and just pass it to the context.

**Comment by atanasster** [comment]
React responsibe libs are usually dealing with ssr breakpoints, not sure why you think its not grommet’s job to also deal with it - can you please elaborate?

**Comment by atanasster** [comment]
Byw, here is a lib for screen detection based on User Agent https://github.com/hgoebl/mobile-detect.js

**Comment by oorestisime** [comment]
Well actually i thought it was natural that UIs didn't mess with that. dont know why but i had a quick look and it you are right!

**Comment by oorestisime** [comment]
i d'like to give this a go! seems interesting.

**Comment by atanasster** [comment]
Fantastic let me know if you need any help with the code or testing it

**Comment by oorestisime** [comment]
i don't have a project with SSR to test it but shouldn't be hard to create one, i guess. thanks!

**Comment by atanasster** [comment]
The easiest might be start a new nextjs sample project or use one of my GitHub nextjs/grommet sample projects

**Comment by oorestisime** [comment]
So after some digging and talking i undestood that i need to make the educated guess in the Grommet component https://github.com/grommet/grommet/blob/master/src/js/components/Grommet/Grommet.js#L116 in order to pass the guess down to the Responsive provider.

My idea was to let user pass a the request or UA directly in the props. Maybe there is a better way to do it?

**Comment by atanasster** [comment]
A Grommet prop could be one way, possibly also have a SSRContext, where the user supplies the Provider and Grommet uses the Consumer part. Possibly the upcoming react-hooks could also be used to implement it in a functional way but haven't investigated that much

**Comment by oorestisime** [comment]
Another thing to consider here, the mobile detect library helps finding out if the ua is a mobile or a tablet or.. 
the problem is that we don't really know the width of the device with it. getting the breakpoint from that information would then not be entirely accurate. should ti be like a default width for mobile, tablet and desktop devices?

**Comment by atanasster** [comment]
We can use something like the bootstrap breakpoints sizes: 

Phones - less than 768px
Tablets - 768px to 992px
Desktops - 992px to 1200px
Large Desktops - 1200px and Up

**Comment by oorestisime** [comment]
Forgot to add this in the commit. but should be closed.

**Comment by chrischen** [comment]
Is there any way to disable this so that mobile-detect doesn't get included? As you can see here it is contributing 6.9% of the total bundle size of *all* of grommet: https://bundlephobia.com/result?p=grommet@2.5.5

**Comment by oorestisime** [comment]
Can you open an issue for that? there is currently no way to do this but it seems to a valid use case.
