### ISSUE TITLE
Calendar component needs a 'size' attribute

### ISSUE THREAD

**Issue by shaiksphere** [grommet/grommet#232]
Currently, the 'Calendar' component is of fixed size and becomes disproportionate to the enclosing UI.

An attribute, such as 'size' would greatly help in making sure the component fits well with it's neighbours.

**Comment by ericsoderberghp** [comment]
Currently, the Calendar drop down aligns its width to the form field context it is in. Could you elaborate a bit more on what you mean by "disproportionate"?

**Comment by bryanjacquot** [comment]
@shaiksphere any response to @ericsoderberghp question?

**Comment by shaiksphere** [comment]
@bryanjacquot: I am no longer with HPE, so I no longer have any visibility in the same. Since I am the reporter of this issue, I would like to **close** this issue.
