### ISSUE TITLE
v2 [TypeScript] More accurate typings

### ISSUE THREAD

**Issue by dennari** [grommet/grommet#2325]
While playing around with v2 and TypeScript, I ran into the following problem:
```typescript
import { TextInput } from 'grommet';

type Handler = React.KeyboardEventHandler<HTMLInputElement>;
const handler: Handler = ({key}) => console.log(key); 
const Input = () => <TextInput onKeyUp={handler} /> // <-- TypeScript complains here
```
The problem is that the `onKeyUp` property is not included in the typings. Looking at the code, if not for the typings, I believe this would actually work as intended: [TextInput.js#L338](https://github.com/grommet/grommet/blob/NEXT/src/js/components/TextInput/TextInput.js#L338).

This is definitely a broader problem: the typings should extend the typings for the appropriate html element, in this case probably `input`.  That would take care of all the attributes you assume you should be able to set for e.g. `TextInput`.

**Comment by atanasster** [comment]
Just from my point of view, but the typings wrappers alone will never give a full typescript experience.  Maybe just document them as being a bit incomplete until a future time when grommet could(if) be rewritten in ts.

**Comment by alansouzati** [comment]
yeah. We should have a wiki page for Typescript support and describe what we did, how it is not complete, and our plan to improve it.

**Comment by jpdesigndev** [comment]
@atanasster I'm new to TS, but, as a library consumer, the full TS experience should be possible/desirable right? Are you speaking from a library author perspective? If the former, as long as the full API is typed, there should be nothing about the experience that is different. After all, don't TS projects simply export a `.d.ts` file when packaging for npm anyways?

**Comment by atanasster** [comment]
@jpdesigndev i meant that the full api to be typed (both for consumers and writers), the components need to be written in typescript. Currently there is only a wrapper around propTypes, which is a good start, but will probably always have flaws and be incomplete. For reference, you can check the ant-design typescript code for their input component

**Comment by hc-12** [comment]
I too have stumbled into this problem when using `TextInput`. 

The fix for this particular case, I just need to extend or intersect with `IntrinsicElements['input']`. This would need to be done for the rest of the components that grommet extends from.

```typescript
declare const TextInput: React.ComponentType<TextInputProps & JSX.IntrinsicElements['input']>;
```

**Comment by alansouzati** [comment]
Thanks for the suggestion @hc-12. I will work on extending our definitions with the intrinsic elements

**Comment by hc-12** [comment]
We also need to account for certain components that accepts a `tag` prop. Where `tag` is `keyof JSX.IntrinsicElements`. Which ideally have a default of `div` or `span` depending on the component.

**Comment by alansouzati** [comment]
i think this is related. let's keep in the same issue. but feel free to open a new one if you prefer.

**Comment by aach** [comment]
> I too have stumbled into this problem when using `TextInput`.
> 
> The fix for this particular case, I just need to extend or intersect with `IntrinsicElements['input']`. This would need to be done for the rest of the components that grommet extends from.
> 
> ```ts
> declare const TextInput: React.ComponentType<TextInputProps & JSX.IntrinsicElements['input']>;
> ```

typescript newbie here 🙋‍♂️
how can i achieve the same in my project? where do i have to put that definition?
thanks

**Comment by hc-12** [comment]
@aach 

In typescript you can merge your own declaration with other declaration such as the libary's declaration.

```typescript
// extend-grommet.d.ts
import {TextInputProps} from 'grommet';

declare module 'grommet' {
   // extend your types in here
   declare const TextInput: React.ComponentType<TextInputProps & JSX.IntrinsicElements['input']>;  
}
```

You can save this in say `<rootPath>/types`. Then include in your `tsconfig.json`:

```json
{
  ...,
  "include": ["src", "__tests__", "types/**/*.ts"]
}
```

There are some limitation on what you can merge: https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by aach** [comment]
@hc-12 Thanks for the explanation!
