### ISSUE TITLE
% Width scaling of charts does not work properly anymore

### ISSUE THREAD

**Issue by abenson337** [grommet/grommet#233]
I am using a modified css file with different sizes for chart rendering, and using 100% width to span the charts to the full width of their containers and now with the most recent changes (Some time this month) the charts are not being scaled properly.

Instead of the true width of the SVG being 100% width in PX, its a static width, and its just stretching the width of the chart instead.

None of the charts have a true width so now the circles and all other shapes are skewed.

![image](https://cloud.githubusercontent.com/assets/13318415/11002369/f476fa30-8471-11e5-939a-4301b96c0d11.png)

This was working fine before some more recent changes, when the width of the container expands, the true pixel width of the SVG area was widened.

**Comment by abenson337** [comment]
It works properly in the bower compiled .3.7 but every version after that its not working.

https://github.com/grommet/grommet-bower/blob/3b537f0118de5ca1d8ae79e9060885dafd0145d8/grommet.js (Valid and working)

**Comment by ericsoderberghp** [comment]
@abenson337: Can you give me a simplified HTML + CSS snippet that illustrates the issue? I'm not seeing the issue here: http://www.grommet.io/docs/hpe/develop/chart
because the Chart is auto-sizing itself to its container's width. I'm wondering why it isn't auto-sizing to fill the container in your case.

**Comment by abenson337** [comment]
From my modified grommet.css =>

.chart__graphic {
    width: 100%;
    height: 192px;
    max-height: calc(100vh - 144px); }
.chart--small .chart__graphic {
    height: 128px; }
  .chart--large .chart__graphic {
    height: 256px; }

From my actual content.css (from the page its displayed from)

.content-right
{
	float: left;
	min-width: 320px;
	width: calc(100% - 230px);
}

content-right is inside of some other containers but that is the inner most container that controls the width of the chart.

**Comment by abenson337** [comment]
*updated info in previous commment*

**Comment by bryanjacquot** [comment]
@abenson337 if you're still having issues, please create a CodePen illustrating the issue.  This one can be used at a starting point if you'd like: http://www.grommet.io/docs/develop/hello-world

**Comment by bryanjacquot** [comment]
Closing for now.  Let us know if this is still an issue.
