### ISSUE TITLE
Split `hpe` theme into a separate repository

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#2337]
To reinforce the open-source-ness of grommet with respect to themeing, we plan to move the `hpe` theme outside of the core `grommet` repository, probably something like `grommet-theme-hpe`.

**Comment by ericsoderberghp** [comment]
I've added https://github.com/grommet/grommet-theme-hpe for this.

**Comment by alansouzati** [comment]
The repo looks good to me. I thought I saw a PR for this. I think we can create it now since it will be a breaking change.
