### ISSUE TITLE
Storybook is broken in ie11

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#2339]
storybook.grommet.io fails on IE11 with:
`Object doesn't support property or method 'assign'`

I can't find any instance of `assign` in the grommet code base, perhaps it is an issue with storybook?

**Comment by ShimiSun** [comment]
I was able to run storybook in IE11 well

![image](https://user-images.githubusercontent.com/6320236/50712131-9328ad00-102d-11e9-9ddd-f15cf2bc5e2f.png)
