### ISSUE TITLE
Layer and context

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#234]
If you pass some Container with redux store or other context into Layer it seams context is not properly passed trough Layer to Container container even router does not seam to work. 
Anyone else had this problem?
Cheers

Versions:
"grommet": "0.4.0",
"react": "0.14.1",
"react-dom": "0.14.1",
"react-router": "1.0.0-rc4", or "react-router": "1.0.0-rc3",

**Comment by ericsoderberghp** [comment]
@primozs: How is the redux store being put into the context in the first place?  Any "router" and "intl" in the context should be getting passed through, via line #31 here: https://github.com/grommet/grommet/blob/master/src/js/components/Layer.js

**Comment by primozs** [comment]
@ericsoderberghp Hello,
Store is being set by Provider. 

```
let appEl = document.getElementById('app');
ReactDOM.render(
  <div>
    <Provider store={store}>
      <IntlProvider locale={'en'} messages={localeData}>
        <Router routes={routes} history={history}/>
      </IntlProvider>
    </Provider>
    {renderDevTools(store)}
  </div>, appEl);
```

The same container receives state if I don't wrap it with Layer container as a child.

```
// like this MainSidebar receives redux state
var sidebar = (
      <MainSidebar primary={true} onClose={this._onCloseSidebar}/>
    );

// like this it does not
var sidebar = (
      <Layer align="left" flush={true} onClose={this._onCloseSidebar}>
        <MainSidebar primary={true} onClose={this._onCloseSidebar}/>
      </Layer>
    );
```

**Comment by ericsoderberghp** [comment]
@primozs: Got it. Thanks. The trick is how to have the Layer know which context properties to transfer across. I think it's doable though.

**Comment by primozs** [comment]
@ericsoderberghp I did not check why `intl` and `router` is being explicitly set in Layer context but if I understand correctly it should be automatic. Is it possible that context settings in Layer are overwriting the rest of the context?

**Comment by ericsoderberghp** [comment]
@primozs the context transfer is indeed automatic as long as you remain within the DOM component hierarchy of the top level render(). The Grommet Layer has to break out of that hierarchy in order to create a separate root/layer in the DOM and thus has to explicitly transfer child context objects.

I've submitted a change to Layer to transfer the 'store' child context across. I'm hoping this will work for you now while we continue investigating better approaches.

**Comment by primozs** [comment]
@ericsoderberghp Thank you, I will try it out.

**Comment by primozs** [comment]
@ericsoderberghp I have tried the stable branch and now Component is no longer complaining about state and context, so this seams to be ok. "Routers history" on the other hand is somehow not working.
In this component that I am using as a child of Layer, i am importing Link
```
import { Link } from 'react-router';
```
it is the same issue as before, if my component is not a child of Layer it works other wise on the clikck of Link I get this error:
```
Cannot read property 'pushState' of undefined
```
it seams that with the router in context maybe there should be also history object.

**Comment by primozs** [comment]
@ericsoderberghp I have added the history object to Layer and LayerContents context and it works. 
History object is now required by router.

**Comment by ericsoderberghp** [comment]
@primozs Would you be willing to submit a pull request for your history changes?

**Comment by primozs** [comment]
@ericsoderberghp I have created pull request but from master branch. Is this ok? How is stable branch being generated currently?

**Comment by alansouzati** [comment]
Stable branch gets updated as soon as changes are merged successfully to Grommet master repository.

In your case, as soon as your PR is approved and passes the CI build it will be automatically moved to the stable branch.

**Comment by primozs** [comment]
Thank You, Cheers

**Comment by ido-ran** [comment]
Hi,
I've run into the same issue of context not been transfer into child component.
Hardcode the context properties does not cut it because we are using proprietary properties.
I'm working around this issue by passing the context from the component that create the Layer using props but that is exactly what context should prevent.
