### ISSUE TITLE
Calendar cannot reset after start selection

### ISSUE THREAD

**Issue by taleschaves** [grommet/grommet#2348]
### Expected Behavior
Calendar allow a reset (an idea would be to click in the same date to unselect it)

### Actual Behavior

Once you start selecting dates with range it is impossible to reset it

### Steps to Reproduce
 1. https://storybook.grommet.io/?selectedKind=Calendar&selectedStory=Range%20Calendar&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel 
 2. Select a range
 3. Try to start a new range
 4. The latest date keeps increasing instead of reset the range selection

### Your Environment

* Grommet version: v2 beta.6
* Browser Name and version: any
* Operating System and version (desktop or mobile): any

**Comment by ericsoderberghp** [comment]
Yep. I just bumped into this yesterday myself.

**Comment by ericsoderberghp** [comment]
So, it turns out this is really in the caller's control. If the user selects the date that was already selected, `onSelect` will still be called and the caller can unset `date` if desired.

**Comment by alansouzati** [comment]
can we add an example of that in storybook? I will try do that.
