### ISSUE TITLE
Box elevation bug

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2361]
### Expected Behavior
Box adds elevation with dark and light mode correctly

### Actual Behavior
Box is adding a dark background when it is supposed to add a light background

### URL, screen shot, or Codepen exhibiting the issue

Here is a codesandbox where this problems shows up: https://codesandbox.io/s/5yk2rn1kvn.
Initally I thought that the elevation was not being added, but if you inspect it is actually there, but with white in color.

To test, I've forced the non-dark mode and it works:

https://codesandbox.io/s/ym7o6kv1yz

### Steps to Reproduce
 1. Open the first codesandbox link
 2. Notice the elevation prop being passed
 3. Elevation is not added in the preview when it should

### Your Environment

* Grommet version: v.2.0.0-beta.7
* Browser Name and version: any
* Operating System and version (desktop or mobile): any

**Comment by d3dc** [comment]
@ericsoderberghp This bug is back in the codesandbox and my code, afaict: https://storybook.grommet.io/?selectedKind=Box&selectedStory=Elevation

**Comment by ericsoderberghp** [comment]
Agreed.
