### ISSUE TITLE
Need smoke tests as part of CI/CD to ensure sample apps and grommet site don't break

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet#2362]
Multiple times in the past month the website has been down and it wasn't until the community (or me) noticed and reported it that we knew.  We need something in our CI/CD pipeline to ensure this is caught and rolled back.

![screen shot 2018-10-17 at 9 29 28 am](https://user-images.githubusercontent.com/6393696/47097681-2997c000-d1ef-11e8-84b6-4430fe2ebe26.png)

### Expected Behavior

The site shouldn't break.

### Actual Behavior

The site breaks and we don't know about it.

### URL, screen shot, or Codepen exhibiting the issue
One example:

![screen shot 2018-10-17 at 9 31 17 am](https://user-images.githubusercontent.com/6393696/47097837-6cf22e80-d1ef-11e8-8d9a-3c2982e9d7bb.png)

### Steps to Reproduce
 1.  Visit the site.

**Comment by ericsoderberghp** [comment]
This should be an issue for `grommet-site`, not `grommet`. FYI, the latest issue stems from problems with the `monaco-editor` we are using for the playground.

**Comment by ericsoderberghp** [comment]
This has been replaced by https://github.com/grommet/grommet-site/issues/40
