### ISSUE TITLE
v2 ResponsiveContent doesn't work with 2.0.0-beta.7

### ISSUE THREAD

**Issue by kmorf** [grommet/grommet#2368]
### Steps to Reproduce
 1. See [working example](https://stackblitz.com/edit/grommet-demo-mps8pm?file=package.json)
 2. Works with grommet `2.0.0-beta.5` and `2.0.0-beta.6`
 3. Doesn't work with `2.0.0-beta.7`

### Your Environment

* Grommet version: 2.0.0-beta.7
* Browser Name and version: Chrome 69.0.3497.100
* Operating System and version (desktop or mobile): macOS 10.14

**Comment by ericsoderberghp** [comment]
In the [release notes for 2.0.0-beta.7](https://github.com/grommet/grommet/releases/tag/v2.0.0-beta.7) we mention that responsive context name `wide` has been removed. We now have `small`, `medium`, and `large` by default. I recommend replacing `=== 'wide'` with `!== 'small'`.
