### ISSUE TITLE
Font-family for specific heading levels

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2370]
### Expected Behavior
Today a different font-family is allowed, but it affects all heading levels

### Actual Behavior

Grommet allows an entry in the theme that let us change the font-family for each level. For example, adding a different font just for h1.

**Comment by oorestisime** [comment]
hello i was having a look here today to understand better the theme process. if i get this right, to do this the base theme should support a font-family for each level here https://github.com/grommet/grommet/blob/master/src/js/themes/base.js#L478-L500 and then modify StyledHeading to take them into account? and fallback to global theme heading if the values are not configured?

**Comment by ericsoderberghp** [comment]
That sounds about right.

**Comment by alansouzati** [comment]
wow. I really like your proactiveness @oorestisime

**Comment by oorestisime** [comment]
Sorry forgot to close this from commit. but i think it is done
