### ISSUE TITLE
DropButton showing warning when clicked - invalid prop align of value [Object object]

### ISSUE THREAD

**Issue by taleschaves** [grommet/grommet#2375]
DropButton is throwing a warning when clicked.

### Expected Behavior
No warnings.

### Steps to Reproduce
 1. https://codesandbox.io/s/3yn88vvxm6

### Your Environment

* Grommet version: v2.0.0-beta7
* Browser Name and version: chrome (latest)
* Operating System and version (desktop or mobile): desktop

**Comment by ericsoderberghp** [comment]
Thanks. This was fixed post beta-7 in https://github.com/grommet/grommet/pull/2369.
