### ISSUE TITLE
Add direction and reverse to Tab

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2378]
It would be great if we could change the way we render tabs. Today we always render the header horizontally. It would be great to have the tabs on the left or right side (with reverse).

**Comment by nomadus** [comment]
I wonder, why menu component is not being used in tabs. This could solve this issue. Any thoughts why we can't use menu component?

**Comment by alansouzati** [comment]
Why you think using Menu would solve this problem? Initially they seem unrelated. But maybe I’m missing something.

**Comment by nomadus** [comment]
I checked, Menu component has a direction property, which could be a row or column.  I also check how it is done here, they seem to be using a menu component. https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Tab/Tab.js

**Comment by nomadus** [comment]
For only vertical case, would this be a valid code?






`// (C) Copyright 2014-2016 Hewlett Packard Enterprise Development LP

import React, { Component } from 'react';

import CSSClassnames from 'grommet/utils/CSSClassnames';
import Intl from 'grommet/utils/Intl';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import Menu from 'grommet/components/Menu';
import Anchor from 'grommet/components/Anchor';
import Box from 'grommet/components/Box';


const CLASS_ROOT = CSSClassnames.TABS;

export default class Tabs extends Component {

    constructor(props, context) {
        super(props, context);

        this._activateTab = this._activateTab.bind(this);

        this.state = {
            activeIndex: props.activeIndex || 0,
            justify: props.justify
        };
    }

    componentWillReceiveProps(nextProps) {
        if ((nextProps.activeIndex || 0 === nextProps.activeIndex) &&
            this.state.activeIndex !== nextProps.activeIndex) {
            this.setState({ activeIndex: nextProps.activeIndex });
        }
    }

    _activateTab(index) {
        if (!this.props.hasOwnProperty('activeIndex')) {
            this.setState({ activeIndex: index });
        }
        if (this.props.onActive) {
            this.props.onActive(index);
        }
    }

    render() {
        const { children, className, justify, responsive, ...props } = this.props;
        delete props.activeIndex;
        delete props.onActive;
        const { activeIndex } = this.state;
        const { intl } = this.context;
        const classes = classnames(
            CLASS_ROOT,
            {
                [`${CLASS_ROOT}--justify-${justify}`]: justify,
                [`${CLASS_ROOT}--responsive`]: responsive
            },
            className
        );

        let activeContainer;
        let activeTitle;
        const tabs = React.Children.map(children, (tab, index) => {
            if (!tab) return null;

            const tabProps = tab.props || tab._store.props || {};

            const isTabActive = index === activeIndex;

            if (isTabActive) {
                activeContainer = tabProps.children;
                activeTitle = tabProps.title;
            }

            return React.cloneElement(tab, {
                active: isTabActive,
                id: `tab-${index}`,
                onRequestForActive: () => {
                    this._activateTab(index);
                }
            });
        }, this);

        const links = React.Children.map(children, (tab, index) => {
            if (!tab) return null;

            const tabProps = tab.props || tab._store.props || {};

            const isTabActive = index === activeIndex;

            return (
                <Anchor
                    href='#'
                    className={isTabActive ? 'active' : ''}
                    onClick={() => this.setState({ activeIndex: index })}>
                    {tabProps.title}
                </Anchor>
            )
        });

        const tabContentTitle = Intl.getMessage(intl, 'Tab Contents', {
            activeTitle: activeTitle
        });

        return (
            <Box
                direction='row'>
                <Box
                    basis='small'>
                    <Menu
                        primary={true}
                        pad={{ vertical: 'medium' }}
                        align='center'
                        justify='center'
                    >
                        {links}
                    </Menu>
                </Box>
                <Box
                    basis='full'>
                    <div aria-label={tabContentTitle} role='tabpanel'>
                        {activeContainer}
                    </div>
                </Box>
            </Box>
        );
    }
}

Tabs.propTypes = {
    activeIndex: PropTypes.number,
    justify: PropTypes.oneOf(['start', 'center', 'end']),
    responsive: PropTypes.bool,
    onActive: PropTypes.func
};

Tabs.contextTypes = {
    intl: PropTypes.object
};

Tabs.defaultProps = {
    justify: 'center',
    responsive: true
};`

**Comment by ShimiSun** [comment]
The `reverse` prop is already available https://v2.grommet.io/tabs#reverse

**Comment by MikeWalrath** [comment]
Closing this issue for the time being. If there is more interest or a larger need in the future we will look to reopen.
