### ISSUE TITLE
callback for Meter's hover state

### ISSUE THREAD

**Issue by thiagoc7** [grommet/grommet#238]
Hi, do you have any plan for this feature?

Or do you accept a PR with suggestions?

**Comment by alansouzati** [comment]
Hey @thiagoc7, this is an interesting question. Can you please provide us with an example where the callback for the Meter's hover is going to be used?

And yes, we definitely accept PR. But I would like first to understand where this is going to be applied.

If we apply that to the Meter, that would be good to explore other components that might need this feature as well.

**Comment by thiagoc7** [comment]
One example would be filtering the todos when you hover over the status arc.
In this case, we just need a callback with the `getLabel()` result that originated the arc.

**Comment by alansouzati** [comment]
What if you use the `onClick` callback instead of the `hover`? 

If you rely on the hover state for actions, how you make that work in a mobile device? Also, how you guarantee that people with disabilities will use your system to the fullest extent?

Another aspect that worries me is: while you are just moving the mouse around and accidentally hover over the meter paths, the UI starts reacting to it. I wonder if this is a good practice in terms of user experience.

**Comment by thiagoc7** [comment]
you are right... we could use `onPress`, and abstract both `onClick` and `onTouch...` events.

**Comment by alansouzati** [comment]
Awesome, I like the `onPress` idea :+1:

**Comment by thiagoc7** [comment]
The `Meter` component is very complex, so I think It would be better if I wait for your call before touching the code.

Maybe in a future version you could think about a set of charts where we have a main `chart container`, and the elements are just regular `children`.
This could open the framework for more UX complexity. Like, I could trigger the `onPress` event from another component, or when same rule is achieved.

It's just ideas... the most important is that you could abstract all the complexity of the charts, and created an amazing library! Thanks again!

**Comment by ericsoderberghp** [comment]
FYI, the new Chart components have broken things out to child components. http://grommet.github.io/docs/chart

**Comment by ericsoderberghp** [comment]
We need to add `onActive` to the Meter documentation.

**Comment by ericsoderberghp** [comment]
Added onActive to Meter documentation as part of 372395c4c824f27994ce6b49e59192deaa2a799a.
