### ISSUE TITLE
Layer no animation out

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2387]
### Expected Behavior

Layer animates in and out

### Actual Behavior

Layer animates in but not out. Since we unmount it immediately it does not animate out.

### Steps to Reproduce
 1. Open storybook for layer
 2. see the layer animates when it opens
 3. layer does not animate when it closes

### Your Environment

* Grommet version: v2.0.0-rc
* Browser Name and version: any
* Operating System and version (desktop or mobile): any

**Comment by karatechops** [comment]
This approach feels very grommet-y especially considering Layer already is using a keyframe animation - https://codesandbox.io/s/1rx7m8px3q

**Comment by djm158** [comment]
I'd love to take point on adding this, I can just do something along the lines of what collapsible does?

**Comment by ShimiSun** [comment]
Thanks @djm158! Go for it! I think that a solution along the lines of how the animation-in is working, will be more consistent

**Comment by ShimiSun** [comment]
Next release will include animation out 🚀
