### ISSUE TITLE
Auto-formatting for grommet core

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2389]
When we save our files we should have an auto formatter to avoid to manually organizing it.

Related to https://github.com/grommet/grommet/issues/2342 since we need to describe it for external contributors.

probably we want to add a pre-commit that will apply the pre-format automatically.

**Comment by oorestisime** [comment]
i might be missing something here, but there is already a prettier pre-commit, It was added recently. so this issue might be outdated

**Comment by alansouzati** [comment]
yes this is fixed. good call
