### ISSUE TITLE
Menu Icon inside drop disappears

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2392]
### Expected Behavior
Menu Icon shows up on white background on drop.

### Actual Behavior

Menu Icon has the same color as drop background.

### Steps to Reproduce
 1. open https://v2.grommet.io/play
 2. open the menu in the header
 3. see the menu disappears once you open it.

### Your Environment

* Grommet version: v2.0.0-beta.7
* Browser Name and version: any
* Operating System and version (desktop or mobile): any

**Comment by ericsoderberghp** [comment]
That looks like a background color context issue. The icon is there, it's just white.

**Comment by alansouzati** [comment]
agreed. I knew the icon is there. but we need to switch the color automatically if the background is white.

**Comment by ericsoderberghp** [comment]
Well, I'm not sure what we can do here. In the example referenced, the color for the icon is being explicitly set to 'white'. That seems to indicate the caller wants to control the color, so we will abide by that. If the color was not set on the icon, then the icon would automatically toggle color based on the background color context.

We have a few options here already:
1) don't overlap the control with the drop content, via `dropAlign`
2) set a background color that aligns more closely with the background color of the Menu, via `dropBackground`
3) don't specify a color on the icon

**Comment by alansouzati** [comment]
Let me try this out

**Comment by alansouzati** [comment]
yes you are right.
