### ISSUE TITLE
Question: How to make Grommet V2 components look like Grommet V1?

### ISSUE THREAD

**Issue by joelgetaction** [grommet/grommet#2393]
### Expected Behavior

I would like to make component X in Grommet V2 look exactly like component X in Grommet V1.  This should be relatively easy to do.

### Actual Behavior

It's not obvious how to make a Grommet V2 component look like its corresponding Grommet V1 component.

### Steps to Reproduce
 1. Load Grommet V1 component X.
 2. Load Grommet V2 component X.
 3. Visually compare them.  They don't look the same.

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

First, thanks for all of your hard work on Grommet!  It is really awesome and I appreciate your hard work.  :-)

I strongly prefer the visual style of Grommet V1 to that of V2.  V1 just looks way more professional / clean / elegant in my (non-designer eye) so I would prefer the V1 styling.  However, I'm hesitant to use V1 on a new greenfield project for fear that I'll be "left behind" or that V1 won't be supported going forward.  I'm fine with the new developer API in V2.

So is there a relatively easy way to use V2 but have component X in V2 look as close as possible to component X in V1?

Or is there relatively little risk to still using V1 and I should still use that?

Please advise and I'd be happy to add a PR to an FAQ or README if there's desire.

Thanks again!

**Comment by alansouzati** [comment]
Thanks for raising this issue. This is a great start.

V2 core is now meant to offer low-level abstractions to help you create design systems. This is different than v1 in essence. So overall, we're not looking to offer a 1:1 mapping here.

That said, I understand where you are coming from when you are asking from v1 components that are not in v2. And having a documentation (or video, or anything really) is definitely desirable.

I have that in my short list of things to do. But our storybook has a bunch of examples on how to customize Grommet v2. That would be my first starting point.

https://storybook.grommet.io

Can you please provide here a few components that you would like to see as a reference?

I can create a codesandbox illustrating it.

**Comment by joelgetaction** [comment]
Thanks @alansouzati I really appreciate your response.

I don't think it's so much that I wanted components from V1 that are missing in V2, but more like for components like Button or TextInput that are in both V1 and V2, I thought the V1 versions looked much better style wise and aesthetically.  Like V1 just looked prettier and classier in my opinion.

For all of the V2 components that are also in V1 (e.g. Button, TextInput etc) is there a way to create a default "skin/theme" that makes those components look exactly like they did in V1?  That would allow us to adapt the newer/netter API of V2 without any visible changes in component appearance.

Does that make sense or do you want me to add more specific component examples, which I'd be happy to do!

Thanks again.

**Comment by ericsoderberghp** [comment]
We've added `grommet-theme-v1`. So far, this covers Button and the various input based components. Any other needs should probably be tracked via issues in that repository.
