### ISSUE TITLE
UIs are very bouncy in IE11

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#240]
Using IE11 you see a very bouncy UI. You can see this throughout the docs. Perhaps most noticeable on Form.

It takes about 1.7 seconds for the rather noticeable bouncing of the UI to be done with IE11 on http://www.grommet.io/docs/hpe/develop/form

**Comment by kylebyerly-hp** [comment]
Here's a big video -> low color gif so you can see the behavior. Gif is a 5 second loop.
![form-bouncing-20-loop](https://cloud.githubusercontent.com/assets/13527666/11050144/a219be3a-8700-11e5-9ce3-9c9d10eabf4c.gif)

**Comment by ericsoderberghp** [comment]
This is the dreaded Flash of Unstyled Text:

**Comment by kylebyerly-hp** [comment]
Hmm. Curiously it looks like if you dev locally (either dist w/ server or dev) the flash is non-existent after the first load. And way less on first load. Which does support the fonts slowing things down.

**Comment by bryanjacquot** [comment]
The alternative would be to load CSS and fonts synchronously forcing the page render to wait for the CSS (specifically for fonts).  This raises other issues, so we're going to close this  without change for now.
