### ISSUE TITLE
Font Changes affected tabs component

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2403]
### Expected Behavior

switching tabs affects panel height

### Actual Behavior

switching tabs should not affect its height

### Steps to Reproduce
 1. Open https://storybook.grommet.io/?selectedKind=Tabs&selectedStory=Uncontrolled%20Tabs&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
 2. Notice that switching tabs moves the text
 3. 

### Your Environment

* Grommet version: v2.0.0 (stable branch)
* Browser Name and version: any
* Operating System and version (desktop or mobile): any

**Comment by alansouzati** [comment]
it seems it affected anchor as well. FYI @ericsoderberghp

**Comment by ericsoderberghp** [comment]
I can't seem to reproduce this after the latest font-family changes. I've tried in Safari, Firefox, or Chrome. At least, the comment indicates that the height is jumping. The width of the tab does change when we switch the font between normal and bold.

**Comment by alansouzati** [comment]
yeah this is what I meant.

Look at this: https://grommet.io/docs/tabs

the transition between the font weight is way more smooth there.

Do we know why the transition is not smooth with the new font family ? Is that at all related?

**Comment by ericsoderberghp** [comment]
We aren't changing the font-weight in v1, only the color. Perhaps we should switch back to that behavior?

**Comment by alansouzati** [comment]
i like that better.

**Comment by alansouzati** [comment]
anyways I feel this is fine to be done after v2 release. removing the tag.

**Comment by ericsoderberghp** [comment]
@L0ZZI and I discussed and agreed that the jumpiness wasn't good. We came up with an alternate way of doing it. In working on that, I've found some issues in theming Tabs that I've fixed.
