### ISSUE TITLE
Update documentation for TextArea to include onInput

### ISSUE THREAD

**Issue by DrewEdwards** [grommet/grommet#2412]
Update the documentation to show that `onInput` is a valid prop for `TextArea`. 

This can be a little confusing, since `TextArea` accepts a `value` prop, but it's not immediately clear from the documentation how to implement `TextArea` as a controlled component. 

Thanks for all the great work on Grommet!

**Comment by ericsoderberghp** [comment]
FYI, we're actually updating it to use `onChange`.
