### ISSUE TITLE
Remove border from Select when in focus

### ISSUE THREAD

**Issue by pstauskas** [grommet/grommet#2413]
When I am focused on a Select, the immediate div within the Button still has a border + radius, which is visible "beneath" the box-shadow.

### Expected Behavior
Either the border should be removed, or made transparent when in the focused state

### Actual Behavior
The border and it's radius is visible, creating uneccessary visual noise.

### URL, screen shot, or Codepen exhibiting the issue

![screen shot 2018-11-02 at 2 56 02 pm](https://user-images.githubusercontent.com/18468451/47942519-7944df80-deaf-11e8-85d9-6e2a085cde5f.png)

### Steps to Reproduce
 1. Focus on a Select component 

### Your Environment
* Grommet version: v2.0.0-rc
* Browser Name and version: Any
* Operating System and version (desktop or mobile): Any

**Comment by dwevedivaibhav** [comment]
When I am focused on a Select, the immediate div within the Button still has a box-shadow, which is not able to customize (I am not able to overwrite ,its seems to me value in box shadow property hard coded ,its not taking as parameter).Please suggest me.

**Comment by JCole45** [comment]
Sorry, but how do we apply the solution, please?

**Comment by ShimiSun** [comment]
I'm AFK, but a quick idea to try is to override its boxshadow value from the extend option of the select theme.
