### ISSUE TITLE
Input fields bounce up and down as user edits or selects in IE11

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#242]
If you edit text in a input field it bounces up and down as you type.

It also bounces as you select or deselect (in an inconsistent manner). The gif below exhibits the behavior.

![input-bounce-loop](https://cloud.githubusercontent.com/assets/13527666/11050001/98fbda3c-86ff-11e5-9548-1fa5a96dd03f.gif)

**Comment by ericsoderberghp** [comment]
This is only an issue with IE11. Cannot reproduce on Edge 13.

**Comment by ericsoderberghp** [comment]
Fixed in bc9e4baaad0f4ad37a4828cc0163ccba1e2b3eac.
