### ISSUE TITLE
Grommet [v2] - Warning: Unsafe lifecycle methods were found within a strict-mode tree

### ISSUE THREAD

**Issue by hc-12** [grommet/grommet#2420]
Grommet v2 still uses unsafe lifecycle methods such as:
- componentWill*
- findDOMNode (since React 16.6)

Warning will appear under `StrictMode`.

### Expected Behavior
Should not be using unsafe lifecycle methods.

### Actual Behavior
Currently using lifecyle methods.

### Steps to Reproduce
 1. Turn on React strictmode 
 2. Look in console for warnings

### Your Environment

* Grommet version: 2
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): N/A

**Comment by alansouzati** [comment]
we will be soon removing this and switching to the hooks approach. We will delay this fix until we are on 16.7.

**Comment by ShimiSun** [comment]
componentWillUnmount is OK. we removed all other componentWill*.
findDOMNode is still being used in Infinite scroll, see #2600 .

**Comment by nateq314** [comment]
Any progress on this? `Select` is still causing `Warning: findDOMNode is deprecated in StrictMode.` with a long stack trace to appear in dev console.

**Comment by bsdis** [comment]
I am getting the same error/warning here by just running the example in the docs:
https://v2.grommet.io/datatable in an app created using npx create-react-app myapp --template typescript
Strange that this still seems to be an issue since this ticket was opnened 1.5 years ago

**Comment by ShimiSun** [comment]
Hi @bsdis @nateq314, we improved the behavior and you can feel free to verify it works as you expected by pointing grommet to its stable branch `https://github.com/grommet/grommet/tarball/stable` on your package.json

**Comment by RobertoSnap** [comment]
Tested this as im experiencing the same with the select component.

After setting latest stable as @ShimiSun referenced I now get a different message:

`DOM.js:182 Uncaught TypeError: target.getBoundingClientRect is not a function
    at isNodeBeforeScroll (DOM.js:182)
    at InfiniteScroll.js:156
isNodeBeforeScroll @ DOM.js:182
(anonymous) @ InfiniteScroll.js:156
setTimeout (async)
(anonymous) @ InfiniteScroll.js:151
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164`

**Comment by ericsoderberghp** [comment]
@RobertoSnap can you provide some code, either inline or via code sandbox, that illustrates the issue? I'm not able to reproduce the problem with any of the grommet storybook stories: https://storybook.grommet.io/?path=/story/select--simple

**Comment by RobertoSnap** [comment]
Have a sandbox here, but couldn't get Codesandbox to take GitHub link as a dependency. 

I can test it again in the next update. Or do you know how to get GitHub link as a dependency in Codesandbox? (Google didn't know either)

**Comment by ShimiSun** [comment]
I was able to reproduce the problem on Select storybook, by opening the Select drop https://storybook.grommet.io/?path=/story/select--simple
![image](https://user-images.githubusercontent.com/6320236/78720380-d46bd480-78e2-11ea-93a0-5d8bd0b718ef.png)

**Comment by nateq314** [comment]
@ShimiSun  Tried `stable` branch as you suggest and confirm that the `findDOMNode` warning is gone. Thanks!

**Comment by nateq314** [comment]
What's the current status on this?

**Comment by jcfilben** [comment]
I believe this issue has been fixed. Grommet no longer uses unsafe lifecycle methods such as `componentWill...` or `findDOMNode`.
