### ISSUE TITLE
v2 Stack: option to disable tab index interaction

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2425]
It would be nice to tell Stack to disable tab for children under the stacked elements.

**Comment by alansouzati** [comment]
it would be just like Layer with modal true. when we open our layer to content behind the layer looses focus.

**Comment by ericsoderberghp** [comment]
Can you provide a real-world example where this issue arises? I'm concerned that it may be hard for us to know which layer in the Stack is the one the user should be able to interact with.

**Comment by alansouzati** [comment]
always the latest will be the one to interact with.

An example is a form that is not allowed to be edited until you log in (or while it is loading data from the backend). so you could use a stack on top of this form where you can login and then the stack disappears and you can edit the form. 

This was an issue in a given use case at work and I was hoping stack would have a solution for this.

**Comment by ShimiSun** [comment]
on `interactiveChild` prop we will remove the focus on all the none interactive childs.

**Comment by ShimiSun** [comment]
I think we can close this issue since `[interactiveChild](https://v2.grommet.io/stack#interactiveChild)` prop is addressing the request.
