### ISSUE TITLE
v2 Select: optionally tell Drop within select to respect the width of the main Select target

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2428]
Today if the content inside the Drop is bigger than the Target, the drop will expand. it would be nice to have a way to tell the Drop to wrap and fix position so that the Select options are always aligned to the end of the target.

**Comment by mikerhyssmith** [comment]
Definitely not ideal, but the solution I resolved to using for this was to get the dimensions of the target element and set the max width with the style prop `{{maxWidth: inputTarget.clientWidth}}`. Definitely not ideal but it seems to work for the moment :man_shrugging:

**Comment by IanKBovard** [comment]
Taking a look at this issue
