### ISSUE TITLE
Status.Warning does not have a square viewbox 

### ISSUE THREAD

**Issue by Plonk42** [grommet/grommet#243]
On [Warning.js, l.25](https://github.com/grommet/grommet/blob/54a850ba909f34e51bf8ee6327539f97d5eb5afc/src/js/components/icons/status/Warning.js#L25), we have: ```viewBox="0 0 27 24"``` (notice the '27'). In all other status icons, we have ```viewBox="0 0 24 24"```.

This has been introduced in [370d4a3e](https://github.com/grommet/grommet/commit/370d4a3eae0e270325b09abc320848b64991dc59#diff-42a2b13a77753bc7b94ed43a7e013b27), where the square viewBox has been replaced by a non-square one:
```diff
-      <svg className={className} viewBox="0 0 384 384" version="1.1">
+      <svg className={className} viewBox="0 0 27 24" version="1.1">
```

Is that expected?

**Comment by ericsoderberghp** [comment]
Thanks for catching this. It is fixed in b145b40379a4cf2362ac5be2bbf97faa6ed5b082.
