### ISSUE TITLE
v2 TextInput shows text in left-hand corner of screen when using suggestions

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet#2439]
### Expected Behavior

Suggestions should not show text when focusing

### Actual Behavior

When focusing on a suggestion field, text is shown in the left-hand corner of screen indicating how many suggestions there are (see screenshot)

I suspect this is Grommet's A11y functionality, but also expect that this text would not be visible to sighted users (correct me if i'm wrong).  I am seeing this happen on OneSphere, but it's been intermittent and I'm not sure how exactly to reproduce it.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/13810084/48232635-418ed980-e380-11e8-8a1f-21187523bdd1.png)

### Steps to Reproduce
 1. Use suggestion field (TextInput) with a list of suggestion
 2. Focus on the field
 3. See that the texts shows in top left corner of screen

### Your Environment

* Grommet version: https://github.com/grommet/grommet.git#173fe04b37980287261aac6e32a1555d8974ad05
* Browser Name and version: Chrome - latest
* Operating System and version (desktop or mobile): MacOS latest

**Comment by ericsoderberghp** [comment]
This looks related to the AnnounceContext, which places an offscreen div that screen readers can access. I can't reproduce getting a browser to show this visually. Can you create a CodePen demonstrating the issue?

**Comment by RyanCCollins** [comment]
@ericsoderberghp I'm actually not sure entirely how to reproduce it at this time.  As I said, we've been seeing it intermittently.  Next time I see it, I will see if I can nail down the root cause so that I can reproduce it for you.

**Comment by RyanCCollins** [comment]
Here is another screen shot.  I think this happens because the grommet AnnounceContext code is interacting with the intercom library in OneSphere.  I will try to reproduce in a code sandbox when I get the time.

You can see the result in the screenshot below.  The announcer node gets attached to the intercom node and the styles break.

![screen shot 2018-11-09 at 12 58 59 pm](https://user-images.githubusercontent.com/13810084/48279706-65edc300-e41f-11e8-8de7-3b0900e4d2c0.png)

**Comment by RyanCCollins** [comment]
The cause of this bug seems to be the fact that OneSphere appends the `#intercom-container` adjacent to the main node.  I think the grommet code finds this node and puts the update text in it.  The CSS overlaps and we end up seeing the text that should be seen only by a screenreader.  We will likely patch this in OneSphere, but should probably keep this open since others will run into it.  

We could probably figure out a better way to append the aria-live content to the dom so that this doesn't happen in the future.  Now that I know how this works, let me try to create an example.

**Comment by RyanCCollins** [comment]
I came up with an example for this:
[Code Sandbox](https://codesandbox.io/s/oq657wn116)
[Live Example](https://oq657wn116.codesandbox.io/textinput)

Try filtering down the suggestion list and you will see the announcer come up.  The issue is that the CSS to hide the aria-live region is being overwritten by libraries we are using.  I suspect this could happen with other libraries and I'm not sure how we could fix it considering the code comes from a library.  I think Grommet could handle this better to avoid this.

**Comment by RyanCCollins** [comment]
I suppose this issue is caused by our library usage in OneSphere.  I will close it.  Feel free to reopen if this is found to be an issue elsewhere.
