### ISSUE TITLE
v2 Markdown page broken link

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet#2441]
### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
1) which link? Can you provide a URL?
2) How is it broken?
2) I suspect this issue belongs on `grommet-site`.

**Comment by MikeWalrath** [comment]
Apologies for the delay. This issue should be in grommet-site. I will close and re-open in grommet-site with the appropriate info.
