### ISSUE TITLE
Sparklines are 300px wide in IE11 and 49px wide in chrome/firefox

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#245]
Sparklines are 
49 wide in firefox and chrome
300 wide in IE11

chrome
![image](https://cloud.githubusercontent.com/assets/13527666/11077904/b196387e-87bf-11e5-8cad-264957e4b7c2.png)

IE11
![image](https://cloud.githubusercontent.com/assets/13527666/11077891/9d1751b2-87bf-11e5-858a-13e4e999d61d.png)

**Comment by ericsoderberghp** [comment]
This has been verified as fixed in the new Chart components.
