### ISSUE TITLE
How to get light colors?

### ISSUE THREAD

**Issue by florianbepunkt** [grommet/grommet#2454]
In recent past I could get all colors of hpe theme as defined in https://v2.grommet.io/color like this
hpe.global.colors['light-1']

How can the value for the light color definitions be accessed?

### Expected Behavior
hpe.global.colors['brand'] works and returns the brand color specified in the theme
hpe.global.colors['light-1'] should also work and return the light-1 color

### Actual Behavior
hpe.global.colors['light-1'] is not defined anymore… but the values are still there somewhere, since using <Box background="light-1" /> works .

hpe.global.colors returns

```
accent-1: "#2AD2C9"
accent-2: "#614767"
accent-3: "#ff8d6d"
brand: "#01a982"
focus: "#2AD2C9"
neutral-1: "#425563"
neutral-2: "#5F7A76"
neutral-3: "#80746E"
neutral-4: "#767676"
status-critical: "#F04953"
status-disabled: "#CCCCCC"
status-error: "#F04953"
status-ok: "#01a982"
status-unknown: "#CCCCCC"
status-warning: "#FFD144"
```

### Steps to Reproduce
import { hpe } from 'grommet-theme-hpe';
console.log(hpe.global.colors['light-1']);

### Your Environment

- Grommet version: 2.0.1

**Comment by alansouzati** [comment]
hey colors are merged with the [base](https://github.com/grommet/grommet/blob/master/src/js/themes/base.js#L42) themes always. 

HPE does not customize light colors, instead it just relies on the base colors coming from grommet. so in your case you can import the base theme instead.

`import { base } from "grommet";` then `base['light-1']` should be there.

if you access to the theme you can use `normalizeColor`.

Check this [codesandbox](https://codesandbox.io/s/vrm24q1q5)
