### ISSUE TITLE
Drop PR2444 set maxHeight

### ISSUE THREAD

**Issue by florianbepunkt** [grommet/grommet#2455]
#2444 introduced some unintended effects. the drop content gets squashed by the max-height property. Consider for example a FAB button that opens a context menu in a drop. the max height of the drop is set related to the button which in this case makes no sense.

### Expected Behavior
Drop itself should not set maxHeight or there should be an option to override

### Actual Behavior
It's a bit tricy to explain… I prepared the most simple code sandbox I could come up with. Try to toggle the text amount / free space with the labeled button and open the context menu with the FAB button.

https://codesandbox.io/s/8yz337xnm9

**Comment by ShimiSun** [comment]
thanks for filing the issue and being patient with the response :)

After adding more entries to the context menu and seeing the squashed behavior, I sort of agree with with the fact it considers the layout and putting a limit, but I also agree that we might want to provide a way to override it in case it is not the desired behavior.
@ericsoderberghp, I'd like to know what you think here, would the right solution from our end is to provide a way to override the `maxHeight` value?

**Comment by ericsoderberghp** [comment]
We cannot reproduce this anymore after updating to the latest version of grommet.

**Comment by florianbepunkt** [comment]
This has been fixed in latest version of grommet. Closing.
