### ISSUE TITLE
styled compoenet version

### ISSUE THREAD

**Issue by cefleet** [grommet/grommet#2459]
### Actual Behavior
Instead of rendering the page it throws an error:
"Uncaught TypeError: Cannot set property 'left' of undefined"

The error is on line 87 of DropContainer.js
It appears as the container object has no attribute "style" and errors out.

Grommet version 2.0.1
React 16.4
Styled-Component 3.4.10

**Comment by cefleet** [comment]
And upgrading to Styled-Component to 4.0.1 fixed the issue.
Closing.

**Comment by kristiandelay** [comment]
https://v2.grommet.io/use
starting a fresh app using the npm install -g grommet-cli & grommet new [app-name] caused a warning and would not load the page.

WARNING in ./node_modules/grommet/es6/contexts/ThemeContext/ThemeContext.js 6:0-12
"export 'ThemeContext' was not found in 'styled-components'
 @ ./node_modules/grommet/es6/contexts/ThemeContext/index.js
 @ ./node_modules/grommet/es6/contexts/index.js
 @ ./node_modules/grommet/es6/index.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

 i had to also upgrade to the latest style components to fix this issue.

Seems like styled components needs to be updated in grommet.

**Comment by ShimiSun** [comment]
@kristiandelay, you are commenting on a closed issue from 3 years ago. could you file a new one with more details. Can you try a fresh clone with only running `npm install`?
