### ISSUE TITLE
Tables are not selectable in IE11

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#246]
Table rows cannot be selected in IE11, either multi-select or single select. The single select table cat at least be initialized with a selected row, as in http://localhost:8002/docs/hpe/develop/distribution

**Comment by Candy374** [comment]
I got this issue too... and actually, the **selected** returns the column index instead of the row index, you can see it in the official page:  http://www.grommet.io/docs/hpe/develop/table

**Comment by ericsoderberghp** [comment]
Fixed in 6d60aaef64332d57d02041735461b2e897f3bd56.
