### ISSUE TITLE
<Anchor> and React Router v5

### ISSUE THREAD

**Issue by uyouthe** [grommet/grommet#2463]
Supporting react-router is crucial.

Recalling #576, we have an [old solution](https://github.com/grommet/grommet/issues/576#issuecomment-250023675) that doesn't work anymore, and [simpler solution](https://github.com/grommet/grommet/issues/576#issuecomment-277503053) which works but produces some warnings:
```JS
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
```

This warning is only appears in Grommet v2. As we can see, @benshell makes Anchor a `span` with `tag` attribute:

```JS
<Link to={props.to}>
    <Anchor tag="span" primary={props.primary}>{props.children}</Anchor>
</Link>
```

It worked flawlessly in v1, but for v2 the `tag` prop is gone.

So how I supposed to combine these two links: one from react router and another one from Grommet v2?

**Comment by alansouzati** [comment]
We  have a component called `<RoutedAnchor />` which is undocumented as of now unfortunately.

You can do `<RoutedAnchor path={props.to} {...props} />` and I think it will be equivalent.

I agree that v2 Anchor should support a `tag` prop regardless. This is a good first issue for a pull request.

**Comment by oorestisime** [comment]
Hey,
i'd like to give this a go. i am not really familiar with the codebase but it is something i need so i'd love to contribute back to grommet.

**Comment by alansouzati** [comment]
Join our slack channel https://slackin.grommet.io. Ping me and I will guide you on that

**Comment by oorestisime** [comment]
So i was looking to do this and i am wondering if using `<Anchor as="span" primary={props.primary}>{props.children}</Anchor>` would work for you.

Rationale:

Rendering the Anchor is looking as the following:

```
<StyledAnchor
        {...rest}
        ref={forwardRef}
        aria-label={a11yTitle}
        colorProp={color}
        disabled={disabled}
        hasIcon={!!icon}
>
...
```

`StyledAnchor` is a styled component and using the as polymorphic property normally you can modify the DOM directly https://www.styled-components.com/docs/api#as-polymorphic-prop

since grommet forwards rest it should work. 

I unit-tested this and have the following tree (without css classes)

```
exports[`renders tag 1`] = `
<div
  className="c0"
>
  <span
    className="c1"
    href="#"
    onBlur={[Function]}
    onFocus={[Function]}
  >
    Test
  </span>
</div>
`;
```

which seems to respond to your issue.

**Comment by oorestisime** [comment]
@alansouzati if you still want i could add a tag property to the Anchor component (if this would be more user friendly etc)

**Comment by uyouthe** [comment]
@oorestisime I'd rather go with RoutedAnchor I guess

**Comment by alansouzati** [comment]
hey @oorestisime I like the idea of being explicit about this. So I'm in favor of adding `as` to our list of documented props in Anchor even though we honor and pass it through.

**Comment by alansouzati** [comment]
btw great job identifying this is already supported.
