### ISSUE TITLE
TS Definitions should not make all object props required

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet#2464]
When using Grommet with TypeScript, I found an issue.  When you use Object type properties, all of the properties will be required.

For example:
```
        <Box
          direction="row"
          justify="between"
          align="center"
          width="xlarge"
          alignSelf="center"
          pad={{ vertical: 'medium', horizontal: 'small' }}
        >
```
complains the following:
```
/Users/ryancollins/Developer/blog/src/components/Navigation/index.tsx
(18,11): Type '{ vertical: string; horizontal: string; }' is not assignable to type 'string | { bottom: string; horizontal: string; left: string; right: string; top: string; vertical: string; } | undefined'.
  Type '{ vertical: string; horizontal: string; }' is not assignable to type '{ bottom: string; horizontal: string; left: string; right: string; top: string; vertical: string; }'.
    Property 'bottom' is missing in type '{ vertical: string; horizontal: string; }'.
```

### Expected Behavior
I would expect that only required props are required, even on objects.

### Actual Behavior
When using an object as a Prop for a grommet component, all the properties are required.

### URL, screen shot, or Codepen exhibiting the issue
N/A

### Steps to Reproduce
Use grommet in a TypeScript app and try to provide only one or two properties to a prop that takes an object.

### Your Environment

- Grommet version: Latest
- Browser Name and version: N/A
- Operating System and version (desktop or mobile): N/A

**Comment by RyanCCollins** [comment]
If @alansouzati will spare a few minutes this week, I might be able to solve this.  I dug into the generator code, but need some help reverse engineering.

**Comment by alansouzati** [comment]
Let me work on updating our CONTRIBUTING.md and take it from there

**Comment by alexwine36** [comment]
There also seems to be an issue with the generator writing true and false to "true" and "false"

If you need any help please let me know
