### ISSUE TITLE
Allow to set font weight in global theme config

### ISSUE THREAD

**Issue by franzwilding** [grommet/grommet#2472]
### Expected Behavior

When I set: 
```
global: {
  font: {
    weight: 500
  }
}
```

in my theme, the default `font-weight` css attribute should be set for all components. 

### Actual Behavior

Only css attributes for font-size and font–family are set, but not font-weight.

###
Grommet v2

**Comment by alansouzati** [comment]
I agree with this. I will leave this up for a couple of days since it is a great first issue for a pull request.

**Comment by ShimiSun** [comment]
https://github.com/grommet/grommet/pull/2473
PR is filed, thanks for your feedback!
