### ISSUE TITLE
List itemDirection="column" in IE11 has a broken layout

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#248]
In IE11 the Layout as column looks like this

![image](https://cloud.githubusercontent.com/assets/13527666/11078699/d6f026e8-87c4-11e5-981d-5ceedf415fbe.png)

**Comment by ericsoderberghp** [comment]
Cannot reproduce on Edge 13.

**Comment by ericsoderberghp** [comment]
Cannot reproduce on IE11.
