### ISSUE TITLE
No toast?

### ISSUE THREAD

**Issue by uyouthe** [grommet/grommet#2482]
Is there a way of alerting users? Toast from v1 was just nice, do we have something similar in v2? Just can't see anything alike in the doc

**Comment by alansouzati** [comment]
have you seen the Notification example in storybook ?

https://storybook.grommet.io/?selectedKind=Layer&selectedStory=Notification&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by uyouthe** [comment]
@alansouzati checked again just now – it doesn't work on iOS Safari

**Comment by alansouzati** [comment]
![64e730d6-c6ac-46a5-ba94-3d52af5d5334](https://user-images.githubusercontent.com/1207250/49103277-bb074280-f22f-11e8-9c31-362cea674298.png)

Interesting it works for me

**Comment by alansouzati** [comment]
anyways I'm closing this issue since I believe we will not be adding Toast as a core component. let's keep the conversation going regardless. we can always reopen if we feel something needs to be changed.

**Comment by uyouthe** [comment]
iPhone SE, iOS 12.1. I press the button but nothing shows up

**Comment by uyouthe** [comment]
nvm it's just showing up below the viewport. But I still can't see it, the page doesn't scroll down there, I literally should push it below the edge to see it. But maybe that's a storybook issue
![fullsizeoutput_8b](https://user-images.githubusercontent.com/14220138/49114229-c185d080-f2a8-11e8-81f9-15a8ee668190.jpeg)

**Comment by alansouzati** [comment]
yup yup this is a storybook issue :(
