### ISSUE TITLE
Use as property of Styled Components to change DOM instead of tag

### ISSUE THREAD

**Issue by oorestisime** [grommet/grommet#2487]
Following PRs #2481 and #2478 it seems better to modify existing implementations of the `tag` property to be aligned with the `as` property of Styled Components. From a quick look this would affect the following components:

* Text
* Heading
* Box
* Grid

It will also introduce a breaking change so it might be better to 

* proxy `tag` props to `as`
* document tag as deprecated (might even warn on usage?) to remove it in future versions

### Expected Behavior

Use `as` to modify the DOM tag of a component

### Actual Behavior

Use `tag` to modify the DOM tag of a component

**Comment by ericsoderberghp** [comment]
Agreed. Removing `tag` would be a breaking change. So, I'm in favor of deprecating `tag` and using `as` going forward.

**Comment by oorestisime** [comment]
Should there be a warning when somebody uses the deprecated `tag` property? I am not sure how you handle deprecations so please let me know :)
And do you prefer a PR that covers all components or separate ones?

**Comment by alansouzati** [comment]
I would leave this up to you @oorestisime. Whatever feels more convenient to you. 

Regarding the deprecation notice you can follow the pattern in [here](https://github.com/grommet/grommet/blob/aeef3c884a5a7c7671f7c7e94ab97a1630fdd1d0/src/js/components/Select/doc.js#L125)

it is basically a comment in our docs. we can make it formal later. to proxy is not heavy so I'm ok living with that for a while.
