### ISSUE TITLE
SyntaxInput proposal

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#2495]
This is a proposal for a new component in grommet version 2. The purpose of the component is to simplify the experience of adding text data that requires a certain syntax, such as IP addresses, data and time strings, etc.

Some notable aspects:
- The caller would specify a `schema` describing the available syntax.
- A placeholder will be generated if one isn't provided.
- The user could tab between input segments.
- The user does not have to type the separator characters but they will be allowed to if they want to.
- Any options would be rendered as a drop down when the user is interacting with a particular segment.
- The user could paste an entire value and it will be coerced into the schema if possible.

Here is an example of using the component to capture a time value:
```
<SyntaxInput
  schema={[
    {
      length: 2,
      options: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
      placeholder: 'hh',
    },
    { separator: ':' },
    {
      length: 2,
      options: ['00', '15', '30', '45'],
      placeholder: 'mm',
    },
    { separator: ' ' },
    {
      length: 2,
      options: ['am', 'pm'],
      placeholder: 'ap',
    }
  ]}
  value={value}
  onChange={this.onChange}
/>
```

Please let us know if this is of interest and any feedback you might have.

**Comment by alansouzati** [comment]
Could this be used to enter a credit card info? I saw one app the other day where I would enter all my credit card data in one line.

First I would enter the card digits and there would be a space between each 4 numbers (that I see as one syntaxinput). I'm not sure if the separator here can be a space.

As I blur out of that input, they shorten it to have only the last 4 digits plus the card type icon (visa, master, ..).

Next would be the month year expiration, i think this is another syntax input.

Lastly, the security code, which I think it can be just a regular input.

Thoughts?

Do you see multiple syntaxinputs or just one that does it all ?

**Comment by ericsoderberghp** [comment]
Agreed on using this for credit cards, where after the first few digits are typed, the schema can be adjusted to align with the type of card.

I wasn't thinking a single SyntaxInput would be used for all fields you mention.

**Comment by alansouzati** [comment]
it would be great to have it exposed in a codesandbox that we can play with

**Comment by ericsoderberghp** [comment]
Agreed. It will just take a little work to get there. I thought I'd solicit some feedback on the concept first.

**Comment by atanasster** [comment]
This is useful yes and since it wasnt anywhere in v2 i created one such component for grommet controls. But its called a masked input and the ‘available syntax’ is called a mask - i really dont see a need to invent a new name and confuse everyone

**Comment by ShimiSun** [comment]
Sounds like a good component to have in the grommet library.
Can you share wireframes or any design drafts of the new component? just so it will be easier to visualize?

**Comment by srallen** [comment]
An input that supports multiple values would be useful for me as I'd like to replace using react-select (see the async multi-select example: https://react-select.com/async) since it has poor accessibility and the library has had an unstable API requiring nearly fully rewrites each major version update.

**Comment by ericsoderberghp** [comment]
Thanks for the great feedback so far. I've created an initial implementation and called it `MaskedInput`. You can find it here: https://github.com/grommet/grommet/pull/2540

**Comment by iad42** [comment]
Hi! Sorry to bump this thread, but how would you implement a submit function once the enter is pressed? I was thinking about `Keyboard` but that event would grab all the enters that were pressed
