### ISSUE TITLE
remove x on Search and SearchInput in IE11

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#251]
Need to add the following to get rid of the clear x in IE. This was already done for form-field inputs.

```
<clazz>::-ms-clear {
    display: none;
}
```

May be worth abstracting out so all input types get this

**Comment by ericsoderberghp** [comment]
This is only an issue with IE11. Cannot reproduce on Edge 13.

**Comment by ericsoderberghp** [comment]
Duplicate of issues #143
