### ISSUE TITLE
v2 TextInput add extend to all Styled elements

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2513]
Currently TextInput Styled elements do not expose an extend function, with the exception being `StyledTextInput`. We should also add the extend for:

`StyledTextInputContainer`
`StyledPlaceholder`
`StyledSuggestions`

**Comment by buoyantair** [comment]
@silltho Heya, just wanted to ping if you're still looking to work on this, if not I will go forward :)

**Comment by ShimiSun** [comment]
@buoyantair go for it 👍

**Comment by buoyantair** [comment]
Looks like StyledPlaceholder & StyledSuggestions already have the extend functionality implemented.

**Comment by silltho** [comment]
@bnoguchi yeah my bad I couldn't find any time to implement this.

**Comment by buoyantair** [comment]
@silltho It's okay! Life happens!
