### ISSUE TITLE
grommet-forms proposal

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#2514]
This is a proposal for a new repository for `grommet-forms`.

The idea is to make it easier to build typical forms with grommet components. Here is an example of how it could be used:
```
import { Form, FormField, FormSubmitButton, FormTextInput, FormTextArea } from 'grommet-forms';

class FormExample extends Component {
  state = { value: {} }

  onSubmit = () => {
    const { value } = this.state;
    // whatever submitting the form should entail
  }

  render() {
    const { value } = this.state;
    return (
      <Form
        value={value}
        onChange={value => this.setState({ value })}
        onSubmit={this.onSubmit}
      >
        <FormField label="Name" name="name" required />
        <FormField label="Email" name="email" type="email" />
        <FormField label="Employee ID" name="employeeId" validate={/^[0-9]+$/} />
        <FormField label="Size" name="size" options={['small', 'medium', 'large']} /> {/* renders RadioButtons */}
        <FormField label="Comments" name="comments">
          <FormTextArea name="comments" />
        </FormField>
        <FormSubmitButton label="Update" />
      </Form>
    );
  }
}

FormField.propTypes = {
  label: PropTypes.string.description("Human readable label"),
  name: PropTypes.string
    .description("The key to use within the Form value to store the data.")
    .isRequired,
  options: PropTypes.arrayOf(PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.object,
  ])).description("Array of options. If less than four, RadioButtons, otherwise, Select."),
  optionLabelKey: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.func,
  ]).description("When options are objects, the key to get the label."),
  optionValueKey: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.func,
  ]).description("When options are objects, the key to get the value."),
  required: PropTypes.bool.description("Whether the field is required."),
  validate: PropTypes.oneOfType([
    PropTypes.object, // regular expression
    PropTypes.func,
  ]).description("Validation rule. Provide a regular expression or a function."),
};
```

Please let us know if you have any feedback. We'd like some discussion in this issue before proceeding further.

**Comment by ericsoderberghp** [comment]
This is being considered as part of grommet via `Form` and `FormField` changes. https://github.com/grommet/grommet/pull/2520

**Comment by murbanowicz** [comment]
Formik is currently best or at least one of the best solutions for forms with React. Maybe instead of creating something new it is better to either just document how to use Formik with Grommet or create simple wrapper for Grommet & Formik ?

**Comment by cyberrian** [comment]
1. Why is name prop at FormField level? Shouldn’t it be a prop of the input component?
Does this mean a FormField can only have one input?
2. What does FormField prop “type=email” do? Seems like it should be a prop of the input component.
3. How do you specify the validation error string?
4. Not excited about FormField's options prop. Not obvious that having < 4 options renders RadioButtons and a Select otherwise. What about multi-select/checkboxes?
5. The comments example shows both FormField and input having prop name=comments. Isn't that redundant? Goes back to 1 where name prop should be at input level.
6. How do we set initial/default value of an input? If initial value doesn't change, will its value get stored in the state?
7. Some dialogs only need to submit modified fields (e.g. edit dialog). Can we enhance this to keep track of dirty fields?
8. FormField.props.required should also support a callback function if flag is dynamically calculated.
9. Some fields may need multiple validators and/or validators which depend on other validators. 
I can see this validate function getting huge/messy. Should we support key/values for multiple validators? If so, FormField.props.required doesn't need to be its own prop.
Example:
```
<FormField validate={{
   isRequired: this.isRequired, // gets called first; if passes, calls next isPhoneNumber validator
   isPhoneNumber: this.isPhoneNumber
   ...
}}/>
```

In general, I feel that the FormField component is becoming a wrapper/God input component which will need logic to render multiple types of input components. I can see many if-else branches which can get messy. I like the idea of leveraging Formik. No reason to re-invent the wheel. Thanks.

**Comment by ericsoderberghp** [comment]
> Formik is currently best or at least one of the best solutions for forms with React. Maybe instead of creating something new it is better to either just document how to use Formik with Grommet or create simple wrapper for Grommet & Formik ?

I've added a comment with some initial analysis on this in the associated pull request: https://github.com/grommet/grommet/pull/2520#issuecomment-444689655

**Comment by ericsoderberghp** [comment]
> 1. Why is name prop at FormField level? Shouldn’t it be a prop of the input component?

It will end up being a prop at the underlying input, but it is also used as the key into the `value` to extract error information.

>    Does this mean a FormField can only have one input?

If you wanted more than one input in a FormField, you would have to add your own children and wrap with FormContext. See notes in the associated pull request.

> 2. What does FormField prop “type=email” do? Seems like it should be a prop of the input component.

In the current direction, all unknown props are passed down to the input component. For TextInput, `type` would be directly passed to the underlying input.

> 3. How do you specify the validation error string?

The current direction allows `validate` to take an object, with a regular expression and a message. If `validate` is a function, the return value is the error string. @atanasster asked that we enhance `validate` to take an array, which seems reasonable.

> 4. Not excited about FormField's options prop. Not obvious that having < 4 options renders RadioButtons and a Select otherwise. What about multi-select/checkboxes?

Agreed. The current direction backs off on including this intelligence inside FormField.

> 5. The comments example shows both FormField and input having prop name=comments. Isn't that redundant? Goes back to 1 where name prop should be at input level.

Again, the `name` is used for the error strings.

> 6. How do we set initial/default value of an input? If initial value doesn't change, will its value get stored in the state?

You would set the `value` object of the Form to have a key with initial value where the key matches the FormField `name`.

> 7. Some dialogs only need to submit modified fields (e.g. edit dialog). Can we enhance this to keep track of dirty fields?

The current direction includes a `touched` object so you can see which fields were modified at all.

> 8. FormField.props.required should also support a callback function if flag is dynamically calculated.

Good idea.

> 9. Some fields may need multiple validators and/or validators which depend on other validators.
>    I can see this validate function getting huge/messy. Should we support key/values for multiple validators? If so, FormField.props.required doesn't need to be its own prop.

Instead of an object, an array makes the ordering more explicit. Agreed that `required` could be handled with this pattern. Although, `required` as a single property might be more convenient. We'll keep discussing.

>    Example:
> 
> ```
> <FormField validate={{
>    isRequired: this.isRequired, // gets called first; if passes, calls next isPhoneNumber validator
>    isPhoneNumber: this.isPhoneNumber
>    ...
> }}/>
> ```
> In general, I feel that the FormField component is becoming a wrapper/God input component which will need logic to render multiple types of input components. I can see many if-else branches which can get messy. I like the idea of leveraging Formik. No reason to re-invent the wheel. Thanks.

The current direction has a `component` that avoids this.

**Comment by cyberrian** [comment]
> > 1. Why is name prop at FormField level? Shouldn’t it be a prop of the input component?
> 
> It will end up being a prop at the underlying input, but it is also used as the key into the `value` to extract error information.
> 
> > Does this mean a FormField can only have one input?
> 
> If you wanted more than one input in a FormField, you would have to add your own children and wrap with FormContext. See notes in the associated pull request.
> 
> > 1. What does FormField prop “type=email” do? Seems like it should be a prop of the input component.
> 
> In the current direction, all unknown props are passed down to the input component. For TextInput, `type` would be directly passed to the underlying input.
> 
> > 1. How do you specify the validation error string?
> 
> The current direction allows `validate` to take an object, with a regular expression and a message. If `validate` is a function, the return value is the error string. @atanasster asked that we enhance `validate` to take an array, which seems reasonable.
> 
> > 1. Not excited about FormField's options prop. Not obvious that having < 4 options renders RadioButtons and a Select otherwise. What about multi-select/checkboxes?
> 
> Agreed. The current direction backs off on including this intelligence inside FormField.
> 
> > 1. The comments example shows both FormField and input having prop name=comments. Isn't that redundant? Goes back to 1 where name prop should be at input level.
> 
> Again, the `name` is used for the error strings.
> 
> > 1. How do we set initial/default value of an input? If initial value doesn't change, will its value get stored in the state?
> 
> You would set the `value` object of the Form to have a key with initial value where the key matches the FormField `name`.
> 
> > 1. Some dialogs only need to submit modified fields (e.g. edit dialog). Can we enhance this to keep track of dirty fields?
> 
> The current direction includes a `touched` object so you can see which fields were modified at all.
> 
> > 1. FormField.props.required should also support a callback function if flag is dynamically calculated.
> 
> Good idea.
> 
> > 1. Some fields may need multiple validators and/or validators which depend on other validators.
> >    I can see this validate function getting huge/messy. Should we support key/values for multiple validators? If so, FormField.props.required doesn't need to be its own prop.
> 
> Instead of an object, an array makes the ordering more explicit. Agreed that `required` could be handled with this pattern. Although, `required` as a single property might be more convenient. We'll keep discussing.
> 
> > Example:
> > ```
> > <FormField validate={{
> >    isRequired: this.isRequired, // gets called first; if passes, calls next isPhoneNumber validator
> >    isPhoneNumber: this.isPhoneNumber
> >    ...
> > }}/>
> > ```
> > In general, I feel that the FormField component is becoming a wrapper/God input component which will need logic to render multiple types of input components. I can see many if-else branches which can get messy. I like the idea of leveraging Formik. No reason to re-invent the wheel. Thanks.
> 
> The current direction has a `component` that avoids this.

Thanks for addressing all questions. I'm happy with the direction we're heading.

**Comment by krawalli** [comment]
I've played a little bit with this and -> very nice and thumb up! 

However, I'm struggling with e.g. CheckBox. If used as  *component=* parameter - e.g. the *label=* is rendered twice. The OnChange Method seems to be implemented by user (it could be done with auto-magic in the background).The value itself seems not to be picked up by the submit method.

Beyond that:
- Still having problems to get "validator" to do what i want. 
- for validation, there should be any i18n for the error text
- if you have two password inputs, a validator should compare to other inputs in that form. How to reference them in code. Maybe a "auto-ref" could be handy here.
- if I set "errors" via var before first submit, then these are not rendered (or at least i did it wrong)

i would suggest to have a form with all standard input types, so there is a kind of documentation for usage.

**Comment by ericsoderberghp** [comment]
Thanks for the great feedback. I've updated the pull request to address the issues:
- CheckBox should work now.
- You can pass `errors` to Form for initial errors.
- The validation functions now receive two arguments: the current field value and the value object for the whole form.

Also, can you clarify the issue with "any i18n for the error text"?

**Comment by krawalli** [comment]
A note for documentation: 
I tried to integrate the "SeasonsSelect" example from storybook. Since it has a custom "onChange" method, it wont work.
Solution: call the onChange Method from the props. That will give the value back to the form context like this:

~~~
        onChange={event => {
          this.props.onChange(event)
          [...]
        }}
~~~

**Comment by ericsoderberghp** [comment]
> CheckBox is working fine - thank you!
> 
> > Also, can you clarify the issue with "any i18n for the error text"?
> 
> e.g. in FormFields.js
> 
> ```js
> [...]
>   if (required && !data) {
>     error = 'required';
>   } else if (validate) {
> [...]
> ```
> 
> should be something like
> 
> ```js
> [...]
>   if (required && !data) {
>     error = this.props.i18nRequired || 'required';
>   } else if (validate) {
> [...]
> ```

Got it. Thanks. Added `messages` to Form for this.

**Comment by ericsoderberghp** [comment]
> A note for documentation:
> I tried to integrate the "SeasonsSelect" example from storybook. Since it has a custom "onChange" method, it wont work.
> Solution: call the onChange Method from the props. That will give the value back to the form context like this:
> 
> ```
>         onChange={event => {
>           this.props.onChange(event)
>           [...]
>         }}
> ```

The SeasonsSelect example was meant to be an example of using Select. Were you using it via something like: `<FormField component={SeasonsSelect} />`? If so, then I agree that SeasonsSelect should call any `onChange` passed to it. But, I suspect I might not be understanding well enough what you are doing.

**Comment by krawalli** [comment]
yes, thats what i've done
