### ISSUE TITLE
v2 Grommet - onResponsiveChange callback

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2516]
it would be nice if we had an onResponsiveChange callback to that we can make informed decisions when that responsive breakpoint changes.

For example, hide the sidebar by default if size is small.

**Comment by ericsoderberghp** [comment]
I suspect I am missing something, but why isn't ResponsiveContext sufficient? https://v2.grommet.io/responsivecontext

**Comment by oorestisime** [comment]
yeah back at the time i didn't want to wrap another component with a context just to wait for a change. with hooks this is much easier and cleaner to do i agree it is probably not needed

**Comment by ShimiSun** [comment]
We can do it today using `useContext` hook, no need to wrap the component with context.
`const size = React.useContext(ResponsiveContext);` should do the trick.

The storybook example is also adjusted to use hooks https://storybook.grommet.io/?path=/story/responsivecontext--custom-breakpoints.

I'll be closing the issue, feel free to reopen or comment if needed.
