### ISSUE TITLE
Component Architecture Improvements (Initially Box)

### ISSUE THREAD

**Issue by tbranyen** [grommet/grommet#2517]
With styled-components there is a lot of Context and HOC wrapping necessary to communicate between components. Grommet adds to this further by wrapping many components, such as the Box. The Box has the following associated components: Box, StyledBox, GapBox, and WrappedBox. The goals here are to reduce the amount of wrapping and nesting which should help with performance
during the React reconcilation phase.

While this issue only targets the Box, the patterns and work should be applicable to other components as well.

## Areas of Focus

- [x] ~Convert from Class to Function component~ Continuing to use class #2537
- [ ] Merge the various permutations of the Box under a single component #2537 (WIP)
- [ ] Remove context wrapping and leverage the styled-components `withTheme` hoc, if possible use static contextType
- [ ] Move/migrate/remove all specific custom helper logic inside of Box

## Possible areas of improvement

- [ ] Reduce prop complexity (general catch all)
- [ ] Convert domProp to dom (ex color colorProp) to just color to help avoid separate (Box,StyledBox) components

**Comment by jcfilben** [comment]
Closing since this issue refers to an outdated version of Box and suggested updates are no longer relevant.
