### ISSUE TITLE
Child component theme extensions are missing key props from parent component to make styling decisions

### ISSUE THREAD

**Issue by pstauskas** [grommet/grommet#2521]
Some Grommet components render child components that are customizable in the theme file. The idea of the `extend` function on these child components is great in theory for ultimate dynamic styling decisions, but it is limited because it only has access to props which are explicitly being passed into the child components, and does not have access to important parent props. There may be more use cases, but these are the specific ones I am seeing limitations for: `input.toggle.knob`, `select.control`, and `select.container`. 

### Expected Behavior

Child component themes should somehow have access to the parent component's props when trying to an `extend` function when customizing the theme.

### Actual Behavior

Child component themes do not have access to the parent component's props when trying to an `extend` function when customizing the theme.

### Examples of my use cases

1. I'd like to change the `knob` of an `input.toggle` such that the knob is slightly bigger (protruding above and below) than the background area. Ideally i could do this via the `extend` function of the `input.toggle.knob` theme, but that function did not receive the `checked` prop, so instead I had to do some DOM "guessing" by adding knob-related styles to the `toggle.extend` function via a `> span` style:
```
checkBox: {
   toggle: {
      background: grey,
      color: 'white',
      size: '36px',
      knob: {
        extend: `
          background: white !important;
          top: -4px;
          box-shadow: 0px 0px 2px 0px rgba(0,0,0,0.12), 0px 2px 2px 0px rgba(0,0,0,0.24);
        `
      },
      extend: ({ checked }) => `
        height: 14px;
        border-color: grey;
        ${checked && `
          background-color: blue;
          border-color: blue;

          > span {
            margin-left: -1px;
          }
        `}
      `
    }
}
```

2. I'd like to change how the `select.control` appears when it is disabled, for instance adding a grey background and changing the font style. I would expect to be able to have access to the `disabled` prop to the Select, but I don't because the control does not get that prop. I have not yet figured out how to do this, but a simple expectation I would have for the theme would look like this:
```
select: {
    control: {
      extend: props => {
        props.disabled && `
          background-color: grey
          font-style: italic
        `
      }
    }
}
```

An easy solution would be to expose some more useful parent props by passing them explicitly to the sub-components, but this is less scalable and more manual as use cases arise.
 
As a general, more scalable possible solution, might it be worthwhile to ensure all themeable child component that can be `extend`ed additionally have access to all of its parent's props? Obviously the child components themselves don't necessarily need the parent props for rendering, so in order to reduce prop bloat yet still ensure `extend` is maximally flexible in these situations, it may be necessary to pass in parent props as `props.__parentProps` or something of that sort. I'm agnostic to the end solution, but I do feel that accessing these props in a guaranteed way would increase developer efficiency and always provide a backup way of getting what we need for styling decisions.

### Your Environment

- Grommet version: 2.0.0
- Browser Name and version: Any
- Operating System and version (desktop or mobile): Any

**Comment by pstauskas** [comment]
As of Grommet 2.1.0, the `indeterminate` prop was introduced for CheckBox, but I cannot theme my indeterminate checkbox properly because `checkBox.icon.extend` and `checkbox.check.extend` do not have access to the `indeterminate` prop.

**Comment by alansouzati** [comment]
agreed!

**Comment by MikeWalrath** [comment]
Hello! Just doing a bit of clean up here. We have added [checkbox.icons.indeterminate](https://v2.grommet.io/checkbox#checkBox.icons.indeterminate) to the checkbox. I will close this issue but if there is anything that is still limiting your use case please feel free to file a new issue.
