### ISSUE TITLE
Interaction with DataTable and Table

### ISSUE THREAD

**Issue by ChrisWestcottUK** [grommet/grommet#2527]
Is there any way to interact with rows in a DataTable?

I would like to be able to click on a row, highlight that row and then perform an action.

Is there a mechanism for this?
Are there any other suggestions for this sort of behaviour?

**Comment by oorestisime** [comment]
I ve been playing around a bit with this. I am not sure if this will meet what you need but my idea is to add a prop onRowClick on DataTable which will get called when the  onClick event of StyledDataTableRow is fired. The function will receive the event and the datum clicked. 

This will basically respond to half of what you need. I am not sure how to highlight the area and whether this should be temporary (like you click and you get an animation for 1 second or so). Maybe datatables should support something like checkboxes to control which rows or groups are selected?

**Comment by oorestisime** [comment]
this is covered in #2708 
should we close this in favor of the other that covers more details (both design and implementation ones?)

**Comment by ShimiSun** [comment]
We'll be tracking this one in #2708.
