### ISSUE TITLE
Tabs do not work in chrome, firefox, or IE11

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#253]
Chrome and FIrefox give an Error in the console that looks like the following. Chrome and Firefox do give the appearance of the selected item being different (even though it hasn't).

16:48:58.047 Error: Invariant Violation: findComponentRoot(..., .1cs4bk69g5c.1.1.1.1.1:1:3.2.0.1.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.

IE11 leaves the mousover css, and outputs no stack or error against grommet.io. Against local instance outputs the expected console.log errors and also gives the appearance of moving. Apparently stripping out the console.logs (or whatever is done with server side render) results in slightly different behavior in IE.

**Comment by alansouzati** [comment]
Very weird issue that started after we migrated to React 0.14 and React-Intl 2.0. I did a work around in commit https://github.com/grommet/grommet/commit/ae14e9f81ec5cd89cd58dd69f46cd64407e09c26.

Also, I've submitted an issue with react-intl project: https://github.com/yahoo/react-intl/issues/212

**Comment by jaitthomas** [comment]
Is there is any workaround for this issue or any timeline for this fix? This issue is preventing us from leveraging the tab component.

**Comment by jaitthomas** [comment]
When will we release 0.4.1, as we are dependent on it?

**Comment by alansouzati** [comment]
The release is going to happen this week, in the meantime stable branch will unblock you.

**Comment by jaitthomas** [comment]
I am currently unblocked with the stable branch. Just curious when the next release will be?

**Comment by alansouzati** [comment]
Fixed in 0.4.1

**Comment by jaitthomas** [comment]
np..Thank you Alan.
