### ISSUE TITLE
Add FileInput component

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2535]
I know @RyanCCollins worked on a file upload component for v1.

It would be nice to have a file upload component in v2 with dropzone capabilities.

**Comment by oorestisime** [comment]
I ve recently used with https://github.com/react-dropzone/react-dropzone and it worked great. would the component use an external library for this or actually implement all the dropzone capabilities?

**Comment by ShimiSun** [comment]
Sounds like a good idea for a pattern @MikeWalrath

**Comment by ShimiSun** [comment]
A new FileInput component is now available on the[ stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F). It will be officially available on our next release, thanks for reporting.
