### ISSUE TITLE
Incorrect type definitions for Select interface

### ISSUE THREAD

**Issue by dininski** [grommet/grommet#2538]
### Expected Behavior
The latest version should be consumable from a TS project. The property definitions for the Select component should be correct:

```typescript
...
disabledKey?: string | ((...args: any[]) => any);
...
```

### Actual Behavior
When using grommet components TypeScript throws an error:

```
/node_modules/grommet/components/Select/index.d.ts
Type error: Type expected.  TS1110

     9 |   closeOnChange?: boolean;
    10 |   disabled?: boolean | number | string | object[];
  > 11 |   disabledKey?: string | (...args: any[]) => any;
       |                           ^
    12 |   dropAlign?: {top?: "top" | "bottom",bottom?: "top" | "bottom",right?: "left" | "right",left?: "left" | "right"};
    13 |   dropTarget?: object;
    14 |   focusIndicator?: boolean;

```

### URL, screen shot, or Codepen exhibiting the issue
In the official [TypeScript playground](http://www.typescriptlang.org/play/#src=interface%20SelectProps%20%7B%0D%0A%20%20a11yTitle%3F%3A%20string%3B%0D%0A%20%20alignSelf%3F%3A%20%22start%22%20%7C%20%22center%22%20%7C%20%22end%22%20%7C%20%22stretch%22%3B%0D%0A%20%20gridArea%3F%3A%20string%3B%0D%0A%20%20margin%3F%3A%20%22none%22%20%7C%20%22xxsmall%22%20%7C%20%22xsmall%22%20%7C%20%22small%22%20%7C%20%22medium%22%20%7C%20%22large%22%20%7C%20%22xlarge%22%20%7C%20%7Bbottom%3F%3A%20%22xxsmall%22%20%7C%20%22xsmall%22%20%7C%20%22small%22%20%7C%20%22medium%22%20%7C%20%22large%22%20%7C%20%22xlarge%22%20%7C%20string%2Chorizontal%3F%3A%20%22xxsmall%22%20%7C%20%22xsmall%22%20%7C%20%22small%22%20%7C%20%22medium%22%20%7C%20%22large%22%20%7C%20%22xlarge%22%20%7C%20string%2Cleft%3F%3A%20%22xxsmall%22%20%7C%20%22xsmall%22%20%7C%20%22small%22%20%7C%20%22medium%22%20%7C%20%22large%22%20%7C%20%22xlarge%22%20%7C%20string%2Cright%3F%3A%20%22xxsmall%22%20%7C%20%22xsmall%22%20%7C%20%22small%22%20%7C%20%22medium%22%20%7C%20%22large%22%20%7C%20%22xlarge%22%20%7C%20string%2Ctop%3F%3A%20%22xxsmall%22%20%7C%20%22xsmall%22%20%7C%20%22small%22%20%7C%20%22medium%22%20%7C%20%22large%22%20%7C%20%22xlarge%22%20%7C%20string%2Cvertical%3F%3A%20%22xxsmall%22%20%7C%20%22xsmall%22%20%7C%20%22small%22%20%7C%20%22medium%22%20%7C%20%22large%22%20%7C%20%22xlarge%22%20%7C%20string%7D%20%7C%20string%3B%0D%0A%20%20children%3F%3A%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3B%0D%0A%20%20closeOnChange%3F%3A%20boolean%3B%0D%0A%20%20disabled%3F%3A%20boolean%20%7C%20number%20%7C%20string%20%7C%20object%5B%5D%3B%0D%0A%20%20disabledKey%3F%3A%20string%20%7C%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3B%0D%0A%20%20dropAlign%3F%3A%20%7Btop%3F%3A%20%22top%22%20%7C%20%22bottom%22%2Cbottom%3F%3A%20%22top%22%20%7C%20%22bottom%22%2Cright%3F%3A%20%22left%22%20%7C%20%22right%22%2Cleft%3F%3A%20%22left%22%20%7C%20%22right%22%7D%3B%0D%0A%20%20dropTarget%3F%3A%20object%3B%0D%0A%20%20focusIndicator%3F%3A%20boolean%3B%0D%0A%20%20labelKey%3F%3A%20string%20%7C%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3B%0D%0A%20%20messages%3F%3A%20%7Bmultiple%3F%3A%20string%7D%3B%0D%0A%20%20multiple%3F%3A%20boolean%3B%0D%0A%20%20onChange%3F%3A%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3B%0D%0A%20%20onClose%3F%3A%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3B%0D%0A%20%20onOpen%3F%3A%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3B%0D%0A%20%20onSearch%3F%3A%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3B%0D%0A%20%20options%3A%20string%20%7C%20JSX.Element%20%7C%20object%5B%5D%3B%0D%0A%20%20placeholder%3F%3A%20string%20%7C%20React.ReactNode%3B%0D%0A%20%20plain%3F%3A%20boolean%3B%0D%0A%20%20searchPlaceholder%3F%3A%20string%3B%0D%0A%20%20selected%3F%3A%20number%20%7C%20number%5B%5D%3B%0D%0A%20%20size%3F%3A%20%22small%22%20%7C%20%22medium%22%20%7C%20%22large%22%20%7C%20%22xlarge%22%20%7C%20string%3B%0D%0A%20%20value%3F%3A%20string%20%7C%20JSX.Element%20%7C%20object%20%7C%20string%20%7C%20object%5B%5D%3B%0D%0A%20%20valueLabel%3F%3A%20React.ReactNode%3B%0D%0A%20%20valueKey%3F%3A%20string%20%7C%20(...args%3A%20any%5B%5D)%20%3D%3E%20any%3B%0D%0A%7D)

### Steps to Reproduce

1. create-react-app
2. add any tsconfig.json
3. run the application

### Your Environment

- Grommet version: 2.1.1
- Browser Name and version: any
- Operating System and version (desktop or mobile): desktop/Windows 10

**Comment by oorestisime** [comment]
hm this would be tricky to solve inside react-desc. i wonder if there is another way to indicate functions since the problem is multiple times definition of args

**Comment by MadRabbit** [comment]
is there a way around this? seems like v2.2 is still affected

**Comment by MadRabbit** [comment]
i patched it like so in my local machine and it seems to work:

```ts
import * as React from "react";

interface AnyFunc {
  (...args: any[]): any
}

export interface SelectProps {
  a11yTitle?: string;
  alignSelf?: "start" | "center" | "end" | "stretch";
  gridArea?: string;
  margin?: "none" | "xxsmall" | "xsmall" | "small" | "medium" | "large" | "xlarge" | {bottom?: "xxsmall" | "xsmall" | "small" | "medium" | "large" | "xlarge" | string,horizontal?: "xxsmall" | "xsmall" | "small" | "medium" | "large" | "xlarge" | string,left?: "xxsmall" | "xsmall" | "small" | "medium" | "large" | "xlarge" | string,right?: "xxsmall" | "xsmall" | "small" | "medium" | "large" | "xlarge" | string,top?: "xxsmall" | "xsmall" | "small" | "medium" | "large" | "xlarge" | string,vertical?: "xxsmall" | "xsmall" | "small" | "medium" | "large" | "xlarge" | string} | string;
  children?: AnyFunc;
  closeOnChange?: boolean;
  disabled?: boolean | number | string | object[];
  disabledKey?: string | AnyFunc;
  dropAlign?: {top?: "top" | "bottom",bottom?: "top" | "bottom",right?: "left" | "right",left?: "left" | "right"};
  dropTarget?: object;
  focusIndicator?: boolean;
  labelKey?: string | AnyFunc;
  messages?: {multiple?: string};
  multiple?: boolean;
  onChange?: AnyFunc;
  onClose?: AnyFunc;
  onOpen?: AnyFunc;
  onSearch?: AnyFunc;
  options: string | JSX.Element | object[];
  placeholder?: string | React.ReactNode;
  plain?: boolean;
  searchPlaceholder?: string;
  selected?: number | number[];
  size?: "small" | "medium" | "large" | "xlarge" | string;
  dropHeight?: "xsmall" | "small" | "medium" | "large" | "xlarge" | string;
  value?: string | JSX.Element | object | string | object[];
  valueLabel?: React.ReactNode;
  valueKey?: string | AnyFunc;
  emptySearchMessage?: string;
}

declare const Select: React.ComponentType<SelectProps>;

export { Select };
```

**Comment by oorestisime** [comment]
Yeah the thing is that typescript definitions are automatically generated using https://github.com/grommet/react-desc so modifying the file by hand won't do it.

If you are interested in contributing to solve this the change needs to happen in this file https://github.com/grommet/react-desc/blob/master/src/descToTypescript.js which is responsible for consuming descriptions and turning them into typescript defnitions.
Hope this helps.

**Comment by dininski** [comment]
@oorestisime when would a new release with this bugfix be released?

**Comment by alansouzati** [comment]
We can release a bug fix soon. let me target friday since there are other minor fixes that can be included.

**Comment by fnimick** [comment]
@alansouzati Any word on the release? I'm not sure which Friday you intended but this is blocking use of grommet in typescript projects.

**Comment by dininski** [comment]
Yeah, please release this as the fix has already been merged and this is blocking any usage in TS projects. I've been struggling to find a TypeScript workaround with the latest version of grommet, apart from diving in the `node_modules` folder and updating it by hand. This works for local development purposes, but is obviously blocking CI deployments.

Even forking the repo does not seem to work out of the box as there are non-trivial build+release steps.

**Comment by matepapp** [comment]
We have the same issue and we're waiting for the new release. We solved it by using a temporary workaround with [patch-package](https://www.npmjs.com/package/patch-package). It's great for solving minor issues such as typings, but I still recommend pull requests for major problems. If you fix the typedefs locally then run the script for the specific package it creates a `patches` folder with the file and version you patched. Our method is to include the related github issue (if there's any) in a comment on top of the patch. We revise them monthly to see if the issue has been resolved.

**Comment by dininski** [comment]
I'm using a different approach, probably equally as hacky:

1. copy the fixed definition to `custom-definitions.d.ts`
2. use a `postinstall` script to delete the original type definition within node_modules

**Comment by sdebaun** [comment]
discovered Grommet a few days ago, playing with it in a toy app, same issue, would love to use it.

**Comment by oahehc** [comment]
also expecting for the new release.

@matepapp 
thanks for the sharing.
[patch-package](https://www.npmjs.com/package/patch-package) is a great workaround.
