### ISSUE TITLE
Select Object Multiple is not filtering

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#2549]
Select Object Multiple is not filtering
### Expected Behavior
Search should work and filter correctly

### Actual Behavior
Filters properly for numbers but not for ABC charcters

### URL, screen shot, or Codepen exhibiting the issue
<img width="1093" alt="screen shot 2018-12-05 at 11 02 15 pm" src="https://user-images.githubusercontent.com/6320236/49564848-46dd3680-f8e2-11e8-9d3f-114f6d93ac62.png">

### Steps to Reproduce

1. go to https://storybook.grommet.io/?selectedKind=Select&selectedStory=Object%20Multiple&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
2. enter 'option' on the search box 
3. see no results

### Your Environment
Mac Chrome

- Grommet version: 2.1.1
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): MAC

**Comment by alansouzati** [comment]
this is a great first issue I'm pretty sure it is a bug in the story not in grommet.
