### ISSUE TITLE
Button children have no access to hover state

### ISSUE THREAD

**Issue by taleschaves** [grommet/grommet#2554]
Currently, there is no easy way for children components of a Button (plain == true) to tell if the button is being hovered.

### Expected Behavior
A way for the children to know if button is being hovered

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/y0k48n9r9z

### Steps to Reproduce

1. Open the modal by clicking on the button
2. Hover over the back icon
3. See that the icon color has changed

### Your Environment

- Grommet version: 2.0.1
- Browser Name and version: Chrome 70.0.3538.110
- Operating System and version (desktop or mobile): Desktop

**Comment by stvmachine** [comment]
+1
