### ISSUE TITLE
Leverage the new hooks API to replace the context API

### ISSUE THREAD

**Issue by oorestisime** [grommet/grommet#2556]
Hooks will be released sometime at Q1 2019 and besides the excitement around them Grommet could simplify some of its internal core by leveraging them.

Instead of having multiple context providers, which seem to also slow down https://github.com/styled-components/styled-components/issues/2215 , the hooks API (useContext, https://reactjs.org/docs/hooks-overview.html#-other-hooks) could come in handy to simplify the codebase (avoiding to always needing to wrap code in a consumer to get theme or responsive) and improve user experience.

While i dont propose to convert all at once i think a nice step forward would be to experiment on a side-branch by just converting the responsive context to be used with hooks. this would give the opportunity to test them and if desired proceed to incremental changes in the other components.

**Comment by oorestisime** [comment]
So this will be kind of a learning experience for me but i am willing to give this a go in another branch to see how it behaves.  i ll just modify the responsive context and the components that are using it in order to have something functional and a base for further testing!

**Comment by dheerajvs** [comment]
@ericsoderberghp Now that hooks are released, is there a plan to leverage them?

**Comment by ericsoderberghp** [comment]
We've been using this pattern in apps built with grommet recently:
```
...
import { ResponsiveContext } from 'grommet';
...
const MyComponent = props => {
    const responsive = React.useContext(ResponsiveContext);
    ...
}
```
So, you can use the `useContext()` hook with grommet today.

I think the intent of this issue is to use hooks internally in the grommet implementation more. @ShimiSun and I discussed migrating grommet code, both the components and the stories, to use hooks over time. Any help in this effort would be most welcome.

**Comment by alexlabrioche** [comment]
@ericsoderberghp  hello Eric, can we see an exemple of how to use the responsive context ? without Hooks I must wrap my component around the ResponsiveContext.consumer every time i need (but I'm pretty sure it's not the good way) 
And maybe an example with the new useContext Hooks ?

thanks so much

**Comment by ericsoderberghp** [comment]
I would have thought that the above code snippet would be a useful example. Can you clarify a bit more on what else you'd like to see?

**Comment by MikeWalrath** [comment]
Component left for refactoring:
- Grommet.js

@MikeKingdom
