### ISSUE TITLE
InfiniteScroll onMore is not triggered

### ISSUE THREAD

**Issue by cslashnet** [grommet/grommet#2559]
### Expected Behavior
Using the InfiniteScroll component with an onMore call that calls an external API to get more data doesn't get triggered.
Any function I use for onMore is not executed.
Also the Table component onMore has the same issue as it uses the InfiniteScroll.

This worked on v1.x

### Actual Behavior
The onMore should be triggered the first time when the component loads and it makes the first call, then when the list max length is reached when scrolling down.

- Grommet version: 2.1.1
- Browser Name and version: Any
- Operating System and version (desktop or mobile): MacOS

**Comment by ShimiSun** [comment]
@cslashnet Thank you for taking the time for filing the issue! We added a storybook example to demonstrate the onMore in action. Please let us know if you have more questions.

**Comment by silltho** [comment]
https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=infinitescroll&module=%2Fsrc%2FInfiniteScroll.js shows that onMore isn't working.
