### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by justinglibert** [grommet/grommet#2563]
Grommet.io shows a GoDaddy parking page. Same for Grommet Icons. V2 is up though

**Comment by ShimiSun** [comment]
WIP, please use https://v2.grommet.io/ in the meanwhile.
sorry for the inconveniency.

**Comment by ShimiSun** [comment]
@justinglibert can you please let me know if the issue still reproduces for you? we checked on a few clients and the website was redirecting properly.

**Comment by justinglibert** [comment]
No it's fixed. Thank you!
