### ISSUE TITLE
Layer inside Box when both have 'onClick' prop, when clicking inside Layer, both are invoked

### ISSUE THREAD

**Issue by nivo33** [grommet/grommet#2564]
### Expected Behavior

When I have a `<Layer>` Inside a `<Box>` like so:
`<Box onClick={this.setState({showLayer: true})>
    ....
    {this.state.showLayer && <Layer>
        <Button  onClick={() => this.setState({showLayer: false})} />
    </Layer}
</Box`

Clicking on the box should open the layer, and clicking the button should close it.
### Actual Behavior

Both the functions are called, and so I can't close the layer. This worked in V1. I know so, because I found out the issue while migrating to V2.

### URL, screen shot, or Codepen exhibiting the issue
check out the Codepen:
EDIT: 
https://codesandbox.io/s/qkj756zr0q

### Your Environment

- Grommet version: 2.0.1
- Browser Name and version: chromium 
- Operating System and version (desktop or mobile): ubuntuu 18.04 on desktop

**Comment by ericsoderberghp** [comment]
I don't think that CodePen is the right one for this issue. Perhaps another one?

**Comment by alansouzati** [comment]
I would stay away from adding `onClick` directly in Box. can you explain your scenario?

My inclination is that you need to call `event.stopPropagation();` inside your Layer onclick.

**Comment by nivo33** [comment]
@ericsoderberghp 

> I don't think that CodePen is the right one for this issue. Perhaps another one?
My bad. Here it is: (edited in original as well)
https://codesandbox.io/s/qkj756zr0q

**Comment by nivo33** [comment]
@ericsoderberghp 
> I don't think that CodePen is the right one for this issue. Perhaps another one?


My bad. Here it is: (edited in original as well)
https://codesandbox.io/s/qkj756zr0q

**Comment by ericsoderberghp** [comment]
If you add an `event.stopPropagation();` inside the `onClick` handler for the Layer, you will get the behavior you are looking for. But, as @alansouzati mentioned, you should be using a Button instead, as that is semantically more correct and will be more accessible.
