### ISSUE TITLE
Box should support flex-grow and flex-shrink factor

### ISSUE THREAD

**Issue by ChrisRose** [grommet/grommet#2565]
Both the `flex-grow` and `flex-shrink` CSS properties accept a number or factor, e.g. `flex-grow: 2`, but it can't be specified via `Box`'s `flex` props.

### Expected Behavior

The `flex-grow` or `flex-shrink` factor should be supported via prop(s) by `Box`.

### Actual Behavior

Flex grow/shrink factor is not supported.

- Grommet v2.2.0
- Chrome Version 70.0.3538.110
- macOS Mojave

**Comment by alansouzati** [comment]
a possible idea would be to extend the `flex` prop to accept grow and shrink values:

```
<Box flex={{ grow: 2 }} />
```

**Comment by ChrisRose** [comment]
That makes sense to me.
