### ISSUE TITLE
Markdown missing components

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#2573]
### Expected Behavior
The Markdown component should render all common html tags with appropriate grommet styling and behavior. 

### Actual Behavior
Markdown renders some elements a bit too bare. Missing tags are as follows:
- `img` does not use Grommet's Image component
- `blockquote` has no discernible contrast from a `p` tag other than an indent
- `pre` and `code` render in a monospace font but dont provide much contrast to existing `p` tags and may be hard to catch inline
- `table` has basic browser styles which is probably fine however it would be more consistent if DataTable's styles were shared with Markdown's table

### URL, screen shot, or Codepen exhibiting the issue
I've prepared a codepen with common Markdown elements to review
https://codesandbox.io/s/j2m4z408xv?initialpath=%2Fmarkdown&module=%2Fsrc%2FMarkdown.js

**Comment by oorestisime** [comment]
i agree that user needs to be able to override on its own the default components #2522 for the moment only `p` `a` are set

**Comment by karatechops** [comment]
@oorestisime this functionality is built out but it took digging into the code to discover the implementation. You can pass overrides in Markdown's `components` prop and it will deep merge with the initial Grommet overrides set.

```javascript
<Markdown
    components={{
      blockquote: {
        component: Quote,
        props: {
          border: '1px aliceblue solid'
        }
      },
      pre: {
        component: Pre
      },
      code: {
        component: Code
      },
    }}
  >
    {children} // Markdown string
  </Markdown>;
```

I filed #2574 to update the documentation
