### ISSUE TITLE
Markdown missing documentation

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#2574]
The Markdown component does not have any documentation.
https://v2.grommet.io/markdown

Specifically, the `components` prop should be added to the documentation as this is an important prop to effectively use the component.

**Comment by karatechops** [comment]
This may also be a good place to note that I don't think the `components` prop is intuitive. As someone who is used to `markdown-to-jsx`I would expect Grommet to properly handle the user passing in `overrides` and gracefully merging those with Grommet's existing override set. With Grommet's current behavior if a user passes in a single override it will clear the existing Grommet component set.

**Comment by oorestisime** [comment]
are you sure it is not merging? i added a single override of a pre tag in a storybook and `p` and `a` rendered correctly. unless i didn't really understand what you mean imho this part works.

**Comment by karatechops** [comment]
The Markdown component will lose the grommet components/styling if it's passed via the `options` prop, [here's a code example](https://codesandbox.io/s/81p8713zw0?initialpath=%2Fmarkdown&module=%2Fsrc%2FMarkdown.js)

![screen shot 2018-12-11 at 4 33 29 pm](https://user-images.githubusercontent.com/5983843/49831732-aa43ea00-fd62-11e8-884d-4d0a3f088b0b.png)

**Comment by oorestisime** [comment]
damn sorry i did not understand that you meant touching the options and not components. so the component should destructure options as well and deep merge all of them together right? i ll update my pr

**Comment by karatechops** [comment]
It would seem we could effectively expose markdown-to-jsx's native behavior to handle the `options` prop.

```javascript
    <Markdown
      options={{
        overrides: {
          blockquote: {
            component: Quote
          }
        }
      }}
    >
```

The above snippet should merge with the existing component set. I would think you could just spread the overrides prop values before components [here](https://github.com/grommet/grommet/blob/master/src/js/components/Markdown/Markdown.js#L29)

```javascript
    const overrides = deepMerge(
      {
        p: { component: Paragraph },
        a: { component: Anchor },
      },
      heading,
      ...this.props.options.overrides, // probably desctructured to options...
      components,
    );
```

**Comment by oorestisime** [comment]
yeap i think spreading them is the best solution as well.
