### ISSUE TITLE
Grommet 'background' property not working

### ISSUE THREAD

**Issue by dderooy** [grommet/grommet#2577]
I recently updated to Grommet 2.2.1 and now its not loading colors properly using the 'background' property. 

### Expected Behavior
```
import { Grommet, Box } from 'grommet';
import { grommet } from 'grommet/themes';

<Grommet theme={grommet}>
    <Box background="brand">
        test
    </Box>
</Grommet>
```
This should yield a purple box

### Actual Behavior
Throws an "Uncaught TypeError: Cannot read property 'colors' of undefined"

Also when importing 'grommet/themes', VS code says: 
[ts]
Could not find a declaration file for module 'grommet/themes'. 

- Grommet version: ^2.2.1
- Browser Name and version: Chrome Version 70.0.3538.102 
- Operating System and version (desktop or mobile): Mac Mojave, V10.14

**Comment by alansouzati** [comment]
can you reproduce this in a codesandbox ? this works for me:

https://codesandbox.io/s/4xnvpz78xw

**Comment by dderooy** [comment]
I can't reproduce it in the sandbox. It must be an issue with my local setup. If I remove 'background' property from my components, the site loads without errors.

**Comment by alansouzati** [comment]
can you confirm your `grommet` and `grommet-icons` versions?

**Comment by dderooy** [comment]
"grommet": "^2.2.1",
"grommet-icons": "^3.2.1",

**Comment by alansouzati** [comment]
yup. can you upgrade to grommet icons v4 ?

**Comment by alansouzati** [comment]
https://github.com/grommet/grommet/releases/tag/v2.2.0 <-- we describe the update process here

**Comment by dderooy** [comment]
That solved it! Thanks for your help 😃

**Comment by alansouzati** [comment]
yeah sorry for the bumpy road there.

**Comment by deangibson89** [comment]
I'm still getting this with grommet 2.7.1 and grommet-icons 4.2.0
