### ISSUE TITLE
Table mirror is positioned to first positioned element.

### ISSUE THREAD

**Issue by tobias-flitsch** [grommet/grommet#258]
The table mirror is positioned to the first positioned element, which should be the root div element `.table--selectable`. However this div element is not positioned (refer to _objects.table.scss). Adding the following code should help.

```
.table {
  &--scrollable {
    position: relative;
  }
}
```

But I am not sure if the table is always positioned like that. I assume if anyone would want to position the table differently, they would specify the position as an inline style, overwriting the above css.

**Comment by ericsoderberghp** [comment]
Thanks for submitting. Fixed in 506a5e9f4840c39e03d588d515eb1a45b02b91ca.
