### ISSUE TITLE
Node value for TextInput placeholder prevents focus

### ISSUE THREAD

**Issue by ChrisRose** [grommet/grommet#2584]
Using a node for the placeholder of a `<TextInput>` prevents you from clicking into the input to focus.

Example:

https://9318364wp4.codesandbox.io/textinput

- Grommet v2.2.0
- Chrome
- macOS

**Comment by ericsoderberghp** [comment]
I suspect I am not understanding the issue. If I click on the TextInput, I get a flashing prompt bar and I can type to enter text. I can tab away from and back to the element and I see a focus outline and can type. These behaviors are consistent with https://storybook.grommet.io/?selectedKind=TextInput&selectedStory=Simple%20TextInput&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel.

**Comment by ChrisRose** [comment]
Loooong overdue response.  Sorry about that.  But, when I click on the placeholder text, I am unable to focus the input.  Clicking in the space within the Select, before the placeholder text, does apply focus though.
