### ISSUE TITLE
TextInput onChange has a event.target null

### ISSUE THREAD

**Issue by shai32** [grommet/grommet#2590]
Expected Behavior
The event object passed from a TextInput component's onChange should have a key named target where the value is the text itself.

Actual Behavior
The target key consistently has a value of null.

Screenshot of Console
Uncaught TypeError: Cannot read property 'value' of null

Steps to Reproduce
render a TextInput component
add onChange prop onChange={event => console.log(event.target)}
the target is always null, so we can't extract the value of the input

Your Environment
Grommet version: v2.2.1
Browser Name and version: Google Chrome Version 71.0.3578.80 (Official Build) (64-bit)
Operating System and version (desktop or mobile): Mac Mojave - Desktop
Editor: Webstorm
Package Manager: Node 11.4 / YARN

**Comment by oorestisime** [comment]
Hey,
i ve just launched storybook locally and can't reproduce this bug.
here's the example code https://github.com/grommet/grommet/blob/master/src/js/components/TextInput/textinput.stories.js#L10-L30
`event.target` is not null. 
can you probably share some more information or a codesandbox to reproduce this?

**Comment by shai32** [comment]
its happen when wrapping the onChange with _.debounce
_.debounce(event => onSearch(event.target.value), 400);

**Comment by ericsoderberghp** [comment]
I believe you need to call `event.persist()` in order to prevent the event object from being re-used due to React's event pooling. See: https://reactjs.org/docs/events.html#event-pooling

**Comment by shai32** [comment]
@ericsoderberghp , this is right, I am closing the issue.

**Comment by KiranVH** [comment]
I am new to this. I just need to know how to do this event.persist() on onChange event, I have something like this at present `onChange={(event) => debounce(this.handleChange(event.target.value),200} ` ? Currently, I am getting it as null event

**Comment by ShimiSun** [comment]
@KiranVH I think we need to see the minimal reproducible code to help with your scenario.

**Comment by KiranVH** [comment]
@ShimiSun  Thanks for replying, Below is my code snippet. Whenever I try to wrap my waitUntilUserFinishTyping inside debounce, I am getting event as null. 

` waitUntilUserFinishTyping(filter, e){
    let tempSearch = e.target.value;
    this.setState({tempSearch});
    this.onSearchChange(filter, value);
  }

<input type="text" value={tempSearch} onChange={debounce(this.waitUntilUserFinishTyping.bind(this, filter),250)} />

MyDebounce fun:
const debounce = (func, wait) => {
  let timeout;

  return function executedFunction(...args) {
    const later = () => {
      clearTimeout(timeout);
      func(...args);
    };

    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
  };
};

`

**Comment by ShimiSun** [comment]
@KiranVH this is [grommet template code](https://codesandbox.io/s/m7mml8l0zj), please feel free to fork and reproduce your problem on it. I have multiple questions on the code you shared, and those could be easily answered if will run on the application. Also please mind adding the package that debounce is imported from.

**Comment by KiranVH** [comment]
Hi @ShimiSun 

I have made the code changes in the grommet template ref: https://codesandbox.io/s/m7mml8l0zj?file=/index.js 
whenever a user typing something in the text box, I am waiting for 250 ms after they stop typing then making handleChange event call and updating the "search" value in state. I am not using any external library to implement debounce . I have used my own version of debouncing function.

**Comment by allen-munsch** [comment]
@shai32 see : https://stackoverflow.com/a/63665601/2026508

Basically instead of passing the entire event to `debounce` just pass the `event.target.value` to the debounced function.
