### ISSUE TITLE
No option to have transparent background with Layer

### ISSUE THREAD

**Issue by harveyslash** [grommet/grommet#2593]
### Expected Behaviour
Some way to have no background (in the layer) and also have disabled background. 

This feature is generally useful for having some kind of loading spinner. 

### Actual Behaviour

There is always a white background in the layer with plain mode set to false

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/6jyy45r4nz

**Comment by ShimiSun** [comment]
This fixes the issue:
https://codesandbox.io/s/5k8rr2l21k

**Comment by lqhuang** [comment]
@ShimiSun Hey, the page of codesandbox.io shows "Something went wrong. Request failed with status code 404". So could you help to republish your code to illuminate how to make background  transparent? Thanks very much!

**Comment by lqhuang** [comment]
Oh, It set plain to false will let background become transparent. But my problem now is why I cannot click outside to exit. I have used `onClickOutside={() => setSidebarLayer(!sidebarLayer)}`. I look over most examples in story book, but my logical code is almost the same, I can't figure out why. Did I miss some important size / action props...

**Comment by lqhuang** [comment]
OK, set plain to true fix background to transparent. Thanks :)
