### ISSUE TITLE
Snapshot testing generates huge files

### ISSUE THREAD

**Issue by kimwanglee** [grommet/grommet#2597]
We using Grommet in one of our projects and in this project we also using Jest and Enzyme for snapshot testing.
Our snapshot tests generates huge snapshot files, because for every grommet component in our components the whole theme object is rendered.
Even with a small component it generates a file with over 800 lines of code and they look like this:

```
exports[`component Test renders itself 1`] = `
<WithTheme(Box)
  direction="column"
  margin="none"
  pad="none"
  responsive={true}
  theme={
    Object {
      "accordion": Object {
        "icons": Object {
          "collapse": [Function],
          "expand": [Function],
        },
      },
      "anchor": Object {
...
```
### Expected Behavior

Snapshot tests don't render the whole theme for each used component.

### Actual Behavior

Snapshot tests renders the whole theme for each component.

### Steps to Reproduce

Create Component:
```
import React, { Component } from 'react';
import { Box, Text } from 'grommet';

class Test extends Component {
  render() {
    return (
      <Box fill align="center" pad="large">
        <Text>I am a Test!</Text>
      </Box>
    );
  }
}
export default Test;
```

Create test:
```
import React from 'react';
import { shallow } from 'enzyme';
import Test from '../../components/Test';

test('renders itself', () => {
  const wrapper = shallow(<Test />);
  expect(wrapper).toMatchSnapshot();
});
```

### Your Environment
- Grommet version: 2.1.1
- Browser Name and version:
- Operating System and version (desktop or mobile): macOS Mojave 10.14

**Comment by oorestisime** [comment]
Hello,

i gave this a quick test. i think the problem is not in grommet, and not that it is a problem actually. you should probably look at https://github.com/styled-components/jest-styled-components for improving your snapshots instead of bare enzyme (grommet is using styled-components).

you can have a look at how grommet tests its components to get "inspired"

**Comment by kimwanglee** [comment]
@oorestisime thx for your reply.
I will give jest-styled-components a try.
