### ISSUE TITLE
InfiniteScroll does not work with components that do not forward a ref anymore

### ISSUE THREAD

**Issue by taleschaves** [grommet/grommet#2600]
InfiniteScroll breaks when trying to render a React component for an item.

### Expected Behavior
InfiniteScroll should not break when rendering a React component for an item.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/10688k4753

### Steps to Reproduce

```
class Item extends Component {
  render() {
    const { item } = this.props;
    return (
      <Box border={{ color: "accent-1", size: "small" }}>
        <Text>{item}</Text>
      </Box>
    );
  }
}

class App extends Component {
  render() {
    return (
      <Grommet theme={grommet}>
        <InfiniteScroll items={items}>
          {(item, index) => {
            return <Item key={index} item={item} />;
          }}
        </InfiniteScroll>
      </Grommet>
    );
  }
}
```

### Your Environment

- Grommet version: 2.2.1
- Browser Name and version: Chrome 70.0.3538.110 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Desktop

**Comment by alansouzati** [comment]
This seems like a regression after we removed `findDOMNode`. this seems like one we should keep the `findDOMNode` or investigate a better solution.

thanks for creating this issue. I'm taking a look at this right now.
