### ISSUE TITLE
reduce grommet dependencies on windows to ease the instalation

### ISSUE THREAD

**Issue by bungcip** [grommet/grommet#261]
I am curious why i need to install python and windows SDK to try grommet on windows.  As old fashioned developer, I only know about jquery and knockout, so I want to refresh my knowledge on JS frontside. For now, I still learning how to use react and babel to create some SPA. Then I found out about grommet and want to try it. However the dependency of grommet is too much for me , running  `npm install -g grommet` fail in my machine, and I don't have enough patience to install windows SDK.

I think I am not the only one windows developer who have the trouble.

**Comment by eabay** [comment]
I suggest you to take a look at [docker](https://www.docker.com/docker-toolbox). There are lots of ready-to-use node images in [hub](https://hub.docker.com).

**Comment by bryanjacquot** [comment]
We are working on a new Grommet CLI, you can see the beginnings of it here (https://github.com/grommet/grommet-cli) that will dramatically reduce the requirements for installing the CLI.  We will validate what dependencies are required on windows to develop a grommet-based application with Node 4.x.
