### ISSUE TITLE
A way to remove carousel buttons?

### ISSUE THREAD

**Issue by dderooy** [grommet/grommet#2629]
Is there a way to remove the side buttons from the carousel? Ideally the bottom buttons as well to get a clean image slider look.

**Comment by ShimiSun** [comment]
I didn't try it fully myself, but I can see the icons are being set from the theme under `carousel.icons`, can you try to override it so the icons won't be displayed.
Here is the full carousel theme from `base.js`:
``` carousel: {
      icons: {
        current: Subtract,
        next: Next,
        previous: Previous,
        // color: undefined,
      },
    },```

**Comment by dderooy** [comment]
I ended up going with another carousel plugin with more formatting options. I see you added those changes though. Thanks for your help!
