### ISSUE TITLE
Would like the ability to have line separators in table rows

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#2630]
Today there is no general way to have line separators between table rows. You can attempt to emulate this by putting borders on TableCell's but then you have to top align the values and you must create a false row on the bottom for the last row to have an underline. It would be easier if TableRow allowed a border or separator. 
### Expected Behavior

Line between each row
### Actual Behavior

Putting the (border) line on the TableCell is awkward and leads to unexpected behaviors.

**Comment by ShimiSun** [comment]
@oorestisime I believe this is related to the DataTable improvements you suggested in your PR.
