### ISSUE TITLE
Inconsistent behavior for Table/DataTable in Chrome vs FF & Edge

### ISSUE THREAD

**Issue by dininski** [grommet/grommet#2631]
When a `<Table />` is wrapped in a `<Box fill={true}/>` the end result differs between Chrome vs FF and Edge. On Chrome the table fills the width of the container, whereas in the others - it does not.

### Expected Behavior
`Table` should fill the width of the parent `Box` on FF & Edge.

### Actual Behavior
`Table` grows as much as it's content and does not fill the parent.

### URL, screen shot, or Codepen exhibiting the issue

Reproduced - https://codesandbox.io/s/j3n5ky80k3
Screenshots - https://imgur.com/a/FIwDro4

### Steps to Reproduce

1. Create a `Table`
2. Wrap the table inside a `<Box fill={true}><Table {..props} /></Box>`

### Your Environment

- Grommet version: 2.2.1
- Browser Name and version: Firefox 64, Chrome 71.0.3578.98
- Operating System and version (desktop or mobile): Windows 10

**Comment by oorestisime** [comment]
i wonder whether the right solution is to `width: 100%` on StyledTable. @ShimiSun ?

**Comment by ShimiSun** [comment]
@oorestisime I kind of like what @mrebb is offering better. what do you think?
