### ISSUE TITLE
Theme not propagated to context correctly on certain version of react-dom (16.5.2)

### ISSUE THREAD

**Issue by c0rvax** [grommet/grommet#2638]
The theme is not correctly sent to context when using react-dom 16.5.2. Theme is `{}` on that version of the library

### Expected Behavior

Theme object should be sent correctly

### Actual Behavior

Theme is equal to `{}`

### URL, screen shot, or Codepen exhibiting the issue

Here is the code. Only index.jsx roles here. Please note that react-dom 16.5.2 is a bad version for the library.
https://codesandbox.io/s/jq4mx03w5

### Steps to Reproduce

Visit the codepen

### Your Environment

Upgrade react-dom 16.5.2 to some other version to fix the problem

**Comment by iad42** [comment]
To make google search of this problem easier, here is the error

`Cannot read property 'drop' of undefined`

This should also occur on other modules which rely on theme

**Comment by oorestisime** [comment]
Maybe we can close this right? I mean it will still be indexed.
Unless react dependency in package.json should be updated to disable that version

**Comment by c0rvax** [comment]
If there is a way to make the dependencies exclude this specific version, that should be a nice fix, i think

**Comment by ShimiSun** [comment]
Thank you for taking the time to file the issue. the `package.json` is now updated with the correct dependency
