### ISSUE TITLE
InfiniteScroll within table: Reloads new items only once

### ISSUE THREAD

**Issue by florianbepunkt** [grommet/grommet#2644]
The issue #2636 was fixed with the latest release. Given an array of 100 items and a step length of 10, the Infinite scroll component load only 20 items total (== 1 "reload").

### Expected Behavior
All items should be lazily rendered.

### Actual Behavior
Only a part of the items is lazily rendered

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/5vopj41j8n

### Your Environment

- Grommet version: 2.3.1
- Browser Name and version: Chrome 71.0.3578.98
- Operating System and version (desktop or mobile): OSX

**Comment by ericsoderberghp** [comment]
I think this might be a mis-understanding in how `items`, `step`, and `onMore` work. InfiniteScroll will render `step` elements from `items`. As the user scrolls, it will render `step` more elements from `items`. As long as `items` has elements to render, it will keep rendering them without calling `onMore`. `onMore` will be called when the user scrolls to the end of the `items`. `onMore` is typically used to lazily load items from a server, where the items are expensive to retrieve, either in time or size. If `items` already has everything that could be shown, `onMore` can be left undefined. You can see an example of `onMore` being used in the storybook: https://github.com/grommet/grommet/blob/6f804a130d031ccf0d7e6246a8491f8898c174d2/src/js/components/InfiniteScroll/infinitescroll.stories.js#L53

**Comment by florianbepunkt** [comment]
@ericsoderberghp I don't think there is a missunderstanding. Could you please have a look at the codesandbox I provided?

There are 100 items with a step size of 10.

If you open on a large screen where there is enough space, only 20 elements are rendered even if there is still space.

<img width="1920" alt="bildschirmfoto 2019-02-02 um 14 28 09" src="https://user-images.githubusercontent.com/8314202/52164784-1dc8fe80-26f7-11e9-9fcb-103bc6894fec.png">

Expected behaviour: More elements should be rendered.

If I narrow the screen space so that it becomes scrollable and reload, everything works as expected.

Also I add fill={true} to the outer box it also works. I'm not sure what the problem is exactly but in our internal apps we experience this issue with all tables where we try to use InfiniteScroll

**Comment by ShimiSun** [comment]
Thanks for filing the issue
