### ISSUE TITLE
Select in FormField renders border / Select plain prop has no effect

### ISSUE THREAD

**Issue by florianbepunkt** [grommet/grommet#2645]
Latest grommet 2.3.1 breaks the rendering of Select inside a form field and the rendering of Select with a plain prop.

### Expected Behavior
This is with grommet 2.1.0: https://codesandbox.io/s/54yy313l64

### Actual Behavior
This is with grommet 2.3.1: https://codesandbox.io/s/w2oq7l986l
It renders borders

- Grommet version: 2.3.1

**Comment by oorestisime** [comment]
I am inclined to think i broke this with PRs on Box component and the borders. i ll try and have a look tonight.
