### ISSUE TITLE
InfiniteScroll within Grid: Weird behavior between 'columns' and window size

### ISSUE THREAD

**Issue by krismorf** [grommet/grommet#2646]
### Actual Behavior
InfiniteScroll does not render items on certain breakpoints (depending also on item width). 
### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/149zvkox37
<img width="1091" alt="screen shot 2019-01-10 at 5 06 57 pm" src="https://user-images.githubusercontent.com/42035849/50977136-472cab00-14fa-11e9-83d8-dfc11ee1a395.png">

### Steps to Reproduce

1. Go to https://codesandbox.io/s/149zvkox37
2. Resize window
3. InfiniteScroll does not render items

### Your Environment

- Grommet version: 2.3.1
- Browser Name and version: Chrome 71.0.3578.98
- Operating System and version (desktop or mobile): macOS 10.14.2

**Comment by florianbepunkt** [comment]
This is related to #2644 

Your step size is 12 and there are 24 items rendered. There is only one "reload" / additional render when there should be several batches of elements rendered.

**Comment by florianbepunkt** [comment]
Interestingly this only happens, when there is enough space so no additional scrolling is needed. With the example in this issue: If there is enough space for 30 elements to be rendered, only 24 items are rendered.

When there is not enough screen estate (for example on a mobile) and scrolling is necessary, everything works as expected.
