### ISSUE TITLE
Tiles has "justify-content: flex-start" by default and doesn't have Box's flex properties

### ISSUE THREAD

**Issue by josephalhamad** [grommet/grommet#265]
Tiles has "justify-content: flex-start" by default which makes everything shift to the left.
.tiles {
  width: 100%;
  padding: halve($inuit-base-spacing-unit);

  display: flex;
  flex-wrap: wrap;
  justify-content: flex-start;
}

Tiles, unlike Tile, doesn't have access to Box's flex properties. So, that prevents me from changing the justify property. 

var Tiles = React.createClass({
propTypes: {
    direction: React.PropTypes.oneOf(['row', 'column']),
    fill: React.PropTypes.bool,
    flush: React.PropTypes.bool,
    onMore: React.PropTypes.func,
    size: React.PropTypes.oneOf(['small', 'medium', 'large']),
    small: React.PropTypes.bool
  },

**Comment by ericsoderberghp** [comment]
Tiles is meant to be a bit more controlled than Box. Could you elaborate a bit more on what you are trying to achieve?

**Comment by josephalhamad** [comment]
I am trying to have 2 buttons side by side to have the same size and align them in the center of the page.

**Comment by ericsoderberghp** [comment]
Would it work to put the Buttons inside a Box instead of using Tiles?

**Comment by bryanjacquot** [comment]
Closing based on lack of response.
