### ISSUE TITLE
 RoutedAnchor not working with   "react-router-dom" version 4.4.0

### ISSUE THREAD

**Issue by shai32** [grommet/grommet#2652]
### Expected Behavior

should support react-router 4.4.0 version
### Actual Behavior

RoutedAnchor not working with   "react-router-dom" version 4.4.0
 using it, will print an error on console
 Failed context type: The context `router` is marked as required in `RoutedAnchor`, but its value is `undefined`

### URL, screen shot, or Codepen exhibiting the issue
**
look at react route changelog
https://github.com/ReactTraining/react-router/releases/tag/v4.4.0-beta.0
![image](https://user-images.githubusercontent.com/16700996/51057535-93591780-15ee-11e9-8c71-065cb7824c31.png)
**

### Steps to Reproduce

1. Use     "react-router-dom": "next",
2. create an app with RoutedAnchor
3. run the app and you will see the error on console 
![image](https://user-images.githubusercontent.com/16700996/51057641-e0d58480-15ee-11e9-9fc0-8837011e10a1.png)

### Your Environment

- Grommet version:     "grommet": "2.3.1",
- Browser Name and version: Version 71
- Operating System and version (desktop or mobile): macOS Mojave 10.14.2 ( deskop)

**Comment by oorestisime** [comment]
can you share how you use RoutedAnchor? From what i understand from the documentation It seems you need to wrap it withRouter?

**Comment by shai32** [comment]
I didn't wrap it with withRouter, but I didn't have to in react-router v3.3
If we need to warp it with withRouter, its not really usable

**Comment by oorestisime** [comment]
can you probably set up a codesandbox reproducing the problem?

**Comment by shai32** [comment]
wrapping it with withRouter, still does not work

**Comment by oorestisime** [comment]
would you be able to share a codesandbox with the problem or a repo? i don't have any projects with react-router (personally using router5) so it will be much easier to debug.

**Comment by shai32** [comment]
@oorestisime of course, here is the codesandbox:
https://codesandbox.io/s/930z3kjx8y

**Comment by shai32** [comment]
![image](https://user-images.githubusercontent.com/16700996/52232360-f9bb1800-28c4-11e9-8e7e-a8c1456e8699.png)

**Comment by oorestisime** [comment]
So i as i understand from their changelog they don't allow any more the `this.context.router`.
I updated the codesandbox https://codesandbox.io/s/l5ov5y4269 to show what they expect. You need to wrap components withRouter so you get access to the history, location and match props.

As i see it RoutedAnchor is router agnostic right now so i am not sure it makes any sense form grommet to wrap it internally in the library (it will need to depend on react-router-dom). Plus this is a fairly undocumented component.

Maybe @ericsoderberghp can shred some light on how this is supposed to work.

**Comment by ShimiSun** [comment]
Since we will be deprecating RoutedButton and RoutedAnchor, we won't be attempting to address this issue. (see #2855)
