### ISSUE TITLE
CheckBox z-index:1 won't play nice by default with other position sticky/absolute elements

### ISSUE THREAD

**Issue by pstauskas** [grommet/grommet#2653]
CheckBox is opinionated by default with z-index: 1. This doesn't play nicely with other position: sticky or position: absolute elements. In general, if there are other Grommet components that have a z-index opinion, it may be worth evaluating if it is really necessary.

### Expected Behavior

I don't think CheckBox should be opinionated with z-index: 1.

### Codesandbox exhibiting the issue

https://codesandbox.io/s/zr1nqv1x33 (See CheckBox.js)

### Steps to Reproduce

Scroll down and notice the CheckBox appearing above the "Click Me" position: sticky header. By default I'd expect the header to be above the CheckBox due to position:sticky, but I have to give it z-index:2 in order for that to happen.

### Your Environment

- Grommet version: v2.3.0
- Browser Name and version: Any
- Operating System and version (desktop or mobile): Any

**Comment by ericsoderberghp** [comment]
Have to reopen this as the earlier fix broke other things.
