### ISSUE TITLE
v2.3.0 Heading base size changes

### ISSUE THREAD

**Issue by pstauskas** [grommet/grommet#2654]
v2.3.0 update has caused Heading font-sizes to change. For example, Heading level 3 changed from 22px to 26px. I am not sure if this was intentional but don't see a mention in release notes, and only noticed because my application Heading sizes all looked bigger than normal after updating. This is reproducible in a simple code sandbox with v2.3.0 vs v.2.2.1

Additionally my TextInput's throughout my app all of a sudden included `font-weight: 500`, whereas before the update there was no `font-weight` (inheriting). I can't reproduce this in a sandbox since v.2.2.1 had `font-weight:600` on a simple TextInput so I am not sure what is going on, but I suspect it may be related to the Heading issue described above.

**Comment by ShimiSun** [comment]
v2.3.0 includes a fix (#2624) for `h3` on size `medium`. both `medium` and `small` on size `h3` were sized the same, and that was a bug, so we corrected `medium` to show the right size. I believe that if you change the `h3` `medium` sizes to `small` it should work as expected. 

for `font-weight` issue, sounds like we should take a look at that, I'm with limited access but maybe @alansouzati or @oorestisime can jump in here, it probably involves #2607.

Thanks for taking the time to file these issues peter

**Comment by oorestisime** [comment]
hm, i can't figure out any reason why the font-weight changed.

* That PR  just includes the ability to add a font-weight in the heading levels. If you did not modify your base theme to include a font-weight then it should be backwards compatible.

* The TextInput component does not make use of that part of the theme at all, unless you restyled it or so?

in any case sorry if i broke anything but probably with a bit more context i can debug this better

**Comment by ShimiSun** [comment]
Thanks for the detailed response @oorestisime , sounds reasonable.
I think that if the `h3` heading will be resized to `small` the `font-weight` issue will be gone as well.
@pstauskas let us know.

**Comment by pstauskas** [comment]
@ShimiSun @oorestisime thanks for confirming the header fix and its `size` property, makes sense!

My apologies for the `font-weight` issue, after spending some more time debugging, I think it was a subtle tweak made in my environment which caused this. Thanks for looking into this anyways :)
