### ISSUE TITLE
In Firefox, <Meter> wrapped in <Table> extends beyond <Box> with width

### ISSUE THREAD

**Issue by Ganevru** [grommet/grommet#2656]
If ``<Table>`` is wrapped in ``<Box width = "small">`` (Box with a width limit) and ``<Meter type = "bar">`` is inside this table, then in Firefox it will go beyond the limits of this Box. The problem is found only in Firefox - in Chrome and in Safari everything works fine.

Here is the code. Below is a link to codesandbox.

```
   <Box width="small" border>
      <Table caption="Simple Table">
        <TableBody>
          <TableRow>
            <TableCell>
              <Meter
                type="bar"
                values={[
                  {
                    value: 60
                  }
                ]}
              />
            </TableCell>
            <TableCell>
              <Text>Text</Text>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </Box>
```

### Expected Behavior
Should work like in Chrome - Meter wrapped in Table should not go beyond the ``<Box width = "small">``.

### Actual Behavior
Meter wrapped in Table goes beyond the ``<Box width = "small">`` (only in Firefox)

### URL, screen shot, or Codepen exhibiting the issue
Reproduced - https://codesandbox.io/s/qqv93r007q?module=%2Fsrc%2FTable.js (see Table)
Screenshots - https://imgur.com/a/7t6FWTV

### Steps to Reproduce
Create a ``<Box width="small">``
Create a Table inside this Box
Create a ``<Meter type="bar">`` inside this Table

### Your Environment
* Grommet version: 2.3.1
* Browser Name and version: Firefox 64 (64-bit), Chrome 71.0.3578.98 (Official Build) (64-bit) (works fine), Safari 12.0 (works fine)
* Operating System and version (desktop or mobile): macOS Mojave 10.14

**Comment by mrebb** [comment]
@ShimiSun One possible solution to avoid overflow on Firefox could be `table-layout: fixed` along with `width:inherit`. This fixes the overflow issue but keeps each cell width same across table.

**Comment by mrebb** [comment]
Here is the final solution and this should fix the problem on FF:
```
table-layout: fixed
width: inherit
min-width: calc( same as parent div)
```

**Comment by ShimiSun** [comment]
@mrebb sounds like a PR is coming! 🎉  
I also liked the example @Ganevru suggested, we should consider to leverage it for storybook's regression testings.
