### ISSUE TITLE
Bar Charts xAxis ({ Placement: Bottom }) not working correctly

### ISSUE THREAD

**Issue by stephanbochet** [grommet/grommet#266]
The Bar Charts  xAxis ({ Placement: Bottom }) not working correctly.

The Bars should be translated in the Y position to the top so that it aligns with threshold and all other components.

Example of issue:
http://codepen.io/anon/pen/bENObX

I fixed the issue on my local files by adding the following code to the Chart.js component ->  renderBars: () { 

    _renderBars: function () {
    //Code
          if ('bottom' === bounds.xAxis.placement) {
          stepBarBase += XAXIS_HEIGHT;
        }
         return (
               <rect key={item.label || seriesIndex}

**Comment by alansouzati** [comment]
Thank you so much for adding a codepen to illustrate the issue. It helped me a lot to see what is going on.

I tried the fix you suggested and it works just fine. Would be kind enough to send a Pull Request with this contribution?

**Comment by stephanbochet** [comment]
Yes, I will do that.
