### ISSUE TITLE
Target element of Drop and DropButton get tabindex of -1

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#2660]
### Expected Behavior
The target element should keep a tab index so that it is accessible by keyboard interaction.

### Actual Behavior
The target element, or in the case of the DropButton, the button gets a tabindex of -1 when the drop is in an open state. 

### URL, screen shot, or Codepen exhibiting the issue
Here's an example of trying to build a reusable button with a tooltip on hover/focus using DropButton:

https://codesandbox.io/s/jv3nwx1jrv

User should be able to tab between the buttons.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by srallen** [comment]
I did a bit of investigating yesterday and found that the `FocusedContainer` is the reason the child button gets a `tabIndex` of -1. The `DropContainer` is wrapped by it:

https://github.com/grommet/grommet/blob/001cd59bc1ee792019a88646589fd223c87e2cdb/src/js/components/Drop/DropContainer.js#L320-L328

The `FocusContainer` calls a function on mount that ends up calling this utility function:

https://github.com/grommet/grommet/blob/001cd59bc1ee792019a88646589fd223c87e2cdb/src/js/utils/DOM.js#L121-L133

The child button does not already have a tab index, so then, `unsetTabIndex` is called on it, which calls a function to set the tab index as -1:

https://github.com/grommet/grommet/blob/001cd59bc1ee792019a88646589fd223c87e2cdb/src/js/utils/DOM.js#L99

As an experiment, I removed `FocusedContainer` from the `DropContainer` and it fixed this accessibility issue and didn't break as far as I could tell any of the storybook examples or any of the tests. This leads to the questions:

- What is `FocusedContainer` doing here? 
- Does removing it have a consequence that I'm not seeing?

**Comment by alansouzati** [comment]
I agree with the intent of removing tabIndex -1 from the target container. it makes sense.

**Comment by IanKBovard** [comment]
If we accept this solution https://codesandbox.io/s/grommet-v2-template-koi4o?file=/index.js 
i belive we can close this issue.

**Comment by IanKBovard** [comment]
I can't assign myself, but i am working on this issue with jesseolsen.
