### ISSUE TITLE
ThemeContext.Extend causing issues from CRA production build, possibly missing 💥 

### ISSUE THREAD

**Issue by m11m** [grommet/grommet#2669]
Hint: I did spend a little time trying to figure it out and it seems like ThemeContext / ThemeContext.Extend is not available in the build?

I did a temporary workaround where I just brought in a copy of ThemeContext.js and deps into project source and loaded it from there instead of in grommet package and it seems to work after that.

### Expected Behavior

Should work in production build, not cause fatal crash the moment ThemeContext.Extend gets imported / used.

### Actual Behavior

Works fine in webpack dev server, explodes in CRA build using `npm run build` 💥 

### URL, screen shot, or Codepen exhibiting the issue
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/1445487/51254454-c2f97e00-1966-11e9-92ff-9ede379c58eb.png">

### Steps to Reproduce
1. Install stuff
```
npm init -y
npm i -S react-scripts
npx create-react-app my-react-app
cd my-react-app
npm i -S grommet styled-components
```

2. Edit index.js to something like attachment

[index.js.txt](https://github.com/grommet/grommet/files/2764466/index.js.txt)

3. Verify it works fine in webpack dev server

`npm start`

4. Try to load the production build

```
npm run build
cd build
python -m SimpleHTTPServer
```
View http://localhost:8000/ and verify that the page does not render and console is full of red

### Your Environment

- Grommet version: 2.3.1
- Browser: FF Quantum Latest Stable

**Comment by ShimiSun** [comment]
@m11m can you please verify if this is still reproducible now after we updated the `react-dom` dependency.

**Comment by jay-aye-see-kay** [comment]
I'm having the same issue, same reproduction steps. I tried updating `node_modules/grommet/package.json` directly to match the changes in PR#2702, this had no effect. Happy to help more if I can.

### Environment
* Grommet version: 2.3.1
* Tested on: 
    * Kubuntu 18.10 FF 65 and Chrome 72
    * Ubuntu 16.04 Chrome 72

**Comment by robinmetral** [comment]
Hi @ShimiSun, I'm running into the same issue here.

How can I fix it?

**Comment by oorestisime** [comment]
Which react, grommet and webpack version are you using?

**Comment by robinmetral** [comment]
```
react: 16.7.0
webpack: 4.28.3 
grommet: 2.5.5
```

*Note*: this is a CRA project so Webpack is configured via `react-scripts`.

I checked and I do have these lines from #2735 in my `node_modules/grommet/package-json`:

https://github.com/grommet/grommet/blob/d280fef6c254fb2f9f4d8035a87dc44b49da9820/package.json#L7-L9

**Comment by robinmetral** [comment]
Just noticed something: should't the `sideEffect` say:
```
"./contexts/ThemeContext/ThemeContext.js"
```

**Comment by oorestisime** [comment]
ok i am retrying to reproduce this. on the other hand the storybook doesn't fail on build. this seems localized in  CRA

**Comment by oorestisime** [comment]
and i do reproduce.

**Comment by robinmetral** [comment]
### For anyone else running into this issue:

While it's being addressed, a workaround is to use a local copy of `ThemeContext` (as mentioned by @m11m).

 1. From your CRA project root, go to `node_modules/grommet`
 2. Move `contexts/ThemeContext/ThemeContext.js` and `utils/` (dependencies) to your `src/` folder
 3. In `ThemeContext.js`, change the path to the `utils/` directory to `./utils`
 4. `import { ThemeContext } from "path/to/ThemeContext";`

**Comment by oorestisime** [comment]
I digged in a bit more, i think this is a tree shaking issue than a side effect one. Not sure yet. 
A better work around from the one to c/p files around is to use

`import {ThemeContext} from "grommet/contexts"` to import the ThemeContext instead of importing from grommet. 

Digging more to find why this is happening.

**Comment by robinmetral** [comment]
Thanks @oorestisime

**Comment by mmmoli** [comment]
@oorestisime I had to use

`import { ThemeContext } from 'grommet/contexts/ThemeContext/index'

 but I can confirm that this method worked in Gastby's production build.

**Comment by oorestisime** [comment]
Hello,

With the recent release everything should be working back as they should. No need to import from the full path i think but i can't try this right now. Can you confirm this with me?

**Comment by mmmoli** [comment]
@oorestisime Confirmed this is working with 2.6.5:

`import { ThemeContext } from 'grommet'`

**Comment by oorestisime** [comment]
Excellent! 
Once again thanks to everyone who contributed to the resolution of this bug!

**Comment by AshleyCheny** [comment]
I am encountering same issue in prod build using:
react: 16.13.1
grommet: 2.15.0
webpack: 4.44.1
typescript: 4.0.2

Importing in the following way does fix the issue, but want to check if there is any change in grommet 2.15.0 that introduces this error again.

`
import {
  ThemeContext
} from 'grommet/contexts'
`

**Comment by jcfilben** [comment]
Hi @AshleyCheny I looked through the changes between grommet 2.14 and 2.15 and I wasn't able to find anything that I thought might be causing this. Still looking into it, but let us know if you have any other insights into what may be causing the problem
