### ISSUE TITLE
Select box color

### ISSUE THREAD

**Issue by ibha** [grommet/grommet#267]
![chrome](https://cloud.githubusercontent.com/assets/11291084/11682912/a8f2d468-9e8d-11e5-8714-064ba3e02532.png)
![mozilla](https://cloud.githubusercontent.com/assets/11291084/11682911/a8f1c078-9e8d-11e5-8b1f-c04a1228e937.png)

Select box has blue border in Chrome and black in Firefox

**Comment by jwijay** [comment]
This no longer appears to be an issue in Firefox or Chrome.
