### ISSUE TITLE
Issue with grommet Select in Firefox

### ISSUE THREAD

**Issue by if14b007** [grommet/grommet#2675]
When using the Select component and rendering the selected options inside of it (as shown in the Grommet storybook "**SeasonsSelect**" where you can also see the error), the selected options cannot be removed. I assume this is because the Select component is a button and other buttons shouldn't be rendered inside of it.

### Expected Behavior

Selected options should be removeable when rendered inside the SelectBox.

### Actual Behavior

When clicking on a selected option, the Select dropdown opens.

### URL, screen shot, or Codepen exhibiting the issue

https://storybook.grommet.io/?selectedKind=Select&selectedStory=Seasons&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

### Steps to Reproduce

1. Select a seaon
2. Click on the X to remove it

### Your Environment

Firefox 64.0

**Comment by ericsoderberghp** [comment]
I agree with your assertion that Buttons should not be rendered inside of Buttons. See https://stackoverflow.com/a/39386695.

**Comment by mrebb** [comment]
@if14b007 Tried with FF 66.0.3 on Mac and couldn't reproduce the issue. Do you still see this issue?

**Comment by if14b007** [comment]
No, seems to be fixed now. Thanks guys!
