### ISSUE TITLE
border-radius on FormField error border

### ISSUE THREAD

**Issue by joserocha3** [grommet/grommet#2681]
Is there a way to set the `border-radius` on the error border of a `FormField` component?

### Expected Behavior

Provide a `formField` theme property of `round` or something similar. Or add `extend` property, currently it is not implemented.

### Actual Behavior

Cannot set `border-radius`.

### URL, screen shot, or Codepen exhibiting the issue

This is the border that needs a radius.

![screen shot 2019-01-20 at 8 49 53 pm](https://user-images.githubusercontent.com/11415340/51450160-27189b00-1cf5-11e9-9d02-f99c19808c3e.png)

**Comment by ericsoderberghp** [comment]
The default FormField theme doesn't have a full rectangle border, just a single line below the input field. https://storybook.grommet.io/?selectedKind=FormField&selectedStory=Help%20and%20error&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
The border radius on TextInput can be controlled with `theme.global.control.border.radius`.
Is the screenshot image shown from a different theme? Can you provide a little more context, or a CodePen?

**Comment by MikeWalrath** [comment]
@joserocha3 does Erics comment above help resolve your issue? Do you have any other questions?

**Comment by MikeWalrath** [comment]
@joserocha3 I will be closing this issue. Please feel free to reopen if you have additional questions.
