### ISSUE TITLE
Select onChange event should contain target's name and id

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#2684]
A vanilla select form component in React would function like the following
```javascript
<select
  id="selectid"
  name="selectid"
  onChange={e => console.log(e.target.name, e.target.id)}
>
  <option>test</option>
  <option>test</option>
</select>
```

### Expected Behavior

Grommet's Select component should return id and name properties in the event.

### Actual Behavior

```javascript
<Select
  id={id}
  name={id}
  options={options}
  onChange={(e) => {
    console.log(e.target.name, e.target.id); // doesn't work
  }}
>
  {option => <Box>{option.name}</Box>}
</Select>
```

- Grommet version: v2

**Comment by oorestisime** [comment]
Hm it seems you already get this information, i tried on storybook on SimpleSelect the following onChange:

```
onChange={(e) => {
              console.log(e)
              this.setState({ value: e.option })
            }}
```
and you get `e.target` has the information you mention. maybe i am missing something here though.

**Comment by karatechops** [comment]
You're correct. I updated Grommet to latest and React/DOM to `16.6.0` and it is working now. Not sure if it was a React bug or Grommet but it's working well now. Thanks!
