### ISSUE TITLE
Export a basic Icon in grommet-icons v4

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#2689]
### Expected Behavior

v1 of Grommet provided a base generic `Icon` component, then when the grommet-icons package was extracted out, it was still available there, although undocumented. The base Icon component is useful for any custom SVG logos an app might have, like a brand logo, but still making sure it inherits the Grommet theme colors and sizes. An exported, documented basic `Icon` in v4 and later versions will still be useful.

### Actual Behavior

`Icon` is no longer available. `StyledIcon` can be used as a workaround, but it isn't a part of the rest of the exports and you must use the direct file path for it.

### Steps to Reproduce

1. Try to use `import { Icon } from 'grommet-icons';` It will break because Icon is no longer exported in v4.

### Your Environment

- Grommet version: 3.2.1 vs 4.1.0 of grommet-icons
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
Thanks for taking the time to file the issue.
The source of the problem is in grommet-icons and the fix should be apply on the grommet-icons repo.

**Comment by srallen** [comment]
@ShimiSun Would you like me to move this issue over to the grommet-icons repo?

**Comment by ShimiSun** [comment]
@srallen yes, thank you. for your convenience: https://github.com/grommet/grommet-icons/issues

**Comment by srallen** [comment]
Ok, I've opened it at https://github.com/grommet/grommet-icons/issues/87
