### ISSUE TITLE
Theme is not passed down to components when linking grommet to an external project via npm/yarn link

### ISSUE THREAD

**Issue by petercpwong** [grommet/grommet#2691]
### Expected Behavior

Linking a local copy of grommet's `dist` directory via `yarn link` or `npm link` should work as if installed from npm.

### Actual Behavior

When linking to a local copy of grommet's `dist` directory via `yarn link` or `npm link`, the `theme` prop is not passed down to any of the components. This will break any project linking to grommet locally since all of the components' css depends on `props.theme` being present.

Oddly enough, copying the `dist` directory to your project's `node_modules` works without issues.

 I haven't investigated this issue at length but it might have to do with styled-component's theme context?

### Steps to Reproduce

Build your local copy of grommet 
```
$ yarn build
```
Link local grommet dist dir to your project
```
$ cd ./dist
$ yarn link
$ cd /path/to/other/project
$ yarn link grommet
```
This should break your project

- Grommet version: 2.3.1
- Browser Name and version: Chrome 71
- Operating System and version (desktop or mobile): Ubuntu 18.04

**Comment by petercpwong** [comment]
Setting webpack's `resolve.symlinks` to `false` solved the problem. Closing this issue.

**Comment by ShimiSun** [comment]
Thank you for the follow-up @petercpwong
