### ISSUE TITLE
Locale.getCurrentLocale() always returns fallbackLocale

### ISSUE THREAD

**Issue by eabay** [grommet/grommet#270]
Hi,

Thanks for this great UI framework!

I am evaluating Grommet to use in a local project but Locale is kind of broken I think.

In people-finder repo `locale` is [set](https://github.com/grommet/grommet-people-finder/blob/28db5988a3069cf5614433fede2763d6b8f0d66a/src/js/index.js#L14) from `Locale.getCurrentLocale()` but this method always [returns](https://github.com/grommet/grommet/blob/8009f8ba7542721db6828b126974d1988fdc2a0c/src/js/utils/Locale.js#L19) `fallbackLocale`, and there is no way to get locale from cookies or browser language because `module.exports` is not defined in packed javascript file.

I tried to force locale when calling `Locale.getLocaleData(messages, locale)` like [this](https://github.com/grommet/grommet-people-finder/blob/28db5988a3069cf5614433fede2763d6b8f0d66a/src/js/index.js#L29) but `Locale.getLocaleData()` accepts only one argument and `locale` is [defined](https://github.com/grommet/grommet/blob/8009f8ba7542721db6828b126974d1988fdc2a0c/src/js/utils/Locale.js#L31) with `Locale. getCurrentLocale()` so `messages` attribute of returned value becomes a combination of en-US and the forced locale and `locale` attribute is always en-US.

I wanted to send a PR but it might not be a good idea without consulting you guys about the intensions because I don't have the whole picture yet.

Thanks,
Erhan

**Comment by alansouzati** [comment]
Thanks for submitting this issue @eabay!

If you use Locale while in server side mode, we are currently using the default Locale. This seems wrong to me, but I'm not fully sure how to solve the Locale running on top of node. Feel free to send a PR to fix this issue if you have something in mind that will be able to load the current locale when running in the context of Node. If you run locale in the browser, `module.exports` will be undefined, then we will use the cookie variable to properly load your locale.

I really like the idea of having an extra attribute for `getLocaleData` with the desired locale to use.

Looking forward to hearing back from you...

**Comment by eabay** [comment]
Better to discuss over PR #271
