### ISSUE TITLE
Storybook browser discrepancy 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet#2701]
Difference in display between Edge (on left) and Chrome (right). The dial clock and the line connector not working.

![image](https://user-images.githubusercontent.com/17712467/51873629-2c8c6b80-231b-11e9-851a-cda938171d0d.png)

Might be best to double check IE as well. 

Each component should work consistently across different browsers. 
  

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
CSS transforms on SVG elements don't work on IE. https://css-tricks.com/transforms-on-svg-elements/
Edge is actually working fine for me via browserstack today, but IE11 still exhibits this problem.

**Comment by ShimiSun** [comment]
@MikeWalrath can we close this one?
