### ISSUE TITLE
interactive Table refinements proposal

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#2708]
This issue is intended as a forum to discuss and record some refinements to how users can interact with Table and DataTable. There are two primary aspects to cover:

1. How to make a table row behave like a button or anchor? This would include hover indicators and keyboard accessibility.
2. How to handle selection of table rows? This could build on the prior aspect but adds the need to add an indicator for selection.

For both aspects, allowing table cells to contain other controls, for example embedded links or menus, make the interaction more complicated as depending on where the user clicks within the row, different behavior will ensue. Making sure the indicators and accessibility work with these further complicates things.

What makes this complicated is that `<tr />` has some restrictions that make doing these things not as straightforward as one might like.

We would like to at least support the following flavors:

## single row-wide control

- hover interaction indicator, via background, border, or icon (such as `<Next />`)
- `onClick` or `href`, DataTable: per data item as a value or function, Table: caller's responsibility to use Button or Anchor within each TableCell and set the hover state across the row as appropriate
- accessibility via up/down arrow keys to traverse rows. This allows the tab key to jump to other areas without having to tab through many rows, which scales better. We would likely only provide this via DataTable. Caller's using Table directly would have to wrap with Keyboard.
- no selection needed

## checkbox selection

- hover indicator, via background or border
- one column devoted to a checkbox selection indicator, could be first or last, or maybe any
- clicking anywhere in the row toggles the selection of the checkbox for that row
- if no rows are selected, allow a DropBox style where no checkboxes are shown unless the user hovers over a row and upon clicking one row, all checkboxes are shown
- whether the selection state is controlled by DataTable or not is still a question. If DataTable manages it, we would likely add `selected=[index, ...]` and `onChange(index, selected)` as properties of DataTable, allowing the caller to place the checkbox via a new key within `columns`. If DataTable doesn't manage it, we would need an `onClick` that callers would use to track which rows were selected and explicitly render 
CheckBoxes per row with the right `checked` state. I'm leaning towards the former.

**Comment by oorestisime** [comment]
Thanks for starting this!

> ## single row-wide control
> 
>     * hover interaction indicator, via background, border, or icon (such as `<Next />`)
+1
>     * `onClick` or `href`, DataTable: per data item as a value or function, Table: caller's responsibility to use Button or Anchor within each TableCell and set the hover state across the row as appropriate

I am not sure i understand what you mean here. (what needs to be done in the DataTable) 

>     * accessibility via up/down arrow keys to traverse rows. This allows the tab key to jump to other areas without having to tab through many rows, which scales better. We would likely only provide this via DataTable. Caller's using Table directly would have to wrap with Keyboard.
> 
yes that would be an improvement over current state of things
>     * no selection needed
> 
> 
> ## checkbox selection
> 
>     * hover indicator, via background or border
> 
+1
>     * one column devoted to a checkbox selection indicator, could be first or last, or maybe any
> 
+1
>     * clicking anywhere in the row toggles the selection of the checkbox for that row
> 
+1
>     * if no rows are selected, allow a DropBox style where no checkboxes are shown unless the user hovers over a row and upon clicking one row, all checkboxes are shown
> 

to do this the selection needs to be handled by the DataTable directly. Even if it does i think this can complicate things and not bring much value in return. 

>     * whether the selection state is controlled by DataTable or not is still a question. If DataTable manages it, we would likely add `selected=[index, ...]` and `onChange(index, selected)` as properties of DataTable, allowing the caller to place the checkbox via a new key within `columns`. If DataTable doesn't manage it, we would need an `onClick` that callers would use to track which rows were selected and explicitly render
>       CheckBoxes per row with the right `checked` state. I'm leaning towards the former.

I think handling the selection directly in the DataTable is better. It will probably avoid many bugs and c/p for the users since it is a feature needed quite often!

**Comment by eoliphan** [comment]
This would be great.   Also 'architecturally', I think that moving a lot of this to the Table (and TableCell/Row/etc) would be useful as well.  Such that we can have stuff like
```javascript
<Table selectable ... / <Table selectable='checkbox'...
<Table selected .. onSelect=(...) ..>
```

And have DataTable inherit/compose the visuals/callbacks and focus mainly on data integration (content as array, sorting, paging?, etc.).  That way DataTable is more of a out of the box 80/20 shortcut, but you can easily 'drop down' to the base Table if you have some specific needs that DataTable doesn't line up with.

For me as a 'consumer', SUI-React's approach is pretty well, approachable: https://react.semantic-ui.com/collections/table

**Comment by oorestisime** [comment]
with this https://github.com/grommet/grommet/pull/3310 in should we close this @ericsoderberghp ?

**Comment by nrydevopswatch** [comment]
Hello,

I have been playing around a lot with Grommet and really love it! One thing I need for my current project is "interactive tables." Does this exist with Grommet V2 today? 
My requirements for interactive tables are:
- Being able to click on cells and edit the data in the table.
- Being able to control which users can have this editing capability. 

I'm assuming that if the first requirement is available withing Grommet that the second one can be handles elsewhere.

**Comment by ericsoderberghp** [comment]
Grommet's DataTable let's you put whatever you want inside a table cell, check out the `columns={[{ render }, ...]}` property. You could put a control outside the table to toggle whether it is in editing mode and then have your column render properties render input controls, like `TextInput`. I don't have an example of this. We don't tend to build our sample applications with this style of editing. A pattern we use is to click a row to bring up a Layer with a Form in it. That allows help text, validation messaging, etc.

**Comment by IanKBovard** [comment]
im curious if we can close this issue. I see a lot of the functionality discussed here in dataTable.

**Comment by ShimiSun** [comment]
Linking to the design--system discussion https://github.com/hpe-design/design-system/issues/800

The bulk of these items on this list on DtatTable, feel free to file separate PRs on more specific or fresh issues that are desired
