### ISSUE TITLE
Checkbox within FormField does not have margins

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet#2709]
When Checkbox is in FormField it does not have margins. Please see the attached screen:

![image](https://user-images.githubusercontent.com/3382143/51988262-78334680-24ce-11e9-99af-4642d8d6f8fb.png)

In StoryBook is it OK

**Comment by oorestisime** [comment]
Are you using the `pad` property of the form field? or maybe you can share the code leading to this in a codesandbox?

**Comment by nomadus** [comment]
Hi, I did not use pad property, shouldn't it be enabled by default?
The example is here https://codesandbox.io/s/l2j98kk467

**Comment by nomadus** [comment]
Here is code. When it is CheckBox is in FormField, there is no pad, but when it is used with version #2, it is Ok
`<Form>
	<FormField pad>
	  <CheckBox />
	</FormField>

	<FormField
	  name="subscribe"
	  component={CheckBox}
	  pad
	  label="Subscribe?"
	/>
  </Form>
 `

**Comment by oorestisime** [comment]
Wait but is it meant to be used with a child like that? i am not sure :/ Maybe @ericsoderberghp can help here

**Comment by ShimiSun** [comment]
the second option looks good to me.
@oorestisime we have the same example as the second option in storybook https://storybook.grommet.io/?selectedKind=Form&selectedStory=All&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

```
  <FormField
            name="subscribe"
            component={CheckBox}
            pad
            label="Subscribe?"
          />
```
 @nomadus anything else you need help with related to this issue?

**Comment by oorestisime** [comment]
yeah but doing like:
```
<FormField pad>
	  <CheckBox />
	</FormField>
```
does not apply the pad

**Comment by nomadus** [comment]
Agree, this happens to Select component as well. I am migrating V1 project to V2, re-writing as you suggest will take extra work.

**Comment by ShimiSun** [comment]
the documentation explains that `pad` on the `FormField` is applied when using `TextInput`, (and it actually pads well after adding `TextInput`), so it wasn't meant to be applied on `CheckBox`.
https://v2.grommet.io/formfield

```pad
Whether to add padding to align with the padding of TextInput.```

**Comment by oorestisime** [comment]
hm i am not sure, there's also some logic around the label in it. 
If you need to have the checkbox as a child then you will need to configure the padding on your own as:

```
<Box pad={{ horizontal: 'small', vertical: 'xsmall' }}>
          <CheckBox id="check-box" label="CheckBox" />
        </Box>
``` 

this is an example on storybook.

**Comment by ShimiSun** [comment]
I'll be closing this issue since there few alternative ways as suggested to achieve the above without the need to extend the component with the pad prop. let us know if you have more comments
