### ISSUE TITLE
Rest throw Origin is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by shuangshan** [grommet/grommet#272]
Does anyone know how to resolve "Origin is not allowed by Access-Control-Allow-Origin" when use Rest get information from other website?

**Comment by eabay** [comment]
This is not something about Grommet Rest.

Maybe you should take a look at [this](http://www.html5rocks.com/en/tutorials/cors/).

**Comment by shuangshan** [comment]
eabay,thanks for your valuable tips.
