### ISSUE TITLE
Enhancement: Would like to have a card stack component

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#2720]
Per the mockup for Ferret 2 we'd like to be able to stack cards on top of each other with about a 10px offset of each so you can flip through each card or at least display that there are additional cards behind the first.

**Comment by ShimiSun** [comment]
@MikeWalrath do we have this one on our templates ideas list?

**Comment by ShimiSun** [comment]
I'll be closing this issue due to a lack of community interest. Feel free to make a contribution or start a discussion around implementation for this issue in case its still relevant.
