### ISSUE TITLE
Failed prop type: Invalid prop `value` of type `number` supplied to `TextInput`

### ISSUE THREAD

**Issue by shai32** [grommet/grommet#2721]
### Expected Behavior

TextInput should support type number or alternatively we should have NumberInput component 

### Actual Behavior

using TextInput with number value throw an error:
```Failed prop type: Invalid prop `value` of type `number` supplied to `TextInput`, expected `string```

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/16700996/52229330-51ee1c00-28bd-11e9-93c6-0970ce73fcc0.png)

### Steps to Reproduce

1. use TextInput with value=3, and you will get the error on console

### Your Environment

- Grommet version: 2.3.1
- Browser Name and version: chorme
- Operating System and version (desktop or mobile): desktop

**Comment by oorestisime** [comment]
this seems to be a duplicate of #2658 that was fixed

**Comment by shai32** [comment]
Thanks!
