### ISSUE TITLE
Meter 'background' option has no effect

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet#2724]
Meter background options do not work

Default grey meter background should turn to the color specified in 'background' prop

Grey background remains visible

### Steps to Reproduce

Code sandbox: https://codesandbox.io/s/nwr032n94m

**Comment by oorestisime** [comment]
There seems to be a relation to highlight at the code but i am not sure what it is yet.
As a quick and temporary workaround you can maybe do

```
values={[
          { value: 100, color: 'accent-2' },
          { value: 30, color: 'black' },
        ]}
```

and play with the values

**Comment by ShimiSun** [comment]
So this might be a misunderstanding, in the codesandbox example you added, the `background` isn't used as a prop for `Meter` like the docs suggested, but as an object within the prop of `values`. 
background- is only the the background color of the space in the meter that isn't utilized with value.
 
if your intention was to set the `color` of the value (and not the meter's background color) to be fixed differently per value please use 
```
values={[
          { value: 100, color: 'accent-2' },
          { value: 30, color: 'black' },
        ]} 
```
like @oorestisime suggested.

But if you want to set only the background color of the Meter use 
```
<Meter
          type="circle"
          background="dark-4" ... />
```
I attached an example of how to use `background` as a prop vs using `color` within `value`
https://codesandbox.io/s/wqpw2yw65w

Note that if the values colors are taking all the real-estate you won't have any space left to show the background color, the background is only displayed when meter values are not taking 100% of the space.

I hope it makes sense, let me know if you have questions.
