### ISSUE TITLE
Can't fetch @types for grommet, 

### ISSUE THREAD

**Issue by Inukares** [grommet/grommet#2725]
I've noticed going through my package.json that the only package missing `@types` is `grommet`. I've tried to run
 ```
npm install @types/grommet
 ```
but failed. I've then checked with:
```
npm view @types/grommet
```
and got back:
```
npm ERR! code E404
npm ERR! 404 Not found : @types/grommet
npm ERR! 404
npm ERR! 404  '@types/grommet' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
### Expected Behavior

`npm install @types/grommet` should succeed, as this package seems to actually have typescript types.

### Actual Behavior

`npm install @types/grommet` failed.

### URL, screen shot, or Codepen exhibiting the issue

```
npm view @types/grommet
npm ERR! code E404
npm ERR! 404 Not found : @types/grommet
npm ERR! 404
npm ERR! 404  '@types/grommet' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Steps to Reproduce

1. `npm install @types/grommet`
2. Profit (?)

### Your Environment
OS: Windows 10
Node version: 10.13.0
Grommet: 2.3.1

**Comment by oorestisime** [comment]
hello,

the `@types` is managed by [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped) but the typescript definitions for grommet are living in the repository directly. 
AFAICT there is no need to install whatsoever to be using them.

**Comment by krismorf** [comment]
`@types/grommet` doesn't exist yet. You can search [here](https://microsoft.github.io/TypeSearch/).

**Comment by Inukares** [comment]
Ok, I guess that may be a subject to change in the future but we certainly can live without it :)

**Comment by oorestisime** [comment]
I am inclined to close this. TS is supported from within the repo i am not sure it makes sense to move it elsewhere.

**Comment by ericsoderberghp** [comment]
agreed
