### ISSUE TITLE
Icon passed into rounded button distorts the button by adding extra space beneath icon

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet#2728]
### Expected Behavior
When trying to create a round button, I expect that the icon would be spaced in the center of the button.
<img width="89" alt="screen shot 2019-02-05 at 2 18 31 pm" src="https://user-images.githubusercontent.com/13810084/52298479-ebc7ce80-297a-11e9-9c27-de9fc1f82dc1.png">

### Actual Behavior
The button becomes oblong and the icon has space beneath it.
<img width="84" alt="screen shot 2019-02-05 at 2 18 16 pm" src="https://user-images.githubusercontent.com/13810084/52298466-e5d1ed80-297a-11e9-9ad4-db8227884565.png">
<img width="77" alt="screen shot 2019-02-05 at 2 18 24 pm" src="https://user-images.githubusercontent.com/13810084/52298467-e5d1ed80-297a-11e9-88e2-989a35d9074f.png">

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/30ol4r18vp

### Steps to Reproduce
Create a button inside of a round box with an icon:
```
<Box round="full" background="light-3">
  <Button icon={<Add />} onClick={() => ""} />
</Box>
```

### Your Environment

- Grommet version: 2.3.1
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Either

**Comment by RyanCCollins** [comment]
I asked in the grommet slack whether there is a better way to create a rounded button.  We use them in many places across OneSphere.

**Comment by atanasster** [comment]
Some PRs atom it seems the icon display css changed to inline-block

Here is what I am now using:
```
export default styled(Button)`
  border-radius: 50%;
  &>svg {
    display: block;
  }
`;
```
https://github.com/atanasster/grommet-controls/blob/master/src/js/components/IconButton/StyledIconButton.js

**Comment by RyanCCollins** [comment]
Thanks @atanasster.  It'd be ideal to not have to add additional CSS.  I think this is a bug that could be addressed in grommet.

**Comment by atanasster** [comment]
I also think so - the icons are supposed to be square, not elongated. Wasn't trying to stop a fix, just giving my potential workaround.
After this happened, I had to fix my code in multiple places - I have a DropInput component that has 'widgets' and they all became out of center, also this kind of circle buttons. 
However I am not sure why at some point it was changed to ` display: inline-block;`, probably to fix some other issue. And with the lack of regression tests, it might be dangerous to make such a change during small version revisions.

**Comment by ericsoderberghp** [comment]
I think the change isn't about the inline-block. At least, the default `display` for `<button />` is already inline-block. So, removing our setting of it in StyledButton doesn't change the behavior. We are setting it so that when using it as an `<a />` element gets inline-block instead of just inline. I'm still investigating it.

**Comment by atanasster** [comment]
The inline-block is on the svg - I might be wrongly recollecting on the exact way it started hapenning, but i am sure it was working ok up to a certain point and then suddenly all buttons with icons became off-center and i started using my fix.
