### ISSUE TITLE
How can I use gatsby-link with Grommet v2.0?

### ISSUE THREAD

**Issue by eisque** [grommet/grommet#2738]
Gatsby has a Link component for prefetching data and page. I want to use it in the default menu component and buttons. How can I do it?
Is that possible? if so, any examples are appreciated

**Comment by oorestisime** [comment]
Did you encounter any particular difficulty?

This is working for example.

```
        <Link to="/">
          <Button
            plain
            hoverIndicator
            icon={<Home />}
            label={Home}
          />
        </Link>
```

**Comment by oorestisime** [comment]
I personally wrap Link into a styled component to remove the visited and decoration styling it has:

```
const InternalLink = styled(Link)`
  text-decoration: none;
  :visited {
    color: inherit;
  }
`
```

**Comment by eisque** [comment]
And for the menu component?

**Comment by oorestisime** [comment]
Hm i dont think you can use Link in the Menu component. it is tightly coupled with button and only takes a few parameters as options not components. 
You can use the navigate function although you won't get the prefetch with it.

**Comment by oorestisime** [comment]
Is there anything else we can help you with gatsby + grommet?

**Comment by a-type** [comment]
Seems like you could build your own `Menu` component using `Drop` and use any links you want.

Adding render functions for customizing the behavior of more complex components _may_ be something Grommet would want to look into. But at the same time, all the primitive tools are already provided to craft your own version of the complex things like Menu or DropButton if you need that level of control.

**Comment by oorestisime** [comment]
Seems this could be a nice pattern or a nice blog post. Anything else that comes up your mind about gatsby integration? could try and draft something soon!

**Comment by ShimiSun** [comment]
@MikeWalrath let's list this one as a potential pattern and add it to FAQs as well. other than that we may consider closing this issue unless @eisque has any other questions.

**Comment by woss** [comment]
>  <Button
>             plain
>             hoverIndicator
>             icon={<Home />}
>             label={Home}
>           />

that works to a point. if you would add this to a sidebar navigation menu, you need to add the `activeClassName` or `activeStyle` which do not work with the `theme.active` or any of the grommet theme styles
