### ISSUE TITLE
Type of title and secondaryText in LoginForm

### ISSUE THREAD

**Issue by eabay** [grommet/grommet#274]
Type of those two properties is `React.PropTypes.string` although it can safely be `React.PropTypes.node`. Forcing `string` causes warning messages when `FormattedMessage` passed as value.

I can send a PR if it's OK for you.

**Comment by alansouzati** [comment]
I faced similar issues in the past with exact situations as you are describing. 

I agree with you that it is safe to have these properties as node, but it feels wrong to me.

Can you use the `intl` context variable to translate your content?

You can find in [here](https://github.com/grommet/grommet/blob/master/src/js/components/Tabs.js#L51) how I fixed the issues with `FormattedMessage`.

I don't have a strong opinion about this, but I have an inclination to keep these properties as string.

**Comment by eabay** [comment]
Actually I've tried your suggestion before opening the issue but it doesn't feel right somehow.

I would push little bit more if I have good arguments other than personal but I don't :)

Thanks for your time!
