### ISSUE TITLE
Clicking Select inside DropButton closes Drop

### ISSUE THREAD

**Issue by a-type** [grommet/grommet#2741]
### Expected Behavior

Clicking a Select option inside the Drop should select the item and keep the Drop open.

### Actual Behavior

Drop closes and the Select value does not change.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/lz4kq8v7m

### Steps to Reproduce

1. Open DropButton
2. Select option
3. Witness closing

### Your Environment

- Grommet version: 2.4.0
- Browser Name and version: Chrome 69.0.3497.100 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows, Desktop

I'll look into opening a PR myself to fix this if that's cool. I'm fairly familiar with the problem as it relates to portals and events.

**Comment by ShimiSun** [comment]
>I'll look into opening a PR myself to fix this if that's cool. I'm fairly familiar with the problem as it relates to portals and events.

That's cool, thanks man! let us know how it goes
