### ISSUE TITLE
CheckBox Toggle doesnt display the correct state in v2.4.0

### ISSUE THREAD

**Issue by benbarber** [grommet/grommet#2743]
### Expected Behavior

The toggle should switch and display an on or off state based on the checked prop thats passed to it.

### Actual Behavior

Regardless of the value passed in as the checked prop, the display of the toggle doesnt update.

### URL, screen shot, or Codepen exhibiting the issue

V2.4.0 with the toggle prop set to true on the CheckBox component, doesnt update when the cheked prop changes.
https://codesandbox.io/s/xv3w6pj24p

When rolled back to v2.3.1, it works as expected dispalying the correct state.
https://codesandbox.io/s/18km542o14

### Your Environment

Present in Firefox and Chrome on MacOS

**Comment by oorestisime** [comment]
Thanks for reporting this and sorry for this regression. There's already an issue tracking it here #2742 so i am closing this one. Feel free to add any other feedback on that one
