### ISSUE TITLE
Grommet v2 incompatible with nextjs < 8.0.3

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2749]
Since 2.1.0 a crash happens with nextjs:

Sample project to reproduce: 

https://github.com/atanasster/grommet-contexts-issue

**Comment by oorestisime** [comment]
So to get this right, this happens only in next afaiu right? and it is not related only to announce context?

**Comment by atanasster** [comment]
For me I was able to reproduce only with nextjs, but I am mostly using nextjs anyway

It is not related to AnnounceContext - just shuffling around the order of context hocs in https://github.com/grommet/grommet/blob/524e9fbcfd4a31144e5a7fc256fe0f8ae45f6b05/src/js/components/TextInput/TextInput.js#L401

fixes it for AnnounceContext but makes it happen for some other context

**Comment by atanasster** [comment]
The following works when announce is last in the list (however it seems some of the other hocs are not applied):

```
const TextInputWrapper = compose(
  withFocus({ focusWithMouse: true }),
  withTheme,
  withForwardRef,
  withAnnounce,
)(TextInputDoc || TextInput);
```

**Comment by atanasster** [comment]
Ok, after some investigation:
This PR on Dec3 started using "hoist-non-react-statics" to copy static props.

https://github.com/grommet/grommet/pull/2498/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R48

grommet is using "hoist-non-react-statics": 3.xx -  with ForwardRef Support

however nextjs is using "hoist-non-react-statics": 2.5.5
![screenshot786](https://user-images.githubusercontent.com/6075606/52671352-dc033980-2ee8-11e9-81b6-f57d8a2534ad.jpg)

nextjs apps are using the nextjs version (see the path webpack:///./node_modules/next/node_modules/hoist-non-react-statics/dist/hoist-non-react-statics.cjs.js): 
![screenshot787](https://user-images.githubusercontent.com/6075606/52671358-e02f5700-2ee8-11e9-9da5-4ac7050fbaa5.jpg)

nextjs8 will come with "3.2.0", but for the time being is not ready.

not sure what to do with this issue
1. In the first place, really shouldn't make changes like that in a minor version update
2. Probably was better to assume the lower version of "hoist-non-react-statics" is available, instead of going for the latest without much testing
3. Possibly a small custom version to copy static props bundled with grommet will avoid such issues in the future.

**Comment by oorestisime** [comment]
Thanks for investigating more on this.

(we talked about it on slack but...)

> nextjs8 will come with "3.2.0", but for the time being is not ready.
> 
> not sure what to do with this issue
> 

not sure either. seems grommet needs that hoist package. might need to document somewhere what needs to be done until nextjs 8 is out?

>     1. In the first place, really shouldn't make changes like that in a minor version update
> 

i still believe it is impossible to test every possible building tool for breaking changes especially the ones not used by the team. This is what the community is here for and it is great! 

>     2. Probably was better to assume the lower version of "hoist-non-react-statics" is available, instead of going for the latest without much testing
> 
3.x was needed for forward ref.

**Comment by atanasster** [comment]
It feels by ‘community’ - it means me and a few other users, since there arent many more doing any significant development with v2. Its very time consuming. (jfyi, nextjs is allegedly used by HPE, can point you to some repos)

The rest of the arguments are without merit -  grommet did not ‘need’ the hoist library suddenly in 2.1.0 and it does not need forwardRefs and v3. It was just a choice.

Anyway, i am doing my best trying to suggest a bit more rigorous development and release schedule. I had a ‘fix’ from the get go and just trying to help out, as its a a very nasty issue.

**Comment by atanasster** [comment]
For anyone wondering if this is some obscure bug - all you need is an empty screen with a TextInput to crash a grommet app. Here is the entire code:

```
import React from 'react';
import { Box, Grommet, TextInput } from 'grommet';

const App = () => {
  return (
    <Grommet full>
          <Box>
            <TextInput
        placeholder='enter some text'
        suggestions={[
          { label: '1', value: '1'},
          { label: '2', value: '2'},
        ]}
      />
          </Box>
    </Grommet>
  );
}
```

**Comment by atanasster** [comment]
update - with nextjs 8.0.3 finally able to use grommet hocs

You might want to add a note somewhere that "hoist-non-react-statics" >= 3.x.x is required and specifically next.js < 8.0.3 is not compatible with grommet > 2.0.0

I also updated my next.js page docs: https://grommet-nextjs.herokuapp.com/nextjs

**Comment by oorestisime** [comment]
maybe we can change the issue title so that people can find this easier? (and close it).

Something like `Grommet v2 incompatible with nextjs < 8.0.3 `?

**Comment by atanasster** [comment]
done
