### ISSUE TITLE
Chart crashes if you use CSS sizes for "size" 

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#2750]
Documentation says that size can take "any CSS size" but in fact if you try using a CSS size it crashes.

### Expected Behavior

Doesn't crash
### Actual Behavior
https://codesandbox.io/s/5m2y7w6w4p

proxyConsole.js:72 TypeError: Cannot read property 'replace' of undefined
    at parseMetricToNum (mixins.js:9)
    at Chart.render (Chart.js:246)
    at finishClassComponent (react-dom.development.js:14400)
    at updateClassComponent (react-dom.development.js:14355)
    at beginWork (react-dom.development.js:15222)
    at performUnitOfWork (react-dom.development.js:18789)
    at workLoop (react-dom.development.js:18829)
    at renderRoot (react-dom.development.js:18912)
    at performWorkOnRoot (react-dom.development.js:19809)
    at performWork (react-dom.development.js:19721)
    at performSyncWork (react-dom.development.js:19695)
    at requestWork (react-dom.development.js:19564)
    at scheduleWork (react-dom.development.js:19373)
    at scheduleRootUpdate (react-dom.development.js:20041)
    at updateContainerAtExpirationTime (react-dom.development.js:20069)
    at updateContainer (react-dom.development.js:20126)
    at ReactRoot.render (react-dom.development.js:20422)
    at eval (react-dom.development.js:20559)
    at unbatchedUpdates (react-dom.development.js:19924)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:20555)
    at Object.render (react-dom.development.js:20624)
    at evaluate (VM11169 index.js:21)
    at de (eval.js:45)
    at e.value (transpiled-module.js:947)
    at e.value (manager.js:345)
    at e.value (manager.js:328)
    at compile.js:563
    at g (runtime.js:62)
    at Generator._invoke (runtime.js:288)
    at Generator.e.(anonymous function) [as next] (https://codesandbox.io/static/js/common-sandbox.458a22cf.chunk.js:1:11394)
    at r (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:25)
function.console.(anonymous function) @ proxyConsole.js:72
r.(anonymous function) @ index.js:26
(anonymous) @ compile.js:638
g @ runtime.js:62
(anonymous) @ runtime.js:288
e.(anonymous function) @ runtime.js:114
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
re @ compile.js:380
(anonymous) @ compile.js:715
g @ runtime.js:62
(anonymous) @ runtime.js:288
e.(anonymous function) @ runtime.js:114
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
ie @ compile.js:710
ce @ compile.js:732
(anonymous) @ index.js:51
g @ runtime.js:62
(anonymous) @ runtime.js:288
e.(anonymous function) @ runtime.js:114
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ index.js:40
(anonymous) @ codesandbox.es5.js:392
k @ codesandbox.es5.js:390
D @ codesandbox.es5.js:407
postMessage (async)
(anonymous) @ codesandbox.es5.js:400
(anonymous) @ codesandbox.es5.js:398
j @ codesandbox.es5.js:364
(anonymous) @ index.js:613
(anonymous) @ index.js:538
d @ raven.js:418
requestAnimationFrame (async)
(anonymous) @ raven.js:1153
(anonymous) @ index.js:537
b @ debounce.js:95
x @ debounce.js:144
w @ debounce.js:132
d @ raven.js:418
setTimeout (async)
(anonymous) @ raven.js:1059
w @ debounce.js:135
d @ raven.js:418
setTimeout (async)
(anonymous) @ raven.js:1059
w @ debounce.js:135
d @ raven.js:418
setTimeout (async)
(anonymous) @ raven.js:1059
w @ debounce.js:135
d @ raven.js:418
setTimeout (async)
(anonymous) @ raven.js:1059
w @ debounce.js:135
d @ raven.js:418
setTimeout (async)
(anonymous) @ raven.js:1059
w @ debounce.js:135
d @ raven.js:418
setTimeout (async)
(anonymous) @ raven.js:1059
w @ debounce.js:135
d @ raven.js:418
setTimeout (async)
(anonymous) @ raven.js:1059
(anonymous) @ debounce.js:103
k @ debounce.js:172
(anonymous) @ index.js:168
(anonymous) @ index.js:53
_ @ mobx.module.js:191
n @ mobx.module.js:183
h @ mobx.module.js:607
(anonymous) @ mobx.module.js:587
(anonymous) @ mobx.module.js:3463
hn @ mobx.module.js:3589
fn @ mobx.module.js:3567
(anonymous) @ mobx.module.js:3596
Aa @ react-dom.production.min.js:249
fn @ mobx.module.js:3596
pn @ mobx.module.js:3572
Kt @ mobx.module.js:3011
(anonymous) @ mobx.module.js:226
_ @ mobx.module.js:194
n @ mobx.module.js:183
(anonymous) @ mobx-state-tree.module.js:1993
ae @ mobx-state-tree.module.js:1892
r @ mobx-state-tree.module.js:1915
value @ Model.js:89
value @ Model.js:141
(anonymous) @ State.js:34
Rs @ actions.js:649
value @ FunctionTree.js:98
(anonymous) @ executeTree.js:77
(anonymous) @ FunctionTree.js:247
t @ executeTree.js:13
(anonymous) @ executeTree.js:27
value @ FunctionTree.js:158
(anonymous) @ executeTree.js:77
(anonymous) @ FunctionTree.js:247
t @ executeTree.js:13
n @ executeTree.js:15
(anonymous) @ executeTree.js:32
value @ FunctionTree.js:166
(anonymous) @ executeTree.js:77
(anonymous) @ FunctionTree.js:247
t @ executeTree.js:13
(anonymous) @ executeTree.js:45
(anonymous) @ FunctionTree.js:247
t @ executeTree.js:13
(anonymous) @ executeTree.js:82
s @ FunctionTree.js:318
value @ FunctionTree.js:335
value @ BaseController.js:166
run @ Module.js:36
onChange @ index.js:493
(anonymous) @ index.js:1068
(anonymous) @ index.js:202
e.fire @ editor.main.js:156
(anonymous) @ editor.main.js:1666
(anonymous) @ editor.main.js:948
e.fire @ editor.main.js:156
t.endDeferredEmit @ editor.main.js:989
f.pushEditOperations @ editor.main.js:962
e._innerExecuteCommands @ editor.main.js:1064
e.executeCommands @ editor.main.js:1064
t._executeEditOperation @ editor.main.js:1059
t._type @ editor.main.js:1062
t.trigger @ editor.main.js:1061
t.trigger @ editor.main.js:1659
t.runCommand @ editor.main.js:1346
handler @ editor.main.js:1315
e.invokeFunction @ editor.main.js:1188
e.executeCommand @ editor.main.js:2116
type @ editor.main.js:1668
e.type @ editor.main.js:1347
(anonymous) @ editor.main.js:1612
e.fire @ editor.main.js:156
(anonymous) @ editor.main.js:398
d @ raven.js:418>

### Steps to Reproduce

set size={'20px')
Same happens if you set size={{ width: 'xsmall', height:'20px'}}

**Comment by oorestisime** [comment]
Closing this since it was merged

**Comment by RobertGary1** [comment]
This and tripped me up a couple of times now. The docs online are out of alignment with the released version of Grommet. Would it make sense that the online docs reflect the released version of Grommet? There could be another page that reflects docs for whatever is on master.
