### ISSUE TITLE
[Documentation] Box prop direction is missing options

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2751]
`<Box />` is missing two options in doc.js

 'row-reverse' and 'column-reverse' - they are both valid flex box values and work fine on <Box />

https://github.com/grommet/grommet/blob/524e9fbcfd4a31144e5a7fc256fe0f8ae45f6b05/src/js/components/Box/doc.js#L146

**Comment by ericsoderberghp** [comment]
Just because I haven't seen it used in the real world and am curious, do you have an example of when `row-reverse` or `column-reverse` would be used?

**Comment by atanasster** [comment]
I believe row-reverse was used in v1 for ‘reverse’ like for a button with text and icon. I think those are the kind of use cases - compind components and allow alignment left or right.

Also i think Box should support the full flexbox api, otherwise there will be questions what is supported, what not and why etc. just for completeness
