### ISSUE TITLE
[Documentation] Box width and Height props are missing options

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2753]
For `<Box />` width and height props, the following are valid but missing in doc.js

'xxsmall'
''xxlarge'

https://github.com/grommet/grommet/blob/524e9fbcfd4a31144e5a7fc256fe0f8ae45f6b05/src/js/components/Box/doc.js#L273

**Comment by ShimiSun** [comment]
@britt6612 is taking a look at that

**Comment by atanasster** [comment]
I uploaded my flexbox playground, if you guys want try out most of the the `<Box />` flexbox props : 
https://grommet-nextjs.herokuapp.com/flexbox

**Comment by ShimiSun** [comment]
@atanasster I've copied your flexbox comment to #2754, so it won't get lost.
Thanks for filing this issue.
