### ISSUE TITLE
Enhance support  for flex-wrap in Box

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2754]
flexbox accepts also wrap='wrap-reverse', this is currently not supported by `<Box />`

this one is not just documentation and PropTypes, it needs some small code changes

**Comment by ShimiSun** [comment]
@atanasster thank you for filing the issues, it will help us track and tackle

**Comment by ShimiSun** [comment]
from @atanasster #: I uploaded my flexbox playground, if you guys want try out most of the the `<Box />` flexbox props :
https://grommet-nextjs.herokuapp.com/flexbox #2753

**Comment by ShimiSun** [comment]
@atanasster loved the flexbox simulator, thanks!
