### ISSUE TITLE
Accordion component has unexpected overflow

### ISSUE THREAD

**Issue by michaelplazek** [grommet/grommet#2757]
### Expected Behavior
The Accordion should not be in a scrollable container.

### Actual Behavior
The Accordion has y-overflow, even when it doesn't have to.

### URL, screen shot, or Codepen exhibiting the issue
Here is the behavior in the example in our app.
![chrome-capture 5](https://user-images.githubusercontent.com/28572118/52664656-ce3cbc80-2ec6-11e9-8d87-5e60da7b5982.gif)

You can also observe the issue in the Storybook example linked to from the Grommet site:
https://storybook.grommet.io/?selectedKind=Accordion&selectedStory=Simple&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

### Steps to Reproduce
1. Hover over the Accordion
2. Scroll

### Your Environment
N/A

- Grommet version: 2.4.0
- Browser Name and version: Chrome - 72.0.3626.96 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): macOS Mojave - 10.14.2 (18C54)

**Comment by ericsoderberghp** [comment]
Agreed. It should be the caller's prerogative to decide whether the container has any overflow.

**Comment by ShimiSun** [comment]
Thanks for filling the issue & the corresponding PR :)
