### ISSUE TITLE
Chart could use labels

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#2760]
Its exceedingly difficult to get labels to match exactly chart bars. The text changes with locale and screen size affects the bar positions. If you get it aligned in one scenario it won't be in another.

Need to do this...
![image](https://user-images.githubusercontent.com/3485567/52677373-7449f000-2ee2-11e9-9a21-2650e4732e49.png)

**Comment by ericsoderberghp** [comment]
You could do this: https://storybook.grommet.io/?selectedKind=Chart&selectedStory=Labelled&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by ShimiSun** [comment]
Any further actions for this issue? @RobertGary1 were you able to achieve your required design?

**Comment by IanKBovard** [comment]
@RobertGary1 was ericsoderberghp able to address your issue?

**Comment by ShimiSun** [comment]
Thanks for reporting, Chart had come a long way with enhancements and improvements, feel free to reopen the issue if needed.
