### ISSUE TITLE
[Documentation] Box prop 'gap' is missing options 

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2761]
`<Box />` is missing 'gap' options:

'xxsmall' 
('xxlarge' doesnt seem to be working)

https://github.com/grommet/grommet/blob/2a232077587b5c8b7d99894148876c6905b93210/src/js/components/Box/doc.js#L175

**Comment by ShimiSun** [comment]
@britt6612 is taking a look at this issue. not sure why she can't be assigned.
