### ISSUE TITLE
Exporting with `module.exports` in ES6 modules

### ISSUE THREAD

**Issue by eabay** [grommet/grommet#278]
I see you guys switching to ES6 syntax but still using `module.exports` to export modules instead of `export`. Is this intentional?

```js
import React, { Component } from 'react';

export default class GrommetComponent extends Component {}
```

**Comment by ericsoderberghp** [comment]
That was not intentional. We were focused on the React Component class aspects. Your suggestion  is a good one. Pull requests gladly accepted.

**Comment by eabay** [comment]
And one more before getting my hands dirty...

What about static properties?

http://babeljs.io/blog/2015/06/07/react-on-es6-plus/
https://github.com/jeffmo/es-class-fields-and-static-properties

```js
import React, { Component } from 'react';

export default class GrommetComponent extends Component {
  static propTypes = {};

  static defaultProps = {};
}
```

**Comment by ericsoderberghp** [comment]
Take a look at Button.js to see how React propTypes and defaultProps are handled.

**Comment by eabay** [comment]
I know. I just suggested to move them up inside class declaration and wanted to know how you think about that.

I deep dive into the codebase and trying to understand internals and your intentions.

Another thing is that you prefer to create bindings to class methods in constructor. Using ES7 function bind syntax would help to reduce work to accomplish the same but it's still experimental although babel supports it. Not using it in this project might be choice but I would prefer to use it.

**Comment by ericsoderberghp** [comment]
We were intentional about adopting ES6 but holding off on ES7 until it solidified more. I agree that the function binding stuff in constructor() is annoying boilerplate.

**Comment by eabay** [comment]
That was the thing I want to hear!

I'll send a PR.

Thanks.
