### ISSUE TITLE
Themes issues - new

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2781]
A tool to check themes (elements invisible in dark/light combinations):

https://grommet-nextjs.herokuapp.com/themes-status

initial findings:
'dark' - 4 issues
'aruba' - 2 issues
'dxc' - 2 issues
'grommet-v1' - 1 issue
'hp' - 2 issues

This expands on the older issue 'Theme issues', also 'grommet' has been fixed since.

**Comment by ShimiSun** [comment]
linked to #2471

**Comment by atanasster** [comment]
added tests for CheckBox and RadioButton theming:

'dark' - 12 issues
'aruba' - 7 issues
'dxc' - 7 issues
'grommet-v1' - 7 issue
'hp' - 7 issues

**Comment by atanasster** [comment]
just in case it was missed - there is a hint for each ERROR text status - where you can see if the issues is the color of text, border or icon

**Comment by ShimiSun** [comment]
All themes (except hpe) are having isssues.

From
https://grommet-nextjs.herokuapp.com/

Select the following themes to see the issues ie anchor on brand color, arrow on Select component
dxc
grommet
grommet-v1
aruba
dark
hp

**Comment by ericsoderberghp** [comment]
All of the themes have been updated to address the issue details. Unfortunately, the Aruba brand colors are not accessible, but those are their colors. So, we aren't planning to change that. I believe we can close this issue.

**Comment by atanasster** [comment]
thanks for letting me know, tested on the theme status page and all except aruba are ok
