### ISSUE TITLE
focus on text area

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#2785]
c/p from @alansouzati 
```
The focus outline is showing if I click in the textinput
IMHO the focus outline should only show if you are using the tab

if I use grommet 2.3.1 this problem goes away
so for sure was something that changed from 2.3.1 to 2.4.0
```
https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=textinput&module=%2Fsrc%2FTextInput.js

**Comment by ShimiSun** [comment]
contradicts #2687

**Comment by atanasster** [comment]
```
The focus outline is showing if I click in the textinput
IMHO the focus outline should only show if you are using the tab
```
I would disagree - the focus outline is an indicator of where the text input will go, regardless of how the focus was achieved (by mouse of by keyboard). 

Any real world examples where its implemented the way described in this issue (no outline if TextInput focused by mouse click)?

**Comment by oorestisime** [comment]
yeah i also think it makes sense to have the same behavior on mouse click

**Comment by ericsoderberghp** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input sets focus on click of `<input />`,

**Comment by ShimiSun** [comment]
I'll be closing the issue if there is no objection.

**Comment by MikeWalrath** [comment]
Closing. Please feel free to re-open if further discussion is needed.

**Comment by alansouzati** [comment]
Take this for example: https://codesandbox.io/s/rrjz94lj7m

If you open the filter on the left and start selecting things, you will see the outline. this is a regression.

The outline is very distracting and I feel we should only show this if we are using the keyboard.
