### ISSUE TITLE
Feature Request: Image Component should take fallback image

### ISSUE THREAD

**Issue by MaxMillington** [grommet/grommet#2791]
### Expected Behavior

A fallbackSrc prop should be able to be passed to the `<Image />` component. The fallbackSrc should be used if the main src returns anything other than a 200.

### Actual Behavior

Currently, only one src prop can be passed in, and if the link is broken, there will be a broken image.

**Comment by oorestisime** [comment]
I personally not sure if this is a nice addition to Image.
It is a simple component wrapping the img tag and this is a fairly edge case.

Would you have an idea on how to implement this? I think img tag doens't actually support this natively so in my understanding it will require a few modifications in the component.

Some other thoughts on the matter?

**Comment by MaxMillington** [comment]
I don't think it's an edge case, I think it's pretty common to want to have a fallback if for some reason the image src is broken. Regarding whether or not it would be a nice addition, I can't really speak much to that since I'm not overly familiar with what Grommet wants to cover regarding features. 😃 

The implementation in my opinion would not be too complex. `onError()` can already be passed into `<Image />`. The way I have it now, I just have a simple wrapper around `<Image />`, and pass this in as a prop `onError={() => this.setState({ imageMissing: true })}`. On error, I set the state of the wrapper, and then render a different component instead of the `<Image />`.

**Comment by oorestisime** [comment]
oh right ok! i was thinking something more complicated would be needed but just handling it via onError seems legit!
If you have an implementation may i suggest you PR ;) ?
