### ISSUE TITLE
<Calendar /> theme docs

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2802]
add the following theme dependencies:

1. `global.colors.icon`

2. `global.edgeSize` (margin)

3. `global.edgeSize` (padding)

4. `heading.level.4.small.size`

5. `heading.level.4.small.height`

6. `heading.level.4.small.maxWidth`

7. `heading.weight`

**Comment by oorestisime** [comment]
OK i was working on this and i am quite reluctant to start referencing "side-effect" documentation in each component. Not only it is hard to keep track with current implementation it will heavily bloat the docs page without much value. 

The heading for example is the title of the calendar month/year. I am thinking to do something like:

```
'heading.level': {
    description: 'The month/year title is rendered using the Heading level 4 or 3 component. Refer to the heading component for the available options.',
  },
```

This enables user to get the information about the side effect and its up to them to navigate and change the available options.

Same goes for the rest of the options here (margin and pad is for a box container). and it is similar with #2817 #2818

cc @ShimiSun

**Comment by ShimiSun** [comment]
I 100% see the need for the user to know which theme props will impact his app, to avoid misunderstanding and undesired side-effects as well as leveraging this knowledge for style manipulations. But I do agree we have to draw a certain line on how far we should document it. let's discuss it in our next meeting. @atanasster feel free to share more inputs so we can find a mutual purpose.

**Comment by atanasster** [comment]
@ShimiSun - I guess it depends how you look at the 'theme docs'. 
1. I see them as a source of structured information like you - to verify when you change a theme value, what components will be affected. To that end, I created the theme explorer - for example we can see that `global.breakpoint` in a theme affects `<Box />`, `<Layer />` and `<Heading />`  http://grommet-nextjs.herokuapp.com/themes-explorer/global-breakpoints

2. On the other hand, if you view them as just for publication on the web site as textual information, then I can see them being treated as just some text information.  

if the original intent was to have them simply as reference text, then there was no need to go into such details.

I would prefer as much detail as possible, and on the grommet site some properties are collapsed (ie the `<Box />` props that affect `<Calendar />` can be collapsed as they reference another component)

**Comment by ShimiSun** [comment]
I think all global props should be documented as part of the common global props.
My inclination is to allow `calendar.heading` on the theme, so the component could relly on it's own styling and won't need to rely on the behavior of the heading component itself. 
this approach will remove the drilling down to the "side-effect" documentation as @oorestisime described it.
@britt6612, will you like to take a go on that?

**Comment by ShimiSun** [comment]
I believe this issue can be closed, feel free to reopen if you think it should have more attention.
