### ISSUE TITLE
LoginForm initial values

### ISSUE THREAD

**Issue by eabay** [grommet/grommet#281]
It is not possible to give initial values to the fields of LoginForm component. It would be useful to make remember me field turned on by default and preserve the value of username between re-renders.

Any plan to make it possible? Idea how to implement?

**Comment by alansouzati** [comment]
Good point.

If I were to implement this, I would add a prop `data` to LoginForm as in:

```
<LoginForm
  logo={<Logo />}
  title="Product Name"
  secondaryText="Product Secondary Text"
  rememberMe={true}
  forgotPassword={<a>...</a>}
  onSubmit={...}
  errors={["Invalid username or password."]}
  data={{
    username: 'eabay@grommet.io',
    rememberMe: true
  }}
/>
```

Then, inside LoginForm `data` property would be used as provided to pre-fill the form fields. Both of them would be optional.

What about you? How would you implement this?

@ericsoderberghp would love your insights here.

**Comment by eabay** [comment]
I would use the same approach except the name of prop. I personally prefer `defaultValues` or `values` but `data` would be the choice regarding conventions used in grommet.

**Comment by eabay** [comment]
Maybe we should ping @ericsoderberghp
