### ISSUE TITLE
<Box /> row-responsive switch basis for children

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2811]
The following example:
```
 <Box direction='row-responsive'>
  <Box basis='medium'> <----we want this box to be a fixed *width*
  <Box> <- some other box that will fill the remaining parent area when direction is horizontal
</Box>
```

However when on mobile, the basis: 'medium'  will now become a vertical constraint and the Box will have a cut off height, instead of a fixed width. 

It would be best to align the children basis when the parent is switching from `row` to `column`

**Comment by jcfilben** [comment]
Here is a [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-95vrz?file=/index.js) showing the issue.

**I just want to confirm, the desired behavior would be that row-responsive keeps the main axis as the 'row' (the horizontal axis)?**

Right now the way basis is set up, basis is a fixed or relative size along the containers main axis. When direction='row-responsive' and we are in mobile view, it switches from displaying items in a row to displaying items in a column. This causes the main axis to switch to 'column' (the vertical axis). This is when basis is no longer determining the width and instead affecting the height.
Here is an image that helps illustrate this:
![image](https://user-images.githubusercontent.com/54560994/116910348-c336e980-ac02-11eb-9f62-0d13842fada2.png)

**Comment by jcfilben** [comment]
I think the above comments addressed the issue so I am closing for now, but feel free o re-open if you still feel that this is an issue.
