### ISSUE TITLE
[Safari] DataTable - UI

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2815]
I am not planing on using DataTable, but @oorestisime asked for some issues with DataTable, here are a few screenshots from looking at the documentation storybook. 

![screenshot792](https://user-images.githubusercontent.com/6075606/53214495-b02b3680-3601-11e9-9d31-92a5f4408d7e.jpg)

![screenshot793](https://user-images.githubusercontent.com/6075606/53214497-b1f4fa00-3601-11e9-95ad-1e62cc2f76d2.jpg)

**Comment by atanasster** [comment]
yes, Safari :)

**Comment by britt6612** [comment]
@ShimiSun I believe with the changes that were made to data-table also cleaned up the issues that were happening in safari. 

<img width="833" alt="Screen Shot 2019-09-25 at 6 26 48 PM" src="https://user-images.githubusercontent.com/42451602/65649108-6d2fa800-dfc2-11e9-9c22-2371287b4cbc.png">
<img width="800" alt="Screen Shot 2019-09-25 at 6 26 36 PM" src="https://user-images.githubusercontent.com/42451602/65649111-6e60d500-dfc2-11e9-9a0a-269d146def6c.png">
![Screen Shot 2019-09-25 at 11 27 34 AM](https://user-images.githubusercontent.com/42451602/65649113-6f920200-dfc2-11e9-8170-f245aed81a33.png)

**Comment by ShimiSun** [comment]
Let's thank @ericsoderberghp for this one! MERCI 🥇 
Thanks for verifying and adding screenshots @britt6612! 
I'll be closing this issue, feel free to reopen if needed.
