### ISSUE TITLE
<Tabs /> theme doc

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2817]
Tabs also depend on the following theme props:

1. `global.borderSize` for border size

2. `global.colors.border` - border color 

3. `global.edgeSize.small` - for margin

4. `global.edgeSize.small` - for padding 

5. `global.edgeSize.small` - for gap size

**Comment by oorestisime** [comment]
Hm as with range selector #2818 those values seem to be there because of the container using the Box and forwarding the props in there.
This makes me wonder if there are even more props missing based on all the available box properties.

**Comment by atanasster** [comment]
There might be more for some, but for now this is all that my tool detected. 

Maybe create a boxProps in themeDocUtils, so if more are found to add them there?
