### ISSUE TITLE
Can't set theme font-size for TextArea

### ISSUE THREAD

**Issue by halmos** [grommet/grommet#2819]
The TextArea component does not seem to have full theme options. In particular, the `font-size` seems to be set to `inherit`. 
As far as I can tell, the reason for this limitation can be found at: 
https://github.com/grommet/grommet/blob/fd803e9bd3e1c871cd02e14e322cf03b3eb2dd41/src/js/utils/styles.js#L169

For now, it seems that the only way to set the font-size is to wrap the TextArea in another component or element with the font-size set.

**Comment by ShimiSun** [comment]
You can always use `textArea.extend`. I made a quick example (go to TextArea.js)
https://codesandbox.io/s/nrpr9wp1zj
Let me know if you have more questions.

**Comment by halmos** [comment]
Great, thank you. That is very helpful.

**Comment by ShimiSun** [comment]
great, I'm closing the issue, feel free to reopen or file a new issue if needed.

**Comment by talarico43** [comment]
I think, it would be great if TextArea could use the size prop that TextInput uses to set font size and line height

**Comment by ericsoderberghp** [comment]
Good idea.

**Comment by ShimiSun** [comment]
@talarico43 thanks for the suggestion, the enhancement will be available on our next release. 🎉

**Comment by ssolari** [comment]
@ShimiSun specifying a theme size seems to work, however, the docs say 'string'  and specifying a size like '16px' does not work.
