### ISSUE TITLE
LoginForm component remember me field value

### ISSUE THREAD

**Issue by eabay** [grommet/grommet#282]
It is easy to create a remember me field in LoginForm but no way to [set a default](281) or read value.

Feels like value should be passed to `onSubmit` prop as an argument?

**Comment by alansouzati** [comment]
I've added a comment in https://github.com/grommet/grommet/issues/281 that I believe will address the default value issue.

For the read value, you could use the `remembeMe` property of LoginForm:

```javascript
  ...
  _onFormSubmit () {
    if (this.props.rememberMe) {
      ...
    }
  }

  render () {
    return (
      <LoginForm
        rememberMe={this.props.rememberMe}
        onSubmit={this._onFormSubmit}
      />
    );  
  }

```

Please let me know if I'm missing something...

**Comment by eabay** [comment]
I am sorry, I think I failed to express the situation.

Passing a `rememberMe` property perfectly renders a checkbox but renderer component has no control on it like initially turning it on or getting the value when form is submitted. Initial value issue will be solved after #281 but accessing value should be considered as well.

Having a function signature like this on `onSubmit` would be the choice of mine:

```
onSubmit: function ({username: ..., password: ...[, rememberMe: true|false]}) {...}
```

**Comment by alansouzati** [comment]
Fully agree. Let me know if you want me to fix this, or if you are going to send a PR for that.

**Comment by eabay** [comment]
I'll send a PR as soon as I get the chance.
