### ISSUE TITLE
<Button /> icon does not respect theme color

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2820]
### Expected Behavior
when theme.button.color is changed, the icon color should match the label color. 

### Actual Behavior
Button icon currently uses text color, regardless of the theme. The better behavior would be to work like Anchor https://github.com/grommet/grommet/blob/fd803e9bd3e1c871cd02e14e322cf03b3eb2dd41/src/js/components/Anchor/Anchor.js#L46

### URL, screen shot, or Codepen exhibiting the issue
example with Button and Anchor 
https://codesandbox.io/s/y07v9k2mkv

**Comment by britt6612** [comment]
@oorestisime @ShimiSun  currently the button icon depends on the background color for it to be light or dark I can change this so that the icon will take the color of the theme instead of looking for the background color to determine the icon color if this sounds good to you guys I can do this!

**Comment by oorestisime** [comment]
sounds good to me. i wonder whether we should fallback to text though if theme value is not defined.

**Comment by atanasster** [comment]
imho, changing the icon color only for primary is also an issue, and the code should look something like
```
if (icon && !icon.props.color) {
      buttonIcon = cloneElement(icon, {
        color:normalizeColor(color || theme.button.color  || 'text', theme),
      });
    }
```

**Comment by atanasster** [comment]
sorry, we need to account for primary color in theme:
```
if (icon && !icon.props.color) {
  const themeColor = primary ? theme.button.primary.color : theme.button.color;
  buttonIcon = cloneElement(icon, {
        color:normalizeColor(color || themeColor || 'text', theme),
      });
}
```

**Comment by britt6612** [comment]
@atanasster  thankyou I just saw that there was both a primary color in the themes under the button I will account for that as well

**Comment by ShimiSun** [comment]
Thank you for filing the issue! @britt6612 thank you for dedicating time to solve it!

**Comment by ShimiSun** [comment]
Applying a direct fix for this issue requires code changes that might cause backward compatibility issues. Hence, the fix was implemented as part of the new 'kind' Button structure. once the user has `theme.button.default` (along with other kind of buttons `theme.button.secondary` or `theme.button.primary`) defined on the theme, for those types of buttons the color of the icon will respect the theme color. For more context, use https://v2.grommet.io/button
