### ISSUE TITLE
Theme docs - 'border' structure for TextArea and TextInput

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2821]
The format for documenting theme properties would best be the last detail, sometimes the documentation is lumping together properties

Current situation:
TextArea and TextInput docs are:

```
'global.control.border': {
    description: 'The border of the textarea.',
    type: 'object',
    defaultValue: {
      width: '1px',
      radius: '4px',
      color: 'border',
    },
  },
```

desired behavior like Button

```
 'button.border.color': {
    description: `The color of the border.`,
    type: 'string | { dark: string, light: string }',
  },
  'button.border.radius': {
    description: 'The corner radius.',
    type: 'string',
    defaultValue: '18px',
  },
  'button.border.width': {
    description: 'The border width.',
    type: 'string',
    defaultValue: '2px',
  },
```

**Comment by ShimiSun** [comment]
@atanasster, thanks, I appreciate the feedback, and in some cases it does make more sense for me too, but if for example, the border object has 8 possible styling, I think it will be more readable if all the styling are nested within the same object and wouldn't make the docs look too long and scattered.
Another example is a user wanting to see all the possible options of `border` and having it all under the same theme entry is quicker and doesn't require too much navigation. 
Let me know what do you think.

**Comment by atanasster** [comment]
Thanks for the answer @shimi
I am trying to use the theme docs to enable exploration and editing of themes.

So all of the props that are lumped together are a stop for strucured editing. I will show you the tool when its ready, in the meantime probably take it at ‘faith’ - long term it would be much better to have structured documentation of the themes. 

Also in this case already the button.border are strucured so its also a bit of inconsistency.

**Comment by oorestisime** [comment]
I agree with @atanasster here as well. We could create a helper function if the problem is to write them down every time.
It would also be beneficial for my theme-builder or any other tool playing with themes since right now it requires handling JS objects as strings which is sub-optimal.

**Comment by ShimiSun** [comment]
good feedback, thanks guys!

**Comment by ShimiSun** [comment]
@iankbovard will be tackling this one
