### ISSUE TITLE
Can't style selection options in theme

### ISSUE THREAD

**Issue by halmos** [grommet/grommet#2823]
It doesn't seem possible to set the styles of the children components of the Select component. 
Is there a way to address the styles of the `Select`'s children: `SelectOption` and `Text`?

So far I have not found a way to change the font size of the `Text` child component. 

Additionally, it seems as though the `SelectOption` does not inherit the size setting of the parent `Select`.

**Comment by oorestisime** [comment]
Hello,

Have you tried using the children prop of the Select component? Here's an example https://storybook.grommet.io/?selectedKind=Select&selectedStory=Lots%20of%20options&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

Let me know if this corresponds to what you ve been searching!

**Comment by halmos** [comment]
Great, yes, thanks I should be able to use that as a workaround, however I believe that the SelectOption styles should still be targetable from within the theme as well as inherit the Select's size option.

**Comment by ShimiSun** [comment]
@halmos I agree. we'll keep this issue as an enhancement. feel free to make a contribution and help us improve.

**Comment by halmos** [comment]
@ShimiSun great - thanks. I'll take a look in the sourcecode as well.

**Comment by ShimiSun** [comment]
Let us know if you need help getting started @halmos

**Comment by juanlanus** [comment]
I have this, that might be useful for you:
`  select: {
    background: 'dark-1',
    icons: {
      color: 'rgb(238,238,238)',
      margin: '0px 0px',
      down: <FormDown />,
    },
    control: {
      open: {
        color: 'rgb(238,238,0)'
      }
    },
    options: {
      container: {
        pad: 'xxsmall',
        background: 'dark-1'
      },
      text: {
        margin: 'none',
        size: 'small',
        color: 'light-1',
      },
    },
  },
`

**Comment by ShimiSun** [comment]
Thanks for sharing @juanlanus

**Comment by ShimiSun** [comment]
We now allow different customization for the Select options and the options text:
https://v2.grommet.io/select#select.options.container
https://v2.grommet.io/select#select.options.text

I'll be closing this issue, feel free to reopen if anything else needed in this scope or file a new issue.
