### ISSUE TITLE
"disabled" inconsistencies with TextInput and TextArea

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2825]
For disabled state styles: 

`<Button />` - type inputs are applying an opacity style, while the TextInputs are displaying the text in regular font color>

I would expect `<TextInput />` and `<TextArea />` to have disabled styles compatible with `<Select />` inputs

example here:
https://codesandbox.io/s/o5x6qvm8wy

**Comment by oorestisime** [comment]
Right now the disabled prop was handled directly by the html5 tag. i am changing this to enhancement
