### ISSUE TITLE
v2 Table Needs scrollable feature

### ISSUE THREAD

**Issue by episodeyang** [grommet/grommet#2826]
### Expected Behavior

Similar to v1, we need the v2 table to be able to have a scrollable body. @atanasster #1869

### URL, screen shot, or Codepen exhibiting the issue

The v1 table with scrollable={true} can be found here:

https://v1.grommet.io/docs/table/examples?responsive=true&scrollable=true&i-header=true

**Comment by oorestisime** [comment]
Table components just provide the necessary abstraction on top of html5 tags to build your own tables. Maybe you are looking for datatable? https://storybook.grommet.io/?selectedKind=DataTable&selectedStory=Sized%20DataTable&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

Or do you mean TableBody should have a size property as well?? It could probably make sense to move https://github.com/grommet/grommet/blob/master/src/js/components/DataTable/StyledDataTable.js#L35-L42 into TableBody

**Comment by MikeWalrath** [comment]
@episodeyang did the above comment help?

**Comment by MikeWalrath** [comment]
@episodeyang I will be closing this issue. Let us know if you continue to see the issue.
