### ISSUE TITLE
<Button /> minWidth and maxWidth not functional

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#2828]
`<Button />` theme minWidth and maxWidth are not functional:

https://github.com/grommet/grommet/blob/d6c3a7f83c9fc3dea641eafac16ac87ba2121890/src/js/components/Button/doc.js#L141

code sandbox:
https://codesandbox.io/s/w68vxr2787

**Comment by oorestisime** [comment]
Can't find any trace of this to be used besides mentioned in the docs. This is a bug in the docs like some sort of leftover prop or has anybody used this?

**Comment by atanasster** [comment]
no trace of where it came from into the theme docs

**Comment by oorestisime** [comment]
haven't dig in really in detail but there was a commit ?refactoring themes? 7 months ago adding this prop along with the restructure. but i can't find anywhere in the code that this is used this is why i am wondering if this was used somewhere or just a glitch in the restructure.
@ericsoderberghp ? (you commited i think)

**Comment by ericsoderberghp** [comment]
I wish I could recall :(
I scanned through the commit history but didn't find anything that looked promising.

**Comment by oorestisime** [comment]
Ok lets remove them then.
