### ISSUE TITLE
Using `label` prop in Menu to create a aria-label causes errors thrown by react-intl

### ISSUE THREAD

**Issue by eabay** [grommet/grommet#284]
I am using person name for `label`. Menu component uses it for translation and `react-intl` module throws lots of errors like this:

```
[React Intl] Missing message: "ERHAN ABAY" for locale: "tr", using default message as fallback.
```

![image](https://cloud.githubusercontent.com/assets/158772/12025278/ca304b4c-adb5-11e5-8cb8-76badff5a936.png)

```js
<Menu label={user.name}>
  <a onClick={::this.logout}><LogoutIcon /> Çıkış</a>
</Menu>
```

Using the same approach like in #274 can solve the problem and give a more uniform experience.

**Comment by alansouzati** [comment]
Agreed. Are you going to work on this or you want me to go ahead and change this?

**Comment by eabay** [comment]
I'll try when I get time
