### ISSUE TITLE
Dropbutton demo 'close' button doesn't work

### ISSUE THREAD

**Issue by Funcan** [grommet/grommet#2845]
In the demo https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=dropbutton&module=%2Fsrc%2FDropButton.js (No idea how to get version info out of that, sorry) when I click 'choose' then box opens. The close (X) button in that box does nothing however.

### Expected Behavior

I click close, the pop-up box closes.

### Actual Behavior

I click close, the pop-up box ignores me. The close button gets a green box around it but that's it.

Clicking elsewhere on the page closes the popup box.

- Grommet version: Unknown
- Browser Name and version: Chrome linux (Google Chrome 72.0.3626.109 unknown)
- Operating System and version (desktop or mobile): Ubuntu 18.04 desktop

**Comment by oorestisime** [comment]
Agreed, there needs to be an `onOpen` to open as well: here's a proposed example

```
export default class extends Component {
  state = { open: false };

  render() {
    const { open } = this.state;

    return (
      <SandboxComponent>
        <DropButton
          label="Choose"
          open={open}
          onClose={() => this.setState({ open: false })}
          onOpen={() => this.setState({ open: true })}
          dropContent={
            <Box pad="small">
              <Box direction="row" justify="between" align="center">
                <Heading level={3} margin="small">
                  Heading
                </Heading>
                <Button
                  icon={<Close />}
                  onClick={() => this.setState({ open: false })}
                />
              </Box>
              <Text>Content</Text>
            </Box>
          }
        />
      </SandboxComponent>
    );
  }
}
```

**Comment by Funcan** [comment]
Yup, thanks, I tried that in the sandbox and it works as expected

**Comment by oorestisime** [comment]
Feel free to close this since the problem is more in the codesandbox example (and you already opened a PR to fix it )

**Comment by Funcan** [comment]
Fixed by PR
