### ISSUE TITLE
Missing PasswordInput component

### ISSUE THREAD

**Issue by robinmetral** [grommet/grommet#2850]
### Expected Behavior

I'd like to use [`PasswordInput`](https://v1.grommet.io/docs/password-input) :key: 

The docs say to import it on its own:
```javascript
import PasswordInput from 'grommet/components/PasswordInput';
```

### Actual Behavior

```
Module not found: Can't resolve 'grommet/components/PasswordInput'
```
`PasswordInput` doesn't exist in [`src/js/components`](https://github.com/grommet/grommet/tree/master/src/js/components) and isn't exported in [`src/js/components/index.js`](https://github.com/grommet/grommet/blob/master/src/js/components/index.js).

### Steps to Reproduce

 1. Import `PasswordInput`
```javascript
import PasswordInput from 'grommet/components/PasswordInput';
```

### Your Environment

- Grommet version: ^2.5.5

**Comment by oorestisime** [comment]
Which docs are you referring to?

**Comment by robinmetral** [comment]
@oorestisime The [docs page](https://v1.grommet.io/docs/password-input) I linked to in the issue's text.

I was just coming back to say that they were the V1 docs though, I must have mixed them up somehow. Closing this.

Any plan of re-integrating `PasswordInput` in V2? The [article](https://medium.com/grommet-io/technical-migration-from-grommet-v1-to-grommet-v2-df56084e46b1) on migrating from V1 don't mention it.

**Comment by oorestisime** [comment]
Sorry missed the docs page silly me!
Password input is basically `<TextInput type="password" />` in v2. If you want the hide reveal mechanism i can open a codesandbox to show you an example on how to do it.

**Comment by robinmetral** [comment]
That would be amazing @oorestisime! :heart_eyes:

**Comment by oorestisime** [comment]
Here you are https://codesandbox.io/s/7jzo24or0
