### ISSUE TITLE
<Heading /> color prop TypeScript error

### ISSUE THREAD

**Issue by krismorf** [grommet/grommet#2851]
Using the color prop for `light` and `dark` Heading renders a TypeScript error i.e
```jsx
<Heading color={{ dark: 'white', light: 'black' }}>
  Title
</Heading>
```

### Expected Behavior

No errors

### Actual Behavior
TypeScript error
```
Type '{ dark: string; light: string; }' is not assignable to type 'string | ({ dark?: string | undefined; light?: string | undefined; } & string) | undefined'.
Type '{ dark: string; light: string; }' is not assignable to type '{ dark?: string | undefined; light?: string | undefined; } & string'.
Type '{ dark: string; light: string; }' is not assignable to type 'string'.
```

### Your Environment

- Grommet version: 2.5.5

**Comment by krismorf** [comment]
In the [Docs](https://v2.grommet.io/heading) `dark` and `light` are not documented but it is working as expected.

**Comment by ShimiSun** [comment]
We'll need to fix the docs as well as the typescript issue. thank you.

**Comment by ShimiSun** [comment]
Thanks for reporting! issues are fixed and will be available on our next release

**Comment by c3s4** [comment]
Hi, I have same issue with Text component, also with the same error by typescript. I write here because I think is the same problem.

**Comment by ShimiSun** [comment]
@c3s4 thanks for bringing it up! will you be willing to file a separate issue and attache a sandbox that reproduces it?
