### ISSUE TITLE
Enhancement: Would like to provide hover behavior for charts

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#2854]
In v1 Grommet I was able to use tooltip along with hotspot and marker to show a vertical line where the cursor is hovering and then put annotation dots on the line.
For me to migrate my charts to v2 I'd need similar behavior..

![image](https://user-images.githubusercontent.com/3485567/53587885-5fa36400-3b40-11e9-9b40-eab096b47e97.png)

**Comment by ShimiSun** [comment]
v2 doesn't have the tooltip built-in, but here is a good example that addresses rendering of a tooltip https://storybook.grommet.io/?selectedKind=Chart&selectedStory=Scan&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by RobertGary1** [comment]
For a line graph you would need to annotate the line as shown above. (in v1 we had the dots on the line)

**Comment by RobertGary1** [comment]
The vertical line is also probably needed.

**Comment by ShimiSun** [comment]
Reopening for further discussions...

**Comment by ericsoderberghp** [comment]
Did you see the hover interaction and line rendering on the storybook story linked above?

**Comment by RobertGary1** [comment]
Yes, that was what my comment was about below it.

**Comment by ShimiSun** [comment]
I think we need to think about how to leverage the new Tip component for the suggested functionality.

**Comment by jcfilben** [comment]
Closing since this feature is already supported https://storybook.grommet.io/?path=/story/visualizations-datachart-detail--detail
