### ISSUE TITLE
Intention to deprecate RoutedAnchor and RoutedButton

### ISSUE THREAD

**Issue by oorestisime** [grommet/grommet#2855]
### Context

Both RoutedAnchor and RoutedButton are in the components folder exported as meant to be experimental or at least not committing to fully support them.
Reason for this was that both of these components depend on a dependencies or at least functionalities we don't directly control.

### State

- As of the next release of react-router they won't be functional, at least not the way they were. #2652  A kind of hacky way to make them work would be to take a look at this sandbox https://codesandbox.io/s/l5ov5y4269

- Internally in the storybook we started removing occurrences of those buttons

- They are probably only working with react-router and it is not a solution to cover all available routers. In addition there are no tests covering those components hence they might break from one release to another without noticing

### Intention

Since those were not documented and kind of "hidden", it might be a good moment to actually issue deprecate warnings for these components starting from the next release with the intention of removing them in a v3.

Are you using these components? Can you share your use cases? Migrating away shouldn't be difficult and we want to make this migration without any issues.

**Comment by atanasster** [comment]
Excellent way to communicate and deprecate a component, great job. 
Not using the RoutedXx components myself, just wanted to say i really appreciate this (new) way of handling the dev process.

**Comment by alansouzati** [comment]
Great job in the communication indeed.

I'm not using it.

Here is what I've been doing..

`<Anchor as={Link} ... />`

When we created Routed** `as` was not an option in styled components. so today it is fairly easy to use it. I'm totally down to deprecating it.

**Comment by ShimiSun** [comment]
A good example of how a RoutedButton (with history) can be independently implemented can be found here https://codesandbox.io/s/216vvpmlqj RoutedButton.js

**Comment by atreb** [comment]
I would like to see `<Anchor as={Link} ... />` and it does work. However I do see warnings in browser console. I believe the `as` attribute expects string.
<img width="1665" alt="screen shot 2019-03-04 at 4 34 24 pm" src="https://user-images.githubusercontent.com/5122056/53764485-6fea7480-3e9b-11e9-84d0-52cca63db795.png">

**Comment by oorestisime** [comment]
yes there is an open PR to fix this. coming soon!

**Comment by atreb** [comment]
Awesome...looking forward to it!

**Comment by episodeyang** [comment]
@oorestisime I'm looking forward to this PR too! Warning-free finally :)

**Comment by atreb** [comment]
@episodeyang in the short term, I am using Anchor's onClick property to navigate react router 4. eg. `<Anchor label='my link' onClick={()=>{ props.history.push('/some/link'); }}/>` Note this only works with top level component whose props get the history object from the router or else you will have to pass the history to child components. Not ideal, but keeps my browser console warning free for now.

**Comment by episodeyang** [comment]
@atreb this trade-off makes sense 👍

**Comment by atoy40** [comment]
I'm new to grommet, but what i've coded to replace the deprecated component is this :

````
import * as React from "react";
import { RouteComponentProps, withRouter } from "react-router";

import { Anchor, AnchorProps, Button, ButtonProps } from "grommet";

interface RouterLinkProps {
  path: string;
}
const RouterAnchorBase = (props: RouteComponentProps & RouterLinkProps & AnchorProps) => {
  const anchorProps = props as AnchorProps;
  return <Anchor {...anchorProps} onClick={() => props.history.push(props.path)} />;
};

const RouterAnchor = withRouter(RouterAnchorBase);

const RouterButtonBase = (props: RouteComponentProps & RouterLinkProps & ButtonProps) => {
  const anchorProps = props as ButtonProps;
  return <Button {...anchorProps} onClick={() => props.history.push(props.path)} />;
};

const RouterButton = withRouter(RouterButtonBase);

export { RouterAnchor, RouterButton };
```

Any comments are welcome :)

Anthony.

**Comment by ShimiSun** [comment]
@atoy40 thanks for sharing with the community! 
Feel free to check how we replaced RoutedButton in the following pattern https://codesandbox.io/s/216vvpmlqj 
and of course feel free to share a pattern yourself, we'd love more live examples :)

**Comment by atoy40** [comment]
@ShimiSun looks very similar using the withRouter() HOC :) very cool sample apps to learn grommet btw 👍

**Comment by iMerica** [comment]
I think @atoy40's approach is the recommended option because `this.context` (used in @ShimiSun's code) is deprecated.

**Comment by the-spyke** [comment]
Using `<Anchor as={Link} ... />` gives me warning about unknown DOM props, also there're caveats with using icon+label. So, instead of proposed solutions in this issue, I've made myself a hook from router's code as described here: https://github.com/ReactTraining/react-router/issues/7390

**Comment by the-spyke** [comment]
I've [published](https://www.npmjs.com/package/@spyke/react-hook-router-link) extracted hooks from the `react-router` code. They allow you to use the `Anchor` or any other component without `as` or other tricks and with the same behavior which `react-router`'s Link components do:

```js
import { useLinkState } from "@spyke/react-hook-router-link";

<Anchor label="Home" icon={Icons.Home} {...useLinkState("/home")} />
```

Or more advanced:

```js
import { useHref, useGoTo } from "@spyke/react-hook-router-link";

const href = useHref("/home");
const handleClick = useGoTo("/home");

<Anchor label="Home" icon={Icons.Home} href={href} onClick={handleClick} />
```
