### ISSUE TITLE
Breaking change causes multiple Grommet v1 Codepens to not render the UI.

### ISSUE THREAD

**Issue by Ranguro** [grommet/grommet#2864]
### Expected Behavior

It should be rendering the grommet application UI.  

### Actual Behavior

Instead the only visible thing is a white screen. This is also reproducible in all other codepen that were made by @karatechops 

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/grommet/pen/gaEGPY

### Steps to Reproduce

1. https://v1.grommet.io/docs/hello-world

**Comment by ShimiSun** [comment]
@karatechops let us know if you know what is going on here

**Comment by karatechops** [comment]
The pen points to `https://rawgit.com/grommet/grommet/stable/grommet.min.js` which loads v2. Is there a cdn to pull v1 from?

**Comment by ShimiSun** [comment]
not that I'm familiar with, @ericsoderberghp might know.

**Comment by karatechops** [comment]
This one works -> https://codepen.io/karatechops/pen/aMmzoJ?editors=0110

Point to:
https://s3.amazonaws.com/hpe-developer-portal/grommet.min.js
https://s3.amazonaws.com/hpe-developer-portal/grommet.min.css

**Comment by ShimiSun** [comment]
Hi @Ranguro are we all good with this issue? or are you still finding broken links that need attention?

**Comment by Ranguro** [comment]
I'm still finding broken links that need attention. Check the getting started in grommet v1 page. 
https://codepen.io/pen?template=gaEGPY&editors=0010

It would have been nice to implement a workaround that doesn't require other codepens to take action.

**Comment by ShimiSun** [comment]
@karatechops can you please resolve the link issues 👆

**Comment by karatechops** [comment]
Fixed with [#317](https://github.com/grommet/grommet-docs/pull/317) on grommet-docs. To fully implement the fix the CDN links in the [Hello World gist](https://gist.github.com/grommetux/fb257dcd546a58070db9) and [grommetux codepen account](https://codepen.io/grommet/) need to be updated. I do not have access to these.

**Comment by ShimiSun** [comment]
@ericsoderberghp can you please send me the credentials.

**Comment by ericsoderberghp** [comment]
I don't seem to have it. Maybe @MikeWalrath or @alansouzati do?

**Comment by MikeWalrath** [comment]
Not me. @alansouzati ?

**Comment by alansouzati** [comment]
it is the github login. you log with github using the grommet account (you should have it), and the login to codepen and do the necessary work. How are you posting the weekly templates? It should be the same process.

**Comment by ShimiSun** [comment]
@Ranguro looks like it is fixed, can you confirm closing the issue?

**Comment by ShimiSun** [comment]
it is working for me hence I'll be closing the issue. feel free to reopen if you still encounter the problem
