### ISSUE TITLE
SubMenu within Menus

### ISSUE THREAD

**Issue by Rakshaki** [grommet/grommet#287]
![image](https://cloud.githubusercontent.com/assets/16102795/12166844/b50c1200-b54e-11e5-9d0b-de6be96174c7.png)

Hi,

I need to have SubMenus within Menu. Can you let me know if that can be done?

Thanks
Rakshaki

**Comment by bryanjacquot** [comment]
@Rakshaki this should technically be possible using the Grommet menus.  However, this is not a pattern we encourage given the interaction issues with navigating sub-menus and the poor translation of such navigation to mobile.
