### ISSUE TITLE
Custom z-index not applied to modal Layer wrapper

### ISSUE THREAD

**Issue by robinmetral** [grommet/grommet#2872]
I'm working on an app with a full-screen Leaflet map, which has z-indexes ranging from 0 to 600 (to manage different map layers).

I'm tying to integrate Grommet but I've been having problems with positioning Layers on top of the map.

### Expected Behavior

Using a custom z-index (#2499) for the `Layer` component should place it on top.

I'm doing something like this:
```jsx
<ThemeContext.Extend
  value={{
    layer: {
      container: {
        zIndex: "1000"
      }
    }
  }}
>
  <Layer />
</ThemeContext.Extend>
```

### Actual Behavior

Here's the HTML that gets generated:
```html
<div tabindex="-1" class="StyledLayer-rmtehz-0 jBWlj"> <!-- wrapper -->
  <div class="StyledLayer__StyledOverlay-rmtehz-1 gVTfaV"></div>  <!-- overlay -->
    <div class="StyledLayer__StyledContainer-rmtehz-2 iOAJRY">  <!-- container -->
      <a tabindex="-1" aria-hidden="true" class="LayerContainer__HiddenAnchor-sc-1srj14c-0 LMZHJ"></a>  <!-- anchor -->
      <div></div>  <!-- layer content -->
    </div>
  </div>
</div>
```

The container (`StyledLayer__StyledContainer-rmtehz-2 iOAJRY`) has a z-index of 1000, as expected.  
However the wrapper (`StyledLayer-rmtehz-0 jBWlj`) has a z-index of 10.

This results in the entire layer being hidden by the map. If I manually give the wrapper a z-index of 1000, it shows up.

### Your Environment

- Grommet version: 2.5.5
- Browser Name and version: Mozilla Firefox 65.0
- Operating System and version (desktop or mobile): Ubuntu 18.04.2

**Comment by robinmetral** [comment]
Also note that this is only the case for a Layer with [`modal`](https://v2.grommet.io/layer#modal) set as true.

A Layer with `modal={false}` generates the following HTML:
```html
<div class="StyledLayer__StyledContainer-rmtehz-2 bWDQDs"> <!-- container -->
  <a tabindex="-1" aria-hidden="true" class="LayerContainer__HiddenAnchor-sc-1srj14c-0 LMZHJ"></a> <!-- anchor -->
  <div></div> <!-- layer content -->
</div>
```

So it really is about the modal wrapper that should receive the container's custom z-index.

**Comment by oorestisime** [comment]
I hope i understood this right but:

can you try using:
```
layer: {
  zIndex: "1000"
}
```

i think there are two zIndex values in the theme. one for the container and one for the layer applied when it is a modal.

otherwise a minimal example showing this (even a repo) could help

**Comment by robinmetral** [comment]
Thanks @oorestisime, it works!

I was about to suggest a PR to the docs but I realized that it was actually already there:

 - [`layer.container.zIndex`](https://v2.grommet.io/layer#layer.container.zIndex) (which I had seen)
 - [`layer.zIndex`](https://v2.grommet.io/layer#layer.zIndex) (which I hadn't seen)

So if I understand correctly, `layer.zIndex` is for the layer itself and `layer.container.zIndex` is for the container, when `modal={true}`. Maybe we can clarify this.

**Comment by oorestisime** [comment]
The container always get the `layer.container.zIndex`. if modal is true then there's the overlay and you basically set the z-index of the overlay with `layer-zIndex`
