### ISSUE TITLE
Document component prop in FormField and handle onReset event

### ISSUE THREAD

**Issue by bytewoopy** [grommet/grommet#2876]
### Expected Behavior

console.log on submission should return values from input components that are children of FormField just like the StoryBook example.

https://storybook.grommet.io/?selectedKind=Form&selectedStory=All&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

### Actual Behavior

I don't get anything back, empty object.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/l29k1603wm

### Steps to Reproduce

type something into text area, hit Post.

### Your Environment

"dependencies": {
        "@emotion/core": "^10.0.7",
        "grommet": "^2.5.5",
        "grommet-icons": "^4.2.0",
        "laravel-echo": "^1.5.3",
        "prop-types": "^15.7.2",
        "pusher-js": "^4.4.0",
        "react-icons": "^3.4.0",
        "react-spinners": "^0.5.1",
        "react-timeago": "^4.4.0",
        "styled-components": "^4.1.3"
    }
- Browser Name and version: Chrome Version 72.0.3626.119 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10, desktop

**Comment by oorestisime** [comment]
i think you shouldn't pass the textarea as child but as a the component prop. Here's the example in the storybook
`<FormField label="Comments" name="comments" component={TextArea} />`

**Comment by oorestisime** [comment]
So the documentation should probably mention this. And maybe the example needs to be changed as well.

**Comment by atreb** [comment]
I can confirm that if I use component props to specify TextArea or TextInput, then onSubmit handler's event.value gets the form field values and regex validation also works. However I could not get reset button to work in that form.
<Button type='reset' label='reset'/>

I could get the reset button to clear off the form fields only if I have TextInput or TextArea as child to FormField, but then validation does not work nor the form submits.

**Comment by oorestisime** [comment]
Can you post a codesandbox with a reset button and the issue please so i can take a look?

**Comment by atreb** [comment]
https:// https://codesandbox.io/s/3kv7y1z346 has two forms. First one uses component props and the one below it uses TextInput as child to FormField.

**Comment by oorestisime** [comment]
Right ok i get it! i think the problem here is that there is no onReset event handling!
