### ISSUE TITLE
Enhancement: Circular Progress indicator

### ISSUE THREAD

**Issue by mrebb** [grommet/grommet#2882]
Currently Grommet doesn't seem to have any progress indicators or spinner components. There is a `Meter` component but it is not exactly same as a loading progress indicator that Material UI provides.

### Expected Behavior
Something that [Material UI]( https://material-ui.com/demos/progress/#circular-indeterminate) provides.
`Spinner` should overlay the entire view while UI is waiting for data from server or to allow any background processing. 

### Actual Behavior
Currently there is no component to support this functionality

### URL, screen shot, or Codepen exhibiting the issue
https://material-ui.com/demos/progress/#circular-indeterminate

**Comment by ShimiSun** [comment]
Sounds fun, can you share your thoughts on how to embed it in the library?

**Comment by mrebb** [comment]
@ShimiSun Something like example shown below. `Props` can be used to customize `width`, `height`, `color`,etc. Also, to provide different types of indicators, these components can be wrapped in `Box` and based on the `prop` value, respective spinner component can be served.

```
import styled from 'styled-components';
import { Box } from 'grommet';

export const PulseSpinner = styled(Box)`
  width: 40px;
  height: 40px;
  margin: 40px auto;
  background-color: #2f0dde;
  border-radius: 100%;
  -webkit-animation: pulseScaleOut 1s infinite ease-in-out;
          animation: pulseScaleOut 1s infinite ease-in-out;
@-webkit-keyframes pulseScaleOut {
  0% {
    -webkit-transform: scale(0);
            transform: scale(0); }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    opacity: 0; } }
@keyframes pulseScaleOut {
  0% {
    -webkit-transform: scale(0);
            transform: scale(0); }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    opacity: 0; } }
`;
```

**Comment by oorestisime** [comment]
Right, maybe this could be part of a pattern? The idea here is that maybe these kind of components are quite opinionated:

- why circular and not linear?
- why pulsing and not like circular loading?
- how about the color? (although i guess this can be customized with the theme props)

Maybe it would be best to create a pattern with different flavors of progress indicators? Otherwise we might need to have a progress component that takes a variant prop and picks one of the css animations.

**Comment by mrebb** [comment]
I was exactly thinking of second idea that provides a progress component that takes a variant prop to pick of one of the animations like pulse, circular, linear or anything that is supported by progress component. 

Code Sandbox Example [here](https://codesandbox.io/s/r0q6m3n9nn).

**Comment by ShimiSun** [comment]
So it seems like we already have a spinner, can you check out the spinner in this story: and let me know if it works. it uses svg, and shown when you open Highlight. https://storybook.grommet.io/?selectedKind=Accordion&selectedStory=Rich&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel 
@MikeWalrath FYI

**Comment by mrebb** [comment]
This spinner is a `svg` that is wrapped in `Box` component as part of example story. It would be nice if similar can be given as a component to get customised user experience.

**Comment by ShimiSun** [comment]
@L0ZZI your opinion is more than welcome :)

**Comment by ShimiSun** [comment]
@mrebb can you share your idea of a spinner component? were you thinking of using Layer or Drop or any other cool idea?

Regardless, I'll put it here so I won't lose it, I got some useful tips from @L0ZZI today on the style requirement for the spinner in case we are planning to enhance the current SVG from https://storybook.grommet.io/?selectedKind=Accordion&selectedStory=Rich&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel.
* remove static background
* have some longer section with more decay on it
* make it PURPLE :)

**Comment by mrebb** [comment]
I was thinking of more of a layer but a spinner that could allow to wrap any component and provide an overlay experience. Apart from that it would be nice to support some of the props like spinner color, overlay background color, status text to be shown, spinner size, boolean flag for spinner to turn on & off. 
```
<LoadingOverlay
  active={isActive}
  text='Loading your content...'
  color='purple'
  background='white'
  >
  <p>Some content or child components.</p>
</LoadingOverlay>
```
If no child component is wrapped inside `LoadingOverlay` component, it should just act like a plain spinner without overlay. 
```
<LoadingOverlay
  active={isActive}
  color='purple'
  background='white' />
```

**Comment by joehandzik** [comment]
+1 on interest in this. For example, Material UI has both linear and circular designs here, along with methodology behind choosing one or the other: https://material-ui.com/components/progress/

**Comment by ShimiSun** [comment]
@joehandzik we will publish a template that will demonstrate how it can be achieved in the next few days, please make sure you are on our slack channel to get the notification.

**Comment by ShimiSun** [comment]
Hi guys, here is a template idea of how loaders/spinners/shimmer can be achieve using grommet https://codesandbox.io/s/loaders-and-spinners-4jltk 🎉 
Make sure to sign-in to our slack channel to get all of our live updates and pattern announcements!

**Comment by forresthopkinsa** [comment]
So is this going to be merged into master or is it just going to stay in a sandbox? Not sure the standard procedure for new 'patterns' like this

**Comment by YassienW** [comment]
The sandbox is great, but is there a reason to why there is no Spinner/Loading component?

**Comment by ShimiSun** [comment]
@forresthopkinsa , @YassienW thanks for asking. 
We think the loading functionality and rendering are too opinionated per use case and styling requirements, hence the sandbox is showing examples of how it can be achieved with the user to control the styling and the rendering.
