### ISSUE TITLE
DataTable component usage gives warnings for missing unique key prop

### ISSUE THREAD

**Issue by atreb** [grommet/grommet#2883]
### Expected Behavior

Use of column.primary and/or primaryKey prop on DataTable should prevent the warnings from showing up

### Actual Behavior

Seeing warnings on browser console

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/mq8ww899ox
![screen shot 2019-03-05 at 10 13 38 am](https://user-images.githubusercontent.com/5122056/53815634-023c5800-3f30-11e9-8c78-28a1c7bfc3e6.png)

### Steps to Reproduce

1. Open https://codesandbox.io/s/mq8ww899ox
2. Open browser console for the running example
3. reload the browser part of the example and notice the warnings in the console

### Your Environment

- Grommet version: 2.5.5
- Browser Name and version: Chrome 72.0.3626.119
- Operating System and version (desktop or mobile): macOS High Sierra 10.13.6 (17G5019)

**Comment by oorestisime** [comment]
Hello,

i think the problem here is that you didn't specify a property for each column (the action column is missing), hence the key for that column is undefined and provoking issues. 
It is a required property.

**Comment by atreb** [comment]
@oorestisime thanks for the update. The last column in my example is not tied to any property per say since I want to show buttons for the actions. But I can confirm that it works if I specify an existing unused/used property or even set `property=''`.  Thanks for taking the time to look into this.
