### ISSUE TITLE
Improve typescript support by incrementally rewriting core-componets to typescript

### ISSUE THREAD

**Issue by oorestisime** [grommet/grommet#2886]
I ve had a pretty productive discussion with @mikesol today around this! This issue
documents an initial research and proposes an action plan!

## Idea

It's been looming around for a little while and discussed in the slack channel
and in some issues. TS support albeit improving is not optimal in grommet.
One could definetely argue that there is no need to rewrite component logic to
improve TS support but there could be many more benefits from doing so, like
reducing implementation bugs, another layer of tests based on the typings etc.

The changes need to be of incremental nature. Starting a parallel ts branch that
only gets published on v3 will make effort more complicated. In addition we will
pay more attention to breaking changes and actually making sure there are none.

## Things to consider

- This could set a barrier for first time contributors not familiar with typescript
- How far are we going for a rewrite? Do we rewrite Styled*.js files as well?

## Initial research

A [TS branch](https://github.com/grommet/grommet/tree/ts) exists which contains most of @mikesol work on supporting TS components, tooling and setup, and rebased
with current master. It contains many configurations options such as tslint and
modifications in build steps.

It also contains rewrites for components Paragraph, Markdown.

This branch can be the initial setup for things to get going. Tests are failing, most of them
because jest decided to reorder a bunch of things, and some snapshots got renamed to
reflect tsx in the test file. Definetely need to dig a bit more here.

## Suggested action plan

- Get to an acceptable state the TS branch to go through first round of review and then merge.

  - test build process and make sure it doesn't break in production
  - change import paths of most test cases to import each component from full path (Otherwise js files would import ts files and this doesn't work)
  - update tests
  - make sure storybook is running ok

- open an issue to track all the available components and their current state. 

- Call for contributors to pick a component. PR Review Merge Repeat!

  - pick first components that are low level are not dependencies of other internal componetns.
  For example if we start rewriting Box we should make sure that all the components using Box are already on TS. TS can import JS but not the other way around.

- Release a v3 when all the components are on TS.

- Party

**Comment by mikesol** [comment]
Great initiative @oorestisime !
I can't comment much on grommet versioning, but if you are using semantic versioning, this would represent IMO a `patch` bump as there should ideally be no change in functionality.

**Comment by ShimiSun** [comment]
Yes, we are using semantic-versioning https://semver.org/

**Comment by atanasster** [comment]
Excelent plan except doing it on v2 - i would strongly suggest to first stabilize v2 and have those changes for v3.
 I understand its eqsier on the devs to do it on v2 and have the users as beta testers, but the priority should be more on the users.
We really do need first a version of grommet that can be used in production projects.

**Comment by jcfilben** [comment]
At this time I don't think we have enough resources to undertake this effort. We are still committed to improving typescript support but we are doing it through efforts like [rewriting all the tests in typescript](https://github.com/grommet/grommet/issues/5599).
