### ISSUE TITLE
Calendar format should be editable

### ISSUE THREAD

**Issue by Waize** [grommet/grommet#289]
Hi, 

I want to use the calendar-component for a german web application. 
Therefore I need to change the date format to "dd.MM.yyyy" and the week to start on monday. 

Is it possible to make these settings to component-props?

**Comment by alansouzati** [comment]
This seems like a reasonable request. I will add that to our backlog of items.

In the meantime, feel free to send Pull Requests for this.

**Comment by ericsoderberghp** [comment]
We would like to drive as much of the formatting from the locale as possible.

**Comment by ericsoderberghp** [comment]
See also issue #872.
