### ISSUE TITLE
Icon buttons have padding despite being plain

### ISSUE THREAD

**Issue by robinmetral** [grommet/grommet#2898]
I have Buttons without labels, just icons, that I'm rendering in a Box.

I want to reduce spacing between them but the `plain` prop doesn't remove padding.

*Note: could be similar to #1343*

### Expected Behavior

A `Button` with the prop of `plain` shouldn't have padding, as per [the docs](https://v2.grommet.io/button#plain):
> **plain** Whether this is a plain button with no border or padding

### Actual Behavior

| The padding is still set |
| --- |
| ![capture du 2019-03-08 15-49-58](https://user-images.githubusercontent.com/35560568/54036091-062fda80-41bb-11e9-9df5-96990e24fe9b.png) |

### URL, screen shot, or Codepen exhibiting the issue

[Here's a sandbox](https://codesandbox.io/s/q38lo22kzj), navigate to `Button`

### Your Environment

- Grommet version: 2.5.5
- Browser Name and version: Firefox
- Operating System and version (desktop or mobile): Ubuntu desktop

**Comment by ShimiSun** [comment]
Hi @robinmetral ! thanks for letting us know, I suspect that in your example the spacing comes either from the Icons margin or the Box, can you show on the sandbox which spacing you think is coming from the button? I might be missing something.

**Comment by robinmetral** [comment]
Hi @ShimiSun :wave: 

Well from the source it seems that `StyledButton` has padding, if this is what you meant. Screenshots:

StyledButton | StyledIcon
-- | --
![styledbutton](https://user-images.githubusercontent.com/35560568/54044883-5c5b4880-41d0-11e9-9207-4730703257ef.png) | ![styledicon](https://user-images.githubusercontent.com/35560568/54044896-611ffc80-41d0-11e9-86e4-45a0a5c3c0c9.png)

**Comment by ShimiSun** [comment]
yep, I see it now, thanks for reporting.

**Comment by ShimiSun** [comment]
@robinmetral it appears the issue reproduces if you use the `icon` prop, but if you use an icon inside the button it doesn't have additional spacing, see my example https://codesandbox.io/s/189nlwrqr3
I need to see if there is a reason the button allows spacing when using `icon` prop, in the meanwhile let me know if this is a sufficient workaround.

**Comment by robinmetral** [comment]
Definitely a sufficient workaround! Thanks a lot @ShimiSun :rocket: 

Feel free to close this if the bug doesn't need to be addressed.

**Comment by oorestisime** [comment]
So the padding is applied here https://github.com/grommet/grommet/blob/master/src/js/components/Button/StyledButton.js#L121-L129

Here are some screenshots when not applying it and when we do (line height is always needed)

![Screenshot_2019-03-10 Storybook(1)](https://user-images.githubusercontent.com/3874836/54082150-6afd4900-4311-11e9-877c-2e3e33ab047c.png)
![Screenshot_2019-03-10 Storybook](https://user-images.githubusercontent.com/3874836/54082151-6afd4900-4311-11e9-91ee-1b248eb25426.png)

Don't know if this is needed either

**Comment by ShimiSun** [comment]
Fixed! thank you for filing the issue!
