### ISSUE TITLE
InfiniteScroll not rendering additional items

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet#2901]
InfiniteScroll is only rendering the first few items in the array. In my example the array has 2000 items and only the first 30 or so are being rendered, even when I scroll to the bottom of the screen. It is respecting the `step` prop value but not loading additional steps.

### Expected Behavior

Additional items rendered up to the maximum of 2000 in the array.

### Actual Behavior

Only the first 30 items are being rendered.

### URL, screen shot, or Codepen exhibiting the issue

Was not able to reproduce in CodeSandbox.

### Steps to Reproduce

I created a fresh Create-React-App and was able to reproduce the issue with a bare minimum amount of code: https://github.com/markjackson02/grommet-infinite-scroll-issue

### Your Environment

- Grommet version: 2.5.5
- Browser Name and version: Chrome 72.0.3626.119, Firefox 64.0
- Operating System and version (desktop or mobile): Windows 7

**Comment by markjackson02** [comment]
I just tested it on Windows 10 and it works as expected (Chrome 72.0.3626.121 + Firefox 65.0.2)

**Comment by markjackson02** [comment]
Still testing this but one thing is that it seems InfiniteScroll does not play nice when it's wrapped with a <Box fill>

**Comment by Timunas** [comment]
I'm also facing this issue on electron. The Infinite scroll loads the inital items but then the onMore function is not being triggered.

**Comment by hugomn** [comment]
I have the same issue. For me, Infinite Scroll is not working in Internet Explorer. Tested with Internet Explorer 11, using this codesandbox: https://storybook.grommet.io/?path=/story/select--lots-of-options
