### ISSUE TITLE
Layer component Error in Gatsby js

### ISSUE THREAD

**Issue by Ganevru** [grommet/grommet#2906]
I have a starter for [gatsby js](https://github.com/gatsbyjs/gatsby): [gatsby-starter-blog-grommet](https://github.com/Ganevru/gatsby-starter-blog-grommet) based on Grommet - it has an error described here: [gatsby-starter-blog-grommet/issues/4](https://github.com/Ganevru/gatsby-starter-blog-grommet/issues/4)

I wrote about this error: [Grommet Layer component Error #12467](https://github.com/gatsbyjs/gatsby/issues/12467), but there I was recommended to write here, a quote: 

> @Ganevru Looks like the Layer component is trying to access document.

> It is breaking during build because document is not available in a non browser environment and therefore server side rendering is failing. gatsby develop works because we don't do SSR during develop currently.

> I'd recommend opening an issue in grommet/grommet

The error itself occurs if use [Layer component](https://github.com/grommet/grommet/tree/master/src/js/components/Layer) anywhere in the code:

    <Grommet theme={THEMES[themeByThemeType(themeType)]}>

      <Grommet theme={siteTheme}>

        <Layer />

        <GlobalStyle />

        <Box direction="column" align="center">

        ...

In `develop` everything works fine, but when generating the site `gatsby build` the following error occurs:

    error Building static HTML failed for path "/blog/as-you/"

    See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html

    24 |     _this = _Component.call.apply(_Component, [this].concat(args)) || this;

    25 | 

    > 26 |     _defineProperty(_assertThisInitialized(_assertThisInitialized(_this)), "originalFocusedElement", document.activeElement);

     | ^

    27 | 

    28 |     _defineProperty(_assertThisInitialized(_assertThisInitialized(_this)), "layerContainer", getNewContainer());
    29 | 

    WebpackError: ReferenceError: document is not defined

    - Layer.js:26 new Layer
    [lib]/[grommet]/es6/components/Layer/Layer.js:26:1

    - bootstrap:22 c
    lib/webpack/bootstrap:22:1

    - bootstrap:25 Sa
    lib/webpack/bootstrap:25:1

    - bootstrap:30 a.render
    lib/webpack/bootstrap:30:1

    - bootstrap:30 a.read
    lib/webpack/bootstrap:30:1

    - bootstrap:42 renderToString
    lib/webpack/bootstrap:42:1

    - static-entry.js:194 Module.default
    lib/.cache/static-entry.js:194:18

    - bootstrap:24 Promise
    lib/webpack/bootstrap:24:1

    - gatsby-browser-entry.js:11 Promise._resolveFromExecutor
    lib/.cache/gatsby-browser-entry.js:11:1

    - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1

    - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1

    - bootstrap:50 MappingPromiseArray._promiseFulfilled
    lib/webpack/bootstrap:50:1

    - api-runner-ssr.js:6 MappingPromiseArray.PromiseArray._iterate
    lib/.cache/api-runner-ssr.js:6:16

    - bootstrap:67 MappingPromiseArray.init
    lib/webpack/bootstrap:67:1

    error Command failed with exit code 1.

**Comment by oorestisime** [comment]
can you share a markup where this is happening? (Looked for Layer in your starter but failed)
is the layer open on mount directly? 
Because if you could modify your Layer to open not at build (meaning not being open by default) then it should work.

**Comment by Ganevru** [comment]
I understood. Element `layer` should be used only as an element that can be called (by pressing the button by the user, for example), but not as an element open by default. In this case, everything works fine. Thank you @oorestisime !

**Comment by oorestisime** [comment]
Well this is a workaround really since we rely on document for Layer which is not available on SSR. 
On non SSR contexts you could have the Layer open by default!

**Comment by oorestisime** [comment]
## Proposed solution: haven't tested yet

We make use of document here https://github.com/grommet/grommet/blob/master/src/js/components/Layer/Layer.js#L17
Maybe if we just moved that line on `componentDidMount` then we wouldn't have this issue. It seems to be only used on `componentWillUnmount` so it shouldn't affect normal functionality. And document would be available on `componentDidMount`

**Comment by ericsoderberghp** [comment]
Are you suggesting we don't call `createPortal()` during the initial render but instead have `componentDidMount()` call `forceUpdate()` to re-render after constructing the `layerContainer` lazily?

**Comment by oorestisime** [comment]
Yes, but i am not sure if this is going to work
