### ISSUE TITLE
Themed CheckBox check is broken when checked

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#2910]
CheckBox in any non-grommet theme shows the checked icon in the upper left corner of the window.

### Expected Behavior

The checkmark should be displayed within the box.

### Actual Behavior

The checkmark is displayed in the top left corner of the window.

### URL, screen shot, or Codepen exhibiting the issue

![Screen Shot 2019-03-11 at 2 09 03 PM](https://user-images.githubusercontent.com/11637956/54158335-877bad00-4407-11e9-9ff0-d409004128a0.png)

### Steps to Reproduce

Navigate to https://storybook.grommet.io/?selectedKind=Components&selectedStory=All&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

and select a theme.

**Comment by mrebb** [comment]
`position:inherit !important` on `StyledCheckBoxIcon` should fix the issue.

**Comment by ericsoderberghp** [comment]
I'd really prefer to avoid using `!important` in CSS. It always feel like we're doing something wrong.

**Comment by oorestisime** [comment]
I think we can close this now right? Checked on the PRs storybook and the problem no longer shows.
