### ISSUE TITLE
you have issues with your cdn

### ISSUE THREAD

**Issue by arxii** [grommet/grommet#2915]
your library is kinda shitty. but most importantly, you have problems with your cdn ->
<img width="990" alt="Screen Shot 2019-03-12 at 7 39 05 PM" src="https://user-images.githubusercontent.com/3401121/54245407-b9bc0600-44fe-11e9-95e5-8f72fa089f88.png">

**Comment by ShimiSun** [comment]
This issue should be filed with https://github.com/grommet/grommet-site, I moved it to the relevant repo. thanks.
