### ISSUE TITLE
Disable mobile-detect dependency

### ISSUE THREAD

**Issue by chrischen** [grommet/grommet#2917]
Is there any way to disable this so that mobile-detect doesn't get included and gets tree-shaken? As you can see here it is contributing 6.9% of the total bundle size of all of grommet: https://bundlephobia.com/result?p=grommet@2.5.5

My understanding is that it's used to *guess* browser window size to show/hide components on initial server-side render, but this is an expensive library (when minified) for a specific use case.

Possible solutions:

1) Make this a separate import and function call/helper to be used on server render only (and thus can be included in server JS bundles when used with server side rendering and excluded from client side bundles).

2) Use just a little bit of CSS...

**Comment by oorestisime** [comment]
So 2 is not possible, the problem was on the initial rendering so it is not a matter of css. 

## Proposal: not sure if this will work 

- Add the dependency in [externals](https://webpack.js.org/configuration/externals/) (verified and is not in the bundle)
- move the import and logic of mobiie detect in a separate file with commonjs imports that we can surround with try catch. if import is not there on runtime we don't break.
- if user passes a user agent then they will also have to install the dependency

**Comment by ericsoderberghp** [comment]
Sounds reasonable. I also wonder if we could do a light-weight inline version that just had a couple of regular expressions to match the user agent against to handle 99% of the devices being used.

**Comment by chrischen** [comment]
> So 2 is not possible, the problem was on the initial rendering so it is not a matter of css.

I haven't worked with styled-components, but it should support media queries? Can't a media query be used, and thus hide/show/widths of components will be calculated when the CSS is parsed on the browser? Why is there display code being sent from the server anyways?

**Comment by oorestisime** [comment]
SSR does a bunch of things worth noting 

- performance
- SEO
- scaling

and so on. I invite you to search the topic since it is kind of a huge one.

**Comment by chrischen** [comment]
I'm not against SSR, in fact, I use it and require it when selecting any React solutions, but I'm just not totally understanding why the responsive rendering information is needed in the react render function rather than purely done with media queries.

That being said, I think at the least mobile-detect should be an opt-in dependency since many people do not use SSR, and it is quite large a dependency on an optional feature.

**Comment by oorestisime** [comment]
Agreed it should be opt out.

the problem with the initial render of SSR is that it gets to load something on screen and then at 1 second when media queries get in place a flick is happening to rescale everything. Like lets say if the default render is for mobile and you are on a tablet then for a second or less you will get to see a mobile version of the site. i could reproduce this with a version of grommet before the mobile detect addition if you want me to.

**Comment by chrischen** [comment]
Maybe the flickering can be solved by auto-inlining critical CSS where it's needed?

Also it seems like the ResponsiveContext api passes the size information to react, which means people may already be depending on that on the server?

 I'll play around first and get back to this...
