### ISSUE TITLE
Time MaskedInput inside DropButton does not transition between time sections correctly

### ISSUE THREAD

**Issue by Resalith** [grommet/grommet#2918]
### Expected Behavior

Using Time MaskedInput, if I were to click, a dropdown would pop up with the hour, minute or am/pm. When selecting the input for any of this, the next one should become available. For example, if I select hour, the drop would close and the minute drop would come up.

### Actual Behavior

When the MaskedInput is inside a DropButton (Calendar), the drops for the time do not transition automatically. For example, when selecting the hour, the drop closes and I have to select the MaskedInput again for the minutes Drop to pop up.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/pm5rzz78z0

### Steps to Reproduce

In the above SandBox, when selecting the calendar icon, the Calendar DropButton with the MaskedInput inside should pop up. Try selecting a time on the MaskedInput to see mentioned behavior.

### Your Environment

- Grommet version: 2.4
- Browser Name and version: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 7, Desktop

**Comment by mrebb** [comment]
@Resalith added an example story to cover this scenario as part of PR #3012 . I spent time almost fixing it using a different approach but later realized that example provided in code sandbox is actually causing the issue. Please take a look at #3012 for example and let me know if you still see the issue. Creating dropContent inside render function is causing component to remount and loosing focus.

**Comment by ShimiSun** [comment]
Thank you for the collaboration guys! @mrebb thanks for taking a look and resolving it
