### ISSUE TITLE
Calendar component should show days of the week along the top.

### ISSUE THREAD

**Issue by eyesno** [grommet/grommet#2919]
### Expected Behavior

As with most desktop calendar widgets, the calendar component should have a row for the day of the week along the top so that a user can tell at a glance that the 1st falls on a Monday, for example. It also communicates to the user whether the calendar begins on Sunday or Monday. 

### Actual Behavior

There is no day of the week bar, so a user cannot tell what "next tuesday" is without looking at another calendar to compare. 

### URL, screen shot, or Codepen exhibiting the issue

Is this:

![image](https://user-images.githubusercontent.com/204191/54317004-da4c9480-45c0-11e9-94e7-a3b9e69059b8.png)

Should have the M T W T F S S bar. 

: ![image](https://user-images.githubusercontent.com/204191/54316962-b5582180-45c0-11e9-9108-c946004b6d52.png)

### Steps to Reproduce

Use the Calendar widget.

### Your Environment

- Grommet version: 2.5.5
- Browser Name and version: Latest Chrome
- Operating System and version (desktop or mobile): MacOS 10.14.2

**Comment by oorestisime** [comment]
So one thing i haven't thought about is i18n!
I think this  could actually be a pattern instead of adding the functionality. 
@ShimiSun thoughts?

**Comment by ShimiSun** [comment]
I think I was able to workaround the i18n issue, check out my PR @oorestisime

**Comment by L0ZZI** [comment]
Sorry for the late reply but it's always been in the https://github.com/grommet/design-kit 😉. So I tend to agree with the issue. Glad it's fixed.

![Calendar](https://user-images.githubusercontent.com/1753301/54658990-42055280-4a8d-11e9-8e55-8a9a11ecd35a.png)
