### ISSUE TITLE
User Icon lost

### ISSUE THREAD

**Issue by Waize** [grommet/grommet#292]
After updating grommet from 0.4.1 to 0.5.1 is my application complaining that the User-Icon is gone. 
Can you bring it back? 
Found only the user.svg-file in your directories.

**Comment by alansouzati** [comment]
Sorry to hear that @Waize. I tried looking here and I was able to find the user icon.

Are you importing like this?

```javascript
var User = require('grommet/components/icons/base/User');
//or var User = Grommet.Icons.Base.User
<User />
```

**Comment by Waize** [comment]
I'm doing this:

    import UserIcon from "grommet/components/icons/base/User";
    <UserIcon className="control-icon--small logo" colorIndex="grey-4"/>

And as I wrote, the file even does not exist in the icons-directory anymore :(

**Comment by alansouzati** [comment]
Interesting. Let me check that real quick.

**Comment by eabay** [comment]
@Waize I think you are using Grommet directly from git repo.

Icons are not available unless you build them by yourself with `gulp generate-index-icons` if you clone repo.

**Comment by alansouzati** [comment]
thanks @eabay.

Yeah, I can't seem to reproduce this. If you look in the stable branch you will see the icon is there.

https://github.com/grommet/grommet/blob/stable/components/icons/base/User.js

**Comment by Waize** [comment]
I am using npm and as it seems, the icons are there missing. The building process semmed to stopped after Trigger (for example the trophy-Icon is also missing). 
I deleted all npm files and caches locally, but that does not help. 
![trigger](https://cloud.githubusercontent.com/assets/16035154/12265878/00995a62-b940-11e5-993f-03048dad26c3.PNG)

**Comment by alansouzati** [comment]
Thanks for the extra info @Waize. Can you describe how you are using Grommet? Please specify your NPM and Node version.

Also, looking at your path I see a temp folder with a `package.tar`. Can you describe your installation process?

**Comment by Waize** [comment]
OS is win7,
npm version 3.4.1
node verion 4.2.2 

The path you are seeing is just in my local cache-data. That explains the package.tar. 
My installation is done with maven: 
    --- frontend-maven-plugin:0.0.26:npm (npm install) @ Webapplic ---
    [INFO] Found proxies: [proxy{protocol='http', host='proxy.data-experts.de', port=8080}]
    [INFO] Running 'npm install --color=false in   D:\...
etc. 

So the installation will start node, run npm install, afterwards webpack.js and deploying it.
Do you need any further infromation?

**Comment by alansouzati** [comment]
I know that it is probably unrelated, but can you try running `npm install grommet -g` and check if the icon is present in your global installation ?

**Comment by Waize** [comment]
Unfortunately it's still the same issue.

**Comment by alansouzati** [comment]
I can't reproduce this issue. Did you run `npm cache clean` ?

Can you try to update your Node to 5.1 ?

**Comment by Waize** [comment]
Updated Node to 5.1.0, deleted every chache from npm, installed everything new... but I still just have the Icons until "Trigger.js".

Building process doesn't throw any errors.

**Comment by Waize** [comment]
https://registry.npmjs.org/grommet/-/grommet-0.5.1.tgz

**Comment by Waize** [comment]
@bryanjacquot can you please reopen the issue? 
It is not solved yet.
Thanks.

**Comment by alansouzati** [comment]
Yeah, by downloading this tgz i was able to see that the some icons are actually missing. 

We are not creating this compressed file, I wonder if this could be a bug in NPM.

I will try and investigate this. In the meantime you can use grommet stable which is very close to 0.5.1. 

In your package.json change grommet version to the following:

```json
{
  ...
  dependencies: {
    "grommet": "https://github.com/grommet/grommet/tarball/stable",
  }
}
```

**Comment by Waize** [comment]
Hey,
thanks for your support, i really appreciate it. I will try it with the stable version as long the package in npm isn't fixed.
So this issue can be closed.
On Mi., Jan. 13, 2016 at 3:25 nachm., Alan Souza < notifications@github.com [notifications@github.com] > wrote:
Yeah, by downloading this tgz i was able to see that the some icons are actually
missing.

We are not creating this compressed file, I wonder if this could be a bug in
NPM.

I will try and investigate this. In the meantime you can use grommet stable
which is very close to 0.5.1.

In your package.json change grommet version to the following:

{
  ...dependencies: {
    "grommet": "https://github.com/grommet/grommet/tarball/stable",
  }
}

—
Reply to this email directly or view it on GitHub
[https://github.com/grommet/grommet/issues/292#issuecomment-171305305] .[https://github.com/notifications/beacon/APStUhMaSurbMWi3F4ZR6PVk5EgL-l4Iks5pZlXlgaJpZM4HDJ3M.gif]

**Comment by alansouzati** [comment]
Hi @Waize can you try this again with Grommet 0.5.3? I've updated NPM and Node and released a new version of Grommet. It seems now that all icons are present inside the compressed file.

**Comment by Waize** [comment]
Hi @alansouzati, 
the new package seems to be fine! 
Thanks!
