### ISSUE TITLE
Ability to programmatically close Menu/Drop

### ISSUE THREAD

**Issue by MaxMillington** [grommet/grommet#2926]
It would be nice to have the ability to pass in a flag to programmatically open/close components such as `<Menu />`. Currently, if you wanted to close the menu outside of the standard behavior, you would have to manually trigger a mousedown event on the container surrounding the component. 

There should be a `true/false` field that will open and close the `Menu` and `Drop` components

Right now, you have to actually click outside the menu or select an element or do something like `document.dispatchEvent(new Event('mousedown'))` to close the menu

**Comment by ShimiSun** [comment]
Do you mean a similar behavior of https://github.com/grommet/grommet/issues/2884 to `Menu` and `Drop`?

**Comment by MaxMillington** [comment]
@ShimiSun I haven't used the new feature in the Select component, but looking at the PR, I think the new `open` prop will only affect this initial state of the component if I'm not mistaken? I think this is a good feature, but there should also be the ability to simply toggle open and close of `Menu`, `Drop`, and `Select` with a function if the user so chooses. 

E.G. if for some reason there was a use case where the desired effect was that when a user opened a menu on the left side of the page, a menu on the right side of the page opened as well, likewise for Drop

**Comment by oorestisime** [comment]
I think no it should be able to handle any change. if props change there has to be a re-render hence it will close. At least that was what i wanted to do. https://github.com/grommet/grommet/pull/2885/files#diff-19aa4813d5217c4120837104c9b593ffR43

**Comment by MaxMillington** [comment]
In that case, I think the same functionality should be added to Drop and Menu, and DropButton as well come to think of it

**Comment by oorestisime** [comment]
- DropButotn already supports this
- Menu agreed
- For Drop i am not sure it needs to support this. Maybe a closed Drop shouldn't be in the dom in the first place no? I mean we add a div in the dom and we remove it on unmount. if we just hide it then we will pollute the dom for no use case. 
Not sure what @ericsoderberghp or @alansouzati think on this.

**Comment by oorestisime** [comment]
@MaxMillington what are your thoughts here as well?

**Comment by MaxMillington** [comment]
@oorestisime I think that is a good point about the Drop. @alansouzati thoughts? 

But the need for it in Menu is pretty obv/straightforward in my opinion.

**Comment by ShimiSun** [comment]
Since we addressed the enhancement for Menu I'll be closing the issue. @MaxMillington if you still feel like this feature is needed for Drop regardless of the concerns raised by @oorestisime, feel free to reopen the issue. Thank you all for collaborating.
