### ISSUE TITLE
Enhancement: Allow opacity to be set for Image

### ISSUE THREAD

**Issue by Funcan** [grommet/grommet#2928]
Image component doesn't currently allow opacity to be see

### Expected Behavior

```
<Image src="foo" opacity="0.3" />
```
would result in a faded image

### Actual Behavior

```
<Image src="foo" opacity="0.3" />
```
opacity value is ignored

### Your Environment
- Grommet version: 2.5.5
- Browser Name and version: Chrome

**Comment by ShimiSun** [comment]
If you are using a theme this is another way to do it:
https://codesandbox.io/s/3r7nqmzjzq

**Comment by Funcan** [comment]
I don't seem to be able to do that for just some images though - this might be simply because I've no idea what I'm doing, please don't discount that option. Thanks for the example, I'll keep playing and see if I can get anywhere.

**Comment by ShimiSun** [comment]
no worries, I filed a PR that allows the functionality you requested, let's see what the team thinks about having an `opacity` prop.
Out of curiosity, I'd love to see what you are trying to do and not able to, feel free to share a snippet/snadbox.

**Comment by Funcan** [comment]
Fantastic, thanks! Seeing all the moving parts a simple change has to touch was instructive.
