### ISSUE TITLE
Sticker sheet Checkbox style can be confused with radio button and tri-state checkboxes

### ISSUE THREAD

**Issue by cschlipf** [grommet/grommet#293]
A square within a check box usually meand that there are checked and unchecked sub items (e.g. when using check boxes in a tree or when used as a select-all checkbox in a list like Gmail is doing it) or that the state is undefined.

Another issure is that the the style can also be confused with a radio button.

The Grommet implementation is still using a check mark and the sticker sheet should follow that.

**Comment by bryanjacquot** [comment]
Yes, we need to update the sticker sheet to match the checkboxes used in Grommet.

**Comment by bryanjacquot** [comment]
This has been resolved in the v0.9.5 version of the sticker sheets.
