### ISSUE TITLE
Select does not allow to replace entire value

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#2935]
I have a use case for a select where the design does not have the down icon. I feel the "plain" Select should not have any styles, similar on how we do with the text input.

### Expected Behavior

Select to allow to replace the entire value (e.g. removing the down arrow)

### Actual Behavior
As of today, Select does not have a way to replace the entire value. Icon needs to be present always.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: v2 latest
- Browser Name and version: any
- Operating System and version (desktop or mobile): any

**Comment by ShimiSun** [comment]
I think its a reasonable request.
what about adding an `icon` prop (as Button does), and by default `icon === (true || undefined)` it will show the down button, so there won't be a breaking change, but in case it will be set to false we will remove the icon from the value. just an idea.

**Comment by alansouzati** [comment]
great idea ❤️ 

@ericsoderberghp @oorestisime  thoughts?

**Comment by oorestisime** [comment]
Sounds good to me as well!

**Comment by alansouzati** [comment]
working on a PR for this right now...
