### ISSUE TITLE
Would like more functionality in the "color" docs page

### ISSUE THREAD

**Issue by juanlanus** [grommet/grommet#2938]
### Expected Behavior

{0] As a Grommet newbie I would like to see the colors of the theme I'm using, or at least the colors of all the available themes like for example "dark". 
[1] Also, I would like to be able to copy a snippet to reference one of the displayed colors into my code. 

### Actual Behavior
[0] Only the default theme colors are displayed. 
[1] Only the #RGB part of the code is shown

### URL, screen shot, or Codepen exhibiting the issue
https://v2.grommet.io/color

### Steps to Reproduce
1. Open the color page with a purpose, like referencing a theme color from within a TextInput
2. Think as a complete newbie.

### Your Environment
Chrome on Ubuntu 18

- Grommet version: 2
- Browser Name and version: Chrome Version 73.0.3683.75 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): desktop Ubuntu 18

**Comment by oorestisime** [comment]
Temporary solution:

0. not very intuitive but you can ?theme=dark in every url i think. while in the homepage that doesn't help much in the colors section you will get what you are looking for.

1. not sure what you mean. copy what exactly?

**Comment by ShimiSun** [comment]
great feedback. thanks for letting us know!

**Comment by juanlanus** [comment]
My issue is with Grommet's v2 docs. I didn't explain it clearly because I was in a hurry.  
I'm aware that v2 is a work in progress, and that we developers most of the times are struggling with bugs and urgent requirements more than with documentation.  
As I really like Grommet I'd like it to have useful docs to foster adoption and increase momentum.  
I think I'm a good test subject because I'm not very good at programming JS, so I try to record the issues I find along my way to become a L33t.  
These might be useful because when we are immersed in a we subject give for granted many details that for the newcomers are far from obvious. I attempt to record the newcomer's view.  
Actually, it would be ideal if anybody could use Grommet without needing to get too involved.  
I envision a big community with many users who can leverage Grommet without delving into the code, and a set of more committed developers who delve deep.  
Think of a hybrid car. Think of the least techie aunt you can think of. The car is as complex as a tech product can be but she can use it being unaware of that.  
This is what good UIs are made of.  
As Grommet is a tool, it has two UIs to think of.  
One is that of the applications made with Grommet.  
The other one is how we the developers see Grommet as a tool.  
Although nobody reads the manuals any more, there must be a good docs set available for the devs to solve their issues at once, not needing Shimi's or Oresti's help on Slack (which is excellent, BTW).  
If you are old enough you might have experienced Underscore or jQuery's docs, concise and to the point, fostering the success of those. On the other hand, YUI had too verborragic pages that dropped readers after a few thousand words.  
I'm here after trying MUI and finding that it required too much involvement to get started while the available information was not that good.  
I'm toying with the idea of getting involved in the writing of Grommet's docs, given that I'm a shitty JS programmer.  
  
That said, I get to the point.  
I was trying to get the gist of the colors thing (actually, the theme thing).  
I found this, which is good but incomplete: 
  https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation
The author agrees with me, there is a "More to come..." at the bottom.  
  
Mi first issue [0] is that if I do what the Basics section says I end up with a theme I'd like to see like this:  
  https://v2.grommet.io/color  
with control samples too.  
My issue [1] is that I'd like to be able to get in the clipboard snippets like those in the [API](https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation#api) section of WWW
like `global.colors.focus` in JS format.  
This issue might stem from my lack of understanding of the whole theme thing.  
  
Well, these are my ideas. tl;dr: want Grommet to be successful by providing excellent docs.

**Comment by oorestisime** [comment]
Lot's of things in your comment! I think we are constantly improving the documentation but i agree there is much improvement to be made!
What could be interesting is to list what __you__ are missing from the docs. I mean do we need to better advertise how to get started? Are the examples difficult to find? When you did read the code what was the use case? Where can we improve there?

I personally suck at documenting, but if there are actionable items we could work on improving the documentation :)

**Comment by juanlanus** [comment]
Orestis, you say you are bad at documenting. Most devs are.  I was.  
This is because as devs we have to laser-focus on the piece of code we are giving birth to, in a flow mind state, disregarding the rest of the universe. Actually, this is a Good Thing.  
Documenting is like UX or Usability, in that the developer has to switch her mindset to the user's, has to wear the user's hat.  
I learned that while participating (many years ago, like in a previous millennium) in discussions of the [STC](https://www.stc.org/), the Technical Writers Guild.  
I was willing to learn about usability. It was interesting to notice that docs (they called "manuals" then) have to be crafted much like UIs.  
  
A docs set requires planning, designing. Like in software architecture, not graphical design.  
To achieve outstanding results with minimal effort it has to cover the most important use cases, like onboarding, or "get the gist".  
  
Also, we need to set a style. For example brief reminder-like snippets (like the current v2 pages) with "read more" links that can be useful for the first time, thus combining reference with education.  
The language has to be screened to devoid it of any words or idioms that might complicate millions :-) of readers from anywhere who struggle with English. Only the simplest, cleanest wording should remain.  
  
When writing the use cases we must wear the user's hat, not the developer's.  
As developers we tend to explain what the software does, while as users we come with a goal ("need to display a list") and would like to do it with the least posible disruption.  

> Disruption: having to switch focus from an interesting coding activity to reading a treatise on lists in order to be able to splash several choices on the UI.  

The treatise might still be there, but hidden behind a "read more" link.  
We should take pride in the users not needing to "read more".  
  
Remember, many users are not forced to Grommet. They are more likely staying if they can find an easy path to their goals (this is how I ot to know Grommet).  
  
I suggest we build a use-cases listing and somehow prioritize them.  
It is not like a FAQ. FAQs are bad in that if a question arises frequently it's because somewhere something is confusing or unclear.  
  
One thing the STC tech writers complained about was to have to write about far-from-awesome features (have you ever pressed F1 for help in Windows?).  
They wished they could influence the software design (the UI) to make it more "explainable" which means more usable.  
This happened because almost always the docs were an afterthought.  
Thinking the docs along with the UI design helps making both much better.

**Comment by juanlanus** [comment]
Oops! Orestis asked for a listing of docs issues and I didn't answer that.  
With code, you can't go to a shitty repo and turn it into a world class application by fixing bugs.  
This is not to say that Grommet's docs are so bad. They are yes a bit skinny but a findable reference.  
IMO a layer is lacking between the intro "a react-based framework that provides accessibility, modularity, responsiveness, and theming in a tidy package" and the components reference.  
IMO some candidate users drop while trying to build such knowledge on their own.

**Comment by oorestisime** [comment]
Thanks for putting all these thoughts here :) I think some people are great at documenting (python-requests) but some of them are not (and i clearly fall in to this category). I ve heard people documenting before implementing which is the documentation driven development which clearly helps building a clean API and great documentation! i would love to talk this on slack but lets keep this issue a bit leaner ;)

> I suggest we build a use-cases listing and somehow prioritize them.
>It is not like a FAQ. FAQs are bad in that if a question arises frequently it's because somewhere something is confusing or unclear.

i think this is a great idea! Do you have an example? Or do you maybe want to work on something like this? Seems quite interesting!

> IMO a layer is lacking between the intro "a react-based framework that provides accessibility, > modularity, responsiveness, and theming in a tidy package" and the components reference.

Do you mean we need an example showing this? like ready apps or actually provide easier access to the patterns?

Overall i also believe there is a improvement to be made on the landing page and documentation. some of it is being tracked here #2896

**Comment by juanlanus** [comment]
In order to do a design of the docs body we need first to characterize the users, called "actors" in use-cases parlance, and "personas" un usability.  
An actor is a user that approaches the system UI with a purpose, her "goal". They are usually named after their function, like "PM" or "Tech Lead" or "Jr Developer" or "Branch Manager".   
"[Personas](https://www.usability.gov/how-to-and-tools/methods/personas.html)" are synthetic users crafted after the real ones.  
In a project there are a few personas defined (like 7 tops) and the UI is designed after them.  
It is customary to give them names, a face, and a set of characteristics to make them more real. The rationale behind is that once their characteristics are set (including personality details) we "interact" with them more consistently. Like for example you don't approach a 50 years old Chinese with a smart NY baseball metaphor.  
See this example, [Clark Andrews](http://www.keepitusable.com/blog/tag/alan-cooper/), created by or around [Alan Cooper, the inventor](https://www.cooper.com/journal/2008/05/the_origin_of_personas).  
<img src="http://www.keepitusable.com/blog/wp-content/uploads/2016/06/ExPersona_Clark2.png" >
I would like if we could develop together a few personas to characterize the Grommet users population.  
Afterwards we could run a poll to ask them a few non-intrusive questions about them. For example, I think Shimmy is asking them how did they got to know Grommet.  
  
Next step would be to enumerate the main goals of those personas against the Grommet, which would lead us into their minimal doc needs.  
Once the docs are set straight then a huge number of users could be handled, like jQuery's, without a proportional growth in Slack activity.

**Comment by juanlanus** [comment]
I have been reading the published docs and a few related commits and issues like #2896  
In #2896 [ericsoderberghp](https://github.com/ericsoderberghp) has a suggestion about patterns, and also seems to perceive some overlap (I do) in https://v2.grommet.io/components and https://storybook.grommet.io/?path=/story/components--all  
For those who are inside the Grommet the functionalities are clear, for those who are new (like me) it's "intruing" like "if I go with this one what am I losing that is in the other one (for some reason there are two, right?)".  
There is also the CodeSandbox, kind of a third version of all the components.

**Comment by ShimiSun** [comment]
@juanlanus can you tell if this is solving the issue you raised? it's still on its beta version, but I want to make sure it answers your needs. https://theme-designer.grommet.io/

**Comment by juanlanus** [comment]
I saw the tool, it't really good. :-)
But my problem is much dumber. 
Using the color tool I can build a theme and paste its code into a file in my project. 
I already managed to download the dark theme and to merge some changes above it. 
My problem starts here: how do I use all those color names, how do I refer to them from within my code?
How do I style a component using that scheme, a component written by me? Not a simple button but for example a grid and its rows. 
By sure I have a problem of not having worked with scheme before, but anyway. 
Thinks that are obvious for those like you that are in. The problem for insiders to communicate is to think like the others, especially without patronizing (it is not happening in Grommet, not at all). 
Actually, my problem is that I have a theme but I don't know how to use it.

**Comment by oorestisime** [comment]
have you had a look at the grommet code? it makes use of the theme and you could get inspired by it. 
Here's an example https://github.com/grommet/grommet/blob/master/src/js/components/Anchor/StyledAnchor.js#L27 you can see the styled component gets the theme in it automatically (props.theme)
let me know if that helps.

**Comment by ShimiSun** [comment]
regarding using the theme values (such as colors), you can see how it works with every template/code that uses a custom theme, check out my recent post on the #i-made-this channel.

**Comment by juanlanus** [comment]
@orestis: Thanks for the link to the Grommet code, I will study it
carefully and it might solve my issue.
Please be aware that I appreciate Grommet very much, that's why I insist on
these issues in an attempt to provide material to enhance the docs at the
noobie level.
Usually the application code is way too smart for normal users, who are
taming JS, React, Grommet, their domain and whatever all at once. Lowering
the initial threshold has a lot of value in terms of acceptance. For
example I switched to Grommet after evaluating the effort needed to go
Material UI. And ReactN after seeing Redux.

**Comment by juanlanus** [comment]
@shimi: I kept thinking of the theme designer in background as a usability
guy, and realized that it's usefulness is hindered by the fact that the
theme is applied to an alien design.
It would be waaay more useful if the styles form (the left hand side of the
page) was applied to a page designed by the user, as if the theme-designer
was a HOC engulfing the designer's components.
This is so because se all desing differently. For example I cram data into
the available real estate, used to build enterprise biz applications, while
some designers foster white space (a blank page is the ultimate design, the
Zen of it).
Thus, allowing the Grommet consumer to run her app under the control of the
theme designer and to tweak its styles on the fly might be, perhaps, an
attractive plus for Grommet.

**Comment by ericsoderberghp** [comment]
In case you weren't aware, you can publish themes created by the theme designer and then plug the published URL into any design created with designer.grommet.io and the design will use that theme. That allows you try the theme across a variety of designs.

**Comment by juanlanus** [comment]
@eric: I am aware, thanks.
What I was suggesting is to build a better tool (someday) allowing the
designer to change the theme and see the effect of the changes on her own
pages, on the fly, in real time.
This would enhance the value of the theme-designer and perhaps Grommet's.
At least, is one of those features that people like to "purchase".

**Comment by ericsoderberghp** [comment]
Great feedback, thanks.

**Comment by britt6612** [comment]
@juanlanus This is related to issue #3330 please feel free again to read the wiki page and let me know what else we can improve on!  👍 

https://github.com/grommet/grommet/wiki/Color-Properties

**Comment by ShimiSun** [comment]
I think we can close this issue thanks to the new wiki page. let me know if you think otherwise.
