### ISSUE TITLE
Tabs appears distorted in Safari 8

### ISSUE THREAD

**Issue by jaitthomas** [grommet/grommet#294]
Tabs and grommet site layout appears distorted in Safari 8. Try the tabs link below in Safari 8.

http://www.grommet.io/docs/hpe/develop/tabs

**Comment by bryanjacquot** [comment]
Safari 8 is not officially supported since the latest version of Safari is 9 and only the latest version is supported (http://grommet.github.io/hpe/docs/browser-support).  But if there is a simple fix, we will explore it.
