### ISSUE TITLE
Accept `{ light: ..., dark: ...}` as Box background color value

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#2940]
This is a request to enhance Box to accept an object for background color. This would allow callers to set an overall `global.colors.background` color at the outer Grommet theme and then have all internal background and text colors automatically adapt to it.

The design example is an app or site that allows the end user to choose a light or dark version of the UI.

I think the key change is to accept the object, choose the appropriate color to use based on the outer background context, and then set the subsequent `dark` context for children appropriately.

**Comment by ShimiSun** [comment]
I believe this issue is solved with the `themeMode` prop https://storybook.grommet.io/?path=/story/radiobuttongroup--simple
