### ISSUE TITLE
Cannot set background color for a button

### ISSUE THREAD

**Issue by midnightcodr** [grommet/grommet#2947]
https://codesandbox.io/s/xvz2jmwooz
I am able to change border radius and color but just **not** the background color. According to the doc on https://v2.grommet.io/button, `border.primary.color` should be the one to change
### Expected Behavior
The button should have a red background.

### Actual Behavior
The button background is transparent.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/xvz2jmwooz

### Steps to Reproduce
https://codesandbox.io/s/xvz2jmwooz

### Your Environment

- Grommet version:
```
  "dependencies": {
    "grommet": "^2.5.5",
   ...
  }
```
- Browser Name and version:
All browsers.
- Operating System and version (desktop or mobile):
Mac OSX Mojave

**Comment by oorestisime** [comment]
Hello,

Did you add the primary prop in your button? Which file should we look in your codesandbox?

**Comment by midnightcodr** [comment]
Forgot to save, sorry. Button.js is the file. Actually you are right, it would work if the `primary` prop is set.
