### ISSUE TITLE
Required flag in FormField not picking up provided value

### ISSUE THREAD

**Issue by MaxMillington** [grommet/grommet#2948]
If you have a `FormField` component and you provide it a value (e.g. say you are pre-filling a form for a user), and that specific field is `required`, on submitting the form the component should recognize that the field is not empty and the `required` check should not fail.

### Actual Behavior

Instead, with the following code contained in a `Form`: 

`<FormField name="address" label="Address" required value="prefilledvalue" />`

upon submit, this will fail the `required` check even though the field is filled out.

**Comment by ericsoderberghp** [comment]
The `required` and `validate` properties are only meaningful in a `Form` context. When in a `Form` context, any initial values should be passed in via the `value` property of `Form`.

I'm investigating making FormField smarter to update the Form state to include the value passed directly to FormField.
