### ISSUE TITLE
Not able to change global font size

### ISSUE THREAD

**Issue by midnightcodr** [grommet/grommet#2949]
https://codesandbox.io/s/8kv9lq1648
### Expected Behavior
Font size of the text should follow what's set in `global.font.size`

### Actual Behavior
The font size remains 18px no matter what value I assign to `global.font.size`

### URL, screen shot, or Codepen exhibiting the issue
Please see https://codesandbox.io/s/8kv9lq1648

### Steps to Reproduce

See above

### Your Environment

- Grommet version: 2.5.5
- Browser Name and version: Tested on Mac Chrome only
- Operating System and version (desktop or mobile): MacOS Mojave

**Comment by midnightcodr** [comment]
I just realized that if I `don't` wrap the text inside `Text` tag, the size is working as expected. But again why `Text` does not follow the global font-size setting?

**Comment by midnightcodr** [comment]
I also discovered that the following code obeys the value set by `global.font.size`
```jsx
<Button>Some Button</Button>
```
But
```jsx
<Button label='Some Button' />
```
does not. Can someone point me a direction on how to set a default font size globally?

**Comment by oorestisime** [comment]
Hello,

I welcome you to check the theme documentation for each component. For example the <Text /> has the following entry in the theme https://v2.grommet.io/text#text that handles size.

The button label (you second example) has the following https://v2.grommet.io/button#text.medium.size
We can not style the text in the first example since we wouldn't want to modify the children of a component. You can always do `<Button><Text>Some Button</Text></Button>` if you want your buttons to adhere to a specific size.

Hope this shreds some light into the theming process!

**Comment by midnightcodr** [comment]
Thanks @oorestisime for the timely response. Regarding setting the (default) size for <Text> tags, I'll just need to set the theme to, for example,
```javascript
{
  global: {
    text: {
      medium: {
        size: '40px'
      }
    }
  }
}
```

**Comment by midnightcodr** [comment]
@oorestisime although the method you suggested by wrapping the button text inside a `<Text />` component works, it doesn't exactly address the issue, Please take a look at https://codesandbox.io/s/k1399z0v5r, constructing a button using `<Text>Button Label</Text>` renders differently than `<Button label='...' />`.

Also I am curious why the styling (size to be more specifically) of a button does not follow the settings in global.text.medium.size. There are other examples, such as a FormField's label.

**Comment by oorestisime** [comment]
Sorry i don't follow. Button size follows `global.text.medium.size` if you use the label. 

On the codesandbox if you do `Text size="medium"` you render it the same. what are the differences you are seeing?

**Comment by midnightcodr** [comment]
Border styles of the buttons are different: button using label attribute has a rounded corner box while the one using Text as a child component does not.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by midnightcodr** [comment]
Forgive me I forgot to wrap Text with Button but even if I do it renders still without borders.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by oorestisime** [comment]
We only apply border if we control the label. If you are rendering the button the way you wish (meaning controlling the children and its appearance) then we don't do any styling for you besides handling onclick event hovering etc.
