### ISSUE TITLE
InfiniteScroll isn't working on Edge via browserstack

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#2953]
### Expected Behavior

https://storybook.grommet.io/?path=/story/infinitescroll--simple (Safari on MacOS)

scrolls past 50th item

### Actual Behavior

(Edge on Windows 10 via browserstack.com)

doesn't scroll past 50th item

**Comment by oorestisime** [comment]
is this a duplicate of #2901 ?

**Comment by ShimiSun** [comment]
@oorestisime yep, I think you are right.
