### ISSUE TITLE
Box border style has no proper documentation, Storyboard example not working.

### ISSUE THREAD

**Issue by shivamsingha** [grommet/grommet#2959]
Apparently the PR for border styles has been merged but there no documentation at grommet.io and the example in storyboard is wrong. #2604    

In [Storyboard](https://storybook.grommet.io/?path=/story/box--border), the example is `<Box border={{ type }} >`, which does not work.
It should be `<Box border={{ style: "..." }} >`
There's no documentation at [Grommet website](https://v2.grommet.io/box).
But it is documented at [Github](https://github.com/grommet/grommet/tree/master/src/js/components/Box)  

Border styles work as expected.

**Comment by ShimiSun** [comment]
Thanks for filing the issue! we fixed the storybook example, and thanks again for the grommet-site PR. 🎉
