### ISSUE TITLE
do we support sortable table?

### ISSUE THREAD

**Issue by zjufish** [grommet/grommet#296]

**Comment by alansouzati** [comment]
sorting is not supported at this point. PR welcome!

**Comment by bryanjacquot** [comment]
Our approach for sorting is to use rich filtering and sorting via menus as you can see on this page http://hc380.grommet.io/virtual-machines (click the Filter icon in the upper right).  If you're prompted to login, any username and password will work.  We don't have further plans for a sortable table at this time.
