### ISSUE TITLE
Button documentation does not explain accessibility of hover state in children

### ISSUE THREAD

**Issue by bytewoopy** [grommet/grommet#2966]
I managed to find this behavior via the story book example but wasn't sure what it was doing until I found this ticket (https://github.com/grommet/grommet/issues/2554). 

It would be nice if the documentation was more clear that the Button can have children and the hover state is accessible. 

### Expected Behavior

Documentation to indicate children are supported and get hover state passed down.

### Actual Behavior
Documentation only explains about hoverIndicator which does not seem to be related.

### URL, screen shot, or Codepen exhibiting the issue
https://github.com/grommet/grommet/issues/2554
https://storybook.grommet.io/?path=/story/button--sidebar

### Steps to Reproduce

Hover over the button, box gets hover state update.

### Your Environment

- Grommet version: 2.6.2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): desktop, windows 10

**Comment by ShimiSun** [comment]
Do you think the header that explains about `hover` on the child isn't sufficient?
![Screen Shot 2019-03-22 at 8 39 56 PM](https://user-images.githubusercontent.com/6320236/54860653-cb619280-4ce2-11e9-8c31-c16e08489743.png)

```
You can provide a single function child that will be called with 'hover' and 'focus' keys. This allows you to customize the rendering of the Button in those cases.
```

**Comment by oorestisime** [comment]
We should maybe mention this in `hoverIndicator` and `focusIndicator`.
I am expecting there something more of a general description and probably many people will get by without reading it.

**Comment by bytewoopy** [comment]
I actually did not notice the description. I tend to jump down to the props to see what is available, I guess I saw children mentioned in some components like this one https://v2.grommet.io/select so might have expected the same on others. Might just be me though:😁

**Comment by ShimiSun** [comment]
We should have a `children` prop to Button docs and add the example there.
Improve the example of select `children` as well.

**Comment by ShimiSun** [comment]
We have elaborated on the docs and on storybook with the requested examples. Feel free to let us know if anything else might be missing.
