### ISSUE TITLE
How to disable font antialias

### ISSUE THREAD

**Issue by midnightcodr** [grommet/grommet#2967]
According to
https://github.com/grommet/grommet/blob/master/src/js/utils/styles.js#L21 The base style has
```
  -webkit-font-smoothing: antialiased;
```
set globally. How can I change that to 
```
-webkit-font-smoothing: auto;
```
by using a custom theme? I've tried setting `global.font.extend`, `global.text.medium.extend` and `global.extend`, none of them works. Advice? Thanks.

**Comment by ShimiSun** [comment]
From what I see, `baseStyle` is used for the components Drop, Layer, Grommet.
which one are you using? 
I suggest that if you use either `theme.grommet.extend`, `theme.global.drop.extend`, `theme.layer.extend` 
```
-webkit-font-smoothing: auto;
```
it should work, let me know how it goes.

**Comment by midnightcodr** [comment]
Thanks for giving me the hint - `which one are you using?`, by applying to `global.text.extend` I am at least able to apply the style to all `<Text />` components.
