### ISSUE TITLE
How can I change the size of a FormField's label?

### ISSUE THREAD

**Issue by midnightcodr** [grommet/grommet#2968]
With the following code, how can I change the size for the label inside the FormField? By reading the source code for FormField, I can't seem to find a way to customize that.
```jsx
<FormField label="Field label" help=''>
  <TextInput placeholder="type here" />
</FormField>
```

I also found a similar limitation, for example, if I have
```js
  global: {
    text: {
      medium: {
        size: '14px'
      }
    }
```
I would expect
```jsx
<Button label="A button" />
```
to have the font size set to 14px, but it does not. It uses the default medium font size of 18px insead, one of the workarounds for the Button case is to change to
<Button><Text>A button</Text></Button>.

You can found more details about this in another related issue I reported https://github.com/grommet/grommet/issues/2949

**Comment by ShimiSun** [comment]
FormField `label` also accepts the type of `node`, which basically means you can do something along these lines:
```
<FormField label={<Text size='small'> Field label</Text>} help=''>
  <TextInput placeholder="type here" />
</FormField>
```
and then leverage the Text component to control the size. Is that answering your question?

**Comment by midnightcodr** [comment]
Yes that should do it. Thanks @ShimiSun.

**Comment by hedleysmith** [comment]
Here's how to change the font-size in a reusable component:

```
import React from 'react';
import { FormField, Text } from 'grommet';
import styled from 'styled-components';

const WrappedInput = styled(FormField)`
  font-size: 12px;
`;

export default function CustomFormField(props) {
  return ( <WrappedInput {...props} label={<Text size="small">{ props.label }</Text>} /> );
}

```
