### ISSUE TITLE
Ability to unselect / clear selected value with <Select>

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet#2973]
Currently there is no built-in way for a user to unselect an option after selecting (resetting to original state). Proposed enhancement would be to add a "clearValue" prop that adds a grey "x" on the right side of the Select input to clear the current value.

My current workaround is to put the first option as a blank string, but this doesn't look great from a UI perspective.

**Comment by oorestisime** [comment]
hm, maybe the solution here is to approach the selection closer to the select multiple handling. In multiple when you re-select the option it will unselect it. Unselecting all the selected values clears all the values.

**Comment by oorestisime** [comment]
I ve been thinking about this a bit. not sure this should be supported on the core library. there are so many ways of doing this (handle re-clicking, adding a checkbox, adding a close icon, adding an empty...) it will end up not being generic enough.
We could have an example with a few ways of doing this though.

**Comment by ShimiSun** [comment]
@JetLim what do you think of a template example for this one? 
@MikeWalrath can you add it to out templates list.

**Comment by JetLim** [comment]
@oorestisime 
We'll discuss this with a checklist of possible selector solutions. 

@ShimiSun 
@MikeWalrath

**Comment by markjackson02** [comment]
@JetLim @oorestisime any progress here?

**Comment by oorestisime** [comment]
Thanks for reminding us! We haven't got the chance to talk about this. will in the next few days.

**Comment by markjackson02** [comment]
Hi @ShimiSun I noticed the "in progress" tag. Is the team moving forward with a specific solution to this? If so I am interested to know what it is!

**Comment by markjackson02** [comment]
@ShimiSun @JetLim any updates on this?

**Comment by ShimiSun** [comment]
Yes, we will be discussing the designs today, hopefully we'll have something to share soon. @MikeWalrath @L0ZZI FYI

**Comment by JetLim** [comment]
Yes, we have something that is in the works. @ericsoderberghp @ShimiSun @markjackson02

@MikeWalrath @L0ZZI

**Comment by ShimiSun** [comment]
Hi buddy, thanks for your feedback and patience with this one.

There are a couple of approaches here I would like to share:
1. Unselect could be done today with clearing the selected options, whether it is a multiple or single Select option. @britt6612 contributed a story to demonstrate this implementation (Thanks @britt6612). https://github.com/grommet/grommet/pull/3371
https://deploy-preview-3371--sad-tereshkova-173d07.netlify.com/?path=/story/components--all
If you don't find this to be sufficient, continue reading :)

2. The second option is to embed the clear behavior within grommet, so it will be generic enough with its usability and look and feel for most users, feel free to share your feedback on the two options if any of them seems like something you'll be interested in.
(Thanks to @JetLim for those designs)
<img width="1228" alt="select_single_multiple" src="https://user-images.githubusercontent.com/6320236/65728693-eee20d00-e078-11e9-829e-cce013916dfb.png">

Please share with us what you think, and let's continue from here.

**Comment by markjackson02** [comment]
Thank you @ShimiSun @JetLim ! I like design option 2. My only question is how would the size of the scroll region be set? Would this be a prop e.g. maxScrollSize = 5 shows means 6th item would not be visible until scroll? Or could that be set dynamically somehow based on the viewport?

**Comment by ShimiSun** [comment]
@markjackson02 This is a valid concern, thanks for bringing it up. I guess with option #1 we won't have this use case, only with option #2. 
In case we will pursue option #2, I guess I need to see an idea of implementation and brainstorm from there, I'm inclining to show it based on the viewport.

**Comment by markjackson02** [comment]
Hi any status update here? @ShimiSun @JetLim @oorestisime

**Comment by ShimiSun** [comment]
hi buddy, thanks for the friendly reminder, I won't be able to be the main driver of this feature (lots on my plate at the moment) but feel free to drive this enhancement, or maybe @oorestisime will be able to join too?
I would say that I think we should go with option #2.

**Comment by oorestisime** [comment]
I have also a lot on my plate right now. my schedule and availability should look much better in 2 weeks. If it can wait till there then i am happy to take this.

**Comment by markjackson02** [comment]
hi @oorestisime are you still planning on working this one?

**Comment by oorestisime** [comment]
Hey i finally have time to take this! Thanks @markjackson02 for the patience :) I ll be picking option 2.
My plan is to have a clearPosition prop for the placement of the clear, clearText for the text and try to have the styling as themable as possible. Maybe a render prop would even make more sense.

Hope to have something in the next days.
