### ISSUE TITLE
RadioButtonGroup to remove hover when using keyboard

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#2977]
### Expected Behavior
Not having hover functionality when using keyboard navigation in RadioButtonGroup.
More like how select is working

### Actual Behavior
hover is still being displayed when using keyboard

### URL, screen shot, or Codepen exhibiting the issue
https://storybook.grommet.io/?path=/story/radiobuttongroup--simple

### Steps to Reproduce

1. 2. 3.

### Your Environment
any

- Grommet version: 2.6.5
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by taysea** [comment]
@ShimiSun Is this still an issue or can we close it? I don't see the hover state when using keyboard.

**Comment by IanKBovard** [comment]
i dont notice a hover state when i use keyboard either. tested on storybook

**Comment by ShimiSun** [comment]
Thanks for verifying guys! 🚀
