### ISSUE TITLE
CircleCI - validate publication by verifying new release in an app

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#2978]
### Expected Behavior
currently CircleCI is publishing the release but not testing whether it is working.

### URL, screen shot, or Codepen exhibiting the issue
https://github.com/grommet/grommet/blob/2bd52dd23ea76e15bc1a5684d579ddbeb1db1c0e/.circleci/config.yml#L72

### Steps to Reproduce

1. 2. 3.

### Your Environment
any

- Grommet version: 2.6.5
- Browser Name and version: any
- Operating System and version (desktop or mobile): any

**Comment by oorestisime** [comment]
How should the release be tested?

**Comment by ShimiSun** [comment]
@oorestisime working on a PR now, I was thinking a simple `yarn build` on a cloned repo with the newly released version should be enough. what did you have in mind?

**Comment by oorestisime** [comment]
Well i hope once we get monorepo we build all the patterns in every PR or every master push to netlify. but yes probably linking the release in a cloned repo could be enough now.

**Comment by ShimiSun** [comment]
@oorestisime agree. eric had a nice idea that I've implemented and it didn't require cloning. let me know  what you think on the PR ☝️
