### ISSUE TITLE
grommet init and babel setup

### ISSUE THREAD

**Issue by larryhengl** [grommet/grommet#298]
Just stumbled onto grommet, looks really good.  Nice work and thanks for sharing it!  

In the process of installing grommet and setting up my sample-app, I got babel related errors when running ```gulp dev```.

I played with the settings mods found in the wiki page [here](https://github.com/grommet/grommet/wiki/Grommet-0.5.0-and-Babel-6), but it didn't work.  So here's what I did to get it to all work:
- install gulp globally
- install grommet globally
- run the grommet init
- *manually*: 
  + ```npm i -D babel-preset-es2015```
  + ```npm i -D babel-preset-react```
- edit .babelrc:
```
{
  "presets": [ "es2015", "react" ]
}
```

perhaps add those babel preset packages to the app generator's package.json?

also, it looks like the current babel-reset-2015 includes transforms presets for ES6 spread, which is why i omitted
 ```"plugins": [
    "transform-object-rest-spread"
  ]``` 
from the .babelrc file, as prescribed on the wiki page.

Looking forward to diving into some app dev with grommet!

cheers,
:Larry

**Comment by alansouzati** [comment]
Thanks for reporting this. I tried the sample app without adding the presets and worked normally. But you are not the first one to report this very same issue. Maybe I had the presets in the global context.

Sorry you had to face this issue. I will add the presets and plugin to the init commands.

**Comment by larryhengl** [comment]
Cool , np, and thanks!  Feel free to close this puppy if you've already addressed this issue.

Side Q while I've got your ear:

Regarding the [Examples](https://github.com/grommet/grommet/wiki/Exporting-examples-from-Grommet)...is the Exporting idea now deprecated in lieu of a separate repo or subdirectory?  Or is that still in-progress, and I should fire up the example server in the meantime...to view the examples code?

thx!

**Comment by bryanjacquot** [comment]
Checkout the new grommet CLI which allows easy creation of different types of apps with different themes and supports babel.  https://github.com/grommet/grommet-cli
