### ISSUE TITLE
RangeInput: Add support to add ticks at intervals with optional titles

### ISSUE THREAD

**Issue by nikitavoloboev** [grommet/grommet#2980]
### Expected Behavior

New prop to [RangeInput](https://v2.grommet.io/rangeinput) that would allow to add ticks at certain intervals inside the input slider with optional labels.

### Actual Behavior

No such prop and thus no way to do it.

### Your Environment

- Grommet version: 2.5.5
- Browser Name and version: Safari/Chrome
- Operating System and version (desktop or mobile): macOS 10.14.3

**Comment by nikitavoloboev** [comment]
I would like to contribute to this issue in form of PR if this is something you agree on is useful too.

Currently I am trying to find another slider that accepts this use case but ideally I use Grommet's RangeInput component.

**Comment by ericsoderberghp** [comment]
A quick way to do this, which would allow a great degree of customization, would be to do something like:

**Comment by nikitavoloboev** [comment]
How can I make the ticks start correctly at the first instance of the slider? 

I am not sure what I should edit from above code to do that.

**Comment by ShimiSun** [comment]
@nikitavoloboev play with the initial value, e.g. https://v2.grommet.io/rangeinput?c=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKRAbwChFEIEBnKRAbQDd1cR8AaRO-KAGrtOAXUQBeRACV86aADoQfAMpR0UIgAZiAbiqIATvxAGkhfdQA8quQGtEAcxAwAJjDAOAwgAsYuF+IARLjoDIEAfBbUiJYAQnCoiMB+uIjY6AFkZIgARnBQUHCYAFyIgaiodJjsuIGIAL71iG5G0PBgQQZwAO51AFZKsMAAnkE5-N34+GB17DAOHYEQ0xoGEVHR5EwAjDwATDwAzDwALDwArCLy1diEAJIS4YiEcQmItvijZHdN6ZnZhWwpUCVRqdUauTgBhc+AMnXm3igdQA9OFiMR6hsYsj4qhIpsrFJ0B58HcwNgQFAsdQ2Bx8OIyLTOJiCdEED5iQ56WR8CwVo9ePwhHTCLyVvI1AYuVB5Ez8BisaiopZkTYILZ8YhdBR6kA

**Comment by nikitavoloboev** [comment]
Thank you
