### ISSUE TITLE
FormField component prop without proper type

### ISSUE THREAD

**Issue by cristiandley** [grommet/grommet#2981]
FormField expects a function as a component. 

### Expected Behavior

Render without issues and warnings

### Actual Behavior

Renders ok but presents warnings

```
Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `FormField`, expected `function`.
```

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/4rrnnop2m4

### Your Environment

- Grommet version: 2.6.x
- Browser Name and version: Firefox
- Operating System and version (desktop or mobile): Mac Mojave

**Comment by ShimiSun** [comment]
Thanks for filing the issue @cristiandley! will you be will to make an open-source contribution? https://github.com/grommet/grommet/blob/5bd6c2c41731e4b29565e867ca47c7ec315a853a/src/js/components/FormField/doc.js#L20

**Comment by resdevd** [comment]
I had the same console error, however looks like using like this is getting rid of error.

`   <FormField
                            label="Comment"
                            name="comment"
                            component={()=><TextArea rows="6"/>}
                        />`

**Comment by ShimiSun** [comment]
Thanks for reporting! I moved your sandbox example to include typescript so it will be easier to notice issues. https://github.com/grommet/grommet/pull/3041, you can leverage this sandbox template for future TS issues that you'd like to report.

Thanks to your example, I noticed an issue with the types of Heading levels, hence fixed as well
https://github.com/grommet/grommet/pull/3041
