### ISSUE TITLE
Could we port Grommet to React Native using primitives?

### ISSUE THREAD

**Issue by italomlp** [grommet/grommet#2991]
### Expected Behavior

Hi there! I'm thinking in last days about to port Grommet to work on React Native too. Searching in the google, I found a way that can be used.
- Grommet uses styled-components :heavy_check_mark: (half way over)
- What I would do (or someone else interested in it), is to adapt Grommet to use `styled-components/primitives` and `react-primitives`, so having universal and reusable components, on ReactJS **and** React Native

I believe that most of the main Grommet components can be ported with this. Then, I would like to hear your opinions and, as suggested by @oorestisime and @ShimiSun in Grommet Slack, I'm opening this issue to discuss about that. 

### Actual Behavior

Actually, Grommet doesn't work in React Native.

### URL

Here's some links that can be useful:
- https://medium.com/styled-components/announcing-primitives-support-for-truly-universal-component-systems-5772c7d14bc7
- https://github.com/lelandrichardson/react-primitives

**Comment by oorestisime** [comment]
Hello,

This is an interesting use case. I am not familiar with RN nor with the burden that would require to support this. I am wondering how things like Layer would work. Is there a chance you could list some actionable items on what needs to be done? Seems quite vague to me and some questions i have in mind are:

- are all the css props valid in RN?
- how about the react api and react hooks. would it require changing anything on that level?
- how about typescript?
- would this need any additional testing? how would we be able to test this consistently

**Comment by italomlp** [comment]
Well, let's see. About Layer component, I think that it can be ported, but with more manually work. About de questions:
- React Native has Stylesheet to use most of the css properties, but with lowerCamelCase. Luckily, styled-components for RN already has a parser ([css-to-react-native](https://github.com/styled-components/css-to-react-native)) to avoid it.
- Beginning in RN 0.59.x, React Hooks are now supported, and React Api is pretty the same.
- RN accepts Typescript out of the box with a template ([React Native Template TypeScript](https://github.com/emin93/react-native-template-typescript)) or adapting an existing project (I made a [Gist for it](https://gist.github.com/italomlp/4d16bf0f19d09f9fae48d272f9e6306e) days ago). This is possible because of the release of [Babel 7](https://babeljs.io/blog/2018/08/27/7.0.0)
- About tests I can't say for sure, but I believe that there's no problem as Grommet uses Jest for it.

If there is another RN dev, and I say anything wrong, correct me please.

But, after all of that said, I would like to say one more thing: what I thought before is to adapt most of the features, but **not all** of it. E.g: RN use flex-box and doesn't accept grid layout. So Grid components of Grommet could be limited. There are another things to consider, but I believe that the main simple components can be portted.

I'm thinking in start a repo to try it myself. If I can get time for it, I'll say and let you know about my experience.

**Comment by ericsoderberghp** [comment]
Back in v1, we created an initial native version of grommet in the `grommet-native` repository and built a few apps with it. Back then, there were enough differences in how the components would be composed, with interaction being separate react-native components from visual  structure components, that except for extremely simple cases, it would be unlikely to build a single grommet based app that worked for both native and web. But, that was three years ago. Perhaps things have changed. I'm open to exploring.

**Comment by italomlp** [comment]
I think that it's possible. 

Buuuuut... Some minutes ago, I got me thinking of instead of to readapt/port all Grommet for work with RN. we could use an already RN Ui framework that accepts theming, and only "inject" Grommet styles (or most of them) with a theme on it. An example is [NativeBase](https://github.com/GeekyAnts/NativeBase), where we can change colors and styles of its components.

This last idea sounds me more maintainable and less costly. What do you think about it?

**Comment by mrebb** [comment]
There are certain differences when it comes to React Native and React. Crucial part is playing around DOM elements since there is no DOM/HTML support on mobile. I am sure there would be lot of tweaks and re-writing of code required to make it work for both React and RN. Most styled components from `Grommet` need special handling to deal with some of the DOM elements that RN doesn't support, like `Div`, `ul` and `ol` and their event listeners.

**Comment by italomlp** [comment]
Of course, there are many differences between web and native. What I told is maybe react primitives and styled-components/primitives be a way to make it works.

However, like I said in the last comment, I was thinking about make a "theme", with colors, spacements and more details that can be made, for NativeBase.

**Comment by macintoshhelper** [comment]
Hi, I‘ve been working on a UI library that's similar to Grommet, but has cross-platform UI component primitives, with `react-sketchapp` as a primary focus (compiles to web and React Native also though): https://github.com/elemental-design/elemental-react

What I would suggest from my findings, is having a `@grommet/primitives` package that exports `styled-components` (exporting the `ThemeProvider`, `styled` function, etc to make sure the context remains consistent. It could export `{ View, Text, ...etc }` It can work something like this:

Pseudo-code from my import resolving system: https://github.com/elemental-design/elemental-react/blob/master/src/styled.ts

```js
let styled;

if (Platform.OS === 'web') {
  styled = require('styled-components');
} else {
  styled = require('styled-components/primitives');
}
const { ThemeProvider } = styled;

export { styled, ThemeProvider };
```

I had a quick look through #3029 and noticed that it uses `styled-components/primitives`, but I think this should be avoided for web, as it uses `react-native-web` for styling, which messes up SSR and creates quite a bit of bugginess. `styled.div` should be used on web, and `styled.View` on native platforms.

This shouldn't be too difficult, the main limiting factor would probably be that Yoga doesn't support CSS grid yet though.

**Comment by jcfilben** [comment]
I don't think we have enough resources to undertake this effort at this time. Closing for now, if there is strong interest we can revisit this.
