### ISSUE TITLE
Need a help to implement Select options component to load pagination api data

### ISSUE THREAD

**Issue by 2manoj1** [grommet/grommet#2999]
How load a pagination data in Select options? 

### Your Environment

- Grommet version: 2.4.0
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by oorestisime** [comment]
Hello,

please provide some more information with the issue you are facing this is too broad.where do you have your data, did you try sometihng and you are facing an error?

**Comment by 2manoj1** [comment]
For Example: In Select component we need load 50 options in initially after scroll reach end we again call API and load another 50 options.

**Comment by shivamsingha** [comment]
Here's an example.
https://storybook.grommet.io/?path=/story/infinitescroll--onmore

This one doesn't use api. You'll have to implement it yourself in the `onMore` function.

**Comment by 2manoj1** [comment]
@shivamsingha in Select component need it. Can you give me small example with Select where options list will load with infinitescroll

**Comment by shivamsingha** [comment]
Sorry my bad!
I'm not sure if it's possible with select.

**Comment by oorestisime** [comment]
I am not sure how this would work. how can we know what is selected when the options are not all there yet? 
having a hard time seeing the use case

**Comment by shivamsingha** [comment]
How about loading all options at once?

**Comment by oorestisime** [comment]
then you can handle this at a higher level. like getting them in one of the lifecycle method.

**Comment by 2manoj1** [comment]
@shivamsingha for performance related issue we cant load all at once. API not providing all data.

**Comment by ShimiSun** [comment]
@2manoj1 
Select includes out of the box InfiniteScroll, you can see the implementation of SelectContainer here https://github.com/grommet/grommet/blob/390c3862bb2b43711534318273ecf832b63770cc/src/js/components/Select/SelectContainer.js#L393  
Have you tried leveraging the `theme.select.step` to determine how many items to render at a time?
I suggest playing with InfiniteScroll and after getting it down, reading the docs of [Select](https://v2.grommet.io/select) to see how you can leverage it's out of the box functionality.

**Comment by 2manoj1** [comment]
@ShimiSun I am not find any callback function from where I trigger API call and update the options data. Current implementations of Select provide load all options at a time and play with step. Is it possible providing callback function when 'ismore' or similar type props value true and options reach current length.

**Comment by ShimiSun** [comment]
@2manoj1 , I think I'm missing something with your desired functionality, and why using `step` is not enough to leverage the lazy loading behavior. To call your API, have you tried adding a callback on the onMore function? you can do something like `onMore={() => load()}` and put a callback on `load()` to call the API, will that work?
if not, can you elaborate what will be the expected behavior in your opinion?

**Comment by 2manoj1** [comment]
@ShimiSun I trying your approach but cant found solution. PFA

Example: https://codesandbox.io/s/6ljr40mjpr
![image](https://user-images.githubusercontent.com/15128569/57427898-92a25c00-7243-11e9-8105-4f2bcc39c2ef.png)

Can you make update storybook where we found example for this issue.

**Comment by oorestisime** [comment]
Yeah there is no onMore callback on the select field and it is not forwarded on InfiniteScroll right now. A PR to fix this would help you ;)

**Comment by 2manoj1** [comment]
@oorestisime yes, its will help if Select also come with onMore callback function

**Comment by shivamsingha** [comment]
> 
> 
> @oorestisime yes, its will help if Select also come with onMore callback function

Is this what you want? 
[https://deploy-preview-3114--sad-tereshkova-173d07.netlify.com/?path=/story/select--lazy-loading-options](https://deploy-preview-3114--sad-tereshkova-173d07.netlify.com/?path=/story/select--lazy-loading-options)

**Comment by 2manoj1** [comment]
@shivamsingha yes. Thank You.
