### ISSUE TITLE
The default search component is closing fast when mouseup

### ISSUE THREAD

**Issue by nanndoj** [grommet/grommet#30]
The default search functionality

    <Search />

Is open when clicking (mousedown) on search icon, but it's closing fast when the "mouseup" event occur. So we're no able to type in the search input. 

Tested on Firefox 38.0.5
Chrome 43.0.2357.81
Internet Explorer 11

**Comment by nanndoj** [comment]
The problem is fixed by putting `layer: false` on file **src/js/components/Search.js** line 45. But I couldn't find any information about this property on search docs. What would be the impact of this change?

**Comment by alansouzati** [comment]
@ericsoderberghp, can you provide insight here?

**Comment by bryanjacquot** [comment]
@nanndoj we're cleaning up old issues and believe this has been resolved.  Let us know if you're still seeing this with the latest grommet.
