### ISSUE TITLE
Calendar date doesn't seem to match prop

### ISSUE THREAD

**Issue by jamstooks** [grommet/grommet#3000]
Providing dates to and receiving dates from seem to be one day off.

### Expected Behavior

Providing `"2019-04-05"` should highlight the 5th of April.

### Actual Behavior

It highlights the 4th of April. Incidentally, it works fine for `2019-04-05T12:00:00.000Z` but not for `2019-04-05T01:00:00.000Z` which makes me think there might be some sort of timezone issue.

### URL, screen shot, or Codepen exhibiting the issue

Codepen fork here: https://codesandbox.io/s/jn3wyvm9y9
(Click on `Calendar` under `Visuals` in the preview)

A snippet of the relevant code:
```
export default class extends Component {
  state = { date: "2019-04-05T00:00:00.000Z" };

  onSelectSingle = date => this.setState({ date });

  render() {
    const { date } = this.state;
    return (
      <SandboxComponent>
        <Text>{date}</Text>
        <Calendar date={date} range={false} onSelect={this.onSelectSingle} />
      </SandboxComponent>
    );
  }
}
```

Screenshot showing date value in a `Text` component and `Calendar` component with the same date prop:
![Screenshot from 2019-04-05 12-12-28](https://user-images.githubusercontent.com/585436/55651011-22b03a00-579c-11e9-9947-65b20bd61621.png)

### Steps to Reproduce

This is shown immediately and clicking on a date will return the next day. I've tried this using UTC time with the same result:
```
  constructor(props) {
    super(props);
    let date = new Date(new Date(Date.UTC(2019, 4, 5, 12, 0, 0)));
    this.state = { date: date.toISOString() };
  }
```

The only way I can think to get this to work consistently is just using 12:00:00 for the time.

### Your Environment

- Grommet version: `"grommet": "^2.4.0",`
- Browser Name and version: Chromium
- Operating System and version (desktop or mobile): Ubuntu 19.04

**Comment by ShimiSun** [comment]
I think the date you chose is missing the timezone offset, I didn't take a deep look into it yet, but try to have a look at this example where it does work https://codesandbox.io/s/k5pp0r3y2v, and let me know what you think. (make sure you are using grommet ^2.6.5 as it includes bug fixes for this component, please note that I've updated sandbox on my fork)

**Comment by jamstooks** [comment]
Strange, I'm still seeing the same result with your fork: :confused: 

![Screenshot from 2019-04-08 07-32-57](https://user-images.githubusercontent.com/585436/55732334-a8b4c680-59d0-11e9-8dbf-67f70b7929e4.png)

I clicked the 11th, but the date was set to 12th...

**Comment by jamstooks** [comment]
Since the `Calendar` returns a naive date string, I guess it's really on the user to handle it correctly.

If `onSelect` returns `'2019-04-11'` for example, regular parsing with javascript behaves like this (in my timezone):

```
> new Date('2019-04-11')
Wed Apr 10 2019 17:00:00 GMT-0700 (Pacific Daylight Time)
```

It would be nice if `onSelect` could return a localized `Date`, but given issues like this with `Date` I don't blame you. I'll just work around it...

**Comment by oorestisime** [comment]
Closing this, feel free to reopen if you think there's any improvement we could do.
