### ISSUE TITLE
Please add selected prop to radio button extend

### ISSUE THREAD

**Issue by berndschimmer** [grommet/grommet#3005]
Please add the selected state to the radio button extend field (as the checked state is in the checkbox).

### Expected Behavior

```
radioButton: {
    extend: ({ selected }) => `
        ${selected && color: red;}
    `
},
```
Should render the label of the radio button in red.

### Actual Behavior

```${selected} ```
is undefined.

### All Environments

- Grommet version: 2.6.5

**Comment by ShimiSun** [comment]
RadioButton has `checked` you can use. 
But why would you use the `extend` when you explicitly style the `check` prop from the theme? see the example on https://storybook.grommet.io/?path=/story/radiobutton--custom-theme
```
const customTheme = deepMerge(grommet, {
  radioButton: {
    ...
    check: {
      color: {
        light: "neutral-1"
      }
    }
  }
});

```

**Comment by ShimiSun** [comment]
Hi buddy, I'll be closing this issue, feel free to shoot us a message if you have more questions.
