### ISSUE TITLE
Feature request: Can we get HSL color parsing?

### ISSUE THREAD

**Issue by dallas** [grommet/grommet#3009]
I use `hsl(…)` colors extensively in my theming but doing so means that they are currently not properly calculated as being “dark”.

### Expected Behavior

I would expect that if I have a `global.colors.text` of `{ light: "black", dark: "white" }` and a primary button background color of `hsl(100, 3%, 18%)`, that it would have white text.

### Actual Behavior

It has black text because there is currently no way for `getRGBArray` to parse it, so that function just returns the same value it got – the string `"hsl(100, 3%, 34%)"` – which is not what the `colorIsDark` function is expecting to deal with.

### URL, screen shot, or Codepen exhibiting the issue

[Codesandbox](https://codesandbox.io/s/zl3187znqx)

### Steps to Reproduce

Use `hsl(…)` based colors in your theme, particularly for button colors.

### Your Environment

- Grommet version: 2.6.5
- Browser Name and version: irrelevant
- Operating System and version (desktop or mobile): irrelevant

**Comment by dallas** [comment]
I’d be happy to try my hand at contributing something for this, although I’m eyeing the use of tools like [`color-string`](https://www.npmjs.com/package/color-string) (to convert CSS string notation to something JavaScript can use) and [`color-convert`](https://www.npmjs.com/package/color-convert) to do the actual conversion from whatever it is to RGB. Would such dependencies be welcomed?

**Comment by oorestisime** [comment]
Hello and thanks for jumping up on this.
Bundlephobia says: 

- https://bundlephobia.com/result?p=color-convert@2.0.0 
- https://bundlephobia.com/result?p=color-string@1.5.3

which equals to around 7kb minified and gzipped which is around 10% of the current size.
Is there a chance we could enable this as per user requested feature?

**Comment by dallas** [comment]
@oorestisime:
Ahh, yeah … probably not a worthwhile expense for incorporating those libraries, then.

What would it mean to have it be enabled as a per user requested feature?

**Comment by dallas** [comment]
What if we just add the piece we need to go from HSL to RGB?

https://github.com/kayellpeee/hsl_rgb_converter/blob/master/converter.js

**Comment by oorestisime** [comment]
lets wait a bit to hear from the rest of the team! didn't mean to say no we shouldn't add these libraries.
Not sure if this is possible but to structure the code in a way if the user installs those libraries then to make use of it, otherwise just keep current flow. I am not sure if this is possible though.
For example in python i would do :

```python
HSL_AVAILABLE = False
try:
    import foo
    HSL_AVAILABLE = True
except:
    pass
```

i haven't explroed these in JS, so this is just food for thought

**Comment by dallas** [comment]
Could be like a configurable provider of sorts with the default just being the simple hex & rgb only code that is currently there. Even if all that the provided library needed to adhere to was `convertToRGB(...args)`.

Although, I was kind of curious about the actual threshold for what is considered light vs. dark. I don’t know how much configuration Grommet wants to have, but it might be nice to be able to adjust that as well. Let me just 🎈 this a bit … 😛

**Comment by dallas** [comment]
@oorestisime: How about using [`tinycolor2`](https://github.com/bgrins/TinyColor) instead. It’s [only 5kb](https://bundlephobia.com/result?p=tinycolor2@1.4.1) and would also provide the ability to brighten, lighten/darken, (de)saturate, as well as asking if a color `isLight()` or `isDark()`, something that the Grommet code in question is already doing.

**Comment by dallas** [comment]
Looks like `tinycolor2` uses the exact same formula for calculating a color’s brightness, the main difference is that it considers a value `< 128` as dark, while the current Grommet code considers a value `< 125` as dark.

**Comment by oorestisime** [comment]
@ericsoderberghp @alansouzati would love your input here as well.

**Comment by dallas** [comment]
Awesome! Thank you, @ericsoderberghp! 😄
