### ISSUE TITLE
search input has issue when input special chars like : (%3A)

### ISSUE THREAD

**Issue by simpleofac** [grommet/grommet#301]
In the Ferret search screen, eg search service profile screen 
http://ferret.grommet.io/server-profiles

if I input 8, I will get 2 records,  url will become
http://ferret.grommet.io/server-profiles?q=8

if I input a special char, for example :  (colon), the url will become 
http://ferret.grommet.io/server-profiles?q=8%3A

If i input any chars,  the search input will become empty and the url will become 
http://ferret.grommet.io/server-profiles?q=8%3Aa

type any char in the search input afterward will return no results.

**Comment by bryanjacquot** [comment]
This appears to be working properly now.  When a colon is typed, the results list is empty (as expected) but the field and URL continue to update as expected.  If this is still an issue with a different app, please provide a CodePen.
