### ISSUE TITLE
Minor repo documentation edits

### ISSUE THREAD

**Issue by dallas** [grommet/grommet#3010]
Not much of an issue, per se, but while reading through some of the GitHub repo documentation I noticed a few typos, awkward phrasings, inconsistent capitalizations of things like “Grommet” or “GitHub.” I’m just wondering if I spruce it up as I read along and make a pull request at the end, would that be useful and worthwhile? It’s really little things, but I’m the kind of person that likes to tidy the little things on my way to bigger things 😄

**Comment by oorestisime** [comment]
Yes feel free to help us improve documentation even for typos! :)

**Comment by dallas** [comment]
Cool. Thanks for getting back so quick (again), @oorestisime! I noticed that the Slack community is mentioned quite a bit in the `CONTRIBUTING.md` file. Would you like those to be links to someplace where people can actually join that Slack workspace?

**Comment by oorestisime** [comment]
Hm, there's the join the community slack badge on `README.md`. do you think we need to link on every mention? no opinion on the matter.

**Comment by dallas** [comment]
Probably not… It just feels like there are a lot of calls-to-action to join the Slack community on this page and no instructions on how to do so.

**Comment by ShimiSun** [comment]
@dallas I agree with your last comment, feel free to add it where you believe is helpful.
