### ISSUE TITLE
Make the gap between Button's icon and label configurable

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#3015]
### Expected Behavior
Add support in the theme and as a prop to set the gap size between the Button component's icon and label

### Actual Behavior
The gap size between the icon and label is set and non-configurable. 

### Steps to Reproduce

1. 2. 3. N/A

### Your Environment

- Grommet version: 2.5.5
- Browser Name and version: 
- Operating System and version (desktop or mobile):

**Comment by dallas** [comment]
The only way to configure the gap is to change the theme’s `global.edgeSize.small` value since that’s the gap size that `Button` uses when it has an icon + label. It’s also the same way for `Anchor` components that have an icon.
