### ISSUE TITLE
Box background opacity property incorrectly reports numbers as bad input

### ISSUE THREAD

**Issue by bowdeng** [grommet/grommet#3022]
When using the background property in <Box> and setting an opacity to something other than what is described in the docs "weak", "medium", "strong" or True, the javascript console reports:

Warning: Failed prop type: Invalid prop `background` supplied to `Box`.

However, it works fine and would be more appropriate to accept the value without complaining. The validation and the docs will need updating.

### Expected Behavior

The value for opacity is applied as now, with no error. The docs also reflect the ability to use values here.

### Actual Behavior

The error Warning: Failed prop type: Invalid prop `background` supplied to `Box` displayed even though the value applied fine.

### URL, screen shot, or Codepen exhibiting the issue

https://xz9xjlq3kw.codesandbox.io/

### Steps to Reproduce

1. Create the Box component as described in the Codepen. View the javascript console.

### Your Environment

- Grommet version: 2.6.5
- Browser Name and version: Chrome 73.0.3683.103
- Operating System and version (desktop or mobile): Windows 10 and Mac OS Mojave

**Comment by ShimiSun** [comment]
source https://codesandbox.io/s/xz9xjlq3kw
