### ISSUE TITLE
Label color to plain button

### ISSUE THREAD

**Issue by guschnwg** [grommet/grommet#3031]
When I want a `plain` <Button />, I would like to choose the label color based on Button's `color` property, as it does nothing when Button is `plain`

### Expected Behavior

`color` property's value must set css's `color` property to the given button

### Actual Behavior

Actual Button's `color` property for a `plain` Button does nothing.

Behaviour can be seen at: https://codesandbox.io/embed/py5mv7o1z0

**Comment by dallas** [comment]
I think the [color declaration line](https://github.com/grommet/grommet/blob/master/src/js/components/Button/StyledButton.js#L82) in `StyledButton.js` would need to be changed to something like this:

```javascript
const plainStyle = css`
  color: ${props => normalizeColor(props.colorValue || "inherit", props.theme)};
  border: none;
  padding: 0;
  text-align: inherit;
`;
```
