### ISSUE TITLE
ResponsiveContext doesn't work with Gatsby SSR

### ISSUE THREAD

**Issue by pawelsas** [grommet/grommet#3044]
I know this issue looks like a duplicate, but #2311 differs from this bug.

Steps to reproduce:

1. Install a Gatsby starter of your choice (default is fine)
2. Add Grommet and wrap the root file, e.g. index.js or layout.js (theme doesn't matter)
3. Add `ResponsiveContext.Consumer`
4. Print the current `size` to the screen
5. Run `npm run develop` and resize the screen. Like expected the `size` value changes as the screen size does.
6. Run `npm run build`, open index.html from public folder and resize the screen. Now the `size` value remains **medium** on every screen size.

layout.js
```
import React from "react"
import { Grommet } from "grommet"
import PropTypes from "prop-types"
import { StaticQuery, graphql } from "gatsby"
import theme from "../themes/default"

import Header from "./header"
import "./layout.css"

const Layout = ({ children }) => (
  <StaticQuery
    query={graphql`
      query SiteTitleQuery {
        site {
          siteMetadata {
            title
          }
        }
      }
    `}
    render={data => (
      <Grommet theme={theme}>
        <Header siteTitle={data.site.siteMetadata.title} />
        <div
          style={{
            margin: `0 auto`,
            maxWidth: 960,
            padding: `0px 1.0875rem 1.45rem`,
            paddingTop: 0,
          }}
        >
          <main>{children}</main>
          <footer>
            © {new Date().getFullYear()}, Built with
            {` `}
            <a href="https://www.gatsbyjs.org">Gatsby</a>
          </footer>
        </div>
      </Grommet>
    )}
  />
)

Layout.propTypes = {
  children: PropTypes.node.isRequired,
}

export default Layout
```

index.js
```
import React from "react"
import { Link } from "gatsby"
import { Heading, ResponsiveContext } from "grommet"

import Layout from "../components/layout"
import Image from "../components/image"
import SEO from "../components/seo"

const IndexPage = () => (
  <Layout>
    <SEO title="Home" keywords={[`gatsby`, `application`, `react`]} />
    <ResponsiveContext.Consumer>
      {size => (
        <>
          <Heading>Hi people</Heading>
          <Heading level="2">{`Size: ${size}`}</Heading>
          <p>Welcome to your new Gatsby site.</p>
          <div style={{ maxWidth: `300px`, marginBottom: `1.45rem` }}>
            <Image />
          </div>
          <Link to="/page-2/">Go to page 2</Link>
        </>
      )}
    </ResponsiveContext.Consumer>
  </Layout>
)

export default IndexPage
```

**Comment by oorestisime** [comment]
Do you have gatsby-plugin-styled-components installed?

**Comment by pawelsas** [comment]
Yes, current version.

**Comment by oorestisime** [comment]
And i guess you have it in the gatsby config? this is a weird error, i have multiple gatsby sites and haven't run into this issue just yet. any chance you could provide a full fledged reproduction?

**Comment by pawelsas** [comment]
I'm new to Gatsby and Grommet so this is likely my fault but I have no clue what is wrong. A weird thing I noticed: when I run `npm run serve` it works as well.

I'm going to create an example repo.

**Comment by oorestisime** [comment]
My guess is that you don't have `gatsby-plugin-styled-components` in your `gatsby-config.js` file. if you have a repo i could take a look

**Comment by pawelsas** [comment]
Here we go: https://github.com/pawelsas/gatsby-grommet-example

**Comment by pawelsas** [comment]
@oorestisime I've cloned your gatsby-source-instagram project. It looks like I have the same issue with your project. ResponsiveContext and media are not working in build. 

I'm really confused right now...

**Comment by oorestisime** [comment]
sorry i haven't had time to check this out yet. but jsut to be on the same page. During ssr it will always be medium. as soon as the page is loaded then it will change. the medium is just the default there. does this make sense? 
Here https://gatsby-src-instagram.netlify.com/ you can see the builded version and play with responsive design mode.

**Comment by pawelsas** [comment]
Yeah, but in my case it's always 'medium'. Maybe I miss something? After building I just open the index.html from public folder in my browser?!

**Comment by pawelsas** [comment]
Please forget the example Repo. It had another issue.
I will upload the actual project ASAP.

**Comment by oorestisime** [comment]
@pawelsas  Any news here?

**Comment by pawelsas** [comment]
The bug occured due to `i18next-xhr-backend` module. So I think this here can be closed. Thanks!

**Comment by ShimiSun** [comment]
@pawelsas thanks for the update!
