### ISSUE TITLE
Should Box gap use the same tag as its parent Box?

### ISSUE THREAD

**Issue by dallas** [grommet/grommet#3046]
### Expected Behavior

I would expect the gap elements within a `Box` component to have the same tag as the `Box` itself (e.g. `<Box as="span" gap="small">…</Box>` would also use `<span>` for each of the gaps).

### Actual Behavior

Instead, `Box` gaps are always `div` elements. This isn’t normally an issue, but since an `Anchor` with an icon uses an `"inline-flex"` `Box` component with a gap, it becomes an issue when that `Anchor` is within a `Paragraph`.

### Code Sandbox exhibiting the issue

Notice the console warnings when you first load this Code Sandbox: https://codesandbox.io/s/5yr109m8k4

### Steps to Reproduce

1. Create a `Paragraph`
2. Add an `Anchor` with an `icon` prop
3. Watch console for errors/warnings

### Your Environment

- Grommet version: 2.6.5
- Browser Name and version: Google Chrome 73.0.3683.103
- Operating System and version (desktop or mobile): MacOS Mojave 10.14.4

### Suggested Solution

Pass along the same `as`/`tag` props to the `StyledBoxGap` that are currently being passed to the `StyledBox` component.

**Comment by buoyantair** [comment]
@ShimiSun Can I take this? :)

**Comment by ShimiSun** [comment]
@buoyantair you got it buddy!

**Comment by jcfilben** [comment]
I think this issue can be closed since #4464 was merged
