### ISSUE TITLE
How do I custom style Grommet components?

### ISSUE THREAD

**Issue by chancesmith** [grommet/grommet#3049]
In the docs I see [`ThemeContext`](https://v2.grommet.io/themecontext). Is this the way to style the components or is there a different way?

I'm just clear on how to add custom styles to all components and one single component.

**Comment by josiahdahl** [comment]
Hey @chancesmith, I've been working through some of these same questions and here's a short overview of what I've found so far. I hope to contribute to the documentation a bit, as I find it lacking as well.

All of the available theme settings are listed here https://github.com/grommet/grommet/blob/master/src/js/themes/index.d.ts (auto-generated). Line 70 is where the component style descriptions start. Whatever you customize is merged with the base styles found here https://github.com/grommet/grommet/blob/master/src/js/themes/base.js using the `generate` function.

> You can also find the theme options in the docs in the Theme section https://v2.grommet.io/button#theme

Once you've customized what you want, you simply pass the theme object to the `ThemeContext` component and the child components should inherit that styling.

**Example**
```jsx
const theme = {
  button: {
      border: {
          width: '5px',
          radius: '0',
      },
      padding: {
          vertical: '1rem',
          horizontal: '2rem',
      };
  };

const CustomTheme =  () => (
  <ThemeContext theme={theme}>
    <Button>I have a border of 5px with no radius</Button>
  </ThemeContext>
);

// You might have the import the base theme, not sure...
const StandardTheme = () => (
  <ThemeContext>
    <Button>I'm the standard purple button with a radius</Button>
  </ThemeContext>
);
```

You can apply custom styles on a per-component basis by extending a component's styles with `styled-components`.

```jsx
import styled from 'styled-components`;
import { Button } from 'grommet';
const MyStyledButton = styled(Button)`
  font-weight: bold;
  background-color: #BADA55;
`;

const MyComponent = () => (
  <div>
    Press Button <MyStyledButton />
  </div>
);
```

> Some components accept an `as` prop - this doesn't work when extending them with `styled-components`. See #2699 

Let me know if that makes sense or if you have any other questions. I'm sure other people have more insight into it, but this is what I've found so far.

**Comment by oorestisime** [comment]
ThemeContext is great when you want to custom style components locally. meaning not to alter the components globally.
When you want all your anchors to have a [weight of 1000](https://v2.grommet.io/anchor#anchor.fontWeight)  then you want to pass this custom theme into the grommet top level component. https://v2.grommet.io/grommet
You will want to wrap `<Grommet theme={customTheme}><App/></Grommet>` your application in order for all the children to be access the modifications to the base theme changed by `customTheme`.

Hope this shreds a bit more light.

**Comment by josiahdahl** [comment]
@oorestisime thanks for clarifying! I do use the Grommet component to pass the theme globally but had a brain fart. I've updated my comment to reflect using `Grommet`

**Comment by oorestisime** [comment]
So does my comment respond to this issue? I am not sure if you are looking for any more info

**Comment by chancesmith** [comment]
What is the differnce between the Grommet component and ThemeContext?

**Comment by buoyantair** [comment]
Hi, @chancesmith Grommet component internally makes use of ThemeContext. Grommet is generally used at the root of the application to setup the Grommet UI (for example event handlers to keep track of website size for responsive web design etc). ThemeContext is basically this: 
https://github.com/styled-components/styled-components/blob/4115a1f8e4814b3843d781ce84d686c998ddfd3e/packages/styled-components/src/models/ThemeProvider.js#L14
 which is imported from Styled Components. It's just a plain ReactContext with an additional component property called "Extend" which enables you to extend a particular theme for _specific_ use cases.

**Comment by oorestisime** [comment]
spot on @buoyantair !
i may also add you should have only one Grommet component as the top level of your application. 
Then you can use as many times as you want the ThemeContext to change the theme locally (i.e change the color of the anchor only in one component etc).

**Comment by chancesmith** [comment]
Thank helps. Yet, from global Grommet, how do I give styles and colors to all `<Heading/>`'s, and other sub-components?

I made a repo asking about wrapping a styled-component `<ThemeProvider/>` and `<Grommet/>` around the full app. I'm trying to style `<Heading/>` and a HTML `<hr/>`.
https://github.com/sodiumhalogenteam/grommet-global-theme-example

Am I heading in a good direction?
What is the best way to set this up?

**Comment by oorestisime** [comment]
So few comments:

- you don't need to rewrite all the theme. only the parts you want to override. 
- for `<hr/>` you will need to create your own styled component. i think grommet doesn't provide an hr component. have a look in the docs for more info https://www.styled-components.com/docs/basics#getting-started
- to style the existing components you need to use the theme. what i am personally doing is checking the theme docs for the component (i.e for heading https://v2.grommet.io/heading) and looking what i would like to change. A handy property is the extend one. you can add any css property you want and it will get rendered. to answer your question about Heading. The color is not globally set but in the props. Either you create `const CustomHeading = ({...rest}) => <Heading color="red" {...props} />` or you use the extend property in the heading theme to add the color property. I would suggest you also check the patterns https://codesandbox.io/u/grommetux/sandboxes The use of theme, ThemeContext and extend can be found in there!

**Comment by chancesmith** [comment]
1. Okay, I'll only overwrite what I need.

2. Eeek. I usually use the styled-components [createGlobalStyle](https://www.styled-components.com/docs/api#createglobalstyle).

3. I need many CustomGrommetComponents? I thought I could modify the theme colors to modify the colors of any Grommet component.

**Comment by oorestisime** [comment]
Yeah you could do with global style although i don't think is that idiomatic to the whole component reasoning. Your application your call!

Usually you can set most from the theme. I cant check this right now but probably heading gets the color also from the theme. you might want to check colors->text
Maybe we should update the docs for this. @ShimiSun might have a clearer view as well on this.

**Comment by chancesmith** [comment]
@ShimiSun, any suggestions?

**Comment by ShimiSun** [comment]
@chancesmith long overdue response, thank you for your patient. 

I think you raised a good design/dev question on what is the best practice for composing a theme; my personal preference is to leverage the theme to minimize internal prop styling/coding. I'll use prop styling only when it can't be done with a theme. 

Let's say we have an app with the same Heading color cross the app (green), and there is only one place that requires Heading with a different color (red). 
In this case, the theme will dictate the common color, (I'll be using the `extend` styling since Heading doesn't accept an explicit color object)
```
heading: {
    extend: `color: green`
  }
```
so the `color` prop won't need to be explicit for every Heading component, it will stay as simple as `<Heading />`. The Heading component that requires a different color will be `<Heading color='red' />`. I think it is cleaner this way.

A little more advanced example, let's take the use case where there is only one section in the app that uses different Heading color but uses Heading with a different color (red) multiple times, in this case, instead of duplicating 
```
<Heading color='red' />`
...
<Heading color='red' />`
...
<Heading color='red' />`
...
```
This may be a good candidate to use ThemeContext just for this scope of code that uses the red Heading color, and define the color on the ThemeContext Heading color, it will simplify the multiple Heading components with the explicit `color` prop, as simple as:
<Heading />`
...
<Heading />`
...
<Heading />`
...
```

I've created a quick sandbox that demonstrates the ⬆️ above behavior https://codesandbox.io/s/heading-theme-themecontext-lhevm

I think the theme is a super strong tool, and in order to leverage it properly one needs to ask the right questions - so you are doing it right buddy :) 
I hope I covered and answered your questions, I'm thinking of writing a blog on the theme's best practices or something along those lines, so feel free to ask more questions if needed.

**Comment by oorestisime** [comment]
Closing this since seems to resolved. don't hesitate to open again to restart the discussion :)

**Comment by ssolari** [comment]
Wondering if someone could help me out with a design integration question related to this issue.    I have a designer who created a theme using the Adobe XD design kit.     In principle, I would like to simply upload the file or theme somehow.    Whenever they make changes it doesn't seem to make sense to me to have to redefine the theme manually, this would seem very error prone.

Are there methods of doing this?  Or if not what are the best practices for Grommet.

**Comment by ShimiSun** [comment]
Try to use the theme-designer tool and see if it helps https://theme-designer.grommet.io/Dashboard

**Comment by dpolant** [comment]
I settled on this for the use case of assigning different colors to different heading levels:

`const theme = {
  heading: {
    extend: ({ level, theme }) => {
      const colors = {
        '3': 'accent-4'
      };
      const color = colors[level];
      return {
        color: theme.global.colors[color]
      };
    }
  }
};`

Then inject that into your top level grommet container as usual:

`<Grommet theme={theme} full>...</Grommet>`
