### ISSUE TITLE
Tabs doesn't retain the value while navigating

### ISSUE THREAD

**Issue by jaitthomas** [grommet/grommet#305]
In http://www.grommet.io/docs/hpe/develop/tabs, enter some value in "Your Name" in first tab. Navigate to the second tab. Navigate back to the the first tab. Value entered in the first tab is lost. 

Tab doesn't retain values during navigation. If the values are to be restored in tab, there is no direct way to retain it. If Tab can have attribute such as 'retain=true|false' it will be helpful in development.

**Comment by alansouzati** [comment]
hi @jaitthomas I believe it is better to handle this scenario using react state. Check out this code pen: http://codepen.io/alansouzati/pen/KVQomV?editors=0010.

```
var App = React.createClass({
  getInitialState: function () {
    return {
      test: ''
    }  
  },
  
  _onTestChange: function (event) {
    this.setState({test: event.target.value});
  },
  
  render: function() {
    return (
      <Grommet.App>
        <Grommet.Tabs>
          <Grommet.Tab title="First Title">
            <h3>First Tab</h3>
            <p><input name="test" value={this.state.test} onChange={this._onTestChange} /></p>
          </Grommet.Tab>
          <Grommet.Tab title="Second Title">
            <h3>Second Tab</h3>
            <p>Contents of the second tab</p>
          </Grommet.Tab>
          <Grommet.Tab title="Third Title">
            <h3>Third Tab</h3>
            <p>Contents of the third tab</p>
          </Grommet.Tab>
        </Grommet.Tabs>
      </Grommet.App>
    );
  }
});

var element = document.getElementById('content');
ReactDOM.render(React.createElement(App), element);
```

In this case the input test will retain value because we are using react state.

**Comment by bryanjacquot** [comment]
@jaitthomas let us know if you still need assistance.  Closing this issue for now as the suggestion provided should handle your needs.

**Comment by harshithjv** [comment]
Hi @alansouzati ,

I thought I will open a issue similar to this but I think can comment on this thread as its similar issue.

I have CRUD forms on three tabs, i.e., Add, Delete and Update user forms. So when you navigate between tabs the user name field retains value. I have changed the id and fieldname and still the issue persists. Is it some code-glitch along with one of browser nuisances to preserve field value? 

Also note that password field gets cleared sometimes. It works this way:
1) When I fill fields on 'Add user' tab and click on 'Delete User' tab the username field is as it is. When you click on 'Reset Password' tab username still persists but password fields are empty.
2) Follow same steps as above but skipping 'Delete User' tab will retain password fields in 'Reset Password' tab

Refer the screenshot attached to this comment.

![userformrestproblemsontabclick](https://cloud.githubusercontent.com/assets/809278/18158845/741ba70a-7043-11e6-88aa-4474bc5745e7.jpg)
