### ISSUE TITLE
Datatable should support step so that onMore takes it into account.

### ISSUE THREAD

**Issue by faizi23** [grommet/grommet#3063]
firstly I was not able to use onMore prop of the data table but after a lot of effort I found out it works for data which is greater than 50 in the count.
If this is the case it is not written anywhere that data length should of greater than 50.

Why the value is set to greater than 50?
it should be customizable

### Steps to Reproduce
1. Document onMore of Data table Prop properly
2. Make sure there is a prop for customizing the no of data for which the onMore function will be called

### Your Environment

"dependencies": {
    "axios": "^0.18.0",
    "browser-router": "^0.2.0",
    "chart.js": "^2.8.0",
    "enzyme": "^3.9.0",
    "enzyme-adapter-react-16": "^1.9.1",
    "grommet": "^2.5.5",
    "grommet-icons": "^4.2.0",
    "react": "^16.8.2",
    "react-chartjs-2": "^2.7.4",
    "react-dom": "^16.8.2",
    "react-js-pagination": "^3.0.2",
    "react-redux": "^6.0.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.5",
    "react-test-renderer": "^16.8.2",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "styled-components": "^4.1.3"
  },

- Grommet version: 2
- Browser Name and version: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Desktop

**Comment by oorestisime** [comment]
have you tried adjusting the step property?

**Comment by faizi23** [comment]
@oorestisime yes I have, it is not making any difference, onMore is still working for data length greater than 50
I don't think step prop is supported by Data Table

**Comment by oorestisime** [comment]
Yeah indeed it isnt listed. Mind re-wording the title to reflect this? Datatable should support step so that onMore takes it into account.

**Comment by faizi23** [comment]
yeah sure

**Comment by ShimiSun** [comment]
Thank you for reporting! fixed, and will be available on our next release.
