### ISSUE TITLE
FormField as TextArea that supports markdown

### ISSUE THREAD

**Issue by 4face-studi0** [grommet/grommet#3064]
_Premise: I am an Android developer, just working on my personal website in my spare time, so forgive me about my noobness here_

### Expected Behavior

I successfully used a `TextArea` in my `Form` as following:
```jsx
<Form>
  <FormField as={TextArea} />
</Form?
```
Now I'd like to add support to markdown to that Component. 

### Actual Behavior 👇

🥴

**Comment by ShimiSun** [comment]
I might be missing something, why not using Markdown? something along this lines https://codesandbox.io/s/qkyko6k39

**Comment by 4face-studi0** [comment]
Because it's a `Form`. Using a `Markdown` inside the `FormField`, form field can't handle the text inside the `Markdown`

**Comment by oorestisime** [comment]
But why just a textarea isn't enough? Are you searching for syntax highlight or?

**Comment by 4face-studi0** [comment]
@oorestisime yep, I'd like to support **markdown**'s syntax highlights into a `TextArea`, part of a `Form`.
As I said Js and Front-end is not my field, so maybe I'm just making a mess 😅

**Comment by oorestisime** [comment]
No worries, i was just trying to understand your need. Well there is no component like this in grommet right now and i am not sure it is getting one soon. You are probably looking for a web based text editor like ace https://github.com/securingsincity/react-ace or maybe https://github.com/facebook/draft-js . 
For example for forms with yaml i use ace at work.

**Comment by 4face-studi0** [comment]
I think a could achieve something similar with just a `TextArea` + `Markdown`, isn't it? But then I'll have the same problem for "link" it to my form I guess... So I should take care of the validation of all my fields by myself, without taking advantage of the `Form` component, is that right?

**Comment by oorestisime** [comment]
you could have your markdown component subscribing to the textarea and just presenting the value. It would serve as a preview lets say. let me know if you want me to create a sandbox with this.

**Comment by 4face-studi0** [comment]
Thanks, I'd love a code example if you could.
That my actual field, maybe the twill save you some time:
```js
<FormField
  name="message"
  label={string("contact.form.message")}
  placeholder={string("contact.form.message.hint")}
  required={true}
  validate={validateMessage}
  as={TextArea}
  />
```

**Comment by oorestisime** [comment]
Put this up really fast so ignore styling ;) https://codesandbox.io/s/019qm7jpll
The idea is to have a controlled textarea and then use the value to provide the markdown component and see a live change. I am not sure this is what you are looking for! let me know if i didn't get what you are aiming for.

**Comment by 4face-studi0** [comment]
Thank you very much! Not exactly my primary idea, but a nice workaround if is not possible to do better in an easy way. I could use a checkbox for enable the preview only for "markdown users". Just checked the result as now, since I'm from smartphone, I'll check the code tomorrow. Thank you very much again!

**Comment by oorestisime** [comment]
if you an example of what you are looking for i would love to take a look

**Comment by 4face-studi0** [comment]
I'd just like to see the "real-time syntax highlight" in the same field where writing. So, a normal field that bold my text when I type the double '*'

**Comment by oorestisime** [comment]
Right, check this https://draftjs.org/ as well.

**Comment by 4face-studi0** [comment]
Ok, thank you for you time, you gave me enough hints 🙂 tomorrow I'll find the best solution and I'll update my main post. You can close the issue.

**Comment by ShimiSun** [comment]
Thank you for collaborating! good luck @4face-studi0
