### ISSUE TITLE
Duplicate key error when RadioButtonGroup option has value of 1

### ISSUE THREAD

**Issue by djm158** [grommet/grommet#3069]
It appears that RadioButtonGroup creates several Box components wrapping the RadioButton components it creates based on the `options` prop. Because Box components create `StyledBoxGap`s that are keyed off of the `index` of the rendered children, we get a duplicate key if you have an `option` where the `value` = `"1"` in RadioButtonGroup. Should probably be able to specify keys in the options prop of RadioButtonGroup (or something along those lines?)

### Expected Behavior

Should not have duplicate keys

### Actual Behavior

React throws a warning saying there are duplicate keys.

```
  <RadioButtonGroup
    name="Cell"
    onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
      this.setState({ cellValue: e.target.value })
    }
    options={[
      {
        label: "1",
        value: "1"
      },
      {
        label: "2",
        value: "2"
      }
    ]}
    value={this.state.cellValue}
    direction="row"
  />
```

### Steps to Reproduce

Use the component in the snippet above

### Your Environment

Grommet 2.6.6
Windows 10
Chrome Version 74.0.3729.108 (Official Build) (64-bit)

**Comment by mrebb** [comment]
@djm158 Another thought is to use `label` and `value` combination as key for `RadioButtonGroup` component and this new combination key would be no longer same as `index` value assigned to `StyledBoxGap` key.
