### ISSUE TITLE
chart sparkline is too small

### ISSUE THREAD

**Issue by zjufish** [grommet/grommet#307]
as in the http://www.grommet.io/docs/develop/chart
the sparkline chart is tiny even with size=large, anyway to get it larger?

**Comment by ericsoderberghp** [comment]
The sparkline size is intended to be small, to be included inline within text content. Can you provide an example of a situation where are you wanting to use a larger sparkline?

**Comment by bryanjacquot** [comment]
Closing for now.  You may also want to checkout the new Grommet charts: http://grommet.github.io/docs/chart/ which provide a lot of flexibility.
