### ISSUE TITLE
Button With type file not supported

### ISSUE THREAD

**Issue by Faizan-Khurshid** [grommet/grommet#3071]
<Button type="file" />
not working
what should I use for browsing files on my local computer?
Is there any alternate method?

### Your Environment

"dependencies": {
"axios": "^0.18.0",
"browser-router": "^0.2.0",
"chart.js": "^2.8.0",
"enzyme": "^3.9.0",
"enzyme-adapter-react-16": "^1.9.1",
"grommet": "^2.5.5",
"grommet-icons": "^4.2.0",
"react": "^16.8.2",
"react-chartjs-2": "^2.7.4",
"react-dom": "^16.8.2",
"react-js-pagination": "^3.0.2",
"react-redux": "^6.0.1",
"react-router-dom": "^4.3.1",
"react-scripts": "2.1.5",
"react-test-renderer": "^16.8.2",
"redux": "^4.0.1",
"redux-thunk": "^2.3.0",
"styled-components": "^4.1.3"
},

- Grommet version: 2

- Browser Name and version: Chrome Version 73.0.3683.103 (Official Build) (64-bit)

- Operating System and version (desktop or mobile): Desktop

**Comment by oorestisime** [comment]
For the moment only "button""reset""submit" are supported. You might be interested in creating a dropzone (#2535).
I personnaly use https://react-dropzone.js.org/

**Comment by seelikes** [comment]
@oorestisime is it possible to support file browser, this is a basic function. for now, i am facing the same issue.

**Comment by ShimiSun** [comment]
@seelikes we have a template idea for this type of functionality.
@MikeWalrath & @JetLim can we share the progress on the design? is @oorestisime working on it?

**Comment by ShimiSun** [comment]
adding this as a pattern idea that includes the above use case 
https://grommet.slack.com/archives/C04LMHN59/p1564499348114700?thread_ts=1564498504.114100&cid=C04LMHN59

![txt media](https://user-images.githubusercontent.com/6320236/62232020-79acd100-b382-11e9-90a8-e536c772e9a6.PNG)

@jermsam 👍

**Comment by jermsam** [comment]
@Faizan-Khurshid , check these out:
sandbox: https://codesandbox.io/s/github/jermsam/RichTextEditor/tree/master/
repo: https://github.com/jermsam/RichTextEditor

**Comment by mamathaveluru** [comment]
@ShimiSun @ericsoderberghp Great to see that Grommet prioritized FileInput, When can we expect this available in grommet package? Thanks in Advance.

**Comment by ShimiSun** [comment]
@mamathaveluru We currently provide integration example with Dropzone https://grommet-dropzone.netlify.com/

**Comment by ShimiSun** [comment]
A new FileInput component is now avilable on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F). It will be available on our next release, thanks for reporting.
