### ISSUE TITLE
Button gap in typescript getting error

### ISSUE THREAD

**Issue by FlyingUnicornSF** [grommet/grommet#3080]
<Button icon={<Ascend />} label="Last Saved" alignSelf='end' gap="large" onClick={() => {}} />
in tsx file. 
it's getting error
``Property 'gap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ButtonProps & Pick<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "ref" | "key" | "defaultChecked" | ... 261 more ... | "value">, any, any>> & Readonly<...> & Readonly<...>'.  TS2322``

### Expected Behavior

Not get error
### Actual Behavior

error
``Property 'gap' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ButtonProps & Pick<DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "ref" | "key" | "defaultChecked" | ... 261 more ... | "value">, any, any>> & Readonly<...> & Readonly<...>'.  TS2322``
### Steps to Reproduce

1. create a react app with typescript v3.4
2. put this element <Button icon={<Ascend />} label="Last Saved" alignSelf='end' gap="large" onClick={() => {}} />
3. cross your fingers

### Your Environment

- React version: 16.8
- TypeScript version:  3.4
- Grommet version: 2
- Browser Name and version: chrome - whatever the latest - it's auto update
- Operating System and version (desktop or mobile): ios

**Comment by oorestisime** [comment]
can you share the exact grommet version please?

**Comment by oorestisime** [comment]
oh this was fixed in master https://github.com/grommet/grommet/pull/3057 . upcoming release will have the fix.
