### ISSUE TITLE
Meter size not taking a font as string

### ISSUE THREAD

**Issue by britt6612** [grommet/grommet#3094]
The size for meter is not taking in a font size as a string
### Expected Behavior
The size for meter can be set to either 'xsmall' or you should also be able to use '24px'

The meter size should take into account a font size being passed in as a string
### Actual Behavior
An Type error that
fontAsString is undefined

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/jlz9n9nvj3

### Steps to Reproduce

1. Go to the code sandbox that was provided
 2. Go into the meter and you will see that 24px is passed at a string for the size but the error is coming up.

### Your Environment

- Grommet version: latest 
- Browser Name and version: chrome latest
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
According to the docs, Meter should accept a `string` i.e. custom size. so I'd mark this one as a bug.
