### ISSUE TITLE
Crash when rendering accordion on server side

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet#3099]
### Expected Behavior
Render accordion successfully on server side.

### Actual Behavior
Crash on SSR in production mode with the error message below.
> TypeError: Cannot read property 'active' of undefined

### URL, screen shot, or Codepen exhibiting the issue
None.

### Steps to Reproduce

1. Download the repro: "https://github.com/jim-king-2000/nextbugrepro".
2. Open shell and type the following command
```
cd nextbugrepro
npm i
npm run build
npm start
```
3. Open browser and access "localhost:3000", the error occurs.

It is very weird that we can get accordion render successfully if we run `npm run dev` which starts debug mode of Next.js or by client-side rendering. Although it fails when starting SSR in production mode.

### Your Environment

- Grommet version: 2.7.0
- Browser Name and version: Latest versions of Chrome, Firefox, Microsoft Edge
- Operating System and version (desktop or mobile): Windows 10, Ubuntu 18

**Comment by oorestisime** [comment]
I think the problem might not be in grommet directly. i haven't used a lot next.js but it seems there is something wrong with the context api. The value of the consumer is `undefined`. Do you know if next.js supports this?

**Comment by oorestisime** [comment]
@atanasster if i recall correctly you use often next.js. if you could provide an insight on this would be nice! You seem to have accordion in grommet-next this is why i am asking.

**Comment by jim-king-2000** [comment]
Hi @oorestisime , thanks for the replay. I'll report the bug to Next.js if you could show some hints that "Accordion" is innocent. By the way, the other components of Grommet can work perfectly with Next.js. That's why I decided to fire the bug here.

**Comment by oorestisime** [comment]
Lets wait for atanas to provide his opinion before. I just don't see anything done in the grommet code that would explain having a provider not correctly initialised. i haven't investigated a lot though.

**Comment by atanasster** [comment]
Hi @jim-king-2000 , seems its a next.js 8.1.0 issue: https://github.com/zeit/next.js/issues/7167

for now, you can install `"next": "^8.1.1-canary.33",`

**Comment by jim-king-2000** [comment]
Hi @atanasster , thank you very much and sorry for the bothering.
