### ISSUE TITLE
Issue with **"Responsive Context .Consumer"**

### ISSUE THREAD

**Issue by ypinnek1** [grommet/grommet#3102]
Issue with **"Responsive Context .Consumer"**

Cannot perform full screen on any videos after browser is resized/less than full viewport

When we are embedding a video in iframe, and when the browser is resized, the iframe is being reset due to DOM manipulation.
Either the elements containing the iframe are being destroyed and regenerated, or the elements are being moved to a different parent element.  In both cases, the browser treats the iframe as though it has been removed from the DOM and recreated at the new location.  This causes the iframe to load its contents again, which makes the player appear to reset back to the beginning.  

 Resizing the browser and entering full screen are both triggering the resize handler.  In the case of full screen, because the iframe initiating the full screen is removed temporarily from the DOM, the associated full-screen request gets canceled.

 To prevent this from happening, the responsive layout code needs to not redraw or reassign the elements containing the iframe.  Changing classes or styles is not an issue- it’s strictly DOM tree that must not change.  

This issue is due to using "**Responsive Context .Consumer**". removing this has solved the issue.

**Comment by oorestisime** [comment]
Can you elaborate a bit more here? Where do you think we should remove the consumer?

**Comment by ypinnek1** [comment]
The problem is with the consumer wrapper.
On using it, everytime the browser is resized the DOM elements are reloaded. 
Due to which, if I am playing a video via iframe & browser is resized, the iframe element is loaded again (player is loaded again, need to again click play). 
Also when browser is not in its 100% viewport, video will not go fullscreen due the problem mentioned above

**Comment by oorestisime** [comment]
Yes but at the same time the consumer enables the library to be reactive based on the screen width in case of resizing etc. I am going to investigate a bit.

**Comment by crashuniverse** [comment]
In a context based approach, the consumer will render if props (window size in this case) change. Is it even possible to stop this rendering in this way? It is an interesting problem and more I think about it, more I want to pick it up. I'll relay my findings to you @oorestisime

**Comment by crashuniverse** [comment]
I'm adding a very good example to move this discussion forward. Also for original author (@ypinnek1) of the issue can go through this example to see why it may not be a problem with grommet itself.

UI example: https://s4emq.codesandbox.io/responsivecontext
Source: https://codesandbox.io/s/grommet-sandbox-s4emq?fontsize=14 (Look at Utilities/ResponsiveContext in UI and `ResponsiveContextConsumer.jsx` in code).

I understood that although context makes children render, the iframe itself does not re-render.

**Comment by ypinnek1** [comment]
Hi Priya Ranjan,

In the example you have mentioned,

   1. The video player is in the same component where ResponsiveContext is
   used.
   2. My issue is a case in which I am using ResponsiveContext at root
   level and passing it down as a prop to the children. One of the deeply
   nested child is the video player which is being unmounted & mounted on
   browser resize.

Let me know if you have any questions. I will try to replicate the issue on
a dummy app & share it with you if time permits.

Thanks & Regards,
Yashwanth

**Comment by IanKBovard** [comment]
Just checked, I'm unable to replicate this issue in the current version of grommet. I think we can close this issue.

https://yxbux.csb.app/responsivecontext

**Comment by ShimiSun** [comment]
Thanks @IanKBovard. @ypinnek1 feel free to reopen or file a new issue. Thanks for reporting.
