### ISSUE TITLE
Issue with **open** prop of Select component

### ISSUE THREAD

**Issue by MrunalShidurkar** [grommet/grommet#3103]
An issue with **"Select"** component on opening select option programmatically. 

### Expected Behavior

When we try to open the select component programmatically, it should open the select-options 

### Actual Behavior

Set initial **open** prop to **false** and try to change it to true, which fails to open the select component 

### URL

[https://stackblitz.com/edit/grommet-270-selectbox-issue?file=index.js](https://stackblitz.com/edit/grommet-270-selectbox-issue?file=index.js)
### Code to Reproduce

` <>
        <Button label="open SelectBox" onClick={() => this.setState({ open: true })} />
        <Select
          multiple={true}
          value={value}
          open={this.state.open}
          options={options}
        />
  </>`

- Grommet version:2.7.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile):Windows 8.1

**Comment by ShimiSun** [comment]
@MrunalShidurkar thanks for reporting! fixed, and will be available on our next release
