### ISSUE TITLE
How would I use my custom font styling ?

### ISSUE THREAD

**Issue by Mohtashim-Sonasoft** [grommet/grommet#3107]
I wanna use my custom font styling instead of grommet font styling and also wanna edit grommet styling .

**Comment by ShimiSun** [comment]
This should do the trick https://codesandbox.io/s/customfont-ndtnd

I wasn't sure if you mean custom font as a none standard font family, so this should help as well https://github.com/grommet/grommet-theme-hpe/issues/5

Let me know if you need any more info.

**Comment by Mohtashim-Sonasoft** [comment]
2nd Link very helpful for me partially. Whenever I had to use global--> font--> family and face both keys and values so it was not working while I had use only family key and value here and font-face defined in my main.css file so its work properly.

This is my theme.js file
![image](https://user-images.githubusercontent.com/50501142/58229476-4713a600-7d4b-11e9-8508-98aa4c649f35.png)


and this one is my main.css file
![image](https://user-images.githubusercontent.com/50501142/58229487-51ce3b00-7d4b-11e9-8fc3-71ae83868a67.png)


while I am using this way my font works properly.

Thanks for your response.
