### ISSUE TITLE
Stateless functions

### ISSUE THREAD

**Issue by eabay** [grommet/grommet#311]
In Grommet codebase most of the components can be [stateless functions](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions).

Right now, there is not much to gain but as they [stated](https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html#stateless-function-components), they'll make performance optimizations specific to these components.

What do you think about converting possible candidates to stateless components?

**Comment by alansouzati** [comment]
Interesting concept. Thanks for checking this. I see a lot of components in Grommet that are a map of its props, so yes I like the idea of converting possible candidates (Anchor, Button, Form ...) to stateless components.

**Comment by eabay** [comment]
I am glad you agree. And I've started with `Anchor`, #313, and want to know what you think about if.

**Comment by eabay** [comment]
It appeared that stateless functions broke things and they need to be improved somehow...
