### ISSUE TITLE
Virtualize DataTable

### ISSUE THREAD

**Issue by cmmartin** [grommet/grommet#3111]
DataTable currently supports pagination with `onMore`. However, rendering the DOM is a much more common bottleneck than the network. 

It's fairly fast to load 1,000 rows worth of data over a network. But rendering 1,000 rows in the DOM pretty much never works and will block the thread and degrade the experience substantially.

It's a much better experience to scroll through a preloaded virtual list than it is to continuously pause scrolling and wait for a network request for the next page.

Pagination also makes sorting more difficult, since you haven't fetched all the data yet.

Pagination is obviously needed in certain cases, but I'd guess 99% of cases don't need it at all if we implement virtualization. 

I just wanted to open this issue to explore the possibility of virtualization. We could incorporate existing open source solutions like [react-window](https://github.com/bvaughn/react-window) or [react-virtualized](https://github.com/bvaughn/react-virtualized).

Let me know if anyone has any thoughts or concerns

**Comment by ShimiSun** [comment]
Interesting point of view to consider while focusing on DataTable enhancements. @ericsoderberghp

**Comment by ericsoderberghp** [comment]
Totally agreed. This is related to exposing InfiniteScroll's `replace` property in DataTable. Should be easy.

**Comment by ggill-tt** [comment]
Is there any estimated delivery time for 1st version of this ?

**Comment by Sherlock92** [comment]
Hi, we urgently need this resolved as we are rolling out soon. I made a PR to expose the replace property https://github.com/grommet/grommet/pull/3376.

@ericsoderberghp can you let me know if this looks ok and merge? Thanks!
