### ISSUE TITLE
autoFocus does not work with child components of Layer

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#3112]
### Expected Behavior
Child components of Layer should be able to be autofocused

### Actual Behavior
Autofocus does not work.

### URL, screen shot, or Codepen exhibiting the issue
Codesandbox demonstrating that autofocus of the TextInput works unless it is a child of the Layer component: https://codesandbox.io/s/grommet-v2-template-ltsyf?fontsize=14

### Steps to Reproduce

1. Add `autoFocus` to a TextInput
2. Make TextInput a child of Layer

### Your Environment

- Grommet version: 2.7.0
- Browser Name and version: Chrome 74
- Operating System and version (desktop or mobile): MacOS 10.14.4

**Comment by crashuniverse** [comment]
I've an upcoming PR and I'll discuss a few approaches here to determine validity of the pull request.

The current situation is for a11y, we have a hidden anchor element is created in layer and focus is set to this anchor element. Problem is this happens without `Layer` being aware of if children components carry an `autoFocus` prop or not, like an input element.

The approaches I found are:
1. Have a new prop `focusLayer` that is by default `true`, and when it is `false`, it does not autofocus anchor tag as something else in `Layer` has focus. I got the idea from https://github.com/reactstrap/reactstrap/blob/8.0.0/src/Modal.js#L66 after looking at several solutions.
2. `Layer` looks recursively inside `props.children` tree to detect an `autoFocus` prop. Expensive & inconvenient to write.

I'd like to use approach 1, but change the prop name to be `focusLayer` like react-aria-modal (a more accessible modal) does. Ex. https://github.com/davidtheclark/react-aria-modal/blob/master/src/react-aria-modal.js#L216
