### ISSUE TITLE
TextInput makes it difficult to listen for select events on input element

### ISSUE THREAD

**Issue by jvatic** [grommet/grommet#3118]
`<TextInput />` has an `onSelect` prop used for the suggestions feature which overrides the `<input />`s `onSelect` prop for listening to [`select`](https://developer.mozilla.org/en-US/docs/Web/API/Element/select_event) events. This makes listening to `select` events on the input more difficult than it should be.

As a solution, I purpose changing the current `onSelect` prop to `onSuggestionSelect` and allow `onSelect` to resume it's default behaviour on the `<input />`.

### Expected Behavior

`<TextInput onSelect={/* ...  */} />` should add the provided function as an event handler for `select` events.

### Actual Behavior

Grommet overrides the `onSelect` prop for suggestion selection events.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-5rcuj (includes a workaround).

### Steps to Reproduce

1. Define an `onSelect` event handler on a `<TextInput />`
2. Notice that it does not listen for `select` events on the `<input />`.

### Your Environment

- Grommet version: 2.7.0

**Comment by IanKBovard** [comment]
Im for having onSelect renamed to something else, so the default onSelect doesn't get overridden. If this is an acceptable solution, i can take this on.

**Comment by ShimiSun** [comment]
@IanKBovard let's discuss this on on our call tomorrow.

**Comment by ShimiSun** [comment]
@jvatic, thanks for reporting!
@IanKBovard next steps for this issue should be to create our own `onSuggestionSelected` call that will perform the same as our current `onSelect` function.
For backward compatibility, we will still accept `onSelect`, but in case the users will define `onSuggestionSelected` the `onSelect` will fallback to the [WebAPI](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onselec).
Let me know what you think.

**Comment by IanKBovard** [comment]
@ShimiSun sounds good to me. Ill get started on it.
