### ISSUE TITLE
autoFocus prop for TextInput

### ISSUE THREAD

**Issue by dougmacklin** [grommet/grommet#3119]
I think it would be useful to be able to autofocus on a `TextInput` without jumping through the hoops of assigning it a `ref`. This becomes particularly painful when trying to override the `Select` component's `searchInput` with a custom `TextInput` that automatically focuses when the select opens (see codepen for example).

### Expected Behavior

I would have access to an `autoFocus` prop like `<TextInput autoFocus />`

### Actual Behavior

I have to use a class component and use the `componentDidUpdate() { this.forceUpdate() }` hack to get the focus to work

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-pjdbd?fontsize=14

- Grommet version: 2.7.1

**Comment by juanlanus** [comment]
Should also work for TextArea and Select.  
I'd like to be able to use this feature ASAP, as all alternative focus control methods are a hurdle.  
IMO this is more a bug than an enhancement, because it's about restoring a feature that was present in HTML and React since ever.

**Comment by IanKBovard** [comment]
autoFocus is a default prop for input components. It works with TextArea, Select, and TextInput. we can close this issue.

**Comment by ShimiSun** [comment]
@IanKBovard I think you meant `focusIndicator`, and that is correct, it is available on input elements, see for example https://v2.grommet.io/textinput#focusIndicator
Focus is applied out of the box with additional theme customizations, you should be able to use it without `ref`.

I'll be closing this issue, thanks for reporting!

**Comment by nateq314** [comment]
I am seeing this behavior still. `TextInput` is accepting `autoFocus` but not doing anything with it. Tried to get around it with `ref` but it's not accepting `ref` as a prop.

**Comment by IanKBovard** [comment]
I'm able to use autofocus. Here's a codesandbox to play around with. Adding and removing autofocus from each field works on my end. 
https://codesandbox.io/s/cold-dust-9ti5f?file=/src/App.js
