### ISSUE TITLE
The Table header moves when using scrollable option

### ISSUE THREAD

**Issue by jldzcxlxn2** [grommet/grommet#312]
Description:

When using the Table component with the scrollable = {true } and the user scrolls the page, the header moves down and appears twice .

Grommet Version:

react: 0.14.6,
grommet: 0.5.3

![errorexample](https://cloud.githubusercontent.com/assets/16906452/12594729/dc567676-c44d-11e5-80d7-ccbbf2eed083.png)

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/pull/364
