### ISSUE TITLE
Change hover color on select options

### ISSUE THREAD

**Issue by c3s4** [grommet/grommet#3123]
I would like to set a "custom" color for hover event in select options elements. I searched for in documentation and the web but I have not found anything helpful.

### Expected Behavior

When the mouse over an element of the dropdown for a select component, the background color is the custom one, instead of the default gray.

### Actual Behavior

The hover color is the default one

### URL, screen shot, or Codepen exhibiting the issue

This is what I have
![current](https://user-images.githubusercontent.com/7916898/58464257-abf94280-8135-11e9-9c95-c358819bc13f.png)

This is what I would like
![desired](https://user-images.githubusercontent.com/7916898/58464275-b287ba00-8135-11e9-9946-86b84934fd11.png)

### Your Environment

- Grommet version: 2.7
- Browser Name and version: Firefox Dev Edition 68.0b4 (64-bit)
- Operating System and version (desktop or mobile): Mac OS X 10.14.4 (18E226)

**Comment by oorestisime** [comment]
Just to get you unblocked you can modify the hover color by changing the theme.global.hover.background color. this will also change the hover of the button so you would probably need to do this using the ThemeContext.Extend functionnality instead of doing this over the whole theme.

**Comment by ShimiSun** [comment]
Available on release ^2.7.6
