### ISSUE TITLE
FormField hidden property stills render border

### ISSUE THREAD

**Issue by brunocrpontes** [grommet/grommet#3128]
In some cases forms may have the need to contain an input with information important to the context of the action that will be done by it, but not necessarily that information should be shown to the user.

### Expected Behavior
When pass hidden props to FormField component, it don't display anything visually, but keep traceable by its parent Form.

### Actual Behavior

When you pass hidden objects to the Form Field component, it should do not display its content / children, but continue to process the bottom border and this breaks the previously designed by design

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/h1306

### Steps to Reproduce

1. Create a <FormField />
2. Add hidden props to it

### Your Environment

- Grommet version: 2.7.1
- Browser Name and version: Brave/Chrome/Firefox
- Operating System and version (desktop or mobile): Linux Mint 19 - Desktop

**Comment by oorestisime** [comment]
I am assuming this would be fixed by #2975

**Comment by IanKBovard** [comment]
I don't see this anywhere on the docs, do we still plan to support the hidden prop in FormField?

**Comment by ShimiSun** [comment]
This actually works as expected, the `hidden` is propagated to the input filed which is hidden while the border is coming from FormField itself.
I'd recommend using a logic differently if you'd like to apply `hidden` to the whole FormField, something like :

```
...
const [show, setShow] = useState();
...
render() {
    return (
      <Grommet theme={grommet}>
        <Box pad="small">
          <Form onSubmit={this.onSubmit}>
            <FormField name="field-1" />
            { show && <FormField name="field-hidden" value="1" /> }
            <Button type="submit" label="Submit" />
          </Form>
        </Box>
      </Grommet>
    );
```

**Comment by brunocrpontes** [comment]
Using conditional to render the form i lost the utility to receive the value from onSubmit. Isn't perfect, but is a valid work around.

Thanks 🥇 

> This actually works as expected, the `hidden` is propagated to the input filed which is hidden while the border is coming from FormField itself.
> I'd recommend using a logic differently if you'd like to apply `hidden` to the whole FormField, something like :
> 
> ```
> ...
> const [show, setShow] = useState();
> ...
> render() {
>     return (
>       <Grommet theme={grommet}>
>         <Box pad="small">
>           <Form onSubmit={this.onSubmit}>
>             <FormField name="field-1" />
>             { show && <FormField name="field-hidden" value="1" /> }
>             <Button type="submit" label="Submit" />
>           </Form>
>         </Box>
>       </Grommet>
>     );
> ```
