### ISSUE TITLE
Add max-height (or maxHeight) property for Box.

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet#3136]
### Expected Behavior
We need to set the max-height for Box component. So the height of Box can be the contents' height when the max-height is not reached or be max-height (and with scrollbar by setting 'overflow' to auto) when contents are too high.

### Actual Behavior
There is no max-height props for Box. And the same issue to max-width.

**Comment by oorestisime** [comment]
Hello thanks for reporting this. Grommet does not intend to respect all the css proprties around. You can always use the styled components api to produce what you seek. https://www.styled-components.com/docs/basics#styling-any-components
(ping us if you need help but the idea is that you can do a `const wrapper = styled(Box)`all my styling``). 
I am tagging this as discussion just in case we decide to add a max height around.

**Comment by jim-king-2000** [comment]
We meet the requirement frequently which many controls (checkboxes for example) are put in a Box. We expect the scrollbar is shown when there are too many controls which take too much room. Or the height of the Box should be set to the height of the contents if the controls are not so many. The simple and straightforward way to describe it is:

`<Box maxHeight='medium' overflow='auto' />`

**Comment by oorestisime** [comment]
yeah makes sense am not saying this is a wontfix right!! i just wanted to laid out some alternatives so that you are not blocked with this!

**Comment by ShimiSun** [comment]
@jim-king-2000 thank you for filing the issue, we appreciate your grommet mindset and your suggestion above.
We are thinking along the following lines to solve your issue, please share your opinion or further ideas
`<Box height={{min: 'medium', max: 'large'}} overflow='auto' />`
so the height will be `auto` according to its content, but will still be controlled with a potential min/max object filled with "t-shirt" size values. 
Will you be willing to share your thoughts whether the suggestion should work for your use case, and maybe take it to the next level of making a code contribution?

**Comment by jim-king-2000** [comment]
The suggestion is great! It exactly match what we need.

**Comment by ShimiSun** [comment]
@jim-king-2000 awesome! Glad to hear, care to make an open source contribution? 
The initial way to go will be to extend the hight and width props to accept an object and set the styled component with the corresponding min & max values.

**Comment by jim-king-2000** [comment]
Hi ShimiSun, I'm not so familiar with the code of Grommet. If I were to prepare the code, the time of finishing it would be several months. Do you mind that it would be to long?

**Comment by ShimiSun** [comment]
@jim-king-2000 Hi buddy, that will be great, please take a try at it and reach out to us on slack if you need any help, we appreciate your contribution effort 💟

**Comment by jim-king-2000** [comment]
Sure. I'll get you posted when there's any progress.

**Comment by jim-king-2000** [comment]
Hi @ShimiSun , how to test the change?

**Comment by ShimiSun** [comment]
Create a storybook example and call it maxHeight. In the content of the story put a simple but clear example of how to use the new prop.
Also, there is the test file, make sure that the new prop is being tested.

**Comment by jim-king-2000** [comment]
Thanks. I'll try it ASAP.

**Comment by jim-king-2000** [comment]
I see the empty storybook after running "npm i&&npm run storybook". Is there any doc that guide me to the test? By the way, I'm using Windows 10.

**Comment by ShimiSun** [comment]
I'll use `yarn storybook` to verify the new story. And use `yarn test update` to create new snapshots for the added feature. I'll also make sure that the new created snapshots are all new code and are backward compatible (i.e not overriding previous snapshot code). Hope it makes sense.

**Comment by jim-king-2000** [comment]
Great! "yarn test update", that is the thing interested.

**Comment by jim-king-2000** [comment]
Hi @ShimiSun , the PR is sent. Let me know if there is any additional work.
