### ISSUE TITLE
MaskedInput - name prop not being passed to event.target.name

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet#3137]
### Expected Behavior

On the `<TextInput>` component, the `name` prop is passed to the `onChange` event. This is not happening with the `<MaskedInput>`.

### Actual Behavior

`event` object only contains `target.value`

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommetsandbox-c3ipe
(See console log after updating 1st masked input box) 

- Grommet version: 2.7.1
- Browser Name and version: Chrome 74
- Operating System and version (desktop or mobile): Win 10

**Comment by oorestisime** [comment]
Indeed, the issue is with the selection. https://github.com/grommet/grommet/blob/master/src/js/components/MaskedInput/MaskedInput.js#L230 we don't re-introduce the other target properties like here https://github.com/grommet/grommet/blob/master/src/js/components/MaskedInput/MaskedInput.js#L211

**Comment by ShimiSun** [comment]
I believe this issue is fixed, feel free to let us know if anything else is missing.
