### ISSUE TITLE
Can we change border radius of DropButton?

### ISSUE THREAD

**Issue by flaurida** [grommet/grommet#3138]
Hi Grommet,

I am trying to change the border radius of the content that becomes visible in `DropButton`, is there a way to do that? 

Thanks,
Laura

**Comment by flaurida** [comment]
Figured it out, thanks!

**Comment by cirdes** [comment]
@flaurida, could you share your solution?

**Comment by flaurida** [comment]
Hi @cirdes  - I solved it by passing `dropProps={{plain: true}}` and then styling the child. I'll paste a more expanded code snippet below. Let me know if that works for you!

```
  return (
    <DropButton
      a11yTitle="User Menu"
      dropContent={<UserMenuContent name={name}  />}
      dropProps={{ plain: true }}
    >
      <Avatar />
    </DropButton>
  );
```

**Comment by cirdes** [comment]
@flaurida . I tried to use plain:true and I was able to set border-radius but the box-shadow isn't working

dropContent
```
<Box width="240px" round="5px" elevation="medium" background="white">
...
</Box>
```
