### ISSUE TITLE
Probably a bug in types for color prop in <Text> component

### ISSUE THREAD

**Issue by c3s4** [grommet/grommet#3139]
If I try to use a color for <Text> component in the "object" way with dark and light attributes I get this typescript error: "Type '{ dark: string; light: string; }' is not assignable to type 'string | ({ dark?: string; light?: string; } & string)'."

I think is because of the `& JSX.IntrinsicElements['span']` part of this
```
declare const Text: React.FC<TextProps & JSX.IntrinsicElements['span']>;
```

### Expected Behavior
Use this
```
<Text color={{ dark: "brand", light: "red" }}>My custom text</Text>
```
without typescript errors

### Actual Behavior

I'm getting this compilation error: _"Type '{ dark: string; light: string; }' is not assignable to type 'string | ({ dark?: string; light?: string; } & string)'."_

### Steps to Reproduce

Just use this:
```
<Text color={{ dark: "brand", light: "red" }}>My custom text</Text>
```
in a typescript environment

### Your Environment

- Grommet version: 2.7.1
- Browser Name and version: -
- Operating System and version (desktop or mobile): Desktop Mac OS 10.14.4 (18E226

**Comment by oorestisime** [comment]
Nice catch. this should be the case with other components as well such as Heading or Paragraph. fix is easy and should use the omit utility as here: https://github.com/grommet/grommet/blob/master/src/js/components/Heading/index.d.ts#L18
