### ISSUE TITLE
Required FormField labels should be rendered with an *

### ISSUE THREAD

**Issue by charleenfei** [grommet/grommet#3140]
It would be great if when a FormField component contains the `required` prop, the label of the field is displayed with an asterisk after ie: `Name *`.

This would allow us to not have to manually insert the asterisk for better UX.

**Comment by oorestisime** [comment]
So there is some discussion on slack going on. probably grommet shouldn't be opinionated here. best course of action is probably to propose a story that wraps formfield and does this so that we can support `*` or `required` word etc.

**Comment by elieteyssedou** [comment]
I'd use that. 🙏

**Comment by ShimiSun** [comment]
great idea @oorestisime , @britt6612 will be taking a look at it ❤️

**Comment by ShimiSun** [comment]
@charleenfei & @elieteyssedou You can find the Required Label story available on storybook, thank you for the suggestion ! closing the issue
