### ISSUE TITLE
MaskedInput - cannot exit dropdown without selecting value

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet#3144]
Once the MaskedInput is selected, the dropdown does not disappear until a value is selected. If user clicks somewhere else on the page, the dropdown remains active which is not expected behavior. 

### Expected Behavior

When user moves away from the MaskedInput field, the dropdown should disappear.

### Actual Behavior

Dropdown stays visible and does not go away until user enters a valid value.

### URL, screen shot, or Codepen exhibiting the issue

This behavior can be seen on the grommet docs code sample https://v2.grommet.io/maskedinput

**Comment by adampblack** [comment]
+1 

When I click off the control the window stays open.

When I select a value from the list it also stays open.
