### ISSUE TITLE
Button shouldn't apply transition to all the properties

### ISSUE THREAD

**Issue by dimitrisnl** [grommet/grommet#3145]
https://github.com/grommet/grommet/blob/71671c87873f0602c1420234e2dc71265479ad18/src/js/components/Button/StyledButton.js#L127-L131

I believe that

1. Color
2. Background Color
3. Border Color

should be enough.

Please let me know if I'm missing something, and I would love to submit a PR.

**Comment by oorestisime** [comment]
Not sure i understand what you mean here. care to explain a tiny bit more?

**Comment by oorestisime** [comment]
I mean why not have it for all.

**Comment by dimitrisnl** [comment]
@oorestisime 	I was implementing a ButtonGroup component (like [this one](https://getbootstrap.com/docs/4.3/components/button-group/)). Due to the CSS rules, when the buttons were exactly 2, the border-radius would be animated.

Of course I could patch it in my implementation, but it made sense to me to be specific about the properties that have a transition effect.

**Comment by oorestisime** [comment]
right makes sense! do you feel like opening a pr?

**Comment by dimitrisnl** [comment]
Sure thing
