### ISSUE TITLE
Module not found "classnames"?

### ISSUE THREAD

**Issue by jastuccio** [grommet/grommet#3148]
[Grommet Starter - Existing App instructions](https://github.com/grommet/grommet-starter-existing-app#grommet-starter---existing-app)

Installing with either NPM and Yarn returned an error when I run `start` iin the terminal:

```
Failed to compile.

./src/pages/index.js
Module not found: Can't resolve 'classnames' in <path to my-app>/grommet-ui/src/pages
```

`yarn add classnames` resolves the issue for me. I looked in package.json going back a few commits and did not see a `classnames` package.

Am I the only one that experienced this issue?

### Your Environment
- Grommet version: 2.7.1
- Browser Name and version: FF developer 68.0b7
- Operating System and version (desktop or mobile): MacOS 10.14.5

**Comment by oorestisime** [comment]
I wonder whether this broke with the recent major release of mui. care to make a PR on the starter to fix this?

**Comment by crashuniverse** [comment]
Spot on. 17 days back in their major release, they moved away from `classnames` to `clsx`. Instead of using `latest` in `package.json` we could use `^3.3.0` and similar for other packages. I am available to work closely with @jastuccio for any help we may need here.

**Comment by jastuccio** [comment]
Cool 😁.  Thank you @crashuniverse!

I forked Grommet.  I am guessing "mui" = material UI.  I do not see that in package.json. Which dependency needs to be rolled back to 3.3.0?  What will it take to update Grommet to work with [clsx](https://www.npmjs.com/package/clsx)

**Comment by oorestisime** [comment]
oh no the dependency is not in grommet. just the starter example you mentioned above.

**Comment by jastuccio** [comment]
Thank you @oorestisime. Now it makes sense why I could not find that dependency.   I am a pull request noob, but decided to make a draft pull request anyway.

**Comment by oorestisime** [comment]
Closing this issue since there's a PR and it is not in the right repo.
