### ISSUE TITLE
Set icon custom dimensions

### ISSUE THREAD

**Issue by localhosted** [grommet/grommet#315]
How can I set an icons dimensions? Using the `style` property won't work:

    <Grommet.Icons.Base.CaretUp colorIndex="brand" style={{height: 12, width: 12}} />

With the above code, the icons continue with their 24px width and height.

**Comment by alansouzati** [comment]
In general we don't enable custom styling. Instead we provide normalized sizes (small, large). The smallest size we enable for icons is 24px. I'm wondering if we should add small(12px), medium (24px), large(48px). Can you share the environment where you want to render a 12px icon?

**Comment by localhosted** [comment]
When setting a tables order, usually there are up/down carets that signify the direction being ordered and availability of a column to be ordered. Like in: http://carlosrocha.github.io/react-data-components/

But, even then, I'm not actually sure having those smaller would fit.

**Comment by alansouzati** [comment]
I agree we should support a smaller icon version. I will add that to our backlog, PR gladly appreciated :+1: 

In the meantime you can use Sass and override the icon size.

```
.control-icon {
  width: 12px;
  height: 12px;
}
```
