### ISSUE TITLE
[Select] Allow the "value" prop to be a primitive when the options are objects

### ISSUE THREAD

**Issue by sradevski** [grommet/grommet#3154]
When the `options` props are objects, we need to specify a `valueKey` prop to specify which field holds the value, and a `labelKey` prop to specify the label for that value. Since we already have `valueKey` specified, it is more intuitive for the `value` prop to be whatever primitive the `valueKey` points to, instead of an entire `option` object.

The reasoning behind this is that we normally only want to store the value from a list, instead of an entire object describing how to render that list. However, if `value` has to be an object, we need to either store that object in state, or query the array that was used to generate the options every time we specify the `value` prop, and neither of the two is ideal.

For example, I would like to be able to:

```javascript
<Select
  placeholder='Passed an object as option'
  options={[
    { title: 'Object 1', value: '1' },
    { title: 'Object 2', value: '2' },
    { title: 'Object 3', value: '3' }
  ]}
  labelKey='title'
  valueKey='value'
  // Currently I have to do this:
  // value={{title: 'Object 1', value: '1'}}
  // I want to be able to do this:
  value="1"
/>
```
This would be a non-breaking change, so it shouldn't be an issue from that point of view.

- Grommet version: 2.6.6
- Browser Name and version: Irrelevant
- Operating System and version (desktop or mobile): Irrelevant

**Comment by c3s4** [comment]
I agree!!!
I don't really understand what the `valueKey` prop is for if the entire option is returned as value, but maybe I'm missing something :)

**Comment by ericsoderberghp** [comment]
The `valueKey` is used internally to determine which options are selected by comparing the `value[valueKey]` with the `option[valueKey]`.

**Comment by ShimiSun** [comment]
We are currently exposing both `valueKey` and `labelKey` as props that can control the value and labels of the Select `options`. I'll be closing the issue.
