### ISSUE TITLE
Serve documentation to Dash app (& similar apps)

### ISSUE THREAD

**Issue by bromso** [grommet/grommet#3155]
**Is your feature request related to a problem? Please describe.**
It's always frustrated when I'm on the "run" and don't have access to a stable internet connection. Especially when I'm out in the world as a Digital Nomad. The amount of reason why access to internet maybe down are so many, such as: power outage, poor reception, data plan is over due etc. It seems that you are always in a critical situation when you lose access to the internet (Murphy's law ;) ).

**Describe the solution you'd like**
If you could add/serve Grommet documentation (eg.: https://v2.grommet.io/components) to the Dash app (https://kapeli.com/dash , and similar apps), so that Digital Nomads can have access to all of the documentation offline.

Because Grommet is awesome and already uses the offline functionality built into HTML5, performing my feature request, would only serve Grommet as marketing/exposure activity.  Basically, "branching out" to other established platforms that developers already use, to showcase Grommet.

**Are you able to assist bring the feature to reality?**
Maybe... I'm looking into it as I write this.

**Additional context**

**Comment by bromso** [comment]
https://github.com/Kapeli/Dash-User-Contributions#readme

**Comment by ShimiSun** [comment]
Hi @bromso ,

>Are you able to assist bring the feature to reality?
Maybe... I'm looking into it as I write this.

were you able to make any progress you can share with us?

**Comment by bromso** [comment]
I don't think I have the programming skills to perform this task unfortunately. I haven't coded in like 10 years.

But if I understand everything correctly, it not that hard to do (if you got the skills):
- Copy the [Sample_Docset](https://github.com/Kapeli/Dash-User-Contributions/tree/master/Sample_Docset) folder into the docsets folder and rename it. Use the same name as your docset, but replace whitespaces with underscores. Note: don't add _Docset at the end of the name, just use the docset name (e.g. ExtJS) and nothing else.
- Archive your docset using:
  ```bash
  tar --exclude='.DS_Store' -cvzf <docset name>.tgz <docset name>.docset
  ```
- [Docset generation guide](https://kapeli.com/docsets)
- [Docset requirements](https://github.com/Kapeli/Dash-User-Contributions/wiki/Docset-Contribution-Checklist)
- [Versioning Guidelines](https://github.com/Kapeli/Dash-User-Contributions/wiki/Docset-Versioning-Guidelines)

**Comment by oorestisime** [comment]
i think this would need to rewrite the documentation to be in accordance with the docset requirements.
If what we need is just offline documentation then i guess we can have an offline service worker that caches the v2 website so that it can be accessed offline. i personally cloned the repo and build the documentation when i am on plane :)

**Comment by ericsoderberghp** [comment]
v2.grommet.io should already be usable offline. It has a service worker configuration. If you have an iPhone and add it to your home screen, you can use it offline.

**Comment by bromso** [comment]
I know and I love it!
I was just thinking from a marketing point of view. It's always good to market horizontally. And maybe Dashapp is to small for this purpose, what do I know? But maybe there are similar apps, editors, IDE were a similar approach could be taken to give the same type of functionality?

So perhaps close this issue?

**Comment by ShimiSun** [comment]
I kept this issue opened cause I think that 
>v2.grommet.io should already be usable offline. It has a service worker configuration. If you have an iPhone and add it to your home screen, you can use it offline.

will be valuable to other users, hence I want it to be documented properly on the grommet-site.

**Comment by oorestisime** [comment]
so we can close this?

**Comment by bromso** [comment]
@oorestisime Yes please! :)
