### ISSUE TITLE
[Select] Extend the "select.control" themability when the Select component is open

### ISSUE THREAD

**Issue by sradevski** [grommet/grommet#3157]
I would like to be able to change the style of the Select control component when the component is open. Adding a field to the theme like `select.control.open.extend` would be nice to have and would allow achieving this in the easiest possible manner.

**Comment by ShimiSun** [comment]
Thank you @halocline for enhancing grommet with this implementation, the fix will be available on ^2.7.4. 🎉

**Comment by sradevski** [comment]
Thanks a lot, I was actually going to work on it but didn't find the time since opening the issue. Cheers!
