### ISSUE TITLE
How to support old versions?

### ISSUE THREAD

**Issue by rothskeller** [grommet/grommet#316]
Today I had a need to make a bug fix in a Grommet application I wrote months ago (on Grommet 0.3.6).  I checked out the code of my application, ran npm install, made my change — and gulp dist failed because of new jslint checks that weren't there when the application was originally built.

It is essential, when supporting an old application, to be able to rebuild it *exactly* the way it was originally built, even if it was years ago.  npm's versioning model is designed to support this.  It's not clear to me what I did wrong; it seems clear that there was something in my environment whose version wasn't specified, and therefore got a new version when I ran npm install.  But I can't tell what it was.  Can you tell me what I did wrong?  Or, if it's something in Grommet, can you fix it?  Stable builds are a necessity for any production application.

[package.json.txt](https://github.com/grommet/grommet/files/107068/package.json.txt)

**Comment by kylebyerly-hp** [comment]
You probably got hit by a transitive or a direct dependency using any of the fun version range type options (>, >=, ~, ^, etc)

`npm shrinkwrap` seems to be one way to do lock down specific versions of direct and transitive dependencies for production and reproducability. Of course, this doesn't help you getting an unshrinkwrapped project going again.
Adding `--dev` saves the dev deps too.

Combining this with running `npm outdated` at the beginning of a new version cycle (and periodically) will probably get what we would want for predictable versioning and keeping up with the latest.

**Comment by alansouzati** [comment]
Thanks @kylebyerly-hp for great explanation.

@rothskeller I would take a look in any `eslint` dependency you have with `^` or `~` and remove it as you don't want to keep updating your dependencies.

I would replace `"gulp-eslint": "^1.0.0",`  with `"gulp-eslint": "1.0.0",`. In this case version 1.1.0 may add/remove roles and it is considered a minor change. There are more eslint dependencies in your package.json, so I would follow the same principle.

**Comment by bryanjacquot** [comment]
Changing a product to not use transitive dependencies is not sufficient.  We don't control the declaration of dependencies in underlying components.  Using this example, `eslint` depends on `esutils` and the manner `eslint` uses to declare that dependency is outside of our control.  As such, utilities such as shrinkwrap are necessary as it controls the version of the recursive list of dependencies.   https://docs.npmjs.com/cli/shrinkwrap

In grommet, we've decided to follow the pervasive pattern of allowing updates to keep using the latest version of dependencies.   It's up to each consumer to follow the same pattern or use something like npm shrinkwrap.
