### ISSUE TITLE
How to set background-color of RadioButton?

### ISSUE THREAD

**Issue by m11m** [grommet/grommet#3160]
I have noticed that the background color of a RadioButton cannot be set, which makes it difficult to complete some designs where the background color of other elements "behind" is different from the desired background color of the RadioButton.

**Comment by oorestisime** [comment]
Hey there,
I am not sure i get this right, but can't you add the button in a box and set the background there?

**Comment by m11m** [comment]
Have a look in code sandbox?

https://nqhcz.codesandbox.io/radiobutton

https://codesandbox.io/s/nqhcz

**Comment by oorestisime** [comment]
So you want the background around the button only and not the label ?

**Comment by m11m** [comment]
Right, some designs will need to a different background color inside of the radio button, right?

**Comment by oorestisime** [comment]
So i think this is a pretty edge case for adding a prop. here's how you can do it with the extend. https://codesandbox.io/s/grommet-v2-template-9gc01
What do you think of this? @ericsoderberghp @ShimiSun do you think we should add a prop?

**Comment by ericsoderberghp** [comment]
I tend to agree that this should be handled at the theme level and not via a new prop to RadioButton. Would that be sufficient?

**Comment by m11m** [comment]
Why not both? :D

Ok, thanks for showing me how to use the theme to set this, I'll try that. If it's not global, I guess I can wrap a theme extender component around it?

**Comment by ericsoderberghp** [comment]
To answer "Why not both?", one of grommet's key principles is simplicity, we don't try to provide properties for everything possible. Instead, we shoot for the most common needs. We realize this is a judgement call. We tend to wait for something to seem like a general need before adding a property for it. We don't always get this right, but that's the rationale.

**Comment by m11m** [comment]
![image](https://user-images.githubusercontent.com/1445487/60356753-6bd8ea00-9997-11e9-93cc-088061c04dff.png)

**Comment by m11m** [comment]
Ok, so now I'm trying to get the border to match the background and stay that way even on hover...

**Comment by m11m** [comment]
Ok, I think I figured it out, thanks. I'm getting what I need with a theme like:

``` 
{
radioButton: {
    check: {
      color: "black",
      extend: "background-color: white;"
    },
    color: "white",
    hover: {
      border: {
        color: ""
      }
    }
  }
}
```

**Comment by ShimiSun** [comment]
@m11m sounds about right. Feel free to take a look at all the potential `extend` options of the RadioButton in the theme https://github.com/grommet/grommet/blob/0ab1c512b5c2a3949aa1a083d95ce0e9ca91521e/src/js/themes/base.js#L645
I'll be closing this issue since we will stick with the theme solution rather than using a prop. let us know if we can help with anything else.
