### ISSUE TITLE
Add Mobile-first media queries

### ISSUE THREAD

**Issue by gonzarascon** [grommet/grommet#3162]
### Expected Behavior

Use `min-width` media queries for styles applied to components. 

### Actual Behavior

At the moment Grommet uses `max-width` media queries to apply the styles of each component. 

Is there any plans to implement this change? A bunch of search engines count on the Mobile-first spec for SEO optimization.

**Comment by gonzarascon** [comment]
Thinking further on this issue: There could be an option for defining custom Media  Queries in a custom theme similar to how breakpoints are defined.

**Comment by ShimiSun** [comment]
@gonzarascon I think you can use `extend` on the theme and apply any style you like including `min-width`. Do you have a use case this suggestion will not work for you?

**Comment by gonzarascon** [comment]
@ShimiSun I know that `extend` can be used for adding custom styles that grommet does not have out of the box, my point is that why not have `min-width` media queries from start? I think this feature could be a time saver.

**Comment by ericsoderberghp** [comment]
So, we have some components, like Heading that have a `responsiveBreakpoint` in the theme that ties in to the global theme breakpoints. Are you suggesting we do more of that?
I think I'm confused still on why `min-width` seems to be the primary concern. Are the current breakpoint definitions not working in some context?

**Comment by gonzarascon** [comment]
Hi @ericsoderberghp! There's no problem with the current breakpoint definitions, but they are using `max-width` media queries making Grommet, basically, a desktop-first framework. 
Don't get me wrong, sometimes `desktop-first` approach is the best for a website/app, but in other cases a `mobile-first` approach is needed and since [Google is changing it's indexing to Mobile-first](https://developers.google.com/search/mobile-sites/mobile-first-indexing) , it would be nice to have some kind of setting to allow you to choose what approach your project is going to use.

**Comment by jcfilben** [comment]
Hi just wanted to check in and see if there was still interest in this issue

**Comment by jcfilben** [comment]
Marking this as closed. We can revisit if interest arises.
