### ISSUE TITLE
Grommet v2 does not load on IE 11

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#3164]
going to https://v2.grommet.io/ on IE 11 results in the following error.
SCRIPT1002: Syntax error
vendors~main-b31570d6e1e32e26b39d.js (29,17318)

I get a similar error in my Grommet application now. I believe this used to work correctly.SCRIPT5022: Cannot create styled-component for component: [object Object].
index.js (14861,5)

**Comment by RobertGary1** [comment]
I'm on Grommet 2.5.5. Not sure what the v2.grommet.io website is on.

**Comment by dustykeyboard** [comment]
Seems that the webpack/babel build step didn't transpile this arrow function
`...,g=(e,t,n)=>t?n?u.UNICODE_IGNORE_CASE.get(e):u.UNICODE.get(e):u.REGULAR.get(e),...`

**Comment by oorestisime** [comment]
Maybe wrong here but isn't up to the application to add the polyfills?

**Comment by shivamsingha** [comment]
create-react-app adds this to package.json by default:  
```json
"browserslist": [
  ">0.2%",
  "not dead",
  "not ie <= 11",
  "not op_mini all"
]
```  
Maybe that's why it doesn't work in IE 11.  
Try changing `"not ie <= 11"` to `"not ie <= 7"`

**Comment by stefk** [comment]
This PR should fix the website: https://github.com/grommet/grommet-site/pull/110.

**Comment by ShimiSun** [comment]
@stefk you are my hero 🥇 PR merged!
