### ISSUE TITLE
Stack does not position where expected

### ISSUE THREAD

**Issue by c3s4** [grommet/grommet#3166]
If we use stack inside a generic container with a width greater then the stacked area, the child is positioned based on parent dimension

### Expected Behavior

The position is related to items contained inside the Stack component

### Actual Behavior

The child position is related to parent size.

### URL, screen shot, or Codepen exhibiting the issue

![immagine](https://user-images.githubusercontent.com/7916898/59846490-50029200-9360-11e9-991f-8aa7584009e4.png)

### Steps to Reproduce
```
<Box width="300px">
<Stack anchor="top-right">
  <Icons.Notification size="large" />
  <Box
    background="brand"
    pad={{ horizontal: 'xsmall' }}
    round
  >
    <Text>8</Text>
  </Box>
</Stack>
</Box>
```
### Your Environment

- Grommet version: 2.7.1
- Browser Name and version: Firefox Developer Edition
- Operating System and version (desktop or mobile): Mac OS Mojave desktop

**Comment by ericsoderberghp** [comment]
In the scenario you describe, Stack is behaving correctly since the default `align` for Box is `stretch`, meaning that the Stack container will stretch across the full width of the Box. Button works the same way. Generally, if you do not want this behavior, you would change the `align` of the containing Box. If there's some reason preventing that, you would wrap the Stack in a Box with the needed alignment there.

**Comment by c3s4** [comment]
Ok, no problem about a way to make things behave as I need, now I figured out how it works. Maybe I just imagined that stack behaved as a sort of container. My bad.
I think that this in documentation can be confusing:

> One child is designated as the guidingChild which determines the size. All other children are placed within that size, either above or below based on their order

**Comment by IanKBovard** [comment]
It looks like the documentation for stack has been updated. From my point of view, it's clear. @c3s4 if you're happy with the changes, I believe we can close this issue.

**Comment by ShimiSun** [comment]
Thanks @IanKBovard. 
Feel free to reopen if still relevant.
