### ISSUE TITLE
Placeholder in TextInput does not accept a react node usign typescript

### ISSUE THREAD

**Issue by c3s4** [grommet/grommet#3167]
Using typescript if you add a react node in the placeholder field you get this error:

```
TS2322: Type 'Element' is not assignable to type 'string | ({} & string) | (ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)> & string) | (ReactNodeArray & string) | (ReactPortal & string)'.
  Type 'Element' is not assignable to type 'ReactPortal & string'.
    Property 'children' is missing in type 'Element' but required in type 'ReactPortal'.
```

It seems there are some problems about typings in the placeholder field.

### Expected Behavior
No compiler error

### Actual Behavior

This compiler error:

```
TS2322: Type 'Element' is not assignable to type 'string | ({} & string) | (ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)> & string) | (ReactNodeArray & string) | (ReactPortal & string)'.
  Type 'Element' is not assignable to type 'ReactPortal & string'.
    Property 'children' is missing in type 'Element' but required in type 'ReactPortal'.
```

### Steps to Reproduce

Just try this:

```
<TextInput size="small" name="parcelWidth" placeholder={<Text>Foo</Text>} />
```

### Your Environment

- Grommet version: 2.7.1 with typescript v3.4.5

**Comment by c3s4** [comment]
I'm writing here again because we have the same issue for the `Tab` component in the `title` field.

If needed I'll open another issue

**Comment by oorestisime** [comment]
yeah pelase open a new one :)

**Comment by c3s4** [comment]
ok, I opened it right now: #3193

**Comment by c3s4** [comment]
Hi, I think the problem is not solved here for TextInput.
I didn't try the fix until now but it seems there's something wrong:

```
Type 'ReactNode' is not assignable to type 'string | ({} & string) | (ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)> & string) | (ReactNodeArray & string) | (ReactPortal & string) | (Element & string)'.
  Type 'number' is not assignable to type 'string | ({} & string) | (ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)> & string) | (ReactNodeArray & string) | (ReactPortal & string) | (Element & string)'
```

**Comment by c3s4** [comment]
@ShimiSun I think this issue has to be open again, what do you think?

**Comment by ShimiSun** [comment]
@c3s4 if you can provide a sandbox where the problem still reproduces, then of course, please attach it and feel free to open

**Comment by britt6612** [comment]
@ShimiSun this problem was not solved https://codesandbox.io/s/grommet-ts-v8lyz

**Comment by britt6612** [comment]
This same error is happening in #3205 #3193 
Adding the React.ReactNode is giving this error of 

TS2322: Type 'Element' is not assignable to type 'string | ({} & string) | (ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)> & string) | (ReactNodeArray & string) | (ReactPortal & string)'.
  Type 'Element' is not assignable to type 'ReactPortal & string'.
    Property 'children' is missing in type 'Element' but required in type 'ReactPortal'.
