### ISSUE TITLE
Change TextInput width and show multiple on the same row

### ISSUE THREAD

**Issue by c3s4** [grommet/grommet#3168]
I can't find a way to change text input field width and place multiple of them in the same row.
I tried a lot of workaround but no one worked.
I saw a `div` surrounding the input field in the output with its width to 100%, so I think the problem is this one. I know I can wrap each field with a `Box` of a custom size but I think is very bad to add another element just to change a width.

### Expected Behavior

Change width of the text input field

### Actual Behavior

Every field takes all the parent width

### URL, screen shot, or Codepen exhibiting the issue

![immagine](https://user-images.githubusercontent.com/7916898/59858924-2192b000-937c-11e9-9152-501402cb7c62.png)

### Steps to Reproduce

To obtain what is in the screenshot just use this code:
```
<TextInput style={{ width: "120px" }}/>
<TextInput style={{ width: "120px" }}/>
<TextInput style={{ width: "120px" }}/>
```

### Your Environment

- Grommet version: 2.7.1
- Browser Name and version: firefox develeoper edition 
- Operating System and version (desktop or mobile): mac os mojave

**Comment by oorestisime** [comment]
You have to use the Box component changing its direction to row.
```
<Box direction="row-responsive" gap="small">
<TextInput />
<TextInput />
</Box>
```

**Comment by c3s4** [comment]
Theank you for your suggest, i didn't find anything in the documentation about what this direction property was for. Anyway this solution is not completly working because I can't change the text input width. How can I do this? Only using the style property?

**Comment by oorestisime** [comment]
Here's the direction property https://v2.grommet.io/box#direction 
and here's the size property in text input https://v2.grommet.io/textinput#size

**Comment by oorestisime** [comment]
Closing this! don't hesitate to re-open if you need more info!

**Comment by c3s4** [comment]
Thank you again and sorry to be here only after a while.
I understand what the `row-responsive` is but I think is not what I need and also I think the size is not intended for what I described.

https://codesandbox.io/s/staging-browser-pt3qw?module=%2Fsrc%2Frow_responsive.js&moduleview=1

what is happening is:
- I have a responsive behavior, this is not wrong but is not what I'm looking for
- the size prop seems to only affect the font size

what I need is:
- place many fields in the same row
- have control to the field size

Here a way to accomplish my task:
https://codesandbox.io/s/staging-browser-pt3qw?module=%2Fsrc%2Frow.js&moduleview=1

Now I wonder if this is a good practice 🤔

**Comment by oorestisime** [comment]
For me wrapping it in a div is not bad. i would avoid adding hardcoded px in the width since we already support specific width values but that's all.
If you want to avoid the extra div, reading the code we seem to have this extend `props.theme.textInput.container.extend` in the theme.
You can add your width there. Right now it is at 100% which makes sense to me since the width should be handled by the parent.

**Comment by c3s4** [comment]
> For me wrapping it in a div is not bad.
ok, I agree, after all the input field is an inline element so the width is related to its content. Maybe I thought I could use the width attribute because is already wrapped in a div. But I can live with this :)

> i would avoid adding hardcoded px in the width since we already support specific width values but that's all.
I completely agree, it was just to explain the concept.
