### ISSUE TITLE
deepMerge and other utils have no public documentation

### ISSUE THREAD

**Issue by DanielBaird** [grommet/grommet#3172]
### Expected Behavior

Utility tools that general users are expected to use, e.g. `deepMerge` for managing themes, should be documented sufficiently so that a user can follow Grommet's best practices.

### Actual Behavior

As far as I can tell, there is no documentation on grommet.io describing `deepMerge` or any other tool in `grommet/util`.

### Steps to Reproduce

https://www.google.com/search?q=site%3Agrommet.io+deepmerge

**Comment by ShimiSun** [comment]
labeled as `discussion` as I'm not sure where this will go on the site or docs, we might consider adding it [here](
![image](https://user-images.githubusercontent.com/6320236/61246405-fa759700-a70b-11e9-93db-899febe6e62c.png)) under `Utilities`

**Comment by ShimiSun** [comment]
We need to discuss why Utilities on the grommet site are components and not actual utils, and which grommet utils should we exposed due to grommet backward compatibility issues.

**Comment by ShimiSun** [comment]
You can find it now on the `functions` page https://v2.grommet.io/functions.
Thanks for the feedback!
