### ISSUE TITLE
"type" attribute missing from docs for TextInput

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#3180]
Need to document that type is a valid attribute here...
https://v2.grommet.io/textinput

**Comment by oorestisime** [comment]
Not sure if we want to document all valid html5 attributes. We probably need to make clearer that textinput is really an html5 input?

**Comment by gonzarascon** [comment]
@oorestisime It would be nice if the documentation clarified which components accepts html5 attributes!

**Comment by ericsoderberghp** [comment]
Agreed. Added https://github.com/grommet/grommet-site/issues/108
