### ISSUE TITLE
typescript fixes

### ISSUE THREAD

**Issue by jeremy-coleman** [grommet/grommet#3181]
Note: the root cause is not grommet, but styled components.
### Expected Behavior
no type errors
### Actual Behavior
errors everywhere

### Steps to Reproduce
use pretty much any component

### Your Environment
- Grommet version: latest
-@types/react: 16.8.22

i know maintaining typescript is a nightmare if your repo is in js, but here is how you can fix it if you want to.

Using the paragraph component as an example, you can fix it by changing the types to something like 
```ts
import * as React from 'react'
import { Omit } from '../../utils'

//just did React.HTMLProps for brevity
export interface ParagraphProps extends React.HTMLProps<any> {
  a11yTitle?: string
  alignSelf?: 'start' | 'center' | 'end' | 'stretch'
  gridArea?: string
  margin?:
    | 'none'
    | 'xxsmall'
    | 'xsmall'
    | 'small'
    | 'medium'
    | 'large'
    | 'xlarge'
    | {
        bottom?: 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | string
        horizontal?: 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | string
        left?: 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | string
        right?: 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | string
        top?: 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | string
        vertical?: 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge' | string
      }
    | string
  color?: string | { dark?: string; light?: string }
  responsive?: boolean
  size?: 'small' | 'medium' | 'large' | 'xlarge' | 'xxlarge' | string
  textAlign?: 'start' | 'center' | 'end'
}

/** important bit here */
export declare const Paragraph: (props: ParagraphProps) => JSX.Element;
```

**Comment by oorestisime** [comment]
do you feel like doing those fixes in a PR?

**Comment by jeremy-coleman** [comment]
I actually rewrote it all in typescript over the weekend, but decided against finishing it because of all the ‘munged’ props. Fixing the types would only take like an hour, i can do that np, but i think they are currently being auto generated from a script in react-desc , if so, would they not just be over written during build?

**Comment by oorestisime** [comment]
They are no longer auto generated. So you can go ahead and fix any of them you want and they will not get crashed by a build (maybe you need to pull?). 
Would be best to avoid huge changes in  one PR so we can follow but otherwise we are happy to receive any improvements for ts (or any PR as a matter of fact)

**Comment by ShimiSun** [comment]
I think we made a huge progress in this area, feel free to reopen or file a PR with anything you feel like is missing.
