### ISSUE TITLE
Video Component throw "Invariant Violation: Maximum update depth exceeded." when pass 'contain' to fit props

### ISSUE THREAD

**Issue by Basone01** [grommet/grommet#3185]
When i pass fit props as 'contain' to Video like this.

```
<Video controls="over" fit="contain">
  <source key="video" src={src} type="video/mp4" />
</Video>
```

I got this error.
![image](https://user-images.githubusercontent.com/25749290/60645066-e99e6900-9e61-11e9-8594-6d59789e1974.png)

But If I not pass this props, It's work like as I expected to get from fit='contain' props.

**Comment by ShimiSun** [comment]
@Basone01, not all platforms support the `fit` prop. can you please elaborate on which environment are you using? (browser, OS, mobile? )

**Comment by Basone01** [comment]
It's Google Chrome Version 75.0.3770.100 (Official Build) (64-bit) on MacOS High Sierra 10.13.6

**Comment by ShimiSun** [comment]
@Basone01 thanks, I've tried to run your markup code within a codesandbox, but interestingly the issue doesn't reproduce. https://codesandbox.io/s/video-3185-gqihw
Can you elaborate more on the issue?

**Comment by Basone01** [comment]
> @Basone01 thanks, I've tried to run your markup code within a codesandbox, but interestingly the issue doesn't reproduce. https://codesandbox.io/s/video-3185-gqihw
> Can you elaborate more on the issue?

I've just found something about that, I wrote it in my storybook (v5) and got that issue.
But when I put the same code in real app, it's work correctly.

**Comment by ShimiSun** [comment]
@Basone01 glad it is working for you! I'll be closing the issue, feel free to let us know if you have further questions.
