### ISSUE TITLE
[TS] Title in Tab component does not accept a react node usign typescript

### ISSUE THREAD

**Issue by c3s4** [grommet/grommet#3193]
Using typescript if you add a react node in the title field (inside a Tab component) you get this error:

```
TS2322: Type 'Element' is not assignable to type 'string | ({} & string) | (ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)> & string) | (ReactNodeArray & string) | (ReactPortal & string)'.
  Type 'Element' is not assignable to type 'ReactPortal & string'.
    Property 'children' is missing in type 'Element' but required in type 'ReactPortal'.
```

It seems there are some problems about typings in the title field.

### Expected Behavior
No compiler error

### Actual Behavior

This compiler error:

```
TS2322: Type 'Element' is not assignable to type 'string | ({} & string) | (ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<any, any, any>)> & string) | (ReactNodeArray & string) | (ReactPortal & string)'.
  Type 'Element' is not assignable to type 'ReactPortal & string'.
    Property 'children' is missing in type 'Element' but required in type 'ReactPortal'.
```

### Your Environment

- Grommet version: 2.7.1 with typescript v3.4.5

**Comment by ShimiSun** [comment]
Thanks for reporting @c3s4, it will be helpful for us if you can share a markup or reproduce the problem. 
This is a [codesandbox template of Grommet + typescript](https://codesandbox.io/s/6x2n6zxm63), it will help us speed up the process of seeing & fixing the problem if we already have it reproduced.

**Comment by c3s4** [comment]
ok, here the sample: https://codesandbox.io/s/grommet-ts-ffpyu

**Comment by britt6612** [comment]
@ShimiSun I'll work on this!
