### ISSUE TITLE
Carousel: prop to set activeIndex

### ISSUE THREAD

**Issue by luisrudge** [grommet/grommet#3199]
```
<Carousel fill activeIndex={2}>
  {files.map(f => (
    <Image src={f} fit="cover" />
  ))}
</Carousel>
```

Is this something you'd be willing to take a PR? I have this particular need in my application and there's no way to programmatically set what is the activeIndex for a given Carousel.

**Comment by oorestisime** [comment]
Sounds like a nice feature for me! Would love to see a PR

**Comment by ShimiSun** [comment]
Sounds fun to me too, let's see a PR with a storybook example to demonstrate the functionality, thanks buddy!
