### ISSUE TITLE
Shimmer Component

### ISSUE THREAD

**Issue by progmem64** [grommet/grommet#3200]
I need a Shimmer component like this one to mock paragraphs, unloaded menu items, ...: https://developer.microsoft.com/en-us/fabric#/controls/web/shimmer

How can I achieve something similar?

If you open the Storybook (https://storybook.grommet.io/) you can also see mocked menu items in the Sidebar to the left while the components are loading. But I guess that this is a feature of the Storybook-lib.

**Comment by ShimiSun** [comment]
@britt6612 is working on a template that might be helpful for this issue. we will post the template on the slack channel hopefully in the next couple of days.

**Comment by ShimiSun** [comment]
Hi @progmem64 , here is a template idea of how loaders/spinners and shimmer can be achieve using grommet https://codesandbox.io/s/loaders-and-spinners-4jltk, make sure to sign-in to our slack channels to get all of our live updates!
