### ISSUE TITLE
Add displayNames to all components

### ISSUE THREAD

**Issue by talarico43** [grommet/grommet#3201]
It looks like some of the components (Grommet, Box, Form, Image) have a displayName specified, but not all. It would be great if all of the components had a displayName to help with UI tests and making use of react dev tools.

**Comment by oorestisime** [comment]
Which components are missing the displayName? Isn't it inferred from the name of the component?

**Comment by talarico43** [comment]
Sorry, I think I may have logged this one prematurely. I saw that some of the components have an explicit displayName defined ([Box](https://github.com/grommet/grommet/blob/master/src/js/components/Box/Box.js#L14) for example), but not all.  If displayName is not explicitly defined, when a production bundle is built with uglification/minification those component names get converted to `<t>`.  I'm going to close this as I don't think this is something everyone will want.
