### ISSUE TITLE
Allow setting custom individual borders

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet#3203]
Could you please add a possibility to set custom individual borders with the Box component? E.g. with margin prop it is possible to set different vertical, horizontal margins, but with the border props one can only set a fixed styling for all the borders.
Ideally, I would like to have different borders with the same Box.

**Comment by ShimiSun** [comment]
Can you share a markup of how you'd think you'd like to consume it?

**Comment by nomadus** [comment]
Essentially, I would like to achieve the following.

<!DOCTYPE html>
<html>
<head>
<style>
div {
  background-color: white;
  width: 300px;
  border: 15px solid blue;
  border-left: 1px solid grey;
  border-right: 1px solid grey;
  border-bottom: 1px solid grey;
  padding: 50px;
  margin: 20px;
}
</style>
</head>
<body>

<h2>Demonstrating the Box Model</h2>

<p>The CSS box model is essentially a box that wraps around every HTML element. It consists of: borders, padding, margins, and the actual content.</p>

<div>This text is the content of the box. We have added a 50px padding, 20px margin and a 15px green border. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>

</body>
</html>

**Comment by shabtaisharon** [comment]
I was thinking of trying to tackle this issue by enhancing the border prop to also accept an array of "border styling". 
The current border styling:
```"top"
"left"
"bottom"
"right"
"horizontal"
"vertical"
"all"
{
  "color": "border",
  "size": "medium",
  "style": "dashed",
  "side": "all"
}
```
Will be enhanced with the additional support of:
```
[
  {
    "color": "border",
    "size": "medium",
    "style": "dashed",
    "side": "all"
  }, 
  {
    "color": "border",
    "size": "medium",
    "style": "dashed",
    "side": "all"
  },
  ...
]
```
for backward compatibility you can still use:
`<Box border={{color: "white", side: "vertical"}}>`

and for the custom option you can use:
`<Box border={[{color: "white", side: "top"}, {color: "red", side: "vertical"}]}>`

I want to make sure this is compatible with the grommet style before starting to work on the change. Any thoughts?

**Comment by ericsoderberghp** [comment]
That's how I'd do it. Sounds good to me.
