### ISSUE TITLE
Icon aligning is broaken in Menu component

### ISSUE THREAD

**Issue by dmitrij-borchuk** [grommet/grommet#3209]
https://github.com/grommet/grommet/blob/8105c0c2d9a5cb571702f5bb3fbcb0c3e9cad579/src/js/components/Menu/Menu.js#L198
Here you can see that Icon and Label are alined with the `<Box align="start">` and there is no clear method to aline them in the center.

**Comment by ShimiSun** [comment]
Can you please share a markup of what you are trying to achieve?

**Comment by ShimiSun** [comment]
@dmitrij-borchuk , I've created this sandbox to show how the menu icon can be handled in different alignments https://codesandbox.io/s/menu-icon-alignment-04m5k please share your thoughts on how else you'd like it to behave.

**Comment by dmitrij-borchuk** [comment]
@ShimiSun Hi, thank you for answering. I have forked your example and modified it to show the problem. pls take a look here https://codesandbox.io/s/menu-icon-alignment-0ecq1

**Comment by dmitrij-borchuk** [comment]
@ShimiSun You need to open the drop menu
![image](https://user-images.githubusercontent.com/3431453/61779428-52e21e00-ae09-11e9-9439-ee35f9a7a030.png)

**Comment by ShimiSun** [comment]
I think the root cause is here https://github.com/grommet/grommet/blob/924f237001ebff76ba107e64ebe291a8869224d3/src/js/components/Menu/Menu.js#L181
so if I add for example `align="center"` to this line, I get this layout 
![Screen Shot 2019-07-31 at 10 45 19 AM](https://user-images.githubusercontent.com/6320236/62231003-541ec800-b380-11e9-8eb9-94e24a2a627c.png)

@dmitrij-borchuk, Is this what you are trying to achieve? 

We want to think of a generic solution to solve this, maybe dropProps can accommodate a generic prop for the Button container. thoughts?

**Comment by ShimiSun** [comment]
after discussion: we might consider allowing the generic customization that is allowed with Select.

**Comment by dmitrij-borchuk** [comment]
My suggestion is to remove this container https://github.com/grommet/grommet/blob/924f237001ebff76ba107e64ebe291a8869224d3/src/js/components/Menu/Menu.js#L198 so icon and label will be aligned by `Button` component and we already have the possibulity to set properties on the `Button`s

**Comment by ShimiSun** [comment]
@dmitrij-borchuk , I suspect removing this line may cause a backward compatibility issue but I'm willing to consider your suggestion. 
Sounds like you are feeling comfortable enough with the code to file a PR, care to give it a try?

**Comment by ShimiSun** [comment]
I've added another storybook example to demonstrate how you could still play with the alignment without changes on grommet-core. try to see if it helps you out.

**Comment by dmitrij-borchuk** [comment]
@ShimiSun Thank you for the Storybook example. Later I will try to make a pull request if you still need it

**Comment by ShimiSun** [comment]
@dmitrij-borchuk yes, feel free to file a PR, this issue will be waiting for you :) appreciate your collaboration.

**Comment by dmitrij-borchuk** [comment]
@ShimiSun I have tried to make this fix, but looks like it pretty hard to do it with backward compatibility and without adding new component properties. So I gave up =( sorry

**Comment by ShimiSun** [comment]
Thanks, I'll be closing this issue due to the backward compatibility concern and lack of community interest.
