### ISSUE TITLE
Storybook structure 

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#3212]
This direction and issue came up from our #pattern-ideas channel on slack.
I thought it is worth tracking it because it does offer a good direction.
https://grommet.slack.com/archives/CEKR61G2D/p1560114072001400

from @crashuniverse:

I spent a few weeks with grommet and I had an idea this evening that I thought I can contribute to. I'll put my notes here to generate any reactions.
Improvements with how we write stories:

1. Usage: Every story must have the first story as the simplest one. This helps a developer
   to see the first story and look at the simplest props to make it work. This also reflects the core principle - 80% of grommet by learning the simplest way of using a component if user doesn't need much customization.
2. Storage of stories: Currently stories use filenames {component}.stories.js (Anchor & 34 more) 
   or stories/{use_case}.stories.js (Accordion & n more). We can restructure everything to follow
   2nd way i.e. using stories/ directory that seems to be more efficient by grouping and moreover
   separating them from actual components.
   To find stories following pattern 1:
   `~/D/l/grommet ❯❯❯ find src | grep -i .stories.js`
3. Fixing links in documentation: Story links of pattern https://storybook.grommet.io/?selectedKind=${availableAt}&full=0&addons=0&stories=1&panelRight=0
   are no longer valid so it should be updated with new pattern https://storybook.grommet.io/?path=/story/${availableAt}
   This would still not work completely unless we do 1 and have a "basic" story for every
   component and then use https://storybook.grommet.io/?path=/story/${availableAt}--basic
   Needs more research for a proper fix.
4. Add missing stories: Assess if some components like AccordionPanel (& 12 more) do need a story.

**Comment by ShimiSun** [comment]
Some components have stories named `Custom` because they are demonstrating the capabilities of the 'Custom Theme' of the component, and 'Custom' was the shortcut name for the story.
I'm thinking of renaming all the story names of `Custom` to `Theme` or some other short name that implies 'theme' context. 
This way the users will be more exposed to the Theme concept and get immediate theme examples per component. Custom doesn't imply 'theme' context because it can imply other types of customizations.
Thoughts and ideas will be appreciated.

**Comment by ericsoderberghp** [comment]
Excellent notion.

**Comment by ShimiSun** [comment]
Wonderful work on the storybook refactoring efforts!
