### ISSUE TITLE
Layer component error in IE11

### ISSUE THREAD

**Issue by stefk** [grommet/grommet#3221]
The layer component uses the `String.prototype.includes` method, which is not available in IE11: 

https://github.com/grommet/grommet/blob/master/src/js/components/Layer/StyledLayer.js#L79

Since no polyfill is included, this obviously results in an error being thrown immediately in that browser when the component is used.

**Comment by ShimiSun** [comment]
https://stackoverflow.com/questions/36574351/includes-not-working-in-internet-explorer

**Comment by stefk** [comment]
Fixed in #3223.
