### ISSUE TITLE
Unable to define new colors in HPE theme

### ISSUE THREAD

**Issue by bemineni** [grommet/grommet#3224]
Cannot customize HPE theme, by defining more colors
```
const theme = deepMerge(hpe, {
  global: {
    colors: {
      "my-text-color": "",
      // always use the same color regardless of the context
      //"another-color": "rgb(230, 60, 34)"
      // This is orange
      "another-color": "#ff916d"
    }
  }
});
```

<Button icon={Apps color="another-color" /} />

### Expected Behavior

another-color should be applied on ICON

### Actual Behavior

defaults to brand color or white.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/embed/understanding-v2-colors-j8m07

### Steps to Reproduce

N/A

### Your Environment

- Grommet version: V2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 2012

**Comment by ShimiSun** [comment]
Thanks for putting the sandbox together, it helped troubleshoot the issue more quickly.
You grommet-icons version doesn't know how to handle the theme color. I've upgraded grommet-icons to the latest and it works well.
https://codesandbox.io/s/understanding-v2-colors-ms6cs

**Comment by bemineni** [comment]
Moving to grommet-icons@4.2.0 fixed the issue. Thank you
