### ISSUE TITLE
Interaction Consistency Check resolutions

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#3225]
While comparing interaction behaviors across components, using https:designer.grommet.io/?id=Interaction-Consistency-eric-soderberg-hpe-com

We came up with the following issues:
- [ ] tabbing - tab on Menu and Select doesn’t open drop, in order to get the drop opened we need to click space.
tab on TextInput & MaskedInput does open the drop. 

- [ ] enter/select - by default, TextInput is closing the drop when clicking enter on one of the options, but MaskedInput doesn’t.

- [ ] focus + esc - working consistently.

- [ ] space - MaskedInput doesn’t open the drop on space after it had been closed. (Navigate with keyboard => MaskedInput is auto open => close it => try to open again using space => not opening anymore). this flow does open the drop on TextInput. 

- [ ] keyboard- one can't use the arrow keys to navigate through Menu items

**Comment by taysea** [comment]
Hi Shimi, I investigated these notes and these are my replies based on what typical HTML behavior is:
- Tabbing should not automatically open Menu or Select drops. However, there should be different behaviors for opening Select and Menu.
- [x] Select: Pressing space or up/down arrow keys should open it. (Grommet does this)
- [ ]  Menu: Pressing enter should open it. (Grommet does not do this. Currently, space or arrow keys can be used)
- [x] For both, Enter should be used to make a selection. (Grommet does this)

- Keyboard navigation within options of a Select drop and Menu drop should differ.
- [x] Select: Use arrow keys to navigate between elements. (Grommet does this)
- [x] Menu: Use tab to navigate between elements. (Grommet does this)

- TextInput drop:
- [ ] Typically, if drop is used a suggestion to complete text, it does not appear until the user has typed at least one character into the input field. (Currently, it automatically opens upon focus).

I will look further into the behaviors of masked input.

**Comment by ericsoderberghp** [comment]
This is fantastic!!! We should add this into the code comments somewhere. It should be persisted so we can refer to it readily.

**Comment by ShimiSun** [comment]
I agree!! Thank you for being so thorough on the investigation and presenting the outputs, as you make progress with this issue, feel free to embed comments regarding the accessibility considerations on the grommet code as @ericsoderberghp, GREAT work 💟 

Regarding the issues you presented:
>Menu: Use enter or space to open Menu? There seem to be two conflicting views (see Select Menu vs Menu Bar): https://webaim.org/techniques/keyboard/. Various websites have differing implementations of keyboard control on menus. We should discuss/decided which behavior we want to allow for. @ericsoderberghp

I'm suspecting, that in our use case it is true to say we are using Menu as a `Select Menu` rather than `Menu Bar`. AFAIK, we don't really have a component of a Menu Bar, usually, we use a collection of RoutedButtons or Anchors to implement a Menu Bar outside of grommet-core in case we want a Menu Bar behavior. The current Menu that grommet is providing, is closer, IMO, to the Select Menu behavior. @ericsoderberghp feel free to share inputs if you are disagreeing.

>Menu: Use tab or arrows to navigate between elements? There are two views: (see Select Menu vs Menu Bar): https://webaim.org/techniques/keyboard/. (Grommet allows for tab)

Same answer from me :) 

>Arrow keys should allow user to navigate between elements. (Grommet doesn't allow for any keyboard navigation of MaskedInput dropdown elements.

Feel free to mark this one as done, you've earned it!! 🥇

**Comment by ShimiSun** [comment]
Had to reopen due to a rollback of the accessibility PR https://github.com/grommet/grommet/issues/3408

**Comment by jcfilben** [comment]
Closing, Menu accessibility issues are being tracked in this issue https://github.com/grommet/grommet/issues/4068
