### ISSUE TITLE
Typescript definitions only implemented for object.js in utils

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#3235]
Multiple utils functions do not have typescript typings :
from colors.js:
colorIsDark
getRGBA
all other exports, not from object.js
https://github.com/grommet/grommet/blob/master/src/js/utils/index.js

**Comment by ShimiSun** [comment]
I'm not sure how much of those we will like to expose. It is also not part of our documentation.

**Comment by atanasster** [comment]
I think all exported classes and functions should be typed. In this case, I am using colorIsDark and can not import it from `grommet/utils.d.ts` -> have to go instead for `grommet/utils/colors.js` to import the untyped version.
If typescript is not a priority with v2, then also no need to export the object.js types from utils/index.d.ts - it just makes it confusing that some utils functions are typed, others are not.

**Comment by ShimiSun** [comment]
Thanks for sharing your findings, we'll take it all into account.

**Comment by ericsoderberghp** [comment]
Here's our current thinking on this one ...

We will publish documentation for the utils functions we'll commit to aligning with the semantic-versioning rules. I think @ShimiSun is already working on this.

**Comment by atanasster** [comment]
Not sure the semantic versioning is related to this issue?
For typescript, I think the best for utils functions is to export type definitions for all exported functions. Otherwise, the .js files and their .ts counterparts are not compatible and this is a bug in my opinion. Best would be to no go the current route of having all types in index.d.ts, but instead in the corresponding files ie styles.d.ts etc and export them from index.d.ts

For utils functions in general and their documentation as well as limiting which ones will be documented, Its hard to determine which functions are **really** just for internal use. I would suggest the other way around - make a case for any exported function why it **should not** be used by external apps and only then mark it as **internal only** for documentation and versioning purposes. The semantic versioning seems great, but i am not that familiar to give feedback.

**Comment by jcfilben** [comment]
I think since these util functions are not officially published or documented it is okay to not have typescript definitions them.
