### ISSUE TITLE
Typescript definitions - extract types

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#3237]
The types for common properties like `align`, `gap`, `margin` etc. need to be extracted in a core types file. The current typescript implementation leads to code duplications, both in grommet itself and in the applications using grommet.
https://github.com/grommet/grommet/blob/9a2663082bb21bb5d4a947cedfdc769451c72522/src/js/components/Box/index.d.ts#L7

for example 
`export type GapProp = "xxsmall" | "xsmall" | "small" | "medium" | "large" | "xlarge" | string;`

`
export interface BoxProps {
...
  gap?: GapProp,
...
}
`

**Comment by ShimiSun** [comment]
@britt6612 / @atanasster any other types that needs to be extracted?

**Comment by britt6612** [comment]
@ShimiSun there will be more especially once we start handling all of the event handlers for issue #3165

**Comment by ShimiSun** [comment]
Any updates on this issue?

**Comment by taysea** [comment]
I opened one more PR (see above), but after that I think we can close this.

**Comment by ShimiSun** [comment]
Thank you @taysea & @britt6612 for working on this issue! 
I'm closing the issue but let's keep our eyes open to keep optimizing the typescript coding.
