### ISSUE TITLE
Clock countdown timer does not work

### ISSUE THREAD

**Issue by jguo1002** [grommet/grommet#3246]
I wanted to add a countdown timer. But it seems not work using Clock. 
It just froze there and no countdown. 

Here is my code of a 30 min timer:

```
<Clock type="digital" time="PT0H30M0S" center="center" run="backward" />
```
[![Edit grommet-clock-example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-bassi-ykhj2?fontsize=14)

I set up as it says in the [doc](https://v2.grommet.io/clock). Was there anything wrong? 

- Grommet version: 2.7.4
- Browser Name and version: Chrome 75.0.3770.142
- Operating System and version (desktop or mobile): Mac 10.14.5

**Comment by ali-wetrill** [comment]
Any update on this?

**Comment by IanKBovard** [comment]
If #3246 fixed this issue we can close this.
