### ISSUE TITLE
Select options not shown any more after search for non-existent value

### ISSUE THREAD

**Issue by juanlanus** [grommet/grommet#3247]
In a Select with search, after searching for a value not present in the options, the options list doesn't show any more. Also does the search input. 

### Expected Behavior
Keep showing the search text and the clear [x] button.

### Actual Behavior
Both the list ans the search value disappear. 

### Steps to Reproduce

1- Open: https://storybook.grommet.io/?path=/story/select--custom-search
2- Open the Select
3- Type 21 in search: the list disappears (OK)
4- Click outside the Select
5- Re-open the Select
6- Notice that the options still don't show, but also the search value, and even there is no [x] to clear the not-visible search value

This is a bug because that "21" in the search input is the alibi for the stolen options list, so it must be shown - together with the [x] button to help the user repent for having entere an invalid value. 

### Your Environment
https://storybook.grommet.io
I'm running in Chrome Version 76.0.3809.87 (Official Build) (64-bit) in Ubuntu 19.04

**Comment by ShimiSun** [comment]
@taysea, we need to understand the rationale behind the current Select behavior and see if we can accommodate the issue's expected behavior without a breaking change.

**Comment by oorestisime** [comment]
@taysea let me know if you started working on this otherwise i might fix this.

**Comment by juanlanus** [comment]
In other tests I found that the onSearch() event calls its function with an undefined instead of an element when the search text is gibberish, and my console shows a stack dump. 
Maybe this is a similar case. 
Notice I'm not asking for help hare, I already solved it. I'm trying to help to make a bulletproof control. 
What I'm trying to communicate is that there might me a missing try/catch somewhere.

**Comment by taysea** [comment]
@oorestisime I haven't started working on this yet. If you have a fix, go for it!

**Comment by mlshv** [comment]
Hello everyone! 

I've discovered that it happens because SelectContainer gets mounted and unmounted every time when search opens and closes. The search text lives in SelectContainer state, but matched options list is stored in CustomSearch state.

For me, the most obvious way to fix it is to reset options list to default value on search dropdown close. Just checked – it works as expected. 

Am I doing it right? If so, I will make a PR.

**Comment by oorestisime** [comment]
By all means if you have a solution make a PR and we can discuss there! Thanks for jumping on this!
