### ISSUE TITLE
Enable Select to grow the list with new options

### ISSUE THREAD

**Issue by juanlanus** [grommet/grommet#3248]
Top-gun Select controls have options to add new items to the list. 
Like for example https://react-select.com/creatable 
As I see it, it should be available only in searched Select's. 
The functionality is to pass the search value typed by the user to the caller so she can handle the new value (for example popping-up a dialog, or whatever). 
This should happen when the user leaves the Select with enter or tab, not with esc or clicktouching outside. The user action should be one of the args of the handling function. 
I need this in my site to handle collaborative data creation. 

This is a feature request. I'm sorry I'm not smart enough to provide a PR even for this, that seems so simple to me. 
I would be happy to update the docs if this feature is added.

**Comment by markjackson02** [comment]
Yeah I am using react-select to accomplish this currently. This would be a welcome addition.

**Comment by nik72619c** [comment]
I would like to work on this

**Comment by juanlanus** [comment]
Hi Nik,
There are two kinds of options list: the simple strings array, and an array of objects.  
As I see it now (working with an array of objects), this feature would be practical to implement in the case of the strings array only, because the other case implies showing the user form interactions that will always be very application-specific. 
I would like to perform as a tester for you  :-)

**Comment by nik72619c** [comment]
cool, thanks !

**Comment by nik72619c** [comment]
Can I please know which component is exactly facing this issue?
Which one of the select component is this?

**Comment by juanlanus** [comment]
Select is a single component. 
It can be provided two kind of options lists: plain strings array, or objects array. 
IMO what you want to do makes sense only in the plain strings array case.

**Comment by nik72619c** [comment]
so basically the searched selects here, must work like react-select about which you mentioned. I believe the current behaviour is that the searched select inputs only display the current value being clicked or selected. Am I thinking in the right direction @juanlanus ?

**Comment by juanlanus** [comment]
Yes, Select displays a list of values and lets the user to choose one of the displayed values. 
The text the user types into the control is used as a search string, not as an input value. 
This issue is asking to allow the user to add the typed text to the list as a new item when it doesn't matches any of the existing items and the user wants to.

**Comment by oorestisime** [comment]
Hey folks before jumping into the implementation lets take some time to think a bit more on this. This will change the select behaviour so we need to think a bit on the API before. @ericsoderberghp @ShimiSun would love your thoughts as well.

**Comment by nik72619c** [comment]
#3430 please have a look and suggest changes :)

**Comment by ShimiSun** [comment]
Here is an example to achieve it https://storybook.grommet.io/?path=/story/select--create-option
