### ISSUE TITLE
parameter `responsive` in roundStyle of StyledBox is never used

### ISSUE THREAD

**Issue by crossjs** [grommet/grommet#3252]
https://github.com/grommet/grommet/blob/28366f60cda7ace2ff2d3a5d385f9eee8411f73c/src/js/components/Box/StyledBox.js#L239

**Comment by ShimiSun** [comment]
were you trying to use it? how did you run into this issue?

**Comment by crossjs** [comment]
> were you trying to use it? how did you run into this issue?

```jsx
<Box round="medium" responsive={false} />
```

**Comment by ShimiSun** [comment]
@crossjs I agree it might be redundant from the function, and I see it is true for `borderStyle` but does it impact your app in any way?

**Comment by crossjs** [comment]
> @crossjs I agree it might be redundant from the function, and I see it is true for `borderStyle` but does it impact your app in any way?

Yes. I want to use same `border-radius` in break-points.

**Comment by ShimiSun** [comment]
@crossjs the Box's responsive breakpoint is impacted by `global.breakpoints.borderSize` for the `borderStyle`, and by  `global.breakpoints.edgeSize` for the `roundStyle`. so you can still achieve customization of it by modifying these theme values, were you trying to do it in other ways?

I'll do a clean-up for those redundant arguments.
