### ISSUE TITLE
Calendar doesn't show first day of month if firstDayOfWeek prop is set to Monday

### ISSUE THREAD

**Issue by myktra** [grommet/grommet#3253]
### Expected Behavior

Calendar should ensure the first day of the month is always shown, regardless of `firstDayOfWeek` prop value.

### Actual Behavior

The first week of the month – _if the first day of the month falls on a Sunday_ – will not appear if the `firstDayOfWeek` prop is set to `1`, or "Monday" (it defaults to `0`, or "Sunday").

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-nqe6q

### Steps to Reproduce

Here's some code:

```
<Calendar
  firstDayOfWeek={1}
  date={(new Date(2019, 9, 0)).toISOString()}
/>
```

Notice that the calendar drops the first week of the month of September 2019.

### Your Environment

- Grommet version: 2.7.4
- Browser Name and version: Chrome 75.0.3770.142, Safari 12.1.1
- Operating System and version (desktop or mobile): macOS 10.14.5

**Comment by myktra** [comment]
Yay, thank you @ShimiSun et al!!! 

🙌

**Comment by ShimiSun** [comment]
Thanks for reporting buddy, thank you to @shabtaisharon for fixing it 🎉
