### ISSUE TITLE
Menu of drop button shows up at the top left corner of the page for the first time

### ISSUE THREAD

**Issue by bemineni** [grommet/grommet#3261]
I see the menu of drop button showing up at the top left corner of the page for the first time when the page loads. Next successive clicks on the button show the menu properly underneath the button. I am not able to reproduce this issue on code sandbox

### Expected Behavior
The  menu should show up beneath the button

### Actual Behavior

Shows up at the top left corner of the page on the first click, later shows up properly underneath the button.

### URL, screenshot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/1664905/62587616-628d4800-b888-11e9-927c-a76c0771f3a5.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.7.4
- Browser Name and version: Chrome 74.0.3729 
- Operating System and version (desktop or mobile): Windows 2012

**Comment by oorestisime** [comment]
Hm if this is not reproducible reliably i am not sure how we can investigate. can you share some more information with markup? or if this is in a public repository to link?

**Comment by ShimiSun** [comment]
I'll be closing this issue if there is no further information to help us reproduce the issue reliably.
