### ISSUE TITLE
JSConf - explore extending testing-library

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#3267]
Would it help grommet adoption if we provided some test integration libraries or utilities? Apparently testing-library has something this for react-select

**Comment by atanasster** [comment]
Yes it would attract the target audience (enterprise users), including adding testing hooks for commercial tools such as TestComplete, TestCafe etc. but i am afraid its currently a long shot - other issues are much more pressing imho. To clarify what I have in mind, i created a rough roadmap outline.

**Comment by jcfilben** [comment]
Closing in favor of https://github.com/grommet/hpe-design-system/issues/2344
