### ISSUE TITLE
Table cells' borders are broken when setting a size for the cell

### ISSUE THREAD

**Issue by imad93** [grommet/grommet#3281]
If a size is not set to TableCell inside a Table, the cell will grow horizontally so that all the content inside of it fit. This being said, all cells will have the same width.
Now when we fix all the cells' size, for example to small, and when a cell contains a long text, it will grow vertically so that the content fit. When this happens, other cells from the same row will add padding to the top and bottom so that the row doesn't get broken (which is normal behaviour).
If we set the border to 'all' for the TableCells, the border will only cover the Box inside the TableCell. Hence a broken and non-continuous border.

### Expected Behavior

The borders should always be aligned even if a cell's width grows.

When a user sets the prop border to a TableCell, he/she expects a border set on the TableCell and NOT on the Box inside the TableCell. User should not know that a Box is rendered inside the TableCell. If the user needs a custom Box inside, then he/she should just add one and style it by passing his own props to the Box.

### Current Behavior
A TableCell is rendered as a **td** tag containing a **div** (Box). The border is being set to the **div** (Box) instead of the **td**.

#### Why Why Why
TableCell calls StyledTableCell. Which is a styled td. It passes to the td **only** the following props:
props.size,
props.verticalAlign, and
props.tableContextTheme.extend

tableContextTheme being:
theme.table.body.extend or
theme.table.header.extend or
theme.table.footer.extend

All other props are being passed to the Box inside the TableCell.

### URL, screenshot, or Codepen exhibiting the issue

Here's a Codesandbox template that serves as a nice starting point
 for demonstrating an issue: https://codesandbox.io/s/grommet-table-broken-borders-e1bhz

![image](https://user-images.githubusercontent.com/10802895/63323725-c99a0a80-c326-11e9-8dfa-4ec3969544ae.png)

Here's a screenshot that shows how padding get added so that the row doesn't get broken.

![image](https://user-images.githubusercontent.com/10802895/63323896-27c6ed80-c327-11e9-9d84-5fb207cb38be.png)

### Possible fix
A way to fix (a hack) the broken **top** and **bottom** borders: instead of adding borders to the TableCell, add them to the row using CSS.

Instead of adding the border to the **div** inside the **td**, add them to the **td** itself.

### Environment

- Grommet version: 2.7.4
- Browser Name and version: Chrome Version 76.0.3809.100
- Operating System and version (desktop or mobile): Windows, mac, desktop

**Comment by imad93** [comment]
The explanation of this is simple. TableCell calls StyledTableCell. Which is a styled **td**. It passes to the **td** the following props:
`props.size`,
`props.verticalAlign`, and
`props.tableContextTheme.extend`

All other props are being passed to the Box inside the TableCell.

A fix for this is to **NOT** set borders for TableCells, but instead, create a theme.table.body.extend, in which CSS is added with custom borders, like so:

`const theme = {
  table: {
    body: {
      align: "center",
      extend: ({ theme }) => css`
        border-right-color: grey;
        border-right-style: solid;
        border-right-width: 1px;

        border-top-color: grey;
        border-top-style: solid;
        border-top-width: 1px;

        border-bottom-color: grey;
        border-bottom-style: solid;
        border-bottom-width: 1px;

        border-left-color: grey;
        border-left-style: solid;
        border-left-width: 1px;
      `
    }
  }
};`

Then call TableCell like this:
`<TableCell theme={theme} size="small"/>`

**Comment by ShimiSun** [comment]
Thanks for reporting buddy, the issue is fixed!
