### ISSUE TITLE
Button - hoverIndicator issue

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#3287]
`Button.hoverIndicator` property is used for call to backgroundStyle utility function.
https://github.com/grommet/grommet/blob/2212141e30b0cb262484e07999c705b01f035af1/src/js/components/Button/StyledButton.js#L57

However, the hoverIndicator property does not allow to use a full background object ie:
```
{
  dark: {
    color: 'dark-2',
    opacity: '1',
  },
  light: {
    color: 'light-2',
    opacity: '1',
  },
  border: {
    radius: '50%',
  }
```

The issue is both with react-desc .doc files and typescript .d.ts files, for my use case, the typescript implementation is a critical issue, but it might be worth fixing both.

Suggested fix:
1. Standardize a BackgroundType property to be same as the `<Box />` background property:
https://github.com/grommet/grommet/blob/2212141e30b0cb262484e07999c705b01f035af1/src/js/components/Box/doc.js#L76
2. Use in Button doc file: https://github.com/grommet/grommet/blob/2212141e30b0cb262484e07999c705b01f035af1/src/js/components/Button/doc.js#L47
3. Extract type script BackgroundType interface from `Box/index.d.ts` https://github.com/grommet/grommet/blob/2212141e30b0cb262484e07999c705b01f035af1/src/js/components/Box/index.d.ts#L19
4. Use BackgroundType in `Button/index.d.ts` for hoverIndicator property plus the allowed boolean as well as string 'background' which instruct the function to use theme hover settings

**Comment by britt6612** [comment]
Hi @atanasster I started looking into this hoverIndicator issue you filed. I have a clarifying question to make sure I understand your ask/suggestion. I have created a quick CodeSandbox (https://codesandbox.io/s/elated-waterfall-1719l) which demos passing in the same object to both Button's hoverIndicator and Box's background, which both render the intended styling. Can you help me understand what you expect to pass to these props and how they differ from what is implemented in this example?

Thank you in advance! 👍

**Comment by atanasster** [comment]
Hi @britt6612 thank you for taking care of this. 
You are correct  - both hoverIndicator and background should have the same property types since they do work the same under the hood.
The issue is reported about the .doc file and the typescript type file. So the fix is to update the doc and .d.ts files, possibly extract the BackgroundType type so it doesn't have to be duplicated. 

Hope it makes better sense now?
