### ISSUE TITLE
Documentation page (https://v2.grommet.io/docs) empty/broken

### ISSUE THREAD

**Issue by LucaBlackDragon** [grommet/grommet#3289]
### Expected Behavior

The documentation page sections ("grommet principles", "best practices", etc.) should contain useful information (or if they are intended to be links, they should bring the user to useful resources)

### Actual Behavior

The documentation page sections are empty:

![image](https://user-images.githubusercontent.com/3714010/63409722-05e66d00-c3f2-11e9-9dd7-0c3eae48cde1.png)

### Steps to Reproduce

1. navigate to the [documentation page (https://v2.grommet.io/docs)](https://v2.grommet.io/docs)

### Additional info

An error is logged in the browser console:

```
Uncaught (in promise) Error: Wrong response status
    at https://v2.grommet.io/sw.js:3:7979
    at async Promise.all (index 0)
```

**Comment by oorestisime** [comment]
Hi thanks for finding out, this is a WIP and something new we are adding to the site so not usable for right now!

**Comment by ShimiSun** [comment]
I was wondering how quickly someone notices that ❤️  thanks for raising it up... It's a WIP like @oorestisime mentioned, will keep you posted

**Comment by ShimiSun** [comment]
https://github.com/grommet/grommet-site/pull/115
