### ISSUE TITLE
.eslintrc adding rule to wrap comment lines

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#3290]
True. I've tested it locally and only the lines of code are being wrapped above 80 characters. and not comments. 
I fixed to comment positioning of this PR and it is good to go. 
@shabtaisharon feel free to file a PR with your suggested fix, adding this rule might be a good addition to grommet, thanks for your inputs!

https://github.com/grommet/grommet/pull/3288

_Originally posted by @ShimiSun in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDMxNjM4MjMzOA==/comments/review_comment_

**Comment by ShimiSun** [comment]
side comment: this change will cause many changes to the repo.

**Comment by ShimiSun** [comment]
➜  release git:(master) ✗ yarn run lint
yarn run v1.17.3
$ eslint src

/Users/shimi/github/release/src/js/components/Accordion/Accordion.js
  91:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Accordion/doc.js
  25:1  error  This line has a length of 107. Maximum allowed is 80  max-len
  26:1  error  This line has a length of 92. Maximum allowed is 80   max-len

/Users/shimi/github/release/src/js/components/Accordion/stories/Custom.js
  42:1  error  This line has a length of 85. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Accordion/stories/Rich.js
  72:1  error  This line has a length of 95. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/AccordionPanel/AccordionPanel.js
  150:1  error  This line has a length of 97. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Anchor/Anchor.js
  91:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Anchor/doc.js
  20:1  error  This line has a length of 84. Maximum allowed is 80   max-len
  62:1  error  This line has a length of 82. Maximum allowed is 80   max-len
  86:1  error  This line has a length of 144. Maximum allowed is 80  max-len
  97:1  error  This line has a length of 158. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Box/StyledBox.js
  58:1  error  This line has a length of 93. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Box/__tests__/Box-test.js
  128:1  error  This line has a length of 176. Maximum allowed is 80  max-len
  132:1  error  This line has a length of 164. Maximum allowed is 80  max-len
  139:1  error  This line has a length of 164. Maximum allowed is 80  max-len
  146:1  error  This line has a length of 164. Maximum allowed is 80  max-len
  153:1  error  This line has a length of 164. Maximum allowed is 80  max-len
  160:1  error  This line has a length of 164. Maximum allowed is 80  max-len
  167:1  error  This line has a length of 164. Maximum allowed is 80  max-len
  174:1  error  This line has a length of 164. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Box/doc.js
  458:1  error  This line has a length of 104. Maximum allowed is 80  max-len
  466:1  error  This line has a length of 97. Maximum allowed is 80   max-len

/Users/shimi/github/release/src/js/components/Box/stories/Background.js
  24:1  error  This line has a length of 81. Maximum allowed is 80  max-len
  34:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Button/Button.js
  155:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Button/doc.js
   41:1  error  This line has a length of 87. Maximum allowed is 80  max-len
  112:1  error  This line has a length of 86. Maximum allowed is 80  max-len
  117:1  error  This line has a length of 92. Maximum allowed is 80  max-len
  128:1  error  This line has a length of 86. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Button/stories/Fill.js
  10:1  error  This line has a length of 81. Maximum allowed is 80  max-len
  13:1  error  This line has a length of 81. Maximum allowed is 80  max-len
  16:1  error  This line has a length of 81. Maximum allowed is 80  max-len
  17:1  error  This line has a length of 87. Maximum allowed is 80  max-len
  19:1  error  This line has a length of 81. Maximum allowed is 80  max-len
  20:1  error  This line has a length of 83. Maximum allowed is 80  max-len
  25:1  error  This line has a length of 98. Maximum allowed is 80  max-len
  28:1  error  This line has a length of 85. Maximum allowed is 80  max-len
  29:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Calendar/Calendar.js
   44:1  error  This line has a length of 83. Maximum allowed is 80  max-len
   45:1  error  This line has a length of 85. Maximum allowed is 80  max-len
   49:1  error  This line has a length of 92. Maximum allowed is 80  max-len
  143:1  error  This line has a length of 81. Maximum allowed is 80  max-len
  415:1  error  This line has a length of 85. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Calendar/StyledCalendar.js
  101:1  error  This line has a length of 97. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Calendar/doc.js
  65:1  error  This line has a length of 105. Maximum allowed is 80  max-len
  66:1  error  This line has a length of 128. Maximum allowed is 80  max-len
  74:1  error  This line has a length of 82. Maximum allowed is 80   max-len

/Users/shimi/github/release/src/js/components/Calendar/stories/SundayFirstDay.js
  7:1  error  This line has a length of 145. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Calendar/utils.js
  12:1  error  This line has a length of 121. Maximum allowed is 80  max-len
  13:1  error  This line has a length of 99. Maximum allowed is 80   max-len

/Users/shimi/github/release/src/js/components/Carousel/Carousel.js
  217:1  error  This line has a length of 85. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Carousel/doc.js
  59:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/CheckBox/CheckBox.js
   26:1  error  This line has a length of 110. Maximum allowed is 80  max-len
  193:1  error  This line has a length of 85. Maximum allowed is 80   max-len

/Users/shimi/github/release/src/js/components/CheckBox/doc.js
  32:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/CheckBox/stories/CustomToggle.js
  48:1  error  This line has a length of 89. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Clock/Analog.js
  33:1  error  This line has a length of 92. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Clock/Clock.js
  7:1  error  This line has a length of 103. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Collapsible/Collapsible.js
   86:1  error  This line has a length of 88. Maximum allowed is 80  max-len
  136:1  error  This line has a length of 91. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/DataTable/Body.js
  80:1  error  This line has a length of 83. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/DataTable/DataTable.js
  175:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/DataTable/buildState.js
  54:1  error  This line has a length of 93. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/DataTable/doc.js
  78:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Diagram/Diagram.js
  241:1  error  This line has a length of 83. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Diagram/stories/Animated.js
  13:1  error  This line has a length of 155. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Distribution/Distribution.js
   56:1  error  This line has a length of 85. Maximum allowed is 80  max-len
  121:1  error  This line has a length of 93. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Distribution/doc.js
  25:1  error  This line has a length of 90. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Drop/DropContainer.js
  162:1  error  This line has a length of 103. Maximum allowed is 80  max-len
  163:1  error  This line has a length of 101. Maximum allowed is 80  max-len
  164:1  error  This line has a length of 109. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Drop/doc.js
  33:1  error  This line has a length of 81. Maximum allowed is 80  max-len
  45:1  error  This line has a length of 91. Maximum allowed is 80  max-len
  64:1  error  This line has a length of 84. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/DropButton/DropButton.js
  120:1  error  This line has a length of 89. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/DropButton/doc.js
  11:1  error  This line has a length of 94. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Form/__tests__/Form-test.js
  147:1  error  This line has a length of 89. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/FormField/FormField.js
    1:1  error  This line has a length of 95. Maximum allowed is 80  max-len
  180:1  error  This line has a length of 90. Maximum allowed is 80  max-len
  257:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/FormField/doc.js
  24:1  error  This line has a length of 387. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Grid/StyledGrid.js
  77:1  error  This line has a length of 83. Maximum allowed is 80  max-len
  78:1  error  This line has a length of 92. Maximum allowed is 80  max-len
  83:1  error  This line has a length of 83. Maximum allowed is 80  max-len
  88:1  error  This line has a length of 92. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Grid/stories/Responsive.js
  128:1  error  This line has a length of 84. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Grommet/Grommet.js
  112:1  error  This line has a length of 83. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Grommet/__tests__/Grommet-test.js
  94:1  error  This line has a length of 151. Maximum allowed is 80  max-len
  95:1  error  This line has a length of 248. Maximum allowed is 80  max-len
  96:1  error  This line has a length of 112. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Grommet/doc.js
  21:1  error  This line has a length of 96. Maximum allowed is 80  max-len
  31:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Heading/Heading.js
  30:1  error  This line has a length of 83. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Heading/doc.js
   75:1  error  This line has a length of 100. Maximum allowed is 80  max-len
  105:1  error  This line has a length of 124. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Image/__tests__/Image-test.js
  10:1  error  This line has a length of 143. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Image/doc.js
  21:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/InfiniteScroll/InfiniteScroll.js
    1:1  error  This line has a length of 86. Maximum allowed is 80  max-len
  268:1  error  This line has a length of 97. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Keyboard/Keyboard.js
  62:1  error  This line has a length of 85. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Layer/LayerContainer.js
  96:1  error  This line has a length of 84. Maximum allowed is 80  max-len
  98:1  error  This line has a length of 83. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Layer/doc.js
   42:1  error  This line has a length of 81. Maximum allowed is 80   max-len
   81:1  error  This line has a length of 90. Maximum allowed is 80   max-len
   85:1  error  This line has a length of 94. Maximum allowed is 80   max-len
   88:1  error  This line has a length of 92. Maximum allowed is 80   max-len
  147:1  error  This line has a length of 104. Maximum allowed is 80  max-len
  157:1  error  This line has a length of 97. Maximum allowed is 80   max-len

/Users/shimi/github/release/src/js/components/Markdown/Markdown.js
  54:1  error  This line has a length of 99. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/MaskedInput/MaskedInput.js
  207:1  error  This line has a length of 83. Maximum allowed is 80  max-len
  393:1  error  This line has a length of 91. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/MaskedInput/stories/Date.js
  45:1  error  This line has a length of 96. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/MaskedInput/stories/IPv4Address.js
  6:1  error  This line has a length of 88. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Menu/doc.js
  37:1  error  This line has a length of 86. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Meter/Circle.js
  112:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Meter/doc.js
  71:1  error  This line has a length of 132. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Paragraph/Paragraph.js
  11:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Paragraph/doc.js
  47:1  error  This line has a length of 109. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/RadioButton/RadioButton.js
   51:1  error  This line has a length of 118. Maximum allowed is 80  max-len
  110:1  error  This line has a length of 91. Maximum allowed is 80   max-len

/Users/shimi/github/release/src/js/components/RadioButton/doc.js
  32:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/RadioButtonGroup/RadioButtonGroup.js
  134:1  error  This line has a length of 101. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/RadioButtonGroup/doc.js
  17:1  error  This line has a length of 82. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/RangeInput/RangeInput.js
  16:1  error  This line has a length of 89. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/RangeInput/StyledRangeInput.js
  76:1  error  This line has a length of 145. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/RangeSelector/RangeSelector.js
  170:1  error  This line has a length of 81. Maximum allowed is 80  max-len
  208:1  error  This line has a length of 81. Maximum allowed is 80  max-len
  237:1  error  This line has a length of 81. Maximum allowed is 80  max-len
  255:1  error  This line has a length of 95. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/RoutedAnchor/RoutedAnchor.js
  19:1  error  This line has a length of 155. Maximum allowed is 80  max-len
  52:1  error  This line has a length of 93. Maximum allowed is 80   max-len

/Users/shimi/github/release/src/js/components/RoutedAnchor/doc.js
  10:1  error  This line has a length of 96. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/RoutedButton/RoutedButton.js
  39:1  error  This line has a length of 155. Maximum allowed is 80  max-len
  55:1  error  This line has a length of 93. Maximum allowed is 80   max-len

/Users/shimi/github/release/src/js/components/Select/Select.js
  152:1  error  This line has a length of 94. Maximum allowed is 80  max-len
  239:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Select/SelectContainer.js
   91:1  error  This line has a length of 89. Maximum allowed is 80  max-len
  132:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Select/__tests__/Select-test.js
  481:1  error  This line has a length of 86. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Select/doc.js
   86:1  error  This line has a length of 108. Maximum allowed is 80  max-len
  154:1  error  This line has a length of 82. Maximum allowed is 80   max-len
  238:1  error  This line has a length of 81. Maximum allowed is 80   max-len

/Users/shimi/github/release/src/js/components/SkipLinks/SkipLinks.js
  72:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/SkipLinks/doc.js
  19:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Table/doc.js
  11:1  error  This line has a length of 86. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/TableBody/TableBody.js
  16:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/TableCell/TableCell.js
  72:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/TableFooter/TableFooter.js
  14:1  error  This line has a length of 91. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/TableHeader/TableHeader.js
  14:1  error  This line has a length of 91. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/TableRow/TableRow.js
  9:1  error  This line has a length of 85. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Text/doc.js
  37:1  error  This line has a length of 90. Maximum allowed is 80  max-len
  89:1  error  This line has a length of 93. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Text/text.stories.js
  42:1  error  This line has a length of 95. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/TextArea/TextArea.js
  29:1  error  This line has a length of 85. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/TextInput/TextInput.js
  412:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/TextInput/doc.js
   50:1  error  This line has a length of 83. Maximum allowed is 80  max-len
  136:1  error  This line has a length of 93. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/Video/Video.js
  478:1  error  This line has a length of 85. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/WorldMap/WorldMap.js
  680:1  error  This line has a length of 85. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/components/WorldMap/doc.js
  14:1  error  This line has a length of 98. Maximum allowed is 80   max-len
  20:1  error  This line has a length of 88. Maximum allowed is 80   max-len
  31:1  error  This line has a length of 94. Maximum allowed is 80   max-len
  37:1  error  This line has a length of 109. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/contexts/AnnounceContext/announce-context.stories.js
  48:1  error  This line has a length of 102. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/contexts/AnnounceContext/doc.js
  10:1  error  This line has a length of 99. Maximum allowed is 80  max-len
  19:1  error  This line has a length of 97. Maximum allowed is 80  max-len
  20:1  error  This line has a length of 99. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/contexts/ResponsiveContext/doc.js
  13:1  error  This line has a length of 105. Maximum allowed is 80  max-len
  19:1  error  This line has a length of 128. Maximum allowed is 80  max-len
  30:1  error  This line has a length of 99. Maximum allowed is 80   max-len

/Users/shimi/github/release/src/js/contexts/ThemeContext/doc.js
  10:1  error  This line has a length of 87. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/themes/base.js
  184:1  error  This line has a length of 92. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/themes/grommet.js
  12:1  error  This line has a length of 215. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/utils/mixins.js
  49:1  error  This line has a length of 108. Maximum allowed is 80  max-len
  51:1  error  This line has a length of 83. Maximum allowed is 80   max-len
  55:1  error  This line has a length of 142. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/utils/router.js
  9:1  error  This line has a length of 81. Maximum allowed is 80  max-len

/Users/shimi/github/release/src/js/utils/themeDocUtils.js
  2:1  error  This line has a length of 98. Maximum allowed is 80  max-len

✖ 179 problems (179 errors, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  release git:(master) ✗

**Comment by ShimiSun** [comment]
I'm inclining to use a warning instead of an error. thoughts?

**Comment by ericsoderberghp** [comment]
For changes like this, I've found it can be easier to manage by changing the code itself in smaller batches and then updating the eslint config at the end.
