### ISSUE TITLE
Edge RangeSelector issue

### ISSUE THREAD

**Issue by DaksGreen** [grommet/grommet#3295]
Smth wrong with positioning in Edge

![msedge-rangeselector-bug](https://user-images.githubusercontent.com/25715095/63585218-4b986680-c5a7-11e9-8a50-f92fea76f171.gif)

**Comment by ShimiSun** [comment]
I've opened the same [story](https://storybook.grommet.io/?path=/story/rangeselector--thin) on my MacOs and tested on both Chrome and Firefox browsers, and it is working fine for me. @oorestisime, @britt6612 or @taysea, can you see what is the behavior on your end? 

Side note, in case we do see an issue on grommet side, it might be worth taking a look at this commit https://github.com/grommet/grommet/commit/3788b4cfb72e0255db319eebbeec05db3b642392

**Comment by oorestisime** [comment]
Working good for me but i don't have Edge to test this out :/

**Comment by ignatvilesov** [comment]
@ShimiSun @oorestisime This issue is reproducible in Microsoft Edge only

**Comment by ShimiSun** [comment]
Thanks for reporting buddy, the fix will be available on our next release!

**Comment by ignatvilesov** [comment]
Thank you for the fix @ShimiSun Much appreciated

**Comment by ignatvilesov** [comment]
@ShimiSun Is there any ETA when this fix is going to be released?
That's just for our reference to revisit our bug and update Grommet in our app as well.
