### ISSUE TITLE
RadioButtonGroup: missing property in docs

### ISSUE THREAD

**Issue by juanlanus** [grommet/grommet#3306]
A needed property is not listed in the control docs

Go https://v2.grommet.io/radiobuttongroup#options
The object example is: 
```
  {
    "disabled": false,
    "id": "ONE",
    "name": "one",
    "value": "1"
  }
```
This renders the buttons without name.  
It should have `"label": "one"` too. 
Or maybe the `name` property could be used as a default for `label`. 

Running this code in the docs page demonstrate the issue: 
```
function Example() {
  const [value, setValue] = React.useState('1');
  return (
    <Box direction = "row">
      <RadioButtonGroup
        name="doc"
        options = {[
          { id: "existing", name: "existing", value: "1" },
          { id: "new", name: "new", value: "0" }
        ]}
        value={ value }
        onChange={(event) => {
          setValue( event.target.value );
          console.log( 'value: ' + event.target.value )
        }}
      />
    </Box>
  );
}
```

### URL, screen shot, or Codepen exhibiting the issue

- Grommet version: + grommet@2.7.6
- Browser Name and version: Chrome newwest
- Operating System and version (desktop or mobile): Ubuntu 19

**Comment by oorestisime** [comment]
I think this was closed by mistake?

**Comment by oorestisime** [comment]
oh lol sorry. pr merged
