### ISSUE TITLE
[Task] Fix warnings that appear while running tests.

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#3312]

**Comment by oorestisime** [comment]
Most of the warnings that appear are legit (i think). we are testing that we do console.warn for some deprecation warning we issue.

**Comment by ShimiSun** [comment]
@oorestisime actually, in the last few days we started seeing really bad warning on the tests. Not just console warnings, red messages. 
I need to check if Eric's recent PR is fixing it.

**Comment by ShimiSun** [comment]
This beauty is fixing the warning https://github.com/grommet/grommet/pull/3311, I'm reviewing it now

**Comment by iMerica** [comment]
👍
