### ISSUE TITLE
TypeScript: DropButton component's dropProps property required a target

### ISSUE THREAD

**Issue by Chinow** [grommet/grommet#3315]
The `DropButton` component exposes the `dropProps` property to allow users to set the properties of the `Drop` the components uses.
However the typscript definition of this `dropProps` property reuses the `DropProps` type making `target` a mandatory value.

Setting that value overrides the `DropButton` target and breaks the component.

### Actual Behavior

The `dropProps` is raising an error when not setting a `target` :
```
<DropButton
  disabled={isDisabled}
  label={"Menu"}
  open={menuOpen}
  onClick={toggleMenuOpen}

  dropProps={{
    onClickOutside: toggleMenuOpen,
    overflow: 'visible',
   }}
/>
```
 Is getting this error:
`Error:(115, 15) TS2741: Property 'target' is missing in type '{ onClickOutside: () => void; overflow: string; }' but required in type 'DropProps'.`

### Expected Behavior

The target shouldn't be required by the `dropProps` property of the `DropButton`

### Your Environment

    Grommet version: 2.6.6
    TypeScript version: 3.5.2
    React version: 16.9.0
    @types/react version: 16.9.2

**Comment by britt6612** [comment]
@Chinow Thank you for reporting this issue I will take a look! 👍

**Comment by Chinow** [comment]
It seems that I failed at researching for fixed issues on that one.
It has been fixed a few month ago, we just need to update grommet on our side:
https://github.com/grommet/grommet/commit/5950ebb0d990b0b5d97001e8021fdbd0689c9c95

Sorry for that.
