### ISSUE TITLE
Cannot read property 'style' of null on Layer

### ISSUE THREAD

**Issue by faizrktm** [grommet/grommet#3318]
error happen when closing Layer, and i assumedly caused by usage Layer with styled-components this way:
`const StyledLayer = styled(Layer)`

### Expected Behavior
Layer closed successfully with animation.
### Actual Behavior
Layer not closed with animation, instead show this error
```
Layer.componentWillUnmount
node_modules/grommet/es6/components/Layer/Layer.js:97
   94 | layerClone.id = 'layerClone';
   95 | document.body.appendChild(layerClone);
   96 | var clonedContainer = layerClone.querySelector('[class^="StyledLayer__StyledContainer"]');
>  97 | clonedContainer.style.animationDirection = 'reverse';
      | ^   98 | setTimeout(function () {
   99 |   // we add the id and query here so the unit tests work
  100 |   var clone = document.getElementById('layerClone');
```

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/eloquent-mcnulty-8cd76

<img width="1440" alt="Screen Shot 2019-09-02 at 14 54 34" src="https://user-images.githubusercontent.com/46273747/64098662-a5601400-cd91-11e9-9c4a-3c2b50cd054c.png">

### Steps to Reproduce

1. Click to open the modal
2. close the modal
3. error occured

### Your Environment

- Grommet version: 2.7.7
- Browser Name and version: Chrome v76.0.3809.132
- Operating System and version (desktop or mobile): MacOS mojave desktop

**Comment by faizrktm** [comment]
if i disable the animation `animate={false}`, error not occured..

**Comment by ShimiSun** [comment]
Thank you for reporting buddy!
