### ISSUE TITLE
Table caption always hidden?

### ISSUE THREAD

**Issue by robinandeer** [grommet/grommet#3326]
### Expected Behavior

When I provide a caption to the `Table` component, it shows up in the DOM.

### Actual Behavior

The Table caption is always hidden.
See here: https://github.com/grommet/grommet/blob/master/src/js/components/Table/StyledTable.js#L57

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-kw9xt?fontsize=14

### Steps to Reproduce

Import `Table` and supply the "caption" property.

### Your Environment

- Grommet version: 2.7.7 (or current master)
- Browser Name and version: Chrome 77
- Operating System and version (desktop or mobile): Mac desktop macOS 10.14.6

**Comment by ShimiSun** [comment]
YEa, I agree it doesn't look right. looks like you already found the root cause of a problem, feel like contributing a PR?

**Comment by robinandeer** [comment]
Sure I can try to do that 🙂

**Comment by ShimiSun** [comment]
Hi buddy, @robinandeer let us know how it goes and if you need any help!

**Comment by robinandeer** [comment]
Yeah thanks, didn't have to get to it until now but I've just opened a new PR :-)
