### ISSUE TITLE
v2 Improve Button docs for hoverIndicator 

### ISSUE THREAD

**Issue by juanlanus** [grommet/grommet#3330]
The `Button`'s `hoverIndicator` prop does not work as the docs say. 

### Expected Behavior
Something like:
`{
  dark: {
    color: 'dark-2',
    opacity: '1',
  },
  light: {
    color: 'light-2',
    opacity: '1',
  },
`

### Actual Behavior

`true
false
"string"
"background"
{
background:
"boolean"
"string"
}`
### URL, screen shot, or Codepen exhibiting the issue

No need, specifying `hoverindicator` as in the docs does nothing. 

### Steps to Reproduce

See https://v2.grommet.io/button#hoverIndicator 
and also #3287

### Your Environment
Linux, chrome, whatever :-)

- Grommet version: 2.7.8
- Browser Name and version: Chrome latest
- Operating System and version (desktop or mobile): Ubuntu 19.4

**Comment by juanlanus** [comment]
Additionally, in https://raw.githubusercontent.com/grommet/grommet/master/src/js/themes/base.js 
global.hover says:
`      hover: {
        background: {
          color: 'active',
          opacity: 'medium',
        },
        color: {
          dark: 'white',
          light: 'black',
        },
      },`
Where the background is called background and color is for the strokes as it should.  
IMO using `color` instead of `background` for the hover background is misleading. 

Anyway, I failed miserably trying to specify hover behavior in my theme:  
`global: {
    hover: {
      background: {
        color: '#555555',
        opacity: 'medium',
      },
      color: {
        dark: 'white',
        light: 'black',
      },
    },
}`  
I also tried:  
`  button: {
    hoverIndicator: {
      dark: { color: 'dark-3' },
      light: { color: 'light-3' },
    },`  
in the theme, nothing happened.

**Comment by juanlanus** [comment]
Hi @britt6612 thanks for calling. 
My issue (it was not clear enough in my original post) is that following the docs as of that time I was unable to activate the hoverIndicator for any button. 
The docs said that the options for the prop were: 
`true false "string" "background" { background: "boolean" "string" }`
stacked vertically, not in a single row. 
Of course, initially I thought that I was doing something wrong, so I spent a lot of time trying combinations of the values above   >:(
After a gazillion failures I searched Slack and found an example by Shimi that did work (the syntax was completely different to that in the docs). 
That solved _my_ issue, then I filed the issue so that nobody else will have this same problem any more. 
That's it. Simple.

**Comment by juanlanus** [comment]
Now I read the docs again. They have changed but there are still issues.  
1- "This prop is meant to be used only with plain Buttons." raises a question: non-plain buttons lack the ability to react to hover? 
2- The possible values in unclear. What is "string"? "The rain in Spain" is a string, it should work... 
3- Similarly, the 4th. option "background" is not explained. 
  
One who is not an insider, and is trying to evaluate Grommet, might recommend not to adopt it. Docs must explain all in detail, or at least provide complete examples (those on the storybook are somehow skinny). 
![Screenshot from 2019-09-13 20-29-08](https://user-images.githubusercontent.com/950497/64901560-3035ee00-d671-11e9-988c-9ba38dd08366.png)

**Comment by juanlanus** [comment]
Another thing that is not explained is what is the purpose of "dark" and "light".  
And why "dark" has "boolean" (meaning what?) and "light" does not; why the difference?

**Comment by oorestisime** [comment]
> Now I read the docs again. They have changed but there are still issues.
> 1- "This prop is meant to be used only with plain Buttons." raises a question: non-plain buttons lack the ability to react to hover?

Non plain buttons have the hover effects baked in. Think of hoverIndicator as a utility.

> 2- The possible values in unclear. What is "string"? "The rain in Spain" is a string, it should work...

It means you can add whatever color you want not in the theme file like black. this is the same with every color prop.

> 3- Similarly, the 4th. option "background" is not explained.
> 

Agreed! It means it will take the background prop of the theme. Care for a small PR to change the wording here?

**Comment by oorestisime** [comment]
> Another thing that is not explained is what is the purpose of "dark" and "light".
> And why "dark" has "boolean" (meaning what?) and "light" does not; why the difference?
that's another good suggestions. @britt6612 since you owned these changes you might want to think on how to explain these a bit more ?

**Comment by oorestisime** [comment]
> Another thing that is not explained is what is the purpose of "dark" and "light".
> And why "dark" has "boolean" (meaning what?) and "light" does not; why the difference?
that's another good suggestions. @britt6612 since you owned these changes you might want to think on how to explain these a bit more ?

**Comment by juanlanus** [comment]
@oorestime @britt6612 Tahnks for answering _me_, but keep in mine that my comments on the docs tend to point parts of the text that are not clear for normal users (I mean those who are not immersed in the Grommet culture). 
There are things that for insiders are crystal clear but muddy for the rest of the world population. 
Like ne myself. I've spent  **_hours_**  trying to style controls. 
As the usability guy I am, I try to contribute by pointing at such cases.  
As of sprouting a PR, I don't feel I'm solid enough, as much as I would like to. Perhaps the moment I become an expert I will stop noticing the insider/outsider glitches  :')

**Comment by britt6612** [comment]
> > Another thing that is not explained is what is the purpose of "dark" and "light".
> > And why "dark" has "boolean" (meaning what?) and "light" does not; why the difference?
> 
> that's another good suggestion. @britt6612 since you owned these changes you might want to think on how to explain these a bit more ?
 @oorestisime I can do a PR which better explains this. 

@juanlanus thank you for your feedback I will share your feedback with the team and see how we can leverage your suggestions to help improve our docs!

**Comment by juanlanus** [comment]
@britt6612 ... and then contact me again so I can participate more. 
I'm thinking of the advantage of defining a set of "common props" (similar to [CSS commom attributes](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Properties_Reference)) to be (better) defined in a doc by itself to be referenced in the individual controls.  
This would render a two-fold advantage: allowing to focus more effort in defining each while shortening the controls' own docs. Additionally it might add coherence (like in "fill" vs "full").

**Comment by ShimiSun** [comment]
@juanlanus sounds like you already have a good idea of how to articulate the docs unclear area. 
and if you don't feel comfortable making a code contribution, could you start with a WIKI page that articulates the gaps of understanding, and we can start/grow from there?

**Comment by juanlanus** [comment]
@ShimiSun would like so much to do so, only it will be a huge distraction from my work. 
I tend to be passionate for these issues (usability, user onboarding, reducing support questions). 
But I have to complete the development of my web site before I die (it's taking so much time!)  :-) 
Additionally, I loathe markdown so a wiki would be an additional pain point. 
I also looked at the Grommet docs sources and they are horrible. Such tech-oriented formats distract the writer from the main track. I saw in the road map that switching is proposed, but that will not necessarily mean better docs (albeit there is a promise for better integration). 

I'll have to think about assuming such a responsibility. 
Actually, I don't have yet a clear generalized idea about the docs shape, for now I was only sending feedback about the issues I find, because I can still look at Grommet as a newbie partly because I am a newbie but mostly because of my usability training. 

For now this is something I wrote yesterday for myself (struggling with the bitbucket wiki):

### The Grommet "Select" component ###

There is a working example in https://codesandbox.io/s/selectsearch-mxvll   


```
#!javascript

import React, { Component } from "react";
import ReactDOM from "react-dom";
import { Box, Grommet, Heading, TextInput } from "grommet";
import myTheme from './myTheme';
import SelectSearch  from './SelectSearch';
import MyStyledSelect from './MyStyledSelect';
import countryData from './countryData';

import "./styles.css";

class App extends Component {
  state = {
    countrySelected: { code: '', name: '' }, // { code: 'ar', name: 'Argentina' },
    countryOptions: countryData
  };

  render(){
    const countryOptions = this.state.countryOptions;
    const countrySelected = this.state.countrySelected;
    return (
      <div className="App">
        <Grommet full theme={ myTheme } >
          <Box direction = 'column' width='15em' pad='2px'>
            <Heading level = "3">Hello Select test!</Heading>
            {/* <SelectSearch /> */}
            <MyStyledSelect 
              options = { countryOptions }
              value = { countrySelected }
              placeholder = 'Choose a country'
              labelKey = 'name'
              valueKey = 'code'
              onSearch = { text => {
                const exp = new RegExp( text, 'i' );
                this.setState({
                  countryOptions: countryData.filter(
                    option => exp.test( option.name + '  ' + option.code + ' ' )
                  )
                });
              }}
              onChange={({ option }) => {
                if( option ){
                  this.setState({ countrySelected: option });
                  console.log( 'changed: ', option.code + ' ' + option.name );
                } else {
                  console.log( 'changed: no option' );
                };
              }}
              onClose = {
                () => this.setState({ countryOptions: countryData })
              }
            />
            <TextInput />
          </Box>
        </Grommet>
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```
It works with two data items: the `options` and the `value` props.  
In this case, set for search, `options` is an array of objects (instead of the more simple array of strings), like so: 

`[  `  
`  {code: "AC", name: "Ascension Island"},  `  
`  {code: "AD", name: "Andorra"},  `  
`  {code: "AE", name: "United Arab Emirates"},  `  
`  {code: "AF", name: "Afghanistan"},  `  
`  {code: "AG", name: "Antigua & Barbuda"},  `  
`  {code: "AI", name: "Anguilla"},  `  
`  {code: "AL", name: "Albania"},  `  
`  {code: "AM", name: "Armenia"},  `  
`...  `  
`]`  
Both `options` and `value` must be members of the control's `state`.

The props: `labelKey = 'name'` and `valueKey = 'code'` tell the control what to display and what to return.  
The control will display the strings of the `name` property and, upon selection, will return the content of the associated `code` property.  
Clicking the control, or tabbing into it and keying down-arrow, opens the list and focus in a text input for the search text.  
Each time the search text changes the control calls `onSearch( text )`:
```
              onSearch = { text => {
                const exp = new RegExp( text, 'i' );
                this.setState({
                  countryOptions: countryData.filter(
                    option => exp.test( option.name + '  ' + option.code + ' ' )
                  )
                });
              }}
```
This builds a regex to search for the typed text ignoring case that one can implement at will.  
The function must return a new array containing only the items selected.  
In this case the search text is tested against the names and the codes (surrounded by spaces).  
The `onSearch()` function is called when the user stops typing for a time longer than a debounce threshold set in the theme.  
Then a new list if built and displayed. At any moment the user can click one of the options, or hit enter to select the first one displayed.  
During this operation the options list in local `state` is used to persist the shortened versions, so the original list is restored 'onClose()'.  
The function `onChange()` is called whenever an option gets selected.  
It passes the selected option as its argument, and there you have the opportunity to grab it, for example storing it in local `state`.  
If you hit enter after having typed a gibberish search string that doesn't match any item, the function is called anyway only the argument is undefined.  
  
It interesting to note that you are not constrained to the two fields shown in this example for search.   
If there is more data it is presented by `onSearch()` and can be checked. For example a property containing the names without accents would be useful.

**Comment by britt6612** [comment]
@juanlanus I just got done with a wiki page that explains the color properties as well as some of the themes that include colors. I would really appreciate your feedback on this. 
https://github.com/grommet/grommet/wiki/Color-Properties

**Comment by juanlanus** [comment]
@britt6612 Good! I like your copy.  
I've read it quickly and it's really good.  
I'd like to review it in detail and suggest enhancements, details, that I'll need to check with Those Who Know. 
As quick examples (that I remember now) it starts saying that the theme is a choice of colors, I'd say colors, measures, ... (things like the debounce timeout and the like). 
I can read it wearing the hat of a complete newbie and identify things that are mentioned but not yet defined, the usual issue when the docs are written by people deeply immersed in the subject. 
  
Also, I'd like to make two docs out of your one. The first to "Improve Button docs", this issue's name. The other to introduce the _theme_ in general.

**Comment by britt6612** [comment]
@juanlanus Thank you feel free to reach out once you have read it in more detail for the feedback. I like the adding measures and other things so new users do not think theme is just all about colors. 

Im not sure if you are able to see the page source I can check with @ShimiSun and get back to you!

**Comment by ShimiSun** [comment]
Not sure everyone has permissions to get to the source file, do you see an edit button? you can drop your comments here if it doesn't let you edit the page.

**Comment by juanlanus** [comment]
No "edit" button, which is consistent with the fat that I'm not a committer or anything.  
What I'd like is to clone the wiki in my PC, edit here in Buenos Aires, and and send sort of PR's.

**Comment by IanKBovard** [comment]
@juanlanus Anything else you want to add before we close this issue?

**Comment by juanlanus** [comment]
It's OK  :-)

**Comment by jaynammodi** [comment]
> @juanlanus I created 2 code sandboxes for you to take a quick look at. I want to understand the problem you had when trying to pass in the object color to the hoverIndicator prop. Also with the theme I did make another code sandbox that uses a custom theme which was very similar to your example you gave.
> https://codesandbox.io/s/buttonhovertheme-02teb
> 
> https://codesandbox.io/s/buttonhoverindicatorprop-l8zvk
> 
> Please feel free to let me know what was still not clear in the documentation 👍

how do i animate the background image's position using the hoverIndicator prop? it should be possible but isnt clear enough in the docs
