### ISSUE TITLE
Cannot change selected option background color from Select component

### ISSUE THREAD

**Issue by andresromerodev** [grommet/grommet#3341]
Hello, I am trying to change the background color of the selected option for my Grommet Select components, after trying several things modifying the global theme, a the select component properties: select.option.background I haven't been able to get it done and could not find any documentation on Grommet's site. Could someone tell me if this currently possible? I also tried to modify the generated CSS class for the selected option with no luck.

### Expected Behavior
Background should change to Teal color:

![image](https://user-images.githubusercontent.com/22283177/64809127-d8569480-d555-11e9-8b17-885d4932c838.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/22283177/64808903-60886a00-d555-11e9-8100-dfe819dbf8cf.png)

- Grommet version: 2.7.8

**Comment by faizrktm** [comment]
Hi @britt6612, can you update the sandbox? seems like the codes is missing :(

**Comment by britt6612** [comment]
@faizrktm sorry about that the code sandbox should be updated again. So whats happening is Grommet has a section in their base theme in which they define selected to be the brand color which is that purple so you would just need to override that color.

```
const colors = {
  selected: "#008080"
};

const customTheme = deepMerge(grommet, {
  global: {
    colors
  }
});

```

Once you have that defined in your colors you can then pass your custom theme and that will change the color. check the link again should be working! Let me know if you need anything else!

**Comment by ShimiSun** [comment]
@britt6612 can you please file PR to enhance the custom theme example with the mark-up you just shared? It will help the community get what they need while browsing the storybook examples.
