### ISSUE TITLE
Expected components from Grommet.

### ISSUE THREAD

**Issue by kkgowtamasa** [grommet/grommet#3354]
**- Layout Management:** We would like to see more hybrid methods in layout management. It helps most of the enterprise applications to build in an organized way. (e.g. Divide the page into two segments - LHS: List all the resources using data table/grid system with pagination and upon selecting a particular resource paint the details view)

**- Grommet-native -** to build mobile applications. 

**- Build a component**/service which tracks all asynchronous operations performed in the application.

**Comment by ShimiSun** [comment]
linking to #3271

**Comment by brodybits** [comment]
For "Grommet-native" I already started this kind of work in DRAFT PR #3029. It should be theoretically straightforward to support some more basic components using react-primitives. It took me quite a while to make some workarounds needed for React Native.

**Comment by jcfilben** [comment]
I think the Page and PageContent components added in https://github.com/grommet/grommet/pull/5960 cover the layout management.

For Grommet-native we have decided not to go in this direction and instead aim to support mobile applications through the built in responsive nature of grommet.
