### ISSUE TITLE
Form onChange returns two objects instead of only value

### ISSUE THREAD

**Issue by cscognamiglio** [grommet/grommet#3356]
### Expected Behavior
```
<Form onSubmit={({value}) => this.save(value)}
            onChange={(value) => console.log(value)}
            value={value}
>
```

onChange should log the content of value, that is the changed form values object.

### Actual Behavior

onChange seems to be called twice, first time with an event object and second time with the actual value object.

### URL, screen shot, or Codepen exhibiting the issue
![Screenshot 2019-09-18 at 12 31 44](https://user-images.githubusercontent.com/11227537/65141289-9a071c80-da10-11e9-9ec1-e2c2d95421db.png)

Reproduced here:

https://codesandbox.io/s/grommet-v2-template-slom4

### Steps to Reproduce

1. Create a Form
2. Add an onChange prop
3. log value

### Your Environment

- Grommet version: 2.7.8
- Browser Name and version: Firefox Quantum 69
- Operating System and version (desktop or mobile): MacOS Mojave 10.14.6

**Comment by maslennikov** [comment]
I confirm with Chrome (ver 79 - latest for the time being) on Mac. Looks like some keypress event is leaking from TextInput (both as regular form field children, and nested deeper inside other form components (like search input inside a select).

For example, within a searchable select, normal click upon an option from the list will trigger only a valid Form.onChange event. But after any key press inside of the search field it will trigger two successive Form.onChange invocations (first - with a keypress event passed as a param, second - with a valid Form.onChange param).

Also, local onChange() callbacks passed to FormField components won't catch this buggy event, it happens only with Form.onChange.

**Comment by johnny1K** [comment]
Same issue which @maslennikov has with grommet ^2.7.11
With the latest grommet (2.11.1) as of now, the synthetic event is gone, but the form object arrives twice.

**Comment by ShimiSun** [comment]
Hi @maslennikov can you share a [codesandbox](https://codesandbox.io/s/m7mml8l0zj) that reproduces the problem? It will help us to quickly troubleshoot.

**Comment by britt6612** [comment]
There has been many changes to `form` in the past few months 

I created an updated codesandbox to show that onChange is now just called once. 

https://codesandbox.io/s/onchange-form-1efo4?file=/src/App.js

If there are no objections I believe this issue can be closed. The Grommet 2.11.0 release with the massive improvements to `form` and `formfield` this issue was no longer happening

**Comment by cscognamiglio** [comment]
Yes I can confirm that the problem is fixed, thanks! I will close the issue.

**Comment by ShimiSun** [comment]
@cscognamiglio thank you for the collaboration.
