### ISSUE TITLE
Bug in `step` parameter of <RangeSelector />

### ISSUE THREAD

**Issue by saidelmark** [grommet/grommet#3360]
### Expected Behavior
`<RangeSelector />` with a given `step` parameter should select only select `n`*`step` values

### Actual Behavior
If `step` equals `2`, then everything works as expected.
Otherwise I can select `5` when `step` is `3` and available range is `[0, 100]`. But if I change the selection using arrow keys, then every keystroke increases/decreases selected value by the exact value of `step`.

### URL, screen shot, or Codepen exhibiting the issue

I also created a codepen so you don't have to: https://codepen.io/saidelman/pen/ExYdwbM?editors=0010
It's based on [grommet's storybook](https://storybook.grommet.io/?path=/story/rangeselector--thin).

This is an example with `step` 3, while you can see that I can move the selector to values like 7 or 8:
![RangeSelector](https://user-images.githubusercontent.com/9284083/65163447-9e006200-da43-11e9-92b3-a44421aa0224.gif)

### Steps to Reproduce

1. Create a `<RangeSelector />`
1. Set `step` parameter to 2
1. Check that it works fine
1. Set `step` to a bigger value
1. Move the sliders with your mouse, the selected value will have incorrect values
1. Move the sliders using arrow keys to see that this time the difference in selected value changes by `step` each time.

I initially noticed the issue when I was working with huge numbers: I wanted to have `[0, 1e9]` range and `1e6` step. Expected to be able to select only values with 6 zeros ending. And then, when started to investigate the issue, found similar problems with `[0, 100]` range and `5` step.

The most interesting part is that there is no this bug in a similar `Grommet` component, `<RangeInput />` (I added this component to my codepen as well to illustrate that).

### Your Environment
- Grommet version: tested with `2.7.6` and `2.7.8`
- Browser Name and version: Google Chrome Version 77.0.3865.75 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Debian 10
- TypeScript version: 3.6.2
- React version: 16.9.0

**Comment by taysea** [comment]
Thanks for raising this issue @saidelmark! I submitted a PR for this. It looked like the calculation for the value of the range selector based on the mouse position wasn't working as expected.

**Comment by ShimiSun** [comment]
Thank you for reporting buddy!
