### ISSUE TITLE
Grommet 2.7.8 causes grommet-icons color to stop working

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#3365]
You can now only use base colors like "plain". Colors like "brand", "light-1" no longer work...
https://codesandbox.io/s/j8njp1lpv?fontsize=14

**Comment by oorestisime** [comment]
Your dependencies are all outdated. have a look here https://codesandbox.io/s/grommet-v2-template-cc9vp
v2 since a long time requires 4.x from grommet-icons. And you also need newer versions of react.

**Comment by RobertGary1** [comment]
That’s disappointing. I’m using the latest in my dev env and thought I’d reproduced it. I’ll go back and work on reproducing it again.

**Comment by oorestisime** [comment]
If you paste your package.json maybe i can look
