### ISSUE TITLE
Let the width of Select be content-based.

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet#3367]
### Expected Behavior
The width of Select control is too large when there are only 2 ~ 4 characters in it. And there are a lot space on the right side. Shall we make the width content-based, so that it would look compact?

### Actual Behavior
The width is too large, there is a lot of space in the right side.

### Steps to Reproduce

None.

### Your Environment
Win10, latest Chrome

- Grommet version: Latest
- Browser Name and version: all
- Operating System and version (desktop or mobile): all

**Comment by ivandevp** [comment]
May I help on this?

**Comment by mlshv** [comment]
Select uses HTML `<input>` element that has a `size` attribute with default value of 20. It is not possible (as I know) to set it's width by content without JS hacks. So I am afraid that it won't be implemented

**Comment by jim-king-2000** [comment]
Should it be <select> element?

**Comment by ShimiSun** [comment]
@IanKBovard could this be controlled with the recent fix of Drop to adjust width of target?

**Comment by IanKBovard** [comment]
This can be done with dropProps stretch.

https://codesandbox.io/s/pensive-sammet-fmc3z?file=/src/App.js

**Comment by jim-king-2000** [comment]
Open the link, I see the code below:

```jsx
import React, { useState } from "react";
import { Box, Grommet, Select, Text, grommet } from "grommet";

const App = ({ ...rest }) => {
  const options = ["one", "two"];
  const [value, setValue] = useState("");
  return (
    <Grommet full theme={grommet}>
      <Select
        id="select"
        name="select"
        placeholder="Select"
        value={value}
        options={options}
        onChange={({ option }) => setValue(option)}
        {...rest}
      />
    </Grommet>
  );
};

export default App;
```

Where is the dropProps stretch?

**Comment by IanKBovard** [comment]
Forgot to save, its up there now

**Comment by jim-king-2000** [comment]
What we expect is to shrink the whole `<Select />` control according to its content, not the drop down of the control.

**Comment by IanKBovard** [comment]
@jim-king-2000 do you want it to match the width of the drop or the label? Is there a specific use case for this. I would just wrap the select in a box and give it a width. Updated the codesandbox.

**Comment by jim-king-2000** [comment]
It is great! This is almost the requirement I propose except for the width being decided by the content (the max of the drop and the label) of the `<Select />` instead of a hard-coded one.

**Comment by jim-king-2000** [comment]
The use case of the requirement is for the mobile web. The default width is too large for a phone screen. However, your solution is viable and it can resolve more then 80% cases.

**Comment by IanKBovard** [comment]
I don't know if it's possible to match the select to the drop, since the drop is not rendered right away. Currently grommet matches the drop width with the select width(which makes more sense to me). For mobile development, i would use media queries, percentages, or both. That should handle all cases.

**Comment by jim-king-2000** [comment]
Sure. Close it.
