### ISSUE TITLE
Carousel control hiding doesn't work

### ISSUE THREAD

**Issue by fortydegrees** [grommet/grommet#3377]
Setting `<Carousel controls={false}>` doesn't hide the controls.

I'm using nextJS, not sure why it's happening.

This is my code:

```
<Carousel controls={false} play={4000}>
                        {Object.keys(props.game.questions).map((key, idx) => {
                          return (
                            <Box key={key} justify='around' fill='vertical'>
                              <Text textAlign='center' color='light-1'>
                                {props.game.questions[key].question}
                              </Text>
                              <Text
                                weight='bold'
                                color='light-1'
                                textAlign='center'
                              >
                                {props.prediction[key]}
                              </Text>
                            </Box>
                          )
                        })}
                      </Carousel>
```

controls={true} or {false} has no effect, the controls show. The 'play' prop responds though,

**Comment by ShimiSun** [comment]
Which version of Grommet are you using? And browser

**Comment by fortydegrees** [comment]
Sorry for the lack of useful info. I'm using 2.7.4 and Firefox 69.0.1. The issue also persists on Chrome.

For what it's worth, this codesandbox: https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=carousel&module=%2Fsrc%2FCarousel.js

behaves properly.

**Comment by ShimiSun** [comment]
The ability of hiding Carousel controls was introduced on Grommet 2.7.7, so one more reason for you to upgrade my friend ;) https://github.com/grommet/grommet/releases/tag/v2.7.7

I'll be closing this issue, feel free to reopen id needed.
