### ISSUE TITLE
Improve documentation of extend theme concept

### ISSUE THREAD

**Issue by brianbancroft** [grommet/grommet#3389]
The extend theme object is a useful way to add other non-common attributes to Grommet elements such as the RangeInput, but lack of applied examples in the documentation may preclude their adoption among other developers

### Expected Behavior

Somewhere in the documentation (or storybook), there should be a fleshed-out example of an extend theme object so that developers who code through example can use it with less friction. 

### Actual Behaviour

In documentation pages such as [that of the RangeInput](https://v2.grommet.io/rangeinput#theme), there are two examples which are not clear. 

![image](https://user-images.githubusercontent.com/6225122/65983990-9a051480-e433-11e9-9032-4590b5aab28f.png)

#### "Any CSS"
This doesn't tell me whether I should write the rules directly, or whether I should encase them within a class or similar. While Grommet does use styled-components, it doesn't address whether tools available to that library (such as the '&' operator) are available. 

#### "(props) => {}"
This does not show what could exist in the object, or where it could be applied. Or how to pull from the props as well. 

This is not to detract from the library itself. It is a lovely set of abstractions that I've come to enjoy the more I use them. Thank you for all of your hard work

**Comment by ShimiSun** [comment]
I think we can close this one now unless @brianbancroft thinks we can improve elsewhere.

**Comment by brianbancroft** [comment]
Concurred. Closing.

**Comment by rodmartinezmedina** [comment]
Hi, So where can i find more detailed explanation about the extend property to clarify? I've checked all the links in this and the other post and can't find it.
Thanks

**Comment by IanKBovard** [comment]
Here is an example of TextInput using extend
https://storybook.grommet.io/?path=/story/textinput--themed
and Heading using extend with dynamic variables
https://storybook.grommet.io/?path=/story/heading--extend
