### ISSUE TITLE
Menu items onClick handlers do not fire on Firefox as of v2.7.9

### ISSUE THREAD

**Issue by ryanjchr** [grommet/grommet#3408]
### Expected Behavior
Clicking on a `<Menu items={[{ onClick: ... }]}>` item should fire its `onClick` handler if provided on all browsers.

### Actual Behavior
The `onClick` handler does not fire on the latest version of Firefox, but does on Chrome.
Reverting to Grommet 2.7.8 fixes the issue.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v279-menu-items-broken-bhr5w

### Steps to Reproduce
1. Have a `<Menu items={[{ onClick: ... }]}>` component with an item containing an `onClick` property
2. Click the item with the `onClick` property
3. Note that the handler does not execute if using Firefox

### Your Environment
- Grommet version: 2.7.9
- Browser Name and version: Firefox 69.0.2, Chrome 77.0.3865.90
- Operating System and version (desktop or mobile): macOS 10.14.6

**Comment by taysea** [comment]
Thanks for raising this issue! It looks like potentially Firefox is having an issue with the nested onClick? https://stackoverflow.com/questions/24103072/reactjs-onclick-handler-not-firing-when-placed-on-a-child-component

I'm going to look more into this to understand why the recent changes to Menu are causing this to occur.

**Comment by ShimiSun** [comment]
linking #3334
