### ISSUE TITLE
Sparkline is very wide if x values are not consecutive integers

### ISSUE THREAD

**Issue by JeffAMcGee** [grommet/grommet#342]
The width of a sparkline is seven times the difference between the maximum x value and the minimum x value.  As an extreme example, this will create a 7000 pixel wide sparkline:

```
const trend = [[new Date(2015,11,16,0,0,0),1],[new Date(2015,11,16,0,0,1),2]]
const series = [{values: trend, colorIndex: "graph-1"}]
return (
  <Chart series={series} sparkline={true} />
)
```

The difference between the two times is one second, or 1000 miliseconds. `1000 * (SPARKLINE_STEP_WIDTH + SPARKLINE_BAR_PADDING)` gives you a 7000 pixel wide element. As best I can tell, there isn't a way to change the width of a sparkline except for doing the scaling yourself.

**Comment by tracybarmore** [comment]
Looking into issue.

**Comment by ericsoderberghp** [comment]
Looking into changing Chart sparkline size to honor width.
