### ISSUE TITLE
I need to customise the select component grommet.

### ISSUE THREAD

**Issue by karthickselvendran** [grommet/grommet#3432]
I need to customise the select component with the textInput component.  See the picture below to understande the question.  I need a nice look of the components.

![project](https://user-images.githubusercontent.com/52481101/66272887-9be43300-e88c-11e9-95c6-ef8c12309293.png)

**Comment by oorestisime** [comment]
Lets keep the discussion here

so you are actually not using the prop i mentioned. can you please try?

> > Please share a codesandbox with the behaviour. are you using the size prop both in select and textinput? its difficult to help without more information.
> 
> import React, { Component } from 'react';
> import { TextInput, Button, Box, RadioButtonGroup, Select, Clock } from 'grommet';
> import { Container, Row, Col } from 'react-bootstrap';
> import { Link } from 'react-router-dom';
> 
> class Bangalore extends Component {
> constructor(props) {
> super(props)
> this.state = {
> radio1: ''
> }
> }
> setValue(e) {
> this.setState({
> radio1: e
> })
> }
> render() {
> 
> ```
>     return (
>         <div>
>             <Box flex={false} tag="header" align="center" background="#0091ea" pad="small" >
>                 Student Registration Form
>       </Box>
>             <Container style={{ padding: "5%" }}>
> 
>                 <div className="form">
>                     <Row>
>                         <Col>
> 
>                             <Row>
>                                 <Col xs={6} sm={12}>
>                                     <TextInput
>                                         id="registernumber"
>                                         placeholder="University Register Number"
>                                     />
>                                 </Col>
>                             </Row>
>                             <br />
>                             <Row>
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="firstname"
>                                         placeholder="First Name"
>                                     /></Col>
>                                 <br />
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="lastname"
>                                         placeholder="Last Name"
>                                     />
>                                 </Col>
>                             </Row>
>                             <br />
>                             <Row>
>                                 <Col>
> 
>                                     <RadioButtonGroup
>                                         name="radio1"
>                                         id="radio1"
>                                         options={['Male', 'Female']}
>                                         value={this.state.radio1}
>                                         onChange={(event) => this.setValue(event.target.value)}
>                                     />
>                                 </Col>
>                             </Row>
>                             <br />
>                             <Row>
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="email"
>                                         placeholder="Email"
>                                     />
>                                 </Col>
> 
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="aemail"
>                                         placeholder="Alternate Email"
>                                     />
>                                 </Col>
>                             </Row>
>                             <br />
>                             <Row>
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="mobilenumber"
>                                         placeholder="Mobile Number"
>                                     />
>                                 </Col>
> 
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="amobilenumber"
>                                         placeholder="Alternate Mobile Number"
>                                     />
>                                 </Col>
>                             </Row>
> 
>                             <br />
>                             <Row>
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="nationality"
>                                         placeholder="Nationality"
>                                     />
>                                 </Col>
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="caste"
>                                         placeholder="Caste"
>                                     />
>                                 </Col>
>                             </Row>
>                             <br />
>                             <Row>
>                                 <Col xs={12} sm={12}>
>                                     <TextInput
>                                         id="college"
>                                         placeholder="College"
>                                     />
>                                 </Col>
>                             </Row>
>                             <br />
> 
>                             <Row>
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="university"
>                                         placeholder="University"
>                                     />
>                                 </Col>
> 
>                                 <Col xs={6} sm={6} style={{ width: '100%' }}>
> 
>                                     <Select
>                                         placeholder="University State"
>                                         options={["Tamil Nadu", "Bengaluru", "Kerala", "Maharastra"]}
> 
> 
>                                     />
>                                 </Col>
>                             </Row>
>                             <br />
>                             <Row>
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="tenthpercentage"
>                                         placeholder="Tenth Percentage"
>                                     />
>                                 </Col>
> 
>                                 <Col xs={6} sm={6}>
>                                     <Select
>                                         placeholder="Tenth Passing Year"
>                                         options={["2012", "2013", "2014", "2015", "2016"]}
>                                     // style={{ width: '1225px' }}
>                                     />
>                                 </Col>
>                             </Row>
>                             <br />
>                             <Row>
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="twelfthpercentage"
>                                         placeholder="Twelfth Percentage"
>                                     />
>                                 </Col>
> 
>                                 <Col xs={6} sm={6}>
>                                     <Select
>                                         placeholder="Twelfth Passing Year"
>                                         options={["2014", "2015", "2016", "2017", "2018"]}
>                                     // style={{ width: '1225px' }}
>                                     />
>                                 </Col>
>                             </Row>
>                             <br />
>                             <Row>
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="gcollege"
>                                         placeholder="Graduation College"
>                                     />
>                                 </Col>
> 
>                                 <Col xs={6} sm={6}>
> 
>                                     <Select
>                                         id="gspecialization"
> 
>                                         placeholder="Graduation Specialization"
>                                         options={["CSE", "ECE", "EEE", "MECH", "CIVIL"]}
>                                         style={{ alignSelf: 'stretch',size:'large' }}
>                                     />
>                                 </Col>
>                             </Row>
>                             <br />
>                             <Row>
>                                 <Col xs={6} sm={6}>
>                                     <TextInput
>                                         id="percentage"
>                                         placeholder="Aggregate Percentage in Graduation Degree"
>                                     />
>                                 </Col>
> 
>                                 <Col xs={6} sm={6}>
>                                     <Select
>                                         placeholder="Graduation Passing Year"
>                                         options={["2016", "2017", "2018", "2019", "2020", "2021", "2022"]}
>                                     // style={{ width: '1225px' }}
>                                     />
>                                 </Col>
>                             </Row>
>                             <br />
>                             <Row>
>                                 <Col>
>                                     <Box align="center" >
>                                         <Link to="/New">
> 
>                                             <Button
>                                                 label="Submit"
>                                                 color="orange"
>                                                 primary={true}
>                                             />
>                                         </Link>
> 
>                                     </Box>
>                                 </Col>
>                             </Row>
>                             <Row>
>                                 <Col>
>                                     <Clock type="digital" align="center" justify='front' />
>                                 </Col>
>                             </Row>
>                         </Col>
>                     </Row>
>                 </div>
>             </Container>
>             <Box flex={false} tag="footer" align="center" background="#0091ea" pad="small" border={{ side: 'top' }}
>             >
>                 Management Information System
>             </Box>
>         </div >
>     );
> }
> ```
> 
> }
> export default Bangalore;

from what i see here you are not using the size prop i mentioned. can you try and let me know how it works?

**Comment by karthickselvendran** [comment]
I used but before that some erros on codesandbox how can i solve that?
![p1](https://user-images.githubusercontent.com/52481101/66273373-e5cf1800-e890-11e9-8874-dc901c739862.png)

**Comment by karthickselvendran** [comment]
How can I contact you ?

**Comment by oorestisime** [comment]
But you are using this in the style prop. it has to be directly in the Select component just like the placeholder or options. Please join the slack https://slackin.grommet.io/ and ask in the channel for general help! more people should be able to help.

**Comment by karthickselvendran** [comment]
help me to solve this problem

**Comment by ShimiSun** [comment]
@karthickselvendran on `style` prop you supposed to use CSS styles. `size` is a grommet prop and not meant to be used as a CSS style.
Try to use something like:
```
<Select
  ...
  size="large" />
```
For more questions feel free to use the slack channel https://slackin.grommet.io/ .

**Comment by karthickselvendran** [comment]
Kindly anyone Please add me in slack grommet channel. I am not able to join in that channel.  I don't have a invite link.

> Try to use something like:
> 
> ```
> <Select
>   ...
>   size="large" />
> ```
> 
> For more questions feel free to use the slack channel
     Please add me in slack channel am not able to join in that.  I don't have a invite link.

**Comment by karthickselvendran** [comment]
> @karthickselvendran on `style` prop you supposed to use CSS styles. `size` is a grommet Select prop and not meant to be used as a CSS style.
> Try to use something like:
> 
> ```
> <Select
>   ...
>   size="large" />
> ```
> 
> For more questions feel free to use the slack channel https://slackin.grommet.io/ .

I used the prop size but it will enlarge in all side.  I only need to increase the width only. please help me to Solve the problem

**Comment by ShimiSun** [comment]
Have you tried using this link https://slackin.grommet.io/, click Advanced -> and proceed?

**Comment by karthickselvendran** [comment]
In my country the website is blocked I not able to join in that
