### ISSUE TITLE
InfiniteScroll: onMore() doesn't get fired if step == items.length 

### ISSUE THREAD

**Issue by NetworkAndSoftware** [grommet/grommet#3447]
It appears that if the amount of items is <= than the step value, onMore never fires. 

This is strange for an application developer if you're using this to fetch data in pages. You'd expect to be able to set step to the same size as your data pages and initially populate with exactly step items.

### Expected Behavior

Fire onMore when the last of step items comes into view and items.length == step.

### Actual Behavior

onMore() doesn't get fired if step == items.length 

### Steps to Reproduce

1. Open the example InfiniteScroll sandbox at https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=infinitescroll&module=%2Fsrc%2FInfiniteScroll.js
2. Change the amount of items created to 20 (`while (ITEMS.length < 20)`), set step to 20. 
3. Might need to save or refresh for the edit to take effect.
3. Observe how you can't scroll past item #19. 

### Your Environment

Firefox 69.0.2 on Windows. See it in Chrome too.

- Grommet version: 2.7.9

**Comment by rodrigoalvesvieira** [comment]
I've also observed this same behavior

### Your Environment
Chrome 78.0.3904.97 on macOS.

 * Grommet version: 2.7.8

**Comment by oorestisime** [comment]
Calling the infinite guru :D @ericsoderberghp

**Comment by IanKBovard** [comment]
@NetworkAndSoftware Have you checked again? It seems the issue has been solved by a previous PR.

**Comment by ShimiSun** [comment]
Thanks for reporting, I'll be closing this issue, please file an updated one if you still encounter any new issues.
