### ISSUE TITLE
Cannot access Theme Properties outside of components

### ISSUE THREAD

**Issue by afreix** [grommet/grommet#3470]
### Expected Behavior

Docs say "import { defaultProps } from 'grommet' and accessing defaultProps.theme" (https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation#accessing-theme-data-outside-grommet-components)

### Actual Behavior

I get an error when trying to `import { defaultProps } from "grommet"`
I assume the docs are out of date, but I don't know how to access theme props outside of components

### Your Environment
- Grommet version: "grommet": "2.7.8",

**Comment by taysea** [comment]
Hey @afreix, I just was looking into this. Are you by chance working on a project using Typescript? For me, I had the same issue when testing on a typescript project, but was fine on a non-TS project. Let me know because that will help narrow down the fix.

**Comment by afreix** [comment]
Hey @taysea yeah I’m working on a TypeScript project. Could it be that the types are just incorrect?

**Comment by taysea** [comment]
Potentially, but I will look into it more!
