### ISSUE TITLE
DropButton: iOS (all Browsers) Not closing on blur (iOS 12.4.2 and below)

### ISSUE THREAD

**Issue by KaSSii** [grommet/grommet#3472]
### Expected Behavior

- If dropButton is open, clicking outside of the drop down should trigger the onClose event

### Actual Behavior

- onClose event is not triggered

### Steps to Reproduce

1. Open dropButton on any iOS device
2. Attempt to close dropButton but clicking outside of the options

### Your Environment

- Grommet version: 2.7.9
- Browser Name and version: iOS Safari/Chrome 
- Operating System and version (desktop or mobile): iOS 12.4.2 and below (working in iOS 13 and above. Including beta)

**Comment by ShimiSun** [comment]
Can you describe the use case you are using the Drop?
If the Drop opens as part of Menu or Select http://localhost:9001/?path=/story/select--simple, it will be closed when clicking outside, but in some cases, if the drop is meant to be part of the DOM without disappearing then it shouldn't.
You have a prop `onClickOutside` https://v2.grommet.io/drop#onClickOutside, where you can set the behavior to apply when you click outside of the drop.
Hope this helps.
I'll be closing this issue, feel free to ask more questions or reopen if needed.

**Comment by KaSSii** [comment]
Thanks @ShimiSun I didn't know that "onClickOutside" existed, I will give it a go and report any finding.
