### ISSUE TITLE
ts: Select on change event error

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet#3481]
The onChange event for `<Select />` does not correspond to the actual use of the type
ie: 
https://github.com/grommet/grommet/blob/d8f7eafcccaa38b79d810d36f8f9734bf0636cd4/src/js/components/Select/index.d.ts#L25

while: https://github.com/grommet/grommet/blob/d8f7eafcccaa38b79d810d36f8f9734bf0636cd4/src/js/components/Select/SelectContainer.js#L163 
has `value` and `option`

example to reproduce: any of the storybook examples convert to typescript. ie
```
<Select
  options={options}
  onChange={({ option }) => setValue(option)}
/>
```

will result in error 
`Property 'option' does not exist on type 'ChangeEvent<HTMLSelectElement>'.`

**Comment by taysea** [comment]
I've been looking into this and found that onChange has these items:
```
onChange({
        option,
        value: nextValue,
        selected: nextSelected,
})
```
I am thinking that the type definition should be something like:
```
  onChange?: ((event: { option, selected, value }) => void);
```
However, the piece I am working on is how to declare types for `option`, `selected`, and `value`. If I give each of these the type that is defined in the Select interface (for example: `option: string | boolean | number | JSX.Element | object;`), but in a user's application the Select options are strings, then something like this will have the following error:
```
<Select
          id="select"
          name="select"
          placeholder="Select"
          value={value}
          options={options}
          onChange={({ option } ) => setValue(option)}
        />
```
Error: `Argument of type 'string | number | boolean | object | Element' is not assignable to parameter of type 'SetStateAction<string>'.
  Type 'number' is not assignable to type 'SetStateAction<string>'`

However, if we don't declare any types on option, selected, or values, then it seems to defeat the purpose of declaring types. @britt6612 any thoughts?

**Comment by ryanjchr** [comment]
I've had success with this by re-declaring Select and SelectProps as generic types as follows:
```tsx
/** /src/@types/grommet.d.ts */
import React from 'react';
import { DropProps } from 'grommet';
import {
  A11yTitleType,
  AlignSelfType,
  GridAreaType,
  MarginType,
  PlaceHolderType,
} from 'grommet/utils';

declare module 'grommet' {
  interface SelectProps<T extends string | boolean | number | JSX.Element | object> {
    // ... all the other SelectProps omitted for clarity
    disabledKey?: string | ((value: T) => any);
    labelKey?: string | ((value: T) => any);
    onChange?: (event: { option: T; value: T[]; selected: number[] }) => void;
    valueKey?: string | ((value: T) => any);
    options: T[];
  }

  class Select<T extends string | boolean | number | JSX.Element | object> extends React.Component<SelectProps<T>> {};
}
```

And then you can use `Select` just as you always have, no need to use the diamond operator or anything, because the generic type gets inferred from the type of the `options` prop.
```tsx
/** /src/App.tsx */
const App: React.FC = () => {
  const OPTIONS = [{ name: "Lesie", age: 35 }, { name: "Ron", age: 55 }];
  const [selected, setSelected] = React.useState<{
    name: string;
    age: number;
  }>();

  return (
    <Select
      options={OPTIONS}
      value={selected}
      labelKey={({ name, age }) => `${name} (${age})`} // these props now have full type safety
      onChange={({ option }) => setSelected(option)}
   />
);
```

Heres a codesandbox that demonstrates the above:
https://codesandbox.io/s/select-grommet-generic-es6un

**Comment by jcfilben** [comment]
Closing this since updating the type for `onChange` in Select is already being tracked in https://github.com/grommet/grommet/issues/3165
