### ISSUE TITLE
grommet enterprise components and design-system, need your comments

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#3489]
Grommet is inclining to allow an extended version of components that may be serving the enterprise industry.

The current list of components we had in mind for the extended design-system:
Avatar 
Navbar
Header
Footer
Sidebar
List
Onboard
Breadcrumbs
wizard
pagination
Tip
Tags
Toggle
Popover
Card
Login
Content/Section
Tree
TreeTable
Validation
Dialog Forms
NumberInput
Tiles
Charting
Toast

You can find more context here https://github.com/grommet/grommet/issues/3271

We are not committing to any component yet, and we'll initially like to hear your feedback!
Feel free to share with us any more ideas for components or directions.

Linked to #3354

**Comment by nomadus** [comment]
Happy to help with the priorities. My list of priorities would be (in descending order):
Pagination, breadcrumbs, tip (tooltip), charts, tags, numberinput, datetime (it is not in the list). As I am already using grommet-controls, tags, date and number inputs are at the bottom.

**Comment by atanasster** [comment]
first priorities list:
https://v1.grommet.io/docs/components

**Comment by sergeylukin** [comment]
Thanks for asking! My preference would be as follows:

- Masonry grid (missing!)
- Cards
- Plug-n-play mobile navigation
- All-the-forms (inputs, login, validation, etc.)
- Navbar
- all the rest mostly the ones from v1

**Comment by jcfilben** [comment]
Oof the components listed above the following have been added to grommet:
Avatar
Navbar
Header
Footer
Sidebar
List
Pagination
Tip
Tags
Card
Toast (Notification)

Moving forward we would like to track new components by request in separate issues. I will be closing this issue and separate issues can be created for new components as needed.
