### ISSUE TITLE
Calendar: accept empty values and disabled didn't work

### ISSUE THREAD

**Issue by Waize** [grommet/grommet#349]
Hey, 

if you put an empty value (" ") into the calendar component, it will create the date of today. 
Is it possible to put and get empty values too? 
For example using this for "get it done until ..." and you can leave it empty if it doesn't matter when it will be done. :) 

And the second one: 
You cannot disable the input field of the component.

**Comment by alansouzati** [comment]
Thanks for the feedback.

This is a behavior added only to the docs site: https://github.com/grommet/grommet-docs/blob/master/src/docs/components/CalendarDoc.js#L16

If you have your Calendar instance the date will only be set when you select it.
