### ISSUE TITLE
MS Edge: Read Only Form Field will Display an "x" to Remove the Read Only Data

### ISSUE THREAD

**Issue by ANDRESROMEROH** [grommet/grommet#3495]
I just wanted to log this with an issue, when using ReadOnly FormFields in MS Edge the browser will display a little "x" when clicking on the field meaning that can be editable even when the field is read only, the "x" removes the text on it but it will get back after clicking any other place which does not affect but I think it can cause a miss perception for some users meaning they can actually edit the field. 

### Expected Behavior:
MS Edge should not show the removing "x" just as Firefox and Chrome does.

### Actual Behavior
![image](https://user-images.githubusercontent.com/22283177/67487084-8744c080-f62a-11e9-927e-25b7093f9c26.png)

### Steps to Reproduce

```jsx
<FormField label='QA Audit Date*' name='audit-date'>
     <TextInput 
        readonly
        size='medium'
        value={this.props.auditDate || ''}
     />
</FormField>
```

### Your Environment

- Grommet version: 2.7.8
- Browser Name and version: MS Edge build 18362 
- Operating System and version (desktop or mobile): Windows 10 1903

**Comment by IanKBovard** [comment]
not sure if I'm reproducing this correctly, but I no longer see this in the latest version of edge.

https://codesandbox.io/s/cranky-mountain-mbc9e?file=/src/App.js

grommet Version 2.15
edge Version 84.0.522.63 (Official build) (64-bit)

**Comment by ShimiSun** [comment]
Thank you @IanKBovard.
@ANDRESROMEROH feel free to reopen the issue with detailed steps on how to reproduce in case the issue is still relevant. Thank you for reporting.
