### ISSUE TITLE
max-width for Sidebar?

### ISSUE THREAD

**Issue by NerdGGuy** [grommet/grommet#350]
On Chome: Sidebar size="small" has no effect in the case below. The split is in the middle of the page

```
ReactDOM.render( <Split><Sidebar size="small"><List><ListItem justify="between"><span>test</span><span className="secondary">second</span></ListItem><ListItem>test2</ListItem></List></Sidebar><List><ListItem>Test</ListItem></List></Split> , element);
```

adding max-width seems to solve the issue.

**Comment by alansouzati** [comment]
Take a look on the flex option in here: http://www.grommet.io/docs/hpe/develop/split

You need to specify that your flexible container is the one on the right. By default, the split uses flex both.

```
<Split flex="right"></Split>
```

I've created a codepen to illustrate your scenario. http://codepen.io/alansouzati/pen/KVxMEJ?editors=0010

**Comment by NerdGGuy** [comment]
Thanks!
