### ISSUE TITLE
Tabs are always aligned to center of the page

### ISSUE THREAD

**Issue by C5197328** [grommet/grommet#351]
Is there a way to align the tabs to left rather than default to center?

**Comment by alansouzati** [comment]
Currently this is not supported. PR gladly welcome. This should not be difficult to implement.

**Comment by jwijay** [comment]
Hi @C5197328 ! We've implemented a justify option for the Tabs component.
The updated Docs page is here:
http://www.grommet.io/docs/develop/Tabs

If you leave the responsive option to true (default), then for smaller screen sizes, the tabs will stack into a centered column. If you set responsive to false, in smaller screen sizes, the tabs will continue to wrap, and remain left (or right) justified.
