### ISSUE TITLE
Grid component a11yTitle is documented but not clear

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#3517]
Using `<Grid a11yTitle="ARIA label">...</Grid>` does not produce a div tag wth an `aria-label`.

### Expected Behavior
It is unclear what the expected behaviour ought to be.  Perhaps the `a11yTitle` attribute ought to be removed from the `<Grid>` component?

It is unclear.  The documentation describes it, so I was only experimenting with it to understand how it worked.

### Actual Behavior
`aria-label` was not rendered.

Despite using `a11yTitle` attribute in my `<Grid>` component, it did not render an `aria-label` attribute.
### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: v2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10.

**Comment by ShimiSun** [comment]
Thank you for reporting, the fix will be available on our next release! (soon :) )
