### ISSUE TITLE
Bug: Moving RangeInput or RangeSelector on Chrome for Android triggers swipe-to-go-back/forward

### ISSUE THREAD

**Issue by skoshy** [grommet/grommet#3518]
### Expected Behavior

You should be able to swipe on RangeInputs and RangeSelectors without triggering any side effects.

### Actual Behavior

Swiping on them triggers the back button or forward gestures on Chrome for Android.

### URL, screen shot, or Codepen exhibiting the issue

See the official RangeInput Codesandbox
https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=rangeinput&module=%2Fsrc%2FRangeInput.js

![20191031_123632](https://user-images.githubusercontent.com/369825/67967315-c8654380-fbdb-11e9-97c1-acd9c973d01f.gif)

### Steps to Reproduce

Try swiping on a RangeInput or RangeSelector on Chrome Mobile with swipe gestures turned on.

### Your Environment

Samsung Galaxy S10

### Potential Solution

I was able to make a small modification to fix the issue - see [this Codesandbox](https://codesandbox.io/s/grommet-sandbox-fz9lv). I wrapped the RangeInput with a `div` with a passive event handler on it (sources for further reading: [[1]](https://stackoverflow.com/a/46439501/506913), [[2]](https://developers.google.com/web/updates/2017/01/scrolling-intervention))

Ideal version would be to do this on the input itself instead of a container div.

**Comment by jcfilben** [comment]
I'm no longer seeing this issue (using v2.19.1 of Grommet) I tested on my android device and was able to swipe on RangeInput and RangeSelector without triggering the back/forward behavior on the browser.
Related to https://github.com/grommet/grommet/pull/5139
