### ISSUE TITLE
Grommet component with full prop does not extend with scrolling

### ISSUE THREAD

**Issue by blakehilliard** [grommet/grommet#3521]
When I render a `<Box fill background=something>` inside a `<Grommet full>` which goes down further than the browser can show, and then I scroll down, the background color of the Box stops at the point where the initial view was cut off. If I remove "full", the background color extends downward as expected.

### Expected Behavior

The full prop should not make it _less_ full in how much space it fills up!

### Actual Behavior

The background color of the Box does not fill the entire Box.

### URL, screen shot, or Codepen exhibiting the issue

![grommet-full-bug](https://user-images.githubusercontent.com/25166376/68057715-c32ff380-fcc4-11e9-87d1-029c33bbca2c.png)

### Steps to Reproduce

```
import React from 'react';
import { Box, Grommet } from 'grommet';

export default () => (
  <Grommet full>
    <Box fill background="light-2">
      <Box align="center">
        {[...Array(80).keys()].map(idx => (
          <Box flex={false}>{`Index ${idx}`}</Box>
        ))}
      </Box>
    </Box>
  </Grommet>
);
```

Drop the `full` above, and the problem goes away!

### Your Environment

- Grommet version: 2.7.11
- Browser Name and version: Chrome 78.0.3904.70 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows desktop

**Comment by blakehilliard** [comment]
A codesandbox: https://codesandbox.io/s/grommet-issue-3521-lixy7

**Comment by Blacknosaur** [comment]
You can bypass the issue by adding height 100% to your html, body and your grommet component.

**Comment by ShimiSun** [comment]
Hi @blakehilliard , you have a bug in your bug, you should use `full` instead of `fill`, there is no `fill` prop for Grommet.
I fixed it and it seems to work as expected https://codesandbox.io/s/grommet-issue-3521-tk0ro
I'll be closing the issue, feel free to reopen if needed.

**Comment by blakehilliard** [comment]
> Hi @blakehilliard , you have a bug in your bug, you should use `full` instead of `fill`, there is no `fill` prop for Grommet.
> I fixed it and it seems to work as expected https://codesandbox.io/s/grommet-issue-3521-tk0ro
> I'll be closing the issue, feel free to reopen if needed.

I'm confused. The example and codepen I posted do use `full` for Grommet. And when I look at your codepen, it still has the same issue.

I don't have permission to re-open this issue. So I guess I'll just open a new one in a few days if this doesn't get re-opened by someone with permission to do so.

**Comment by ShimiSun** [comment]
@blakehilliard reopening and taking another look....

**Comment by ShimiSun** [comment]
@blakehilliard so it works if you remove the `fill` from the upper Box, was there a reason you used it there? https://codesandbox.io/s/grommet-issue-3521-tk0ro

**Comment by blakehilliard** [comment]
> so it works if you remove the `fill` from the upper Box, was there a reason you used it there?

Well the codepen was an oversimplified example to just demonstrate the problem. What I'm trying to do is just have a consistent background color for an app no matter how much info gets displayed on the screen. If you have to scroll down, I don't want the background color to suddenly get cut off. But if I remove `fill`, and the browser is larger than the amount of space it needs, I don't want the background color to get cut off either.

**Comment by ShimiSun** [comment]
Thanks for clarifying @blakehilliard

**Comment by IanKBovard** [comment]
@blakehilliard just checking in on this issue, have you tried giving the Grommet component itself a background color? That would solve your issue, but I'm not sure if it would suit your implementation.

**Comment by ShimiSun** [comment]
I'm thinking that adding a `fill` prop to the Grommet component will help resolve this issue.

**Comment by ericsoderberghp** [comment]
I think the end result we want in this case is for `<Grommet />` to end up with `min-height: 100vh;`.  Currently, `<Grommet full />` results in `height: 100vh;`. Both are valid scenarios. One suggestion: `<Grommet full="min" />`?

**Comment by ShimiSun** [comment]
Hi guys, in the meanwhile, here is a quick fix for the issue while we work on the enhancemnet https://codesandbox.io/s/grommet-issue-3521-9mlis?file=/src/index.js

**Comment by jcfilben** [comment]
To achieve the desired behavior I believe the `full='min'` prop should be used here instead of `full={true}`. See this example https://codesandbox.io/s/grommet-issue-3521-forked-lh6f5?file=/src/index.js.

**Comment by avirgvd** [comment]
`flex={false}` as in the code from [https://codesandbox.io/s/grommet-issue-3521-tk0ro](https://codesandbox.io/s/grommet-issue-3521-tk0ro) fixed the same issue I faced.
