### ISSUE TITLE
Checkbox Toggle inconsistent border pixel size on hover

### ISSUE THREAD

**Issue by remjx** [grommet/grommet#3522]
### Expected Behavior

Toggle border does not look pixelated on hover.

### Actual Behavior

When the toggle is off, and I hover over the toggle button, the visible border on the left side is an inconsistent number of pixels. 

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/35121685/68089160-078dd180-fe34-11e9-94ad-d41db1f46cd4.png)

### Steps to Reproduce

https://v2.grommet.io/checkbox?c=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKRAbwChFEIEBnKRAbQgAt8IBrfAEwBpEdfFADC7LrwC6iALyIASvnTQAdCCEBlKOihEoAJxD5iAbiqJ9wkPqSFz1ADxiOnAEJxU96jXHceMsjYXXgBfL2ooOABzKIJwxFx0ACN8XBkAIhgwXUsGXgB+dPiEMXQwKPwAwnwAN3xs0hkAPkFhZwkearrslW19CqgVII7iMO9EAHom81MKEKA

### Your Environment

Tested in Chrome and Firefox.

**Comment by felipebrunetti94** [comment]
got it  :D

**Comment by ShimiSun** [comment]
what do you mean by 
>is an inconsistent number of pixels.

would you expect not to see the border at all when hovering on the left side of the toggle off checkbox?

**Comment by markjackson02** [comment]
Not sure if it would look better with or without border when toggle is off. But right now it is somewhere in between and it looks off. That screenshot is from 1080p desktop. On iPhone XR it is less noticeable because of higher resolution / antialiasing.

**Comment by ericsoderberghp** [comment]
The current math is correct. If I remove the border radius from the track and the knob everything looks right. I think the bleed through is a side effect of how the anti-aliasing is working along the rounded edges. It doesn't seem to matter whether the colors are changed or whether a border is added to the knob. Rather than fight with the pixels further, I'm inclined to leave the behavior as it is.

**Comment by jcfilben** [comment]
Marking this as closed based on the above comment but feel free to re-open/comment if you would like to continue discussion on this.
