### ISSUE TITLE
Discussion on format of storybook titles

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#3526]
Opening a discussion on how Grommet Storybook examples are named/formatted. Across the board, we are using very various capitalization/formatting approaches. For example, some stories use a mixture of upper and lower case (`Areas prop alternative`) while the majority use title case (`Responsive Grid`). For consistency across stories, I think we should come up with a style guide on how stories are named/capitalized.

Some areas of consideration would be:

- If a storybook example is titled with the name of the prop, do we leave it lowercase/camel case to match how it would be typed in code? (`border` or `onChange` as opposed to `Border` or `OnChange`)
- If a storybook is combining multiple props or concepts, what punctuation do we use to indicate this? (`Controlled and Grouped` or `Controlled & Grouped` or `Controlled, Grouped` or `Controlled + Grouped`)
- Do we use all lowercase?

Storybook has their own default page (https://storybooks-official.netlify.com/?path=/story/addons-notes--addon-notes-rendering-inline-github-flavored-markdown) and they seem to be using the convention that the main folders (in our case the components) are capitalized while stories within those folders are all lowercase. However, this is not consistent across all of their examples, so I'm not sure we can lean fully on this as a guide.

Please feel free to add your comments/input. While this doesn't affect the ability to use grommet code, I think that establishing structure/consistency in storybook titles will create a more polished look.

**Comment by ShimiSun** [comment]
Thank you for putting this together! 
linking to #3212

**Comment by ericsoderberghp** [comment]
I am leaning towards Title case for folders, matching the case of properties when a story is for demonstrating that property, and using Sentence case for all other stories.

**Comment by taysea** [comment]
And what about stories that have multiple concepts in the title. Would we want to standardize punctuation/phrasing in any way? For example there is a story for Accordion called `Dark no animation`. I think the title makes sense to someone familiar with grommet, but for a new user it might not be clear that it's really saying Dark _and_ there's no animation on the panels. Some variations in how that might be handled (following sentence case) could be:
- `Dark, no animation`
- `Dark + no animation`
- `Dark and no animation`
- `Dark & no animation`

another example would be for the FormField help/error text story:
- `Help, error`
- `Help + error`
- `Help and error`
- `Help & error`

Does it make sense to select one of these formats and standardize this punctuation, or should it be a case by case decision?

**Comment by ericsoderberghp** [comment]
I'd tend towards simple English sentences:

- Dark without animation

And, since `help` is a property of `FormField`:

- help and error

**Comment by ShimiSun** [comment]
For the latter, I'm thinking it will look inconsistent if some stories will be names lower case while others won't, and I'm inclining to do it all lower case like the storybook official https://storybooks-official.netlify.com/?path=/story/addons-notes--addon-notes-rendering-inline-github-flavored-markdown

**Comment by ShimiSun** [comment]
This was taken care of as part of the storybook refactoring and renaming all stories to use sentence case. Thank you!
