### ISSUE TITLE
Unable to change focus behavior of `TextInput` / `Selection` components via theme

### ISSUE THREAD

**Issue by clockelliptic** [grommet/grommet#3542]
I would like to great a reusable Grommet theme where the focus-state of `Selection` and `TextInput` is a custom color. There is apparently not possible to change this by providing a theme to a Grommet component. It is not possible by using the Grommet Theme Builder.

Perhaps I am not editing the theme correctly, I don't know.

### Behavior

I provide a theme as a prop to the main app component in `index.js`:

    const theme = {  
        "select": {
          "background": "black",
          "container": {},
          "control": {},
          "icons": {},
          "options": {
            "box": {
              "align": "start",
              "pad": "small"
            },
            "text": { "margin": "none" }
          },
          "step": 20,
        },
    . . .  /* more custom theme options */
    }

    ReactDOM.render(
        <Grommet full theme={theme}><App /></Grommet>, 
        document.getElementById('root')
    );

Then in  `App.js`:

```
import React from 'react';
import { Select, Box } from 'grommet';

function App() {
    return (
        <Box>
            <DropSelect options={...} placeholder={...} />
        </Box>
    );
}

function DropSelect(props) {
    const [value, setValue] = React.useState(props.placeholder);
    return (
      <Select
        options={props.options}
        value={value}
        onChange={({ option }) => setValue(option)}
      />
    );
}
```

Unfocused `<DropSelect />`:
![select_no_glow](https://user-images.githubusercontent.com/38416270/68522105-8d1ae280-0275-11ea-836e-047b19337e0d.PNG)

Focused `<DropSelect />`:
![select_glow](https://user-images.githubusercontent.com/38416270/68522111-92782d00-0275-11ea-9bbb-ddb8835ec6fb.PNG)

I've tried providing the `theme` object with several variations of attempts to change the `outline` and/or `border`, as well as attempts to change its style in a focused state. Again, I would like to apply this as a theme to several apps from the highest level possible, without having to do any inline styling.

Any insight would be very helpful.

**Comment by ShimiSun** [comment]
Have you seen this story where you can customize the theme focus color? https://storybook.grommet.io/?path=/story/theme--focus
Does that answer your question?

**Comment by IanKBovard** [comment]
@clockelliptic Just checking in to see if ShimiSun was able to answer your question.

**Comment by clockelliptic** [comment]
Thanks so much for the reply and sorry for the delay. Somehow I missed this.

This is very helpful, but no it doesn't entirely answer my Q. 

Would love to be able to style the focus color of a single specific element.

**Comment by IanKBovard** [comment]
If it's for a single specific element, styled-components could help you with that.

```
  const styledBox = styled(Box)`
    // your focus styling here
  `
```

**Comment by ShimiSun** [comment]
In addition to styled-component option that @IanKBovard suggested, you may want to consider the ThemeContext component that allows setting the theme for specific components this is wrapped with ThemeContext.  See an example here https://storybook.grommet.io/?path=/story/accordion--rich
and docs here: https://v2.grommet.io/themecontext

**Comment by IanKBovard** [comment]
@clockelliptic Let us know if that solves your problem, and we can close this issue.

**Comment by IanKBovard** [comment]
@clockelliptic this should help you with your issue https://storybook.grommet.io/?path=/story/theme--themecontext-extend

**Comment by ShimiSun** [comment]
I think we are good on closing this issue, @clockelliptic let us know if you have further questions.
