### ISSUE TITLE
FormField > TextInput as number becomes text after change

### ISSUE THREAD

**Issue by RobertoSnap** [grommet/grommet#3545]
### Expected Behavior
When passing a number to a FormField > TextInput it should resolve a number value on submit. 

### Actual Behavior
It resolves the number as a string.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-sandbox-utqys

### Steps to Reproduce

1. Input name
2. Click submit
3. Check console (Age is number)
4. Input age
5. Click submit
6. Check console (Age is a string)

### Your Environment

Check https://codesandbox.io/s/grommet-sandbox-utqys

**Comment by RobertoSnap** [comment]
Worked by adding `type="number"` to the FormField. 

Maybe document this?

**Comment by ShimiSun** [comment]
@RobertoSnap thanks for sharing. `type` prop is coming from HTML input tag and grommet is documenting the grommet props and not all react or html props.
Will you be willing to make a contribution to https://storybook.grommet.io/?path=/story/form--all so the Employee ID field will have type="number" so the users will still be able to see an example of how to achieve it?
