### ISSUE TITLE
gap prop ignored for items in Menu

### ISSUE THREAD

**Issue by blakehilliard** [grommet/grommet#3546]
For Menu "items", the documentation says `The object values can be any Button prop`. But if I specify a "gap", it is ignored.

### Expected Behavior

The gap should be used to put space between the icon and label of the item, just like in a "Button".

### Actual Behavior

No gap is used.

### URL, screen shot, or Codepen exhibiting the issue

Here is a codesandbox demonstrating the issue: https://codesandbox.io/s/grommet-menu-item-no-gap-86omy

### Steps to Reproduce

```
      <Menu
        label="Menu"
        items={[
          {
            icon: <Power />,
            label: "Power",
            gap: "xlarge"
          }
        ]}
      />
```

### Your Environment

- Grommet version: 2.8.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows desktop

**Comment by ShimiSun** [comment]
Thank you for filing this issue. It's a bug with how the icon is rendered separately from the button. We'll take a look at that.

**Comment by ShimiSun** [comment]
Thank you for reporting, the fix will be available on our next release.
