### ISSUE TITLE
MaskedInput component is indistinguishable from a placeholder

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#3554]
## Summary
Currently the masked input behavior behaves more as input validation with a placeholder, not as mask. 

![output](https://user-images.githubusercontent.com/487897/68980325-c7c8d180-07c5-11ea-8f07-66071c961712.gif)

## Steps to Reproduce
- View the input mask example for emails in the [storybook](https://storybook.grommet.io/?path=/story/maskedinput--email)
- Observe that the entire email value placeholder is replaced upon inputting a value. 
- Observe this is placeholder behavior, not mask behavior.

## Expected Results
I expect input masks to persists and display to the left, right or in-between values (e.g date slashes). Examples

- https://codepen.io/kjhobin/pen/rVYNjb
- http://jsfiddle.net/ThomasH/108grs9g/

**Comment by IanKBovard** [comment]
@iMerica If you look at these storybook examples you can clearly see the MaskedInput component working. I just think the email example makes it confusing, as it's not the best representation of the component.

https://storybook.grommet.io/?path=/story/maskedinput--ipv4-range
https://storybook.grommet.io/?path=/story/maskedinput--date-range
https://storybook.grommet.io/?path=/story/maskedinput--phone
https://storybook.grommet.io/?path=/story/maskedinput--time

**Comment by IanKBovard** [comment]
@iMerica Please look at the examples provided. MaskedInput behaves as it should.

**Comment by iMerica** [comment]
We appear to be operating on different definitions of input masks. The way, I'm expecting to see it:

**ip addresses**
The dots always appear when the element is in focus, even when nothing has been entered.

**email addresses**
A few approaches depending on requirements
- `@` always symbol appears
- `@domain.com` always appears, (restricting any 3rd party emails).

**Phone numbers**
`(___) - ___- ____` (dashes always appear)


I'm expecting input masks to behave as template that let users fill in the blanks.

**Comment by ShimiSun** [comment]
So the action item from this issue will be to refactor story examples to keep the templates on the input fields instead of placeholders.

**Comment by IanKBovard** [comment]
@iMerica any update on this before we close this issue? This seems to be an issue with implementation.

**Comment by ShimiSun** [comment]
I'll be closing this issue, feel free to reopen if it is still relevant and you have more details to share.

**Comment by ShimiSun** [comment]
I'm reopening this issue, following slack communication https://grommet.slack.com/archives/C09QQEG69/p1594256496360000
![image](https://user-images.githubusercontent.com/6320236/86993876-54177280-c162-11ea-8e5a-b312efd017ee.png)

**Comment by bdesouza** [comment]
Thanks! @ShimiSun 

One of the drawbacks with the current component is with keyboard interactions. Specifically, if there is a mask in place a user wouldn't know how to move forward other than typing. It's not very obvious as `tab` will remove focus from the component. `space` on the other hand does move the user to the next section of the mask.

Secondly, since the mask enforces the "structure", moving the cursor backward (via back arrow or delete) is particularly challenging. It results in a messy fight with the mask and the keyboard.

**Comment by ShimiSun** [comment]
The last comment may be related to: #4122

**Comment by jcfilben** [comment]
Closing since MaskedInput has been enhanced since this issue was created and you can have fixed text and keyboard interaction has improved. (note tabbing will still remove focus from the input For users navigating by keyboard I think the expectation is for tab to take them to the next element).
