### ISSUE TITLE
Does Grommet have a "loading indicator" component?

### ISSUE THREAD

**Issue by localhosted** [grommet/grommet#356]
Does Grommet have a general purpose loading indicator? I see that the graph seem to have a loader when there is no data, and I wanted to add something similar to tables and lists.

**Comment by alansouzati** [comment]
```
var Spinning = require('grommet/components/icons/Spinning');
```

You can see it live here: http://www.grommet.io/docs/hpe/design/basics#icons

**Comment by danielo515** [comment]
That does not exist, so no, gromet does not have a loading indicator.

**Comment by forresthopkinsa** [comment]
So this used to be a thing and now it's not? Pretty lame.

**Comment by atanasster** [comment]
@forresthopkinsa , there is a spinning component in `grommet-controls` https://atanasster.github.io/grommet-controls/?path=/docs/controls-controls-spinning--main

You can also add your input into #3271

**Comment by britt6612** [comment]
@forresthopkinsa Grommet has provided a pattern to provide users examples of how to use a loading page https://codesandbox.io/s/loaders-and-spinners-4jltk check out this link! Also feel free to provide any feedback!

**Comment by forresthopkinsa** [comment]
Thanks for the help guys

**Comment by Eplumecocq** [comment]
@britt6612 this is exactly what I need, thanks a lot

**Comment by britt6612** [comment]
@Eplumecocq Your welcome glad to help! 👍

**Comment by leifg** [comment]
It does since 2.17.0: https://v2.grommet.io/spinner
