### ISSUE TITLE
Consider adding `fill` to Markdown

### ISSUE THREAD

**Issue by vrde** [grommet/grommet#3568]
### Expected Behavior
As a user of the library I would like to have a `fill` option when rendering markdown using the `Markdown` component.

The `fill` option can be used in the `Paragraph` component, and I would expect to have the same behavior using `Markdown`.

### Actual Behavior
Right now I have no way to make the paragraph fill the width of the container :crying_cat_face: 

A workaround would be to use component override, but I'd still prefer to have the same behavior as the `Paragraph` component.

### URL, screen shot, or Codepen exhibiting the issue
Visit the Storybook [under the Markdown section](https://storybook.grommet.io/?path=/story/markdown--simple).

### Steps to Reproduce
Use the `Markdown` component :smiley: 

### Your Environment
- Grommet version: v2
- Browser Name and version: any
- Operating System and version (desktop or mobile): any

**Comment by oorestisime** [comment]
With the addition of the fill prop in Paragraph https://v2.grommet.io/paragraph#fill 
You can component override with the Paragraph component and set the fill there. 

Something along the following should work
```
<Markdown components={{ p: (props)<Paragraph {...props} fill/> }}>{CONTENT}</Markdown>
``` 

I am not sure it makes sense to set this as a default

**Comment by vrde** [comment]
Thank you for the tip! I've tried it out and it works.

As a newbie, I think `fill` would avoid confusion and align the behavior of the `Markdown` component to the one of `Paragraph`.

**Comment by oorestisime** [comment]
Do you mean adding a fill prop in the Markdown component that we forward to the Paragraph?

**Comment by vrde** [comment]
> Do you mean adding a fill prop in the Markdown component that we forward to the Paragraph?

Exactly :+1:

**Comment by ShimiSun** [comment]
Thank you for reporting, you can use the options prop to control the fill property.
