### ISSUE TITLE
Not able change selected date range in Grommet V2 Calendar picker

### ISSUE THREAD

**Issue by krishna-panjimar** [grommet/grommet#3569]
### Expected Behavior

When we pre-select date ranges in calendar component then it should allow us to change date ranges on changing dates 

### Actual Behavior

currently when we pre-select date ranges then it won't allow us to change the date on clicking on dates

Here is my code https://codesandbox.io/s/grommet-sandbox-e19j8

### Steps to Reproduce

1. By default initialize date ranges 
2. Click on other dates in calendar picker 
3. Not able to change dates

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by oorestisime** [comment]
Your previous date is always undefined in your case because you enter first in the else statement of the first if.
You need to check if  you don't have a previous selected date already to set it up at that time. You may also need to clear this value as soon as you enter the next date in range.

**Comment by krishna-panjimar** [comment]
@ShimiSun Thank you for responding. Can you please tell me when can I clear the preselected range. Once we initialize dates then onSelect event is not triggering.

**Comment by krishna-panjimar** [comment]
I got the solution. I need to initialize range in this formate [["2018-10-19", "2018-11-23"]]. Please close this issue.
