### ISSUE TITLE
React Router and Anchor do not work together

### ISSUE THREAD

**Issue by naishe** [grommet/grommet#3572]
I am setting up a new React project using Grommet. Grommet Anchor and React Router Link won't work together. Here is my requirements:

1. The links should be stylized by Grommet. I am using `Anchor` component for this and UI theming is controlled by Grommet.
2. I am using React Router, and the app heavily depends on `Link` component. 

### Reasoning behind why this is crucial
1. I want the user to switch between different themes. Since the theming is controlled by Grommet, I want to use components that are naturally reactive to the theme and theme context.
2. I cannot use bare bone `<Anchor href=` because it causes page reload. On the other hand, `<Link` jumps to the URL without page reload / flicker.
3. A suggested method elsewhere is to use `<Anchor onClick={()=> props.history.push('/path/123')} ...`. This is not desirable because I lose the semantic and the behavior of an anchor. User would not be able to perform "copy the link URL" or "open the link in new tab" features (by right clicking on desktop or long pressing on phone). It is not the right way. You'd use button instead.
4. Another suggested way was to wrap the component in the following manner:
    ```
    <Anchor as="span">
      <Link to="/path/123"/>Path 123</Link>
    </Anchor>
    ```
    It does not work. The Grommet theme is not rendering the Link here.
5. Yet another post suggests to user `<Anchor as={Link} ...` does not work.

### Expected Behavior

Grommet should have a way to wrap `Link` and `NavLink` of React Router -- which is probably the most commonly used routing library.

### Actual Behavior

`Anchor` does not work desirably with `Link`.

### References

1. https://github.com/grommet/grommet/issues/2855#issuecomment-485305773 
2. https://github.com/grommet/grommet/issues/2463#issuecomment-441462312
3. [Getting rid of browser warning when using Grommet Anchor as Link from react-router-dom](https://stackoverflow.com/questions/46786534/getting-rid-of-browser-warning-when-using-grommet-anchor-as-link-from-react-rout)
4. [Relevant discussion on Slack](https://grommet.slack.com/archives/C04LMHN59/p1574687113064800)

### Your Environment

- Packages used:
    ```
    "grommet": "^2.7.11",
    "react-router-dom": "5.0.1",
    "styled-components": "^4.4.0"
    ```
- Chrome latest
- MacOS Majave

**Comment by naishe** [comment]
FYI @ShimiSun @oorestisime

**Comment by oorestisime** [comment]
Thanks for this detailled issue. i ll work on this tomorrow. please hang in there a bit more.

**Comment by localnet** [comment]
It is not fully tested, but seems to work as temporary workaround.

Component `NavigationLink`:
```typescript
import React, { ReactElement } from "react";
import { NavLink, NavLinkProps } from "react-router-dom";
import styled from "styled-components";

const UnsetLink = styled(NavLink)`
    all: unset;
`;

export default function NavigationLink(props: NavLinkProps): ReactElement {
    const { children, ...attributes } = props;

    return <UnsetLink {...attributes}>{children}</UnsetLink>;
}
```

Use the component with Grommet `Anchor`:
```typescript
<Anchor as="span" alignSelf="center" margin={{ horizontal: "small" }}>
  <NavigationLink to="/tattoo">Tatuajes</NavigationLink>
</Anchor>
```

It require a little more of work to see how handle `disabled`, at now the style work perfectly but the link yet permit to click.

PS: Unfortunately, this not work with `Button` well.

**Comment by quinnturner** [comment]
My current solution for a routed button is:

```tsx
interface RouterLinkProps {
  path: string;
}

const RouterButtonBase = (
  props: RouteComponentProps & RouterLinkProps & ButtonProps,
) => {
  return (
    <Button
      {...props}
      href={props.path}
      onClick={e => {
        e.preventDefault();
        props.history.push(props.path);
      }}
    />
  );
};

const RouterButton = withRouter(RouterButtonBase);
```

I add the `href` so that the browser detects that it's a "routed button." I cancel the event, then push to the history stack.

Example:

```tsx
<RouterButton
  path={`/example/path`}
  icon={<Add size="small" />}
  label="Add example"
  primary
/>
```

**Comment by budiadiono** [comment]
@naishe I don't see any problem with `<Anchor as={Link} to="/foo" label="Go to foo" />`, am I missing something?

**Comment by budiadiono** [comment]
I'm using typescript and customize the `Anchor` this way:

```ts
import { Anchor, AnchorProps } from 'grommet/components/Anchor'
import React from 'react'
import { Link, LinkProps } from 'react-router-dom'

export const AnchorLink: React.FC<AnchorLinkProps> = props => {
  return <Anchor as={Link} {...props} />
}

export type AnchorLinkProps = LinkProps &
  AnchorProps &
  Omit<JSX.IntrinsicElements['a'], 'color'>
```

Usage:

```ts
<AnchorLink to="/foo" label="Foo Page"/>
```

And it works!

**Comment by oorestisime** [comment]
Hey i am coming back to this after a long time and i am wondering why the as is not working. what were you experiencing with it?

https://codesandbox.io/s/react-router-basic-de4tx (notice the dashboard link in the example.)

**Comment by oorestisime** [comment]
Lol sorry @budiadiono i didn't read your message. indeed this is the way i would go to avoid the props leakage there. We should document this somewhere as an example. @ShimiSun maybe you have an idea where :) do we have react-router in the storybook?

**Comment by naishe** [comment]
@budiadiono -- thanks for taking time to write the workaround. I really appreciate it. I think we can close this.

**Comment by budiadiono** [comment]
My pleasure @oorestisime & @naishe  :)

**Comment by digitalmonad** [comment]
I've solved it in the "render props" way:

<Anchor
        as={(props) => (
          <Link {...props} to='/some-url'>
            Click me!
          </Link>
        )}
      />

This approach works well with the "<NavLink />" too.

**Comment by alexmirrington** [comment]
@budiadiono As an additional note, we completed a lot of work in March-April 2021 to help improve TypeScript interfaces for component props. From this, we consolidated `AnchorProps & Omit<JSX.IntrinsicElements['a'], 'color'>` into a new interface, `AnchorExtendedProps`. We can expect `AnchorExtendedProps` to be updated as new functionality is added or removed to the `Anchor` component. Your solution is now even more readable and maintainable:

```TypeScript
import { Anchor, AnchorExtendedProps } from "grommet/components/Anchor";
import { Link, LinkProps } from "react-router-dom";
import React from "react";

export const AnchorLink: React.FC<AnchorLinkProps> = (props) => {
  return <Anchor as={Link} {...props} />;
};

export type AnchorLinkProps = LinkProps & AnchorExtendedProps;
```
