### ISSUE TITLE
DataTable onClickRow missing on Typescript

### ISSUE THREAD

**Issue by GaryB71** [grommet/grommet#3574]
Implementing the dataTable in typscript and the onClickRow method is not present/throws TS error 

### Expected Behavior
Shoudl be supported as on the js version

### Actual Behavior
`/home/gary/Source/ui/src/modules/databases/components/DatabaseTable.tsx
TypeScript error in /home/gary/Source/-ui/src/modules/databases/components/DatabaseTable.tsx(82,8):
Type '{ key: string; columns: any[]; data: any; sortable: true; onClickRow: (e: any) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DataTableProps & ClassAttributes<HTMLTableElement> & TableHTMLAttributes<HTMLTableElement>, any, any>> & Readonly<...> & Readonly<...>'.
  Property 'onClickRow' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DataTableProps & ClassAttributes<HTMLTableElement> & TableHTMLAttributes<HTMLTableElement>, any, any>> & Readonly<...> & Readonly<...>'.  TS2322
 
    80 |   return (
    81 |     <Box key="assets-table" data-test-id="assets-table" overflow="scroll" pad="small" elevation="medium">
  > 82 |       <DataTable key="assets-data-table" columns={columns} data={data} sortable={true} onClickRow={onTableRowClick} />
       |        ^
    83 |     </Box>
    84 |   );
    85 | };
`

### Your Environment
Grommet 2.7.3
react 16.9.0
os Fedora 29

**Comment by ShimiSun** [comment]
Thank you for reporting buddy! I filed a fix for it.

**Comment by ltchurch88t** [comment]
Error still seems to be happening on the new release, any thoughts?

`Property 'onClickRow' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DataTableProps & ClassAttributes<HTMLTableElement> & TableHTMLAttributes<HTMLTableElement>, any, any>> & Readonly<...> & Readonly<...>'.  TS2322`

**Comment by ShimiSun** [comment]
@ltchurch88t are you pointing to the master branch? There was no release with this fix yet. you can point to the master branch until the next release.
