### ISSUE TITLE
Datatable infinite scrolling doesn't work with changing data

### ISSUE THREAD

**Issue by atoy40** [grommet/grommet#3576]
InfiniteScrolling doesn't work when DataTable is instanced with an empty list and then updated later.

### Expected Behavior

Infinite scroll must display the remaining data items.

### Actual Behavior

When data of the DataTable is not set at initialisation, only the first "page" of data appear and infinite scroll doesn't work (it's working with 2.8.0 but not with 2.8.1)

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/datatable-scrolling-gudbs

In this codesandbox, the datatable first display an empty list, then the load button click function set the data with a list (DATA) of 200 items. But infinitescroll doesn't add more data when you scroll to the bottom of the list. Only the first 50 are display. If you setup DataTable with data={DATA} directly, no problem.

### Your Environment

- Grommet version: 2.8.1
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by andru** [comment]
I can recreate this with 2.12.0 - any workarounds?

**Comment by IanKBovard** [comment]
@atoy40 and @andru 
In this example onMore fires the instant DataTable renders, and not when data is fetched. Conditionally rendering DataTable when data.length is greater than 0 fixes the issue. 
```
{data.length > 0 && (
  <DataTable
    columns={[{ header: "value", property: "value" }]}
    onMore={() => console.log("LOAD MORE")}
    data={data}
    step={20}
  />
)}
```
It also looks like there was a height issue with the Box the DataTable was in. I updated your example with the solution.

https://codesandbox.io/s/datatable-scrolling-oi1g1?fontsize=14&hidenavigation=1&theme=dark

**Comment by IanKBovard** [comment]
Let me know if this answers your question.

**Comment by atoy40** [comment]
@IanKBovard I'm not working on the app I had the problem, but yes your solution probably works ... sounds obvious :)

**Comment by IanKBovard** [comment]
@atoy40 Thanks for getting back to me. If you're happy with the solution, I think we can close this issue.
