### ISSUE TITLE
No opt-out for box focus style if onClick is specified

### ISSUE THREAD

**Issue by michaeljguarino** [grommet/grommet#3577]
Looks like this PR https://github.com/grommet/grommet/commit/aa70b6ecd6ac875e58615a123c71c93ad4d5907a added some neat functionality around hoverIndicators and focus handling, unfortunately the styling applied isn't possible to opt-out, so suddenly any box using an onClick event handler now gets them.  Ideally this can be avoided.

### Expected Behavior

Have a way to disable focus styling.

### Actual Behavior

Can't seem to disable focus styling

### URL, screen shot, or Codepen exhibiting the issue

n/a

### Steps to Reproduce

n/a

### Your Environment

- Grommet version: 2.7.9, but I think my docker build is actually pulling in latest...
- Browser Name and version: n/a
- Operating System and version (desktop or mobile): n/a

**Comment by ShimiSun** [comment]
Fix will be available on the next Grommet release 2.9.0.
