### ISSUE TITLE
TypeScript: ExtendType does not accept styled-components css helper

### ISSUE THREAD

**Issue by JasonRoss-bt** [grommet/grommet#3578]
### Expected Behavior

Previously we were able to use the `css` helper for `extend`ing components in the theme; however, the new typed theme does not seem to allow for it.

```typescript
const theme: ThemeType = {
  ...grommet,
  anchor: {
    ...grommet.anchor,
    extend: css`
      background-color: red;
    `
  }
};
```

### Actual Behavior

TypeScript build fails with:

```
(property) extend?: ExtendType
Type 'FlattenSimpleInterpolation' is not assignable to type 'ExtendType'.
  Type 'FlattenSimpleInterpolation' is not assignable to type 'string'.ts(2322)
base.d.ts(235, 5): The expected type comes from property 'extend' which is declared here on type '{ color?: ColorType; extend?: ExtendType; fontWeight?: number; hover?: { extend?: ExtendType; textDecoration?: string; }; textDecoration?: string; }'
```

### URL, screen shot, or Codepen exhibiting the issue

Codepen: https://codesandbox.io/s/grommet-typescript-theme-extend-issue-cbpo8

### Your Environment

- Grommet version: 2.8.1
- React version: 16.8.4
- TypeScript version: 3.7.2
- styled-components version: 4.4.1

**Comment by oorestisime** [comment]
Do you know which version was working?

**Comment by ShimiSun** [comment]
hi buddy, @JasonRoss-bt, care to make a contribution and extend the `ExtendType`? and should go here https://github.com/grommet/grommet/blob/e6bac4512e0ae18fdfce17ba65f4a7d920f1000a/src/js/themes/base.d.ts#L18

**Comment by JasonRoss-bt** [comment]
@ShimiSun Thanks for pointing me to the right file... saved me some time :)

I'm working on a fix and hope to have a PR soon.

**Comment by ShimiSun** [comment]
Thank you again for your contribution! ❤️
