### ISSUE TITLE
Proposal: Add support for more semantic React Elements

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#3580]
### Background

One pain point of Grommet currently is readability and debuggability due to the overloading of `Box`, which communicates zero intent. 

For example, let's say all your margins are inconsistent between pages on a site and you want to fix it. In today's Grommet, this is a frustrating experience because, when looking in your Web Inspector all you will see is Style Component random classes. If you look in the Chrome React Toolbar all Boxes are indistinguishable. So we are left with reading through the source, parsing each `<Box/>` trying to guess what its intent is. 

This is a slow and frustrating way to develop in React, so I would like to propose support for some kind of way to address this either with built-in semantic elements with sensible defaults or with `as` props to annotate each `Box`. 

@ericsoderberghp proposed this example

```jsx
const Header = props =>
  <Box as="header" direction="row" align="center" justify="between" gap="medium" {...props} />;
const NavBar = props =>
  <Box as="nav" direction="row" align="center" {...props} />;
const Nav = props =>
  <Box as="nav" {...props} />;
const Main = props =>
  <Box as="main" fill="vertical" overflow="auto" {...props} />;
const Footer = props =>
  <Box as="footer" direction="row" align="center" justify="between" gap="medium" {...props} />;
```

My opinion:

### Good Improvement

Grommet  provides an `as` prop and makes this value prefix styled component classNames. Sort of like an annotation.

### Better Improvement

Grommet provides `Header`, `NavBar`, `Nav`, `Main`, `Footer` components (and more) that already have sensible default styles/props and use the component names in the generated styled component classNames

**Comment by ShimiSun** [comment]
Thanks again for filing this issue! The components we agreed to implement are all up now. Feel free to shoot us more great ideas.

**Comment by iMerica** [comment]
👍
