### ISSUE TITLE
Property 'index' does not exist on type 'MouseEvent<Element, MouseEvent>'

### ISSUE THREAD

**Issue by dmitryrn** [grommet/grommet#3581]
Typescript error in "onClickItem" in https://storybook.grommet.io/?path=/story/list--selection `Property 'index' does not exist on type 'MouseEvent<Element, MouseEvent>'`.

As I can see from typings type of onClickItem is: `onClickItem?: (event: React.MouseEvent) => void;` and `React.MouseEvent` does not have `index`. And as I can guess you adding `index` prop on this event.

### Expected Behavior

No type error.

### Actual Behavior

Type error.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/25539852/70079494-ea584880-1615-11ea-81b6-bdae449784c5.png)

### Steps to Reproduce

Copy-paste example from [here](https://storybook.grommet.io/?path=/story/list--selection) to CRA with typescript.

### Your Environment

- Grommet version: ^2.8.1
- Browser Name and version: chrome 78.0.3904.108
- Operating System and version (desktop or mobile): mac

**Comment by ShimiSun** [comment]
Thank you for reporting, fixed and will be released on grommet 2.9.0.
