### ISSUE TITLE
Add hover property to Chart Legend

### ISSUE THREAD

**Issue by elronalds** [grommet/grommet#360]
When using the overlay legend position the legend is always docked to the important property when the chart first loads.  This blocks the initial view of chart data points.  Due to this we should add a property to the legend called hoverOverlay that only shows the chart legend when the data points are hovered.

**Comment by bryanjacquot** [comment]
@ericsoderberghp, please take a look at this issue and PR to consider along with the chart improvements underway.

**Comment by ericsoderberghp** [comment]
The new Chart interface separates the Legend out and leaves it up to the caller to position it around the chart as needed. There is no more overlaying of the Legend, partly due to the reason's indicated in this issue.
