### ISSUE TITLE
Checkboxes respond to clicks outside of visible area

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#3605]
## Summary

See below

![output](https://user-images.githubusercontent.com/487897/70382230-2d6c3180-191e-11ea-94ae-e1417ed9d0b7.gif)

### Expected Behavior

I expect this toggle checkbox to only respond when I click on the area

### Actual Behavior

The state changes even when a click occurs outside the visible area of the element.

### Steps to Reproduce

Add a checkbox with the following props:

```jsx
            <CheckBox
              toggle
              onChange={...}
              checked={currentLink['active']}
              label={'Active'}
            />
```

### Your Environment

- Grommet version: "grommet": "^2.8.1",
- Browser Name and version: Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- Desktop, macOS

**Comment by ShimiSun** [comment]
Hi buddy, can you share a codesandbox? I'm looking at https://storybook.grommet.io/?path=/story/checkbox--toggle and I don't see it reproducing.

**Comment by iMerica** [comment]
Here's a quick one that demonstrates the problem

https://codesandbox.io/s/grommet-v2-template-xnmqs

**Comment by IvanFrescas** [comment]
Hi, I think this can be solved if we add the width property with the value fit-content. 
Is it okay if I do a PR with this? 
<img width="510" alt="Screen Shot 2019-12-11 at 22 02 51" src="https://user-images.githubusercontent.com/16979749/70684265-cffc1b80-1c62-11ea-97c0-14babc316fb5.png">

**Comment by iMerica** [comment]
That would be great. Thanks @IvanFrescas  👍 .
