### ISSUE TITLE
Footer not present in package

### ISSUE THREAD

**Issue by Dirk-tooth** [grommet/grommet#3607]
In the documentation there is a `<Footer>` component but it does not appear in the distributed package anywhere and throws an error when I try to import it into my app.

### Expected Behavior

From the docs (https://v2.grommet.io/footer)

```
<Footer pad="small" background="light-4">
    Footer is a good place to place your content.
</Footer>
```
should exist and render a footer component. 

### Actual Behavior

Error in the terminal when using the footer component in my app:

```
./src/components/footer.js
Attempted import error: 'Footer' is not exported from 'grommet'.
```

My import:

```
import { Anchor, Box, Footer, Grommet, Text } from "grommet";
```

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/github/grommet/grommet-sandbox/tree/master/?fontsize=14&hidenavigation=1&theme=dark

This link throw a `Could not find the module ./src/Footer.js`

<img width="1439" alt="grommet-footer-issue" src="https://user-images.githubusercontent.com/3733140/70480201-802c2180-1ab5-11ea-922a-671d3ea4b12d.png">

### Steps to Reproduce

1. Import the footer component as per the documentation `import { Footer } from 'grommet';`
2. Use Footer component in your code: `<Footer>Footer Content Here</Footer>`
3. When you try to run your app you should get the same error as above.

### Your Environment

React (v16.12.0) web app build off create-react-app and grommet (v2.8.1)

- Grommet version: 2.8.1
- Browser Name and version: Chrome  v78.0.3904.108 
- Operating System and version (desktop or mobile): macOS Mojave v10.14.6

**Comment by ShimiSun** [comment]
Hi buddy, Footer, Header & Main have been introduced less than a week ago and weren't officially released yet, they will be available on the upcoming 2.9.0 release

**Comment by Dirk-tooth** [comment]
@ShimiSun, Awesome, looking forward to seeing them implemented! When you you plan you have the 2.9.0 release available?

**Comment by ShimiSun** [comment]
@Dirk-tooth by the end of week :)

**Comment by Dirk-tooth** [comment]
oh AWESOME! y'all rock, thanks! looking forward to it and loving grommet so far!
