### ISSUE TITLE
Calendar traps keyboard users

### ISSUE THREAD

**Issue by DAnselC** [grommet/grommet#3609]
### Expected Behavior

My personal opinion is that tabbing once into the calendar sets focus on the calendar, and then from there the arrow keys navigate through days. A second tab should then tab the keyboard user out of the calendar.
However, minimal expected behavior is that there should be _a_ way to get out of the calendar with a keyboard.

### Actual Behavior

Currently, once you start tabbing into the days of the calendar, you're basically trapped inside the calendar with no way to navigate outside of the calendar, as the tab key also navigates between days, and tabbing to the next month's days switches months, essentially trapping a keyboard user. While it definitely could be fixed by passing in the showAdjacentDays={false} prop, this kind of doesn't look that great if you don't have a transparent background, as the height doesn't decrease when hiding adjacent days.

### URL, screen shot, or Codepen exhibiting the issue
Below is a gif of being stuck in the calendar pressing tab:
![trappedInTheCalendar](https://user-images.githubusercontent.com/16843726/70577134-2fc5ca00-1b70-11ea-8e3c-5c258e310b42.gif)

Below is an image of the calendar with showAdjacentDays set to false, with the height not adjusting:
![image (1)](https://user-images.githubusercontent.com/16843726/70577151-3b18f580-1b70-11ea-9c91-86be62fec50a.png)

Here's a Codesandbox demonstrating the issue: https://codesandbox.io/s/pedantic-zhukovsky-5fhk6?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce

1. Tab into the Calendar 
2. Tab through the days 
3. Try and tab to the button below the calendar (in my codesandbox)

### Your Environment

- Grommet version: 2.8.1
- Browser Name and version: Chrome version 78.0.3904.108
- Operating System and version (desktop or mobile): Windows desktop

**Comment by juanlanus** [comment]
I have a loosely related issue with the calendar focus.  
In my UI the calendar is hidden, and shows upon click on a calendar icon (same action closes it).  
I would like the user to be able to close it with Esc, but for this to happen the calendar should be focused. 
AFAIK there is no way to give focus to the internal Calendar artifacts. 
This is the opposite problem: my user is trapped _outside_ of Calendar. 
She could focus the month buttons with tab, but this is a usability glitch, a hack that it's not fair ti adk her to find.

**Comment by IanKBovard** [comment]
i believe we can close this issue if it has been solved with #3692

**Comment by DAnselC** [comment]
Sweet! Glad this is fixed 😄
