### ISSUE TITLE
Box `border` is missing boolean value on docs

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#3611]
`<Box border />` is a valid usage yet not documented. `border="true"` will apply borders to all sides. 
https://v2.grommet.io/box?c=DwIQ9gHgUABDAmBLATgUwMYBdFgHYF4AiZMAd0NjiuuoCMxl5VlKAHAQ3iIFtUkBXbhQB8lUJBgcuhAM7d2AGwWEYtdugDWAcxL9c0+O2QaAtAGYVAelFxxESZx59EglWs06we6QsRaAFpjmVqLAluAQwkA#border

**Comment by joybhallaa** [comment]
Can I work on this ?

**Comment by ShimiSun** [comment]
@joybhallaa absolutely!

**Comment by mauriceLC92** [comment]
@ShimiSun I created a PR for this issue: https://github.com/grommet/grommet/pull/3727
Could you or someone perhaps tell me if I am on the correct track or if more needs to be done with regards to the docs on the site

@joybhallaa I hope you do not mind but I opened a PR for this -  perhaps you could help me get it over the line with any suggestions If I missed something

**Comment by joybhallaa** [comment]
@mauriceLC92 , I don't mind!

**Comment by ShimiSun** [comment]
This issue is actually easier than it looks and no changes should be done on Grommet, we should just improve the docs on the grommet-site to include the boolean values. 
The fix should be placed on the site https://github.com/grommet/grommet-site/blob/fabcdd2239f2f1392c199553c90e8b6b01368cb0/src/screens/Box.js#L94

Any takers?
