### ISSUE TITLE
Improve Chart Legend UI

### ISSUE THREAD

**Issue by elronalds** [grommet/grommet#362]
It would be a nice enhancement if the chart legend didn't block most of the chart.  The showcase shows a good solution to this issue, where a tooltip could be shown at the top of the chart and doesn't block the actual chart data points, as shown below.  This could be more aligned to the top of the chart though.

![image](https://cloud.githubusercontent.com/assets/1728513/12817510/1f77c8ea-cb9e-11e5-9146-93823348e252.png)

I believe that this would improve the overall user experience of the chart control when using the overlay legend combined with the hoverOnly property in PR #361.  Thoughts?

**Comment by bryanjacquot** [comment]
@elronalds we've found this example works well when the data point is in the lower 2/3 of the graph, but when values reach the top of the graph, they extend beyond the top of the graph which could be near the top of the page.  So we're left asking if we pad graphs on the tap to account for this.  Hence our current direction.  We continue to make improvements in this area, but in the example here, there are cases it doesn't always work well.

**Comment by elronalds** [comment]
@bryanjacquot If the chart is at the top of the page then couldn't the tooltip just be shown extending down at the bottom of the chart.  Just like how the legend tooltip changes left/right directions at the moment?  I think showing the legend outside the graph area is the way to go forward.

**Comment by bryanjacquot** [comment]
The new charting component now displays the legend and current value outside the graph area.
