### ISSUE TITLE
Right to left support in Grommet 2

### ISSUE THREAD

**Issue by abishekram** [grommet/grommet#3621]
Is right to left supported in Grommet 2 ?

**Comment by ShimiSun** [comment]
Unfortunately, it does not.

**Comment by ShimiSun** [comment]
#3271

**Comment by ericsoderberghp** [comment]
Actually, if you use `<Grommet dir="rtl" />`, it should work. Flexbox rows are flipped, text is right aligned everywhere, etc. We haven't done exhaustive testing of it, so we'd be interested in hearing anything still needed to improve on it.

**Comment by IanKBovard** [comment]
if #3629 solves this issue, i believe we can close this.

**Comment by ShimiSun** [comment]
I am ok closing this one, @abishekram feel free to provide feedback from your experience and file a new issue if something comes up. THANK you for asking and encouraging us to extend the functionality.
