### ISSUE TITLE
Layer component leaving container div in document

### ISSUE THREAD

**Issue by dstordy** [grommet/grommet#3623]
The element `layerContainer` is never removed from the document in `Layer`.
This leaves many `div` elements in the `body` node.
It looks as if when animate on exit behaviour was added in #3307 the portal's container is no longer being removed after the clone for animation.
This also seems to impact the refactor #3520.

### Expected Behavior

The `body` node is left in a 'clean' state when the `Layer` component is unmounted.

### Actual Behavior

Empty `div` element is left on the `body` node.

### URL, screen shot, or Codepen exhibiting the issue

Issue is seen when inspecting the storybook:
https://storybook.grommet.io/?path=/story/layer--center

### Steps to Reproduce

1. Open a `Layer` component
2. Close the component.

**Comment by IanKBovard** [comment]
I can confirm this.
When opening and closing layer.
![Kapture 2020-01-31 at 9 48 13](https://user-images.githubusercontent.com/21990914/73553018-d7dc6e80-440e-11ea-95a1-af7080fb4dd3.gif)

**Comment by ShimiSun** [comment]
Issue fixed, thanks @IanKBovard for fixing and @dstordy for reporting.
