### ISSUE TITLE
Missing Documentation: Schema Definition for theme objects.

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#3631]
## Summary
One pain point I encounter is the schema of a Grommet theme. If someone who has intimate understanding of this schema could add a dedicated page in https://v2.grommet.io/components, it would be really helpful. I would add it myself, but themes are a black box right now.

## Example
Currently in dark mode my `<Tabs/>` have active colors and inactive colors. How do I change these colors? The [tab theme documentation](https://v2.grommet.io/tabs#theme) says the color is controlled in `tab.active`, however all of the override examples in the StoryBook nest overrides within `global` so is it `global.tab.active`? Also, what about the inactive color?

More questions: 
- Do I have to use deepMerge like all of the StoryBook examples do? Why can't I use spread syntax?
- What is `global`?
- How come some colors are nested under global.colors and some are under specific namespaces?

## Proposal
Add a page to https://v2.grommet.io/ that shows up in search results for "Theme". This page can be the schema definition for themes and some discussion for how to override a theme, create brand new themes, conventions used and any general advice.

**Comment by ShimiSun** [comment]
Lots of great questions here, I agree we need to improve the documentation, and we are currently running user-testing research to see how this information could be documented efficiently. 
In the meanwhile check out the following resources:
https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation
https://github.com/grommet/grommet/wiki/Color-Properties
And theme-builder tool 
https://theme-designer.grommet.io/Dashboard

**Comment by jcfilben** [comment]
A page has been added to the Grommet site that documents all of the global theme properties (component theme properties are documented on the individual component pages). The global theme props page gives a brief explanation of global theme props and links to our theming wiki page for more info. Let us know if we missed anything or could make any additional improvements.

Link to global theme prop documentation on grommet site: https://v2.grommet.io/globaltheme
