### ISSUE TITLE
UX: Active vs inactive tab colors are inverted. 

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#3633]
## Background
One of my beta testers pointed out how confusing the tabs are due to the choice of colors used in inactive vs active tabs. At first I thought it was a bug in my code, but the issue also occurs on the grommet documentation site, so it appears to be a bug.

![tabs-bug](https://user-images.githubusercontent.com/487897/71312522-94dfb200-23f1-11ea-96e3-098e594770db.gif)

Notice how the "active" tab switches to black, the same color as the text. There is nothing domimant and active about black text and a black underline beside a tab of accented text and a accented underline.

### Expected Behavior
As a user, when I click on a tab, the active color should change to something unmistakably and obviously active and all inactive tabs should look inactive.

Examples in popular component libraries
### Bootstrap
![Screen Shot 2019-12-21 at 12 56 53 PM](https://user-images.githubusercontent.com/487897/71312592-47177980-23f2-11ea-9cc8-930d23e3a5b4.png)

## Semantic
![Screen Shot 2019-12-21 at 1 00 49 PM](https://user-images.githubusercontent.com/487897/71312595-51397800-23f2-11ea-918b-1daed27ff321.png)

## Material UI
![Screen Shot 2019-12-21 at 1 04 57 PM](https://user-images.githubusercontent.com/487897/71312620-85149d80-23f2-11ea-9d18-35d086001faa.png)

### Actual Behavior

Confusion about which tab is actually active.

### Steps to Reproduce

- View the tab docs and toggle between the two tabs.

### Your Environment

- Grommet version: 2.9.0
- Browser Name and version: All
- Operating System and version (desktop or mobile): macOS

**Comment by iMerica** [comment]
### Temporary Workaround

Add a `.tab` class to the `<Tab/>` component

```jsx
<Tab
  className={'tab'}
  focusIndicator={false}
  title={'XXXXXXXXX'}>
  // Content
</Tab>
```
and drop in these styles to your stylesheet

```css
.tab[aria-expanded="true"] > div {
  border-bottom: solid 2px #FD6FFF
}

.tab[aria-expanded="false"] > div {
  border-bottom: solid 2px #021734
}

.tab[aria-expanded="false"] span  {
  color: #021734;
}
```

### Demo

![workaround](https://user-images.githubusercontent.com/487897/71313973-615b5280-2406-11ea-875d-240b665fdc1c.gif)


YMMV.

**Comment by ShimiSun** [comment]
A good design discussion.

**Comment by IanKBovard** [comment]
@ShimiSun Have you come to a conlcusion about this issue? I agree that it's a worthwhile enhancement, and could take a look at it.

**Comment by IanKBovard** [comment]
Any updates on the discussion regarding this issue? I assume this would cause a lot of backwards compatibility issues with people who use theme to adjust the active coloring for tabs, or just the default styling. Since, a lot of this can be customized with theme, and we have an example of that, I believe we can close this issue in favor of the theme approach.

https://storybook.grommet.io/?path=/story/tabs--custom-theme

**Comment by jcfilben** [comment]
Closing in favor of https://github.com/grommet/hpe-design-system/issues/2151

**Comment by jcfilben** [comment]
Re-opening since https://github.com/grommet/hpe-design-system/issues/2151 is only related to tabs styling in the hpe-theme, we need a separate issue to track this issue for the grommet theme

**Comment by jcfilben** [comment]
Closing, after discussing we felt that since we allow the caller to change the active and inactive tab styling as they see fit using `tab.active.color` and `tab.color`, we don't need to change the current default behavior.
