### ISSUE TITLE
Dom is not removed when unmounting for Layer components

### ISSUE THREAD

**Issue by mateeyow** [grommet/grommet#3634]
This might be related to issue #3623.

So I created a `Modal` component that accepts a props of boolean. If props is false the component will not render anything, if props is true it should render the `Layer` component along with its children.

Upon running the test with props to true, the test will pass correctly. But, upon adding a second test to check if the Modal component renders - it fails.

### Expected Behavior

Test should pass and should not see the `Modal` component on the DOM.

### Actual Behavior

Tests fails if the previous.

### URL, screen shot, or Codepen exhibiting the issue

You can check the repository [here](https://github.com/mateeyow/failing-test)

OR just add this code.

```js
// Modal.js
import React from 'react'

const Modal = ({ isOpen = false }) => {
  if (!isOpen) { return null; }

  return (
    <div data-testid='modal'>
      <span>You should see this</span>
    </div>
  )
}

export default Modal

// ModalSpec.js
import React from 'react'
import { render, cleanup } from '@testing-library/react'
import Modal from '../Modal'

describe('#Modal', () => {
  afterEach(cleanup)

  it('should be able to see the modal', () => {
    const { getByTestId } = render(<Modal isOpen={true} />)

    expect(getByTestId('modal')).toBeInTheDocument();
  })

  it('should not be able to see the modal', () => {
    const { queryByTestId } = render(<Modal isOpen={false} />)

    expect(queryByTestId('modal')).not.toBeInTheDocument()
  })
})
```
### Steps to Reproduce

1. Clone the repository
2. Run `yarn`
3. Run `yarn test`

### Your Environment

- Grommet version: ^2.9.0
- Browser Name and version: Terminal
- Operating System and version (desktop or mobile): MacOS Mojave (10.14.6)

**Comment by IanKBovard** [comment]
It looks like layer is removed from the dom after it's animation is complete.
Adding this
```
    setTimeout(
      () => expect(queryByTestId("modal")).not.toBeInTheDocument(),
      1000
    );
```
causes the test to pass.

**Comment by ShimiSun** [comment]
@mateeyow can you please check out @IanKBovard suggested solution? I don't think there is an additional work from the grommet side for this matter, let us know what you think.

**Comment by mateeyow** [comment]
But it was working before, and suddenly it does not work.

**Comment by ShimiSun** [comment]
@mateeyow can you share a code example (codesandbox) we could work with?

**Comment by IanKBovard** [comment]
@mateeyow The reason your tests fail is because, due to a previous PR, layer now unmounts when the animation completes. You tests do not account for the time of the animation. When you factor that into your tests they pass. A quick way to do that would be to add a setTimeout() to the test that checks if the layer has unmounted.

If, however, you are still unable to get them to pass, please send an example so that we can work it out.

**Comment by IanKBovard** [comment]
@mateeyow Is there anything else that you'd like to add before we close this issue?

**Comment by mateeyow** [comment]
Hi @IanKBovard sorry for the late response as I was out for vacation. Anyway, I can add `setTimeout` and it works but it just feels icky to me that we need to add these "hacks" just for the layer to unmount completely. But I'm happy to close this issue. Thanks!

**Comment by IanKBovard** [comment]
@mateeyow You misunderstand. The layer unmounts without you adding setTimeout. It's your tests that are the issue. The layer will unmount after it's finished with it's transition animation. Your tests did not account for that, giving you a false negative.

**Comment by mateeyow** [comment]
@IanKBovard what I'm meaning to say is that previously before the changes were introduced to the layer component I had a running tests for my custom components and everything was passing. I did not have to add the setTimeout or have to do anything. It just baffles me why we need to check for the transition to finish just to make the tests pass.

**Comment by ShimiSun** [comment]
@mateeyow  this issue is addressed on https://github.com/grommet/grommet/pull/3737, thank you for reporting.

**Comment by mateeyow** [comment]
@ShimiSun thank you.
