### ISSUE TITLE
Select dropdown options become empty while in a scrollable modal due to InfiniteScroll

### ISSUE THREAD

**Issue by aga5tya** [grommet/grommet#3636]
### Expected Behavior
Select dropdown with search enabled becomes empty when its placed in a Layer that has scroll in it and body has scroll enabled.

### Actual Behavior
Select dropdown with search enabled and placed inside a modal with fewer options that results in no scroll, InfiniteScroll.js seems to compute **nextBeginPage** & **nextEndPage** to be same (1 in my case) which results in array slicing to be off and becomes empty array. 

- Grommet version: v2.9.0
- Browser Name and version: Chrome latest

**Comment by IanKBovard** [comment]
@aga5tya Could you give me an example I can toy around with. Just want to make sure I understand what this issue is.

**Comment by ShimiSun** [comment]
We no longer seem to be able to reproduce this issue, feel free to reopen and file an issue that we can reproduce & investigate, thank you all for your cooperation.
