### ISSUE TITLE
A row-responsive Box of buttons overflows before changing directions

### ISSUE THREAD

**Issue by blakehilliard** [grommet/grommet#3641]
If I fill a row-responsive Box with buttons, they will horizontally overflow quite a bit before their direction changes from row to column.

### Expected Behavior

No overflow should occur.

### Actual Behavior

Overflow does occur.

### URL, screen shot, or Codepen exhibiting the issue

Codepen: https://codesandbox.io/s/grommet-row-responsive-buttons-g7s0b

Screen shot from the code pen:
![grommet-row-responsive-buttons](https://user-images.githubusercontent.com/25166376/71697159-be4af700-2d7c-11ea-9c4b-d80f726ecd69.png)

### Steps to Reproduce

Open the codepen above.

### Your Environment

- Grommet version: 2.9.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by sivakar12** [comment]
Wouldn’t giving the Box a wrap prop solve this issue?

**Comment by IanKBovard** [comment]
@blakehilliard have you tried using the solution provided by sivakar12?

**Comment by ShimiSun** [comment]
@blakehilliard any updates?

**Comment by blakehilliard** [comment]
Yes that does work around it.

**Comment by blakehilliard** [comment]
I'm concerned that issues are being closed simply because they can be worked around, even though they really are issues. If I don't specify `wrap`, the buttons _do_ wrap, just not consistently. And if I use boxes in place of buttons, they consistently wrap and never overflow. Is this _really_ the correct behavior of `direction="row-responsive"`? To have the actual responsiveness work "kind of" for _some_ child components?

**Comment by ShimiSun** [comment]
Thank you for raising your concern, I do not think that using `wrap` is a workaround, it is the intent of the prop and its functionality, see docs https://v2.grommet.io/box#wrap
I will agree that there is a room for discussion on maybe 'row-responsive' should automatically apply a wrap, which might be a breaking change for some users, but I'm opened to discussion if anyone has other ideas.
