### ISSUE TITLE
Box gap is applied to a layer inside the box

### ISSUE THREAD

**Issue by blakehilliard** [grommet/grommet#3645]
When you render a layer inside a Box that has a gap set, extra gap is added for the layer even though the layer is not actually rendered inside the box.

### Expected Behavior

The Box the layer pops up from should not be affected by the presence of a layer.

### Actual Behavior

An extra gap is added, which shifts other components around when you open or close the layer.

### URL, screen shot, or Codepen exhibiting the issue

Codepen: https://codesandbox.io/s/grommet-layer-gap-rbcrv

### Steps to Reproduce

Open the codepen above. Make sure you widen your browser enough that the layer does not fill the entire screen. Then open the layer. Notice the extra gap in between "Hello" and "World".

### Your Environment

- Grommet version: 2.9.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by IanKBovard** [comment]
@blakehilliard It might look strange, but gap is working as intended. It is being applied to all children in the box, and since layer is a child of the box it receives a gap. To avoid this move the layer outside.
```
const App = () => {
  const [openLayer, setOpenLayer] = React.useState(false);
  return (
    <Grommet>
      <Box border gap="medium">
        <Box border>Hello</Box>
        {/* layer should not be rendered here */}
        <Box border>World</Box>
        <Button label="Toggle layer" onClick={() => setOpenLayer(!openLayer)} />
      </Box>
      {/* layer is outside, no gap issue */}
      {openLayer && (
        <Layer onClickOutside={() => setOpenLayer(false)}>I am a layer.</Layer>
      )}
    </Grommet>
  );
};
```

**Comment by blakehilliard** [comment]
@IanKBovard Is the recommendation to always place a `Layer` directly under `Grommet` then? I have components that can pop up layers, and it's nice to just be able to place the Layer in that component without regard for what is using that component, rather than have to add some hook at a higher level to make it place the layer outside the component.

Maybe I'm missing something fundamental about Layers: what is the significance supposed to be of where they are declared?

**Comment by IanKBovard** [comment]
@blakehilliard Check the example more carefully. Layer is still rendered in grommet, just, in this example, outside of the box applying gap. You don't have to place the layer outside of the component, just on the same level as it if you don't want some styles to be passed down. This isn't exclusive to layers or grommet.
```
<Box> //layout
  <Box styles here won't pass down to layer>
    // content
  <Box>
  {layer}
<Box>
```

**Comment by blakehilliard** [comment]
Thanks, I'll do it that way with an extra `<Box>` around my component.

I'm fine with closing the issue if this really is the desired behavior. But I still don't understand why it'd ever be the desired behavior to have a `gap` apply to a Layer. It seems all upside and no downside to just make Layers be an exception when it comes to apply a gap.

**Comment by ShimiSun** [comment]
@blakehilliard We wouldn't want to exclude behaviors that break consistency, hence the `gap` is applied to all child components without exceptions. Thank you for reporting and sharing your feedback.
