### ISSUE TITLE
Grid - adding props from Box (`border` and `pad`)

### ISSUE THREAD

**Issue by skoshy** [grommet/grommet#3654]
### Expected Behavior

`Grid`s would have similar props to `Box`

### Actual Behavior

`Box` has many more stylistic props than `Grid`

### Reasoning

As `Grid`s and `Box`es are both used for basic layouting often, it could be beneficial to add similar stylistic props to `Grid`.

Currently focusing on `border` and `pad` before considering other props

See this Slack thread for more info - https://grommet.slack.com/archives/C04LMHN59/p1578672831048600

**Comment by ShimiSun** [comment]
Linking to #3750

**Comment by ShimiSun** [comment]
@skoshy can you please clarify what `border` would do? would you want it only on the outer Grid or in between rows and columns as well?

**Comment by skoshy** [comment]
I was thinking the outer border only, to keep it consistent with how border would work if applied with css to a grid element and also with how border works in `Box`. Inner borders could be a separate prop if deemed necessary?

**Comment by srallen** [comment]
I just ran into this trying to apply an outer border to a `Grid` and discovering that it is not supported at the moment. I would also expect that `border` when applied to `Grid` functioned like it does with `Box`

**Comment by ShimiSun** [comment]
@srallen I'm supportive, feel free to work on a contribution.

**Comment by srallen** [comment]
@ShimiSun I'm hoping to participate in Hacktoberfest more broadly this year, so I'll have a look! 😄

**Comment by jcfilben** [comment]
I think this issue can be closed, Grid now has both `border` and `pad` props available

**Comment by ShimiSun** [comment]
Thank you @jcfilben !
