### ISSUE TITLE
Redux-Form validate getting passed undefined on submit

### ISSUE THREAD

**Issue by pbenmoser4** [grommet/grommet#3655]
I'm trying to use redux-form with Grommet, and for some reason my validate function is getting passed "undefined" on submit. The function is getting passed the correct values whenever a change is made to one of my inputs. 

Validate should be passed the same data on submit that it is passed whenever the form input is changed.

Validate is passed undefined.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-jhb1f?fontsize=14&hidenavigation=1&theme=dark

### Steps to Reproduce

1. Open Console in order to register console.log statements
2. Type input into form field, and see the log statements originating from the `validate` function
3. Click "submit"
4. Logs show two different values for "formValues", one registered in the `validate` function (undefined) and one registered in the `onSubmit` function (accurate)

### Your Environment

- Grommet version: 2.9.0
- Browser Name and version: Chrome Version 79.0.3945.79 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): MacOS Mojave 10.14.6

**Comment by ShimiSun** [comment]
I still see this behavior on grommet 2.12.0.

**Comment by crashuniverse** [comment]
Your codesandbox example is [missing (see doc here)](https://redux-form.com/8.3.0/docs/api/field.md/#-code-validate-array-lt-function-gt-value-allvalues-props-name-gt-error-code-optional-) a `validate` prop for `Field` component. Once we put that in, values are consistent. Result: https://i2lgec.csb.app/ Forked sandbox: https://codesandbox.io/s/grommet-v2-template-forked-i2lgec?file=/NewReading.js

Can you please verify this @pbenmoser4 if we got this right? I know it has been a bit longer, yet just for our curiosity now yeah.

**Comment by jcfilben** [comment]
Thanks for looking into this and sharing a solution @crashuniverse! 
Looking at the codesandbox this appears to solve the issue. @pbenmoser4 I'm going to mark this as closed but feel free to comment and re-open if needed.
