### ISSUE TITLE
Placeholder in TextInput does not disappear if I use a react node instead of a string

### ISSUE THREAD

**Issue by c3s4** [grommet/grommet#3657]
If in a TextInput I use a react node as placeholder, the placeholder itself does not disappear when I write something inside the input text.

https://codesandbox.io/s/placeholder-does-not-disappear-w41o5

**Comment by thaydds** [comment]
i just have finished and soon i'm going to open a PR!!!

**Comment by ShimiSun** [comment]
Fixed and will be available on our next release!
