### ISSUE TITLE
Chart smoothing algorithm issue

### ISSUE THREAD

**Issue by elronalds** [grommet/grommet#366]
There seems to be an issue with the chart smoothing algorithm for line and area charts as shown below:

![image](https://cloud.githubusercontent.com/assets/1728513/12837387/f85c69ee-cc0d-11e5-83ae-b6a90e0df5d3.png)

There is three data points at the start of this chart with values 0, 9, 11 and between the 9 and 11 data points there is a dimple in the chart smoothing that shouldn't be there.

**Comment by ericsoderberghp** [comment]
Adjusted smoothing algorithm a bit in e250f5c2610ffadb1367aabdcc43ce65fab54a0d.
