### ISSUE TITLE
Clock onChange called with non-changing time

### ISSUE THREAD

**Issue by standamo** [grommet/grommet#3662]
When using the below, the time printed is not changing:
```
<Clock type="digital"  onChange={t => console.log(t)} />
```

### Expected Behavior

Time should increment on every printout

### Actual Behavior

Startup time is printed over and over again.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-sandbox-0e6bh
https://0e6bh.csb.app/clock

### Steps to Reproduce

Run the above code and check console

### Your Environment

- Grommet version: 2.9.0
- Browser Name and version: Chrome (latest), FF (latest)
- Operating System and version (desktop or mobile): Win10

### Possible fix

Changed run() of Clock to fix:
```
      this.setState({ elements: nextElements }, () => {
        if (onChange) {
          if (elements.duration) {
            onChange(
              `P${nextElements.hours}H${nextElements.minutes}M${nextElements.seconds}S`,
            );
          } else {
            onChange(
              `T${nextElements.hours}:${nextElements.minutes}:${nextElements.seconds}`,
            );
          }
        }
```

**Comment by ShimiSun** [comment]
The fix for this issue is merged and will be available on our next release. Thank you for reporting
