### ISSUE TITLE
Select component flashes when having random length options

### ISSUE THREAD

**Issue by yoomury** [grommet/grommet#3665]
Hey, I found a pretty weird behaviour on the *Select* component. My use case randomly has *82* elements in the options array and apparently this causes some weird flashes if you scroll really fast to the bottom. If you change the array to has *80* or *100* elements, everything is fine.

### Expected Behavior

Select component works fine.
### Actual Behavior

Select component has some weird flashes if you use some randomly length arrays. 

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/elegant-tesla-hjipo

### Steps to Reproduce

1.  Scroll fast to the bottom of the options

**Comment by IanKBovard** [comment]
@yoomury This _**is**_ strange! Checking it out now. It looks like there some extra length at the bottom of the list.

**Comment by IanKBovard** [comment]
![Screen Shot 2020-01-29 at 12 52 17 PM](https://user-images.githubusercontent.com/21990914/73387441-3205f400-4296-11ea-892b-9ef6d877b733.png)

This div constantly resizing from 0 height to its original height when it should stay at 0 is causing the flashing.

![Kapture 2020-01-29 at 13 01 13](https://user-images.githubusercontent.com/21990914/73388247-7f369580-4297-11ea-975b-5b0910335398.gif)

**Comment by anoopadvaitha** [comment]
Facing same issue. If the length of the object is more than 100 it seems to be working fine.

**Comment by christophrath** [comment]
Facing the same issue here. actually dropdown must be higher than viewport for reproducing that issue

**Comment by ShimiSun** [comment]
Thanks for reporting @christophrath

**Comment by ShimiSun** [comment]
The fix will be available on our next release. thank you all for reporting and @IanKBovard for fixing!
