### ISSUE TITLE
Styles and ClassName props ignored by Select component.

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#3677]
For 99% of my grommet style overrides I use either SCSS or inline styles (so called 'JSS'), not the Grommet theme system. The box and button components allow me to do this as one would expect, but the Select component seems to completely ignore these props.

### Expected Behavior

I expect Select components to honor `style` and `className` props, but at a minimum at least one of them. 

### Actual Behavior
Select ignores style and className props

### Steps to Reproduce

- Add style or className props to Select.
- Observe they are ignored.

### Environment

Grommet version: 2.9.0

**Comment by thaydds** [comment]
hi IMerica,
i tryed to reproduce the same behavior as you say but style props works nice for me.

my test:
https://codesandbox.io/s/hardcore-bell-j3o7b?fontsize=14&hidenavigation=1&theme=dark

if i don't test it right, could you try to reproduce this behavior for me in codesanbox?

tnks.

**Comment by Bahlaouane-Hamza** [comment]
Does it work if you wrap your select in a Styled Box and target the <select> element from it ?

**Comment by IanKBovard** [comment]
@iMerica Can you share an example of the issue? I am able to give select a class name and use inline styles.

**Comment by iMerica** [comment]
Demo of the bug:

https://codesandbox.io/s/epic-easley-ky76t

**Comment by IanKBovard** [comment]
I'm not sure I understand the problem correctly. I don't see a Select component in the example, just this block.
```
    <div className="App">
      <Grommet>
        <Header pad="medium">
          <Box direction="row" align="center" gap="small">
            <Menu />
          </Box>
        </Header>
      </Grommet>
    </div>
```

**Comment by IanKBovard** [comment]
@iMerica Just checking in to see if you can clarify this issue for me. The example you provided does not have your issue present, and I am able to give the select component a class name and inline styles.

**Comment by IanKBovard** [comment]
Here is an example and a few screenshots
https://codesandbox.io/s/cranky-pond-iwvzu?fontsize=14&hidenavigation=1&theme=dark
![Screen Shot 2020-02-20 at 11 56 45 AM](https://user-images.githubusercontent.com/21990914/74963976-3a0a0d00-53d8-11ea-8eb8-9613d24b74a2.png)
![Screen Shot 2020-02-20 at 11 56 38 AM](https://user-images.githubusercontent.com/21990914/74963982-3bd3d080-53d8-11ea-9523-ea8ead36fc1e.png)

**Comment by iMerica** [comment]
Apologies, I assume I was doing something wrong then. Thank you for looking into it.
