### ISSUE TITLE
Missing documentation: Select Options Schema 

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#3679]
There is no guidance on how to pass an array of objects to the Select component, just that it accepts `[]object`

### Expected Behavior

If a component accepts an array of objects, I expect to see the exact shape/schema of the object.

### Actual Behavior

There is no documentation on the shape of the data when accepting an array of objects. I glanced at the story books and didn't see any there either.

**Comment by thaydds** [comment]
nice point.

select docs says:

> Options can be either a string or an object. If an object is used, use
>  children callback in order to render anything based on the current item.

i dont know what children callback means.

so, i found a solution if you want to use an array of object.
you need to use a labelKey tag to especify what key of your objects will be an options.

i can create a storybook for this.

**Comment by ShimiSun** [comment]
@thaydds feel free to share a storybook example.

**Comment by ShimiSun** [comment]
Since @thaydds was awesome enough to contribute an example here, I think we are good, thanks for reporting.
