### ISSUE TITLE
Theme object

### ISSUE THREAD

**Issue by arman94** [grommet/grommet#3690]
would you please, for the god sake explain how can I completely change the style object??
I've done lots of searches and i found no result.

**Comment by ShimiSun** [comment]
hi buddy, are you a member of our Slack channel? https://slackin.grommet.io/
You can find lots of conversations and examples there.

In addition, you might find the below helpful:
https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation
A custome Theme example on Select component:
https://storybook.grommet.io/?path=/story/select--custom-theme

**Comment by ShimiSun** [comment]
@arman94 anything else we can help with?

**Comment by arman94** [comment]
> @arman94 anything else we can help with?
Thanks a lot for your guide, I couldn't find anything about the theme through the net.

**Comment by arman94** [comment]
> @arman94 anything else we can help with?

Thanks a lot for your guide

**Comment by ShimiSun** [comment]
No worries, I'll be closing the issue, feel free to join our slack community for more directions and issues.
