### ISSUE TITLE
<Nav> component breaking app

### ISSUE THREAD

**Issue by whoisryosuke** [grommet/grommet#3717]
### Expected Behavior

[Copied example from Storybook](https://storybook.grommet.io/?path=/story/nav--sidebar) into another responsive example from the repo (the responsive app layout example). 

Expected to see the Sidebar similar to Storybook example.

### Actual Behavior

App crashes. Displays error saying that component isn't defined.

```
Invariant Violation
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Sidebar`.
```

If I remove the `<Nav>` component from the `<Sidebar>` component I created to encapsulate the Storybook example, it works. You can test this yourself quickly by replacing the Sidebar import with an import for `{ SidebarWorking }`.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-nav-issue-1r4i0

### Steps to Reproduce

1. Fork my [Grommet Starter](https://codesandbox.io/s/grommet-starter-68gby) on CodeSandbox
2. Create a new component for the sidebar: `./components/Sidebar.tsx`
3. [Paste example into it](https://storybook.grommet.io/?path=/story/nav--sidebar) without the Grommet wrapper (since app already has it).
4. Import and use Sidebar component in app: `./index.tsx`

### Your Environment

- Grommet version: v2.9.0
- Browser Name and version: Chrome 79.0.3945.117
- Operating System and version (desktop or mobile):  MacOS 10.13.6  - Desktop

**Comment by sivakar12** [comment]
Nav component isn't there in version 2.9

**Comment by ShimiSun** [comment]
@sivakar12 you are correct my friend. I've upgraded the grommet version on the sandbox above to 2.10. and it all renders as expected. https://codesandbox.io/s/grommet-nav-issue-d7ulz
Closing the issue.
