### ISSUE TITLE
Responsive Context doesn't display outside render

### ISSUE THREAD

**Issue by whoisryosuke** [grommet/grommet#3718]
### Expected Behavior

Copied example from [ResponsiveContext docs](https://v2.grommet.io/responsivecontext) and tried to use the context outside the render scope. 

Expected the context to work outside of render scope. I should be able to check what the initial size of the browser is, maybe not directly, but inside a layout effect (where the DOM is loaded and parsable). Allows me to hide/show sidebar using component state based on the size of the browser on load (rather than reacting to it on render, which can conflict with default state).

### Actual Behavior

Context displays `undefined` outside of render scope.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-responsive-context-issue-jb7p5

### Steps to Reproduce

1. Create sample Grommet app
2. Attempt to use context inside a functional component, but before/outside render scope:

```js
  const size = React.useContext(ResponsiveContext);

  React.useEffect(() => console.log("the size after DOM (using Effect)", size));
  React.useLayoutEffect(() =>
    console.log("the size (using LayoutEffect)", size)
  );

  console.log("responsive size is ", size);
```

### Your Environment

- Grommet version: v2.9.0
- Browser Name and version: Chrome 79.0.3945.117
- Operating System and version (desktop or mobile):  MacOS 10.13.6  - Desktop

**Comment by ShimiSun** [comment]
>Expected the context to work outside of render scope

If you are not using hooks, such as the example provided on the codesandbox you shared, you shouldn't make this type of assumption. `size` value would be initialized inside the context of <ResponsiveContext>.

If you are using hooks you have a better chance to get the value before the `return`, but you need to make sure you are not using the `useContext` inside a Component Class, and I'm clarifying on this matter since you mentioned you are using the `render` function.

**Comment by Bahlaouane-Hamza** [comment]
Here is how i would do it.
https://codesandbox.io/s/grommet-responsive-context-issue-dy96c

Grommet has not being initialized at the moment you call useContext, so the responsive context did not get any update yet.

**Comment by IanKBovard** [comment]
@whoisryosuke were Bahlaouane-Hamza and ShimiSun able to answer your question? This seems to be an issue with implementation.

**Comment by ShimiSun** [comment]
I think we are ok closing this issue, feel free to re-open or file a new issue if any need arises.
