### ISSUE TITLE
Ability to overwrite onSort in DataTables

### ISSUE THREAD

**Issue by francescodist** [grommet/grommet#3728]
As for the `onSearch` method I would like to be able to pass a method to the `onSort` property that, when defined, will overwrite the default behaviour for sorting. 
### Expected Behavior
The property would be used to just send to callback from the parent the property and direction (basically the current sort configuration) without making any change to the data in the table. This way the developer is free to do any transformation to the data.

### Actual Behavior
There is no way to have custom behaviors for sorting

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.10.0
- Browser Name and version:
- Operating System and version (desktop or mobile):

If you accept external PRs, I can work on this as I will need to do it anyway for the project I am currently working on

**Comment by ShimiSun** [comment]
Hi @francescodist, in Grommet v2.11.2 we released new props for `sort` and `onSort` https://v2.grommet.io/datatable#onSort. 
Feel free to reopen the issue with a concrete example in case it doesn't meet your needs, from what you are describing it should work as expected. good luck!

**Comment by ShimiSun** [comment]
#3840
