### ISSUE TITLE
Form validate onBlur and FormField validate prop broken in 2.10.0

### ISSUE THREAD

**Issue by jHwls** [grommet/grommet#3732]
FormFields won't validate on blur, despite setting the Form `validate` prop to "blur". Additionally, setting a FormField `validate` prop to an array doesn't work, although the docs list this as an option. Using a function does work however.

Additionally, it would be nice to be able to imperatively trigger certain behaviors of the Form using a ref where Grommet's in-built functionality doesn't meet requirements. Is it possible to expose the `submit` and `validate` functions of the Form so that they can be triggered by, for instance, `formRef.current.validate()` ?

### Expected Behavior

1. Set Form's `validate` prop to "blur". Form triggers FormField validations on removing focus.
2. Set a FormField's `validate` prop to an array: each of the validations, function or object style, should trigger per the docs.

### Actual Behavior

1. Form only triggers validation function on submit, regardless of `validate` prop.
2. FormField won't trigger any validation errors if an array is provided to the `validate` prop.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-sandbox-fj1jn

### Your Environment

- Grommet version: 2.10.0

**Comment by ShimiSun** [comment]
Hi buddy, this issue might have been fixed on the stable master branch, can you verify?
(change `package.json` grommet to point to  "https://github.com/grommet/grommet/tarball/stable" and remove yarn.lock, yarn cache clean)

**Comment by jHwls** [comment]
Awesome, that helps massively. Thanks!

Is there any plan to expose more of the Form api at all? FinalForm/Formik allow for a render props where you can access `errors` and `values` for instance—not seeing how to do something similar in grommet?

**Comment by jHwls** [comment]
@ShimiSun Is there a chance of a release that will lock down the Rorm fixes? Point to master is proving difficult

**Comment by ShimiSun** [comment]
Yes, @jHwls thank you for your feedback, expect a lockdown in the next couple of days.

**Comment by ShimiSun** [comment]
Done. Grommet 2.11.0 is live and ready, check out the release notes https://github.com/grommet/grommet/releases/tag/v2.11.0 and let us know if you need anything else.

**Comment by jHwls** [comment]
Thank you so much! Appreciate all your hard work on Grommet!
