### ISSUE TITLE
DataTable rendering old data

### ISSUE THREAD

**Issue by albertotimoteo** [grommet/grommet#3748]
I'm using grommet's DataTable on one of our projects here in my company and I treat every type of sort in my backend. So, when I change the order of my data, my backend returns me an array and I set this array to a state. This state is the same that the datatable receives, and the table re-renders, but when it does it I have 5 "ghost" registers that always stay at the top of the table. If I do a console.log at the data rendering to check which data the table is rendering, it shows me the right data that should render and does not show this 5 registers that are rendered. I'm cleaning this state one time before it receives the new data, but it's not working either. Does anyone know what's happeing?

- Grommet version: 2.8
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Desktop

**Comment by IanKBovard** [comment]
@albertotimoteo Could you give me an example in codesandbox?

**Comment by ShimiSun** [comment]
Since this issue is stale and DataTable had gone through massive improvements in the last 8 months, I'll be closing the issue. Feel free to reopen if still relevant while providing a reproducible code snippet.
