### ISSUE TITLE
Menu is displaying warning in console when using `as` props

### ISSUE THREAD

**Issue by santaclauze** [grommet/grommet#3749]
First of all, thank you for this great library.

I have a console warning in my console when using `Link` component in the Menu, items props.

### Expected Behavior

Not have a console warning

### Actual Behavior

Have a console warning when using `as` props in Menu Items props.

### URL, screen shot, or Codepen exhibiting the issue

I was unable to reproduce with codepen but here are some screenshots.

Menu component with items props
![Screen Shot 2020-02-14 at 11 36 54 AM](https://user-images.githubusercontent.com/17665998/74484876-56143700-4f1e-11ea-804a-1b8dfd5d1c78.png)

Created a custom Link to remove props that created warnings (Link did no accept certain Button props)
![Screen Shot 2020-02-14 at 11 37 20 AM](https://user-images.githubusercontent.com/17665998/74484898-60363580-4f1e-11ea-8a4d-b47a44cef7ba.png)

Console warning due to `as` props. It does not seem to be trickled down to the MenuItem button props as it should have the `as` one but rather its passed to the Menu Button component.
![Screen Shot 2020-02-14 at 11 35 27 AM](https://user-images.githubusercontent.com/17665998/74484773-2107e480-4f1e-11ea-92e8-7564a51cada1.png)

### Steps to Reproduce

Add a menu item as I have on the screenshots.

### Your Environment

- Grommet version: 2.10.0
- Browser Name and version: Chrome , latest
- Operating System and version (desktop or mobile): Mac Os Mojav 10.14.6

My diagnosis is that the [DropButton](https://github.com/grommet/grommet/blob/35c00d8ad842b3793b2aba554a64c6e904f3f795/src/js/components/Menu/Menu.js#L234) is receiving `{...rest}` which includes the `as` props and it is not listed [here](https://github.com/grommet/grommet/blob/35c00d8ad842b3793b2aba554a64c6e904f3f795/src/js/components/DropButton/DropButton.js#L7) which creates the console warning. 

It could also possible originate in this [line](https://github.com/grommet/grommet/blob/35c00d8ad842b3793b2aba554a64c6e904f3f795/src/js/components/Menu/Menu.js#L266).

Or maybe I am missing something

Anychance we can look into this. I believe that using `Link` component in a place such as MenuItems is quite important and has been encountered before.

**Comment by IanKBovard** [comment]
@santaclauze could you elaborate more on this issue for me? You're unable to use the as prop within menu items? Is there a reason you want to use the Link component, and not href in the menu items? Sorry, I'm just having trouble pinpointing the issue without an example i can work with.

**Comment by IanKBovard** [comment]
@santaclauze Just checking in to see if you can clarify this issue for me.

**Comment by ShimiSun** [comment]
I'll be closing the issue, feel free to reopen and share the requested information.
