### ISSUE TITLE
Select crash strangely with some data opening the drop

### ISSUE THREAD

**Issue by c3s4** [grommet/grommet#3751]
When I use some specific data, the select crashes opening it (only if I need to scroll), telling `NotFoundError` and it seems related to `Drop` component.
I can't explain better than this, I create a codepen to reproduce it.

https://codesandbox.io/s/grommet-select-not-working-with-react-hook-form-ti9wz

**Comment by IanKBovard** [comment]
@c3s4 Can you replicate this again. I'm not sure, but the issue may have been fixed.

**Comment by c3s4** [comment]
Ok the issue I was trying to reproduce was different and while I was trying to reproduce it, I found the crash reported, but I'm not able to reproduce it, maybe is an issue with codepen.

The real issue is similar to the #3636 and I reproduce it here:

https://codesandbox.io/s/grommet-select-not-working-with-react-hook-form-ti9wz

Mayb can help.
I think we can close this one

**Comment by ShimiSun** [comment]
I'm closing this issue and we can track the problem on #3636 , thanks for reporting @c3s4
