### ISSUE TITLE
Layer backdrop not individually styleable

### ISSUE THREAD

**Issue by NickClark** [grommet/grommet#3753]
### Expected Behavior

I should be able to set styles on the Layer backdrop

### Actual Behavior

Setting the style attribute only allows styling of the container. Since a Layer is pulled out of the normal DOM flow, I can't wrap it meaningfully enough to even create a selector so I can manually style it in CSS. Even just being able to assign a `className` to it would be helpful. I know you can override it successfully in the theme overrides, but that overrides it for the entire app. I want to only apply this effect selectively.

### Steps to Reproduce

Create a plain Layer, try adding a style, like `backdrop-filter: blur(5px);` Can't do it.

### Your Environment

- Grommet version: 2.10
- Browser Name and version: Electron 7
- Operating System and version (desktop or mobile): macOS 10.13.6

**Comment by IanKBovard** [comment]
@NickClark This can be done with styled-components.
https://codesandbox.io/s/festive-sammet-we1ie?file=/src/App.js
 Let me know if this answers your question, and we can close this issue.

**Comment by IanKBovard** [comment]
@NickClark let me know if this answers your question an we can close this issue.

**Comment by ShimiSun** [comment]
Feel free to reopen if still relevant.

**Comment by purcymarte** [comment]
@ShimiSun the example applied the backdrop to the layer. Is there a way to add the backdrop to `layer.overlay`? I think this is the more common use-case. A `layer.overlay.extend` for example, would be great.
