### ISSUE TITLE
dropProps being ignored in Menu

### ISSUE THREAD

**Issue by shovelmn12** [grommet/grommet#3755]
https://github.com/grommet/grommet/blob/afdc12fa0b5311ce037bf5410b32b83463e85660/src/js/components/Menu/Menu.js#L234

dropProps not being passed to DropButton in Menu Component.
need to add to DropButton:
<DropButton
           dropProps={dropProps} //maybe remove align or merge all drop props here
           .../>

**Comment by IanKBovard** [comment]
@shovelmn12 could you give me an example of your problem on codesandbox?

**Comment by shovelmn12** [comment]
Simplest is when i want to set direction of the drop with style, now i cant do it so i rebuilt it using dropbutton.

What i tried is to pass dropProps={{style: { direction: "rtl" } }} but it didnt work and i didnt know why until I checked the source code

**Comment by IanKBovard** [comment]
have you tried style={{direction: 'rtl'}}? yeah, could you give me an example i can toy around with?

**Comment by ShimiSun** [comment]
Menu has an RTL support built-in, not sure what you are trying to achieve but Menu has `margin` prop and using either `start` & `end` should play with the RTL property, give it a try and if it doesn't work share with us a codesandbox with your problem description.

**Comment by shovelmn12** [comment]
https://codesandbox.io/s/frosty-hofstadter-rhqkd

look at the drop when its open. Grommet is set to dir="rtl" but the drop is ltr.
btw its a problem i encountered with drop everywhere. because the drop is mounted outside <Grommet/> i need to specify direction manually for all drops. usually i am building a drop of my own which checks the current language of the app and set direction accordingly.

**Comment by ShimiSun** [comment]
Thanks for elaborating, we'll use your example to enhance Drop to work with RTL.

**Comment by shovelmn12** [comment]
Sure no problems, i love Grommet. Cant build a website without it now, make things so much easier.
I still think that Menu should pass dropProps to DropButton as i originally showed.
That way users can control better the Drop for Menu.

**Comment by ShimiSun** [comment]
We'll take a look into it as well, thanks again!

**Comment by ShimiSun** [comment]
Thanks for the fix @IanKBovard
