### ISSUE TITLE
Meter docs

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#3759]
Gotcha, I'll check into how Meter works -- these are just the values that already existed and I was moving them into the Meter file. Will address this in a separate PR.

_Originally posted by @taysea in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjM1Nzg2Njk5OnYy/pull_request_review_threads/discussion_

**Comment by ShimiSun** [comment]
@taysea

**Comment by brodybits** [comment]
@ShimiSun can you give us a little context? The github link seems broken to me.

**Comment by ShimiSun** [comment]
@brodybits thanks for being alert about it. github auto-generated the link, I guess we should file an issue there :)
This issue is derived from the conversation on the following PR:
https://github.com/grommet/grommet/pull/3735

**Comment by brodybits** [comment]
Grommet Meter as described here for the sake of Grommet n00bs like myself:

- https://v2.grommet.io/meter
- source: <https://github.com/grommet/grommet/tree/master/src/js/components/Meter>
- also found this: https://bit.dev/grommet/grommet/meter

Maybe I should just mind my own business though.
