### ISSUE TITLE
Expand Grommet Architecture Page

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet#376]
-  Style – application uses just the CSS, keeping existing code and technology platforms
  -  Component – leverage of the React components and CSS styling.  This model is useful for:
    - A legacy application wanting to begin using React components as legacy portions of the UI are replaced (e.g. Flex or Java applets).
  - AngularJS applications wanting to leverage the React components.
  - A new application, or an application rebuilding the UI.
  - Application – React Components and a set of common backend services for things like search, associations, dashboard, etc.  Can be acheived using one of two modes:
    - Reference API
  - Reference backend services

**Comment by tracybarmore** [comment]
Creating a fact (or FAQ) page and moving issue to grommet-docs (closing this issue).

**Comment by tracybarmore** [comment]
Opened issue #179
