### ISSUE TITLE
AnnounceContext does not accept timeout as a parameter.

### ISSUE THREAD

**Issue by zaferkadi** [grommet/grommet#3760]
### Expected Behavior
announce func from the AnnounceContext accepts 3 arguments message, mode, timeout.
timeout should work as well.

### Actual Behavior
announce func from the AnnounceContext only accepts 2 arguments message, mode

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/bold-swartz-s7wcm?fontsize=14&hidenavigation=1&theme=dark

- Grommet version: 2.10.0
- Browser Name and version: chrome 79.0.3945.130
- Operating System and version (desktop or mobile): macos catalina

Edit:
This is mainly for typescript project, the link I shared was JS only.
Looking into the TS code definition, timeout is missing, am I missing something?

```
export type AnnounceValue = (
  message: AnnounceMessage,
  mode: AnnounceMode,
) => void;

declare const AnnounceContext: React.Context<AnnounceValue>;
```

**Comment by IanKBovard** [comment]
@zaferkadi I'm not sure I understand the issue. Is timeout not working for you in the example, or just when using TS?

**Comment by ShimiSun** [comment]
@zaferkadi If this indeed a typescript issue, please use this code sandbox example of Grommet + TS to reproduce and share your example. https://codesandbox.io/s/grommet-ts-nez6b

**Comment by zaferkadi** [comment]
@IanKBovard @ShimiSun 
Thank you for your response, here is a ts version of the code. I also shared a screenshot of the typescript error for passing timeout to the announce function, I think it's only missing the definition
https://codesandbox.io/embed/grommet-ts-ovtw7?fontsize=14&hidenavigation=1&theme=dark

<img width="630" alt="Screenshot 2020-03-01 at 18 42 57" src="https://user-images.githubusercontent.com/1412075/75630615-ad87f780-5bec-11ea-90fc-e25d6a13b466.png">

<img width="608" alt="Screenshot 2020-03-01 at 18 45 19" src="https://user-images.githubusercontent.com/1412075/75630657-0ce60780-5bed-11ea-94b9-eef46d080f38.png">

**Comment by IanKBovard** [comment]
sorry for the wait, working on this now

**Comment by ShimiSun** [comment]
Fixed thanks to @IanKBovard ! will be available on our next release.
