### ISSUE TITLE
Bug report: FormField does not work well with nested TextInput.

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet#3761]
### Expected Behavior
This code should work:

```javascript
<Form onSubmit={({ value }) => console.log(value)}>
    <FormField name='password' label='password' required>
      <TextInput name='password' type='password' />
    </FormField>
    <Button primary type='submit' label='sign-in' />
</Form>
```

### Actual Behavior
Type anything in the TextInput and click "Submit", there is an error message "required" below the TextInput.

### URL, screen shot, or Codepen exhibiting the issue
Sandbox URL: "https://codesandbox.io/s/confident-lamport-uilum"

### Steps to Reproduce

- next.js
  1. Browse "https://github.com/jim-king-2000/nextbugrepro", clone the code.
  2. cd nextbugrepro, npm run dev
  3. Open "localhost:3000", type anything in the password text input.
  4. See the error: "required".

- sandbox
  1. Open "https://codesandbox.io/s/confident-lamport-uilum", , type anything in the password text input.
  2. See the error: "required".

### More information
1. Nested TextInput does not work while standalone FormField works well.
2. If I move "required" property from FormField to TextInput, the "required" error disappears. But click "submit", we see "{}" in the console. It's value can't be captured.

### Your Environment

- Grommet version: 2.10.0
- Browser Name and version: Chrome 80
- Node.js: v13.9.0
- Operating System and version (desktop or mobile): Win10 & Ubuntu 18.04

**Comment by ShimiSun** [comment]
Thank you for the detailed reporting buddy, I've put the code on both storybook and the grommet [playground code](https://v2.grommet.io/form?c=AQ4HgcQJwewWzgUwC4D4BQpRgGIynMDAHYDKArgEZwCWyAvAN4AUjwAbgIYA25iwAXwCUweqmABjEgGcY3RADpuMAObMuvREIEYsWXPjg4aibgBNgxTknoAiAA6dp0gO74zt4N06VTdx85uUB66evoAKogAHsgAksT25MiW1oj+Tq7unsgAnvZpDhlBHsAA9KFhYKV4BMamZhV6YABCScgkwPZQNHCcUDnAufl20lS0yJ7evtwjNCrEALQ0xJ7lmE3Vho1V0PBIaEA), and I wasn't able to reproduce it which made me think this issue might be fixed on the master branch already, you can point your grommet package on package.json to "https://github.com/grommet/grommet/tarball/stable" and helped me verified this issue had been fixed. please keep me posted.

**Comment by jim-king-2000** [comment]
Verified. It's been fixed. Looking forward to the new release.

**Comment by ShimiSun** [comment]
@jim-king-2000 sooner than you think ;) 
It's here https://github.com/grommet/grommet/releases/tag/v2.11.0.

I'll be closing the issue, keep us posted if anything else comes up.

**Comment by jim-king-2000** [comment]
Thanks for the quick response, fix and release. Good wishes to Grommet.
