### ISSUE TITLE
Form validate is not accepting React Elements

### ISSUE THREAD

**Issue by ypinneka** [grommet/grommet#3762]
Hi,

In the story,
https://storybook.grommet.io/?path=/story/form--validate-on-blur
If you check the FormField part of the story,
          <FormField
            label="Name"
            name="name"
            required
            validate={[
              { regexp: /^[a-z]/i },
              name => {
                if (name && name.length === 1) return "must be >1 character";   _==== ERR line_
                return undefined;
              }
            ]}
          />

The validate prop error is showing up only if the return value is a string. There is no error if I return a React Element.
Ex,               name => {
                if (name && name.length === 1)
                  return **"HTML text tag"**must be 1 character**"HTML text tag"**;
                return undefined;
              },

This was working before the status flag has been added to Validate prop. (https://github.com/grommet/grommet/pull/3745)

I am facing this issue when pointing to stable branch.

**Comment by shayanc** [comment]
Same issue here, looking at the console warning it appears that it no likes the array type. 
Non-array based validate objects works fine however - `validate={{ regexp: /^[a-z]/i }}`.

**Comment by ShimiSun** [comment]
Fixed on the stable branch, thanks for reporting. we'll have an official release in the next couple of days.
