### ISSUE TITLE
Can't resolve 'styled-components'

### ISSUE THREAD

**Issue by adriangabardo** [grommet/grommet#3770]
### Expected Behavior
`npm i grommet-icons` should work by itself

### Actual Behavior
Need to manually install styled-components after the grommet install

Can you add styled-components to the package.json dependencies? It will install with grommet automatically then.

**Comment by oorestisime** [comment]
Hey there,

styled-components is intentionally a peer dependency so we don't lock you in our version of styled-components. Same with react! 
This is not a bug but a feature :)

**Comment by IanKBovard** [comment]
@adriangabardo Was oorestisime able to answer your question?

**Comment by IanKBovard** [comment]
@adriangabardo anything else you'd like to add before we close this issue?

**Comment by adriangabardo** [comment]
Ah, the old feature not a bug trick ;) 
Just wanted to double checked, happy to close the issue guys.
