### ISSUE TITLE
Layer opaque background in IE11

### ISSUE THREAD

**Issue by chris-grandinetti** [grommet/grommet#3781]
Layer opaque background in ie11
### Expected Behavior
When selecting an item that pops up an overlay, you should continue to see the screen behind it:
<img width="1304" alt="Screen Shot 2020-02-25 at 8 36 44 AM" src="https://user-images.githubusercontent.com/31540481/75252344-7f4c8700-57aa-11ea-9b6c-f545491a0abe.png">

### Actual Behavior
When clicking that item it instead causes the background to become gray (opaque):
![Grommet_Overlay_Issue](https://user-images.githubusercontent.com/31540481/75252255-4d3b2500-57aa-11ea-95ef-8be10a7499ed.JPG)

### Steps to Reproduce

1. In Internet Explorer 11, click on an item that causes an overlay to pop up
2. Observe the screen behind the overlay is gray (opaque)

### Your Environment

- Grommet version 2.11.0
- IE11 11.1685.16299.0
- Windows 10 Desktop 10.0.16299 Build 16299

**Comment by ShimiSun** [comment]
https://stackoverflow.com/questions/11516680/css-opacity-not-working-in-ie

**Comment by IanKBovard** [comment]
The layer overlay is in the same div as the layer itself.

<div layerContainer>
  <div layerOverlay />
  <div layer />
</div>

applying opacity to the overlay won't display the background, and applying opacity to the layerContainer will make the entire layer transparent. The layerOverlay needs to be moved outside of the layerContainer, and opacity applied.

**Comment by IanKBovard** [comment]
@ShimiSun how do you feel about making the layerContainer transparent? That would fix the issue in ie11, but i'm not sure how it would affect layer as a whole.

**Comment by ShimiSun** [comment]
@IanKBovard I think the approach should be for IE to behave the same as Chrome and not make any specific changes for this issue.
How come Chrome works as expected without a transparent background?

**Comment by ShimiSun** [comment]
Fixed and will be available on our coming release. thanks for reporting
