### ISSUE TITLE
Allow user to specify target for Layer positioning

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#3785]
It'd be useful to be able to tell Layer what box to position relative to. Similar to how Drop has dropTarget. Right now, it only positions relative to the entire window.

### Expected Behavior

Be able to apply layerTarget to Layer which refers to an element that it should position itself relative to.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
Thank you for reporting! The issue is fixed and will be available on our next release.
