### ISSUE TITLE
ThemeType breakpoints missing types for medium and large?

### ISSUE THREAD

**Issue by NiekBetty** [grommet/grommet#3787]
When I try to set `edgeSize` for breakpoints `medium` and `large` my TypeScript compiler complain about `edgeSize` not being a valid type on `global.breakpoints.medium` and `global.breakpoints.large`.

### Expected Behavior

Typescript builds the project.

### Actual Behavior

Typescript throws the following type error:

```
src/theme/index.ts:28:9 - error TS2322: Type '{ edgeSize: typeof edgeSize; }' is not assignable to type '{ value?: number; }'.
  Object literal may only specify known properties, and 'edgeSize' does not exist in type '{ value?: number; }'.

28         edgeSize,
```

### Steps to Reproduce

1. Add the following config to the theme:

```
global: {
  breakpoints: {
    medium: {
      edgeSize: {
        small: '1px'
      }
    }
  }
}
```

### Your Environment

- Grommet version: 2.11.0
- TypeScript

**Comment by ShimiSun** [comment]
Hi buddy, thanks for reporting! 
I created a sandbox of Grommet+TypeScript+customBreakpoints theme, and I don't see the error reproduces, feel free to tune the theme so the error reproduces and I can take better-educated fix https://codesandbox.io/s/grommet-ts-nez6b

**Comment by NiekBetty** [comment]
Hi @ShimiSun 

Thanks for your quick reply!

I typed the `customBreakpoints` constant with `ThemeType`. That's when you get the TypeScript error, see this edited code sandbox: https://codesandbox.io/s/grommet-ts-6bi3j

**Comment by NiekBetty** [comment]
Inside the `base.d.ts` file the `medium` and `large` breakpoints are typed differently than the `small`:

```
    breakpoints?: {
      small?: {
        value?: number;
        borderSize?: {
          xsmall?: string;
          small?: string;
          medium?: string;
          large?: string;
          xlarge?: string;
        };
        edgeSize?: {
          none?: string;
          hair?: string;
          xxsmall?: string;
          xsmall?: string;
          small?: string;
          medium?: string;
          large?: string;
          xlarge?: string;
        };
        size?: {
          xxsmall?: string;
          xsmall?: string;
          small?: string;
          medium?: string;
          large?: string;
          xlarge?: string;
          full?: string;
        };
      };
      medium?: {
        value?: number;
      };
      large?: {
        value?: number;
      };
```

GitHub link to file: https://github.com/grommet/grommet/blob/master/src/js/themes/base.d.ts

**Comment by ShimiSun** [comment]
Perfect, let me work on a fix.
