### ISSUE TITLE
Select Component with big options scroll bug

### ISSUE THREAD

**Issue by christophrath** [grommet/grommet#3790]
Should:
Using the select component with lots of options should be able to get into a proper scrolling mode when viewport is too small to show the complete dropdown.

But you can scroll "endless" and there's flickering content. 

https://codesandbox.io/s/grommet-sandbox-3xpq2
-> go to "select" component and add a big list of options here

Steps to reproduce:
1. add select component
2. make a pretty long array with options that are higher than your vieport height. 

- Grommet version: 2.11.1
- Browser Name and version: Chrome 80
- Operating System and version (desktop or mobile): Desktop Mac OS Catalina 10.15.3

**Comment by ShimiSun** [comment]
Is this a duplication of https://github.com/grommet/grommet/issues/3665?

**Comment by christophrath** [comment]
You are right. 
Duplicate of #3665
