### ISSUE TITLE
Inconsistent and broken behavior in detecting empty required FormFields

### ISSUE THREAD

**Issue by blakehilliard** [grommet/grommet#3791]
### Expected Behavior

If a FormField is empty on submittal, and it was marked as required, don't submit and point out the error. If it's not empty on submittal, don't say that it is!

### Actual Behavior

With FormFields of type="password", I get strange inconsistent behavior instead of the expected behavior described above.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-formfield-required-password-qe680

![image](https://user-images.githubusercontent.com/25166376/75395498-2f5be600-58b8-11ea-8b7e-1eaec24548db.png)

![image](https://user-images.githubusercontent.com/25166376/75395572-4f8ba500-58b8-11ea-9c12-badf9496dfff.png)

![image](https://user-images.githubusercontent.com/25166376/75395635-68945600-58b8-11ea-864e-843f595179eb.png)

### Steps to Reproduce

Follow the steps described in the codepen.

### Your Environment

- Grommet version: 2.11.1
- Browser Name and version: Chrome 79.0.3945.130 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10, desktop

**Comment by ShimiSun** [comment]
hi @blakehilliard, thanks for reporting! 
Your codesanbox was very helpful to quickly troubleshoot the issue. 
Here is the fixed version of your sandbox to unblock you https://codesandbox.io/s/grommet-formfield-required-password-q73pq, the only thing I added to your sandbox is the `name` prop on the FormFields. Not setting the `name` prop will mark the field as undefined, and the `required` logic wouldn't be set on an `undefined` formfield, hence it needs a `name` prop - that being said, I 100% agree this should be either fixed or documented. I've seen a similar issue on https://github.com/grommet/grommet/issues/3777 a couple of days ago and it should be addressed.

Regarding action items for us, we can take one of the following measures:
1. Document that the `name` prop is required, and send warning messages if it isn't. 
2. Set a default `name` of FormField with default grommet values or derived the `name` from its child component. If the Child element doesn't have a `name` then back to #1.

@ericsoderberghp I'd love to hear your inputs on this issue.

**Comment by ericsoderberghp** [comment]
I lean towards measure #1 

I don't think we should construct a default `name`, it could conflict with the name of another element somewhere in the document. I'm leery of looking inside children to try to figure out what to do. If my child is `<MyCustomComponent name="Fred" />`, that `name` may or may not be what we should use.

**Comment by blakehilliard** [comment]
I just noticed that if I downgrade from grommet 2.11 to 2.10 or earlier, the behavior of the codepen is different. It seems to not enforce `required` on the 2nd FormField, but no strange behavior other than that.

**Comment by ShimiSun** [comment]
We are working on a fix for the issue you mentioned:
> It seems to not enforce required on the 2nd FormField

I'll keep this github issue updated as we go. Thanks again for reporting!

**Comment by ShimiSun** [comment]
One more PR before we close it https://github.com/grommet/grommet/pull/3815

**Comment by IanKBovard** [comment]
looks like #3815 was merged, are we free to close this issue?

**Comment by ShimiSun** [comment]
@blakehilliard can you please confirm that the master branch works as expected on your end? you can point your package json grommet package to "https://github.com/grommet/grommet/tarball/stable", re-install grommet and verify the fixes works for you as expected. let us know how it goes.

**Comment by blakehilliard** [comment]
How can I do that in the codepen?

**Comment by ShimiSun** [comment]
The stable branch isn't published to npm, so I suspect you can only do it on your local repo.
