### ISSUE TITLE
Adding extend option for table.body

### ISSUE THREAD

**Issue by dchen323** [grommet/grommet#3792]
Currently trying to set a min-height on the table body, but there is no extend option on table body. Using workaround to set an estimated min-height by setting it on the table extend option. Would be nice if it would be possible to add  the extend option on table body.

### Expected Behavior

Should be able to set table body height with extend.

```javascript
const theme = { table: {
  body: { extend: `min-height: 100px;`}
  }
};
```
### Current Behavior

Have to use an estimate at the moment. No Table.body.extend

```javascript
const theme = { table: {
   extend: `min-height: 100px + table.header height + ect;`
  }
};
```

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-55rdu

### Steps to Reproduce

In Sandbox

### Your Environment

- Grommet version: ^2.8.1
- Browser Name and version: Chrome Version 80.0.3987.122
- Operating System and version (desktop or mobile): Mac OS Mojave 10.14.6

**Comment by ShimiSun** [comment]
The fix will be available on our next release, thanks for reporting, and thank you @britt6612 for the contribution!
