### ISSUE TITLE
Enable right-to-left locales

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet#380]

**Comment by ericsoderberghp** [comment]
We are about 50% of the way there at the moment. Remaining items include:

Menu drop alignment
Search drop alignment
Table cell order
fix grommet-docs Options code examples
Meter flip vertical arc, draw RTL
Chart draw RTL
Distribution draw RTL
Calendar control location, prev/next control icons
LoginForm
Map

**Comment by alireza-ahmadi** [comment]
@ericsoderberghp do we have any progress on RTL support? if not, does anyone working on this or we can start to complete it?

**Comment by alansouzati** [comment]
I dont think there is anyone working on that at this point. It would be awesome if you can send a PR for that.

**Comment by dgennetten** [comment]
Link to 1529?

**Comment by RyanCCollins** [comment]
@dgennetten yes please!

**Comment by L0ZZI** [comment]
Adding to Grommet v2.

**Comment by jsina** [comment]
I don’t understand is the an RTL style or not on v2?
