### ISSUE TITLE
This project has been added to the react-ui-roundup

### ISSUE THREAD

**Issue by dimitropoulos** [grommet/grommet#3804]
Hi!

I am making this issue just to let you know that I've included your amazing project in the [react-ui-roundup](https://github.com/dimitropoulos/react-ui-roundup).

For more information see https://github.com/dimitropoulos/react-ui-roundup/issues/2.

Please feel free to close this issue at will - I just wanted to let you know :smile:.

Thanks!

**Comment by ShimiSun** [comment]
Hi @dimitropoulos , thanks for letting us know! nice work!!
I filed a PR to your project to enhance the info on grommet https://github.com/dimitropoulos/react-ui-roundup/pull/12

After merging the PR and updating your site, feel free to publish this announcement on our Slack #announcement channel so more React users will be exposed to this comparison tool. 

Regardless, an enhancement request for your tool, since you have a growing framework list, I'd recommend using alphabet order for easier and quicker framework lookup.

Let me know what you think! Bests

**Comment by dimitropoulos** [comment]
thanks!  I updated the PR over there.

> Regardless, an enhancement request for your tool, since you have a growing framework list, I'd recommend using alphabet order for easier and quicker framework lookup.

As it turns out, I do actually already automatically sort everything everywhere (as far as I am aware), [including the framework name](https://github.com/dimitropoulos/react-ui-roundup/blob/master/frameworks/index.ts#L39), but the branding I have seen for grommet suggests the _lowercase_ `g`.  Due to:

```js
["A", "b", "C"].sort()
```

returning
```js
["A", "C", "b"]
```

In JavaScript, that means that `grommet` and `react-md` are sorted after all the other frameworks that happen to use capital letters.

Still.. I have to say I really agree with you that this is a bug.  The sort, independent of whatever javascript does by default, shouldn't be case sensitive like this.  It's counter-intuitive.  I'll open an issue.

In the meantime.. is the lowercase `g` branding correct?

**Comment by dimitropoulos** [comment]
update: I fixed the sorting in https://github.com/dimitropoulos/react-ui-roundup/pull/14, but please do let me know if the branding (i.e. using the lowercase `g`) is your preference.  These details matter to me - you worked hard to make this project and I don't want to misrepresent you in any way!

**Comment by ShimiSun** [comment]
I think we can use "Grommet" in a title case rather than a lower case. thanks.

**Comment by ShimiSun** [comment]
@dimitropoulos hi buddy, any news on this one? how is the PR review going?

**Comment by dimitropoulos** [comment]
Thanks for the followup! Just merged the PR.  Thanks!

re: RTL - it's always helpful if there's somewhere more overt than storybook that it's mentioned.  It looks like, from your roadmap, that you're targeting having increased RTL support - which is great!

**Comment by ShimiSun** [comment]
Awesome, thanks @dimitropoulos , and you are right we should put more focus on RTL docs.

Feel free to announce our work on the Grommet [#slack](http://slackin.grommet.io/), and get exposure for your project. the #announcment channel will be a good place for it. 

I'll be closing this issue. 

Good luck buddy!
