### ISSUE TITLE
MaskedInput allows input outside of the mask

### ISSUE THREAD

**Issue by copperwall** [grommet/grommet#3807]
When controlling the MaskedInput state using the `onChange` handler, the input will allow an extra character. A good example of this is the [Date](https://storybook.grommet.io/?path=/story/maskedinput--date) story in the storybook.

The mask specifies an input format for dd-mm-yyyy, but the user can enter a value of dd-mm-yyyyy.

### Expected Behavior

When a MaskedInput specifies a mask for a date (dd-mm-yyyy), it shouldn't let users add an additional character to the end of the input value

### Actual Behavior

When controlling the MaskedInput state using the `onChange` handler, the input will allow an extra character. A good example of this is the [Date](https://storybook.grommet.io/?path=/story/maskedinput--date) story in the storybook.

The mask specifies an input format for dd-mm-yyyy, but the user can enter a value of dd-mm-yyyyy.

### URL, screen shot, or Codepen exhibiting the issue

![2020-02-29 17 19 12](https://user-images.githubusercontent.com/2539016/75617732-16517000-5b18-11ea-9b57-ca5fbacf67e0.gif)

### Steps to Reproduce

1. Go to https://storybook.grommet.io/?path=/story/maskedinput--date
2. Enter 01/01/19999

### Your Environment

- Grommet version: 2.11.1
- Browser Name and version: Chrome 80
- Operating System and version (desktop or mobile): MacOS Catalina

**Comment by ShimiSun** [comment]
Thank you for the contribution buddy.
adding a reference of a playground to this issue https://codesandbox.io/s/grommet-v2-template-tiuuf, switching between grommet versions will demonstrate the issue clearly.

**Comment by ShimiSun** [comment]
Thanks again for reporting and making a contribution, sending some grommet love ❤️
