### ISSUE TITLE
FormField : onChange parameter undefined in "component" property

### ISSUE THREAD

**Issue by emmanuelgratuze** [grommet/grommet#3812]
Since version 2.11.1, the props.onChange parameter seems to be undefined when giving a function to component property in FormField.

### Expected Behavior
In the previous release (2.10.0), the component property callback was returning the parameter onChange :
```
<FormField
  component={({ onChange, ...props }) => {
    // onChange was defined here
    return <CustomInput onChange={onChange} {...props} />;
  }
/>
```

### Actual Behavior
onChange property is not defined anymore when component property is being called.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/custom-input-onchange-undefined-k9zml

In the codesandbox, changing the grommet version from 2.11.1 to 2.10.0 solves the problem.

### Your Environment
- Grommet version: 2.11.1
- Browser Name and version: Google Chrome 80.0.3987.122
- Operating System and version (desktop or mobile): macOS Catalina 10.15.3, desktop

Thank you!

**Comment by ShimiSun** [comment]
Thank you for reporting buddy, I was able to fix it by adding a `name` prop to the component field https://codesandbox.io/s/custom-input-onchange-undefined-fixed-qftc8. we will add documentation for it. Thanks.
linking to #3777 #3791

**Comment by ShimiSun** [comment]
...That being said, we are working on a fix that potentially won't need the workaround. I'll keep this issue updated as we go.

**Comment by ShimiSun** [comment]
This issue is fixed, we will post a release soon to include this fix. thanks for reporting!
