### ISSUE TITLE
Meter, WorldMap, Distribution is not rendering correctly

### ISSUE THREAD

**Issue by jatarga** [grommet/grommet#3819]
### Expected Behavior
Meter, WorldMap, Distribution should render in **Gatsby**

### Actual Behavior
Meter, WorldMap, Distribution is not rendering, instead they render meaningless DOM: https://ibb.co/GnCB40G

### URL, screen shot, or Codepen exhibiting the issue
https://ibb.co/GnCB40G

### Steps to Reproduce
```jsx
import React from "react"
import { Box, WorldMap } from "grommet"
export default () => (
  <Box align="center" pad="large" background="red">
    <WorldMap />
  </Box>
)
```

### Your Environment
- **Gatsby**
- Grommet version: 2.11.1
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Macos Sierra

**Comment by ShimiSun** [comment]
@oorestisime @halocline or any other Gatsby users can confirm?

**Comment by jatarga** [comment]
I've created a demonstration with the following dependencies and it rendered successfully.

``` json

{
    "gatsby": "^2.19.7",
    "grommet": "^2.11.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "styled-components": "^5.0.1"
  }
```
So I guess in the project there is something broke not related to grommet.

**Comment by ShimiSun** [comment]
@jatarga , great, thanks for sharing buddy.
