### ISSUE TITLE
Input Component's suggestion drop does not popup correctly

### ISSUE THREAD

**Issue by bytewoopy** [grommet/grommet#3820]
I updated from 2.10 -> 2.11.1 and noticed my input search drops stopped activating when typing...

### Expected Behavior
Drop should show up as in previous releases as soon as user starts typing

### Actual Behavior
No suggestions show up unless I click outside the input and click back in and focus the input or press down arrow key

### URL, screen shot, or Codepen exhibiting the issue
You can see the issue in the existing storybook example:
https://storybook.grommet.io/?path=/story/textinput--custom

### Steps to Reproduce

1. Type in "Marlon"
2. Click outside the input to lose focus
3. Click back in the input to regain focus

### Your Environment
- Grommet version: 2.11.1
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by DAnselC** [comment]
I also just ran into this issue. I would be fine with this functionality if there was a way to have the suggestions drop open automatically like it did in previous releases!

Additionally I found another semi-related bug. Even in the [existing storybook example](https://storybook.grommet.io/?path=/story/textinput--custom) you will notice this:
There is a flash of "[Object object]" when selecting an element from the suggestions dropdown. Additionally, once you select an option, if you reselect an option it will put "[Object object]" as the value for the input.

**Comment by ShimiSun** [comment]
@DAnselC thanks for reporting. 
We fixed an issue on the TextInput drop this morning, can you confirm you are still seeing this issue? storybbok is up to date.

**Comment by DAnselC** [comment]
@ShimiSun Thanks for getting back to me! 
I checked out the Grommet Storybook, and I also pulled the latest version of Grommet (with the commits of the TextInput drop fixes) and built and copied files over to my project, and in both cases I'm still running into this issue 🙁

**Comment by ShimiSun** [comment]
@DAnselC thank you for verifying, I'm not able to reproduce the storybook issue you attached with the gif, are you still seeing the same thing? or does it behave differently now?

**Comment by DAnselC** [comment]
This is the storybook I'm looking at! https://storybook.grommet.io/?path=/story/textinput--custom

To clarify, here are steps to reproduce the issues that I'm seeing:
- Start typing into the TextInput. The suggestions drop no longer opens when the user is typing. The user _must_ press the down arrow key for the drop to open.
- Type "Eric." Press the down arrow key to open the suggestions drop. Select Eric from the drop **with a mouse click**. It will flash with `[object Object]` and then put in the correct value. Open the drop again by pressing the down arrow key. Reselect Eric **with a mouse click** and `[object Object]` will be put into the value of the TextInput.

**Comment by ShimiSun** [comment]
Thank you guys for reporting, a fix is ready on the master branch and will be available on our next official release.

**Comment by DAnselC** [comment]
Thanks!
