### ISSUE TITLE
Bug: Select in Form, the value is not controlled by value property.

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet#3825]
### Expected Behavior

    const [a, setA] = useState();
    <Form>
      <Select name='some_name' value={a} />
      <Button onClick={() => setA('a')} />
    </Form>

We use state `a` to control the value of the Select component. When clicking the button, we set state `a` to string 'a'.

The content of Select component should be controlled by the value property. The value changes, the content changes.

### Actual Behavior

Click the button, the state will be set to 'a'. But the string in the Select control wouldn't change.

By the way, the icon `<Qr />` looks weird.

### Steps to Reproduce

A. Sandbox
  1. See https://codesandbox.io/s/distracted-taussig-hdvjb
  2. click "text" button, see no effect.

B. Github
  1. goto https://github.com/jim-king-2000/nextbugrepro
  2. clone the code
  3. `cd nextbugrepro && npm i && npm run dev`
  4. access http://localhost:3000
  5. click "text" button, see no effect.

### More Information

1. The bug occurs with two conditions. First, there is a `name` property in Select. Second, Select is in a Form. Without any of the two, it works.
2. It works when we select a value in the dropdown menu of the Select component.
3. It can't be reproduced on grommet@2.10.0. (But grommet@2.10.0 contains other bugs)

### Your Environment

- Grommet version: 2.11.1
- Browser Name and version: Chrome 80
- Operating System and version (desktop or mobile): win10

**Comment by ShimiSun** [comment]
Fixed on the master branch. Hoping we'll have a release soon. thanks for reporting!

**Comment by ShimiSun** [comment]
Fixed on the master branch. Hoping we'll have a release soon. thanks for reporting!

**Comment by jim-king-2000** [comment]
:smiley:

**Comment by jim-king-2000** [comment]
What about the `<Qr />` icon bug?

**Comment by ShimiSun** [comment]
Our designers may need to take a look at that.
