### ISSUE TITLE
plain is true on button when label prop has no value

### ISSUE THREAD

**Issue by NiekBetty** [grommet/grommet#3826]
I apply extended styling on a `Button` component via the theme. Hereby I make use of `extend` accepting a function as value. One of the arguments of this function is `plain`. I think this prop has some unexpected behavior when  no value is given to the `label` prop on the `Button` component.

### Expected Behavior

When a `Button` component has no `plain` prop and no value for the `label` prop the `plain` value should be `false`.

### Actual Behavior

The `plain` value is `true`.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-yv28m

### Steps to Reproduce

1. Add `Button` component
2. Add icon to `Button`
3. Make sure to use no value for `label` and do not add `plain`

### Your Environment

- Grommet version: 2.11.0

**Comment by britt6612** [comment]
@NiekBetty thanks for reporting this. 

I did find in the code where this logic is 

https://github.com/grommet/grommet/blob/bc8daccc5ea4ef5f39e78b296850303736003e10/src/js/components/Button/Button.js#L137

I believe because if there is a icon and no label this is indicating that it is plain.

**Comment by NiekBetty** [comment]
Hi @britt6612 , thanks for you reply.

Does this mean this is intended behaviour?

**Comment by ShimiSun** [comment]
@NiekBetty thanks for raising this question.
Just to clarify, in case there is no 'strong' value assigned to `plain` (either true/false), it will be treated as `undefined` which will be the default value of the plain Button. 
You can see the differences in this behavior of `plain` (true, false and undefined) on https://storybook.grommet.io/?path=/story/button--icon-plain let me know what you think.

**Comment by taysea** [comment]
@NiekBetty, just to add onto Shimi's comment. The reason an icon only button automatically gets assigned `plain=true` is so that the hit target of the icon is a minimum of 48x48px. This is to meet accessibility recommendations on hit target size.

**Comment by ShimiSun** [comment]
@taysea I don't think 
>icon only button automatically gets assigned plain=true

`plain='true'` will remove all padding, while 'only icon button' does have auto pad apply for the accessibility reasons you specified ⬆️  
 'only icon button' without a `plain` prop will be treated as `undefined` as follows: https://storybook.grommet.io/?path=/story/button--icon-plain

**Comment by taysea** [comment]
You're right @ShimiSun. But I think what is happening behind the scenes is two things.
First, if and icon is provided but no label, Button applies "plain": https://github.com/grommet/grommet/blob/master/src/js/components/Button/Button.js#L140

Then, in the styling it applies the plain styles first (https://github.com/grommet/grommet/blob/master/src/js/components/Button/StyledButton.js#L139) but then later on it adds back in the padding for accessibility: https://github.com/grommet/grommet/blob/master/src/js/components/Button/StyledButton.js#L171

Let me know if that seems correct

**Comment by NiekBetty** [comment]
Ah I get the solution for accessibility, nice 👍

However, why are the `icon` and `label` prop influencing this? Doesn't this accessibility apply for a text buttons as well? Or is the width of a text button enough to meet accessibility recommendations?

Also `plain` has three possible values: `undefined`, `true` and `false`. Shouldn't this be an `enum` with a default value then? The documentation now states that there are two possible values and it defaults to `false`: https://v2.grommet.io/button#plain

**Comment by taysea** [comment]
With text, the button will typically be wide enough to meet accessibility. 

Thanks for the note on the documentation of `plain`. I'll take a look at how the possible values are documented.

**Comment by hedleysmith** [comment]
Just to add that this tripped me up when starting out with Grommet (which is awesome, btw).

When I tried to add a simple <Button> with text - I couldn't figure out why it wasn't displaying with any background color (as I'd expect, by default).

The following worked for me:

`<Button plain={false}>Test</Button>`

**Comment by ShimiSun** [comment]
@hedleysmith & @NiekBetty please share how you think that this issue should be approached? I'm not sure what we can do with staying backward compatible.

**Comment by NiekBetty** [comment]
We're using the `plain={false}` workaround as well.

Maybe I can expand a little bit on my problem. We're using the `extend` theme sections a lot to customize in this exmample the Grommet buttons to look like our buttons. However we have three kinds of buttons; primary, secondary and tertiary. Right now we're misusing the `plain` prop to behave as our tertiary button.

So my suggestion would be to add a tertiary prop and support a tertiary button. However this solves our case, I don't know if it solves @hedleysmith 's problem?

**Comment by hedleysmith** [comment]
I've just found that there's a difference in how a Button will behave depending on whether you use the `label` prop or add label text as a child: https://codesandbox.io/s/grommet-v2-template-fprh2

@ShimiSun - for now, updating documentation would be very useful. Otherwise, setting `plain` to `false` when a Button has children makes more sense in my use cases, perhaps this could be considered for the next major release.

**Comment by bcbrian** [comment]
Would a partial solution to the latter part of this issue be treating a `label === children`? I just spent 2-3hrs debugging why styling was not working when I excluded plain(plain === undefined) and had children and no label.
`<Button>Submit</Button>` should inherit default styles, unless it is an intentional design system decision.
I am willing to help just need some help to know which direction to take this issue.

**Comment by ShimiSun** [comment]
@bcbrian Thanks for the feedback, sorry you had to spend time debugging it.
Currently, we have a style disclaimer on the docs when using `children` of Button - as follows:
> When Button has children, it is styled as a plain button.

Is there anything else we can add to make it clearer in your opinion?

**Comment by jcfilben** [comment]
If `label` is not specified I think the expectation is that the button will have either an `icon` or `children`, in both of these cases the Button will be `plain`. I believe this is the intended and documented behavior. I'm going to mark this issue as closed but feel free to re-open and comment if more discussion on this is desired or if there are any suggestions on improving the documentation for this.
