### ISSUE TITLE
required FormField with Select child always rejects submit

### ISSUE THREAD

**Issue by blakehilliard** [grommet/grommet#3832]
required FormField with Select child always rejects submit

### Expected Behavior

If you do `<FormField required ...><Select .../></FormField>`, it should only be rejected if you have not selected anything from the drop-down menu.

### Actual Behavior

Even if you select something, submission is rejected saying that the field is required.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-required-select-bzoi1

### Steps to Reproduce

Open the above codepen. Select something from the drop-down menu, then click "Submit".

### Your Environment

- Grommet version: 2.11.1
- Browser Name and version: Chrome 79.0.3945.130 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10, desktop

**Comment by ericsoderberghp** [comment]
I think this is due to the Select not having a `name` property. Here's a fork showing it: https://codesandbox.io/s/grommet-required-select-nxfle

**Comment by blakehilliard** [comment]
That works, thanks. "name" isn't listed here, so I didn't know I could use it with Select: https://v2.grommet.io/select

**Comment by ShimiSun** [comment]
@blakehilliard thanks for raising the docs issue, I added a PR to enhance the documentation.

**Comment by ShimiSun** [comment]
I'll be closing this issue now that the docs are improved, thanks for reporting!
