### ISSUE TITLE
How to use local custom font?

### ISSUE THREAD

**Issue by codeinaire** [grommet/grommet#3835]
I want to use a custom local font, but I've been unable to get it to work. I've tried this solution: https://github.com/grommet/grommet/issues/3107 but couldn't get it to work and cannot find any other solution.

I tried it in the theme object and also in the style sheet but to no avail.

### Expected Behavior

The custom local font should load.
### Actual Behavior
The custom local font is not loading.

### URL, screen shot, or Codepen exhibiting the issue
I'm using Next.js 9.1.6 as well, but I tried it in the sandbox below and it still didn't work so I don't think Next.js is the issue.

https://codesandbox.io/s/grommet-v2-template-68g5b

### Steps to Reproduce
As per the code sandbox

### Your Environment

- Grommet version: 2.11.1
- Browser Name and version: Firefox 74.0b9
- Operating System and version (desktop or mobile): OSx

**Comment by ShimiSun** [comment]
hi buddy, I took your example and loaded custom font to it so you can have a working example.
Please mind the cleanups I changed on the file. https://codesandbox.io/s/custom-font-l7xz9 hope that helps.

**Comment by codeinaire** [comment]
Thanks for the quick feedback. It didn't help, but I did get this error:

`downloadable font: download failed (font-family: "NoMeatMayTitle" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: http://localhost:3000/public/fonts/NoMeatMayTitle-Regular.woff`

It seems what I'm doing to use the font is correct, but there's something else going on that mucking up the process.

**Comment by ShimiSun** [comment]
@taysea I think you had a similar issue with your website, can you help troubleshoot?

**Comment by codeinaire** [comment]
Yup, I can help troubleshoot! What do you need me to do?

**Comment by taysea** [comment]
@codeinaire It looks like you just need to modify the path to the font. Instead of `/public/fonts/NoMeatMayTitle-Regular.woff`, you should use `/fonts/NoMeatMayTitle-Regular.woff`. Once I did that, I could see your custom font.

**Comment by ShimiSun** [comment]
Thanks @taysea, I'll be closing this issue, let us know if you have any more questions.

**Comment by codeinaire** [comment]
I did try that but I was using `local()` instead of `url()`. Once I switched to `url()` it worked.

Thanks @taysea and @ShimiSun for the help! :)
