### ISSUE TITLE
[TypeScript] GapType should allow boolean false

### ISSUE THREAD

**Issue by tpinne** [grommet/grommet#3837]
We want to completely take over the styling of the RadioButtonGroup. Thats why we modify the RadioButtonGroup component via styled-components to get CSS grid behaviour. But then we have to get rid of the gap dom elements.
If one wants to disable the gaps for RadioButtonGroup you have to set `gap={false}` to not render them to the dom at all. Because if you set `gap={undefined}` the default value of RadioButtonGroup takes over.
But `gap={false}` throws a typing error.

### Expected Behavior

`gap={false}` is an allowed value for GapType

### Actual Behavior

TypeScript throws a typing error.

**Comment by ShimiSun** [comment]
Hi @tpinne, you can use `gap='none'` and should do the trick.
see this [example](https://v2.grommet.io/radiobuttongroup?c=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKRAb0QChLFEIEBnKRbOJgWXygAs4ATBogC8iANo1a5RLnQAjfLgBciAOQAxACoAFFQBpEAN3S4Q+Zeu0rEAX10TaZe5Noz5S1WpgFEAZQCeTPiYek7ORiZmHl74-oHBds62To7Ozq4K5ppaiABkiJ7esVBBIamS4aaZ2gDCcNh+pZJJALoA3NT0YEyIfPjA6CC4UFpsUJw8-MJS6e4WOvoVkXNW1u2Und2ii-oMXABqxqbNUwBK+OjQAHQguz5Q6MWEvf2Dw6PjvHzEa7QATlwgX5gQhOAA8J3QfHgACEQFAoAgAOK-OAgbBOADm6GwQhUYAQ+BUTjAWHwQgARL9IfByU46rBGEIyKwOFxPgxrE5FkzFpznAhqtx0GAMWSyPgDPgwMwhAA+RC7KAHCKECVSqCXe6-UUaxbEPmIAD0sokxEo1iAA).

**Comment by ShimiSun** [comment]
I've updated the docs to display the `gap='none'` option, thanks for raising the issue.

**Comment by tpinne** [comment]
Actually it doesn’t do the trick in the case, if you apply display: grid to the container. 
gap=„None“ renders dom elements with 0 height/width. But in a css grid these elements will be rendered into a column taking up space. 

That’s because the „if (gap) {...}“ in the box component always renders those gap Dom elements unless you provide „false“ and ignore the typescript error. 

I try to put a fiddle together sometime tomorrow.

**Comment by ShimiSun** [comment]
ok, thanks, looking forward to see your example code. And feel free to make a contribution to fix the issue, it seems like you have an idea where the issue might occur.

**Comment by tpinne** [comment]
Sorry for the delay, but here is a Sandbox demonstrating the problem I described if the RadioButtonGroup gets a custom Style with `display: grid` and the difference it makes between `gap={false}` and `gap="none"`.

But `gap={false}`  is not allowed in GapType https://github.com/grommet/grommet/blob/38866da3e67c852f99135634a07af135990bf1f5/src/js/utils/index.d.ts#L54 therefore breaking TS compiling.

https://codesandbox.io/s/loving-mcclintock-rfwvb

**Comment by ShimiSun** [comment]
Hi @tpinne, I filed a PR to fix the behavior of `none`, so we wouldn't need to allow boolean value  to `gap`.

**Comment by ShimiSun** [comment]
Thanks for reporting! This issue is fixed on the stable branch, feel free to try it out on by pointing your grommet package.json to "grommet": "https://github.com/grommet/grommet/tarball/stable" and let us know if it works as expected.
The fix will be officially available on our next official grommet release.
