### ISSUE TITLE
Bug with Calendar, dates and range

### ISSUE THREAD

**Issue by shovelmn12** [grommet/grommet#3844]
https://github.com/grommet/grommet/blob/1f8dece662dfa5034db12912903343f42a72cc89/src/js/components/Calendar/Calendar.js#L196

When setting `<Calendar dates={[date1,date2]} range />`
and then clicking another date in the calendar it resets the current selected dates.

I wasn't digging deep but my guess is because theres no update of lastSelectedDate it happens

UPDATE:

example - https://codesandbox.io/s/blazing-haze-q2c28
when you first select another date it resets the selected dates, maybe i am doing something wrong?

**Comment by ShimiSun** [comment]
Thank you for reporting! the fix will be available on our next official release (soon :) ).

**Comment by shovelmn12** [comment]
Sure no problems :)

just out of curiosity what what the issue? was it lastSelectedDate?

**Comment by ShimiSun** [comment]
@shovelmn12 you can check the PR that fixed it and attached to this issue #3907.
The fix is available on grommet v2.12.0.
