### ISSUE TITLE
FormField shows required even when value is set

### ISSUE THREAD

**Issue by bilak** [grommet/grommet#3846]
When I change the value of required field, then hit the submit of form form field is marked as required. This is correct behaviour. 
However when I cancel the form edit action and set the form to it's previous value, form field is still marked as required and its value is not present.

### Expected Behavior
When I cancel the edit operation the data should be present with previous data, like in codesandbox (see onCancelClick method).

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/festive-moser-ybzrn

### Steps to Reproduce

* hit edit button
* change value of email field
* hit save button
* hit cancel button

**Comment by ShimiSun** [comment]
Interesting issue, I havn't drilled into it much yet, but I'm wondering if different management of the functions would help this issue, for example using `useEffect` to update the userData and rerender. It looks like the userData has the correct values but not being re-rendered correctly.

**Comment by ShimiSun** [comment]
@bilak any news on this one? I'm thinking that since you are handling the edit/cancel behavior you are the one who can control the values on cancel.

**Comment by ShimiSun** [comment]
Hi buddy, I'll be closing this issue, feel free to reopen or file an updated issue after incorporating the feedback. thanks for reporting.
