### ISSUE TITLE
multiple frame/item carousel

### ISSUE THREAD

**Issue by negati-ve** [grommet/grommet#3850]
As I see from the examples, 
Grommet provides for a carousel that has a single item display at a given point in time

<img width="527" alt="image" src="https://user-images.githubusercontent.com/13253073/76697516-44a98080-66be-11ea-903a-b30c39d09d62.png">

Does the current grommet carousel have any option/configuration to produce a multi frame/item carousel? like so
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/13253073/76697535-702c6b00-66be-11ea-8117-6e9345c6bb64.png">

Thanks

**Comment by negati-ve** [comment]
it looks like grommet internally uses stacks to build the carousel

in that case, I just grouped the images (4 images in my case) into a box and inserted them into my carousel to get this multi slides view carousel effect 
`<Carousel play={5000}>
        <Box align="center"  direction="row" height="small">
          <Image src='//v2.grommet.io/assets/Wilderpeople_Ricky.jpg' />
          <Image src='//v2.grommet.io/assets/IMG_4245.jpg' />
          <Image src='//v2.grommet.io/assets/IMG_4210.jpg' />
          </Box>
          <Box align="center"   direction="row" height="small">
          <Image src='//v2.grommet.io/assets/Wilderpeople_Ricky.jpg' />
          <Image src='//v2.grommet.io/assets/IMG_4245.jpg' />
          <Image src='//v2.grommet.io/assets/IMG_4210.jpg' />
          </Box>
        </Carousel>`

**Comment by negati-ve** [comment]
grommet carousel is built using stacks.. 

only way to have multiple view per carousel view is to use images inside a box element.. 
better to use third party carousel lib if you are looking for more control

**Comment by dchen323** [comment]
I was able to have multiple views by chunking my data into an array of array where each inner array has up to 4 things for the number of items I wanted to display at a time.

https://codesandbox.io/s/hidden-rgb-gdc6x

**Comment by negati-ve** [comment]
@dchen323 
yup, that's the way to go with the current underlying carousel setup

I was looking for more control over the carousel with per item movement of carousel
