### ISSUE TITLE
Modify Form to support an array of FieldValues

### ISSUE THREAD

**Issue by mrcleanandfresh** [grommet/grommet#3853]
I would like to be able to have `Form` control an array of inputs. For instance, if I have a form where I am allowing a user to input multiple phone numbers.

### Expected Behavior

Originally I thought this would have worked by making the `name` of the controlled component with the index of the FieldValue. Something like `phones[0].number` which would be an object.

### Actual Behavior

It does not work like this, instead I have to implement my own array of FieldValues, and control them using external state.

### URL, screen shot, or Codepen exhibiting the issue

Here is my code sandbox with a [demonstration of the issue](https://codesandbox.io/s/formfield-arrays-l39ds).

### Your Environment

- Grommet version: 2.11.1
- Browser Name and version: Brave Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): macOS Catalina 10.15.3

**Comment by ShimiSun** [comment]
@ericsoderberghp idea for Forms

**Comment by ericsoderberghp** [comment]
Sounds reasonable. My inclination is to have FormContext.update() know how to translate a name like `person[0].name` into setting `value['person'][0]['name'] = value`.

**Comment by mrcleanandfresh** [comment]
Another use case that I have is I have checkboxes like this:
```
{trees.map((tree: any, index: number) => (
    <CheckBox
        key={tree.id}
        name={`treeIds[${index}]`}
        label={tree.name}
        onChange={(e) => handleAddOrRemoveTreeIds(tree.id, e)}
        checked={isChecked(tree.id)}
        value={tree.id}
    />
))}
```
When this data gets sent to me from the `Form` `onChange` prop, it is only a true or false. So I would suggest this change be made to support arrays of objects as well as arrays of primitive values like strings, numbers, etc.

**Comment by mrcleanandfresh** [comment]
> Sounds reasonable. My inclination is to have FormContext.update() know how to translate a name like `person[0].name` into setting `value['person'][0]['name'] = value`.

I'm using Lodash, not saying it's right or wrong, but this is what I'm doing right now:
```
    const handleFormChange = useCallback((newFormState) => {
        if (newFormState) {
            const cleanState = {};
            _.forIn(newFormState, (value, key) => {
                _.set(cleanState, key, value);
            });

            setFormState(cleanState);
        }
    }, [setFormState]);
```

**Comment by g4rry420** [comment]
Can I work on this issue ?

**Comment by jcfilben** [comment]
Go for it! @g4rry420

**Comment by jcfilben** [comment]
Closing since #5630 was merged
