### ISSUE TITLE
MaskedInput scroll bars goes back to the top

### ISSUE THREAD

**Issue by mrnguuyen** [grommet/grommet#3854]
### Expected Behavior
Scroll bar should stay within place inside the MaskedInput and show allow user to click an input at the bottom of the scroll.

### Actual Behavior
Scroll bar goes back to the top and does not allow user to click on the input at the bottom of the scroll.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/12700313/76793413-3de44180-6782-11ea-9713-f6f8dfb3d0c2.png)

Storybook: https://storybook.grommet.io/?path=/story/maskedinput--date

### Steps to Reproduce
Make the browser small enough to make the MaskedInput scrollable as shown in the screenshot above and try to click on the month 12.

### Your Environment
Web browser from storybook and grommet website

- Grommet version: latest
- Browser Name and version: chrome and latest
- Operating System and version (desktop or mobile): windows 10

**Comment by mrnguuyen** [comment]
Some issues that I am experiencing with this:
When I try to select the month (12) when the browser is minimized to the screenshot above with a scroll bar, the scroll bar goes back to the top the moment I try to click on 12.

**Comment by mrnguuyen** [comment]
![image](https://user-images.githubusercontent.com/12700313/76882511-0041f000-6838-11ea-869b-27a53a2eba6a.png)

**Comment by IanKBovard** [comment]
Looks like this pr caused the issue
https://github.com/grommet/grommet/pull/3776

hooks are causing renrenders on every mouseover.

**Comment by mrnguuyen** [comment]
@ShimiSun, how's the progress on this issue?

**Comment by ShimiSun** [comment]
The fix is available on the [stable branch ](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) and it will be officially published on our next release. Thanks for reporting!
