### ISSUE TITLE
Unable to disable autocomplete for search input box in firefox & chrome browser

### ISSUE THREAD

**Issue by techPackets** [grommet/grommet#386]
The autocomplete="off" doesn't work for `<SearchInput placeHolder=""" suggestions={this.state.suggestions} ...> `for both firefox & chrome. 

I've tried the solutions provided on web, none of them seem to work
I've also tried putting autocomplete="off" at the form & input field level. Still it doesn't work.

I am trying to implement an autosuggest autocomplete feature for my search module. On typing a search string in the search input box I get two autocomplete flyouts one by the browser other by the application code. 
![chromebug](https://cloud.githubusercontent.com/assets/3320053/12969398/d8d101c4-d0a5-11e5-9a33-5845d525cefe.PNG)

**Comment by bryanjacquot** [comment]
We will turn off autocomplete for SearchInput, Search, and NumberInput.
