### ISSUE TITLE
Select with valueKey not working as expected

### ISSUE THREAD

**Issue by mrcleanandfresh** [grommet/grommet#3864]
When I give `Select` an array of objects then use the `labelKey` and `valueKey` to try and display a really basic use-case across our app, it doesn't work.

### Expected Behavior

I would expect that if I defined the `labelKey` and `valueKey` that when I select an item from the dropdown, that when I receive an `onChanges` event from the `Form`'s context, that it would contain the properties value for the `valueKey` specified. For example, if `valueKey` was set to `id` and that id was `10` I would expect that to be the value. `{myField: 10}`

### Actual Behavior

It gives me the the label as the value `{myField: "Item Label"}`

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-select-issue-ol1p3

### Steps to Reproduce

1. Select an item from the dropdown
2. The JSON Data on the page will match the label of the selected item, and not be a numerical value.

### Your Environment

- Grommet version: 2.11.2
- Browser Name and version: Brave Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): macOS Catalina 10.15.3

**Comment by ericsoderberghp** [comment]
Part of the root cause of this is due to `Select` using `TextInput` internally and both trying to drive the form context.

**Comment by mrcleanandfresh** [comment]
I did notice the Select rendered a text input. In my case the value attribute is empty. The other part of the problem seems to be that the value attribute is what is displayed to the user, instead of a traditional `option` element where it has a label and a value. It’s not trivial for sure.

**Comment by ShimiSun** [comment]
Looks like this issue is fixed, feel free to reopen if needed.
