### ISSUE TITLE
[feature request] Add Box functionality to TableRow

### ISSUE THREAD

**Issue by bilak** [grommet/grommet#3865]
Currently the [TableRow](https://github.com/grommet/grommet/blob/master/src/js/components/TableRow/index.d.ts) does not contain properties of box like [TableCell](https://github.com/grommet/grommet/blob/master/src/js/components/TableCell/index.d.ts). Please add this functionality to `TableRow` also, it would be very helpful to use for example `onClick`, `hover` ...

### Your Environment
- Grommet version: 2.11.2

**Comment by ShimiSun** [comment]
Do you mean allowing the all column to be clickable? how would that work with TableCell behavior if both are clickable?

**Comment by bilak** [comment]
Would it be possible to decide on which element it should be clickable? So if I need click on row I will provide onClick on row and if I need it on cell, then I will provide in on cell? So basically it can't be enabled on both row and cell at the same time.

**Comment by bilak** [comment]
@ShimiSun eventually is in current version some workaround how to create row clickable?

**Comment by ericsoderberghp** [comment]
Have you taken a look at https://v2.grommet.io/datatable#onClickRow ? There is some extra stuff in DataTable to get row clicking to work well that TableRow doesn't participate in.

**Comment by bilak** [comment]
Well, I've created [example](https://codesandbox.io/s/goofy-frost-w1w50) maybe we can elaborate a little bit on it. 
First thing, yes dataTables `onClickRow` works like expected, however there are many issues with it. I'm always struggling with proper setup of `onMore`. With current setup there's error when data are duplicating. In other component where I'm using `DataTable` it's working correctly and I don't know what's the difference. 
Then if I click on a row there's blue border around entire table, can I disable it?
Also there's an error in console saying ```<div> cannot appear as a child of <tbody>.
    in div (created by StyledBox)
    in StyledBox (created by Box)```. So is `<Table>` intended for usage like this? 

And finally additional question regarding table - can I lock the table header to top so when I scroll it will stay at the top? In this case it would be helpful if I can lock `Hello World` part and also column names.

Thanks

**Comment by bilak** [comment]
Problem with data duplication  solved, on this example is used first page with index 1 instead of 0. 🤦‍♂
