### ISSUE TITLE
Set value of TextInput to undefined if no value prop is provided

### ISSUE THREAD

**Issue by petercpwong** [grommet/grommet#3872]
When no `value` prop is passed into a TextInput component, the value of the input should default to undefined - currently it's set to an empty string. This is especially problematic when working with libraries that require components to be uncontrolled (eg. react-hook-form).

### Expected Behavior

The default value of TextInput was undefined before hooks rewrite.

### Actual Behavior

The default value of TextInput is now an empty string after hooks rewrite.

### The code in question

https://github.com/grommet/grommet/blob/546e18c9fea9d4e888d6437cf39b1a3453f1eb0c/src/js/components/TextInput/TextInput.js#L361

### Proposed fix
```
value={renderLabel(value)}
```

- Grommet version: 2.11.0 and above
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Ubuntu 18.04

**Comment by ShimiSun** [comment]
Thank you for reporting, fix will be available on our next release or on the ongoing stable branch.
