### ISSUE TITLE
Make root element configurable for Drop/Layer containers

### ISSUE THREAD

**Issue by brentropy** [grommet/grommet#3881]
### Expected Behavior

I have a case where I need the container elements for `Drop`s and `Layer`s to be inserted somewhere other than `document.body`. There may be other uses, but my particular use cases is using grommet inside a shadow root (using [ReactShadow](https://github.com/Wildhoney/ReactShadow)). I am working on a browser extension where I need complete style isolation for UI rendered within inside any web page. For the most part grommet styled components work great in the shadow root, but because the Drop/Layer containers are rendered outside of the shadow root that don't have any styles. If those elements could instead be inserted in the shadow root it would be solved.

I would be happy to submit a PR for this, but wanted to get feedback first. My initial thoughts on this would be to add an optional `containerRoot` prop on `Grommet` which would use a context to make the container root available to child components. It would continue  to default to `document.body` so it would be a non-breaking change. I would create a `useContainer` hook so the components would not need to be aware of the context directly. The `getNewContainer` function in `utils/DOM.js` would take an optional param for the root. It could also default to `document.body` in case anyone is using it directly.

Would you be good with this being available in grommet? What are your thoughts on how I would attack it in a PR?

### Actual Behavior

Drop/Layer containers are always inserted in `document.body`.

### Demo

https://codesandbox.io/s/blissful-murdock-cbrer

### Steps to Reproduce

1. Use grommet inside a shadow root
2. Use a Drop/Layer component.

### Your Environment

- Grommet version: `2.11.2`
- Browser Name and version: `Firefox 74.0`
- Operating System and version (desktop or mobile): `Ubuntu 19.10`

**Comment by brentropy** [comment]
Since this was blocking me, I went ahead and got this working for me and submitted a PR (#3883). If this isn't the best way that's fine, but since I got it working for myself I figured I would share my solution.

**Comment by ShimiSun** [comment]
Thanks for reporting + fixing! awesome work
