### ISSUE TITLE
theme does not seem to get applied to the component

### ISSUE THREAD

**Issue by intelcoder** [grommet/grommet#3885]
I am trying to update header style with theme. However, it does not seem to get applied.
Also, not sure If I have to pass theme every time I create component or it applies to the all existing component if theme is set on root level. 
I looked up examples regards to theme and the example update anchor. 

```
const myTheme = {
  global: {
    font: {
      family: 'Roboto',
    },
  },
  body: {
    margin: 0
  },
  header: {
    background: 'red',
    height: '40px',
  },
}
```

  ```
<Provider store={store}>
        <Grommet theme={myTheme}>
          <Header />
          <Component {...pageProps} />
        </Grommet>
      </Provider>
```

Used 

 <Header pad="small">
      tes
 </Header>
### Expected Behavior

It should update header component style
### Actual Behavior
It did not apply any style.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
I don't think `header` is a valid key for the theme. Can you share what are you trying to do? 
The available keys would be found here  https://github.com/grommet/grommet/blob/master/src/js/themes/base.js

**Comment by intelcoder** [comment]
Thank you for the info @ShimiSun . I just want to apply custom css to the Header component.
I also tried with styled.  However I am getting   **Prop `className` did not match.** error. 
```
const AppHeader = styled(Header)`
  border-bottom: 1px solid ${props => props.theme.global.colors['light-1']};
`
```

**Comment by ShimiSun** [comment]
@intelcoder any feedback for us to improve the learning process?

**Comment by intelcoder** [comment]
I think it would be very helpful if Grommet's git page have more examples such as how to customize a component and  how to customize theme. Of course, people can go and see the code to know which field is available to change on theme but it will be nice to show those to the new user upfront.

Thank you for the maintaining this project!

**Comment by ShimiSun** [comment]
@intelcoder thanks for your input. we have storybook examples with Theme customizations  https://storybook.grommet.io/?path=/story/theme--focus. also, each component has a Custom story where you can see how its theme could be customized.
