### ISSUE TITLE
CheckBox 'required' prop does not work correctly with Form

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet#3891]
### Expected Behavior

`<Form>` `onSubmit()` should not be called if a `required` CheckBox is not selected.

### Actual Behavior

Given a `<CheckBox>` with prop `required={true}` inside a `<Form>`, the user is able to bypass the `required` logic by Selecting, then Unselecting, the CheckBox. 

### URL, screen shot, or Codepen exhibiting the issue

Codesandbox demo https://ge4kp.csb.app/Form
Codesandbox code https://codesandbox.io/s/grommet-sandbox-ge4kp (Form component)

### Steps to Reproduce

See Codesandbox example: 
1) Select checkbox
2) Unselect checkbox
3) Submit form (this works, but it shouldn't) 

### Your Environment

- Grommet version: 2.11.2

### Workaround

My workaround for this is to add a `validate` prop to the FormField:

```
validate={(value) => {
  if (!value) {
    return "You must select checkbox";
  }
  return undefined;
}}
```

**Comment by ShimiSun** [comment]
Fixed on recent release https://github.com/grommet/grommet/releases/tag/v2.12.0
Thanks for reporting!
