### ISSUE TITLE
FormField validate passing incorrect value from other FormField in Form

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet#3892]
### Expected Behavior

FormField validation should be based on its own value

### Actual Behavior

FormField is validating value from a different FormField

### URL, screen shot, or Codepen exhibiting the issue

Codesandbox demo https://oescm.csb.app/form
Codesandbox code https://codesandbox.io/s/formfield-validation-issue-oescm (see `Form` component)

### Steps to Reproduce

In demo link above,
1. Click submit before entering any data. It will show "required" for both.
2. Click CheckBox. It errors here.

If you look at the console logs, it seems to be passing the `true` from the CheckBox into the validation for the Username FormField. Username FormField expects a string but a boolean is being passed in. 

This only happens when the other FormField is left blank. 

### Your Environment

- Grommet version: 2.11.2

**Comment by ShimiSun** [comment]
Hi buddy, can you move the Grommet version to 2.11.3 and let us know if you still see the problem?

**Comment by markjackson02** [comment]
The behavior is different in 2.11.3 but there is still an issue. I created a new issue here https://github.com/grommet/grommet/issues/3896. Closing this one since it is outdated since 2.11.3 release.
