### ISSUE TITLE
Calendar not showing individual selected dates

### ISSUE THREAD

**Issue by eamrhein** [grommet/grommet#3893]
### Expected Behavior

When I click a date I can add it to my array of selected dates or remove it on a double click, but Individually selected dates are not highlighted at all in the calendar. Shouldn't all selected dates  be  highlighted in some way?
### Actual Behavior
only the current selected date is being highlighted

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-ff1wp

### Your Environment

- Grommet version: v2
- Browser Name and version:  google-chrome 82.0.4085.12
- Operating System and version (desktop or mobile):
Desktop Linux

**Comment by ShimiSun** [comment]
Thanks for reporting! The fix is available now on grommet v2.11.4
