### ISSUE TITLE
No Multi language support in grommet calendar 

### ISSUE THREAD

**Issue by Rashi-jain21** [grommet/grommet#3897]
The calendar component does not show the year, date, time, days, month in multi-language 
### Expected Behavior

The year, date, time, month, days label should be visible with the language we pass in the props

- Grommet version: V1 and V2
- Browser Name and version: all browser
- Operating System and version (desktop or mobile): desktop

**Comment by ShimiSun** [comment]
@IanKBovard let's take care of it as part of the I18N project. and provide Calendar as an example there.

**Comment by IanKBovard** [comment]
@Rashi-jain21 Just trying to understand your issue. Have you used the locales prop? Month and days of the week appears to change with it. I don't think calendar shows time. The only thing that does not change visually would be the year and day numbers. could you give me an example of what you want?

**Comment by IanKBovard** [comment]
@Rashi-jain21  the locale prop should handle your issue.
https://v2.grommet.io/calendar#locale
let me know if this is what you're looking for.

**Comment by IanKBovard** [comment]
```
<Calendar
  size="small"
  date={new Date().toISOString()}
  daysOfWeek
  onSelect={(date) => {}}
  locale="pt-br"
/>
```
this should do the trick

**Comment by IanKBovard** [comment]
@Rashi-jain21 Let me know if this answers your question, and we can close the issue.

**Comment by ShimiSun** [comment]
I'll be closing this issue, feel free to let us know if we can help with anything else.
