### ISSUE TITLE
FormField doesn't work with CustomComponent after updating to v2.11.3

### ISSUE THREAD

**Issue by hoshomoh** [grommet/grommet#3898]
### Expected Behavior
FormField should work with CustomComponent

### Actual Behavior

After updating to v2.11.3, after typing one character in a custom text input, I can no longer type any other character. After spending some time debugging, I noticed that by adding the `value` property to the `Form`  component fixes it. 

This, however, introduces a warning.

```Warning: Cannot update a component (`Form`) while rendering a different component (`TextInput`). To locate the bad setState() call inside `TextInput`, follow the stack trace as described in https://fb.me/setstate-in-render```

### URL, screen shot, or Codepen exhibiting the issue
![Screenshot 2020-03-30 at 03 08 04](https://user-images.githubusercontent.com/5657993/77866519-bd1e4e80-7233-11ea-974e-5cfb9d45dc69.png)

You can try it out here https://codesandbox.io/s/grommet-sandbox-vso4c. Try removing the value from From and notices that you can no longer type in the CustomComponent

### Steps to Reproduce

1. Add a CustomComponent to a FormField 
2. Make sure `value` property is not set for the Form
3. Try to type in the CustomComponent, this wouldn't work.
4. Add `value` to the Form component and you will be able to type
5. Open your console, reload and type again
6. You will see the warning message written above

### Your Environment

- Grommet version: 2.11.3
- Browser Name and version:  Chrome Version 80.0.3987.149 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): macOS Catalina version 10.15.3 (Desktop)

**Comment by forresthopkinsa** [comment]
Related: https://github.com/facebook/react/issues/18178

**Comment by ericsoderberghp** [comment]
Thanks for including the code sandbox, that helps to see what you are doing. I think the issue is that you don't have an `onChange` property in your custom `FormFieldText`. If I change` to be `onChange={onChange}` and remove the `value` from `Form`, it works.

**Comment by hoshomoh** [comment]
Thanks, @ericsoderberghp. Why should I have to pass an onChange my `customComponent`  when I am already handling the change event? I guess Grommet is using the event internally for something. 

The reason why I am leaving onValueChange is because I want the component to be controlled. I also tried this and it works too.

```
onChange={e => {
        onChange(e);
        onValueChange(e.target.value);
}}
```

**Comment by ericsoderberghp** [comment]
Who is `onValueChange` intended for?

The documentation for FormField `component` indicates that it is expecting `onChange` property, which aligns with how React works for `<input />` elements. https://v2.grommet.io/formfield#component

**Comment by myktra** [comment]
This *might* be a related issue: #3910. I noticed the sandbox demonstrating this issue is also using React 16.13.1 as of this comment.

**Comment by hoshomoh** [comment]
> Who is `onValueChange` intended for?
> 
> The documentation for FormField `component` indicates that it is expecting `onChange` property, which aligns with how React works for `<input />` elements. https://v2.grommet.io/formfield#component

`onValueChange` is intended for the parent component. In my case, I am using a controlled input which when value change I update the parent state, which is why I have passed an `onValueChange`  the get called when the input changes. 

Considering that Grommets explicitly wants an `onChange` with no custom code, I see no other way no approach this than to call both functions when the input changes.

**Comment by hoshomoh** [comment]
But also when I do what you suggested I still get that warning in the console.

<img width="551" alt="Screenshot 2020-04-02 at 18 33 08" src="https://user-images.githubusercontent.com/5657993/78274437-82a50200-7510-11ea-995c-3a58c187f8d8.png">

```
import React, { useState } from "react";
import {
  Box,
  Button,
  CheckBox,
  Form,
  FormField,
  TextInput
} from "grommet";

const FormFieldText = ({
  name,
  placeholder,
  ariaLabel,
  value,
  onChange = () => {}
}) => (
  <Box fill="horizontal" direction="row" align="center">
    <TextInput
      plain
      type="text"
      name={name}
      placeholder={placeholder}
      aria-label={ariaLabel}
      value={value}
      onChange={onChange}
    />
  </Box>
);

const Main = () => {
  const [name, setName] = useState();

  return (
    <Form onSubmit={({ value }) => console.log("Submit: ", value)}>
      <FormField
        label="Full Name"
        name="full_name"
        placeholder="Max Mustarmann"
        value={name}
        onChange={e => setName(e.target.value)}
        component={FormFieldText}
      />
      <Button type="submit" label="Submit" primary={true} />
    </Form>
  );
};

export default Main;
```

**Comment by hoshomoh** [comment]
Any update on this issue?

**Comment by ShimiSun** [comment]
I think this issue is fixed on the latest release, can you please verify?

**Comment by hoshomoh** [comment]
Will do so today. Thanks for the update.

**Comment by hoshomoh** [comment]
The initial error reported doesn't seem to happen anymore, however, I get a new console error regarding changing an uncontrolled input of type text to be controlled.

See sample component https://codesandbox.io/s/grommet-sandbox-g7564?file=/src/CustomFormField.js

**Comment by ericsoderberghp** [comment]
The warning in the above sandbox is due to: `const [name, setName] = useState();` not specifying an initial value. If I change that line to be `const [name, setName] = useState('');` instead, the warning is removed. This is due to `name` now having an initial value of '' instead of undefined.

**Comment by hoshomoh** [comment]
Thanks, @ericsoderberghp and @ShimiSun
