### ISSUE TITLE
Not a good sales pitch: broken Search field on Component page (iOS)

### ISSUE THREAD

**Issue by mosesoak** [grommet/grommet#3899]
### Expected Behavior

From mobile Safari or the iOS Google app, the component Search textfield should open the keyboard and allow typing

### Actual Behavior

Selecting the field closes the Search dialog unexpectedly

Sidebar: Evaluating component libraries for a new project and was very interested in Grommet but, the first two hits were this malfunctioning input and seeing a sandbox with a Select that didn’t properly update its own state. Impression so far: good design choices but potentially very buggy. (Still. If this is a community project that’s managing to compete with the big players in this space, I commend your effort! And will still consider it. But fix that broken Search - it makes for a terrible first impression!)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
This issue should be moved to the grommet-site repo.

**Comment by jcfilben** [comment]
Moved issue to https://github.com/grommet/grommet-site/issues/180. We should be able to close this issue

**Comment by IanKBovard** [comment]
I believe we can close this issue as @jcfilben has moved this to the appropriate repo.
