### ISSUE TITLE
Search input drop down list gets displaced when resized

### ISSUE THREAD

**Issue by saumildharia** [grommet/grommet#390]
When the search input drop down list is open, if we try to re-size the browser  to 600 X 960 or till we get rid of the left pane, the drop down list gets displaced and appears to the left top of the screen.

![image](https://cloud.githubusercontent.com/assets/9210001/12986442/23e05556-d0ac-11e5-95ee-608890c8b273.png)

**Comment by jwijay** [comment]
resolved in PR: https://github.com/grommet/grommet/pull/433
