### ISSUE TITLE
Typescript Definitions for Border Array Side Property incorrect

### ISSUE THREAD

**Issue by MLRichmond** [grommet/grommet#3900]
This commit: https://github.com/grommet/grommet/commit/287a1149b8801df5a530abeaf85b6cfd9357d7f3#diff-ddf307fc1f06868a6ec4f6c34025e65e

Broke the BorderType property when using an array of borders.

`export type BorderType = boolean | BoxSideType | {color?: ColorType, side?: BoxSideType, size?: BoxSizeType, style?: BoxStyleType} | ({color?: ColorType, **side?: BoxStyleType**, size?: BoxStyleType, style?: BoxStyleType})[];`

### Expected Behavior

Should be allowed to provide a BoxSideType for the side property when using an array.

### Actual Behavior

Array borders expect a BoxStyleType as the side.

### Your Environment

- Grommet version: 2.11.0

**Comment by ShimiSun** [comment]
@MLRichmond do you want to try making a contribution? seems like you already found where is the issue.

**Comment by MLRichmond** [comment]
@ShimiSun Sure. I have the fix on a local branch.

**Comment by ShimiSun** [comment]
@MLRichmond let's put it on a PR 🎉

**Comment by MLRichmond** [comment]
See [PR 3912](https://github.com/grommet/grommet/pull/3912)

**Comment by ShimiSun** [comment]
This fix will be available on our next official release, and is now available on the stable branch "https://github.com/grommet/grommet/tarball/stable", you can change your package.json  to point to the stable branch and enjoy the fix now.
