### ISSUE TITLE
Router example exported from designer––onpopstate not working properly

### ISSUE THREAD

**Issue by gabroo** [grommet/grommet#3902]
I am running a single page app with client side routing. It is deployed on Firebase.

### Code in Question
After exporting my design from the designer studio I found a useful router using React hooks:
```
const RouterContext = React.createContext({})

const Router = ({ children }) => {
  const [path, setPath] = React.useState(document.location.pathname)

  React.useEffect(() => {
    const onPopState = () => {
      console.log('in pop')
      setPath(document.location.pathname)
      console.log(document.location.pathname)
    } 
    window.addEventListener('popstate', onPopState)
    return () => window.removeEventListener('popstate', onPopState)
  }, [])

  const push = nextPath => {
    if (nextPath !== path) {
      window.history.pushState(undefined, undefined, nextPath)
      setPath(nextPath)
      window.scrollTo(0, 0)
    }
  }

  return (
    <RouterContext.Provider value={{ path, push }}>
      {children}
    </RouterContext.Provider>
  )
}
```

### Expected Behavior

I expect the `setState` statement in the `onPopState` function in the `useEffect` statement to work.

### Actual Behavior

I get `TypeError: n is not a function`. It seems that the `setPath` function given by `useState` is not defined after the pop event.

### URL, screen shot, or Codepen exhibiting the issue

<img width="418" alt="ss 2020-03-30 at 11 24 03 PM" src="https://user-images.githubusercontent.com/6046841/77993955-0925cd80-72de-11ea-9e6c-0435b54c0fe5.png">

**Comment by ShimiSun** [comment]
I'm thinking it will be better to file the issue under the grommet-designer repo, and not on grommet.

**Comment by gabroo** [comment]
Ok thanks @ShimiSun
