### ISSUE TITLE
Filter "Not inline" radio button

### ISSUE THREAD

**Issue by tomtosi** [grommet/grommet#391]
Can the draft version of the Filter "Not inline" with checkboxes (http://index.grommet.io/docs/grommet-index/filter) be adapted to create a version of the same control using radio buttons (i.e. single-select)?
![image](https://cloud.githubusercontent.com/assets/17185641/12990518/d0aa4310-d0d8-11e5-814c-c3653d261e41.png)

**Comment by bryanjacquot** [comment]
@tomtosi, can you please submit this issue against the grommet-index project?  https://github.com/grommet/grommet-index/issues/new
