### ISSUE TITLE
DataTable: The sorted column arrow is always pointing up.

### ISSUE THREAD

**Issue by alexzicat** [grommet/grommet#3916]
While the column is still being sorted, the arrow beside the column name is always pointing up.

### Expected Behavior
The arrow should be pointing up or down depending if the sort direction is ascending or descending.

### Actual Behavior
The arrow is always pointing up.

### URL, screen shot, or Codepen exhibiting the issue
![Grommet V2 - DataTable issue](https://user-images.githubusercontent.com/6243503/78313940-6613c480-7526-11ea-8935-f81804f17227.gif)

### Steps to Reproduce

1. Render a DataTable.
2. Use the sortable prop.
3. Click on the column name multiple times.

### Your Environment

- Grommet version: 2.11.2
- Browser Name and version: Chrome 80.0.3987.163
- Operating System and version (desktop or mobile): macOS Mojave 10.14.6

**Comment by ShimiSun** [comment]
Thanks for reporting, a PR is in process.
