### ISSUE TITLE
TextInput value is not changing when provided default value property in form

### ISSUE THREAD

**Issue by rohitkedari** [grommet/grommet#3925]
TextInput value is not changing when provided initial value in the value property of form
`<Form value={{name: 'test'}}>...</Form>`

This was working in 2.11.3 but broken later.

### Expected Behavior

When initial value is provided in form then, user should able change it by typing/updating it.

### Actual Behavior

When we try to type new value in text input still old value is displayed.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=form&module=%2Fsrc%2FForm.js

Above is the code sandbox url from the form documentation.

### Steps to Reproduce

1. Open sandbox url https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=form&module=%2Fsrc%2FForm.js
2. Add value property to form as follows:
value={{ name: 'test' }}
3. Now try to type any value in name text field, typed data not reflecting.

### Your Environment

- Grommet version: 2.12.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by ericsoderberghp** [comment]
When `<Form />` is passed a `value`, it operates like a [controlled component](https://reactjs.org/docs/forms.html#controlled-components). You must update some state in the caller via an `onChange`.

**Comment by IanKBovard** [comment]
@rohitkedari eric is correct. The field will not change because you're providing a static value to it. What you're experiencing isn't a bug, but an issue with implementation. Did you want to use it as an uncontrolled component?

**Comment by rohitkedari** [comment]
Thank You Eric, Ian.
