### ISSUE TITLE
Image component - a11yLabel doesn't produce aria-label

### ISSUE THREAD

**Issue by codeinaire** [grommet/grommet#3930]
The Image component is meant to produce an aria-label when the a11yTitle prop is used. However, none is produced.
### Expected Behavior
Aria label should be produced in the HTML `img` element.

### Actual Behavior
Aria label isn't produced.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-sandbox-6czt8

### Steps to Reproduce

1. Inspect the image in the codesandbox and you'll see there's an `aria-lable` produced b/c of the `aria-label` prop, but there's not `aria-label` for the `a11yTitle` prop.

### Your Environment

- Grommet version: 2.4.0
- Browser Name and version: Firefox developer edition 75.0b12
- Operating System and version (desktop or mobile): OSx

**Comment by ShimiSun** [comment]
Thanks for reporting, a PR is ready.
