### ISSUE TITLE
FormField - Allow FormField to have focus and border colors be set independently and displayed simultaneously

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#3932]
Would like FormField to have both a border color, plus focus. A scenario would be when I have a border color set for validation, but would like to have focus when the user is interacting with that FormField.

Currently, focus color overrides the border color. Do not have the ability to display both simultaneously.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
https://designer.grommet.io/button?id=HPE-design-system-taylor-seamans-hpe-com

**Comment by taysea** [comment]
Designer can be used to view how grommet is currently behaving: https://designer.grommet.io/textinput?id=HPE-design-system-taylor-seamans-hpe-com

**Comment by ShimiSun** [comment]
Fixed on https://github.com/grommet/grommet/pull/4018, ready on the stable branch.
