### ISSUE TITLE
Passing callback ref to Select prevents dropdown from opening

### ISSUE THREAD

**Issue by jasnross** [grommet/grommet#3942]
When passing a callback ref to the Select component it prevents the select dropdown from opening. Other form field components (such as TextInput and TextArea) seem to work with a callback ref, but not Select. If I pass a standard ref (not a callback) then it also works properly.

### Expected Behavior

When passing a callback ref to Select the Select box should still open a dropdown when clicking it.

### Actual Behavior

The Select dropdown does not open when clicking the Select box when a callback ref is used.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/throbbing-sun-6fl10?file=/src/App.js

### Steps to Reproduce

Open the CodeSandbox above and confirm the Select box dropdown will not open. Removing the ref attribute from Select will restore the dropdown functionality.

### Your Environment

- Grommet version: 2.12.0
- React version: 16.12.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Desktop

**Comment by ShimiSun** [comment]
Thanks for reporting buddy!
