### ISSUE TITLE
SearchInput className, icon change

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#395]
Hello,
What is your opinion on InputSearch modification so it would support icon change from the props and className prop merge? I am also wondering when should one use Search and SearchInput?
Cheers
Primoz

**Comment by ericsoderberghp** [comment]
Could you provide an example of when you would want to change the icon?

Originally, Search was meant for more standalone scenarios, such as global site search in a banner/header while SearchInput was meant as an enhanced means of filling our an input field in a form. Over time their functionality has merged a bit. One area where they still differ is that Search will handle responsive situations by reducing to an icon and then expanding to show the input in a drop layer on focus.

**Comment by primozs** [comment]
Thank you for explanation. For the use case: with fixed "suggestions", SearchInput looks a lot like nice "advanced" select box or "search select" box but icon should be replaceable. Icon could be "down", "caret-down" or something else ...

**Comment by bryanjacquot** [comment]
If the set of suggestions is fixed, have you considered using a standard HTML `<select>` control?  That control uses a down icon.  You can examples on the form page: http://www.grommet.io/docs/hpe/develop/form

**Comment by primozs** [comment]
@bryanjacquot Beside select options to have also autocomplete options, I had in mind something like this. https://github.com/JedWatson/react-select To make an example for myself I modified SearchInput to change icon. The next thing would be "x" button to remove current selection!

**Comment by bryanjacquot** [comment]
@primozs, we are considering merging the current SearchInput and Search components as there's a lot of similarities.  Then we'd add a new Select component and make it operate more like Search Input and the react-select project you referenced.  What elements of the react-select project were you looking at?  That's a pretty comprehensive component that I don't think we need all of those capabilities.  Interesting in your perspective.

**Comment by ericsoderberghp** [comment]
We have deprecated SearchInput in favor of Select and TextInput.
