### ISSUE TITLE
Incomplete Type Definitions

### ISSUE THREAD

**Issue by avin-kavish** [grommet/grommet#3951]
Types are mostly incomplete with `{}` being used liberally where better types could be used. Would you accept a PR fixing this?

**Comment by avin-kavish** [comment]
Why is this issue ignored while others are getting attention?

**Comment by ShimiSun** [comment]
Sorry, we might have missed, PRs will be more than welcome!! THANK YOU!

**Comment by ShimiSun** [comment]
Thank you for your contribution! Feel free to open more issues to improve our TS behavior.
