### ISSUE TITLE
Adding an icon to anchor adds margin

### ISSUE THREAD

**Issue by 132041** [grommet/grommet#3953]
### Expected Behavior

Having icons in <Anchor /> should generate same height of anchor as the height of the icon or label (whatever is the tallest).

### Actual Behavior

It creates an additional whitespace below the icon.

### URL, screen shot, or Codepen exhibiting the issue

Screenshot:
<img width="404" alt="Screenshot 2020-04-12 at 22 45 13" src="https://user-images.githubusercontent.com/6842487/79079421-4ee78a80-7d0f-11ea-98e0-c2ec6394766e.png">

Codesandbox:
https://codesandbox.io/s/grommet-v2-template-izo72?file=/index.js

### Steps to Reproduce

    import React, { Component } from "react";
    import { render } from "react-dom";
    import { grommet, Grommet, Box, Anchor } from "grommet";
    import { MailOption } from "grommet-icons";

    class App extends Component {
      render() {
        return (
          <Grommet theme={grommet}>
            <Box gap="medium">
              <Box background="red">
                <Anchor
                  label="With icon"
                  onClick={() => {}}
                  icon={
                    <Box background="blue">
                      <MailOption color="green" />
                    </Box>
                  }
                />
              </Box>
              <Box background="red">
                <Anchor label="Without icon" onClick={() => {}} />
              </Box>
            </Box>
          </Grommet>
        );
      }
    }

    render(<App />, document.getElementById("root"));

### Your Environment

- Grommet version: v2
- Browser Name and version: Chrome and Safari
- Operating System and version (desktop or mobile): Desktop

**Comment by ShimiSun** [comment]
Hi buddy, what version of Grommet are you using?

**Comment by 132041** [comment]
Hey! I use 2.12.0

**Comment by IanKBovard** [comment]
@132041 A margin is not being added. The default behavior for inline-block components like <svg> is to add space for text with character decenders like lowercase 'y' or 'g'. This behavior can be removed, but im not sure if it is wanted or not.

**Comment by IanKBovard** [comment]
This issue can be closed. This is the default behavior of inline-block components.
