### ISSUE TITLE
DE1347: UI: Grommet version changes 

### ISSUE THREAD

**Issue by Priya-Koushik-L** [grommet/grommet#3954]
Below are the details of issues due to new grommet changes.

1. Indication of Hyperlink for instance ID is missing in new grommet changes
Before
![image](https://user-images.githubusercontent.com/51032161/79094459-3f029180-7d75-11ea-891d-87db9caf661a.png)

after
![image](https://user-images.githubusercontent.com/51032161/79094556-91dc4900-7d75-11ea-8805-8c3eb1b1cc44.png)

2. “Service Instances” page is not auto scaling according to screen resolution, which has scroll bar at below.

3.The “Services” and “Service Instances” pages are too bold
Before
![image](https://user-images.githubusercontent.com/51032161/79094590-aae4fa00-7d75-11ea-9382-1f6433a3dcf1.png)
After
![image](https://user-images.githubusercontent.com/51032161/79094614-bd5f3380-7d75-11ea-8de9-71d8fcdb8a50.png)

4. Every font is larger than before

Before
![image](https://user-images.githubusercontent.com/51032161/79094656-d7007b00-7d75-11ea-8e5d-337ab42894f6.png)
After
![image](https://user-images.githubusercontent.com/51032161/79094672-e2ec3d00-7d75-11ea-9ed4-e6098f4fad96.png)

5. Table in Service Instances page is not aligned properly.

Before
![image](https://user-images.githubusercontent.com/51032161/79094690-f4cde000-7d75-11ea-9425-2bb30112d380.png)
After
![image](https://user-images.githubusercontent.com/51032161/79094707-fe574800-7d75-11ea-89dc-3245c4622d10.png)
6.The widget or the page highlights with Green border for all the actions selected.

![image](https://user-images.githubusercontent.com/51032161/79094798-45453d80-7d76-11ea-814f-12118119b699.png)

7. The service instances button is overlapping with Action and is clickable only on edges at 100% resolution. Seeing this issue in integration only and not in production.

![image](https://user-images.githubusercontent.com/51032161/79094814-568e4a00-7d76-11ea-944c-01eaca8b76b5.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
    "grommet": "^2.10.0",
    "grommet-icons": "^4.2.0",
    "grommet-theme-hpe": "^1.0.0",
- Browser Name and version: chrome, Version 80.0.3987.149 
- Operating System and version (desktop or mobile): desktop

**Comment by ShimiSun** [comment]
Hi Priya,
Each github issue has a template the submitter need to fill in order to help us with the investigation and suggest a solution. 
Your issue doesn't specify which grommet version you were using before and after the upgrade, so it will be hard for us to understand which code is relevant.
In addition, reading through bullet number one, is it possible you are confusing the Grommet library upgrade with the theme upgrade?
Please elaborate so we could understand the issue.

**Comment by MikeWalrath** [comment]
@Priya-Koushik-L  any update on the above questions? We would like help but will need the additional information before we can get to the root of the issue.

**Comment by Priya-Koushik-L** [comment]
> Hi Priya, thanks for reporting.
> Each github issue has a template the submitter needs to fill, in order to help us with the investigation.
> Your issue doesn't specify which grommet version you were using before and after the upgrade, so it will be hard for us to understand which code is relevant.
> In addition, reading through bullet number one, is it possible you are confusing the Grommet library upgrade with the theme upgrade?
> Please elaborate so we could understand the issue.

About the first point, we were able to make a difference in appearance whether its a hyperlink or not, now its seen as simple text where user wont be able to know its clickable or not

**Comment by ShimiSun** [comment]
>About the first point, we were able to make a difference in appearance whether its a hyperlink or not, now its seen as simple text where user wont be able to know its clickable or not

From what you are describing this change is coming from the theme upgrade and not from grommet, correct? 
can you share what versions you are using?
We can get a quicker turnaround if the information would be elaborative.

**Comment by Priya-Koushik-L** [comment]
> > About the first point, we were able to make a difference in appearance whether its a hyperlink or not, now its seen as simple text where user wont be able to know its clickable or not
> 
> From what you are describing this change is coming from the theme upgrade and not from grommet, correct?
> can you share what versions you are using? the package.json you shared doesn't specify the actual version only the lower version that is optional ( since you are using the Caret^).
> Make sure you are using **version v1.0.5 for grommet-theme-hpe** and let us know if it works.
> 
> We can get a quicker turnaround if the information would be elaborative.

caret version make sure that it will be updated automatically to the latest.

**Comment by ShimiSun** [comment]
> caret version make sure that it will be updated automatically to the latest.

Caret is giving you the option to update to the latest but the lock files are determining the version that is being used.
If you delete the lock files and the node_modules/grommet-theme-hpe, and rebuild your project, you supposed to see the behavior as expected. keep us posted.

**Comment by IanKBovard** [comment]
@Priya-Koushik-L Have you tried ShimiSun's suggestions? If you are still having issues, maybe I can help as well.

**Comment by MikeWalrath** [comment]
@Priya-Koushik-L we would like to continue to make progress on the issue. Did Shimis suggestions help?

**Comment by ShimiSun** [comment]
Feel free to reopen the issue if you have helpful information for us to continue with the investigation process.
