### ISSUE TITLE
Calendar body width issue when custom global size is provided

### ISSUE THREAD

**Issue by shivs077** [grommet/grommet#3959]
I'm using a custom theme for my project. So, when I'm overriding the "global.size.medium" property (256px), the Calendar body is getting a width greater than that, and as a result some of the days aren't visible (as Calendar body's overflow is set to hidden), while at the same time Calendar header adjusts perfectly.
The only workaround I've found is by manually reducing the "daySize" width. ( "calendar.medium.daySize"). It would be nice if someone could suggest a better approach if any.
Thank you.

### Expected Behavior
The Calendar width should adjust to the provided size.

### Actual Behavior
The Calendar body is overflowing and because of that some of the days aren't visible. 

### URL, screen shot, or Codepen exhibiting the issue

 Here's a Codesandbox template that serves as a nice starting point
for demonstrating an issue: https://codesandbox.io/s/grommet-calendar-size-tybyn

### Steps to Reproduce

Open the CodeSandbox above and confirm the overflowing Calendar body. Uncommenting the "calendar.medium.daySize" code from theme object will make the calendar body fit nicely inside its parent.

### Your Environment

- Grommet version: 2.12.0
- Browser Name and version: Chrome & Edge
- Operating System and version (desktop or mobile): Desktop Win10

**Comment by IanKBovard** [comment]
@shivs077 I think yours is the best solution. It looks like if you plan on changing global.size of the calendar you should appropriately adjust the other sizes to match as well.

**Comment by shivs077** [comment]
Seems fair. Thanks.
