### ISSUE TITLE
Search Input:  selected item should be highlighted in the drop down menu

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#396]
Selected item 'three', close the drop down menu.
Open it again.  Expect to see 'three' highlighted in the drop down menu
![image](https://cloud.githubusercontent.com/assets/13039669/13120895/a3aaaf40-d564-11e5-9dcb-f9390bf81293.png)

**Comment by bryanjacquot** [comment]
Agree.  The selection should be highlighted.

**Comment by jwijay** [comment]
PR: https://github.com/grommet/grommet/pull/435
