### ISSUE TITLE
TypeScript: Avatar only accepts AvatarProps and BoxProps and no props for standard DIV elements

### ISSUE THREAD

**Issue by tpinne** [grommet/grommet#3968]
### Expected Behavior

The Avatar component should accept all props/attributes for standard DIV elements like the Box component does.

### Actual Behavior

The Avatar component does not accept standard props/attributes from DIV elements like for example `title`.

### Steps to Reproduce

Try to use an Avatar component with `title="something"`.

### Your Environment
- Grommet version: 2.12.0

### Possible Fix (untested)
Extending additionally `JSX.IntrinsicElements['div']` should do the trick.

**Comment by ShimiSun** [comment]
Fixed, thanks for reporting.
