### ISSUE TITLE
A trivial function imported from polished is adding 10kb to bundlesize

### ISSUE THREAD

**Issue by avin-kavish** [grommet/grommet#3976]
The rgba function, which essentially does nothing is the only import from `polished` and adds 10kb to the bundle.

It's used in situations like, 

```js
import { rgba } from 'polished';

const colors = {
  active: rgba(221, 221, 221, 0.5),
}
```

which can simply be replaced with the equivalent string, `rgba(221, 221, 221, 0.5)`.

https://bundlephobia.com/result?p=polished@3.5.1

![image](https://user-images.githubusercontent.com/48435155/79688486-4097f200-826c-11ea-8a94-969b08a1f0fe.png)

**Comment by ShimiSun** [comment]
Thank you for the analysis!! we'll need to take a look at that.

**Comment by avin-kavish** [comment]
No worries. Actually, I missed one situation where `rgba` seems to be needed very much.  https://github.com/grommet/grommet/blob/ab402dd96c0e402d1cfd8de2de9892b3b8ab11f3/src/js/themes/base.js#L802

**Comment by ShimiSun** [comment]
Yea, it is helpful when we need the opacity to translate.
Any other alternatives?

**Comment by avin-kavish** [comment]
Hmm... do you know the return format of this function? `normalizeColor('border', props.theme)`

**Comment by ShimiSun** [comment]
Adding @ericsoderberghp to see if there is additional info that we should account for.

@avin-kavish feel free to share a PR if you already have something in mind.

**Comment by g4rry420** [comment]
Can I work on this issue ?

**Comment by taysea** [comment]
Closed by https://github.com/grommet/grommet/pull/5255
