### ISSUE TITLE
Search input:  should we have counter?

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#398]
If the search results in a large number of items, should we limit the number of displayed items?
If we do, then should we have a counter listed how many items found, and how many are displayed?

**Comment by bryanjacquot** [comment]
We'd like to avoid adding the counter to keep the content to a minimum.  If there's a specific scenario where we must have the counter, then we'd like to discuss further.

**Comment by tran2519** [comment]
We currently have use cases where the search results in a list of more than a hundred items.  We just display 50 out of total, and load more pages when users scroll down.

**Comment by bryanjacquot** [comment]
Search suggestions should be kept relatively small, in the ballpark of 5-10 ideally, but it could be as high as 40.  Beyond that, the user should be encourage to type a few characters to limit the size of the list, rather than scrolling through pages of items in a search suggestion list.
