### ISSUE TITLE
Invalid PropType 'background' supplied to Box

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#3981]
### Expected Behavior

I should be able to supply Box with a background where the color property is an object and not receive a PropType warning.
```
background: {
  color: {
     dark: 'yellow',
     light: 'blue',
  },
}
```

### Actual Behavior

Receive the following console warning:
"Warning: Failed prop type: Invalid prop `background` supplied to `Box`."
![Screen Shot 2020-04-20 at 3 28 04 PM](https://user-images.githubusercontent.com/1756948/79803117-9a58f480-831e-11ea-89d3-d25206588435.png)

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-background-proptype-0o3lx?file=/src/App.js

### Steps to Reproduce

```
import React from "react";
import { Grommet, Box } from "grommet";

function App() {
  return (
    <Grommet>
      <Box
        background={{
          color: {
            dark: "yellow",
            light: "blue"
          }
        }}
        height="small"
        width="small"
      />
    </Grommet>
  );
}

export default App;
```

### Your Environment

- Grommet version: 2.13.0 as well as /Stable
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by halocline** [comment]
I will have a fix PR shortly.

**Comment by ShimiSun** [comment]
Thanks!
