### ISSUE TITLE
DataTable produces duplicate keys (v2.13 and v2.12)

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#3987]
### Expected Behavior

`DataTable` must generate rows with unique keys.

### Actual Behavior

The row's key value is [object Object], so they are all the same.

> This looks like it was also a problem in 2.12, but it was masked by "first" and "last" rows having unique keys.  Since my table only had 3 rows, each row was created with a unique key.

#### v2.13 Duplicate Keys

 Note: key val of each row is [object Object]

![image](https://user-images.githubusercontent.com/8231064/79818984-66d4a380-83cc-11ea-9d09-a86cb0153d6b.png)
---
#### v2.12:

Note: The key val was still [object, object], but it was masked since the first and last rows were keyed uniquely, so my middle row key was also unique.  So this masked the problem in v2.12.
 
![image](https://user-images.githubusercontent.com/8231064/79819037-87046280-83cc-11ea-9198-237ca0f9f233.png)

### Steps to Reproduce

This is how my DataTable is rendered:

```
  return (
    <DataTable
      pad={{ vertical: 'xxsmall', horizontal: 'xxsmall' }}
      caption="Addresses"
      columns={columns}
      data={protocolAddresses}
    />
  );
```

### Your Environment

- Grommet version: v2.13 (problem was masked in v2.12)
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): W10 desktop.

**Comment by IanKBovard** [comment]
@LiveFreeAndRoam could you give me an example of what your data looks like? I think i see the problem.

**Comment by LiveFreeAndRoam** [comment]
Hi Ian,

Here is the `console.log` of `columns` and `protocolAddresses`.  NOTE: the raw `protocolAddresses` is formatted by wrapping the raw data with Grommet components.

#### `columns`
```
columns: Array(2)
0: {property: "protocol", primary: true}
1: {property: "address"}
length: 2
```

#### `protocolAddresses` (raw data)
```
0: {protocol: "MAC", address: "94:40:c9:d6:04:2f"}
1: {protocol: "IPv4", address: "10.229.130.43"}
2: {protocol: "IPv6", address: "Stateful"}
length: 3
```

#### `protocolAddresses` data wrapped with Grommet components

_This is the `DataTable data` that gets rendered..._
```
0:
address: {$$typeof: Symbol(react.element), key: null, ref: null, props: {…}, type: ƒ, …}
protocol: {$$typeof: Symbol(react.element), key: null, ref: null, props: {…}, type: ƒ, …}
__proto__: Object
1:
address: {$$typeof: Symbol(react.element), key: null, ref: null, props: {…}, type: ƒ, …}
protocol: {$$typeof: Symbol(react.element), key: null, ref: null, props: {…}, type: ƒ, …}
__proto__: Object
2:
address: {$$typeof: Symbol(react.element), key: null, ref: null, props: {…}, type: ƒ, …}
protocol: {$$typeof: Symbol(react.element), key: null, ref: null, props: {…}, type: ƒ, …}
__proto__: Object
length: 3
```

And here is the rendered content...

![image](https://user-images.githubusercontent.com/8231064/79964362-edbd7500-84cd-11ea-9c15-c976908f7b02.png)

Matt.

**Comment by LiveFreeAndRoam** [comment]
In case it helps...

Each raw `protocolAddresses` element is wrapped as:
```
<Heading margin="none" level="6">{protocol}</Heading>

<Text size="small">{address}</Text>
```

**Comment by IanKBovard** [comment]
Thanks, thisll help me figure this out

**Comment by IanKBovard** [comment]
@LiveFreeAndRoam Sorry for the wait. Hopefully, I understand your issue.

My guess is that this will fix your problem.
https://v2.grommet.io/datatable#columns :: check out the render prop for custom rendering of the row.

Something, like this.
```
  {
    property: 'protocol',
    render: datum => (
      <Box>
        {datum.protocol}
      </Box>
    ),
  },
```
Let me know if this helps.

**Comment by IanKBovard** [comment]
if you dont wrap your data with grommet components, does the error still appear?

**Comment by LiveFreeAndRoam** [comment]
@IanKBovard, your suggestion to use the `render` property worked! Thank you.

As I think about this a moment longer and ponder how I might have avoided this, perhaps the doc can be enhanced?  E.g. in the `data` property documentation, emphasize that the `data` object values must not be JSX?

I was mistakenly expecting that if the `data` value was a JSX object, then the `DataTable` component would render it without me needing the `column render` property.  In fact, it *is* rendered correctly, except the console displays the duplicate keys warning.

This one can be closed.

**Comment by IanKBovard** [comment]
Not sure if this needs an update to the documentation. 

> Use 'render' for custom formatting for things like currency and date or to display rich content like Meters.
 
can be found in columns prop documentation.

data's documentation states.

> Array of data objects.

I think that the omission that data doesn't take React components is enough.

I could add something like this to data.

> Array of data objects. If you want to render custom components use the render function found in the columns property.

**Comment by ShimiSun** [comment]
>Array of data objects. If you want to render custom components use the render function found in the columns property.

@IanKBovard sounds good to me

**Comment by ShimiSun** [comment]
Thanks @IanKBovard . 

>I could add something like this to data.
>>Array of data objects. If you want to render custom components use the render function found in the columns property.
I think it will be redundant and restating `columns`, also data is more about the data structure than rendering. 
@LiveFreeAndRoam any other alternatives or we can close this issue?

**Comment by LiveFreeAndRoam** [comment]
This issue can be closed.

As a general point of concern with the documentation; by not repeating (or cross-referencing) information across properties that have some depenendcy between them, it makes it very difficult for the beginner (or even intermediate expert) to get it right.  There are lots of properties and each property has lots of content, so giving a little more support through repetition/cross-referencing, would be friendlier, imho.  It seems unreasonable for a user to have to figure out these dependencies by trial-and-error.

In this case, there is no content that suggests JSX must not be used in the data object.  In fact, it works, but in some cases it will display an ugly console error message.  So only if you're watching the console and your dataset meets some threshold, does it become clear something is amiss.

**Comment by ShimiSun** [comment]
@LiveFreeAndRoam thank you.
We are considering a site refactoring, so your inputs are valuable.
I attached your comment and this thread to the existing issue, and we can consider that when we'll take steps on the docs refactoring.
I'll be closing this issue for now. Thanks again.
