### ISSUE TITLE
legend option not working in Meter component

### ISSUE THREAD

**Issue by maple10001** [grommet/grommet#399]
In Meter component ([http://www.grommet.io/docs/develop/meter](url)), setting the legend option as: `legend={{"placement": "inline", "total": false}}`. In the page, meter still has the total in the legend.

**Comment by bryanjacquot** [comment]
![2016-02-23_14-42-21](https://cloud.githubusercontent.com/assets/6393696/13267681/cc464280-da3b-11e5-8f6d-0cdd2193a01e.png)

**Comment by jwijay** [comment]
Resolved by PR: https://github.com/grommet/grommet/pull/443
