### ISSUE TITLE
Multiple charts with gradients will override chart data and gradient

### ISSUE THREAD

**Issue by jlilly** [grommet/grommet#3992]
When multiple instances of charts are created with different gradients, the data and gradient of the first chart will override and be displayed in the subsequent charts.

A gradient is simply defined in this case an array being passed to the color prop. This case is called out in my codepen

### Expected Behavior
Charts should be independent of each other.

### Actual Behavior
The first chart with a gradient will become the only data displayed within any other chart with a gradient

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-chart-bug-v2-13-cs8rl

Note, the first and second charts exhibit the bug, the third shows that a single color prop is immune to the bug. The second chart should be at 100% with a gradient.

### Steps to Reproduce
See codepen. Also happens when charts are distant cousins.

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: Chrome, suspect all
- Operating System and version (desktop or mobile): Ubuntu

**Comment by laka3000** [comment]
@jlilly 
This is happening because at Chart.js:475, the gradientId and the maskId depends on the `id` prop, since no `id` prop is being passed to the charts in your sandbox (you're setting unique `key` props though), they are all being set as `undefined-gradient` and `undefined-mask`, which leads to this behavior.
![image](https://user-images.githubusercontent.com/7442967/87820915-5013e080-c845-11ea-929a-f0cac30adcd1.png)
Since [key is a special prop](https://reactjs.org/warnings/special-props.html), you should use `id` as a unique identifier for your charts.

@ShimiSun I've opened a PR #4322 that suggests a possible fallback to missing ID, care to take a look?

**Comment by ShimiSun** [comment]
@laka3000 Thanks buddy, appreciate the work and the contribution! we'll take a look in the next few days.

**Comment by ShimiSun** [comment]
I've encountered a similar issue while building different `type` of Charts that uses gradient color. I noticed that using the same `color` gradient on different Charts renders the same type of Chart even if one Chart is type of 'bar' and the other is a 'line'.

Here is a code that reproduces the problem:
```
import React from 'react';
import { storiesOf } from '@storybook/react';

import { Grommet, Box, Chart } from 'grommet';
import { grommet } from 'grommet/themes';

const gradient = [
  { value: 28, color: 'status-ok' },
  { value: 50, color: 'status-warning' },
];
const values = [{ value: [10, 20] }, { value: [20, 30] }, { value: [30, 15] }];

const BarChart = () => <Chart type="bar" values={values} color={gradient} />;
const LineChart = () => <Chart type="line" values={values} color={gradient} />;

export const App = () => (
  <Grommet theme={grommet}>
    <Box margin="medium">
      <BarChart />
      <LineChart />
    </Box>
  </Grommet>
);

storiesOf('Chart', module).add('Bug', () => <App />);


```

Before the fix, both of the Charts were displayed as Bar (even when one of the Charts is a Line Chart)

![image](https://user-images.githubusercontent.com/6320236/88012372-fcb8c100-cad6-11ea-9d6c-836cf0d887de.png)


After the fix, each Chart used the correct `type` of Chart when rendering:

![image](https://user-images.githubusercontent.com/6320236/88012128-5967ac00-cad6-11ea-8ed1-26bb282fc934.png)


Fantastic isolation of the problem and a fix @laka3000 !! ❤️ 
If you guys are into the Chart component, we'd love to hear your feedback on the DataChart component, https://github.com/grommet/grommet/pull/4226, let us know what you think.
