### ISSUE TITLE
Select component in React.StrictMode, component is throwing errors

### ISSUE THREAD

**Issue by kkgowtamasa** [grommet/grommet#3993]
When we use the Select component in React strict mode then we could see the following errors:
`findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Ref which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node.`

### Expected Behavior
-The component should render without any console errors.

### Actual Behavior
- Getting error:
`findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Ref which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node.`

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/9958655/79961996-17ae7180-84a5-11ea-9194-f9f0f38764a2.png)

Code sandbox: https://codesandbox.io/s/objective-glitter-0dzqt?file=/src/App.tsx

### Steps to Reproduce

1. Click on the Select box.
2. See the console errors

### Your Environment
1. Windows and browser is Chrome.

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by kkgowtamasa** [comment]
@ShimiSun @ericsoderberghp

**Comment by IanKBovard** [comment]
@kkgowtamasa Taking a look at this issue now

**Comment by MarkMarine** [comment]
Seems to exist in the DataTable as well

**Comment by Yoruba** [comment]
Same error with List

**Comment by jimwhurr** [comment]
People, myself included, seem to be incurring the same fault after it has been 'closed'

**Comment by ShimiSun** [comment]
Thank you for reporting guys, I've reopened the issue. Feel free to make a contribution and help us improve the open-source for StrictMode users.
