### ISSUE TITLE
Select Component is throwing error in console.

### ISSUE THREAD

**Issue by sindhoora-r** [grommet/grommet#3994]
Select component is throwing the below error in console,
Uncaught TypeError: target.getBoundingClientRect is not a function
    at isNodeBeforeScroll (main.c47b31f916ead3080e9b.bundle.js:1)
    at main.c47b31f916ead3080e9b.bundle.js:1

### Expected Behavior
The Select should render without any console errors.

### URL, screen shot, or Codepen exhibiting the issue
https://storybook.grommet.io/?path=/story/select--simple

### Steps to Reproduce
1. Go to https://storybook.grommet.io/?path=/story/select--simple
2. Check console and change the options,
The following error is thrown,
![image](https://user-images.githubusercontent.com/50887311/79991863-c42a2c80-8480-11ea-8532-c6b0448ed95b.png)

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: Chrome  80.0.3987.163
- Operating System and version (desktop or mobile): Windows laptop

**Comment by IanKBovard** [comment]
I just noticed this too. Its coming from DOM.js in utils either or both sNodeBeforeScroll and isNodeAfterScroll functions are causing the issue.

**Comment by captainheart** [comment]
The same issue is happening to me.
![image](https://user-images.githubusercontent.com/42261423/80865897-c0728300-8c94-11ea-9072-4ea17f45788e.png)

**Comment by ShimiSun** [comment]
The fix is available on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) and will be officially published on our next release. Thanks for reporting!

**Comment by leocavalcante** [comment]
There is any workaround until the next stable version is released?
