### ISSUE TITLE
 Box gap prop rendering gaps between null children

### ISSUE THREAD

**Issue by nateq314** [grommet/grommet#3999]
```JSX
<Box direction="row" gap="10px">
  {null}
  {null}
  {null}
  <Something />
</Box>
```
is rendering 3 gaps, whereas common sense would dictate that there should be none, since there is only one non-null child element.

**Comment by IanKBovard** [comment]
@nateq314 Can you tell me what version of grommet you're using? I'm unable to reproduce this issue.

**Comment by nateq314** [comment]
@IanKBovard The original description is slightly off, sorry about that. It's children elements whose ** render functions ** return null. As in:
```jsx
const RenderNull = () => null;

export default () => (
  <SandboxComponent>
    <Box gap="large" direction="row-responsive">
      <Box border={{ color: "brand", size: "medium" }} pad="large" />
      <RenderNull />
      <RenderNull />
      <Box border={{ color: "red", size: "medium" }} pad="large" />
      <RenderNull />
      <RenderNull />
      <Box border={{ color: "yellow", size: "medium" }} pad="large" />
      <RenderNull />
      <Box border={{ color: "green", size: "medium" }} pad="large" />
      <RenderNull />
      <RenderNull />
      <RenderNull />
      <Box border={{ color: "pink", size: "medium" }} pad="large" />
    </Box>
  </SandboxComponent>
);

```

**Comment by IanKBovard** [comment]
ah, i gothca. thanks for clarifying that.

**Comment by IanKBovard** [comment]
Here is the code that creates the gap.

```javascript
    let contents = children;
    if (gap && gap !== 'none') {
      contents = [];
      let firstIndex;
      Children.forEach(children, (child, index) => {
        if (child) {
          if (firstIndex === undefined) {
            firstIndex = index;
          } else {
            contents.push(
              <StyledBoxGap
                // eslint-disable-next-line react/no-array-index-key
                key={`gap-${index}`}
                gap={gap}
                directionProp={direction}
                responsive={responsive}
                border={border}
              />,
            );
          }
        }
        contents.push(child);
      });
    }
```

It looks for components and renders the boxes based on how many are available. This might be a difficult fix. As far as i know there is no way to detect if a react component returns null, however, I could be wrong. For conditional rendering that works with grommet's gap property, i suggest this.

https://codesandbox.io/s/focused-gould-jjged?file=/src/App.js

**Comment by IanKBovard** [comment]
@nateq314 was the sandbox able to solve your issue?
https://codesandbox.io/s/focused-gould-jjged?file=/src/App.js

**Comment by IanKBovard** [comment]
I think we can close this issue this sandbox addresses the problem, and I don't believe that there is a good way to detect if a component renders null.

This is most likely the best way to conditionally render a component in grommet.
https://codesandbox.io/s/focused-gould-jjged?file=/src/App.js

**Comment by IanKBovard** [comment]
There has not been movement on this in a while, and the solution proposed here works
https://codesandbox.io/s/focused-gould-jjged?file=/src/App.js
I believe we can close this issue.

**Comment by ShimiSun** [comment]
Thank you @IanKBovard !
