### ISSUE TITLE
font with background color contrast issue in Meter Componet

### ISSUE THREAD

**Issue by maple10001** [grommet/grommet#400]
In meter component, font color of the label has contrast issue with background color.
![image](https://cloud.githubusercontent.com/assets/8744187/13121681/37dc4a2c-d568-11e5-9a22-5aa74be7555b.png)

**Comment by bryanjacquot** [comment]
Confirmed issue.

**Comment by jwijay** [comment]
Resolved by PR: https://github.com/grommet/grommet/pull/443
