### ISSUE TITLE
faulty documentation for <Markdown />

### ISSUE THREAD

**Issue by nateq314** [grommet/grommet#4000]
Documentation for `Markdown` gives this as the example code for customizing a `<p></p>`  element in the output:
```json
{
  "p": {
    "component": "Paragraph",
    "props": {"size": "medium"}
  }
}
```
but actually that results in the following console warning:
```
Warning: <Paragraph /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
    in Paragraph (created by Markdown)
    ...(component stack trace follows)
```
and the following markup:
```html
<paragraph><strong>Who I am</strong></paragraph>
```
When you replace `"Paragraph"` with `Paragraph` (no quotes) it works as intended. Not sure if this is an issue with the documentation or with the code?

**Comment by IanKBovard** [comment]
The component key takes a component. When you get the error, you're passing a string. We could update the docs to better reflect the types of values components, and props takes.

This could be more descriptive.
> Custom components and props to override html elements such as 'img' or 'pre'.
