### ISSUE TITLE
FormField theme refactoring for error

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#4004]
This seems like it should be `error.border`, to align with `error.background`.

_Originally posted by @ericsoderberghp in https://github.com/grommet/grommet/pull/3973/files_

**Comment by mcraepv** [comment]
Hi, Would it be ok for me to work on this?

**Comment by ShimiSun** [comment]
@mcraepv sure, go for it!

**Comment by mcraepv** [comment]
Just wanted to update you guys, I'm still working on this. Got held up with some other stuff. I'm hoping to have a PR in by this weekend.
