### ISSUE TITLE
Proposal: Move TypeScript stories into component sub-folders

### ISSUE THREAD

**Issue by avin-kavish** [grommet/grommet#4005]
At the moment, all TypeScript stories are under a root level TypeScript folder. This is inconvenient because usually since the TypeScript stories are incomplete compared to JavaScript ones, users have to switch back and forth between two mega folder structures.

![image](https://user-images.githubusercontent.com/48435155/80121888-73aeee00-85aa-11ea-8372-ba4da4939b62.png)

I propose having a typescript sub-folder for each component, so that all stories related to a component are kept locally and easily accessed for reference. As follows,

![image](https://user-images.githubusercontent.com/48435155/80123167-259aea00-85ac-11ea-817a-155b1c85389d.png)

**Comment by ShimiSun** [comment]
Thanks for reporting, we will be heading this direction and @negreirosleo will help us get there!
