### ISSUE TITLE
Accordion breaks when AccordionPanel is in a different component

### ISSUE THREAD

**Issue by csclyde** [grommet/grommet#4007]
### Expected Behavior

Our app was set up and working in a previous version of Grommet (2.7.2). We have an Accordion component in one place, and then the AccordionPanel in another component (MeterDetails) as the top-level component. Within the Accordion, we would loop through our data and create the AccordionPanel container component (MeterDetails). This would work fine, and users could expand/collapse the meters.

### Actual Behavior

With the new version of Grommet we are using (2.10.2), the expand/collapse functionality of the AccordionPanels breaks. All of the panels are collapsed, and they will not open.

### Steps to Reproduce

1. Create a page with an Accordion
2. Create a wrapper component around an AccordionPanel component
3. Add some of those wrapper components to the Accordion
4. None of the accordion panels can expand

### Your Environment

- Grommet version: 2.10.2
- Browser Name and version: Chrome, up to date
- Operating System and version (desktop or mobile): Ubuntu

**Comment by ShimiSun** [comment]
Thanks for reporting. This issue was fixed on Grommet v2.13.0, enjoy the upgrade.
https://github.com/grommet/grommet/issues/3960
PR #3962
