### ISSUE TITLE
Proposal: remove date and dates from Calendar

### ISSUE THREAD

**Issue by shovelmn12** [grommet/grommet#4008]
### Why?

1. it makes code look ugly:
```
<Calendar
    date={isRange ? undefined : value}
    dates={isRange ? value : undefined}
    />
```
2. hard to read.
3. hard to use without reading the docs.
4. need to validate what type of value is passed every time.

### So what should be done?

```
<Calendar value={array|date|undefined} />

or

<Calendar selected={array|date|undefined} />
```

1. much easier to read
2. no need to check what type of value passed
3. if `value={}` is used, `<Calendar />` will be compatible with `<FormField />` (maybe not, if missed something) which makes it even more generic.

**Comment by g4rry420** [comment]
@ShimiSun Can I work on this issue ?

**Comment by ericsoderberghp** [comment]
A couple of thoughts:
- we cannot remove props without breaking backward compatibility
- DateInput already works as discussed here and is compatible with FormField, is there a reason to not just use it?

**Comment by g4rry420** [comment]
Hey @ericsoderberghp , Can you think of any possible solution for this ?

**Comment by ericsoderberghp** [comment]
> Hey @ericsoderberghp , Can you think of any possible solution for this ?

Perhaps enhance `date` to support the full set of possible types?

**Comment by g4rry420** [comment]
okay, I will take a look into this and let you know if I need any help.

**Comment by jcfilben** [comment]
Closing since #5030 was merged
