### ISSUE TITLE
Autocomplete component?

### ISSUE THREAD

**Issue by dandv** [grommet/grommet#4014]
I've just discovered grommet and appreciate how much simpler it is [compared to MUI](https://github.com/mui-org/material-ui/issues/20755#issue-606906410).

It's obviously a much newer library, but I was wondering if there's an autocomplete component on the map? I'm looking specifically for tags input / [multi-value autocomplete](https://material-ui.com/components/autocomplete/#multiple-values).

**Comment by ShimiSun** [comment]
would that be something you can use https://storybook.grommet.io/?path=/story/textinput--tag?

**Comment by ShimiSun** [comment]
Any news here @dandv ?

**Comment by dandv** [comment]
Actually yes, not sure how I hadn't noticed the Tag TextInput.

Souldn't [Suggestion](https://storybook.grommet.io/?path=/story/textinput--suggestions) work as well though? I tried typing matching characters (e.g. `9`), but that list wasn't filtered to the matching entries.

**Comment by ShimiSun** [comment]
If you need the search functionality then Select will be a better candidate for you https://storybook.grommet.io/?path=/story/select--seasons

**Comment by dandv** [comment]
Thanks @ShimiSun, actually I think https://storybook.grommet.io/?path=/story/select--search is an even better fit!

**Comment by ShimiSun** [comment]
Glad you found what you are looking for.
