### ISSUE TITLE
Animation doc and features

### ISSUE THREAD

**Issue by jjalonso** [grommet/grommet#4015]
Hello Grommets

I was trying to find documentation about animation but could not find more than the little animation paragraph, and I have some question.

1) I saw that setting an anime object like slideLeft with 2000 delay, it hold on the initial position until the 2sec happens, what's the way to do the animation from the initial and default position of that box?

2) I have been testing with pulse animation and it doesn't stop, is there some kind of repeat property or how I can achieve the same effect?

3) On the doc I saw an array of animation string names, I guess it is some kind of chain of anime but its not clear. Is there some documentation that I am missing?

**Comment by ShimiSun** [comment]
Hi, thanks for asking.
Grommet allows an `animation` for components that should allow animation behavior, for example, check out https://v2.grommet.io/box?#animation
For an advance example of animations, check out this code example https://codesandbox.io/s/graphs-animations-bl9th

**Comment by ShimiSun** [comment]
We added a story for animation options https://storybook.grommet.io/?path=/story/box--animation that should cover the request for this issue. Feel free to reopen with more inputs for us if needed.

**Comment by jjalonso** [comment]
Thanks Shimi, Ill catchup with it on following weeks. Appreciate it.
