### ISSUE TITLE
Select component displays gaps on scroll with many items (e.g. 25)

### ISSUE THREAD

**Issue by jesseolsen** [grommet/grommet#4019]
### Expected Behavior

Normal display of items in a Select component, even if > 25 items

### Actual Behavior

Select item in the middle (e.g. 22), then I see a large gap (whitespace) after that item.  See screenshot below.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-sandbox-2r3qw?file=/src/Select.js

![image](https://user-images.githubusercontent.com/6043493/80508603-7bb5b780-8935-11ea-8d8e-86388e3a614f.png)

### Steps to Reproduce

1. Go to codesandbox forked above
2. Select the "Select" item
3. Select "22" from the list of numbers
4. Scroll up and down quickly, until you notice a big gap, like the one shown in the screenshot after 20.

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10

**Comment by ericsoderberghp** [comment]
Hmm... I can't seem to reproduce this. I'm wondering if it is tied to timing differences that only surface in a Windows environment. Still exploring ...

**Comment by jesseolsen** [comment]
I have reproduced it on Windows as well as Mac, both on Chrome.  Steps I used to reproduce this (more detailed this time):
Select Input | Select.
Select 22.  The drop down will close.
Open it back up.  Slowly scroll down until you see "20".  Continue slowly scrolling, and you should see a large gap (white-space) before you eventually see 22 at which time the white space disappears.  Scroll back up and the white space reappears.

**Comment by IanKBovard** [comment]
here's a video of the issue.
![Kapture 2020-05-08 at 11 19 35](https://user-images.githubusercontent.com/21990914/81425788-da411980-911d-11ea-9222-847b831e3d85.gif)

**Comment by ShimiSun** [comment]
Fixed and available on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F).
Thanks for reporting.
