### ISSUE TITLE
Search input:  scrollbar is not available

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#402]
![image](https://cloud.githubusercontent.com/assets/13039669/13125613/596b24ac-d57b-11e5-8993-895d3ae01ca2.png)

**Comment by bryanjacquot** [comment]
Confirmed this is an issue.

**Comment by ericsoderberghp** [comment]
Fixed in 71b6a73d2375d21b9e0f426a83cba0d5e0ba1525.
