### ISSUE TITLE
Incorrent TS definition for Form onChange

### ISSUE THREAD

**Issue by nozzle-a** [grommet/grommet#4024]
### Expected Behavior

According to [the documentation](https://v2.grommet.io/form), The `Form` component `onChange` handler should implement an interface like:
```
(nextState: FormState) => void;
```
Where `FormState` is whatever I'm passing to `React.useState`.

### Actual Behavior

However, the TS definitions defined for `Form` have a different interface:
```
((event: React.ChangeEvent) => void);
```

In `Form.js` line 141 you can see that the documentation is correct, `onChange` is passed the next form state object, not a `React.ChangeEvent`.
```
      if (onChange) onChange(nextValue);
```

If I have strict settings on my compiler which disallow `any`, I can't compile due to this issue.

### URL, screen shot, or Codepen exhibiting the issue

This compiles
```
  function onChange(e: ChangeEvent): void {
    console.log('nextState', e);
  }
// elsewhere
      <Form onChange={onChange}>
```
But `e` is not a `ChangeEvent` object, it is a `FormState` object (see below)

This does not compile:
```
interface FormState {
  email?: string;
  password?: string;
  username?: string;
}

  function onChange(nextState: FormState): void {
    console.log('nextState', nextState);
  }
// elsewhere
      <Form onChange={onChange}>
```

It produces the error:
```
Type '(nextState: FormState) => void' is not assignable to type '((event: ChangeEvent<Element>) => void) & ((event: FormEvent<HTMLFormElement>) => void)'.
  Type '(nextState: FormState) => void' is not assignable to type '(event: ChangeEvent<Element>) => void'.
    Types of parameters 'nextState' and 'event' are incompatible.
      Type 'ChangeEvent<Element>' has no properties in common with type 'FormState'.
```

### Your Environment

- Grommet version: 2.12.0
- Typescript version: 3.8.3

**Comment by ShimiSun** [comment]
Thanks for reporting, feel free to submit a fix for the issue, looks like you've already done some investigation here https://github.com/grommet/grommet/blob/8912aefbc78b041d4670e68b4ed2d346aedbef9f/src/js/components/Form/index.d.ts#L7

**Comment by nozzle-a** [comment]
I've [opened a PR](https://github.com/grommet/grommet/pull/4037) for this.  Anything I need to do to get it reviewed and merged?

**Comment by ShimiSun** [comment]
Thank you for the PR @nozzle-a , I dropped a couple of comments.
