### ISSUE TITLE
Search input:  Long label without spaces will introduce horizontal scroll bar

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#403]
Should we have a max width and wrap the rest to the next line instead of introducing horizontal scrollbar?
Also notice that there is no padding between value (first) and sub(alpha)

![image](https://cloud.githubusercontent.com/assets/13039669/13125956/17a9b11c-d57d-11e5-8f75-10f885e87baa.png)

**Comment by bryanjacquot** [comment]
In this case, the consumer of the component can structure suggestions as components and control rendering and layout as desired.   In this example, the content wasn't structured for a better layout.
