### ISSUE TITLE
AccordionPanel: validateDOMNesting is thrown wnen Menu is used in header

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet#4045]
When I do as below, I am getting this error thrown in the console
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    in button (created by StyledButton)
    in StyledButton (created by Button)
    in Button (created by DropButton)
    in DropButton (created by Menu)
    in Keyboard (created by Menu)
    in Menu (created by Menu)
    in Menu (created by WithTheme(Menu))

```
<AccordionPanel
                header={
                    <Box
                        align='start'
                        direction='row'
                        justify='between'>
                        <Heading>
                            {agenda.title}
                        </Heading>

                        <Menu
                            icon={<More />}
                            items={[
                                {
                                    icon: <Edit />,
                                    onClick: () => this._handleEdit(item)
                                },
                                {
                                    icon: <Trash />,
                                    onClick: () => this.props.onDelete(item)
                                }
                            ]} />
                    </Box>
                }>
```

**Comment by ShimiSun** [comment]
I'm thinking it is because the AccordionPanel is a Button and Menu is a Button as well. some browsers restrict the usage of button nested inside of a button, here is a related read https://stackoverflow.com/questions/47282998/validatedomnesting-warning-react

**Comment by nomadus** [comment]
Yeah, I have seen this. So the suggestion will be to reconsider usage?

**Comment by ShimiSun** [comment]
>Yeah, I have seen this. So the suggestion will be to reconsider usage? 

Yea. Take a look at nested Collapsible, maybe it will be helpful to use it instead https://storybook.grommet.io/?path=/story/collapsible--nested

**Comment by nomadus** [comment]
Thanks!
