### ISSUE TITLE
Search input:  click on the input field does not open the menu

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#405]
Click and hold will open the menu.  Click only will not.  Wonder if it's a feature or it's a defect.  I seldom run into any web pages where I need to click and hold to see the drop down menu though.

**Comment by bryanjacquot** [comment]
Can you clarify what component where you're seeing this issue and what browser you're using?

**Comment by jwijay** [comment]
resolved in PR: https://github.com/grommet/grommet/pull/433
