### ISSUE TITLE
Button with size small rounds corners

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet#4052]
When I set a button to be of small size, it rounds the corners. I have not set any rounding theme.
e.g. when size is small
![image](https://user-images.githubusercontent.com/3382143/81138445-eee9aa00-8f83-11ea-85d3-97ead3a0922f.png)

the same button, when no size is set 
![image](https://user-images.githubusercontent.com/3382143/81138496-13de1d00-8f84-11ea-89c0-567860044ea2.png)

**Comment by IanKBovard** [comment]
@nomadus can you give me an example of your code in codesandbox?

**Comment by nomadus** [comment]
You are right, I have added the individual radii for all the sizes and it fixed the issue.
