### ISSUE TITLE
Select valueKey doesn't work when set as a string

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#4054]
Example here...

https://codesandbox.io/s/grommet-sandbox-2wn1v?file=/src/Select.js&module=/src/Select.js

**Comment by RobertGary1** [comment]
This worked in 2.12.0 and is broken in 2.13.0

**Comment by ericsoderberghp** [comment]
That is behaving as designed. Perhaps the documentation isn't clear enough. When options contains objects, there are two ways to consider how `onChange()` behaves. With `reduce: true`, `onChange(({ value }) => {})` is called with `value` equal to `option[valueKey]` for the selected option. With `reduce: false`, `onChange(({ value }) => {})` is called with `value` equal to `option` for the selected option.

In release 2.12.0, we accidentally broke the prior behavior in 2.11.0. So, 2.13.0 is the correct behavior. 2.12.0 was broken.

You can read more details here: https://github.com/grommet/grommet/issues/3934#issuecomment-613116954 and in the associated pull request.
