### ISSUE TITLE
Accessing style properties of a specific grommet component for use in a custom component in a tidy style object

### ISSUE THREAD

**Issue by rileyskyler** [grommet/grommet#4056]
Based on the documentation on [Accessing theme data outside Grommet Components](https://github.com/grommet/grommet/wiki/Grommet-v2-theming-documentation#accessing-theme-data-outside-grommet-components) I'd expect to be able to access style properties from `defaultProps.textInput` to use in my own  input component like so,
`<input style={{...defaultProps.textInput}}input>`

Instead `defaultProps.textInput` is just an empty object which serves no utility.

https://codesandbox.io/s/defaultprops-textinput-issue-4nib4

**Comment by IanKBovard** [comment]
You can do this two ways. Using ThemeContext.Consumer, or by accessing default props. You have issues in your codesandbox example as well.

I've adjusted your codesandbox to show you both ThemeContext and defaultProps.
https://codesandbox.io/s/defaultprops-textinput-issue-yrq25?file=/index.js

**Comment by ShimiSun** [comment]
@IanKBovard I'm thinking we should add the defaultProps example to the external component example on storybook, thoughts?

**Comment by IanKBovard** [comment]
Sure, i can do that.

**Comment by rileyskyler** [comment]
@IanKBovard thank you for that code sandbox!

The way `ThemeContext.Consumer` or `defaultProps` appears to work in this example doesn't quite solve my initial problem. I want an intuitive way to inherit **all** default styling of a `<TextInput/>` into my own custom `<input />`. Seeing that there is a `theme.textInput` empty object, I'd intuit this would be a good place to access all defaults specific to `TextInput` rather than all of the properties manually accessed in the example. I modified the example to include how I think all text inputs should look.

https://codesandbox.io/s/defaultprops-textinput-issue-nghew

Also, I want a way that if I change the global theme in anyway, especially TextInput on the theme object, it will affect all inputs which inherit.

My end goal is to use Grommet's default theme styling for `TextInput` with a SlateJS's `Editor` component so that my project doesn't require any reverse engineering to get the same aesthetic.

**Comment by IanKBovard** [comment]
Just trying to clarify here. You want a custom input to use inside of slatejs's editor, or you want to customize the slatejs editor itself?

I don't quite understand your example. I assume this is it. Is the codesandbox you sent me incomplete?
```javascript
      <Box align="start">
        <input
          style={{
            color: theme.global.colors.brand,
            fontSize: theme.text.large.size
          }}
        />
      </Box>
```

This does not differ from the two examples i provided you. Both use theme and will change when theme changes.

**Comment by rileyskyler** [comment]
I want to style Slate.js's editor itself just like the Grommet input component.

For some reason the Sandbox I sent you did not save properly. What I intended to do was show how I wanted the two `</input>` that you provided to look like `<TextInput/>` default from the component library.

This link should be saved as I intended to send it:
https://codesandbox.io/s/defaultprops-textinput-issue-xowzr?file=/CustomInput.js

**Comment by IanKBovard** [comment]
I havent worked with slatejs that much. How do you normally style the editor?

**Comment by rileyskyler** [comment]
I'm fairly new to the library, but I know you can style the `<Editable` component for the entire text field, but then the 'tokenized text' can be rendered to any custom styling parameters. From this I want the Grommet styling but in addition to the features available from Slate.
https://docs.slatejs.org/walkthroughs/04-applying-custom-formatting

In case we are getting side tracked, I want to be clear that the reason I brought up SlateJS was to provide context as to why I want to extract the *precise* styling of a TextInput from Grommet.

**Comment by IanKBovard** [comment]
My guess is that you're looking for this.
https://docs.slatejs.org/walkthroughs/03-defining-custom-elements

I think we can close this issue, and continue this conversation on slack. As, this is not an issue with grommet.

**Comment by rileyskyler** [comment]
I don't think my issue is being understood properly and I'm not sure how to clarify without being verbose. Maybe this is a blindspot of mine or it boils down to a feature request. 🤔

I want to access the raw css properties `border-radius`, `margin` `input:focus` ect of a Grommet TextInput component to plug into the Slate paradigm at my discretion for a pixel perfect aesthetic I see on the Grommet docs. I have other inputs in my app that will plain `<TextInput/>` components and I want consistent design throughout my app. Further more, I want a way to inherit my own custom themes mixed into Grommet's defaults into my custom component as well as actual TextInput components. It would be really nice if it were all accessible in one tidy object, maybe by calling a function. 
Ex: `Grommet.getCustomThemedStyleProps('TextInput')` -> `{borderRadius: 5px, ':focus': '#6FFFB0', font: //MY CUSTOM FONT ...}`

 I don't want to have to hard code and reverse engineer Grommet's design with my own CSS to get consistent UI.

**Comment by IanKBovard** [comment]
Let me try to break down what you're asking.

You want to access css properties of a grommet component.
  That can be done with ThemeContext.Consumer or defaultProps.

You want to make custom grommet components that also inherit all styles from theme.
  You can use styledComponents, customize the theme, or the extend property to do that.

I've adjusted my original codesandbox with more examples and comments.
https://codesandbox.io/s/defaultprops-textinput-issue-yrq25?file=/CustomInput.js

**Comment by rileyskyler** [comment]
@IanKBovard I appreciate you taking the time to update that Sandbox. This helps me in my understanding of how theming works with Grommet, but unfortunately misses my key challenge.

ThemeContext.Consumer/defaultProps do not provide an intuitive way to get all the style props specific to TextInput. I think an intuitive solution would be to have it all in the `textInput` property on the theme object provided by ThemeContext.Consume. But this is just an empty object.

![Screen Shot 2020-05-11 at 3 46 12 PM](https://user-images.githubusercontent.com/29023970/81620811-98c0a080-93a1-11ea-834d-d555259066e1.jpg)

From what I've gathered in this discussion, this isn't how it works. But, I am then curious why does this `textInput` property exist to begin with? Maybe this is a feature that could be implemented down the line?

So, instead I'm searching through this large complexly nested theme object

![Screen Shot 2020-05-11 at 3 45 55 PM](https://user-images.githubusercontent.com/29023970/81621091-66637300-93a2-11ea-895b-b52a51485a8f.jpg)

 to find the styles I need to make my custom input look like exactly like this.

![Screen Shot 2020-05-11 at 3 42 24 PM](https://user-images.githubusercontent.com/29023970/81620893-cf96b680-93a1-11ea-9d18-29757ad3cf90.jpg)

Implemented as such:

![Screen Shot 2020-05-11 at 3 44 23 PM](https://user-images.githubusercontent.com/29023970/81621127-7bd89d00-93a2-11ea-8676-c45590adb18c.jpg)

But this result is the closest we've come to the design

![Screen Shot 2020-05-11 at 3 17 16 PM](https://user-images.githubusercontent.com/29023970/81621204-acb8d200-93a2-11ea-910b-874d5f918a6a.jpg)

because there're all these unmet css properties to fulfill such as `border-radius`.

![Screen Shot 2020-05-11 at 3 42 06 PM](https://user-images.githubusercontent.com/29023970/81621268-d3770880-93a2-11ea-8fdd-ba906129e699.jpg)

If these properties exist in the theme or defaultProps object, this implementation is not intuitive to me where I am at and seems to require much forensics 😁.

**Comment by IanKBovard** [comment]
Here is documentation where textInput gets its styling from theme.
https://v2.grommet.io/textinput#theme

For a custom input with all of the styled from grommets textInput styled components or textinput.extend is your answer.
https://styled-components.com/docs/basics

**Comment by rileyskyler** [comment]
Thanks @IanKBovard, I think this is the solution I am looking for. After I sent my last comment I found the theme props in the documentation. I think I can figure it out from the two links you've provided.
