### ISSUE TITLE
Uncontrolled Form throws warning when not using component prop in FormField

### ISSUE THREAD

**Issue by cscognamiglio** [grommet/grommet#4067]
Uncontrolled Form block with FormField components will throw the warning:
A component is changing an uncontrolled input of type undefined to be controlled.

If the FormField input field is not a children, i.e. is either not specified (defaults to TextInput) or is passed to FormField through the component props.
 
### Expected Behavior

The behavior should be similar to passing the input component as a child.

### Actual Behavior

The following warning is thrown:
A component is changing an uncontrolled input of type undefined to be controlled.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-uiddw

### Steps to Reproduce

You can use the second example of the doc for the uncontrolled form here:

https://v2.grommet.io/form

And simply remove the TextInput component.

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: Firefox 76.0.1
- Operating System and version (desktop or mobile): MacOS Catalina

**Comment by ShimiSun** [comment]
Hi buddy, I didn't dive much into your example yet but I can see that our story example of Uncontrolled Form is working as expected, can you confirm you are following the same structure of uncontrolled Form as the example we are providing https://storybook.grommet.io/?path=/story/form--uncontrolled

**Comment by cscognamiglio** [comment]
Hi ShimiSun,
Yes there is no warning in that example because the input components are passed as children of the FormField components.
In my example I am using a simple FormField without any input component specified, that from what I understands defaults to:
<FormField component={TextInput} />

Also whan specifying other input components this way with the uncontrolled Form I get the warning.
I was also wondering about the difference between passing the input component to FormField as props or child.

Anyway, in my app I solved the issue by passing the input components as children.

**Comment by seawolf42** [comment]
I get the same error with a controlled form: https://stackoverflow.com/questions/61990216/creating-a-controlled-form-with-grommet-throws-errors. An

**Comment by jcfilben** [comment]
I was unable to reproduce the issue in codesandbox or by using the storybook Form uncontrolled story and removing TextInput. 

> I get the same error with a controlled form: https://stackoverflow.com/questions/61990216/creating-a-controlled-form-with-grommet-throws-errors.

In this case the warning 'A component is changing an uncontrolled input of type undefined to be controlled' is caused by initially setting defaultValue to be uncontrolled (`defaultValue = {};`) and then changing it later to be controlled.

explanation provided here: https://stackoverflow.com/questions/61990216/creating-a-controlled-form-with-grommet-throws-errors

more information here: https://stackoverflow.com/questions/47012169/a-component-is-changing-an-uncontrolled-input-of-type-text-to-be-controlled-erro

**Comment by cscognamiglio** [comment]
I forgot about this... the issue I had was mainly a different behavior when using FormField and passing an input component as a child as opposed to with the "component" prop.
I solved somehow and judging by the docs the recommended method is to use input components as children of a FormField.
Maybe show a deprecation warning when using the "component" props can help? anyway, I'll close this issue.
