### ISSUE TITLE
Search input:  can the drop down menu formatted as a table

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#407]
We have a use case where the menu list is a table, as shown below.  I wonder if grommet search input  can be done that way.  
![image](https://cloud.githubusercontent.com/assets/13039669/13128602/cfcd0632-d58b-11e5-858a-fea2c92c5401.png)

**Comment by bryanjacquot** [comment]
We'd like to explore ways to provide this feature without requiring a table in a search combo.  Suggest using a `ListItem` with a `justify="between"` parameter.

**Comment by bryanjacquot** [comment]
Closing based on previous guidance.
