### ISSUE TITLE
Markdown doesn't work correctly for bullet lists

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet#4070]
### Expected Behavior

AM expecting that I can create a bulleted list.

### Actual Behavior

![image](https://user-images.githubusercontent.com/17883783/81604492-2940b600-938d-11ea-8096-bfcdac3bfa08.png)

also:
![image](https://user-images.githubusercontent.com/17883783/81604555-4d9c9280-938d-11ea-8753-3a6f9776411b.png)

### URL, screen shot, or Codepen exhibiting the issue

https://v2.grommet.io/markdown?c=DwWQhgTg1gJg9gdwHYD4BQACAtBsmcBGawA9ONPMikA

**Comment by taysea** [comment]
Hey Edgar, I think that this is just because the live editor on grommet site isn't interpreting the "enters" as line breaks. Here's an example on designer showing that bulleted list is functioning as expected: https://designer.grommet.io/?id=Markdown-taylor-seamans-hpe-com

**Comment by IanKBovard** [comment]
@ecircenis let me know if taysea answered you question, and we can close this issue.

**Comment by IanKBovard** [comment]
@ecircenis just checking in to see where you are with this issue

**Comment by jcfilben** [comment]
Here is a code sandbox showing the Markdown list working https://codesandbox.io/s/grommet-v2-template-forked-usx6w?file=/index.js. 

The reason the list was not working in your example is that the markdown-to-jsx library that grommet is using doesn't preserve newlines in multiline text when the content is placed directly into he Markdown component like this:
```javascript
<Markdown>
  - item 1
  - item 2
  - item 3
</Markdown>
```

therefore it is recommended to do something like this instead:
```javascript
const CONTENT = `
  - item 1
  - item 2
  - item 3
`;
<Grommet>
  <Markdown>
    {CONTENT}
  </Markdown>
</Grommet>
```
More information: https://github.com/probablyup/markdown-to-jsx/

**Comment by jcfilben** [comment]
I think we should be able to close this issue. Feel free to reopen this issue or file a new issue if the above solution isn't working as expected.
