### ISSUE TITLE
FormField docs inaccurate about custom `component`.

### ISSUE THREAD

**Issue by jonjamz** [grommet/grommet#4075]
### Expected Behavior

The docs state:

"The component may be custom as long it supports the properties of name, value, onChange (event => {}), while event has either **event.value** or **event.target.value**."

### Actual Behavior

Passing an object to onChange with shape `{ value: <anyValue> }` results in an error being thrown and upon inspecting the code from the stack trace it is revealed that the only supported shape is `{ target: { value: <anyValue> } }`. 

### URL, screen shot, or Codepen exhibiting the issue

Specifically, see the onChange code below:

```js
var renderInput = function renderInput(formValue, invalid) {
    var Input = component || TextInput;

    if (Input === CheckBox) {
      return React.createElement(Input, _extends({
        name: name,
        label: label,
        disabled: disabled,
        "aria-invalid": invalid || undefined
      }, rest));
    }

    return React.createElement(Input, _extends({
      name: name,
      value: !isGrommetInput(component) ? formValue[name] : undefined,
      disabled: disabled,
      plain: true,
      focusIndicator: false,
      "aria-invalid": invalid || undefined
    }, rest, {
      onChange: // Grommet input components already check for FormContext
      // and, using their `name`, end up calling the context.update()
      // already. For custom components, we expect they will call
      // this onChange() and we'll call context.update() here, primarily
      // for backwards compatibility.
      isGrommetInput(component) ? rest.onChange : function (event) {
        context.update(name, event.target.value);
        if (rest.onChange) rest.onChange(event);
      }
    }));
  };
```

### Steps to Reproduce

I believe this is fairly straightforward but let me know and I'll create a Codesandbox if required.

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: Chrome latest
- Operating System and version (desktop or mobile): Desktop MacOS 10.15.4

**Comment by ShimiSun** [comment]
I believe this issue is fixed on grommet v2.14.0, feel free to reopen the issue if needed and attach a codesandbox so we can see how exactly you reproduce it.
