### ISSUE TITLE
TextInput plain doesnt work?

### ISSUE THREAD

**Issue by jjalonso** [grommet/grommet#4078]
TextInput plain doesn't appear to do anything.

### Expected Behavior

Remove padding

### Actual Behavior

Doesn't remove the padding

### URL, screenshot, or Codepen exhibiting the issue

https://codesandbox.io/s/textinput-plain-issue-jexeu

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: Latest Chrome
- Operating System and version (desktop or mobile): both

**Comment by ShimiSun** [comment]
I think the padding is coming from the Formfield and not from the TextInput itself, can you verify?

**Comment by IanKBovard** [comment]
Padding is still there when textinput isn't wrapped.
https://codesandbox.io/s/textinput-plain-issue-forked-w4t6q?file=/index.js

**Comment by tobyspark** [comment]
In my case, `plain` removed the border, but not the padding. 

Current workaround for the one-off I need this for is a slight elaboration on `<ThemeContext.Extend value={{  textInput: { extend: { padding: ‘0’ }}}}><TextInput/></ThemeContext.Extend>`. Thanks to @ShimiSun in slack for the pointer.

> I think the padding is coming from the Formfield and not from the TextInput itself, can you verify?

Aside from any current implementation, I would expect `plain` to override any inheritance.

**Comment by ShimiSun** [comment]
Starting from grommet release ^2.15.1, this issue is solved by using `plain='full'`.
Thank you for reporting.

**Comment by tobyspark** [comment]
Was able to removed my ThemeContext workaround. Thanks!

**Comment by jjalonso** [comment]
Great job guys.
