### ISSUE TITLE
Types are now broken in Grommet, causing prop auto completion to not work.

### ISSUE THREAD

**Issue by iMerica** [grommet/grommet#4081]
Hey guys,

Something is now broken with the types in Grommet. Before, I could write `<Box>` and type the first few characters of props like height, pad, width, height etc and my editor would auto complete and suggest available props.

This is now broken. 

I've verified its not an issue with my editor, by

- Testing other 3rd party components in my app, verifying this issue only effects Grommet.
- Testing Grommet in a completely different IDE, verifying the issue persists.

![x](https://user-images.githubusercontent.com/487897/82011505-cbd19100-963a-11ea-9f1e-f6038dffa0a0.gif)

(version ^2.13.0)

Thank you,

Michael

**Comment by ShimiSun** [comment]
Can you identify from which version you are reproducing this issue?

**Comment by ShimiSun** [comment]
Friendly reminder on the question above ⬆️  
Regardless, it works for me as expected.

**Comment by iMerica** [comment]
It's in the issue description

**Comment by ShimiSun** [comment]
It doesn't reproduce on my end so I was hoping you can give a more accurate explanation of which version the issue started. Does it work as expected on v2.12.0?

**Comment by RobertoSnap** [comment]
Tried updating a project to 2.13.0 

rm node_modules, tried with yarn and npm

![image](https://user-images.githubusercontent.com/4772930/83348406-92806d00-a32c-11ea-9485-a600465c4d57.png)

**Comment by RobertoSnap** [comment]
Strange, downgraded to 2.11.2 but getting the same error. I have recreated the tsconfig, maybe there is something there.

**Comment by RobertoSnap** [comment]
Found out why, add this to tsconfig

"moduleResolution": "node"

**Comment by ShimiSun** [comment]
@RobertoSnap thanks buddy, is it something that should be added to grommet's tsconfig? if so would you like to make a contribution?

**Comment by iMerica** [comment]
It's not working for me.

**Comment by jcfilben** [comment]
@iMerica are you still experiencing this issue? I was not able to reproduce the issue

**Comment by iMerica** [comment]
Issue persists. It's like editing a react project with Nano...

**Comment by iMerica** [comment]
Fixed this by manually adding support in Webstorm. 

https://stackoverflow.com/a/46871743/1118492
