### ISSUE TITLE
Fix deprecation warnings when installing Grommet

### ISSUE THREAD

**Issue by jecassis** [grommet/grommet#4082]
`npm install grommet` and `yarn add grommet` should not output deprecation warnings on install.

### Actual Behavior
Yarn example:
```
warning grommet > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning grommet > css > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning grommet > css > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning grommet > recompose > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

### URL, screen shot, or Codepen exhibiting the issue
See console output above.

### Steps to Reproduce
`yarn install grommet@2.13.0`

### Your Environment
- Grommet version: 2.13.0
- Browser Name and version: Not applicable
- Operating System and version (desktop or mobile): Windows 10

**Comment by jecassis** [comment]
The last one is fixed by removing the `recompose` dependency in #4074.

For the first three may I propose the following solution (as submitted in pull request #4083):

1. Replace `css` with `postcss`. `css` appears to not be actively maintained.
2. Move it out of `dependencies` and into `devDependencies` as the `portal.js` file is only imported in `*-test.js`.

**Comment by ShimiSun** [comment]
Thank you for your contribution to this issue buddy! I'll be closing this issue.
