### ISSUE TITLE
Enhancement to Form - would be nice to offer immediate validation

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#4084]
For forms without a submit button it would be nice to offer validation as the user types.

**Comment by ShimiSun** [comment]
Hi @RobertGary1, does the new `onValidate` (released on v2.15.0) API answers your request? https://v2.grommet.io/form#onValidate

**Comment by ShimiSun** [comment]
I'll be closing this issue since we have provided the `onValidate()` solution a few releases ago. Feel free to reopen and elaborate with more details if needed.
