### ISSUE TITLE
Formik setFieldValue right-aligns Select option when selected

### ISSUE THREAD

**Issue by chrisvalmonte** [grommet/grommet#4087]
It seems that `Formik.setFieldValue` imperatively simulates typing in a value into the `<input type="text" />` that's rendered by the `Select`, which causes the text to be right-aligned.

### Expected Behavior
Selected option inside the `Select` box should be left-aligned after selected

### Actual Behavior
Selected option inside the `Select` box is right-aligned after selected

### URL, screen shot, or Codepen exhibiting the issue

Code sandbox for repro: https://codesandbox.io/s/grommet-issue-4087-text-right-aligned-in-select-after-selecting-option-55oxz?file=/src/App.js

![grommet-select-issue](https://user-images.githubusercontent.com/22405692/82084836-d6267600-96a0-11ea-9885-d66d492802df.gif)

### Steps to Reproduce

1. Create a custom handler that uses `Formik.setFieldValue` and pass it to the `onChange` prop of a `Select` component:
```
  const onChange = (event: GrommetSelectEvent<typeof options[number]>) => {
    const value = event.value?.id || form.initialValues[field.name];
    form.setFieldValue(field.name, value);
  };
```

Documentation on `Formik.setFieldValue` here: https://jaredpalmer.com/formik/docs/api/formik#setfieldvalue-field-string-value-any-shouldvalidate-boolean--void

2. Pass these options to the same `Select` component: `['option 1', 'option 2', 'option 3', 'extra super long name that needs to be truncated inside the select box']`
3. In the UI, click the 'extra super long name that needs to be truncated inside the select box' option
4. Verify that the selected text inside the `Select` box is right-aligned (see GIF above)

### Your Environment

- Grommet version: "grommet": "^2.7.7"
- Browser Name and version: Chrome for Mac Version 81.0.4044.138 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): macOS Catalina v10.15.4

Also reproducible in Edge, Safari, and Firefox.

**Comment by ShimiSun** [comment]
Can you please isolate the problem reliably on a newer version of grommet, and send us a codesandbox with the markup to explore the problem. it will have a quicker turnaround if we'll know how you are using the component within Formik.

**Comment by chrisvalmonte** [comment]
@ShimiSun Thanks for the response, I'll send that over.

**Comment by chrisvalmonte** [comment]
@ShimiSun I updated the issue with the code sandbox link. Here it is: https://codesandbox.io/s/grommet-issue-4087-text-right-aligned-in-select-after-selecting-option-55oxz?file=/src/App.js

**Comment by chrisvalmonte** [comment]
@ShimiSun I think that somewhere in the implementation you will have to set the selection range to "move" the cursor inside the text input to the beginning of the inputted string. https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange

**Comment by jcfilben** [comment]
Hi @chrisvalmonte One thing I noticed on your codesandbox what that you weren't wrapping with `<Grommet>`. Does this example accomplish what you need? The text isn't right aligned in this https://codesandbox.io/s/grommet-issue-4087-text-right-aligned-in-select-after-selecting-option-forked-j8bcj?file=/src/App.js

**Comment by chrisvalmonte** [comment]
@jcfilben Thanks for the input. I tried repro’ing the issue in your example as well. If you select option 1 first, and then select the long-text option, it will still be right-aligned

**Comment by jcfilben** [comment]
![Sep-14-2020 10-44-01](https://user-images.githubusercontent.com/54560994/93114069-57a20b00-f677-11ea-8a47-5e7ae9c988d6.gif)

It is still left-aligned for me even after selecting option 1

**Comment by ShimiSun** [comment]
@chrisvalmonte please let us if there is anything else we can help with since the issue doesn't reproduce on grommet itself.

**Comment by chrisvalmonte** [comment]
@ShimiSun Okay, thanks! Closing the issue

**Comment by der1igedon** [comment]
> Hi @chrisvalmonte One thing I noticed on your codesandbox what that you weren't wrapping with `<Grommet>`. Does this example accomplish what you need? The text isn't right aligned in this https://codesandbox.io/s/grommet-issue-4087-text-right-aligned-in-select-after-selecting-option-forked-j8bcj?file=/src/App.js

Hello, I tried the sample. But for me it doesn't work. It still aligns to the right. Was there any change with newer grommet versions?

**Comment by jcfilben** [comment]
Hi @der1igedon I don't think there was any change related to this in newer versions on Grommet. I created a new [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-uye4j5?file=/index.js) with updated versions or React, Grommet, etc. Let us know if you are still seeing the issue in the new codesandbox. If your are still seeing the issue can you share the browser, version, and operating system you are running?
