### ISSUE TITLE
Can't click lower options from Select inside a FormField inside a Layer

### ISSUE THREAD

**Issue by blakehilliard** [grommet/grommet#4088]
### Expected Behavior

Opening the drop-down choices of a select, then scrolling down, then clicking your selection, should select what you just clicked.

### Actual Behavior

For choices toward the bottom of the options, clicking them just scrolls the drop-down menu back to the top and does not change the selected value.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-formfield-long-select-bzoi1

### Steps to Reproduce

1. Open the codepen above.
2. Make the rendered portion large enough that the layer does not take the full screen.
3. Make sure your browser's height is not too high, so that the list of options in the drop-down menu would require you to scroll down to reach the bottom of the list.
4. Click the drop-down menu, scroll down, and click on "Twenty".

Notice that the drop-down menu suddenly scrolls back to the top, and "One" is still selected.

Oddly, this problem goes away if you do any one of the following:
1. Remove the FormField around the Select.
2. Remove the Layer.
3. Make the Layer fill the screen.

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by ShimiSun** [comment]
I think this issue is fixed on the stable branch https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F.
Will you be willing to give it a try and let us know using the stable (our updated master branch) solved your problem?

**Comment by blakehilliard** [comment]
That works!

**Comment by ShimiSun** [comment]
Great, I'll be closing the issue then.
