### ISSUE TITLE
form errors show wrong style

### ISSUE THREAD

**Issue by jjalonso** [grommet/grommet#4101]
When passing an array to form errors, it look like info. 
### Expected Behavior

Show error styling
### Actual Behavior

Show info styling

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/form-errors-3tyv1?file=/index.js

**Comment by buoyantair** [comment]
Hi @ShimiSun I would like to pick this up!

**Comment by ShimiSun** [comment]
Perfect! thanks @buoyantair , looking forward to the PR.

**Comment by ShimiSun** [comment]
Hi dear, any updates on this issue/PR?

**Comment by buoyantair** [comment]
@ShimiSun Hey, not able to work on this right now. Really sorry ☹️ Hope someone else picks it up!

**Comment by IanKBovard** [comment]
@jjalonso here is the correct use of the errors prop

https://codesandbox.io/s/form-errors-xhx83?file=/index.js

require is overriding your custom error message. If you want to use this prop, i suggest handling different errors in state. if you want to customize the required message, i suggest using the messages prop, like so.

https://codesandbox.io/s/form-errors-7rxik?file=/index.js

**Comment by jjalonso** [comment]
You mean is not an issue then ?

**Comment by jjalonso** [comment]
I just check my codesandbox and now show red messages. Before it was used to show gray messages like info.

Maybe grommet version got upgraded and problem solved ?

**Comment by IanKBovard** [comment]
if you want to show info, you need to use the infos prop.

https://codesandbox.io/s/form-errors-2mj8i?file=/index.js

**Comment by jjalonso** [comment]
@IanKBovard the _bug_ was reported on 2.13, 
You check the codesandbox again now that I fixed the version.

**Comment by IanKBovard** [comment]
@jjalonso remove the square brackets, and it should be fine.
https://codesandbox.io/s/form-errors-e0v6e

**Comment by jjalonso** [comment]
It works  thanks, is the documentation right with that array?


errors

An object representing any errors in the data. Their keys should match the keys in the value object.

{"name": **[**"message", "<Box>...</Box>"**]**}

**Comment by IanKBovard** [comment]
Yeah, thats a little confusing to me too. Not sure why its an array. I'll have to ask.

**Comment by MikeKingdom** [comment]
I'm not sure of the real purpose of the array in the doc yet, but if the value for a key is an object rather than a string, that value is inside a <Box>(by FormField's <Message>) and the Box props come from the theme. Well in this case the theme provides a "color: status-critical" which is passed along to <Box> but since <Box> doesn't have a color prop it ends up in the DOM as <div color="status-critical"> which has no effect. 

As workaround, although it isn't directly from the theme, you can do something like more like:
```
name: [
  <Text color="status-critical">We are sorry, your name is so ugly to continue</Text>,
  <Text color="status-critical">Other error</Text> 
],
```
or
```
name: <Box style={{ color:'red' }}>
    We are sorry, your name is so ugly to continue
    Other error
  </Box>,
```

I'm guessing you'd run into a similar problem with info or help.

**Comment by ericsoderberghp** [comment]
I think the array example shown, `["message", "<Box>...</Box>"]` is just some poor auto-formatting. I think it's trying to say the value for each name could be either a string or JSX.

**Comment by MikeKingdom** [comment]
The result of this was to fix the grommet site doc for Form to more clearly show the infos and errors props can be an object with keys that map to either a string message or a JSX node. The way it was making it look like it could be an array was confusing. Form now documents these props more like FormField does for basically the same feature.

**Comment by ShimiSun** [comment]
Thank you @MikeKingdom for getting this issue to the finish line and for your contribution!
