### ISSUE TITLE
Button.primary.color applies background instead of label color

### ISSUE THREAD

**Issue by mihai-ro** [grommet/grommet#4111]
`button.primary.color` sets background-color, instead of label color

### Expected Behavior
`button.primary.color` sets label color

When setting the color property for button variants, a CSS rule for `color` should be applied to button element.

### Actual Behavior
A background-color rule is applied instead, this making it impossible to overwrite colours for labels in button variants.

![Result](https://user-images.githubusercontent.com/15910058/82906379-d4489680-9f6d-11ea-8679-51931c9af2be.png)

### Steps to Reproduce

1. set up your theme
```export default {
  global: {
    colors: {
      brand: '#A7893D'
    },
    font: {
      family: 'Helvetica'
    }
  },
  button: {
    primary: {
      color: 'salmon'
    }
  }
}
```
 2. run storybook
3. see result

### Your Environment

- Grommet version: grommet@2.13.0
- Browser Name and version: Chrome  81.0.4044.138
- Operating System and version (desktop or mobile): MacOS Catalina 10.15.4

**Comment by ShimiSun** [comment]
I'm not sure whether this issue is a bug since we document the primary color as the fill color https://v2.grommet.io/button#color
the color that is used for the text is `text` color https://v2.grommet.io/button#global.colors.text

**Comment by mihai-ro** [comment]
> I'm not sure whether this issue is a bug since we document the primary color as the fill color https://v2.grommet.io/button#color
> the color that is used for the text is `text` color https://v2.grommet.io/button#global.colors.text

My issue is not related to the `primary` colour in the `global.colors` object, but rather to the button variant called `primary` - `<Button primary {...} />`. I am trying to adjust the style for primary buttons, e.g. changing the label colour and its background colour.
Now, I can see these being described in the documentation as `button.primary.color` and `button.primary.background.color` accordingly.  However, changing `button.primary.color` actually changes the background colour, and `button.primary.background.color` is being ignored entirely. Am I missing something? According to the documentation, this is not intended behaviour.

**Comment by ShimiSun** [comment]
I agree with your comment. I think we should consider having separate color theme props for `color` and `background.color` within `primary` button.

Regardless, please take a look at how I was able to impact the text color of primary button in this code snippet: https://codesandbox.io/s/themed-button-pp77f?file=/index.js

```
const theme = {
  button: {
    primary: {
      extend: `color: white;`
    },
}
```

**Comment by mihai-ro** [comment]
Thank you @ShimiSun. Extending it did the trick.

It looks like the `button.primary.color` and `button.secondary.color` rules (probably a few more besides them) do not apply the colour to the label, but rather to the border and background. Should we extract task out of this ticket? It does look like a mismatch between what's written in the docs and the actual behaviour.

**Comment by ShimiSun** [comment]
@mihai-ro I'll keep this issue open to extend the `theme.button` API to allow to configure background color separately to text color. 
You are welcome to make a code contribution :)

**Comment by ShimiSun** [comment]
we recently added `button.default` that changes the way of `background` and `color` to the way you described. it is available on stable branch. If you are defining `button.default` you should experience the expected behavior, please give it a try and let me know if it works as you expected.

**Comment by mihai-ro** [comment]
> we recently added `button.default` that changes the way of `background` and `color` to the way you described. it is available on stable branch. If you are defining `button.default` you should experience the expected behavior, please give it a try and let me know if it works as you expected.

Thank you, @ShimiSun . I think that was it! Can we specify this as a N.B. in the docs, that one should explicitly define a default style for `<Button />` to enable customisation of button variants? (e.g. primary, secondary)

**Comment by ShimiSun** [comment]
@mihai-ro thank you for your feedback. 
Here is the documentation for the Button component: https://github.com/grommet/grommet/blob/master/src/js/components/Button/doc.js
Resolved to https://v2.grommet.io/button.
Feel free to edit the doc.js file and submit a PR with the way you think that makes the docs clearer. I would love to hear your inputs.

**Comment by ShimiSun** [comment]
Just an update the new Button functionality is officially released on grommet 2.14.0.

**Comment by holdenmad** [comment]
From what I can tell from reading this thread and looking at the [button documentation](https://v2.grommet.io/button), it looks like the documentation reflects the current functionality, but the [Button/doc.js](https://github.com/grommet/grommet/blob/master/src/js/components/Button/doc.js) doesn't reflect these changes. Should this issue be closed, or does the Button/doc.js file still need to be updated?

**Comment by ShimiSun** [comment]
Thank you @holdenmad for keeping this issue moving, I agree this issue can be closed since the new button was released and the docs had been adjusted.
Feel free to reopen if anything else is needed.
