### ISSUE TITLE
<Select> drop throws getBoundingClientRect exception in InfiniteScroll.js

### ISSUE THREAD

**Issue by MikeKingdom** [grommet/grommet#4112]
In Grommet 2.13.0 <Select> throws an error in InfiniteScroll.js when you try to click on the <Select> and choose an option.

This doesn't seem happen with Grommet 2.12.0

DOM.js:217 Uncaught TypeError: target.getBoundingClientRect is not a function
    at isNodeBeforeScroll (DOM.js:217)
    at eval (InfiniteScroll.js:167)

### Expected Behavior

Pop up the drop with options when the <Select> is clicked upon and then you try to choose an option

### Actual Behavior

The drop should appear rather than an exception.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/hidden-haze-cc0z5?file=/src/App.js

### Steps to Reproduce

1. Create a simple select with several options.
2. Click on the select
3. Hover over the options in the drop and pick one
4. Hit F12 and look in the debugger console to see the exception in InfiniteScroll.js

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10, Desktop

**Comment by ericsoderberghp** [comment]
Can you check whether this is fixed on the stable branch? I think it might be.

**Comment by MikeKingdom** [comment]
It seems fixed on the stable branch. I couldn't get it to happen there.

**Comment by ShimiSun** [comment]
I'll be closing this issue. @MikeKingdom feel free to reopen if needed.
