### ISSUE TITLE
Opacity not working for background image in Box

### ISSUE THREAD

**Issue by Berbel93** [grommet/grommet#4121]
"opacity" is not working when used in the background property of the Box component if "image" is set. However, it does work when "color" is used instead of "image" for the background.

### Expected Behavior

Opacity works when using "image" inside the background property of the Box component.

### Actual Behavior

Opacity only works with "color".

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/box-opacity-4t6ym?file=/src/App.js

### Steps to Reproduce

1. Use the Box component.
2. Specify the background property.
3. Use the object {"image": "url(...)", "opacity": 0.5} in the background.

### Your Environment

Webstorm IDE

- Grommet version: 2.13.0
- Operating System and version: Windows 10

**Comment by ShimiSun** [comment]
Thank you for reporting, in the meanwhile, you can consider using the Image component with `opacity`. https://v2.grommet.io/image#opacity

**Comment by ShimiSun** [comment]
Thank you for reporting, the fix will be available on our next release. Thank you @taysea for the contribution! 💟
