### ISSUE TITLE
Backspacing in maskedInput has odd side-effects

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet#4122]
I am trying to use a maskedInput to force a URL to begin with "https://".

It seems to work well and allows for both pasting in a full URL as well as typing in the part after the fixed portion.  But, if you backspace all the way to the beginning, it is adding unexpected text into the input.

I should be able to backspace without having unwanted text inserted.

Try it here:
https://designer.grommet.io/screen?id=MaskedInput-edgar-circenis-hpe-com

Use cases (you will have to refresh browser between use cases to get back to starting conditions):
1. Paste in "https://foo.com" (works)
2. Paste in "http://foo.com" (fails; the input ends up containing "https://http").  I would expect this paste should not be allowed.
3. Type in foo.com (works), then backspace all the way back (fails; Eventually, input contains "https://http")

**Comment by ShimiSun** [comment]
The fix is available on the grommet stable branch, thanks for reporting.
