### ISSUE TITLE
No tool tooltip component in grommet v1

### ISSUE THREAD

**Issue by naveenrj98** [grommet/grommet#4128]
### Expected Behavior
When we click on button or hover on component, we need to show a component which has tip on it to referring component we use in the same thing.

### Actual Behavior
we do not have any component as like to show with tip on any side to reffer the component we use 

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: v1
- Browser Name and version: chrome
- Operating System and version (desktop or mobile): desktop

**Comment by ShimiSun** [comment]
Hi @naveenrj98 thanks for reaching out.

We currently do not have the resources to address v1 enhancement requests or overall maintenance.

The solution in v2 for tooltip is using Drop component, https://v2.grommet.io/drop
