### ISSUE TITLE
Scrolling inside masked input's drop content keeps resetting back to top

### ISSUE THREAD

**Issue by novykh** [grommet/grommet#4132]
### Expected Behavior

When scrolling to select a value for masked input, it should keep the position.

### Actual Behavior

When scrolling to select a value for masked input, ti resets the scroll position and is not possible to select it.

### URL, screen shot, or Codepen exhibiting the issue

This happens in the codesandbox example as well: https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=maskedinput&module=/src/MaskedInput.js&file=/src/MaskedInput.js

It works in the storybook examples.

### Steps to Reproduce

1. Scroll to find a value that is not visible.
2. After scroll move the pointer to select a value.

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: Chrome 83.0.4103.61 & Safari 13.1
- Operating System and version (desktop or mobile): macOS Catalina

**Comment by novykh** [comment]
The issue should be caused by this: https://github.com/grommet/grommet/blob/2a38c185e178ff63d87c7868d5e52dd609f4d284/src/js/components/Drop/DropContainer.js#L271

**Comment by ShimiSun** [comment]
I think this issue is already fixed on the [stable](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) branch.

**Comment by ShimiSun** [comment]
Fixed was released on Grommet 2.14.0. Thanks for reporting!
