### ISSUE TITLE
Grommet icon isn't aligning with text beside it vertically

### ISSUE THREAD

**Issue by RobKohr** [grommet/grommet#4133]
I am putting the icon next to text, and tried margins, padding, alignment, etc. I can't center the icon next to the text

### Expected Behavior

Icon vertically aligns with text

### Actual Behavior

They are misaligned

### URL, screen shot, or Codepen exhibiting the issue
```
  <Text size="large" weight="bold" color="lightseagreen">
            <StatusGood color="lightseagreen" />
            Completed!
  </Text>
```
![image](https://user-images.githubusercontent.com/26756/83400808-81d60280-a3d1-11ea-8826-031f40f4d8ba.png)

### Steps to Reproduce
Just using the code sample above would work. Trying to wrap it various ways still results in the same layout

### Your Environment

    "grommet": "2.13.0",
    "grommet-icons": "^4.4.0",

**Comment by ShimiSun** [comment]
Wrap it in a box with the `align` or `justify` properties, it should do the trick.

**Comment by ShimiSun** [comment]
I'll be closing the issue, feel free to reopen and add more info if needed.
