### ISSUE TITLE
Button inconsistent padding

### ISSUE THREAD

**Issue by sabarnix** [grommet/grommet#4134]
### Expected Behavior
Button padding should be consistent for StyledButtonKind.js and StyledButton.js

### Actual Behavior

https://github.com/grommet/grommet/blob/2a38c185e178ff63d87c7868d5e52dd609f4d284/src/js/components/Button/StyledButtonKind.js#L36
https://github.com/grommet/grommet/blob/2a38c185e178ff63d87c7868d5e52dd609f4d284/src/js/components/Button/StyledButton.js#L44

button reads button padding from different key 'pad' in  StyledButton and 'padding' in StyledButtonKind

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: NA
- Operating System and version (desktop or mobile): NA

**Comment by ShimiSun** [comment]
Sounds like you already have an idea of how to solve the issue, feel like submitting a PR?

**Comment by sabarnix** [comment]
Will submit a PR by tomorrow
