### ISSUE TITLE
Range input lower color seems to not work

### ISSUE THREAD

**Issue by c3s4** [grommet/grommet#4144]
### Expected Behavior
Have the range input track color befor the thumb as in the provided theme.

### Actual Behavior
The lower and upper colors provided in the theme are completly ignored but in the storybook of the library work as expected

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-range-input-colors-bbyuf

Here your original storybook working example: https://storybook.grommet.io/?path=/story/rangeinput--bounds

I copied the same code to make my sand box

**Comment by c3s4** [comment]
ok, I found it inside online documentation so I thought was available.

Thank you

**Comment by ShimiSun** [comment]
Happy to hear you found this feature valuable :)
