### ISSUE TITLE
[TS] Calendar: disabled dates (buttons) receive number instead of boolean for disabled prop

### ISSUE THREAD

**Issue by tpinne** [grommet/grommet#4146]
### Expected Behavior
Date buttons receive boolean value if disabled instead of number.

### Actual Behavior
If you define disabled dates via prop you get a console error/warning ```Warning: Failed prop type: Invalid prop `disabled` of type `number` supplied to `Button`, expected `boolean`.```

Have a look a this sandbox: https://codesandbox.io/s/react-typescript-0v6jy?file=/src/index.tsx and watch the console (see screenshot)

![Bildschirmfoto 2020-06-04 um 18 38 41](https://user-images.githubusercontent.com/1384345/83786846-423e3d80-a693-11ea-9b51-4c5787e5df44.png)

### Your Environment

See code sandbox

- Grommet version: latest
- Browser Name and version: all

**Comment by britt6612** [comment]
@tpinne I opened the example that you provided and was not able to see the error ? I may be missing something I wanted to check with you on your end if the error is still showing up. 😄

**Comment by tpinne** [comment]
That's because the supplied date range is in the past now I guess. I updated the sandbox to have bound in august. And there the typescript warning still pops up. 
https://codesandbox.io/s/react-typescript-2f3dh

**Comment by britt6612** [comment]
@tpinne thank you I will look at this now!

**Comment by lmuntaner** [comment]
I got the same issue :)

**Comment by ShimiSun** [comment]
The fix will be available on our next release, thank you for reporting!
