### ISSUE TITLE
Box background image is not applying the image

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#4155]
### Expected Behavior
Box background should display image.

### Actual Behavior
No image is displayed.

### URL, screen shot, or Codepen exhibiting the issue
```
      <Box
        pad="small"
        background={{
          image:
            "url(http://librelogo.org/wp-content/uploads/2014/04/gradient2.png)"
        }}
      >
        image
      </Box>
```

### Steps to Reproduce

Use the above code, or go to storybook https://storybook.grommet.io/?path=/story/box--background and see the 4th example isn't showing the background image.

### Your Environment
Chrome

- Grommet version: stable
- Browser Name and version: Chrome latest
- Operating System and version (desktop or mobile): Found on desktop

**Comment by ericsoderberghp** [comment]
I think the problem is with the URL not being available anymore, not a problem within Grommet.

**Comment by ShimiSun** [comment]
action item for this issue will be to apply a working image example to fix the story.
