### ISSUE TITLE
DropButton Content Doesn't Respond to Dark Mode

### ISSUE THREAD

**Issue by ArcticHen7** [grommet/grommet#4160]
### Expected Behavior

When a DropButton element is clicked while the app's theme is set to "dark" in the defaultMode property of the theme, the background of the Box should be dark.

### Actual Behavior

When a DropButton is clicked while the app is in dark mode, the dropContent's background remains light.

### URL, screen shot, or Codepen exhibiting the issue

CodePen URl:
https://codesandbox.io/s/grommet-v2-template-xe041

Click on the Example DropButton, and you'll see that the dropContent has a light background, despite the app being in dark mode.

### Steps to Reproduce

1. Create a simple Grommet app.
2. Set a theme to use `defaultMode: "dark"`, then make the top-level Grommet container use that theme, as opposed to the default `grommet` theme.
3. Click on the DropButton, and you'll see that the dropContent is light.

### Your Environment

As in the CodeSandbox, these are the dependency versions:
- grommet: 2.12.0
- grommet-icons: 4.4.0
- react: 16.6.1
- react-dom: 16.6.1
- styled-components: 5.0.1

## Side Note
Grommet is seriously awesome. Thank you so much guys for creating an incredible replacement to Material Design!

**Comment by ShimiSun** [comment]
Good catch!
In the meanwhile try to use 
```
const theme = {
   drop: {
      extend: 'background-color: { dark: ..., light:... }
   }
}
```

**Comment by netochaves** [comment]
This is because in `base.js` a default white color is defined and replaces the theme color:
https://github.com/grommet/grommet/blob/07203885d5da564695390038b09c8ddb9d81044e/src/js/themes/base.js#L220

Should this be removed?

**Comment by ShimiSun** [comment]
I think what we should do is to add a default dark light colors instead of hardcoding it to white.
