### ISSUE TITLE
focusIndicator on Select shouldn't work unless Select uses `plain`

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#4165]
### Expected Behavior
focusIndicator on Select shouldn't work unless Select uses `plain.

See the docs: 
https://v2.grommet.io/select#focusIndicator

### Actual Behavior
focusIndicator should affect the focus behavior only when the component is using `plain`.

### URL, screenshot, or Codepen exhibiting the issue
https://v2.grommet.io/select#focusIndicator

```
function Example() {
  const [value, setValue] = React.useState('medium');
  return (
    <Select   
      focusIndicator={false}
      options={['small', 'medium', 'large']}
      value={value}   
      onChange={({ option }) => setValue(option)}
    />
  );
}
```

### Steps to Reproduce

1. Open the code example
2. Notice how the focus is gone 
3. Focus should be there unless the component is using `plain`

### Your Environment
any

- Grommet version: latest
- Browser Name and version: any
- Operating System and version (desktop or mobile): any

**Comment by julieg18** [comment]
Hello! I'd like to try fixing this bug. Can I contribute?

**Comment by britt6612** [comment]
@julieg18 of course let us know if you need anything but feel free to put up PR
