### ISSUE TITLE
ie11: Sidebar animation in the wrong direction with button type='submit'

### ISSUE THREAD

**Issue by jesseolsen** [grommet/grommet#4167]
### Expected Behavior

When a sidebar closes, the animation should go the correct direction.

### Actual Behavior

I found a grommet bug where in ie11 the sidebar slides back on close the wrong direction (all other browsers are okay).  This is only when the sidebar has a button with type='submit' (if type='button' there is no issue). 

### URL, screen shot, or Codepen exhibiting the issue

 Since it's ie11, sandbox doesn't work, so I created a create-react-app simple sample to show this: https://github.com/jesseolsen/grommet-starter-new-app/pull/1

### Steps to Reproduce

1. 2. 3.
Run the code above.  Note the sidebar on the right.  CLick the Toggle button on the top, center.  The sidebar goes away, but the animation is going left instead of right.  Note that if the button on the sidebar is switched to type='button' instead of 'submit' then the animation is the correct direction (but in my case I need the button to be type='submit')

### Your Environment

ie11 (other browsers, including older Edge, are fine)

- Grommet version:
2.13.0

- Browser Name and version:
ie11 (other browsers, including older Edge, are fine)

- Operating System and version (desktop or mobile):
Windows 10 Desktop

**Comment by IanKBovard** [comment]
@jesseolsen are there any errors being reported? or, is the console clear?

**Comment by IanKBovard** [comment]
could be a rerender happening when submitting

**Comment by ShimiSun** [comment]
@IanKBovard were you able to reproduce the issue? Try to reach @jesseolsen on slack for a quick turnaround.

**Comment by IanKBovard** [comment]
@jesseolsen 

Is this the issue?
![Kapture 2020-06-29 at 12 19 14](https://user-images.githubusercontent.com/21990914/86035981-cb326580-ba02-11ea-9533-2866ca9c681f.gif)

Not sure of the fix to this, but it looks like submit buttons are causing the layer component to rerender. This is why you see the open animation again, right before the layer is removed. Keeping the button as type button and running the submit logic within an onClick could work around the issue. 

Something like this.
```
<Button
  type="button"
  label="button"
  onClick={() => {
    // ...run submit logic here
    setLayer(false)
  }}
/>
```

**Comment by jesseolsen** [comment]
@IanKBovard Yes, you have reproduced it.  Thanks!

**Comment by jesseolsen** [comment]
@IanKBovard, As this is an ie11 only, cosmetic issue, it is no longer a high priority for us.

**Comment by IanKBovard** [comment]
IE11 can be tricky, thanks for closing the issue @jesseolsen.
