### ISSUE TITLE
Pressing `Enter` in List results in 2 onClickItem calls

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#4173]
### Expected Behavior

When the user presses `Enter` on a list item one call should be made to `onClickItem`

### Actual Behavior

Instead when a user presses `Enter` two calls are made to `onClickItem`

### URL, screen shot, or Codepen exhibiting the issue

<img width="560" alt="Screen Shot 2020-06-10 at 3 11 10 PM" src="https://user-images.githubusercontent.com/54560994/84319148-c75ea200-ab2c-11ea-8eb8-4e754356e4f3.png">

### Steps to Reproduce
This issue is shown using the following test:
```
let onClickItem;
let App;

  beforeEach(() => {
    onClickItem = jest.fn();
    App = () => {
      return (
        <Grommet>
          <List
            data={[{ a: 'alpha' }, { a: 'beta' }]}
            onClickItem={onClickItem}
          />
        </Grommet>
      );
    };
  });

  afterEach(cleanup);

  test('Enter key', () => {
    const { container, getByText } = render(<App />);

    expect(container.firstChild).toMatchSnapshot();
    fireEvent.click(getByText('beta'));
    fireEvent.mouseOver(getByText('beta'));
    fireEvent.keyDown(getByText('beta'), {
      key: 'Enter',
      keyCode: 13,
      which: 13,
    });
    expect(onClickItem).toHaveBeenCalledTimes(2);
    expect(container.firstChild).toMatchSnapshot();
  });
```
This test will fail because `onClickItem` is called is 3 times instead of 2 (one from the fireEvent.click and 1 from the fireEvent.keydown on the Enter key).

**Comment by ShimiSun** [comment]
@halocline for some reason I can't assign you this issue (@MikeWalrath ?) see if you can assign yourself.
In the spirit of approaching List on the design-system, this could be a nice warm up for next week's task force work.

**Comment by halocline** [comment]
@MikeWalrath @ShimiSun I am unable to assign myself or take any administrative actions with issues in this repo.

**Comment by MikeWalrath** [comment]
Thanks @halocline can you try again?

**Comment by halocline** [comment]
Bingo! 🎉
