### ISSUE TITLE
Select with object value cannot be set back to undefined

### ISSUE THREAD

**Issue by MLRichmond** [grommet/grommet#4175]
### Expected Behavior

Select should accept `undefined` as valid value and clear the selected text (or show the placeholder if specified) when using objects as the value.

### Actual Behavior

Select continues to render the text of the last selected value instead of clearing or showing the placeholder.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-sandbox-9dux9?file=/src/Select.js

### Steps to Reproduce

1. Create a Select using objects as options with `valueKey` and `labelKey` to control the select.
2. Pass in `undefined` as the starting value.
3. Select a value from the drop down.
4. Using another control (like a button) set the Select's `value` prop back to `undefined`
5. Observe that the select continues to display the previously selected value.

Note: If using labelValue prop to render a custom label - the behavior gets even more interesting. When clear is clicked, the custom labelValue is removed, but the default Select rendering of the label still appears.

### Your Environment
- Grommet version: 2.13.0 
- Browser Name and version: Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10

**Comment by ShimiSun** [comment]
I've played with this one today, upgrading to 2.14.0 and it still reproduced.
However, I'm curious to why si you set the `value` to `undefined`  when clicked on the Clear Button?
Since there is no `undefined` value the Select didn't clear. I've replaced it with an empty object and it seems to work as expected https://codesandbox.io/s/grommet-sandbox-9dux9?file=/src/Select.js

Let me know what you think.

**Comment by MLRichmond** [comment]
Because in my code `value` is coming from a hook.

so I have an object like:
```
interface SelectOption {
    name:string;
    value:int;
}
```

Then in my component I have a hook like this:
```
const [selectedValue, setSelectedValue] = useState<SelectOption>();
```

That `selectedValue` is what I pass in to Grommet's Select. For Typescript with a hook, empty object is not a valid value. Trying to call `setSelectedValue({})` will yield an error. The "no selection" value for this hook needs to be `undefined`. That's also the value it holds until the first set as well.

**Comment by ShimiSun** [comment]
@IanKBovard Can you please take a look at the specific scenario that's shared here?

**Comment by IanKBovard** [comment]
I could be wrong, but i don't think this is good practice. Setting an inputs value to undefined would make it an uncontrolled component. @MLRichmond Is there a reason it must be undefined, and not an empty string.

**Comment by MLRichmond** [comment]
@IanKBovard It can't be an empty string because the hook is predicated on an object that is not a string and Typescript does not allow for type mutability. That's why we're using it.

Therefore the only valid values for the hook are either an object of the appropriate type (in this example: SelectOption) - or undefined.

This article does a decent job of explaining how Typescript works with hooks and complex types.
https://www.carlrippon.com/typed-usestate-with-typescript/

Empty object or empty string are not valid values for this hook.

**Comment by IanKBovard** [comment]
@MLRichmond I gotcha, thanks for clearing that up. I'm not too familiar with typescript, but it doesn't look like the article refers to setting the value of an input (submitResult sounds like, to me, all the data is collected on submit and then stored in that variable). It still isn't good practice to set the value of an input from uncontrolled to controlled. The example looks like its a collection of all form data, and isn't used to render the value of an input. 

I've gone back to grommet version 2.10, and was not able to use undefined as a value.

I would approach it this way
https://codesandbox.io/s/grommet-sandbox-hgdl7?file=/src/Select.js:0-1239
value and formdata are handled separately, so you're not changing a component from uncontrolled to controlled, and back again.

**Comment by MLRichmond** [comment]
That places the burden of managing the value on the consumer instead of the control which seems backwards. The solution you've offered doesn't make sense as all it does is say "don't really use objects for your value - just use a string".

The Select control allows complex objects to be used as values. This was done explicitly in your typescript defs.
`value?: string | JSX.Element | object | (string | object)[];`

As such, if you want to work with Typescript, that value should tolerate undefined since that is the default value for Typescript Hooks with complex object types.

If you want to sanitize the input before it reaches the actual `<input/>` tag to prevent the uncontrolled component, that seems a reasonable measure for the Select component to do and can be done as simply as `<input value={value && ""}`. Fixing the placeholder may take a bit more work since there's something amiss with the memo there. That's the only reason I haven't attempted to fix it myself.

It seems really odd to publish a typescript definition that accepts objects but then place the burden on the consumer to not actually send the Typescript default value for that object.

**Comment by MLRichmond** [comment]
Forgot to tag @IanKBovard on the last reply. Hope it helps.

**Comment by IanKBovard** [comment]
@MLRichmond I am hesitant to sanitize the input, because passing undefined would make it an uncontrolled component. This is default react behavior. I would have to discuss it with @ShimiSun or @ericsoderberghp to see what they want to do. 

If you can give me examples of people passing undefined to inputs with react typescript that would help me. I've seen examples use null, but not undefined.

https://www.carlrippon.com/typed-usestate-with-typescript/
This article here doesn't say anything about setting an inputs value to undefined, just about setting state.

Also, if you could show me an example of when it was working with grommet that would help as well. I've checked down to grommet 2.10 and you are unable to pass undefined as a value to an input.

**Comment by MLRichmond** [comment]
@IanKBovard I'll defer to @ShimiSun and @ericsoderberghp on that - but I don't see how passing undefined makes it intrinsically an uncontrolled component. Passing it all the way to the input would, I agree. But I can't find any documentation that says it becomes uncontrolled the second it takes an undefined prop. 

In fact, trying this
[sandbox](https://codesandbox.io/s/wizardly-hypatia-f6wol?file=/src/TextInput.js)

With the TextInput page - I have a "Test" control that sanitizes the input it receives so that it can still render properly, but follows the "controlled component" model, as far as I can tell, It takes its value from a prop, sanitizing it if needed, and then notifies changes on a callback. This component doesn't throw any of the "changing an uncontrolled input of type text to be controlled" warnings we see with passing undefined to the control as currently implemented.

**Comment by IanKBovard** [comment]
@MLRichmond Your example doesn't pass an undefined value to the control, it always passes a string. As shown here `value={this.props.value === undefined ? "" : this.props.value}`. 

here's a simpler example showing the error https://codesandbox.io/s/interesting-diffie-8tycr?file=/src/App.js

I'm very reluctant to sanitize values any more than we should. If a user passes `undefined` through to an input, my assumption is that they intended to. Changing it into a string without their knowledge seems like it could create more problems in the future.

It only takes one line of code on the users end to address this issue, and I still believe it's the best approach to this.

**Comment by MLRichmond** [comment]
@IanKBovard You asserted 

> I am hesitant to sanitize the input, because passing undefined would make it an uncontrolled component.

The example was to show that just accepting `undefined` as a prop, which the "Test" component accepts, does not make it uncontrolled. It is perfectly capable of sanitizing that input before it is sent to an Input without issue.

If Grommet doesn't want to sanitize inputs, that's a perfectly fine stance to take - but this issue could not be more simple.

Complex objects are reasonable to use as datasources in Selects. A hook is an incredibly simple way to store and set a single selected value. It should be usable as a value and setValue in a Grommet component. In any other framework, this is databinding 101.

In Typescript, a hook using a complex object that has no value is reflected as `undefined`. I didn't decide this. Typescript did. Therefore if Grommet claims to be Typescript friendly, it stands to reason that a hook should be mappable to the value and onChange of a Select control and that it should accept "undefined" as a valid "empty" value.

Alternatively, dispense with the pretense of Grommet being Typescript friendly because my experience so far has strongly indicated that no one on the Grommet development team actually uses Grommet with Typescript.

**Comment by ShimiSun** [comment]
@jcfilben Please take a look and confirm whether this issue is still relevant. We have done many TS improvements and I think we might have solved it already. Thanks!

**Comment by jcfilben** [comment]
This issue is still relevant, here is an updated [codesandbox](https://codesandbox.io/s/grommet-sandbox-forked-r99sb?file=/src/Select.js). 
That being said, I agree with what was said above about not wanting to sanitize inputs and that if a user passes `undefined` it shouldn't be changed into an empty string by default.
