### ISSUE TITLE
Clean up all dev warnings and errors on running`yarn test`

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#4177]
### Expected Behavior
No warnings and errors

### Actual Behavior
Existing errors and warnings that need to be addressed.

### Steps to Reproduce

1. run `yarn test` 
2. view the warnings and errors

### Your Environment
Any

**Comment by ShimiSun** [comment]
Excellent work on this one! Can we close it?

**Comment by jcfilben** [comment]
Yes this issue can be closed
