### ISSUE TITLE
Selection visualization within Select with searchPlaceholder is wrong

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet#4178]
### Expected Behavior

When opening a select with a searchPlaceholder, I should clearly see the selected item.

### Actual Behavior
This is showing an expanded Select with option 1 selected:
![image](https://user-images.githubusercontent.com/17883783/84438881-7ade9980-abf4-11ea-8d60-49822f0afc97.png)

This is showing an expanded Select (with searchPlaceholder) and option 1 selected:
![image](https://user-images.githubusercontent.com/17883783/84438939-92b61d80-abf4-11ea-8faa-5160d4ca9021.png)

The selection highlighting is incorrect in the second case.  As soon as I hover over any of the items in the second case, the selection highlighting changes to be correct.

**Comment by ShimiSun** [comment]
I think this issue is fixed on the Recent release (2.14.0), can you please verify?

**Comment by ShimiSun** [comment]
Confirmed this was fixed on the recent release, closing.
