### ISSUE TITLE
Would like ability for RadioButtonGroup styling to be set in theme

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#4184]
### Expected Behavior

I'd like to be able to specify styling for RadioButtonGroup in a theme, specifically the options `gap`.

### Actual Behavior

Theme not currently referenced.
RadioButtonGroup styling can not be set in theme (e.g. desired gap size)
  - Same applies to CheckBoxGroup

Use case. HPE Design System designs desire a gap of none between RadioButtonGroup and CheckBoxGroup options. Implementers can achieve this by setting the `gap` property for each instance, however for the Design System, this specification would make sense to live in the theme.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jackjwilliams** [comment]
I'd like to take a stab at this this weekend.

Any other specific props other than gap you'd like implemented first?

**Comment by ShimiSun** [comment]
Thanks @jackjwilliams! I think we should just provide the option for the styling but not set anything as a default to keep the component backward compatible.

**Comment by jackjwilliams** [comment]
Sorry life has gotten a little busy as of late, I won't be able to take this issue

**Comment by netochaves** [comment]
I would like to work on this

**Comment by ShimiSun** [comment]
Thanks for letting us know @jackjwilliams, and Thank you @netochaves , that will be awesome.
