### ISSUE TITLE
Would like RadioButton input background color to be specified via theme

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#4187]
### Expected Behavior

Able to set the background color of the check input in my theme.

### Actual Behavior

Currently need to specify this via `extend`

Background: https://github.com/grommet/grommet-theme-hpe/pull/75#discussion_r437616833

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by joybh98** [comment]
@ShimiSun is this issue open?

**Comment by ShimiSun** [comment]
Yes buddy, want to take a stab at it? go for it!

**Comment by netochaves** [comment]
Can I work on this?
