### ISSUE TITLE
Grommet Themer seems to be broken 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet#4197]
### Expected Behavior
Navigate through https://theme-designer.grommet.io/Dashboard seamlessly 

### Actual Behavior
On https://theme-designer.grommet.io/Dashboard when you click the "forms" button on the left the page goes blank. 

### Steps to Reproduce

1. Go to https://theme-designer.grommet.io/Dashboard
2. Click on the form link on the left hand side of the page 

### Your Environment

- Grommet version:
- Browser Name and version: Mac Chrome and FF
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
This issue is specific to the theme-designer and should be filed in https://github.com/grommet/grommet-theme-designer. I don't think it is Grommet core related.

**Comment by MikeWalrath** [comment]
Apologies, I will file in the correct repo.
