### ISSUE TITLE
Search input 

### ISSUE THREAD

**Issue by JetLim** [grommet/grommet#422]
On clicking the search icon control, a drop down menu opens with the focus selector remaining on the search icon control. However a search text cannot be entered. Is this intentional? 

It would be great if the user can type into the field while the menu is open. (Similar to Piano)

reference
[http://www.grommet.io/docs/hpe/develop/searchinput](url) 
## 

When on the control, do we allow using a [down arrow] key to open the menu? (Similar to Piano)
## 

@ericsoderberghp @L0ZZI

**Comment by ericsoderberghp** [comment]
We have deprecated SearchInput in favor of Select and TextInput, in part in response to this issue. Thanks.
