### ISSUE TITLE
<MaskedInput /> doesn't work (onChange event doesn't have a event.currentTarget.value)

### ISSUE THREAD

**Issue by Robbie-Cook** [grommet/grommet#4222]
### Expected Behavior

If I pass a value and a onChange event handler (event) to a MaskedInput, and start typing I should get a currentTarget.value or a target.value out of the event that is returned.

### Actual Behavior

If I pass a value and a onChange event handler (event) to a MaskedInput, I never get a currentTarget.value or a target.value out of the event that is returned.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/masked-input-error-w3niq?file=/src/App.js

### Steps to Reproduce

Make a component like so:
```javascript
import React from "react";
import "./styles.css";
import { MaskedInput, Paragraph, TextInput } from "grommet";

export default function App() {
  const [brokenText, setBrokenText] = React.useState("hello");
  const [workingText, setWorkingText] = React.useState("hello");

  return (
    <div className="App">
      <Paragraph>Please try entering text in the input below:</Paragraph>
      <MaskedInput
        value={brokenText}
        onChange={event => {
          setBrokenText(event.currentTarget?.value);
        }}
      />
      <Paragraph>This is a text input, so it works:</Paragraph>
      <TextInput
        value={workingText}
        onChange={event => {
          setWorkingText(event.currentTarget?.value);
        }}
      />
    </div>
  );
}
```

### Your Environment

- Grommet version: 2.14.1
- Browser Name and version: Chrome (latest)
- Operating System and version (desktop or mobile): desktop MacOS

**Comment by netochaves** [comment]
We should set a default regex, something like `[^]*`. What do you guys think?

I'll open a PR if that's ok.

**Comment by Robbie-Cook** [comment]
Thanks @netochaves , I didn't realise it was related to me not setting a mask. Appreciate your quick PR!
