### ISSUE TITLE
Props not being passed from Tabs to Tab when using custom Tab component

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet#4224]
I have a component that uses Tab at the top level:
```
const MyTabComponent = props => (
  <Tab title="Tab 2" {...props}>
      <Text>Content for the Second tab</Text>
  </Tab>
);
```

When I render it within tabs like this:
```
<Tabs>
      <Tab title="Tab 1">
         <Text>Content for the First tab</Text>
      </Tab>

      <MyTabComponent />
</Tabs>
```

"Content for the First tab" is displayed in Tab 1 but "Content for the Second tab" is not displayed within Tab 2.

### URL, screen shot, or Codepen exhibiting the issue

Code: https://codesandbox.io/s/grommet-sandbox-tab-composition-issue-447vm?file=/src/Tabs.js
Demo: https://447vm.csb.app/tabs

### Your Environment

- Grommet version: 2.14.0

**Comment by ShimiSun** [comment]
@taysea For some reason, I can't assign you to the issue, see if you can assign yourself or maybe @MikeWalrath will be able to assign you.
Since you worked on Tabs for the design system, this might be a good one for you to tackle for next week's task force work.

**Comment by ShimiSun** [comment]
Fix will be available on our next release, thanks for reporting, and thank you @taysea for the fix!
