### ISSUE TITLE
More theme support for customization of font family per component

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#4225]
### Expected Behavior

More components in the theme object should support customization by specifying a `family` property for those components. I was attempting to customize `List` while a coworker is trying to customize `Anchor`. Using the extend function is a workaround for now.

### Actual Behavior

Only `Heading` and `Button` support `family` on the theme object.

### Steps to Reproduce

1. 2. 3. N/A

### Your Environment

- Grommet version: v2.x
- Browser Name and version: N/A
- Operating System and version (desktop or mobile): N/A

**Comment by ShimiSun** [comment]
Thank you for raising this issue. Looking at the bigger picture from the design aspect, we need to come up with a list of components it will make sense to have the setting of the font on the theme. 
For example, I see a use case Heading having its own font that is different than the overall app, but that wouldn't be true to all of our components. Can you share some of your designs that can help demonstrate your requirements use case?

**Comment by srallen** [comment]
Ok, I was incorrect that it was an `Anchor` needing font family customization. Here's one of the designs in question:

https://invis.io/Z5WTSPMUQEY#/412548720_title (this should be public, but do let me know if you can't see it)

There is a serif and a sans-serif font face. The `Headings` can be customized to use the serif font face, but it'd be useful to be able to apply this to `Text` and `Paragraph` as needed.

Our other case is this: https://invis.io/UAN6AP0JTBC#/420788232_91-4_Text_Transcription_Line_Text_Previous_classifications

The `List` component is using a monospaced font face that is different from the default.

**Comment by ShimiSun** [comment]
Thank you for filing this interesting issue and sharing your use cases, it helped us come to the resolution on PR #4513.

The request for `font-family` support on Text, Paragraph, and List, was considered and the use cases (designs) you provided helped us get to the realization of what we think will be the most generic approach for grommet to take forward.

Our thoughts were that it would make sense to allow `font-family` for Typography components i.e. Text & Paragraph, but less for visualization components such as List. we can see a need to customize text/font for Typography components more frequently and less for tables/lists which are visualization components and we'd like to keep their API clean. 
That being said you can always use the theme `extend` to apply specific `font-family` to any component that is not providing it out of the box (such as List) which I believe is your current workaround at the moment. 
Thank you for your cooperation on this issue, and we hope you enjoy the fix @jcfilben has provided! Bests.

**Comment by srallen** [comment]
That's reasonable. Thank you!
