### ISSUE TITLE
Test coverage for Form

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#4227]
Increase test coverage for Form component

**Comment by ShimiSun** [comment]
Is this issue a duplication of https://github.com/grommet/grommet/issues/4166? Or do you need a separate issue?

**Comment by jcfilben** [comment]
I created a separate issue because this issue is focusing on the coverage of Form whereas issue #4166 is just focused on testing for controlled and uncontrolled forms. They are closely related though so they could be combined into one issue

**Comment by ShimiSun** [comment]
I'm OK if we want to keep them separated
