### ISSUE TITLE
Select component not working with `required` prop on Form field

### ISSUE THREAD

**Issue by JoeButler7** [grommet/grommet#4235]
### Expected Behavior
When putting a `Select` component inside of a `FormField` with the `required` prop the form should not submit unless there is a value in `Select` 

### Actual Behavior
The Form does not submit if the `Select` component has no value but it also does not submit if the `Select` component does have a value

### URL, screen shot, or Codepen exhibiting the issue
<img width="728" alt="Screen Shot 2020-06-26 at 4 29 31 PM" src="https://user-images.githubusercontent.com/49867133/85898852-064a5400-b7cb-11ea-9752-44dc2ff8cbec.png">

Codesandxox example https://codesandbox.io/s/grommet-v2-template-bv773?file=/index.js

### Steps to Reproduce
1.) Choose a value from the `Select` component
2.) Click the Submit button

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Happens both in Chrome Version 83.0.4103.116 and Firefox 77.0.1 
- Operating System and version (desktop or mobile): Mac OS Catalina 10.15.5

**Comment by netochaves** [comment]
I think you're missing the `name` prop in Select.
```diff
<Form onSubmit={({ value }) => {}}>
          <FormField name="test" label="Test" required>
-            <Select options={["one", "two", "three"]} />
+            <Select name="test" options={["one", "two", "three"]} />
          </FormField>
          <Button type="submit" primary label="Submit" />
</Form>
```

**Comment by JoeButler7** [comment]
@netochaves Thanks that seemed to work! We'll be closing the issue now

**Comment by ShimiSun** [comment]
Thank you @netochaves !
