### ISSUE TITLE
Header in IE11 does not honor align="center" correctly

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#424]
<img width="927" alt="screen shot 2016-02-25 at 8 49 36 am" src="https://cloud.githubusercontent.com/assets/11637956/13326964/c85e674e-db9c-11e5-855a-a90dec19d2e4.png">

**Comment by kylebyerly-hp** [comment]
May also be related to Title in Header is cut off in IE11 #239

**Comment by ericsoderberghp** [comment]
This is only an issue with IE11. Cannot reproduce on Edge 13.

**Comment by ericsoderberghp** [comment]
Fixed in 901ff1ccefd928228737598987b0ab93c25c6a66 and in grommet-index 7a0f66a22cad6b5d46018167d1a4a9c2457d9700.
