### ISSUE TITLE
[Menu component] children prop missing from documentation

### ISSUE THREAD

**Issue by markjackson02** [grommet/grommet#4247]
The `<Menu />` component takes a `children` prop that is not documented https://v2.grommet.io/menu but is used in this Storybook example https://storybook.grommet.io/?path=/story/menu--custom

**Comment by ShimiSun** [comment]
Great catch, thanks for reporting. Also true for Button which Menu is inheriting it from.

**Comment by ShimiSun** [comment]
Thank you for reporting, and thank you @britt6612 for addressing!
