### ISSUE TITLE
IE11 Layer does not turn off all scrollbars

### ISSUE THREAD

**Issue by kylebyerly-hp** [grommet/grommet#425]
At least until you leave focus for a certain amount of time.
![image](https://cloud.githubusercontent.com/assets/13527666/13328261/fa48d6e6-dbaa-11e5-84d4-d22ab6dc504e.png)

Steps to reproduce.
Mouse over section with a scrollbar, click a layer button.

**Comment by ericsoderberghp** [comment]
Cannot reproduce on IE11.
