### ISSUE TITLE
Clock: Docs for onChange not aligned with actual behavior

### ISSUE THREAD

**Issue by tpinne** [grommet/grommet#4251]
### Expected Behavior

The docs describe the actual behavior of the onChange handler.

### Actual Behavior

The docs state that the current time as ISO string is returned. But instead a duration or something like `T15:59:21` is returned.
### Your Environment
- Grommet version: 2.13.0
- Browser Name and version: does not matter
- Operating System and version (desktop or mobile): does not matter

**Comment by ShimiSun** [comment]
On [Grommet release 2.14.0](https://github.com/grommet/grommet/releases/tag/v2.14.0) we had some improvements and changes on the Clock component, can you please confirm you see the issue there as well?

**Comment by tpinne** [comment]
I looked back through to release 2.7.0 and since then (I guess in older releases as well) the strings which are emitted by the onChange handler are exactly the same as in 2.14.0. So it seems the docs have been wrong for the onChange handler for quite some time.

Screenshot from the docs:
![Bildschirmfoto 2020-07-02 um 12 03 42](https://user-images.githubusercontent.com/1384345/86345676-227f4280-bc5c-11ea-8202-1981acbb59bd.png)

What the onChange handler really exposes is either `T15:59:21` or `P15H59M21S` as seen in https://github.com/grommet/grommet/blob/000ff1d09d3e8f27ec6a416ecb4a98a8775f5f10/src/js/components/Clock/Clock.js#L131-L138
