### ISSUE TITLE
[Typescript] Clock: Typings for onChange handler not aligned with actual implementation

### ISSUE THREAD

**Issue by tpinne** [grommet/grommet#4252]
### Expected Behavior

The typings are aligned with the actual code. 

```typescript
export interface ClockProps {
  // ...
  onChange?: ((varName: string) => void);
  // ...
}
```

### Actual Behavior
```typescript
export interface ClockProps {
  // ...
  onChange?: ((...args: any[]) => void);
  // ...
}
```

### Your Environment

- Grommet version: 2.13.0
- Browser Name and version: not relevant
- Operating System and version (desktop or mobile): not relevant

**Comment by ShimiSun** [comment]
Feel free to file a PR,  sounds like you've already reached a solution. https://github.com/grommet/grommet/blob/master/src/js/components/Clock/index.d.ts
