### ISSUE TITLE
Width of the DataTable doesn't extend to its container's width in Firefox Developer Edition

### ISSUE THREAD

**Issue by johnliu55tw** [grommet/grommet#4267]
I recently started to try out Firefox Developer Edition and I noticed that DataTable, by default, will not extend its width to its container's width, which is different from Chromium.

### Expected Behavior

The behavior should be consistent in both browsers, that the width of DataTable should be extended to the width of its container Box.

### Actual Behavior

DataTable in Firefox Developer Edition does not extend its width to its container's width.

### URL, screen shot, or Codepen exhibiting the issue
- Left: **Firefox Developer Edition**
- Right: **Chromium**
![image](https://user-images.githubusercontent.com/5047724/86529192-430bfe80-bee1-11ea-8348-1b33605ce72f.png)

- Codesandbox Link: https://codesandbox.io/s/datatabletest-4ttje

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version:
  - Chromium - 83.0.4103.116
  - Firefox Developer Edition - 78.0b9 
- Operating System and version (desktop or mobile): Arch Linux Desktop

**Comment by IanKBovard** [comment]
@britt6612 and I have been looking at this issue. If you add width to the wrapping box, the issue is fixed.

https://codesandbox.io/s/datatabletest-0m73v?file=/src/App.js

**Comment by IanKBovard** [comment]
@johnliu55tw let me know what you think.

**Comment by johnliu55tw** [comment]
@britt6612 Thanks for the solution!

But I just found if I set the width to `{min: 'medium', max: '100%'}`, it breaks again :(
https://codesandbox.io/s/datatabletest-ejt90?file=/src/App.js

**Comment by IanKBovard** [comment]
You have to give it an explicit width. Table is set to inherit width from it's parent. 
style={{ width: '...', minWidth: '...', maxWidth:'...'}}

**Comment by IanKBovard** [comment]
@johnliu55tw this is an issue with firefox handling css a little different than chrome. The table is set to inherit its width from its parent. if you set a width(not just min and max width), the problem is resolved. Let me know what you think, and we can close this issue.

**Comment by johnliu55tw** [comment]
@IanKBovard Sorry I got busy lately...Thanks for the explanation!
