### ISSUE TITLE
FormField required parameter doesn't work.

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#427]
I use FormField with "required" parameter, it doesn't work. The grommet.js has "--required" function, but the css files grommet-aruba.css, grommet-hpe.css, grommet-hpinc.css, grommet.css don't work for "--required" function.

**Comment by tearsofphoenix** [comment]
some other `bool` field also not work in several components, such as `Header`. It seems grommet not fit with latest babel syntax.

**Comment by bryanjacquot** [comment]
Our recommendation to handle required fields with validation messages when the user attempts to submit the form.  We also recommend having good defaults for all fields that allows users to input fields without having to interact with all form elements.  In addition, apps may a label to indicate which fields are optional that do not have an obvious default value.
