### ISSUE TITLE
Select component not working with react-hook-form ref should be forward to input instead on styled box

### ISSUE THREAD

**Issue by MathieuDoyon** [grommet/grommet#4273]
`<Select />` ref should be forward to input instead of `<Box />`

### Expected Behavior

React-hook-form use ref to register input fields. When submitting form `<Select .../>` selected value should be in the form data

### Actual Behavior

Select property value is missing from data received into onSubmit function

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/amazing-driscoll-m08if

### Steps to Reproduce

Fill all the fields in the form and submit

**Comment by martin-koenig** [comment]
I just ran into the same issue. Is there maybe already any solution to this?

**Comment by ericsoderberghp** [comment]
This is a tricky one. Select doesn't render a `<select />` element in the DOM. When there is no value, there is a `<button />` that handles focus and interaction, such as opening the drop containing the options. When there is a value, an `<input />` element is added to the DOM, which contains the actual value.

**Comment by Alkindi42** [comment]
Hello,

You can use [Controller component](https://react-hook-form.com/api/#Controller):

```js
<Controller
  name="gender"
  control={control}
  defaultValue="Female"
  render={({ onChange, value }) => (
    <FormField
      htmlFor="gender"
      label="Gender"
      error={errors.gender && errors.gender.message}
    >
      <Select
        name="gender"
        defaultValue={value}
        options={["Female", "Male"]}
        onChange={({ option }) => onChange(option)}
        />
      </FormField>
  )}
/>
```

It's not a perfect solution but it works.

**Comment by disbelief** [comment]
Thanks so much @Alkindi42! A few tweaks to your snippet got it working for me. I'll post my slightly modified version here (maybe a recent change to react-hook-form API is the reason for the difference):

```tsx
const options = [
  { label: 'brown', value: '1' },
  { label: 'blond', value: '2' },
  { label: 'grey', value: '3' },
  { label: 'blue', value: '4' },
];

return (
  <Controller
    name="hairColor"
    control={control}
    render={({ field: { name, value, onChange }, fieldState }) => (
      <Select
        {...fieldState}
        name={name}
        options={options}
        value={value}
        labelKey="label"
        valueKey={{ key: 'value', reduce: true }}
        onChange={({ value: nextValue }) => onChange(nextValue)}
      />
    )}
  />
);
```

**Comment by jcfilben** [comment]
Thanks for sharing your solution @disbelief and @Alkindi42. I'll go ahead and close this issue.
