### ISSUE TITLE
min-height in Box styles

### ISSUE THREAD

**Issue by pLavrenov** [grommet/grommet#4274]
### Expected Behavior

"min-height: 0" in Box styles breaks the layout and add the scroll, if it disabled from styles, then everything works fine.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/billowing-tdd-tweuf

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Google Chrome 83.0.4103.116
- Operating System and version (desktop or mobile): Mac desktop

**Comment by ShimiSun** [comment]
Can you please provide some guideness on what to do with the codesandbox? I don't see how and where you are using `min-height`.

**Comment by pLavrenov** [comment]
https://prnt.sc/tdhopt

https://prnt.sc/tdhph3

its a default Box component styles

**Comment by pLavrenov** [comment]
for correction, you can do so:

`<Box height={{
                        min: 'auto'
                    }} background="#fff">
                        Header sfdsdfs
                    </Box>`

but it seems to me wrong

**Comment by ShimiSun** [comment]
Interesting, thanks for sharing. 
I think it will be tricky to change the current behavior due to backward compatibility reasons. 
We'll need to take a closer look on your layout and see how it could be optimized.
I think the `min-height` is coming from https://github.com/grommet/grommet/blob/c13d1cfe05187aa17bee0bb39537f7c6ce603ff9/src/js/components/Box/StyledBox.js#L69

**Comment by phatcatmatt** [comment]
I'm having this issue as well.

**Comment by ShimiSun** [comment]
@IanKBovard I think you handled a similar case on a separate issue, can you elaborate?

**Comment by IanKBovard** [comment]
@pLavrenov has the correct solution.  `<Box height={{ min: 'auto' }}>Hello</Box>` will fix this issue.
Currently, I don't think changing the default min-height within grommet would be a good idea because it would cause backwards compatibility issues.

**Comment by ShimiSun** [comment]
I agree with @IanKBovard , I'll be closing this issue. feel free to share more feedback.
