### ISSUE TITLE
Grommet distributable is very large on file system

### ISSUE THREAD

**Issue by DeanKooiman** [grommet/grommet#428]
The grommet framework with all its dependencies is massive on the file system.  I believe this is due to the build infrastructure and utilities that are also included in the base distribution.  Delivering the grommet utilities and build chain as a separate package should drastically shrink the size of the repository.  

Additionally on later versions of NodeJS (I am on v4.2.0), developers have to include babel presets as direct dependencies, so including these dependencies directly provides no added benefit.
- "babel-preset-es2015": "^6.5.0",
- "babel-preset-react": "^6.5.0",

![image](https://cloud.githubusercontent.com/assets/17497972/13355925/f9aa8044-dc5f-11e5-89c9-bdf2d731b60c.png)

**Comment by ericsoderberghp** [comment]
Agreed. Alan Souza, along with Derek Ahn have been looking into separating out the build tasks from grommet.

**Comment by alansouzati** [comment]
Thanks for reporting this issue @DeanKooiman ! I have it in my short list of things to fix. I will keep you posted.

**Comment by bryanjacquot** [comment]
Addressed with the new Grommet Toolbox.  https://github.com/grommet/grommet-toolbox
