### ISSUE TITLE
Select `onOpen` being called twice & also is being called onClose

### ISSUE THREAD

**Issue by JoeButler7** [grommet/grommet#4283]
### Expected Behavior
When a select component is opened the function assigned to `onOpen` should only be called once. It also should not be called when select is closed
### Actual Behavior
The function assigned to `onOpen` is being called twice and it is being called a third time when the select is closed

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/select-onopen-bug-sz20x
![ezgif-2-1be2421a77d8](https://user-images.githubusercontent.com/49867133/87057169-89f53f00-c1d4-11ea-912a-fe5d3ac55986.gif)

### Steps to Reproduce
1.) Make sure the codesandbox console is open
2.) Click on the select to open it (click on the component, not the drop arrow as shown above)
3.) Check the console to see that the `onOpen` function was called twice ('Test' will be printed twice)
4.) Close the select
5.) Check the console to verify that `onOpen` was called a third time

### Note
There is a test in `src/js/components/Select/__tests__/Select-test.js` line 38 that asserts that `onOpen` is called twice when Select is opened. Once this issue is resolved the test will need to be updated
### Your Environment 

- Grommet version: 2.14
- Browser Name and version: Chrome 83.0.4103.116
- Operating System and version (desktop or mobile): Mac OS 10.15.5

**Comment by IanKBovard** [comment]
I'm unable to reproduce this issue, are there any more steps i'm missing?

![Kapture 2020-07-09 at 9 48 52](https://user-images.githubusercontent.com/21990914/87055176-9de77380-c1c9-11ea-8503-c19a364d1b07.gif)

**Comment by JoeButler7** [comment]
> I'm unable to reproduce this issue, are there any more steps i'm missing?
> 
> ![Kapture 2020-07-09 at 9 48 52](https://user-images.githubusercontent.com/21990914/87055176-9de77380-c1c9-11ea-8503-c19a364d1b07.gif)

I should have been more clear, you need to click on the component, not the drop icon to get the bug. If you were to click on just the box you will see the bug

**Comment by IanKBovard** [comment]
Ah! i gotcha. Thanks for clearing that up.

**Comment by netochaves** [comment]
Can I work on this?

**Comment by ShimiSun** [comment]
Fixed, thank you @netochaves !!
