### ISSUE TITLE
Theming in grommet -edgeSize

### ISSUE THREAD

**Issue by codebee25** [grommet/grommet#4296]
Hi, 
I have been trying to get a border for the circle graph using a grommet theme-edgeSize. It's been confusing, I am unable to get the border. Is there any suggestions. Thank you!
This is sample code for reference, I would like to get the border for the outline of the circle with increased thickness so it gets highlighted.

```
import React from 'react';
import { Meter } from '@bit/grommet.grommet.meter';

class Example extends React.Component {
  constructor() {
    super();
    this.state = {};
  }

  render() {
    const { active } = this.state;
    return (
      <div>
        <Meter
          type='circle'
          values={[
            {
              value: 60,
              onHover: over =>
                this.setState({ active: over ? 'First' : undefined })
            },
            {
              label: 'Second',
              value: 20,
              highlight: active === 'Second',
              onHover: over =>
                this.setState({ active: over ? 'Second' : undefined })
            }
          ]}
        />
      </div>
    );
  }
}

export default <Example />;
```

Taken from: https://bit.dev/grommet/grommet/meter

**Comment by ShimiSun** [comment]
It is not clear to me what you are trying to achieve, do you need the border on the Circle at all time or only on hover? can you share a design of what you are trying to achieve?

**Comment by codebee25** [comment]
Thanks @ShimiSun for responding. Yes , border on the circle at all time.

**Comment by ShimiSun** [comment]
First time I hear of a border on a meter circle, so we'll try to be creative here:
1. One way is to let a wrapping Box take care of the border: https://codesandbox.io/s/meter-with-border-6lfhw?file=/index.js
2. Use the theme `extend` of meter to add CSS that renders the border, I haven't done it myself but it will be similar to this attached example, look at the theme.js file and for the `meter` prop.
https://codesandbox.io/s/graphs-animations-bl9th?file=/src/theme.js:1314-1500

**Comment by codebee25** [comment]
Hi @ShimiSun. Thank you. I see a border for the Box. I am looking to have a border for each value with respective color. So in my code, two borders with light and dark green for two values 60 & 20. 

Example: http://beatexcel.com/interactive-donut-chart/ -- here it shows for one value. Can we have for all values.

**Comment by ShimiSun** [comment]
You'll need to manipulate it via css, we don't have an out of the box support for it. You can be creative and play with the theme extend as suggested above to achieve it.

**Comment by codebee25** [comment]
Sure. Is label display is feasible? I tried that one too but it doesn't display anything.

https://grommet-nextjs.herokuapp.com/examples/grommet/Meter/values

Tried todo something like this-https://docs.microsoft.com/en-us/sql/reporting-services/report-design/display-percentage-values-on-a-pie-chart-report-builder-and-ssrs?view=sql-server-ver15

**Comment by ShimiSun** [comment]
I see you filed a separate issue on that the team will take it there #4305
