### ISSUE TITLE
label display in grommet- Meter type circle

### ISSUE THREAD

**Issue by codebee25** [grommet/grommet#4305]
Hi,

I am trying to display a label for a graph but it wouldn't do anything as shown in the below example. 

https://grommet-nextjs.herokuapp.com/examples/grommet/Meter/values

Does grommet doesn't support displaying a label ?

eg: label: 'sixty' .

Tried todo something like this-https://docs.microsoft.com/en-us/sql/reporting-services/report-design/display-percentage-values-on-a-pie-chart-report-builder-and-ssrs?view=sql-server-ver15

**Comment by halocline** [comment]
Hi @codebee25, I put together a [few examples](https://codesandbox.io/s/grommet-issue-4305-display-meter-label-btpp7?file=/src/App.js) how you can currently display `labels` and `values` with `<Meter />` which resemble the pie chart example you referenced.

The approach is in these examples is to use the `<Stack />` component to compose the resulting pie charts w/ labels.

Additional resources for your reference include:
- [Meter storybook example](https://storybook.grommet.io/?path=/story/meter--multiple-values)
- [Chart](https://v2.grommet.io/chart)

Please let me know if the examples I put together end up helping you out. Cheers.

**Comment by ShimiSun** [comment]
I'll be closing the issue since @halocline provided great inputs. Feel free to reopen if needed.
