### ISSUE TITLE
Grommet 'Search input' and 'Search form fields'

### ISSUE THREAD

**Issue by JetLim** [grommet/grommet#431]
![search_input3](https://cloud.githubusercontent.com/assets/16657091/13369237/58e32484-dca7-11e5-8a81-02cfdda43257.png)

Search
http://www.grommet.io/docs/hpe/develop/search

Search input 
http://www.grommet.io/docs/hpe/develop/searchinput

On the onset the form field with 'search' icon control for both Search and Search input looks the same. However, it behaves differently. For Search input, the user can click the control then opens a drop down menu (it is also a Tab enabled element). 

The  other, the user could not click on the icon control nor is a tab enabled element. 

-
Can we make the control different (on Search Input field) than the 'Search' field ?
For example, adding a down arrow for a control with a drop down menu. This will make it obvious to the user that it is a clickable/press control > for a drop down menu.

![example](https://cloud.githubusercontent.com/assets/16657091/13369483/5ca6783e-dcaa-11e5-856a-69cce6b43aaa.PNG)

**Comment by tearsofphoenix** [comment]
+1

**Comment by L0ZZI** [comment]
I think we can merge the the Search and Search Inputs into a more ubiquitous design for Search.  I would suggest that we show suggestions when the property is present and the user focused on the field regardless of the field having a value or no value. If there property isn't present then we don't display the suggestions on focus. 

The other aspect of the design is the focus highlight and the Search icon strength. The other suggestion I would have is to, on text input put a box of in the brand color behind the search icon, and/or change the color of the icon to be more vibrant on input. While making the search icon submit the input text.

This would simplify the design and  clean up the areas you highlighted. Let me know what you think.

**Comment by ericsoderberghp** [comment]
Decided to split the SearchInput component into TexInput and Select components. TextInput is a text input field with optional suggestions, no icon. Select is a select-like component with optional search control in the drop down to allow filtering the options. The icon for Select is a caret-down. You cannot merely type in a value with Select, you must choose from one of the options.

**Comment by ericsoderberghp** [comment]
Fixed with addition of TextInput and Select.
