### ISSUE TITLE
'Tab' component has not extend in theme

### ISSUE THREAD

**Issue by whilemouse** [grommet/grommet#4310]
Grommet > component > Tab
tab compnent has not extend in theme

### Expected Behavior
I want use custom css in tab theme. 
So, I tried theme extend. 
But tab theme has not extend. Or is there another way to modify custom css(features not in the Document)?

### Actual Behavior
tab.extend is not found.

### URL, screen shot, or Codepen exhibiting the issue
https://v2.grommet.io/tabs

![image](https://user-images.githubusercontent.com/16111790/87508300-0642c300-c6aa-11ea-85f2-ab90294df2b6.png)

tab.hover.extend is exist. But, tab.extend is not found

### Your Environment

- Grommet version: 2.14.0

**Comment by ShimiSun** [comment]
Tab does have an `extend` option on theme https://github.com/grommet/grommet/blob/0a2f1fa5d249e43c3deb21ac24a83bb637a068de/src/js/components/Tab/StyledTab.js#L30, it should be documented though.

**Comment by whilemouse** [comment]
Thanks. ;)

**Comment by ShimiSun** [comment]
Keeping the issue open so we can add the missing prop to the documentation.
Feel free to make a contribution to Tab/doc.js file.
