### ISSUE TITLE
How to remove box-shadow in tab?

### ISSUE THREAD

**Issue by whilemouse** [grommet/grommet#4314]
### Expected Behavior
I want remove box-shadow when selected tab.

### Actual Behavior
box-shadow does not disappear when tab is selected.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/16111790/87612759-65561580-c746-11ea-8e4e-b3864c28086f.png)
- .bIwdDF has box-shadow

![image](https://user-images.githubusercontent.com/16111790/87612802-80c12080-c746-11ea-8b91-30f47ab44c98.png)
- theme extend can control .cvgKwZ

I think theme extend can't control box-shadow.

https://codesandbox.io/s/grommet-v2-template-5sm9y?file=/index.js

### Steps to Reproduce

1. Select tab
2. this shown box-shadow on selected tab.

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: chrome 83
- Operating System and version (desktop or mobile): desktop

**Comment by IanKBovard** [comment]
@whilemouse are you talking about the green border around the tab?

**Comment by whilemouse** [comment]
> @whilemouse are you talking about the green border around the tab? or do you want to add a shadow and remove it when its active?

Green border is box-shadow. I want remove green border.

**Comment by IanKBovard** [comment]
My understanding is that the green border is there for accessibility purposes. It shows an element has focus.

**Comment by whilemouse** [comment]
> My understanding is that the green border is there for accessibility purposes. It shows an element has focus.

Sorry. I can't understand your words. How does your words relate to removing the green border.

**Comment by ShimiSun** [comment]
Focus is important for accessibility reasons, grommet is supporting WCAG 2.1 standards so we provide the out of the box focus. If you want to learn more about focus, accessibility and what it means here is a nice read https://usability.yale.edu/web-accessibility/articles/focus-keyboard-operability.

If we want to remove the focus form all of your applications you can use the theme to set it, (although it is not the best practice approach), or you can also control the color. Here are couple of examples:
https://storybook.grommet.io/?path=/story/theme--themecontext-extend
https://storybook.grommet.io/?path=/story/theme--focus

**Comment by whilemouse** [comment]
> Focus is important for accessibility reasons, grommet is supporting WCAG 2.1 standards so we provide the out of the box focus. If you want to learn more about focus, accessibility and what it means here is a nice read https://usability.yale.edu/web-accessibility/articles/focus-keyboard-operability.
> 
> If we want to remove the focus form all of your applications you can use the theme to set it, (although it is not the best practice approach), or you can also control the color. Here are couple of examples:
> https://storybook.grommet.io/?path=/story/theme--themecontext-extend
> https://storybook.grommet.io/?path=/story/theme--focus

I solved it thanks to your answer. :)
