### ISSUE TITLE
DateInput is missing in version 2.14.0

### ISSUE THREAD

**Issue by jbyttow** [grommet/grommet#4330]
It looks like DateInput is not included in the source and so is not available.

### Expected Behavior

I'd expect this to be available. Is this something being addressed

### Steps to Reproduce

download 2.14 and attempt to import DateInput

- Grommet version: 2.14.0

**Comment by ShimiSun** [comment]
Hi, thanks for your interest in DateInput, DateInput is still under exploration and wasn't released officially yet (same for Card).
You can still find the component on the[ stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F until we'll officially release.
Both the stable branch and storybook are up to date with the master branch, we appreciate the feedback from the community on new components before officially releasing them, so feel free to let us know how it goes.
The website documentation is updated on a separate repo, and we try not to publish the documentation of none-finalized items, so the docs will be updated closer to the official release with the finalized content. (If you would still like to access to documentation of components that are not officially released yet but are available on the stable branch, go to its doc.js file and read its docs.)
