### ISSUE TITLE
Shrink width of Heading level 6 causes it to jump up in size

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#4332]
See https://grommet.slack.com/archives/C09QQEG69/p1595361593434100?thread_ts=1595361593.434100&cid=C09QQEG69

For h6 elements, shrinking page width should not cause the font size to increase.

Thanks to Taylor Seamans for this explanation... (paraphrased)

...this is likely a boundary condition.  As the pages shrinks and crosses breakpoints, the theme's heading sizes are reduced.  Since "6" is the smallest, it can't go any smaller and I noted finds some defa t size.

### Actual Behavior

Shrinking page width causes font size to increase.

### Steps to Reproduce

Start with component `<Heading level="6">Hello Grommet</Heading>`.  Now shrink the page below the breakpoint of 768 and the font size increases.

### Your Environment

- Grommet version: 2.14
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows

**Comment by ShimiSun** [comment]
Feel free to fill in the issue template for future issues, to drive more conversations and interactions with github users that aren't using slack.

![image](https://user-images.githubusercontent.com/6320236/88227975-b032ca00-cc2b-11ea-9184-9530f034a50b.png)

**Comment by IanKBovard** [comment]
I could be wrong, but it looks like this might be intended behavior. This function handles the size.
`const responsiveData = headingTheme.level[Math.min(props.level + 1, 4)][size];`

![Screen Shot 2020-08-10 at 2 06 07 PM](https://user-images.githubusercontent.com/21990914/89820540-cb01ab80-db12-11ea-91e1-6ec554b0144a.png)

The level here is the passed in heading level
the number is what is calculated by Math.min
and medium is the default font size.

My question would be to @ShimiSun or @ericsoderberghp, is this intended behavior? It looks like any heading size lower than 4 will default to 4 when resizing.

**Comment by ericsoderberghp** [comment]
It looks like we are trying to handle the small responsive scenario by shrinking the font size by one heading level but not shrinking below 4. So 1 -> 2, 2 -> 3, 3 -> 4, 4 -> 4, 5 -> 4, 6 -> 4. It feels like it was intended, but I can't remember :( . I agree that this doesn't seem right for larger heading levels. I wonder if we should change the hard coded `4` to be something like `Math.max(...Object.keys(theme.heading.level))`?

**Comment by ShimiSun** [comment]
> It feels like it was intended, but I can't remember :( . I agree that this doesn't seem right for larger heading levels.

I think it was there before we actually supported the levels of 5 & 6.

>I wonder if we should change the hard coded 4 to be something like Math.max(...Object.keys(theme.heading.level))

I agree that will be the right approach to handle it.
