### ISSUE TITLE
DateInput: Add fields to drop

### ISSUE THREAD

**Issue by P4R4DiSi4C** [grommet/grommet#4333]
Hi,

I'm testing the stable branch which reflects the current master to have the DateInput component.
Would it be possible to get a way to add fields to the dropdown ?

I'm looking to do the exact same thing as this example but with the new DateInput component:
[https://storybook.grommet.io/?path=/story/maskedinput--date-time-drop](https://storybook.grommet.io/?path=/story/maskedinput--date-time-drop)

My goal is to:

- Have the calendar
- + 2 fields below it as start time and end time.

Regards

**Comment by P4R4DiSi4C** [comment]
![image](https://user-images.githubusercontent.com/17826095/88162359-89679a00-cc11-11ea-9b8f-b12e102ff466.png)

Something like this. I used the MaskedInput DateTime exemple from StoryBook

**Comment by ShimiSun** [comment]
Thank you for your feedback and for using the stable branch to try the component out!
I took a look at how your example could be achieved with the current DateInput implementation, and we might need to enhance the component to welcome `children` prop, the trick will be to know where to place `children` relative to the Calendar component (top/ bottom/ left/right..)

**Comment by jcfilben** [comment]
For now we are leaning towards keeping the DateInput simple and not adding the option to have additional fields within the drop. I think if we do want to go this route there would be a good amount of work determining design and accessibility. I'm going to close this for now, but feel free to re-open or comment if interested in continuing the discussion on this.
