### ISSUE TITLE
Select does not display the selected value

### ISSUE THREAD

**Issue by antonio-lm-jr** [grommet/grommet#4335]
I updated my packages today and noticed that my selects are not showing the selected value. I am using the `valueKey` and `labelKey` properties as shown in the examples, but to no avail.

I performed some tests and the problem occurs from the version v2.13.0.

### Expected Behavior

Display the selected value

### Actual Behavior

Not applicable

### URL, screen shot, or Codepen exhibiting the issue

Here's a Codesandbox template that serves as a nice starting point for demonstrating an issue:
https://codesandbox.io/s/jovial-rgb-eszoe?file=/src/App.js

### Steps to Reproduce

Not applicable

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Versão 84.0.4147.89 (Versão oficial) 64 bits
- Operating System and version (desktop or mobile): Windows 10

**Comment by IanKBovard** [comment]
You have to make sure your value resembles your options object.
here is your error:
`state = { value: "2", options: OPTIONS };`
it should be:
`state = { value: { id: "1", name: "Option 1" }, options: OPTIONS };`

working codesandbox:
https://codesandbox.io/s/serene-burnell-7hzli?file=/src/App.js:249-316

**Comment by antonio-lm-jr** [comment]
The way I implemented it works in versions prior to v2.13.0. So, I opened the issue.

Making the change you propose is a little difficult for me. For now I will stay on version v2.12.0.

**Comment by IanKBovard** [comment]
if that is too much you can just do `  state = { value: { id: "2" }, options: OPTIONS };`

**Comment by ericsoderberghp** [comment]
Whether the value is an object or is a property of an object is controlled by `valueKey={{ reduce: true }}`. https://v2.grommet.io/select#valueKey
If I change the code sandbox to have `valueKey={{  key: "id", reduce: true }}`. I believe it works as is expected.
We added this `reduce` sub-property to disambiguate which way the value should be interpreted.

**Comment by antonio-lm-jr** [comment]
Nice @ericsoderberghp . Add `reduce=true` on `valueKey` property is the least impactful for my project.

Thank you very much!
