### ISSUE TITLE
InfiniteScroll stops intermittently

### ISSUE THREAD

**Issue by nnbrandon** [grommet/grommet#4337]
### Expected Behavior
Should be able to keep scrolling through an infinite scroll list.

### Actual Behavior
The content or page does not show on the rendered application and unable to scroll through the infinite scroll list anymore. 

This seems to be related to https://github.com/grommet/grommet/issues/3106

### URL, screen shot, or Codepen exhibiting the issue
Here is a code sandbox that shows the issue: https://codesandbox.io/s/green-water-n7e21?file=/src/App.js:1025-1046

### Steps to Reproduce
Keep trying to scroll down until you are unable to. 
On a Macbook 13 inch, I am unable to scroll past index 159.
The maximum index to be reached at is 999.

- Grommet version: 2.14.0
- Browser Name and version: Chrome

**Comment by nnbrandon** [comment]
@IanKBovard if you have any questions, feel free to reach out to me on skype or here

**Comment by ShimiSun** [comment]
Hi @nnbrandon, this issue had been a great challenge for the team, thank you all who have contributed to this effort @IanKBovard @halocline &  @ericsoderberghp 💟 
The fix is now available on our [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F), feel free to give it a try and let us what you think.

**Comment by nnbrandon** [comment]
> Hi @nnbrandon, this issue had been a great challenge for the team, thank you all who have contributed to this effort @IanKBovard @halocline & @ericsoderberghp 💟
> The fix is now available on our [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F), feel free to give it a try and let us what you think.

Wow this is great to hear! Thank you to the Grommet team for fixing this issue. This will resolve the issue that we have been facing on our product and will be happy to adopt it. 👍
