### ISSUE TITLE
Cannot assign to read only property 'target' of object '#<MouseEvent>'

### ISSUE THREAD

**Issue by AlexBHarley** [grommet/grommet#4340]
Using the `Select` component with Preact fails with `Cannot assign to read only property 'target' of object '#<MouseEvent>'
 `.

I'd very much like to use Preact in my project but this is blocking me.

### Expected Behavior

`Select` component should work as it does with React.

### Actual Behavior

Crashes with `Cannot assign to read only property 'target' of object '#<MouseEvent>'`.

### URL, screen shot, or Codepen exhibiting the issue

![Screen Shot 2020-07-25 at 16 18 31](https://user-images.githubusercontent.com/11168524/88459055-8af3c500-ce92-11ea-9893-f5fb30cb9ab7.png)

### Steps to Reproduce

1. Scaffold a create-react-app project and add grommet
2. Create a basic select component
3. Add a `config-overrides.js` file 

```
module.exports = function override(config, env) {
  config.resolve.alias['react'] = 'preact/compat';
  config.resolve.alias['react-dom'] = 'preact/compat';
  config.resolve.alias['create-react-class'] =
    'preact/compat/lib/create-react-class';
  config.resolve.alias['react-dom-factories'] =
    'preact/compat/lib/react-dom-factories';

  return config;
};
```
4. Use `react-app-rewired start` to start app

### Your Environment

- Grommet version: stable
- Browser Name and version: Chrome 84.0.4147.89
- Operating System and version (desktop or mobile): MacOS 10.13.2 (Desktop)

**Comment by ShimiSun** [comment]
Thanks for reporting! we'll be happy to receive a contribution from the community for this issue.
