### ISSUE TITLE
Accessibility error in Grommet data table search box cell

### ISSUE THREAD

**Issue by Krishnasuma** [grommet/grommet#4347]
Hi,

I was trying to update some accessibility errors in one of our projects but I am not able to correct it for the data-table component search cell in the header. Please find below the details of that.

After clicking the search icon in the header of the DataTable component from the grommet, if run wave tool we can see an error in that search input box. Here is the attached screenshot.

Here is my code sandbox link https://codesandbox.io/s/grommet-v2-template-j8u1x?file=/index.js

![image](https://user-images.githubusercontent.com/17309263/88653924-51b59200-d0ea-11ea-851d-03f726dcd27e.png)

- Grommet version: v2

**Comment by ShimiSun** [comment]
Can you please share what is the error?

**Comment by Krishnasuma** [comment]
@ShimiSun the error is "Missing Form label". You can check error here https://codesandbox.io/s/grommet-v2-template-j8u1x?file=/index.js by running wave tool for this example.

![image](https://user-images.githubusercontent.com/17309263/88907613-75a5de80-d276-11ea-80de-096724295cc1.png)

**Comment by jcfilben** [comment]
The codesandbox is using grommet version 2.12 does upgrading to the latest version (2.15) solve the problem?

**Comment by ShimiSun** [comment]
I think upgrading too 2.15 should solve the problem. please give it a try and let us know.

**Comment by Krishnasuma** [comment]
@ShimiSun and @jcfilben I see the same issue even after updating to 2.15.

**Comment by ShimiSun** [comment]
The issue is fixed on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) and will be officially released on the later version of 2.15.2.

**Comment by Krishnasuma** [comment]
@ShimiSun Still I'm able to see the issue even after updating to 2.15.2. Here is the Codepen link https://codesandbox.io/s/grommet-v2-template-forked-2d1qo?file=/package.json
