### ISSUE TITLE
Drop component to have an option of showing caret to target

### ISSUE THREAD

**Issue by maryjufang** [grommet/grommet#4349]
Drop component to have an option of showing caret to target

### Expected Behavior

![image](https://user-images.githubusercontent.com/9951106/88703011-2aef5f80-d0da-11ea-9187-dd88839da813.png)

### Actual Behavior

No caret option

**Comment by ShimiSun** [comment]
This issue is fixed as part of the Tip component.https://storybook.grommet.io/?path=/story/controls-tip-caret--caret
