### ISSUE TITLE
DateInput Range crashes after click same date three times 

### ISSUE THREAD

**Issue by maryjufang** [grommet/grommet#4351]
DateInput Range crashes after click same date three times 

### Expected Behavior

same date selected as range

**Comment by ShimiSun** [comment]
https://storybook.grommet.io/?path=/story/dateinput--range

**Comment by ShimiSun** [comment]
This issue is fixed on the [stable branch ](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F), and will be available on our next release.
