### ISSUE TITLE
DateInput - Calendar not to show 6th row if all in next month

### ISSUE THREAD

**Issue by maryjufang** [grommet/grommet#4353]
Calendar not to show 6th row if all in next month

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/9951106/88704118-a69ddc00-d0db-11ea-84bc-9b41a37ee102.png)

**Comment by ShimiSun** [comment]
The example is taken from DateInput https://storybook.grommet.io/?path=/story/dateinput--range

**Comment by halocline** [comment]
@ShimiSun Confirming we want to treat this as a feature enhancement, correct?

**Comment by ShimiSun** [comment]
Yea, otherwise it might be considered as a breaking change.

**Comment by halocline** [comment]
Looking into the work here, relates to "showAdjacentDays" functionality, I am noticing a few buggy behaviors which should be addressed. Documenting them here, then can broken out into separate issues if needed:
- Navigating to previous months, then forward does not advance the calendar dates and also results in incorrect styling of the "adjacent days"
- Navigating to previous months, then forward eventually results in the calendar dates getting "stuck" and not advancing
- Navigating forward a single month increments correctly, displaying the 1st of the month in the first row. Navigating forward an additional month adds a week from the previous month to the first row and does not advance the calendar. The calendar gets "stuck" here. Additional forward navigation ends up adding and removing a week from the view, but does not advance the calendar (always displaying the last week of the original month).

Steps to reproduce to be added to this comment.

**Comment by ShimiSun** [comment]
@jcfilben check out the above analysis for testing effort.

**Comment by halocline** [comment]
**Update**. Have proposed solution which would prevent the 6th row from displaying if all dates in next month. Need to add tests + question re: API.

@ShimiSun What are your thoughts of this being viewed as a bug vs. an enhancement? If enhancement, for backwards compatibility, I think we need to expose a new property. If viewed as bug, then we can implement without a new prop.
