### ISSUE TITLE
Calendar: provide an interface not to show in date range in adjacent days

### ISSUE THREAD

**Issue by maryjufang** [grommet/grommet#4354]
Calendar: provide an interface not to show in date range in adjacent days

### Expected Behavior
Some times, user may want to skip highlighting date range in adjacent days

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/9951106/88704377-fbd9ed80-d0db-11ea-906a-ea26633071dc.png)

**Comment by taysea** [comment]
Hey @maryjufang, could you provide a little more detail here about what you're trying to achieve and where things aren't going as expected? I'm not fully understanding what you mean by "user may want to skip highlighting date range in adjacent days"

**Comment by ShimiSun** [comment]
@maryjufang please provide more information on this issue, so we can start to discuss a resolution.

**Comment by ShimiSun** [comment]
I'll be closing the issue, feel free to reopen and add the requested details to help navigate for a solution.
