### ISSUE TITLE
SkipLink example broken in docs site

### ISSUE THREAD

**Issue by RyanCCollins** [grommet/grommet#4360]
### Expected Behavior
When using the examples given on the grommet docs site, I'd expect the skiplink to be working.

### Actual Behavior
The skiplinks don't work in the examples on the grommet site

### URL, screen shot, or Codepen exhibiting the issue
https://v2.grommet.io/skiplinks

### Steps to Reproduce
Try any of the skip link examples on the grommet site.

### Your Environment

- Grommet version: any since v2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Mac OSX

**Comment by ShimiSun** [comment]
For now, we are providing a SkipLinks example on codesandbox  https://069bi.csb.app/skiplink#C5
Let me know if this is aligned with what you had in mind, and where it needs refinement.

**Comment by ShimiSun** [comment]
Some insights while taking a look at the grommet-site [SkipLinks](https://v2.grommet.io/skiplinks) component:
1. The SkipLinks window with the _Main Content_ does show after navigating to the end of the page - we should consider changing tabIndex so it will be displayed at the beginning.
2. When the window opens, we should allow a way to navigate out of it without selecting an option.
![image](https://user-images.githubusercontent.com/6320236/88968535-b39e0500-d26c-11ea-9193-41a5f7aaed50.png)

**Comment by RyanCCollins** [comment]
Hey @ShimiSun thanks for looking into this! I do see what you mean.  Is there an example of how to use the skiplinks?  I did try to add them to GLC and it crashes the page.  I think perhaps I'm using them incorrectly.

**Comment by ShimiSun** [comment]
@RyanCCollins good feedback. Let me take another look and get back to you on that.
