### ISSUE TITLE
MaskedInput options messes up logic of regex

### ISSUE THREAD

**Issue by seanmehra** [grommet/grommet#4366]
Has anyone else experienced a bug where the MaskedInput 's options doesn't work well?
Here's my mask prop:
{
        length: [1, 2],
        placeholder: 'number of minutes',
        options: ['5', '10', '15'],
        regexp: /^[1-9][\d]?$/
}
I can type any number except the numbers 50 through 59. Any idea why?

**INITIAL THOUGHT:**

"i think its because 5 is satisfying your option exactly.  it might be a bug but one idea is to change your option to `5 ` (5 plus space) and then trim the value on your state...."

https://codesandbox.io/s/grommet-buttons-ispuj?file=/index.js

typically in the examples the options correspond exactly to the regex allowed values...in your case you're just putting a subset... so if the idea is for the component to allow that behavior then i would say its prob a bug. if its not intended to allow that behavior then the docs should prob reflect that

**SLACK THREAD**
https://grommet.slack.com/archives/C04LMHN59/p1596084780023400

**Comment by moodele** [comment]
Yes this bug still exist

**Comment by IanKBovard** [comment]
@seanmehra could you clarify the issue for me? You can't enter any number in the input besides 50-59?

![Kapture 2020-09-09 at 12 18 06](https://user-images.githubusercontent.com/21990914/92631157-952d1f80-f296-11ea-9c49-9dd5ee8bea63.gif)

**Comment by seanmehra** [comment]
Hi @IanKBovard , you are correct. With my code above, I cannot type any numbers other than 50-59.  This fixed it, but it's a hack:

https://codesandbox.io/s/grommet-buttons-ispuj?file=/index.js

**Comment by IanKBovard** [comment]
Have you tried making you options an integer instead?

https://codesandbox.io/s/grommet-buttons-forked-5i1vc?file=/index.js

**Comment by ShimiSun** [comment]
Any updates @seanmehra? Have you tried @IanKBovard idea?

**Comment by IanKBovard** [comment]
@seanmehra just checking in to see what your thoughts are on this issue

**Comment by seanmehra** [comment]
Sorry for the delay @IanKBovard @ShimiSun, this perfectly resolves the issue. Wonder if this should make it into the documentation somewhere as a tip or warning. Thanks for the help! It's a more "correct" solution than trimming whitespace from a string.

**Comment by ShimiSun** [comment]
@IanKBovard Can you please get it documented on the docs?

**Comment by IanKBovard** [comment]
Before I do that I'd like to know if this is how we expect the regex to work.
https://codesandbox.io/s/grommet-buttons-forked-5i1vc?file=/index.js

Any single digit option will halt any more inputs when the options are strings. When the options are integers the im allowed two inputs. Is this expected?
