### ISSUE TITLE
Heading responsive behaviour is not documented

### ISSUE THREAD

**Issue by jjalonso** [grommet/grommet#4373]
The way that the heading resize on differents breakpoints is a great mystery for lots of us, 
I could not find explanation on the doc, i think it need some explanation about how to use it and how to disable it.

**Comment by taysea** [comment]
@jjalonso I've filed [this PR](https://github.com/grommet/grommet/pull/4413) to address this. Can you let me know if the wording is clear/would have helped you understand the behavior?
