### ISSUE TITLE
TextArea prevents onEsc event if used in Layer

### ISSUE THREAD

**Issue by srallen** [grommet/grommet#4377]
### Expected Behavior

I would expect that onEsc closes the Layer

### Actual Behavior
onEsc is prevented when focused on the TextArea in the Layer. 

### Steps to Reproduce

This can be observed in the Grommet story for a form rendered in a Layer: https://storybook.grommet.io/?path=/story/layer--form

The third input is a TextArea and if you are focused on it, then onEsc does nothing. If you are focused on the other inputs, then onEsc functions as expected and closes the Layer.

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Chrome 84
- Operating System and version (desktop or mobile): MacOS 10.15.4

**Comment by ShimiSun** [comment]
Why do you think this is a Layer related issue and not just an issue with TextArea?

**Comment by srallen** [comment]
@ShimiSun I made this sandbox to demonstrate that it's an issue inside `Layer`: https://codesandbox.io/s/grommet-v2-template-2458f?file=/index.js

You'll see that if you open the Layer, then focus the `TextInput` and hit esc, my custom `onKeyDown` handler fires, then `onEsc` for the Layer will fire and close the `Layer`, if you do the same when  focused on the `TextArea`, `onEsc` for the `Layer does not run. There's also a `TextArea` outside of the `Layer` which you can focus and hit esc on and see my handler run as expected.

**Comment by IanKBovard** [comment]
This was intentional, a code snippet from the TextArea component.

```
<Keyboard
  onEsc={event => {
    // we have to stop both synthetic events and native events
    // drop and layer should not close by pressing esc on this input
    event.stopPropagation();
    event.nativeEvent.stopImmediatePropagation();
  }}
  onKeyDown={onKeyDown}
>

```

**Comment by srallen** [comment]
Any reasoning for this intention? If so, I think this should at least be configurable. Right now this behavior is confusing and unpredictable for our keyboard users.

**Comment by IanKBovard** [comment]
I'm not sure as to the reasoning. I don't see any difficulty in removing this functionality, or adding a prop. I would like to know what @ShimiSun and @ericsoderberghp would think to be the best solution.

**Comment by ShimiSun** [comment]
@IanKBovard can you check to which commit/PR/issue this comment is related to, it might provide better context on the approach.

**Comment by IanKBovard** [comment]
Looks like it was added with this pr to improve accessibility.
https://github.com/grommet/grommet/pull/2467

**Comment by ShimiSun** [comment]
I'll be closing this since its desired functionality. Feel free to file a new issue if needed but please consider applying any behavioral changes may be perceived as a breaking change.
