### ISSUE TITLE
Add `rel` prop to Anchor

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#4379]
When you link to an external site and open the link in a new tab it creates a security issue unless you include `rel='noopener'` or `rel='noreferrer'`. 

https://medium.com/sedeo/how-to-fix-target-blank-a-security-and-performance-issue-in-web-pages-2118eba1ce2f

Linking to an external site can be done using: 
```
<Anchor
  label="Grommet"
  href="https://v2.grommet.io/"
  target="_blank"
/>
```
but this behavior is unsafe. For this to be secure the `rel='noopener'` or `rel='noreferrer'` prop should be added. Like this:
```
<Anchor
  label="Grommet"
  href="https://v2.grommet.io/"
  target="_blank"
  rel='noreferrer'
/>
```

Maybe the `rel` prop should be added to Anchor and in the grommet documentation for Anchor there should be information included about `rel` and its suggested use. Currently the code above works but the `rel` prop isn't officially included in the Anchor component or the documentation.

**Comment by ShimiSun** [comment]
Any idea how we can anticipate whether the `href` will be internal or external to the user’s site? applying a default value will require us to make this assumption.

**Comment by IanKBovard** [comment]
I'm not too sure about this. We can already add rel="noopener noreferrer" to any anchor or button that links externally without the help of grommet. Personally, I think it's possible for grommet to do too much.

**Comment by ShimiSun** [comment]
@IanKBovard I agree, and I'll be closing the issue.
