### ISSUE TITLE
Button Alignment differs with icon as child vs property

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#4380]
### Expected Behavior

Expected that the alignment of a Button would be the same if the icon is a property or a child.

### Actual Behavior

Alignment differs.  This makes it difficult to align Buttons from different components that define the icon differently.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/button-and-icon-alignment-orfyy?file=/src/App.js

![image](https://user-images.githubusercontent.com/8231064/89477086-ae423c80-d7cf-11ea-895f-63d7780b35f9.png)

### Steps to Reproduce

See codeSandbox.

### Your Environment

- Grommet version: 2.14
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10

**Comment by ShimiSun** [comment]
@britt6612 is this the issue you already fixed today?

**Comment by britt6612** [comment]
<img width="1187" alt="Screen Shot 2020-08-06 at 12 49 30 AM" src="https://user-images.githubusercontent.com/42451602/89500273-b32ad000-d77e-11ea-8876-6c556cd45682.png">

Yes this is a screen shot of the code with my fix so it should be good now on stable! 😄

**Comment by ShimiSun** [comment]
Perfect @britt6612 , thank you!
@LiveFreeAndRoam, @britt6612 solve the problem before you even filed it, Now, that's what I call a first-class service!!

**Comment by LiveFreeAndRoam** [comment]
That is fantastic!  Nice work and thank you for the quick turn around.

Another question; in the image showing the fix, you can see the Stacked icon is not aligned with the Notification icon.  I would expect they should also be aligned, should they not?

**Comment by ShimiSun** [comment]
>Another question; in the image showing the fix, you can see the Stacked icon is not aligned with the Notification icon. I would expect they should also be aligned, should they not?

Is that part of #4372 ? It's a separate issue.
