### ISSUE TITLE
Unintentional removal of DOM elements

### ISSUE THREAD

**Issue by cliffpyles** [grommet/grommet#4384]
Grommet removes DOM elements that were built by external libraries (and live outside of the application).

### Expected Behavior

Grommet doesn't remove DOM elements that are unrelated to the application and the design system.

### Actual Behavior

In the AnnounceContext component, `document.body.querySelector('[aria-live]')` is used to target elements, but because of the broadness of the selector it also targets elements it doesn't intend to target. A few lines later it replaces the innerHTML of the wrong element with content (or a blank string).

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-rl60j

### Steps to Reproduce

1. Go to https://codesandbox.io/s/grommet-v2-template-rl60j
2. Make note of the text at the bottom.
3. Start typing something in the TextInput. The content is replaced with one of the suggestions or an empty string.

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Saw the issue on Chrome and Firefox. Haven't checked others.
- Operating System and version (desktop or mobile): MacOS Catalina (10.15.6)

**Comment by ShimiSun** [comment]
Thanks for reporting.
