### ISSUE TITLE
Storybook/Chromatic clean-ups

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#4385]
1. Clean up the console warning:
![image](https://user-images.githubusercontent.com/6320236/89604045-ae6e2680-d827-11ea-8f4d-75709bc21612.png)

1. Disable all Chromatic testing for DropButton component.

1. Disable Chromatic on DateInput -> Range and Simple stories. 

1. Remove Chromatic from all these 4 stories of Layer 
![image](https://user-images.githubusercontent.com/6320236/89604593-d27e3780-d828-11ea-9eab-1df36540fc9c.png)

1. Add Carousel story example for the use case of #3850.

1. Add the Grommet Tools Header to Storybook Header component.

**Comment by ShimiSun** [comment]
More relevant content https://www.chromatic.com/docs/ischromatic

**Comment by jcfilben** [comment]
The chromatic snapshots for
Menu: reverse, simple, and themed
seem like they could be removed. Also not sure if we need chromatic testing on the Collapsible stories.

**Comment by ShimiSun** [comment]
Example code for Layer-> Form, should use Form and not just FomFields inside of Box.https://storybook.grommet.io/?path=/story/layer--form

**Comment by ShimiSun** [comment]
Can we also exclude Chart -> Scan & Zoom stories from Chormatic.

**Comment by jcfilben** [comment]
Removed: 19 chromatic snapshots
Added: 2 new stories added to carousel and header

Total difference is chromatic snapshots: -17

**Comment by ShimiSun** [comment]
Fantastic work team, I'll be closing this issue!!
