### ISSUE TITLE
Multiple buttons can have focus at a time

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet#4389]
![image](https://user-images.githubusercontent.com/3485567/89692519-cba30380-d8c0-11ea-8131-c5d8ce5573f5.png)

The first button disables itself
The second button enables the first.

1) Click the first
2) Click the second
3) Notice both are active and focused.

https://codesandbox.io/s/youthful-cartwright-hj28u?initialpath=/text&module=%2Fsrc%2FText.js

**Comment by ShimiSun** [comment]
Thank you for reproducing and filing the issue.
To understand the use case better, after clicking an icon, you expect the Button to be disabled and the focus shadow to be removed? when will the focus be shown if the Button is becoming disabled?

**Comment by RobertGary1** [comment]
I would think once it becomes disabled it would lose focus but at least once something else gains focus.Right now it seems to get stuck so it always holds focus, even when its re-enabled.

**Comment by ShimiSun** [comment]
Thanks for clarifying, I agree it should lose the focus once disabled, so the root cause of the issue will be on how the disabled styled is handled rather than the focus itself.

**Comment by ericsoderberghp** [comment]
I suspect that part of the issue could be relying on the internal `focus` state to drive style instead of `&:focus {}` in the styling.

**Comment by taysea** [comment]
I think your intuition is correct, Eric. I am looking at this locally and updated the focus to be driven by &:focus {} and it is removing this error. I am going to do some more explanation, then I will work on putting together a PR.
