### ISSUE TITLE
Button focus style gets "stuck" when disabled while focused

### ISSUE THREAD

**Issue by MLRichmond** [grommet/grommet#4393]
As the title says, Buttons have an issue when they are disabled while focused that causes them to retain the focus styling.

### Expected Behavior

The focus styling should either clear when the button is disabled, or at least when another element subsequently takes focus.

### Actual Behavior

The focus styling remains stuck on the button even after a new element takes focus.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/pensive-shirley-ebrt9?file=/src/Home.js

### Steps to Reproduce

See Code sandbox. Click a button, wait for the buttons to disable and re-enable. Click other button.

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by ShimiSun** [comment]
Is this issue a duplication of the issue in #4389 ?

**Comment by MLRichmond** [comment]
Looks like. It looks like Eric has already identified the root cause in that item. Apologies for the duplication - I opened this as a result of a slack thread. I didn't realize someone else opened it as well.

**Comment by ShimiSun** [comment]
@MLRichmond no worries, thank you for reporting.
