### ISSUE TITLE
Error while displaying nested JSON Object DATA in DataTable

### ISSUE THREAD

**Issue by parth611git** [grommet/grommet#4394]
I have used DataTable to display JSON data.
I have defined columns and DATA are fetched using API.
Each row in API response, is nested JavaScript Object
I am facing issue issue in displaying data from nested JavaScript Object.

```
column= [
{property: "empName", header:"Employee Name"},
{property: "designation", header:"Designation"}];

data = [
{"empName": "EMP001", "designation": {"designationId" : "1", "designationName" :"Software Engineer"},
{"empName": "EMP002", "designation": {"designationId" : "2", "designationName" :"Project Manager"}]
```
How can I display "desginationName" which is nested under "designation"?

### Expected Behavior
I have tried by make column property as designation.designationName and it is working fine.
It must make property as designation.
In such allow user to render data using render prop like,
```
render : (datum) => (<Text value={datum.designation.designationName} />      
      ),
```

### Actual Behavior

DataTable must make property value as designation but not as designation.designationName
I have tried with rendering designationName using render prop, but is giving me below error:

`Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates`

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Chrome Version 84.0.4147.105 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10

**Comment by ericsoderberghp** [comment]
I am unable to reproduce this using:
https://v2.grommet.io/datatable?c=DwEQhgLmAqYEYBsCmAoABGgxgewQVwFsA7AZwF4BvAbXQzQtrrQAcAnbZpViATwC40AciJgCSQQBpGdABZIwAEy4Dg0JAA8IAPgByopMAD0azVqlMMbAJYEwrfmgis8Sc3QC+bjAwst2nbgdBMAA6OElpDDlFZSEAIQimT1oAXXdaBUgwShomCjQRMQFBAEEEMCJJNDABfLgBACYABjR3Vq96Av1iuPsKqprO+rQAZlb21PTDLSA

Have you tried this?:
```
{ property: "designation.desginationName", header: "Designation" }
```

**Comment by IanKBovard** [comment]
I believe this is because datatable uses property to create the key. Since your property is an object the key for each row will be [object, object] causing duplicate keys. I agree with @ericsoderberghp, that change to the property should address the issue.

**Comment by parth611git** [comment]
@ericsoderberghp  @IanKBovard 
Thank you Folks for your response.
I tried with designation.designationName and it was working fine as I have said in my initial question.

> I have tried by make column property as designation.designationName and it is working fine. 

Is there any scope to make property as "designationName" and display proper designation value in DataTable.

Or 

Is there any way to change key value for each row, for said example?

**Comment by parth611git** [comment]
Is there any that I keep property as "designation" and use render prop to display proper "designationName" value.
I have tried with below code, but it didn't work.
`render : (datum) => (<Text value={datum.designation.designationName} /> )`

**Comment by IanKBovard** [comment]
@parth611git just trying to understand the issue. Is there any reason why you absolutely need property to be designationName?

**Comment by parth611git** [comment]
@IanKBovard 
I can have designationName available in DataTable by setting property as
`property : designation.designationName`
It works perfect, no issue in it.

My issue is can it be possible to have property as "designation" and using render attribute display "designationName"
I have tried with below code, but it didn't work.
`render : (datum) => (<Text value={datum.designation.designationName} /> )`

**Comment by halocline** [comment]
@parth611git I believe this accomplishes what you are attempting: https://codesandbox.io/s/sparkling-cdn-xcisc?file=/src/App.js

A couple points to note:
- `<Text value={datum.designation.designationName} />` should be `<Text>{datum.designation.designationName}</Text>`
- For your second column, you may specify `designation` as your property, but you still must reference the object property beginning with `datum` --> `datum.designation.designationName` or `datum.designation.designationId`

**Comment by parth611git** [comment]
@halocline 
Yes Issue is I am using wrong prop "value" inside Text. Thanks for catching it.
Things are working fine after your feedback.
You can close this issue.

**Comment by parth611git** [comment]
For more information, I have added checkbox against each row using 
https://storybook.grommet.io/?path=/story/datatable--controlled

https://codesandbox.io/s/romantic-kepler-z97dn?file=/src/App.js

Somehow console get cleared and I cannot see warning.

**Comment by IanKBovard** [comment]
@parth611git just checking in, i don't see the error in halocline's example. Would you mind showing me a codesandbox with your error?

**Comment by parth611git** [comment]
Thank you, @IanKBovard 
I did not face warning right now.
I will try again with proper data to reproduce it.
So right now we can close this issue as it fulfill initial requirement of this issue.
