### ISSUE TITLE
Margin documentation misleading

### ISSUE THREAD

**Issue by holdenmad** [grommet/grommet#4407]
In the documentation, for example for <Box>, the margin properties are structured like this to explain how it should work:
```
"xsmall"
"small"
"medium"
"large"
"xlarge"
{
  "vertical": "...",
  "horizontal": "...",
  "top": "...",
  "bottom": "...",
  "left": "...",
  "right": "..."
}
```

This leads me to think that in a project, I could do this:
`<Box margin={"bottom": "small"}>Boxity Box</Box>`

Butin reality it should be like this:
`<Box margin={{bottom: "small"}}>Boxity Box</Box>`

I think the documentation should look more like this to avoid confusion:
```
"xsmall"
"small"
"medium"
"large"
"xlarge"
{{
  vertical: "size",
  horizontal: "size",
  top: "size",
  bottom: "size",
  left: "size",
  right: "size"
}}
```

**Comment by ShimiSun** [comment]
linking to #3887

**Comment by IanKBovard** [comment]
While I do agree that the quotes should be removed, I don't think wrapping the object in two curly brackets is a good idea. Passing any value through as props that isn't a string requires it to be wrapped in curly brackets already.

```
<Box props="boxprops" /> // no curly brackets required
```

```
<Box  props={props}/> // curly brackets wrap the variable
```

```
<Box  props={ {object: props} }/> // curly brackets wrap the object
```

Knowing default react behavior, documentation such as this {{ vertical: size }} looks like i have to pass in a nested object.

**Comment by ShimiSun** [comment]
@jcfilben can we please move this issue to the grommet-site repo?

**Comment by jcfilben** [comment]
Moved issue to grommet-site https://github.com/grommet/grommet-site/issues/181
