### ISSUE TITLE
RadioGroup and CheckBoxGroup don't update options when passing a mutated version of the same array 

### ISSUE THREAD

**Issue by phinch** [grommet/grommet#4415]
### Expected Behavior

When an updated version of `options` is passed into `RadioGroup` or `CheckBoxGroup`, the component should re-render with an updated set of options

### Actual Behavior

If the array of `options` passed into `RadioGroup` or `CheckBoxGroup` is a mutated version of the same array passed in on the previous render, then the component does not re-render. 

I don't want to over-diagnose, but I believe this is because of the `useMemo` optimization in these components ([like in RadioGroup here](https://github.com/grommet/grommet/blob/323cdbaddbea3563a0e3f88da4f81fe12e6a7840/src/js/components/RadioButtonGroup/RadioButtonGroup.js#L35)) that does not re-map options unless the `options` array has changed, and since the mutated version of the `options` array succeeds in a shallow compare with the previous render's `options` array, the `useMemo` hook doesn't rerun. As seen in the example below, forcing the options to spread into the component (thus creating a copy of the array rather than passing in the reference) causes the component to work as expected. 

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/small-lake-uyt2p

### Steps to Reproduce

We encountered this in our app because we were passing an array stored in Redux directly into the `RadioGroup` component, so the example attempts to emulate this scenario in a very simplistic way (where a mutating array is stored at a global level and is being passed through to the `RadioGroup` component). 

1. Click the button to add an option
2. Observe that the `console.log` statement on line 6 logs an updated set of options, but the component does not visually re-render.
3. If you change line 30 to spread the options into the component, i.e. `options={[...OPTIONS]}`, then the component works as expected.

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Chrome 84.0.4147.105
- Operating System and version (desktop or mobile): OSX Catalina 10.15.4

**Comment by IanKBovard** [comment]
Thanks for reporting. My guess is that you're right about the useMemo causing this issue.

Got a codesanbox here with base react showing your example working
https://codesandbox.io/s/youthful-meitner-qkkj7?file=/src/App.js:483-491

taking a deeper look at it now.

**Comment by ShimiSun** [comment]
@IanKBovard any updates on this?
