### ISSUE TITLE
Select box items not visible with classic background

### ISSUE THREAD

**Issue by ibhag** [grommet/grommet#442]
Hi,
Select box items are not visible as text color is white and background is also white. Please see under
http://www.grommet.io/docs/hpe/develop/form#Inverse item7 drop down. 
Also is it possible to replace the background image of drop down with Icon.
Thanks

**Comment by ericsoderberghp** [comment]
Can you provide more context on what browser you are using, and perhaps a screenshot? I am not seeing the problem when I look at it.

**Comment by ibhag** [comment]
I works fine in Firefox, but is reproducible on Chrome and IE.
PFA screen shot
![selectboxissue](https://cloud.githubusercontent.com/assets/17637919/13624325/f369fc2e-e5d2-11e5-9ace-33bf70809717.png)

**Comment by bryanjacquot** [comment]
@ibhag we aren't able to reproduce this any longer in Chrome.  Are you still seeing this?

**Comment by bryanjacquot** [comment]
I've confirmed this is still an issue with Edge v14 on Windows 10:

![image](https://cloud.githubusercontent.com/assets/6393696/18483805/ff1515c2-79a2-11e6-8d5f-44de372aed66.png)

**Comment by jwijay** [comment]
grommet-core PR pending: https://github.com/grommet/grommet/issues/442

**Comment by jwijay** [comment]
Issue resolved by PR #870
