### ISSUE TITLE
DataTable: Accessibility issue in column search box

### ISSUE THREAD

**Issue by SagarTrimukhe** [grommet/grommet#4421]
The search box width is not enough when the number columns are more. The user is not able to see what he/she is typing. 
Here is an example: https://codesandbox.io/s/grommet-v2-template-forked-qwfig?file=/index.js

### Expected Behavior
The column width should resize to make the search box wide enough.

### URL, screen shot, or Codepen exhibiting the issue
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/46806187/90361770-a9597480-e07c-11ea-84d6-af385f395e5b.gif)

### Steps to Reproduce

1. Click on the search icon
2. A search box will be opened. Type something but it doesn't show up anything which is typed.
3. The correct results will be shown, but the typed string is not visible. 

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Chrome:  84.0.4147.125
- Operating System and version (desktop or mobile): desktop

**Comment by ShimiSun** [comment]
Thank you to @StheffanyHadlich for fixing this issue!
