### ISSUE TITLE
DataTable with fixed header

### ISSUE THREAD

**Issue by SagarTrimukhe** [grommet/grommet#4431]
Datatable's header is not fixed to the top of the scrolling window.

### Expected Behavior
There should be an option to have a fixed header. This lets users quickly determine what each column refers to rather than needing to scroll back to the top of the table.

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Chrome  84.0.4147.125
- Operating System and version (desktop or mobile): Desktop

**Comment by halocline** [comment]
@SagarTrimukhe Would DataTable's `size` prop satisfy your needs? When provided, it defines the height of the table body and has a fixed header as the user scrolls.

https://v2.grommet.io/datatable?theme=hpe#size

**Comment by SagarTrimukhe** [comment]
> @SagarTrimukhe Would DataTable's `size` prop satisfy your needs? When provided, it defines the height of the table body and has a fixed header as the user scrolls.
> 
> https://v2.grommet.io/datatable?theme=hpe#size

Size prop is not taking pixel/viewport values. The table size needs to be dynamic based on the screen resolution. Also, the constant column width is problematic for our use cases.

**Comment by ShimiSun** [comment]
@SagarTrimukhe this enhancement was addressed on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F), feel free to give it a try and reopen the issue if needed. Here is a storybook example for reference https://storybook.grommet.io/?path=/story/datatable--fill-and-pin
