### ISSUE TITLE
DateInput not importing??

### ISSUE THREAD

**Issue by trumanpurnell** [grommet/grommet#4432]
The DateInput component is nowhere to be found

### Expected Behavior
`import {DateInput} from 'grommet'`
`console.log(DateInput)` // not undefined

### Actual Behavior
`console.log(DateInput)` // undefined

### URL, screen shot, or Codepen exhibiting the issue
Same thing happens on Codepen

### Steps to Reproduce
Easy as ^^^

### Your Environment
- Grommet version: latest
- Browser Name and version: chrome latest

**Comment by ShimiSun** [comment]
DateInput wasn’t officially released yet, we were still gathering feedback on the user experience and API and provided it on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) (not on the latest yet) so you can use it on the stable branch for now. It will be available on our next official release which will be sooner than later :)
