### ISSUE TITLE
Loader and Empty text in DataTable component

### ISSUE THREAD

**Issue by dileepthomas** [grommet/grommet#4433]
Do we have a prop for loading, so when data is fetching we can show a loader in the table body section.
Also if we pass the data as an empty array will it show a default text as "No Data"

For both above feature can we pass custom component and custom text. 

Didn't find any doc related to this.

- Grommet version: Latest

**Comment by ShimiSun** [comment]
Hi buddy, check out the Loaders and spinners template, and see if that helps. https://codesandbox.io/s/loaders-and-spinners-4jltk 
Keep us posted
