### ISSUE TITLE
Disabled prop on DateInput FormField is not disabling the field

### ISSUE THREAD

**Issue by ypinneka** [grommet/grommet#4438]
Hi,

Disabled prop on DateInput used inside a formfield is not working as expected.
Please check the attached sandbox, https://codesandbox.io/s/agitated-cdn-x7bsp?file=/src/App.js

**Comment by myasul** [comment]
Why is this closed? It is still an issue. The DateInput component is not being disabled even if the FormField wrapping it is disabled nor is there any prop that can be passed to disable the component.

**Comment by ShimiSun** [comment]
@ypinneka can you share your insights for closing the issue?
@myasul If you think this is a merely typescript issue,  feel free to file a dedicated issue for it.
