### ISSUE TITLE
Investigate alternative to moment.js

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet#444]
Moment.js consumes 420.68 KB (before compression) in Grommet apps.  Need to find a lighter-weight alternative.  Possibly https://github.com/taylorhakes/fecha

**Comment by arlair** [comment]
I briefly investigated localisation for currency recently and found there is a Intl Api (ECMAScript Internationalization API (ECMA-402) for JavaScript) that has support in most major browsers except Safari. It sounds the meaning of support is variable in terms of features:
http://caniuse.com/#search=intl

and a Intl polyfill available here:
https://github.com/andyearnshaw/Intl.js/

There is also Globalize (no jquery dependency, just under the repository)
https://github.com/jquery/globalize

globalize/date.js	5.1KB(Minified + gzipped size)	3.8KB(Runtime minified + gzipped size)

"Globalize doesn't use native Ecma-402 yet, which could potentially improve date and number formatting performance. Although Ecma-402 support is improving among modern browsers and even Node.js, the functionality and locale coverage level varies between different environments (see Comparing JavaScript Libraries slide 25). Globalize needs to do more research and testings to use it reliably."

**Comment by alansouzati** [comment]
Thanks for your investigation.

We are using react-intl for localization support. behind the scenes they use Intl api, so that's good news.

We need a date library to handle data formatting in input fields, and easy time conversion (string -> date and vice versa).

We are using moment.js for that but it is quite big. We are evaluating the use of fecha instead.

https://github.com/taylorhakes/fecha

**Comment by arlair** [comment]
Yes, unfortunately it seems like the Intl API only does half the job, date formatting:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

Date parsing in ECMAScript doesn't seem so well covered.

I looked at React-Intl as well and it didn't seem to fit my needs. I started using formatting and parsing based on Globalize via a store passed in the props.

This article seems to suggest jQuery will Globalize for their own date picker:
http://blog.scottlogic.com/2015/03/06/localisation.html

**Comment by arlair** [comment]
Just to clarify, there is Date.parse(), but it seems like a bit of a mess.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

**Comment by karatechops** [comment]
I'd like to propose [date-fns](https://github.com/date-fns/date-fns) as a potential replacement for moment.js. From what I can tell you only import what you need so you're left with a much smaller file size.

**Comment by tracybarmore** [comment]
Hi @arlair, is this still an issue?

**Comment by arlair** [comment]
Hi @tracybarmore, I didn't open the issue :) Moment.js still seems to be listed in the packages.json file, so I would assume this is still a valid issue to consider.

**Comment by eugenioclrc** [comment]
You could try with https://github.com/taylorhakes/fecha

**Comment by dgennetten** [comment]
just fyi, 0180e4c increased dependency on moment.js to fix an ie/edge issue.

**Comment by RyanCCollins** [comment]
I'll bet we could create a babel plugin, similar to babel-plugin-lodash, to enable tree shaking with es6 module imports.  I'll look into this.  I agree that it's crazy to have that big of a dependency.

**Comment by karatechops** [comment]
Looping in 2.x DateTIme  #1460.

**Comment by arlair** [comment]
Maybe it could use an Adapter Pattern if the internal usages are not complex. Then write a default adapter, but allow flexibility with different adapters to replace the default.

People could write their own adapters for the date libraries if they want to continue using an existing or their favourite date library.
