### ISSUE TITLE
List onClickItem not raised

### ISSUE THREAD

**Issue by matthieu-stacklabs** [grommet/grommet#4441]
Since version 2.15 (it used to work on 2.14)

In a List component with onClickItem handler, the expected event is not raised when the item is clicked.

### Expected Behavior

It should behave as documented: "When supplied, this function will be called with an event object that include a 'item' property containing the data value associated with the clicked item and an 'index' property containing the index in 'data' of the clicked item."

### Actual Behavior

The whole List component takes focus and, I guess, prevents the click event from bubbling

### URL, screen shot, or Codepen exhibiting the issue

See official codesandbox, https://storybook.grommet.io/?path=/story/list--onclickitem

### Your Environment

- Grommet 2.15
- Chrome browser v84.0.4147.135
- MacOS Catalina (Desktop)

**Comment by taysea** [comment]
Hey @matthieu-stacklabs, could you provide a sandbox demonstrating the bug? 

I tried the storybook example locally and adjusted the onClickItem to be: `onClickItem={event => console.log(event)}` and the event properly logged out and contained the additional `event.item` as documented.

**Comment by ericsoderberghp** [comment]
FYI, I am seeing this behavior on an app as well. The first click causes the List to receive focus but the `onClickItem` handler isn't called. The second click does call `onClickItem`.

**Comment by ericsoderberghp** [comment]
If I insert a `<Box height="medium" flex={false} />` above the List in the onClickItem story, the problem reproduces. It looks like if clicking will cause the List to scroll in some way, the onClickItem function isn't called.

**Comment by matthieu-stacklabs** [comment]
Hi Taysea, you're right it works well on simple example, but find below a little more complex one which raises the issue:

```
import React from "react";

import { Grommet, List } from "grommet";

const Demo = (props) => {
    const data = [
        { label: "a" },
        { label: "b" },
        { label: "c" }];

    return (
        <Grommet><List data={data} primaryKey="label"
            onClickItem={(e) => { console.log(e.item.label) }} />
        </Grommet>
    )
}

export default Demo;
```

Actually, it's when the "primaryKey=..." attribute is present that the behaviour is odd: it seems that only the clicks on "b" are well received, many clicks on "a" or "c" go missing

Regards

**Comment by ericsoderberghp** [comment]
I'm wondering if the problem is tied to `listRef.current.focus();` inside `onFocus`. If I remove that, it seems to behave correctly.

**Comment by taysea** [comment]
Thanks for the updated examples and context on this @matthieu-stacklabs @ericsoderberghp. I'm going to take a look into that behavior.
