### ISSUE TITLE
Datatable without header <thead>

### ISSUE THREAD

**Issue by bhavin-r-shah** [grommet/grommet#4442]
We have a requirement to show info as a table without header. Can DataTable support the same?

I played with DataTable and was able to remove the header names from the header column. But I need a way to remove the thead from the DOM and the border below it. Please refer https://codesandbox.io/s/grommet-datatable-without-header-fep05

I am using Grommet version 2.15.0.

**Comment by halocline** [comment]
Hi  @bhavin-r-shah. Can you please elaborate on the need for removing `<thead />` from the DOM?

In your example, it looks as if this use case is to display a relatively static set of terms and definitions. If this is the case, using Grommet's `<Table />` component might be more suitable than `<DataTable />` which I would tend to reach for more in cases where I was displaying more "live" data.

https://v2.grommet.io/table

If the `<Table />` approach, you would simply omit the `<TableHeader />` from your markup.

```
const data = [
  {
    term: "Group Usage",
    description: "Physical usage of the group."
  },
  {
    term: "Pool Usage",
    description: "Physical usage of the pool."
  },
  {
    term: "Volume Usage",
    description: "Logical usage of the volume."
  },
  {
    term: "Snapshot Usage",
    description: "Logical usage of the snapshot."
  },
  {
    term: "Array Usage",
    description: "Physical usage of the array."
  }
];

const Definitions = data => (
  <Table>
    <TableBody>
        {data && data.map(datum => <TableRow>
          <TableCell>{datum.term}</TableCell>
          <TableCell>{datum.description}</TableCell>
        </TableRow>)}
    </TableBody>
  </Table>
);
```

**Comment by bhavin-r-shah** [comment]
Thanks for the proposal. What use case suits best for DataTable and Table components? They look similar but the Table component looks more extensible by providing control over the table body, header etc.

**Comment by halocline** [comment]
DataTable is actually consuming Table, but enhancing it with functionality such as sorting, filtering, infinite scroll, grouping/collapsing, etc.

I would reach for DataTable the vast majority of the time. Any time a user is attempting to find a specific record, filter down a result set to records of interest (e.g. to perform batch actions), browse a data set for patterns, assemble a data set for analysis, etc. would all be cases I would want DataTable.

My guess is the requirement for a table without column headers would be more edge case. In most cases users users are going to want column headers for definition, reference, and orientation.

I would go to Table in more edge cases where I might be interacting with more static, limited data. Even then, depending on the use case, I might reach for List, Grid, or others that might be a better fit.

**Comment by bhavin-r-shah** [comment]
Sounds good.
