### ISSUE TITLE
DataTable with fixed header height

### ISSUE THREAD

**Issue by bhavin-r-shah** [grommet/grommet#4443]
Is there a way to provide fixed height to Grommet data table header?

**Comment by halocline** [comment]
Hi @bhavin-r-shah. I believe the way to define this currently is in the theme via `theme.table.header.extend`.

https://github.com/grommet/grommet/blob/03136c5e1a5fc55b20b41ddeb3162d2c096d25a9/src/js/themes/base.js#L1072

You can do this by providing a fixed value:
```
table: {
    header: {
        extend: `
            height: 48px;
        `,
},
```

Or, perhaps even better, by tying it to the theme's global sizing:
```
table: {
    header: {
        extend: ({ theme }) => `
            height: ${theme.global.edgeSize.large};
        `,
},
```

**Comment by jcfilben** [comment]
@bhavin-r-shah let us know if the explanation @halocline gave helped. If so we should be able to close this issue

**Comment by ShimiSun** [comment]
I'll be closing this issue, feel free to reopen with more details in case still relevant.
