### ISSUE TITLE
Handle row selection within DataTable

### ISSUE THREAD

**Issue by bhavin-r-shah** [grommet/grommet#4444]
In the current DataTable, the consumer has to handle the checkbox and row selection logic. Reference - https://storybook.grommet.io/?path=/story/datatable--controlled

Since this is a common use case for most tables, can this be handled by the DataTable component internally?

Grommet version used - v2.15.0

Requirements:
Option to add row selection which provides:
1. Checkbox for header and each row
2. Get count of selected rows in the table
3. Option to control visual styling of of the selected row(s) like background color, opacity etc.

**Comment by halocline** [comment]
@ShimiSun This seems like a reasonable and useful feature request. I'd recommend discussion to see if this functionality is something Grommet would like to support.

**Comment by bhavin-r-shah** [comment]
Thanks @ShimiSun . We had discussed this with Eric and he can help provide the context.

**Comment by ShimiSun** [comment]
The fix will be available on v^2.15.1.
