### ISSUE TITLE
DataTable with col span

### ISSUE THREAD

**Issue by bhavin-r-shah** [grommet/grommet#4445]
Does DataTable support col span like HTML table?

Requirements:
1) Have different column headers but their data is combined into 1 cell.
2.a) Have grouped column header
2.b) Have 2 rows in column header

Requirement example - https://codepen.io/bhavin120986/pen/abNpxrw

Grommet version used - v2.15.0

**Comment by IanKBovard** [comment]
@bhavin-r-shah have you checked out the storybook examples? These two examples look like they would be of use to you.

https://storybook.grommet.io/?path=/story/datatable--grouped
https://storybook.grommet.io/?path=/story/datatable--column-sizes-resizeable

**Comment by bhavin-r-shah** [comment]
The examples are grouping rows. Our requirement is to combine cells in header and table body.

**Comment by jcfilben** [comment]
Just wanted to check in and see if there was still interest in this enhancement. If you are interested feel free to leave a comment that says so. If there is no longer interest in this I think we can close this issue.

**Comment by jcfilben** [comment]
Closing, see previous comment
