### ISSUE TITLE
Customizable sort icons for DataTable

### ISSUE THREAD

**Issue by bhavin-r-shah** [grommet/grommet#4446]
Can DataTable sort icons be customized?

Requirements:
1. Allow user to provide sort icon. 3 options - sort ascending, sort descending and icon to show column is sortable but not currently sorted upon.
2. Allow user to provide background color for the sorted column

Grommet version used - v2.15.0

**Comment by halocline** [comment]
@bhavin-r-shah Sort icons may be defined via the theme at `theme.dataTable.icons`.

https://github.com/grommet/grommet/blob/03136c5e1a5fc55b20b41ddeb3162d2c096d25a9/src/js/themes/base.js#L683

This will take care of the "sort ascending" and "sort descending".

----------------------------------------

For "sortable, but not currently sorted upon," this would be a feature enhancement. The sort Icon is being defined here: https://github.com/grommet/grommet/blob/dc3ad5cbaf99c64c01a6c987c472f8bf2141e6d7/src/js/components/DataTable/Header.js#L69
This definition would need to be expanded to consider the scenario for when `sort.property !== property`. Additional considerations would be:
- Does the implementer have the ability to choose whether or not this "sortable" icon is shown?
- Does the implementer have the ability to specify when this "sortable" icon is shown? (e.g. always, on hover, etc.)
@ShimiSun I can create a feature request issue for this if you would like.

------------------------------------

For "allow user to provide background color for the sorted column," this would also be a feature enhancement. The DataTable's sort state would need to be passed to its Body / Body's Cell (Header already receives this) and then styling for the Cell's would need be added based on the `sort.property` state.
@ShimiSun I can create a feature request issue for this if you would like.

**Comment by ShimiSun** [comment]
Thank you @halocline, I think your suggestion of the existing icons API should work 
https://github.com/grommet/grommet/blob/03136c5e1a5fc55b20b41ddeb3162d2c096d25a9/src/js/themes/base.js#L683

Regarding the 3rd option icon: 
>...to show column is sortable but not currently sorted upon.
We would stick with the simple design of not showing an icon at all.
@bhavin-r-shah feel free to share screenshots that your team/designer thinks it will be useful to use a sortable icon before we'll add enhancements to the code base.

Regarding:
> Allow user to provide background color for the sorted column

We would like to see a design for that, that demonstrates the required behavior.
