### ISSUE TITLE
DataTable height and column resizing

### ISSUE THREAD

**Issue by bhavin-r-shah** [grommet/grommet#4447]
The grommet spec mentions that if the size attribute is used to control the table height, it cannot be used in combination with column resizing. Also it will give same width to all cells.

Is there a plan to remove these constraints?

**Comment by IanKBovard** [comment]
I assume it won't change for the reason stated in the grommet docs.
> ...in order to preserve header and footer cell alignment, all cells will have the same width.

For questions like these, I recommend the [grommet slack channel](http://slackin.grommet.io/)

**Comment by ShimiSun** [comment]
@bhavin-r-shah I agree with @IanKBovard, please bring up this issue on your call with eric to explain your use case and see how it can be addressed. Or file a new issue with the detailed use case and designs.
