### ISSUE TITLE
DataTable column resizing

### ISSUE THREAD

**Issue by bhavin-r-shah** [grommet/grommet#4449]
When data table column resizing is enabled:

1) The size provided to column acts as min-width when resizing the column. The column cannot be resized less than this size (width).
Can this be over-ridden? We want size to be the default width of the column when the table loads but allow re-sizing to change the column width irrespective of the size.

CodePen - https://codesandbox.io/s/grommet-resizable-datatable-lns1y

2) Can we override the style of the column resizer? Like the placement, height, weight, color etc.?

**Comment by IanKBovard** [comment]
@bhavin-r-shah just trying to clarify. You want a min-width along with the use of the resizeable prop?

Is this something you're looking for?
https://codesandbox.io/s/grommet-resizable-datatable-forked-b6zs8?file=/index.js

**Comment by bhavin-r-shah** [comment]
The above sandbox solution works. The solution is to wrap the DataTable inside Grommet tag and pass the full={true} attribute. I would need to test the impact of using this attribute.

**Comment by ShimiSun** [comment]
Feel free to reopen if needed.
