### ISSUE TITLE
New version release?

### ISSUE THREAD

**Issue by localhosted** [grommet/grommet#445]
Is there going to be a newer release anytime soon? I didn't want to have to maintain a Grommet package with the latest changes, but 0.5.3 is missing several components, like Column, and the structure is different from the docs.

**Comment by tearsofphoenix** [comment]
+1

**Comment by alansouzati** [comment]
We are still in the process of fixing few things before releasing grommet 0.5.4. I'm hoping we will be able to release next Tuesday. In the meantime we can use the stable branch, in your package.json add that:

```
"grommet": "https://github.com/grommet/grommet/tarball/stable",
```

**Comment by localhosted** [comment]
This works for now, but after awhile, having to keep track of versions changing on an old application will be quite challenging. Would be nice if there where a faster release schedule.
