### ISSUE TITLE
DataTable - hover style for row

### ISSUE THREAD

**Issue by bhavin-r-shah** [grommet/grommet#4450]
We need to provide style when we hover over a row like change background color. Is there a way to do the same?

**Comment by jcfilben** [comment]
@bhavin-r-shah Looking through the issues you've filed I think these questions would be better suited for discussion on the Grommet #help slack channel. Filing and issue usually means that there is a bug in Grommet or issues can also be filed for potential improvements to Grommet.

If you are new to Grommet I would encourage you to join the slack channel [here](http://slackin.grommet.io/). You can post questions here and look through old discussions as well. When asking for help on the slack channel it is helpful to include a codesandbox with an example of you code. Also there are some great examples on Grommet's storybook [here](https://storybook.grommet.io/) that you can look through

**Comment by halocline** [comment]
Hi @bhavin-r-shah 👋 . Row hover style for DataTable can be defined in your theme at `table.row.hover`.
https://github.com/grommet/grommet/blob/03136c5e1a5fc55b20b41ddeb3162d2c096d25a9/src/js/themes/base.js#L1089

From there, you can specify `background` and `color` treatments.

Currently, DataTable only applies these hover styles when `onClickRow` prop is defined such as:
```
<DataTable
  onClickRow={ () => {} }
  ...
/>
```

I believe the intent behind this is that the hover style (including cursor as a pointer) is only applied when there is an action associated with the row's click. If the hover style needs to be applied on hover, regardless of accompanying click action, I believe that would be a feature request.

**Comment by IanKBovard** [comment]
@bhavin-r-shah let me know if halocline has answered your question, and we can close this issue.

**Comment by IanKBovard** [comment]
@bhavin-r-shah just checking to see where you're at with this issue.

**Comment by ShimiSun** [comment]
I'll be closing this issue, feel free to communicate if you still have any related concerns.
