### ISSUE TITLE
Tab - active props is no longer working

### ISSUE THREAD

**Issue by deniselashlley** [grommet/grommet#4460]
We created a general tab style in the main theme, however want to override the active style in a specific component using props.active. It works fine in version 2.14.0. Updated to the latest version and no longer works with props.active

### Expected Behavior

The tab button should show the overriding background-color when active=true/false

### Actual Behavior

the background color uses the default theme color instead active=undefined

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/brave-tdd-ussjb?file=/src/component/buttonTab.js

### Your Environment

- Grommet version: @2.15.0
- Browser Name and version: chrome
- Operating System and version (desktop or mobile): both

**Comment by ShimiSun** [comment]
Adding @jcfilben comment from [Slack](https://grommet.slack.com/archives/C04LMHN59/p1598483127016400?thread_ts=1598439935.015400&cid=C04LMHN59):

>Jessica Filben  2 hours ago
Hey Denise, I found this PR that was merged in the latest release. It mentions that previously active was passed to Tab as a prop via clone child. Now active is passed via TabsContext . I think that this is why props.active is not working. I think that the active prop can still be accessed from Tab just might have to go about it differently than before. I'm still trying to figure out exactly how this can be done or if something needs to be changed in the code. Let me know if you have any insights
https://github.com/grommet/grommet/pull/4255

**Comment by ericsoderberghp** [comment]
It looks like we should have passed `active` onto StyledTab: `<StyledTab active={active} />`.

**Comment by taysea** [comment]
I'm taking a look at where this isn't getting passed through. I tried out adding active to styled tab and didn't have success but will try again.

**Comment by ShimiSun** [comment]
Thank you for reporting, the fix is now available on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F). And it will be available on our next official release (^2.15.1)
