### ISSUE TITLE
DateInput and Calendar Bug

### ISSUE THREAD

**Issue by moodele** [grommet/grommet#4463]
### Expected Behavior

Navigating the DateInput / Calendar month and selecting a date should work perfectly

### Actual Behavior

When navigating forward the months of the calendar and going backwards to a previous month still shows calendar of the current navigated month.

### Steps to Reproduce

1. In calendar control click the forward arrow like twice or thrice
2. Try navigating backward by one step or two and select a date
3. Selected date is incorrect

Note: Also setting showAdjacentDays to false doesn't work properly when navigating back and forth of the calendar month

- Grommet version: 2.15.0

 @ShimiSun

**Comment by ShimiSun** [comment]
Linking to #4353

**Comment by jcfilben** [comment]
Was able to reproduce the issue here: https://codesandbox.io/s/grommet-v2-template-forked-gwyjy?file=/index.js
Looks like the `showAdjacentDays` prop is causing the issue in Calendar. I tested in both Calendar and DateInput and issue is occurring in both (uncomment DateInputExample line 33 to see).

**Comment by jcfilben** [comment]
Made another code sandbox to explore the issue more. This one shows the incorrect date issue better and shows the DateInput without the `showAdjacentDays` prop. Also it looks like things being passed through `dropProps` in dateInput are not working
https://codesandbox.io/s/grommet-v2-template-forked-4m509?file=/index.js

**Comment by Kamony** [comment]
Not displaying correct month when navigating forward and back in Calendar header is probably caused by related animations. 

Quick fix is to set Calendar property `animate` to `false`
