### ISSUE TITLE
"min" aggregate function not working properly for DataTable

### ISSUE THREAD

**Issue by parth611git** [grommet/grommet#4471]
When groupBy attribute is provided in DataTable and some one of the field is aggregated by "min" function then it is always giving result as 0
### Expected Behavior
It should calculate proper minimum value from given dataset

### Actual Behavior
Currently it is displaying minimum value as 0.

### Your Environment
https://codesandbox.io/s/inspiring-heisenberg-0k0vn?file=/src/App.js

- Grommet version: 2.15.0
- Browser Name and version: Chrome and Latest
- Operating System and version (desktop or mobile): win 10 Desktop

**Comment by ShimiSun** [comment]
Thank you for reporting and fixing, fix will be available on our next release.
