### ISSUE TITLE
Publishing Theme error

### ISSUE THREAD

**Issue by RicardoGaefke** [grommet/grommet#4476]
### Expected Behavior
To publish theme

### Actual Behavior
Form validation error even when fulfilled

![image](https://user-images.githubusercontent.com/32141532/91852725-9ecfdb00-ec37-11ea-9839-634b9e1bbf73.png)

**Comment by ShimiSun** [comment]
Should this issue be filed on the grommet/grommet-designer repo vs grommet/grommet?

**Comment by ericsoderberghp** [comment]
Should be grommet-theme-designer

**Comment by jcfilben** [comment]
I moved the issue to grommet-theme-designer https://github.com/grommet/grommet-theme-designer/issues/9
Should be able to close the issue here
