### ISSUE TITLE
Add support for custom days in the Calendar component

### ISSUE THREAD

**Issue by cliffpyles** [grommet/grommet#4481]
### Requested Behavior

The developer would have the ability use their own component in each day block in the Calendar. The component should also have access to the current day it is rendering, the selected date(s) on the calendar, and if the Calendar is handling range selection.

### Example

![calendar-example](https://user-images.githubusercontent.com/904039/91962866-1d318900-ecdb-11ea-92d4-fa85ed663b86.png)

### Implementation

The Select component solves similar problems, and it does so by providing a function as the child for the component. I believe this is a good solution for the Calendar also.

The Calendar would now have a `children` prop that accepts a function. The function is passed 3 arguments :

1. `day` - the current day being rendered (string in ISO8601 format)
2. `selected` - the day(s) that is selected (string in ISO8601 format or  array of strings in ISO8601 format)
3. `inRange` - whether the calendar is using range selection (boolean)

The Calendar would now have a `fill` prop which is a boolean. This tells the calendar to fill the width and height of the container, and that the days should have a width of 14.3%.

**Comment by ShimiSun** [comment]
Feel free to make an open-source contribution :)

**Comment by ericsoderberghp** [comment]
Great start. I'm thinking the render function arguments could be: `({ date, day, isSelected, isInRange }) => {}`. Where
`date` is a string containing the ISO8601 date for the day being rendered,
`day` is a number containing the day of the month being rendered, since most implementations will want to render this and it's easier than having to pull it out of `date`.
`isSelected` is a boolean indicating whether this date is selected,
`isInRange` is a boolean indicating whether the date is within a selected range of dates.

I am assuming that the Calendar component continues to handle user interaction with each day when `onSelect` is provided. If `onSelect` is not provided, the children render function can contain interactive elements.

**Comment by cliffpyles** [comment]
@ShimiSun Sounds good. Looking forward to it! :)

@ericsoderberghp Thanks. It's been a fun problem to think through. The props sound great, and the onSelect treatment will give lots of flexibility. Should I let the issue sit for a few days and give others a chance to chime in? Or should I get started on the code?

**Comment by ShimiSun** [comment]
Go have fun with it, its all yours!! ❤️

**Comment by cliffpyles** [comment]
I've applied the style changes for the fill prop, and I am about half done with the changes needed for the custom component. Would there be any issues with me moving some of the Calendar's render functions to internal components in the Calendar?

**Comment by cliffpyles** [comment]
It looks like the scope of moving them is larger than I thought. I'll just stick to the custom component for now. :)

**Comment by cliffpyles** [comment]
I've taken a shot at it. Please let me know if I've missed anything, or if there are additional changes to be made.

I was drawing a blank on what the correct treatment should be when using the `fill` property with `daysOfWeek`. The spacing for the days of the week are a little off. You should be able to see what I mean by navigating to the "Fill" Calendar story, or you can checkout the screenshot in the PR. Please let me know if you have any ideas.

**Comment by nomadus** [comment]
@cliffpyles Thanks for the changes, I have long waited to have a calendar which fills the space nicely. I have installed the new version and I have a question. If I intend to change some specific days but leave the rest intact, how would I do it? Currently, the custom days changes the look of all the days.

**Comment by cliffpyles** [comment]
Hi @nomadus. Awesome. I'm glad you find it helpful! When the custom day feature is used it applies to all days. Unfortunately there isn't currently a way to apply the default days on some days, and the custom on other days. Does that answer your question?

**Comment by nomadus** [comment]
Thanks, @cliffpyles, it is indeed helpful as now I don't have to search for a magic combination of cell and calendar widths. Maybe leaving defaults will be in the scope of another PR:)

**Comment by ShimiSun** [comment]
@cliffpyles thank you for the fantastic contribution! Can this issue be closed now or are there still any pending issues?
The fix can be found on the  [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) and will be available on our next official release.

**Comment by cliffpyles** [comment]
@ShimiSun Thanks again for all of your help! It can be closed!
