### ISSUE TITLE
Chart xaxis overlap each other when labels are long

### ISSUE THREAD

**Issue by ibhag** [grommet/grommet#449]
xAxis overlap when labels are long. With time charts, mostly the labels will be long and should be readable. May be we can wrap the labels as d3 does. You can see the same 
in http://codepen.io/ibhag/pen/YqWqJy if you make the window smaller.

![test](https://cloud.githubusercontent.com/assets/17637919/13694756/893983bc-e77e-11e5-98c0-76aee4fc600a.png)

**Comment by ericsoderberghp** [comment]
This has been addressed by the new chart Axis component.
