### ISSUE TITLE
Grommet styles being applied to shadowDOM sub-components

### ISSUE THREAD

**Issue by jwyunker** [grommet/grommet#4493]
When using a shadowDOM library to limit styling on components.  [https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM](url)  Grommet seems to find a way to style the components even though the component exists in a shadow tree.

### Expected Behavior

The grommet stylings should apply to the document and the shadow hosts, but everything within the shadow tree should be unstyled.

### Actual Behavior

In the sample app provided the styles are applied with various degrees of success to all components and disappear depending on how the page is accessed.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/react-shadow-forked-406hh?file=/README.md

### Steps to Reproduce

See the README.md document in the sandbox and look at the App.js code in the sandbox to see which components are within the shadowDOM and which are not.

### Your Environment
Linux, and Windows 10

- Grommet version: 2.15
- Browser Name and version:
- Operating System and version (desktop or mobile):
Ubuntu 20.04.1 LTS:   Firefox 79.0, Chrome: Version 85.0.4183.83 (Official Build) (64-bit)
Windows 10: Firefox 80.0.1

**Comment by IanKBovard** [comment]
@jwyunker Just trying to clarify things. Are you using shadow dom and style overrides to make custom components with custom styles? Is there any reason, you don't want to use theme, ThemeContext, or styled-components?

**Comment by jwyunker** [comment]
We are building a container that can house components from different sources which may be using different underlying toolkits which we do not want to dictate.  We were trying to use shadowdom to prove that a contained component wouldn't interfere with the outside container through css.

**Comment by IanKBovard** [comment]
It might take me some time, but I'll look into this.

**Comment by IanKBovard** [comment]
Not sure if this is the problem, but it looks like styled-components doesn't support the use of shadow-dom out of the box, but there are some fixes in this issue here. Will do more testing. 

https://github.com/styled-components/styled-components/issues/659

**Comment by jwyunker** [comment]
Sorry I didn't see your update.  I'll take a look at the thread.

**Comment by IanKBovard** [comment]
Not sure if this is correct, but do you see the issue here?
https://codesandbox.io/s/react-shadow-forked-vm7tr

**Comment by jwyunker** [comment]
Ian, removing the styled-components aspect of the react-shadow import seems to fix the vanishing styles issue I was seeing.  I'm not sure why they gradually blink out of existence based on what panel you are on though.  

The react-shadow README.md says: "Alternatively you can use styled-components normally, as each time a shadow boundary is created, a new StyleSheetManager context is also created which will encapsulate all related styles in their corresponding shadow root"  which makes it seem like the components should have remained styled depending on how they were contained.

**Comment by IanKBovard** [comment]
my guess is that grommet heavily uses styled components. It might just take a while for it to render, which is why you see your styles being applied when you go from page to page, and not on initial render. i'm not sure the same rules apply to a component getting its styles from theme rather than its parent when using the root from react-shadow. There may be a way to use react-shadow/styled-components with some config files, but i'm not sure how. 

I don't view this as an issue with grommet, but just a tricky implementation issue using styled-components and react-shadow. @jwyunker let me know if you have any more questions, otherwise i believe we can close this issue.

**Comment by jwyunker** [comment]
I agree it's probably an issue with the styled-components and the react-shadow component based on your sandbox.  Not knowing the details on how grommet handles and applies stylesheets led me to believe grommet could be part of the problem.
