### ISSUE TITLE
Certificate icon error

### ISSUE THREAD

**Issue by RicardoGaefke** [grommet/grommet#4495]
I am using TypeScript with eslint (AirBnB) and when I try:

```
import {
  UserAdmin, Organization, Compliance, Certificate,
} from 'grommet-icons';
```

I get the error: `export 'Certificate' was not found in 'grommet-icons'`

### Expected Behavior

To be able to use the `Certificate` icon.

### Actual Behavior
Error:
`export 'Certificate' was not found in 'grommet-icons'`

- Grommet version:
```
"grommet": "^2.15.0",
"grommet-icons": "^4.4.0",
```
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
This issue should be placed on the grommet-icon library.
The Certificate icon wasn't officially released yet, and you wouldn't find it on npm.
You can use the icons stable branch:
```
  "grommet-icons": "https://github.com/grommet/grommet-icons/tarball/stable",
```
