### ISSUE TITLE
Collapsible allows user to tab focus on focusable children when not open

### ISSUE THREAD

**Issue by jkkealii** [grommet/grommet#4498]
### Expected Behavior

When Collapsible is not open, user should not be able to tab focus on any focusable children within the Collapsible.

### Actual Behavior

User is able to tab focus on focusable children within the Collapsible.

### URL, screen shot, or Codepen exhibiting the issue

[Code Sandbox](https://codesandbox.io/s/compassionate-goldwasser-u60d0?file=/index.js)

### Steps to Reproduce

1. Create Collapsible with focusable element inside, e.g. Button.
2. While Collapsible is not open, attempt to tab focus.
3. Observe focus on focusable element inside of Collapsible, instead of the next focusable element outside of the Collapsible.

### Your Environment

- Grommet version: 2.15.0
- Browser Name and version: Firefox Developer Edition 81.0b3
- Operating System and version (desktop or mobile): MacOS Catalina 10.15.6

**Comment by laka3000** [comment]
Fix proposal: #4501

**Comment by ShimiSun** [comment]
Thank you for reporting this issue! The fix will be available on our upcoming release.
