### ISSUE TITLE
Lack of passing props to children in components

### ISSUE THREAD

**Issue by localhosted** [grommet/grommet#450]
Several components don't pass props to their children, making reuse a very hard job. One case is the Calendar component, not passing on onBlur, making it necessary to create a component wrapping it up, and then modifying the CSS so it fits inside the FormField.

Would be nice if passing props was the default behavior.

**Comment by bryanjacquot** [comment]
Box works this way, but other components should be updated to behave this way.

**Comment by ericsoderberghp** [comment]
Let's focus on one component at a time for this type of issue. I think we should treat this issue as Calendar specific for onBlur.
