### ISSUE TITLE
Unable to import Card components and CodeSandbox example broken (v2)

### ISSUE THREAD

**Issue by cyberflowsurfer** [grommet/grommet#4506]
From https://v2.grommet.io/card  go to the CodeSandbox.   It reports that it could not find src/Card.js
![image](https://user-images.githubusercontent.com/1638720/92335710-602e8c00-f04e-11ea-9c5c-a1b15cbd76cc.png)

I tried the example code  in my application. The following imports fail:
import { Card, CardHeader, CardBody, CardFooter} from 'grommet/components'; 

### Expected Behavior
  1. Ability to successfully import Card components
  2. Working CodeSandbox example for Card

### Actual Behavior

See preceding
See preceding

### Steps to Reproduce

See preceding 

### Your Environment
create-react-app using 
    "grommet": "^2.14.0",
    "grommet-icons": "^4.4.0",
    "grommet-styles": "^0.2.0",

- Browser Name and version: N/A (Chrome, Edge)
- Operating System and version (desktop or mobile): Windows 10 Pro

**Comment by halocline** [comment]
@cyberflowsurfer I believe Card was released in Grommet 2.15.0. Can you try upgrading you Grommet version? That should resolve your issue.

**Comment by IanKBovard** [comment]
@cyberflowsurfer halocine is correct. You can import the card component from grommet version 2.15 like so.
`import {Card} from 'grommet`

Sorry about codesandbox. It's pretty out of date, and has not been updated in a while. I recommend the storybook examples, as they are updated frequently.

https://storybook.grommet.io/?path=/story/card--clickable

**Comment by cyberflowsurfer** [comment]
Thanks for the version upgrade tip and pointer to story/card.  That resolves my issues and hopefully anyone similarly confused will find the "bread crumbs" useful!
