### ISSUE TITLE
ResponsiveContext is undefined with Gatsby

### ISSUE THREAD

**Issue by jnapprogs** [grommet/grommet#4511]
### Expected Behavior

When I console log the result of the `ResponsiveContext` component, I should see `small`, `medium`, or `large` as I adjust the size of my browser.

### Actual Behavior

When I open up my browser, I get undefined.

### URL, screen shot, or Codepen exhibiting the issue

Here is the code that extracts the size and logs it out.
![image](https://user-images.githubusercontent.com/57240956/92528248-4e2f2380-f1dd-11ea-94aa-59af6c94d631.png)

This is the result I am receiving when I open up my browser console.
![image](https://user-images.githubusercontent.com/57240956/92528287-5edf9980-f1dd-11ea-802d-56d6cd4ee37a.png)

### Steps to Reproduce

1. Download the Gatsby CLI
2. Run `gatsby new`
3. Choose the default project name
4. Choose `gatsby-starter-default`
5. Navigate to the `{projectDir}/src/components` directory and delete `layout.css` and `layout.js`
6. In the same directory, create a directory named `shared` and navigate into it.
7. Create a file named `layout.tsx`
8. Run `npm install grommet styled-components grommet-icons --save`.
9. Paste the following code into your `layout.tsx` file

```
import React, { useContext } from "react"
import { ResponsiveContext, Grommet, Nav, Anchor } from "grommet"
import { Home, ChatOption, Notification } from 'grommet-icons';

interface Props {
  children: React.ReactNode
}

const Layout = ({ children }: Props) => {
  const size = useContext(ResponsiveContext)

  console.log(`The size is ${size}`);

  return (
    <Grommet full>
      <Nav direction="row" background="brand" pad="medium">
        <Anchor icon={<Home />} />
        <Anchor icon={<Notification />} />
        <Anchor label={size} />
        <Anchor icon={<ChatOption />} />
      </Nav>
      {children}
    </Grommet>
  )
}

export default Layout
```
10. Navigate to your `{projectDir}/src/pages` and delete all files within the directory.
11. Create an `index.tsx` file.
12. Paste the following code into your file:
```
import React from 'react';
import Layout from '../components/shared/layout';

const IndexPage = () => (
  <Layout>
    <h1>Hello</h1>
  </Layout>
);

export default IndexPage;
```
13. Run `npm run develop` into your terminal and open your console in your browser of choice.  In my case, it is Firefox -- information is below.

### Your Environment

- Grommet version: ^2.15.0
- Browser Information
![image](https://user-images.githubusercontent.com/57240956/92529000-a155a600-f1de-11ea-82c8-2e1e40cd3bc7.png)

- Operating System and version (desktop or mobile): I am on a desktop
![image](https://user-images.githubusercontent.com/57240956/92529067-c4805580-f1de-11ea-8bb2-ab3bcf6f426e.png)

Additional information:
I am using Gatsby as my front-end framework.  I was experimenting with Grommet last night for possible use with a company project and there were no issues.  There was a [security vulnerability](https://www.npmjs.com/advisories/1555) with a sub-dependency but it seems to have been patched as I'm not getting an issue anymore when I run `npm audit`.  Not sure if the issue is tied to that but just keeping possibilities open.  The current version of Gatsby is `^2.24.55`.

**Comment by halocline** [comment]
Hi @jnapprogs 👋. For SSRs like Gatsby or Next, context providers aren't available at the SSR build time. The solution is to move the context provider (in this case `<Grommet />`) wrapping the SSRs root element.

Here's the Gatsby documentation: https://www.gatsbyjs.com/docs/ssr-apis/#wrapRootElement

Here's a related Slack thread which helps another developer in a similar situation: https://grommet.slack.com/archives/C04LMHN59/p1573144644422200?thread_ts=1573142429.415300&cid=C04LMHN59

**Comment by jnapprogs** [comment]
Hi @halocline!  Thanks for getting back to me.  I'll go ahead and try that out.

**Comment by jnapprogs** [comment]
Hi @halocline!  I went ahead and moved the `<Gatsby />` component to the root of the application and, in terms of rendering, everything is still normal.  Which is awesome 🚀 

![image](https://user-images.githubusercontent.com/57240956/92535136-686ffe00-f1eb-11ea-9463-6a7b83614ad9.png)

Unfortunately, I'm still getting an undefined when it comes to extracting out the value of the ResponseContext.

Here is the updated `layout.tsx` code with the `<Gatsby />` component moved to the `gatsby-ssr.js` file.
![image](https://user-images.githubusercontent.com/57240956/92535405-fe0b8d80-f1eb-11ea-9104-e0b483892138.png)

Here is the result on the UI.
![image](https://user-images.githubusercontent.com/57240956/92535327-cef51c00-f1eb-11ea-8b59-0cde3bf0f1d4.png)

After looking at the [Responsive Context documentation](https://v2.grommet.io/responsivecontext) again, it says that the value is derived from the `global.breakpoints`.  After looking at the type definition file, I see that the values are optional.  I was wondering if the values are always computed or only when the `ResponseContext` is wired up correctly?

Thanks!

**Comment by jnapprogs** [comment]
Solved the issue.  Instead of putting the setup code in the `gatsby-ssr.js` file, I moved it over to the `gatsby-browser.js` and I'm able to extract the size of the screen using the ResponsiveContext component.  Here is the code that I used:

```
/**
 * Implement Gatsby's Browser APIs in this file.
 *
 * See: https://www.gatsbyjs.org/docs/browser-apis/
 */

// You can delete this file if you're not using it

const React = require('react');
const Grommet = require('grommet').Grommet;

exports.wrapRootElement = ({ element }) => {
  return (
    <Grommet full>
      {element}
    </Grommet>
  )
}
```
