### ISSUE TITLE
Customizable Avatar text size

### ISSUE THREAD

**Issue by Zodiase** [grommet/grommet#4537]
### Expected Behavior

I'd expect the size of the text in the Avatar component to be customizable to suit the different sizes of the Avatar component.

### Actual Behavior

The text size is fixed at `"large"`, per https://github.com/grommet/grommet/blob/85e3d85896327d9e6bf96ca5e6e307bd4793fccc/src/js/components/Avatar/Avatar.js#L50.

### URL, screen shot, or Codepen exhibiting the issue

Looks ridiculous when using `"xsmall"` for the size of the Avatar component, while the text is still `"large"`. The problem is there is no way to change the text size without changing the global size of `"large"` Text.
![image](https://user-images.githubusercontent.com/1815174/93738233-1d1a0000-fb9a-11ea-8e3c-cbf6f09287a2.png)

### Steps to Reproduce

```
<Avatar size="xsmall">T1</Avatar>
```

### Your Environment

- Grommet version: 2.14.0
- Browser Name and version: Irrelevant
- Operating System and version (desktop or mobile): Irrelevant

**Comment by leossantiago** [comment]
Just sent a PR that fixes that :)
