### ISSUE TITLE
Tracking the test coverage improvements effort

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#4539]
### Expected Behavior
Our goal is to improve the test coverage of the grommet core.
Components that need attention:
1-10 top components with the lowest coverage score.
1. Video - 60.53%
2. RadioButtonGroup - 61.22%
3. InfiniteScroll - 66.67%
4. RangeInput - 68.85%
5. Layer - 70.12%
6. DataChart - 74.76%
7. WorldMap - 78.57%
8. Chart - 79.72%
9. Main - 80%
10. Menu 80.52%

### Actual Behavior
Overall coverage:
85.15% Statements 5552/6520
75.58% Branches 4627/6122
82.59% Functions 1200/1453
86.18% Lines 5308/6159

### URL, screenshot, or Codepen exhibiting the issue
Screenshots of baselines
<img width="799" alt="Screen Shot 2020-09-28 at 11 46 08 AM" src="https://user-images.githubusercontent.com/54560994/94467439-3580b080-0180-11eb-8355-4c3dc62e9398.png">

<img width="1777" alt="Screen Shot 2020-09-28 at 11 46 25 AM" src="https://user-images.githubusercontent.com/54560994/94467465-3fa2af00-0180-11eb-83c5-1524528e8e7c.png">

### Steps to Reproduce on tracking coverage (running local coverage)
1. Run `yarn test --coverage`
2. Open grommet/coverage/icov-report/index.html
3. Click on the component for more detail. Lines of code that aren't being covered by tests are marked in red. 

### Additional Info
The top ten components are just a suggestion of what components currently have the lowest coverage. If you want to improve the coverage for another component not on that list feel free to do so.

Please share the coverage improvements (before and after) on your PRs.

Example PRs:
https://github.com/grommet/grommet/pull/4216/files
https://github.com/grommet/grommet/pull/4209/files

**Comment by brendoncaulkins** [comment]
Would you be interested in some help integrating [coveralls](https://coveralls.io/) into your pipeline?  It's a code coverage tracking and enforcement tool that's free for open-source repos. It can deny PRs that drop global coverage below a certain threshold (which you set), or that drop coverage by a certain percentage (so if a PR drops you by, say, 2%, even it's still above the minimum it'll get denied).  This would give you code coverage enforcement on all future PRs, and you can tune the thresholds within coveralls, no code change necessary.

This would require adding an orb and about 5 lines of code into your CircleCi config (probably inside the `jest` step) and connecting the repo to coveralls.  CircleCI handles the rest (blocking PRs).  There's a nifty repo badge with your coverage % on `master`, if that's of interest (who doesn't like repo badges?).

Here's an example repo where I've set it up: [here](https://github.com/brendoncaulkins/splittheloot).  The CircleCi config changes are standard, but a code owner would need to handle adding the repo to coveralls (takes about 2 minutes).  Then we can update the README with the badge code from the repo's coveralls settings page.

**Comment by ShimiSun** [comment]
@brendoncaulkins thank you for the suggestion! Sounds like an interesting idea we can consider for the testing enforcement, feel free to file a PR with the relevant changes.

**Comment by brendoncaulkins** [comment]
> @brendoncaulkins thank you for the suggestion! Sounds like an interesting idea we can consider for the testing enforcement, feel free to file a PR with the relevant changes.

Took a different angle than Coveralls for initial implementation.  Jest can do this all on its own: https://github.com/grommet/grommet/pull/4590

Coveralls would be some extra icing if you care about the repo badge and coverage delta enforcement.  Typically I see Jest set to the contractual minimums, and then Coveralls layered on top to help manage large swings due to large feature branches, refactors or other issues.  Coveralls is also useful for coverage history tracking.

( I swear, I'm not associated with Coveralls, I just like their service)

**Comment by ShimiSun** [comment]
Closing this issue since Hacktoberfest is DONE!! Fantastic results you all!!
![image](https://user-images.githubusercontent.com/6320236/99704990-5ebe0e80-2a56-11eb-995f-77e48444f7e1.png)
![image](https://user-images.githubusercontent.com/6320236/99705053-75fcfc00-2a56-11eb-820b-c14c9cc72f4d.png)
