### ISSUE TITLE
Vertically stretch Drop?

### ISSUE THREAD

**Issue by Zodiase** [grommet/grommet#4544]
### Expected Behavior

Since Drop can stretch horizontally to match the width of the target, wouldn't it be nice if it could alternatively stretch to match the height of the target? Just like the drop menu case for horizontal stretch, when the Drop is aligned to the left or right of the target, one might want it to match the height of the target.

### Actual Behavior

From the component doc it seems `stretch` only applies horizontally.

### URL, screen shot, or Codepen exhibiting the issue

To produce something like this, where the panel with messages is expanded by clicking the buttons on the left side bar and the panel matches the height of the side bar:
![image](https://user-images.githubusercontent.com/1815174/94109970-b04f7180-fdf6-11ea-8feb-e5807bcbb778.png)

**Comment by IanKBovard** [comment]
Just double checking the issue, you want the drop to be aligned with the button? or do you want the height of the drop to be that of the button?

**Comment by Zodiase** [comment]
@IanKBovard imagine the right side panel is a drop/pop-up, and it matches the height of the left side panel (the dark gray slip).

**Comment by IanKBovard** [comment]
The right side panel is the one justified top with the text 'Gerneated....'? The dark gray sidebar is pretty much fullscreen right? Would a layer better serve your purpose?

**Comment by Zodiase** [comment]
@IanKBovard The right side panel is the entire chat "window", all the way from top to bottom. This screenshot is just a small part of the app window. Sorry about the confusion. Let me show you another illustration and hope it's more clear.

![image](https://user-images.githubusercontent.com/1815174/94206317-044f6a00-fe7a-11ea-8015-fa7b9d70e63e.png)

So in this image, the content (e.g. buttons) in the red area will open the magenta layer. The magenta layer hovers above the green area. 
If I use `Layer` for the magenta area and I don't apply other tricks, the magenta area would be aligned with the window, and I'd have to use the `margin` prop to prevent the magenta area to reach into the yellow and blue area. But that means the red component now has to know how it's being positioned, which is a bad practice.
If I could use `Drop` with vertical stretch, then the vertical size of the magenta area would match that of the red area, and now the position of the magenta area becomes adaptive instead of hard-coded.

**Comment by IanKBovard** [comment]
ahh, i gotcha. thanks for clearing that up. ill take a deeper look at this tomorrow, and see if there is any way to do this with grommet currently, and post a sandbox when i do.

**Comment by Zodiase** [comment]
@IanKBovard FYI I have a playground here: https://codepen.io/Zodiase/pen/07c143d67eaf3a5e8a2c9ae87ef470de
I'm not using Grommet in there but I reproduced pretty much the same DOM structure as if I were using `Layer`. The `#left-layer` element is the root of the `Layer`.
The trick I'm using to confine the layer to the vertical size of the red area is by creating a stacking context on `#left-layer-container` with `transform: translate(0)`. Ideally I don't want to use hacks like this.

**Comment by IanKBovard** [comment]
Quick question, is this what you want the sidebar and drop section to function like?

![Kapture 2020-09-25 at 10 39 29](https://user-images.githubusercontent.com/21990914/94287045-7035df00-ff1b-11ea-8326-24fc8c404c32.gif)

Sidebar is test/test2 and the drop section has 'nothing in folder' in it?

**Comment by Zodiase** [comment]
@IanKBovard yes in terms of size correlations. In my case the drop section is toggled on/off and hovers above something else, while the sidebar is only a small portion of the page, meaning there may be other views surrounding the sidebar. For example, A is the "sidebar", B is the drop that conditionally opens and hovers above some of C, C is content around A:
```
CCCCC     CCCCC
CCACC  >  CCABC
CCACC  >  CCABC
CCACC  >  CCABC
CCCCC     CCCCC
```

**Comment by IanKBovard** [comment]
@Zodiase working on something now, but i have a few more quick questions. Do you want users to be able to interact with the page beneath the drop when its open(scroll, clicks, ...)? is the drop section over the content or does it push the content aside? 

I'm still not sure if drop is the correct component for this. One main reason being it changes position based on scroll, and might create issues with the ui. 

conditionally rendering views might be the best choice, since you can rely on your layout to restrict the height.

**Comment by Zodiase** [comment]
@IanKBovard 

> Do you want users to be able to interact with the page beneath the drop when its open(scroll, clicks, ...)?

I don't really mind either ways. I see there is already an `onClickOutside` prop which I assume can be used to intercept clicks. I don't mind scrolls as much.

> is the drop section over the content or does it push the content aside?

It is over the content, just like how `Drop` currently is if it's `align: {top: 'bottom', left: 'left'}, stretch: true`. Except in my case it would have `align: {top: 'top', left: 'right'}, stretch: 'vertical'`.

```
CCCCD     CCCCD
CCACD  >  CCABD
CCACD  >  CCABD
CCACD  >  CCABD
CCCCD     CCCCD
```

> One main reason being it changes position based on scroll, and might create issues with the ui.

That sounds like it is currently the case with `Drop`, be it a problem or not. I don't mind that behavior as long as it's stable.

If the drop opener is scrolling with the content, the `Drop` should stay with it.
If the drop opener is fixed to the viewport (either through fixed positioning or simply because it's parent is fixed to the viewport), the `Drop` should still stay with it.

> since you can rely on your layout to restrict the height.

What I'm building is a component that adaptively fills the height of the container (see the red section of my repro) just like a div adaptively fills the width of the container, so in its nature it shouldn't be aware of its height. And the magenta layer hovering above surrounding content is part of the component and should match the height of the component (the red section).

Imagine you are building a vertical side menu bar and it's vertically filling all available space, excluding perhaps the header and footer. When the menu opens, I want the drop to fill all available vertical space but not exceed the vertical bounds of the menu bar.

**Comment by Zodiase** [comment]
I've updated my demo with more details: https://codepen.io/Zodiase/pen/07c143d67eaf3a5e8a2c9ae87ef470de

![image](https://user-images.githubusercontent.com/1815174/94629394-81fae780-0277-11eb-98eb-a80d0b710f68.png)

**Comment by Zodiase** [comment]
Another demo where the red section is not relative to the viewport: https://codepen.io/Zodiase/pen/b727dfd550fa836936e460cd0e850803

![image](https://user-images.githubusercontent.com/1815174/94629659-4a406f80-0278-11eb-8f58-a67a7066ca7d.png)

**Comment by IanKBovard** [comment]
Gotcha, thanks for that. Not sure if this is the best solution, but I do believe this is better than using drop. You'll just need to manage the responsive behavior of layer at certain widths.

https://codesandbox.io/s/amazing-cartwright-8lw1l?file=/src/App.js

**Comment by Zodiase** [comment]
@IanKBovard thanks for the demo. I see that in your demo, you are positioning the layer in relation to the content it's going to cover. I don't think that's applicable for my case. The expandable (magenta) section belongs to the side bar component (red section), and it shouldn't be aware of what's outside. Otherwise its interface would have to be something like this:

```
<SideBarWithExpandablePanel
    expandablePanelShouldAlignWith={someViewRef}
/>
```

This creates a coupling between the sidebar and what may be next to it.

Also consider this case (I've updated my second demo slightly):

![image](https://user-images.githubusercontent.com/1815174/94727752-09963400-0314-11eb-932b-d98bef998390.png)

What I'm trying to illustrate here is that the sidebar and its expandable panel shouldn't be aware of what's outside, so it's unreasonable to instruct it to position the expandable panel based on something that's outside of the sidebar.

**Comment by Zodiase** [comment]
Or let me put it this way: currently `stretch` in `Drop` helps implement `Menu`, which is has an expandable view that's "attached" to the button in a vertical way (anchored at left side, top side and right side, and growing downwards). And what I'm suggesting in this ticket is simply a need to attach the expandable view horizontally (e.g. anchored at bottom side, left side and top side, and growing rightwards).

**Comment by IanKBovard** [comment]
@Zodiase I understand what you're asking, sorry if I didn't make that clear. I still think layer is the best use for this situation. I've updated my sandbox to allow the layer to overflow past its ref container.

https://codesandbox.io/s/amazing-cartwright-8lw1l?file=/src/App.js

**Comment by jcfilben** [comment]
Hi @Zodiase just checking in to see if Ian's solution fits your needs. If so I think we should be able to close this issue

**Comment by ShimiSun** [comment]
I'll be closing this issue, feel free to reopen if still relevant.
