### ISSUE TITLE
[TS] Missing type for `containerTarget` in GrommetProps

### ISSUE THREAD

**Issue by Zodiase** [grommet/grommet#4545]
### Expected Behavior

```
<Grommet containerTarget={foobar} />
```

`containerTarget` should be part of `GrommetProps`.

### Actual Behavior

```
Property 'containerTarget' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<GrommetProps & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement>, any, any>> & Readonly<...> & Readonly<...>'.ts(2322)
```

### URL, screen shot, or Codepen exhibiting the issue

See https://github.com/grommet/grommet/blob/3fe225ef178b3446153cca8a4ca0b0aebc1f5679/src/js/components/Grommet/index.d.ts#L5-L14

**Comment by ShimiSun** [comment]
Looks like you are on your way to solving it, in the spirit of Hacktoberfest feel like making a contribution?
