### ISSUE TITLE
Breadcrumb widget needed

### ISSUE THREAD

**Issue by HeidiTosi** [grommet/grommet#455]
A breadcrumb widget appears in the sticker sheet. We would like to use this widget in our app, but one does not appear in the current set of widgets.

**Comment by alansouzati** [comment]
Thanks for reporting this. We currently don't have a Breadcrumb in the develop side of things.

PR gladly welcome.

**Comment by HeidiTosi** [comment]
I realize you do not have a Breadcrumb in the develop side of things and I'm not quite sure I understand what "PR gladly welcome" means. 

Is it possible for your team to supply us with a coded version of the Breadcrumb widget? And if so, what would the time frame for it to be available for us to use?

**Comment by alansouzati** [comment]
I'm sorry for using terms without explaining them first.

PR stands for Pull Request. It is the Github term for sending contributions over. As we don't have the implementation of this component in our upcoming tasks we are counting on the community support to implement this component. You or anyone in need for this component can go ahead and try it out. It should not be difficult to get it done.

There is a video that explains how to contribute to Grommet: https://vimeo.com/129681048.

Also you can see our backlog of items here: https://waffle.io/grommet/grommet.

That's the beauty of open source. If you or anyone needs a feature/component in a given timeframe, then it is a great candidate for a Pull Request. Our team can help to review your code if needed.

**Comment by tracybarmore** [comment]
Closing issue. Not pursing breadcrumbs as an individual component. Feel free to reach out to the grommet team for further discussion.
