### ISSUE TITLE
npm err 401 unauthorized

### ISSUE THREAD

**Issue by Chenchaiah23** [grommet/grommet#4553]
I am upgrading from grommet v1 to v2 by specifying grommet version 2.15.0 in package.json file and getting below error while build 
npm ERR! 401 Unauthorized: grommet-icons@https://github.com/grommet/grommet-icons/tarball/stable
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-28T07_01_57_948Z-debug.log

Please suggest some solution for this issue
I am using HPE private npm repo
Is there any specific way to access the grommet-icons?
### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
This issue was fixed part in #4555. Try to use [grommet stable](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) until we'll officially release 2.15.1.

**Comment by jcfilben** [comment]
Hi @Chenchaiah just checking in and seeing if you are still experiencing this issue after upgrading to the latest version. If not we should be able to close this issue

**Comment by ShimiSun** [comment]
The problem should no longer reproduce with the latest upgrade, thanks for reporting!!
