### ISSUE TITLE
themeMode with custom theme

### ISSUE THREAD

**Issue by brampurnot** [grommet/grommet#4557]
Hi!

I'm trying to use a different color for the arrow icon when the themeMode is set. When the themeMode is set to dark, I want to have a white icon; when it is set to light, I want to have black icon. 

Here is the code I have but it doesn't seem to be working correctly; the background changes nicely between white and black but the arrow icon always remains white.

Any help is appreciated since I'm struggling a bit to understand how this works. 

Bram

Here is the piece of code I'm using: 

```javascript
//This is the theme where I make a distinction between dark and light in the control. 
const theme = deepMerge(grommet, 
  {
    global: { 
      colors: {
        brand: '#26547C',
        focus: 'transparent', // added focus color,
        control: {
          dark: "#ffffff",
          light: "#000000"
        }
      }
    },
    formField: {
      label: {
        size: 'small'
      }
    }
  });

//Here is where I embed the menu inside of a Grommet component
   <Grommet full={true} theme={theme} themeMode="dark">
      <Menu label={title.pageTitle || 'Page Title Placeholder'} items={[{ label: 'logout' }]} />
    </Grommet>

**Comment by jcfilben** [comment]
<img width="159" alt="Screen Shot 2020-09-30 at 11 48 25 AM" src="https://user-images.githubusercontent.com/54560994/94721282-e28b3280-0312-11eb-91a1-80c21476563c.png">
<img width="150" alt="Screen Shot 2020-09-30 at 11 51 22 AM" src="https://user-images.githubusercontent.com/54560994/94721547-46adf680-0313-11eb-9849-ef58ff39c516.png">

I just tested and it appears to be working correctly, here is a codesandbox showing it working:
https://codesandbox.io/s/grommet-v2-template-forked-lyxr3?file=/index.js

**Comment by brampurnot** [comment]
Thanks for the quick response. In the codesandbox it is indeed working but unfortunately the structure of my app is a bit different. 

Here is an example of the structure of my app:
https://codesandbox.io/s/jovial-rosalind-l0s38?file=/src/theme.js

Bram

**Comment by jcfilben** [comment]
In your example the icon is appearing as white because the Header has a darkblue background so a black icon wouldn't have enough contrast with the background. If you remove the background color it will work as expected

**Comment by halocline** [comment]
To expand on @jcfilben's explanation...

Whether the light or dark color value is chosen based of the background of the containing element (not necessarily the value specified in `themeMode`).  In your case for `control`, I think of it as "when I have a `control` presented on a light background, use `control.light`; when I have a `control` on a dark background, use `control.dark`."

Grommet is not looking at themeMode="dark" and then always choosing the dark values.

Instead, in effect, Grommet is analyzing the color of your AppBar, determining that the AppBar's shade of blue is dark, and then choosing to serve up the control.dark value. When the body background color changes behind the AppBar, the AppBar color does not change, therefor the control remains unchanged.

**Comment by brampurnot** [comment]
Woow awesome information and thank you for the quick reply. Now it makes more sense. 

Bram

**Comment by brampurnot** [comment]
Thanks all for this amazing framework!
