### ISSUE TITLE
Rings disappear when meter total count equals zero.

### ISSUE THREAD

**Issue by HeidiTosi** [grommet/grommet#456]
We are using the Meter: Circle, Series, Legend widget in our app. When the total count=1 for at least one item, all of the rings/dials appear regardless of count. When the total count=zero, all of the rings/dials disappear. We would like the rings/dials to remain in the display.

**Comment by HeidiTosi** [comment]
I have not heard from the Grommet team on this bug. Please let me know if it will be possible to fix.

I have added 3 attachments showing current and expected behavior.
![currentmeter_circle_1count](https://cloud.githubusercontent.com/assets/17186165/14146821/0e413ebe-f667-11e5-98b8-7ab2e0bb2b4b.png)
![currentmeter_circle_zerocount](https://cloud.githubusercontent.com/assets/17186165/14146832/192a0824-f667-11e5-82a8-63bf04f995ec.png)
![expectedmeter_circle_zerocount](https://cloud.githubusercontent.com/assets/17186165/14147025/d9c376ba-f667-11e5-893b-c0d56935b86a.png)

**Comment by ericsoderberghp** [comment]
Fixed in 82b022cb0723ac631809dd3a7a891524b241aaa2.
