### ISSUE TITLE
How to use the `step` prop in DataTable?

### ISSUE THREAD

**Issue by carolina-cascade** [grommet/grommet#4565]
### Expected Behavior

According to the docs, `step`  is "How many items to render at a time."  I understand this to control the number of rows displayed per page by DataTable.

### Actual Behavior

The number of items displayed bears no relationship to the number in `step`.

### URL, screen shot, or Codepen exhibiting the issue

I copied the sandbox example, adding the `step` prop, into https://codesandbox.io/s/dark-haze-wzn76?file=/src/App.js The DATA array has 6 elements:

<img width="640" alt="Screen Shot 2020-10-02 at 13 42 34" src="https://user-images.githubusercontent.com/51412052/94953260-3a619f00-04b5-11eb-92ee-73d67deeccd8.png">

<img width="581" alt="Screen Shot 2020-10-02 at 13 44 21" src="https://user-images.githubusercontent.com/51412052/94953357-6aa93d80-04b5-11eb-9b41-6b23f649096a.png">

### Steps to Reproduce

1. Create a basic DataTable component and a static array of data 
2. Set `step` as an int
3. Get any number of rows

### Your Environment

- Grommet version: 2.15.0
- Browser Name and version: Chrome 83.0.4103.97 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): macOS 10.15.6 Catalina

**Comment by ShimiSun** [comment]
If `data` already has all the items in advance then the `step` wouldn't apply I believe. @IanKBovard can you please take a look at this issue?

**Comment by carolina-cascade** [comment]
Yes, my data does have all items in advance.

**Comment by IanKBovard** [comment]
Step determines how many items are rendered at a time before the scroll bar reaches the end of the page, and more items are rendered. Step is used with a large number of items, and prevents them from all being rendered at once. Your example is not a good representation on how to use step, since your dataset is small.

Here is an example of step working. This is using infiniteScroll, which dataTable uses.
Large item set with a step of 50
https://storybook.grommet.io/?path=/story/infinitescroll--simple

> According to the docs, step is "How many items to render at a time." I understand this to control the number of rows displayed per page by DataTable.

I'm not sure what you mean by displayed per page, but I think this understanding is causing you some confusion.

**Comment by carolina-cascade** [comment]
>  I'm not sure what you mean by displayed per page, but I think this understanding is causing you some confusion.

Simply a paginated table, like this one from another library.

<img width="644" alt="Screen Shot 2020-10-02 at 16 15 55" src="https://user-images.githubusercontent.com/51412052/94966105-af8b9f00-04ca-11eb-824d-4d01b15b6a75.png">

Thank you for your help!

**Comment by IanKBovard** [comment]
I gotcha. That's not what step is for. I don't think dataTable handles pagination like that on its own. If you check out the infiniteScroll example that should give you a better idea of step.

If you have all your data in advance, I would just add some logic on next page click and pass in only specific datasets to datatable.
e.g
page one <DataTable data={items 1 - 50}
click next page
page two <DataTable data={items 51 - 100}
...

**Comment by carolina-cascade** [comment]
Yeah, that could work. I am implementing a table inside a modal (crazy, but those are my specs), so InfiniteScroll will not work. But I can paginate manually.

Thank you again for your super quick response.

**Comment by IanKBovard** [comment]
@carolina-cascade No problem, happy to help. Let me know if we can close this issue.

**Comment by carolina-cascade** [comment]
Yes, please close it. I got my answer.
