### ISSUE TITLE
Grommet Themer share functions does not work

### ISSUE THREAD

**Issue by smiciulis** [grommet/grommet#4575]
### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/68843910/95133629-82a0eb80-0759-11eb-9539-3a25799bc65e.png)

### Steps to Reproduce

1. Open up Share pup-up
2. Punch in the details
3. Hit Publish

### Your Environment

- Grommet version: N/A
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Win 10 Desktop

**Comment by jcfilben** [comment]
Yes, there is an open issue for this here: https://github.com/grommet/grommet-theme-designer/issues/9

**Comment by smiciulis** [comment]
Thanks, I've subscribed on the other issue.
