### ISSUE TITLE
Empty span tag in Layer causes layout changes despite it's not being displayed

### ISSUE THREAD

**Issue by eabay** [grommet/grommet#458]
If Layer is mounted in Header component for example, It reserves some space with empty span tag and causes rearrangements in flex layout.

![untitled](https://cloud.githubusercontent.com/assets/158772/13907605/93186be0-eefa-11e5-8913-f5cea3745e94.gif)

`display: none` solves the problem but I don't know if this should be the way to do that.

**Comment by eabay** [comment]
Do yo guys agree with the quick fix?

**Comment by alansouzati** [comment]
I've just tested it, I agree with adding `display: none`. Do you want me to go ahead and implement this, or are you going to send a PR ?
