### ISSUE TITLE
the page's focus changes at the moment a Layer is closed

### ISSUE THREAD

**Issue by cacheHit001** [grommet/grommet#4587]
```javascript
const page = () => {
  const [open, setOpen] = useState(false);
  useEffect(() => {
    if (open) {
      setTimeout(() => {
        setOpen(false);
      }, 3000);
    }
  }, [open]);
  return (
    <Grommet plain full>
      {open && (
        <Layer plain responsive={false} modal={false}>
          <Box width="100px" height="100px" background="green" />
        </Layer>
      )}
      <Box gap="10px" width="500px">
        <TextInput
          onBlur={() => {
            setOpen(true);
          }}
        />
        <TextInput />
      </Box>
    </Grommet>
  );
};
```
As shown in the code, there are two TextInputs and a Layer on my page. I let the Layer  appear when the onBlur of the first TextInput  is triggered and it will be closed after 3 seconds. 

### Expected Behavior

At first, I click the first TextInput. Then I click the second one. Due to the onBlur, the Layer will be visible for 3 seconds. After that, I immediately click the first TextInput before the Layer disappear. It is expected that nothing will happen when the Layer turns into invisible  .

### Actual Behavior
The focus goes to the second TextInput at the momont the Layer is closed.

### Steps to Reproduce

1. click the first TextInput 
2. click the second TextInput 
3. click the first TextInput before the Layer is closed
4. wait for the Layer is closed
5. the focus will go to the second TextInput when the Layer is closed

### Your Environment

- Grommet version:2.14.0
- Browser Name and version: chrome 85.0.4183.121/Microsoft Edge 44.18362.449.0
- Operating System and version (desktop or mobile): windows 10

**Comment by leossantiago** [comment]
Looks like the problem is related to your code logic.

Layer has a prop called `originalFocusedElement`. It's used to restore focus on the element focused before Layer is set.

Your logic is set to happen when TextInput is not focused anymore. So, when Layer is triggered, the first input will never be the `originalFocusedElement`. If you click on the page and then click in an focusable element, there will be no `originalFocusedElement`, so the last focus will be maintened. But in the current conditions, your actual behavior will happen with any focusable element.

In the example below, your logic is also triggered when passing the mouse over the button. It won't be a focus-changing action, and you'll be able to see what I explained above.

```
const [open, setOpen] = useState(false);
  useEffect(() => {
    if (open) {
      setTimeout(() => {
        setOpen(false);
      }, 3000);
    }
  }, [open]);
  return (
    <Grommet plain full>
      {open && (
        <Layer plain responsive={false} modal={false}>
          <Box width="100px" height="100px" background="green" />
        </Layer>
      )}
      <Box gap="10px" width="500px">
        <TextInput
          onBlur={() => {
            setOpen(true);
          }}
        />
        <TextInput color="blue" />
        <Button label="Trigger Layer" onMouseOver={() => setOpen(true)} />
      </Box>
    </Grommet>
  );
```

**Comment by cacheHit001** [comment]
> Looks like the problem is related to your code logic.
> 
> Layer has a prop called `originalFocusedElement`. It's used to restore focus on the element focused before Layer is set.
> 
> Your logic is set to happen when TextInput is not focused anymore. So, when Layer is triggered, the first input will never be the `originalFocusedElement`. If you click on the page and then click in an focusable element, there will be no `originalFocusedElement`, so the last focus will be maintened. But in the current conditions, your actual behavior will happen with any focusable element.
> 
> In the example below, your logic is also triggered when passing the mouse over the button. It won't be a focus-changing action, and you'll be able to see what I explained above.
> 
> ```
> const [open, setOpen] = useState(false);
>   useEffect(() => {
>     if (open) {
>       setTimeout(() => {
>         setOpen(false);
>       }, 3000);
>     }
>   }, [open]);
>   return (
>     <Grommet plain full>
>       {open && (
>         <Layer plain responsive={false} modal={false}>
>           <Box width="100px" height="100px" background="green" />
>         </Layer>
>       )}
>       <Box gap="10px" width="500px">
>         <TextInput
>           onBlur={() => {
>             setOpen(true);
>           }}
>         />
>         <TextInput />
>         <Button label="Trigger Layer" onMouseOver={() => setOpen(true)} />
>       </Box>
>     </Grommet>
>   );
> ```

Thanks for your detailed explanation.  I still have one question: Could I set the prop called originalFocusedElement?

**Comment by IanKBovard** [comment]
@cacheHit001 What is your goal with this implementation of layer? Not sure I see the usecase for this.

**Comment by leossantiago** [comment]
@cacheHit001 No, you can't. Passing anything as this prop wouldn't change a thing, as `originalFocusedElement` is handled inside Layer code using `setOriginalFocusedElement(document.activeElement)`. As you can see, it comes directly from `document`.

Also, I agree with @IanKBovard . I don't think that would be nice to have without a usecase for this.

**Comment by cacheHit001** [comment]
@leossantiago @IanKBovard 

Sorry, that is just an abstract demo of my code. Here is my usecase. There are some TextInputs on my page and the users will fill them. I hope to check whether the content is legal, for example a user name must has both number and letter, when the focus leaves every TextInput. If the content is illegal, a layer with some notification will occur.

According to my code logic, if a user types something illegal into the first TextInput and clicks the second TextInput,  the layer will occur. Then he clicks back to the first TextInput, however the focus will transfer to the second TextInput when the layer disappears which may interrupt the user's typing.

**Comment by IanKBovard** [comment]
I gotcha. While layer can be used as a notification toast, this implementation seems really off to me. It looks like, to me, layer is working correctly. 

> According to my code logic, if a user types something illegal into the first TextInput and clicks the second TextInput, the layer will occur. Then he clicks back to the first TextInput before the layer disappears, however the focus will transfer to the second TextInput when the layer disappears which may interrupt the user's typing.

The originalFocusedElement when the layer opens is the second input, when the layer closes it should snap back to that. A notification toast for errors on a form seems like poor user experience to me. What if i miss the error message? I won't know my issue until I click to and from the first input again. What if i rely on screenreaders, i'll might never know of any errors. For error handling, I would use grommets internal api or conditionally rendered text.

I'm not sure if this issue requires a pr, because this sounds like layer is doing what it's supposed to.

**Comment by leossantiago** [comment]
> I'm not sure if this issue requires a pr, because this sounds like layer is doing what it's supposed to.

Agreed. 

Unless you really need a Layer to this, I could make a couple suggestions alongside @IanKBovard ones.

You could call a validation function in onChange, or even in onBlur. As suggested by Ian, a conditionally rendered text would be really helpful in those situations.
Also, if you're using forms, FormField receives a prop called `validade`.  

`Validation rule when used within a grommet Form. Provide an object with a regular expression, a function, or an array of these. If a function is provided, it will be called with two arguments, the value for this field and the entire value object. This permits validation to encompass multiple fields. The function should return a string message describing the validation issue, if any, or an object with 'message' and 'status' properties.`

It might be worth checking out :smile:

**Comment by cacheHit001** [comment]
@IanKBovard  @leossantiago Thanks for your detailed explanation to my problem, now I know that the layer is working correctly and the better way to implement the error notification. You really helped me a lot!!
