### ISSUE TITLE
Add caret/arrow on tooltip

### ISSUE THREAD

**Issue by padmacnu** [grommet/grommet#4588]
Dynamically change position of tooltip arrow based on position on content.
![image](https://user-images.githubusercontent.com/6428437/95487230-e76e6880-0948-11eb-9712-f6a4ca53d563.png)

Current:
![image](https://user-images.githubusercontent.com/6428437/95487265-f5bc8480-0948-11eb-82bb-61cd00f2f981.png)

**Comment by ShimiSun** [comment]
Can you please add the full description of the issue?
I’m not sure I understand the expected behavior. We currently don’t have a tooltip component, so how do you think the behavior should work?

**Comment by IanKBovard** [comment]
@ShimiSun is correct, there is no tooltip component in grommet. This is an example of using drop to replicate a tooltip. As it stands, it's up to the user to design the tooltip box. For me, I would prefer to styled the box myself using CSS, is this something we want to eventually implement?

**Comment by padmacnu** [comment]
@ShimiSun I am talking about Drop component, we use it in CURO as tooltip component. Could you please confirm if you're planning to implement it in Grommet? Else we can try to style it our self.

**Comment by ShimiSun** [comment]
I'm currently working on #4599, and I'm not sure how smoothly it will operate with a caret as we are not planning to provide the caret behavior out of the box in grommet. I'll keep you posted on how it goes early next week.

**Comment by ShimiSun** [comment]
@padmacnu, it is still under review, but it is very close 😃  
https://deploy-preview-4613--sad-tereshkova-173d07.netlify.app/?path=/story/tip--caret 
Let me know what you think. Mike supposed to schedule us a call.

**Comment by ShimiSun** [comment]
The solution for the Caret is now demonstrated in our storybook. Best of luck! https://storybook.grommet.io/?path=/story/visualizations-tip--caret
