### ISSUE TITLE
Input type range slider widget dissapear

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#459]
After chrome update to Version 49.0.2623.87
widget to move - change the input value disappeared. Problem is also visible in documentation example.
http://www.grommet.io/docs/develop/form

**Comment by jwijay** [comment]
PR pending: https://github.com/grommet/grommet/pull/461

**Comment by jwijay** [comment]
Resolved by PR https://github.com/grommet/grommet/pull/461
