### ISSUE TITLE
Add `fill` prop to Heading

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#4593]
### Expected Behavior
Heading should be able to fill the container space as an alternative to being a constraint to `max-width`, using a `fill` prop. Similarly to how Paragraph works with fill.

### Actual Behavior
No `fill` option.

Thread from slack https://grommet.slack.com/archives/C09QQEG69/p1602251094055800

### Your Environment

- Grommet version: 2.15.2
- Browser Name and version: any
- Operating System and version (desktop or mobile): any

**Comment by leossantiago** [comment]
Hey, Shimi!
Looks like only people with @hpe.com emails can get access to the linked thread  :)

**Comment by ShimiSun** [comment]
@leossantiago you are quick! 💟
