### ISSUE TITLE
Text and icon scaling in a Select are not proportional

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet#4594]
The text and icon in a select do not scale proportionately.  Here's an example of the four different scales available.  They get uglier as they get larger:
![image](https://user-images.githubusercontent.com/17883783/95610867-3cc87980-0a1e-11eb-8772-cd26e90c72e8.png)

**Comment by ShimiSun** [comment]
According to the styling of the attached screen shot, the issue will be better placed under the hpe-design-system repo, as the styles are driven from the HPE theme. I'll be closing this issue and file it on the theme repo.
