### ISSUE TITLE
Responsive Split causes re-render  & re-fetch of data

### ISSUE THREAD

**Issue by linde12** [grommet/grommet#460]
Hello!

I've encountered a problem using `Split`.

Wrapping a component, `<C1 />`, inside a `<Split onResponsive={this._onResponsive.bind(this);}></Split>` causes `C1` to unmount and then remount(causing me to fetch data two times in `componentWillMount`) since `_onResponsive` updates the responsive-state & if the menu should be shown or not.

Do you have any solution on how to do this without re-fetching data? I want the responsive menu, but i'd like to avoid fetching more data.

I think this is more of a general React-problem rather than Grommet but i'm wondering if anyone has encountered the issue and how you solved it? I'm thinking of fetching data when a react-router route is changed, but that's not optimal IMO.

I followed [the docs-example](https://github.com/grommet/grommet-docs/blob/master/src/DocsSplit.js) but the DocsSplit doesn't fetch data so it'll only cause a re-render.

**Comment by linde12** [comment]
For clarification i made a [fiddle](https://jsfiddle.net/1kph3mLv/1/) of the problem. The problem is the same i have when i use Grommet.

Open the console and toggle the button and you'll see that the children get's unmounted and mounted every toggle instead of just being re-rendered or "moved"

**Comment by alansouzati** [comment]
Have you considered using a Flux architecture for your data fetching layer?

There are handful options that implements that, Grommet as of this moment is using Redux: http://redux.js.org/index.html

There are few open-source source apps done on top of Grommet using Redux. Take a look at http://ferret.grommet.io.

Source code is available here: https://github.com/grommet/grommet-ferret

**Comment by eabay** [comment]
Another problematic use case is when you use a statedul form and resize the
window, boom, form is reset and changes are gone. I switched to use Layer
after facing the same problem.

**Comment by alansouzati** [comment]
I see, you can keep your form data in your React state for your given component. You still face the same issue when you keep your form data in a state?

**Comment by alansouzati** [comment]
Actually this is an interesting issue... 

https://jsfiddle.net/alansouzati/1kph3mLv/2/

I did a change by moving the sub up on level, but I guess this is not the real fix for the problem

**Comment by eabay** [comment]
It's OK if you store data in a redux state, data will be kept between mount/unmount cycle. But it wasn't desirable in our case to sync temporary data in a central store just to prevent this to happen. We preferred to use Layer and give the control to the user to lose filled data by closing it rather than losing it by chance just because of a resize.

Anyway, I just wanted to point it out while speaking the issue.

**Comment by alansouzati** [comment]
yeah yeah, thanks for chiming in.

**Comment by alansouzati** [comment]
good news I think i fixed the issue, it was just a matter of removing props.children from within the if clause.

https://jsfiddle.net/alansouzati/1kph3mLv/3/

Would any of you be kind enough to submit a PR to fix that in Grommet :smile: 

@linde12 up to your first PR?

**Comment by linde12** [comment]
@alansouzati 
@eabay 

Sorry for getting back to you so late. Damned timezones.

Anyway, the problem is as @eabay describes it. Since the props are conditionally rendered they seem to always be remounted.

If you look at the `DocSplit` of the grommet-docs repo [here](https://github.com/grommet/grommet-docs/blob/master/src/DocsSplit.js#L151-L154) you are using it the same way as i did(as i had a look at the source :-)):
* When the window is small(responsive=single) the `left` variable is the content(`_.renderDoc()`). If showMenu is true then `left` variable is instead the menu. In both cases the `right` variable is undefined since we only want one column.
* When the window is big(responsive=multiple) the `left` variable is always the Menu and the `right` variable is always the content/doc.

So unfortunately i think we will always need the if around `this.props.children` to determine whether we're in single-mode and are showing the menu or not.

As of now i'm using Redux so apart from the extra API calls, right now, the user doesn't notice anything on the page except maybe some possible updates. However when i start adding forms etc. they'll be reset, like @eabay said, when the window resizes unless i store them in the redux store.

Wish i had a working solution to share! If i find something interesting i'll make sure to post it.

**Comment by linde12** [comment]
@alansouzati Oh and the DocSplit component had the same problem as described above, so unfortunately the fix to the fiddle won't fix the problem else i'd be happy to contribute. As it looks now the `{this.props.children}` have to be wrapped in a if-statement. :(

**Comment by linde12** [comment]
Looking at the `Split` component [over here](https://github.com/grommet/grommet/blob/master/src/js/components/Split.js#L103-L117) we can see that it's always conditional and will be remounted every time. I updated your fiddle to mirror the conditions in the render method of `Split`. See [here](https://jsfiddle.net/1kph3mLv/5/)

**Comment by linde12** [comment]
I think i've got a fix for this coming up tomorrow hopefully. It involves some CSS and isn't perfect but it works. If we didn't have to take `priority` into account it'd be an easy fix but now i have to hide elements.

I'll get back to you tomorrow!

**Comment by linde12** [comment]
My fix wraps the elements that shouldn't be visible in a div with a css display property set to none. Works perfectly for me. No more remounting. And when in `responsive=single` mode i pop a `Layer` to show the menu.

I'm not sure if we want to merge this "fix" or not since it changes the behavior of `Split` to not remount.

What do you think @alansouzati?

**Comment by linde12** [comment]
@alansouzati Can you have a look at [this merge](https://github.com/linde12/grommet/pull/1/commits/3298bbb3e2c1528f47ccd8a4f6516850684661c6) when you have time?

It solves the problem of the components remounting(thus refetching data, resetting state etc.) but introduces another problem when `Split` is used with **3 or more** children.

The flex breaks since the children are wrapped in two separate `div` elements in order to hide/show them at the correct width.

I just thought that maybe you'd have some better way of solving this after seeing the merge? Or if you've got some css-magic to make the flex work anyway?
