### ISSUE TITLE
Box background property doesn't work properly with linear-gradient that has RGBA values

### ISSUE THREAD

**Issue by oskari** [grommet/grommet#4608]
### Expected Behavior

Form correct css style for Box component background when using linear-gradient that has rgba values as stops.

### Actual Behavior

Box component ends up using the linear gradient in `background-color` css property.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-background-linear-gradient-rgba-u3oi7

### Your Environment

Dependencies as listed by codesandbox: 
Package | Version
-|-
Grommet | ^2.12.0 (2.15.1)
grommet-icons | ^4.4.0 (4.5.0)
react | ^16.6.1 (16.13.1)
react-dom | ^16.6.1 (16.13.1)
styled-components | 5.0.1 
- Grommet version: 2.15.1
- Browser Name and version: FF Dev 82.0b
- Operating System and version (desktop or mobile): MacOS Catalina

**Comment by ShimiSun** [comment]
Thank you for reporting, issue is fixed and available on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) and will be available officially on the next release.
