### ISSUE TITLE
Pagination component API ideation

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet#4617]
Pagination component that can also integrate with other components (ex: table, list) 
Design thinking: https://docs.google.com/document/d/1rBlrQPNiV9Mvl9mjea3rWb4xq5tVshWECi0AWGYpOvk/edit
https://www.figma.com/file/slRqNvhJub0QlgN46zSXoY/HPE-Pagination-Component?node-id=1%3A9

Construct a variety of code examples of how this could be done. For instance,
- embedded within DataTable/List or as a separate component
- just the "< 1 2 3 4 >" stuff or also including the count summary

We don't need to implement pagination, just explore what API surface we should target.

**Comment by halocline** [comment]
In progress draft of potential functionality: https://docs.google.com/document/d/1rBlrQPNiV9Mvl9mjea3rWb4xq5tVshWECi0AWGYpOvk/edit#heading=h.lg9p3h5pqpgw

**Comment by ShimiSun** [comment]
Thanks @taysea @halocline! Feel free to share the API for the component with the community to start a NEW component discussions

**Comment by halocline** [comment]
> Thanks @taysea @halocline! Feel free to share the API for the component with the community to start a NEW component discussions

https://github.com/grommet/grommet/pull/4646

**Comment by ShimiSun** [comment]
Let's track the pagination effort under #4647 or on a design-system issue. Feel free to link between relevant issues.
