### ISSUE TITLE
DataTable 'background' color doesn't apply to the column of checkboxes when 'select' is enabled

### ISSUE THREAD

**Issue by RetroJect** [grommet/grommet#4620]
Using the DataTable, and specifying the `select` parameter allows for checkboxes to appear as the left-most column of the table, but it is currently not possible to specify the color of the background for the section of the header the checkboxes appear in. The other sections of the DataTable can utilize the `background` property of the component through named properties as shown in the [documentation](https://v2.grommet.io/datatable#background), but for some reason the color name given to the component under the 'header' property of the object is not applied to this section (see below for example). Is this intentional, and if not, can it be added in?

> A side note: this also applies to the 'body' property of `background` as well

### Expected Behavior

Specifying the `background` property of the DataTable should apply the color to the checkbox in the header.

### Actual Behavior

The 'header' property of the supplied object is ignored for the checkbox in the header.

### URL, screen shot, or Codepen exhibiting the issue

Codesandbox to demo applying a header coloring: https://codesandbox.io/s/grommet-datatable-header-coloring-n3zxz?file=/index.js

### Steps to Reproduce

Create a DataTable and supply the `background` property with a color name for the `header` property. Also include the `select` propertiy for the checkboxes.

```js
<DataTable
  ...
  background={{ header: 'brand' }}
  select={[]}
  ...
/>
```

### Your Environment

- Grommet version: latest 2.15.2
- Browser Name and version: latest Chrome
- Operating System and version (desktop or mobile): Windows 10 Enterprise Desktop

**Comment by ericsoderberghp** [comment]
That behavior is not intentional. This is a good issue.

**Comment by leossantiago** [comment]
Hey guys! Just sent a PR addressing that issue. Even though it's a fix, there are a couple of things I'd like to open to discussion based on this issue.

1. select Cell in Header is rendered as a `td` element. Shouldn't it be a `th` as the other Cells in Header?
2. Right now, backgrounds can be set using `background` prop and setting each context inside of it, but only Header background can the set through themes. What's your opinion on allowing Body and Footer backgrounds to be set using themes aswell?
