### ISSUE TITLE
DataTable overflow in fixed sized tab

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [grommet/grommet#4624]
### Expected Behavior

DataTable should fit according to the size of the tab and display a scrollbar.

### Actual Behavior

DataTable overflow out of the tab and take full height, avoiding scrollbar.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-zmfgx?file=/index.js

### Steps to Reproduce

1. Just create a DataTable inside Tabs and fix the height of box containing the Tabs element (ex : 25vh).
2. If you remove the Tabs, DataTable take the correct 25vh size.

### Your Environment

- Grommet version: v2.15.1
- Browser Name and version: Firefox 81.0.2 (64 bits)
- Operating System and version (desktop or mobile): Desktop - Windows 10 1903 - 18362.1139

Yours faithfully,
LCDP

**Comment by jcfilben** [comment]
I made a code sandbox based off of the one you sent, showing the DataTable fitting within the Tab and the text being displayed beneath the Tab. : https://codesandbox.io/s/grommet-v2-template-forked-wz65v?file=/index.js
Let me know if that solves the issue

**Comment by LeComptoirDesPharmacies** [comment]
Hi @jcfilben,

Indeed, setting a fixed height on Box inside "<Tab>" will workaround this problem with the DataTable maximum height.
However, if there is X tabs, I need to create the fixed height Box in the X tabs and I would like to set the height once on "<Tabs>" parent element which is more natural.

Yours faithfully,
LCDP

**Comment by jcfilben** [comment]
If you set `overflow="scroll"` in the Box container the Tabs will be contained within the Box and you wont have to set the height for each individual Tab https://codesandbox.io/s/grommet-v2-template-forked-fkg35?file=/index.js

**Comment by ShimiSun** [comment]
I think @jcfilben is correct and since you are hardcoding the height you might want to account for the overflow and fix it as @jcfilben suggested. Let us know if that works for you, if not will be reopening the issue.
