### ISSUE TITLE
Mis-alignment of last box when wrapped into a single column

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#4631]
Wrapping Box children, causes last child to be mis-aligned when the page shrinks so they wrap into a single column.  Continuing to shrink the window causes the alignment to be corrected, (I think the correction occurs at the small breakpoint).

### Expected Behavior

Shrinking a page so that all wrapped children are in a single column, should leave all children properly aligned.

### Actual Behavior

The last child in a column appears to be mis-aligned.  Evidently, the previous children are center-aligned around the "child + gap".  The last child is center-aligned for the "child" only.  Because the previous children include the "gap", the alignment of the last child is out of place.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-box-wrap-alignment-t7y8d?file=/src/App.js

![image](https://user-images.githubusercontent.com/8231064/96525555-96526300-12be-11eb-8e10-da6eededb1fb.png)

### Steps to Reproduce

```
import React from "react";
import { Box, Card, Grommet, grommet, Heading, Paragraph } from "grommet";
import { hpe } from "grommet-theme-hpe";

const theme = hpe;
const cardWidth = "medium"; // medium or large (small cards do not wrap for some reason)
const cardHeight = "small"; // small, medium or large

export default function App() {
  return (
    <Grommet theme={theme}>
      <Heading>Wrap Alignment</Heading>
      <Paragraph margin="small">
        <b>Instructions</b>: Shrink window width until all three cards are in a
        column. Notice that the alignment of the last card is offset by the "gap
        width".
        <br />
        <br />
        <i>
          NOTE 1: This problem only shows up with "medium" and "large" cards.
          Small sized cards do not wrap for some reason.
        </i><br /><br />
        NOTE 2: Alignment is corrected as screen width reaches the small breakpoint.
      </Paragraph>
      {/* wrap allows one-card at a time to wrap to next row */}
      <Box align="center">
        <Box direction="row-responsive" gap="medium" justify="center" wrap>
          <Card
            border
            width={cardWidth}
            height={cardHeight}
            margin={{ bottom: "small" }} // for wrapped cards
          ></Card>
          <Card
            border
            width={cardWidth}
            height={cardHeight}
            margin={{ bottom: "small" }} // for wrapped cards
          />
          <Card
            border
            width={cardWidth}
            height={cardHeight}
            margin={{ bottom: "small" }} // for wrapped cards
          />
        </Box>
      </Box>
    </Grommet>
  );
}
```
### Your Environment

- Grommet version: v2.15.2 (tested with both grommet-theme-hpe and grommet)
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows

**Comment by ericsoderberghp** [comment]
This is a known behavior when combining `wrap` and `gap`. See the note here: https://v2.grommet.io/box#gap.
Typically, a better approach is to use Grid as it will maintain the appropriate gap.

**Comment by LiveFreeAndRoam** [comment]
Thanks Eric.  If I understand `Grid`, it requires fixed width columns.  In my case, the Card width flexes with its content.  So `Grid` would not be a suitable replacement for me here.

I guess I could probably figure out an algorithm to append the same gap to the last child, so then at least each row will consume the same width (child + gap).  Though, I'm probably not that desperate.

Not to worry, this is a minor annoyance.

**Comment by ericsoderberghp** [comment]
I see. In that case, you might consider not using `gap` on the container Box but instead using `margin` on the contained Cards.

**Comment by LiveFreeAndRoam** [comment]
Excellent, thank you Eric.  That fixed it.  _Mind the gap_ :smile:.

**Comment by ShimiSun** [comment]
Great energy on this thread 😄 

@LiveFreeAndRoam Are we good with closing this issue, or is there anything else we can help with?

**Comment by LiveFreeAndRoam** [comment]
Yes, this one can be closed.

Cheers,
Matt.
