### ISSUE TITLE
Icon inside Anchor doesnt change style (Active and hover)

### ISSUE THREAD

**Issue by rodmartinezmedina** [grommet/grommet#4637]
Please help.  
How can I target an icon on hover or active? 
I'm going crazy. I have an icon in a Grommet Anchor and nothing seems to work. 

[](https://stackoverflow.com/questions/64454214/cant-style-grommet-icon-inside-anchor)

### Expected Behavior

Icons should change the style on hover or active status of the Anchor.
Also for some reason, border is green when on focus even if i specified everywhere border:none;

### Actual Behavior
LAbel in the anchor changes on hover and active. But icon doesn't

CODE 
```
import React from "react";
import { Anchor, Box, Text } from "grommet";
import styled from "styled-components";
import { Currency as PayoutIcon, Menu as MenuIcon } from "grommet-icons";

const StyledAnchor = styled(Anchor)`
  display: flex;
  height: 56px;
  color: #808191;
  padding: px 20px;
  border-radius: 12px;
  background: transparent;
  width: max-content;

  text-decoration: none;
  font-family: Inter;
  color: #808191;
  padding: 0px 20px;
  background: transparent;
  transition: all 0.25s ease 0s;
  text-decoration: none;
  border: none;

  &:visited {
    text-decoration: none;
    border: none;
  }

  &:hover {
    color: #6c5dd3;
    text-decoration: none;
  }
  &:active {
    color: #fff;
    background: #6c5dd3;
    text-decoration: none;
    border: none;
  }

  &:focus {
    color: #fff;
    background: #6c5dd3;
    textdecoration: none;
    border: none;
  }

  .isActive {
  }
`;
const SidebarItem = () => {
  return (
    // <Box color="#808191" hoverIndicator="true">
    <StyledAnchor
      color="#808191"
      label="Payouts"
      onClick={() => {}}
      href="#"
      icon={<PayoutIcon />}
    />
    // </Box>
  );
};

export default SidebarItem;
```

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-icon-not-working-t0wt6?file=/index.js

### Your Environment
React (create-react-app)

- Grommet version:   "grommet": "^2.15.2",
- Browser Name and version: chrome latest 
- Operating System and version (desktop or mobile): Linux Mint

**Comment by IanKBovard** [comment]
You need to target the svg with your styles. The border you're seeing is a box-shadow. It's a focus indicator used for accessibility purposes, and is added to any clickable element.

https://codesandbox.io/s/grommet-icon-not-working-forked-v1mei?file=/index.js
