### ISSUE TITLE
cannot install grommet via NPM

### ISSUE THREAD

**Issue by geshenyi** [grommet/grommet#464]
**I am trying to install grommet via NPM but just failed with following error message.
I couldn't figure out what the problem is...**

npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN optional dep failed, continuing fsevents@1.0.9
npm WARN deprecated lodash@1.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN optional dep failed, continuing fsevents@1.0.9
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> spawn-sync@1.0.15 postinstall C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

> node-sass@3.4.2 install C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/win32-x64-46_binding.node":

tunneling socket could not be established, cause=write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.4.2 postinstall C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files (x86)\nodejs\node.exe C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\ssge\\AppData\\Roaming\\npm\\node_modules\\grommet\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.3.1
gyp info using node@4.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:63:19)
gyp verb `which` failed     at E (C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:72:29)
gyp verb `which` failed     at C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:81:16
gyp verb `which` failed     at C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 [Error: not found: python2]
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.10\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 4.4.0
gyp verb command install [ '4.4.0' ]
gyp verb install input version string "4.4.0"
gyp verb install installing version: 4.4.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 4.4.0
gyp verb build dir attempting to create "build" dir: C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\ssge\\AppData\\Roaming\\npm\\node_modules\\grommet\\node_modules\\node-sass\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ssge\\AppData\\Roaming\\npm\\node_modules\\grommet\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ssge\\AppData\\Roaming\\npm\\node_modules\\grommet\\node_modules\\node-sass\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ssge\\.node-gyp\\4.4.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ssge\\.node-gyp\\4.4.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\ssge\\AppData\\Roaming\\npm\\node_modules\\grommet\\node_modules\\node-sass\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\ssge\\AppData\\Roaming\\npm\\node_modules\\grommet\\node_modules\\node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\ssge\\AppData\\Roaming\\npm\\node_modules\\grommet\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\ssge\.node-gyp\4.4.0
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? null
gyp verb copying "node.lib" for x64 C:\Users\ssge\.node-gyp\4.4.0\Release\node.lib
gyp info spawn C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 2016/3/25 17:08:34.
Project "C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
The target "Midl" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\BuildCustomizations\masm.targets (28,5)" does not exist in the project, and will be ignored.
The target "CustomBuild" listed in an AfterTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\BuildCustomizations\masm.targets (29,5)" does not exist in the project, and will be ignored.
Project "C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\binding.sln" (1) is building "C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targ
ets).
Project "C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (defa
ult targets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platform for project 'libsass.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to build a project witho
ut a solution file, and have specified a non-default Platform that doesn't exist for this project. [C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\src\libsass.vcxproj]
Done Building Project "C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
(InvalidPlatformError target) -> 
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platform for project 'libsass.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to build a project wit
hout a solution file, and have specified a non-default Platform that doesn't exist for this project. [C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\build\src\libsass.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.13
gyp ERR! build error
gyp ERR! stack Error: `C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\ssge\\AppData\\Roaming\\npm\\node_modules\\grommet\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass
_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\ssge\AppData\Roaming\npm\node_modules\grommet\node_modules\node-sass
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grommet" "-g"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by alansouzati** [comment]
It seems you are ina proxied network. Do you have your proxy settings configured with NPM?

Alan

**Comment by geshenyi** [comment]
there is no proxy server...but i just installed it on my mac successfully...Can i just copy the grommet folder of node_modules to my win7 laptop and directly use it?

**Comment by genyded** [comment]
I wouldn't copy. Try running `npm update npm` on the Win box and try again (after deleting the current node_modules folder just to be sure). Also make sure the cmd window you are running in has `Adminstrator Command Prompt` in the title (right like and open it with Run as Administrator).

**Comment by bryanjacquot** [comment]
@geshenyi were you able to get your environment running on your windows laptop?

**Comment by bryanjacquot** [comment]
Closing.
