### ISSUE TITLE
Pagination component prototypes

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#4647]
Create first pass prototype implementation for Pagination applied to DataTable, List, Grid, etc. and as a standalone implementation.

Publish PR for feedback, commentary, direction, etc.

**Comment by halocline** [comment]
https://github.com/grommet/grommet/pull/4646

**Comment by ShimiSun** [comment]
Linking to https://github.com/grommet/grommet/issues/3354

**Comment by nomadus** [comment]
Will InfinteScroll have a pagination component?

**Comment by halocline** [comment]
> Will InfinteScroll have a pagination component?

@nomadus I think the current thinking is that InfiniteScroll and Pagination are two distinct approaches for presenting a lengthy set of results whether they be in a DataTable, List, or Grid. When using DataTable, List, or Grid, I should have the ability to choose whether to present those results in either 1) in full (i.e. all results), 2) paginated, or 3) progressively with infinite scroll.

Here is a draft PR with current proposal and discussion: https://github.com/grommet/grommet/pull/4646

I'd be interested in hearing your thoughts on the approach. Please feel free to comment here or on the draft PR.

**Comment by nomadus** [comment]
I am not sure if having onMore feature with InfineScroll is UX friendly. Let's say a user wants to navigate to Nth page, with the Pagination component it is easy to do, with onMore you have to click several times to achieve the same. I would have both.

**Comment by halocline** [comment]
Closing this issue as prototypes are included in this PR https://github.com/grommet/grommet/pull/4646
