### ISSUE TITLE
Problems with forms. Cant change background color of inputText or TextArea. cant change text color of checkbox

### ISSUE THREAD

**Issue by rodmartinezmedina** [grommet/grommet#4648]
Problems with forms. Cant change background color of inputText or TextArea. cant change text color of checkbox

### Expected Behavior
be able to change colors and background colors

### Actual Behavior
nothing

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forms-d1lt0?file=/index.js

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment]
Hi @rodmartinezmedina, the background color can be changed using: `formField.disabled.background.color`, `formField.error.background.color`, and `formField.focus.background.color`. The text color can be changed using: `formField.label.color`. Or you can also use `extend` to set the colors as shown in this example https://codesandbox.io/s/grommet-v2-template-forms-forked-ck06s?file=/index.js. Let me know if this helps solve the problem you are having.

**Comment by IanKBovard** [comment]
@rodmartinezmedina @jcfilben is correct. In the future, I recommend the Grommet Slack channel if you need any more help with implementation. We can answer your questions a lot more quickly there. I also, recommend simplifying your codesandbox example to just the issue, like jcfilben's. It makes it easier for us to see the root cause.

**Comment by rodmartinezmedina** [comment]
Thanks a lot. Last question here
. What about the green outline when in focus? any way to change that?
also please link to slack channel.
Thanks again

**Comment by jcfilben** [comment]
The green outline can be changed using `global.focus.border.color`. Here is the slack channel: https://slack-invite.grommet.io/

**Comment by ShimiSun** [comment]
Here are some story examples regarding handling the focus https://storybook.grommet.io/?path=/story/theme--focus
https://storybook.grommet.io/?path=/story/theme--themecontext-extend
