### ISSUE TITLE
Need onFocus function for input

### ISSUE THREAD

**Issue by maryjufang** [grommet/grommet#4652]
Need onFocus function for input

### Expected Behavior
provide onFocus function for input so user can manipulate some behavior when certain input box got focused.

### Actual Behavior
N/A

**Comment by ShimiSun** [comment]
React `onFocus` should propagate to grommet input components, can you please provide more context on the issue with details of a specific grommet component that doesn't propagate the `onFocus` as expected?

**Comment by ShimiSun** [comment]
Can you please respond to the question @maryjufang ?

**Comment by ShimiSun** [comment]
I'll be closing this issue, feel free to reopen with more details in case still relevant
