### ISSUE TITLE
Button does not always honor hoverIndicator={false}

### ISSUE THREAD

**Issue by kariwhitcomb** [grommet/grommet#4659]
### Expected Behavior

I expect that setting hoverIndicator={false} would remove all hover styling from the button.

### Actual Behavior

With default or secondary buttons, they still get the hover styling applied.  

Not hovering over button
![Screen Shot 2020-10-27 at 11 55 05 AM](https://user-images.githubusercontent.com/12547826/97341991-599ce380-184b-11eb-87c3-f793c20296f8.png)

Hovering
![Screen Shot 2020-10-27 at 11 55 23 AM](https://user-images.githubusercontent.com/12547826/97342005-5bff3d80-184b-11eb-8a28-2d783018fbb6.png)

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/brave-rosalind-no4xi?file=/src/App.js

### Steps to Reproduce

- Create a Button like: `<Button label='Hello' hoverIndicator={false} />`
- Hover over the button and you will see the background change.  For a secondary button, the outline of the button thickens on hover.  (Although the details of the styling may depend on the theme used.  For my test I'm using the grommet-theme-hpe)

### Your Environment

- Grommet version: 2.15.2
- grommet-theme-hpe: 2.0.1
- Browser Name and version: Chrome 86.0.4240.111
- Operating System and version (desktop or mobile): Mac OS 10.15.7

**Comment by halocline** [comment]
Hi @kariwhitcomb. I believe `hoverIndicator` is behaving as intended. Per the [docs](https://v2.grommet.io/button#hoverIndicator), `hoverIndicator` is `false` by default, so setting it to false would not impact the buttons behavior. `hoverIndicator` is intended to provide hover styling to `plain` buttons (last line in the doc description).

Can you share the design / behavior you are trying to achieve? Perhaps we can come up with a suitable approach for your requirements?

**Comment by taysea** [comment]
Hey @kariwhitcomb, thanks for raising this and I'm seeing how the naming of the prop is a little confusing in this case. The `hoverIndicator` prop is only meant to be used with plain buttons (not default/secondary/etc.), pulling from grommet docs here: "This prop is meant to be used only with plain Buttons." The reason being, this prop is supposed to be an opportunity to give some sort of hover indication to plain Buttons (which inherently don't have any hover styling), however it is not intended to remove any hover stylings of other button kinds (such as default or secondary). So, it appears `hoverIndicator` is behaving as expected, but it seems there is a use case you're facing where the hover styling is not desired anymore. Maybe we can talk about that separately to better understand that need?

**Comment by taysea** [comment]
I touched base with @kariwhitcomb, and the initial scenario which had prompted this issue is no longer being used and we concluded that hoverIndicator is behaving as expected. I believe we can close this issue now.

**Comment by kariwhitcomb** [comment]
Agreed we can close this.  Thanks
