### ISSUE TITLE
Spinning component missing

### ISSUE THREAD

**Issue by edvinh** [grommet/grommet#466]
The Spinning component is missing in the latest version, but it's still in the docs. Is the spinning component removed or is it a bug?

**Comment by alansouzati** [comment]
Thanks for reporting this, actually in the docs it seems we don't have the import commands, are you trying like this:

`var Spinning = require('grommet/components/icons/Spinning')`

or 

`import Spinning from 'grommet/components/icons/Spinning';`

I'm to update the docs page to include these commands.

**Comment by linde12** [comment]
Having the imports in the docs would be great!

Should we create a separate issue in the docs-repo and close this one?

**Comment by alansouzati** [comment]
The docs website has been updated with the import command :)

http://www.grommet.io/docs/develop/spinning

I believe we can close this issue, feel free to re-open if you are still facing problems!

**Comment by vsuoni** [comment]
There seems to be a wrong import path in the docs:
import Spinning from 'grommet/components/Spinning';

**Comment by alansouzati** [comment]
Thanks fixed in https://github.com/grommet/grommet-docs/commit/6e50f3ade5aecba972c3def60b000442757a6589
