### ISSUE TITLE
Duplicating list borders when side property is set to horizontal

### ISSUE THREAD

**Issue by GabrielMochi** [grommet/grommet#4665]
When working with the List component, if I set the property `side` of the `boder` prop to `horizontal`, it show two lines in the middle of the list items.

### Expected Behavior

It should render just one line in the middle of list items.

### Actual Behavior

It's rendering two lines in the middle of list items.

### URL, screen shot, or Codepen exhibiting the issue

[evidence image](https://i.imgur.com/y1JVufH.png)
[sandbox example](https://codesandbox.io/s/grommet-v2-template-forked-02uwi?file=/index.js)

### Steps to Reproduce

1. create a List component
2. add some data to it
3. set the border prop with the value: `{ color: "brand", side: "horizontal" }`

### Your Environment

- Grommet version: 2.15.2
- Browser Name and version: Google Chrome Version 86.0.4240.111 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): desktop and mobile

**Comment by ShimiSun** [comment]
I think it behaves as expected. The `border` prop has consistent behavior across the grommet components, and the `horizontal` value is consistently rendering horizontal borders which are both the top and bottom borders you are seeing and sensing those are duplicated. Why not using just `top` or `bottom` as the border values if you'd like to have a single border rendered, or even just using the default border behavior of List?

**Comment by ShimiSun** [comment]
I'll be closing this issue if there is no further input. Feel free to reopen if needed and provide more details.
