### ISSUE TITLE
Default expand all in Accordion component.

### ISSUE THREAD

**Issue by SagarTrimukhe** [grommet/grommet#4669]
### Expected Behavior
It would be great if we can have an option to pre-open all the accordion panels or at least the first one.
In the documentation a prop called **activeIndex** is mentioned, where the developer can mention the indices of panels to be kept open, but it needs to be managed via onActive function.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
Thanks for reporting, as you mentioned `activeIndex` and `onActive` are the props (API) to manage the open/close behavior. From what you are describing, you'd like a combination of controlled and uncontrolled behaviors where the user can control the initial behavior but let the Accordion 'do its thing' in an uncontrolled way after the initial interaction, I'm not sure we would want to get into this inconsistent behavior of mixed controlled and uncontrolled states, but I'd like to see if anyone else has any opinion here on how to handle the issue in a clean way.

**Comment by jcfilben** [comment]
Hey, just wanted to check back in on this issue and see if there is still interest. If there is I think it would be good to hear more about the use case and why using `onActive` and `activeIndex` to accomplish this doesn't work well. If there is no longer interest I think we can go ahead and close this.

**Comment by SagarTrimukhe** [comment]
> Hey, just wanted to check back in on this issue and see if there is still interest. If there is I think it would be good to hear more about the use case and why using `onActive` and `activeIndex` to accomplish this doesn't work well. If there is no longer interest I think we can go ahead and close this.

Hi, You can close this enhancement request.
