### ISSUE TITLE
CheckBox onClick event

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#467]
CheckBox would need onClick event or props transfer. 
If you want to use CheckBox in a TableRow you can not stop propagation for click event and table row clicks fires before CheckBox onChange happens. 

Example: Use CheckBox for multi select and table row click for detail view.
![screen shot 2016-03-27 at 10 24 14](https://cloud.githubusercontent.com/assets/1006789/14064519/76648270-f406-11e5-91bc-ad55f00ee597.png)

Would you accept pull request?

**Comment by alansouzati** [comment]
Good idea, let's target the props transfer to be consistent with the Box implement :+1:

**Comment by bryanjacquot** [comment]
@primozs eagerly awaiting a PR for this.

**Comment by primozs** [comment]
Hello, let me know your opinion.
Cheers

**Comment by alansouzati** [comment]
Fixed.

**Comment by dakt** [comment]
Am I missing something...it seems that this is not working anymore. Can anyone confirm this?

**Comment by alansouzati** [comment]
@dakt let me work on a codepen to test this out again.

**Comment by dakt** [comment]
@alansouzati  Yeah, sorry, completely missed the  "props transfer" comment you made. I just wrapped CheckBox inside the Box and worked from there. Not sure why we cannot do the directly on CheckBox?

**Comment by alansouzati** [comment]
oh for the checkbox I believe you need to listen for the onChange, right?

**Comment by alansouzati** [comment]
it is just like another form input i believe.
