### ISSUE TITLE
Selected value is not being displayed in a select element under Layer while it is focused

### ISSUE THREAD

**Issue by eabay** [grommet/grommet#468]
Here is the codepen: http://codepen.io/anon/pen/GZEQVd?editors=1010

The problem is the padding value applied in focused state:
https://github.com/grommet/grommet/blob/cbfce2b8665528bec320a2ba617f42d34006a1bc/src/scss/grommet-core/_base.input.scss#L23

**Comment by alansouzati** [comment]
Thanks for pointing this out. Fixed by https://github.com/grommet/grommet/commit/4713f1873634411ec2875f4942c3d0ec9ebe3c81
