### ISSUE TITLE
Multiple Dates in calendar do not display. 

### ISSUE THREAD

**Issue by joshpauline** [grommet/grommet#4696]
Multiple Dates in calendar do not display. 

what passing an array of ISO8601 format dates into the Calendar component as a a prop to the 'dates' prop the selected dates are not highlighted. 

### Expected Behavior

They should highlight 

### Actual Behavior

they do not highlight

### Steps to Reproduce

pass the following information to codepen or in your current project

<Calendar
  size="small"
  date={(new Date()).toISOString()}
  onSelect={(date) => {}}
  dates={['2020-11-07', '2020-11-09']}
/>

### Your Environment

- Grommet version: 2.15.2
- Browser Name and version: Chrome 86.0.4240.111 
- Operating System and version (desktop or mobile): Mac OS Catalina 10.15.6

**Comment by taysea** [comment]
Hey @joshpauline, I noticed here that you're defining a default value for both `date` and `dates`. If your desire is to do multiple date selection, you should just use the `dates` prop and can implement something like this: https://storybook.grommet.io/?path=/story/calendar--multiple

Let me know if that clears up your issue!

**Comment by joshpauline** [comment]
> Hey @joshpauline, I noticed here that you're defining a default value for both `date` and `dates`. If your desire is to do multiple date selection, you should just use the `dates` prop and can implement something like this: https://storybook.grommet.io/?path=/story/calendar--multiple
> 
> Let me know if that clears up your issue!

That is it, sorry I thought I could have one as selected whilst still showing all the other dates that I wanted. 

Cheers
