### ISSUE TITLE
When Layer component is set up as a modal, it still allows keyboard focus to go behind the modal

### ISSUE THREAD

**Issue by katekourbatova** [grommet/grommet#4721]
When Layer component is set up as a modal, it still allows keyboard focus to go behind the modal.

### Expected Behavior

I would expect that when a modal is open, keyboard navigation should not leave the modal (except Esc which should close the modal). This is supported by the description of the `modal` attribute in the doc: "Whether there should be an overlay preventing interaction underneath the layer."
I'd expect that continuing to Tab through the modal should loop through the focusable elements inside it.

### Actual Behavior

When a modal is open, tabbing allows you to leave the modal and select elements behind it.

### URL, screen shot, or Codepen exhibiting the issue

https://v2.grommet.io/layer

### Steps to Reproduce

1. Create a Layer component with modal set to true (which is the default)
2. Open the modal (with keyboard or mouse, doesn't matter)
3. First Tab gets you in to the modal, but when you keep tabbing and run out of focusable elements inside the modal it continues to focus on elements outside of the modal instead of looping back through the modal.

### Your Environment

I was testing the modal right in the example here https://v2.grommet.io/layer
But another user has confirmed they have the same issue in their app built with Grommet.

**Comment by LiveFreeAndRoam** [comment]
I spoke with Shimi about this.

Here is a CodeSandbox to demo the issue... https://codesandbox.io/s/modal-layer-does-not-block-tab-to-underlayer-4srul?file=/src/App.js.

We found the problem was introduced in v2.15.0.  Shimi felt it was possibly related to [PR #4381](https://github.com/grommet/grommet/pull/4381/files?file-filters%5B%5D=.js).

**Comment by ShimiSun** [comment]
Also reproducible on https://storybook.grommet.io/?path=/story/layout-layer--corner-layer

**Comment by ShimiSun** [comment]
@LiveFreeAndRoam, the root cause of the problem is https://github.com/grommet/grommet/pull/4378
