### ISSUE TITLE
Uncontrolled TextInput doesn't hide placeholder when it's not a string

### ISSUE THREAD

**Issue by leossantiago** [grommet/grommet#4729]
### Expected Behavior

As title, uncontrolled TextInput should hide placeholder (non string) when user starts typing anything. Instead, it keeps both.

### Actual Behavior

- Controlled TextInput with non string placeholder:

Code:
```js
function Example() {
  const [value, setValue] = React.useState('');
  return (
    <TextInput
      placeholder={<Text>This is the placeholder</Text>}
      value={value}
      onChange={event => setValue(event.target.value)}
    />
  );
}
```

SS:
![image](https://user-images.githubusercontent.com/47114840/98449776-7b347f80-2115-11eb-9305-59d9009158fe.png)

- Uncontrolled TextInput with non string placeholder:

Code:
```js
function Example() {
  return (
    <TextInput
      placeholder={<Text>This is the placeholder</Text>}
    />
  );
}
```

SS:
![image](https://user-images.githubusercontent.com/47114840/98449760-43c5d300-2115-11eb-9e15-aa28d3ea346c.png)

- Uncontrolled TextInput with string placeholder:

Code:
```js
function Example() {
  return (
    <TextInput
      placeholder="This is the placeholder"
    />
  );
}
```

SS:
![image](https://user-images.githubusercontent.com/47114840/98449840-1b8aa400-2116-11eb-8b78-e9df12917599.png)

### URL, screen shot, or Codepen exhibiting the issue

Test code: 
```js
function Example() {
  return (
    <TextInput
      placeholder={<Text>This is the placeholder</Text>}
    />
  );
}
```

### Steps to Reproduce

1. Access `Storybook -> Input -> Styled placeholder`
2. Type anything
 
**OR**

1. Access [`TextInput`](https://v2.grommet.io/textinput?)  component page
2.  Use the code provided above.

You can also pass something like `placeholder={43}` as prop.

### Your Environment

Web storybook, using both Chrome and Firefox.

**Comment by ShimiSun** [comment]
Fixed, thanks for reporting!
