### ISSUE TITLE
Right-justified text input for numeric data in order forms

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet#4736]
Editable numeric tabular data would benefit from the ability to support right-justified text input (and precision specification for decimal point positioning.

Here's an example:
![image](https://user-images.githubusercontent.com/17883783/98743680-aca78800-236d-11eb-84b2-d1f3ab74911a.png)

**Comment by ShimiSun** [comment]
Fixed, thanks for reporting, and thanks @MikeKingdom for enabling this property.
