### ISSUE TITLE
DateInput - Wrong TS definition of the onChange event 

### ISSUE THREAD

**Issue by gynekolog** [grommet/grommet#4738]
Current [TS annotation of the DateInput onChange event](https://github.com/grommet/grommet/blob/master/src/js/components/DateInput/index.d.ts#L18):
```
onChange?: (event: { target: { value: string | string[] } }) => void;
```

but DateInput event provides `event.value`

Possible fix:
```
onChange?: (event: value: string | string[] }) => void;
```

- Grommet version: 2.5.12

**Comment by MathieuDoyon** [comment]
`target` is also `undefined` when the user select a date from the calendar instead of typing into the field.

**Comment by ShimiSun** [comment]
Anyone would like to make an open-source contribution?

**Comment by arthursakemi** [comment]
I would like to make this my first contribution
