### ISSUE TITLE
How to remove font-weight 600 from select component

### ISSUE THREAD

**Issue by benwainwright** [grommet/grommet#4740]
Hi there!

I've spent the last hour trying to remove the 600 font-weight that seems to be applied to the `<Select />` component and I can't seem to do it. 

There are no props or documented global styles for this (like there are for `<TextInput>`. I've tried setting up the following:

```
  const theme = {
    select: {
      control: {
        extend: `
          font-weight: 300 !important;
        `,
      },
    },
  };

<ThemeProvider.Extend theme={theme}>
   <Select />
</ThemeProvider.Extend>
```

When I do this, although the style appears on the stylesheet, it is being superseded by an inline style somewhere, so never actually works. 

If anyone has any pointers, I'd be eternally greatful.

**Comment by halocline** [comment]
Hi @benwainwright, the weight is defined at `global.input.font.weight` and applies to inputs like <TextInput /> and <MaskedInput /> as well. You can use the same strategy as above using  `global.input.font.weight` instead.

**Comment by benwainwright** [comment]
Fab, thanks @halocline that did the job!
