### ISSUE TITLE
Typescript - Video controls typing not allowing any value other than undefined

### ISSUE THREAD

**Issue by ArrayKnight** [grommet/grommet#4746]
### Expected Behavior

Video controls accepts `undefined`, `false`, `'over'`, or `'below'`

```typescript
export interface VideoProps {
  a11yTitle?: A11yTitleType;
  alignSelf?: AlignSelfType;
  autoPlay?: boolean;
  controls?: false | 'over' | 'below';
  fit?: 'cover' | 'contain';
  gridArea?: GridAreaType;
  loop?: boolean;
  margin?: MarginType;
  messages?: {
    closeMenu?: string;
    fullScreen?: string;
    progressMeter?: string;
    openMenu?: string;
    scrubber?: string;
    pauseButton?: string;
    playButton?: string;
    volumeUp?: string;
    volueDown?: string;
  };

  mute?: boolean;
}

declare const Video: React.ComponentClass<VideoProps &
  Omit<JSX.IntrinsicElements['video'], 'controls'>>;
```

### Actual Behavior

Video controls accepts only `undefined`

```typescript
export interface VideoProps {
  a11yTitle?: A11yTitleType;
  alignSelf?: AlignSelfType;
  autoPlay?: boolean;
  controls?: 'false' | 'over' | 'below'; // <-- Change 'false' to false
  fit?: 'cover' | 'contain';
  gridArea?: GridAreaType;
  loop?: boolean;
  margin?: MarginType;
  messages?: {
    closeMenu?: string;
    fullScreen?: string;
    progressMeter?: string;
    openMenu?: string;
    scrubber?: string;
    pauseButton?: string;
    playButton?: string;
    volumeUp?: string;
    volueDown?: string;
  };

  mute?: boolean;
}

declare const Video: React.ComponentClass<VideoProps &
  JSX.IntrinsicElements['video'] & // <-- Remove
  Omit<JSX.IntrinsicElements['video'], 'controls'>>;
```

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/5431637/99105571-9c72f100-2597-11eb-8f0b-eaa615f48abd.png)

### Steps to Reproduce

1. Implement Video component
2. Add `controls` attribute
3. Give attribute any `VideoProps['controls']` value

### Your Environment

- Grommet version: 2.15.2
- IDE Name and version: PhpStorm 2020.2.3
- Operating System and version (desktop or mobile): Windows 10

**Comment by ArrayKnight** [comment]
As a temporary, hacky workaround: `controls={('false' as unknown) as undefined}`

**Comment by ShimiSun** [comment]
Hi buddy, do you feel like making a contribution and help us improve the TS support?

**Comment by ArrayKnight** [comment]
@ShimiSun How often do new builds get released?

**Comment by ShimiSun** [comment]
Hi buddy, I'm planning one for next week if all will go smoothly. In the meanwhile, try to use the stable branch to include the fix https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F
