### ISSUE TITLE
Export all internal Styled Components for use in style overrides as selectors

### ISSUE THREAD

**Issue by ArrayKnight** [grommet/grommet#4748]
### Expected Behavior

When implementing a component that requires style overrides that are not easily accomplished using the theme, it should be possible to use Grommet styled components as selectors.

```typescript
import { Menu, StyledButton, StyledDropContainer } from 'grommet'
import styled from 'styled-components'

const CustomMenu = styled(Menu)`
    ${StyledDropContainer} {
        // ... some specific styles

        ${StyledButton} {
            // ... more specific styles

            &:hover {
                // ... 
            }

            @media (min-width: 1000px) {
                // ...
            }
        }
    }
`
```

### Actual Behavior

A few styled components can be imported but only from deeply nested, untyped, paths:
```typescript
import { StyledFoo } from 'grommet/this/path/isnt/real'
```

But most styled components are inaccessible. And even if they were, the Typescript types would need to be adjusted for the deep paths where they reside.

### Steps to Reproduce

1. Implement a component with nested components
2. Try to restyle those nested components without using theme extend (which isn't reliably available)

### Your Environment

- Grommet version: 2.15.2
- IDE Name and version: PhpStorm 2020.2.3
- Operating System and version (desktop or mobile): Windows 10

**Comment by jcfilben** [comment]
Closing this for now. Rather than export the internal styled components I think we should lean into making theme enhancements and using extend. Feel free to comment if interested in continuing the discussion on this.
