### ISSUE TITLE
Ideate approaches to Button sizing

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#4754]
Explore possible approaches to ensure Button's size, state, and kind styling all work together.

### Expected Behavior

A button implemented as:
```
<Button secondary size="large" label="Large" icon={<FormNext />} reverse />
```
And a theme defined as:
```
button: {
    default: {
      ...
      padding: {
        horizontal: '12px',
        vertical: '6px',
      },
    },
    secondary: {
      border: {
        color: 'green',
        width: '2px',
      },
      color: 'text-strong',
      font: {
        weight: 700,
      },
      padding: {
        horizontal: '10px',
        vertical: '4px',
      },
    },
    size: {
      ...
      large: {
        border: {
          radius: '6px',
        },
        pad: {
          vertical: '8px',
          horizontal: '16px',
        },
      },
    },
  },
```
should apply the button kind's styling as well as be able to be sized.

### Actual Behavior

Related: https://github.com/grommet/grommet-theme-hpe/issues/139#issuecomment-724901504

Instead, the button's kind styling ("secondary" in this case) trumps any size styling when in conflict and does not render desired results:
**Large secondary button, not large**
![Screen Shot 2020-11-16 at 1 11 21 PM](https://user-images.githubusercontent.com/1756948/99303045-82424880-280d-11eb-94b5-615786fb2690.png)

**Resulting CSS shows padding being set multiple times on same component:**
![Screen Shot 2020-11-16 at 1 11 32 PM](https://user-images.githubusercontent.com/1756948/99303158-b0278d00-280d-11eb-9a2f-77307e5feb4a.png)

**Solution should also account for:**
- Buttons at different states (e.g. hover state such as`button.hover.secondary` can also have styling specified)
![Screen Shot 2020-11-16 at 1 22 36 PM](https://user-images.githubusercontent.com/1756948/99304254-5a53e480-280f-11eb-9750-243a4a0efa76.png)
- Gap between label and icon
- Icon scaling

### Steps to Reproduce

**Theme definition:**
```
button: {
    default: {
      color: 'text-strong',
      border: undefined,
      font: {
        weight: 700,
      },
      padding: {
        horizontal: '12px',
        vertical: '6px',
      },
    },
    primary: {
      background: {
        color: 'green',
      },
      border: undefined,
      color: 'text-strong',
      font: {
        weight: 700,
      },
      padding: {
        horizontal: '12px',
        vertical: '6px',
      },
    },
    secondary: {
      border: {
        color: 'green',
        width: '2px',
      },
      color: 'text-strong',
      font: {
        weight: 700,
      },
      padding: {
        horizontal: '10px',
        vertical: '4px',
      },
    },
    option: {
      color: 'text',
      border: {
        radius: '0px',
      },
      padding: {
        horizontal: '12px',
        vertical: '6px',
      },
      font: {
        weight: 400,
      },
    },
    active: {
      background: {
        color: 'background-contrast',
      },
      color: 'text',
      secondary: {
        border: {
          color: 'transparent',
        },
      },
      option: {
        background: {
          color: 'active-background',
        },
      },
    },
    selected: {
      option: {
        background: 'selected-background',
        color: 'selected-text',
      },
    },
    disabled: {
      background: {
        color: 'transparent',
      },
      color: 'text-weak',
      primary: {
        border: {
          color: 'border-weak',
          width: '2px',
        },
        padding: {
          horizontal: '10px',
          vertical: '4px',
        },
      },
      secondary: {
        border: {
          color: 'border-weak',
        },
      },
      opacity: 1.0,
    },
    hover: {
      default: {
        background: {
          color: 'background-contrast',
        },
        color: undefined,
      },
      secondary: {
        border: {
          width: '3px',
        },
        padding: {
          horizontal: '9px',
          vertical: '3px',
        },
      },
      option: {
        background: 'active-background',
        color: 'active-text',
      },
    },
    size: {
      small: {
        border: {
          radius: '4px',
        },
        pad: {
          vertical: '4px',
          horizontal: '8px',
        },
      },
      medium: {
        border: {
          radius: '4px',
        },
        pad: {
          vertical: '6px',
          horizontal: '12px',
        },
      },
      large: {
        border: {
          radius: '6px',
        },
        pad: {
          vertical: '8px',
          horizontal: '16px',
        },
      },
    },
    border: {
      radius: '4px',
    },
    color: 'text-strong',
    padding: {
      vertical: '4px',
      horizontal: '10px',
    },
  },
```
**JSX:**
<Button secondary label="Default" icon={<FormNext />} reverse />
<Button secondary size="small" label="Small" icon={<FormNext />} reverse />
<Button secondary size="medium" label="Medium" icon={<FormNext />} reverse />
<Button secondary size="large" label="Large" icon={<FormNext />} reverse />
```

### Your Environment

<!--- Include as many relevant details about the environment you experienced the bug in -->

- Grommet version: 2.15.2 / Stable
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
@halocline please keep this issue as the main informed issue and enhance its details, so the community will be up to date with the details and potential suggested solutions of what grommet is focusing on.

**Comment by halocline** [comment]
> @halocline please keep this issue as the main informed issue and enhance its details, so the community will be up to date with the details and potential suggested solutions of what grommet is focusing on.

@ShimiSun I've updated the issue description to document in full.

**Comment by ericsoderberghp** [comment]
Tied to https://github.com/grommet/hpe-design-system/issues/1306
