### ISSUE TITLE
Modal Layer leaves underlying Opened DropButton active

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#4756]
Related to #4721.  In this case a DropButton remains active after a Modal Layer is open.  In my case, I have a modal layer that appears after a timeout.  If the DropButton happens to be open at that time, then the opened DropButton remains active.  As soon as the DropButton is closed, then the modal Layer works as advertised.

### Expected Behavior

A Modal Layer ought to prevent interaction with all other "underlayer" components.

### Actual Behavior

If a DropButton component is open at the time the Modal Layer is displayed, then the DropButton can continue to be interacted with.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/modal-layer-does-not-block-tab-to-underlayer-4srul?file=/src/App.js

### Steps to Reproduce

Open a DropButton.
Open a modal Layer.

Notice the DropButton remains active while the modal Layer is open.

### Your Environment

- Grommet version: 2.14, 2.15.2, stable (with the fix from #4721.
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
Thanks for reporting @LiveFreeAndRoam , this fix will be available on the upcoming hotfix.
