### ISSUE TITLE
Time Picker Component

### ISSUE THREAD

**Issue by JasonWeise** [grommet/grommet#476]
Hi All

I'd like to start by saying how great this library is, I have come from Material-UI and Grommet just feels more polished everywhere.
I have been working with Grommet for a little bit now and have now come across the need for a Time Picker Component.
Is there any roadmap for a Time Picker? It is kind of causing a small speed-hump in my project not having one but if there is a Time Picker likely soon I will just keep working around it and wait.

Thanks in advance, keep up the awesome work.

**Comment by JasonWeise** [comment]
I have done a little bit more investigation whilst waiting for a response and I have noticed in the StickerSheet for Sketch there is a DateTime component that looks perfect for what I need.
I have looked through the src file in this repo and cannot see this component.

Is there a DateTime Picker like demonstrated in the Sketch Sticker Sheet in resources.

Thanks heaps for looking at this..

**Comment by alansouzati** [comment]
Thanks for the kind words @JasonWeise.

For now we don't have the Time Picker in the develop side of things, sorry about that.

I've created a codepen recently that should help in the meantime: http://codepen.io/alansouzati/pen/YqpKmK

**Comment by ericsoderberghp** [comment]
FYI, I'm working on a DateTime component. :)

**Comment by alansouzati** [comment]
great @ericsoderberghp looking forward to see that :+1:

**Comment by CoveTechnologyAus** [comment]
This is terrific news guys. Can't wait to see the DateTime component @ericsoderberghp . A Time Picker is definitely a much needed component.
@ericsoderberghp, will it likely be able to just do time selection without the Date/Calendar component?

**Comment by ericsoderberghp** [comment]
A first version of the DateTime component is now available:

**Comment by murbanowicz** [comment]
What happened with TimePicker? :(

**Comment by ShimiSun** [comment]
@murbanowicz your timing is kinda perfect. We added a DateInput component and it is still under exploration on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F), feel free to check it out and tell us if its what you are looking for, here are some examples https://storybook.grommet.io/?path=/story/dateinput--form

**Comment by murbanowicz** [comment]
Shimi, I do not see any examples with Time? 
Date picker looks great anyway :)

**Comment by ShimiSun** [comment]
@murbanowicz gotcha... Can you share an example of what you had in mind?

**Comment by murbanowicz** [comment]
> @murbanowicz gotcha... Can you share an example of what you had in mind?

Something like this.
<img width="345" alt="CHzmN" src="https://user-images.githubusercontent.com/9385106/87852506-c0346c00-c902-11ea-9677-13020bc17946.png">

**Comment by P4R4DiSi4C** [comment]
> > @murbanowicz gotcha... Can you share an example of what you had in mind?
> 
> Something like this.
> <img alt="CHzmN" width="345" src="https://user-images.githubusercontent.com/9385106/87852506-c0346c00-c902-11ea-9677-13020bc17946.png">
> 
> Of course with or without date.

@ShimiSun The Date Picker is pretty nice, good job on that one !

BUT I'd love to see something like @murbanowicz showed since I'm working on an app where clients should be able to select a date and set a start + end time..

Cheers !

**Comment by ShimiSun** [comment]
linking to #4333
