### ISSUE TITLE
Failed prop type: Invalid prop `columns` supplied to `Grid`

### ISSUE THREAD

**Issue by oskari** [grommet/grommet#4767]
### Expected Behavior

No errors should be given when Grid columns has array of strings defined for size

### Actual Behavior

Invalid prop warning is given, while the component works as expected.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-grid-columns-7r0r9?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/506596/99776193-14519600-2b19-11eb-9702-4069ce756cc7.png)

### Steps to Reproduce

1. Define Grid columns size as an array of strings
2.
3.

### Your Environment

name | version
-|-
grommet |  2.15.2
react | 17.0.0
react-dom | 17.0.0
react-scripts | 3.3.0
styled-components | 5.2.1

- Grommet version: 2.15.2
- Browser Name and version: Firefox Developer Edition 83.0b9
- Operating System and version (desktop or mobile): macOS Catalina 10.15.7

**Comment by leossantiago** [comment]
I do believe this issue can be closed :tada:
