### ISSUE TITLE
Removing white background for Layer

### ISSUE THREAD

**Issue by ryanadhi** [grommet/grommet#4772]
### Expected Behavior
`Layer` should have option to be used withoud white background (or probably I missed to read the Docs) 

### Actual Behavior

`Layer` does have white background, if we set `plain === true` the grey-ish background overlaying the Modal also gone

### URL, screen shot, or Codepen exhibiting the issue

![Screenshot 2020-11-22 165807](https://user-images.githubusercontent.com/35433920/99925521-131aa600-2d71-11eb-917b-fa5271b1fbdd.png)

### Steps to Reproduce

```
<Layer
	position="bottom"
	onClickOutside={closeLayer}
	onEsc={closeLayer}
	responsive={false}
	full="horizontal"
	>
		<Box
			fill
			round={{ corner: 'top' }}
			align="center"
			justify="center"
			pad="small"
			background='teal'
			gap="medium"
			>
				<Heading margin="small" level='3' alignSelf='center'>Select payment method</Heading>
		</Box>
</Layer>

```

### Your Environment

- Grommet version: 2.15.2
- Browser Name and version: Chrome Version 87.0.4280.66 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by ShimiSun** [comment]
We fixed it a couple of weeks ago, it was just wasn't release yet, @jcfilben would you like to share a working example or provide more context?

**Comment by jcfilben** [comment]
The background color is set to white by default but you can change the color with the theme. You can use `layer.background` to set the color of the layer background and `layer.overlay.background` to change the color of the layer overlay. [Here](https://codesandbox.io/s/grommet-v2-template-forked-31rey?file=/index.js:256-267) is a codesandbox example showing the default white background being removed by setting the `layer.background` to "#ffffff00"

**Comment by ryanadhi** [comment]
@jcfilben cool. Thanks!!
