### ISSUE TITLE
Chart docs mention `fill` value for `size` prop, fill is not included in values list

### ISSUE THREAD

**Issue by DanielBaird** [grommet/grommet#4776]
### Expected Behavior

Looking at this URL, the docs for `Chart`: https://v2.grommet.io/chart#size
The `size` prop docs should include the `"fill"` value.

### Actual Behavior

`fill` value is mentioned in the descriptive text, but not shown in the values list:
![image](https://user-images.githubusercontent.com/25352/100029821-d5378380-2e3d-11eb-8b79-4dadf378307c.png)

### Your Environment

I just noticed this today (24 November 2020) at the URL above (I'm using Chrome 87 on Win10, but I'm fairly confident that's not the problem..).  I went looking for the doc-source to see if I could correct it, but as far as I can see, the doc sources have been correct for six months (they include both the `fill` prop and the deprecated `full` prop).

Apparently correct doc source:
https://github.com/grommet/grommet/blob/master/src/js/components/Chart/doc.js#L147-L167

Possibly it's just that the docs site needs updating?

**Comment by ShimiSun** [comment]
I think you are right, the docs on the site itself should be updated and not on the grommet core, here is the issue https://github.com/grommet/grommet-site/blob/3497d9e2558b7a61ad328466b31dde9242c07e5b/src/screens/Chart.js#L61

Feel free to make a contribution to the site itself.

**Comment by ShimiSun** [comment]
Thank you for your contribution buddy, the site should be up to date!
