### ISSUE TITLE
Add "onScrollTop" and "onScrollBottom" to InfiniteScroll

### ISSUE THREAD

**Issue by resynth1943** [grommet/grommet#4779]
### Feature Request

I'm developing a chat application. 

In the main room view, I intend to append new items to the buffer when
a user scrolls to top / bottom. In its current state, `InfiniteScroll`'s `onMore`
callback doesn't really say which **direction** items need to load in
(which margin the user has hit, e.g. top / bottom).

This would be extremely useful for bidirectional infinite scrolling, like in my 
chat application. Are there any plans to implement this?

**Comment by halocline** [comment]
Related issue: https://github.com/grommet/grommet/issues/4392

**Comment by resynth1943** [comment]
Thanks @halocline :+1:
