### ISSUE TITLE
Move list to bottom/top programmatically

### ISSUE THREAD

**Issue by jimwhurr** [grommet/grommet#4780]
At the moment there is no way send the <List> (or maybe the underlying InfiniteScroll) to the bottom of the top from your code.

### Expected Behavior
Expose one or more props from the <List> component so that you can direct the list to the bottom/top (as a minimum).

Rationale - for large lists buttons could be programmed to move to the bottom/top saving the user from tediously scrolling to the bottom/top. (It might also be nice to position the list on a specific, pre-selected, item)

### Actual Behavior
No such feature

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
I think this is a duplication of https://github.com/grommet/grommet/issues/4779 and #4392, @jimwhurr can you please confirm?

**Comment by jimwhurr** [comment]
They may be related but I don't think that they are duplicates.
4779 talks about direction of scroll when items are appended to a list (and which end they should be appended to) & 4392 talks about a way to perform scrolling when data is added using onMore.

I was thinking more about the UI aspect - providing a way to programmatically move to the top/bottom of a large (static) list other than making a user manually scroll down.

Maybe the best description would be that they are aspects of traversing/using a very large list? With a twist that the list may be attached to a stream of some sort (e.g. chat). A sort of combined linux head/tail.

**Comment by ShimiSun** [comment]
> Maybe the best description would be that they are aspects of traversing/using a very large list? With a twist that the list may be attached to a stream of some sort (e.g. chat). A sort of combined linux head/tail.

I think there are many ways to achieve it that are not component related, you can always create a button that flips the order of the list or sort it differently,  and that will control the order of the items.
One more popular option is to use Filtering on the list, see if any of the examples here are helpful https://design-system.hpe.design/templates/filtering.

Either way, I think this functionality is user-specific and content related. 
I personally don't think it should be a part of the component, would love to hear more opinions here.

**Comment by halocline** [comment]
> I was thinking more about the UI aspect - providing a way to programmatically move to the top/bottom of a large (static) list other than making a user manually scroll down.
> 
Rephrasing to see if I understand the request. Would this be a fair representation? "In effort to minimize extensive scrolling through a long list, I would like the ability for a user to 'jump to' the first or last index in a list. Even better, I would like the ability to 'jump to' any index I specify."

If that is accurate, List has a `show` prop which accepts an integer representing which index of the list should be visible when rendered. Here is a [Storybook example](http://localhost:9001/?path=/story/visualizations-list--show) demonstrating that functionality. @jimwhurr is this in line with your needs?

@ShimiSun noticing that `show` is omitted from List's documentation. Would you like me to add it?

**Comment by ShimiSun** [comment]
> @ShimiSun noticing that show is omitted from List's documentation. Would you like me to add it?

**Comment by jcfilben** [comment]
Closing since the `show` prop has been added to List and can be used to achieve the desired behavior.
