### ISSUE TITLE
Is there a way to control the activeSuggestionIndex property of TextInput?

### ISSUE THREAD

**Issue by ddohler** [grommet/grommet#4781]
We've had a request to auto-select the first suggestion in a TextInput's suggestions list when the user hits Enter, so that they are not required to click or use the down-arrow first. I've found that the active suggestion is managed by `activeSuggestionIndex` within the TextInput, but that state seems to be internal to the component, without any way to control it from the outside. Is this possible?

### Expected Behavior

(Not sure this is helpful in this case since this is more of a question, but here's an example just in case):
Type an entry into a TextInput that has suggestions, so that one or more suggestions are shown.
Hit Enter
`onSuggestionSelect` is fired with the value of the first item in the suggestions list.

### Actual Behavior

The suggestions Drop disappears, and `onSuggestionSelect` is not fired. I haven't found a way to customize this behavior so far.

### URL, screen shot, or Codepen exhibiting the issue

I believe this behavior occurs with TextInputs that use suggestions, but I am specifically referring to the geography name search at the top of this page: https://wildfirerisk.org/explore/0/30/30063/3000050200/

<img width="469" alt="Screen Shot 2020-11-24 at 4 58 55 PM" src="https://user-images.githubusercontent.com/447977/100156333-b1446400-2e76-11eb-8286-c2083eadd074.png">

### Steps to Reproduce

1. Type an entry into a TextInput that has suggestions, so that one or more suggestions are shown.
2. Hit Enter

### Your Environment

- Grommet version: 2.10.0
- Browser Name and version: All desktop browsers.
- Operating System and version (desktop or mobile): Desktop

Thanks!

**Comment by ShimiSun** [comment]
Just a quick thought here, have you tried wrapping the component with Keyborad component and control the Enter behavior yourself?

**Comment by ddohler** [comment]
Thanks for the reply! Yep, that's a potential fallback we've discussed, but the trouble with that approach is that there will be no visual indication that the first suggestion will be selected if the user presses Enter. Ideally we'd like to also highlight the first suggestion. 

Looking at other autoselect libraries, we've seen a `highlightFirstSuggestion` prop used to accomplish this goal -- would you all be open to a PR adding something like that to `TextInput`? My quick read of the `TextInput` makes me think that it should primarily require adjusting all the occasions where `setActiveSuggestionIndex` is called with `-1` to instead call with `0` if the new prop is true. Does that sound like a fair characterization of the task to you, or is there something major I'm missing?

If you'd be open to a PR, do you have a guesstimate of how long it might take to move it through the review process and have it end up in a release? That'll probably determine what approach we choose.

**Comment by ShimiSun** [comment]
I like your idea of improvement, the discussion could go smoother and on point once will see a PR, feel free to file one.

**Comment by wrdaigle** [comment]
@ddohler, here is another thought.  

Instead of selecting the first element, what if you populated the first item into the TextInput value and styled it to act like predictive text. You would need to wrap it in a Keyboard component to listen for the  onEnter and onDown events.  

The chrome browser uses something similar in the address bar.

**Comment by ddohler** [comment]
@ShimiSun Thanks, we'll give it a shot.

@wrdaigle Thanks for the suggestion -- I'll respond in the project repo to avoid bringing non-Grommet discussion into this thread.

**Comment by ShimiSun** [comment]
The new prop `defaultSuggestion` is added to grommet, the only piece that is missing is documenting it by adding it to the doc.js file. I'll keep this issue open until then.

**Comment by ddohler** [comment]
@ShimiSun Sorry for missing that in the initial PR -- I've opened #4852 to cover this.

**Comment by ShimiSun** [comment]
@ddohler Thank you for your contributions buddy ❤️
