### ISSUE TITLE
TableCell align prop is not documented

### ISSUE THREAD

**Issue by jjalonso** [grommet/grommet#4783]
As said, TableCell align prop is not documented on the doc. it just appear as a theme option but it works as props.

**Comment by g4rry420** [comment]
Can I work on this issue ?

**Comment by g4rry420** [comment]
I am sorry, Can you please tell me how to start the application locally ? @jjalonso

**Comment by ShimiSun** [comment]
@g4rry420 How is it going? Let us know if you need any help with the direction and PR.

**Comment by g4rry420** [comment]
I am facing some testing errors before while I am try to commit.

**Comment by ShimiSun** [comment]
@g4rry420 feel free to share with us what you are facing in case you'd like the help.

**Comment by jcfilben** [comment]
I think this issue can be closed since #4983 was merged
