### ISSUE TITLE
Unable to select a dynamically loaded option from Select Field

### ISSUE THREAD

**Issue by sindhoora-r** [grommet/grommet#4792]
Unable to select a dynamically loaded option from Select Field. 
In a Select component, where we lazy load more options, we are unable to select an option from the lazy loaded options.

### Expected Behavior
We should be able to select any option from the Select Component

### Actual Behavior
We are unable to select an option from the latest list of options(load more)
https://storybook.grommet.io/?path=/story/input-select--lazy-loading-options
Unable to select the options after the Option 199 in this story book.

### URL, screen shot, or Codepen exhibiting the issue
https://storybook.grommet.io/?path=/story/input-select--lazy-loading-options

### Steps to Reproduce

Open https://storybook.grommet.io/?path=/story/input-select--lazy-loading-options
Scroll to Option 200
Select Option 200, it is not selected, if we close and open it, the option is selected but the selected value is not displayed in the Select Field.

### Your Environment

- Grommet version: 2.16.0
- Browser Name and version: chrome
- Operating System and version (desktop or mobile): Mac, Windows

**Comment by ShimiSun** [comment]
Thanks for reporting, we'll prioritize the issue.

**Comment by sabino-gadaleta** [comment]
> Thanks for reporting, we'll prioritize the issue. Can you confirm the behavior was working as expected on v2.15.2?

We did confirm inside our UI that the problem did not show up if we added a resolution that forced use of the v2.15.2 grommet version.

**Comment by halocline** [comment]
FYI, I did some initial investigation to track down where this regression was introduced.

Using git bisect (starting on the master branch) as follows:
```
git bisect start
git bisect bad
git bisect good v2.15.2
```

Identified https://github.com/grommet/grommet/pull/4778 as the commit which introduced the regression. 

I haven't researched beyond here, but the description in the PR "The problem was that options change when they are filtered using search. So indexes of selected values are invalid. Now we always use the initial list of options, so the indexes will always be valid." sounds as if the approach taken may not work in scenarios where the options are loaded using InfiniteScroll's onMore.

**Comment by ShimiSun** [comment]
@romanalesenkov1 FYI ⬆️

**Comment by sabino-gadaleta** [comment]
Just for more information. We had seen the issue too in our UI if we just render the select component before the options are fully loaded. So it's not only an issue with onMore maybe but a more general loss of binding if the options change after render.

**Comment by ShimiSun** [comment]
Thanks for sharing @sabino-gadaleta , we are prioritizing this issue and we'll release a hotfix to include a fix asap.

**Comment by romanalesenkov1** [comment]
As a workaround it is possible to re-render select when options changed :

![image](https://user-images.githubusercontent.com/13457738/101407273-b203de00-38eb-11eb-93c4-c7c5d74d1ac1.png)

At a first glance I didn't find the way to fix the problem without breaking changes.

It looks like we should make onChange function clear function: 
1. do not set filtered options in this function
2. return filtered options from
3. use this function in select to filter options

**Comment by halocline** [comment]
I have written tests for:
1. search+multiple select
1. lazy load more options and select

Will be working on fix today.
