### ISSUE TITLE
No Photoshop assets.

### ISSUE THREAD

**Issue by codehexss** [grommet/grommet#48]
The grommet.io homepage says "All the resources you could possibly need! Sticker sheets, Stencils, PSDs, and more. Simply click the app you use to get started." But the downloads section doesn't have psd assets.

All assets(except photoshop psds)  are available.

They are also not available in the design folder in the repo.

**Comment by bryanjacquot** [comment]
This is on our backlog; we just wrapped up a major revision of the AI file, and will now turn our attention to updating and creating the other formats.  Thanks for your interest.  If you are willing to contribute a PSD file, please let us know.  Others have expressed interest in this as well.

**Comment by bryanjacquot** [comment]
Dup of https://github.com/grommet/grommet-design/issues/15
