### ISSUE TITLE
In IE11 is the toggle checkbox a bit misplaced

### ISSUE THREAD

**Issue by Waize** [grommet/grommet#480]
Like the titel says... 
Here is a picture. 

![checkbox misplaced](https://cloud.githubusercontent.com/assets/16035154/14309486/0a4ba526-fbdd-11e5-9480-2beac7396147.PNG)

**Comment by kentsalcedo** [comment]
Not able to recreate, is anyone else able to recereate? Screenshot below is a screenshot of my toggle checkbox in ie11 and looks okay in Edge as well
![screen shot 2016-05-31 at 10 34 00 am](https://cloud.githubusercontent.com/assets/14192753/15689554/41065070-271b-11e6-9b49-cde852354234.png)

**Comment by alansouzati** [comment]
maybe this is outdated. @Waize can you confirm that you are still experiencing this issue in the latest grommet?

**Comment by Waize** [comment]
Hi, 

nope, this issue is outdated :)
