### ISSUE TITLE
Is it possible that do not show outline while focusIndicator is false?

### ISSUE THREAD

**Issue by seelikes** [grommet/grommet#4803]
### Expected Behavior

show no outline when i pointed that i do not want a outline when focused

### Actual Behavior
when i pointed that focusIndicator is false, it shows a dark outline.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/37497358/101129204-20227980-363c-11eb-88a3-a8ca5a0bd4e5.png)

### Steps to Reproduce

no need, 100% reproduce.

### Your Environment

- Grommet version: 2.16.0
- Browser Name and version: Microsoft Edge 87.0.664.52 64-bit
- Operating System and version (desktop or mobile):Windows 10

**Comment by ShimiSun** [comment]
The black outline isn't coming from grommet and unless you changed your theme to display it as black I'll question whether it is actually coming from grommet.

Regarding your frequent comment of 
> no need, 100% reproduce.

Please be mindful that providing code or at-least naming the component you are using could help us provide better guidance. I have no direction on how to currently reproduce the issue you are describing so I can't really help, just guess, so please do not assume the reproducing is obvious.

**Comment by ShimiSun** [comment]
I'll be closing this issue, feel free to reopen once all content is available for us to reproduce.
