### ISSUE TITLE
Layer does not animate on exit

### ISSUE THREAD

**Issue by alphonso06** [grommet/grommet#4809]
Based from the example [Notifications and Popovers.](https://codesandbox.io/s/9jpz0z2ym4?file=/components/Toast.js)

It should be noted that I currently have a much larger application but I create components in an isolated environment like Storybook. The steps below are relevant.

### Expected Behavior

Upon the timeout duration being reached, it should animate out, either slide or fade out.

### Actual Behavior

It disappears suddenly without animation.

### Steps to Reproduce

1. Copy the Toast.js and AccountCreated.js components
2. Use React Hook `useState` to determine whether or not it will be shown

### Attempted Solutions

1. I've tried putting `<Layer>` inside of a `<Collapsible>` component but it still disappears suddenly without animation
2. I added the `animation` prop to `<Layer>` and tried to set it - both as `slide` or `fadeIn` according to documentation but still no exit animation as seen in the codesandbox examples
3. I also tried the pattern [from this example.](https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=/layer&module=%2Fsrc%2FLayer.js)
4. Tried reinstalling dependencies but that didn't do anything.

### Current Workaround

I tried installing **2.16.0** and can confirm that does not have animation also. I downgraded individually from 2.15.2 to 2.12.0, all of which do not have the exit animation.

**At the moment it seems only v2.11.0 does not have this issue.**

### Environment

- Grommet version: **2.15.2**
- Browser Name and version: any
- Operating System and version: **Linux Mint 20**

**Comment by jcfilben** [comment]
Hi @alphonso06 I was not able to reproduce the issue with Layer not animating when it is closed. I created a PR with a new storybook example showing how to use Layer with a timeout function and animation.

**Comment by ShimiSun** [comment]
You can see on our storybook examples https://storybook.grommet.io/?path=/story/layout-layer--notification-layer that the Layer is exiting with the proper I/O animation using grommet v2.16.0. Please be more specific with your example and create a sandbox that reproduces the problem reliably, on the sandbox(es) you shared we saw no problem with the animation even after upgrading to latest grommet.

**Comment by kid-icarus** [comment]
@ShimiSun @jcfilben I just looked at https://storybook.grommet.io/?path=/story/layout-layer-notification--notification-layer and I'm not seeing any exit animations being run. I am also unable to see any exit animations with the Layer component in general.

**Comment by jcfilben** [comment]
Hi @kid-icarus thanks for letting us know the exit animation isn't working anymore. It looks like this was caused when we upgraded react-dom from v16 to v17. Here is a [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-mijxy?file=/index.js) showing the animation working correctly when react-dom is set to v16.14.0 if you switch it to v17 the animation will not longer work. I am in the process of finding a solution for this. I am reopening the issue until a solution is found
