### ISSUE TITLE
Using the <Menu> component with sub-components shows React warning in the browser console.

### ISSUE THREAD

**Issue by tromgy** [grommet/grommet#4811]
### Expected Behavior

Components render without warnings.

### Actual Behavior

The following seen in the browser console:

```
Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `Menu`, expected `function`.
```

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/12632548/101269858-16366e80-3741-11eb-8ff5-a30c89cf2a8a.png)

### Steps to Reproduce

1. Create a new React application: `npx create-react-app menu-app`
2. Change the directory to the newly created one: `cd menu-app`
3. Add Grommet: `yarn add grommet grommet-icons styled-components`
4. Replace the code in **src/App.js** with the code from this [story](https://storybook.grommet.io/?path=/story/controls-menu--item-with-icon)
5. Edit the code so that it has the `App` function again:

```
import React from 'react';

import { Grommet, Box, Menu, Text } from 'grommet';
import { grommet } from 'grommet/themes';
import { FormDown, Github, Slack } from 'grommet-icons';

function App() {
  return (
    <Grommet theme={grommet}>
      <Box align="center" pad="large">
        <Menu
          plain
          open
          items={[
            {
              label: <Box alignSelf="center">Github</Box>,
              onClick: () => {},
              icon: (
                <Box pad="medium">
                  <Github size="large" />
                </Box>
              ),
            },
            {
              label: <Box alignSelf="center">Slack</Box>,
              onClick: () => {},
              icon: (
                <Box pad="medium">
                  <Slack size="large" />
                </Box>
              ),
            },
          ]}
        >
          <Box direction="row" gap="small" pad="large">
            <FormDown />
            <Text>Menu with Icon on the left</Text>
          </Box>
        </Menu>
      </Box>
    </Grommet>
  );
}

export default App;
```
6. Run the app: `yarn start`
7. You will see the warning in the browser console, although all components render OK.

_Note_: If I remove the `<Box>` from under the `<Menu>` and add the `label` prop instead, the warning goes away. But, of course in this case the icon would be on the right, and I would also lose any other customization of the menu title display.

### Your Environment

- Grommet version: 2.16.0
- Browser Name and version: Chrome 87.0.4280.88
- Operating System and version (desktop or mobile): macOS Big Sur 11.0.1

**Comment by jcfilben** [comment]
Hi @tromgy I filed a PR [here](https://github.com/grommet/grommet/pull/4820) that updates the Menu/ItemWithIcon story so that it no longer has a warning. Based on the [grommet documentation](https://v2.grommet.io/menu#children), children of Menu should be passed in as a function through the prop `children` and button props can be passed to the children function. Thanks for raising this issue so that the storybook example can be fixed to show the correct usage.

**Comment by ShimiSun** [comment]
We should change the documentation to allow both `node` and `children` as types, similarly to how it is done for the Button. Fix will go on Menu/doc.js if anyone is interested in making a contribution.

**Comment by tromgy** [comment]
@ShimiSun, you meant `node` and `func`, right?

**Comment by ShimiSun** [comment]
@tromgy yes. I'll edit my answer to make it more clear.
