### ISSUE TITLE
Select element isn't multi unless options array has at least one element

### ISSUE THREAD

**Issue by REX500** [grommet/grommet#4812]
If you use a Select element and don't initially pass an array with at least one element, that select won't be initialised as a multi select even though you pass _multiple_ prop.

### Expected Behavior

Select should initialize as a multiselect regardless of the options parameter. Real life use case could be: you want to show options that are fetched from an array and therefor options param for the select would initially be empty.
Quick fix could be to prevent rendering the select until the array of options is created but that could lead to a bad UX.

### Actual Behavior

Element get's instantiated as a "quazy" select element. What I mean by that is that it passes an array on every change but that array always has just the value that is clicked on, not multiple values - which you would expect.
 
### URL, screen shot, or Codepen exhibiting the issue

```
let options = [];

setTimeout(() => options = [1, 2, 3 ...], 1000); <= this will cause the Select to be rendered as a semi-multi select

return (
           <Select
              placeholder="Select type..."
              multiple
              options={options}
              value={value}
              onChange={({ value }) => {
                updateValue('test', value)
              }}
              children={(option) => option.label}
            />);
```
### Steps to Reproduce

1. Create a select element and set options to an empty array
2. Miliseconds later pass a full array
3. On each click the value of onChange will be an array with ONLY ONE value even though you clicked on other values

### Your Environment

- React: 16.13.1
- Grommet version: 2.15.0
- Browser Name and version: Chrome (87.0.4280.88 (Official Build) (x86_64))
- Operating System and version (desktop or mobile): Mac OS (11.0.1 (20B50))

**Comment by ShimiSun** [comment]
Hi buddy, the Select multi behavior had changed on grommet v2.16.0, can you please upgrade and let us know if you still see a problem?

**Comment by REX500** [comment]
@ShimiSun will do!

**Comment by REX500** [comment]
Seems to be fixed so Im closing the isssue!
