### ISSUE TITLE
Infinite Scroll is missing key property.  

### ISSUE THREAD

**Issue by jlarso11** [grommet/grommet#4826]
Adding column with a Menu component in the render property of the data table should not throw a console error. 

Console error is thrown.   Key property missing with-in the DataTable component

https://codesandbox.io/s/grommetgrommet-sandbox-forked-ibpl3?file=/src/DataTable.js

Console error:  

Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Header`. See https://fb.me/react-warning-keys for more information.
    in TableCell (created by Header)
    in Header (created by DataTable)
    in table (created by Context.Consumer)
    in StyledComponent (created by StyledTable)
    in StyledTable (created by Table)
    in Table (created by Context.Consumer)
    in StyledComponent (created by StyledDataTable)
    in StyledDataTable (created by DataTable)
    in DataTable (created by _class)
    in div (created by Context.Consumer)
    in StyledComponent (created by StyledBox)

**Comment by ShimiSun** [comment]
I could make you sandbox work and reproduce the problem, I've isolated it to a smaller sandbox https://codesandbox.io/s/datatable-warning-9wuhc?file=/index.js. Feel free fork and add what is needed for the sandbox to work and reproduce the problem properly so we could take a look.

**Comment by jlarso11** [comment]
This one should work now and be simplified: https://codesandbox.io/s/datatable-warning-forked-hlcjz?file=/index.html

**Comment by ericsoderberghp** [comment]
Thanks for the example. I took a look at it and I think the reason there is no key is because the column rendering the Menu has no `property` defined for it. If I change that column definition to the following, the warning doesn't appear.
```{
  property: 'percent',
  header: 'hello',
  render: () => (
    <Menu
      icon={<More />}
      items={[{ label: 'View Details', key: 1, onClick: () => {} }]}
    />
  ),
},
```

**Comment by jlarso11** [comment]
That removes it for me as well.  Thanks!
