### ISSUE TITLE
Select with search is broken

### ISSUE THREAD

**Issue by sindhoora-r** [grommet/grommet#4829]
### Expected Behavior
When I search for an option in the Select field and select a particular option, it should be displayed in the Select Field.

### Actual Behavior

When we search for an option in the Select Field and select a option 'A' a different option is populated in the field.

### URL, screen shot, or Codepen exhibiting the issue
https://storybook.grommet.io/?path=/story/input-select--search

### Steps to Reproduce

https://storybook.grommet.io/?path=/story/input-select--search
Search for 'Option 10' and select 'Option 101' from the dropdown
Option 3 is being populated in the Select Field, where as Option 101 should be selected

### Your Environment

- Grommet version: 2.16.1
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): desktop

**Comment by ShimiSun** [comment]
Fixed and officially released on grommet v2.16.2. Thanks for reporting.
