### ISSUE TITLE
Typo in the sample code on grommet.io

### ISSUE THREAD

**Issue by tromgy** [grommet/grommet#4842]
The sample code for the `<Form>` component contains a typo

### Expected Behavior

The sample code at https://v2.grommet.io/form should say:
```
<FormField name="name" htmlFor="text-input-id" label="Name">
```

### Actual Behavior

The code contains a typo:

```
<FormField name="name" htmlfor="text-input-id" label="Name">
```

The property should be spelled **htmlFor**, not **htmlfor**

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/12632548/102803761-c5e91e80-4386-11eb-9ea8-be3efb6b2f2c.png)

### Steps to Reproduce

Open the following URL: https://v2.grommet.io/form

**Comment by leossantiago** [comment]
It seems component usage examples are handled directly on  [grommet/grommet-site](https://github.com/grommet/grommet-site). That being said, it can't be fixed from this repo.

**Comment by tromgy** [comment]
Ah, thanks. That's why I couldn'd find the code here. I'll submit a PR there.
