### ISSUE TITLE
TextInputProps type definition missing onSuggestionSelect

### ISSUE THREAD

**Issue by jkkealii** [grommet/grommet#4844]
### Expected Behavior

TextInputProps should include `onSuggestionSelect`

### Actual Behavior

`onSuggestionSelect` is missing from the `index.d.ts` file for TextInput

### URL, screen shot, or Codepen exhibiting the issue

https://github.com/grommet/grommet/blob/master/src/js/components/TextInput/index.d.ts#L26

### Steps to Reproduce

N/A

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: N/A
- Operating System and version (desktop or mobile): N/A

**Comment by jcfilben** [comment]
Looks like [this PR](https://github.com/grommet/grommet/pull/4848) has fixed the issue. I think this issue can be closed
