### ISSUE TITLE
Table placeholder property is typed wrong

### ISSUE THREAD

**Issue by mattoni** [grommet/grommet#4849]
### Expected Behavior

Adding a component as a placeholder to a table doesn't fail

### Actual Behavior

Fails with a typescript error. This appears to be because it's inheriting the default table element placeholder type, so it should be omitted from the properties.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/5110855/103309747-c313ac80-49ca-11eb-97f7-966e7e7744f5.png)

### Steps to Reproduce

1. Attempt to set anything besides a string as the placeholder to a table

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by mattoni** [comment]
Ah it appears the placeholder property only exists on the DataTable component, not the regular table.

**Comment by ShimiSun** [comment]
>Ah it appears the placeholder property only exists on the DataTable component, not the regular table. 

I think that might be it. Where have you seen documentation that supposed to support your issue as a valid behavior that is currently not working?

**Comment by mattoni** [comment]
I mixed up with Table vs DataTable, my fault!
