### ISSUE TITLE
[0.5.5] In node_modules/grommet/index.js './index-icons' module not valid

### ISSUE THREAD

**Issue by johnnyvcn** [grommet/grommet#485]
In 0.5.4, there is a index-icons.js in node_modules/grommet folder, this file is missing in 0.5.5, but the reference to it is still in node_modules/grommet/index.js:

Base: require('./index-icons')

My node version - 5.10.1, npm version - 3.8.5

**Comment by primozs** [comment]
Because index-icons is in .gitignore you can have this file still there and the problem is not noticed if you are building grommet yourself. For me this became visible when I build application for production with stable branch.

**Comment by primozs** [comment]
Hello @alansouzati,
This issue with index-icons still persist in the latest stable branch.
```
vendors.js:158 Uncaught Error: Cannot find module "./index-icons"
```
When I build "dev" I don't have this error only for production.
```
  Icons: {
    Grommet: require('./components/icons/Grommet'),
    Spinning: require('./components/icons/Spinning'),
    Status: require('./components/icons/Status'),
    Base: require('./index-icons') ****
  },
```

**Comment by primozs** [comment]
When I remove grommet from "vendors" in webpack config error disappears.

**Comment by bryanjacquot** [comment]
@johnnyvcn: the latest grommet should address this issue.  Please let us know if you're still having issues.
