### ISSUE TITLE
Chart type=area renders points in reverse order every other render

### ISSUE THREAD

**Issue by MikeKingdom** [grommet/grommet#4854]
When the Chart component renders a set of points in type=area mode it generates a closed SVG path of the points but on every other render it renders the path in reverse order.

This makes it a bit unpredictable which direction it draw the points. This is a problem for automated tests which could fail oddly. 

### Expected Behavior

The drawn area should be consistent and predictable for the same points.

### Actual Behavior

On first render points are drawn in the order they were passed in values.
On second render points are drawn in the reverse order.

(This happens because Chart.js renderArea does a .reverse() on the values array which permanently modifies the memo'd values array. Next render it will reverse them back again to the original order...ad nauseum,)

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Win10

**Comment by MikeWalrath** [comment]
#4856

**Comment by MikeKingdom** [comment]
Fixed by PR #4856
