### ISSUE TITLE
[0.5.5] Have to modify \node_modules\grommet\utils\gulp\eslintrc to run grommet ferret

### ISSUE THREAD

**Issue by johnnyvcn** [grommet/grommet#486]
To run'gulp dev' in grommet ferret root folder, I have to modify \node_modules\grommet\utils\gulp\eslintrc, remove this line:
block-scoped-var: 2

Otherwise, an exception is thrown:

aYAMLException: Cannot read config file: C:\grommet-ferret-master\node_modules\grommet\utils\gulp\eslintrc

Error: duplicated mapping key at line 62, column 22:
             block-scoped-var: 0

**Comment by bryanjacquot** [comment]
Should be fixed in latest grommet-toolbox.
