### ISSUE TITLE
Datatable theme header targets not working

### ISSUE THREAD

**Issue by TylerKienVu** [grommet/grommet#4860]
I am trying to customize the DataTable component with a theme. The specific target I am trying to use is `dataTable.header.color`. My goal is to use the header theme targets in order to customize the header for the data table.

I have found that some of the header targets do not seem to work properly. I am trying to use `dataTable.header.font.weight` specifically to make the headers bold. 

This is the current theme that I am using:

```
export const theme = deepMerge(grommet, {
  global: {
    colors: {
      brand: '#228BE6',
    },
    font: {
      family: 'HelveticaNeue',
      size: '18px',
      height: '20px',
    },
  },
  dataTable: {
    header: {
      font: {
        weight: 'bold',
        size: '30px',
      },
      background: 'red',
    },
  },
});
```

The background color changes correctly but the font weight and size for the header do not. For the weight I have tried using 'bold' and '800' without success. 

I found a story book where there is a custom theme applying `text-strong` to the theme target `dataTable.header.color`. That doesn't seem to have an effect on the example.

[Link to storybook](https://storybook.grommet.io/?path=/story/visualizations-datatable--custom)

### Expected Behavior

Expected behavior is that the theme selectors for the data table should work.

### Actual Behavior

The styles applied to the theme targets do not affect the styling for the component.

### URL, screen shot, or Codepen exhibiting the issue

This screenshot shows that the headers for the data table are applying the background `red` but not applying the font weight `bold` or font size `30px`

<img width="996" alt="Screen Shot 2021-01-05 at 12 16 32 PM" src="https://user-images.githubusercontent.com/15975780/103694532-f23c9780-4f4f-11eb-9b4b-5a4bee6a9b15.png">

### Steps to Reproduce

1. Apply theme for data table header font weight and size
2. Create data table

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: Google chrome 87.0.4280.88 (Official Build) (x86_64)
- Operating System and version (desktop or mobile): macOS Catalina 10.15.4

**Comment by ShimiSun** [comment]
Seems to work as expected for me, https://deploy-preview-4862--sad-tereshkova-173d07.netlify.app/?path=/story/visualizations-datatable--custom

Please take a look at my example and let me know if I'm missing anything.

**Comment by TylerKienVu** [comment]
Thank you @ShimiSun for helping me investigate this issue! I ended up realizing that the way that I was defining the header columns in the column definitions was the issue. Instead of providing a string for the header I was supplying a <Text> tag like so:

```
          {
            property: 'phone',
            header: <Text>Phone</Text>,
            size: 'small',
            render: (driver) => {
              return driver?.contact?.phone;
            },
          },

```

Changing the column header to `header: 'Phone'` fixed the issue. Thank you again for the help!
