### ISSUE TITLE
Tooltip showing on disabled button with custom label

### ISSUE THREAD

**Issue by Jam42** [grommet/grommet#4865]
When using Tip with disabled Button with custom label tooltip still appears

### Expected Behavior

Tooltip shouldn't appear

### Actual Behavior

Tooltip is appearing – and not hiding when mouse leave it

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-wlr22?file=/index.js

### Steps to Reproduce

1. Add Button with custom label and disable it
2. Wrap it with Tip
3. Hover over it

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: Brave v1.16.68 Chromium: 86.0.4240.111
- Operating System and version (desktop or mobile): macOS Big Sur

**Comment by ShimiSun** [comment]
I think the issue is with onMouseLeave of Button, and not with the Tip itself.

**Comment by sabarnix** [comment]
We have a use case to show tooltip on disabled button. We want to show the reason of disabling on tooltip. This could be a common use case. Can we allow tooltip on disabled buttons?

**Comment by jcfilben** [comment]
Hey @sabarnix currently we don't allow a tooltip to show on a disabled button because that would be an accessibility violation. People who use assistive technology wouldn't be able to interact with the tooltip.
