### ISSUE TITLE
Get theme colors

### ISSUE THREAD

**Issue by jpmazza** [grommet/grommet#4866]
Once I define my custom theme I would like to get the colors of my custom theme in some components, for example, to use my brand color in a StyleSheet. I want to apply the brand color in non-grommet components.

Chakra has the [`useTheme` hook](https://chakra-ui.com/docs/hooks/use-theme) which is useful in these cases.

Does grommet have something similar?

### Expected Behavior

Get my brand color in a component.

### Actual Behavior

I don't know how to access my theme values

### Your Environment

"grommet": "^2.16.2"
"react": "^17.0.1"

**Comment by MikeKingdom** [comment]
That's what ThemeContext is for.

```jsx
import React, {useContext} from 'react';
import { ThemeContext } from 'grommet';
import { normalizeColor } from 'grommet/utils';

const MyComponent = () => {
  const theme = useContext(ThemeContext);
  const brandColor = normalizeColor('brand', theme);
...
}
```
