### ISSUE TITLE
TextInput renders styled placeholders even when there is a value

### ISSUE THREAD

**Issue by MikeKingdom** [grommet/grommet#4867]
A TextInput that has a styled placeholder (`placeholder={<someJSX>}` rather than `placeholder="somestring"`) renders the placeholder even when the textinput has a value, at least until another render happens. 

### Expected Behavior

If a TextInput has a value (either from a value prop or by typing text in the input), the placeholder should not be shown.

### Actual Behavior

One first render the placeholder will be drawn whether or not the input has a value.
On next render, if the input has a value the placeholder will not be rendered. Note that typing in the text field does not cause a re-render so the typed text will overlap the placeholder.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/12054362/103911440-487e1780-50c3-11eb-97cd-bd6465f832be.png)

### Steps to Reproduce
```jsx
<Grommet>
    <h1>some content</h1>
    <TextInput
      data-testid="styled-placeholder"
      id="styled-placeholder"
      name="styled-placeholder"
      placeholder={<Text>placeholder text</Text>}
    />
</Grommet>
```

This happens because on first render, the inputRef is not defined yet and so this check in TextInput's render returns true even though a value was specified:
```javascript
const showStyledPlaceholder =
      placeholder &&
      typeof placeholder !== 'string' &&
      !(inputRef.current && inputRef.current.value);
```

There is also nothing that causes a re-render on typing text. Some onChange/setValue type of code is necessary to cause the input to re-render on input.

Note that there is a test case in TextInput-test that tries to make sure the placeholder doesn't get rendered but it only works if something causes the input to get rendered twice.
 
### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows10

**Comment by ShimiSun** [comment]
Might be related to https://github.com/grommet/grommet/pull/3659
