### ISSUE TITLE
HTML Component

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet#4871]
Explore creating a new grommet <Html /> component that could contain any valid HTML markup. This is intended for inline help content. The HTML elements would be styled according to the theme using something like styled.div(' h1 {} ...')

- [ ] include styling for  h1-h6, p, a, button, ul, ol, li, table (and related) elements
- [ ] do not include styling for fonts, background, and text colors, those should be coming from the outer context where `<Html />` is used.

## Deliverables

- [ ] Html.js, StyledHtml.js
- [ ] documentation in doc.js
- [ ] typescript typings in index.d.ts
- [ ] unit tests covering all of the styles
- [ ] storybook story

**Comment by ericsoderberghp** [comment]
Closing for now, until demand returns.
