### ISSUE TITLE
TextInput with suggestions with keyboard skips every other suggestion

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#4875]
### Expected Behavior

Using down arrow with textinput + suggestions should go through each suggestion.

### Actual Behavior

Down arrow goes to every other suggestion (skipping every other one).

### URL, screen shot, or Codepen exhibiting the issue
https://storybook.grommet.io/?path=/story/input-textinput--suggestions

### Steps to Reproduce

1. Click into text input
2. Use down arrow to navigate through suggestions
3. Notice that you only navigate to every other one

### Your Environment

- Grommet version: stable
- Browser Name and version: Chrome Version 87.0.4280.141
- Operating System and version (desktop or mobile): MacOS Mojave 10.14.6

**Comment by netochaves** [comment]
This problem is because `onUp` and `onDown` is called two times
First here:
https://github.com/grommet/grommet/blob/8a0fd52b8ae330a245525033b2f72c2ab1b09bbb/src/js/components/TextInput/TextInput.js#L265-L268

And here:
https://github.com/grommet/grommet/blob/8a0fd52b8ae330a245525033b2f72c2ab1b09bbb/src/js/components/TextInput/TextInput.js#L395-L415

I can open a PR to remove one of this but which one is safely to remove?

**Comment by halocline** [comment]
@ShimiSun I had just started looking into this but saw that you had assigned yourself.

Based on running `git bisect` I believe this was introduced in [this commit](https://github.com/grommet/grommet/pull/4864).

![Screen Shot 2021-01-26 at 4 17 41 PM](https://user-images.githubusercontent.com/1756948/105919228-75528a00-5ff2-11eb-9f95-b938a3806680.png)

I will shift focus to another issue.

**Comment by ShimiSun** [comment]
@netochaves Thank you!! Please review my associated PR and let me know what you think. I took the opportunity to do some cleanups along with the fix.

@halocline just saw your comment, feel free to read the analysis of the root cause on my associated PR.

**Comment by taysea** [comment]
Closing this issue since it was solved in the recent release: https://github.com/grommet/grommet/pull/4901
