### ISSUE TITLE
DataTable has lag showing hover style with large number of rendered rows

### ISSUE THREAD

**Issue by kariwhitcomb** [grommet/grommet#4881]
### Expected Behavior
DataTable's hover styling should be applied consistently fast, even with a large amount of data being shown

### Actual Behavior
Using DataTable with onClickRow and large number of rendered rows (ex 200) experiences noticeable lag in showing the hover style. 

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/dark-hooks-ctdl3?file=/src/App.js

![Screen Shot 2021-01-15 at 9 47 18 AM](https://user-images.githubusercontent.com/12547826/104756478-18fd8980-5719-11eb-887e-5a6e2fc86f5a.png)

### Steps to Reproduce

1. Use DataTable component with step={200}, data (with at least 200 rows of info), and onClickRow handler set
2. Use mouse to hover over rows in the table.  There is a noticeable lag in the hover styling being applied after mousing onto a row.
3. Check browser console (I use chrome) and you may see the Violation messages I screenshotted above indicating the mouseover and mouseout handlers are taking too long

I did poke through some of the performance/react profiler behavior... it appears that every mouse event is causing the whole table to rerender.  So the larger the table, the longer this takes.  It seems like it should only have to rerender a max of 2 rows (the one that used to have hover, and the one that does now) so not sure why it is rerendering everything.

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: Chrome latest
- Operating System and version (desktop or mobile): MacOS

**Comment by halocline** [comment]
Tagging potentially related https://github.com/grommet/grommet/issues/4559 & https://github.com/grommet/grommet/issues/3935.
