### ISSUE TITLE
Datatable thead not aligned with tbody when overflow is set to true

### ISSUE THREAD

**Issue by smartnexus** [grommet/grommet#4887]
### Expected Behavior
When I set the size of Datatable to a fixed height, it automatically fits table data to the fixed height adding an overflow bar(as html by default), but when that scroll bar is being displayed table tbody width reduces and thead does not reduces with the same anchor.

### Actual Behavior
Datatable does not resize thead to keep the columns aligned.

### URL, screen shot, or Codepen exhibiting the issue
Columns not being aligned.
![image](https://user-images.githubusercontent.com/6134261/105168763-dd98fb80-5b1a-11eb-9f12-e4756518ee5f.png)
------------------------------------------------------------------------------------------------------------
Fixed adding padding to last th element of thead.
![image](https://user-images.githubusercontent.com/6134261/105168627-aa566c80-5b1a-11eb-84ad-0c1f811f8b1c.png)

### Steps to Reproduce

1. Create datatable element with data.
2. Add "size" property to DataTable component.

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: Firefox 84.0.2
- Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by ShimiSun** [comment]
Thank you for reporting!

**Comment by smartnexus** [comment]
What is the expected time to solve this?

**Comment by ericsoderberghp** [comment]
We are always ready to review pull requests. :)

**Comment by ShimiSun** [comment]
Thanks for reporting, the fix will be available in the coming release.
