### ISSUE TITLE
Replace dependency of awesome-typescript-loader

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#4894]
### Expected Behavior
awesome-typescript-loader is archived and no longer maintained. 
We should replace this dependency with other alternatives so we wouldn't receive unmaintained warnings.

### Actual Behavior
awesome-typescript-loader is currently throwing a peer-dependency warning during installation
> awesome-typescript-loader@5.2.1" has incorrect peer dependency "typescript@^2.7 || ^3"

### Steps to Reproduce

1.  run `yarn install` and see the warning

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version:Any
- Operating System and version (desktop or mobile): Any

**Comment by joaoGabriel55** [comment]
Nice @ShimiSun, I will take a look

**Comment by ShimiSun** [comment]
@joaoGabriel55 awesome buddy, let us know how it goes

**Comment by joaoGabriel55** [comment]
I trying now to replace `awesome-typescript-loader` to `ts-loader`.

**Comment by jcfilben** [comment]
I think this issue can be closed since #4918 was merged
