### ISSUE TITLE
In Select component: TypeError: setting getter-only property "target"

### ISSUE THREAD

**Issue by simonv3** [grommet/grommet#4915]
When using the `Select` component and choosing an option, the error `TypeError: setting getter-only property "target"` at Select.js:168

### Expected Behavior

In the select dropdown I should be able to select an option.

### Actual Behavior

An TypeError gets thrown. 

### URL, screen shot, or Codepen exhibiting the issue

```
import { FunctionalComponent, h } from "preact";
import { useState } from "preact/hooks";
import { Link } from "preact-router/match";
import styled from "styled-components";
import { Box, Button as GrommetButton, Select } from "grommet";

const H1 = styled.h1`
  float: left;
  margin: 0;
  padding: 0 1rem;
  font-size: 1.2rem;
  line-height: 56px;
  font-weight: 400;
  color: var(--color-sdg-blue);
`;

const REGIONS = [
  "Africa",
  "Arab States",
  "Asia and the Pacific",
  "Europe and Central Asia",
  "Latin America and the Carribbean"
];

const Header: FunctionalComponent = () => {
  const [regionSearchValue, setRegionSearchValue] = useState<string>("");
  const [regionOptions, setRegionOptions] = useState<string[]>(REGIONS);

  return (
    <div>
      <Box direction="row" className="logo" align="center">
        <img width={100} src="assets/logos/logo_elkano.png" alt="" />

        <H1>Data Portal</H1>
      </Box>
      <Box direction="row" as="nav" align="center" gap="small">
        <Select
          plain
          value={regionSearchValue}
          onChange={(event): void => {
            console.log("event", event);
            // console.log("event", event.value);
            setRegionSearchValue(event.value);
          }}
          placeholder="Region"
          options={regionOptions}
        />
        <GrommetButton color="primary" label="Login" />
      </Box>
    </div>
  );
};

export default Header;
```

### Steps to Reproduce

![grommet](https://user-images.githubusercontent.com/485583/106530523-585e0100-64a1-11eb-9b21-a862d8555af9.gif)

### Your Environment

- TypeScript version: 4.1.2
- Grommet version:    from package.json: "^2.16.2"
- Browser Name and version: Firefox 85.0
- Operating System and version (desktop or mobile): Linux Mint 20 Cinnamon 4.6.7

**Comment by joaoGabriel55** [comment]
Can I work on this?

**Comment by joaoGabriel55** [comment]
Hello @simonv3! I simulate your error on codesandbox (https://codesandbox.io/s/tender-borg-sm114?file=/src/App.tsx) and I do not had your error, quoted above. Can you explain more about your problem?

**Comment by ShimiSun** [comment]
@joaoGabriel55 Definitely! Go for it

**Comment by simonv3** [comment]
@joaoGabriel55 thanks for trying to reproduce. I've unfortunately moved on from using Grommet because I needed a framework that I could work with. I wonder if it's somehow related to using React vs Preact? But the type error is being thrown by Grommet, so that seems odd to me.

**Comment by jcfilben** [comment]
In Grommet's storybook, Select has a typescript example [here](https://storybook.grommet.io/?path=/story/input-select-create-option--create-option) that is working correctly and not giving any errors where you choose an option. Since we care unable to reproduce the issue I think this can be closed

**Comment by ShimiSun** [comment]
Hello @simonv3 ,  thanks for reporting. As @jcfilben suggested, please find a reliable reproducible code so we can troubleshoot the problem. Feel free o reopen the issue if you find it still relevant.
