### ISSUE TITLE
Grommet Sidebar component issue

### ISSUE THREAD

**Issue by arjunbm468** [grommet/grommet#492]
The &lt;hr&gt; tag inside the Colored Context Sidebar component should be white in color.

One more issue is that when we minimize the browser, there is extra space is inserted between menu items inside the Sidebar.

The below code pen will demonstrate the issue:
http://codepen.io/arjunbm/pen/pydoRG

@alansouzati @ericsoderberghp

**Comment by alansouzati** [comment]
Please use separator where you want to break.

See one possible way to do this:

http://codepen.io/alansouzati/pen/vKxPmK?editors=0010
