### ISSUE TITLE
Migrating to v2 - Split component

### ISSUE THREAD

**Issue by Waize** [grommet/grommet#4926]
Hey there,

I'm planning to upgrade our existing Projects from v1 to v2. 
After reading the migration docs and Checking the components which needs to be replaced, I stumbled over the [Split-Component](https://v1.grommet.io/docs/split) from Version 1. 

Is there any recommended Component to migrate to or any other ideas? 
Do we have to implement a Split on our own? 

The answer should be added to the [2.0 Migration Guide](https://github.com/grommet/grommet/wiki/2.0-Migration-Guide).

Thanks!

**Comment by ShimiSun** [comment]
Hi, thanks for reaching out.
Split is opinionated and depends on the use case, in the v1 docs example, it demonstrates a sidebar, so we'll recommend using the Sidebar component in a layout context, see some examples here https://design-system.hpe.design/templates/page-layouts

Let me know if that helps,
Shimi

**Comment by Waize** [comment]
Thank you for the quick response! 

Great idea, thanks for the link :)
