### ISSUE TITLE
Typings on Text component are incorrect on the latest release

### ISSUE THREAD

**Issue by andrewthamcc** [grommet/grommet#4928]
The latest release of Grommet [(2.16.3)](https://github.com/grommet/grommet/releases/tag/v2.16.3) includes new additional sizes for the Text component. The typings for these new sizes are incorrect in that these properties are not optional.

```
'2xl?': {
      size?: string;
      height?: string;
      maxWidth?: string;
    };
3xl?': {
      size?: string;
      height?: string;
      maxWidth?: string;
    };
'4xl?': {
      size?: string;
      height?: string;
      maxWidth?: string;
    };
'5xl?': {
      size?: string;
      height?: string;
      maxWidth?: string;
    };
'6xl?': {
      size?: string;
      height?: string;
      maxWidth?: string;
    };
    '
```

These sizes should be optional. The optional property should not be within the string value of the key. 

### URL, screen shot, or Codepen exhibiting the issue

[Source in Code - lines: 1194 - 1217](https://github.com/grommet/grommet/blob/2fb2ffe5ee8d272f31196a8b5f82e8324f9707e0/src/js/themes/base.d.ts)

### Steps to Reproduce

Running Grommet with TypeScript causes these properties to be non-optional with custom themes.

### Your Environment

- Grommet version: ^2.15.2
- Browser Name and version: Chrome Version 88.0.4324.96
- Operating System and version (desktop or mobile): Mac OS Catalina 10.15.7

**Comment by ShimiSun** [comment]
hi buddy, that latest release is 2.16.3, are you sure about the version you have listed 2.15.2?

**Comment by andrewthamcc** [comment]
That's copied from my `package.json` file. The carat is a semver range which will update to anything less than 3.0.0

[semver](https://docs.npmjs.com/cli/v6/using-npm/semver)

**Comment by ShimiSun** [comment]
Thanks, feel free to make a contribution, this feature was introduced on 2.16.3 so that will be the explicit version of the issue for whoever tries to fix it.

**Comment by ShimiSun** [comment]
Thank you for reporting and fixing the issue 💟

**Comment by andrewthamcc** [comment]
> Thank you for reporting and fixing the issue 💟

My pleasure! It was a simple fix. I was especially motivated because the latest release broke our Builds and CI/CD at work.  We just rolled our versions back.
