### ISSUE TITLE
RadioButtonGroup Options Text Color

### ISSUE THREAD

**Issue by wguerram** [grommet/grommet#4935]
How do I change the text color?

I can't find in the documentation how to change the RadioButtonGroup text color

The text is not changing color no matter what I try.

### Steps to Reproduce

Simple put a RadioButtonGroup, I can't find a way to change the text color.

### Your Environment

Windows 10

- Grommet version: 2
- Browser Name and version: Chrome 88.0.4324.146
- Operating System and version (desktop or mobile): Windows 10

**Comment by ryanadhibit** [comment]
```
<RadioButtonGroup
          name="radio"
          options={[
            { label:<Text color='red'>Choice 1</Text>, value: 'c1' },
            { label: <Text color='blue'>Choice 2</Text>, value: 'c2' },
            { label: <Text color='green'>Choice 3</Text>, value: 'c3' },
          ]}
          value={value}
          onChange={event => setValue(event.target.value)}
          {...props}
        />
```

this one would do it, right?

**Comment by jcfilben** [comment]
It may also help to take a look at [this storybook example](https://storybook.grommet.io/?path=/story/input-radiobuttongroup--custom-radio-button-group) that shows RadioButtonGroup with a custom theme to customize the colors. You can look at the RadioButton documentation to learn more about the theme options https://v2.grommet.io/radiobutton.

**Comment by wguerram** [comment]
Thanks @ryanadhibit and @jcfilben

**Comment by ShimiSun** [comment]
> Thanks @ryanadhibit and @jcfilben

@jcfilben just modified the storybook example to demonstrate your request on the storybook source code, you can see it live now https://storybook.grommet.io/?path=/story/input-radiobuttongroup-custom-theme--custom-radio-button-group
