### ISSUE TITLE
Storybook - Remove the OTHERS package

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#4943]
Looking good, I don't think we need the "Others" package anymore, we can move the one last item of "Theme" to utils and remove the "Others" package. we can do it on a separate PR though.

_Originally posted by @ShimiSun in https://github.com/grommet/grommet/issues/4941#issuecomment-775556749_

**Comment by joybh98** [comment]
if no one else has shown interest, I'll be happy to work on it

**Comment by ShimiSun** [comment]
@joybh98 go for it buddy! Good to see you see back
