### ISSUE TITLE
Grommet V1 Toast is not supporting localization

### ISSUE THREAD

**Issue by SubhrajyotiShaseni** [grommet/grommet#4946]
I'm trying to localize the message of a Toast component and I'm unable to do it.

The code I'm using like below
 let toastMessage = ( <FormattedMessage id="hf.unsupported.message" defaultMessage="default We have detected"/> );
<Toast status='warning' >{toastMessage}</Toast>
Here "hf.unsupported.message" is the key I'm using for the different localized message in json file. 

Is there any limitation from the internal implementation of the Toast to make the message localized?

Just to note:
The exact same code is working perfectly fine for other components like Heading, Notification etc.
<Heading tag="h4" align="center" >{toastMessage}</Heading>  --> Working fine

### Expected Behavior

The Toast should read the message from the json file using the key

### Actual Behavior

The Toast is always reading the default English language

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/32291884/107507800-1aaa5800-6bc6-11eb-942e-388f53787ed9.png)

### Steps to Reproduce

N/A

### Your Environment

- Grommet version: V1
- Browser Name and version: Google Chrome is up to date Version 88.0.4324.150 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows 10

**Comment by ShimiSun** [comment]
Hello, we are no longer extending functionalities for grommet v1, please see the templates provided for Toast and Notification on grommet v2 https://codesandbox.io/s/9jpz0z2ym4

Cheers
