### ISSUE TITLE
Remove double focus on some FormField components

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#4947]
### Expected Behavior
Each FormField component should have a single focus on the Formfield itself rather than both the input field and the FormField itself. Similarly to how TextInput works inside FormField.

The issue should be fixed for:
* RadioButton
* CheckBox
* Group components
* RangeInput
* Select

### Actual Behavior
Each FormField component has two focus indicators, one for the FormField and the other for the input field.

### URL, screen shot, or Codepen exhibiting the issue

https://user-images.githubusercontent.com/6320236/107573065-44558600-6baa-11eb-832f-4b3e77ae2328.mov

### Steps to Reproduce

1. https://storybook.grommet.io/?path=/story/input-form-custom--custom 
2. See the double focus behavior of the components listed above.

### Your Environment

- Grommet version: 2.16.3
- Browser Name and version: any
- Operating System and version (desktop or mobile): any

**Comment by Isaius** [comment]
this still unsolved @ShimiSun ? The #4930 seems to be solving this, but the last update was a few weeks ago.

**Comment by g4rry420** [comment]
#4930 resolves only for the checkbox. I think similar logic can be applied to resolve another components also.

**Comment by jcfilben** [comment]
Update on which components the double focus issue has been fixed on:
- [x] RadioButton
- [x] CheckBox
- [x] Group components
- [ ] RangeInput
- [x] Select
