### ISSUE TITLE
Child component for DataTable component

### ISSUE THREAD

**Issue by anoopadvaitha** [grommet/grommet#4952]
I was looking at having a sub component for the Datatable rows. At HPE we use tables a lot and this is one of the requirement for us. It is something available in majority of Table components available outside Grommet.

### Expected Behavior
Option to have a childComponent to a Datatable row.

### Actual Behavior
No way to provide a chidComponent.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/5357867/107683204-4e20db80-6cc7-11eb-8902-124eb5fb9daa.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.16.3
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10

**Comment by anoopadvaitha** [comment]
I have managed to implement something in these lines. Is it open for a PR ? 
Will share the storybook link soon

**Comment by anoopadvaitha** [comment]
Please find the link for the storybook
Let me know if this is acceptable for you.
https://www.chromatic.com/component?appId=602aa3d849721200238dcf29&name=Visualizations%2FDataTable%2FchildComponent&buildNumber=2

**Comment by ericsoderberghp** [comment]
I would use this story as the basic design direction: https://storybook.grommet.io/?path=/story/visualizations-datatable-grouped--grouped-data-table
I think we can restrict that you cannot group and have row detail rendering in the same DataTable.
I am open to a pull request for this functionality.

**Comment by anoopadvaitha** [comment]
@ericsoderberghp  Thanks for the input will try to address your comments and open a PR.

**Comment by anoopadvaitha** [comment]
@ericsoderberghp Regarding the restriction of not allowing both group and childComponent. I'm thinking of going with an approach of ignoring the childComponent if groupBy prop is provided rather than throwing the error. Please let me know your thoughts will change accordingly
