### ISSUE TITLE
SkipLinks component tab functionality only works on Chrome browser

### ISSUE THREAD

**Issue by nakaz** [grommet/grommet#4953]
### Expected Behavior

When tabbing from the address bar in a browser, the SkipLinks component should be rendered. 

This only works on the Chrome browser but not Firefox and Safari

### Actual Behavior

On Firefox and Safari, the component is never triggered or rendered. 

### Steps to Reproduce

1. Go to https://v2.grommet.io/skiplinks on the Firefox and/or Safari browser.
2. Hit tab multiple times. 
3. Confirm that the component does not render/appear.

### Your Environment

- Grommet version: Whatever version the grommet.io site is using.
- Browser Name and version: Firefox and Safari
- Operating System and version (desktop or mobile): macOS

**Comment by ShimiSun** [comment]
Thanks for reporting!

**Comment by ShimiSun** [comment]
@nakaz, I took a look at the issue and the functionality seems to work as expected.

I tried to understand what you might be experiencing, and if you are using a MAC [this might be your issue](https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox):

HINT: 
> On your MAC, go to System Preferences → Keyboard, in the Shortcuts pane, check the “all controls” radio at the bottom.

Restart your FF and that should do the trick.

Here is a quick video from running it on FF and verifying it works as expected:
https://user-images.githubusercontent.com/6320236/108777736-832bfa00-7521-11eb-9597-0e96b2c4aaaf.mov

**Comment by nakaz** [comment]
Confirmed that it was due to lack of accessibility options set via the machine/client/user. Component appears to work as expected.
