### ISSUE TITLE
optional text props types is not applied to latest 2.16.3 version

### ISSUE THREAD

**Issue by worst-developer** [grommet/grommet#4962]
**The problem:** [commit]( https://github.com/grommet/grommet/commit/e48684ed4898bf0155e84bea3ff70938068d73a1
) is not applied to the same version that I am installing from npm (2.16.3 )
 
### Expected Behavior 
Use text types schema same as in master branch

 `"2xl"?` instead of `"2xl?"` and so on 3,4,5,6

### Actual Behavior
My local version of grommet is `2.16.3` but it is still using old text types schema with wrong not required type assignment.
The error: 
```ts
(property) text?: {
    extend?: ExtendType<Record<string, any>>;
    xsmall?: {
        size?: string;
        height?: string;
        maxWidth?: string;
    };
    small?: {
        size?: string;
        height?: string;
        maxWidth?: string;
    };
    medium?: {
        ...;
    };
    ... 7 more ...;
    '6xl?': {
        ...;
    };
} & {
    ...;
}
Type '{ xxsmall: { size: string; height: string; maxWidth: string; }; xsmall: { size: string; height: string; maxWidth: string; }; small: { size: string; height: string; maxWidth: string; }; xmedium: { size: string; height: string; maxWidth: string; }; medium: { ...; }; large: { ...; }; xlarge: { ...; }; xxlarge: { ...; }...' is not assignable to type '{ extend?: ExtendType<Record<string, any>>; xsmall?: { size?: string; height?: string; maxWidth?: string; }; small?: { size?: string; height?: string; maxWidth?: string; }; medium?: { ...; }; ... 7 more ...; '6xl?': { ...; }; } & { ...; }'.
  Type '{ xxsmall: { size: string; height: string; maxWidth: string; }; xsmall: { size: string; height: string; maxWidth: string; }; small: { size: string; height: string; maxWidth: string; }; xmedium: { size: string; height: string; maxWidth: string; }; medium: { ...; }; large: { ...; }; xlarge: { ...; }; xxlarge: { ...; }...' is missing the following properties from type '{ extend?: ExtendType<Record<string, any>>; xsmall?: { size?: string; height?: string; maxWidth?: string; }; small?: { size?: string; height?: string; maxWidth?: string; }; medium?: { size?: string; height?: string; maxWidth?: string; }; ... 7 more ...; '6xl?': { ...; }; }': '2xl?', '3xl?', '4xl?', '5xl?', '6xl?'ts(2322)
base.d.ts(1163, 3): The expected type comes from property 'text' which is declared here on type 'ThemeType & CustomThemeType'
```

#### This what I am having locally:

![image](https://user-images.githubusercontent.com/7397161/107947060-8875cb80-6f9a-11eb-8d6d-8385231aca2f.png)

![image](https://user-images.githubusercontent.com/7397161/107947160-ae02d500-6f9a-11eb-9d57-38c877613722.png)

In my package.json
![image](https://user-images.githubusercontent.com/7397161/107947318-e6a2ae80-6f9a-11eb-9faa-193ee493ccec.png)

### Steps to Reproduce
1. Install latest grommet
2. look on your local text types and master on the github repo

### Your Environment

- Grommet version: 2.16.3
- Browser Name and version: -
- Operating System and version (desktop or mobile): mac, linux

**Comment by ShimiSun** [comment]
Hi buddy, thank you for reporting, this issue was already fixed on https://github.com/grommet/grommet/pull/4929. The next official release will include this fix. In the meanwhile, you can use the stable branch to include the fix locally.  https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F
