### ISSUE TITLE
FormField error size theme property not documented

### ISSUE THREAD

**Issue by raywong-fb** [grommet/grommet#4964]
### Expected Behavior

The documentation for [formField](https://github.com/grommet/grommet/blob/master/src/js/components/FormField/doc.js) should include an entry for `formField.error.size`.

### Actual Behavior

There is no documentation for the theme field `formField.error.size` even though it appears to work.

- Grommet version: 2
- Browser Name and version: all
- Operating System and version (desktop or mobile): both

**Comment by g4rry420** [comment]
Can I work on this issue ?
