### ISSUE TITLE
copy & links in blog header hard to read

### ISSUE THREAD

**Issue by djksar** [grommet/grommet#497]
in the previous version of the blog we had the blog post title, author name and addthis link in a white box underneath the header image. Now it is over-layed on-top of the header image and hard to read.

**Comment by alansouzati** [comment]
Agreed we need to review this. I will talk to @L0ZZI. I assume this is the same problem we have today in the home page for both blog versions right?

**Comment by djksar** [comment]
It's not the same problem. in the header of the image we did a cut-out to fit in the copy and links. Take a look at the below screenshots. 

what it looks like:
![the_great_grommet_podcast__episode_two___grommet_blog](https://cloud.githubusercontent.com/assets/5169327/14567669/17215aca-02ea-11e6-96af-7014cdce88ee.png)

what the comparable post looks like now:
![top_5_rules_for_giving_enterprise_apps_a_consumer-grade_ux___grommet_blog](https://cloud.githubusercontent.com/assets/5169327/14567816/b5da057c-02ea-11e6-9ec7-1f76e8927f83.png)
