### ISSUE TITLE
[TS] Layer prop `background` doesn't work

### ISSUE THREAD

**Issue by AlexandrChebotar** [grommet/grommet#4976]
I see prop `background` in Layer component documentation - https://v2.grommet.io/layer#background. But it's not work at all. Please fix it or at least update documentation.

### Expected Behavior

Layer prop `background` should change LayerContainer background

### Actual Behavior

LayerContainer background provided only over theme

### URL, screen shot, or Codepen exhibiting the issue

That prop even not exists in type declarations:
```typescript
export interface LayerProps {
  animate?: AnimateType;
  animation?: 'none' | 'slide' | 'fadeIn' | boolean;
  full?: boolean | 'vertical' | 'horizontal';
  margin?: MarginType;
  modal?: boolean;
  onClickOutside?: (...args: any[]) => any;
  onEsc?: KeyboardType;
  plain?: boolean;
  position?: LayerPositionType;
  responsive?: boolean;
  target?: object;
}

declare const Layer: React.ComponentClass<LayerProps &
  JSX.IntrinsicElements['div']>;

export { Layer };
```

### Your Environment

- Grommet version: 2.16.3

**Comment by britt6612** [comment]
@AlexandrChebotar can you share a code snippet of how you were trying to use the `background`  

https://codesandbox.io/s/layer-background-gfg7p

I created a quick example of using a pink background. I agree this should be in the type declarations I can add that.

**Comment by abnersajr** [comment]
The prop background is supposed to be inherited from `JSX.IntrinsicElements['div']`.
However if you are extending the `LayerProps` interface you will not have access to this prop. Because the `Union` between `LayerProps` and `JSX.IntrinsicElements` it's defined on the `declare` scope.

You can see a similar issue where one prop didn't exist in the `<Component>Props` if you try to extend it.
https://github.com/grommet/grommet/pull/4909

**Comment by AlexandrChebotar** [comment]
@ShimiSun @britt6612 @abnersajr sorry, my bad... something was wrong with my updates. I saw version 2.16.3 in yarn.lock, but behavior was the same. So I have created this issue and passed background to container this way - `style={{ background: "transparent" }}`
I have now reinstalled dependencies and all ok.
