### ISSUE TITLE
Grommet stable tarball seems to be corrupt

### ISSUE THREAD

**Issue by ypinneka** [grommet/grommet#4988]
Getting this error now, when trying to do `npm i` while pointing grommet to `https://github.com/grommet/grommet/tarball/stable`

npm WARN tarball tarball data for grommet@https://github.com/grommet/grommet/tarball/stable (sha512-MEDE183OmgHdMTjvFNwuSEa1/9hfNWoxfxQN2mqCNt/v2A580eB97skRjMGfV0JVgwtHh4jNQSWwBBqsanSkzg==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for grommet@https://github.com/grommet/grommet/tarball/stable (sha512-MEDE183OmgHdMTjvFNwuSEa1/9hfNWoxfxQN2mqCNt/v2A580eB97skRjMGfV0JVgwtHh4jNQSWwBBqsanSkzg==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-MEDE183OmgHdMTjvFNwuSEa1/9hfNWoxfxQN2mqCNt/v2A580eB97skRjMGfV0JVgwtHh4jNQSWwBBqsanSkzg== integrity checksum failed when using sha512: wanted sha512-MEDE183OmgHdMTjvFNwuSEa1/9hfNWoxfxQN2mqCNt/v2A580eB97skRjMGfV0JVgwtHh4jNQSWwBBqsanSkzg== but got sha512-hqOhm7T94bjjYIN2COoMYPoio1W9MjvUd0QNzHLi6ehf2HUC1Z+LVLfH8GUfI2+gPiQ4tSn+f8HQbKu2G4t/pw==. (2160569 bytes)

**Comment by ypinneka** [comment]
Hi @ericsoderberghp,
any idea about this ?

**Comment by ShimiSun** [comment]
You need to update your hash of grommet-stable, clean cache and rebuild the grommet stable dependency.
If you are using yarn it would be something like:
```
rm -rf yarn.lock
yarn cache clean
yarn install
```

*****
`npm cache clean --force`

**Comment by ypinneka** [comment]
> You need to update your hash of grommet-stable, clean cache and rebuild the grommet stable dependency.
> If you are using yarn it would be something like:
> 
> ```
> rm -rf yarn.lock
> yarn cache clean
> yarn install
> ```
> 
> `npm cache clean --force`

Thanks, Got it !
