### ISSUE TITLE
MaskedInput not accepting input

### ISSUE THREAD

**Issue by versoworks** [grommet/grommet#5002]
Using the sample at https://v2.grommet.io/maskedinput with either the latest versions of Chrome or Edge, the MaskedInput does not accept input. Either typing or with the mouse selecting an option from the drop list.

**Comment by ShimiSun** [comment]
This is probably just an issue on the website example, all the MaskedInput on our storybook works as expected
https://storybook.grommet.io/?path=/story/input-maskedinput-date--date-masked-input

Unless you think the component itself has an issue, I'll move this issue to the grommet-site repo.

**Comment by versoworks** [comment]
@ShimiSun I can confirm the storybook examples work. The reason for raising the issue is we're experiencing it within our own implementation of MaskedInput and can not pinpoint the cause. Any advice as to the cause ?

**Comment by ShimiSun** [comment]
Can you share a code sandbox of what you are trying to do? The issue is probably with how the value is being updated. Here is a template of grommet you can use to share your code more easily https://codesandbox.io/s/m7mml8l0zj

**Comment by versoworks** [comment]
@ShimiSun thanks for the tip; the issue was indeed caused by how the value was being updated.
