### ISSUE TITLE
Video component does not work in Safari

### ISSUE THREAD

**Issue by nakaz** [grommet/grommet#5007]
### Expected Behavior

Video component should be rendered and usable on the browser (Safari) 

### Actual Behavior

Does not display any video content. Some values are `NaN`

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/2155125/109240189-eae57d80-778b-11eb-999a-71bf6dd7a834.png)

### Steps to Reproduce

1. Navigate to https://v2.grommet.io/video on Safari

### Your Environment

- Grommet version: Version that is on Grommet.io 
- Browser Name and version: Safari 14.0.3
- Operating System and version (desktop or mobile): macOS 10.14

**Comment by ShimiSun** [comment]
Works as expected on Safari for me, please provide more details in case we are missing something.

https://user-images.githubusercontent.com/6320236/109242516-7d8c1980-7798-11eb-832f-58ce6cb98dbc.mov

**Comment by RyanCCollins** [comment]
Works for me as well.

**Comment by ShimiSun** [comment]
@nakaz Feel free to reopen the issue once you have a reproducible code for us to troubleshoot.
