### ISSUE TITLE
Selectable data tables, header checkbox not aligning correctly with body checkboxes

### ISSUE THREAD

**Issue by mgh5** [grommet/grommet#5011]
Upgrade to Grommet version: 2.16.3, is causing header checkbox in selectable tables not to align correctly with the body checkboxes.  Please see screen shot.

<img width="142" alt="Screen Shot 2021-02-26 at 12 00 30 PM" src="https://user-images.githubusercontent.com/78939064/109351397-11f48b80-782e-11eb-9880-bee05aca311a.png">

**Comment by halocline** [comment]
I believe this is related to the HPE Theme, and should be filed at this repository https://github.com/grommet/grommet-theme-hpe/issues.  @mgh5, would you be able to file the issue there?

**Comment by mgh5** [comment]
Filed issue #170 with HPE Theme.  Thanks.

**Comment by ShimiSun** [comment]
Correct link https://github.com/grommet/grommet-theme-hpe/issues/170, I'll close this issue.
