### ISSUE TITLE
Form's valid prop inside onValidate() callback not returning accurate value for checkbox

### ISSUE THREAD

**Issue by shreyashah7** [grommet/grommet#5012]
I have a form with some required input fields and required checkbox. onValidate() callback is not returning correct value for checkbox and it always returns false. If i remove checkbox, it works fine.

### Expected Behavior

Needs to check checkbox and return correct value

### Actual Behavior

Not returning correct value

CC: @ypinneka

**Comment by ypinneka** [comment]
https://github.com/grommet/grommet/pull/5014

**Comment by ShimiSun** [comment]
Thanks for the contribution @ypinneka , can we close this issue?  Or are there more functionalities that are expected as part of this issue?

**Comment by ShimiSun** [comment]
I think this issue could be closed. Feel free to reopen if needed.
