### ISSUE TITLE
Icons misaligned inside of dropdown menu

### ISSUE THREAD

**Issue by nickjvm** [grommet/grommet#502]
Because of padding on icons, when used inside of a drop menu anchor the anchor is pushed to the right. Additionally, icons are not aligned vertically with the link text.

```
<Menu size="small" inline={false}>
  <Anchor icon={<PauseIcon size="small"/>}>
    Suspend
  </Anchor>
  <Anchor icon={<PowerIcon size="small"/>}>
    Power On
  </Anchor>
  <Anchor icon={<PowerIcon size="small"/>}>
    Power Off
  </Anchor>
  ...
</Menu>
```
![drop](https://cloud.githubusercontent.com/assets/4998403/14617330/0e7eb1f0-056b-11e6-8a00-06c4876e72ab.jpg)

**Comment by jwijay** [comment]
Closing issue, since it appears resolved from merged PR:
https://github.com/grommet/grommet/pull/509

![screen shot 2016-06-20 at 11 22 27 am](https://cloud.githubusercontent.com/assets/10161095/16210757/69b3ce62-36d9-11e6-8154-841cb2a59c32.png)

```
<Menu inline={false}>
  <Anchor href="#" className="active" icon={<Configuration />}>
    First
  </Anchor>
  <Anchor href="#" icon={<Configuration />}>
    Second
  </Anchor>
  <Anchor href="#" icon={<Configuration />}>
    Third
  </Anchor>
</Menu>
```

**Comment by rodmartinezmedina** [comment]
Please help.  Do you know how to target the icon on hover? I'm going crazy. I have an icon in a Grommet Anchor and nothing seems to work. 
[https://stackoverflow.com/questions/64454214/cant-style-grommet-icon-inside-anchor][1]


  [1]: https://stackoverflow.com/questions/64454214/cant-style-grommet-icon-inside-anchor

**Comment by ShimiSun** [comment]
@rodmartinezmedina I've responded to your stackoverflow question. Feel free to join our grommet slack #help channel and let us know if you have any further questions.
