### ISSUE TITLE
Box don't take up all the available space when flex is set to true

### ISSUE THREAD

**Issue by varungupta85** [grommet/grommet#5024]
I add a `Box` with `flex` set to `true` and I expect it to take up all the available space. But it only takes up the space required by the contents inside the `Box`. When I inspect the components tree in Chrome. I see that a `Context.Provider` component is added which reduced the height of the box to fit the contents in the box. Please see attached screenshots. The first screenshot displays that the `StyledBox` is taking up the whole height of window as expected.

![Screenshot 2021-03-02 at 6 11 33 PM](https://user-images.githubusercontent.com/7475133/109651376-74c68980-7b84-11eb-8297-14b6aa527d3f.png)

Below screenshot shows that the `Context.Provider` component right after the `StylesBox` clips the height to the contents of the `Box`.

![Screenshot 2021-03-02 at 6 11 58 PM](https://user-images.githubusercontent.com/7475133/109651543-accdcc80-7b84-11eb-9ff6-a7ce8171ae8a.png)

How can I avoid the `Context.Provider` changing the height of the `Box`.

### Expected Behavior

Take the complete height of the window.

### Actual Behavior

Only the height required to fill the contents was used.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-box-height-issue-yxj4j

In the above sandbox, why is the box not taking up the whole height of the window even though flex and fill is enabled for the box.

### Steps to Reproduce

Please check the sandbox.

### Your Environment

- Grommet version: 2.16.3
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Mac

**Comment by versoworks** [comment]
@varungupta85 it appears the issue is caused by not using the `Grommet `component on the top level. Based on the supplied codesandbox example, the following change resolves the issue;

 ```
<Grommet full>
    <Box fill background="green">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </Box>
 </Grommet>
```

**Comment by varungupta85** [comment]
@versoworks Thanks for your reply. Could you also please explain the difference between `flex` and `fill` properly that can be applied on a `Box`. I am seeing mixed results when these properties are applied. For example, sometimes applying `flex` to a `Box` does take up whole space but sometimes it doesn't. For example, the supplied sandbox, if I apply `flex` to the `Box`, it doesn't take up the whole space while applying `fill` does. And I know on some of the `Box`es, applying `flex` also does the trick.

From my understand, applying `flex` to the `Box` should take up all the available space and make the whole box green. I didn't find any explanation of `fill` outside of `grommet`. So, I think it is not a standard CSS property.

**Comment by jcfilben** [comment]
Hi @versoworks take at look at `fill` and `flex` in the grommet [Box documentation](https://v2.grommet.io/box#fill). You can also look at more information about how [flex-grow](https://www.w3schools.com/cssref/css3_pr_flex-grow.asp) and [flex-shrink](https://www.w3schools.com/cssref/css3_pr_flex-shrink.asp) work. In general if you want a box to take up the full space of its container use `fill`. If you want a box to adjust its size based on other components use `flex`.

**Comment by varungupta85** [comment]
@jcfilben Thanks for your reply.
