### ISSUE TITLE
Ability to make table headers sticky

### ISSUE THREAD

**Issue by sabarnix** [grommet/grommet#5031]
### Expected Behavior

Table can accept sticky header as a prop and add position sticky to header tableCells.

I am creating a PR but not sure how to pass the top value. Should that be on cell level or table level.
Also for table with multiple level table header is more difficult to handle.

### Actual Behavior

No support for table headers sticky

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
Have you taken a look at: https://v2.grommet.io/datatable#pin ?

**Comment by sabarnix** [comment]
I understand the behavior can be achieved using dataTable. But sticky headers in the table also make sense. Btw, why do we need both?

**Comment by ericsoderberghp** [comment]
Table, TableRow, etc. are very rudimentary table elements. One could argue that we could have omitted them and just had DataTable. Is there a reason DataTable doesn't work for you?

**Comment by sabarnix** [comment]
Since my requirement is a fixed table with no dynamic data. Rudimentary table elements make it kind of more readable. It can definitely be replaced by datatable though.

**Comment by sabarnix** [comment]
https://github.com/grommet/grommet/pull/4430/files#diff-3c607ce17d65f5520f60a0b3ad2154f7d906796eb228bd0a0ebb076090a9286bR127
Is there any problem making this part of TableCell?

**Comment by sabarnix** [comment]
Can be easily done using theme ``table.header.extend``
