### ISSUE TITLE
Make it possible to have leading zeroes on dates

### ISSUE THREAD

**Issue by jonasostrom** [grommet/grommet#5036]
Hi,

Is it possible to add the option have leading zeroes on DateInputs?

![no-leading-zero](https://user-images.githubusercontent.com/4511851/110234680-1c004380-7f2c-11eb-84a3-1b2843227942.png)

**Comment by ShimiSun** [comment]
```
<DateInput
  format="mm/dd/yyyy"
  value="03/07/2021"
  onChange={({ value }) => {}}
/>
```
Attached a snippet to demonstrate the problem.
