### ISSUE TITLE
Slack Invite Email with Subdomain

### ISSUE THREAD

**Issue by ademey** [grommet/grommet#5051]
The Slack invite email input (https://slack-invite.grommet.io/) does not accept an email with a subdomain. 

### Expected Behavior

I would expect to be able to get a slack invite using an email like "myname@us.company.com".

### Actual Behavior

The input only allows for one period after the "@".

### URL, screen shot, or Codepen exhibiting the issue

![grommet-email](https://user-images.githubusercontent.com/211533/110671627-5ec45480-8194-11eb-8f27-f0c731845da3.gif)

### Steps to Reproduce

1. Visit https://slack-invite.grommet.io/
2. Try to input an email like "myname@us.company.com" or "my.name@us.company.com"
3. Input will not accept a second "." after "@"

### Your Environment

- Browser Name and version: Chrome 89 or Firefox 86
- Operating System and version (desktop or mobile): MacOS 10.15.7

**Comment by ShimiSun** [comment]
Thanks for reporting!

**Comment by ShimiSun** [comment]
Thank you for reporting and helping us improve the slack-invite experience! ❤️  The issue is fixed.
