### ISSUE TITLE
SearchInput component, need to hit ENTER key twice to perform the search event

### ISSUE THREAD

**Issue by techPackets** [grommet/grommet#506]
I have implemented a search text box with the <SearchInput> component , grommet version 0.5.5, for some reason the search doesn't happen when I press the ENTER key for the first time. I have to press ENTER twice to get it working. 

Codepen for this: [http://codepen.io/shivang/pen/aNYVQx]

There are suggestions in the SearchInput. A user can type in the text & do a search or he can select one of the suggestions. I tried to get it working by removing the suggestions & tested it still doesn't work on a single enter press.

**Comment by bryanjacquot** [comment]
@techPackets, this appears to be working properly with the latest version of Grommet.  Can you please verify?
