### ISSUE TITLE
Multi-Select component variation

### ISSUE THREAD

**Issue by vavalos5** [grommet/grommet#5063]
### Expected Behavior
Add Multi-select component to Grommet. Designs could be found here: https://www.figma.com/file/EcLSFz5L7EwmOadmEYGshZ/Multi-Select-Component?node-id=0%3A1
 

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
Are we sure this issue is grommet and not design-system reltaed? @vavalos5 @MikeWalrath

**Comment by ericsoderberghp** [comment]
I see a couple of things to explore on this issue:
- whether to offer checkboxes as an alternative visual indicator for selection
- whether to add the footer variation of the clear action, as well as the view toggle

**Comment by jcfilben** [comment]
Closing in favor of https://github.com/grommet/hpe-design-system/issues/2367
