### ISSUE TITLE
Avatar size could have 'xxlarge' size to match UX

### ISSUE THREAD

**Issue by sathishiva** [grommet/grommet#5064]
Please provide 'xxlarge' size for Avatar component. Right now it supports only till 'xlarge' (https://v2.grommet.io/avatar).

### Expected Behavior

`<Avatar size='xxlarge' />`

### Actual Behavior

`<Avatar size='xlarge' />
`

**Comment by ShimiSun** [comment]
According to our predefined `baseSpacing`, here are the larger Avatar sizing:
```
{
  2xlarge: '120px', // xxlarge
  3xlarge: '144px',
  4xlarge: '168px',
  5xlarge:  '192px'
}
```
So if I remember correctly, and just to verify, `xxlarge` won't be efficient for you, you'll need a size of `5xlarge`, correct?

**Comment by sathishiva** [comment]
3xlarge: '144px', is the size as per the UX. But it would be good to keep up to '5xlarge' if any use case comes in the future.
