### ISSUE TITLE
DataTable onSelect does not pin header checkbox 

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5070]
### Expected Behavior

If caller provides `pin` on DataTable while also using `onSelect` or `select`, the checkbox in the header of the table should remain fixed with the rest of the header cells.

### Actual Behavior

The checkbox scrolls away and does not stay pinned/

### URL, screen shot, or Codepen exhibiting the issue

https://user-images.githubusercontent.com/12522275/111372635-215e3c00-8658-11eb-8f75-c406f2cd35f3.mov

### Steps to Reproduce

1. Create DataTable
2. Apply `pin`
3. Apply `onSelect={() => {}}` (to display checkboxes)
4. Scroll

### Your Environment

- Grommet version: Stable
- Browser Name and version: Chrome Version 89.0.4389.82
- Operating System and version (desktop or mobile): Mac OS

**Comment by ericsoderberghp** [comment]
Alex is working on this ...

**Comment by AkshayChoulwar** [comment]
Hi @taysea , @ericsoderberghp and @ShimiSun 

https://user-images.githubusercontent.com/17611765/111416771-8a9e8780-870a-11eb-8818-756622f1eec6.mov




I tried it on latest master branch and looks like it's not reproducible at my side. I have attached the video which contains functionality and code. Please let me know if I'm missing anything.

**Comment by taysea** [comment]
@AkshayChoulwar Thanks for attaching the video. Interesting find. If the user sets the `size` on DataTable (as you have), then all is fine. However, in my implementation I had the DataTable wrapped in a Box with height="medium" and overflow and that's where I see the checkbox scrolling away:
```
<Box height="medium" overflow="auto">
   <DataTable />
</Box>
```
I would expect that either implementation would still pin the checkbox. What do you think? @ericsoderberghp @ShimiSun ?

**Comment by taysea** [comment]
Thanks for confirming @ericsoderberghp. @AkshayChoulwar are you good to still work on this?
