### ISSUE TITLE
Range Selector not draggable on mobile

### ISSUE THREAD

**Issue by leifg** [grommet/grommet#5076]
### Expected Behavior

When I have a range selector that I use on a mobile device I expect to drag the endpoints like I would with a mouse curser

### Actual Behavior

On a mobile device (I tested with an iPhone) I am not able to drag the endpoints. Instead I tap where I want the individual endpoints to be.

### URL, screenshot, or Codepen exhibiting the issue

- [Codepen example](https://codesandbox.io/s/grommet-v2-template-forked-ybb73?file=/index.js)
- [Slack Discussion](https://grommet.slack.com/archives/C09QQEG69/p1615942603000700)
- [Video outlining the issue](https://user-images.githubusercontent.com/110321/111541494-ce56b880-872d-11eb-9184-96cf1d7d878b.MOV)

### Steps to Reproduce

- Go to codeine example with your phone
- try to drag the endpoints to adjust the range
- nothing happens

### Your Environment

- Grommet version: 2.16.2
- Safari on IOs
- iOS 14.4.1

**Comment by ShimiSun** [comment]
Thank you for reporting, the issue is fixed and will be available on the following release of ^2.17.2.
