### ISSUE TITLE
Pagination folder is missing in the NPM package grommet": "2.16.3"

### ISSUE THREAD

**Issue by Yoruba** [grommet/grommet#5086]
After removing and downloading NPM package "grommet": "2.16.3" multiple times there is no Pagination folder in the node_modules/grommet/components.

A temp fix for me was to build the package by my self and copy the folder into the right folder.

Thanks, Yoruba

**Comment by ShimiSun** [comment]
Hello, and thank you for your interest in the new Pagination component! 
The Pagination component is still under exploration and hadn't been released yet officially, It is available on our [grommet-stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) in case you'd like to explore it and send us feedback.
We are planning on releasing it officially in the coming week.
