### ISSUE TITLE
How to only disable selecting past dates on Calendar?

### ISSUE THREAD

**Issue by ImSolitude** [grommet/grommet#5090]
I'm trying to figure out how can I not only disable selecting past dates but also highlight them on the calendar itself, Is this doable?

**Comment by ShimiSun** [comment]
Can you share what you have so far and your use case? it will help speed up the discussion.

**Comment by jcfilben** [comment]
Hi @ImSolitude I am confused by what you are trying to achieve here. I understand the past dates being disabled but not sure how you are trying to highlighting them? Could you share more details or an image of what you are trying to do?

**Comment by ShimiSun** [comment]
Hello, I'll be closing this issue due to a lack of details, feel free to elaborate and reopen if it is still relevant. Thank you!

**Comment by ImSolitude** [comment]
Hey @ShimiSun @jcfilben,

Sorry for not providing details. I'm just trying to prevent users from selecting past dates on the Calendar https://v2.grommet.io/calendar. Similar to this 
<img width="883" alt="error" src="https://user-images.githubusercontent.com/20565199/120506807-eeae1f00-c3ce-11eb-93b7-ebc135eb2076.png">

**Comment by jcfilben** [comment]
@ImSolitude you can use the `bounds` prop to tell the Calendar what dates are available to select, this will prevent users from selecting dates outside of the bounds and grey out those dates.
