### ISSUE TITLE
Carousel shows different image on mount

### ISSUE THREAD

**Issue by rolule** [grommet/grommet#5093]
When you mount a Carousel component containing images (probably also with other children) it shows the last image for a brief moment before displaying the first image (initialChild has to be set to 0).

### Expected Behavior
Show the first image instantly without a fading animation.

### Actual Behavior
Shows the last image for a brief moment before showing the first image.

### URL, screen shot, or Codepen exhibiting the issue
The best way to showcase this is using a layer because this forces the initial render after a button click.
For demonstration purposes: https://codesandbox.io/s/grommet-carousel-fix-kokh7?file=/src/BrokenModal.tsx
Note that I copied the source code of the Carousel component and had to adapt it to TypeScript. However the only line I changed in the "fix" was the rendering of the wrappedChildren, where I reversed the array (CarouselFixed.tsx line 187). This fix does only work when initialChild is set to 0. If it is set to another value, e.g 1 or 2, the first image is shown for a brief moment before displaying the specified image (which applies to both the broken and the fixed version). 

### Steps to Reproduce

1. Create Carousel with images (best in modal)
2. Watch render of Carousel

### Your Environment

- React version: 17.0.0
- Grommet version: v2.17.0
- Browser Name and version: Google Chrome 89.0.4389.90
- Operating System and version (desktop or mobile): MacOS Big Sur 11.2.3

**Comment by rolule** [comment]
The issue seems to exist still after upgrading to grommet v2.17.0

**Comment by ShimiSun** [comment]
> The issue seems to exist still after upgrading to grommet v2.17.0

Thanks for confirming, I'll update the grommet version on the PR description.

**Comment by ShimiSun** [comment]
Thank you for reporting! @DolceTriade had contributed a fix for this issue and it will be available on our next grommet release! 💟
