### ISSUE TITLE
Calendar HeaderProps has wrong typings

### ISSUE THREAD

**Issue by andrewthamcc** [grommet/grommet#5107]
The `HeaderProps` for the Calendar were recently changed (https://github.com/grommet/grommet/pull/5074) and the props for  `previousInBound` and `nextInBound` are incorrect.

```typescript
previousInBound: 1 | 2 | undefined;
nextInBound: 1 | 2 | undefined;
```

According to the [documentation](https://v2.grommet.io/calendar) for the calendar component both `previousInBound` and `nextInBound` should be of type `Boolean`

### Actual Behavior

Currently the type of `previousInBound` and `nextInBound` are `number | undefined`

### URL, screen shot, or Codepen exhibiting the issue

PR that changed this: https://github.com/grommet/grommet/pull/5074/files
Current code: https://github.com/grommet/grommet/blob/master/src/js/components/Calendar/index.d.ts
Docs describing prop types: https://v2.grommet.io/calendar

### Steps to Reproduce

N/A

### Your Environment

- Grommet version: 2.17.0
- Browser Name and version: Chrome Version 89.0.4389.90 (Official Build) (x86_64)
- Operating System and version (desktop or mobile): Desktop

This process really fails my build CI as the typing automatically fail

**Comment by britt6612** [comment]
I think this issue can be closed since PR got merged
