### ISSUE TITLE
MaskedInput prop type focusIndicator

### ISSUE THREAD

**Issue by andrewthamcc** [grommet/grommet#5108]
According to the release notes for [2.17.0](https://github.com/grommet/grommet/releases/tag/v2.17.0) `focusIndicator ` was corrected for the MaskedInput component but the typings are missing the prop `focusIndicator`

### Expected Behavior

The typings should contain: 
```typescript
focusIndicator?: boolean;
```

### Actual Behavior

This prop is currently missing as seen here: https://github.com/grommet/grommet/blob/master/src/js/components/MaskedInput/index.d.ts

### URL, screen shot, or Codepen exhibiting the issue

Please see above URL

### Steps to Reproduce

NA

### Your Environment

- Grommet version: 2.17.0
- Browser Name and version: Chrome Version 89.0.4389.90
- Operating System and version (desktop or mobile): desktop

**Comment by ShimiSun** [comment]
Thank you for reporting, the issue is fixed!
