### ISSUE TITLE
Spinner is missing from CodeSandBox linked in docs

### ISSUE THREAD

**Issue by samuelgoff** [grommet/grommet#5112]
### Expected Behavior

CodeSandBox linked from [Spinner docs](https://v2.grommet.io/spinner) should correctly demonstrate the usage of Spinner component.

### Actual Behavior
Spinner is currently missing in the [CodeSandBox](https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=/spinner&module=%2Fsrc%2FSpinner.js) linked in [Spinner docs](https://v2.grommet.io/spinner), displaying the following error message:

> Could not find module /src/Spinner.js
> Cannot find module in /src/Spinner.js

### URL, screen shot, or Codepen exhibiting the issue

![screen grab of error](https://user-images.githubusercontent.com/2007084/112768696-d7c00a80-8fe2-11eb-97b5-dc394ec9b72e.png)

### Steps to Reproduce

1. go to Spinner docs at https://v2.grommet.io/spinner
2. click on CodeSandBox link to go to https://codesandbox.io/s/github/grommet/grommet-sandbox?initialpath=/spinner&module=%2Fsrc%2FSpinner.js
3.note the error message that displays ("Could not find module /src/Spinner.js")

### Your Environment

- Grommet version: v2
- Browser Name and version: Chrome Version 89.0.4389.90 & Safari Version 14.0.3 (16610.4.3.1.7)
- Operating System and version (desktop or mobile): macOS Big Sur 11.2.3 (desktop)

**Comment by ShimiSun** [comment]
Fixed thanks to @britt6612 PR linked above.
