### ISSUE TITLE
Grommet global theme for formField complains that 'side' is incompatible (TypeScript)

### ISSUE THREAD

**Issue by dvdprr6** [grommet/grommet#5118]
### Expected Behavior

The theme prop added to the `Grommet` component should recognize the key `side` in `BorderType` when configuration global theme for formField

### Actual Behavior

I am trying to set a global theme for my formField where the border is displayed all around the TextInput. This is my theme configuration, which I took from the story book found here: https://storybook.grommet.io/?path=/story/input-form-field-custom-states--field-custom-states

```TypeScript
const theme = {
  formField:{
    border: {
      error: {
        color: 'border'
      },
      color: 'border',
      side: 'all'
    },
    round: '4px'
  }
}
```

The theme prop that is passed to the `Grommet` component complains that `side` is incompatible. I get this message
![image](https://user-images.githubusercontent.com/1852283/112927922-c4e12f00-90e3-11eb-99de-260b926b65a1.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.17.1
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by thamanchand** [comment]
I get this issues too with Grommet 2.19.1

**Comment by britt6612** [comment]
@thamanchand I believe the issue is you need to specify ThemeType in your example. You are missing the `const customTheme: ThemeType = {`

Let me know if this helps

https://codesandbox.io/s/grommet-ts-textinput-type-forked-j5fhk?file=/src/index.tsx:315-324

**Comment by thamanchand** [comment]
@britt6612 You're so right, it did worked :) Thank you!
