### ISSUE TITLE
DataTable TypeError when Data Array is empty with `paginate`

### ISSUE THREAD

**Issue by TPK2002** [grommet/grommet#5123]
### Expected Behavior
When data array is empty, the table should display no rows but the header.

### Actual Behavior
This perfectly works in most cases, but one. When I set the paginate prop in combination with the onClickRow Prop it crashes on empty data array.

### URL, screen shot, or Codepen exhibiting the issue

Error reproduced in Codesandbox
https://codesandbox.io/s/datatable-empty-data-bug-94i1z
![Bildschirmfoto 2021-03-31 um 11 15 26](https://user-images.githubusercontent.com/19915810/113120943-6797cb80-9212-11eb-8a5c-a86564cce363.png)

### Steps to Reproduce

1. SetUp a React App
2. Install Grommet
3. Create a DataTable
4. Set data to '[]'
5. Set the paginate and onClickRow Props

### Your Environment

- Grommet version: 2.17.0
- Browser Name and version: Safari/Firefox/Chrome (all newest versions)
- Operating System and version (desktop or mobile): macOS 11

**Comment by ShimiSun** [comment]
For troubleshooting, I think the root cause of this issue is the `paginate` prop, as this functionality seems to work in the past.
