### ISSUE TITLE
Paginate prop in types added to ColumnConfig instead of DataTableProps

### ISSUE THREAD

**Issue by jzarzeckis** [grommet/grommet#5125]
https://github.com/grommet/grommet/blob/7c363d5850bf3344bef355b6fdf1d6c74b05bfa5/src/js/components/DataTable/index.d.ts#L44

Shouldn't this have been added to `DataTableProps` instead?

**Comment by britt6612** [comment]
Yes, this should be under`DataTableProps` There is an open PR for this issue.
Thank you for reporting
https://github.com/grommet/grommet/pull/5121

**Comment by ShimiSun** [comment]
Thanks for reporting, this issue is fixed!
