### ISSUE TITLE
Icons are not positioned in front in Accordion Panel

### ISSUE THREAD

**Issue by jayant246** [grommet/grommet#5128]
https://codesandbox.io/s/grommet-accordion-icon-size-and-color-9o140

I want to build this UI design, but how to position the icons in front:
https://www.uidesigndaily.com/posts/figma-accordion-day-1242

**Comment by ShimiSun** [comment]
You can use the `header` prop of the Accordion Panel.
https://v2.grommet.io/accordion?#props
https://storybook.grommet.io/?path=/story/controls-accordion-header--header

**Comment by jayant246** [comment]
I got it. Thanks for the answer.
