### ISSUE TITLE
Card, Avatar, Tooltip Component

### ISSUE THREAD

**Issue by icukaegbu** [grommet/grommet#513]
Hi,
Are there any plans to implement the Card, Avatar and Tooltip components (and other Material Design components)?

**Comment by icukaegbu** [comment]
Is it possible to integrate jxnblk.com/rebass/ into your amazing framework? Can there be a combination of effort?

**Comment by bryanjacquot** [comment]
@icukaegbu, our goal is not to copy Material Design.  We are building components based on need in apps we're developing, and we're happy to accept PRs from the community.   For Cards, have you looked at [Tiles](http://www.grommet.io/docs/hpe/develop/tiles)?  For Avatar, we use the existing react-gravatar project as shown in the [Ferret](https://github.com/grommet/grommet-ferret/blob/2628df0c57d314e127928647a8e43006e59f0036/src/js/components/SessionMenu.js) example app [demo](http://ferret.grommet.io/).  Finally, we use tooltips very sparingly as they don't translate well to mobile where there is no hover state.  I know these three were example components you were referencing from Material, but if there are others you'd like to see, let us know...or better yet, submit a PR.  :-)
