### ISSUE TITLE
Enhance Text with truncate to use Tip when truncating text

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#5132]

**Comment by britt6612** [comment]
@ericsoderberghp 
Would `tooltip`  always appear when truncate is set to `true` or would we add a value to be passed into truncate for example `truncate="tip"`

**Comment by ericsoderberghp** [comment]
Hmm... I'm leaning towards a separate `tip` prop, to align with Button.

**Comment by britt6612** [comment]
That sounds good Ill look into that!

**Comment by ShimiSun** [comment]
This issue might already be a WIP by @kid-icarus , FYI

**Comment by britt6612** [comment]
> This issue might already be a WIP by @kid-icarus , FYI

Thank you I saw the PR. I can review PR once ready!
