### ISSUE TITLE
FileInput -- Call onChange when file is removed

### ISSUE THREAD

**Issue by meekrhino** [grommet/grommet#5143]
The `FileInput ` component calls `onChange` when file(s) are added, providing the complete list of files in the callback.  However, this behavior is not replicated when a file is removed from the list by the user.  In order for consumers of `FileInput` to accurately track the list of files, `onChange` should be called any time the list of files changes.

### Expected Behavior

`onChange` is called any time the list of files changes.

### Actual Behavior

`onChange` is only called when files are added to the list. 

### URL, screen shot, or Codepen exhibiting the issue

[The Grommet example storybook](https://storybook.grommet.io/?path=/story/input-fileinput-custom--custom)

### Steps to Reproduce

1. Add files to the list.
2. Remove a file
3. Observe `onChange` is not called

### Your Environment

- Grommet version: 2.17.1
- Browser Name and version: (any)
- Operating System and version (desktop or mobile): Windows 10 Home -- 19041.867

**Comment by Lukazovic** [comment]
Hey @meekrhino and @ShimiSun. I think this issue is fixed by #5028.

Some console errors are displayed when the file is removed but I think it only affects the storybook examples.


https://user-images.githubusercontent.com/54550926/124215867-4376af80-dacb-11eb-8ac7-0c0e291e3764.mp4

**Comment by jcfilben** [comment]
Closing since #5028 was merged and #5428 fixed the storybook examples
