### ISSUE TITLE
FileInput -- Add prop to limit number of files

### ISSUE THREAD

**Issue by meekrhino** [grommet/grommet#5144]
The `FileInput` component cannot be operated in a controlled mode, so currently there is no way to limit the number of flies allowed in the list in `multiple` mode.  The easiest solution to this would be to add a new prop for `maximumCount` or similar.  This is distinct from `aggregateThreshhold` which only limits the files displayed, not the number in the list.

### Expected Behavior

There is no way to stop a user from adding any number of files.

### Actual Behavior

A prop to limit the number of files allowed.

### URL, screen shot, or Codepen exhibiting the issue

[The Grommet example Storybook](https://storybook.grommet.io/?path=/story/input-fileinput-custom--custom)

### Steps to Reproduce

1.  Add many files to the list

### Your Environment

- Grommet version: 2.17.1
- Browser Name and version: (any)
- Operating System and version (desktop or mobile): Windows 10 Home -- 19041.867

**Comment by g4rry420** [comment]
Can I work on this issue ?

**Comment by britt6612** [comment]
@g4rry420 of course! 👍 Feel free to file a PR!
