### ISSUE TITLE
Enhance RangeInput with thumb Label and dynamic track color based on a prop value

### ISSUE THREAD

**Issue by q-oh** [grommet/grommet#5145]
This is not an issue. Either Grommet doesn't support or I can't seem to figure out.
Currently looking to add the following:
1. Thumb label
2. Dynamic track color based on a prop value (range input value)

Image: 
![image](https://user-images.githubusercontent.com/81991460/113619180-8250b280-960d-11eb-80e1-85e8c9ea4390.png)

### Expected Behavior

- Be able to add an element/string/number to a prop which will generate a label for a thumb
- Be able to add a series of background colors and their corresponding threshold so that track color could reflect based on the range input value.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-puh94?file=/index.js

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: "^2.14.0"
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
Look at how we support gradients with Chart to see if we can do something similar.
https://storybook.grommet.io/?path=/story/visualizations-chart-gradient--gradient-charts
https://v2.grommet.io/chart#color

**Comment by q-oh** [comment]
Hi @ericsoderberghp - would it be possible to get an ETA? Trying to plan for our project release. Thanks

**Comment by ericsoderberghp** [comment]
> Hi @ericsoderberghp - would it be possible to get an ETA? Trying to plan for our project release. Thanks

This isn't at the top of the grommet team's work list: https://github.com/orgs/grommet/projects/10?fullscreen=true

Would you be interested in contributing the changes for it?

**Comment by g4rry420** [comment]
@ericsoderberghp  My apologies. I am not sure if the issues moved to `Grommet/Design System Backlog ` can be picked by anyone or not. Still, I find this issue interesting and have worked on `Dynamic track color based on a prop value` part. Wanted to know your thoughts if this is how you wanted to implemented. For the passing the colors, I used used the `rangeInput.track.colors` as an array of objects.


https://user-images.githubusercontent.com/61521805/118433105-40089f80-b6a8-11eb-9e50-58602f8478a9.mp4

**Comment by halocline** [comment]
Closed by #5275

**Comment by robustdj** [comment]
Would it be possible to make the colors fixed? Right the track color will change depending on the value. I have a `RangeInput` such that I want the colors to remain there regardless of the value

https://github.com/grommet/grommet/pull/5275#discussion_r832698086

**Comment by jcfilben** [comment]
Hi @robustdj currently we don't support having all the colors show regardless of the value. We felt at the time we didn't have a good use case for it. We had a similar discussion with adding gradient to the Meter component (see full discussion here :https://github.com/grommet/grommet/pull/5773#issuecomment-990125324) and we felt that the colors were helping convey information to the user about the value so showing all the colors even when the value was small felt like there was a disconnect between the information the color is giving the user and the value of the RangeInput or Meter.

Would you be willing to share you use case and then we can continue discussion from there?
