### ISSUE TITLE
FormField loses focus on validation

### ISSUE THREAD

**Issue by MikeKingdom** [grommet/grommet#5146]
This seems to be a regression from 2.16.3 to 2.17.1. The problem does not happen in 2.16.3

When trying to enter text in a required TextInput in a FormField and the field is marked invalid, entering the first character causes the field to switch to valid but the character never appears and the focus shifts elsewhere. You have to click back in the input and before you can enter more text.
 
### Expected Behavior

The focus should not change when the field switches between valid and invalid.

### Actual Behavior

The field loses focus and the text is lost (although the field appears to be valid at this point.)

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/long-shadow-mjs3i?file=/src/AddForm.js
```jsx
  <Form onSubmit={onSubmit}>
    <FormField
      label="Description"
      name="description"
      htmlFor="description"
      required
      component={TextInput}
      placeholder="Enter a description for the volume"
    />
    <Button type="submit" primary label="Submit" />
  </Form>
```

### Steps to Reproduce

Click on Submit. The field is marked invalid since it is required:
![image](https://user-images.githubusercontent.com/12054362/113739344-ee3e2400-96bc-11eb-90b7-6e877fb5526d.png)

Click in the input and try to enter something (e.g 'a')
![image](https://user-images.githubusercontent.com/12054362/113739489-16c61e00-96bd-11eb-8594-80151ea2753c.png)

The red background and validation message disappear but the character you typed does not appear. The field still has the focus border but further typing is ignored.

You must click in the field again and continue typing.

Backspacing to remove the text clears the field, but the field doesn't get marked invalid once you clear all text.

![image](https://user-images.githubusercontent.com/12054362/113740061-9a800a80-96bd-11eb-969f-43716624d4b0.png)

### Your Environment

- Grommet version: 2.17.1
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows 10

**Comment by MikeKingdom** [comment]
This only happens with the hpe theme on grommet 2.17.0 or later.
It seems like something about the styling from the theme causes the TextInput to be re-created (ie. the [focus, setFocus] = useState() in the component is reset to undefined again which should only be possible if the TextInput is newly created. All setFocus() calls pass either true or false)

**Comment by ShimiSun** [comment]
@MikeKingdom Can you confirm it's also reproducing with hpe-theme stable branch? we haven't released it lately so it might already contain a fix.

**Comment by MikeKingdom** [comment]
> @MikeKingdom Can you confirm it's also reproducing with hpe-theme stable branch? we haven't released it lately so it might already contain a fix. If the fix is already there I can prioritize a release.

Confirmed it happens with the hpe-theme stable branch.

It doesn't appear to be a change in the theme that's the problem. The problem is looking like how FormField applies `formField: { error: { background: { color: 'validation-critical' }}}` causes the TextInput to get re-created (and therefore loses its state).

**Comment by MikeKingdom** [comment]
The root cause is #4801 how Box.js line 126 inserts a ThemeContext.provider if a background is added.

**Comment by kariwhitcomb** [comment]
can you role a patch release with this fix?  It is currently breaking our e2e tests preventing us from updating to the latest grommet.
