### ISSUE TITLE
Select component does not trigger enclosing Form's onChange

### ISSUE THREAD

**Issue by bear-bibeault** [grommet/grommet#5147]
When embedded in a Form, a Select component does not trigger the onChange callback of the enclosing form when its value is changed.

### Expected Behavior

The Form's onChange callback is triggered when the Select's value is changed.

### Actual Behavior

The onChange callback is not triggered

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-5lhth?file=/index.js

### Steps to Reproduce

In the Codepen, change the value of the Select and observe that the console reveals that the onChange callback is not triggered.

### Your Environment

- Grommet version: 4.5.0
- Browser Name and version: Chrome 89.0.4389.90 (Official Build) (x86_64)
- Operating System and version (desktop or mobile): macOS Catalina

**Comment by ShimiSun** [comment]
You are simply missing the binding of `name` prop from the component to the FormField.
Add the following to your Select:
```

**Comment by bear-eden** [comment]
Doh!
