### ISSUE TITLE
Using Tip with Checkbox gives unexpected results

### ISSUE THREAD

**Issue by raywong-fb** [grommet/grommet#5149]
### Expected Behavior

Wrapping a Checkbox component with a Tip generates a tooltip when user hovers over the checkbox.

### Actual Behavior

The tooltip does not display on hover. However, it sometimes displays when the checkbox is clicked.

### URL, screen shot, or Codepen exhibiting the issue

Here's a sandbox example:
https://codesandbox.io/s/grommet-v2-template-forked-d33rx?file=/index.js

### Your Environment

- Grommet version: 2.17.1
- Browser Name and version: All
- Operating System and version (desktop or mobile): OS X

**Comment by ShimiSun** [comment]
This issue is resulted from the lack of React event propagation to Checkbox, and not related to the Tip directly.
Running this snippet would reproduce the issue as onMouseEnter/Over/Leave/Out are not triggered on Checkbox.

```
     <CheckBox
        onMouseEnter={() => console.log('shimi enter')}
        onMouseOver={() => console.log('shimi over')}
        onFocus={() => console.log('shimi focus')}
        label="Checkbox"
      />

**Comment by ShimiSun** [comment]
This issue is expanding beyond Checkbox to other input components due to `ref` of the input component not resolved correctly when used within Tip. For now, wrapping the component with `<span>` would be the workaround.

**Comment by ericsoderberghp** [comment]
CheckBox is done. Any similar issues with other components will be handled by separate issues.
