### ISSUE TITLE
Layer and LayerForm components close when user selects a value in a child SearchInput component

### ISSUE THREAD

**Issue by mark-harmon** [grommet/grommet#515]
To reproduce:

1. Browse to http://www.grommet.io/docs/hpe/develop/layer
2. In the "Edit, left" example of the Examples section, mouse-click on the "edit" button
3. In the "Edit" layer that opens, mouse-click on the search icon for Item 6
4. Mouse-click on any value in the list
5. Once a value is selected, the entire form layer closes, and the user does not get an opportunity to continue modifying values in other fields.  (However, it behaves as expected when using the keyboard cursor and enter keys.)

**Comment by jwijay** [comment]
Addressed by PR: https://github.com/grommet/grommet/pull/518
