### ISSUE TITLE
"Selected" style is not applied to Select options when using custom children

### ISSUE THREAD

**Issue by phinch** [grommet/grommet#5154]
Hello! I'm using the Select input and passing in a custom `children` argument to render a custom label. When I render the custom label, the "hover" and "active" styles from the Select input get applied automatically, so I get the theme's hover/active background/color for free, which is great; but the "selected" style from Select does not seem to get applied to my custom label.

### Expected Behavior

I think the selected style should be applied to the custom option, like the active and hover styles are. (that is, if i'm reading correctly, i think this [OptionBox](https://github.com/grommet/grommet/blob/master/src/js/components/Select/SelectContainer.js#L34), or at least its styles, should get applied to custom children instead of just to default children.)

### Actual Behavior

The active and hover styles are applied to custom options, but the selected style is not.

I know that `selected` is passed as a prop to the children function, so I can use that to apply a style to my custom option; but I feel like since the active and hover styles come for free, it would be nice and consistent if the selected one did as well.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-tw8t4?file=/index.js

### Steps to Reproduce

There are 2 Selects here; the first one does not use custom children and the second one does. 
1. In both Selects, hover and active styles work identically
2. In the Select on the left, selected style works as expected
2. In the Select on the right, selecting an option does not apply the selected style to that option

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): osx 11.2.1

**Comment by ShimiSun** [comment]
We've made recent changes on Select and overall focus behavior on grommet v2.17.1, we'll need to make sure the issue as described is still relevant on this recent version.

**Comment by jcfilben** [comment]
I don't think this issue is relevant anymore since #5148 was merged

**Comment by britt6612** [comment]
This is actually still relevant using this on stable branch you can see the issue
```
<Box fill align="center" justify="start" pad="large" gap="medium">
        <Select
          id="select"
          name="select"
          placeholder="Select"
          value={value}
          options={options}
          onChange={({ option }) => setValue(option)}
        />
        <Select options={options}>{option => <Text>{option}</Text>}</Select>
      </Box>
```
