### ISSUE TITLE
`gridArea` should support non-named areas

### ISSUE THREAD

**Issue by Tbhesswebber** [grommet/grommet#5160]
### Expected Behavior

The CSS specification supports multiple ways of positioning elements within a grid.  While I don't find it necessary to support everything within the grid spec, I would expect to find the ability to place based on at least the start and end column/row

[CodeSandbox](https://codesandbox.io/s/brave-bush-ownqw?file=/src/App.tsx)

### Actual Behavior

TypeScript yells at me for supplying anything other than a string.

### Your Environment

- Grommet version: 2.17.1
- React version: 17.0.2
- TypeScript version: 4.2.3

**Comment by ShimiSun** [comment]
@Tbhesswebber sounds like a nice enhancement! would you like to try and come up with a contribution?

**Comment by Tbhesswebber** [comment]
I would love to in the future, but I work for a stealth-mode startup and won't really have the time to contribute until our Alpha release later this year. 😭

**Comment by g4rry420** [comment]
If I am not wrong, I think `gridArea` supports the non-named areas. I implemented this:-
```
import React from 'react';

import { Grommet, Grid, Box } from 'grommet';
import { grommet } from 'grommet/themes';

export const Test = () => {
  return (
    <Grommet theme={grommet} full>
      <Grid
        columns={{
          count: 4,
          size: 'auto',
        }}
        gap="small"
      >
        <Box background="brand" pad="medium" align="center" gridArea='2 / 1 / span 2 / span 3'>1</Box>
        <Box background="light-5" pad="medium" align="center">2</Box>
        <Box background="accent-2" pad="medium" align="center">3</Box>
        <Box background="dark-2" pad="medium" align="center">4</Box>
        <Box background="dark-1" pad="medium" align="center">5</Box>
        <Box background="dark-3" pad="medium" align="center">6</Box>
        <Box background="dark-4" pad="medium" align="center">7</Box>
      </Grid>
    </Grommet>
  );
};

Test.storyName = 'Test';

export default {
  title: 'Layout/Grid/Test',
};
```
Please, let me know your thoughts.

**Comment by jcfilben** [comment]
Thanks for sharing the above solution @g4rry420!
@Tbhesswebber I'm going to go ahead and mark this issue as closed since the above solution is working. Feel free to reopen if you would like to continue discussion on the topic.
