### ISSUE TITLE
[TS] DateInput type definition is missing disabled prop

### ISSUE THREAD

**Issue by Shannor** [grommet/grommet#5162]
### Expected Behavior

Should be able to disable the DateInput while using typescript

### Actual Behavior

If using typescript you will get an error that disabled doesn't exist on DateInput

### URL, screen shot, or Codepen exhibiting the issue
 Here is a link with someone stating the solution https://github.com/grommet/grommet/issues/4438

### Steps to Reproduce
Use the DateInput and try to disable. 

### Your Environment

- Grommet version:  2.17.1
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment]
Looks like this issue can be closed since #5165 was merged

**Comment by Shannor** [comment]
Cool. Closing now. Thanks!
