### ISSUE TITLE
QUESTION: do you guys have a figma template for faster design?

### ISSUE THREAD

**Issue by woss** [grommet/grommet#5168]
Hi, having a figma template would be of huge help designing the app built on the grommet. 
Icons are not essential but the bazse component yes.

**Comment by ShimiSun** [comment]
Not sure if we do, @L0ZZI do we have figma assets for Grommet?

**Comment by jcfilben** [comment]
We currently don't have any Figma templates for grommet but you can checkout the [grommet designer](https://designer.grommet.io/) to help aid your design process.
