### ISSUE TITLE
Form with `validate='change'` changes focus when displaying error/info/help content.

### ISSUE THREAD

**Issue by versoworks** [grommet/grommet#5170]
Using Grommet v2.17.1. When a `Form` with the property `validate='change'` containing a `TextInput` is used, if you pause whilst typing and the `Form` displays the `Invalid` error for example, the `TextInput` loses focus, so you cannot resume typing without resetting focus on the `TextInput` control.

**Comment by MikeKingdom** [comment]
If the theme being used changes the `FormField` background color when a field is invalid (like `grommet-theme-hpe`) this issue is likely fixed by PR #5158

**Comment by versoworks** [comment]
@MikeKingdom  cheers for the info. Looks like v2.17.2 is going to squash quite a few niggling bugs.
