### ISSUE TITLE
`CheckBox` `fill` property is broken

### ISSUE THREAD

**Issue by versoworks** [grommet/grommet#5172]
Using Grommet v2.17.1. Setting the `fill` property on a `CheckBox` doesn't perform as designed, and also raises an error in the console;

`Warning: Received 'true'  for a non-boolean attribute 'fill'.`

See the [Codesandbox](https://codesandbox.io/s/elated-proskuriakova-p86yu) example.

**Comment by britt6612** [comment]
@versoworks @leossantiago 
The `fill` prop was added on the stable branch you will not see these changes until the next release. So this codesandbox would not be up to date can you maybe check stable branch ?

**Comment by leossantiago** [comment]
@britt6612 even though the codesandbox might not be up to date, I was able to reproduce both issues with the master branch. Thanks for the heads up! 😄

**Comment by ShimiSun** [comment]
Related to #5153.

**Comment by ShimiSun** [comment]
Fixed and available on grommet stable, and on future release grommet 2.17.2
