### ISSUE TITLE
When JSX Element is passed as an option to Select, it gives an error !

### ISSUE THREAD

**Issue by ypinneka** [grommet/grommet#5178]
Issue reproducible, https://codesandbox.io/s/cool-cherry-4r1f0?file=/src/App.js
Error shows up intermittently.

When search option is present in Select, there is no error.
<img width="1318" alt="Screen Shot 2021-04-19 at 3 25 27 PM" src="https://user-images.githubusercontent.com/60210530/115311258-35e49700-a124-11eb-9745-958582adae32.png">

**Comment by jcfilben** [comment]
Steps to reproduce:
1. Select the JSX element
2. Try typing in the select
3. Should get "label.charAt is not a function"
