### ISSUE TITLE
Testing - Refactor the usage of `renderer.create` to `render`

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#5197]
### Expected Behavior
In our grommet testing, we shouldn't use `renderer.create` from 
```
import renderer from 'react-test-renderer';
```
Instead, we should use `render` by 
```
import { render } from '@testing-library/react';
```

### Actual Behavior
Some tests are still using the legacy API.

### Steps to Reproduce

1. Go to tests that use the older API
2. Replace it with the better practice API suggested above.

### Your Environment

- Grommet version: stable
- Browser Name and version:N/A
- Operating System and version (desktop or mobile): N/A

**Comment by g4rry420** [comment]
I am working on it.

**Comment by g4rry420** [comment]
Shall I also remove package `react-test-renderer` ?

**Comment by g4rry420** [comment]
Some of the test are using utility functions such as `findAllByType`. I believe those tests should remain the same. Because if I change them then I also have to change the utility functions, which might be used in other areas of repository. Need your inputs.

**Comment by g4rry420** [comment]
I have made the changes but the pr is a big one. Not sure if I should still make request for it or not ?
