### ISSUE TITLE
Supplement release notes with any areas which might benefit from greater context or clarity

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#5207]
https://github.com/grommet/grommet/wiki/Release

Add clarification or supplement with example for the following release process steps:
- Pre-reqs
  - Step 2 - NPM permissions not necessary since publishing is triggered via Github, not via npm publish command
  - Step 3 - Elaborate on Grommet's flavor of SemVer
  - Step 4 - Provide annotated minutes so that a viewer can jump to relevant content areas in the video
  - Step 6 - Use Slack name if available, otherwise use Github handle

- Let's Get Started
  - Step 3 - Elaborate(?)
  - Step 4 - Grommet flavor of SemVer
  - Step 9 - Explain that this step will publish to NPM

- On Github
  - Supplement these steps with screenshots(?)
  - Step 1 - Provide release notes conventions (e.g. props in backticks, capitalization of component names, how/when to group topics, past tense verbs, verbs to use, ...)
  - Use tag as release title

- Confirmation
  - Confirmation on CodeSandbox has some idiosyncrasies which could be elaborated
  

### Adjustments related to HPE Theme Release 

- Let's Get Started

10. Run locally yarn build to create the production files. (Add in that skip these steps when doing hpe theme release)
11. Run locally npm run pack to create the license files. By the end of this flow, there should be 2 files created on your local environment, a .json and .tgz files for the deployment and licensing.(Add in that skip these steps when doing hpe theme release)

- Last Steps
2. Do we need to update grommet-theme-hpe dependencies in `package.json` on `grommet` or how will that be handled? (This time, Shimi was already updating grommet dependencies so she handled it)

**Comment by halocline** [comment]
@taysea - Can you please review the edits made to the release steps? https://github.com/grommet/grommet/wiki/Release

Only item I was not clear on was:
Last Steps
Do we need to update grommet-theme-hpe dependencies in package.json on grommet or how will that be handled? (This time, Shimi was already updating grommet dependencies so she handled it)

**Comment by taysea** [comment]
@halocline I've reviewed. Notes look good. The item you were unclear on was related solely to theme release and has been included under last steps: https://github.com/grommet/grommet-theme-hpe/wiki/Release#last-steps

I think we can close this issue now.
