### ISSUE TITLE
Tests - DateInput snapshot tests were failing when a new month starts

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#5208]
DateInput snapshot tests were failing because it is a new month. For now I just updated the snapshots but eventually these tests should be rewritten so that the snapshots don't fail at the start of every new month. The UI test differences are also related to the month change

_Originally posted by @jcfilben in https://github.com/grommet/grommet/issues/5202#issuecomment-831388261_

**Comment by jcfilben** [comment]
Closing since #5408 was merged and fixed the issue
