### ISSUE TITLE
Pagination module is missing from the latest version

### ISSUE THREAD

**Issue by emonakov** [grommet/grommet#5214]
https://v2.grommet.io/pagination

### Expected Behavior

It creates a pagination element

### Actual Behavior

Module '"grommet"' has no exported member 'Pagination'.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/1624819/117010952-3f096280-ace5-11eb-9714-b209d207ccde.png)

### Steps to Reproduce

1. Create grommet project
2. Import Pagination from grommet
3. Observer the error

### Your Environment

- Grommet version: 2.17,2
- Browser Name and version: Any modern browser

**Comment by ShimiSun** [comment]
I think you should try cleaning up your lock files and re-install your dependencies.

**Comment by crashuniverse** [comment]
We made you https://codesandbox.io/s/peaceful-rhodes-61rgi?file=/src/App.js so that you can look at a very simple example, sometimes away from complex projects lets us see problems in isolation and clarity.

**Comment by emonakov** [comment]
@ShimiSun @crashuniverse Removing node_modules and reinstalling worked
Thanks for the help!
