### ISSUE TITLE
CheckBox and CheckBoxGroup should accept children

### ISSUE THREAD

**Issue by Tbhesswebber** [grommet/grommet#5221]
In terms of intent, a raw HTML checkbox group is a radio group that allows multiple selections. Given this, the API for the two should be the same when it comes to rendering.

### Expected Behavior

In our forms, we need non-dropdown interfaces for multiple and single selections - i.e. checkbox groups and radio groups.  To support this, we have the following component for the radio button (it's not a radio group because we have a custom radio group that uses a Grid rather than a Box).

```ts
interface RadioChipProps extends Omit<RadioButtonProps, "label"> {
  label: string;
}

function RadioChip({
  name,
  label,
  ...radioProps
}: RadioChipProps): JSX.Element {
  return (
    <RadioButton name={name} {...radioProps} value={label}>
      {({ checked }: { checked: boolean }) => (
        <Chip
          background={!checked ? Colors.white : Colors.primary}
          label={label}
          fill
        />
      )}
    </RadioButton>
  );
}
```

I didn't reference the docs before then writing the following for a CheckBox, which I expected to work with some minor tweaks once I did reference the docs.

```ts
interface CheckBoxChipProps extends Omit<CheckBoxProps, "label"> {
  label: string;
}

function CheckBoxChip({
  name,
  label,
  ...checkBoxProps
}: CheckBoxChipProps): JSX.Element {
  return (
    <CheckBox name={name} {...checkBoxProps}>
      {({ checked }: { checked: boolean }) => (
        <Chip
          background={!checked ? Colors.white : Colors.primary}
          label={label}
          fill
        />
      )}
    </CheckBox>
  );
}
```

### Actual Behavior

The browser throws the following error (in addition to an error about a function not being a valid React child):

![image](https://user-images.githubusercontent.com/28069638/117159553-60725900-ad8e-11eb-99bf-d338044dcbd2.png)

### Your Environment

- Grommet version: ^2.17.2 
- React version: ^17.0.2

**Comment by jcfilben** [comment]
Closing since #5460 was merged
