### ISSUE TITLE
DateInput - format issue

### ISSUE THREAD

**Issue by NRamasamy82** [grommet/grommet#5224]
<FormField name="value" label="value" required>
<DateInput name="value" value={this.state.testDate} format="mm/dd/yyyy" />
</FormField>

![image](https://user-images.githubusercontent.com/32128534/117214231-2458eb80-adc2-11eb-894d-cebe20ab2ca6.png)

<img width="198" alt="DateInputformatt" src="https://user-images.githubusercontent.com/32128534/117214307-42265080-adc2-11eb-86f6-5055e385460f.PNG">

### Expected Behavior

Since the format is mm/dd/yyyy, it should be "09/08/2020".

### Actual Behavior

Display date as  "9/8/2020". Please refer the attached screenshots.

### Steps to Reproduce

1. Create a "formfield".
2. Create a "DateInput" inside the form field.
3. Define format as mm/dd/yyyy.
4. Run the page in the browser and select the date from the calendar icon where month or day is single digits.

<FormField name="value" label="testDate" required>
<DateInput 
        name="value"
         value={this.state.testDate} 
        format="mm/dd/yyyy" 
/>
</FormField>

### Your Environment
- Grommet version: 2.17.0
- Browser Name and version: chrome latest
- Operating System and version (desktop or mobile): windows 10

**Comment by crashuniverse** [comment]
I could not reproduce this. I tried this at https://codesandbox.io/s/peaceful-rhodes-61rgi?file=/src/App.js
@NRamasamy82 can you help me understand 1st step to reproduce well, do we keep this input inside a formfield - is it a different tag that i used `<form>`? If you could edit the sandbox, save, share, it helps troubleshoot.

**Comment by NRamasamy82** [comment]
I'm modifying the CodeSandbox. I will keep you posted.

**Comment by ericsoderberghp** [comment]
Still not able to reproduce and needing guidance on how to. Closing for now due to inactivity.
