### ISSUE TITLE
Layer component does not animate in mobile

### ISSUE THREAD

**Issue by brianbancroft** [grommet/grommet#5236]
### Expected Behaviour

On mobile devices (or simulated), I would expect the Layer component to animate with the following props provided:

```js
     <Layer
        position="left"
        modal={false}
        onEsc={() => setLayer(false)}
        onClickOutside={() => setLayer(false)}
      >
```

### Actual Behaviour

Only animates in desktop [when the size in `ResponsiveContext` is not "small"]

https://codesandbox.io/s/grommet-layer-no-animate-mobile-hl9cr?file=/src/Layout.js&resolutionWidth=320&resolutionHeight=675

I am unsure whether this is a bug or is intended behaviour. If intended, I would be happy to change the documentation to make clear this edge.

### Steps to Reproduce

1. Check out codesandbox
2. Click Menu icon on top of simulation to trigger the layer

### Your Environment

- Grommet version: 2.17.2
- Browser Name and version: Chrome 90.0.4430.93
- Operating System and version (desktop or mobile): MacOS Big Sur 11.2.3

**Comment by jcfilben** [comment]
Closing since #5274 has been merged

**Comment by brianbancroft** [comment]
Thanks @g4rry420!
