### ISSUE TITLE
DataTable groupBy throws typescript exception on use

### ISSUE THREAD

**Issue by serp777** [grommet/grommet#5240]
Greetings. I've got a data table of 10 items, one of which is a server model. I want to group items in the table by the server model, which is a property in my row/column configs. 

Group By should perform as shown in the storybook/not throw an exception.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/10540204/117719774-082ac500-b19b-11eb-9963-f32a8d54eba7.png)

![image](https://user-images.githubusercontent.com/10540204/117719817-1842a480-b19b-11eb-8e25-4d60c5e60fb8.png)

### Steps to Reproduce

1. Create a simple typescript react app
2. NPM install all grommet dependencies
3. Add a data table
4. Use group by in that data table
5. Setup some simple columns 
6. Setup some test row data
7. Run app, see exception.

### Your Environment

- Grommet version:
    "grommet": "^2.17.1",
    "grommet-icons": "^4.5.0",
    "grommet-theme-hpe": "^2.0.2",
- Browser Name and version: Microsoft Edge
- Operating System and version (desktop or mobile): Windows 10 64 bit

**Comment by jcfilben** [comment]
Closing since this was fixed in v2.17.2 with PR #3991
