### ISSUE TITLE
Meter component need more flexibility

### ISSUE THREAD

**Issue by yangguoyk2015** [grommet/grommet#525]
Due to our specific requirement, we need the capability to 
1. choose the position of the value of meter when its used as a progressBar. put it top/ left/ right/ bottom.
2. we can hide the value of meter as well. so far, the value is always present, no option to hide it.

Looking for your answers.

**Comment by bryanjacquot** [comment]
@yangguoyk2015 you can show/hide the legend, but currently the value is always shown.  Can you provide more context for what you're needing to be able to achieve?

**Comment by bryanjacquot** [comment]
@yangguoyk2015 both of these capabilities are coming soon in updated chart and meter components.

**Comment by ericsoderberghp** [comment]
Meter now has a `label` property which you can set to `false` to disable showing the value as part of Meter. You can now put a `Value` on any side by putting it inside a `Box` containing the `Meter`.
