### ISSUE TITLE
Tip with grommet-icon direct child throws error

### ISSUE THREAD

**Issue by samuelgoff** [grommet/grommet#5256]
When `Tip` has a `grommet-icon` as a direct child, it throws an error.

### Expected Behavior

Looking at the [Tip docs](https://v2.grommet.io/tip), I see an example that leads me to believe it should be safe to wrap the tip around other Grommet components, like so:

```
<Tip content="tooltip">
   <Button label="hover me" /> 
</Tip>
```

So I should be able to replace the nested `Button` with a `grommet-icon`, like so:
```
<Tip content="Secure URL has been defined separately from this Display URL.">
  <Secure color="green" />
</Tip>
```

### Actual Behavior

This throws the following error:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `Tip`.
    in Secure (at urlIcon.js:13)
    in Tip (at urlIcon.js:12)
```

### URL, screen shot, or Codepen exhibiting the issue
![Screen Shot 2021-05-14 at 1 10 24 PM](https://user-images.githubusercontent.com/2007084/118311670-d163f000-b4b5-11eb-9773-945c259b5676.png)

The same error can be reproduced at the following sandbox:
https://codesandbox.io/s/grommet-v2-template-forked-t8u9n

![Screen Shot 2021-05-14 at 1 14 09 PM](https://user-images.githubusercontent.com/2007084/118312032-5cdd8100-b4b6-11eb-907f-f57156b327f4.png)

### Steps to Reproduce

1. Use a `Tip` component
2. make a `grommet-icon` a direct child

### Your Environment

- Grommet version:
-- `"grommet": "^2.17.2",`
-- `"grommet-icons": "^4.5.0",`
- Browser Name and version:
- - Safari Version 14.1 (16611.1.21.161.6)
- - Google Chrome Version 90.0.4430.212 (Official Build) (x86_64)
- Operating System and version (desktop or mobile): macOS Big Sur Version 11.3.1

**Comment by ShimiSun** [comment]
Can you please confirm whether this issue is related to https://github.com/grommet/grommet/issues/5149?

**Comment by samuelgoff** [comment]
Hey Shimi, I tried the workaround you suggested and it resolves the error. That said, the description (and folllow-up discussion) on this ticket is misleading, since a grommet-icon is not an input component.

**Comment by ShimiSun** [comment]
Thanks, @samuelgoff , just to confirm: 
1. I'm seeing a Warning vs an Error on the console log, is that what you are experiencing, or am I missing something?
2. The functionality is working as expected it is just the console warning that is the issue, correct? Or should I be aware of functionality implications as well?

Thanks,
Shimi

**Comment by samuelgoff** [comment]
> 1. I'm seeing a Warning vs an Error on the console log, is that what you are experiencing, or am I missing something?
> 2. The functionality is working as expected it is just the console warning that is the issue, correct? Or should I be aware of functionality implications as well?

Hey @ShimiSun,

**1. Warning vs Error:** I think we're seeing the same thing, but we're using different terminology. If you look at the screen grab, it says "warning" but the color is red. This result is what you get when you use `console.error(errorGoesHere)` in the code. So to my mind, this is an "error", even if the text in the error says "warning". If it is a warning, it should use `console.warn(warningGoesHere)`, like so:
![Screen Shot 2021-05-25 at 10 30 57 AM](https://user-images.githubusercontent.com/2007084/119525881-7f885900-bd44-11eb-8be3-5175480ce49d.png)

**2. Functionality:** To my mind, the fact that they chose to use `console.error` is an indication that it is (or can be) more serious than a simple warning. It means that this will work -- right up until it doesn't. I haven't needed to use refs with this component personally, but I can imagine a large number of scenarios where the expected behavior (including extensibility) for Grommet components -- that simply work in every other combination -- break when you combine them in this particular instance. Our own codebase does contain multiple instances of using refs with Grommet components, so this is not a hypothetical.

Personally, I detest log spam, so I work in such a way that if any errors or warnings are generated, I clean them up right away so the signal-to-noise ratio is optimal. If I break something -- or if I'm in danger of breaking something in the future -- I want to know about it ASAP, so I can pro-actively make decisions to minimize this risk.

**Comment by ShimiSun** [comment]
Thank you for the clarification, the intention with the confirmation questions above is just to understand whether I'm missing any pieces. We do encourage users to file issues on console warnings/errors, so thank you for reporting.

**Comment by ericsoderberghp** [comment]
This issue might be related to grommet-icons more than grommet.

**Comment by jlaluces123** [comment]
Hello @samuelgoff ! I made changes to `grommet-icons` so it no longer throws a console error by introducing forwardRefs to the icons themselves. If you wanted / needed to see these changes immediately you could go into your `package.json` and point to the stable branch of grommet-icons via: 

"grommet-icons": https://github.com/grommet/grommet-icons/tarball/stable

Please let me know if the issue still persists or if other issues arise when using a grommet-icon as a direct child of Tip!

**Comment by samuelgoff** [comment]
> Hello @samuelgoff ! I made changes to `grommet-icons` so it no longer throws a console error by introducing forwardRefs to the icons themselves. If you wanted / needed to see these changes immediately you could go into your `package.json` and point to the stable branch of grommet-icons via:
> 
> "grommet-icons": https://github.com/grommet/grommet-icons/tarball/stable
> 
> Please let me know if the issue still persists or if other issues arise when using a grommet-icon as a direct child of Tip!

Hey @jlaluces123 thanks so much! 🙏🏼 We already used the workaround to mitigate log spam in the meantime, so this isn't hair-on-fire emergency at the moment. I'll be happy to bump the dependencies when the next Grommet-icons release occurs and then cleanup the child-wrapping elements. Thanks again!
