### ISSUE TITLE
`hoverIndicator` causes button to lose text color

### ISSUE THREAD

**Issue by anderoonies** [grommet/grommet#5262]
### Expected Behavior

When specifying a `hoverIndicator` on a button, I'd expect to be able to either specify:

```js
hoverIndicator: {
    background: {
        color: 'hover-bg',
    },
    color: 'hover-txt',
}
```

or to have the `button.secondary.hover.color` style remain.

### Actual Behavior

When specifying a `hoverIndicator` on a button, the text color is replaced.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-0byc6?file=/index.js

### Steps to Reproduce

https://codesandbox.io/s/grommet-v2-template-forked-0byc6?file=/index.js
Hover over the button

### More details

It looks like the [`hoverIndicatorStyle`](https://github.com/grommet/grommet/blob/08f320d17ab3edc9abeceab559075b3a957cbce9/src/js/components/Button/StyledButtonKind.js#L177) is only passing a `themishObj` with `.background`, so the `obj.color` handling in [`kindPartStyles`](https://github.com/grommet/grommet/blob/08f320d17ab3edc9abeceab559075b3a957cbce9/src/js/utils/styles.js#L567) isn't used, so the resulting `&:hover` will never have `color` set

**Comment by ShimiSun** [comment]
Just to clarify, when attempting to use `button.secondary` one must have `button.default` configured on the theme, are you using the `button.default`?

**Comment by anderoonies** [comment]
Yep, I have an empty object for “default” in the theme in the sandbox, and
the background color for the “secondary” button is changing, so I think
that’s working properly.

**Comment by ShimiSun** [comment]
Thank you for reporting, the issue will be fixed in our next release.
