### ISSUE TITLE
[QUESTION] How to use a Select component with server-side searches inside FormField?

### ISSUE THREAD

**Issue by ahlechandre** [grommet/grommet#5269]
Here is my basic implementation of a Select component with server-side searches inside FormField:

```js
export default function AddProduct() {
  const [form, setForm] = useState({ category_id: '' })
  const [categories, setCategories] = useState([])
  const onSearch = string => {
    const makeRequest = async () => {
      const term = string && string.length ? string.trim() : ''
      const options = { q: term, 'per-page': 1 }
      // Requesting categories based on user's search.
      const res = await API().categories.fetchMany(options)

      try {
        const json = await res.json()
        // Updating the categories list on-the-fly from server-side response.
        setCategories(json.data)
      } catch (e) {
        // ...
      }
    }
    makeRequest()
  }

  return (
    <Box>
      <Form
        value={form}
        onChange={nextForm => setForm(nextForm)}
      >
        <FormField
          name='category_id'
          htmlFor='input-categories'
          label='Categories'
        >
          <Select
            name='category_id'
            // Dispatches the first request (usability only) in order to prevent
            // user from viewing an empty list.
            onOpen={onSearch}
            onSearch={onSearch}
            // Options are always the filtered list from server-side.
            options={categories}
            labelKey="name"
            valueKey={{ key: 'id', reduce: true }}
          />
        </FormField>
      </Form>
    </Box>
  )
}
```

### Expected Behavior

I expected users to search & select options indefinitely without selected option becoming blank when it's not present in the options array.

### Actual Behavior

If users search for a category and choose then it is correctly displayed as the selected options BUT when the user search again and the selected option doesn't appears on the server-side result (in other words, not in the options list) then the selected option becomes blank.

### URL, screen shot, or Codepen exhibiting the issue

Here I'm intentionally rendering only one result per search. First, I select "Tijolo" category. Then I change to "Ferro". Last step I opened the select dropdown, which dispatches a request "onOpen" event, and "Ferro" is not present in the results then it's options becomes blank:

https://user-images.githubusercontent.com/7119058/118824267-b6afc380-b887-11eb-907f-de4a36df3839.mov

> As we can see, "onSearch" events doesn't appears to make it blank but "onOpen" does. Now I'm wondering why.

### Steps to Reproduce

1. Add a Select component inside Form > FormField
2. Implement a search mechanism based on server-side responses
3. Selected option disappears when the option is not present in the current options list.

### Your Environment

- Grommet version: 2.17.2
- Browser Name and version: Google Chrome, Version 90.0.4430.212 (Official Build) (x86_64)
- Operating System and version (desktop or mobile): macOs Catalina

**Comment by ericsoderberghp** [comment]
I think this is caused by Select not knowing what the label should be using the `labelKey` because there aren't any options that match the `valueKey` to retrieve it from. In some sense, this matches the native `<select />` behavior, where you have to have the selected `<option />` present.

The `valueLabel` is intended to handle this case. You could keep the currently selected option in full in state somewhere and then pass the name label to `valueLabel`.

**Comment by ahlechandre** [comment]
@ericsoderberghp Well, thanks. It closes the question.

Besides that, do you have some example of `valueLabel` node implementation? I couldn't find any so what I'm using:

```js
<Select
  name='category_id'
  onOpen={onSearch}
  onSearch={onSearch}
  options={categories}
  labelKey='name'
  valueKey={{ key: 'id', reduce: true }}
  valueLabel={selectedCategory ? (
    <TextInput
      plain
      focusIndicator={false}
      value={selectedCategory.name}
    />
  ) : undefined}
/>
```
