### ISSUE TITLE
DataTable groupBy should use InfiniteScroll

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5283]
### Expected Behavior

groupBy should leverage InfiniteScroll so grouped data isn't all rendered at once.

### Actual Behavior

InfiniteScroll is not being used with grouped data. Therefore, when a group has many items (such as 500 in a group), the application is slowed down.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: stable
- Browser Name and version: macos chrome
- Operating System and version (desktop or mobile): mac os

**Comment by jennifer-manriquez** [comment]
Hi, I would like to work with this issue :)

**Comment by ericsoderberghp** [comment]
> Hi, I would like to work with this issue :)
great!

**Comment by jennifer-manriquez** [comment]
Hi! I have been doing some research on this. I had though that embedding infiniteScroll in the fragment that controls the expanded group could work, but I guess that's not just it, for now I have only been getting it to render the first {step} elements.  The render marker does seem to be setting, but I guess I must still be missing something. Also, I was wondering if each group should have its own scroll to set the infinite scrollable ancestor to get this to work, or if the issue could be elsewhere. 

I also wanted to ask which were your general ideas on going about this issue, or if the approach should be other. 

For now I had set the step to 5 (for testing purposes, but I guess in the end should leave the default),  I gave the group.data.map function as the children of the infiniteScroll, and set the marker function same as the one in Body.  
<img width="1205" alt="Screen Shot 2021-07-06 at 15 01 43" src="https://user-images.githubusercontent.com/56976945/124660627-12e89a00-de6c-11eb-881c-bacc6b0261ff.png">



Thanks in advance.

**Comment by MikeKingdom** [comment]
Since each expanded group is basically a fragment of `<tr>` elements in the same table body,  InfiniteScroll gets confused when trying to calculate what's visible, so it doesn't work to try and have a separate InfiniteScroll for each expanded group. Instead, GroupedBody in DataTable needs a single InfiniteScroll for the entire table body, just like the normal/non-grouped DataTable Body.js does. PR #5452 does this.
