### ISSUE TITLE
DataTable typescript definition misses theme property

### ISSUE THREAD

**Issue by emonakov** [grommet/grommet#5286]
DataTable typescript definitions do not include theme property which makes theming problematic

### Expected Behavior
DataTable definition has theme property defined and the compiler doesn't throw errors

### Actual Behavior
DataTable doesn't have theme property definition which causes the compiler to fail

### URL, screen shot, or Codepen exhibiting the issue
https://github.com/grommet/grommet/blob/master/src/js/components/DataTable/index.d.ts#L57-L107

### Steps to Reproduce

1. Try to override the theme prop of DataTable
2. Fail with compilation

### Your Environment

- Grommet version: 2.17.2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Desktop

**Comment by ericsoderberghp** [comment]
Hmm... DataTable doesn't have a `theme` prop though. The themes come from `<Grommet theme={theme} />` where that theme object contains a `dataTable` key that refers to an object describing how to theme the DataTable.

**Comment by emonakov** [comment]
> Hmm... DataTable doesn't have a `theme` prop though. The themes come from `<Grommet theme={theme} />` where that theme object contains a `dataTable` key that refers to an object describing how to theme the DataTable.

But Data table itself is accepting theme property like almost any other component in grommet. It's just not documented. But maybe you are right and I need to modify theme globally, not only for one component. Anyway, if I ignore typescript error theme override works perfectly fine, it's just missing definitions.

**Comment by ericsoderberghp** [comment]
Can you clarify where you are seeing that `<DataTable theme={} />` is effective? I don't see it in the properties list for DataTable: https://github.com/grommet/grommet/blob/b7537c9756630db9863542d4fa1e73675078f265/src/js/components/DataTable/DataTable.js#L75

**Comment by emonakov** [comment]
> Can you clarify where you are seeing that `<DataTable theme={} />` is effective? I don't see it in the properties list for DataTable:
> 
> https://github.com/grommet/grommet/blob/b7537c9756630db9863542d4fa1e73675078f265/src/js/components/DataTable/DataTable.js#L75

I initially tried to reduce the font size of the Text components inside datatable which I somehow achieved with the help of theme property on the table itself. I should've mentioned this first place. Didn't want to change the global theme but the datatable. It's working, but as I mentioned, but only with ts-ignore flag.

**Comment by jcfilben** [comment]
The theme isn't meant to be passed to DataTable and instead should just be passed to `<Grommet>` so I don't think the typescript theme definition shouldn't be added to DataTable, it is not documented that way and it is not included in any other components

**Comment by jcfilben** [comment]
Hey @emonakov I'm going to go ahead and close this issue since DataTable should be themed through the `<Grommet>` component
