### ISSUE TITLE
TextInput placeholder will not removed when it is JSX.Element

### ISSUE THREAD

**Issue by gavin99587** [grommet/grommet#5299]
TextInput placeholder can not removed when it is JSX.Element, while when the placeholder is a simple string ,it works as
 expected

<img width="464" alt="截屏2021-06-03 17 45 02" src="https://user-images.githubusercontent.com/11565497/120624600-71001700-c493-11eb-9496-1716ca0588b1.png">

if the placeholder is  a JSX.Element,when i change the value through a function  named handleBtnAllTap, the placeholder will not disappear, but is the placeholder is a simple string,it works as expected.

    <Box width={blockWrap.width} margin={{ top: '24px' }}>
          <Form
            value={formValue}
            onChange={(v) => setFormValue(v)}
            onSubmit={handleFormSubmit}
          >
            <Box direction="column">
              <Box direction="row" align={'center'} justify={'between'}>
                <FormFieldWrap
                  name="amount"
                  label={
                    <Text size="xsmall" color={CustomColor.c697281}>
                      Amount
                    </Text>
                  }
                >
                  <TextInput
                    name="amount"
                    type="text"
                    placeholder={
                      <Text size="small" color={'#697281'}>
                        I am placeholder
                      </Text>
                    }
                  />
                </FormFieldWrap>
                <Anchor size="small" onClick={handleBtnAllTap}>
                  All
                </Anchor>
              </Box>
            </Box>
          </Form>
        </Box>

1. 2. 3.

### Your Environment

- Grommet version:2.17.1
- Browser Name and version: chrome
- Operating System and version (desktop or mobile):

**Comment by loongluangkhot** [comment]
Hey @ShimiSun, i'm a new contributor here, and i'd like to work on this issue! Wondering how do i self-assign / if you could assign this issue to me?

**Comment by jcfilben** [comment]
@loongluangkhot feel free to go ahead and work on this issue

**Comment by g4rry420** [comment]
@loongluangkhot Are you still working on this issue ? If not, Can I take this one ?

**Comment by loongluangkhot** [comment]
@g4rry420 pls go ahead and do it. Sorry for super late reply!

**Comment by jcfilben** [comment]
Closing this issue since #5571 has been merged.
