### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by kennynaoh** [grommet/grommet#530]
Hello @alansouzati ,
I am the member of the [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
The license in ```package.json``` on github is Apache-2.0
But the license in ```grommet.min.js``` on [npm](https://www.npmjs.com/package/grommet) is MIT
So what license should be used or both of them?
Thanks.

https://github.com/cdnjs/cdnjs/issues/7343
https://github.com/cdnjs/cdnjs/pull/7412

**Comment by alansouzati** [comment]
Thanks for your question. The MIT licenses inside the minified js are coming from the libraries we use.

Grommet license is Apache 2 and I believe we don't add the license inside the minified js.

Please let me know if my understanding in wrong.

**Comment by kennynaoh** [comment]
Thanks!
So you mean both are used, right?

**Comment by PeterDaveHello** [comment]
grommet is using Apache-2.0

**Comment by kennynaoh** [comment]
Thanks!
