### ISSUE TITLE
DataChart does not display details for large data sets

### ISSUE THREAD

**Issue by GautamSatish** [grommet/grommet#5312]
Data chart doe not display details when the chart large number of points.

### Expected Behavior

DataChart should display details for the larger data sets or the limit should be documented so that data sets can be sampled down to required size.

### Actual Behavior

The vertical marker does not show up, probably because the points are too close to each other?

### URL, screen shot, or Codepen exhibiting the issue
CodeSandbox link: https://codesandbox.io/s/perf-data-j0rhn?file=/src/App.js

### Steps to Reproduce

1.  The sandbox renders sensor values at 30 intervals, 180 intervals and so on. Except for 30 intervals, the details do not appear for the rest of the charts.

### Your Environment

- Grommet version: 2.17.2
- Browser Name and version: Same across Chrome and Firefox
- Operating System and version (desktop or mobile): Does not matter

**Comment by jcfilben** [comment]
Looks like the limit is 120, you can see that in this [codesandbox](https://codesandbox.io/s/perf-data-forked-4qxlm?file=/src/App.js) if you add one more field to the json data (bringing total to 121) the details will no longer display. I am still looking to see if it is possible to expand this limit or if should just be added to the documentation.
