### ISSUE TITLE
Grommet Templates No Longer Working in CodeSandBox

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#5318]
### Expected Behavior
Grommet examples and templates should run in CodeSandBox.

### Actual Behavior
The Grommet v2 template (and others) throws an error "Cannot use import statement outside a module"

Note: this isn't related to the version of grommet or any other dependencies from what I can tell. I think that this is on CodeSandBox's end and there is an issue filed on their repository for this https://github.com/codesandbox/codesandbox-client/issues/5464. I wanted to create this issue for tracking purposes and to see if there is a workaround we can do to get grommet working in codesandbox.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/m7mml8l0zj

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: any
- Browser Name and version: chrome
- Operating System and version (desktop or mobile): mac os

**Comment by jsejcksn** [comment]
There's been a rapid series of codesandbox client service worker updates over the past couple of days. (@jcfilben You'll notice this when you see a "reload" icon at the top of your sandbox). I suspect that it's just an ephemeral bug in [sandpack](https://github.com/codesandbox/sandpack).

**Comment by jsejcksn** [comment]
Fixed in https://github.com/codesandbox/codesandbox-client/commit/a566285e0bac46978f5a3efd6796caef41762f44

Ref: https://github.com/codesandbox/codesandbox-client/issues/5464#issuecomment-859439346

**Comment by jcfilben** [comment]
Thanks for the follow up @jsejcksn. This issue was fixed on codesandbox's end but Grommet should still remove require statements to conform with ESModules. I am closing this issue since codesandbox is working with Grommet. The removal of require statements in grommet can be tracked through issue #4895
