### ISSUE TITLE
Allow caller to add a custom `onClick` function  to FileInput remove file button

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5321]
### Expected Behavior

Allow a user to provide some custom `onClick` handler to the remove button of FileInput, such as "onClick, open a confirmation dialog about removing the file". This would be useful in cases where file uploads/validations take a long time and removing the file automatically could cause time consuming work to need to occur again.

### Actual Behavior

No way to access any extra handler functions for the file remove button.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: stable
- Browser Name and version: chrome mac os
- Operating System and version (desktop or mobile): mac os mojave

**Comment by DouglasPds** [comment]
Hi, Can I try to implement this?

**Comment by jcfilben** [comment]
Closing since #5711 was merged and allows you to have a custom function for confirming removal of a file with the `confirmRemove` prop
