### ISSUE TITLE
Grommet compatibility on browser of Android 5

### ISSUE THREAD

**Issue by ryanadhibit** [grommet/grommet#5329]
Grommet caused trouble and make the web cannot load on stock Browser 5.1.1 of Android 5

### Expected Behavior

Web should be run normal on older version of Android

### Actual Behavior

Grommet made the web cannot load and shows an error on web console
When I tried to remove Grommet on my web, it runs fine

### URL, screen shot, or Codepen exhibiting the issue

![Screenshot 2021-06-16 223250](https://user-images.githubusercontent.com/70564966/122314815-11017a00-cf43-11eb-8306-869a90c495da.png)

### Steps to Reproduce

1. create a react web app following this instruction: https://developer.hpe.com/blog/using-your-first-grommet-component-with-create-react-app/
2. Deploy your app
3. Run Android simulator using Android Lollipop version
4. Open your deployed web
5. Web won't load (and you could see the error on web console)

### Your Environment

- Grommet version: v2.17.3
- Browser Name and version: stock android Browser 5.1.1
- Operating System and version (desktop or mobile): Android 5

**Comment by MikeKingdom** [comment]
@ryanadhibit I haven't had much luck debugging this in an emulator. I've tried Android Studio's emulator running 5.1.1 Lollipop. It seems to have trouble with most React apps. The browser is quite old
![image](https://user-images.githubusercontent.com/12054362/122470127-f0edad00-cf7a-11eb-9da8-7ced8ca05a71.png)

What emulator were you using and how'd you get the web console in the browser?

**Comment by ryanadhibit** [comment]
@michaelgilley I am using Android Studio with this emulator

![Screenshot 2021-06-17 163240](https://user-images.githubusercontent.com/70564966/122491654-92720e80-d00e-11eb-8026-f4def67dfe88.png)

if you are running emulator on android studio and open the browser inside the emulator, then on the desktop chrome you can go to  `chrome://inspect/#devices` and you will be able to inspect the emulator's web

![Screenshot 2021-06-18 082533](https://user-images.githubusercontent.com/70564966/122491842-f0065b00-d00e-11eb-8709-11e1de02a75d.png)

it will be right there on the arrow (unfortunately I wasn't opening my emulator at this moment)

**Comment by ryanadhibit** [comment]
@MikeKingdom 

Hi, just trying thins here and there
applying both these solutions seems make it working

- https://stackoverflow.com/a/53633307/13311122

- https://stackoverflow.com/a/56882937/13311122

**Comment by MikeKingdom** [comment]
@ryanadhibit Thanks for the tip! I'm glad to hear the polyfills help it run on the older browsers.

Given that's the case I'm closing this issue. Thanks for the great work in this area!
