### ISSUE TITLE
[Button > Badge]: Using badge prop in button doesn't show the badge

### ISSUE THREAD

**Issue by rodrigoea** [grommet/grommet#5360]
### Expected Behavior

Using the prop `badge` in a `Button` should display the badge itself as we see in Storybook:

![image](https://user-images.githubusercontent.com/1905961/123140374-99918600-d42d-11eb-89f2-64d068580680.png)

### Actual Behavior

When I'm passing `badge` to the `Button` component, with any props, it's not showing the badge.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/1905961/123140898-348a6000-d42e-11eb-9afb-139d30e32c98.png)

https://codesandbox.io/s/elastic-nobel-8cb8b?file=/src/App.js

### Steps to Reproduce

1. Import Button from grommet
2. create the following component: `<Button a11yTitle="2 Updates Available" label="Updates" badge={20} />`
3. badge doesn't show up

### Your Environment

- Grommet version: 2.17.2
- Browser Name and version: NA
- Operating System and version (desktop or mobile): NA

**Comment by ericsoderberghp** [comment]
It seems to be working here: https://v2.grommet.io/button?c=DwIQrgLhD2B2AEAbAhgIwKaILwCIUcR3ggEsAHXNADyNWQBMBzdLAbwCYAGAXwHoA+IA

I'm wondering if it requires grommet version 2.17.3?

**Comment by rodrigoea** [comment]
@ericsoderberghp weird, because even changing the version in this codesandbox to `2.17.3`, it doesn't work, it also throws an error now:

![image](https://user-images.githubusercontent.com/1905961/123142656-0e65bf80-d430-11eb-99b5-837888f4c872.png)

**Comment by rodrigoea** [comment]
Updated to `2.17.3` in my local project and it worked, thanks for the quick support :)
