### ISSUE TITLE
Reset Select programmaticaly

### ISSUE THREAD

**Issue by atoy40** [grommet/grommet#5366]
Hello,
I've a Select where options is a list of object.
the "value" attribut is "attached" to a react hook state and the onchange handler set the state value.

To reset the Select value and display the placeholder again (a typical form reset behavior) I've tried to set the state value to undefined, but it has no effect on the Select.

### Expected Behavior

Reset the Select value and display the placeholder as it was in the initial loading of the app.

### Actual Behavior

setting the value to undefined doesn't reset the Select value.

### URL, screen shot, or Codepen exhibiting the issue

this codepen is a simple select with two options and a Button to reset the select.

https://codesandbox.io/s/grommet-v2-template-forked-0hbmc

Anthony.

**Comment by jcfilben** [comment]
Here is an example of a Select with a reset button https://storybook.grommet.io/?path=/story/input-form-uncontrolled--uncontrolled

**Comment by atoy40** [comment]
thks @jcfilben, but in this example (and other form examples) the Select is not "managed" using value/onchange attributes as you can do with formik or with a simple state as I did in my example.

**Comment by jcfilben** [comment]
Here is a controlled version of this example where the Select uses `value` and `onChange` https://storybook.grommet.io/?path=/story/input-form-controlled-input--controlled-input

**Comment by atoy40** [comment]
Yes but it's not reset programmatically, it just reacts to the reset button of the form.
But how to reset de Select value from code ?

**Comment by jcfilben** [comment]
Ah okay I see, here is a codesandbox that is reseting the select value https://codesandbox.io/s/grommet-v2-template-forked-6g7kw?file=/index.js

Note: another option is to use the 'clear' prop in Select https://v2.grommet.io/select#clear

**Comment by atoy40** [comment]
ok, so the solution is to set an object which does not exist in the options array.
It sound to me better if setting value to undefined would have the same behavior :)

Anthony.

**Comment by jcfilben** [comment]
@ericsoderberghp do you know if there are any reasons we aren't currently supporting setting the value to `undefined` as a way to clear the select?

**Comment by ericsoderberghp** [comment]
> @ericsoderberghp do you know if there are any reasons we aren't currently supporting setting the value to `undefined` as a way to clear the select?

Setting `value={undefined}` makes it an uncontrolled input. I think the essence of this issue is how to programmatically change a controlled Select to have no value. For TextInput, one can do `value=""`. We need an equivalent for Select. We cannot use `undefined`. Perhaps `value={null}`? or maybe even `value=""`?

**Comment by jcfilben** [comment]
Setting `value=""` is currently working as a way to clear the select as shown in this code sandbox https://codesandbox.io/s/grommet-v2-template-forked-6g7kw?file=/index.js so I think we can close this issue

**Comment by jcfilben** [comment]
Closing since I think this issue is resolved with the use of `value=""` to reset the select as demonstrated in the codesandbox above.
