### ISSUE TITLE
'Justify' text-alignment

### ISSUE THREAD

**Issue by smalltimer** [grommet/grommet#5368]
I would like to justify the text on a series of blog-pages. My plan is to create a `Box` element in grommet and then insert the output from a remark-based plugin for gatsby ([link](https://www.gatsbyjs.com/plugins/gatsby-transformer-remark/)) inside this box. I am not sure how to go about doing this. It is a blog, and there will be lots of paragraphs per post - I would like to make everything 'justify-aligned'.

### Expected Behavior

The text is justify-aligned.

### Actual Behavior

The options for text-based elements so far contain only 'start', 'center', and 'end'. So 'justify'-alignment is not possible.

### URL, screen shot, or Codepen exhibiting the issue

An example of justify-alignment: 
![](https://1.bp.blogspot.com/-_BSeaErZWM8/WiaFeMzSLNI/AAAAAAAAaJY/Brj91R9ROPYDzEcI4n9rbztYX_MPHElDACLcBGAs/s1600/text%2Balignment%2B%25286%2529.JPG)

### Steps to Reproduce

1. Go to docs for box (https://v2.grommet.io/box) or text-based elements (e.g., https://v2.grommet.io/paragraph). 
2. Look for textAlign "justify" or a variation thereof.
3. Not find it!

### Your Environment

- Grommet version: 2
- Development environment: gatsbyjs, v3

**Comment by jennifer-manriquez** [comment]
Hi, If it is okay I would like to help with this issue! :)

**Comment by jennifer-manriquez** [comment]
Hi if it is okay I would like to help with this issue! :)

**Comment by halocline** [comment]
> Hi if it is okay I would like to help with this issue! :)

That would be much appreciated. Consider it yours @jennifer-manriquez!

**Comment by LucasCarrias** [comment]
I've started working on this issue earlier as well. Will be any problem If I create a PR for this issue?
I've already made some commits with the changes, It shouldn't take longer to finish it.

I'm sorry to not comment here as soon I've started working with this issue.
