### ISSUE TITLE
Add spring animation to checkbox and RadioButton

### ISSUE THREAD

**Issue by dbuarque** [grommet/grommet#537]
Would be nice to have a spring animation to checkbox and RadioButton.

**Comment by L0ZZI** [comment]
Can you be more descriptive about what you mean by "spring"? Are you looking for the check to have some animation when something is clicked. Like draw the check or have the check animate in? Similar to Google's Material Design?

**Comment by bryanjacquot** [comment]
@dbuarque Can you be more specific about what you're looking for?

**Comment by bryanjacquot** [comment]
Closing for now.
