### ISSUE TITLE
DataTable pagination with a remote source

### ISSUE THREAD

**Issue by protek-vrn** [grommet/grommet#5394]
Hey guys,

Could you please point out to the docs or samples where to find info about using the pagination for the DataTable component in case the data source is a remote one?
 
The problem is, the table contains thousands of records, I don't want to transfer all the data to the browser. I'd like to render only the current page, and show the pagination buttons.

### Expected Behavior

Only data for the current page are requested, but the DataTable component "knows" how many records in total, and shows the pagination buttons accordingly.

### Actual Behavior

I did't find a sample in the storybook.

### URL, screen shot, or Codepen exhibiting the issue

No

### Steps to Reproduce

No

### Your Environment

- Grommet version: 2.17.3
- Browser Name and version: Chrome 91.0.4472.114
- Operating System and version (desktop or mobile): macOS Big Sur 11.4

**Comment by halocline** [comment]
Hi @protek-vrn, @taysea recently created a CodeSandbox demonstrating this behavior:  https://codesandbox.io/s/pagination-example-load-data-piugl?file=/index.js

- You'd make your fetch API call inside this example's `getNextData()`.
- `step` gets set to the number of records per page
- Pagination's `numberItemsProp` represents the total number of records needed to be paginated, so you'd want to call your API's get record count method.

Please confirm this satisfies your needs.

**Comment by protek-vrn** [comment]
hey @halocline,

This works just fine, thanks!
