### ISSUE TITLE
Checkbox focus state is stuck if the checkbox is disabled

### ISSUE THREAD

**Issue by MLRichmond** [grommet/grommet#5403]
### Expected Behavior

Focus should still respond appropriately after a checkbox has been disabled and subsequently re-enabled. 

### Actual Behavior

Focus borders become locked in place once a checkbox has been disabled. 

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/unruffled-browser-hewpg?file=/src/CheckBox.js

### Steps to Reproduce

1. Add a checkbox
2. Click the checkbox and disable it in the on-click (so before another control can acquire focus)
3. The checkbox focus border is now stuck, even if the checkbox is subsequently re-enabled.

See code sandbox. Other controls, such as button, do not seem to have this defect.

### Your Environment

- Grommet version: 17.3
- Browser Name and version: Chrome 91.0.4472.101
- Operating System and version (desktop or mobile): Desktop

**Comment by Spectre-ak** [comment]
Hi, I've created a PR for this issue [Fixes Checkbox focus state when checkbox is disabled](https://github.com/grommet/grommet/pull/5658)
