### ISSUE TITLE
navigation for "Nested Tabs" is not working

### ISSUE THREAD

**Issue by JhansiSimma** [grommet/grommet#541]
The Tabs usage like below is not working. While navigating between Slave Tabs it gets stuck at some point. 

<Tabs>
      <Tab title="Master Tab">
               <Tabs>
                <Tab title="Slave Tab1">
                 </Tab>
                <Tab title="Slave Tab2">
                 </Tab>
             
               ....
             </Tabs>
       </Tab>
</Tabs>

**Comment by bryanjacquot** [comment]
@JhansiSimma can you please provide more details using an example in Codepen preferably?  The example screen seems to be truncated.  If you're trying to use Tabs within Tabs, then you are attempting to use Tabs in a way that is not recommended and not supported.

**Comment by bryanjacquot** [comment]
Closing for now.   Please re-open and provide more details if necessary.
