### ISSUE TITLE
TextInput suggestions dropdown issue

### ISSUE THREAD

**Issue by ischoe** [grommet/grommet#5426]
Hi, i use the Textinput with suggestions from api calls. 
As my limit of results is always 5, the dropdown is not opening after i doubleclick inside to remove the value and type something new. I figured out that there is this suggestionsAtClose check, which might be the reason for this. 
```
if (focus && !showDrop && suggestions && suggestions.length && (!suggestionsAtClose || suggestionsAtClose.length !== suggestions.length)) {
      openDrop();
    }
```

You can also see the issue in the storybook : 
https://storybook.grommet.io/?path=/story/input-textinput-default-suggestion--default-suggestion

- type in sug, the dropdown is open
- double click inside and delete
- type again sug => no dropdown opens anymore.
=> You need to click outside and click inside again to make it work.

I am using the latest grommet version 2.17.3

**Comment by novykh** [comment]
@ischoe please check this PR https://github.com/grommet/grommet/pull/5625 to see if it works fine for you. Maybe show some love in order to merge it
