### ISSUE TITLE
[Bug] Select value is not displayed if `valueKey` is set to 'value'

### ISSUE THREAD

**Issue by jamie29w** [grommet/grommet#5435]
When passing an array of objects as the `options` and the `valueKey` is set to `'value'`, the `value` does not render correctly.

### Expected Behavior

A `valueKey` prop set to `'value'` should behave like any other `valueKey`.

### Actual Behavior

A `valueKey` prop set to `'val'` works as intended. But a `valueKey` set to `'value'` does not.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/upbeat-https-j85q8?file=/src/Select.js (Click the link to the Select demo.)

### Steps to Reproduce

1. In the sandbox, change the Select value. It works as expected.
2.  Comment out the first `OPTIONS` declaration and uncomment the second one.
3. Comment out the first `valueKey` select prop and uncomment the second one.
4. Refresh the sandbox browser.
5. Change the select value. The log in the render block reflects a state change. But the newly selected value does not show in the Select.

### Your Environment

- Grommet version: 2.17.3
- Browser Name and version: Chrome 91.0.4472.114
- Operating System and version (desktop or mobile): macOS Big Sur

**Comment by MikeKingdom** [comment]
@jamie29w Your example is not really handling `value` in handleChange correctly for how you are using `<Select>`. It seems to be trying to get the string for `val` or `value` from your option object and use that simple string as the `value` property for the `<Select>`. However, if you are passing Objects in the `options` property, your `value` property need to be one of those objects, not just the value string from one of those objects. For example:
```jsx
handleChange = ({ value }) => {
  console.log("change", value");
  this.setState({ value });
};
```

However if you want the `value` property to be a simple string even though your are passing and array of objects in `options` array, you can set `reduce: true` in the `valueKey` property. Here's an example of doing that:

```jsx
import React, { Component } from "react";
import { Grommet, Select } from "grommet";

const OPTIONS = [
  { label: "First", value: "first" },
  { label: "Second", value: "second" },
  { label: "Third", value: "third" }
];

export default class extends Component {
  state = { value: "" };

  handleChange = ({ value }) => {
    console.log("change", value);

    this.setState({
      value
    });
  };

  render() {
    const { value } = this.state;
    console.log("render", value);

    return (
      <Grommet>
        <Select
          value={value}
          onChange={this.handleChange}
          options={OPTIONS}
          valueKey={{ key: "value", reduce: true }}
          labelKey="label"
        />
      </Grommet>
    );
  }
}
```

When you pass object

**Comment by jamie29w** [comment]
Hey @MikeKingdom I really appreciate your quick response and the helpful code snippet. This saved our team a ton of time refactoring code 🙌🏼

**Comment by MikeKingdom** [comment]
> Hey @MikeKingdom I really appreciate your quick response and the helpful code snippet. This saved our team a ton of time refactoring code 🙌🏼

My pleasure. If you have other questions or ideas feel free to reach out here or in the Grommet slack channels.
