### ISSUE TITLE
Enhancement - Explore Filters Component

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#5438]
### Expected Behavior

How might Grommet implement a component allowing users to easily apply filters to a set of data results?

### Purpose & Motivation

Provide implementors a convenient way to create experiences for users to affect data driven views.

Example data-driven views:
- List displaying a feed of latest posts or activities
- Grid presenting applications available in an app store catalog
- DataTable containing a set of records such as orders or inventory
- DataChart displaying performance metrics for a group(s) of devices

### User Needs

- Should display a subset of data based on applied filters.
- Should allow users to select desired values to filter upon.
- Should allow users to apply filters.
- Should allow users to reset filters to previous state.
- Should allow users to clear all filters.
- When filters applied, should provide an indication that filters are currently applied.
- When filters applied, should provide a summary describing the filtered result set (e.g. "displaying X results of Y items").

### Caller Needs
- Should allow caller to specify which data attributes are filter-able.
- Should allow caller to specify which input type should be used for each filter attribute.
- Should dynamically generate filterable values based on data OR allow caller to specify a defined list of filter values.
- Should allow caller to customize how filter attributes are displayed (i.e. inline vs. within a Layer, Layer positioning, container layout, contents layout, etc.).
- Should allow for server-side searching/filtering (e.g. a property accepting the search/filter state and returns the result set asynchronously).

### Design Examples
![Screen Shot 2021-07-12 at 3 23 34 PM](https://user-images.githubusercontent.com/1756948/125357808-5b4cff80-e325-11eb-80b3-b10a4622a473.png)
![Screen Shot 2021-07-12 at 3 24 09 PM](https://user-images.githubusercontent.com/1756948/125357915-80417280-e325-11eb-980a-ed61cb15e6ac.png)
![Screen Shot 2021-07-12 at 3 24 22 PM](https://user-images.githubusercontent.com/1756948/125357919-82a3cc80-e325-11eb-86f4-b0fc24c09dc8.png)
![Screen Shot 2021-07-12 at 3 26 56 PM](https://user-images.githubusercontent.com/1756948/125358022-a36c2200-e325-11eb-8b49-0e120ac52e15.png)
![Screen Shot 2021-07-12 at 3 25 51 PM](https://user-images.githubusercontent.com/1756948/125357926-85062680-e325-11eb-819d-1e5079d5e3ea.png)

**Comment by taysea** [comment]
Some questions I have around how we might build this out is how much of the layout is going to be determined by Grommet vs providing caller with a component they can access and then build their layout accordingly (Similar to what @ericsoderberghp explored with the Column Component).

Would we be able to provide something like `Filter.Search`, `Filter.Control`, `Filter.ClearFilters`, etc. where if the caller wanted to stray from our default layout, they could implement their own layout?

```
<Filter.Search />
<Box direction="row">
   <Filter.Control />
   <Filter.ClearFilters />
</Box>
```
