### ISSUE TITLE
TextInput with suggestions Drop will close when TextInput is re-selected

### ISSUE THREAD

**Issue by haysclark** [grommet/grommet#5440]
There is a bug when using a TextInput with a suggestions Drop. If the user clicks on the TextInput field to show the suggestions, a 2nd click of the TextInput will close the suggestions. The 2nd mouse click triggers the Drops onClickOutside() event, which subsequently closes the suggestions.

Use case: The user selects the TextInput to start a search, but then tries to move their cursor via a mouse click.

### Expected Behavior

TextInput suggestions should stay open as long as the TextInput has focus.

### Actual Behavior

TextInput suggestions show up on initial click when receiving focus; however, re-selecting the TextField causes suggestions to close despite the TextField never loosing focus.

### Examples

The [Grommet Default Suggestion story](https://storybook.grommet.io/?path=/story/input-textinput-default-suggestion--default-suggestion) and [Grommet Custom Suggestion story](https://storybook.grommet.io/?path=/story/input-textinput-custom-suggestions--custom-suggestions) serve as a nice starting point
for demonstrating the issue.

- https://storybook.grommet.io/?path=/story/input-textinput-default-suggestion--default-suggestion
- https://storybook.grommet.io/?path=/story/input-textinput-custom-suggestions--custom-suggestions

### Steps to Reproduce

1. navigate to one of the examples above
1. click on TextInput and type "a" to show names
1. click TextInput a 2nd time
1. notice suggestions have closed

### Your Environment

- Grommet version: 2.17.2
- Browser Name and version: All browsers (using Chrome)
- Operating System and version (desktop or mobile): All systems, using OSX

**Comment by novykh** [comment]
@haysclark you can check this PR https://github.com/grommet/grommet/pull/5625 until they decide to merge it.
