### ISSUE TITLE
Tabs do not stretch with alignControls="stretch"

### ISSUE THREAD

**Issue by vujevits** [grommet/grommet#5448]
### Expected Behavior

Based on the documentation I'd expect the Tab titles to be spread out along the horizontal axis.

### Actual Behavior

It does not effect the layout, the Tab titles remain grouped together without taking the available space up.

### Codesandbox

Try removing and readding `alignControls="stretch", it does not effect the layout.

https://codesandbox.io/s/grommet-v2-template-forked-h2lgd?file=/index.js

**Comment by ericsoderberghp** [comment]
`alignControls` actually refers to how the tabs are aligned in the vertical axis. For spreading the tabs out across the horizontal axis, you should use something like `justify="between"`. I think the documentation should be improved to make this clearer.

**Comment by jlaluces123** [comment]
I also wanted to create a codesandbox to further showcase `alignControls` as I had trouble with it myself. Copying the `alignControls` [story for Tabs](https://storybook.grommet.io/?path=/story/controls-tabs-align-controls--align-controls), I created an extended version of this showcasing the `stretch` value for alignControls [here.](https://codesandbox.io/s/grommet-v2-template-forked-p1zi3?file=/index.js)

If you inspect the Tabs list in the browser, you'll see that with `alignControls="stretch"`, the Tabs list takes up the rest of the space as it should under the hood (the equivalent would be `align-self: stretch`) which can also be indicated with the lightblue background.
