### ISSUE TITLE
DataTable — cannot do `onSelect` and `onClickRow` together

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5451]
### Expected Behavior

The clickable section of "onClickRow" should not include the selection checkbox so that the user could click on row content and also successfully check/uncheck the box.

### Actual Behavior

The clickable section of the row includes the checkbox, so a user cannot select a checkbox without the `onClickRow` function from being executed.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/datatable-onselectonclickrow-7384x?file=/index.js

### Steps to Reproduce

1. Click on Checkbox in a body row
2. The `onClickRow` function is triggered, so user can't make a selection

### Your Environment

- Grommet version: 2.17.3
- Browser Name and version: MacOS Chrome
- Operating System and version (desktop or mobile): MacOS Mojave 10.14.6

**Comment by ericsoderberghp** [comment]
I think this issue will need to some design work to ensure we've got the right interaction and accessibility behaviors.

**Comment by anuragb26** [comment]
I was just trying this out & fixed this issue locally by replacing onChange by onClick & adding event.stopPropagation in the checkbox code in src/js/components/DataTable/Body.js
![Checkbox-grommet](https://user-images.githubusercontent.com/13941381/138386704-4bb0d647-8de0-40de-b48e-4df643eeeeae.PNG)
Let me know your thoughts about this approach.

**Comment by ericsoderberghp** [comment]
I seem to recall seeing some research, perhaps from NNG, that raised some concerns about an approach like suggested above. I'd also want to see how keyboard-only and screen reader interaction would work.
