### ISSUE TITLE
Validate function on FormField not getting triggered when used with Select that has array of objects as options

### ISSUE THREAD

**Issue by thomas-friedrich** [grommet/grommet#5455]
### Expected Behavior

It should trigger validate function on FormField when selecting options from Select field

### Actual Behavior

When passing strings as options to Select, onValidate gets triggered. However, when an array of options with valueKey and labelKey is configured for Select, validate is not triggered for the form.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/selectvalidateonchange-wukzg?file=/src/index.js

### Steps to Reproduce

1. Select option from first Select "Select with String options". The console prints out:
Form onChange triggered 
onChange Select with string options 
validate for size with string options 
Form onValidate triggered

2. Select option from second Select "Select with array of objects as options". The console prints out:
Form onChange triggered 
onChange Select with options objects
(i.e. no validate is called)

### Your Environment

- Grommet version: 2.17.3
- Browser Name and version: Chrome 91.0.4472.114
- Operating System and version (desktop or mobile): MacOS BigSur 11.4

**Comment by taysea** [comment]
Hi @thomas-friedrich. Thanks for filing this issue -- I was able to play with your sandbox a bit and saw you just need to adjust your valueKey to use reduce "true" so the value passed to Select's next value is a string. Here is a working solution: https://codesandbox.io/s/selectvalidateonchange-solved-d5d72

Let me know if this resolves your issue and I'll close this issue.

**Comment by thomas-friedrich** [comment]
Thanks @taysea , that works. I guess the only small side-effect is that if we have to use reduce=true, the onChange event's value only contains the key, not the label of the selected object (i.e. `{"select-size2":2}` instead of `{"select-size2":{"value":2,"label":"medium"}}`. But that's ok, we can easily retrieve the label from the input data based on the key. I am ok with closing this.

**Comment by taysea** [comment]
Awesome, thanks for the update and glad the update on your side is minimal.
