### ISSUE TITLE
StyledParagraph doesn't work if props size is a custom value

### ISSUE THREAD

**Issue by evagm** [grommet/grommet#5464]
### Expected Behavior

Grommet Paragraph component should accept a custom size value.
Example:
`
<Paragraph size="1rem" />
<Paragraph size="1em" />
<Paragraph size="16px" />
`

### Actual Behavior

The component is not rendered and the "TypeError: data is undefined" error is raised.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-g9242

### Steps to Reproduce

1. Import the Paragraph component
2. Set the size props to a custom value (ex: 1rem, 1em, 16px)
3. The TypeError will appear and the component will not render

### Your Environment

- Grommet version: 2.17.3

### Notes

Looks very similar to the bug @LucasCarrias reported regarding the StyledTextInput. #5402

**Comment by britt6612** [comment]
@evagm thank you for reporting! It was very similar so I went ahead and opened a quick PR! 👍

**Comment by evagm** [comment]
That was the quickest turnaround for an issue if I've ever seen one! Thanks @britt6612!  🙌
