### ISSUE TITLE
No method to clear validation errors when adding and removing inputs from a Form

### ISSUE THREAD

**Issue by canyongrace** [grommet/grommet#5478]
### Expected Behavior

I expect that when I add or remove FormField inputs, the validation error mapping either automatically updates, or there is a method for me to manually do so.

As discussed in issue #5248, when using a controlled Form, I am responsible for changing formValues when items are added or removed from the Form. There should be a similar method to update the validation error list.

### Actual Behavior

When removing Form input fields dynamically, form validation errors aren't getting cleared, and I have no method to clear them myself.

Example: I add three FormFields and cause a validation error on the first two. If I remove all 3 and then re-add them, two out of three show up immediately with validation errors, even if the user hasn't typed anything yet. This is kind of jarring to the user. It's like the Form is "remembering" the validation errors even when there are no corresponding FormFields any more, then when new FormFields are created, it just automatically applies those errors to the fields.

IF the field is not required and the first regex is removed (see example), the errors are not retained. However this precludes the developer from using the required tag or having a regular expression that might run in this case and display errors when the user hasn't typed or clicked anything yet.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/flamboyant-morning-jz5bf?file=/src/App.js

### Steps to Reproduce

1 - (One FormField is added by default with an already-existing error.)
2 - Add a second FormField and generate a similar error.
3 - Now add a third field with no error
4 - Delete all three, then re-add all three.

The result is the first two show 'required' errors even though nothing has been typed yet. You also see some of this behavior during deletion.

### Your Environment

- Grommet version: 2.17.3
- Browser Name and version: Firefox 89.0.2
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by halocline** [comment]
Hi @canyongrace - quick question: In your dynamic form, do you have any requirements for what the input names must be (other than unique)? Do they have to be sequential? Would it be okay if we were to tweak your implementation so that no "names" are re-used(i.e. would the following sequence work? add field0, field1, field2, remove, remove, remove --> add new field where name="field3")? Basically ensuring that any field added is not re-using a fieldName which had been issued previously?

**Comment by canyongrace** [comment]
@halocline My primary concern with that would be keeping the mapping and the formValues managed properly. In the codesandbox example, we're manually updating the formValues, so I would have to see how it would work without the expected indices being in place.

In our project, we're actually not managing this scenario using formValues but are instead setting the value on the TextInput. In that case I'm less concerned about the naming of the fields, but I am still concerned about making sure the mapping and the fieldValuesList works as expected.

I'm sure it's possible to do something completely different, but we're limited in how much code change we can make for this particular project. Could you provide a codesandbox with an example?

**Comment by halocline** [comment]
Thank you for the additional details, @canyongrace. 

> In our project, we're actually not managing this scenario using formValues but are instead setting the value on the TextInput. In that case I'm less concerned about the naming of the fields, but I am still concerned about making sure the mapping and the fieldValuesList works as expected.

^This^ additional detail is helpful. It could affect approach / recommended implementation. Thank you.

--------

RE: Mapping

I was also trying to ensure the mapping was managed properly. In the Codesandbox shared above, the mapping could be tightened up. For example, I receive different behaviors if I add the 3 fields as described, but remove them in different sequences (e.g. add the 3 fields, remove the 2nd field --> remaining field values change unexpectedly).

I don't have a Codesandbox to share yet as I just started evaluating the issue and exploring potential solutions, but noticed that the current sandbox mapping would need to be adjusted a bit regardless of any adjustments to managing validation messages.

**Comment by canyongrace** [comment]
@halocline One thing to note - we're using the TextInput value as a workaround to avoid having to manage formValues. However, if we can get a fix for #5370, we may have to switch to managing formValues after all, as a workaround for that defect.

When you say the behaviors are different, I'm not sure what you're referring to? Are you talking about actual input values, or about the errors accompanying the fields? If the second field is removed, the third field "takes the place" of the second, so that is expected. What I don't expect is that if I remove the first field while it has an error, is that the second field "inherits" that error. 

Ideally I'd like is access to the validation error list so I can directly edit it and clear all of the values - something similar to how the form "reset" works.

**Comment by halocline** [comment]
> What I don't expect is that if I remove the first field while it has an error, is that the second field "inherits" that error.

Understood and agree.

> When you say the behaviors are different, I'm not sure what you're referring to? Are you talking about actual input values, or about the errors accompanying the fields? If the second field is removed, the third field "takes the place" of the second, so that is expected.

Yes, input values.

**Add the 3 fields**
![Screen Shot 2021-08-04 at 9 55 15 AM](https://user-images.githubusercontent.com/1756948/128213881-6e98c02c-8dba-49ec-a423-01b757605238.png)

**Removing the 2nd, value in Name 0 disappears -- I would expect it remain as 'a'**
![Screen Shot 2021-08-04 at 9 55 25 AM](https://user-images.githubusercontent.com/1756948/128213895-c4ee3a8e-862e-46e1-9464-f3b042d0e119.png)


Thanks @canyongrace , I have enough information to proceed for the time being.

**Comment by canyongrace** [comment]
@halocline Gotcha, sorry about that defect. Yes, the first field should retain 'a' in your screen shots. I think it's related to the default value and can try to fix the example when I have time.

**Comment by canyongrace** [comment]
> 
> 
> @halocline Gotcha, sorry about that defect. Yes, the first field should retain 'a' in your screen shots. I think it's related to the default value and can try to fix the example when I have time.

Ok I think the sandbox fixed - I needed to set the default value in the field list also. Sorry about the confusion on that.

**Comment by halocline** [comment]
Just a quick update here --- I should have a recommended implementation to share early next week which I believe should deliver the desired functionality and close this issue and https://github.com/grommet/grommet/issues/5370. 

The approach I am taking is make use of Form's `errors`, `infos`, and `onValidate` props. The method to clear validation errors would be to:
1. Get current errors from `onValidate`
2. When field is removed from dynamic form, remove that field from the errors object
3. Pass updated errors to the `errors` prop

**Comment by halocline** [comment]
Hi @canyongrace, I've modified the CodeSandbox you had shared with a [recommended implementation](https://codesandbox.io/s/nice-meninsky-k1eg0?file=/src/App.js) to support:

1. Ability to add fields to a Form dynamically
2. Ability to remove fields from a Form dynamically
3. Ability to run validation on mount - closes https://github.com/grommet/grommet/issues/5370
4. Ability to keep validation results synchronized with fields present in a form - closes https://github.com/grommet/grommet/issues/5478
  - The method to clear validation errors when removing inputs is Form's `errors` and `infos` props. [Documentation](https://v2.grommet.io/form#errors). At the same time Form's `value` is updated, also update `errors` and `infos`.
  - The implemented pattern does the following:
    1. Similar to how we control Form's `value` in state, also control Form's `errors` and `infos` in state.
    1. Get current validationResults (e.g. `errors` and `infos`) from `onValidate` and update their local states.
    1. When field is removed, in addition to removing that field from Form's `value`, also remove that field from `errors` and `infos` states as well.
    
- Lastly, since form value and validation rely on input field's `name`, I migrated away from the index based approach to one that issues unique `id`s and `name`s. My concern was that the index based approach is likely more prone to bugs.

At your convenience, could you review the [implementation provided](https://codesandbox.io/s/nice-meninsky-k1eg0?file=/src/App.js) and confirm whether or not it satisfies your needs/requirements?

**Comment by canyongrace** [comment]
Thanks @halocline I will take a look when I have an opportunity. Btw do you know if this might address #5479 also? I also received communication on that issue with a sandbox but haven't had a chance to look yet.

**Comment by halocline** [comment]
Hi @canyongrace. This approach could be applied for disabled inputs (#5479), however we believe Grommet's Form validation should handle disabled inputs properly, without the caller needing to apply this approach, and a PR is being submitted to address it.

**Comment by canyongrace** [comment]
@halocline I took a look at the implementation mentioned in this issue and it looks like a good workaround.

While it could serve as a workaround for someone using formValues, I'm not sure it addresses #5370. The concern with #5370 is that we were deliberately using the 'value' on a TextInput to manage values, and we would assume the form would automatically validate any default values the same way it does with formValues. There was discussion that it might be a continuation of #5187.

I think the reason we were expecting this behavior, is that if we edit the TextInput field, the form validate DOES run. So we'd expect it to run with an initial TextInput value also.

**Comment by halocline** [comment]
Hi @canyongrace. Understood. I was hoping this pattern would demonstrate a way to deliver the desired experience without the need for controlled inputs. That said, I will investigate #5370 separately.

Regarding this particular issue regarding "method to clear errors", I will close. Feel free to re-open if needed.
