### ISSUE TITLE
FormField Error messages retained when disabling and clearing Form fields

### ISSUE THREAD

**Issue by canyongrace** [grommet/grommet#5479]
### Expected Behavior

I expect that when I disable a FormField that any associated error messages are cleared, especially if I am clearing the values.

### Actual Behavior

I'm looking for a way to clear or remove error messages on a FormField in cases where I want to disable and clear the text. This is similar to issue #5478 but a different use case, since we're not adding/removing FormFields but instead disabling them.

I can set the FormField "error" property manually to an empty string when the field is disabled, but I'd prefer not to set the error manually in cases where the FormField is enabled and the user is typing. I'm also generally having trouble using the error property as a workaround in this scenario.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/practical-meadow-8t9v0?file=/src/App.js

### Steps to Reproduce

1. Add some invalid text to the field, say one letter like 'a'
2. Observe the expected error message
3. Click the "Disable" button to disable the field
4. Note the field is disabled and cleared, but the error message changes to 'required' and stays.

This behavior is confusing, as the user would expect the error message to be cleared. Leaving it as 'required' when the field can't be edited could be misleading.

If we don't use 'required', the error can still occur if there is a regular expression run first in the validation, such as "{ regexp: /^[a-z]/i }". In this case the error displays as 'invalid'.

### Your Environment

- Grommet version: 2.17.4
- Browser Name and version: Firefox 89.0.2
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by britt6612** [comment]
@canyongrace just a little update on this issue. 

I created a code sandbox that is using the `onValidate` prop from `form` in order to change the state of the error depending on if the `textInput` is disabled. Below I have pasted the example:
https://codesandbox.io/s/jovial-sammet-tuxcm?file=/src/App.js
In the example, there is an error in which I believe is a bug in Grommet Form. I can look more into that! 

I wanted to give you something to go off of in terms of getting your application working.

@ericsoderberghp maybe we can discuss whether to add this as a grommet enhancement or if users should keep track of the errors In their app using the `onValidate`

**Comment by ericsoderberghp** [comment]
The intent is to be able to handle validation in either a controlled or uncontrolled manner. So, the caller should be able to use `onValidate`, `errors`, and `infos` themselves OR, they should be able to use none of those. In either case, the basic behavior should be acheivable.

**Comment by canyongrace** [comment]
Thanks @britt6612 I will take a look when I have an opportunity. I am also looking at the response on #5478.

**Comment by britt6612** [comment]
@canyongrace sounds great! This is just a work around I'm working on changing the way Grommet handles this I should have a PR up today.

**Comment by canyongrace** [comment]
@britt6612 Just took a look, thanks - this looks like it could work for us.

I do have one question. Not to ask anything too obvious, but it appears that the validationResults passed in to the onValidate call is actually referring to the form results data structure in the sense that you can directly modify its members and thus affect the form behavior? For some reason I had the impression that it was a deep copy of sorts, if that makes sense. As in, if you edited a member of validation results (such as errors, in this case), you had to officially set the new object in the form some other way (and I wasn't certain how). That's apparently not true, so I'm trying to make sure I understand the functionality.

**Comment by britt6612** [comment]
@canyongrace If I understand your question correctly you were under the impression that the `validationResults` just gave read access to the `errors`, `info` ? But this actually allows the user to be able to not only have access to the `validationResults` but could actually set the `errors` to another state just like I did in the example.

**Comment by canyongrace** [comment]
@britt6612 Yes, read access and wasn't sure there was any write access or way to overwrite the `validationResults `structure.
I'm not quite following your second sentence. I think you're just saying any user actually does have write access to that structure, as demo'ed in your sandbox, correct?

**Comment by britt6612** [comment]
okay yes I meant that the user can adjust these values just like in the sandbox example
