### ISSUE TITLE
[Feature] Create permanent maskings for MaskedInput

### ISSUE THREAD

**Issue by Tbhesswebber** [grommet/grommet#5480]
Currently, the `MaskedInput` component accepts a prop `mask` that takes an array of objects that identify whether the mask is either a string or regex matcher and what the behavior should be for each.  This is sufficient for most use-cases, but misses a large subset in which the mask should _always_ be in a particular position if there is a value in the field.

These cases include, but are not limited to:

- currencies that leverage the ISO code instead of a symbol (100 INR or 1500 USD)
- percentages (25%)
- almost anything that leverages a specific unit (kg or GB)

While there are workarounds for this, none of them provide the context in as clear a way as a masked input does in that the context is immediately after the letters being typed. (Check out [this Slack thread](https://grommet.slack.com/archives/C09QQEG69/p1627495571044700?thread_ts=1627489921.044400&cid=C09QQEG69) for some of the workarounds...)

This proposal is to add a property similar to `fixed` to the possible elements within a mask object - I'll refer to that property as `permanent`.

### Expected Behavior

```
const mask = [
  { permanent: "https://" },
  { regex: /^.*$/, placeholder: "my-subdomain" },
  { permanent: ".foobar.com" }
];
```

The usage of permanent would mean that the mask is there whenever the typed value is not undefined.

#### Examples with above mask

**Case: User hasn't typed anything**
Rendered Text: (placeholder) `https://my-subdomain.foobar.com`
Value: `undefined`

**Case: User types ba**
Rendered Text: `https://ba.foobar.com`
Value: `"ba"`

**Case: User deletes all text**
Rendered Text: (placeholder) `https://my-subdomain.foobar.com`
Value: `undefined`

### Actual Behavior

Currently, the closest that you can get with this is to use `fixed` with very constrained rules surrounding the fixed value, which means that you have to have a very constrained definition of what the mask can be.

**Comment by MikeKingdom** [comment]
We're deciding not to pursue this for now since it will require a lot more design and changes/implementation to make this idea generally available.
