### ISSUE TITLE
DateInput Calendar doesn't always open when input is clicked

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5481]
### Expected Behavior

Calendar should always open when the input is clicked.

### Actual Behavior

After the input is opened, then date selected and close, the user can't get the calendar to open again without clicking somewhere outside the DateInput and then back into it.

### URL, screen shot, or Codepen exhibiting the issue

https://storybook.grommet.io/?path=/story/input-dateinput-format--format

### Steps to Reproduce

1. Click into input (Calendar will open)
2. Click again (Calendar will close)
3. Click again (Calendar won't open)

### Your Environment

- Grommet version: Stable
- Browser Name and version: Version 92.0.4515.107
- Operating System and version (desktop or mobile): MacOS Mojave

**Comment by PauloE314** [comment]
Hi @taysea, I've reproduced the bug locally and it's really happening. I wish I could work on this, can you assign it to me?
