### ISSUE TITLE
Weird stretch for some images

### ISSUE THREAD

**Issue by devluked** [grommet/grommet#5485]
### Expected Behavior

Image should look how it was uploaded

### Actual Behavior

Some images have a weird stretch that happens to them

### URL, screen shot, or Codepen exhibiting the issue

Image on the left is the one with the problem, the one on the right is normal. Not sure why some images do this weird stretching.

![image](https://user-images.githubusercontent.com/48234476/127517911-effa6fbf-faf9-4943-bb75-e8e1a24bbcc6.png)

### Steps to Reproduce

1. Mapping images to a grommet <Image> tag and setting the source as the photo. Also uses VH: 250 and VW: 250.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by halocline** [comment]
@devluked Would you be willing to create a [CodeSandbox](codesandbox.io) with your implementation and add it to this issue? It will help getting this issue diagnosed and resolved quickly.

**Comment by devluked** [comment]
Hi @halocline I'm going to close it. Found out it was due to some image stretching API. Thanks for the quick response.
