### ISSUE TITLE
rowSpan applied to wrong element

### ISSUE THREAD

**Issue by martenjacobs** [grommet/grommet#5489]
### Expected behavior
When creating an element like this: `<TableCell rowSpan={2}>Text</TableCell>`, I'd expect the cell to span two rows, therefore the generated td element should have a `rowspan="2"` attribute when inspecting it in dev tools. 

### Actual Behavior
The rowspan attribute is actually assigned to a div that's placed inside of the td element, so the resulting table is not rendered correctly. Cells with rowspan>1 are not rendered over multiple rows and the cells in the following rows are not pushed to the side, causing the table to be misaligned.

I created a [Codesandbox that demonstrates the issue](https://codesandbox.io/s/wild-mountain-pg07d?file=/src/App.js).

### Steps to Reproduce

Create an app with the following code:
```jsx
import "./styles.css";
import { Grommet, Table, TableBody, TableRow, TableCell } from "grommet";

export default function App() {
  return (
    <Grommet full>
      <Table>
        <TableBody>
          <TableRow>
            <TableCell rowSpan={2}>Should span</TableCell>
            <TableCell>Col 2</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>Col 2</TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </Grommet>
  );
}
```

### Your Environment

- Grommet version: 2.17.4
- Browser Name and version: Chrome 91.0.4472.114
- Operating System and version (desktop or mobile): macOS 11.3.1

**Comment by jcfilben** [comment]
Closing since #5556 was merged
