### ISSUE TITLE
BundleSize error with CircleCI

### ISSUE THREAD

**Issue by jlaluces123** [grommet/grommet#5490]
On the pre-deploy checks, all tests pass except for CircleCI's. Upon further inspection the error on CircleCi shows that after running `yarn test-bundlesize` the test fails (screenshot below).

### Expected Behavior
Expecting `yarn test-bundlesize` to not throw an error.

### Actual Behavior
`yarn test-bundlesize` currently fails after running the command on CircleCI.

### URL, screen shot, or Codepen exhibiting the issue
<img width="1525" alt="Screen Shot 2021-07-30 at 1 10 27 PM" src="https://user-images.githubusercontent.com/40575859/127688242-4abe3bbc-c926-4a94-a4d2-c3b9b1e56705.png">

### Steps to Reproduce
1. View bundlesize error directly [here](https://app.circleci.com/pipelines/github/grommet/grommet/9230/workflows/280a11a7-431e-4df8-a34c-9479ac5ff540/jobs/45693)
2. PR this error has occurred on [here](https://github.com/grommet/grommet/pull/5457)

### Your Environment

- Grommet version: 2.17.3
- Browser Name and version: Google Chrome (Version 92.0.4515.107 (Official Build) (x86_64))
- Operating System and version (desktop or mobile): macOS Big Sur (v11.3.1)

**Comment by halocline** [comment]
Observations:
- devDependency is [bundlesize](https://github.com/grommet/grommet/blob/c9fc567671a81277d9df8095f4c68e9324960c2d/package.json#L89)
- [Configuration is specified here](https://github.com/grommet/grommet/blob/c9fc567671a81277d9df8095f4c68e9324960c2d/package.json#L178)
- This configuration's values have not been updated in several years.
- `grommet.min.js` has exceeded this threshold for quite awhile.
- Why is this error just now being thrown?

**Comment by ericsoderberghp** [comment]
It looks to me like the bundle size step is correctly flagging that a pull request is increasing the size of the bundle from less than 120KB to 202KB. The cause of the increase should be investigated and rectified.

**Comment by halocline** [comment]
@jlaluces123 - FYI, comparing the bundle contents from master to that of your PR's branch, it appears that in your branch grommet-icons is adding significant size to the bundle. Have you used any symlinks (e.g. yarn link grommet-icons) between projects recently?

**Master Bundle**
![Screen Shot 2021-08-02 at 1 09 50 PM](https://user-images.githubusercontent.com/1756948/127912431-42dfd031-d4ef-468e-920d-916f6cd6bb49.png)


**PR Bundle**
![Screen Shot 2021-08-02 at 11 45 20 AM](https://user-images.githubusercontent.com/1756948/127912435-714c549b-c90d-4901-9275-45e4f50bcd16.png)

**Comment by jlaluces123** [comment]
> @jlaluces123 - FYI, comparing the bundle contents from master to that of your PR's branch, it appears that in your branch grommet-icons is adding significant size to the bundle. Have you used any symlinks (e.g. yarn link grommet-icons) between projects recently?

Not that I know of, related to `grommet-icons` I believe all I did was do an import for the CircleAlert icon via `import { CircleAlert } from 'grommet-icons'`. Could that be the culprit here?

**Comment by ericsoderberghp** [comment]
Definitely, take a look at how other icons are imported, you need a more complete path.
