### ISSUE TITLE
Can't reset date for DateInput

### ISSUE THREAD

**Issue by AlbertoTonegari** [grommet/grommet#5519]
I have created a [PR](https://github.com/grommet/grommet/pull/5517) to solve this issue.

The field for `DateInput` can't be cleared dynamically.

### Expected Behavior

I should be able to clear the date if for the value of `DateInput` I pass `""` or `[ ]`.

### Actual Behavior

If I try to clear the input by passing for example `""` to the value of `DateInput` only the `Calendar` component clears the value, but input still displays it.

### URL, screen shot, or Codepen exhibiting the issue

Here is a codesandbox showcasing the issue that the DateInput field can't be cleared dynamically.
https://codesandbox.io/s/recursing-star-3tnfk

### Steps to Reproduce

1. Open the codesandbox example and select a date.
2. Click `Reset Date`.
3. The Calender clears the date, but the input does not.

### Your Environment

- Grommet version: 2.17.4
- Browser Name and version: Google Chrome latest version
- Operating System and version (desktop or mobile):  desktop

**Comment by danielm-hpe** [comment]
Thanks for finding and proposing a fix for this- I just came across this issue tonight when passing in an empty array.
