### ISSUE TITLE
Grommet 0.6.2 and React v15

### ISSUE THREAD

**Issue by ezu** [grommet/grommet#552]
Hi there,
I was wondering why Grommet is tightly coupled with version 14 of React and if you have plans to upgrade to v15 in the near future.

Oh and by the way, I love Grommet and start using in a project I am working at work: great job!

**Comment by antoligy** [comment]
Presumably for stability?

For the meantime I'm forcibly loading React v15 by supplying a resolver alias in webpack as documented here and this seems to help. https://github.com/grommet/grommet/wiki/Building-Grommet#using-local-grommet-build-in-your-project

**Comment by alansouzati** [comment]
I'm working this week to update all the grommet dependencies, including evaluating React v15.

From what I saw no major change will be required, but @antoligy is right, the only reason we haven't migrated yet is stablity 👍

**Comment by leo4ever** [comment]
Very much Looking forward to the update. I am using MaterialUI and would love to move to grommet as it offers all the components I am looking for.

**Comment by bryanjacquot** [comment]
React 15 was brought into Grommet [v0.6.5](https://github.com/grommet/grommet/releases/tag/v0.6.5)
