### ISSUE TITLE
Box gap is applied for empty children

### ISSUE THREAD

**Issue by vmaark** [grommet/grommet#5523]
Conditional rendering is not playing well with `gap`.
### Expected Behavior
If a `Box` has children which may be `null`, a gap shouldn't be applied for them.

### Actual Behavior
Extra gap is added to the layout if there are "missing" items.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/ecstatic-mclaren-okuu1?file=/src/Box.js

**Comment by jcfilben** [comment]
This issue can be solved by https://github.com/grommet/grommet/issues/6179. Going to close this one and we can just track this work in #6179.
