### ISSUE TITLE
Video - extendable controls

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#5531]
Allow adding the ability to resize a Video from a thumbnail to a larger size within the browser, such as the full width of the browser window, similar to how other embedded videos work. This allows the user to transition from deciding whether they want to watch a video to focusing on watching it, without having to make it full screen.

Suggest achieving this by adding something like `<Video controls={[]} />` which would add additional controls to the current controls drop list. The caller would then add a control that allows the user to initiate it. The caller would then change the layout of the page as needed, especially sizing and placing the container of the Video as desired.

**Comment by g4rry420** [comment]
Is it going to be same as youtube's theater mode ?

**Comment by ericsoderberghp** [comment]
We would still take the string format of `controls`. The object format would put that same string value into the `position` key.
