### ISSUE TITLE
InuitCSS?

### ISSUE THREAD

**Issue by arlair** [grommet/grommet#554]
InuitCSS seems like a dead project with no recent work on the proposed new version:
https://github.com/csswizardry/inuit.css/issues/291

I was a bit surprised to see it listed as one of the technologies being used in an enterprise library and wondered if others investigating might feel the same.

I don't know much about InuiCSS. Is this likely to cause problems, or is there some kind of migration strategy planned?

**Comment by antoligy** [comment]
Relevant- https://github.com/inuitcss/getting-started/issues/12

**Comment by bryanjacquot** [comment]
@antoligy and @arlair: a couple of comments.  First, there is recent activity in Inuit CSS, take a look at the issue mentioned above.  Second, Grommet's use of Inuit is more about the structure and mindset than the leverage of lots of code.  When we started Grommet, Inuit was listed as "pre-alpha" which was a concern.  But as I said, we are relying on it more from a philosophy and structure perspective, not deep code reliance.

**Comment by antoligy** [comment]
Hi @bryanjacquot, I'm completely on board with InuitCSS, the link was for context and and understanding of what was going on in the wider Inuit community.  Very excited to see new development there! 

Cheers for this, 
Alex.
