### ISSUE TITLE
Revise Grommet Contributing.md to account for changes to documentation process

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#5540]
- [x] Revise CONTRIBUTING.md with up-to-date instructions for documentation.
- [x] Review overall guide for accuracy, needed adjustments, and enhancement opportunities.

**Comment by jcfilben** [comment]
> Review overall guide for accuracy, needed adjustments, and enhancement opportunities.

Opened new issue related to this https://github.com/grommet/grommet/issues/5578

**Comment by jcfilben** [comment]
> Revise CONTRIBUTING.md with up-to-date instructions for documentation.

Done in #5577 

>  Review overall guide for accuracy, needed adjustments, and enhancement opportunities.

Done in #5584
