### ISSUE TITLE
Button - add support for justification of content

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5542]
### Expected Behavior

Caller should have option to have icon + label left justified in the button as opposed to justify between / center.

### Actual Behavior

Justification of icon + label is decided by the Button itself. When used in Menu, if the Menu is wide the icon and label (supplied via array of objects to Menu) are justified in between each other.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/menu-justification-typ03

### Steps to Reproduce

Open Menu and observe justification of icon and label. No ability to justify it to the start.

### Your Environment

- Grommet version: Latest
- Browser Name and version: Mac Chrome
- Operating System and version (desktop or mobile): Mac OS Big Sur

**Comment by ericsoderberghp** [comment]
Also consider whether this would be a good fit for a Sidebar navigation context, where Buttons would be vertically stacked but start justified, with appropriate padding and active indication.

**Comment by g4rry420** [comment]
https://github.com/grommet/grommet/blob/2a3934a2f2100db9c8b67b0b5995269829ca7817/src/js/components/Button/Button.js#L277
Here, we are using `align` prop to justify the content. I think we should add `justify` prop for the button.Please, let me know your thoughts,

**Comment by jcfilben** [comment]
@g4rry420 I agree, I think we should add the justify prop and change this `justify={align === 'center' ? 'center' : 'between'} ` to be `justify={justify}`

**Comment by g4rry420** [comment]
okay, I work on this issue.
