### ISSUE TITLE
Drop down menu not closing on Edge 20

### ISSUE THREAD

**Issue by fjwood1** [grommet/grommet#555]
I believe it is related to this:
SCRIPT438: Object doesn't support property or method 'focus'
Menu.js (142,1)
I verified that the problem exists on the grommet dev docs page - for drop down types of menus

and/or

SCRIPT438: Object doesn't support property or method 'focus'
index.js (8,2576)

**Comment by alansouzati** [comment]
Thanks for reporting this, fixed in https://github.com/grommet/grommet/commit/472a0edd63019b43b22c35691578cff3f40952dd
