### ISSUE TITLE
Responsive DataTable component

### ISSUE THREAD

**Issue by protek-vrn** [grommet/grommet#5560]
Hey guys,

I'm looking for an example of the DataTable component that works fine both on desktop and mobile.

Is there an out-of-the-box option to do that? Or I should consider a combination of `DataTable`+`List`+`ResponsiveContext`?

### Expected Behavior

Having a way to override rows' render behavior to fit content into a small screen.

### Actual Behavior

The DataTable is rendered as a non-responsive `table` tag.

### URL, screen shot, or Codepen exhibiting the issue

no

### Steps to Reproduce

no

### Your Environment

any

**Comment by leonwilly** [comment]
You can make `DataTable` responsive by usind the render() method of the column and returning a ```<Text heigh={"1vh"}>...</Text>```

**Comment by protek-vrn** [comment]
@leonwilly not sure how it helps. The table still looks.. as a non-responsive table https://codesandbox.io/s/responsive-datatable-y6os8?file=/index.js

**Comment by jcfilben** [comment]
You can use columns render combined with responsive context to determine how you want you content to look at specific breakpoints. Another option if your DataTable doesn't work well in a smaller view is to wrap it with a Box and set overflow to scroll.

**Comment by protek-vrn** [comment]
Ok. thanks guys
