### ISSUE TITLE
DataTable doesn't render custom footer Node

### ISSUE THREAD

**Issue by leonwilly** [grommet/grommet#5562]
According to the documentation (` footer: node | { aggregate: "..." }`) one should be able to pass a custom Node to the footer property in the columns object of a DataTable. 

The DataTable should render the custom Node

It renders an empty element `<div>` element.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by PauloE314** [comment]
I've reproduced this on my machine and, right now, it only renders simple texts and { aggregate: "...."}. I'm gonna try to fix this.
