### ISSUE TITLE
Impossible to customize RangeSelector EdgeControl zIndex

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [grommet/grommet#5565]
Impossible to customize RangeSelector EdgeControl zIndex

### Expected Behavior

Changing zIndex via theme

### Actual Behavior

Its possible via tricky css class targetting

### Steps to Reproduce

Try to change the zIndex of EdgeControl

### Your Environment

- Grommet version: 2.17.2
- Browser Name and version:  latest Chrome
- Operating System and version (desktop or mobile): MacOS

Related to this pull request => https://github.com/grommet/grommet/pull/5564

**Comment by ericsoderberghp** [comment]
Can you elaborate on a situation when this would be useful? I'm just wanting to understand the need better.

**Comment by LeComptoirDesPharmacies** [comment]
Of course, on our app we have few elements with specific zIndex, to make it consistent we wrote some rules, like :
z-index: auto for body element, z-index: 5 for popups on body, z-index: 25 for our cookie consent.

If we can't manage the zIndex of an element, we have to rebuild our zIndex system around this non-manageable zIndex element.

We encounters issues like that : 

![image (27)](https://user-images.githubusercontent.com/25615113/131638345-af5503c6-e809-4fce-9b23-71e903a78a3b.png)

![image (26)](https://user-images.githubusercontent.com/25615113/131638410-78fabb7e-8ed1-4813-865c-71bef2ab0e6d.png)

**Comment by ericsoderberghp** [comment]
I'm wondering if we should just change the grommet default z-index to be `1`. I don't see any reason it needs to be `10`. Would that also address the issue?

**Comment by LeComptoirDesPharmacies** [comment]
It sounds like a good solution, `z-index` is relative so if we need to elevate the RangeSelector EdgeControls we could just set the `z-index` of the parent.
Should i update our pull request to apply this solution (and also changing our pull request on the documentation).
Thank you.

**Comment by ericsoderberghp** [comment]
Yes

**Comment by LeComptoirDesPharmacies** [comment]
Changes are done and i'll close the pull request (https://github.com/grommet/grommet-site/pull/305/) of the documentation as with this solution there isn't any change to the theme :)
