### ISSUE TITLE
Tip displays after getting focus back from another element

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5569]
### Expected Behavior

Tip shouldn't appear again and persist after a button with tip receives focus programmatically after a Layer closes, etc.

### Actual Behavior

Tip is persisting until user clicks somewhere else in screen.

### URL, screen shot, or Codepen exhibiting the issue

https://design-system.hpe.design/templates/filtering

### Steps to Reproduce

1. Click filtering button
2. Click "Close" button on filtering layer
3. Notice how "Open filters" tip appears again and stays open even as you move your mouse around the screen.
4. 

### Your Environment

- Grommet version: stable
- Browser Name and version: Chrome Mac
- Operating System and version (desktop or mobile): MacOS BigSur

**Comment by jcfilben** [comment]
I've been looking into this, and according to [accessibility guidelines](https://dequeuniversity.com/library/aria/tooltip) the tooltip should appear when the item it is on has focus. So when the Layer closes and focus returns to the Button I think the correct behavior is to show the tooltip

**Comment by jcfilben** [comment]
@taysea and I discussed this yesterday. Current plan is to show the tip after the Layer closes and focus returns to the button only when a user is navigating by keyboard. If a user is navigating with a mouse it makes sense to only show the tip on mouse over. This will enable us to keep the accessibility of tip for keyboard users and allow us to fix the behavior for mouse users.
