### ISSUE TITLE
When set scrollable={true} of <Table />, alert error: Two valid but unequal nodes with the same `data-reactid`

### ISSUE THREAD

**Issue by masogit** [grommet/grommet#558]
function: _buildMirror()
    mirrorRow.appendChild(cells[i].cloneNode(true));

This cloneNode will clone all child elements with 'data-reactid', it will show error:
    Uncaught Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .0.0.0.0:1.3.1.0.0.1:

When thead/tr/th include React Element:
`<tr>
    <th><Anchor href="#" onClick={this._onOrderBy.bind(this, 'self')}>Self</Anchor></th>
</tr>`

**Comment by bryanjacquot** [comment]
Resolved with the latest grommet.
