### ISSUE TITLE
DateInput has no day of week cell on top of columns.

### ISSUE THREAD

**Issue by B-Esmaili** [grommet/grommet#5583]
### Expected Behavior

DateInput have to show day of week on top of each column.
![82713135-4a908480-9c60-11ea-9595-cbc4d928b16d](https://user-images.githubusercontent.com/9152515/132940502-cfdf680b-79f4-454a-bd62-9cb6c7ccf3a4.png)

![image](https://user-images.githubusercontent.com/9152515/132940543-382fe2ec-4f72-46e9-bdf4-b9fed5e94178.png)

### Actual Behavior

Day of week doesn't show up.

- Grommet version: 2.17.4
- Browser Name and version: Chrome 90
- Operating System and version (desktop or mobile): Windows 10

**Comment by jcfilben** [comment]
Can you share more context of what you are hoping to achieve? Maybe include a picture so people can see what you are envisioning.

**Comment by B-Esmaili** [comment]
> Can you share more context of what you are hoping to achieve? Maybe include a picture so people can see what you are envisioning.

Updated the Issue. It's all clear now.

**Comment by ericsoderberghp** [comment]
I think `<DateInput calendarProps={{ daysOfWeek: true }} />` will do it.

**Comment by B-Esmaili** [comment]
Thanks for the suggestion @ericsoderberghp . It did the job.
