### ISSUE TITLE
[Question] AccordionPanel tests

### ISSUE THREAD

**Issue by alexmirrington** [grommet/grommet#5610]
### Question

The `AccordionPanel` component currently doesn't have any unit tests that reside in its own component directory. At the moment, `AccordionPanel` tests are located within the `Accordion` component, and I wonder if it makes more sense to mode those tests that are more focused around the `AccordionPanel` component to the `AccordionPanel` component directory for readability.

**Comment by jcfilben** [comment]
Good question. Could go either way but I think that the AccordionPanel tests can remain within the Accordion component since AccordionPanel is expected to always be wrapped by Accordion

**Comment by alexmirrington** [comment]
No worries, cheers for the quick response! I'll leave tests as they are :)
