### ISSUE TITLE
iconProp and labelProp extend props in theme for Button

### ISSUE THREAD

**Issue by lleBit** [grommet/grommet#5613]
I would like to extend css for specific conditions when the icon and label props has been passed to the Grommet Button, but observed that there are no Grommet specific props available. It would be very helpful to me to have these props.

### Expected Behavior

There is iconProp and labelProp available for extending CSS.

### Actual Behavior

The props are not available.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/91166566/134265937-7126d361-490d-475a-8c0c-6ce8daef7d34.png)

### Steps to Reproduce

Console log out the extend props.

- Grommet version: 2.16.2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Mac desktop

**Comment by halocline** [comment]
@lleBit Can you provide additional details about your use case and what you are trying to achieve? Can you share the design you are wanting to implement?

**Comment by lleBit** [comment]
@halocline - Yes of course! I am using the Grommet theme to edit the Grommet Button. I want to be able to style the Button within the extend property if just an icon is passed to the Button. This will be like the styling for a Button that is icon only. At the moment there's no definitive way to check whether those props have been passed to the Button.

It would be helpful to have those props accessible in the extend props.

**Comment by halocline** [comment]
> @halocline - Yes of course! I am using the Grommet theme to edit the Grommet Button. I want to be able to style the Button within the extend property if just an icon is passed to the Button. This will be like the styling for a Button that is icon only. At the moment there's no definitive way to check whether those props have been passed to the Button.
> 
> It would be helpful to have those props accessible in the extend props.

@lleBit One more thing, can you confirm that you have `button.default` defined in your theme?

**Comment by halocline** [comment]
@lleBit Saw your comment on Slack that you'd be open to exploring a PR. 🤞  this should be a relatively straightforward one.

A couple points for background:
1. Grommet has two types of buttons, `<StyledButton />` (legacy) and `<StyledButtonKind />` (modern).
2. It looks like `<StyledButton />` is getting `hasIcon` and `hasLabel` [props set here](https://github.com/grommet/grommet/blob/c20c1264c8b35b7546f521ab395b53965d0eb275/src/js/components/Button/Button.js#L366). However, those [props don't appear to be set](https://github.com/grommet/grommet/blob/c20c1264c8b35b7546f521ab395b53965d0eb275/src/js/components/Button/Button.js#L319) on `<StyledButtonKind />`.

I think we just need to add those to StyledButtonKind and verify with Storybook test and/or Jest tests.

**Comment by lleBit** [comment]
@halocline  - Yes I do have default defined under button in the theme.

Awesome! I'll ping you when I have it done.

**Comment by lleBit** [comment]
@halocline - Let me know if this is ok.
https://github.com/grommet/grommet/pull/5628

**Comment by halocline** [comment]
> @halocline - Let me know if this is ok.
> #5628

Awesome. Thank you for your contribution. I am wrapping up for the week, but will take a look on Monday. Cheers!
