### ISSUE TITLE
Events are not propagating to Target container when Layer component rendered inside a container.

### ISSUE THREAD

**Issue by venkatesh-elchuri** [grommet/grommet#5624]
### Expected Behavior

If the layer was rendering inside a container , the events fired on the layer component has to propagated to Parent container (which having some event listeners are added to targeted Div).

### Actual Behavior
When we have target property to layer component, The layer was rendering inside target container is fine, But Event listeners that target having were not invoking.

### URL, screen shot, or Codepen exhibiting the issue
Observation : 
   The layer component DOM node was creating with window reference position, it's was not as a children of  Targeted Element.
![image](https://user-images.githubusercontent.com/30321668/134619900-490ab58b-94e8-4fb0-ab65-5f99cfb33f8b.png)

Created Sandbox example to reproduce scenario.
https://codesandbox.io/s/pedantic-noether-nby71?file=/src/Layer.js 

### Steps to Reproduce

1. Refer the code sand box link placed above.

### Your Environment

- Grommet version: latest
- Browser Name and version: Chrome ,Latest
- Operating System and version (desktop or mobile): Desktop, windows

**Comment by venkatesh-elchuri** [comment]
Do we have a solution for, how to propagate events to target element from layer component ?

**Comment by jcfilben** [comment]
I haven't had a chance to look into this much, but I'm wondering if dispatchEvent() could be used here?

**Comment by venkatesh-elchuri** [comment]
Can you have any working example with sand box ?

**Comment by jcfilben** [comment]
I am going to go ahead and close this since a working solution is shown above. Feel free to reopen if needed.
