### ISSUE TITLE
Typescript error when using style or className property for Select

### ISSUE THREAD

**Issue by krist-jin** [grommet/grommet#5629]
### Expected Behavior
Should not give error when using style or className property for Select in Typescript

### Actual Behavior
Error is shown although style is applied and no crash
```
(JSX attribute) className: string
Type '{ options: string[]; className: string; style: { background: string; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<SelectProps, any, any>> & Readonly<SelectProps> & Readonly<...>'.
  Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<SelectProps, any, any>> & Readonly<SelectProps> & Readonly<...>'.ts(2322)
```

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/jovial-heyrovsky-97fql

### Steps to Reproduce

See line 23 and line 24 of index.tsx

### Your Environment
See codesandbox

**Comment by britt6612** [comment]
A fix for `className` should be available on stable branch 

https://github.com/grommet/grommet/pull/5570

We will need to add styles to the types for ts

**Comment by jcfilben** [comment]
#5570 also fixed adding `styles` to Select. @krist-jin I forked and then updated your [codesandbox](https://codesandbox.io/s/dazzling-dan-rstlq?file=/src/index.tsx) to use grommet v2.18.0 and you can see the issue has been fixed
