### ISSUE TITLE
Calendar 1st day of month gets hover styling when clicking on other dates

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#5634]
### Expected Behavior
Hover styling should only be applied when mouse is over the date

### Actual Behavior
If `range` is true or you can select multiple dates on the Calendar, when clicking a date the hover styling is applied to the first day of the month even if you are selecting a different date.

### URL, screen shot, or Codepen exhibiting the issue
Can be seen in the following stories:
https://storybook.grommet.io/?path=/story/visualizations-calendar-active-date--active-date
https://storybook.grommet.io/?path=/story/visualizations-calendar-dual--dual
https://storybook.grommet.io/?path=/story/visualizations-calendar-multiple--multiple
https://storybook.grommet.io/?path=/story/visualizations-calendar-range--range

### Steps to Reproduce
In one of the above stories select a date that is not the first of the month and see the hover styling being applied to the first

### Your Environment
- Grommet version: 2.17.5
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile):

**Comment by Kishore-abhimanyu** [comment]
Can you assign me this issue?

**Comment by jcfilben** [comment]
Hi @Kishore-abhimanyu I am unable to assign you to the issue but feel free to work on it
