### ISSUE TITLE
can't change button border radius via theme context

### ISSUE THREAD

**Issue by BigBadLoser** [grommet/grommet#5642]
### Expected Behavior

Custom theme within a theme context should change the radius of the buttons border

### Actual Behavior
nothing

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/themecontext-extend-forked-sk2hp?file=/index.js

**Comment by alexmirrington** [comment]
You can change the radius of the button border if you replace your theme with this:

```Javascript
const customButton = {
  button: {
    border: {
      radius: "0px"
    }
  }
};
```

As far as I know, there isn't a way to change it just for medium buttons, but that's not the point of themeing. If you want to change it just for medium buttons, leave the theme as it is and pass the `radius` prop as needed or make a custom component.

**Comment by jcfilben** [comment]
Thanks for the response @alexmirrington! @BigBadLoser can we go ahead and close this issue?

**Comment by BigBadLoser** [comment]
I missed the part under themes where it says button.border.radius, I was looking at button.size.medium.border.radius.
