### ISSUE TITLE
Background color for the calendar day when we click on the left/right arrows

### ISSUE THREAD

**Issue by denant0** [grommet/grommet#5646]
Using Calendar, we are trying to change the background color for the calendar day when we click on the left/right arrows
How I can do this?

### Actual Behavior
I need change this
![изображение](https://user-images.githubusercontent.com/1597545/135675392-1f56ef7b-cf87-43b7-97df-89be9b389532.png)

### URL, screen shot, or Codepen exhibiting the issue

![изображение](https://user-images.githubusercontent.com/1597545/135675045-a7e24962-22ec-4e96-8753-726bb9d326f4.png)
![изображение](https://user-images.githubusercontent.com/1597545/135675142-6b50ed37-e153-4254-97fa-345ab1de81d6.png)

**Comment by jcfilben** [comment]
Hi @denant0 you can set `global.active.background.color` in the theme to customize this

**Comment by denant0** [comment]
Thank you very much for the answer!

**Comment by jcfilben** [comment]
Hey @denant0 are you okay if I go ahead and close this issue?

**Comment by denant0** [comment]
Hello, thanks. Yes, this work for my!
