### ISSUE TITLE
Multiple Select with search is broken

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [grommet/grommet#5657]
### Expected Behavior

On a multiple select with Search, when user click on dynamic option returned from search, `onChange` method should return correct `value`, even if previous checked options are not available anymore.

### Actual Behavior

On a multiple select with search, when a user click on an option that was dynamically retrieved, `onChange` return wrong next value. Indeed, it return `[undefined]` instead of the option/reduced value.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/festive-banzai-78ely?file=/src/App.js

### Steps to Reproduce

1. Go to sandbox
2. Click on select and choose "titi"
3. Look in console.log =>
```
value is 
(1) [Object]
{id: 2, label: "titi"}
```
3. Type "to" in the search
4. Click on "toto"
5. Look in console.log => 
```
value is 
(2) [Object, undefined]
{id: 1, label: "toto"}
```

### Your Environment

The following PR tried to fix probems with `multiple` `Select `and `onSearch`.
https://github.com/grommet/grommet/pull/4821

However, it seems that it consider that allOptions is reached when there is not search. This may not be the case.
Ex : We display 5 result over the complete list and when user search, it return other results.

- Grommet version: 2.18.0
- Browser Name and version: Firefox 92.0.1
- Operating System and version (desktop or mobile): Windows 10

**Comment by jcfilben** [comment]
I was looking into this and found a different but potentially related issue. In this [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-pv073?file=/index.js) if you search for something, select and option and then search again and select an option only the second value will be in the value array.

**Comment by amandadupell** [comment]
looking into this more, it seems that the initial [codesandbox example](https://codesandbox.io/s/festive-banzai-78ely?file=/src/App.js) is getting the undefined error from the way in which the onSearch behavior is changing the options. however, there seems to still be an issue with the closeOnChange behavior not properly updating values when selected. will be looking into this prop a bit more with select!

**Comment by amandadupell** [comment]
got some help from @jcfilben this week

when looking more into the nuances of this issue, there are many different ways the user can implement Select with onSearch. for the Multiple Search with Select, the documentation should be updated to reflect this and storybook examples may need to be updated to ensure they are showing the best practice way to use onSearch

**Comment by jcfilben** [comment]
Closing since the guidance in the docs for handling `options` when using `onSearch` has been updated. See https://github.com/grommet/grommet-site/pull/365
