### ISSUE TITLE
General Updates to `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by kevingill55** [grommet/grommet#5669]
### Expected Behavior

Some potential updates to the `CONTRIBUTING.md` file:

- [ ] Include a section on label usage and explanations of what each label means.
- [ ] Add information about the Slack channel. What channels you should join, where to ask what questions, etc.
- [ ] Maybe include a tidbit about checking prior issues and pull requests before reaching out for assistance and submitting issues.
- [ ] The video link at the bottom of the guide is not working. Should probably remove that section for now.

### Steps to Reproduce
Navigate to the [contributing guide.](https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md)

### Your Environment
N/A

**Comment by jcfilben** [comment]
Hi @kevingill55 great notes!
1. Label usage
I agree it would be helpful to include an explanation of the labels we use and what they mean. Here are a few ideas of what we could include:
`waiting`: applied to pull requests that have been reviewed and are waiting for a response or changes from the author. The label can also be applied to issues that have been commented on and are waiting for a response from the author. The waiting label is usually applied after 1 week of no response.
`needs attention`: applied to pull requests that have been waiting for a response or changes for a while but are something we want to get merged. This label lets us know that a pull request may need to be handed off to get it to the finish line.
`good first issue`: indicates issues that are a good place to start for new contributors.
`help wanted`: a request for help from the community on a particular issue. (Keep in mind feedback and help is welcome on any of our issues).
`PRty`: used by our team to flag pull requests that we want to review during our biweekly 'PRty' meeting.

2. Slack channel
I think we can include a link to the slack invite page: https://slack-invite.grommet.io/. And also add some quick descriptions of some of the channels that are available:
`general`: all members of Grommet slack are in this channel.
`announcements`: used for Grommet related announcements such as releases.
`help`: a place to ask questions about Grommet.
and more!
Perhaps the slack channel section could replace the video section.
3. Guidance on checking old issues and pull requests before submitting new ones
I think we can add a note to idea 7 in the `You can Become a Contributor` section about this
4. Video
I tested the link and as you said it is not working. I'm not sure what happened to the video of if there is another place it is stored, but for now I agree we can remove this section.
