### ISSUE TITLE
Support for css-modules?

### ISSUE THREAD

**Issue by antoligy** [grommet/grommet#567]
Hey,

Love what you're doing here.  Is support for [css-modules](https://github.com/css-modules/css-modules) planned?

My current workaround to import Grommet styles into a project using css-modules is to import and extend it via a `grommet.scss-global` file, and to add a new webpack loader for this file extension which disables CSS modules.

**Comment by ericsoderberghp** [comment]
From a quick scan of css-modules. It seems likes it's along the same lines we've been steering Grommet's stylesheets. Until I have time to look into it further, do you have any suggestions on how grommet could change to make it easier to integrate with css-modules?

**Comment by antoligy** [comment]
Hey!  I guess that depends on how Grommet is to be built: If the webpack route is appropriate, then it may be worth attempting to use them wholesale, relying on Webpack's css-loader to transform stylesheets into objects capable of providing class names. (i.e. `import styles from ./something.scss` allows me to `className={styles['chart__axis--x']}`)

**Comment by bryanjacquot** [comment]
Related to: https://github.com/grommet/grommet/issues/678

**Comment by alansouzati** [comment]
For now we will remain with SASS+BEM methodology. 

Please save some time to read my journey when investigating CSS in Javascript, including CSS modules.

https://blog.grommet.io/post/2016/08/10/css-in-js-may-not-be-the-solution-to-all-your-problems
