### ISSUE TITLE
Grommet Carousel Transition

### ISSUE THREAD

**Issue by matsawkaHPE** [grommet/grommet#5675]
Expected Behavior:
When clicking Next or Previous on the Grommet Carousel there would be a smooth transition. Something like Bootstrap, where the current image slides off as the new image slides in.

Actual Behavior
The current image disappears and the new images slides in, which makes the transition feel abrupt especially for large hero carousels. 

Steps to Reproduce
This is the standard out of the box behavior of the carousel as you can see with the grommet example:
https://v2.grommet.io/carousel

Your Environment
- Grommet version: 2.18.0
- Browser Name and version: all 
- Operating System and version: all

**Comment by halocline** [comment]
Notes:
- Abruptness occurs because `visibility` is set to 'hidden' and which does not allow the fadeOut animation to display https://github.com/grommet/grommet/blob/45198d0d6878f79d8e82f0e08ee4190df6d3d839/src/js/components/Carousel/Carousel.js#L162
- Looks like this was a regression introduced by https://github.com/grommet/grommet/pull/5326 when trying to prevent non-active slides from being visible onMount.

**Comment by kevingill55** [comment]
That's right yeah. I can start taking a look at this

**Comment by ericsoderberghp** [comment]
Original requestor is asking for a visual transition that does a whole image slide as opposed to a fade out.

**Comment by halocline** [comment]
Additional details from Slack:

"Hello Grommet Team, I have a deep-pull of a bug for you related to the carousel. On the carousel, we have some text - article title and short description - which is coming from a fetch call, the front-end is using some css to limit the text to 2 lines as to not overflow, the css is:
```
overflow: hidden;
text-overflow: ellipsis;
display: -webkit-box;
-webkit-box-orient: vertical;
-webkit-line-clamp: 2;
```

those 5 lines - which is working, except for Safari and iOS
after some head scratching, I did find this deep-pull article: https://bugs.webkit.org/show_bug.cgi?id=207013
is it possible while you are looking at the source code of the carousel to see if you swapped visibility with opacity, that this issue will be resolved? and either have a fix, or some code to override the visibility with opacity if works?
I didn't see any documentation on how to capture a click event on Next/Previous buttons in the documentation"

I have asked for a CodeSandbox to review. We may have recommendation for an alternate approach for how the truncation / overflow prevention is achieved.
