### ISSUE TITLE
Notification should allow directly controlling the auto dismiss time, including disabling auto dismiss

### ISSUE THREAD

**Issue by danielm-hpe** [grommet/grommet#5681]
There are some cases where the use case for toast notifications call for the toast to be visible for longer than 8 seconds, or to be visible until dismissed (disable the auto-dismiss entirely).  Currently the auto-close time can only be controlled via the theme, but apparently not disabled- https://v2.grommet.io/notification#notification.toast.time

### Expected Behavior

I would like to have the ability to leave a toast notification active until the user dismisses it, or my business logic dictates to close it.  An example use case would be for notifying the user that the application is experiencing API level failures, so the experience will be degraded.  In this example the expectation would be for the toast notification to stay active until the user dismissed it, or the API failures stopped.  If the user dismissed it, the toast would not be shown again until after a successful round of API calls and then more failures occurred.

### Actual Behavior

The notification component default behavior is to close after 8 seconds, which can be controlled via the theme, but apparently not disabled.

### URL, screen shot, or Codepen exhibiting the issue

https://v2.grommet.io/notification#notification.toast.time
https://github.com/grommet/grommet/blob/f6120b2fb6830ac43c9c3ef00497244ff414ce41/src/js/components/Notification/Notification.js#L23

### Steps to Reproduce

Not a defect- enhancement request

### Your Environment

- Grommet version: 2.18.0
- Browser Name and version: chrome 94
- Operating System and version (desktop or mobile): windows 10

**Comment by g4rry420** [comment]
Can I work on this issue ?
