### ISSUE TITLE
FormField alignment with required fields

### ISSUE THREAD

**Issue by bilak** [grommet/grommet#5700]
When using FormField with required fields the fields doesn't have same allignment as FormField without required field.

### Expected Behavior

All fields (required or not required) have same alignment.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/5826062/137797085-d4e7782a-07be-4cc0-b2ef-9e56062c8e77.png)
vs
![image](https://user-images.githubusercontent.com/5826062/137797129-35b8af5c-4f37-450f-9ecb-71f139a596e9.png)

- Grommet version: 2.18.0
- Browser Name and version: chrome
- Operating System and version (desktop or mobile): ubuntu 20.0.4

**Comment by ericsoderberghp** [comment]
The issue appears to be that the Text component doesn't inherit it's font-size and line-height from the FormField `<label />` container.
