### ISSUE TITLE
DateInput: When user choose date from calendar - calendar blinks.

### ISSUE THREAD

**Issue by smiksiukhpe** [grommet/grommet#5726]
When I chose date from calendar, this calendar blinks (looks like re-render)

### Expected Behavior

Calendar should not blink. Calendar should be opened until user close it by clicking outside.

### Actual Behavior

Calendar blinks.

![calendar](https://user-images.githubusercontent.com/81712383/138511208-22f89f46-9e2e-4e5a-bb84-e46d371996ab.gif)

### Steps to Reproduce

1. click on calendar icon in DateInput to open calendar.
2. choose some date from calendar

### Your Environment

- Grommet version: 2.10.0
- Browser Name and version:  chrome 95.0
- Operating System and version (desktop or mobile): MacOS BigSur 11.6 Desktop

**Comment by ZsuzsaMano** [comment]
The calendar in Dateinput was used to close when I clicked on it. But suddenly it changed behaviour, however, we didn't update the version. The new version has a totally different behaviour, also clicking on the calendar doesn't open it, so it would be confusing for our users.

**Comment by samantha-jp** [comment]
@smiksiukhpe Once the user selects a date, the calendar picker should close, not when user clicks outside.

**Comment by iPrime** [comment]
I'm experiencing the same issue.

**Comment by jcfilben** [comment]
I believe this issue should no longer be occurring. In Grommet v2.19.1 the calendar closes after a date is selected so the flashing behavior no longer happends. You can take a look at the behavior in this [codesandbox example](https://codesandbox.io/s/grommet-v2-template-forked-ftpby?file=/index.js).

@iPrime If you are still experiencing this issue could you share a codesandbox showing the drop flashing in v2.19.1?

@ZsuzsaMano there is a separate issue tracking the clicking of the calendar icon not opening the drop. (See https://github.com/grommet/grommet/issues/5706)

**Comment by jcfilben** [comment]
Hi all, I am going to go ahead and close this issue. https://github.com/grommet/grommet/pull/5838 got merged which fixes the calendar icon not opening the drop issue. Now the calendar icon can be clicked to open and close the drop (this is currently available on the stable branch and will be available in the next release). The calendar blinking behavior was fixed previously and is not occurring in v2.19.1 as shown in the codesandbox above.

**Comment by smiksiukhpe** [comment]
@jcfilben @samantha-jp issue fixed for me in v 2.19.1 - thanks!
