### ISSUE TITLE
grommet 0.6.2 & 0.6.4 not working due to missing icon file

### ISSUE THREAD

**Issue by robi-richter** [grommet/grommet#573]
```
ERROR in ./~/grommet/index-icons.js
Module not found: Error: Cannot resolve 'file' or 'directory' 
./components/icons/base/ZoomIn.js in
/home/robert/projects/hhhh/node_modules/grommet
 @ ./~/grommet/index-icons.js 3:19227-19271
```

**Comment by alansouzati** [comment]
Thanks for reporting this, we are investigating this now. I've just tested 0.6.2 and it has all the icons in the base folder. 0.6.4 has missing icons.

**Comment by alansouzati** [comment]
Grommet 0.6.5 has been released and has all the icons. sorry about that.

**Comment by robi-richter** [comment]
Thanks @alansouzati, I will check it out tomorrow.
