### ISSUE TITLE
Need a button inside the select dropdown (is this possible ?)

### ISSUE THREAD

**Issue by NamrataPatel29** [grommet/grommet#5731]
Hi,
I am trying to develop a multiple select component, where i need two buttons at the end of the select dropdown.

i cant find any props which can help me do this.
can anyone please tell me is there a prop or way to  add button components inside the select dropdown at the end of the options 

This is what i want to do :
![image](https://user-images.githubusercontent.com/76097441/138590988-d9efd6bc-d81a-421c-9102-051e24b4af55.png)

The buttons should be present inside the select dropdown located below the options. and on click of any of the buttons i want to call a function to do somethings

**Comment by jcfilben** [comment]
Hi @NamrataPatel29 there is not a way to add a button within the drop for Select except for a clear button. Take a look at [the Select/Clear story](https://storybook.grommet.io/?path=/story/input-select-clear--clear) to see how to add the clear button within Select. If you need the 'View Selected' button as well this would have to be done with a custom component. I hope that answers your question. Feel free to reopen the issue if you have more questions related to this.
