### ISSUE TITLE
Accordion's Title container Can be a Div instead of Button

### ISSUE THREAD

**Issue by venkatesh-elchuri** [grommet/grommet#5733]
### Expected Behavior
 When we are using button inside the accordion's title , No console warnings should present. So, It is possible to have div instead of button .

### Actual Behavior
Getting console warning when using buttons inside accordion title container.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/30321668/138667287-20354e87-e5c6-41c4-9368-841ba938226e.png)

### Steps to Reproduce
Refer below  codesandbox link
https://codesandbox.io/s/nostalgic-tu-7bxjm?file=/src/App.js
### Your Environment

Grommet version: latest
Browser Name and version: Chrome ,Latest
Operating System and version (desktop or mobile): Desktop, windows

**Comment by jcfilben** [comment]
Hi @venkatesh-elchuri the Accordion Panel's title container is a Button that when clicked opens the AccordionPanel's content. Even if we switched this to a div that was clickable it would still break accessibility rules to place a Button within it.
