### ISSUE TITLE
Enhance Stories to Use Storybook Theming Functionality

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#5735]
The ability to view Storybook stories with different themes was added in https://github.com/grommet/grommet/pull/5674.

We need to make adjustments to the stories component by component to take advantage of the theming ability. The Button stories are currently using this enhancement and can be viewed on [storybook](https://storybook.grommet.io/?path=/story/controls-button-active--active). While on a Button story you can change the theme by selecting the 'Theme' button in the top bar above the story and then selecting a theme from the drop down. Notice the stories changes style when you switch themes. We want to add this feature to all the stories.

For each story within a component if the story...
1. Is wrapped with `<Grommet theme={grommet}>...</Grommet>`
  -- remove `<Grommet theme={grommet}>` and replace with the following comment:
      `// Uncomment <Grommet> lines when using outside of storybook`
      `// <Grommet theme={...}>`
  -- comment out `</Grommet>`
  -- remove `import { Grommet }` and `import { grommet }`
2. Uses a custom theme
  -- create a CustomThemed folder directly under the `component/stories` folder
  -- move the story into the CustomThemed folder
  -- change the story export so that it shows up in a 'Custom Themed' folder within storybook. (Example: `export default { title: 'Controls/Button/Custom Themed/Active' };`)

For examples take a look at https://github.com/grommet/grommet/pull/5674. The `Button/stories/Basic.js` file shows an example of a story wrapped with `<Grommet theme={grommet}>`. The `Button/stories/CustomThemed/Active.js` shows an example of a story that uses a custom theme.

- [x] Accordion #5843 
- [x] Anchor #5737 
- [x] Avatar #5840 
- [x] Box #5962
- [x] Button https://github.com/grommet/grommet/pull/5674
- [x] Calendar #5843 
- [x] Card #5843 
- [x] Carousel #5843
- [x] CheckBoxGroup #5740 
- [x] Chart #5764 
- [x] CheckBox #5740 
- [x] Clock #5767 
- [x] Collapsible #5870 
- [x] DataChart #5765 
- [x] DataTable #5870 
- [x] DateInput #5740
- [x] Diagram #5962
- [x] Distribution #5962
- [x] Drop #5769 
- [x] DropButton #5737 
- [x] FileInput #5740 
- [x] Footer #5962
- [x] Form #5962
- [x] FormField #5962
- [x] Grid #5919
- [x] Header #5772 
- [x] Heading #5768 
- [x] Image #5962
- [x] InfiniteScroll #5962
- [x] Keyboard #5962
- [x] Layer #5970 
- [x] List #5752
- [x] Main #5962
- [x] Markdown #5962
- [x] MaskedInput #5962
- [x] Menu #5737 
- [x] Meter #5766 
- [x] NameValueList #5962
- [x] Nav #5770 
- [x] Notification #5755 
- [x] Pagination #5962
- [x] Paragraph #5750 
- [x] RadioButton #5740
- [x] RadioButtonGroup #5740
- [x] RangeInput #5962
- [x] RangeSelector #5962
- [x] Select #5955 
- [x] Sidebar #5955
- [x] SkipLinks #5955
- [x] Spinner #5754
- [x] Stack #5747 
- [x] Table #5955
- [x] Tabs #5771 
- [x] Text #5745 
- [x] TextArea #5909 
- [x] TextInput #5909
- [x] Tip #5945 
- [x] Video #5744
- [x] WorldMap #5742

**Comment by matheushahnn** [comment]
@jcfilben Accordion was finished on https://github.com/grommet/grommet/pull/5843. Can you link the PR?

**Comment by B-Esmaili** [comment]
Hey Grommet team. I wanna contribute on this issue but i have a question. How do you make sure only one contributor works on a component to avoid duplicate PRs? Please help me get started.

**Comment by jcfilben** [comment]
Hi @B-Esmaili once a PR is submitted for a component we add it to the list above in the issue description so that people know there is already a PR out there for that component.

If you want to make sure no one else starts working on the component you are planning to submit a PR for you can go ahead and add a comment to this issue saying that you are going to work on a particular component or components.

**Comment by B-Esmaili** [comment]
` Select`, `Sidebar`, `SkipLink` and `Table` done by me. please check.

**Comment by B-Esmaili** [comment]
What should we do in situations like following? https://github.com/grommet/grommet/blob/ae7e2bfcb55c021ca649b63d523a13778ddfe08b/src/js/components/Layer/stories/Center.js#L21

**Comment by B-Esmaili** [comment]
Required changes applied for all components except `Grommet` and `Layer`. Please check-out my [pull request](https://github.com/grommet/grommet/pull/5962) and please let me know what should we do about these two remaining components.

**Comment by jcfilben** [comment]
> What should we do in situations like following?
> 
> https://github.com/grommet/grommet/blob/ae7e2bfcb55c021ca649b63d523a13778ddfe08b/src/js/components/Layer/stories/Center.js#L21

We should be able to do something similar to what we did for `full` and `dir` where we pass the prop through story args and handle it in the `storybook/preview.js` file

**Comment by B-Esmaili** [comment]
> > What should we do in situations like following?
> > https://github.com/grommet/grommet/blob/ae7e2bfcb55c021ca649b63d523a13778ddfe08b/src/js/components/Layer/stories/Center.js#L21
> 
> We should be able to do something similar to what we did for `full` and `dir` where we pass the prop through story args and handle it in the `storybook/preview.js` file

Yes as I expected. But which prop name should we use to pass the options?

**Comment by jcfilben** [comment]
> Yes as I expected. But which prop name should we use to pass the options?

I think we can just call the prop `options`

**Comment by jcfilben** [comment]
All applicable stories have been enhanced to allow theme switching
