### ISSUE TITLE
HPE Simple Font CSS

### ISSUE THREAD

**Issue by L0ZZI** [grommet/grommet#574]
Add Support for Simple Font on Analytic Data.

**Comment by maysst** [comment]
Is this on the roadmap for Grommet within the HPE theme?

**Comment by tracybarmore** [comment]
Looking to implement in to Value component. Keeping in backlog for further investigation.

**Comment by L0ZZI** [comment]
The Units in the our visualization components and the Value component will receive and updated styles sheet to support the Simple font. This means the developer will no longer be able to use Metric in it's place. And the implementation of Simple will require a text-transform=uppercase and some character spacing to make it compliant with brand.

**Comment by tracybarmore** [comment]
Linking with updates that will be implemented with #1216

**Comment by L0ZZI** [comment]
Added to Grommet v2 plan.
