### ISSUE TITLE
Using Anchor with Link from react-router

### ISSUE THREAD

**Issue by jameswyse** [grommet/grommet#576]
I'm trying to create links using the `Anchor` component with the `Link` component from react-router. I read in the docs that the `tag` prop can be used for this:

> The DOM tag to use for the element. The default is <a>. This should be used in conjunction with components like Link from React Router. In this case, Link controls the navigation while Anchor controls the styling.

However I can't seem to get it working since `tag` is expecting a String and not another component. I tried `<Anchor tag="Link">` but it attempted to render a stylesheet style `<link>` instead.

> Uncaught Invariant Violation: link is a void element tag and must not have `children` or use `props.dangerouslySetInnerHTML`. Check the render method of Anchor.

There's also the issue of passing props (like `to`) to the Link tag. 

Any help appreciated!

**Comment by coltonw** [comment]
I took a different approach and wrapped the anchor element and added an onClick to do my navigating. Something like this:

```
import React, { Component } from 'react';
import { push } from 'react-router-redux';
import Anchor from 'grommet/components/Anchor';

export class NavAnchor extends Component {

  constructor() {
    this.onClick = this.onClick.bind(this);
  }

  onClick(event) {
    event.preventDefault();
    this.props.dispatch(push(this.props.path));
  }

  render() {
    const path = this.props.path;
    return (
      <Anchor
        {...this.props} href={path}
        onClick={this.onClick}
      />
    );
  }
}

export default connect(select)(NavAnchor);
```

**Comment by cjhowe** [comment]
I will work on a pull request for this tonight.

**Comment by alansouzati** [comment]
thanks @coltonw. This is exactly what we are doing in some apps we are developing.

I believe this should live outside Grommet core. As it deals with react-router and redux. In my case the push function is coming from History api.

**Comment by batjko** [comment]
This should probably be changed in the Grommet docs then, so it doesn't explicitly point at the Link element as a use case anymore.

But is it not possible to just use the styling from the Anchor component, somehow?
I am fairly new to React and React-Router and I'm not sure I want/need to create a separate component just for a link?

**Comment by ZephD** [comment]
Tried `tag={Link}`?

**Comment by batjko** [comment]
@ZephD  Yup, ends up reloading the whole page on the link, so we don't want to use the `href` property, but React's `<Link>` instead...

**Comment by alansouzati** [comment]
` this.context.router.push(this.props.path);` should do the trick.

Here is how we use Grommet Anchor with react-router:

```
// (C) Copyright 2014-2015 Hewlett Packard Enterprise Development LP

import React, { Component, PropTypes } from 'react';
import Anchor from 'grommet/components/Anchor';

/**
* This component is used to augment Grommet anchor
* with routing/history capabilities
*/
export default class NavAnchor extends Component {

  constructor () {
    super();
    this._onClick = this._onClick.bind(this);
  }

  _onClick (event) {
    event.preventDefault();
    this.context.router.push(this.props.path);
    if (this.props.onClick) {
      this.props.onClick();
    }
  }

  render () {
    const { path } = this.props;
    const { router } = this.context;
    let className = this.props.className || '';
    if (router.isActive(path)) {
      className += ' active';
    }
    let href = router.createPath(path);
    return (
      <Anchor {...this.props} className={className} href={href}
        onClick={this._onClick} />
    );
  }
};

NavAnchor.propTypes = {
  ...Anchor.propTypes,
  onClick: PropTypes.func,
  path: PropTypes.string.isRequired
};

NavAnchor.contextTypes = {
  router: PropTypes.object.isRequired
};
```

**Comment by bjackson** [comment]
@ZephD, it works for me when I use your suggestion. However, that is not the correct property type for tag. It should be a string, and the browser complains accordingly. Should this be changed to allow other types, @alansouzati?

**Comment by alansouzati** [comment]
I believe this is related to the PR you sent, right @bjackson ?

I added a few comments there.

**Comment by alansouzati** [comment]
https://github.com/grommet/grommet/pull/1108

**Comment by bjackson** [comment]
Right! I'll modify the PR.

**Comment by alansouzati** [comment]
Thanks!

**Comment by benshell** [comment]
I'm just trying/learning Grommet and quickly ran into this issue as well, with React Router v4. It seems to me that the simplest solution is to create a new component to render Anchor as a span, inside of Link:

```
import React from 'react';
import { Link } from 'react-router-dom';
import Anchor from 'grommet/components/Anchor';

export default (props) => (
  <Link to={props.to}>
    <Anchor tag="span" primary={props.primary}>{props.children}</Anchor>
  </Link>
);
```

**Comment by alansouzati** [comment]
I've added indexLink support as part of this commit:

https://github.com/grommet/grommet/commit/06adf025de881686d08ab1dabf1398f40ca0c912

usage:

`<Anchor primary={props.primary} path={{ path: props.to, index: true }}/>`

**Comment by Amurmurmur** [comment]
Cant understand, if I need to wrap Anchor with Link or Link with Anchor?

Could you please provide a little bit more detailed example with react-router @alansouzati ?

Thank you very much in advance!

**Comment by coltonw** [comment]
I think neither? Using Anchor by itself but giving it a `path` instead of an `href` will use react-router under the covers automatically.

**Comment by Amurmurmur** [comment]
@coltonw Sorry just didnt have component connected with react-redux-router.

My mistake, everything works like a charm 👍

**Comment by jvatic** [comment]
Here's a modified version of @alansouzati's example written in typescript:

```typescript
// NavAnchor.tsx
import * as React from 'react';
import { withRouter, RouteComponentProps } from 'react-router-dom';
import Anchor from 'grommet/components/Anchor';

export interface Props extends Grommet.AnchorProps, RouteComponentProps<{}> {
	path: string;
	onClick?(e: React.MouseEvent): void;
}

class NavAnchor extends React.Component<Props> {
	constructor(props: Props) {
		super(props);
		this._onClick = this._onClick.bind(this);
	}

	public render() {
		const {
			path,

			// filter out RouteComponentProps
			match,
			location,
			history,
			staticContext,

			...anchorProps
		} = this.props;
		const href = history.createHref({ pathname: path });
		return <Anchor {...anchorProps} href={href} onClick={this._onClick} />;
	}

	private _onClick(e: React.MouseEvent) {
		if (this.props.onClick) {
			this.props.onClick(e);
		}
		if (e.defaultPrevented) {
			// allow this.props.onClick to cancel this action via e.preventDefault()
			return;
		}
		if (e.ctrlKey || e.metaKey || e.shiftKey || e.altKey) {
			// don't do anything if any modifier key is pressed
			// it's likely the user is trying to open the link in a new tab or window
			return;
		}
		const { path, history } = this.props;
		e.preventDefault();
		history.push(path);
	}
}

export default withRouter(NavAnchor);
```

Usage:

```typescript
<NavAnchor path="/some/path" onClick={(e: React.MouseEvent) => {
    if (/* should prevent navigation */) {
        e.preventDefault();
        return;
    }
    console.log('about to navigate');
)}}>My Resource</NavAnchor>
```

(I'm using [this typescript type definition for grommet](https://github.com/jansel369/grommet-typescript).)

**Comment by uyouthe** [comment]
@benshell this should be mentioned [here](https://v2.grommet.io/anchor).

**Comment by JustMaier** [comment]
Here's a quick and dirty `NavLink` replacement that uses `Anchor` and exposes an `activeColor` property:

```js
import React from 'react';
import { Link, Route } from "react-router-dom";
import { Anchor } from "grommet";

export default function NavAnchor({
  "aria-current": ariaCurrent = "page",
  exact,
  isActive: isActiveProp,
  location,
  strict,
  to,
  color,
  activeColor,
  ...rest
}) {
  const path = typeof to === "object" ? to.pathname : to;

  // Regex taken from: https://github.com/pillarjs/path-to-regexp/blob/master/index.js#L202
  const escapedPath = path && path.replace(/([.+*?=^!:${}()[\]|/\\])/g, "\\$1");

  return (
    <Route
      path={escapedPath}
      exact={exact}
      strict={strict}
      location={location}
      children={({ location, match }) => {
        const isActive = !!(isActiveProp
          ? isActiveProp(match, location)
          : match);

        return (
          <Anchor
            as={Link}
            aria-current={(isActive && ariaCurrent) || null}
            to={to}
            color={isActive ? activeColor : color}
            {...rest}
          />
        );
      }}
    />
  );
}
```

**Comment by ht4963** [comment]
@jvatic, Thanks for the typescript code. It works great!

**Comment by atanasster** [comment]
here is what I am using:
```
import React from 'react';
import { Link } from 'react-router-dom';
import { Anchor, Button } from 'grommet';

class RoutedLink extends React.Component {
  render() {
    const {
      path, 'aria-label': ariaLabel, children, className,
      disabled, href, onBlur, onClick, onFocus,
    } = this.props;
    return (
      <Link
        to={path}
        aria-label={ariaLabel}
        className={className}
        disabled={disabled}
        href={href}
        onBlur={onBlur}
        onClick={onClick}
        onFocus={onFocus}
      >
        {children}
      </Link>
    );
  }
}
export const RoutedAnchor = props => (
  <Anchor
    {...props}
    as={RoutedLink}
  />
);

export const RoutedButton = ({ path, ...props }) => (
  <Button
    path={path}
    {...props}
    as={RoutedLink}
  />
);

```

**Comment by gegis** [comment]
> I took a different approach and wrapped the anchor element and added an onClick to do my navigating. Something like this:
> 
> ```
> import React, { Component } from 'react';
> import { push } from 'react-router-redux';
> import Anchor from 'grommet/components/Anchor';
> 
> export class NavAnchor extends Component {
> 
>   constructor() {
>     this.onClick = this.onClick.bind(this);
>   }
> 
>   onClick(event) {
>     event.preventDefault();
>     this.props.dispatch(push(this.props.path));
>   }
> 
>   render() {
>     const path = this.props.path;
>     return (
>       <Anchor
>         {...this.props} href={path}
>         onClick={this.onClick}
>       />
>     );
>   }
> }
> 
> export default connect(select)(NavAnchor);
> ```

Thanks for `onClick` idea on parent component, that saved my day!
