### ISSUE TITLE
Remove 'v2' from the grommet URL

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#5782]
### Expected Behavior
https://v2.grommet.io/ Should be routed to https://grommet.io/
URL should not present a reference to grommet's major version.

### Actual Behavior
https://v2.grommet.io/

### Steps to Reproduce

1. Go to https://v2.grommet.io/
2. See the URL has `v2`

### Your Environment

- Grommet version: Any
- Browser Name and version: Any
- Operating System and version (desktop or mobile): Any

**Comment by jcfilben** [comment]
Closing this & moved the issue to grommet-site. Issue can be found here: https://github.com/grommet/grommet-site/issues/339.
