### ISSUE TITLE
InfiniteScroll w/ replace={true} breaks when items update

### ISSUE THREAD

**Issue by lleBit** [grommet/grommet#5786]
### Expected Behavior

Should not break when items update.

### Actual Behavior

InfiniteScroll breaks with replace={true} option when items update (see repro steps below).

Could be related to https://github.com/grommet/grommet/issues/5739.

### URL, screen shot, or Codepen exhibiting the issue

Here's a Codesandbox template that serves as a nice starting point
for demonstrating an issue: https://codesandbox.io/s/infinite-scrolling-w-replace-4x095

### Steps to Reproduce

1. Scroll past the item (somewhere in the middle?).
2. Search for the item that has been scrolled past (something like item 150).
3. See no items in the list.
4. See the error in screenshot.

![image](https://user-images.githubusercontent.com/91166566/140436730-ed4260d9-4325-458f-82a2-ab3dcce2b36f.png)

https://user-images.githubusercontent.com/91166566/140436948-b9d80975-3bfd-4881-90a9-9826aefae9c3.mov

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: Chrome 95.0.4638.69
- Operating System and version (desktop or mobile): MacBook Pro - Big Sur 11.6

**Comment by jcfilben** [comment]
In the description for the `replace` prop it mentions when setting the prop to true, "This is more performant but means that in-page searching will not find elements that have been replaced"

**Comment by jcfilben** [comment]
I am going to go ahead and close this since I think based on the `replace` prop description above the search is not expected to work. Feel free to reopen if you want to continue discussion on this.
