### ISSUE TITLE
Calendar does not recognize box width

### ISSUE THREAD

**Issue by nomadus** [grommet/grommet#5795]
I have a DateTime and a button within a Box, but unfortunately, the Calendar component does not recognize the parent box's size. The result is shown in the attached picture.  

```
<Box border gap="small" pad="small">
	<DateInput
		id="dueDate"
		inline
		onChange={{}}
		value={dueDate}/>

	<Button
		color="brand"
		label="Save"
		primary={true}/>
</Box>
```

![image](https://user-images.githubusercontent.com/3382143/140882037-2dc8181c-67d6-4156-8a64-52853ac95997.png)

**Comment by jcfilben** [comment]
Hi @nomadus try adding `calendarProps={{ fill: true }}` as a prop on the DateInput to achieve the desired behavior. Take a look at this [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-930xm?file=/index.js) example.

**Comment by nomadus** [comment]
Thanks, it helped!
