### ISSUE TITLE
ThemeType is missing support for extend property in rangeInput.thumb

### ISSUE THREAD

**Issue by tabular-email** [grommet/grommet#5796]
The `ThemeType` is missing support for the `extend` property in `rangeInput.thumb`.

### Expected Behavior

`ThemeType` should support `rangeInput.thumb.extend`.

### Actual Behavior

`ThemeType` does not support `rangeInput.thumb.extend`. It only allows for the `color` property at the moment.

- Grommet version: 2.18.0

**Comment by jcfilben** [comment]
Hi @tabular-email this was fixed in https://github.com/grommet/grommet/pull/5673. Right now this fix is only applied on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) of Grommet. It will be available in the next release.

**Comment by jcfilben** [comment]
Closing this since it has been resolved and will be available in the next release.
