### ISSUE TITLE
Add modal (or some option) to Layer to prevent clicking backdrop from closing the layer

### ISSUE THREAD

**Issue by genyded** [grommet/grommet#580]
Some use cases mandate that the only way to close a layer (dialog) is so click the closer or a button in the Layer and not be able to close it by clicking the backdrop. Could we consider a modal or some other named property to provide this behavior? This may also help address some of the open Layer re-size issues.

**Comment by alansouzati** [comment]
I like having this as a configurable option. How about naming it `closeOnClick` which defaults to true.

We are evaluating the possibility to deprecate the close attributes, so it would be the caller's responsibility to decide when to close the layer. What are your thoughts on that?

If you look the layer code in here: https://github.com/grommet/grommet/blob/master/src/js/components/Layer.js#L73

all we are doing is to invoke the onClose callback anyways. Probably you are changing the state to actually close the modal.

It is going to be a little more work on the callers side, but at least will avoid problems like this one:

http://codepen.io/alansouzati/pen/regLqJ

If you check the codepen, you will see a colored box inside that Layer that affects the color contrast in the close icon in a non-accessible way. It is really hard to fix this issue, as we don't know what is inside a given layer. If the caller controls the close icon, than you can make sure the icon color will match the background color inside your layer.

**Comment by genyded** [comment]
We're probably OK with whatever the solution ends up being and don't mind if we have to do a bit extra to get it. Our biggest concern is that if a Layer contains a complex form (or wizard multi-step form) and the user is on a larger screen - they can fill in a bunch of stuff, accidentally click the backdrop and then *POOF*. We're in progress adding some confirmations to help prevent this, but it would be nicer to just prevent it in the first place.

Not critical - but nice to have one way or another. Thanks!

**Comment by alansouzati** [comment]
agreed :)

for now, until we figure out if we will deprecate close options or not, i will add the closeOnClick feature. 👍

**Comment by bryanjacquot** [comment]
@genyded this can be achieved by intercepting the event in the onClose function as shown in this updated Codepen.  http://codepen.io/alansouzati/pen/regLqJ
