### ISSUE TITLE
DateInput component of grommet-v2 is not supporting date format with "-". For ex: 12-Nov-2021, 12-11-2021 not working for these kind of cases.

### ISSUE THREAD

**Issue by rahulgoyal21** [grommet/grommet#5802]
### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment]
Hi @rahulgoyal21 can you make sure you are using the latest version of Grommet (currently v2.19.1). Here is a [codesandbox ](https://codesandbox.io/s/grommet-v2-template-forked-i9p7j?file=/index.js) showing date input working correctly with '-' as the separator.

**Comment by jcfilben** [comment]
Closing since the above codesandbox shows the "-" separator working correctly in DateInput.
