### ISSUE TITLE
Anchor prop error -> Invalid prop `as` supplied to `Anchor`.

### ISSUE THREAD

**Issue by motion-x** [grommet/grommet#5803]
### Expected Behavior

No failed prop error should be raised when React Router `Link` is passed to the `as` prop of `Anchor`

### Actual Behavior

When using Anchor with React Router Link in the following fashion:
`<Anchor  as={Link}  label={item.label}  to={item.href}  />`
A Failed prop type error is logged to the console.
However the element behaves as expected. and the Link works fine.

Possible bug in prop types definition.

```
Warning: Failed prop type: Invalid prop `as` supplied to `Anchor`.
./node_modules/grommet/es6/components/Anchor/Anchor.js/Anchor<@http://localhost:3000/static/js/vendors~main.chunk.js:68083:19
NavBar@http://localhost:3000/static/js/main.chunk.js:172:7
div
O@http://localhost:3000/static/js/vendors~main.chunk.js:178530:6
./node_modules/grommet/es6/components/Grommet/Grommet.js/Grommet<@http://localhost:3000/static/js/vendors~main.chunk.js:83447:18
App@http://localhost:3000/static/js/main.chunk.js:309:79
Router@http://localhost:3000/static/js/vendors~main.chunk.js:165525:7
BrowserRouter@http://localhost:3000/static/js/vendors~main.chunk.js:165037:
```

### Steps to Reproduce

In a project using React router dom use an Anchor element like this: `<Anchor  as={Link}  label={item.label}  to={item.href}   />`

### Your Environment

- Grommet version: 2.18.0
- Browser Name and version: Firefox
- Operating System and version (desktop or mobile): Ubuntu 20.04
- React Router DOM version: 6.0.2
- React version: 17.0.2

**Comment by Zodiase** [comment]
I also see this in grommet@2.19.1 after building a custom link following the example in https://github.com/grommet/grommet/issues/3572#issuecomment-913620305.
