### ISSUE TITLE
Enhance FileInput to recognize user operating system for maxSize calculation

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5807]
### Expected Behavior

FileInput should recognize what operating system a user is on when determining if `1024` (binary) or `1000` (decimal) should be used as the conversion factor between bytes, KB, etc.

Right now, FileInput uses binary value (1024) of bytes as a conversion factor to determine if a file has exceeded the max size or not. This seems to be the better option (vs decimal conversion factor of 1000) because it ensures that all windows users will experience and accurate comparison between their file browser and Grommet's FileInput. Previously, window's users were being flagged by Grommet's FileInput that their file was too large even though their file browser said it was less than the max size (their file browser used 1024, while grommet used 1000).

While our current solution provides users (regardless of their operating system) with a reasonable experience, it may be nice to enhance FileInput in the future to be slightly more intelligent.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by Isaac-alencar** [comment]
Hey @jcfilben, can I work on it?

**Comment by jcfilben** [comment]
Hi @Isaac-alencar great to hear you are interested in contributing! Feel free to work on this

**Comment by Isaac-alencar** [comment]
@taysea do you have any concrete example of this behavior? something that we can look up for to define which conversion factor to use

**Comment by jcfilben** [comment]
You can search Gigabyte (GB) vs Gigibyte (GiB) to see the conversion between the two. I believe Mac uses GB and Windows uses GiB.

GB = 1000^3 bytes
GiB = 1024^3 bytes

**Comment by halocline** [comment]
Other references:
- https://askubuntu.com/questions/341143/why-same-file-shows-different-sizes-in-different-operating-systems#answer-341152
- https://qr.ae/pvca9y
- https://discussions.apple.com/thread/5501534#23583820022
- https://www.macprime.ch/a/news/snow-leopard-1-gb-1000-mb/
- https://www.hecticgeek.com/for-the-same-file-why-windows-and-ubuntu-show-different-sizes/

**Comment by Isaac-alencar** [comment]
Thank you so much @jcfilben and @halocline I'll take a look!
