### ISSUE TITLE
Add support for custom controls/components in FormField

### ISSUE THREAD

**Issue by genyded** [grommet/grommet#581]
Trying to use [react-select](https://github.com/JedWatson/react-select) or other existing or even internally developed controls does not work with FormField. Often there are valid reasons why one would not want to map a control back to the basic html type - such as custom rendering for select controls, or drag and drop lists, custom file upload components ( we all hate the `ugly` button now) and so on. So it seems like maybe FormField should maybe be a layout wrapper providing optional labels, but not assume anything about it's children or their classes/types. 

Not sure if that's preferable to beefing up Grommet controls/components to provide a larger set of capabilities that some of the more robust external components provide, so this may become more of a discussion topic instead of an issue, but nonetheless. One might also assert that any React based library should also support integration with other React based libraries/modules (potential namespace and css conflicts aside each of which can quite easily be addressed on it's own merit).

**Comment by alansouzati** [comment]
Sorry but react-select is not accessible. Accessibility is a big feature in grommet and we try to be opinionated about this. Take a look in this issue: https://github.com/JedWatson/react-select/issues/353.
I say the same for drag and drop.

Our main philosophy is to be your one-stop-shop for UI development if you follow our guidelines and components. If we don't support something, we would rather have it natively available than you having to integrate something that does not match with our UX framework.

Please keep in mind that Grommet is not only a ReactJS library, but a UX framework. This means that some features/components will not be available if it does not meet our UX guidelines.

**Comment by genyded** [comment]
Fair enough and kudos for staying true to the core tenants of Grommet. When my team and I get some breathing room (or if we ever do) - we'll try to help invest some time in getting some of this the right way.We can work around it for now. Thanks for the follow up!

**Comment by alansouzati** [comment]
you bet, looking forward to your contributions 👏
