### ISSUE TITLE
Upgrade Chromatic to v6

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#5810]
We are currently using Chromatic v5. We should upgrade to the latest major version, v6.

<img width="578" alt="Screen Shot 2021-11-17 at 4 46 44 PM" src="https://user-images.githubusercontent.com/54560994/142300377-eb776286-2bcd-41d1-afd7-66601ff96158.png">

**Comment by britt6612** [comment]
done here https://github.com/grommet/grommet/pull/5821
