### ISSUE TITLE
grommet crashes Saturn MFE template if React upgraded to v16.8.x or 17.0.x

### ISSUE THREAD

**Issue by samuelgoff** [grommet/grommet#5812]
`grommet` (& `grommet-icons`) crashes any app based on the [new Saturn MFE template](https://github.com/hpe-hcss/saturn-app-template) if `react` is upgraded to v`16.8.x` or `17.0.x`.

### Expected Behavior
MFE developers should be able to upgrade `react` to v`16.8.x` or `17.0.x` without `grommet` or `grommet-icons` crashing the app.

### Actual Behavior

MFE app crashes, hard. The list of errors all relate to `styled-components`, which is also upgraded to the latest version (`5.3.3`)

### URL, screen shot, or Codepen exhibiting the issue

```
Compiled with problems:

ERROR in ./node_modules/grommet-icons/StyledIcon.js 8:48-76

Module not found: Error: Can't resolve 'styled-components' in '/Users/sam/Documents/git/hpe/metal-app/node_modules/grommet-icons'


ERROR in ./node_modules/grommet/components/AccordionPanel/AccordionPanel.js 8:24-52

Module not found: Error: Can't resolve 'styled-components' in '/Users/sam/Documents/git/hpe/metal-app/node_modules/grommet/components/AccordionPanel'


ERROR in ./node_modules/grommet/components/Anchor/Anchor.js 8:24-52

Module not found: Error: Can't resolve 'styled-components' in '/Users/sam/Documents/git/hpe/metal-app/node_modules/grommet/components/Anchor'

[...continues with an apparent enumeration of every grommet component]

```

console shows:
```
Uncaught Error: application 'metal' died in status LOADING_SOURCE_CODE: Cannot find module 'styled-components'
    at webpackMissingModule (animation.js:6)
    at Object../node_modules/grommet/utils/animation.js (animation.js:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../node_modules/grommet/utils/index.js (index.js:5)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../node_modules/@saturn/hooks/es6/hooks/useChartTheme/index.js (index.js:10)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
```

![Screen Shot 2021-11-19 at 11 53 59 AM](https://user-images.githubusercontent.com/2007084/142670880-96f01e6d-7a98-4e4b-a563-6a2556e7f8c5.png)

![Screen Shot 2021-11-19 at 9 43 23 AM](https://user-images.githubusercontent.com/2007084/142672786-17f085bc-315b-42a8-a9bc-59d7cb07b123.png)

![Screen Shot 2021-11-19 at 11 54 08 AM](https://user-images.githubusercontent.com/2007084/142672811-0b730744-fe1e-4fde-b378-82fe0b940747.png)

### Steps to Reproduce

1. go to the [new Saturn MFE template](https://github.com/hpe-hcss/saturn-app-template)
2. click on `use this template` button to generate an MFE app based on the template
3. 'Update the [package name](https://github.com/hpe-hcss/saturn-app-template/blob/main/package.json#L2) in the package.json with your app name' as described in **step 2** of the [code updates](https://github.com/hpe-hcss/saturn-app-template#code-updates) section
4. 'Update the [`saturn.config.js`](https://github.com/hpe-hcss/saturn-app-template/blob/main/saturn.config.js) with the correct app name and/or displayName' as described in **step 3** of the [code updates](https://github.com/hpe-hcss/saturn-app-template#code-updates) section
5. run `yarn`, then `yarn upgrade`, then `yarn start`
6. login, navigate to application path (in this case, `/sample`, unless you update this in [`Routes.js`](https://github.com/hpe-hcss/saturn-app-template/blob/main/src/Routes.js#L38)), & note the app works
7. stop the app & run `yarn upgrade react@^16.8`, then `yarn`, then `yarn upgrade`, then `yarn start`
8. note the app now crashes
9. stop the app & run `yarn upgrade react@^17`, then `yarn`, then `yarn upgrade`, then `yarn start`
10. note the app still crashes
11. revert changes to `package.json`, verify `react` version is back to `^16.0.0`, then run `yarn`, then `yarn upgrade`, then `yarn start`
12. note the app works again

### Your Environment

- Grommet version: `^2.17.5` & `2.19.0`
- Browser Name and version: Chrome Version 95.0.4638.69 (Official Build) (arm64)
- Operating System and version (desktop or mobile): macOS Monterey Version 12.0.1 (21A559)

**Comment by halocline** [comment]
These errors seem like `styled-components` is missing from one of the micro-frontend app dependencies. Have seem similar errors in a monorepo setting. Not exactly sure how the architecture is set up, but perhaps a place to start investigation ...

**Comment by samuelgoff** [comment]
> These errors seem like `styled-components` is missing from one of the micro-frontend app dependencies. Have seem similar errors in a monorepo setting. Not exactly sure how the architecture is set up, but perhaps a place to start investigation ...

Thanks @halocline, I figured out the issue, right before you posted this. Yep! The peerDependency for `styled-components` isn’t installed. For whatever reason, this works fine in react 16 prior to 16.8.x, but breaks when I upgrade to 16.8.x or 17. explicitly installing `styled-components` as a dependency in the MFE fixes the issue.

**Comment by halocline** [comment]
That's a bit odd, but great to hear you're up and running.
