### ISSUE TITLE
DataTable multi-select broken in 2.19

### ISSUE THREAD

**Issue by thomas-friedrich** [grommet/grommet#5813]
The multi-select in the data table is broken in grommet release 2.19.0

### Expected Behavior
Clicking in the checkbox in the table header, it should select all rows.
![image](https://user-images.githubusercontent.com/84544729/142686456-6006a34a-f99f-49c6-8d60-0aeeeadda4a2.png)

### Actual Behavior
The rows are not selected and an exception is thrown in the console log:
![image](https://user-images.githubusercontent.com/84544729/142686310-7eda25e7-8b0b-4eae-a692-400444d8c150.png)

### URL, screen shot, or Codepen exhibiting the issue

This can be reproduced with the grommet storybook for data tables:
https://storybook.grommet.io/?path=/story/visualizations-datatable-onselect--on-select-data-table

### Steps to Reproduce

See above

### Your Environment

- Grommet version: 2.19.0
- Browser Name and version: Chrome 95.0.4638.69
- Operating System and version (desktop or mobile): Mac OS Big Sur

**Comment by taysea** [comment]
Pulling from offline discussion, "looks like https://github.com/grommet/grommet/blob/97e68fb9134c3f9befdd5268d6119149f7973f80/src/js/components/DataTable/Header.js#L228 here this needs to be `if (groupBy?.onSelect)`

**Comment by jcfilben** [comment]
Closing since this was fixed by https://github.com/grommet/grommet/pull/5814 and is available in v2.19.1
