### ISSUE TITLE
Chartjs and invalid hook calls

### ISSUE THREAD

**Issue by careignition-cps** [grommet/grommet#5815]
Inputting a <Line data={data} options={options} /> into a grid component of material UI results in an invalid hook call. 

### Expected Behavior

Expected there to be a simple line graph in the grid with the example data taken from the chartjs github.

### Actual Behavior

Error: Invalid hook call

### URL, screen shot, or Codepen exhibiting the issue

const data = {
  labels: ['1', '2', '3', '4', '5', '6'],
  datasets: [
    {
      label: '# of Votes',
      data: [12, 19, 3, 5, 2, 3],
      fill: false,
      backgroundColor: 'rgb(255, 99, 132)',
      borderColor: 'rgba(255, 99, 132, 0.2)'
    }
  ]
};

const options = {
  scales: {
    y: {
      beginAtZero: true
    }
  }
};

export default function Function() {
  return (
    <Box>
       <Line data={data} options={options} />
    </Box>
  );
}

### Steps to Reproduce

See above.

### Your Environment

- Browser Name and version: Firefox
- Operating System and version (desktop or mobile): Windows desktop
- React dom and React have the same version number of 17.0.2
- Code works before the chart is added

**Comment by jcfilben** [comment]
Looks like this issue is related to Material UI and Chartjs. Feel free to reopen and clarify if it is indeed related to Grommet.
