### ISSUE TITLE
Incorrect display in meter graphs after 4 lines of data

### ISSUE THREAD

**Issue by osvaldovega** [grommet/grommet#582]
There is a problem with the meter graphs (circle/arc) when you try to add more than 4 labels/lines, the graphs start to locate the new circle lines at the center of the graph, then you are not able to see those data lines because is too small.

From 1 to 4 data lines (labels) everything is fine after 4 lines the graph start to display data incorrectly.

Here is an example.
http://codepen.io/osvaldo_vega/pen/ONYzBj?editors=1010#anon-login

**Comment by bryanjacquot** [comment]
@osvaldovega these meters support up to 4 values.  After that point, there's a warning displayed in the console.  
![image](https://cloud.githubusercontent.com/assets/6393696/16398497/0c9076a4-3c88-11e6-9f9a-1c8f420e6220.png)
