### ISSUE TITLE
[TS] Button 'active' theme prop no longer allows ButtonKindType keys

### ISSUE THREAD

**Issue by phinch** [grommet/grommet#5828]
### Expected Behavior

The Typing of the `active` key in `ButtonKindType` [here](https://github.com/grommet/grommet/blob/master/src/js/themes/base.d.ts#L180-L185) is:
```
  active?: ButtonKindType & {
    default?: ButtonKindType;
    primary?: ButtonKindType;
    secondary?: ButtonKindType;
    [key: string]: ButtonKindType;
  };
```

I interpret this as meaning that I could either pass button theme props for each button type, including for arbitrary types, as noted in [this comment](https://github.com/grommet/grommet/pull/5722/files#r735952176) from the author; and/or I could just pass button theme props at the top level, e.g.
```
active: {
  background: 'brand',
  color: 'text',
  primary: {
    background: 'red',
  },
  customButtonKindName: {
    background: 'white',
  },
  ...
}
```

### Actual Behavior

Instead, the top-level button props are no longer allowed to be passed. Passing
```
active: {
  background: 'brand',
  ...
}
```
gives the following error:
```
Type '{ background: string; color: string; }' is not assignable to type 'ButtonKindType & { [key: string]: ButtonKindType; default?: ButtonKindType | undefined; primary?: ButtonKindType | undefined; secondary?: ButtonKindType | undefined; }'.
  Type '{ background: string; color: string; }' is not assignable to type '{ [key: string]: ButtonKindType; default?: ButtonKindType | undefined; primary?: ButtonKindType | undefined; secondary?: ButtonKindType | undefined; }'.
    Property 'background' is incompatible with index signature.
      Type 'string' has no properties in common with type 'ButtonKindType'.
```

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-kgv10?file=/index.tsx

The error should appear in index.tsx at line 8

### Your Environment

- Grommet version: 2.19.0

**Comment by jcfilben** [comment]
Hi @phinch this was fixed in https://github.com/grommet/grommet/pull/5827 and is available on the stable branch or in the next release

**Comment by jcfilben** [comment]
I'm going to go ahead and close this since #5827 has been merged. Here is more information about using the [grommet stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) if you need to access to this fix before the next release is published.
