### ISSUE TITLE
Markdown component does not accept options.wrapper, overrides it with Fragment

### ISSUE THREAD

**Issue by danielm-hpe** [grommet/grommet#5832]
The Markdown component doesn't let you set the wrapper in the options, it forces it to be Fragment:
https://github.com/grommet/grommet/blob/96c2abd5da0c132db3225320b8c6938cca13f4f2/src/js/components/Markdown/Markdown.js#L52

The use case here was desiring to eliminate the margins on paragraphs so that there was not extra space above and below the markdown component, but maintain the ability to insert a gap inbetween paragraphs inside the Markdown component.

### Expected Behavior

With this code snippet I expected to get a markdown component with no margin on the paragraphs, and a gap inbetween the paragraphs.
```
<Markdown gap='small'
  options={{ wrapper: Box }}
  components={{ p: { component: Paragraph, props: { margin: 'none' } } }}>
  {'first paragraph\n\nsecond paragraph'}
</Markdown>
```

### Actual Behavior

Since the options.wrapper parameter is overridden with Fragment, instead a div is the wrapper and the gap is not observed.  I was able to create a workaround as follows to demonstrate the expected behavior:

```
import { compiler } from 'markdown-to-jsx';

...

<Box gap='small'>
  {compiler('first paragraph\n\nsecond paragraph', {
    wrapper: null,
    overrides: {
      p: {
        component: Paragraph,
        props: { margin: 'none' },
      },
    },
  })}
</Box>
```

### Steps to Reproduce

See code snippets above

### Your Environment

- Grommet version: 2.18.0
- Browser Name and version: chrome
- Operating System and version (desktop or mobile): windows 10

**Comment by MikeKingdom** [comment]
The `Markdown` component was modified so it will allow the `wrapper` in the options to override the `Fragment` used otherwise.

Note that no extra properties to the `Markdown` component are passed to the wrapper so if you want have a `Box` with a gap as a wrapper you can do it like this:
```jsx
const Wrapper = props => <Box gap="small" {...props} />;
...
<Markdown
  options={{ wrapper: Wrapper }}
  components={{
    p: { 
      component: Paragraph,
      props: { margin: 'none' },
    },
  }}
>
  {'first paragraph\n\nsecond paragraph'}
</Markdown>
```
