### ISSUE TITLE
Dropdown width is moving out of the container id JSX element is used as an option in select component.

### ISSUE THREAD

**Issue by anshu-kri** [grommet/grommet#5846]
### Expected Behavior
Dropdown width and select component width should be same.

### Actual Behavior
Dropdown width is taking the width of the JSX element. If a very long text is used, It is taking the width according to the text.

### Code sandbox link 
https://codesandbox.io/s/vibrant-smoke-x9ii3?file=/src/App.js

**Comment by jcfilben** [comment]
Not sure if this is a behavior we would want to change. This aligns with the native html select behavior: https://codesandbox.io/s/html-code-editor-forked-8niid?file=/index.html

**Comment by jcfilben** [comment]
This can be achieved by setting `dropProps={{ stretch: "align" }}` on Select. (https://codesandbox.io/s/sparkling-forest-3exj4?file=/src/App.js)

**Comment by anshu-kri** [comment]
Thanks @jcfilben
