### ISSUE TITLE
Can I allow a Drop to scroll offscreen?

### ISSUE THREAD

**Issue by chriszamierowski** [grommet/grommet#5851]
### Expected Behavior
If I'm using a `Drop` on a page that scrolls, and the `target` is positioned in a way that would mean the `Drop`'s natural layout wouldn't fit in the viewport (and it is unable to flip), I would expect the `Drop` to scroll with the `target` and be cut off by the viewport

![image](https://user-images.githubusercontent.com/2229721/146231455-a419e26b-f764-4f95-92b8-7055f620ad2b.png)

### Actual Behavior
The `Drop` gets "squished" by `max-height` in an attempt to stay visible. Browsing the docs, it's not clear whether this is the intended behavior, and/or if there's a way to prevent/opt out of it. It appears to be a side-effect of the [placement code](https://github.com/grommet/grommet/blob/master/src/js/components/Drop/DropContainer.js#L77).

![image](https://user-images.githubusercontent.com/2229721/146231364-94c13725-7c8e-4773-900a-484f49237fcf.png)

### URL, screen shot, or Codepen exhibiting the issue
[This Codesandbox](https://codesandbox.io/s/nameless-butterfly-5l9gg?file=/src/App.js) shows the behavior. When it is scrolled the `Drop` attempts to remain onscreen, and I'd like it to retain its layout and simply scroll off the screen

### Steps to Reproduce
1. In Codesandbox, scroll down
2. Notice image is distorted because the `maxHeight` of the `Drop` is changing, despite the `Box` having its height and width set.

### Your Environment

- Grommet version: 2.19.1
- Browser Name and version: Reproduced in Chrome 95 and Firefox 94, expected to repro across browsers
- Operating System and version (desktop or mobile): Mac OS 10.14

**Comment by jcfilben** [comment]
Hi @chriszamierowski you can prevent the drop from squishing you image by wrapping the image with a Box and setting a min height on the Box. See this [codesandbox example](https://codesandbox.io/s/runtime-butterfly-6hhkh?file=/src/App.js).

**Comment by chriszamierowski** [comment]
Thanks for the prompt reply @jcfilben. My codesandbox repro was a simplification of my real scenario, and I now realize it abstracted away an important detail: in my real scenario I am rendering a list of strings dynamically, so I do not know the `Drop` content's height. Regardless of my `overflow` choice, from your suggestion it seems like I would need to pick a `min-height` for the contents to prevent the squishing behavior, right? But I don't have a good value to use there (without rendering the content, measuring it, and then setting that value, which sounds like a mess) that prevents the `Box` from either being too tall for the content, or cutting it off and needing to overflow unnecessarily. [Here is an updated codesandbox](https://codesandbox.io/s/priceless-jones-x0ok2?file=/src/App.js) demonstrating this.

**Comment by jcfilben** [comment]
Going to go ahead and mark this as a bug. It doesn't feel like the Drop should be squishing content like that. 

Just an extra note to help narrow down the issue, content isn't getting squished when the text isn't dynamic (see this [codesandbox example](https://codesandbox.io/s/wandering-https-x4soh?file=/src/App.js)). Seems related to how Drop is calculating it's height when height is flexible like for an image or dynamically rendered text.

**Comment by B-Esmaili** [comment]
@chriszamierowski I checked out your first storybook and couldn't see the image squeezing. Have you made anu change to sandbox code?

**Comment by chriszamierowski** [comment]
> Thanks for the prompt reply @jcfilben. My codesandbox repro was a simplification of my real scenario, and I now realize it abstracted away an important detail: in my real scenario I am rendering a list of strings dynamically, so I do not know the `Drop` content's height. Regardless of my `overflow` choice, from your suggestion it seems like I would need to pick a `min-height` for the contents to prevent the squishing behavior, right? But I don't have a good value to use there (without rendering the content, measuring it, and then setting that value, which sounds like a mess) that prevents the `Box` from either being too tall for the content, or cutting it off and needing to overflow unnecessarily. [Here is an updated codesandbox](https://codesandbox.io/s/priceless-jones-x0ok2?file=/src/App.js) demonstrating this.

@B-Esmaili I'm not sure about the first sandbox. The one linked in this comment illustrates the problem better anyway. You can see that if the dynamic content is taller than would fit in the viewport, the Drop sets a `max-height`, artificially "squishing" the text, rather than allowing it to overflow and scroll.

https://user-images.githubusercontent.com/2229721/162013446-94e7854a-dbcd-4583-b534-7c93eeb7ae46.mp4

**Comment by B-Esmaili** [comment]
> Going to go ahead and mark this as a bug. It doesn't feel like the Drop should be squishing content like that.
> 
> Just an extra note to help narrow down the issue, content isn't getting squished when the text isn't dynamic (see this [codesandbox example](https://codesandbox.io/s/wandering-https-x4soh?file=/src/App.js)). Seems related to how Drop is calculating it's height when height is flexible like for an image or dynamically rendered text.

@jcfilben It seems to me the problem could be resolved with simply setting `shrink` to `false` in content `Box`. See my [sandbox](https://codesandbox.io/s/focused-davinci-00e4i4) and let me know what you is your openion. If you don't confirm this and you still c this is a bug, i'll go ahead and further investigate the problem.

**Comment by jcfilben** [comment]
@B-Esmaili nice solution! I tried it out with a few different cases and from what I can tell setting `flex={false}` is working well. I think we can close this but @chriszamierowski feel free to re-open if the `flex={false}` solution isn't working for your situation.

**Comment by chriszamierowski** [comment]
Interesting. Looks good to me as well, thanks!
