### ISSUE TITLE
 Drop-down size doesn't take length of the select field 

### ISSUE THREAD

**Issue by AlokKrSinha** [grommet/grommet#5852]
Given solution on issue #5846

dropProps={{
 stretch: "align"
}}

1. Text wrap when option too long 
2. Text doesn't have space between them, showing scroll in drop-down

But issue is with drop-down size, as you can see it doesn't take length of the select field : -
https://codesandbox.io/s/exciting-mcclintock-8xgo5?file=/src/App.js

![image](https://user-images.githubusercontent.com/89459752/146352697-e2e2c607-5dcf-4edd-acee-e7e7e2332a16.png)

**Comment by jcfilben** [comment]
Hi @AlokKrSinha `stretch: 'align'` only restricts the drop from having a greater width than the width of the DropButton or Select.  It doesn't control the min-width, just the max-width. If you want to have the drop be a specific width to match the DropButton or Select width then you can set the `width` of the Drop in `dropProps`.
For example:
```
dropProps: {
  width: "medium"
}
```

**Comment by jcfilben** [comment]
@AlokKrSinha just wanted to check if the above solution works for you and if this issue can be closed

**Comment by AlokKrSinha** [comment]
Thanks @jcfilben
