### ISSUE TITLE
Use better `key` for `List` with custom renderer functions?

### ISSUE THREAD

**Issue by Zodiase** [grommet/grommet#5854]
### Expected Behavior

I'm hoping I could specify `key` values without affecting rendering.

This is not the API I'd expect but just to illustrate one possibility and explain what I'm talking about:
```
<List primaryKey="_id">
    {(item) => <Box>{item.title}</Box>}
</List>
```
With this hopefully the rendered React Virtual DOM would be:
```
<li key="item-id-1">
    <Box>Item title 1</Box>
</li>
<li key="item-id-2">
    <Box>Item title 2</Box>
</li>
```

### Actual Behavior

I could use just `primaryKey` with an attribute name, which would use the attribute value as `key`. But it poses a couple problems:

1. If I use `primaryKey="_id"`, the `key` will be unique, but it will also be rendered. I don't need the `_id` to be rendered.
2. If I use `primaryKey="title"`, "title" being the attribute I'm trying to render, "title" is not guaranteed to be unique so can't be used as `key`.

I could also use the custom renderers but it seems in that case the `List` will always use `index` as the `key`, which is not ideal.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://user-images.githubusercontent.com/1815174/146513111-c969512d-0600-47b2-838e-e1d0764c8341.png)

### Steps to Reproduce

1. Use `List` with a custom renderer.
2. Try to use some ID attribute as the `key`.
3. See the `key` props of the list items are always the index numbers.

### Your Environment

- Grommet version: 2.19.1
- Browser Name and version: N/A
- Operating System and version (desktop or mobile): N/A

**Comment by jcfilben** [comment]
HI @Zodiase, not sure if I am following what you are trying to do here. The documentation for the `primaryKey` prop says, "When a string is supplied, it indicates the property in a data item object to use to get the primary content. If a function is supplied, it will be called with the current data item object and should return a React element that will be rendered as the primary content.". The `primaryKey` and `secondaryKey` should both be used to for the "primary content" and "secondary content" being displayed in your list. You can take a look at this [List/SecondaryKey](https://storybook.grommet.io/?path=/story/visualizations-list-secondary-key--secondary-key) story to see an example.

It sounds like you are wanting to attach a `key` prop to each item in the list, `primaryKey` shouldn't be used for this. Instead in your render function for each item in the list you can attach a key there based on the index.

**Comment by Zodiase** [comment]
@jcfilben 

> Instead in your render function for each item in the list you can attach a key there based on the index.

Which render function are you referring to? In my testing all the result returned by the render functions would eventually be wrapped in a `li` element (the `List__StyledItem` in my screenshots) which has the key prop. The `List__StyledItem` is rendered by the `List` component and the key is always the numeric index unless `primaryKey` is an attribute name.

In other words:
```
<List>
    {(item) => <Box key={item._id}>{item.title}</Box>}
</List>
```
still renders into Virtual DOM:
```
<List__StyledItem key="0">
    <Box key="item-0-id">{item.title}</Box>
</List__StyledItem>
<List__StyledItem key="1">
    <Box key="item-1-id">{item.title}</Box>
</List__StyledItem>
```

For the cases I've tested, having an attribute name for `primaryKey` is the only way to change the `key` prop for `List__StyledItem`.

Does that clarify the issue a bit?

**Comment by jcfilben** [comment]
Yes thanks for clarifying! Sorry I was misunderstanding how List was handling key. I went back and looked at the code for list that handles the key:
```javascript
const getKey = (item, index, primaryContent) => {
  if (typeof primaryContent === 'string') {
    return primaryContent;
  }
  return typeof item === 'string' ? item : index;
};

const getItemId = (item, index, primaryKey) => {
  const primaryContent = getPrimaryContent(item, index, primaryKey);
  return getKey(item, index, primaryContent);
};
```
I am going to go ahead and mark this issue with the "enhancement" label since we need to enhance the list code to allow the user to specify a custom key when generating custom children for list.
