### ISSUE TITLE
Cannot change "required" text in FormField

### ISSUE THREAD

**Issue by Yuktha99** [grommet/grommet#5858]
In the **FormField** component, if the **required** prop is used, there should be an ability to change the text - "requied".
The text is always "required"

### Expected Behavior

there should be an additional prop or existing required prop should accept a message to be displayed ( for example: "please select an input")

### Actual Behavior

The text is always "required"

### Your Environment
- Grommet version: 2.18.0

**Comment by halocline** [comment]
Hi @Yuktha99. I believe the prop you are looking for is Form's [messages prop](https://v2.grommet.io/form?c=BQSgBAvAfGDeBQYwGMD2A7AzgFzAbQDcBDAGwFcBTAGjEwuwDVTKBdSMAJQqOWwDoydAMrYi2CsFgBfEAG5EYAE70yi9GGAKkAHgBiqRQFstSMMXIUIsc5SkmkGAMIALIugDml2OgoAPRswUkDB0ARbAPv5MFiB2pqYYXKFWoMG09NGUkjJx8WAYQmQARoYAltgpsGaBYDJp0rnxhhSYmESemFawygCOZKXKACYAXGAARAAKJNx06dO8YG5gpegADmTYY1KNYFD2YHoGhrqlFCSDYOhEzRBjV81jYM7YhiT6irfi-gC0K+vYv0GjxIRCKZ1uADlrhRHr1+kM9nlTNoACp+bAASTWG2Wg0+6N+2IBpSBl2ht3uMLAAHpEXltNT3sdTuc6fFtAAhVC+MCDAYUXilDC3RSoADuj3cRFWt2afLIhjGbPpHI22AwYGwAE9VpYxphimVNmBVopSoYiIotWAQWCSLdCiVyo9afsdKrsOr1NrdSKWvRgaDwWMkgGacqdNSub5lQymXS5PApEA#messages). Give that a look and see if that meets your needs.

```
() => {
  const [value, setValue] = React.useState({});
  return (
    <Form
      value={value}
      onChange={nextValue => setValue(nextValue)}
      onReset={() => setValue({})}
      onSubmit={({ value }) => {}}
      messages={{required: "Please select an input"}}
    >
      <FormField name="name" htmlFor="text-input-id" label="Name" required>
        <TextInput id="text-input-id" name="name" />
      </FormField>
      <Box direction="row" gap="medium">
        <Button type="submit" primary label="Submit" />
        <Button type="reset" label="Reset" />
      </Box>
    </Form>
  );
}
```

**Comment by Yuktha99** [comment]
With the messages prop, the customised message is applicable for all FormFields within the Form
Is there any way to change it for a particular FormField within the form?

**Comment by halocline** [comment]
> With the messages prop, the customised message is applicable for all FormFields within the Form Is there any way to change it for a particular FormField within the form?

Yes, FormField's [validate prop](https://v2.grommet.io/formfield#validate) allows you to supply a set of validation rules and custom messages for each.

You also have the option to pass a message to FormField's [error prop](https://v2.grommet.io/formfield#error) and [info prop](https://v2.grommet.io/formfield#info).

I'd recommend exploring the [validate prop](https://v2.grommet.io/formfield#validate) approach first.

**Comment by Yuktha99** [comment]
Thanks!!! it worked,
I thought validate prop is invoked only after a value is entered, and not for "required" use case

**Comment by britt6612** [comment]
@Yuktha99 wondering if we reword out docs that might help a little for a better understanding
