### ISSUE TITLE
Add a "pause" prop to video compoent

### ISSUE THREAD

**Issue by devluked** [grommet/grommet#5864]
I would like to determine if a video should be stopped using a prop. What I want to achieve is if say I have 3 videos. I only want one to be able to be played at a time therefore when one video gets played any other videos should be paused.

Im trying to achieve this using state, but its not very possible, so is there a true/false prop to stop a video thats currently playing?

**Comment by rhian-cs** [comment]
Hello, may I give this issue a try?

**Comment by ericsoderberghp** [comment]
I would recommend just adding your own `ref` and calling the existing functions on the HTML DOM element: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/pause
I don't think anything needs to be changed in the grommet Video component.

**Comment by rhian-cs** [comment]
@devluked I created a [Codesandbox](https://codesandbox.io/s/blissful-sutherland-ly3jf?file=/src/index.tsx) testing @ericsoderberghp's suggestion and it seems to work fine. Does this work for you?

**Comment by jcfilben** [comment]
HI @devluked I'm going to go ahead and close this issue since a solution was provided above. Feel free to reopen if needed.
