### ISSUE TITLE
File name is not getting wrapped properly when I upload a file into a file Input component

### ISSUE THREAD

**Issue by mahanthi-arun-kumar** [grommet/grommet#5867]
Actual Behavior:
When I upload a file into a File Input component the file name is not  displaying as expected, it is going out of the container 

Expected behavior:
It should wrap the file name properly!

Steps to Reproduce

1. Upload an image with the name  ArubaInstant_Lupus_8.9.0.1_82011
2. Attached is the image which I uploaded
3. Attaching the screenshot of  how file input is displaying when I upload 

![ArubaInstant_Lupus_8 9 0 1_82011](https://user-images.githubusercontent.com/48381857/147205491-2368f6a1-2541-4722-9bfd-5484817556f8.jpg)
<img width="1280" alt="Screenshot 2021-12-22 at 4 20 28 PM" src="https://user-images.githubusercontent.com/48381857/147205765-808d8b67-f25e-47bd-b923-b91b3896fbe9.png">

- Grommet version:2.18.0
- Browser Name and version:Chrome  (96.0.4664.110 (Official Build) (x86_64))
- Operating System and version (desktop or mobile): desktop

**Comment by jcfilben** [comment]
Hi @mahanthi-arun-kumar can you try using the latest version of Grommet(v2.19.1)? I am not seeing this issue happen while using the most recent version.

Long file name with the FileInput/Custom story:
<img width="422" alt="Screen Shot 2021-12-23 at 9 17 34 AM" src="https://user-images.githubusercontent.com/54560994/147266621-be1f8174-c33e-40f3-9a9d-95ec76648f9f.png">

Long file name with the FileInput/Simple story:
<img width="424" alt="Screen Shot 2021-12-23 at 9 19 52 AM" src="https://user-images.githubusercontent.com/54560994/147266847-3532b2bc-4b25-4ed3-b24b-1719b86b106c.png">

**Comment by ericsoderberghp** [comment]
I am able to reproduce it with the latest grommet on Safari. Fix coming ...
