### ISSUE TITLE
Long bar meter legends not handled correctly

### ISSUE THREAD

**Issue by elliottkat** [grommet/grommet#587]
When using a bar Meter, if the legend text is too long, it is not handled correctly and will overwrite its value at the end of the bar.  I've included a screenshot of the issue where the processor type value is greater than the bar length.  There is also this:

http://codepen.io/dgennetten/pen/RavqMa

![proctypetile](https://cloud.githubusercontent.com/assets/18449274/15410839/36f7a7aa-1dd9-11e6-9c7b-5e8a2c3cfda4.PNG)

**Comment by ericsoderberghp** [comment]
This can be handled by positioning the Label and Value independently from the Meter itself. You can see an example here: http://grommet.us.rdlabs.hpecorp.net/meters/#18
