### ISSUE TITLE
MaskedInput with options won't allow for continued typing after match

### ISSUE THREAD

**Issue by mattoni** [grommet/grommet#5878]
### Expected Behavior

Should be able to continue typing after a match in a MaskedInput

### Actual Behavior

The dropdown options, when matched, stop additional input from happening. For example, if I have an input to match any number, but options of 30, 45, and 60, I can't input 301 though I can input 311.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-l16op?file=/index.js

### Steps to Reproduce

1. Enter 311 into the box, it works
2. Enter 301 into the box, observe you can only input 30.

### Your Environment

- Grommet version: 2.19.1
- Browser Name and version: 
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment]
Note: the MaskedInput is only preventing continued typing when the options are strings. If the options are numbers this issue isn't happening, see this codesandbox: https://codesandbox.io/s/grommet-v2-template-forked-rivgk?file=/index.js

**Comment by matheushahnn** [comment]
I would like to help with this bug, but I didn't get the expected behavior. 
Should be able to type a different key from the regex and options? I mean, it doesn't look right to type 31 if the options are 30, 45, 60 and 120.

**Comment by mattoni** [comment]
Basically I'm trying to use this as an input with some suggestions in the dropdown, that follows a pattern. e.g. I want to allow arbitrary number of minutes to be input, but also provide 'quick' suggestions via the dropdown.
