### ISSUE TITLE
Button styling is causing changes to button dimensions / icon alignment 

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5884]
### Expected Behavior

Icon should be vertically centered in a Button and the Button should retain its dimensions regardless of what theme is used.

### Actual Behavior

It seems that https://github.com/grommet/grommet/pull/5856 introduced some issues with icon alignment in Buttons (as can be seen in HPE themed Tag with onRemove: https://storybook.grommet.io/?path=/story/type-tag-onremove--on-remove&globals=theme:hpe).

### URL, screen shot, or Codepen exhibiting the issue

https://storybook.grommet.io/?path=/story/type-tag-onremove--on-remove&globals=theme:hpe

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: Stable
- Browser Name and version: Chrome Version 97.0.4692.71 (Official Build) (x86_64)
- Operating System and version (desktop or mobile): MacOS Big Sur

**Comment by ericsoderberghp** [comment]
I don't think
> the Button should retain its dimensions regardless of what theme is used
is true. In general, I think it is fine for a theme to customize styling in a way that might cause dimensions to change, for instance by changing the padding.

**Comment by jcfilben** [comment]
Reopening, #5885 fixed the issue on chrome but the icon alignment is still off in safari
