### ISSUE TITLE
MaskedInput when use options with the short string in last position blocks to continue typing

### ISSUE THREAD

**Issue by matheushahnn** [grommet/grommet#5899]
### Expected Behavior

Should be able to continue typing in MaskedInput when the smallest option appears in the final of options.

### Actual Behavior

The dropdown options, when matched, stop additional input from happening. For example, if I have an input to match any string, but options of 'aaa', 'aa', and 'a', I can't input 'aa' or 'aaa'.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-44g5f?file=/index.js

![image](https://user-images.githubusercontent.com/7703431/149638146-3cac77db-f311-46c7-8a91-7113331a972f.png)

### Steps to Reproduce

1. Fill the input with 'abc'

### Your Environment

- Grommet version: 2.16.2
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): OS(desktop)

**Comment by jcfilben** [comment]
Resolved in https://github.com/grommet/grommet/pull/5894
