### ISSUE TITLE
[feature request] Allow programmatic control of Tip compotent 

### ISSUE THREAD

**Issue by JackMF** [grommet/grommet#5900]
### Expected Behavior
I am developing a "Walk through" feature for grommet my app where each button is highlighted in turn and a Tool tip is given on how to use it

### Actual Behavior

The tool tip only displays on hover

**Comment by jcfilben** [comment]
Hi @JackMF I'm wondering if you could use a [Drop](https://v2.grommet.io/drop) instead of a Tip. This would allow you to control when the Drop is opened/closed vs the Tip only showing only on hover.

**Comment by jcfilben** [comment]
Hi @JackMF I am going to close this issue due to inactivity, but feel free to re-open if the above recommendation isn't working for you or you would like to discuss further.
