### ISSUE TITLE
Js Icon 

### ISSUE THREAD

**Issue by Marco1992sjc** [grommet/grommet#5901]
I'm having trouble displaying the javascript icon

"
import {
    Grommet as GrommetIcon,
    Html5, Css3, Js, Reactjs
  } from 'grommet-icons'
;"

< Js size='medium' color='accent-4' />

via 
Grommet Icons

![grommetiocn](https://user-images.githubusercontent.com/79483164/150024798-36f148c4-67fb-409f-bb2e-87f9b2ae1e24.png)

**Comment by MikeKingdom** [comment]
StyledIcon.js is trying to set both the stroke and fill to the `color` property and it's fill rules are overriding the stroke on the JS to match the background fill. This type of icon isn't really handled well by StyledIcon.

**Comment by Marco1992sjc** [comment]
< Js size='medium' color='plain' /> worked for me



Thank you!
