### ISSUE TITLE
Need a way to pass data-*attr to form field error message wrapper

### ISSUE THREAD

**Issue by venkatesh-elchuri** [grommet/grommet#5912]
### Expected Behavior
Need a way to pass **data-* attr**. attributes for the Form field error message span.

### Actual Behavior
We able to pass the data-*attr  to form field and test input's as well , but not be able to pass attributes for , Is their any way to do that. We are able to pass **messages** object to form but it only expects strings' s only. While doing unit testing we need that.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/30321668/150930042-ab5d47b0-f6bf-4bbd-aa74-cdc8010aebe7.png)

### Steps to Reproduce
Refer below codesandbox link
https://codesandbox.io/s/recursing-night-6sxrp

### Your Environment

Grommet version: latest
Browser Name and version: Chrome ,Latest
Operating System and version (desktop or mobile): Desktop, windows

**Comment by jcfilben** [comment]
Hi @venkatesh-elchuri in your unit test are you trying to test that the error message is shown when incorrect input is entered?

**Comment by venkatesh-elchuri** [comment]
> Hi @venkatesh-elchuri in your unit test are you trying to test that the error message is shown when incorrect input is entered?

Yes @jcfilben

**Comment by jcfilben** [comment]
Would something like this work for you?
``` javascript
  test('controlled onValidate custom error', () => {
    const onValidate = jest.fn();
    const errorMessage = 'One uppercase letter';
    const testRules = {
      regexp: /(?=.*?[A-Z])/,
      message: errorMessage,
      status: 'error',
    };

    const Test = () => {
      const [value, setValue] = React.useState({ test: '' });
      const onChange = React.useCallback(
        (nextValue) => setValue(nextValue),
        [],
      );
      return (
        <Form value={value} onChange={onChange} onValidate={onValidate}>
          <FormField name="test" validate={testRules}>
            <TextInput name="test" placeholder="test input" />
          </FormField>
          <Button type="submit" primary label="Submit" />
        </Form>
      );
    };
    const { getByText, container } = render(
      <Grommet>
        <Test />
      </Grommet>,
    );

    expect(container.firstChild).toMatchSnapshot();
    fireEvent.click(getByText('Submit'));
    expect(onValidate).toBeCalledWith(
      expect.objectContaining({
        errors: { test: errorMessage },
        infos: {},
      }),
    );
    expect(container.firstChild).toMatchSnapshot();
  });
  ```

**Comment by venkatesh-elchuri** [comment]
Thanks @jcfilben , It will works with snapshot testing. But when we want's to check error message either it was correct or not, we have to go to multiple children's level to check exact element text, So It would be easy to get element  if we have a attribute for  particular error message element

**Comment by venkatesh-elchuri** [comment]
Hi @jcfilben , This is not the exact case we are referring , We need an test attribute for the error element , to get the element by query , check what error message was it containing ,  not the snapshot match. 
So better, if we can able to pass the data* attributes would be helpful in this case.

**Comment by jcfilben** [comment]
Hi @venkatesh-elchuri I was thinking this snippet of code would work for testing the specific error message
```
expect(onValidate).toBeCalledWith(
      expect.objectContaining({
        errors: { test: errorMessage },
        infos: {},
      }),
    );
```

**Comment by halocline** [comment]
> Hi @jcfilben , This is not the exact case we are referring , We need an test attribute for the error element , to get the element by query , check what error message was it containing , not the snapshot match. So better, if we can able to pass the data* attributes would be helpful in this case.

@venkatesh-elchuri Out of curiosity, what test runner / testing library(s) are you using? Depending on that, we might be able to suggest some more elegant ways to query the error message.

Directly to your point though, the mechanism for passing a `data-*` to the error message is to format the message as a React node [docs](https://v2.grommet.io/formfield#error) instead of string. You can the pass your data attribute in that node's props like:
```
<FormField ...
error={
  <Text data-test-elem="my-test-elem">my error message</Text>
}
... 
/>
```

This seems like you'd be going out of your way to build a component to satisfy your tests though. That's why I ask about what testing library you are using.

**Comment by venkatesh-elchuri** [comment]
> > Hi @jcfilben , This is not the exact case we are referring , We need an test attribute for the error element , to get the element by query , check what error message was it containing , not the snapshot match. So better, if we can able to pass the data* attributes would be helpful in this case.
> 
> @venkatesh-elchuri Out of curiosity, what test runner / testing library(s) are you using? Depending on that, we might be able to suggest some more elegant ways to query the error message.
> 
> Directly to your point though, the mechanism for passing a `data-*` to the error message is to format the message as a React node ([docs](https://v2.grommet.io/formfield#error)) instead of string. You can the pass your data attribute in that node's props like:
> 
> ```
> <FormField ...
> error={
>   <Text data-test-elem="my-test-elem">my error message</Text>
> }
> ... 
> />
> ```
> 
> This seems like you'd be going out of your way to build a component to satisfy your tests though. That's why I ask about what testing library you are using.

We are using Cypres in one application , React Testing Library , Jest in one way. I understood the way of passing custom formatted error element node
But ,In our we are not passing any error message related info, If we have a required field, we are getting "Required" message on blur  event. So in this case we can't catch error element text.
https://codesandbox.io/s/recursing-night-6sxrp?file=/src/formField.js
![image](https://user-images.githubusercontent.com/30321668/157424791-e304c792-462d-4890-a1ec-914a830fe5f1.png)
![image](https://user-images.githubusercontent.com/30321668/157425214-aeb67502-3a01-43b1-b940-33abfd86bc2f.png)

**Comment by halocline** [comment]
I would suggest using React Testing Library's [getByText](https://testing-library.com/docs/queries/about/#priority) method to check whether the 'required' text has been rendered in the DOM. This most resembles what the end user is experiencing.  We are fans of Testing Library's [philosophy and approach](https://testing-library.com/docs/guiding-principles). Here are a few other [helpful resources](https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md#testing-your-code).

In addition, I would recommend @jcfilben's [suggestion](https://github.com/grommet/grommet/issues/5912#issuecomment-1061934622) to check whether `onValidate` has been called.

**Comment by venkatesh-elchuri** [comment]
Agree with you @halocline ,But my concern Today the error message is 'required' , But if in case future it was updated to something else, In this case my test case will get fail. 
If their is no possibility to add data* attributes, Can please suggest how we can verify this use case cypress that could helpful.
Thanks

**Comment by jcfilben** [comment]
Hi @venkatesh-elchuri I think if the error message were to change from 'required' to something else the expectation would be for the test to fail. If a change like this is intentional the test should be updated to reflect that.

**Comment by jcfilben** [comment]
Hi @venkatesh-elchuri I am going to mark this as closed but feel free to re-open if you would like to continue discussion on this or would like help brainstorming additional testing ideas that effectively test your desired behavior.
