### ISSUE TITLE
Not memoizing certain props for Drop causes unexpected scrolling on re-render

### ISSUE THREAD

**Issue by phinch** [grommet/grommet#5928]
Hi! This isn't exactly a bug per se, but it was kind of strange behavior with the Drop component that took me a while to debug on my end, so figured I'd share in case there is something that can be done about it.

### Expected/Actual Behavior

The two modes of behavior can be found [in this codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-vv7jz?file=/index.js). There's more explanation within the CodeSandbox; but basically, if the drop content has scroll, not memoizing the `align` object prop passed into the `Drop` component causes the scroll of the Drop to reset to the top when it is re-rendered; when `align` is memoized (or not provided), this does not happen. I believe (but have not fully confirmed) that this is due to [this dependency array](https://github.com/grommet/grommet/blob/master/src/js/components/Drop/DropContainer.js#L295-L305) triggering the associated `useEffect` on each render, since `align` is an object and does not pass a shallow equality test when it is not memoized. I also encountered similar behavior with `onClickOutside` not being call-backified, which is why I think more strongly that it's connected to that dependency array.

I believe the memoized behavior is what is expected, so there's nothing inherently broken about the Drop. I just feel like this behavior is a little bit cryptic, and is a common pitfall since `align` is commonly a simple object that might not be frequently memoized. There also isn't really any documentation that I could find that explains that the consumer should take care to memoize some/all props being passed into the Drop - instead, I had to dig through the source code to find why my usage of the component was behaving unexpectedly. I think it would be cool if this Drop API were more intuitive, either through a code change or a documentation change - but I also can see the argument for just assuming that the user is memoizing and callbackifying props that are passed to Grommet more indiscriminately than I was. 

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-vv7jz?file=/index.js

### Steps to Reproduce

Steps are outlined in the CodeSandbox above

### Your Environment

- Grommet version: 2.19.0
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
Closed via documentation updates.
