### ISSUE TITLE
Allow changing the opacity of the text inside a disabled select.

### ISSUE THREAD

**Issue by romanpastu** [grommet/grommet#5938]
### Expected Behavior
There should be an option to change the opacity of the selected value in the disabled select

### Actual Behavior
There is no way to change the opacity of the value in a disabled select

### URL, screen shot, or Codepen exhibiting the issue
In this codesandbox u can see that the text is disabled and there is no way to change its opacity (I only need to change the text one to opacity 1)

https://codesandbox.io/s/keen-murdock-ltuhr?file=/src/Select.js:379-806  -> Navigate to /select

![image](https://user-images.githubusercontent.com/43568511/153242554-bae2b6f7-d9cf-41d5-9de0-d6817c7d3c48.png)

**Comment by jcfilben** [comment]
Closing, feel free to re-open if there are still questions or issues with this
