### ISSUE TITLE
DateInput Icon Issue

### ISSUE THREAD

**Issue by versoworks** [grommet/grommet#5948]
The latest Grommet v2.20.1 appears to break past behaviour regarding the DateInput's icon styling. We've been using the DateInput's `inputProps` to style the icon, per @ShimiSun's [advice here](https://stackoverflow.com/a/65827166/15072634). The same code now renders the default icon in addition to the icon specified via `inputProps` as [demonstrated here](https://codesandbox.io/s/bold-torvalds-3cfvi?file=/src/index.tsx).

**Comment by jcfilben** [comment]
Hi @versoworks this issue was fixed in https://github.com/grommet/grommet/pull/5911 and will be available in the next release. If you need it sooner you can use the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F).

**Comment by versoworks** [comment]
Hi @jcfilben thank you.
