### ISSUE TITLE
Am I getting hot reload wrong?

### ISSUE THREAD

**Issue by goloroden** [grommet/grommet#595]
### Steps to reproduce

- Create a sample application using `grommet init`
- Run `gulp dev`
- Make a change to `src/js/index.js`

### Expected result

- The browser hot reloads the part of the application that was changed

### Actual result

- The browser shows a message `App hot update` in the upper left corner, but nothing else happens.

Am I getting hot reload wrong, or doesn't it work as expected?

**Comment by alansouzati** [comment]
This is a known issue with react-hot-loader and ES6 classes. See this issue in `grommet-toolbox`

https://github.com/grommet/grommet-toolbox/issues/3

**Comment by alansouzati** [comment]
Fixed in grommet-toolbox
