### ISSUE TITLE
DataTable placeholder should be visible below header

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#5967]
### Expected Behavior

If placeholder is provided to DataTable, it should be visible and retain proper styling underneath the DataTable header.

### Actual Behavior

The content around the placeholder doesn't always respect the placeholders height / shrinking the DataTable can cause the placeholder to render behind the header. 

### URL, screen shot, or Codepen exhibiting the issue

One example is when DataTable is wrapped in a Box with overflow="auto", the placeholder is hidden behind a very small scrollable region:
https://codesandbox.io/s/datatable-placeholder-bug-i8d8j?file=/index.js

When shrinking browser window, the placeholder is not fully visible:
<img width="685" alt="Screen Shot 2022-02-25 at 2 33 35 PM" src="https://user-images.githubusercontent.com/12522275/155816115-dd32c6a2-debf-41ea-88fa-7a9e9543facc.png">

### Steps to Reproduce

1. Codesanbox example above.

### Your Environment

- Grommet version: 2.21.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): MacOS

**Comment by MikeKingdom** [comment]
The placeholder is implemented via a `<caption>` . Normally the caption is rendered above the table but it is styled to be `position: absolute`. As a result, it doesn't contribute to the size calculation of the table. That means any table that doesn't specify a size may not leave space for the placeholder.

**Comment by MikeKingdom** [comment]
Fixed by https://github.com/grommet/grommet/pull/5987
