### ISSUE TITLE
Table component does not support responsiveness in IE

### ISSUE THREAD

**Issue by aiqingli** [grommet/grommet#597]
Table component does not seem to support responsiveness in IE. In chrome, the content of the cell wrap when the screen size decreases, but in IE, it does not, it just cut off on left and right side.

![tableie1](https://cloud.githubusercontent.com/assets/12969801/15548300/be119bba-2275-11e6-8eb5-eac7842fcd0c.JPG)
![tableie2](https://cloud.githubusercontent.com/assets/12969801/15548299/be10094e-2275-11e6-9440-78570fef2944.JPG)

**Comment by bryanjacquot** [comment]
@aiqingli we fixed several IE issues in the most recent release of Grommet. (https://github.com/grommet/grommet/releases/tag/v0.6.7) can you verify this is still an issue?

**Comment by bryanjacquot** [comment]
Closing for now, please follow-up if this is still an issue.
