### ISSUE TITLE
Layer close breaks in Edge

### ISSUE THREAD

**Issue by michaelgilley** [grommet/grommet#598]
Layer breaks in Edge when closing and the `_originalFocusedElement` is not focusable. See https://github.com/grommet/grommet/blob/1a367577ad661e656c50803d3a95413cff16b1f3/src/js/components/Layer.js#L168 for the offending line.

Thanks!

**Comment by michaelgilley** [comment]
Reproducible when you have an SVG icon inside a button that opens the layer. Clicking on the button works but when clicking on the SVG icon an error is thrown.

**Comment by alansouzati** [comment]
thanks for debugging this further. this information helps when we try and implement a fix for it. i will try and take a look on this soon.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/90b80263d35fc11112d776706cb17689f1b71bb2
