### ISSUE TITLE
[Image] throws console warnings when `fallback` prop defined AND `onError` prop undefined

### ISSUE THREAD

**Issue by apawson** [grommet/grommet#5984]
In the following scenario (when `fallback` is defined and `onError` is not)...

```js
<Image
  fill="horizontal"
  fallback={fallbackImage}
  src={imgSrc}
  alt="test"
  // onError={onError}
/>
```

I see the following `console` warning:

> Warning: Expected `onError` listener to be a function, instead got a value of `string` type.

### Expected Behavior

No console warnings/errors should be generated in this scenario.

### Actual Behavior

I see the following `console` warning:

> Warning: Expected `onError` listener to be a function, instead got a value of `string` type.

### Steps to Reproduce

See above. (Also see: https://github.com/grommet/grommet/blob/master/src/js/components/Image/__tests__/Image-test.tsx#L114)

### Your Environment

- Grommet version: `2.21.0`
- Browser Name and version: Google Chrome `Version 98.0.4758.109 (Official Build) (arm64)`
- Operating System and version (desktop or mobile): `desktop`

**Comment by jcfilben** [comment]
Hi @apawson I put together a [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-98is8e?file=/index.js) that has an image with `fallback` defined but without `onError` and I am not seeing the warning. Could you send a codesandbox that reproduces the warning?

**Comment by jcfilben** [comment]
I'm going to go ahead and close this but feel free to reopen and share a codesandbox example if you are still experiencing the issue
