### ISSUE TITLE
In Form Select component, dropdown values should right align for numeric values.

### ISSUE THREAD

**Issue by anshu-kri** [grommet/grommet#6019]
### Expected Behavior
For Form Select component, need to align dropdown options to the right, only for numeric values.

### Actual Behavior
The options are left aligned by default. There are themes in select component to extend from and give the align as right.

1. select.options.container - This accepts an object. Using this we can change the alignment as `{ align: "end"}`, but since this change is needed only for numeric values so this has to be done conditionally. Since there is no function available for this, Hence this wont work.

Either all the options are left aligned or right aligned

### URL, screen shot, or Codepen exhibiting the issue
![image](https://user-images.githubusercontent.com/96100426/159899586-912623f0-1c7e-4e81-a094-36791ee898c2.png)

https://codesandbox.io/s/grommet-v2-template-forked-0mp4ji?file=/index.js

### Your Environment

- Grommet version: 2.21.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows and Desktop

**Comment by jcfilben** [comment]
Hi @anshu-kri you can customize how items will render in the options list with the `labelKey` prop. From there you can conditionally render and item with align="start" or align="end" based on if it it a number or not. I put together a codesandbox example to demonstrate: https://codesandbox.io/s/grommet-v2-template-forked-sdxkwg?file=/index.js

**Comment by anshu-kri** [comment]
Thanks @jcfilben

**Comment by jcfilben** [comment]
Marking this as closed feel free to re-open if needed.
