### ISSUE TITLE
Select - clear button showing even when no options are selected

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6039]
### Expected Behavior
Select should only show clear options if there are options currently selected.

### Actual Behavior
Select with clear shows clear options even when there are no options selected.

### URL, screen shot, or Codepen exhibiting the issue
<img width="326" alt="Screen Shot 2022-03-30 at 4 30 39 PM" src="https://user-images.githubusercontent.com/54560994/160941755-7a8a4bc4-0090-413e-b517-383222c3eced.png">

### Steps to Reproduce
Issue is reproducible in this storybook example: https://storybook.grommet.io/?path=/story/input-select-clear--clear
1. Open the select and choose an option
2. Unselect the option so that no options are selected
3. Open the drop again and the "Clear selection" button will still show up

### Your Environment

- Grommet version: 2.21.0
- Browser Name and version: chrome
- Operating System and version (desktop or mobile):

**Comment by matheushahnn** [comment]
Hey, can you assign to me this one, please?

**Comment by jcfilben** [comment]
> Hey, can you assign to me this one, please?
Yes, just assigned you

**Comment by jcfilben** [comment]
Closing since #6042 has been merged
