### ISSUE TITLE
List selected-item. How is it supposed to work? 

### ISSUE THREAD

**Issue by Waize** [grommet/grommet#604]
In the documentation is wirtten that selected represents the current selected item.

Here is my Codesnippet:
[...render...]  
`let selectedItem;

    return (
              <List selectable selected={selectedItem}>
                {versionList}
              </List>
)`

But the value of "selectedItem" is always undefined. 

How can I get the value of the selected Item?

**Comment by alansouzati** [comment]
`selectedItem` is am optionally number where the index is the currently selected item (default is 0). you control the changes on this property.

Usually you have a state where you can control the activeIndex that starts with 0.

```
export default class Test extends Component  {
  constructor () {
    super();
    this.state = {
      activeIndex: 0
    };
  }

  render () {
    return (
      <List selectable selected={this.state.activeIndex}>
        {versionList}
      </List>
    );
  }
```

I'm not sure which logic you have to increment/decrement the active index for the list.

Let me know if there is anything else we can help with.

**Comment by Waize** [comment]
thanks for the answer, it works!
