### ISSUE TITLE
Custom Calendar selecting the wrong date

### ISSUE THREAD

**Issue by chriswgreen-lineup** [grommet/grommet#6068]
### Expected Behavior

Not using useSelect When selecting a date, the isSelected should return true for the correctly selected date. 

### Actual Behavior

Inconsistently selecting the wrong date (typically selecting the previous date). 

### URL, screen shot, or Codepen exhibiting the issue

https://storybook.grommet.io/?path=/story/visualizations-calendar-custom-day--custom-day-calendar

#### Note highlight on 14th
<img width="807" alt="image" src="https://user-images.githubusercontent.com/97097648/163396670-af3e734f-05fc-46dd-a8b7-4d0ae11fd887.png">

#### Console log from a custom calendar

<img width="680" alt="image" src="https://user-images.githubusercontent.com/97097648/163397431-ea1e4a0f-1f6c-41ee-a995-b19a27cb7c46.png">

### Steps to Reproduce

1. Navigate to the above link
2. Select any date

### Your Environment

- Grommet version: 2.22.0
- Browser Name and version: Version 100.0.4896.88 (Official Build) (arm64)
- Operating System and version (desktop or mobile): Desktop

**Comment by taysea** [comment]
Fixed by https://github.com/grommet/grommet/pull/6214. This is available in v2.25.1
