### ISSUE TITLE
Grommet is broken with the latest create-react-app and React 18

### ISSUE THREAD

**Issue by irSteve** [grommet/grommet#6075]
First issue: 
- Using the lastest create-react-app, which uses the latest React, Grommet cannot install via npm without the --legacy-peer-deps
- This forces us to use that flag with just about every subsequent, non-grommet package we use
- It is unclear how this will impact continued development of our project

Second issue: 
- Grommet Nav cannot accept child elements in a typescript environment due to an issue in the type declaration
- If child elements are provided (e.g. - Grommet Anchor), the application fails to execute with an error 
- A [simple example from the Grommet Nav documentation](https://storybook.grommet.io/?path=/story/controls-nav-simple--simple) will not run. 

### Expected Behavior
- Grommet supports the latest create-react-app and React environment
- Grommet components function per Grommet documentation

## Install Grommet after running create-react-app --template typescript
```
pathnext@PathNexts-MacBook-Pro grommetsidebartest % npm install grommet  grommet-icons styled-components --save                               
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: grommetsidebartest@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.1 || ^17.0.0" from grommet@2.22.0
npm ERR! node_modules/grommet
npm ERR!   grommet@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/pathnext/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pathnext/.npm/_logs/2022-04-18T22_20_57_422Z-debug-0.log`
```

## App run error
```
  You can now view grommetsidebartest in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.86.30:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

webpack compiled successfully
ERROR in src/App.tsx:15:8
TS2322: Type '{ children: Element[]; pad: string; }' is not assignable to type 'IntrinsicAttributes & BoxProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & BoxProps'.
    13 |   return (
    14 |     <Grommet>
  > 15 |       <Nav pad="large">
       |        ^^^
    16 |         {items.map((item) => (
    17 |           <Anchor href={item.href} label={item.label} key={item.label} />
    18 |         ))}
```
### Steps to Reproduce

1. npx create-react-app --template typescript <projectName> 
2. npm install grommet grommet-icons styled-components --save (will fail)
3. npm install grommet grommet-icons styled-components --save --legacy-peer-deps (kinda works)
4. npm start (you will see the Nav error where type declarations prevent adding children to a Nav).

<img width="842" alt="Screen Shot 2022-04-18 at 4 11 47 PM" src="https://user-images.githubusercontent.com/19754087/163891378-0547d4ac-edf0-4368-b6a5-c9f2645edf1c.png">

### Your Environment

Macbook Pro, latest MacOS, Visual Studio Code

- Grommet version:
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment]
Hi @irSteve can you try using the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) of Grommet? Our React 18 support hasn't been published in a release yet and is currently only available on the stable branch.

**Comment by jcfilben** [comment]
Update: [Grommet v2.23.0](https://github.com/grommet/grommet/releases/tag/v2.23.0) has been released and supports React 18. I am going to go ahead and close this issue but feel free to create new issues if you run across any problems in the future using React 18 with Grommet.
