### ISSUE TITLE
datatable truncation not working in chrome

### ISSUE THREAD

**Issue by stephanpelikan** [grommet/grommet#6081]
datatable width render property <Text truncate> should show ellipses in all browsers

I want a table having 3 columns. first and third are fixed size. second should truncate content. table should scoll only vertically. This works in Firefox but not in Chome.

In Firefox the 2nd column shows ellipses but in Chrome the table is expanded to a size that all context is shown without truncation.

### Steps to Reproduce

Open https://storybook.grommet.io/?path=/story/visualizations-datatable-multiple-pins--multiple-pins in Chrome and in Firefox. 

In the other hand the your sandbox adopted works in both browsers: https://codesandbox.io/s/still-sun-om9e3b?file=/src/DataTable.js

What's  the difference? Unfortunatly, my app behaves like storybook not like sandbox.

### Your Environment

- Grommet version: 2.22.0
- Browser Name and version: Chrome Version 100.0.4896.127 (Offizieller Build) (64-Bit)
- Operating System and version (desktop or mobile): Windows desktop

**Comment by stephanpelikan** [comment]
I figured out that setting the size of that 2nd column makes the truncation work. but this is exactly what I don't want to do. I want this colum to expand to the available space but truncate it's content if not enough space is available. additionally, setting any size wastes space on mobile devices bacause I need to fit it the smallest display but on (usually) bigger screens that makes a lot of whitespace.

**Comment by stephanpelikan** [comment]
OK, now I got it! This works:

    <Box width='100%' overflow="vertical">
      <DataTable
          size='100%'
          columns={columns}
          step={itemsBatchSize}
          onMore={() => loadData()}
          data={data} />
    </Box>

where first column has size:'5rem', second column has no size property and third has size:'4rem'. but actually the size of columns does not change the effect.

but one need to set size='100%' although docs says this property is only about the height of the table: https://v2.grommet.io/datatable#size

this is from the storybook but doesn't work in Chrome:

    <Box align="center">
    <Box height="medium" width="600px" overflow="auto">
      <DataTable
          columns={columns}
          step={itemsBatchSize}
          onMore={() => loadData()}
          data={data} />
    </Box>
    </Box>
    
Is this a bug or intended behavior? If no bug, maybe you can adopt storybook and docs to reflect this? I guess this would save time to others ;-)

**Comment by jcfilben** [comment]
Hi @stephanpelikan, thanks posting updates on this issue with your findings, much appreciated! This looks like a bug to me. I think the truncate behavior should work in chrome without having to set `size='100%'`. For others looking at this issue I created a [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-ji0kiu?file=/index.js) where you can see truncate is no longer working in chrome when you comment out `size='100%'`.

**Comment by britt6612** [comment]
So after looking at this a little further I believe this is a bug in Firefox. Both Safari and Chrome allow the content to expand (in which you do not see the truncation) this actually makes sense given that the browser is letting the content determine the size. When the `size` prop is used this puts a 
```
    display: table;
    width: 100%;
    table-layout: fixed;
```
 
This gets put on the `DataTableRow` which then the table’s layout ignores the content and instead uses the table’s width, any specified width of columns, and border and cell spacing values. The column values used are based on widths defined on columns or cells for the first row of the table.

Im thinking that FireFox is doing this even without setting the `size` prop which would be incorrect the content should drive the size. Going to look into a solution for this to be correct in FireFox
