### ISSUE TITLE
FileInput cursor has split personality

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#6083]
https://grommet.slack.com/archives/C04LMJWQT/p1650324980596959?thread_ts=1650324980.596959&cid=C04LMJWQT

### Expected Behavior

When hovering over FilInput box the cursor ought to be the same icon everywhere within the box.

### Actual Behavior

Hover from left to right and the cursor icon changes 6 times.

### Steps to Reproduce

Go to https://v2.grommet.io/fileinput and hover the mouse from left to right. The cursor icon changes 6 times.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment]
Fixed in https://github.com/grommet/grommet/pull/6154
