### ISSUE TITLE
[Question] How to easily npm link grommet

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [grommet/grommet#6091]
Hi,

We are currently working on a React App which is managed in a lerna monorepo.
During some development process, we would like to modify code from "Grommet" dependency and reload our app with this new modified dependency.

What we successfully did : 
1. Fork and clone `grommet` github repository
2. `yarn build` the project
3. Go into `dist` and do `npm link`
4. Go into our project and do `npm link grommet`
5. Create an alias to `react` in our main project to avoid mixed React version (as Grommet use it with Peer dependency)

This is working fine, however each time we modify the grommet project, we have to do : 

1. Stop the application
2. Go to `grommet` project
3. `yarn build` the project
4. Go into `dist` and do `npm link`
5. Relaunch the application

Do you have any solution in order to do this faster ? Is there any way to directly use `grommet` source and enable  some hot reloading ?

Thanks in advance for your help.
Yours faithfully,
LCDP

**Comment by jcfilben** [comment]
Hi @AntoineDuComptoirDesPharmacies unfortunately I am not aware of a better way to achieve this

**Comment by jcfilben** [comment]
Closing, if anyone has a better solution feel free to comment here.
