### ISSUE TITLE
Allow Layer component to be rendered into a different target container

### ISSUE THREAD

**Issue by shen6653** [grommet/grommet#6100]
Currently, Layer component is always rendered under 'body' tag. There is a 'target' property but it changes layer alignment only, not changing where it's rendered to. In order to render Layer under shadow-root, we need an enhancement to Layer component to allow Layer to be rendered into different target container that's different from 'body'.

### Expected Behavior
Add a new property to pass a target container, then have Layer rendered into that target container. See https://reactjs.org/docs/portals.html

### Actual Behavior
This option is not provided today. Layer is always rendered to 'body'.

### URL, screen shot, or Codepen exhibiting the issue
This is an enhancement request, but a bug.

### Steps to Reproduce
N/A

### Your Environment
N/A

**Comment by shen6653** [comment]
Looks like Layer component is already using React Portal https://github.com/grommet/grommet/search?q=createPortal
Can we make Layer container to be a property of Layer component?

**Comment by ericsoderberghp** [comment]
I'm supportive of exploring adding this capability to `Layer`. Are you thinking the property would be called `container` and used when creating the portal within Layer? Would it have any connection to the existing `target` property? For instance, would the `target` need to be inside the `container` or could they be completely independent?

Alternatively, I'm wondering if it would be better to add `container` to the `Grommet` component, which would cause all portals to be rendered inside that container rather than having to specify it for each one. Would that work?

**Comment by shen6653** [comment]
Thanks Eric!

> Are you thinking the property would be called container and used when creating the portal within Layer?
Yes.

> Would it have any connection to the existing target property? For instance, would the target need to be inside the container or could they be completely independent?
Since <code>target</code> and <code>container</code> (not exposed today) are currently independent, I think it's better to keep them independent as they are today.

> Alternatively, I'm wondering if it would be better to add container to the Grommet component, which would cause all portals to be rendered inside that container rather than having to specify it for each one. Would that work?
This is a great idea. It might be better this way.

**Comment by ericsoderberghp** [comment]
Haha, it looks we've already got this: https://v2.grommet.io/grommet#containerTarget Can you give it a try?

**Comment by shen6653** [comment]
Ha. Looks like exactly what we need! Will try it out and let you know.

**Comment by shen6653** [comment]
Hi Eric, Looks like Grommet's <code>containerTarget</code> property has worked for our purpose to render portal under a Shadow DOM. A big step further to the solution we want. However, the layer/modal onClick event is no longer being captured and handled.

**Comment by ericsoderberghp** [comment]
Can you either file a new issue for that or revamp this issue towards that?

And, we welcome pull requests :)

**Comment by shen6653** [comment]
Sure. Sounds good.
