### ISSUE TITLE
The LayerForm’s first and second control button layout is wrong in IE11

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#611]
These two buttons are showed one by one, this is wrong. Change the browser’s size, the layout will be back to normal status.
![7](https://cloud.githubusercontent.com/assets/16797825/15699046/99e1adf2-27fc-11e6-8471-3ebbe5447a13.jpg)
![8](https://cloud.githubusercontent.com/assets/16797825/15699053/a911717c-27fc-11e6-97e0-3c9ddaca28c2.jpg)

**Comment by christinHP** [comment]
@DerekAhn 
Hi Derek,

I disagree you close 611 and 612, the grommet issue is still there and you haven’t fix it.

Please see the attached file, the attribute compact={false} doesn’t work. The LayerForm provide onSubmit and secondaryControl, then these two buttons layout should be work well with compact={false}.

<LayerForm title="Certificate" submitLabel="Trust"
                 secondaryControl={dontTrustControl}
                 onClose={this.props.onDontTrust} onSubmit={this._onSubmit} compact={false}>

**Comment by christinHP** [comment]
@DerekAhn The certificate LayerForm compact={false} works well in chrome and firefox, but it doesn’t work in IE 11. So the grommet LayerForm has browser compatibility problem.

**Comment by DerekAhn** [comment]
@christinHP I believe this  coincides with issue #612.
