### ISSUE TITLE
Grid.available becomes false negative in SSR environment , and results in opting out of using Grid.

### ISSUE THREAD

**Issue by B-Esmaili** [grommet/grommet#6116]
### Expected Behavior

 In `SSR` environments like `next-js` , `Grid` should be applicable.

### Actual Behavior

`Grid` is not applicable because of `Grid.available` evaluating to false

 [Here](https://codesandbox.io/s/lucid-feather-unzm23?file=/pages/index.js) is link for the sandbox code with a `DataChart` , when you refresh the page the chart no more uses grid for layout.

### Steps to Reproduce

Just open the provided Sandbox and refresh the page.

### Your Environment

- Grommet version: 2.22.0
- Browser Name and version:Chrome latest
- Operating System and version (desktop or mobile): Ubuntu 22

**Comment by ericsoderberghp** [comment]
I'm wondering if we should remove `Grid.available`, given that Internet Explorer support is being dropped.
