### ISSUE TITLE
Create suggestion in Select 

### ISSUE THREAD

**Issue by britt6612** [grommet/grommet#6118]
It would be great if there was an option in the Select to create a new suggestion when searching. It would add a new `string` to the options in the select. This could be done by typing in the search and pressing `enter` or click on the `create new`
### Expected Behavior
Create a new option for Select. The `keyboard` behavior is that the user could type a new option and then press `enter` to select and create that option. The select would have a `Create "string"` for the user to also click on and select the option

### Actual Behavior
This behavior is not an option as of now

### URL, screen shot, or Codepen exhibiting the issue

see the image for intended behavior 

https://design-system.hpe.design/components/tag#assigning-name-value-tags

<img width="408" alt="Screen Shot 2022-05-09 at 2 54 27 PM" src="https://user-images.githubusercontent.com/42451602/167496828-401364f5-f76f-4453-ad70-7f64a0dea689.png">

**Comment by CopyJosh** [comment]
There is an example of implementing something similar in Storybook

https://storybook.grommet.io/?path=/story/input-select-create-option--create-option

I've had a hard time replicating this example without defining the defaultOptions outside of the component, and even greater difficulty with a multiple select...

**Comment by jcfilben** [comment]
Closing, this enhancement is already supported

**Comment by ericsoderberghp** [comment]
While there is a means of building this as shown in the storybook story, I think the intent was to simplify this situation by building it in more. For example, something like:
`<Select onSearch={...} onCreate={(text) => {...}} />` would simplify the caller's code by not having to maintain a special option in the options array.
