### ISSUE TITLE
The LayerForm’s width is wrong in IE11

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#612]
Please see 3 pictures, the display monitor and browser’s size is same, but the width for the LayerForm’s layout is really different.

![7](https://cloud.githubusercontent.com/assets/16797825/15699091/ecc05e56-27fc-11e6-9be6-277a8f8b8984.jpg)
![8](https://cloud.githubusercontent.com/assets/16797825/15699092/ee4fdaa8-27fc-11e6-8af6-721976b80ed9.jpg)
![9](https://cloud.githubusercontent.com/assets/16797825/15699093/effde28c-27fc-11e6-8c11-ffe119b7d681.jpg)

**Comment by DerekAhn** [comment]
@christinHP Is the middle picture a different form from the rest? It could be that the grommet's Form component attr is not set or set to false, i.e. `<Form compact={false}/>`.

**Comment by christinHP** [comment]
Hi Derek,

I disagree you close 611 and 612, the grommet issue is still there and you haven’t fix it.

Please see the attached file, the attribute compact={false} doesn’t work. The LayerForm provide onSubmit and secondaryControl, then these two buttons layout should be work well with compact={false}.

<LayerForm title="Certificate" submitLabel="Trust"
                 secondaryControl={dontTrustControl}
                 onClose={this.props.onDontTrust} onSubmit={this._onSubmit} compact={false}>

**Comment by christinHP** [comment]
@DerekAhn

**Comment by christinHP** [comment]
@DerekAhn The certificate LayerForm compact={false} works well in chrome and firefox, but it doesn’t work in IE 11. So the grommet LayerForm has browser compatibility problem.

**Comment by DerekAhn** [comment]
Hi @christinHP,

Sorry for the delayed response, I typically do not work on the weekends. Also it appears the ip address provided is no longer being hosted any more. However, I did mock up a form utilizing the component <LayerForm/>, and it appears okay in my windows 10 ie11. Simply but utilizing the code snippet that I suggested of nesting <Button/>'s in a <Box/> component.


```
<Box direction="row">
  <Button
    primary={true}
    label="trust"
    onClick={()=>{}} />

  <Button
    label="Don't Trust"
    onClick={()=>{}} />
</Box>
```

I hope that this helps. If I am understanding correctly, you are specifically speaking towards the layout design of `grommet-templates/LayerForm`, this is not apart of grommet core, and should not be changed according to your projects design. I assure you that grommet-template's <LayerForm/> is merely just a simple abstraction of grommet-core's <Layer/>, and <Form/> components. I think if your project is calling for a specific design that is not adherent to the nature of grommet-template's <LayerForm/> I would encourage you to compose the layout with grommet-core's <Layer/>, <Form/>, <Box/>, and <Button/> components.

Please let me know if you need me to clarify more, but I assure you that this is not a bug in grommet-core nor in grommet-templates. 

Mahalo,
Derek
