### ISSUE TITLE
Toggling CheckBox is not updating the input element's checked attribute

### ISSUE THREAD

**Issue by danielm-hpe** [grommet/grommet#6123]
The CheckBox component initially renders with an input whose `checked` attribute matches the expected.  However toggling the checkbox does not update the input's checked attribute.

### Expected Behavior

When a CheckBox is clicked, the input's `checked` attribute should be updated as appropriate.

### Actual Behavior

The input's `checked` attribute is staying the same as it was initially rendered, updates are applied to the other html elements around it in the DOM, but not the input element.

### URL, screen shot, or Codepen exhibiting the issue

The behavior can be observed directly on the docs site:
https://v2.grommet.io/checkbox

The behavior is also captured in the test snapshot output:
https://github.com/grommet/grommet/blob/76b0551a2e506bda07a14a3de76708d50d1fa954/src/js/components/CheckBox/__tests__/__snapshots__/CheckBox-test.tsx.snap#L328

### Steps to Reproduce

1. Have a CheckBox
2. Click it
3. Inspect the DOM to see that the input's checked attribute was not updated to reflect the expected value

### Your Environment

- Grommet version: 2.22.0
- Browser Name and version: chrome
- Operating System and version (desktop or mobile): windows 10 desktop

**Comment by Ojas-Sri** [comment]
Hi Daniel,

I feel this is an inherent feature in HTML. The `checked` attribute seem to indicate `input` elements initial state, but does not capture its state during its lifetime.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#attr-checked

**Comment by jcfilben** [comment]
Thanks for looking into this @Ojas-Sri!
I believe you are correct, and in [the Grommet docs](https://v2.grommet.io/checkbox#checked) it says the `checked` prop follows the same behavior as `<input checked={} />` which is to indicate the initial state, not whether the checkbox is currently checked. Closing this issue.
