### ISSUE TITLE
Title in IE11 cuts off long text without Ellipsis

### ISSUE THREAD

**Issue by michaelgilley** [grommet/grommet#613]
As is in IE11:
<img width="431" alt="screen shot 2016-06-01 at 10 25 04 am" src="https://cloud.githubusercontent.com/assets/473729/15717212/335dfcd4-27e3-11e6-9b8c-4bb732119f9c.png">

Without `overflow: hidden` enabled:
<img width="437" alt="screen shot 2016-06-01 at 10 25 21 am" src="https://cloud.githubusercontent.com/assets/473729/15717216/38b47956-27e3-11e6-8eeb-1531be62ac1b.png">

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/b44296545c4e3e98a739367fad4a97ce79fc62d1
