### ISSUE TITLE
Id prop not working with Chart component - Typescript React 

### ISSUE THREAD

**Issue by theljwhite** [grommet/grommet#6149]
Id prop seems like it's working visually, in map of Charts it changes the style of each of my Charts as it should  but I get an error first. 
Apologies if I'm missing something here, I definitely could be. as I'm new to Typescript.  

I posted it here on StackOverflow first. 

https://stackoverflow.com/questions/72333202/cant-use-built-in-prop-of-grommet-chart-component-with-react-typescript

Thanks!!

**Comment by jcfilben** [comment]
Looks like Grommet is missing the type definition for the `id` prop in Chart

**Comment by theljwhite** [comment]
@jcfilben Figured it was something like that. Thanks for the response!
