### ISSUE TITLE
Incorrect row highlight behavior in DataTable

### ISSUE THREAD

**Issue by eddieshowcase** [grommet/grommet#6165]
Seems there is an odd issue introduced in recent Grommet release where the DataTable row highlight appears on the 1st row when clicking around and making selections. 

### Expected Behavior

I would not expect the 1st row to animate/highlight when clicking around the DataTable.

### Actual Behavior

A highlight appears on the 1st row when clicking elsewhere.

### Steps to Reproduce

You can observe this issue on Grommet Storybook issue here:
https://storybook.grommet.io/?path=/story/visualizations-datatable-onselect--on-select-data-table

I think the trick is to click on a row in the table, click off the table, then click a disabled row... seems an edge case, but reproducible. 

![e214e178-ae50-4a93-b22b-605fce96c69a](https://user-images.githubusercontent.com/7239901/171761252-090f9372-7b74-4b53-b8ae-d9e114356f84.png)

https://user-images.githubusercontent.com/7239901/171761217-5dffaa57-4451-4721-8c57-1fcc01b03ce1.mov

### Your Environment

- Grommet version: 2.24.0
- Browser Name and version: Chrome latest
- Operating System and version (desktop or mobile): Mac

**Comment by britt6612** [comment]
@eddieshowcase thank you for reporting we will look into this looks like it was introduced in the v2.23.0 release

**Comment by eddieshowcase** [comment]
BTW - I think a related or artifact of this issue is that the row highlighting also does not get applied to pinned columns. (or perhaps this is a separate issue).

<img width="1269" alt="Screen Shot 2022-06-03 at 12 41 05 PM" src="https://user-images.githubusercontent.com/7239901/171927001-9a45c1a3-483c-47a1-963f-5b078a279fd1.png">
