### ISSUE TITLE
Notification component to receive custom type and icon [feature request]

### ISSUE THREAD

**Issue by barinbritva** [grommet/grommet#6168]
Now `Notification` component is restricted by a few types: `critical`, `warning`, `normal`, `unknown`. It's a great design for a purpose. At the same time, the component isn't customizable as it might be.

### Expected Behavior

It would be reasonable to add the `custom` type. For this case, the component could use a brand new `customIcon` prop to render any icon for a specific situation.

### Actual Behavior

There is no `custom` type and a property for a custom icon

**Comment by barinbritva** [comment]
Hi @jcfilben,

I was thinking about it, and I've realized that maybe there is no need to create a custom type. But I definitely needed a custom icon option. For example, I would like to create notifications like:

* 💗 Somebody liked you post
* ✉️ I've got 2 new messages
* 👣 Somebody now follows you

I believe each case is just `normal` type, but still would be great to use custom icon.

**Comment by jcfilben** [comment]
Thanks for providing use cases!
Sounds like we should add `icon` prop to Notification. If the `icon` prop is set it will override the `notification.[status].icon` set in the theme. If no `icon` prop is passed we will continue to use the icon defined in `notification.[status].icon`.

**Comment by narayand16** [comment]
Hi @jcfilben I would like to work on this issue around customising notification component. Can you assign it to me ?

**Comment by jcfilben** [comment]
Awesome! I just added you as an assignee on the issue

**Comment by narayand16** [comment]
Hi @jcfilben I have done my changes related to custom icon for notification , but I am getting some test failures(happening in `DateInput` component) while committing. Here is the attached screenshot. Can you guide me on how to bypass this ?

<img width="813" alt="Screenshot 2022-10-03 at 10 36 21 PM" src="https://user-images.githubusercontent.com/29942751/193677982-18551c1d-3d58-46db-ab31-1caf924139ac.png">

**Comment by jcfilben** [comment]
Hey @narayand16 for now can you add your changes with the `--no-verify` flag? Normally we don't want to do this but my suspicion is that these DateInput tests may just be failing because of the timezone you are in. Once you file a pull request I can take a closer look and see if the tests pass in our circleci environment. For debugging purposes what timezone are you working in? There may be an issue with our DateInput component or tests.

**Comment by narayand16** [comment]
Hi @jcfilben Thanks for your prompt response. I am currently working in CET(UTC + 1 hrs) timezone. As this is my first PR for grommet, I would love to get learnt by you and your code review ;)

**Comment by narayand16** [comment]
Hey @jcfilben can you assign certain similar issues to me ?

**Comment by jcfilben** [comment]
> Hey @jcfilben can you assign certain similar issues to me ?

Great to hear you are interested in contributing more! Feel free to look through the issues, ones labeled ['hacktoberfest'](https://github.com/grommet/grommet/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) are a good place to start. Comment on a issue that you are interested in working on and I can add you as an assignee

**Comment by jcfilben** [comment]
Closing since #6389 has been merged
