### ISSUE TITLE
add controls function to video player

### ISSUE THREAD

**Issue by qteter** [grommet/grommet#618]
Functional duration bar that allows users to fast forward and rewind interactively. Could also use function to play/pause on controls bar adjust volume if not already implemented. similar to using "controls" function when adding video using standard html code. 
![video controls](https://cloud.githubusercontent.com/assets/13261077/15757105/a53fae06-28c9-11e6-826f-2451a744cc8d.png)

**Comment by bryanjacquot** [comment]
Agree the Video component could be improved.  We'd suggest starting by making the timeline clickable to allow the viewer to move play position anywhere within the video, instead of being limited to chapter boundaries as it currently is.  A mute button also seems appropriate to add as a next addition.  If you'd like to submit a PR, that'd be great!

**Comment by L0ZZI** [comment]
Add fullscreen button and CC?

**Comment by prewalia** [comment]
Hey guys sorry about the confusion :) here are all the files:

**PDF showing transition** from the current Video Marquee space (where we would be playing the looping video) to the video player once you click on "**Watch Now**". As you can see once you click on "Watch Now" the content below gets pushed further down to accommodate 16:9 format of the actual video:
[VideoMarquee_To_Player_Transition.pdf](https://github.com/grommet/grommet/files/370052/VideoMarquee_To_Player_Transition.pdf)

**The final sketch file** (So this can simply be inserted in the current video marquee space playing inline(vs layer). Added the close X and resized play/pause icons to core grommet 24px, and added our replay/share screen. The video will play inline on page by replacing the video marquee initial state. Height will grow from marquee height, 75% or whatever it is now, to accommodate 16:9 format of the actual video): 
[hpe-video-component-r2-kl.sketch.zip](https://github.com/grommet/grommet/files/370051/hpe-video-component-r2-kl.sketch.zip)

**The PDF file** for the same:
[hpe-video-component-r2-kl.pdf](https://github.com/grommet/grommet/files/370056/hpe-video-component-r2-kl.pdf)

**Comment by kyle-locke** [comment]
FYI, I removed 'option 1' from the sketch file.
[hpe-video-component-r2-kl.sketch.zip](https://github.com/grommet/grommet/files/370162/hpe-video-component-r2-kl.sketch.zip)

**Comment by kyle-locke** [comment]
added hover states for the control icons.
[hpe-video-component-r2-kl.sketch 2.zip](https://github.com/grommet/grommet/files/370342/hpe-video-component-r2-kl.sketch.2.zip)

**Comment by prewalia** [comment]
Hey Son here is the break down of components for you! :) Please let me know if you need me to add any other information and feel free to ask any questions!
[VideoMarquee_InformativeDescription.pdf](https://github.com/grommet/grommet/files/370359/VideoMarquee_InformativeDescription.pdf)

**Comment by bryanjacquot** [comment]
https://github.com/grommet/grommet/pull/758
