### ISSUE TITLE
DataChart label alignment doesn't align when chart is narrow

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#6184]
### Expected Behavior

DataChart labels should stay centered under associated bar.

### Actual Behavior

Label for chart does not align with bar when Chart is displayed in a situation with limited width (narrow box, narrow screen, etc.).

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-2p0rdk?file=/index.js

### Steps to Reproduce

1. Open CodeSandbox (the default view will likely have enough space so labels will be underneath bar)
2. Decrease screen width, you'll notice the labels move to the center more than the bars do, so it's misaligned.

### Your Environment

- Grommet version: Latest
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): MacOS Monterey

**Comment by ericsoderberghp** [comment]
Can you add a screenshot? I'm not quite sure how to use the code sandbox link to generate the issue.

**Comment by jcfilben** [comment]
<img width="239" alt="Screen Shot 2022-07-28 at 9 13 14 AM" src="https://user-images.githubusercontent.com/54560994/181573743-1c4062a0-b1eb-4834-8fed-2c7dfe445347.png">

I attached a screenshot that I think is showing the issue. The labels are more are not aligned under the bar and more centered on the chart instead.
