### ISSUE TITLE
Use in existing app.

### ISSUE THREAD

**Issue by Stalso** [grommet/grommet#619]
Hello. How can I use grommet with [this](https://github.com/mxstbr/react-boilerplate) template? I have installed npm dependecy from npm, setted template to work with SASS (useing css-modules). But styles are not loaded

**Comment by bryanjacquot** [comment]
@Stalso, can you be more specific on the issues you're facing?  There's another open issue regarding the use of just css-modules and grommet (https://github.com/grommet/grommet/issues/567) but without more details it's hard to provide guidance.  We'd be happy to work with you in hopes of getting Grommet working with this boilerplate.

**Comment by Stalso** [comment]
Thank you.  I have managed to set up grommet in this template by myself.  But I need to include prebuild grommet. min. css.  It makes grommet more difficult to customize in project,  which is based on css modules.  Grommet is really cool,  but you should make usage of it ( when people use it like existing library) similar to [this](http://react-toolbox.com/#/)  library. And I am very sorry,  that I have forgotten about the issue and have not closed it yet.  You may close the issue

**Comment by bryanjacquot** [comment]
@Stalso, thanks for the feedback.  We are investigating ways to allow Grommet components to be more easily consumed in apps that may not be using Grommet-toolbox.  You can follow the progress here: https://github.com/grommet/grommet/issues/678

**Comment by alansouzati** [comment]
I see React boilerplate uses css-modules. For now we will remain with SASS+BEM methodology.

Please save some time to read my journey when investigating CSS in Javascript, including CSS modules.

https://blog.grommet.io/post/2016/08/10/css-in-js-may-not-be-the-solution-to-all-your-problems.

If you are interested to understand what is the minium set of tools required for grommet to work, please check the grommet-standalone project: https://github.com/grommet/grommet-standalone
