### ISSUE TITLE
Circle Meter chart not rendering properly for specific input values

### ISSUE THREAD

**Issue by thomas-friedrich** [grommet/grommet#6190]
With specific input values, the slices of a Meter chart of type "circle" won't render correctly

### Expected Behavior
Meter chart of type "circle" should render slices correctly.

### Actual Behavior
<img width="275" alt="image" src="https://user-images.githubusercontent.com/84544729/174159466-41a623fd-e246-4238-b01f-0971191d7d84.png">

### URL, screen shot, or Codepen exhibiting the issue
code sandbox: https://codesandbox.io/s/memory-pie-chart-forked-xk1p3h?file=/index.js

### Steps to Reproduce

It's not clear for what input values the problem is happening. In the code sandbox, the problem shows with a max of 10.3 and two slices of 2.26 and 8.04. Changing the slices to 2.25 and 8.05 renders correctly.

### Your Environment

- Grommet version: 2.24
- Browser Name and version: Chrome 102.0.5005.61
- Operating System and version (desktop or mobile): Mac OS 11.6.2

**Comment by ericsoderberghp** [comment]
Interesting. Here a bit more triage detail:
- when the values are 2 and 8 and the max is 10, it works fine.
- when the values are 2.26 and 8.04 and the max is 10.3, it shows the problem
- when the values are 2.26 and 8.041 and the max is 10.3, it works fine.
So, it looks like a subtle math or rounding issue, probably tied to how SVG arcs work.

https://v2.grommet.io/meter?c=DwWQpgLmBOBQAE8IE8AOYC8AiAxgS2hwBswsF4A3AQyIFcwBnDAbwG1nKb6AueAJgB0fAGzwAvgBp4zcomp0wvABwCADABYJs+ESoAjMEV4ByBngAeKY1sSIA9gDsAwkTw4A1rwAUASngYAPmkxcjEAXRDEAFsqcxYARlUBAGZI+CpoPCoAWl0DImwoyBgyAHoAoA

**Comment by ericsoderberghp** [comment]
The underlying issue is the lack of floating point precision in javascript. See: https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript
