### ISSUE TITLE
Image's onLoad prop is not provided to an img tag

### ISSUE THREAD

**Issue by undermuz** [grommet/grommet#6202]
### Expected Behavior

Image's onLoad prop is provided to an img tag

### Actual Behavior

Image's onLoad prop is not provided to an img tag

source code of the Image component:
```javascript
const handleOnLoad = () => {
      setFallbackInUse(false);
    };

    const extraProps = {
      onError: (onError || fallback) && handleError,
      onLoad: handleOnLoad,
    };

    return (
      <StyledImage
        aria-label={a11yTitle}
        {...rest}
        {...extraProps}
        ref={ref}
        opacityProp={opacity}
        fillProp={fill}
        src={src === undefined ? '' : src}
      />
```

### Steps to Reproduce

```javascript
const onLoadImage = useCallback((e) => {
  console.log("[onLoadImage]", e)
}, [])

return <Image
    src={src}
    onLoad={onLoadImage}
/>
````

onLoadImage message never be shown

### Your Environment

- Grommet version: "grommet": "^2.24.0"
- Browser Name and version: Chrome 102
- Operating System and version (desktop or mobile): Windows 11

**Comment by Lukazovic** [comment]
I think we can close this issue since #6217 is merged
