### ISSUE TITLE
Notification component should render the title above the message for a Toast

### ISSUE THREAD

**Issue by eddieshowcase** [grommet/grommet#6209]
### Expected Behavior

<img width="768" alt="Screen Shot 2022-06-28 at 12 35 16 PM" src="https://user-images.githubusercontent.com/7239901/176274710-f50a9b69-d42f-4d2a-b3a5-960282e338ea.png">

### Actual Behavior

<img width="545" alt="Screen Shot 2022-06-28 at 12 35 53 PM" src="https://user-images.githubusercontent.com/7239901/176274740-681b7b1b-3b3b-4da2-971f-925e0208af54.png">

### URL, screen shot, or Codepen exhibiting the issue

See screenshots

### Steps to Reproduce

Your own storybook reproduces the issue here: 
https://storybook.grommet.io/?path=/story/visualizations-notification-toast--toast&globals=theme:hpe

### Your Environment

- "grommet": "^2.24.0",
- "grommet-icons": "^4.7.0",
- "grommet-theme-hpe": "^3.1.0",

- Browser Name and version: Chrome latest

- Operating System and version (desktop or mobile): Mac Ox

**Comment by EduardoSCosta** [comment]
hi, I could try to solve this issue.

**Comment by eddieshowcase** [comment]
I realize there is some theme options "Notifications.toast.direction" etc. that can be configured via theme to adjust this, but felt the "column" direction should be default when toast prop is true/present for HPE theme.
