### ISSUE TITLE
The 'gulp dist' does not work for big projects?

### ISSUE THREAD

**Issue by harshithjv** [grommet/grommet#621]
I am developing grommet project for fairly intensive UI project. Right now I completed only few parts of it, i.e., 3 out of 12 pages. It runs nicely through 'gulp dev' command. However I am trying to run from output of 'gulp dist' and it renders the blank page. Only title is displayed, meaning the page layout is loading but the bundled JavaScript is not working.

This happens same for local copy downloaded for 'grommet-docs' and 'grommet-ferret' repos which just shows the initial grommet logo and some animation on background, all rendered from html code I assume. Again bundled JavaScript does not seem to work.

**Comment by alansouzati** [comment]
is there anything in the browser console?

Also, when you run gulp dist, are there any issues in the command line?

**Comment by harshithjv** [comment]
@alansouzati

There are no issues and gulp dist runs successfully. 

By default there will be warning for using deprecated customLintErc config in grommet-toolbox config file. Even after fixing that, the same issue persists.

**Comment by harshithjv** [comment]
@alansouzati 

No issues on browser console also.

**Comment by alansouzati** [comment]
Are you trying to open the index.html in the browser, or are you running with an application server?

If you app has routing, it may want to add an application server to serve the app. This might explain why it works for gulp dev (there is an application server in this case).

**Comment by harshithjv** [comment]
@alansouzati

Ya I was trying to open index.html and my project has routing.  The webpage usually works by loading just the HTML file.

By application server you mean Apache or Nginx?

**Comment by slara** [comment]
@harshithjv try to run something like `python -m SimpleHTTPServer` in your `dist` directory. I'm having the same problem with `apache2` and a `react-router` app inside a directory different than the root directory.

**Comment by chandrakantnitt** [comment]
Alternatively you can use http-server
First install http-server by following command
 `npm install http-server -g`
Then navigate to your project directory
 `cd dist/`
later run below command 
 `http-server -p 9999`
Then type following to access your app
 `http://localhost:9999`

**Comment by harshithjv** [comment]
@slara 

That solutions usually works as file server. It loaded the page alright. But mine project was dependent on JSON file data which this server was rendering as download only. So the data from JSON was not parsed successfully into the page. Maybe extra parameter on command line or I may need to write custom python script to serve files. Thanks for the solution and I will look into that part of making it work if I would implement the python server solution. But I did not understand the react-router part of your comment. Please explain further.

**Comment by harshithjv** [comment]
@chandrakantnitt 

Thanks for the answer. I knew about http-server solution. But can it be used for big production site?

**Comment by alansouzati** [comment]
For a production site I recommend setting up an express server with multiple instances as web workers (load balancing)

Checkout the grommet-docs server: https://github.com/grommet/grommet-docs/blob/master/server/server.js#L18

**Comment by harshithjv** [comment]
@alansouzati 

Ok that looks great for closing this ticket. To conclude, if react-router is used in React/Grommet projects, then it is wise to serve the project from bundled output(i.e., project files generated from 'gulp dist' command).

Let me know if any pointers to consider before I close this issue?

**Comment by slara** [comment]
@harshithjv What I'm trying to say is that with `react-router` you may need to specify a `basename` for your application to work. That way you can deploy your application in paths outside your 'root' path. If you are opening your `index.html` directly, I think you will have your filesystem directory as `basename`.

This is how I configured my app to work in `http://example.com/dataentry` using `react-router` and `redux`.

```JavaScript
import { createHistory } from 'history';
import { useRouterHistory } from 'react-router';
import { routerMiddleware } from 'react-router-redux';

const browserHistory = useRouterHistory(createHistory)({
  basename: '/dataentry'
});

const middleware = routerMiddleware(browserHistory);

let store = createStore(
  appReducers,
  persistedState,
  applyMiddleware(middleware)
);

const history = syncHistoryWithStore(browserHistory, store);
```

**Comment by harshithjv** [comment]
@slara Thanks :)

@alansouzati Closing this issue.
