### ISSUE TITLE
Spinner component 'size' prop doesn't always seem to work as expected (xsmall and arbitrary string size has no affect)

### ISSUE THREAD

**Issue by eddieshowcase** [grommet/grommet#6210]
### Expected Behavior

Based on component documentation, the spinner 'size' prop should accept 'xsmall', 'small', 'medium', 'large', 'xlarge' and an arbitrary string like "16px" for size.

### Actual Behavior

It seems that 'xsmall' and an arbitrary string like "16px" does not always work. For whatever reason, this is 100% reproducible for me on all browsers, scenarios. 

Yet, it seems intermittent or perhaps environment/browser based though, as 'xsmall' seems to work for some (worked for Taylor and a few of my devs) but not others (fails 100% for some of my devs too). 

The arbitrary string size doesn't seem to work at all.

### URL, screen shot, or Codepen exhibiting the issue

I can see this easily on your own sandbox here:

https://storybook.grommet.io/?path=/story/visualizations-spinner-size--size&globals=theme:hpe

... you can see that 'xsmall' is rendered the same as 'small' for me:

<img width="672" alt="Screen Shot 2022-06-28 at 8 44 19 AM" src="https://user-images.githubusercontent.com/7239901/176276797-9e2ca099-1a51-48bf-bd31-e073cd723f52.png">

### Steps to Reproduce

https://storybook.grommet.io/?path=/story/visualizations-spinner-size--size&globals=theme:hpe

### Your Environment

   "grommet": "^2.24.0",
        "grommet-icons": "^4.7.0",
        "grommet-theme-hpe": "^3.1.0",

- Browser Name and version: I tried Chrome, Safari, and Vivaldi ... all exhibit the issue.
- Operating System and version (desktop or mobile): Mac OS

**Comment by taysea** [comment]
After investigating, this is being caused the the `pad`  of "small" applied by the `spinner.container`. I think we need to do a check to take the minimum of the `size` dimensions and the dimensions + pad.

Additionally, an item discussed offline is if the spinner sizes should align with the dimensions of `icon` sizes.

**Comment by britt6612** [comment]
closing due to `pad` being taken out in hpe theme 

For now leaving the spinner sizes since teams are using the current sizes as it
