### ISSUE TITLE
[Text] Inline styles should override fontSize and lineHeight of the theme

### ISSUE THREAD

**Issue by pepoospina** [grommet/grommet#6218]
Currently, the theme values for the specific sizes of each "type of size" overrides the style properties in the component. This makes it impossible to change the `fontSize` of a Text component with inline CSS if the theme for that size type was overridden in the theme.

### Expected Behavior

Inline style should override the theme config.

### Actual Behavior

Theme config overrides inline-style.

### Code changes

In [StyledText.js](https://github.com/grommet/grommet/blob/f8c7358c43895ac8bb10e91ada33a5356a3adedd/src/js/components/Text/StyledText.js#L7) replace 

```js
const sizeStyle = props => {
  const size = props.size || 'medium';
  const data = props.theme.text[size];
  if (data) {
    return css`
      font-size: ${data.size};
      line-height: ${data.height};
    `;
  }
  return css`
    font-size: ${size};
    line-height: normal;
  `;
};
```

width 
```js
const sizeStyle = props => {
  const size = props.size || 'medium';
  const data = props.theme.text[size];
  if (data) {
    return css`
      font-size: ${props.style.fontSize ?  props.style.fontSize : data.size};
      line-height: ${props.style.lineHeight ?  props.style.lineHeight : data.height};
    `;
  }
  return css`
    font-size: ${size};
    line-height: normal;
  `;
};
```

I could address this but I'm in a rush to finish something.

**Comment by nashitshayan** [comment]
Hi @pepoospina , do you just want someone to make this exact change?

**Comment by pepoospina** [comment]
Wait wait wait sorry. I'm not sure this is an issue anymore. Let me check it out in detail and I will reopen if I see it was an issue indeed.
