### ISSUE TITLE
DataTable's step and paginate.step not working properly together

### ISSUE THREAD

**Issue by mellis481** [grommet/grommet#6221]
DataTable has two ways to define the page size: `step` and `paginate.step`.  If `paginate.step` is defined, it should use that everywhere, but it appears to be using `step` still in some places including whether or not to display the pagination controls.

### Expected Behavior
Given the following code, I expect a table with a page size of 5 that shows records 1-5 and 10 total pages:

```
const columns = [
  { property: "id", header: "ID" },
  { property: "name", header: "Name" }
];

const DATA = new Array(LENGTH).fill().map((item, index) => ({
  id: index,
  name: `Name ${index}`
}));

<DataTable
  columns={columns}
  data={data}
  paginate={{
    step: 5
  }}
/>
```

### Actual Behavior
Instead, the pager does not appear at all, unless the data set has more than 50 records (which can be done by clicking the "Add another item" button).  The code that determines if the pagination controls should appear seems to be based on `step`, not `paginate.step`.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-datatable-forked-oppxbg?file=/src/index.js

### Your Environment

- Grommet version: 2.24.0
- Browser Name and version: Chrome latest
- Operating System and version (desktop or mobile): Windows 10

**Comment by jcfilben** [comment]
Closing since #6262 has been merged
