### ISSUE TITLE
Storybook - copy code shouldn't include line numbers

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#6228]
### Expected Behavior
When copying code from storybook, it shouldn't include the line numbers of the code. This is a regression.

### Actual Behavior
Copy code include the line numbers.

### URL, screen shot, or Codepen exhibiting the issue
Copy code from https://storybook.grommet.io/?path=/story/visualizations-list-onclickitem--on-click-item-list
And receive this when pasting:

26  const [clicked, setClicked] = React.useState();
27  const [show, setShow] = React.useState();
28
29  return (
30    <Box align="center" pad="large" gap="large">
31      <List
32        data={data.slice(0, 10)}
33        onClickItem={(event) => {
34          setShow(true);
35          setClicked(event.item);
36        }}
37      />
38
39      {show && (
40        <Layer
41          position="center"
42          onEsc={() => setShow(false)}
43          onClickOutside={() => setShow(false)}
44        >
45          <Box margin="medium">
46            <Text>{clicked && JSON.stringify(clicked, null, 2)}</Text>
47            <Button
48              margin={{ top: 'medium' }}
49              label="close"
50              onClick={() => setShow(false)}
51            />
52          </Box>
53        </Layer>
54      )}
55    </Box>
56  );
57};

### Steps to Reproduce

1. Go to any storybook code example, e.g. https://storybook.grommet.io/?path=/story/visualizations-list-onclickitem--on-click-item-list
2. Copy code from storybook 
3. Paste code on your editor

### Your Environment
Mac + Chrome

- Grommet version: Recents
- Browser Name and version: N/A
- Operating System and version (desktop or mobile): N/A

**Comment by taysea** [comment]
As a workaround (not a solve, but takes some of the tediousness out), you can put your cursor on a certain line, then hold alt + shift, and click on a new line -- this will select all the lines in between:

https://user-images.githubusercontent.com/12522275/181321740-eb318250-99e9-416a-88b2-072ec2cdbb6c.mov

**Comment by jcfilben** [comment]
Should be fixed by the storybook 7 upgrade https://github.com/grommet/grommet/pull/6726
