### ISSUE TITLE
Enhancement to "Search" component

### ISSUE THREAD

**Issue by huiwang-hpe** [grommet/grommet#623]
Could you please provide a new feature or an interface to enable a "delete search string" button?
So that user could clear the current search string without select all and delete, or backspace over the entire search string.
It's something like this:
![2016-06-07_135952](https://cloud.githubusercontent.com/assets/19163801/15847505/09ce6c5c-2cb9-11e6-8381-164eedf6c498.jpg)

**Comment by bryanjacquot** [comment]
@huiwang-hpe we've confirmed this behavior is not working properly on Safari, but other browsers seem to be working as you describe.  Please confirm this is the case for your environment, if not please provide more details.

**Comment by karatechops** [comment]
I've posted PR [#880](https://github.com/grommet/grommet/pull/880) which fixes the Safari select bug.
