### ISSUE TITLE
document.activeElement is not working when using Grommet in shadow Dom. This means a form field is not getting highlighted when clicked.

### ISSUE THREAD

**Issue by steveartfx** [grommet/grommet#6232]
When using  formfield and a form element component in shadow Dom and clicking it, the highlighted border does not appear.

### Expected Behavior

The behavior should be the same for web component usages as it is in the normal scenario

### Actual Behavior

The border is missing when clicked. Styles are never added to stylesheetmanager outlet when the element is clicked. When not using shadow Dom, I can see the styles being added correctly.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-forked-cycmxn?file=/index.js

### Steps to Reproduce

Add formfield and form element to shadowDom with a stylesheemanager and click on text input. Notice the highlighted border is missing only when using shadowDom.

### Your Environment

- Grommet version: 2.24.0
- Browser Name and version: Chrome latest
- Operating System and version (desktop or mobile): OSX

**Comment by jcfilben** [comment]
Hi @steveartfx could you share a codesandbox that reproduces the error? Here is a template to get started: https://codesandbox.io/s/m7mml8l0zj

**Comment by jcfilben** [comment]
@steveartfx can you share the link to the codesandbox where you added the code?

**Comment by steveartfx** [comment]
@jcfilben I'm using this link: https://codesandbox.io/s/grommet-v2-template-forked-cycmxn?file=/index.js

**Comment by jcfilben** [comment]
Perfect, thanks!

**Comment by taysea** [comment]
This might be relevant to a fix: https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/activeElement
