### ISSUE TITLE
Tabs Underlines are not sticky when tab are used in a section which has fixed height

### ISSUE THREAD

**Issue by raghuramsomayaji** [grommet/grommet#6235]
Tabs underlines(margin bottom) with grommet-theme-hpe are not stick to the bottom of it when we have scrollable content within the tab. It was working before but after this new feature - https://github.com/grommet/grommet/pull/6137 it is broken.

### Expected Behavior
With grommet 2.24.0 and grommet-theme-hpe - 3.2.0
![image](https://user-images.githubusercontent.com/87470562/179499480-259104aa-f21b-48a3-a9e1-103813598d5d.png)

### Actual Behavior

With grommet - 2.25.0 and grommet-theme-hpe - 3.2.0
![image](https://user-images.githubusercontent.com/87470562/179499857-ae0357a5-66ae-4a2a-b780-62065a3beb20.png)

### URL, screen shot, or Codepen exhibiting the issue
See screenshots

### Your Environment
- Grommet version: 2.25.0
- grommet-theme-hpe: 3.2.0,
- Browser Name and version: Chrome  103.0.5060.114
- Operating System and version (desktop or mobile): Windows 10

**Comment by jcfilben** [comment]
Hi @raghuramsomayaji I created a codesandbox example of Tabs with scrollable content but I wasn't seeing an issue where the tab underline is appearing in the middle of the Tab buttons unless I added a negative bottom margin to the Tab. Can you share a codesandbox that reproduces the issue you are seeing above?

Here is my codesandbox: https://codesandbox.io/s/grommet-v2-template-forked-mnnmzz?file=/index.js

**Comment by raghuramsomayaji** [comment]
Hi @jcfilben This is happening when we use tabs inside a component which has fixed height like grommet **Box** . I just added height to the Box component and here is the codesandbox: https://codesandbox.io/s/grommet-v2-template-forked-xtqw3m?file=/index.js
