### ISSUE TITLE
Markdown line-breaks rendered incorrectly

### ISSUE THREAD

**Issue by kevinworth** [grommet/grommet#624]
It appears that grommet renders all line breaks in .md files, despite the Markdown specification spelling out how this behavior should work (https://daringfireball.net/projects/markdown/syntax#p)

> PARAGRAPHS AND LINE BREAKS
> 
> A paragraph is simply one or more consecutive lines of text, separated by one or
> more blank lines. (A blank line is any line that looks like a blank line - a
> line containing nothing but spaces or tabs is considered blank.) Normal
> paragraphs should not be indented with spaces or tabs.
> 
> The implication of the "one or more consecutive lines of text" rule is that
> Markdown supports "hard-wrapped" text paragraphs. This differs significantly
> from most other text-to-HTML formatters (including Movable Type's "Convert Line
> Breaks" option) which translate every line break character in a paragraph into a
> `<br />` tag.
> 
> When you do want to insert a `<br />` break tag using Markdown, you end a line
> with two or more spaces, then type return.
> 
> Yes, this takes a tad more effort to create a `<br />`, but a simplistic "every
> line break is a `<br />`" rule wouldn't work for Markdown. Markdown's email-style
> blockquoting and multi-paragraph list items work best - and look better - when
> you format them with hard breaks.

For an example, see a Markdown in a file whose text paragraphs are wrapped at 79 characters

http://git.openswitch.net/cgit/openswitch/ops/tree/docs/access_list_cli.md#n45

compared to the website rendered via grommet whose paragraphs are also (incorrectly) wrapped at the same 79 characters

http://www.openswitch.net/documents/user/access_list_cli#description

note the line endings in the "Description" section are exactly the same in .md and html instead of the html wrapping based on the width of the browser window.

Perhaps this is a mis-use or mis-configuration of the openswitch.net deployment of grommet or another layer in the stack?

**Comment by alansouzati** [comment]
Thanks for raising this issue.

If I remember correctly OpenSwitch is not using the Markdown loader from Grommet. We have added recently and unless you have updated OpenSwitch site to use that, it is still doing its own parsing inside gulpfile.js.

See the officially support Markdown parser: http://www.grommet.io/docs/develop/markdown

**Comment by kevinworth** [comment]
I don't know the syntax of gulpfile.js but intuitively it would appear that the grommet markdown loader is in the list of things that it looks like get loaded for .md files

http://git.openswitch.net/cgit/infra/website/tree/gulpfile.js#n47

    module: {
      loaders: [
        {
          test: /\.md$/,
          loader: 'babel!imports?React=react!html-jsx-loader!grommet-markdown'
        }
      ]
    }

**Comment by alansouzati** [comment]
True, thanks for remembering my about this loader. 

Let me investigate why the line breaks are broken in that one and release a new version. Would you mind to transfer the issue to the loader project?

https://github.com/grommet/grommet-markdown-loader

**Comment by kevinworth** [comment]
I'd be happy to but grommet/grommet-markdown-loader project doesn't seem to have issue tracking enabled

**Comment by alansouzati** [comment]
good catch. i've just enabled it.

**Comment by kevinworth** [comment]
Transferred to https://github.com/grommet/grommet-markdown-loader/issues/1
