### ISSUE TITLE
Calendar - Looking for a Month and Year Calender

### ISSUE THREAD

**Issue by romanpastu** [grommet/grommet#6242]
Reopening this issue https://github.com/grommet/grommet/issues/990

I am looking for a calender control in month and year format (no date/day)

### Expected Behavior

Calendar control should have only year and month control
MM/YY

### Actual Behavior

There is no such control
MM/DD/YYYY

### Steps to Reproduce

[grommet docs.](https://v2.grommet.io/calendar?c=DwYQhgNgpgdgJmATgKAASoM4EsBeUC8ARBgLaQSFqoIAuBA3oQIwAMAtAEwtMAchAvsgD0APiA) Use the grommet docs and try to input a dale that doesnt have the day specified, it will autoselect a day

### Your Environment

Generic

**Comment by AbreezaSaleem** [comment]
@romanpastu the issue is closed but I see no solution to this. Can you please share an example code for implementing a month+year only calender? Thank you.
