### ISSUE TITLE
Grid component does not have role="grid"

### ISSUE THREAD

**Issue by Ojas-Sri** [grommet/grommet#6247]
- Grommet `<Grid/>` component does not have WAI-ARIA role of `"grid"`.
- Neither `<Grid/>` cells have WAI-ARIA role of `"grid-cell"`

### Expected Behavior
- The Grid component should have role="grid".
- Grid cells should have role="grid-cell"

### Actual Behavior

- RTL does not find any items with role "grid" or "grid-cell" on the screen.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/upbeat-bell-p080tp?file=/src/App.spec.js  -> go to tests tab

### Steps to Reproduce

1. Create a Grid in Grommet.
2. Write a test file with `react-testing-library` .
3. Query the screen with `ByRole` query with roles `grid` OR `grid-cell`

### Your Environment

- Grommet version: latest
- Browser Name and version: Chromium
- Operating System and version (desktop or mobile): Desktop

**Comment by ericsoderberghp** [comment]
Based on https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Grid_Role, it seems that the roles are primarily used for a data grid with interactive cells arranged in rows, which is basically a table. Most of the uses of Grid in grommet apps are as layout grids where the headings or focusable elements within each of the grid areas would be used to traverse the content by screen reader or keyboard. Do you have an real-world example demonstrating using these roles for a layout grid?

**Comment by Ojas-Sri** [comment]
Got it @ericsoderberghp , as you mentioned the `Grid` aria role represents a different HTML element.

No, I don't have an example for use of the role in "layout grids"

**Comment by jcfilben** [comment]
@Ojas-Sri can we go ahead and close this issue?

**Comment by jcfilben** [comment]
Closing, feel free to re-open if needed
