### ISSUE TITLE
`RadioButton` Custom Icon not passed `theme` as a prop

### ISSUE THREAD

**Issue by GFargo** [grommet/grommet#6263]
### Expected Behavior

Similar to the [custom _checked_ icon ](https://github.com/grommet/grommet/blob/master/src/js/components/CheckBox/CheckBox.js#L139)within the CheckBox component, the `StyleRadioButtonIcon` should be [passed the `theme` as a prop here](https://github.com/grommet/grommet/blob/master/src/js/components/RadioButton/RadioButton.js#L103).

The `ThemeType` type should likely also match the `any` value being used by `checkBox.icons.checked`.

### Actual Behavior

Instead there is both a type error within `ThemeType` & type error when trying to pass a custom icon via `radioButton.icons.circle` due to `icon` being undefined.

### URL, screen shot, or Codepen exhibiting the issue

<img width="679" alt="Screen Shot 2022-08-06 at 5 31 33 PM" src="https://user-images.githubusercontent.com/3642037/183266658-44af7f3c-0b80-4274-877f-fc6ccd144265.png">

[Demo of issue](https://codesandbox.io/s/grommet-v2-issue-with-using-custom-circle-icon-in-radiobutton-1nfhcn)

### Steps to Reproduce

1. Create custom theme for `radioButton.icons.circle` that includes a grommet icon, like you would for `checkBox.icons.checked`

e.g. 

```
// Works 🎉 
checkBox: {
  icons: {
    checked: Gremlin,
  }
},

// Doesn't work 😢 
radioButton: {
  icons: {
    circle: Gremlin,
  }
}  
```

2. Pass theme to any component trying to render the grommet `RadioButton` component.

### Your Environment

- Grommet version: `2.25.1`
- Browser Name and version: Chrome Version 103.0.5060.134 (Official Build) (arm64)
- Operating System and version (desktop or mobile): Desktop - MacOS `12.5`

**Comment by jcfilben** [comment]
Closing since #6264 has been merged
