### ISSUE TITLE
SkipLinks should automatically filter out undefined children

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#6266]
### Expected Behavior

SkipLinks should filter out `undefined`/`null` children before attempting to `cloneElement`. Page content may change based on various conditionals, so not all skiplinks will be relevant to all pages.

### Actual Behavior

Throws error.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-dwsdu5?file=/index.js

<img width="667" alt="Screen Shot 2022-08-09 at 1 56 48 PM" src="https://user-images.githubusercontent.com/12522275/183759954-cc941a87-520f-4b24-a0c4-bdb473fbee83.png">

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.25.0
- Browser Name and version: Chrome MacOS latest
- Operating System and version (desktop or mobile): MacOS Monterey 12.4

**Comment by nidble** [comment]
Hello there, could I work on this?

**Comment by britt6612** [comment]
@nidble of course feel free to open a PR and comment if you have any questions or need help. 🥳

**Comment by jcfilben** [comment]
Closing since #6402 has been merged
