### ISSUE TITLE
Select dropdown is not allowing to scroll all the options when clear selection is enabled.

### ISSUE THREAD

**Issue by DreamerIn** [grommet/grommet#6267]
Select dropdown not allowing to scroll all the options when clear selection is enabled.

### Expected Behavior

Select dropdown should load all the options whether clear option is enabled or disabled.

### Actual Behavior

When clear option is enable Select dropdown is not completely scrollable

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/stupefied-proskuriakova-t9r5xw

### Steps to Reproduce

1. Load some dropdown options for select which has more options that enable scroll in Select.
2. Enable clear selection property for Select
3. Make a selection in the dropdown.
4. Observe you will not be able to scroll through all the options..

### Your Environment

- Grommet version: > 2.21.0
- Browser Name and version: All browsers
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment]
Attaching codesandbox from slack thread https://codesandbox.io/s/stupefied-proskuriakova-t9r5xw
