### ISSUE TITLE
Cannot resolve 'file' or 'directory' ./index-icons

### ISSUE THREAD

**Issue by masogit** [grommet/grommet#627]
ERROR in ./~/grommet/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./index-icons in /Users/maso/Documents/Workspace/amb-grommet/am-browser/node_modules/grommet
 @ ./~/grommet/index.js 68:10-34

**Comment by bryanjacquot** [comment]
@masogit can you confirm the version of Grommet you were using when you saw this issue?

**Comment by bryanjacquot** [comment]
@masogit we don't believe this is still an issue, closing.
