### ISSUE TITLE
Toast Notification Timing Adjustable

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6270]
### Expected Behavior
Toasts need to support a way to extend timing or set a new time limit. See https://www.w3.org/TR/WCAG21/#timing-adjustable

### Actual Behavior
Currently the time limit is controlled by the theme. To adjust it would require changing the theme. We don't support a good way to extend the time limit of a toast before it is removed from the screen.

**Comment by grazirs** [comment]
Can I work on this?

**Comment by jcfilben** [comment]
Hi @grazirs, great to hear you are interested in working on this! I think there may be some interesting design considerations that come up as you work through this so definitely reach out if needed along the way, but feel free to work on this

**Comment by jcfilben** [comment]
Closing since #6462 has been merged
