### ISSUE TITLE
DataTable: sorting arrow icon doesn't change in header when using navigation

### ISSUE THREAD

**Issue by vldmr1986** [grommet/grommet#6278]
We store sorting parameters in the URL (so that you can share the URL)

### Expected Behavior

1. Click on the table header to sort (different columns several times):
 - The URL has changed, arrows in the header should be consistent with the new URL info
2. Use browser navigation arrows (back/forward)
 - The URL has changed, arrows in the header should be consistent with the new URL info

### Actual Behavior
1. Click on the table header to sort (different columns several times):
 - The URL has changed, arrows in the header should be consistent with the new URL info
2. Use browser navigation arrows (back/forward)
 - The URL has changed, but there are no changes in the table headers, arrows icon state does not change

### URL, screen shot, or Codepen exhibiting the issue

  -- Here's a Codesandbox template that serves as a nice starting point
  -- for demonstrating an issue: https://codesandbox.io/s/morning-glade-5c6s38?file=/src/App.js

<img width="469" alt="Screenshot 2022-08-14 at 21 44 25" src="https://user-images.githubusercontent.com/17574496/184552506-15664064-8455-4cf7-8241-07318442cc40.png">

- Grommet version: 2.25.1

**Comment by taysea** [comment]
Hi @vldmr1986 -- when using the `sort` prop, if you indicate `external: true` then the docs indicate that "the caller will take care of sorting the 'data' via 'onSort': https://v2.grommet.io/datatable#sort

If you'd like DataTable to handle the sorting for you, you can remove `external: true` from your sort prop like this: https://codesandbox.io/s/friendly-microservice-ggt1q4?file=/src/App.js

Can you let me know if this solves your issue?

**Comment by vldmr1986** [comment]
@taysea the problem is neither in the data nor in their sorting The problem is in the incorrect arrows in the header.
Pay attention to the property sort={{ property, direction }} 
<img width="1408" alt="Screenshot 2022-08-29 at 22 16 28" src="https://user-images.githubusercontent.com/17574496/187291555-f008834f-c8ef-4b54-bc0c-8aa1301b5f5f.png">

I

**Comment by vldmr1986** [comment]
I noticed that the behavior of the arrows only changes if you manually click on the header. but if you change the sort property through the state or navigation, the arrow does not react.

Assumption: The Table uses the external sort property on componentWillMount only, and then defines the internal local state of these values. So when the Table component is mounted, and the "sort" property is changed, the component won't rerender

If so, the solution could be something like that:
```
useEffect(()=>{
// re-setSate local sort ptoperty inside Table component
}, [sort.direction, sort.property])
```

**Comment by taysea** [comment]
Thanks for clarifying. From your initial code sandbox, I was able to see the arrow change when adjusting the search params in the url -- however, I am now able to replicate the issue with state. I am looking into a solution.

**Comment by vldmr1986** [comment]
Once you adjust the search params directly in the URL (manual), it will cause reload the page, so it will trigger componentWillMount (so sort will be correct).
But, if you will use useSearchParams hook(react-router-dom), it won't reload the whole page.
Steps to reproduce:
1. Click on the header "B"
2. Click on the "backward" arrow navigation button from the built-in browser

 however,  the fix with the local state should fix navigation as well
