### ISSUE TITLE
`grommet init sample-app` Fails to parse package.json data

### ISSUE THREAD

**Issue by dclemmon** [grommet/grommet#628]
When I install grommet on Debian Jessie and try to follow the instructions to init the sample app, grommet dies parsing the package.json data with a trailing comma at 16:3.  My package.json file looks like this:
`{
  "name": "sample-app",
  "version": "0.1.0",
  "main": "src/js/index.js",
  "dependencies": {
    "grommet": "0.6.7",
    "react": "^15.0.2",
    "react-dom": "^15.0.2"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-register": "^6.5.2",
    "grommet-toolbox": "^0.1.0",
    "gulp": "^3.9.0",
  }
}
`
and I believe it should look like this:
`{
  "name": "sample-app",
  "version": "0.1.0",
  "main": "src/js/index.js",
  "dependencies": {
    "grommet": "0.6.7",
    "react": "^15.0.2",
    "react-dom": "^15.0.2"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-register": "^6.5.2",
    "grommet-toolbox": "^0.1.0",
    "gulp": "^3.9.0"  <--- comma removed
  }
}
`

**Comment by alansouzati** [comment]
thanks for identifying this.

Fixed in https://github.com/grommet/grommet/commit/592923d7f581e644b49811fbea2aed8ef5d417f7

**Comment by grantnorwood** [comment]
For those having trouble with the current release, you can install grommet from the master branch using `sudo npm i -g https://github.com/grommet/grommet/tarball/master` and it works great.

@alansouzati Thanks for such a quick fix!

**Comment by alansouzati** [comment]
Thanks for the instructions @grantnorwood.

And sorry for breaking it myself in the first place 😭
