### ISSUE TITLE
Implement shouldComponetUpdate to improve components render performance

### ISSUE THREAD

**Issue by dbuarque** [grommet/grommet#629]
Hey guys,

I was wondering why grommet components don't implement **shouldComponetUpdate**, is this something in the development plan?

The reason I'm asking is that the components don't need to be re-rendered every time that something happen.

**Comment by dbuarque** [comment]
I would suggest this approach for some dumb components that has no state on it.

https://medium.com/@joshblack/stateless-components-in-react-0-14-f9798f8b992d#.7x3hrjoki

**Comment by alansouzati** [comment]
We tried stateless functions before, there is one issue with that though. They don't support `refs` and we are using that for focus management and other important features that Stateless Functions don't support

See this issue: https://github.com/facebook/react/issues/4936#issuecomment-179486461

**Comment by dbuarque** [comment]
Make sense
