### ISSUE TITLE
Button - dark mode label color inconsistent

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#6301]
### Expected Behavior

If the theme doesn't specify a label color for a specific button state (e.g., active), then the active button should have the same label color as the default state.

### Actual Behavior

In dark mode, when a button's default state has a background with opacity < 1 (such as background-contrast) the label color is coming through differently than when that button is active.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/active-button-color-pmujf7?file=/index.js

### Steps to Reproduce

Notice the difference in color in the dark mode of the "test button" vs "active test button"

### Your Environment

- Grommet version: 2.25.1
- Browser Name and version: MacOS Chrome
- Operating System and version (desktop or mobile): MacOS Mojave

**Comment by paola-machado** [comment]
Hi! I would like to work on this, if that's ok

**Comment by jcfilben** [comment]
Hey @paola-machado feel free to work on this!
