### ISSUE TITLE
Json error on package.json

### ISSUE THREAD

**Issue by IsTheJack** [grommet/grommet#631]
The comma after the last dev depencency is not expected in JSON: (Version 0.6.7)

```
{
  "name": "rush",
  "version": "0.1.0",
  "main": "src/js/index.js",
  "dependencies": {
    "grommet": "0.6.7",
    "react": "^15.0.2",
    "react-dom": "^15.0.2"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-register": "^6.5.2",
    "grommet-toolbox": "^0.1.0",
    "gulp": "^3.9.0",
  }
}

```

**Comment by alansouzati** [comment]
This has been fixed in the latest stable. 

Closing as a duplicated of: https://github.com/grommet/grommet/issues/628

I will release 0.6.8 today to avoid people facing this same issue again, sorry about the inconvenience
