### ISSUE TITLE
Layer - different screen widths cause scrolling freeze on Design System site

### ISSUE THREAD

**Issue by JCoder121** [grommet/grommet#6319]
### Expected Behavior
Users on the DS site should be able to scroll through pages regardless if there is a Modal present on the page.

### Actual Behavior
On DS site pages with Layer components where modal={true} and there is a target, certain screen width sizes cause the entire page to lose scrolling functionality.

### URL, screen shot, or Codepen exhibiting the issue
Screen recording: 

https://user-images.githubusercontent.com/23144209/189726273-5704fa6a-18f8-4c5c-9ac5-0af1ae9d3c39.mov

### Steps to Reproduce

Navigate to the DS site with Modal components, such as this one: https://design-system.hpe.design/templates/content-layouts#content-driven-layouts. While the modal is active, change the width of the window and notice that certain widths will cause the user to lose scrolling functionality.

### Your Environment

- Grommet version: 2.25.3
- Browser Name and version: MacOS Chrome
- Operating System and version (desktop or mobile): MacOS Monterey

**Comment by jcfilben** [comment]
Is this an issue with the Layer component on Grommet or just an issue on the Design System site?

**Comment by JCoder121** [comment]
> Is this an issue with the Layer component on Grommet or just an issue on the Design System site?

I discussed this with Taylor and we are treating it as an issue with the Layer component for now.

**Comment by JCoder121** [comment]
After talking with Jessica about this issue we are actually leaning towards it being on the Design System side. I will try to replicate the issue on Storybook first, to confirm if there are any problem on the Grommet side, and from there debug the DS if necessary.

**Comment by JCoder121** [comment]
Update: I think the root of the issue might be the `containerRef` that is passed in on the DS. Logging it while testing.

**Comment by taysea** [comment]
Removing Jeffrey from this issue for now. He has documented his findings up to this point. Someone else can feel free to pick this up.
