### ISSUE TITLE
Grommet and meteor 1.3

### ISSUE THREAD

**Issue by tierralibre** [grommet/grommet#632]
Hello,

When trying to use grommet with meteor I get an error.
Scss compiler error: File to import:
   {}/src/client/scss/grommet-core/inuit-defaults/settings.defaults not found
   in file: settings

Any ideas on how  to use grommet with meteor? I love the idea but is taking a lot of time just to have it working.

Thank you!

**Comment by alansouzati** [comment]
Hi @tierralibre thanks for trying to integrate Grommet with Meteor. Personally I don't have experience with it, but from your log I think I know what's going on.

How are you doing the SCSS compilation? With webpack (the tool I use), I have to configure the `includePaths` key:

```javascript
   {
        test: /\.scss$/,
        loader: 'style!css!sass?outputStyle=expanded&' +
          'includePaths[]=' +
          (encodeURIComponent(
            path.resolve(options.base || process.cwd(), './node_modules')
          )) +
          '&includePaths[]=' +
          (encodeURIComponent(
            path.resolve(options.base || process.cwd(),
            './node_modules/grommet/node_modules'))
          )
      },
```

For now I added two paths for the SCSS compiler to look for modules:

`./node_modules` and `./node_modules/grommet/node_modules`.

Would love to hear your experience after you get everything working properly. Maybe you can be a guest author in our blog.

**Comment by bryanjacquot** [comment]
@tierralibre any update on this issue?

**Comment by mrrfox** [comment]
Hello,
Succeeded in adding grommet scss with minor modifications in imports (using fourseven:scss)

1. change all instances of import paths pointing to "inuit-**" in node_modules/grommet/scss/grommet-core/..*
_specifically in index.scss, _settings.scss, _base.scss, _objects.scss
eg `@import "inuit-normalize/generic.normalize";`
becomes 
`@import "{}/node_modules/inuit-defaults/settings.defaults";`_

2. add grommet to your main scss, eg : 
`@import '{}/node_modules/grommet/scss/grommet-core/index.scss';`

hope this helps

**Comment by adrianmc** [comment]
@mrrfox Is there no way to get it working without editing files inside `node_modules/grommet`? This feels more like a hack than it should be. I think there needs to be a lot more work to get Grommet ready for everyone, because at this point I have spent hours just trying to understand how to get it setup.

The official docs only show you how to use Bower or the Grommet tool itself to create a new project, but nothing about the stuff we need to require/import to get it working and how to do so.

**Comment by alansouzati** [comment]
Thanks for the feedback @adrianmc. We are working on the new website and I'm going to make sure to cover that in the develop section. would you mind to create a github issue for this matter?

**Comment by adrianmc** [comment]
@alansouzati Sure, but for what exactly?

**Comment by alansouzati** [comment]
Something along this line: "Provide instructions on how to use Grommet without its accompanying development stack (grommet-toolbox)"

**Comment by HaveF** [comment]
@alansouzati Can u tell me what is the `options.base` stands for, and where is come from? does it come from some gulp files? thanks!

```js
   {
        test: /\.scss$/,
        loader: 'style!css!sass?outputStyle=expanded&' +
          'includePaths[]=' +
          (encodeURIComponent(
            path.resolve(options.base || process.cwd(), './node_modules')
          )) +
          '&includePaths[]=' +
          (encodeURIComponent(
            path.resolve(options.base || process.cwd(),
            './node_modules/grommet/node_modules'))
          )
      },
```

**Comment by alansouzati** [comment]
Hi @HaveF I'm sorry if the options are not clear for you. It comes from grommet-toolbox our developer environment. All the options are described here:

https://github.com/grommet/grommet-toolbox#options

If you are not using toolbox, you don't need to use options at all, so your configuration it is going to look like this:

```
 {
        test: /\.scss$/,
        loader: 'style!css!sass?outputStyle=expanded&' +
          'includePaths[]=' +
          (encodeURIComponent(path.resolve('./node_modules'))) +
          '&includePaths[]=' +
          (encodeURIComponent(path.resolve('./node_modules/grommet/node_modules')))
      },
```

Better yet, if you are using NPM version 3+ you can safely rely only on `./node_modules`. So, again, your configuration it is going to look like this:

```
 {
        test: /\.scss$/,
        loader: 'style!css!sass?outputStyle=expanded&' +
          'includePaths[]=' +
          (encodeURIComponent(path.resolve('./node_modules')))
      },
```

**Comment by HaveF** [comment]
@alansouzati thanks for your detailed explanation. :+1:

**Comment by vinaypuppal** [comment]
@mrrfox I followed your instructions and resolved scss errors but i am getting this error in chrome console, nothing is showing up on browser screen and no errors on Terminal. I am running `Meteor 1.4`
`Uncaught Error: Cannot find module 'babel-runtime/helpers/defineProperty'require @ install.js:85`

If i remove this statement `import Grommet from 'grommet';` then no error. Any help on how to use grommet with Meteor 1.4

**Comment by alansouzati** [comment]
can you try running `npm install babel-runtime --save` ?

**Comment by vinaypuppal** [comment]
@alansouzati thanks after installing `babel-runtime` error is gone but got this warning

`modules.js?hash=71c1ee8…:21461 Warning: Invalid argument supplied to oneOf, expected an instance of array.`

Can I ignore this warning or will it cause any issues?

**Comment by alansouzati** [comment]
You can ignore it. It is already fixed in the master branch and will be soon part of a new grommet release

**Comment by alansouzati** [comment]
If you are interested to understand what is the minium set of tools required for grommet to work, please check the grommet-standalone project: https://github.com/grommet/grommet-standalone

**Comment by PranayShah** [comment]
What would be the current best way to use Grommet in a Meteor application (as of `v1.4+`)?
