### ISSUE TITLE
Notification - enhance `message` to allow for node type to be passed

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6320]
The `message` prop for notification only allows a string to be passed. It would be nice to enhance this to allow passing a node. This would enable more customization (for example: having anchors within the notification text).

**Comment by narayand16** [comment]
Hi @jcfilben I would like to work on this enhancement issue. Can you assign it to me ?
what do you mean by 'passing a node" to `message` prop. ? clarity on this will help me solving the issue

**Comment by jcfilben** [comment]
> Hi @jcfilben I would like to work on this enhancement issue. Can you assign it to me ?

Great! I will add you as an assignee on this issue.

> what do you mean by 'passing a node" to message prop. ? clarity on this will help me solving the issue

Currently the `message` prop on Notification only allows a string to be passed to it. The prop should accept either a string or a node. An example of a node that could be passed to the `message` prop could be something like this:

```
message={
  <Box>
    <Text>A message</Text>
    <Anchor label="a link" href="#" />
  </Box>
}
```

Feel free to reach out if more questions come up along the way

**Comment by narayand16** [comment]
Hi @jcfilben Kindly review https://github.com/grommet/grommet/pull/6390

**Comment by jcfilben** [comment]
Closing since #6390 has been merged.
