### ISSUE TITLE
Uncaught type error when pass a null value to Select

### ISSUE THREAD

**Issue by kimkscott** [grommet/grommet#6323]
### Expected Behavior

Updated the Compute Ops Manager UI to grommet 2.25.3.  Expected UI to continue to work as before.

### Actual Behavior

We saw the following uncaught type error in the browser debugger console:

![image](https://user-images.githubusercontent.com/91684949/189983440-dade6aa3-d135-4bbd-a39d-8bcb22aeb795.png)

### URL, screen shot, or Codepen exhibiting the issue

The problem happens when we pass a value of null into Select.  If we pass undefined instead, the problem doesn't happen.  Here is a screen shot of how select is used.

![image](https://user-images.githubusercontent.com/91684949/189984507-3bfe5c2b-ffea-4e75-a22e-271d98e69ec6.png)

I think the problem can be fixed by changing applyKey() at line 9 of Select/utils.js to check that option is not null.  Since null is an object, the function executes Object.keys(option) which throws the type error.

### Your Environment

- Grommet version: 2.25.3
- Browser Name and version: Chrome 105.0.5195.102 
- Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by jcfilben** [comment]
Thanks for reporting this @kimkscott! The fix is available on the [stable branch](https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F) and will be included in the next grommet release

**Comment by halocline** [comment]
Thank you, @kimkscott. Much appreciated.

**Comment by kimkscott** [comment]
Thanks @jcfilben for fixing this so quickly!!  As always, thanks @halocline and @ericsoderberghp for all your help!!
