### ISSUE TITLE
href link within a Button doesn't work in IE11

### ISSUE THREAD

**Issue by lambert-zhang** [grommet/grommet#633]
I have seen grommet Button usage in documents : http://www.grommet.io/docs/hpe/develop/button 
But following usage doesn't work in IE11. When click the button, not any response.
![grommet](https://cloud.githubusercontent.com/assets/16793173/16036369/2b9ce79c-324e-11e6-9efa-4243ea54091d.png)

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/1cb2c24542a0df539edea5b10a5a599b99e5b9a9
