### ISSUE TITLE
DataTable header pin not working with paginate.

### ISSUE THREAD

**Issue by rollsover** [grommet/grommet#6333]
Paginated DataTable in Box container not pins header.

### URL, screen shot, or Codepen exhibiting the issue

[CodeSandbox](https://codesandbox.io/s/grommet-v2-not-working-pin-with-paginate-ctth91)

### Steps to Reproduce

See CodeSandbox.

### Your Environment

- Grommet version: 2.23.0
- Browser Name and version: CodeSandbox
- Operating System and version (desktop or mobile): MacOS

**Comment by jcfilben** [comment]
Closing since #6439 has been merged.
