### ISSUE TITLE
Select with Search Component doesn't clear search string 

### ISSUE THREAD

**Issue by FranGann** [grommet/grommet#6349]
**Expected Behavior**
I would expect that in the Select with Search component that when you click outside the component that the search text would re-initialized to empty.

**Actual Behavior**
When I enter text (to search) in the Select with Search component the list matches the text input which is good, however if I then click outside of the component and then click on the component dropdown icon again the old search is still active, I would have expected it to be cleared.

**URL, screen shot, or Codepen exhibiting the issue**
First image select component
![image](https://user-images.githubusercontent.com/114221831/191925131-450fd3b7-95e6-4355-b9de-dda05fae3e37.png)

When I enter search text of "dd" nothing found, which is fine

![image](https://user-images.githubusercontent.com/114221831/191925387-f3574714-9c34-4dcb-bb08-3eb02a27e661.png)

Then I click outside of the select component and then click the dropdown on the select component and the older search is still active

![image](https://user-images.githubusercontent.com/114221831/191925634-b632e455-277b-40b8-b1eb-39c627284929.png)

### Your Environment

- Grommet version: 2.25.3
- Browser Name and version: Chrome 105.0.5195.127 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Windows desktop

**Comment by halocline** [comment]
You can customize that behavior by using the [onClose](https://v2.grommet.io/select#onClose).

```onClose={() => setOptions(defaultOptions)}```

[Codesandbox demo](https://codesandbox.io/s/select-with-search-onclose-f4uhv0?file=/src/SelectSearchExample.js)

**Comment by FranGann** [comment]
@halocline  , thanks work's fine
