### ISSUE TITLE
Add 'auto' as a `themeMode` to align with users settings preference for light/dark

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6354]
Enhance Grommet's `themeMode` prop to allow 'auto' to be passed as a value. If the `themeMode` is set to auto the mode will align with what the user set as their preferred light/dark mode settings for their computer or browser.

**Comment by AnshumanPadiya** [comment]
Hey there, if this issue is till open and no one is working over it, can I work on this one? I am new to open source and I think this would be a great start for me, so can anybody here assign this issue to me I would be glad to work on it, Thanks!

**Comment by jcfilben** [comment]
Closing, this feature was added in https://github.com/grommet/grommet/pull/6397
Thanks for contributing to Grommet @AnshumanPadiya!
