### ISSUE TITLE
DateInput size prop causing TS error

### ISSUE THREAD

**Issue by elliottkat** [grommet/grommet#6357]
I'm using the DateInput component and want to change the size of the font, as it's quite large by default.  The doc says the size prop needs to be string, but when I enter the value as a string, I get the following TypeScript error:

TS2322: Type 'string' is not assignable to type 'number | undefined'.

Unfortunately, entering a number for this prop does nothing, and the font remains really big and makes the component almost unusable.

### Expected Behavior

If a string is expected, I should be able to use a string.  If a number is required, a number should work to control the size of the font.

### Actual Behavior

I get a TS error and my app doesn't load.  If I specify the size as a number, the font size does not change.

### URL, screen shot, or Codepen exhibiting the issue

A Codepen won't show the TS error.  I've attached a screenshot.

![DateInputSizeTSError](https://user-images.githubusercontent.com/18449274/192848930-36d4c15a-f6b3-4757-99cf-a19e94d237f0.PNG)

### Steps to Reproduce

In a TypeScript project, use DateInput component and attempt to set the size value as a string.

### Your Environment

- Grommet version: 2.18
- Browser Name and version:  Chrome 105.0
- Operating System and version:  Windows laptop

**Comment by jcfilben** [comment]
HI @elliottkat can you try upgrading to the latest version of grommet (v2.26.0)? I created a [codesandbox](https://codesandbox.io/s/react-typescript-forked-4hfgoc?file=/src/index.tsx) to try and reproduce the issue but I wasn't seeing any typescript errors.

**Comment by elliottkat** [comment]
> HI @elliottkat can you try upgrading to the latest version of grommet (v2.26.0)? I created a [codesandbox](https://codesandbox.io/s/react-typescript-forked-4hfgoc?file=/src/index.tsx) to try and reproduce the issue but I wasn't seeing any typescript errors.

Hi, @jcfilben, I did update to 2.26 and it fixed the TS issue, yes.  Thanks!

I did try to play around the codesandbox, but the dependencies wouldn't load.  ☹️ 

I'm still seeing issues with DateInput, in general, though.  I'm using it to allow our user to enter a range of dates.

I've copied the code from the storybook Range Format pretty much identically, with some Box format changes only, and mine is not behaving the same as the storybook.

For example, in the storybook example, if I click in the text input area, I can enter a date without the calendar popping up.  If I click on the calendar icon, only then does the calendar pop up.  If I click the calendar icon again, the calendar closes.

In my implementation, if I click in the date text input area, the calendar pops up and I can't get it to close, even if I click the calendar icon.

Are there known issues with the DateInput component, or are there recommendations you can provide to allow me to make my implementation work for us?

Thanks for your help!

Katherine

**Comment by elliottkat** [comment]
> > HI @elliottkat can you try upgrading to the latest version of grommet (v2.26.0)? I created a [codesandbox](https://codesandbox.io/s/react-typescript-forked-4hfgoc?file=/src/index.tsx) to try and reproduce the issue but I wasn't seeing any typescript errors.
> 
> Hi, @jcfilben, I did update to 2.26 and it fixed the TS issue, yes. Thanks!
> 
> I did try to play around the codesandbox, but the dependencies wouldn't load. ☹️
> 
> I'm still seeing issues with DateInput, in general, though. I'm using it to allow our user to enter a range of dates.
> 
> I've copied the code from the storybook Range Format pretty much identically, with some Box format changes only, and mine is not behaving the same as the storybook.
> 
> For example, in the storybook example, if I click in the text input area, I can enter a date without the calendar popping up. If I click on the calendar icon, only then does the calendar pop up. If I click the calendar icon again, the calendar closes.
> 
> In my implementation, if I click in the date text input area, the calendar pops up and I can't get it to close, even if I click the calendar icon.
> 
> Are there known issues with the DateInput component, or are there recommendations you can provide to allow me to make my implementation work for us?
> 
> Thanks for your help!
> 
> Katherine

Never mind.  It looks like the issues I'm seeing are because we're on an older version of grommet.

**Comment by jcfilben** [comment]
Glad to hear that upgrading to the latest version fixed the issue! I'm going to mark this issue as closed
