### ISSUE TITLE
Meter - Support RTL

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6358]
Enhance the Meter component to support displaying progress from right to left instead of only supporting left to right.
<img width="397" alt="Screen Shot 2022-09-28 at 11 44 56 AM" src="https://user-images.githubusercontent.com/54560994/192852449-59c2afc5-83f8-426d-a1d9-45dcf5376265.png">

**Comment by negreirosleo** [comment]
@jcfilben May I take this issue?

**Comment by jcfilben** [comment]
> @jcfilben May I take this issue?

Absolutely!

**Comment by jcfilben** [comment]
Added in #6398
