### ISSUE TITLE
Using Grommet without Gulp via NPM results in problems resolving SCSS imports

### ISSUE THREAD

**Issue by grantnorwood** [grommet/grommet#636]
Is there any existing documentation on using Grommet without Gulp, and without using the `grommet init` command or `grommet-toolbox`?  The UI components are great, but I'm integrating this into an existing project and don't want to add gulp and all of the other tooling to my existing webpack build system.

After simply installing Grommet via `npm i -S grommet` and rendering the App component, the markup is rendered to the DOM correctly.  *However*, none of the styling is working.  When building, I'm getting errors from Grommet's `_settings.scss` file when including the InuitCSS files, as below:

```shell
@import "inuit-defaults/settings.defaults";
^
File to import not found or unreadable: inuit-defaults/settings.defaults
Parent style sheet: /Users/my-username/my-app/node_modules/grommet/scss/grommet-core/_settings.scss
```

Even after adding the InuitCSS dependencies to my package.json file, I'm not able to resolve those properly because the `@import` statements in Grommet's SCSS files do not use `~` to indicate they should be loaded from node_modules.  I could potentially just copy the SCSS files into my own /lib directory and modify those files to import from the correct location, but that breaks the easy upgrade path that npm provides, and requires more maintenance.

Do you have any recommendations on how I can fix the InuitCSS issues, or any other docs to help me integrate Grommet successfully?  If I can contribute some code to make this work properly, I'm happy to help, but would appreciate some guidance  :)

Thank you so much!

**Comment by alansouzati** [comment]
Which loader are you using for your sass files? The one grommet toolbox is using supports `includePaths`

```javascript
test: /\.scss$/,
    loader: "sass?" +
      'includePaths[]=' +
      (path.resolve('./node_modules')) +
      '&includePaths[]=' +
      (path.resolve('./node_modules/grommet/node_modules')))
```

If you are using NPM >= 3 then you don't need to include `grommet/node_modules` folder as NPM structure is flat instead of nested.

Good luck 👍

**Comment by primozs** [comment]
@grantnorwood 
You can check this project:
<https://github.com/primozs/feathers-react-bojler>
specifically:
```
webpack.config.dev.js
webpack.config.prod.js
package.json
```
Cheers

**Comment by grantnorwood** [comment]
Perfect,that took care of the issue!  I'm using sass-loader ^3.1.2 and npm 3.9.5.  Below is a snippet of my webpack config file, in case it helps anyone else.

```js
module: {
  loaders: [
    { test: /\.scss$/, loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap' }
  ]
},
sassLoader: {
  includePaths: [
    path.resolve('./node_modules/grommet/node_modules')
  ]
}
```

Thank you for such a quick response!

**Comment by dpwren** [comment]
Hi guys. I am having A similar issue with Grommet.  I installed the version from the builder
tool. The builder tool uses gulp. The grommet default page will load; but I get a very red message about Sass nodemodule missing. I see a bunch of boxes on screen, with out style working. In would prefer running this without Gulp. For a newbie I like the create-react app boiler plate from react page. It seems to work the first time, without huge learning curve. I need easy. For the build tool version what to do? For WebpackBabel version I can add sass loader  to webpackconfig file like gentle above question?

**Comment by alansouzati** [comment]
See this for instructions how to run Grommet with create-react-app: https://medium.com/@luce.williamt/using-grommet-with-create-react-app-8e8ddaa836ee#.lmfsxkxc3

**Comment by vladblindu** [comment]
Hello

Are there any undocumented upgrades concerning the customising of grommet themes.
I am using create-react-app and I try to avoid ejecting. It's may 2017. Still no chance....?

**Comment by alansouzati** [comment]
The Grommet recommendation to customize Theme is to use SASS. Unfortunately, it seems that create react app does not allow you to use SASS without ejecting. I'm not an expert on create-react-app, so I may be missing something.

**Comment by vladblindu** [comment]
Thanks a lot for your time. I realised that it doesn't even worth the effort of ejecting and tweaking the webpack config if all you want is theme customising or using theme variables in your own css with Create-react-app. A good ol'SASS watcher is good enough.  
I still find the customising procedure a little clumsy, but overall Grommet is great. Many thanks for your time and effort to create and share such a great tool

**Comment by alansouzati** [comment]
I definitely agree. We don't do a good job on describing the proper steps to customize things.

We will hopefully fix that in Grommet 2.0 👏

**Comment by rardoz** [comment]
I was able to fix this by moving over the stuff in grommet's index.scss to my own sass file to get it working with webpacks sass-loader and sass-resources-loader. This is what my grommet.sass file looks like. The problem was sass-loader requires ~ in front of node_module imports. Grommet doesn't have that type of setup.

```
@import "~grommet/scss/grommet-core/settings"

// Generic
@import "~inuit-normalize/generic.normalize"
@import "~inuit-reset/generic.reset"
@import "~inuit-shared/generic.shared"

// Base
@import "~grommet/scss/grommet-core/base"

// Objects
@import "~grommet/scss/grommet-core/objects"
```

**Comment by JJB1980** [comment]
Having the same issue adding grommet to my project from scratch, webpack is unable to locate inuit files as they don't have ~ prepended.  fixed by going into grommet and modifying the imports, no other suggestions have worked.  this obviously isn't an acceptable resolution.
