### ISSUE TITLE
Value component Proptypes

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#639]
Like in Anchor propTypes where label is defined as ```PropTypes.node``` also in Value component 
props like ```label, value and units``` should be the same, at least to be able to use ```FormattedMessage```:

Instead:
```
Value.propTypes = {
...
  label: PropTypes.string,
  value: PropTypes.oneOfType([PropTypes.number, PropTypes.string]).isRequired,
  units: PropTypes.string
};
```

Maybe like this:
```
Value.propTypes = {
...
  label: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
  value: PropTypes.oneOfType([PropTypes.number, PropTypes.string, PropTypes.node]).isRequired,
  units: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
};
```

I find Value component very usable also without setting value prop:
```
I would suggest also removing isRequired from value prop.
Value.propTypes = {
  label: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
  value: PropTypes.oneOfType([PropTypes.number, PropTypes.string, PropTypes.node]),
  units: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
};
```
Opinions?
Cheers
Primoz

**Comment by alansouzati** [comment]
Agreed with all changes. Are you going to send a PR, or you want us to go ahead and apply it?

**Comment by primozs** [comment]
I can make a PR but tomorrow evening. 
Cheers

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/pull/644
