### ISSUE TITLE
SelectMultiple - pre selected object options not working

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6395]
### Expected Behavior
Options in `value` should should show as selected

### Actual Behavior
In SelectMultiple if `options` is an array of objects and `value` is initially set to one of the options, the option will not show as selected when the drop is open

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-forked-ftppqe?file=/index.js

### Steps to Reproduce

1. Go to codesandbox link above
2. Open the drop and see that the 'xyz' option is not checked

### Your Environment

- Grommet version: codesandbox example used v2.26.0 of grommet but I also confirmed this behavior on the stable branch
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by illiteratewriter** [comment]
Hi, can I work on this?

**Comment by jcfilben** [comment]
Hi @illiteratewriter great to hear your interested in contributing! I actually already started work on this issue, we're hoping to get this one resolved before releasing a new version of grommet so had to move fast on this issue. But feel free to look through the other open issues to see if there is anything you might be interested in working on. Issues labeled 'hacktoberfest' are a good place to start!
