### ISSUE TITLE
Styles not Applied

### ISSUE THREAD

**Issue by KeKs0r** [grommet/grommet#640]
Hi,

I am using grommet together with https://github.com/davezuko/react-redux-starter-kit, but cant get it to work.
In my setup I am loading the styles (which i see that the browser loads the grommet css styles, but somehow they are not applied to the components.
https://github.com/davezuko/react-redux-starter-kit/issues/857

**Comment by alansouzati** [comment]
Hi, to avoid touching other components for an existing app, we only apply styles for components rendered inside a grommet app tag, I'm assuming you are not using it?

```
<Grommet.App>
  //grommet components here.
</Grommet.App>
```

**Comment by KeKs0r** [comment]
I was wrapping my whole application in `<Grommet.App>` do I only need to wrap the Grommet Components?

**Comment by alansouzati** [comment]
if you are already wrapping then I don't know why it is not applying the styles 😭 

Can you look in the chrome console and provide additional clues to us?

**Comment by KeKs0r** [comment]
So this is my component I am testing with:
```javascript
        <App inline={true}>
          <Meter value={40} type="arc" size="small" a11yTitleId="meter-title-21" a11yDescId="meter-desc-21" />
        </App>
```

I can see that some styles from grommet are applied:
![image](https://cloud.githubusercontent.com/assets/2970814/16160441/74914282-34c8-11e6-81d8-994d7ec72d4a.png)

But I think there is still something missing, since the rendered components look like this:
![image](https://cloud.githubusercontent.com/assets/2970814/16160450/868cf058-34c8-11e6-818a-56554c7add3f.png)

I am importing the Styles in my main.scss
```
 @import '~grommet/scss/hpe/index';
```

**Comment by alansouzati** [comment]
how are you including the sass in your app?

it seems to me that you are using a sass loader? Are you using webpack?

**Comment by KeKs0r** [comment]
I am using the sass loader and the configuration from the https://github.com/davezuko/react-redux-starter-kit

And my config for scss loading is based on the default with this little adaption: davezuko/react-redux-starter-kit#857

**Comment by bryanjacquot** [comment]
Related to #567 being investigated.

**Comment by bjackson** [comment]
Any update on this? I have the same issue, I had to resort to manually including the stylesheet, which needs alterations to include `~` before the inuit include.

**Comment by alansouzati** [comment]
For now, there are two ways to include styles for Grommet components:

1. Importing the SASS file in your index.js and configure webpack to look for the modules inside `node_modules` and `node_modules/grommet/node_modules`. See includePaths options for sass-loader: https://github.com/jtangelder/sass-loader#sass-options

2. Import the minified css for each of the themes in your index.html.

We are evaluating CSS modules, Css in JS, and other approaches to simplify loading styles in a modular and self-contained manner. Checkout the grommet-simple project for an example of the work that is currently being developed. https://github.com/grommet/grommet-simple

**Comment by Beelal** [comment]
Import of minified css apply the structure attributes like padding/margin but colors are not applied to the component.

For e.g. colorIndex doesn't work. 
<Section colorIndex="brand"></Section>

I am using:
import 'grommet/grommet-hpe.min.css';

**Comment by alansouzati** [comment]
grommet-standalone has been created and it should be available for reference on how to use grommet with webpack

https://github.com/grommet/grommet-standalone

**Comment by Beelal** [comment]
Thanks a lot @alansouzati 
I will try that out and let you know.

**Comment by creephanger** [comment]
Hi! I've had this same issue... tried grommet css and it worked... `https://github.com/mvanlonden/grommet-css
