### ISSUE TITLE
When the form validation is type of blur , then for the <DateInput />  , we can’t select two different dates

### ISSUE THREAD

**Issue by mahanthiarun-kumar** [grommet/grommet#6415]
When the form validation is type of blur , then for the <DateInput format="mm/dd/yyyy-mm/dd/yyyy"/>  , we can’t select two different dates ! But it works fine for   validation is type of submit . Is this something expected ? 
### Expected Behavior

When the form validation is type of blur , then for the <DateInput format="mm/dd/yyyy-mm/dd/yyyy"/>  , we  should be able to select two different  dates !

### Actual Behavior

When the form validation is type of blur , then for the <DateInput format="mm/dd/yyyy-mm/dd/yyyy"/>  , we can’t select two different dates 

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/dateinput-controlled-forked-t9qf06?file=/index.js

### Steps to Reproduce

1.Create a form with validation type as blur
2. Add a DateInput component with format as  'mm/dd/yyyy-mm/dd/yyyy'
3.  Try selecting two different dates of different months (25th September  2022 and 25th  December 2022)

### Your Environment

- Grommet version:  2.26.0
- Browser Name and version: chrome (106.0.5249.91 (Official Build) (arm64)
- Operating System and version (desktop or mobile): desktop

**Comment by marcioflaviof** [comment]
I'll create a PR soon

**Comment by jcfilben** [comment]
> I'll create a PR soon

Sounds good! Thanks for working on this
