### ISSUE TITLE
DataTable: Missing custom offset property for pinned header's z-index

### ISSUE THREAD

**Issue by stephanpelikan** [grommet/grommet#6428]
I built a calendar table using DataTable:

![datatable](https://user-images.githubusercontent.com/5190548/195995106-47a409c8-8c7c-4d79-9070-08c0c19ef10f.png)

Each day is a cell which consists of a separate DataTable for the hours. The black hours' tables header shows the day's date to the user and is pinned. Therefore on scrolling downwards the current day's date is always visible on top.

My application allows to select periods (see orange area with blue border). As you can see, I have overlappings (e.g. avatar). Since latter HTML elements overlap former elements, I had to define a z-index for each hour of the selection from top to bottom (3, 2, 1). Otherwise, for example, the second orange cell would overlap the lower area of the avatar.

The problem is now, as you can see in the screenshot, that the pinned header is not in front of the selection indicator elements. To make this work the pinned needs it's own z-index which is greater then those of the orange selection-indicator. Unfortunately, the z-index of pinned headers is already set: https://github.com/grommet/grommet/blob/master/src/js/components/DataTable/StyledDataTable.js#L170.

I tried to define a negative z-index but this hides the content of my cells behind the table. Maybe there is a workaround but I didn't find one.

### Expected Behavior

DataTable has a possibility to define a z-index offset which is added to the z-indexes as part of creating the table like the z-index for pinned headers.

### Actual Behavior

No possibility to adopt the z-indexes.

### Steps to Reproduce

Define Boxes using a z-index as part of rendering a cell.

### Your Environment

- Grommet version: 2.25.1
- Browser Name and version: Chrome 106.0.5249.119 (Offizieller Build) (64-Bit)
- Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by jcfilben** [comment]
Hi @stephanpelikan I'm wondering if you could define the z-index for pinned cells within the `dataTable.pinned.body.extend` prop in the theme

**Comment by stephanpelikan** [comment]
Thank you for this hint @jcfilben. It seems `dataTable.pinned.body.extend` is not applied but `dataTable.pinned.header.extend` is and that solved the problem! It produces this:

![grafik](https://user-images.githubusercontent.com/5190548/196346865-5e05612c-d03d-4966-9a40-a3a662f3230d.png)

Actually, I saw the code in the https://github.com/grommet/grommet/blob/master/src/js/components/DataTable/StyledDataTable.js#L170 before and since the z-index is calculated somehow I didn't want to override it with a fixed value. I don't understand the purpose of `${Object.keys(props.pin).length}`. For me it always returns 1 so it seems to be safe to override it at least in my situation.

If you can explain I would appriciate but for me the issue solved.

**Comment by jcfilben** [comment]
I believe that `${Object.keys(props.pin).length}` is used to give pinned items a z-index of 1 so that pinned columns appear on top of un-pinned columns
