### ISSUE TITLE
SelectMultiple - show 'Select All' button when searching

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6444]
### Expected Behavior
When SelectMultiple is being filtered by a search term a 'Select All' button should still appear.

### Actual Behavior
The 'Select All' button is removed on search.

### URL, screen shot, or Codepen exhibiting the issue
https://storybook.grommet.io/?path=/story/input-selectmultiple-default--default

### Steps to Reproduce
1. Visit the story at the link above
2. Type something into search
3. 'Select All' button is removed

### Your Environment

- Grommet version: v2.27.0
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
Additionally, I should be able to chain together multiple search+select-all steps. For example, in the "Default" story for SelectMultiple, I should be able to do the following:
- search for "p"
- Select All selects "Apple", "Grape", and "Raspberry"
- clear search and search for "w"
- Select All adds "Strawberry" and "Kiwi" to the existing selection, resulting in 5 options selected

I wonder if we should be clearer by re-labelling the control when there is a search, perhaps something like "Select All Matches" and "Clear All Matches"?

I think this means that:
- if there is no value, the control is "Select All", regardless of search content
- if there is any value and no search content, the control is "Clear All", 80% case I think
- if there is a value and search content and any matched options are selected, the control is "Clear All Matches" and it clears only the options that matched the search
- if there is a value and search content and no matched options are selected, the control is "Select All Matches" and it adds the options that matched the search to the existing selection.
-

**Comment by pyuktha** [comment]
@ericsoderberghp I have a usecase where I dont want "Select All" to appear in any of the case because we are loading the options onMore (lazy loading)
Since i had a "search", "Select All" was not showing up, and my use case was working
I think there should be a prop to enable/disable "Select All"

**Comment by pyuktha** [comment]
Yes, correct!
I thought with this issue changes/fixes, "Select All" will show up always
so, just reconfirming
Thanks!
