### ISSUE TITLE
Box "round" prop not respecting whether its responsive 

### ISSUE THREAD

**Issue by carolineartz** [grommet/grommet#6445]
It is not currently possible to disable the responsive adjustments for border-radius on `Box` with `responsive={false}`. 

### Expected Behavior
The size for `round` should reference the responsive value unless `responsive={false}` is set.

### Actual Behavior
The size for the `round` prop always references the responsive value when given a non-object type value. 

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-forked-d914qf

### Steps to Reproduce

1. create a box 
2. set responsive to false
3. give it round prop with a string value
4. resize the screen (should see radius not change, but it does).

### Your Environment

Codesandbox env has the bug.

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by carolineartz** [comment]
The problem is with this line of code that gets the size value when the prop's value is not an object. It does not check whether the argument `responsive` is `true`.

https://github.com/grommet/grommet/blob/a828bc158a447b100f3db25ac2e1e0ec9a6474c0/src/js/utils/styles.js#L748

unlike this working line which is called when the prop is an object and does check 

https://github.com/grommet/grommet/blob/a828bc158a447b100f3db25ac2e1e0ec9a6474c0/src/js/utils/styles.js#L645-L649

I am happy to take out a PR for this if that is desirable!

**Comment by jcfilben** [comment]
Hi @carolineartz thanks for filing this issue! It makes sense to me that if you set `responsive=false` the desired behavior is most likely that you don't want the round prop to behave responsively. I am supportive of this change. @ericsoderberghp (or anyone else) any objections or concerns?

**Comment by jcfilben** [comment]
@carolineartz Feel free to go ahead and file a pull request for this if interested
