### ISSUE TITLE
SelectMultiple - Gap between number of items selected and search box is chnaging

### ISSUE THREAD

**Issue by pyuktha** [grommet/grommet#6447]
### Expected Behavior

The height of the content above the search box should not change

### Actual Behavior

When we use SelectMultiple component with search, the distance between the text "<no_of_items> selected" and search box keeps changing
This is happening mainly when we set the dropHeight property

### URL, screen shot, or Codepen exhibiting the issue

Video demonstrating the issue:

https://user-images.githubusercontent.com/97274194/197175692-549cd4ae-158d-4fb6-adb7-77d97d9d837c.mov

### Your Environment

- Grommet version: 2.27.0

**Comment by ericsoderberghp** [comment]
Related to https://github.com/grommet/grommet/issues/6444
