### ISSUE TITLE
Menu component inline property change state

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#645]
When on custom responsive logic you want to change inline property on Menu component it is not working by updating menu props. For menu component to refresh its state you need to manually call.
```
// in parent component lifecycle method
this.refs.menu.setState({inline: true}); 
```

**Comment by phuson** [comment]
Can you please attach some sample code of how you are trying to change the Menu component's props in the parent component so we can properly reproduce the issue? Thanks!

**Comment by ericsoderberghp** [comment]
I suspect the issue is that Menu's `componentWillReceiveProps` isn't handling the case where the caller "manually" changes the `inline` property.

**Comment by primozs** [comment]
@phuson Hi, I am sorry but I did not see your message.
I would want to change the "inline" property  in render method when new set of properties arrive. 
```
This is what I would like
<Menu
          size="small"
          dropAlign={{right: 'right', top: 'top', direction: 'right'}}
          responsive={false}
          inline={this.props.inlineNav}
          direction={this.props.directionNav}>

```
This is what I have to do now.
Now I have to use state to use Menu and I have to manually trigger set state on menu.
```
  componentWillReceiveProps(nextProps) {
    this.calcScreen(nextProps);
  }
```

```
  calcScreen(props) {
    if (width <= browser.breakpoints.extraSmall) {
       // I have to manually set menu state
      this.refs.menu.setState({inline: false});
      this.setState({
        inlineNav: false,
        directionNav: 'column'
      });
    } else {
      this.refs.menu.setState({inline: true});
      this.setState({
        inlineNav: true,
        directionNav: 'row'
      });
    }
```

```
// render
<Menu
          ref="menu"
          size="small"
          dropAlign={{right: 'right', top: 'top', direction: 'right'}}
          responsive={false}
          icon={<Actions colorIndex="brand"/>}
          inline={this.state.inlineNav}
          direction={this.state.directionNav}>
```
