### ISSUE TITLE
DropProps does not include 'pad' but it actually works

### ISSUE THREAD

**Issue by stephanpelikan** [grommet/grommet#6467]
The DropProps interface does not include the 'pad' property, but just using it works as expected luckily.

### Expected Behavior

DropProps includes `pad?: PadType;`.

### Actual Behavior

Typescript-error, but pad is applied. I need to as `@ts-ignore`.

### URL, screen shot, or Codepen exhibiting the issue

```tsx
            <DateInput
                format={ t('date_format') }
                value={ parseLocalDate('2022-10-29')?.toISOString() }
                onChange={ () => {} }
                icon={ <History /> }
                dropProps={ {
                    align: { top: "bottom", right: "right" },
                    background: 'white',
// @ts-ignore
                    pad: isPhone ? 'medium' : 'small',
                    width: isPhone ? '90%' : '25rem',
                    height: isPhone ? '50%' : '25rem',
                    responsive: true
                  } }
                calendarProps={ {
                    fill: true,
                    animate: false,
                  } } />
```

### Steps to Reproduce

Use example above.

### Your Environment

- Grommet version: 2.25.1
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Windows desktop

**Comment by britt6612** [comment]
@stephanpelikan you are correct `pad` is available would you be willing to make a PR by adding the `pad` to our TS definitions?

**Comment by britt6612** [comment]
closing since PR #6467 was merged
