### ISSUE TITLE
 Color contrast voilence in Form/AggregateValidation.

### ISSUE THREAD

**Issue by jashanshah33** [grommet/grommet#6470]
Expected Behavior
  no voilence

 Actual Behavior
 Color contrast voilence in Form/AggregateValidation.

URL, screen shot, or Codepen exhibiting the issue
![color contrast](https://user-images.githubusercontent.com/104054121/198923681-37d70e02-dfa0-48e0-aa86-8ea61e0f19ad.png)

 Steps to Reproduce
 color="status-error" needs a update.

**Comment by jcfilben** [comment]
Note: contrast issue is in both the grommet and hpe themes.
