### ISSUE TITLE
rowDetails in datatable seems to be incorrectly typed in typescript

### ISSUE THREAD

**Issue by mrmagcore** [grommet/grommet#6477]
rowDetails takes a function as its argument.  For example:

rowDetails={(row) => {return <Box>I am a box</Box>;}} 

Typescript throws this error:

TS2769: No overload matches this call.
  Overload 1 of 2, '(props: DataTableExtendedProps<Funding> | Readonly<DataTableExtendedProps<Funding>>): DataTable<...>', gave the following error.
    Type '() => JSX.Element' is not assignable to type 'ReactNode'.
  Overload 2 of 2, '(props: DataTableExtendedProps<Funding>, context: any): DataTable<Funding>', gave the following error.
    Type '() => JSX.Element' is not assignable to type 'ReactNode'.

To fix it, I have updated src/js/components/DataTable/index.d.ts  

I replace line 86 with this:

rowDetails?: (row: TRowType) => React.ReactNode;

**Comment by britt6612** [comment]
@mrmagcore thank you for reporting would you be willing to make a PR with these changes for our TS definitions in DataTable?

**Comment by mrmagcore** [comment]
I don't know how to do a pull request.  I messed around with it for a while,  but didn't get it to work.  It's just one line of code,  hopefully you folks can add it in.  Sorry

**Comment by britt6612** [comment]
@mrmagcore no worries I can do it..
if you ever want to make a contribution we are always here to help.
https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md#submitting-code-pull-requests
