### ISSUE TITLE
Box breaks when using border="between" and a gap size in pixels

### ISSUE THREAD

**Issue by shb** [grommet/grommet#6485]
The Box component breaks at runtime when specifying this two properties:
```
border="between"
gap="10px" // or any other size in px
```
which are both legit values according to the docs.

### Expected Behavior

The Box component applies half the value of _gap_ around the separator line.

### Actual Behavior

The Box components throws:
```
TypeError: Cannot read properties of undefined (reading 'match')
```

### URL, screen shot, or Codepen exhibiting the issue

![Screenshot 2022-11-09 at 18 14 51](https://user-images.githubusercontent.com/642896/200898655-3435f323-fe71-4188-a47a-e82d2d51aaad.png)

### Steps to Reproduce

1. Go to https://v2.grommet.io/box
2. Assign `border="between"` to the Box
3. Assign `gap="10px"` to the Box
4. Watch for the 💥 

### Your Environment

- Grommet version: 2.11.4, 2.27.0
- Browser Name and version: any (Chrome, Firefox, Safari)
- Operating System and version (desktop or mobile): macOS 12.6

**Comment by umeshiscreative** [comment]
Hi @shb,
I checked and found you need to pass the correct props to the Box Component for the gap.
Gap will work if you pass the correct prop value to it.
I am sharing the gap props value

<img width="171" alt="GapProps" src="https://user-images.githubusercontent.com/36879900/201534359-2a8b12b2-6729-4f5e-ac8d-0db01eb77f8e.PNG">


```Javascript
 <Box direction="row" gap="medium" border="between" pad="medium">
    <Box pad="small" background="dark-3">
      Test 1
    </Box>
    <Box pad="medium" background="light-3">
      Test 2
    </Box>
  </Box>
```

Output:
<img width="161" alt="GapOutput" src="https://user-images.githubusercontent.com/36879900/201534431-9ef0cf7c-9b5c-477d-ab72-645a9d5d0917.PNG">

Thanks,
Umesh

**Comment by britt6612** [comment]
@umeshiscreative @shb 
This is still a bug even though it works with passing correct t-shirt sizing to `gap` our `gap` should still accept any CSS size. 

<img width="616" alt="Screen Shot 2022-11-13 at 3 21 39 PM" src="https://user-images.githubusercontent.com/42451602/201547488-571d1459-908c-4a0c-84b3-5e8b2e19f610.png">

**Comment by shb** [comment]
@britt6612 thanks a lot for the quick response. As I commented in the PR, I found a deeper issue in the border between implementation: it assumes that numeric gap values are always _px_ disregarding the unit specified by the user. On the other hand the `gap` implementation itself seems to honour the unit of measure, probably because it only copies the value around without doing any math on it.
