### ISSUE TITLE
RangeInput within FormField is off center

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6487]
### Expected Behavior
The RangeInput should be centered and contained within the FormField

### Actual Behavior
The RangeInput extends beyond the edge of the FormField and is not centered. Note this is happening in both the grommet and hpe themes but it is easier to see in the hpe theme.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-forked-jhtmrp?file=/index.js

<img width="332" alt="Screen Shot 2022-11-09 at 1 36 09 PM" src="https://user-images.githubusercontent.com/54560994/200936467-45549a69-cf3a-4910-933e-60daa65fcc2b.png">

### Steps to Reproduce

1. See codesandbox above

### Your Environment

- Grommet version: 2.27.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile):

**Comment by umeshiscreative** [comment]
Hi @jcfilben,
I checked this and found there is a default user agent style adding the extra margin to the Range Input Component.
As mentioned below.

<img width="694" alt="RangeInputIssuePNG" src="https://user-images.githubusercontent.com/36879900/201529105-99e90e78-875b-4159-9c6b-e03bfa6e30c6.PNG">

It can be removed as a default margin set to `0px` or `unset`.

<img width="503" alt="RangeInputSol" src="https://user-images.githubusercontent.com/36879900/201529230-b8b8bf6a-4a30-41d0-b280-23362c2924a5.PNG">

Thanks,
Umesh

**Comment by jcfilben** [comment]
Hi @umeshiscreative thanks for looking into this! Would you be willing to file a PR to add 
 `margin: 0px` to StyledRangeInput?

**Comment by umeshiscreative** [comment]
@jcfilben Sure, I will raise a PR for this.
