### ISSUE TITLE
DataTable - column search causes jumpy header text

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6493]
### Expected Behavior
When selecting the search icon within a column header the text should remain vertically in the same position.

### Actual Behavior
The header text jumps upwards when the search is selected.

### URL, screen shot, or Codepen exhibiting the issue

https://user-images.githubusercontent.com/54560994/201755397-9765bd79-d532-4d02-a511-71d3715e1ae9.mp4

### Steps to Reproduce

This issue can be seen in the [DataTable/Served](https://storybook.grommet.io/?path=/story/visualizations-datatable-served--served-data-table) story by clicking on the search icon

### Your Environment

- Grommet version: 2.27.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile):

**Comment by umeshiscreative** [comment]
Hi @jcfilben, Can you please provide a codesandbox for this?

**Comment by jcfilben** [comment]
Here is a codesandbox: https://codesandbox.io/s/grommet-v2-template-forked-7u1ssu?file=/index.js.

This example can also be viewed in the storybook [DataTable/Served](https://storybook.grommet.io/?path=/story/visualizations-datatable-served--served-data-table) story.
