### ISSUE TITLE
Box' gap not removed on wrapping

### ISSUE THREAD

**Issue by stephanpelikan** [grommet/grommet#6499]
When using Box with `gap` and `wrap` and `justify="center"` the `StyledBoxGap` is not removed on wrapping.

### Expected Behavior

Gaps at wrapped lines have to be removed.

### Actual Behavior

Gaps are not removed and appear as a left-margin in the next line and sometimes as a right-margin of the previous line (depending on the width of the content and the width of the window).

### URL, screen shot, or Codepen exhibiting the issue

With this codesandbox all the problems can be reproduced: https://codesandbox.io/s/box-gap-wrap-issue-e9xgyl

Here also some screenshots to give you an idea:

With no needless gap because no wrapping is necessary:
![gap-wrap-issue1](https://user-images.githubusercontent.com/5190548/202187345-023cae2f-71e6-4115-8103-2e3c97b1d9c6.png)

With needless gap placed right-side next to box "Fifth" and box "Six" is centered as it should be:
![gap-wrap-issue2](https://user-images.githubusercontent.com/5190548/202187414-44775a92-e4c5-4ea1-a61c-c362fe966c71.png)

With:
* needless gap placed left-side next to box "Sixth" and boxes "Third" to "Fifth" are centered as it should be:
* needless gap placed left-side next to box "First" because for sample 1 `direction="row-reverse"` is used.
![gap-wrap-issue3](https://user-images.githubusercontent.com/5190548/202188012-f56ba2af-c9f8-47dd-b51c-8c5a00ed970c.png)

### Steps to Reproduce

Load the sandbox and resize the window the reproduce the problem.

### Your Environment

- Grommet version: 2.25.1
- Browser Name and version: FireFox 107.0
- Operating System and version (desktop or mobile): Ubuntu 22.04

**Comment by vishal400** [comment]
May I know why its using StyledBoxGap component? Can't we use gap property on styledBox itself and remove StyledBoxGap.

**Comment by umeshiscreative** [comment]
Hi @stephanpelikan,
If we pass a prop to the StyledBoxGap and use this prop inside the Styled Box as below:

<img width="453" alt="Gap2" src="https://user-images.githubusercontent.com/36879900/202897514-27caeee1-c35c-4049-a2b5-a34a472240af.PNG">

<img width="619" alt="Gap1" src="https://user-images.githubusercontent.com/36879900/202897525-9c438934-51b7-4c2c-97b4-bce238913db7.PNG">

Then I will resolve your expectation, I hope so.

Output:
Normal Window

<img width="957" alt="GapOp1" src="https://user-images.githubusercontent.com/36879900/202897581-16ffa627-0cec-48c7-86ec-4821d6167c81.PNG">

After Resizing it

<img width="948" alt="GapOp2" src="https://user-images.githubusercontent.com/36879900/202897589-d46ff266-e5b2-4e6f-a4ab-15aa6d53862d.PNG">

Thanks,
Umesh

**Comment by vishal400** [comment]
@umeshiscreative gaps at wrapped lines need to be removed, not every gap after resizing.

**Comment by stephanpelikan** [comment]
@umeshiscreative : I'm sorry, I not aware of the total consequences of your suggestion since I'm just a user of Grommet. What I can see is, that the gap is gone in your screenshots 2, 3 and 4 what would not be OK.

**Comment by umeshiscreative** [comment]
> @umeshiscreative : I'm sorry, I not aware of the total consequences of your suggestion since I'm just a user of Grommet. What I can see is, that the gap is gone in your screenshots 2, 3 and 4 what would not be OK.

Hi @stephanpelikan, What I am thinking is, Instead of removing the _gap_ element from the **DOM tree**, I am reducing its width.
Can you explain a little bit more?

Thanks,
Umesh

**Comment by stephanpelikan** [comment]
OK, got it. But I need that gap. If I define margins or paddings it will also be used at the outer boundaries (towards the window-boundaries) which means even if two boxes would still fit the screen it will show only one because of that margin (of course depending on the size of the boxes and the margins).

Anyway, this is good hint and I will check if this helps me with my layout as a workaround for now. But the reported bug needs to be solved. It doesn't make sense to use a framework and then try to workaround the framework ;-)

**Comment by ericsoderberghp** [comment]
I understand the intent of the issue. Unfortunately, the current implementation of `gap` does not work with `wrap`, as is documented at https://v2.grommet.io/box#gap. A better approach would be to use https://developer.mozilla.org/en-US/docs/Web/CSS/gap, which came into being last year. It's not as easy though as just changing the current Box implementation to use it as the CSS property applies to DOM elements while the current grommet Box approach applies to react children of the Box. When a Fragment is used for a child, react will expand the Fragment's children when rendering in the DOM. So, it would not be backwards compatible to do a straight change. Instead, I think we need to find a way to let the caller opt-in to the new CSS method. On suggestion would be use the `options` property of Grommet: https://v2.grommet.io/grommet#options to support something like `options={{ box: { gap: 'css' } }}`.

**Comment by jcfilben** [comment]
Solved by https://github.com/grommet/grommet/pull/6181

**Comment by stephanpelikan** [comment]
Awesome! I'm looking forward to the next release :-)
