### ISSUE TITLE
FormPin icon imported in themes/base although removed from grommet-icons causes build error

### ISSUE THREAD

**Issue by dherault** [grommet/grommet#6502]
### Expected Behavior

FormPin has been removed from grommet-icons hence should be removed from `themes/base`

### Actual Behavior

A Rollup output gave me this:
![image](https://user-images.githubusercontent.com/4154003/202327311-a0a90af4-cc88-4cc5-8dec-5c85892d51a0.png)

### Steps to Reproduce

- Install grommet
- Build it in any app

### Your Environment

- Grommet version: 2.27.0
- Operating System and version (desktop or mobile): MacOS latest

**Comment by dherault** [comment]
Was a dependency mismatch issue on my side

**Comment by dherault** [comment]
Fix: `rm -rf node_modules` then `npm install`

**Comment by dherault** [comment]
Nope, that didn't fix it, reopening.

**Comment by dherault** [comment]
Grommet depends on grommet-icons 4.7.0, if grommet-icons 4.8.0 is also installed, the error happens.

**Comment by dherault** [comment]
Fix for yarn: 
```json
"resolutions": {
  "grommet/grommet-icons": "4.8.0"
}
```

**Comment by dherault** [comment]
Submitting a PR to fix this.

**Comment by dherault** [comment]
No need, just needs to publish the latest dev grommet version which has grommet-icons 4.8.0 as a dep

**Comment by jcfilben** [comment]
This should be resolved with the new release, v2.28.0 of grommet.
