### ISSUE TITLE
Anchor - icon only Anchor has extra spacing

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6507]
There is extra space below the icon in the Anchor

### URL, screen shot, or Codepen exhibiting the issue

<img width="861" alt="Screen Shot 2022-11-14 at 1 17 50 PM" src="https://user-images.githubusercontent.com/54560994/203176984-a7dcd74e-dc79-4751-9436-6786c766ae85.png">

### Steps to Reproduce

Inspect the first Anchor in the Anchor/Color story to see the extra space https://storybook.grommet.io/?path=/story/controls-anchor-color--color

**Comment by umeshiscreative** [comment]
**Output:**
Anchor component with default usage.

<img width="312" alt="AnchroTag1op" src="https://user-images.githubusercontent.com/36879900/204095024-b3aa63b6-416e-4ca6-854d-0db019a15652.PNG">

Anchor component with passing the props.

<img width="428" alt="AnchroTag2op" src="https://user-images.githubusercontent.com/36879900/204095030-3e94b673-c004-4764-b3b9-1481e149f156.PNG">

**Comment by jcfilben** [comment]
Resolved by #6534
