### ISSUE TITLE
Select's type definition shouldn't include the `readOnly` prop

### ISSUE THREAD

**Issue by anuraghpe** [grommet/grommet#6509]
### Expected Behavior
If Select is marked as readOnly, user should not be able to change options.

### Actual Behavior

readOnly has no effect.

### Steps to Reproduce

https://v2.grommet.io/select?c=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKRAbwChFEIEBnKRAbQDd1cR8AaRO-KAGrtOAXUQBeRACV86aADoQfAMpR0UIgHJM+ACYwQmTcQDcVROYBO-EJaSFz1ADwAxOJcwuY+XLsS50ACMfcU1lGAAvfE1Ea3RdAHkwXABPAD4LaizEJ2UffGhHbN5I-HEyNg58AF8i7LhsWHpypk06THZcTR5tPQMjHoDLAHNokVrirMrOcumauqyEAGEAC3QwUfLCMkQGpqRq0nEMvkFhIj34MGIJydjZROSUhYB6NKKnF7cPLx9dd+opgo1SAA

### Your Environment

- Grommet version: 2.27.0
- Browser Name and version: Edge 107 
- Operating System and version (desktop or mobile): Win 10 Desktop

**Comment by jcfilben** [comment]
Grommet doesn't currently support a readOnly prop for Select. Would you be willing to share a bit more about your use case (for example, what is making the select read only, will it always be read only, why not use a TextInput with `readOnly`, etc.)?

**Comment by anuraghpe** [comment]
Interesting. I think I can use a TextInput with `readOnly` in my use case, it will always be `readOnly`. Is there is a plan to support `readOnly` with Select in future? I guess the typescript definitions are incorrect for Select then.

**Comment by jcfilben** [comment]
> Is there is a plan to support readOnly with Select in future?

Currently there is not a plan to support `readOnly` on Select, but if someone gives us a use case that requires it, I think we can re-evaluate.

> I guess the typescript definitions are incorrect for Select then.

Yes, currently the `readOnly` prop is included in the typescript definition. This is coming from `JSX.IntrinsicElements['input']`. We should adjust this to omit the `readOnly` prop.
