### ISSUE TITLE
[IE 11] One view global dashboard, the message displays not well when setting DHCP

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#651]
Description:
Change network settings Static to DHCP, the message on the right bottom doesn't wrap in IE 11. The display in Chrome and Firefox is good.

OVGD build Version:
OVGD-SSH_1.00.00_253682

IE:
![image](https://cloud.githubusercontent.com/assets/16797825/16291616/6fe27f90-393b-11e6-82b7-8bc4524ec527.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/16797825/16291706/64acbe82-393c-11e6-9c2a-27db61a2ebcf.png)

**Comment by epilande** [comment]
@christinHP Setting `full="horizontal"` on the `Box` component will allow the content to wrap in IE. 
`<Box full="horizontal" ... />`

Another way to fix this issue is to remove the wrapping `Footer` component.
