### ISSUE TITLE
[IE 11] The grommet Split layout is wrong

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#652]
The grommet Split is used in src/js/components/appliances/Appliances.js, the right pane width in IE 11 is much shorter than in chrome and firefox. So the Split layout is wrong.

Please view the appliance detailed page, "Real-time updates enabled for the appliance" is truncated on IE11, but the layout in Chrome and Firefox is good.

OVGD build version:
OVGD-SSH_1.00.00_253488

![image](https://cloud.githubusercontent.com/assets/16797825/16291907/84849ee4-393e-11e6-9a81-cb4acb2acc3b.png)

**Comment by alansouzati** [comment]
Fixed. We will soon release grommet-index and this fix will be available.
