### ISSUE TITLE
Type for select value isn't right

### ISSUE THREAD

**Issue by mrmagcore** [grommet/grommet#6522]
This is the current type declaration for Select:

export interface SelectProps extends BasicSelectProps {
  clear?: boolean | { position?: 'top' | 'bottom'; label?: string };
  closeOnChange?: boolean;
  defaultValue?: string | number | object | (string | number | object)[];
  multiple?: boolean;
  selected?: number | number[];
  value?: string  | JSX.Element | object | (string | number | object)[];
}

but the docs say that value can be a number too, so I would recommend updating components/Select/index.d.ts to say this.

export interface SelectProps extends BasicSelectProps {
  clear?: boolean | { position?: 'top' | 'bottom'; label?: string };
  closeOnChange?: boolean;
  defaultValue?: string | number | object | (string | number | object)[];
  multiple?: boolean;
  selected?: number | number[];
  value?: string  | number | JSX.Element | object | (string | number | object)[];
}

I'd file a pull request, but I don't know how.

**Comment by jcfilben** [comment]
Thanks for reporting, I agree we should update the `value` type to include number. If you are interested you can checkout the [contributing guide](https://github.com/grommet/grommet/blob/master/CONTRIBUTING.md) for some info on how to get started contributing to grommet (including how to file a pull request).
