### ISSUE TITLE
Opened by default, collapsible does not do the animation

### ISSUE THREAD

**Issue by jotacib3** [grommet/grommet#6523]
### Expected Behavior

It should be closed with the smooth animation

### Actual Behavior

It should be closed with the smooth animation, however it is closed roughly (only the first time)

### URL, screen shot, or Codepen exhibiting the issue
`

    const CustomCollapsible= ({
        totalQuestionsCount,
        questionSummaries,
    }) => {
    const [open, setOpen] = useState(true);

    return (
        <Box>
            <BasicButton
                basic
                onClick={() => setOpen((prevState) => !prevState)}
            />
            <Collapsible open={open}>
                {questionSummaries.map(({ description }, index) => (
                    <ExamResultsTabDetailsQuestionDetails
                        key={uniqueId()}
                        idQuestionSummaries={index + 1}
                        description={description}
                        totalQuestionsCount={totalQuestionsCount}
                        isTopHr
                    />
                ))}
            </Collapsible>
        </Box>
    );
  };

`

### Your Environment

- Grommet version: 2.21.0
- Browser Name and version: Microsoft Edge, Version 107.0.1418.62 (Official build) (64-bit)
- Operating System and version (desktop or mobile): Windows 11 Home,  Version 21H2

**Comment by jcfilben** [comment]
For anyone else looking at this issue here is a [codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-g1lurw?file=/index.js) that reproduces it.
