### ISSUE TITLE
Scroll issue with Layer + target

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#6532]
### Expected Behavior

When Layer has a target, the contents should be able to scroll if the content is longer than the target's height.

### Actual Behavior

The Layer scroll is glitchy/blocked. I noticed that if I make the window height smaller than the length of the layer content, then the scroll works. Makes me think the scroll is keying off of window height instead of target height?

### URL, screen shot, or Codepen exhibiting the issue

https://user-images.githubusercontent.com/12522275/206305955-72219722-fbcb-4b33-9ad7-de6da89501e3.mov

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: Stable
- Browser Name and version: Mac Chrome 108 
- Operating System and version (desktop or mobile): MacOS Monterey

**Comment by jcfilben** [comment]
I think this is solved by https://github.com/grommet/grommet/pull/6632
