### ISSUE TITLE
[IE11] The grommet Footer align="start" doesnt' work in IE11

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#654]
Description
Hewlett Packard Enterprise logo should be left aligned. The Footer align="start" works well in Chrome and Firefox, but it's no useful in IE11.

          <Footer direction="column" align="start"
            pad={{ horizontal: 'medium', vertical: 'small' }}>
            <HPELogo size="small" />
            &copy; 2016 Hewlett Packard Enterprise Company, L.P.
          </Footer>

Steps to Reproduce
1. Access OVGD via IE11.
2. Go to log in page.
3. Verify that the Hewlett Packard Enterprise logo is not left aligned.

Build Version
OVGD-SSH_1.00.00_253488.ova

![image](https://cloud.githubusercontent.com/assets/16797825/16332433/73818108-3a28-11e6-9a50-22bfa2a7abe7.png)

**Comment by epilande** [comment]
@christinHP this issue looks like it's been fixed.

![image](https://cloud.githubusercontent.com/assets/3210082/16487878/20567d86-3e69-11e6-9e20-0f08ad8b87f3.png)

**Comment by christinHP** [comment]
@epilande  yes, it's fixed.
