### ISSUE TITLE
Position matters in object array used in select

### ISSUE THREAD

**Issue by mrmagcore** [grommet/grommet#6541]
Object element order shouldn't matter.  However, in select, this is not the case.

This code should work, but doesn't show the selected value in the select box:
      <Select
        options={[
          { title:"moose", id: 2 },
          { title:"beaver", id: 4 }
        ]}
        valueKey={{ property: "value", reduce: true }}
        labelKey="title"
        // value={4}
        defaultValue={4}
      />

This code does work
      <Select
        options={[
          { id:2, title:"moose" },
          { id:4, title:"beaver" }
        ]}
        valueKey={{ property: "value", reduce: true }}
        labelKey="title"
        // value={4}
        defaultValue={4}
      />

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-forked-ld3uon?file=/index.js:203-453

furthermore, it would be nice to be able to have an object like this:

[{title: "moose", id:2, description: "a large horse with antlers"},
{title: "beaver", id: 4, description: "flat-tailed water raccoon"}]

and tell select that value is the "id" element and text is the "title" element

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
I think the issue here is that it should be `valueKey={{ key: 'id', reduce: true }}`. That matches the documentation for 'valueKey': https://v2.grommet.io/select#valueKey and seems to be working in this fork of your sandbox: https://codesandbox.io/s/grommet-v2-template-forked-lvr3ws?file=/index.js

**Comment by mrmagcore** [comment]
It's not working in that fork of the sand box.  The key feature is that the select box does not show the initial value if the object is ordered "title,id", but does work if the object order is "id, title"   If you set up the object to look like this:[
          {  id: 2, title: "moose" },
          { id: 4,title: "beaver" }
        ]
you will see that "beaver" is selected when the page loads.  If the order is reversed, it is not selected.

**Comment by ericsoderberghp** [comment]
Perhaps I didn't save the sandbox. Can you check it again? It is showing "beaver" for me.

**Comment by mrmagcore** [comment]
Ah, yes, it's working now.
The weird thing is that it worked at all with valueKey={{ property: "value", reduce: true }}
I got that from some code someone posted on the grommet slack channel in response to my questions about this.

**Comment by ericsoderberghp** [comment]
I think it's because it is using the first key in the object for the value when no `key` is specified in `valueKey`. That's why the order mattered. Would probably have been better to log a message for a case like this. But, that would break compatibility at this point.

**Comment by mrmagcore** [comment]
Thanks for chasing down my weird dead-end issue.  I appreciate it!
