### ISSUE TITLE
[IE11] The grommet table td onClick function doesn't work

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#655]
Reproduce steps:
1. login 16.125.107.167 with IE11,  administrator/hpvse123
2. Switch to dashboard page, search appliance, input string "christin", press button "enter"
3. it will jump to search page, there is one row about appliance
4. Click the row, the onClick function _onClickTR won't be trigged.
5. Click other place, like other row location. then click back to the appliance row
6. The overview page will be opened.

![image](https://cloud.githubusercontent.com/assets/16797825/16335074/48870374-3a37-11e6-86bb-bf2f13dc020a.png)

**Comment by epilande** [comment]
This is related to #648. 

I'm not able to do any action(click/scroll) on the search page until I click on something else.

![655](https://cloud.githubusercontent.com/assets/3210082/16511876/0e73eff8-3ef1-11e6-970e-d1149af5ea7f.gif)
