### ISSUE TITLE
typescript declaration for valueKey doesn't match docs.

### ISSUE THREAD

**Issue by mrmagcore** [grommet/grommet#6554]
The select and selectmultiple components have documentation for ValueKey that says:

{
  key: "string",
  reduce: boolean
}

but the typescript declaration is this:

  valueKey?:
    | string
    | { property: string; reduce?: boolean }
    | ((...args: any[]) => string);

which is it, key or property?

**Comment by jcfilben** [comment]
Looking at the `Select/index.d.ts` file I am seeing 'key' being used, not 'property'. This matches the docs and the `Select/propTypes.js` file.

<img width="324" alt="Screen Shot 2023-01-03 at 1 42 44 PM" src="https://user-images.githubusercontent.com/54560994/210438237-c02897de-753d-4d46-a362-1778056204a8.png">

**Comment by mrmagcore** [comment]
Huh.  Maybe I changed it myself after Jessica Filben gave me a code sample that used "property".
