### ISSUE TITLE
Cursor got misplaced and list automatically scrolls down when we have large number of items in List with Selection

### ISSUE THREAD

**Issue by gaurav-intelligaia** [grommet/grommet#6574]
### Expected Behavior
When we select an item in List with selection, that item should be selected and cursor should not get misplaced

### Actual Behavior
When we select an item, list scrolls down and cursor position got misplaced to some other item in the list.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/suspicious-mccarthy-g94eib?file=/src/List.js

### Steps to Reproduce

1. Render List with Selection having large number of items in list so that we have scroll.
2. Select any item in the list For instance Item1
3. The cursor scrolls down and pointing to some other item in the list.

### Your Environment

- Grommet version: 2.25.3
- Browser Name and version: 108.0.5359.124
- Operating System and version (desktop or mobile): macOS Monterey Version 12.6

**Comment by MikeKingdom** [comment]
When the List onClick happens it does a .focus() on the List container for WCAG accessibility reasons. Anytime .focus() on the container happens the browser tries to scroll the container to be as much in the viewport as possible (it can scroll to the bottom in some cases too). This happens even if you simply use the Tab key to move keyboard focus to the List. In the case of Tab, Grommet code isn't calling .focus. It simply happens from built in keyboard traversal.

I'm still looking into if this is necessary/avoidable.

**Comment by MikeKingdom** [comment]
Added as part of #4364

**Comment by gaurav-intelligaia** [comment]
@MikeKingdom this should be avoided because it is causing issues when we are trying to implement the double click functionality in the list.

**Comment by MikeKingdom** [comment]
> @MikeKingdom this should be avoided because it is causing issues when we are trying to implement the double click functionality in the list.

@gaurav-intelligaia  Yup. I believe we can remove it.
