### ISSUE TITLE
List - key render story error

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6588]
### Expected Behavior
Storybook stories shouldn't have any console errors

### Actual Behavior
The list key render storybook story has the following error: `Encountered two children with the same key`

### URL, screen shot, or Codepen exhibiting the issue
<img width="315" alt="Screen Shot 2023-01-19 at 11 35 55 AM" src="https://user-images.githubusercontent.com/54560994/213531009-da8742a0-8b44-429b-b38a-6531beb7274d.png">

### Steps to Reproduce

1. Run storybook locally
2. Navigate to the List/Key render story
3. Open the console

### Your Environment

- Grommet version: 2.29.0
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by MadhurSikko** [comment]
@jcfilben I would like to be assigned this issue, can you give a little more insight as I am relatively new to open source? I was able to replicate the issue in List/Key_Render.
