### ISSUE TITLE
Failed to parse json when running npm init

### ISSUE THREAD

**Issue by activescott** [grommet/grommet#659]
Using grommet 0.6.7 from npm and encounter this error when trying to run `npm init` on the sample app:

    npm WARN Failed to parse json
    npm WARN Trailing comma in object at 16:3
    npm WARN   }
    npm WARN   ^
    npm WARN File: /Users/scott/src/bitcoin-mining-calculator-grommet/package.json
    npm WARN bitcoin-mining-calculator-grommet No description
    npm WARN bitcoin-mining-calculator-grommet No repository field.
    npm WARN bitcoin-mining-calculator-grommet No README data
    npm WARN bitcoin-mining-calculator-grommet No license field.

Steps to reproduce
* Follow the steps under Get Going < NPM at http://www.grommet.io/docs/develop/get-started and this will happen at the end of running `grommet init` or if you go to the directory and run `npm init`.

Workaround:
* Go to package.json and remove the comma after the last field in the `devDependencies` object. Then everything works fine.

**Comment by alansouzati** [comment]
Sorry about that. it has been fixed already. we will release a new version soon.

**Comment by activescott** [comment]
No worries @alansouzati! Thanks for the prompt response.
