### ISSUE TITLE
DataSearch component enhancements

### ISSUE THREAD

**Issue by JCoder121** [grommet/grommet#6597]
## Acceptance Criteria

- [ ] DataSearch component enhanced to adapt across resolutions

### Expected Behavior
When on smaller resolutions, the DataSearch component should collapse to a DropButton. On user's click, it should expand to its original size to show the user's input text. Additionally, the DataSearch component should have a set default width or allow the user to set its width using the components properties, rather than requiring the user to wrap DataSearch in a box and set width there.

Expected DropButton interaction: 
![image](https://user-images.githubusercontent.com/23144209/214194122-cbb5af36-8215-4c60-9feb-35151ce7f19a.png)
![image](https://user-images.githubusercontent.com/23144209/214194148-1df9d856-e499-410f-bb7b-51dcd7155ff7.png)

Expected width:
![image](https://user-images.githubusercontent.com/23144209/214194180-a8f8a4a7-7930-4b19-9317-377adac2396b.png)

### Actual Behavior
Small resolution (no dropbutton):
![image](https://user-images.githubusercontent.com/23144209/214194325-e3e2d696-4120-4856-91b4-2345cbbd3924.png)

DataSearch width:
![image](https://user-images.githubusercontent.com/23144209/214194348-7ea73589-bba2-4bbc-8a3d-934249710220.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ericsoderberghp** [comment]
Half of this was done via https://github.com/grommet/grommet/pull/6624.
Still need to consider the Button only behavior.
