### ISSUE TITLE
Sliding Animation for Layer component

### ISSUE THREAD

**Issue by sagar-go** [grommet/grommet#6608]
### Expected Behavior

There is no way for user to select custom animation. It should support custom animation or overwrite already existing animation. We need a way to add custom animation or modify existing animation.

There is a requirement where modal should animate from right of the screen to the center. Current default property for 'Position' prop is 'Center' which brings our Layer/Modal to the center of screen and if we select 'Right' then it is animating from Right side of the screen to edge of the screen. 

Current animation for Position 'Right' is : 0% {
    -webkit-transform: translate(100%,-50%);
    -ms-transform: translate(100%,-50%);
    transform: translate(100%,-50%);
}
100% {
    -webkit-transform: translate(0,-50%);
    -ms-transform: translate(0,-50%);
    transform: translate(0,-50%);
}

According to requirement it should be : 0% {
    -webkit-transform: translate(100%,-50%);
    -ms-transform: translate(100%,-50%);
    transform: translate(100%,-50%);
}
100% {
    -webkit-transform: translate(-50%,-50%);
    -ms-transform: translate(-50%,-50%);
    transform: translate(-50%,-50%);
}

By this way it will slide to the center of the screen.

### Actual Behavior

Existing animation which comes from 'Position' property is causing issues and overwriting any custom animation.

### URL, screen shot, or Codepen exhibiting the issue

- Grommet version: "^2.26.0",
- Browser Name and version: Chrome 109.0.5414.119
- Operating System and version (desktop or mobile): Windows 10

https://user-images.githubusercontent.com/100475830/215069718-910e00f4-8f68-48ed-8085-f3fb4efe4eb2.mp4

**Comment by sagar-go** [comment]
@jcfilben Is there any update on this or any workaround you can suggest?

**Comment by jcfilben** [comment]
Hey @sagar-go sorry for the slow response on this issue! Anyway, you can set `animation={false}` on Layer and then using styled components define your own custom animation. Here is a codesandbox example that shows how to do this: https://codesandbox.io/s/grommet-v2-template-forked-hiu3hs?file=/index.js. Let me know if this solution works for you.

**Comment by jcfilben** [comment]
Hey @sagar-go just checking in to see if this solution worked for you. If so I think we can close this issue.

**Comment by jcfilben** [comment]
Hopefully the above solution worked for you, I'm going to mark this as closed.
