### ISSUE TITLE
Border between fails to show as a property array

### ISSUE THREAD

**Issue by hwdsjtu97** [grommet/grommet#6640]
When use `border: [{side: "between"}]`, the between border won't display
### Expected Behavior
The between border should display as `border: between`

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/s/grommet-v2-template-forked-ru6opq?file=/index.js

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment]
Solved in #6642
