### ISSUE TITLE
Form validation of a nested property in form value

### ISSUE THREAD

**Issue by varungupta85** [grommet/grommet#6652]
This is in continuation of issue #6520. I am not allowed to reopen the issue, so I am opening a new issue. Please feel free to close this one and reopen the previous one if that will be easier.

Dear @jcfilben I am sorry that I completely missed out on your messages. I checked the changes that you made to the sandbox. I see that you have mainly removed the `value` and `onChange` props on the `Select` field which seems to have fixed the issue with the validation. But now, when I making any changes to the start and end time of a shift config, it is not updating the `shiftConfigs` array present in `escalationPolicy` present in the `value` but creating a new property called `escalation.shiftConfigs` and updating that. Why can't we keep the `value` and `onChange` props so we have more control over how the change are stored but still use the validation based on the current value of the form value.

Please refer to the below screenshot
![image](https://user-images.githubusercontent.com/7475133/221135477-512e989b-b31e-47de-b2c7-ee2c27327bd9.png)

Observe that the `value` object has a new property called `escalationPolicy.shiftConfigs` which is an array with 2 elements and the original `escalationPolicy` object is still empty.

**Comment by Jittojoyes98** [comment]
Heyy can i work on this issue ?  Iam new to this project , will need some help.

**Comment by jcfilben** [comment]
Hey @varungupta85 I think there may be an issue with how the onChange at the Form level is setup. When I remove `value` and `onChange` from the Form, but leave them at the FormField level both the validation and console output is as expected. I think the issue might be that when you setup the value variable with useState you declare an object, `escalationPolicy`. Later when you are saving the start time a new `escalationPolicy` object is created and the new value is set to the old value plus the new escalationPolicy.
```
setValue({
      ...value,
      escalationPolicy: { shifts: newShifts }
    });
```

**Comment by jcfilben** [comment]
Hey @Jittojoyes98 glad to hear you are interested in contributing! For this issue I'm not sure yet if any changes will need to be made in grommet yet... In the meantime while we wait for a little more info feel free to look at other issues in grommet, the 'good first issue' or 'help wanted' labels are good starting places, but contributions on other issues are welcome as well. Feel free to just drop a comment or reach out on the grommet slack channel if any help is needed along the way

**Comment by Jittojoyes98** [comment]
Yeah thanks !

**Comment by varungupta85** [comment]
@jcfilben thanks for investigating the issue further.

> When I remove value and onChange from the Form, but leave them at the FormField level both the validation and console output is as expected.

What do you mean by the above? How do I add the `value` and `onChange` to the `FormField`? Would it be possible for you to update the sandbox you created to show what you changed?

```
setValue({
  ...value,
  escalationPolicy: { shifts: newShifts }
});
```

Isn't this how I should be updating the `escalationPolicy`? Wouldn't the `escalationPolicy` in the `value` be overwritten by the new value? If I don't provide the `value` and `onChange`, then `grommet` is incorrectly adding the shift as key `escalatiionPolicy.shifts` instead of keeping it as an object.

**Comment by jcfilben** [comment]
Hey @varungupta85 here is an updated version of the codesandbox: https://codesandbox.io/s/grommet-v2-template-forked-io1vjq?file=/index.js. I adjusted the value to flatten escalationPolicyShifts, it seems like forms don't work well when you try to use object notation for the field name. Some related threads:
https://stackoverflow.com/questions/63819997/in-html-name-objectprop-doesnt-seem-to-work?noredirect=1&lq=1
https://stackoverflow.com/questions/40162911/js-object-notation-in-html-input-name

In the `onSubmit` code I adjusted the value to print in the desired format. Once the form is submitted you can adjust the data received to be in the desired format

**Comment by varungupta85** [comment]
@jcfilben Thanks for the solution and good to know that object notations don't work well for form field name. I will avoid using nested objects in the form value and keep the data flat.
