### ISSUE TITLE
DataTable border does not get applied to checkbox column

### ISSUE THREAD

**Issue by raywong-fb** [grommet/grommet#6657]
### Expected Behavior

When using the `border` prop of `DataTable` the specified border should also apply to the checkbox cell that renders when `onSelect` is provided.

### Actual Behavior

The border does not extend to the checkbox cell.

### URL, screen shot, or Codepen exhibiting the issue

I think this screenshot is self explanatory, but I can create a CodeSandbox if needed

![image](https://user-images.githubusercontent.com/77302368/222214585-8c84457f-567e-48d3-8ab4-d1ce526e4329.png)

### Steps to Reproduce

1. Implement DataTable using `border` w/ `onSelect`
```
<DataTable border={{ body: { side: 'bottom' } }} onSelect={() => {}} />
```
2. Observe that the bottom border does not extend to the checkbox cell.

### Your Environment

- Grommet version: tested on both 1.27.0 and 1.30.0
- Browser Name and version: Chrome (latest)
- Operating System and version (desktop or mobile): Mac OSX Ventura, Desktop

**Comment by jcfilben** [comment]
Hmm that does seem odd, I agree that it would make more sense for the border to extend all the way across including the checkbox column. Marking this as a bug.

Here is a codesandbox for anyone else looking at this issue: https://codesandbox.io/s/grommet-v2-template-forked-ny8fcv?file=/index.js
