### ISSUE TITLE
grommet minor release to support HPE theme release

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet#6658]
Need to be merged/fixed before releasing:
- [x] https://github.com/grommet/grommet/issues/6674

Ensure that there is a test for every bug fix and enhancement
Changes that did not include tests:

Extra areas to manually test:
https://github.com/grommet/grommet/pull/6666
https://github.com/grommet/grommet/pull/6665

Storybook:
- [x] Chrome (hpe theme) - Matt
- [x] FireFox (grommet theme) - Taylor
- [x] Safari (hpe theme) - Taylor

Grommet site:
- [x] Make sure any changes from release are included in docs and remove 'stable' flags

Grommet Designer:
- [x] Check that any new props/components have been added to grommet designer

Release Process:

- [x] Release notes 
- [x] Contributors

**Comment by jcfilben** [comment]
Update 3/10: While checking storybook various issues with the NEXT-stable version of the HPE theme came up. The plan is to look into those a little more today and evaluate if it would make sense to move forward with the grommet release or if there is potential for changes needed on grommet to resolve the issues we are seeing in the hpe theme.

**Comment by taysea** [comment]
WIP Release notes: https://docs.google.com/document/d/1tG8pHMNNjpsWKW4Yutr0tO2498FrivEk5CVNAZ1nC1s/edit?usp=sharing

**Comment by taysea** [comment]
v2.31.0 has been released.
