### ISSUE TITLE
[eslint] Parsing error: The keyword 'import' is reserved

### ISSUE THREAD

**Issue by heyjared** [grommet/grommet#666]
I'm getting this error on the first import statement of any js file on grommet@0.6.6 (since 0.6.7 is having issues with `npm install`)

**Comment by alansouzati** [comment]
what is your node and npm version? es6 is enabled via babel that should be installed in both 0.6.6 and 0.6.7

**Comment by alansouzati** [comment]
I was able to reproduce your issue.

For some weird reason the `.babelrc` is not present in the init command anymore. This will be fixed in the upcoming 0.6.8.

In the meantime, can you create in the root of your project a `.babelrc` file with the following content?

```
{
  "presets": [ "es2015", "react" ],
  "plugins": [
    "transform-object-rest-spread",
    "add-module-exports"
  ]
}

```

**Comment by heyjared** [comment]
That file is already present in my project. Using grommet@0.6.6 I ran `grommet init sample-app` and without changing any files, I get the error above. I'm using node v6.2.2, npm 3.9.5 on OS X 10.11.5. I'm using a local copy of eslint (not installed globally). I'm running Visual Studio Code 1.2.1 using the ESLint extension.

**Comment by alansouzati** [comment]
Thanks for the detailed explaination. Are you able to run `gulp dist`? In other words do you get the same issue in the command line?

**Comment by alansouzati** [comment]
Also can you try to validate the suggestion in this issue

https://github.com/yannickcr/eslint-plugin-react/issues/447#issuecomment-184617282

**Comment by heyjared** [comment]
I was able to run `gulp dist` without any issues. 

I've found that adding .eslintrc.json to the root directory solves the problem.

**Comment by alansouzati** [comment]
The weird thing is that in the commad line works. It feels to me this is an IDE specific issue.

**Comment by heyjared** [comment]
Well, thanks for helping me through this regardless. I'm not sure why it doesn't work by default, but having the .eslintrc.json there works.

**Comment by alansouzati** [comment]
cool. closing the issue. welcome to grommet. we invite you to join our slack channel for live support.

http://slackin.grommet.io
