### ISSUE TITLE
Clear Filters control promoted to top level component instead of embedded in Data

### ISSUE THREAD

**Issue by JCoder121** [grommet/grommet#6660]
### Expected Behavior

From Filtering With Select example: https://design-system.hpe.design/templates/filtering?q=filtering#filtering-with-select, and
Filtering With Layer: https://design-system.hpe.design/templates/filtering?q=filtering#filters-in-a-center-layer
'Clear Filters' button should appear whenever the user interacts with a Data Toolbar component (Filter, Search, etc)

<img width="702" alt="image" src="https://user-images.githubusercontent.com/23144209/222529887-8376c322-3d45-4043-817a-95809e335197.png">
<img width="953" alt="image" src="https://user-images.githubusercontent.com/23144209/222529928-c43da507-7baa-4f12-85a1-16474ead8df5.png">

### Actual Behavior

'Clear Filters' button is missing when the user interacts with the Data Toolbar components as mentioned above.
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/23144209/222530191-ca13e16d-6d8c-4d4d-8b81-4c4fabf0211e.png">
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/23144209/222530437-1941e393-accb-4a1f-b217-350a31eb3165.png">

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by taysea** [comment]
@halocline I'm trying to understand the desire here. Is this still a valid issue given some of the direction to enforce the toolbar anatomy a bit more?

**Comment by halocline** [comment]
Promoting "Clear fliters" to top level should allow for clearing "quick filters" in addition to filters contained when `<DataFilters />` has `drop` or `layer`.

"Clear filters" should be available as a smart default and as a composable element.

**Comment by taysea** [comment]
After diving in to this work, here are some questions/behaviors we should be sure to solve for or file tickets for future enhancements:

The use case driving some of this discovery is when you might have DataSearch + one exposed filter + more filters hidden behind a layer:

![Image](https://github.com/grommet/grommet/assets/12522275/64303f87-1e74-496b-bc9a-b0cf4e786d35)

- [ ] To get the label above a DataFilter, you need to wrap DataFilter in DataFilters. So, is it okay to have multiple `DataFilters`?
- [ ] Functionally, you can have a DataFilter outside of DataFilter and the filtering still works. What then is the specific purpose of DataFilters (we should document this)?
- [ ] If you have an exposed filter, you likely want the filtering to `updateOn="change"` but if you have the rest of the filters in a drop/layer then you likely would want filtering to `updateOn="submit"`. Should `updateOn` be available at the level of `DataFilters` as well for compositional use cases?
- [ ] If caller is using their own `ClearFilters` control, there needs to be a way for them to turn off the ClearFilters that is built into DataFilters. What should this prop be called on DataFilters? `showClearFilters`?
- [ ] If the caller is using their own `ClearFilters` control, should it always render by default and allow the caller to determine their own logic for when to hide it (such as when no filters are applied) or should `ClearFilters` have internal logic to hide itself when no filters are applied (similar to what is already happening in the DataFilters logic)?
- [ ] Should `ClearFilters` be wrapped in a Box with flex={false} the way it is in DataFilters? If so, where should the `{...rest}` props spread (seems like the internal button would be ideal, but breaks common conventions)?
- [ ] Need a way for ClearFilters to have access to the `setTouched` handler from DataFilters
