### ISSUE TITLE
DataView should persist View state on window re-render

### ISSUE THREAD

**Issue by JCoder121** [grommet/grommet#6661]
### Expected Behavior

Upon re-render (ex: resize the window in a way that forces DataView to re-render), DataView should stay on the selected View.

### Actual Behavior

DataView returns back to the default view upon re-render

1. "Paused" View is chosen
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/23144209/222531338-466c658a-069c-4921-b40e-273e2ba4e72b.png">

2. When window is resized, DataView returns to default "Select View" state
<img width="644" alt="image" src="https://user-images.githubusercontent.com/23144209/222531485-ef17b725-637e-4fe3-a7a0-32878691e85d.png">
 

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by Jittojoyes98** [comment]
Heyy, can this be an easy fix ? Can i work on this ?

**Comment by jcfilben** [comment]
@JCoder121 I'm not seeing this issue on the [DataView/simple](https://storybook.grommet.io/?path=/story/data-dataview-simple--simple) story. Is this issue just happening on the design system site?

@Jittojoyes98 love the enthusiasm! Still working out if we need to make any changes on grommet for this issue or if it is just something in the implementation that needs adjusted.

**Comment by JCoder121** [comment]
@Jittojoyes98 Thanks for the enthusiasm as well! It's looking like this is a grommet-related issue.

@jcfilben I think I might've worded my initial issue a bit vaguely, but playing around with the DataView/simple story a bit more I was able to get it to re-render like in the video recording below. 

https://user-images.githubusercontent.com/23144209/223178415-b8879db0-502c-4731-946e-45a91dc1ceb1.mov

**Comment by JCoder121** [comment]
Closing the issue on grommet repo, tracking inside hpe-design-system repo here: https://github.com/grommet/hpe-design-system/issues/3197

**Comment by JCoder121** [comment]
> Fine, any work around for this? Where should i start

Closing the issue related to grommet repo for now as it is looking like DataView behaves as expected, but Example container on the hpe-design-system repo is causing issues.
