### ISSUE TITLE
FormFields don't flex anymore in 2.30.0

### ISSUE THREAD

**Issue by kariwhitcomb** [grommet/grommet#6669]
### Expected Behavior

We have a layout with multiple FormFields inside a Box with direction='row'.  With version 2.29.1 and earlier of grommet, these FormFields would flex, so if the wrapping Box was narrow, the fields would narrow too.  Wider Box/screen, and the FormFields would expand.

### Actual Behavior

In Version 2.30.0, the FormFields no longer flex.  They seem to use a default width and will overflow the Box if it is too narrow

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/nifty-james-9yvrku?file=/src/App.js
This is setup with 2.29.1 in the dependency, but you can switch to 2.30.0 with the same code and see the change in behavior.

This may be related to https://github.com/grommet/grommet/issues/6626

### Steps to Reproduce
```
<Grommet theme={hpe}>
      <Box direction="row" gap="medium">
        <FormField label="Input 1">
          <Select options={options} />
        </FormField>
        <FormField label="Input 2">
          <Select options={options} />
        </FormField>
        <FormField label="Input 3">
          <Select options={options} />
        </FormField>
        <FormField label="Input 4">
          <Select options={options} />
        </FormField>
      </Box>
    </Grommet>
```

### Your Environment

- Grommet version: 2.30.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Mac

**Comment by ericsoderberghp** [comment]
This is a result of adding `flex={false}` to FormField as part of https://github.com/grommet/grommet/pull/6634. The key is that FormField should conceptually have `flex={false}` when laid out vertically, to avoid compressing them. But, they should not have that when laid out in a horizontal flexbox. I think the right short term behavior is to revert the change to FormField to restore compatibility and then revisit later how to address the vertical aspect.
