### ISSUE TITLE
New markdown-to-jsx version

### ISSUE THREAD

**Issue by yaycmyk** [grommet/grommet#668]
Hey @alansouzati! Just wanted to drop a friendly heads-up that a new major version (3.x) of https://github.com/yaycmyk/markdown-to-jsx is out. Here are the behavioral changes you'll want to be aware of:

- __Implement proper handling for "tight" lists__ In the case of a "tight" list--meaning a markdown list with no padding newline between entries--the inner paragraph generated by the AST parser is now automatically stripped out as expected.

- __Automatically remove the root `<div>` wrapper for singular children__  The root `<div>` is now discarded for all scenarios where there is only one top-level element. This prevents the need to add a class to all the wrappers to make them inline or change the block flow.

Cheers and thanks for using the module!

**Comment by alansouzati** [comment]
Nice. I will work on upgrading Grommet to the latest markdown-to-jsx 👍

**Comment by bryanjacquot** [comment]
Fixed in https://github.com/grommet/grommet/commit/68cbef30cc2b06a620880a81778d4c9d6fd5e961
