### ISSUE TITLE
DataTable ignoring primaryKey prop

### ISSUE THREAD

**Issue by jwlsinx** [grommet/grommet#6688]
The data rows created by `DataTable` are ignoring `primaryKey` and using the row index as the key instead.

### Expected Behavior

`<DataTable columns={columns} data={DATA} primaryKey="id" />` should use the `id` property (`DATA.${idx}.id`) as the row key.

### Actual Behavior

The index of the row is use as the row key.

https://codesandbox.io/s/datatable-infinite-scroll-using-index-as-key-w4d1e5?file=/index.js

<img width="825" alt="image" src="https://user-images.githubusercontent.com/5133128/225747009-20e4b8bf-f39b-4cd8-98f6-332325ece268.png">

### Your Environment

- Grommet version: 2.30.0
- Browser Name and version: Chrome 111.0.5563.64
- Operating System and version: MacOS Desktop

**Comment by stephanpelikan** [comment]
👍
