### ISSUE TITLE
Skeleton type is missing from the published grommet/index.d.ts

### ISSUE THREAD

**Issue by coltonw** [grommet/grommet#6700]
### Expected Behavior

When I do `import { Skeleton } from "grommet";` it should just work.

### Actual Behavior

`import { Skeleton } from "grommet";` gives me an error: `Module '"grommet"' has no exported member 'Skeleton'.ts(2305)`

### URL, screen shot, or Codepen exhibiting the issue

You can just look in the file and see Skeleton isn't there: https://unpkg.com/browse/grommet@2.30.0/index.d.ts

### Steps to Reproduce

Call `import { Skeleton } from "grommet";` from a typescript file.

### Your Environment

- Grommet version: 2.30.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): macOS Monterey

**Comment by britt6612** [comment]
@coltonw good catch would you mind adding it to that file and submitting a PR?
