### ISSUE TITLE
Datatable with disable property throws error when user navigates within table page & clicks row immediately

### ISSUE THREAD

**Issue by namrathasingura30** [grommet/grommet#6703]
### Expected Behavior

When user navigates from one page of table with **disabled property** to another & clicks the table row immediately, Datatable should not error out.

### Actual Behavior

When user navigates from one page of table with **disabled property** to another & clicks the table row immediately, Datatable error out with subscription_key(primary key) undefined causing UI to turn blank.

### URL, screen shot, or Codepen exhibiting the issue

https://user-images.githubusercontent.com/97277166/227408847-b81438f5-610a-4934-b348-509a5443e82d.mov

<img width="1512" alt="Screenshot 2023-03-24 at 8 45 35 AM" src="https://user-images.githubusercontent.com/97277166/227415396-0a41e0c6-b753-4c56-b612-8a15c9f07064.png">

```
<DataTable
              pagination={{
                totalItems: totalSubscriptions,
                itemsPerPage,
                page,
                setPage
              }}
              grid={{
                columns,
                data: viewData,
                height: 'medium',
                disabled: [],
                onSort: ({ property, direction, external }) => {
                  setSortByParam({ property, direction, external })
                  setPage(1)
                },
                sort: sortByParam
              }}
              selection={{
                onSelectionChange: (selectedRow) => {
                  setErrorMsg('')
                  handleSelectRow(selectedRow)
                },
                primaryKey: 'subscription_key'
              }}
              testId="select-license-table"
/>
```

### Steps to Reproduce

1. Go to any datatable which has diabled property & pagination
2. Navigate to another page of datatable and quickly click on row before data gets loaded into the page
3. Datatable will error out inturn causing UI to go blank

### Your Environment

- Grommet version: 2.27.0
- Browser Name and version: Chrome Version 111.0.5563.64 (Official Build) (arm64)
- Operating System and version (desktop or mobile): desktop MacOS

**Comment by ericsoderberghp** [comment]
I've been trying to reproduce this by adding `disabled` and `onClickRow="select"` to this story: https://storybook.grommet.io/?path=/story/visualizations-datatable-paginated--paginated
But, I cannot get it to reproduce.

Also, the properties shown in the source above: `grid` and `selection` aren't part of the DataTable API: https://v2.grommet.io/datatable
Is this a wrapper on the grommet DataTable?

Would you be able to provide some more guidance on how to reproduce the issue? Is there any lazy loading of the paginated data involved?

**Comment by namrathasingura30** [comment]
`grid` and `selection` are the prop in UI component which inturn will be supplied to grommet table.

But I did try to use Datatable & Pagination component directly from Grommet & still see this issue. Below is a code snippet. 
   ```
import React, { useState, useEffect } from 'react'
import { Box, DataTable, Pagination } from 'grommet'

const TagsDataTable = () => {
  const [tags, setTags] = useState([])
  const itemsPerPage = 10
  const [page, setPage] = useState(1)
  const { oidcUser } = useReactOidc()
  const [totalTags, setTotalTags] = useState(0)
  const columns = [
    {
      property: 'name',
      header: 'Name',
      primary: true
    },
    {
      property: 'created_by',
      header: 'Created By'
    }
  ]

  useEffect(() => {
  // API call to fetch the date when user clicks on next page
  // if success response -> set tags here
 setTags(response.data)
  }, [page])

  return (
      <Box pad={{ horizontal: 'xxsmall', top: 'small' }}>
        <DataTable
          columns={columns}
          data={tags}
          onClickRow={() => {}}
          disabled={[]}
        />
        <Pagination
          alignSelf="end"
          step={itemsPerPage}
          numberItems={totalTags}
          page={page}
          onChange={({ page: nextPage }) => setPage(nextPage)}
        />
      </Box>
  )
}
export { TagsDataTable }
```
tags is a array of object needs to be shown in Table
itemsPerPage is no of data to be displayed in each page of table
totalTags is no of tags in BE 
page is current page in table 

When user clicks on the page in Pagination component, we are loading next set of data from the BE, setting it in `tags` state and passing the data to Datatable in `data` prop.

When user moves forward & backward and if suddenly clicks on row before next data gets loaded. DataTable is erroring out.
