### ISSUE TITLE
Responsive Grid: How to?

### ISSUE THREAD

**Issue by biapar** [grommet/grommet#6708]
How to create a responsive grid 3x2 like other frameworks?

**Comment by jcfilben** [comment]
Hey @biapar you can find some examples of how to use Grommet's Grid component here: https://storybook.grommet.io/?path=/story/layout-grid-app--app-grid. You can also check out [the documentation](https://v2.grommet.io/grid) for a more detailed description of the properties that can be passed to Grid. Let us know if there is anything missing from the docs/examples or if we can improve them.

**Comment by biapar** [comment]
Doesn't the grid resize like in Bootstrap framework?

**Comment by jcfilben** [comment]
Yes the Grid can responsively resize, here is an example where there are Cards within a Grid. When you adjust the screen size you can see the Card width is changing. 

https://storybook.grommet.io/?path=/story/layout-grid-responsive-cards--example

**Comment by jcfilben** [comment]
Hey @biapar, hope these resources helped answer your questions. I'm going to go ahead and mark this issue as closed. Feel free to reach out in the help channel in [Grommet's Slack workspace](https://slack-invite.grommet.io/) if anything else comes up.
