### ISSUE TITLE
SelectMultiple loses scroll position on select, when inside FormField

### ISSUE THREAD

**Issue by ulvesked** [grommet/grommet#6709]
### Expected Behavior

Provided a long list of options, after selecting an option the scroll position should be preserved so that I can select another option.

### Actual Behavior

After clicking an option, the list scrolls to top so I need to scroll the whole list again

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-select-multiple-long-option-list-scroll-restoration-2gt43p

### Steps to Reproduce

1. Start CodeSandbox link above
2. Open dropdown
3. Select option 900
4. Select option 901

### Your Environment

- Grommet version: 2.28
- Browser Name and version: Chrome 111.0.5563.111 (Official Build) (64-bit)
- Browser Name and version: Firefox 111.0.1 (64-bit)
- Operating System and version (desktop or mobile): Windows 11 Home 22H2 22621.1413 (desktop)

**Comment by jcfilben** [comment]
Thanks for reporting this issue! Marking this as a bug. Some additional notes... it looks like this is happening regardless of whether the SelectMultiple is within a Form or not. If the SelectMultiple is controlled this issue doesn't happen (see https://storybook.grommet.io/?path=/story/input-selectmultiple-long-list--long-list).
