### ISSUE TITLE
[OVGD] Two horizontal scroll bars in the right edge

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#671]
wrong layout with grommet 0.6.9
![image](https://cloud.githubusercontent.com/assets/16797825/16483946/45e8f68e-3ee9-11e6-91f1-33adcd6ce97f.png)

Good (0.6.7)
![image](https://cloud.githubusercontent.com/assets/16797825/16483955/4d3f1daa-3ee9-11e6-9246-9dd2de475f01.png)

**Comment by epilande** [comment]
This is from Inuit's `overflow-y: scroll` on the `html` element. https://github.com/inuitcss/base.page/blob/master/_base.page.scss#L34

A quick workaround would be to override `overflow-y: scroll` on the `html` element to `overflow-y: auto`.

I'm checking in with @alansouzati to see why it got commented out in https://github.com/grommet/grommet/blob/master/src/scss/grommet-core/_base.page.scss#L3L10

**Comment by bryanjacquot** [comment]
@alansouzati found that we made other changes that should allow re-enabling the desired overflow behavior which should result in not having redundant scroll bars.

**Comment by alansouzati** [comment]
Thanks for reporting this. Fixed in https://github.com/grommet/grommet/commit/3fa5e39e4121a99e73da6fd53d69b668cbb1d624

**Comment by christinHP** [comment]
@epilande @alansouzati @bryanjacquot  Thank you very much.
