### ISSUE TITLE
DateInput swaps to ranges when the date-format contains dashes

### ISSUE THREAD

**Issue by cdreier** [grommet/grommet#6714]
When using the DateInput component, initialized with a single date string, and setting the format to something with a dash (for example 'yyyy-mm-dd') the component switches to ranges, after the first change

### Expected Behavior

when the DateInput is not initialized with an array, the DateInput component only selects single dates and stays in "single date mode" - independent from the format

### Actual Behavior

the DateInput compoent switches to ranges and also changes the values / formData from a string to an array

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-dateinput-range-bug-jzjo7t?file=/index.js

**Comment by valeporti** [comment]
hello, could we reopen this one?

**Comment by britt6612** [comment]
@valeporti I beleive the same issue is already filed here https://github.com/grommet/grommet/issues/5922.
can you paste your comment into that issue?
