### ISSUE TITLE
NameValuePair alignment

### ISSUE THREAD

**Issue by der1igedon** [grommet/grommet#6716]
Hello,

I try to align the Name and the value of NameValuePair in column mode like this:
```
 <NameValueList
    valueProps={{ width: "auto", align: "start" }}
  >
    <NameValuePair name="File log level">
        <Select
          options={[
            "Debug",
            "Info",
            "Warning",
            "Error",
            "Panic",
            "Fatal",
          ]}
          // value={value}
          // onChange={({ option }) => setValue(option)}
        />
    </NameValuePair>
  </NameValueList>
```

### Expected Behavior
I want the Name (Text-Element) to be in the same vertical position as the value (see red/green line in the picture).

### Actual Behavior
Right now the label has a different vertial position than the value object. But I want both to be horizontally centered. See example:
![image](https://user-images.githubusercontent.com/21998742/228739835-1090c01d-5ff2-4da0-a481-64fb9d9be17e.png)

### Environment
- Grommet version: https://github.com/grommet/grommet/tarball/stable
- Browser Name and version: Chrome 111.0.5563.147
- Operating System and version (desktop): Windows 7

I would be nice if someone can give me an idea how to solve this.

**Comment by der1igedon** [comment]
Thanks for your help. If I try this I get the following error:

```
Type '{ alignSelf: string; }' is not assignable to type '{ align?: string | undefined; width?: WidthType | undefined; }'.
  Object literal may only specify known properties, and 'alignSelf' does not exist in type '{ align?: string | undefined; width?: WidthType | undefined; }'.ts(2322)
index.d.ts(8, 3): The expected type comes from property 'nameProps' which is declared here on type 'IntrinsicAttributes & NameValueListExtendedProps'
```

It seems alignSelf does not exist in NameValueList?

**Comment by jcfilben** [comment]
I played around with NameValueList and didn't find a way to get the desired behavior. Marking this as an enhancement

**Comment by halocline** [comment]
> I played around with NameValueList and didn't find a way to get the desired behavior. Marking this as an enhancement

According to https://v2.grommet.io/namevaluelist?#align and "The NameValueList component can be customized with any of the properties available in [Grid](https://v2.grommet.io/grid)." `<NameValueList `align="center"` ... />` should be supported.

Is "bug" more appropriate?

**Comment by halocline** [comment]
prop is accepted here: https://github.com/grommet/grommet/blob/7a50c754cb98635fa14d5806ac0b03d6d094e29c/src/js/components/NameValueList/NameValueList.js#L10 but never applied.

Putting up a fix now.

**Comment by jcfilben** [comment]
> According to https://v2.grommet.io/namevaluelist?#align and "The NameValueList component can be customized with any of the properties available in [Grid](https://v2.grommet.io/grid)." <NameValueList align="center" ... /> should be supported.
> 
> Is "bug" more appropriate?

Good note and thanks for looking into this more. I'll switch the label on this from 'enhancement' to 'bug'

**Comment by der1igedon** [comment]
Thanks!
