### ISSUE TITLE
DataTable using first column as primary key causes selection issues

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#6717]
### Expected Behavior

DataTable shouldn't set first column as "primary key" if DataTableColumns is used to hide the defined "primary key" column. It should continue to respect the "primary key" as defined by the caller.

### Actual Behavior

The first visible column is being treated as the primary key which causes issues for selection.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/datatablecolumns-xjs289?file=/index.js

https://user-images.githubusercontent.com/12522275/228935231-42d51005-d459-4cb9-8068-0c9c7935d0bd.mov

### Steps to Reproduce

1. Select a record
2. Use DataTableColumns to hide the "id" column
3. Select on of the "cloud" category rows
4. Notice how all of the "cloud" records become selected

### Your Environment

- Grommet version: 2.31.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): MacOS

**Comment by ericsoderberghp** [comment]
Verified that https://github.com/grommet/grommet/pull/6742 fixes this issue.
