### ISSUE TITLE
DropContainer Error in Cypress Test Automation 

### ISSUE THREAD

**Issue by ale-long** [grommet/grommet#6720]
### Expected Behavior
Clicking on an element within the DropContainer UI component should not result in an error using the Cypress test automation framework. 

### Actual Behavior
Clicking on the Reset button, which is a UI element within the DropContainer component, produces a type error within the Cypress test automation framework. This error does not show up outside of the Cypress testing environment. 

### URL, screen shot, or Codepen exhibiting the issue
<img width="542" alt="image" src="https://user-images.githubusercontent.com/22182636/228990921-a8347434-5d82-4485-aede-61edb7dc9b1d.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/22182636/228990939-1f5fd3b1-b2a2-424f-9092-d9b9af0212cc.png">

### Steps to Reproduce

1. Create a Cypress test case that clicks on an element within the DropContainer component 

### Your Environment

- Grommet version: 2.27.0
- Browser Name and version: Chrome 111
- Operating System and version (desktop or mobile): macOS

**Comment by jcfilben** [comment]
Looks like this issue is coming from line 101 in `DropContainer.js`. See https://github.com/grommet/grommet/blob/master/src/js/components/Drop/DropContainer.js#L101.

We probably just need to check that `dropRef.current` is defined before trying to use `dropRef.current.style`

**Comment by jcfilben** [comment]
> @jcfilben Was this issue resolved by https://github.com/grommet/grommet/pull/6804?

Yeah looks like it is resolved. I forgot to link back and close this ticket
