### ISSUE TITLE
SelectMultiple Dropdown Component

### ISSUE THREAD

**Issue by VijenSingh** [grommet/grommet#6724]
I want to change Button(Select All and Clear All) style.

### Expected Behavior

The dropdown box needs to be on focus with a teal outline during the selection 'Select All': remove the button style and apply the blue link style.

![Screenshot 2023-04-03 at 10 46 45 AM](https://user-images.githubusercontent.com/46666066/229417693-37b02b85-5196-48d3-bd53-0513fac64184.png)

**Comment by jcfilben** [comment]
Hi @VijenSingh the 'Select All' and 'Clear All' are built using Grommet's Button so if you adjust the theme for Button it will change the styling for 'Select All' and 'Clear All' in the SelectMultiple component. Here is a link to Button's theme documentation: https://v2.grommet.io/button#theme

**Comment by VijenSingh** [comment]
import { Grommet, Button } from 'grommet';

const customTheme = {
  
  button: {
    color: 'blue',
    border: {
      color: 'transparent',
    },
    hover: {
      textDecoration: 'underline',
    },
  },
};


const App = () => {
  return (
    <div style={{backgroundColor:''}}>
      <Grommet theme={{ ...customTheme }}>
        <Button label="Click" onClick={()=>alert('click me')}/>
      </Grommet>
    </div>
  );
};

export default App;





![Screenshot 2023-04-04 at 12 30 41 PM](https://user-images.githubusercontent.com/46666066/229713349-66ed5e24-efb1-4541-b5b3-25a271f17f98.png)


hover is not working

**Comment by VijenSingh** [comment]
image.png

**Comment by VijenSingh** [comment]
![Screenshot 2023-04-04 at 3 09 18 PM](https://user-images.githubusercontent.com/46666066/229752206-818921eb-cdcd-417d-b851-495263f0a173.png)


also I want parenthesis in 2 selected 
for example (2 selected)
