### ISSUE TITLE
DataTableColumns needs onChange Property

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#6729]
### Behavior

There is no way to save the current state of the options property. This means the next render will return the options to their initial value.

Refer to: https://v2.grommet.io/datatablecolumns

**Comment by jcfilben** [comment]
Amanda V. brought up a need for preserving the state of DataTableColumns in office hours 7/25/24

**Comment by jcfilben** [comment]
Resolved by #7281
