### ISSUE TITLE
DataFilter Range problems

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#6730]
### Slider and Position of Range Labels

The range boundary values are rendered _inline_ with the slider control (see image). When those numbers become large, the slider control becomes very compressed, to the point it is difficult to use.

This is the current slider control with boundary values rendered inline:

![image](https://user-images.githubusercontent.com/8231064/229915943-9b312cbe-2eb9-4c39-ad39-36fe283c3708.png)

When range values become large, it would be better if the range appeared under the control.  Perhaps a property something like: `{range: { labelAlign: "[top|bottom|inline]" }}`.  E.g. if it were aligned to the bottom, it might look something like this:

![image](https://user-images.githubusercontent.com/8231064/229917150-60b8c2ae-c64a-4510-9804-b3af2c49b2e8.png)

### Floating Point
The slider displays floating point values when the range is not evenly divisible by 20.

![image](https://user-images.githubusercontent.com/8231064/229915650-a6f7e24e-e5a1-4fe8-8ad2-1f6f9ea22c86.png)

### Step size
The step size is currently hardcoded to be `(max-min)/20`.  With 5000 items, the slider granularity is 250. Worst case, my min is 250 below and max 250 above where I want to filter.  i.e. it means I have a range of 500 items that I'm filtering.

The step-size (or number of steps) needs to be made a property so I have control over the granularity of slider steps.

When the range is fewer than 20, the step size should become 1.

### Control the type of filter
The type of filter is determined by the data type and there is no way to override that.

When the data set contains numbers, the DataFilter only provides a Range selector.  However, if the range is very small, (maybe just 5 items or fewer), I'd rather display it as a Select list or CheckBoxGroup.

Perhaps add a property to allow the user to set `filterType="RangeSelector|CheckBoxGroup|SelectMultiple"`

### Filter Range Excludes boundary values
The filter boundary values are exclusive, when they should be inclusive.  E.g. filter 0-3, the filter omits 0 and 3.  This actually makes it impossible to filter only on the min value (e.g. 0) or the max value.

The only workaround to this is to have the filter display values beyond the dataset.  E.g. to filter for items with a value of 0, I need to configure the {min: -1, max: 1}.  Meanwhile, negative values are not permitted in my dataset, so this is a hack to workaround the exclusive behavior.

There is also greater cognitive load required to mentally calculate values either side of the actual range to be filtered, rather than just displaying all the values to be filtered.

**Comment by taysea** [comment]
Doing a bit of testing at the moment. 

I agree with the desire to:
- Allow caller to specify the `step` if desired
- Allow the caller to specify where to render the range labels or how to abbreviate the range labels. Need to discuss what this looks like with @halocline @jcfilben 

I believe the following have been fixed (I'm not running into them when testing locally at least):
- The filter boundaries seem to be behaving inclusively (meaning if the range is 0-3 and I have a datapoint with value of 0, it's included in the result)
- The floating point is cleaned up to be rounded appropriately

At the moment, I'm leaning away from adding the `filterType` concept from the perspective that we're hoping these components drive quick consistency across filtering implementations. That being said, if we start to receive more feedback from user testing that certain filter types aren't allowing ease for filtering I'd be open to revisiting.
