### ISSUE TITLE
SelectMultiple when using object values and expanded handles click wrongly

### ISSUE THREAD

**Issue by urubatan** [grommet/grommet#6737]
There is an error in select multiple when using object values in conjunction with showSelectedInline, when the inline item is clicked instead of de-selecting that item it ends up being the only item selected

### Expected Behavior

Unselect an inline item when clicked

### Actual Behavior

When clicking an inline item it ends up being the only item selected

### URL, screen shot, or Codepen exhibiting the issue

The error happens all the time, it is easy to check it in the storybook 
(https://storybook.grommet.io/?path=/story/input-selectmultiple-object-options--object-options)

the error is in the line (https://github.com/grommet/grommet/blob/bcf727d1ea1734f64dab91173d033a1c9c2bee2c/src/js/components/SelectMultiple/SelectMultipleValue.js#L94-L96)

the object comparison should be !== like the string value comparison, but it is using ===

**Comment by jcfilben** [comment]
Fixed in #6738
