### ISSUE TITLE
Minor bugs are present in RadioButtonGroup Component

### ISSUE THREAD

**Issue by vaishnavyogesh** [grommet/grommet#6751]
There are currently two issues with the RadioButtonGroup component:

1. It ignores the defaultValue being set as 0 (as it could be one of the options value)
2. In case of Number values setting value in onChange as setValue(event.target.value) breaks the component since event.target.value gives a string type value and one needs to manually typecast it to make component work.
### Expected Behavior
It should behave correctly on above edge cases

### URL, screen shot, or Codepen exhibiting the issue
Issue 1
![radio-button-group-issue-1](https://user-images.githubusercontent.com/54815584/232227575-8cd9154d-996e-4d41-8ce1-dea39b21d6a7.png)

Issue 2
![radio-button-group-issue-2](https://user-images.githubusercontent.com/54815584/232227612-d78d94c3-71a0-4541-82dc-550e5bfacbcd.png)

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: latest
- Browser Name and version: chrome@latest
- Operating System and version (desktop or mobile): Ubuntu@22.04

**Comment by vaishnavyogesh** [comment]
I've gone through the Component's code and would like to work on fixing those issues!

**Comment by ericsoderberghp** [comment]
That would be great! We're happy to accept pull requests.

**Comment by vaishnavyogesh** [comment]
Awesome

**Comment by jcfilben** [comment]
Resolved in #6752
