### ISSUE TITLE
Need to show parentheses in 'Number of selected items' for multiple selection in selectMultiple component

### ISSUE THREAD

**Issue by vijendra-panwar** [grommet/grommet#6755]
I am currently using the SelectMultiple component from Grommet, and I need to show the number of selected items when the user selects more than one item. For example, when the user selects 2 items, I want to display "(2 selected)" next to the component label.
This will provide better user experience and improve the usability of the component.

### Expected Behavior

![Screenshot 2023-04-17 at 9 46 57 PM](https://user-images.githubusercontent.com/131149130/232758128-54244394-1ff7-44c8-80d2-19ab381bb916.png)

Need parentheses  for Example : (2 selected)

**Comment by ericsoderberghp** [comment]
Can you clarify, perhaps with a quick design sketch, the visual behavior you are requesting?

**Comment by vijendra-panwar** [comment]
> Can you clarify, perhaps with a quick design sketch, the visual behavior you are proposing?

![image](https://user-images.githubusercontent.com/131149130/232966002-4edafdf2-2ba0-434d-85a5-e50bf82454f4.png)

Need parentheses for Example : (5 selected)
![image](https://user-images.githubusercontent.com/131149130/232966120-18339005-5ff0-4fa6-a355-d6e7e2b8192f.png)

**Comment by jcfilben** [comment]
You can use the `valueLabel` prop to customize how you would like the label to appear. https://v2.grommet.io/selectmultiple#valueLabel

**Comment by vijendra-panwar** [comment]
Hi @jcfilben,
I tried the same in a codeSandbox but when I am using valueLabel Prop, input field's size is automatically changing. Is this expected behavior? Please let me know.

I am attaching the screenshots for your response.

CodeSandbox Link : https://codesandbox.io/s/blissful-zeh-kdth0z?file=/src/App.js

![image](https://user-images.githubusercontent.com/131149130/233362965-98c6f1e4-77ab-4fba-8671-18aeb51c0ccd.png)

When one option is selected:
![image](https://user-images.githubusercontent.com/131149130/233363318-0d0e6420-1e58-46a5-839b-92fb6c31e932.png)


When more than one options are selected:

![image](https://user-images.githubusercontent.com/131149130/233363464-dc36be88-aa8d-44e0-9cd0-1120e11f7b05.png)

**Comment by ericsoderberghp** [comment]
Would this work: https://v2.grommet.io/selectmultiple?c=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKRAbwChFEAnfKEGpQq6xAHgGV8DoBZELlh58rNojzoI+ABZxcAE3w0AvACJuvKGrFs42WAgDOKsgG0A5EczpcuCwBpEFzPgUwQmR89zoaAc3wLAF0AX11qGR5sdSjcbB1xagA3WxB8U0trW3snFzcPLzCIxFTcdIAZdAAjHlN2ACE4VAl0BXVUbLs1AD52ABV8VChEAHd8GH8ZKHVq+QVewgAmRCMefGg3YnYAekHhvp2m1B7w8R2e1mIAbgpQoA

**Comment by vijendra-panwar** [comment]
Its working. Thank you.
