### ISSUE TITLE
DataFilter numeric options works with CheckboxGroup (6 values or less) but not Select dropdown (greater than 6 values)

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#6763]
### Expected Behavior

Select dropdown behaves differently to a CheckboxGroup.

I have the followign DataFilter:

```
<DataFilter
  property="level"
  options={[...Array(MAXLEVEL).keys()].map((x) => ({
    label: `${x}`,
    value: x
  }))}
/>
```

Where

```
const MAXLEVEL = 6
```

When MAXLEVEL is 6, the filter is displayed as a CheckboxGroup and the filter works.
When MAXLEVEL is greater than 6, the filter is displayed as a Select dropdown and the filter no longer works.

E.g. In this [code sandbox](https://codesandbox.io/s/grommet-filtered-datatable-3b37fe?file=/src/App.js:476-517), you will see these lines:

```
const MAXLEVEL = 6
// const MAXLEVEL = 7
```

To see the expected behavior, assign `MAXLEVEL = 6`. Then select the "Filter" icon > "Level" CheckboxGroup > 2 > Apply Filter.  The data set now shows Levels with a value of 2.

Repeat the same with `MAXLEVEL = 7` (note the filter is now a Select dropdown) and the filtered table is now empty.

NOTE: The "Level" data is numeric.  Could that be why the Select dropdown is not working?

### URL, screen shot, or Codepen exhibiting the issue

See [this code sandbox](https://codesandbox.io/s/grommet-filtered-datatable-3b37fe?file=/src/App.js:476-517)

### Steps to Reproduce

Change MAXLEVEL = 7 and try to filter.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by JCoder121** [comment]
4/28/23 status: 🟢 

Need to add a Jest test, then it should be good to wrap up.
