### ISSUE TITLE
Grommet anchor & button cause full page reload in NextJS 13+

### ISSUE THREAD

**Issue by samuelgoff** [grommet/grommet#6767]
### Expected Behavior
`anchor`, `button` & any other component handling internal (SPA-style) navigation in NextJS should be able to handle navigation without triggering a full-page reload.

### Actual Behavior
Grommet `anchor` & `button` trigger full page reload when clicked in NextJS 13+. Previous to v13, NextJS required `next/Link` to be wrapped in an anchor tag, but v13 obviated this requirement, with the side-effect that if you continue to wrap `next/Link` in an anchor, it would trigger a full-page reload.

One potential workaround is to provide the next/Link to Grommet `button` or `anchor` via the `as` prop (e.g. `as={Link}`), but this hasn't worked.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/p/sandbox/quirky-gagarin-pdpjvu

### Steps to Reproduce

1. go to NextJS + Grommet [sandbox](https://codesandbox.io/p/sandbox/quirky-gagarin-pdpjvu)
2. click on either Grommet `Button` or `Anchor` to navigate between `Home` & `Page 2`
3. note the entire page refreshes when doing so
4. click on the `next/Link` below to navigate between `Home` & `Page 2`
5. note the page doesn't refresh & navigation is much faster & smoother

### Your Environment
This is reproducible across environments. MacOS, Safari, Chrome, Codesandbox, etc.

- Grommet version: latest
- Browser Name and version: latest Chrome, Safari, etc.
- Operating System and version (desktop or mobile): latest MacOS X

**Comment by ericsoderberghp** [comment]
Did you try https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag ?

**Comment by jcfilben** [comment]
Confirmed that the above solution is working. Here is a modified codesandbox that shows this:

https://codesandbox.io/p/sandbox/condescending-bird-00kq1p?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A20%2C%22endLineNumber%22%3A18%2C%22startColumn%22%3A20%2C%22startLineNumber%22%3A18%7D%5D

@samuelgoff Let us know if this solution works for you. If so we can go ahead and close this issue
