### ISSUE TITLE
Feature Request: Toggle Button

### ISSUE THREAD

**Issue by padmacnu** [grommet/grommet#6785]
Grommet does not yet have the concept of a toggle button such as https://mui.com/material-ui/react-toggle-button/#exclusive-selection. In Storage BU we use the Toggle button

### Expected Behavior

Currently Grommet doesn't have one

### Actual Behavior

With exclusive selection, selecting one option deselects any other.

### Screen shot
<img width="97" alt="image" src="https://user-images.githubusercontent.com/6428437/235771600-f7637cc8-77df-429c-830c-f76c1fddfdc4.png">
<img width="317" alt="image" src="https://user-images.githubusercontent.com/6428437/235771652-712c1f34-04e3-4121-a5bb-ae8fab5856f5.png">

### Example
https://mui.com/material-ui/react-toggle-button/#exclusive-selection

**Comment by ericsoderberghp** [comment]
You can build this with https://v2.grommet.io/radiobuttongroup#children.

For example: https://v2.grommet.io/radiobuttongroup?c=GYVwdgxgLglg9mABAUQB4EMC2AHANgUwAoBKRAbwChFEIEBnKRAbQDd1cR8AaRO-KAGrtOAXUQBeRACV86aADoQfAMpR0UIgHIE+TcQDcVRACd+IY0kJHqAHinoAJvABCIKFAQBxY3BDZr1IhgWPjiAEQOcBBhAdRw2LD04mRMmnTgmjyamHAImiIAvrGIbByhZKWcRYGBCADCABboYADm5YT4LPhgUKTiAHy8-EJlHV098mrGbVDylfjE1TWITqbQ8GDhPgDuMTX9AWSE8YlgfYNWy4g2ru4IiA1wXcYAkmBOEOpwxogwtJtkE4bCTiSRpDKIAD81xe-zo8mU4EQAHpBgAuGFw+QAWVySFRBRRByuiwCNmR9iccFuHjA3l82GJiAMFAKQA

**Comment by jcfilben** [comment]
Marking this as closed. Hopefully the above solution worked for you. If not feel free to reach back out and we can continue the conversation.
