### ISSUE TITLE
[REGRESSION] Infinite loop when updating component state on ref callback

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [grommet/grommet#6792]
### Expected Behavior

When transforming component parent state on ref callback, the rerender should not produce a `null` ref.
`null` ref should only be sent when component unmount.

### Actual Behavior

We receive infinite alternative between the node object and `null`.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-v2-template-forked-q0v4uf?file=/CustomComponentContainer.js

High probability that it comes from the changes of this PR : 
https://github.com/grommet/grommet/pull/6564

### Steps to Reproduce

1. Go on the codesandbox
2. Look in console the infinite loop, and console log showing switch between `null` and node
3. Pass Grommet in v2.28.0
4. No more infinite loop

### Your Environment

- Grommet version: 2.29.0 -> 2.31.0
- Browser Name and version: Chrome 112
- Operating System and version (desktop or mobile): Windows 10

**Comment by jcfilben** [comment]
Hey @AntoineDuComptoirDesPharmacies it looks like the pattern shared in the codesandbox isn't following reacts rules for using the setState hook.

Excerpt from react docs:

> Note that if you call a set function while rendering, it must be inside a condition like prevCount !== count, and there must be a call like setPrevCount(count) inside of the condition. Otherwise, your component would re-render in a loop until it crashes.

More info here: https://react.dev/reference/react/useState#storing-information-from-previous-renders.

**Comment by jcfilben** [comment]
Hmm I guess I'm a little confused. The way I am understanding it is the following code would be expected to cause an infinite loop because the `setValue` is being called within the render step
```javascript
const useForceUpdate = () => {
  const [, setValue] = React.useState(0); // integer state
  return () => setValue((currentValue) => currentValue + 1); // update the state to force render
};
```

**Comment by jcfilben** [comment]
Thank you, really appreciate the explanation!
