### ISSUE TITLE
CheckBox Padding Issue

### ISSUE THREAD

**Issue by versoworks** [grommet/grommet#6803]
### Expected Behavior

When padding a `CheckBox` with `fill` and `reverse`, the check mark should not exceed its parent's bounds.

### Actual Behavior

The check mark is pushed beyond its container

### URL, screen shot, or Codepen exhibiting the issue
<img width="1162" alt="Screenshot 2023-05-16 at 1 45 03 pm" src="https://github.com/grommet/grommet/assets/16771879/8d7bf013-05f4-41bd-acb2-bca33b849751">

### Your Environment

- Grommet version: 2.32.0
- Browser Name and version: Firefox 112.0.2
- Operating System and version (desktop or mobile): MacOS Venture 13.3.1 a

**Comment by jcfilben** [comment]
Fixed by #6819
