### ISSUE TITLE
TextArea to render any HTML/Grommet components 

### ISSUE THREAD

**Issue by varshasbharadwaj** [grommet/grommet#6814]
Hi! I'm dealing with a use case where we're using the Grommet TextArea component inside a form. Where the user can highlight any word and embed a link to it. Actually issue we are facing is rendering any HTML/Grommets components inside TextArea. As value of the TextArea can be only string.

### Expected Behavior
TextArea to render any HTML/Grommets components just like rich text editors.

### Actual Behavior
In TextArea whenever user highlights any word we are trying to show a Link icon, onClick of the icon we are popping a model  allowing the user to add a link. Once the link is saved, the Anchor tag code is shown as text and not as Anchor/Link. 

### URL, screen shot, or Codepen exhibiting the issue
Screenshot of actual behaviour 
![BF21121D-0602-4D10-94AE-5AD3E8DC9580_4_5005_c](https://github.com/grommet/grommet/assets/57700820/5fccec2f-e551-4a13-8a8e-7f1633b86b8e)

Screenshot of expected behaviour 
![2589865E-7C60-444A-8433-DA5D12C38536_4_5005_c](https://github.com/grommet/grommet/assets/57700820/8fc86b0e-0f1d-4b34-b592-b5eedbaa4c8d)

### Your Environment

- Grommet version: 2.27.0
- Browser Name and version: chrome 113.0.5672.126
- Operating System and version (desktop or mobile): Desktop macOS ventura 13.3.1

**Comment by SOjaHPE** [comment]
@chesleyratliff let me know that an epic for Istanbul has been created to track this enhancement request - [GLCP3-E-86](https://hpepm.aha.io/epics/GLCP3-E-86)

**Background:** This was previously released using a workaround - but still need to get this cleaned up as its getting more usage and will be shown to everyone when they login in Istanbul.

@MikeKingdom & @halocline - let's discuss this week

**Comment by halocline** [comment]
@SOjaHPE this seems to be a duplicate. Can you please find the existing issue(s) related to this work?
