### ISSUE TITLE
Scroll on mobile

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#682]
- I don't have problem with scrolling in the browser, only on mobile devices.
- Scroll on table does not work for me on mobile
- Scroll with custom Box panel does not work on mobile

How would one fix this?

Example:
```
<Split flex="right" priority="right">
<Sidebar ...>
<Box className="filters-panels-group">
   <Header fixed={true} ... />
   <Box>
      <FiltersRangePanel ... />
      <FiltersPanel  .../>
   </Box>
</Box>
</Sidebar>
<SomeTable .../> 
</Split>
```
I was trying with suggestion in #671 but then the table is displayed on the bottom of content in responsive mobile phone size.

**Comment by epilande** [comment]
Hi @primozs I created a [CodePen](http://codepen.io/epilande/full/QEqLow/) following the example layout you've provided, but I'm not able to reproduce this issue. May I know what mobile devices you're testing on? 

http://codepen.io/epilande/full/QEqLow/

**Comment by primozs** [comment]
Hi @epilande Thank you for your example!
I am testing on phone android 6, chrome browser and your example works. 
It might be the problem that I have this structure two levels deep. I have tried to modify your example like that and it still somehow looks ok. I will try to reproduce it and check your example again. Until then I guess this can be closed. Thank you for help!
