### ISSUE TITLE
StyledBoxGap divs appearing in DOM

### ISSUE THREAD

**Issue by davechisholm** [grommet/grommet#6824]
We've noticed whenever a <Box> comp has a "gap" prop, instead of using normal flex gap, it actually inserts empty divs in the dom instead. Is this simply for supporting 10+ year old browsers or is there another reason?  Is there any way to turn this off? Thanks

**Comment by britt6612** [comment]
@davechisholm I beleive this is related to https://github.com/grommet/grommet/issues/6679 you should be able to use the `<Grommet options={{ box: { cssGap: true } }}>` to change the behavior to align with CSS gap.

**Comment by britt6612** [comment]
@davechisholm understandable we have to keep backward compatibility but we can discuss for a future major version change if we want this as default behavior thank you. Tagging @jcfilben just for notes

**Comment by MikeKingdom** [comment]
It might be worth at least documenting this option in the `gap` description for `Box` since it's hard to find. I'm guessing making it the default would require a major version change (especially since I think it gets around the current limitation of fragment children not getting a gap between them)

**Comment by jcfilben** [comment]
Closing this issue. I opened a new issue on grommet-site to include `<Grommet options={{ box: { cssGap: true } }} >` in the documentation for Box `gap`. https://github.com/grommet/grommet-site/issues/480
