### ISSUE TITLE
Menu - props.items with align property to align icon and text

### ISSUE THREAD

**Issue by Repomn** [grommet/grommet#6830]
### Expected Behavior

I cannot align menu items with icon and label to center.
Menu.items.align is needed to me!

### Actual Behavior

workaround solutions
- wrapper component
- inject css, style attributes, styled component

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.25.1
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): MacOS

**Comment by jcfilben** [comment]
Hi @Repomn you should be able to specify the justify prop for each item to handle this. See https://storybook.grommet.io/?path=/story/controls-menu-justify--justify for an example of this. 

Alternatively if you want to set this behavior for the entire application you can use the `menu.item.justify` prop in the theme.

**Comment by Repomn** [comment]
Thank you, @jlaluces123 

I tried menu.item.justify, but the label and icon only aligned horizontally in the center, and did not align vertically in the center.
That's why I want `menu.item.align` property.

**Comment by jcfilben** [comment]
It looks like in the screenshot you shared the text is vertically aligned but the icon is not. In this case you could wrap the icon with a Box and set `alignSelf="center"`. Here is an example: https://codesandbox.io/s/grommet-v2-template-forked-u2n8cx?file=/index.js

**Comment by britt6612** [comment]
> It looks like in the screenshot you shared the text is vertically aligned but the icon is not. In this case you could wrap the icon with a Box and set `alignSelf="center"`. Here is an example: https://codesandbox.io/s/grommet-v2-template-forked-u2n8cx?file=/index.js

that's a good work around but then the `gap` we would need to control that with the `menu.item.gap` so would make sense to add a `menu.item.align` just to make it easier on the user and have everything in one place.

**Comment by jcfilben** [comment]
> that's a good work around but then the gap we would need to control that with the menu.item.gap so would make sense to add a menu.item.align just to make it easier on the user and have everything in one place. https://codesandbox.io/s/competent-merkle-q908cc?file=/src/App.js

Yeah good point about the gap, I agree I think we can add `menu.item.align` as a prop to make this easier
