### ISSUE TITLE
There's no way to show range input color range without the thumb

### ISSUE THREAD

**Issue by Cpt-Falcon** [grommet/grommet#6848]
### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment]
I'm assuming this is a duplicate of https://github.com/grommet/grommet/issues/6849

**Comment by jcfilben** [comment]
Closing, I think this is a duplicate
