### ISSUE TITLE
How to make circular sector buttons?

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet#6853]
We'd like to build this control:

![image](https://img2018.cnblogs.com/blog/1478663/201903/1478663-20190319164222762-2136079326.png)

Does grommet support it?

**Comment by jim-king-2000** [comment]
I built a similar:
```jsx
export function PanControl() {
  const targetRef = useRef();
  const [, setShowDrop] = useState(false);
  useEffect(() => setShowDrop(true) , []);
  return (
    <Box align='center'>
      <Stack anchor='center'>
        <Box background='placeholder' round='full' width='small' height='small' ref={targetRef} />
        <Box background='active' round='full' width='xxsmall' height='xxsmall' />
      </Stack>
      {
        targetRef.current && (
          <>
            <Drop align={{ top: 'top' }} target={targetRef.current} stretch={false} plain>
              <Button icon={<CaretUpFill />} />
            </Drop>
            <Drop align={{ bottom: 'bottom' }} target={targetRef.current} stretch={false} plain>
              <Button icon={<CaretDownFill />} />
            </Drop>
            <Drop align={{ left: 'left' }} target={targetRef.current} stretch={false} plain>
              <Button icon={<CaretLeftFill />} />
            </Drop>
            <Drop align={{ right: 'right' }} target={targetRef.current} stretch={false} plain>
              <Button icon={<CaretRightFill />} />
            </Drop>
          </>
        )
      }
    </Box>
  );
}
```

It looks like:
<img width="169" alt="image" src="https://github.com/grommet/grommet/assets/7019050/0492a668-c1f3-4c24-9340-d182269a2705">
But there is no split and no hover indicator.


I'd like to build the exact effect as the original picture. But it seems that `clip` and `rotate` have to be supported by grommet `Box`.

Any suggestion?

**Comment by halocline** [comment]
@jim-king-2000,`clip` and `rotate` are available via Box's [background prop](https://v2.grommet.io/box#background) and [hoverIndicator](https://v2.grommet.io/box#hoverIndicator). Perhaps investigate those as options?

**Comment by jim-king-2000** [comment]
1. Here is an implementation in pure css. <https://stackoverflow.com/questions/11487557/how-can-i-make-a-circular-sector-using-css>
1. We'd like to translate the pure css to `grommet` elements such as `Box` and `Button`.
1. We choose `grommet` since we are back-end engineers and not good at css.
1. Is it possible that `grommet` could support customized shaped buttons directly?

**Comment by jim-king-2000** [comment]
We implemented this by referencing <https://stackoverflow.com/questions/11487557/how-can-i-make-a-circular-sector-using-css>.

And the code is here: <https://github.com/Cache-Hit-Shanghai/jujiuipcappui>

**Comment by jim-king-2000** [comment]
Finally, I build a better pan control. Here is the code of the component:

```jsx
import { Box } from 'grommet';
import { CaretLeftFill } from 'grommet-icons';

function SectorBox({ angle, onClick }) {
  return (
    <Box
      focusIndicator={false}
      width='50%' height='50%' onClick={onClick}
      style={{
        position: 'absolute',
        transform: `rotate(${angle}deg)`,
        transformOrigin: '100% 100%',
      }}
    >
      <Box
        width='calc(100% - 1px)' height='calc(100% - 1px)' align='center'
        justify='center' background='dark-3' round={{ size: 'full', corner: 'top-left' }}
        style={{
          WebkitMaskImage: 'radial-gradient(circle farthest-side at bottom right, transparent 40%, #000 40%)'
        }}
      >
        <CaretLeftFill style={{ transform: 'rotate(45deg)' }} />
      </Box>
    </Box>
  );
}

function Circle() {
  return (
    <Box background='dark-3' round='full' width='calc(40% - 3px)' height='calc(40% - 3px)'
      margin='auto'
      style={{
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
      }}
    />
  );
}

export function PanControl({ size='medium', ...props }) {
  return (
    <Box flex={false} width={size} height={size} style={{ position: 'relative' }} {...props}>
      <SectorBox angle={45} onClick={() => console.log('up')} />
      <SectorBox angle={135} onClick={() => console.log('right')} />
      <SectorBox angle={225} onClick={() => console.log('down')} />
      <SectorBox angle={315} onClick={() => console.log('left')} />
      <Circle />
    </Box>
  );
}
```

Or clone the code here: <https://github.com/jim-king-2000/testGrommet>

Here are some main ideas:
1. Make circular sector.
    1. Make 4 square divs which the height/width is 50% - 1px.
    1. Turn the left and top border of the square div to round.
    1. Rotate these divs 45deg, 135deg, 225deg, 315deg respectively.
1. Cut the right-bottom corner of the circular sector.
    1. Make a radial gradient from right-bottom corner, 0 ~ 40% transparent, 40% ~ 100% white.
    1. Mask the radial gradient.
1. Add a small circle in the center. The size is 100% - 1px.
