### ISSUE TITLE
Multiple spaces wtihin text are getting removed 

### ISSUE THREAD

**Issue by kkgowtamasa** [grommet/grommet#6858]
### Expected Behavior

It should render the string as it is without trimming the spaces.

### Actual Behavior

![image](https://github.com/grommet/grommet/assets/9958655/7b6f369a-713a-4588-909e-d55059ae5bbe)
![image](https://github.com/grommet/grommet/assets/9958655/ab5f70d6-978b-431c-92f1-ed49821abc58)

### URL, screen shot, or Codepen exhibiting the issue
https://v2.grommet.io/table?c=DwFQhgRgNgpgfAKAARNJWAJGYAmMBOiKKa0MASgPYDuRxJ4ZAwjFFEgM4DGlADjAF4ARDyhCkESvjz5hkgC7zKAWyF16KAHJhlMZBuAB6RrBZt1xUqdbtufQSMpiJUmXMqKVa-RqQAxKDAANykfS2N0GDMoCyMTCho6OMisXAIk+IAhShwAT1j4qlowhkjozh5+YXwab18SDnkagDsAczghAFF8AEsuegBlXjAuGA4hI0aW9pLUCOYbC1KF8yZKHmaAV3lklZiw3dgigsjj2asomwr7atqlyynKNrgmAAtejkmmp5nfQ8vzOd4tE4AB1MDyAi6KBPf4gg7zI6JfT-bJ5RD-OBAA 

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by halocline** [comment]
@kkgowtamasa I believe the removal of the extra spaces is handled by the browser and consistent with how the following are treated:
```
<p>Hello     world!</p>
<h2>Hello        world!</h2>
<span>Hello               world!</span>
```

Typically `&nbsp;` is used to preserve spaces in strings and can be done with a technique like this: https://stackoverflow.com/questions/10474696/how-to-preserve-whitespace-in-dynamically-added-javascript-dom-element-without-u#answer-10474709

Additional info: https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace

Is there additional info I am missing for why whitespace would be treated differently here?

**Comment by jcfilben** [comment]
Closing since the behavior aligns with the native html behavior.
