### ISSUE TITLE
How to customize menu item?

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet#6864]
### Description

When we use grommet together with next.js, we usually use `Link` component to describe an anchor. For example, here is the sample code to use `Link` with `Button`.

```jsx
export function IconLInk({ icon, label, url }) {
  return (
    <Link href={url} passHref legacyBehavior>
      <Button as='a'>
        <Box pad='small' align='center'>
          {icon}
          <Text size='small'>{label}</Text>
        </Box>
      </Button>
    </Link>
  );
}
```

### Question

Now we need to wrap menu item with `Link`. We didn't find any way. So here are some questions:
1. Is it possible to embed `Link` to menu item?
1. Is it possible to customize menu item?

**Comment by jcfilben** [comment]
Hi @jim-king-2000 you might be able to try something like this to wrap the menu item with link.
```javascript
<Menu
  items={[
    {
      label: <Link><Text>Label</Text></Link>,
    }
  ]}
```

As far as customizing the Menu item you can pass any Button props to the objects in Menu `items`. You can also customize Menu items through the theme.

**Comment by jim-king-2000** [comment]
The code works. But the menu item would become a link style (blue color and with a underline). Any way to remove the link style (normal text menu item style but actually a link)?
