### ISSUE TITLE
Allow theme to specify Tag remove icon

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#6870]
### Expected Behavior

Theme should support `tag.icons.remove`. (mirrors select / menu structure)

### Actual Behavior

FormClose is built into Grommet.

Follow-on work from: https://github.com/grommet/hpe-design-system/issues/3467

**Comment by BrunoViveiros** [comment]
@taysea I would like to work on this issue, but I couldn't understand it very well, could you provide additional information?

**Comment by jcfilben** [comment]
Hi @BrunoViveiros great to hear you are interested in working on this! I believe the goal is to add a property to the theme that would allow users to specify what icon should be used for the remove button on tag. The property should be named `tag.icons.remove` (you can see the current theme structure for tag here: https://github.com/grommet/grommet/blob/master/src/js/themes/base.d.ts#L1579).

**Comment by joybh98** [comment]
hi @BrunoViveiros , are you still working on this ?

**Comment by vinodkv2511** [comment]
Hey @jcfilben . 
I would like to work on this and I have most of the required changes already.
Will try to raise a PR today.


I have gone through the unit tests and doesn't look like any changes to tests are needed. 
Will update the snapshot though.

Please let me know if there is anything else I need to consider for this fix.

**Comment by JaiminR28** [comment]
Is the issue resolved ? If not can I try

**Comment by vinodkv2511** [comment]
PR is in place and comments were addressed. It just needs to be merged.
