### ISSUE TITLE
Data - allow search across more properties than filter

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#6871]
### Expected Behavior

When custom `properties` are passed to `Data`, it would still be ideal to search across all fields. For example, in [this filtering example](https://design-system.hpe.design/templates/filtering?q=filter#filtering-with-selectable-results), I would still like to be able to search by "Name" even though I can't filter by name.

### Actual Behavior

I can only search across properties that are also "filterable".

### URL, screen shot, or Codepen exhibiting the issue

https://github.com/grommet/grommet/assets/12522275/d142f52a-acf7-428c-8dd7-6d35ccf38d0f

### Steps to Reproduce

1. search for "Server 1"
2. Notice how there are "0 results"

### Your Environment

- Grommet version: stable
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by halocline** [comment]
MVP - Should be implemented for MVP. Search should be independently configurable and decoupled from filters.
