### ISSUE TITLE
MaskedInput displays "undefined" when unsupported key is entered

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#6884]
### Expected Behavior

MaskedInput shouldn't display "undefined" as text value.

### Actual Behavior

When MaskedInput is in a FormField and a user types in an invalid character, the text value becomes "undefined".

Note: This only happens when MaskedInput is within a Form.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/maskedinput-undefined-wtlqp6?file=/src/App.js

### Steps to Reproduce

1. Type "m" into MaskedInput
2. Notice how "undefined" becomes text in masked input

### Your Environment

- Grommet version: stable
- Browser Name and version: Chrome 
- Operating System and version (desktop or mobile): MacOS

**Comment by MikeKingdom** [comment]
This started happening with grommet v2.25.0. It's avoided if the component is controlled. For example:

```jsx
const [value, setValue] = useState('');
return (
  <MaskedInput
      mask={mask} 
      value={value}
      onChange={(event) => setValue(event.target.value)}
   />
)
```
