### ISSUE TITLE
Layer causes DOMException

### ISSUE THREAD

**Issue by stephanpelikan** [grommet/grommet#6888]
### Expected Behavior

Hiding `Layer`s should not break rendering, even in case of race-conditions.

### Actual Behavior

In some situations hiding a `Layer` causes DOMException because the child was already removed (or maybe its parent changed).

### URL, screen shot, or Codepen exhibiting the issue

![grommet](https://github.com/grommet/grommet/assets/5190548/d428c99a-60f2-414c-89a2-b4027c149727)

### Steps to Reproduce

In my application on certain pages it is reproducable every ~ 4th render (Ctrl-R), but only with dev-server.

It seems to be a race condition. My use-case is that I load data in `useEffect` showing a ´Layer´ for a loading-indicator. On response the `Layer` is hidden.

Using production-builts it works without error because they load faster. In Firefox it works fine even with dev-server, but in Chrome I get those errors.

### Your Environment

- Grommet version: 2.33.0
- Browser Name and version: Chrome 114.0.5735.199 (Offizieller Build) (64-Bit)
- Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by jcfilben** [comment]
Fixed in #6889
