### ISSUE TITLE
Adding control to stop or pause grommet carousels

### ISSUE THREAD

**Issue by samogami** [grommet/grommet#689]
Add a user control that allows user to stop or pause [grommet carousels](http://www.grommet.io/docs/hpinc/develop/carousel). 
[WCAG 2.0 Success Criteria 2.2.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/time-limits-pause.html#time-limits-pause-examples-head)

**Comment by bryanjacquot** [comment]
Thanks for the feedback @samogami.  We're thinking that adding a pause/play button at the bottom corner of the carousel when the AutoPlay is set to true.

**Comment by alansouzati** [comment]
We decided to stop autoplay as soon as the user set the focus on the carousel.

We will not at the buttons at this point, I'm closing the issue for now. Feel free to re-open if you still believe it makes sense to add the buttons.

**Comment by samogami** [comment]
Adding a button/control to stop animations would be beneficial for users with certain cognitive disabilities  [(ADD)](https://en.wikipedia.org/wiki/Attention_deficit_hyperactivity_disorder) that might not use focus controls but still could be distracted by animation and moving text.

**Comment by alansouzati** [comment]
Makes sen, reopening the issue. I will check with @L0ZZI on a possible design for start/pause controls for the carousel

**Comment by tracybarmore** [comment]
design reference grommet/grommet-design#45

**Comment by RyanCCollins** [comment]
Any updates on this @L0ZZI or @tracybarmore ?  I see that the grommet-design issue is closed.  Can we close this one as well?

**Comment by L0ZZI** [comment]
not for v1, but v2 we can design an example with these features

**Comment by L0ZZI** [comment]
Adding to v2.

**Comment by L0ZZI** [comment]
We're going to skip the example of carousel and modify the component to have a hidden pause button when `play` property is enabled allowing screen readers to read the interaction and allow users to play/pause the content. We'll also need to enhance the component to allow for the `aria-label` to be passed to the next/previous buttons—Currently it does not.
