### ISSUE TITLE
MaskedInput: it don't permit input when the mask is applied.

### ISSUE THREAD

**Issue by biapar** [grommet/grommet#6899]
Hi,

I a MaskedInput field.
I create a regex like this one:

When I apply the mask, the input don't accept any input. If I remove the mask tag, the input works again.
Why?

`   <MaskedInput
                  id="barcode"
                  name="barcode"
                  style={{ textTransform: "uppercase" }}
                  required
                  maxLength={14}
                  mask={maskBarcode}
                />`

`const maskBarcode = [
    {
      length: 14,
      regexp:/^(380|381)[0-9]{11}$/,
      placeholder: "xxxxxxxxxxxxx",
    },
  ];`

- Grommet version: 2.32

**Comment by MikeKingdom** [comment]
The trick with MaskedInput is the regular expression needs to accept intermediate results as you type. Your expression currently will only match the full result.

**Comment by biapar** [comment]
That is?
Could you made an example, please?
Thanks.

**Comment by MikeKingdom** [comment]
Your example comes out to something like this (note the `length` property too):
```jsx
const maskBarcode = {
  length: [1, 14],
  regexp: /^(3|38|38[0,1]|38[0,1][0-9]{1,11})$/
};
```
You might also consider fixing the first two digits:
```jsx
 const barcodeMask= [
    {
      fixed: "38"
    },
    {
      length: [1, 11],
      regexp: /^([0,1])|([0-1][0-9]{1,11})$/,
    }
  ];
```

Note there is an issue in MaskedInput in grommet versions 2.25.0 through at least 2.31.0 that make it difficult to use: #6884

**Comment by biapar** [comment]
> The trick with MaskedInput is the regular expression needs to accept intermediate results as you type. Your expression currently will only match the full result.

It works!
Why this trick? Is this rule for all regular expressions used by this field? 
I see here some examples and they don't use this trick: https://design-system.hpe.design/components/maskedinput
Thanks.

**Comment by MikeKingdom** [comment]
> > The trick with MaskedInput is the regular expression needs to accept intermediate results as you type. Your expression currently will only match the full result.
> 
> It works! Why this trick? Is this rule for all regular expressions used by this field? I see here some examples and they don't use this trick: https://design-system.hpe.design/components/maskedinput Thanks.

They do. Notice the regular expressions accept 1 to 3 characters for each field. This means as you type 1 then 12 then 123 each step matches the expression for that slot.

**Comment by biapar** [comment]
Thanks.

**Comment by MikeKingdom** [comment]
Closing as resolved
