### ISSUE TITLE
Menu inline=false on click window scrolls to the top.

### ISSUE THREAD

**Issue by primozs** [grommet/grommet#690]
When window size is big and onResponsive is not active everything is working correct.
When window size is small and Menu Components internal onResponsive is active it scrolls the window to the top.
Is this intentional? 

It's possible to check this in the docks. Resize the window below 720px and click on some menu that will open dropdown. Window will scroll to the top.
Cheers

**Comment by bryanjacquot** [comment]
Steps to reproduce:
1.  Open http://www.grommet.io/docs/hpe/develop/menu
2.  Set browser size to be narrow such as a phone
3.  Open one of the closed menus in the examples

Page scrolls to the top instead of staying in place.

**Comment by lelostsamurai** [comment]
https://github.com/grommet/grommet/commit/f110aa244ce16f806ac2d01732aa6dcecaf8fca7 reintroduces the issue, so window is still scrolling to the top

**Comment by tracybarmore** [comment]
Hi @lelostsamurai. Do you have a codepen for this issue that we can look at?

**Comment by lelostsamurai** [comment]
@tracybarmore, try this - https://codepen.io/anon/pen/JEGPbM

**Comment by tracybarmore** [comment]
linking to #1071
