### ISSUE TITLE
DataTableColumns dropdown content isn't position properly

### ISSUE THREAD

**Issue by kyuohoh** [grommet/grommet#6908]
### Expected Behavior
Not sure if this is an intended behavior but the position of DataTableColumns dropdown content moves when scrolling the window downward. 

Presumably, we should keep the position fixed under the DataTableColumns icon.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/p/sandbox/youthful-tristan-f4phv2?file=%2Fsrc%2FDataTable.js%3A383%2C34
steps to reproduce:

<img width="624" alt="image" src="https://github.com/grommet/grommet/assets/99282684/fa3b0f2e-3af5-4314-b47d-fb9105c3280c">

### Steps to Reproduce
- click the DataTableColumns icon to open the dropdown content
- down scroll the window outside of the dropdown content to see the full list of the content
- notice the content itself moves along with the window and in result, you're not longer able to see the full list of the content.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment]
Hi @kyuohoh I tried taking a look at your codesandbox but looks there there were some issues preventing it from loading (see screenshot). I copied your code over into a [new codesandbox](https://codesandbox.io/s/grommet-v2-template-forked-xdy76k?file=/index.js), but I am not seeing the error. Is there anything I am missing that is needed to reproduce the issue?
<img width="578" alt="Screen Shot 2023-08-01 at 4 17 40 PM" src="https://github.com/grommet/grommet/assets/54560994/cdf82a81-d974-4c55-8e30-b7c10d299d7c">

**Comment by kyuohoh** [comment]
@jcfilben  - I think the issue with the codesandbox was that the <Data />, <Toolbar />, and <DataTableColumns />  components aren't available in the sandbox. One way to reproduce this issue is to use storybook from grommet (DataTableColumns - Simple):

export const Simple = () => (
  // Uncomment <Grommet> lines when using outside of storybook
  // <Grommet theme={...}>
  <Box
    align="center"
    justify="start"
    pad="large"
    gap="medium"
    style={{ marginTop: '500px' }}
  >
    <Notification
      status="info"
      message="Data is in 'beta'. The API surface is subject to change."
    />
    <Data data={DATA} updateOn="change">
      <Toolbar>
        <DataSearch />
        <DataTableColumns drop options={options} />
      </Toolbar>
      <DataSummary />
      <DataTable columns={columns} primaryKey="name" />
    </Data>
  </Box>
  // </Grommet>
);

Here, I just added `style={{ marginTop: '500px' }}` to the Box so that I could reproduce the Drop issue.

**Comment by jcfilben** [comment]
Ah gotcha, thanks for sending the code snippet! I was able to reproduce the issue using that. Making this as a bug

**Comment by kyuohoh** [comment]
@jcfilben @coltonw - fix is available here: https://github.com/grommet/grommet/pull/6933
