### ISSUE TITLE
Carousels controls not showing up in Safari

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#691]
Open http://www.grommet.io/docs/develop/carousel

The controls are not being displayed.

Works as expected in Chrome, Firefox and IE.

**Comment by jwijay** [comment]
PR pending: https://github.com/grommet/grommet/pull/701

**Comment by jwijay** [comment]
Closing this issue, since PR with Safari fix was merged: https://github.com/grommet/grommet/pull/701
