### ISSUE TITLE
Drop support for node v16 in September

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#6911]
Node v16's end of life is September 11th. We should bump the required node version up to v18 once we hit the end of life date.

**Comment by phoenix-clauster** [comment]
Hi,
I've created #6937 to address this issue. Also, I wrote a question regarding a netlify issue.

**Comment by britt6612** [comment]
Holding off on this issue due to many teams that are still using v16. Our recommendation would be that they use v18 since v16 is no longer being maintained.
