### ISSUE TITLE
Button with icon in Menu aligned start

### ISSUE THREAD

**Issue by Repomn** [grommet/grommet#6914]
### Expected Behavior

Text and icon in Menu items that are rendered as Button are aligned center.

or can be set "align" prop.

### Actual Behavior

not aligned center.

### URL, screen shot, or Codepen exhibiting the issue

<img width="216" alt="スクリーンショット 2023-08-07 16 04 27" src="https://github.com/grommet/grommet/assets/11584752/f0b805b0-11d9-4996-9306-9d9d9586646b">

### Steps to Reproduce

```tsx
<Menu
      icon={<RiMore2Fill />}
      items={[
        {
          key: "edit-label",
          label: "ラベルを変更",
          icon: <RiEditBoxFill />,
          gap: "small",
          size: "small",
        },
    ]}
/>
```

### Your Environment

- Grommet version: 2.32.2
- react-icons/ri: 4.4.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): MacOS

**Comment by britt6612** [comment]
@Repomn Is this what you are trying to accomplish? 
https://codesandbox.io/s/competent-merkle-q908cc?file=/src/App.js

**Comment by Repomn** [comment]
@britt6612 Yes, I appreciate this solution! I will attempt to update Grommet to version [2.33.0](https://github.com/grommet/grommet/releases/tag/v2.33.0) or newer and adjust the `menu.item.align` setting. Your example has been very helpful.

**Comment by Repomn** [comment]
It is very good after I updated to grommet@2.33.1.

**Comment by britt6612** [comment]
> It is very good after I updated to grommet@2.33.1.

good glad to help!
