### ISSUE TITLE
Text area content overflow when resized horizontally.

### ISSUE THREAD

**Issue by TanaySde1** [grommet/grommet#6919]
### Expected Behavior

Text area content should not overflow out of the bounding box. 

### Actual Behavior

When resizing the textArea horizontally the content within the box gets spilled.

![image](https://github.com/grommet/grommet/assets/106054062/d20f930d-e583-469b-bbeb-712d7bd5cf58)

### Steps to Reproduce

1.Inside COP go to Manage
2.Go to Authentication 
3.Go to Sessions and type anything inside the textArea and try to resize.

### Your Environment

Present on all the environments

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by jcfilben** [comment]
Hi @TanaySde1 can you provide a minimal reproduction of the issue in a [codesandbox](https://codesandbox.io/s/m7mml8l0zj)?

**Comment by MikeKingdom** [comment]
With Taylor's example at https://codesandbox.io/s/wonderful-farrell-65n27d?file=/src/styles.css if you change the `.formfield width` from `384px` to `fit-content` it works better. The short answer is whatever wraps the `<textarea>` needs to just adapt to the textarea's size and not try to force it given the user can resize it.

I'm not sure of the best solution for grommet yet.

**Comment by halocline** [comment]
`resize="vertical"` exists as an option for this use case and was proposed as an immediate remedy.

I believe @MikeKingdom was thinking about leveraging CSS max-width = 100% as a sensible default for TextArea.

**Comment by TanaySde1** [comment]
Thanks guys! Going ahead with resize = 'vertical' for now.

**Comment by jcfilben** [comment]
Fixed in #6924
