### ISSUE TITLE
Zooming out in Safari shrinks the view

### ISSUE THREAD

**Issue by Beelal** [grommet/grommet#692]
![image](https://cloud.githubusercontent.com/assets/1430223/16786696/9f8fae4c-484b-11e6-9e49-a4d63b1d1738.png)

**Comment by bryanjacquot** [comment]
@Beelal: can you provide more information on what steps you took to reproduce this and the expected behavior?

**Comment by Beelal** [comment]
I pressed CMD and - together to zoom out for few times.
