### ISSUE TITLE
"Table" control won't load more on Firefox, when dragging the scrollbar to the end

### ISSUE THREAD

**Issue by huiwang-hpe** [grommet/grommet#693]
On **Firefox**, the table won't load more if we scroll to the end **by dragging the scrollbar**.
It only works if we use mouse wheel to scroll to the end.
![1](https://cloud.githubusercontent.com/assets/19163801/16793525/3c0ac71c-4904-11e6-9440-8c74071967ee.png)

By adding some console logs into "InfiniteScroll.js", I found dragging the scrollbar to the end on Firefox will cause a non-integer "bottom" value of the client boundary. And that's why the event "onEnd" didn't triggered.

![3](https://cloud.githubusercontent.com/assets/19163801/16793598/bbd80bbc-4904-11e6-86a9-383efd4d9877.png)
![2](https://cloud.githubusercontent.com/assets/19163801/16793595/b880daca-4904-11e6-900b-7ac4b8d39260.png)

**Comment by huiwang-hpe** [comment]
This can be easily reproduced on Ferret demo:

1. Open: http://ferret.grommet.io/activity with Firefox
2. Use mouse to drag the vertical scroll bar to the end

**Comment by epilande** [comment]
Hi @huiwang-hpe, this is related to https://github.com/grommet/grommet/issues/620, which has just been fixed in https://github.com/grommet/grommet/pull/688. The fix should be in the next grommet release. 

If you'd like to test it out, change your grommet in package.json to
`"grommet": "https://github.com/grommet/grommet/tarball/stable",`
Which will get the latest code base that's on master branch.

**Comment by huiwang-hpe** [comment]
Hi @epilande , thanks for the information. 
I've tried on master branch and found that "adding 10px offset" works for the "loading more" feature.

However, two scroll bars appear after pointing to master branch and it used to be only one.
This is another issue which I need to fix if I upgrade grommet to the next release.
![2016-07-14_101012](https://cloud.githubusercontent.com/assets/19163801/16826081/dba227c2-49ac-11e6-8ced-2e05eddee188.png)

**Comment by epilande** [comment]
@huiwang-hpe the two scrollbar issue has just been fixed. https://github.com/grommet/grommet/issues/671#issuecomment-232501315
