### ISSUE TITLE
DataTable "Select All" overwrites previously selected

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet#6946]
### Expected Behavior

"Select All" should extend the currently selected set with newly selected. This behaviour is observed when selecting individual rows, so should be the same when selecting all rows.

### Actual Behavior

"Select All" replaces the currently selected set.

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/s/grommet-filtered-datatable-3b37fe?file=/src/App.js

### Steps to Reproduce

1. Go to the URL above
2. Select the first row in the table
![image](https://github.com/grommet/grommet/assets/8231064/531aa5ae-0b15-4ac4-8e5d-ae53204af91c)

4. Search for "CCCC" to get a disjoint set
![image](https://github.com/grommet/grommet/assets/8231064/77bd55c2-dedd-4622-b022-6597de6fda0f)
5. Check "Select All" (overwrites currently selected)
![image](https://github.com/grommet/grommet/assets/8231064/e05f1614-40e5-4084-a17e-0869e701c703)

Compare that with selecting individual rows.  In this case the selections are additive.
![image](https://github.com/grommet/grommet/assets/8231064/9fcd5ac9-9131-4334-8ea7-8acb9297d74d)### Your Environment
![image](https://github.com/grommet/grommet/assets/8231064/ad14164a-9524-4bb9-9d2a-56094283e9d7)

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by taysea** [comment]
To advance this, we need to gather more data. Currently blocked until we have that environment set up.

**Comment by jcfilben** [comment]
Looks like this issue has been resolved see [this codesandbox](https://codesandbox.io/p/sandbox/grommet-filtered-datatable-3b37fe?file=%2Fsrc%2FApp.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx3p0puc00073b6jdsoc1svx%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx3p0pub00033b6jej89u5ev%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx3p0pub00043b6j29pnyzv8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx3p0pub00063b6jiny4xoj4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx3p0pub00033b6jej89u5ev%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx3p0pub00023b6jcn6ls75k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%257D%255D%252C%2522id%2522%253A%2522clx3p0pub00033b6jej89u5ev%2522%252C%2522activeTabId%2522%253A%2522clx3p0pub00023b6jcn6ls75k%2522%257D%252C%2522clx3p0pub00063b6jiny4xoj4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx3p0pub00053b6jirze2fw4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clx3p0pub00063b6jiny4xoj4%2522%252C%2522activeTabId%2522%253A%2522clx3p0pub00053b6jirze2fw4%2522%257D%252C%2522clx3p0pub00043b6j29pnyzv8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx3p0pub00043b6j29pnyzv8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
