### ISSUE TITLE
`onClickOutside` of `Layer` would be triggered twice when the mouse is clicked once

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet#6948]
### Expected Behavior

`onClickOutside` of `Layer` should be invoked once with one mouse click.
### Actual Behavior

It is invoked twice.
### Steps to Reproduce

1. Create a react or next.js project.
1. In the index page, populate it with the following code
          `<Layer onClickOutside={() => console.log('back')}>123</Layer>`
1. Click the outside of the layer once and notice `back` would be printed twice.

### Your Environment

- Grommet version: 2.33.2
- Browser Name and version: Chrome v117
- Operating System and version (desktop or mobile): Win11

**Comment by jcfilben** [comment]
Hi @jim-king-2000 I tried to reproduce this issue in a codesandbox but when I click outside the layer I am only getting one console log message. Is there something I am missing that is needed to reproduce this issue?

Here is my codesandbox:
https://codesandbox.io/s/grommet-v2-template-forked-72smz5?file=/index.js
Can you share a codesandbox that reproduces the issue?

**Comment by jim-king-2000** [comment]
You can use this page to reproduce the bug:
<https://v2.grommet.io/layer>

Just need to introduce one change:
`onClickOutside={() => setShow(false)}` -> `onClickOutside={() => console.log('close')}`

**Comment by jim-king-2000** [comment]
In your sandbox, you could make a tiny small chagne to reproduce the bug:
```javascript
const onClose = () => {
    console.log("click");
    // setOpen(undefined);
  };
```

**Comment by jcfilben** [comment]
Thanks for the clarification, I updated my codesandbox and was able to reproduce the issue

**Comment by jim-king-2000** [comment]
Glad to know the successful reproduction. This bug is a little bit critical since we are trying [intercepting routes](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes) from [next.js](https://nextjs.org/). When intercepting routes is used, the `onClose()` function would become `router.back()` instead of `setShow(false)`. We find that `router.back()` would be triggered twice with only click once which means `Layer` can't work with `intercepting routes`. I'm looking forwards to the fix.

**Comment by jim-king-2000** [comment]
Any update?

**Comment by britt6612** [comment]
@jim-king-2000 We dont have any updates yet but would still like to keep tracking this.
