### ISSUE TITLE
StarRating component doesn't load in default values

### ISSUE THREAD

**Issue by Cpt-Falcon** [grommet/grommet#6961]
If I hardcode star rating to be at the value 5, it should show 5 stars. Instead, it shows no stars. Therefore, it becomes impossible to restore a previous selection a user had done from another session. 

### Expected Behavior

If I set the value property to 5 as a default value, then I should see 5 stars enabled.

### Actual Behavior

There are 0 stars enabled until you click on a star to enable it. It should show stars even if you haven't clicked on anything if a default value is set

### Steps to Reproduce

1. In any grommet app just try to do this:

`<StarRating name="test" value={5} />`

### Your Environment

- Grommet version: 2.33.1
- Browser Name and version: Chrome, Edge latest
- Operating System and version (desktop or mobile): Windows 11 Desktop

**Comment by Alok-Singh-ops** [comment]
Hi  @jcfilben  i wanna work on it

**Comment by jcfilben** [comment]
Fixed by https://github.com/grommet/grommet/pull/7077
