### ISSUE TITLE
[refactor]: replace twitter old Icon with new Icon

### ISSUE THREAD

**Issue by Omsoni06** [grommet/grommet#6962]
### Expected Behavior

Twitter new 'X' Icon expected

### Actual Behavior

![Uploading x logo.png…]()

update twitter old bird Icon with new X Icon

**Comment by OmarRoBra** [comment]
HI i would like to work on this issue

**Comment by jcfilben** [comment]
The new icon for X was added in https://github.com/grommet/grommet-icons/pull/322. It will be available in the next release of grommet-icons
