### ISSUE TITLE
MultiSelect: default messages customization "`n out of N 

### ISSUE THREAD

**Issue by tol-any** [grommet/grommet#6965]
Hey there,

I work for a french company and we'd like to customize, localize actually, the SelectionSummary.js text contents.

For now I'll juste create the issue but we'll may plan some time to contribute on the matter :)

### Expected Behavior

Maybe, add keys to the `messages` object prop for theses specific texts ?

```
interface Messages {
    multiple?: boolean
    total?: string
    clearAll?: string
    selectAll?: string
}
```

This is a really raw idea, I guess the actual implementation will have to handle default cases and difficulties related to i18n. I'll just paste the current code for now but I'll think about it...

```
// SelectionSummary.js:71
const summaryText =
    value?.length === 0 ||
    onMore ||
    !value ||
    (search !== '' && search !== undefined)
      ? `${value?.length || 0} selected`
      : `${value?.length || 0} selected of ${options.length}`;
```

### Actual Behavior

The `messages` object has only one `multiple` key.

### URL, screen shot, or Codepen exhibiting the issue

![Capture d’écran 2023-10-10 à 08 57 41](https://github.com/grommet/grommet/assets/108674993/5d562fe9-ee43-4c5f-8cd4-2ad2183e5453)

---

![Capture d’écran 2023-10-10 à 08 57 46](https://github.com/grommet/grommet/assets/108674993/68bdb35d-1211-4a2a-b645-4c88e794d92f)

---

![Capture d’écran 2023-10-10 à 09 01 59](https://github.com/grommet/grommet/assets/108674993/667e216b-a66a-4054-ba78-5541ac32ea04)

### Steps to Reproduce

Default [MultiSelect](https://storybook.grommet.io/?path=/story/input-selectmultiple-default--default) behavior

### Your Environment

- Grommet version: 2.32.2
- Browser Name and version: All
- Operating System and version (desktop or mobile): All

Thanks a bunch !

**Comment by jcfilben** [comment]
Hi @tol-any thanks for raising the issue and great to hear you team may contribute! We already have this issue tracked here: https://github.com/grommet/grommet/issues/6337. I'm going to close this issue so we just have it tracked in one place.
