### ISSUE TITLE
Enhance Search Component to have Search  Clickable

### ISSUE THREAD

**Issue by L0ZZI** [grommet/grommet#697]
This to have the search icon clickable in the Search Component as opposed to hitting enter to submit the query.

**Comment by epilande** [comment]
Hi @L0ZZI, what do you mean by enhance search component to have search clickable? Are you talking about the icon? If so, when a user clicks on the icon, should it fire the same event as when the enter key is pressed?

**Comment by alansouzati** [comment]
The icon should be a button instead of a regular svg element, if only if, the onSearch callback is passed.

Clicking on the button will always trigger the onSearch callback. It will be up to the developer to decide to trigger a request or not when the onSearch is invoked.
