### ISSUE TITLE
add Dependabot

### ISSUE THREAD

**Issue by Akshayp02** [grommet/grommet#6972]
To add Dependabot to a project, create a dependabot.yml file in project root. Configure it to check for updates in project's dependencies, and set up notifications for automated pull requests. Dependabot will then help keep dependencies up-to-date, enhancing project stability and security.

**Comment by britt6612** [comment]
@Akshayp02 We actually did have dependabot before and we found that it wasn't as helpful just because we have been consistent on doing releases as well as upgrading dependences on a consistent basis. Have you ran into issues with using grommet that you created this issue?

**Comment by Akshayp02** [comment]
Hey @nolleto  Actually I've seen you didn't added dependabot, seem it is convenient to update all the dependencies Automatically so that's why raised an issue.

**Comment by jcfilben** [comment]
Thanks for the suggestion @Akshayp02, we do have dependabot enabled, it is configured to only be visible to users with certain permissions on this repo

**Comment by Akshayp02** [comment]
Okay, thanks for your reply. I'll be happy to contribute to other issues from here 😊
