### ISSUE TITLE
DataTable triggers 'Submit' event which propagates to its parent "wizard" component 

### ISSUE THREAD

**Issue by RohanEmmanuel07** [grommet/grommet#6975]
hi All, I recently started working on React... I created a "wizard" template to take multiple inputs in forms in different steps of the wizard based on the template documented in the HPE design templates-->https://design-system.hpe.design/templates/wizard.
In one of the steps of the wizard, I am using another template called "data table customization" documented at -> https://design-system.hpe.design/templates/datatable-customization
this data table template allows filtering the data based on the filters. But when this data table is placed inside the wizard template, and when I navigate to the filters layer which shows user data to apply the filter, and when the "apply filters"  button is clicked, it triggers a "submit" event which is reaching all the up to the wizard form which is incrementing the active step and moving to the next step.
is there any way or configuration available in the component (I believe the data table is using a data filters component to filter the data) to stop this event from reaching its parent, so that only the filters get applied and the related data is shown in the table?
Please let me know if there are any other issues that I could be overlooking?

### Expected Behavior

the submit event should not propagate to the wizard . It should stop at the data table level and show the selected filtered result

### Actual Behavior

The submit event on data table template triggers submit event which propagates to its parent wizard component . This submit event in wizards moves the wizard to the next step which is not desired.

**Comment by taysea** [comment]
I created this CodeSandbox to recreate the issue: https://codesandbox.io/s/adoring-dubinsky-4rkmrx?file=/src/components/wizard/WizardValidationExample.js:1178-1212
