### ISSUE TITLE
Certain Box types are not exposed

### ISSUE THREAD

**Issue by Cpt-Falcon** [grommet/grommet#6977]
Trying to create a component that extends the box, and the issue is that some of the box types aren't extensible because they're not exported. BoxStyleType is not exported, but for some reason EdgeSizeType is. 

All box types should be exported if someone needs to extend a grommetjs component.

![image](https://github.com/grommet/grommet/assets/10540204/3de0a693-4325-479c-b868-b0fcf3457ee8)

These types here need to have the keyword export added in front of them so that they could be used in a component that had a prop that needed to be passed in like the BoxStyleType. Exporting these will help to prevent typescript errors and complaints.

### Steps to Reproduce

N/A

### Your Environment

N/A

**Comment by SaiAdithya3** [comment]
Hi, I will work on it and make sure that all those components are exported. 

Regards, 
Adithya

**Comment by Cpt-Falcon** [comment]
> Hi, I will work on it and make sure that all those components are exported.
> 
> Regards, Adithya

Thanks very much!

**Comment by jcfilben** [comment]
Resolved by https://github.com/grommet/grommet/pull/6979
