### ISSUE TITLE
No swiping functionality in Carousel component 

### ISSUE THREAD

**Issue by jim-king-2000** [grommet/grommet#6978]
I saw #343 and #423. But I swipe the Carousel component, nothing happened. Can Carousel be swiped or not?

**Comment by jcfilben** [comment]
It looks like Carousel doesn't currently support swiping. Marking this issue as an enhancement.

The PR referenced is from grommet v0.5.3, which is quite a while ago. I'm guessing somewhere along the way that functionality was dropped.

**Comment by jim-king-2000** [comment]
Thanks for the quick response. Hope it could be added soon.
