### ISSUE TITLE
NumberInput shows scrollbar on narrow widths

### ISSUE THREAD

**Issue by nickjvm** [grommet/grommet#698]
### Expected Behavior
When `FormField` is a child of `FormField` which has a width of < 300px, the input field should scale to fit the width without the need for a horizontal scrollbar

### Actual Behavior
`NumberInput` overflows the `FormField` parent, and a horizontal scrollbar is displayed.

### URL, screen shot, or Codepen exhibiting the issue
Here's a Codepen that serves as a nice starting point for demonstrating an issue: http://codepen.io/nickjvm/pen/akVgaV

![image](https://cloud.githubusercontent.com/assets/4998403/16822666/4ce1cc68-491b-11e6-812c-9efbe534066a.png)

Proposed CSS adjustments to resolve the issue are included in the Codepen link.

### Environment

* Grommet version: Latest
* Browser Name and version: Firefox & Chrome latest
* Operating System and version (desktop or mobile): Windows

**Comment by bryanjacquot** [comment]
@nickjvm thanks for the information.  A PR with the proposed CSS adjustments would be awesome.

**Comment by jwijay** [comment]
Tested the codepen (http://codepen.io/nickjvm/pen/akVgaV) and grommet-docs NumberInput example, and both work as desired (without scrollbar) on IE11 (Windows), Chrome (Windows/OSX), Firefox (Windows/OSX) and Safari (OSX).

![ie11numberinput](https://cloud.githubusercontent.com/assets/10161095/17538436/00c37be8-5e41-11e6-8a95-460f23f67878.PNG)
