### ISSUE TITLE
Instructions to build old grommet 0.5.3

### ISSUE THREAD

**Issue by ltWolfik** [grommet/grommet#6980]
Hello. For some old project I'm trying to build grommet 0.5.3 and am getting set of different problems.
I've noticed there used to be instructions for this by reference:
[Building-Grommet](https://github.com/HewlettPackard/grommet/wiki/Building-Grommet)
But now it's invalid.
Can someone publish here lost instructions?
I will be grateful.

**Comment by jcfilben** [comment]
Hey @ltWolfik I'm not sure where those instructions would have ended up, grommet 0.5.3 is pretty old at this point. The latest version of grommet is `2.33.2`, if it is possible I would encourage upgrading to get the latest features and support

**Comment by ltWolfik** [comment]
@jcfilben, thank you for reply! 
it turns out that Github Wiki Pages is itself separate git project. 
So I've found the instructions like this:
```shell
git clone https://github.com/grommet/grommet.wiki.git
cd ./grommet.wiki
git checkout <HASH>
```

I also succeeded to build grommet 0.5.3 like this (actually, I also solved several problems with dependencies):
```shell
sudo gem install -v 0.38.0 scss_lint
export PATH="/usr/lib64/ruby/gems/3.2.0/gems/scss_lint-0.38.0/bin:$PATH"
nvm use v6.17.1
rm -rf ./node_modules
npm install
npm install -g gulp
gulp dist
```
