### ISSUE TITLE
autoFocusingTags regex unintentionally matches `<data` and `<meta`

### ISSUE THREAD

**Issue by lukaw3d** [grommet/grommet#6981]
https://github.com/grommet/grommet/blob/7ad63c7326a531cf8b4997143346c204291420a1/src/js/utils/DOM.js#L160

matches `data` and `meta` elements

**Comment by aditya000099** [comment]
can you assign this to me?

**Comment by lukaw3d** [comment]
Update: this would match various web-components too

**Comment by jcfilben** [comment]
Resolved by #7174
