### ISSUE TITLE
Revisit smart defaults for ordering/positioning/placement of the Toolbar anatomy

### ISSUE THREAD

**Issue by halocline** [grommet/grommet#7003]
For MVP, we may not want to commit to the smart defaults provided by the API surface. We may want to take a "composition first" approach and allow that to drive what smart defaults evolve.

To do:
- [x] Do we want to support `toolbar` prop? Yes, this supports the 80%
- [x] If so, are we happy with the values/order? If not happy, what do we want to change? Yes, the current values and order support the 80% case and recommended order.
- [x] If we don't want to support with MVP, remove from functionality and file enhancement ticket for future.: We will support in MVP.

**Comment by halocline** [comment]
Related to [#6731](https://github.com/grommet/grommet/issues/6731)

**Comment by taysea** [comment]
Closing as of discussion on 1/4 and answers noted above.
