### ISSUE TITLE
Enhancement : DataSearch to trigger search onenter, instead of onchange

### ISSUE THREAD

**Issue by anoopadvaitha** [grommet/grommet#7024]
### Expected Behavior
DataSearch Component should give an option to choose us to select whether to search onchange or onsubmit/or enter.

### Actual Behavior
DataSearch triggers search as soon as I start typing, this causes issue if we are using REST API triggers a lot of API calls.

### Steps to Reproduce

1. 2. 3.

### Your Environment

- Grommet version: 2.34.1
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by anoopadvaitha** [comment]
Open to contribute if accepted.

**Comment by jcfilben** [comment]
Hi @anoopadvaitha this seems like a reasonable enhancement

**Comment by taysea** [comment]
This is closed by #7110
