### ISSUE TITLE
RangeSelector -- floating point step issue

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#7030]
### Expected Behavior

RangeSelector should support floating point step cleanly.

### Actual Behavior

When step is a value like `0.15`, for example, there can be resulting issues with the floating point addition that results in an undesired value. As this compounds, it can lead to cases where the keyboard can't get back to the "min".  Notice the console log statement in below video which is the [min, max], step.

### URL, screen shot, or Codepen exhibiting the issue

https://github.com/grommet/grommet/assets/12522275/0b96d2c3-a288-47c7-9306-517d7a817f6e

### Steps to Reproduce

1. Step min to 0, max to 3
2. Set step to 0.15
3. Set `label` true on RangeSelector to see bounds
4. Use arrow keys to move lower bound to the right a handful of times

### Your Environment

- Grommet version: 2.34.1
- Browser Name and version: MacOS Chrome
- Operating System and version (desktop or mobile):

**Comment by joaoGabriel55** [comment]
I can work on that

**Comment by taysea** [comment]
Closed by https://github.com/grommet/grommet/pull/7033
