### ISSUE TITLE
Extend prop type issue with SCv6 and v2.35.0-alpha.1

### ISSUE THREAD

**Issue by buberdds** [grommet/grommet#7048]
How can I use `extend` prop in the v2.35 or how should I correctly type it?

### Expected Behavior

I can define my custom theme without encountering ts errors.

### Actual Behavior

In the SCv5 and Grommet v2.34 Navigate to any code that uses `extend` prop `src/js/all/stories/CustomThemed/ExtendTheme.tsx`. If you hover over `extend` props arg you can see a type like `ExtendProps<T>`

With styled-components v6 and grommet v2.35.0-alpha.1 ts will complain because ` Parameter 'props' implicitly has an 'any' type, but a better type may be inferred from usage.`
`

### URL, screen shot, or Codepen exhibiting the issue
any place in a code base with `extend` prop usage, sample:`src/js/all/stories/CustomThemed/ExtendTheme.tsx`

### Steps to Reproduce

Switch deps to the latest SC and Grommet alpha

### Your Environment

- Grommet version: v2.35.0-alpha.1, SCv6

**Comment by jcfilben** [comment]
It seems like this behavior is happening in v2.34.1 with styled components v5, so it doesn't look like it is an issue with v2.35.1-alpha + styled-components 6.

codesandbox with grommet v2.34.1 and styled-components 5: https://codesandbox.io/p/sandbox/grommet-v2-template-forked-hj4t7s?file=%2Findex.tsx%3A13%2C5

**Comment by buberdds** [comment]
Ok, thanks for checking.
