### ISSUE TITLE
How does Menu Component get e.preventDefault working in the example?

### ISSUE THREAD

**Issue by stonecold123** [grommet/grommet#705]
I can't understand how the menu examples in the document manage to get e.preventDefault() working to avoid jumping to the top of the document on click.
Do you add a onClick function on the menu?

Here's a [codepen](http://codepen.io/stonecold1111/pen/qNxEOY?editors=1010) example where the menu is in a tile. I have added a click function, but it isn't working.

````
render(){
   <Grommet.Menu onClick={this._onClickMenu.bind(this)} inline={false}>
}
 ......
  _onClickMenu(e){
      e.preventDefault();
  }
````

**Comment by alansouzati** [comment]
Menu currently does not support onClick function.

The jump to the top is an existing issue in grommet:

https://github.com/grommet/grommet/issues/690

I'm closing this one, please use the other issue to track the progress.
