### ISSUE TITLE
DataSort and DataFilters - determine a reasonable default behavior

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#7063]
Having both `DataSort` and `DataFilters` results in some strange behavior. After selecting ‘sort by’ and ‘sort direction’ those fields show up in DataFilters. It feels like they should not show up in DataFilters.

This behavior is coming from https://github.com/grommet/grommet/blob/master/src/js/components/DataFilters/DataFilters.js#L110-L112
If `DataFilters` doesn't have children and `view.sort` is defined, `DataFilters` will include `DataSort` within.

What is the 80% case when using DataSort. Do we expect it should be within DataFilters or a separate control?

### URL, screen shot, or Codepen exhibiting the issue

https://github.com/grommet/grommet/assets/54560994/7eca31ee-f346-4f8c-9923-7b789e4c62b6

### Steps to Reproduce

1. https://storybook.grommet.io/?path=/story/data-data-properties--properties
2. Notice the DataFilters drop initially only shows a location filter
3. Open the DataSort drop and select a property to sort by and a direction
4. Open the DataFilters drop. Notice the drop content now includes DataSort.

**Comment by taysea** [comment]
After some discussion with Matt:

- [ ] Decouple "DataSort" from "DataFilters" -- sort control should be a peer to filters as opposed to nested inside it. Located to the left of filters (to ensure consistency of placement of filter/clear filters as "end of list" and search as "start of list")
- [ ] DataView control should be placed to the right of the Filter/Sort controls
- [ ] Based on [designs](https://www.figma.com/file/bMVkdgHkimCENGHiKPGcYH/Maps?type=design&node-id=1260-91540&mode=design&t=ABgPyLwvKbDaPeLj-0), reassess spacing between and within regions.
