### ISSUE TITLE
DataSort - no hover styling or tooltip

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#7064]
### Expected Behavior
When I hover over the DataSort control I am expecting to see hover styling and a tooltip similar to DataFilters

### Actual Behavior
There is no hover behavior or tooltip.

### URL, screen shot, or Codepen exhibiting the issue

https://storybook.grommet.io/?path=/story/data-data-properties--properties

### Steps to Reproduce

Go to the above story and hover over the DataSort control

**Comment by abdulbasithqb** [comment]
Hey @jcfilben can i work on this ?

**Comment by jcfilben** [comment]
Hey @abdulbasithqb feel free to work on this
