### ISSUE TITLE
Question - DOM props

### ISSUE THREAD

**Issue by OhNoAga** [grommet/grommet#7068]
Hi

I have a question, how did you manage to get rid of passing props to the DOM without using Transient props (eg. $color) or shouldForwardProp ?

**Comment by jcfilben** [comment]
Prior to styled componets v6 `shouldForwardProp` was provided by default. Notice in the grommet styled components v6 branch (https://github.com/grommet/grommet/tree/styled-components-beta) we are manually specifying `shouldForwardProp`
