### ISSUE TITLE
StarRating - Form value not synched

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#7071]
### Expected Behavior
If the Form has a value for the StarRating field the StarRating component should reflect that

### Actual Behavior
The StarRating doesn't show the value

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/p/sandbox/grommet-v2-template-forked-tdlvg8?file=%2Findex.tsx%3A42%2C14

**Comment by abdulbasithqb** [comment]
Hey, I was looking into this issue. I fixed it, but one Jest test failed. The test is in src/js/components/StarRating/tests/StarRating-tests.tsx:5:58. 
<img width="1038" alt="Screenshot 2023-12-20 at 6 17 59 PM" src="https://github.com/grommet/grommet/assets/134603758/bf58b24d-e019-4c9f-82dd-659d584b9f7f">

**Here are the code changes. Please let me know if I made any mistakes. Thanks.**
https://github.com/grommet/grommet/compare/master...abdulbasithqb:grommet:fixes/form-value-start-rating-sync?diff=split&w=

**Comment by abdulbasithqb** [comment]
> Hey Team, I was looking into this issue. seems like almost fixed & working as expected, but one Jest test failed. The test is in src/js/components/StarRating/tests/StarRating-tests.tsx:5:58. can somebody help me to figure out this issue, or do you have any idea why this is failing ? <img alt="Screenshot 2023-12-20 at 6 41 13 PM" width="1038" src="https://private-user-images.githubusercontent.com/134603758/291901315-ea5ff51d-a12b-4a21-a19e-0d4d0b6fc125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzk5MjksIm5iZiI6MTcwMzEzOTYyOSwicGF0aCI6Ii8xMzQ2MDM3NTgvMjkxOTAxMzE1LWVhNWZmNTFkLWExMmItNGEyMS1hMTllLTBkNGQwYjZmYzEyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwNjIwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGY0ZDlmZWYxYjhlYTViMjlmYWRiNGRjODAyYjBhZmQ1YjNjYjVhMDk3ZjM2ZmI4ZmY0MzAwNjkzMTJiNjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5LiGWIe__9ksna6dvmBSOOU9qHVzxrqBpQT_KmxrIbM">
> 
> **Here are the code changes. Please let me know if I made any mistakes. Thanks.** https://github.com/grommet/grommet/compare/master...abdulbasithqb:grommet:fixes/form-value-start-rating-sync?diff=split&w=

Hey @jcfilben could you have a look

**Comment by jcfilben** [comment]
Hey @abdulbasithqb your code looks good, I think the `onChange` in StarRating just needs to be changed to use `event.value` instead of `event.target.value`. This should preserve the number value instead of converting it to a string.
```
onChange={(event) => {
  setValue(event.value);
}}
```

**Comment by abdulbasithqb** [comment]
> Hey @abdulbasithqb your code looks good, I think the `onChange` in StarRating just needs to be changed to use `event.value` instead of `event.target.value`. This should preserve the number value instead of converting it to a string.
> 
> ```
> onChange={(event) => {
>   setValue(event.value);
> }}
> ```

Thanks, this solution working as expected,
