### ISSUE TITLE
SelectMultiple - adding additional options within `onSearch`

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#7074]
### Expected Behavior
When I search within SelectMultiple I should be able to use my search term to query a backend to fetch more options that were not available already in the `options` array.

### Actual Behavior
The internal `allOptions` prop doesn't get updated to reflect the new options. SelectMultiple is currently built in a way that `onSearch` can't change `options` to something that isn't a subset of the previous `options`.

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/p/sandbox/grommet-v2-template-forked-ht9y6h?file=%2Findex.js%3A16%2C34

### Steps to Reproduce
In the above codesandbox example search for 'cd', notice new options were added but the new options can not be selected

### Your Environment
- Grommet version: 2.34.2
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by MikeKingdom** [comment]
To support scalability, both Select and SelectMultiple need to be changed so they don't rely on having all the options in allOptions . I looked at this a bit before the break and it's not trivial, but the code that tries to map indexes from one to the other shouldn't have to do it that way. We shouldn't attempt to somehow add new stuff to allOptions based on an async search query and a selection list shouldn't be index based.
