### ISSUE TITLE
Feature Request: Add more granular widths/heights to choose

### ISSUE THREAD

**Issue by Cpt-Falcon** [grommet/grommet#7090]
It would be great to have some more granular size options available. The difference between medium, large, and extra-large is quite substantial. I often have to resort to using sizes like 500px when i'd rather use the descriptive medium/large type sizes. 

I've seen some other frameworks provide options like medium medium1, medium2, medium3, ... medium n, etc. Something like that to enable granular control. Even just having a medium large option or large/xlarge in between would be helpful. 

GrommetJS only has medium, large, extra-large options which often is not quite right to fit something properly.

**Comment by taysea** [comment]
Hi @Cpt-Falcon you can configure sizes however you'd like by building your own theme. You can name them whatever you want and choose whatever values you'd like. Here's an example of extending grommet's theme to include your own sizes for width/heights. The same could be done for padding/border sizes/etc.

```
const baseSpacing = 24;

const grommet = deepMerge(grommetPublished, {
  global: {
    size: {
      xxsmall: `${baseSpacing * 2}px`, // 48
      xsmall: `${baseSpacing * 4}px`, // 96
      'xsmall-small': `${baseSpacing * 6}px`, // 144
      small: `${baseSpacing * 8}px`, // 192
      'small-medium': `288px`, // can also just hardcode values
      medium: `${baseSpacing * 16}px`, // 384
      'medium-large': `576px`,
      large: `${baseSpacing * 32}px`, // 768
      'large-xlarge': `960px`,
      xlarge: `${baseSpacing * 48}px`, // 1152
      'xlarge-xxlarge': `${baseSpacing * 32}px`, // 768
      xxlarge: `${baseSpacing * 64}px`, // 1536
      full: '100%',
    },
  },
});
```

Result of doing `<Box width="small-medium" height="medium" />`

<img width="492" alt="Screen Shot 2024-02-02 at 11 47 52 AM" src="https://github.com/grommet/grommet/assets/12522275/ea646c03-e382-4225-abb0-94101c99cd4f">


<img width="470" alt="Screen Shot 2024-02-02 at 11 47 57 AM" src="https://github.com/grommet/grommet/assets/12522275/977c560a-a174-4b17-bd94-71376b2e157f">

**Comment by jcfilben** [comment]
Hey @Cpt-Falcon hopefully Taylor's comment helped you out, I'm going to mark this as closed. Feel free to reach out if there are any additional questions.
