### ISSUE TITLE
Unable to use plain html tags inside FormField

### ISSUE THREAD

**Issue by Moullisha** [grommet/grommet#7095]
Using html tag inside FormField doesn't update the data and touched property comes out to be empty even though a value was entered for the input field.

### Expected Behavior

Use of html tags should be allowed inside Grommet forms

### Actual Behavior

Using an html tag inside a Grommet form doesn't update the value of the field.

### URL, screen shot, or Codepen exhibiting the issue

Code sample -> https://codesandbox.io/s/priceless-darkness-f5dnfl?file=/src/App.js:496-501

**Comment by taysea** [comment]
I believe this was answered here: https://grommet.slack.com/archives/C09QQEG69/p1706303661601269?thread_ts=1706093288.357739&cid=C09QQEG69

Copying text:

Components which contribute to the state of a Form tend to do so by explicitly calling a setValue on the FormContext. For example, TextInput has
```
    const [value, setValue] = formContext.useFormInput({
      name: readOnly ? undefined : name,
      value: valueProp,
    });
```

And it's internal onChange calls this setValue If you want some random or custom component/input to interact with the Form value, validation, etc, You'd have to do something similar.

**Comment by jcfilben** [comment]
Marking as resolved, feel free to re-open if needed
