### ISSUE TITLE
Conflicting peer dependency versions in Grommet package installation

### ISSUE THREAD

**Issue by 97revenge** [grommet/grommet#7107]
### I'm having this error in a `create-next-app@latest` application (app directory and pages directory) when I update the Groomet package with npm. I have some conflicting versions of the `style-components` required by Grommet but it seems that the root project requires version 6.1.8, while Grommet specifies version 5.1.0. I used `--force` flag and I think I made the problem a little worse.

```
 npm install grommet styled-components --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gemini-getting-started@0.1.0
npm ERR! Found: styled-components@6.1.8
npm ERR! node_modules/styled-components
npm ERR!   styled-components@"^6.1.8" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer styled-components@"^5.1.0" from grommet@2.34.2
npm ERR! node_modules/grommet
npm ERR!   grommet@"^2.34.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
``` 

but, look my `npm outdated` , none of this issue : 
```
npm outdated
Package         Current    Wanted    Latest  Location                     Depended by
@prisma/client    5.8.1     5.9.0     5.9.0  node_modules/@prisma/client  gemini-getting-started
@types/node     20.11.5  20.11.10  20.11.10  node_modules/@types/node     gemini-getting-started
prisma            5.8.1     5.9.0     5.9.0  node_modules/prisma          gemini-getting-started
``` 

### Steps to Reproduce

1. `git clone https://github.com/97revenge/gemini-getting-started`
2. `npm install`
3. `npm run dev`

### Your Environment

_Node.js project (v0.1.0), utilizing Next.js, React, Grommet, Tailwind CSS. It includes scripts for development, build, and lint, with specific versions for dependencies like Grommet and styled-components._

- Grommet version:
``` 
"grommet": "^2.34.2",
```
- Browser Name and version:
Google Chrome 100% updated
- Operating System and version (desktop or mobile):
``` 
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v20.10.0

```

**Comment by britt6612** [comment]
@97revenge can you try using grommet beta version? `2.35.0-alpha.1` This has the support for styled-components v6 and above, so that may help your problem with needing `styled-components@"^6.1.8"`
