### ISSUE TITLE
[TypeScript] List component types don't correctly support render props

### ISSUE THREAD

**Issue by Tbhesswebber** [grommet/grommet#7160]
### Expected Behavior

When using the `List` component in TS with a render prop function as `props.children`, the types should be correctly inferred, either from an explicit passing of the generic type or inference from the passing of typed data.

### Actual Behavior

The types for `props.children` seem to have been set in such a way that inference expects a union of `(((...args: any[]) => Element) & (string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode> | ReactPortal | null)) | undefined`.

### URL, screen shot, or Codepen exhibiting the issue

<figure>
<img alt="TS errors when passing a generic" src="https://github.com/grommet/grommet/assets/28069638/2ff16604-7076-43c8-8455-3a42371827d7" />
<br />
<figcaption>In the current state, it seems that typescript expects a string for the children prop.</figcaption>
</figure>

<br />
<br />
<br />

<figure>
<img alt="TS errors when passing a string as recommended in the above screenshot" src="https://github.com/grommet/grommet/assets/28069638/790a7650-f397-4b6e-9ed4-90a831235232" />
<br />
<figcaption>When passing a string as recommended above, TypeScript provides a more useful response showing the intersection type expected.</figcaption>
</figure>

### Steps to Reproduce

See screenshots above - PR with fix incoming

### Your Environment

- Grommet version: 2.35.0
- TypeScript version: 4.9.5

**Comment by pabdev** [comment]
Facing the same issue with my code : [Details on SO](https://stackoverflow.com/questions/78158812/not-assignable-to-type-error-for-grommet-list-with-children-in-typescript) . Hope this issue will be fixed soon.

**Comment by jcfilben** [comment]
Related to https://github.com/grommet/grommet/issues/6836 and https://github.com/grommet/grommet/pull/7039
