### ISSUE TITLE
Expand all/Collapse all variation for Accordion

### ISSUE THREAD

**Issue by HeidiTosi** [grommet/grommet#719]
Expand all/Collapse all variation for Accordion

### Expected Behavior
Appreciate that the Accordion widget has been added to the Grommet library, but have noticed that there is no ability to see all rows expanded if desired. Is it possible to include a version that allows the user to expand all/collapse all?

### Actual Behavior
Current widget allows only one row to be expanded and collapses that row if another is expanded.

**Comment by bryanjacquot** [comment]
@HeidiTosi the `openMulti` option allows multiple rows to be expanded.  I know this isn't the expand / collapse all variation you mentioned, but it does add a bit of flexibility.

**Comment by HeidiTosi** [comment]
Thanks, Bryan. We will leverage the openMulti for our purposes. I would like to ask if the expanded content area of the accordion supposed to be indented like the row header. I would expect the lines of the accordion to span the full width of the container (similar to a table or list) which would leave the expanded content butting the container wall. Is this the expected display?

**Comment by bryanjacquot** [comment]
@HeidiTosi the latest Accordion doesn't indent the expanded content area.  It's up to the caller to add any desired padding.  However, the heading of accordion items have an unnecessary padding by default which should be left to the caller using a `padding` attribute.  We've added a new issue in a different repo to track this issue (long story).
