### ISSUE TITLE
Pagination endIndex fails to update if step is changed

### ISSUE THREAD

**Issue by thsmale** [grommet/grommet#7209]
Say there are a 1000 items I would like to paginate. If the step is 10 then there should be 100 pages. If the step is 100 then there should be 10 pages. Grommet will fail to change the pagination if the step changes from 10 to 100.

### Expected Behavior

The pagination component should be re rendered to update the `endIndex` if the step changes.

### Actual Behavior

If step is a dynamic value set using state, the pagination component fails to update the endIndex.

### URL, screen shot, or Codepen exhibiting the issue

Change the grommet version from 2.36.1 to 2.34.2 to observe the breaking change. 

[Code Sandbox](https://codesandbox.io/p/sandbox/grommet-v2-template-forked-smlv6x?file=%2Findex.js%3A2%2C47)
[Minimum Replicable Example Source Code](https://github.com/thsmale/grommet-step-pagination-issue)

### Steps to Reproduce

1. Create a Select component to dynamically set the `step` value
2. Set the Paginate `numberItems` to 1000 and set `step` to the state value from 1
3. Observe that Paginate does not update the `endIndex` 

Change the grommet version from 2.36.1 to 2.34.2 to observe the breaking change. 

### Your Environment

- Grommet version: 2.36.1
- Browser Name and version: Safari and Chrome
- Operating System and version (desktop or mobile): MacOS and Windows 10

**Comment by thsmale** [comment]
This functionality works as expected in grommet version 2.34.2. However, it fails in the most up to date grommet version 2.36.1.

**Comment by thsmale** [comment]
As shown in https://github.com/grommet/hpe-design-system/issues/3708 this is the use case I am looking to implement. I see `stepOptions` was added in 2.36.0 to achieve this behavior.

**Comment by thsmale** [comment]
Although I do not see `stepOptions` in the Grommet documentation for [Pagination](https://v2.grommet.io/pagination).

**Comment by britt6612** [comment]
@thsmale This is being added to grommet site for next release.

**Comment by thsmale** [comment]
Hi @britt6612, thanks for your response! So how will we know when the step was changed in `stepOptions`? Currently, `onChange` is not triggered when the value of `stepOptions` is changed. I would like to change the number of rows shown in the data table to the value selected in `stepOptions`. 

[Codesandbox](https://codesandbox.io/p/sandbox/grommet-v2-template-forked-vr8lpd)

**Comment by britt6612** [comment]
@thsmale this was a bug that was just fixed so if by chance you can use the stable branch then we have the fix on there. We are also planning a release this week so that fix will be included. 

The PR that fixed this is here. https://github.com/grommet/grommet/pull/7205
