### ISSUE TITLE
Add ability to provide colorIndex for simple meters

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#722]
### Expected Behavior
`<Meter value={40} colorIndex="critical" />` should render a red meter for single value.

### Actual Behavior
colorIndex only works inside series, which is inconsistent.

### Your Environment
* Grommet version: Latest
* Browser Name and version: Any
* Operating System and version (desktop or mobile): Any

**Comment by ericsoderberghp** [comment]
Added in commit 62098bf36a0ee3aa9962b8724ea28196d4ead42e.
