### ISSUE TITLE
Need a fix to the Meter-Circle, Series, Legend with 1 item

### ISSUE THREAD

**Issue by HeidiTosi** [grommet/grommet#723]
Need a fix to the Meter-Circle, Series, Legend with 1 item

### Expected Behavior
I would expect the legend to retain the same font size and total alignment as when items listed are greater than one. Also I would expect the total to stay in position outside the dial as when items listed are greater than one.

### Actual Behavior
When only one item is display with a legend, the total appears inside the dial and the font size of the count within the legend jumps up in size.

### URL, screen shot, or Codepen exhibiting the issue

<Grommet.Meter type="circle" legend={true} size="small" series={[
  {"label": "Critical", "value": 0, colorIndex: "error"},
]} />

![meter-circleserieslegend-1item](https://cloud.githubusercontent.com/assets/17186165/17194326/7598e3a2-5425-11e6-8341-e53fddcf07a8.png)

### Your Environment
* Grommet version: Codepen latest
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): desktop

**Comment by ericsoderberghp** [comment]
Please refer to the new style of doing Meters. http://grommet.us.rdlabs.hpecorp.net/meters/#22
You can control the Legend position independently from the Meter itself.
