### ISSUE TITLE
Cannot upgrade styled-components v6 with Grommet 2.37.0

### ISSUE THREAD

**Issue by fostertime** [grommet/grommet#7239]
NPM cannot resolve the dependency of styled-components@^5.1.0 with styled-components^6.1.11

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: project@2.2.0
npm ERR! Found: styled-components@6.1.11
npm ERR! node_modules/styled-components
npm ERR!   styled-components@"^6.1.11" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer styled-components@"^5.1.0" from grommet@2.37.0
npm ERR! node_modules/grommet
npm ERR!   grommet@"^2.37.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
``` 

Running the following:

- Node: v20.x
- React: 18.3.1
- Grommet version: 2.37.0
- styled-components: 6.1.11

I've tried wiping out node_modules, package-lock... not sure what else might be going on.

**Comment by taysea** [comment]
Hi there, grommet v2.37.0 is not yet compatible with styled-components v6. That said, we just [merged a PR with styled-components v6 support](https://github.com/grommet/grommet/pull/7165) which will be included in our next release. Stay tuned for that soon.

For now, use styled-components v5 in your project.

**Comment by fostertime** [comment]
Ah. Well that makes sense. I thought I saw that 2.35 or 6 had support for styled components v6. My mistake. Thank you for the update!
