### ISSUE TITLE
Display issue of dashboard cycle : some parts are overlapped

### ISSUE THREAD

**Issue by wutaosh** [grommet/grommet#725]
I guess below code is related to the issue:
1.	grommet/components/meter/Graphic.js line:136, startValue += Math.max(MIN_WIDTH * this.props.max.value, item.value);
2.	grommet/components/meter/Circle.js  line:63, var endAngle = Math.max(startAngle + (item.value > 0 ? RING_THICKNESS / 2 : 0), (0, _utils.translateEndAngle)(startAngle, this.state.anglePer, item.value));

### Expected Behavior
When mouse over green part, the green part should be thicker, the rest part should be thinner; if mouse over red part, the red part should be thicker, the rest part should be thinner. And there shouldn't be some part overlapped.
### Actual Behavior
The red part is overlapped with green part. 
### URL, screen shot, or Codepen exhibiting the issue
https://github.com/HewlettPackard/oneview-hubble/issues/523
### Your Environment

* Grommet version: 0.6.7
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): desktop win7

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/f15c609326a543d354251b5b357b8468db6b632a
