### ISSUE TITLE
Select multiple do not honour the order of selection

### ISSUE THREAD

**Issue by sabarnix** [grommet/grommet#7274]
https://storybook.grommet.io/?path=/story/input-selectmultiple-inside-a-formfield--inside-form-field
in the example if your order of selection is "Grape", "Banana" and then "Kiwi", the dropdown selection will show "Banana", "Grape" , "Kiwi". It orders the selection according to list.

It's not a big deal in the example as checkboxes are shown besides the options. Image if we don't show the checkbox and hide the selected value from the list. In that case the order of selection matters. There could be use cases where order of selection is important.

### Is this something you or your team is interested in contributing a pull request towards?

yes
### Expected Behavior

The selected value should be shown based on the order of selection

### Actual Behavior

The selection is ordered based on the list.

### URL, screen shot, or Codepen exhibiting the issue

https://storybook.grommet.io/?path=/story/input-selectmultiple-inside-a-formfield--inside-form-field

### Your Environment

- Grommet version: latest
- Browser Name and version: chrome
- Operating System and version (desktop or mobile): desktop mbp

**Comment by jcfilben** [comment]
Hi @sabarnix thanks for sharing your proposal. I'm not sure if I am understanding the use case correctly. 

> It's not a big deal in the example as checkboxes are shown besides the options. Image if we don't show the checkbox and hide the selected value from the list. In that case the order of selection matters. There could be use cases where order of selection is important.

It seems like there could be usability and accessibility issues with a design like this. I'm also not understanding why the selection order is important in the scenario you described

**Comment by sabarnix** [comment]
![image](https://github.com/user-attachments/assets/08c62c5d-7fcd-4148-9122-0d7013ca1f4c)
Our select roughly looks like this. And in our case the order matters. 

One of the popular multiselect component https://react-select.com/home also retains the order. I think that should be the expected behaviour. The way react-select uses multiselect is very common. I don't see any usability or accessibility issue with it.

**Comment by jcfilben** [comment]
Thanks for sharing the image, that is helpful to visualize. I'm not sure that it is currently possible to achieve this type of design using the grommet multi-select component, regardless of wether the order of selection is retained or not. My concerns with accessibility stemmed from this comment:
>  Image if we don't show the checkbox and hide the selected value from the list.
In the image above it looks like you have two lists, one of selected items and one of unselected items. When someone makes a selection and the item moves from the unselected list to the selected list does the keyboard focus move with it? How does the screenreader provide context to a user that the item has moved and that item has been selected but moved to a new list

**Comment by jcfilben** [comment]
Resolved by #7291
