### ISSUE TITLE
DateTime picker month switching not working

### ISSUE THREAD

**Issue by jackychow** [grommet/grommet#728]
When hitting the next (or previous) arrow of the pop up calendar for switching to a different month, the calendar would close and call the onChange function with a moment object instead of switching the calendar.

For the demo from documentation:
http://www.grommet.io/docs/develop/datetime

All of the DateTime components throws error when I try to interact with the calendar. So I cannot tell if I'm not using the component as it should or there is a bug somewhere.

Can someone shed some light on this? Thanks in advance!

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/97cdc90beee92a61939ad78cb05e5a6a47adbeee.

We will soon release a new version of Grommet including this fix.

In the meantime you can use the stable branch.

Update your package.json entry to the following, and run npm install:

```
{
  ...
  "grommet": "https://github.com/grommet/grommet/tarball/stable"
}
```

**Comment by alansouzati** [comment]
I've also updated the site, thanks for reporting this.

**Comment by jackychow** [comment]
@alansouzati Thanks for the fast response! you guys rock.
