### ISSUE TITLE
Bug when set JSX elements in Select options prop

### ISSUE THREAD

**Issue by cassa10** [grommet/grommet#7287]
### Context
I recently update to the last grommet version from (<= v2.25.2). When I set JSX elems in options props in Select component, then it doesn't show any option.

Looks like this stopped working v2.25.2 which does seem like a bug.

Example of code:
```javascript
    // color is a hexa value
    <Select
      options={colors.map((color) => (<StatusGoodSmall size="small" color={color} />))}
      value={<StatusGoodSmall size="large" color={initialColor} />}
      onChange={({ option }) => setColor(option.props.color)}
    />
```

### Is this something you or your team is interested in contributing a pull request towards?

No by now.

### Expected Behavior

Should show options rendering jsx elements (eg: Icon from grommet-icons) 

[Codesandbox with expected behavior using previous versions](https://codesandbox.io/p/sandbox/selectmultiple-8h7hcp?file=%2Fsrc%2FApp.js%3A14%2C34-14%2C39)

### Actual Behavior

Do not show any option but handle onChange function successfully.

### URL, screen shot, or Codepen exhibiting the issue

[Codesandbox with issue](https://codesandbox.io/p/sandbox/selectmultiple-forked-jrdwf2)

### Steps to Reproduce

1. Code this component with some JSX element
2. Open Select input
3. No option is shown

### Your Environment

- Grommet version:` 2.39.0`
- Browser Name and version: `Chrome - Version 127.0.6533.89 (Official Build) (64-bit)`
- Operating System and version (desktop or mobile): `Windows 10 desktop`

**Comment by avantika-codes** [comment]
Hello @jcfilben and @cassa10,  I would like to work on this issue, could you please assign this to me?, meanwhile I am starting to work on the fixes

**Comment by jcfilben** [comment]
Hi @avantika-codes we usually don't assign issue but feel free to work on this and put up a pull request
