### ISSUE TITLE
LoginForm is not rendering properly

### ISSUE THREAD

**Issue by shridhargovindaiah** [grommet/grommet#730]
###Summary of Issue
LoginForm is not rendering properly, Email field and username field displays with horizontal scroll bars.
I am facing this issue after I upgraded grommet to 0.6.10 earlier it was working as expected.
### Expected Behavior
I hope scroll bar should not display in username and password textfield. 

### Actual Behavior
Login Fields displays with horizontal scroll bar which looks very wired. 

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/20173538/17253217/5dd6da2a-5575-11e6-903e-0f2d3ecdea45.png)

### Steps to Reproduce
 1. Import Login 
 2. Pass required parameters to Login component
 3. run gulp dist or gulp dev

### Your Environment
* Grommet version: 0.6.10
* Browser Name and version: Firefox 47.0
* Operating System and version (desktop or mobile): Ubuntu 14 on desktop

**Comment by gustahrodrigues** [comment]
Do you have a code pen to reproduce it?

I could not reproduce it using this one: [http://codepen.io/gustahrodrigues/pen/ZOjKwX?editors=1010](url)

**Comment by alansouzati** [comment]
Thanks for the follow up
