### ISSUE TITLE
UI issue when FormField label is a node and required

### ISSUE THREAD

**Issue by nnurmano** [grommet/grommet#7303]
I am using HPE theme and when FormField label is a node and required, the required indicator slips to the next row. 
<img width="359" alt="image" src="https://github.com/user-attachments/assets/f475ab9d-81ed-4d07-ab03-e1eb7ebeb736">

Here is a sandbox that illustrates the issue https://codesandbox.io/p/sandbox/grommet-v2-template-forked-d87lgp?file=%2Findex.js%3A34%2C34&workspaceId=724eced4-5631-43d4-a90e-1f99ee73f924

**Comment by britt6612** [comment]
@nnurmano Im not able to see the codesandbox can you make it public or paste the code snippet?

**Comment by nnurmano** [comment]
Made it public, sorry I did not know that it is private by default

**Comment by britt6612** [comment]
@nnurmano I see the issue now thank you for bringing up! Wondering if that container with the `label` and `required` needs a direction `row` would you be interested in submitting a PR?

**Comment by NOMADE55** [comment]
@britt6612 Please check my PR observations regarding this fix in https://github.com/grommet/grommet/pull/7435

**Comment by NOMADE55** [comment]
> > @britt6612 Please check my PR observations regarding this fix in #7435
> 
> Your node child could have `style="display: inline-flex;"` and get the desired effect.

I agree.

**Comment by jcfilben** [comment]
> > @britt6612 Please check my PR observations regarding this fix in #7435
> 
> Your node child could have `style="display: inline-flex;"` and get the desired effect.

Good comment, I think it makes sense to avoid building this style into the grommet component and instead people can add this to their custom FormField label node if needed. Going to mark this issue as closed.

**Comment by nnurmano** [comment]
Unfortunately, this does not solve the issue
When there is an icon, the asterisk is not above the label. 
<img width="412" alt="image" src="https://github.com/user-attachments/assets/b23ee13c-03e5-4662-af47-95e9c1890987">

**Comment by nnurmano** [comment]
Used the changes by @NOMADE55 & styled the FormField component

const StyledFormField = styled(FormField)`
  & label {
    display: flex;
  }
`;

**Comment by NOMADE55** [comment]
@nnurmano my changes have been dismissed.

Another solution could be to prevent the showIndicator from appearing, *even if required*, so you can control the asterisk's position manually within the label you created.
