### ISSUE TITLE
Layer -- console error when focus placed on HiddenAnchor for `modal`

### ISSUE THREAD

**Issue by taysea** [grommet/grommet#7330]
### Is this something you or your team is interested in contributing a pull request towards?

Yes.

### Expected Behavior

Opening a `modal` Layer should not result in a console error.

### Actual Behavior

Getting a console error when the "HiddenAnchor" in Layer receives focus when a `modal` layer opens.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://github.com/user-attachments/assets/47f5531a-8fac-4a81-9921-39b5a9fc3ec8)

### Steps to Reproduce

1. Open modal layer
2. See console error.

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by britt6612** [comment]
closing. Im not seeing the error on any of the Layer stories or used the story from trapFocus PR and console error is no longer there. https://github.com/grommet/grommet/pull/7324
