### ISSUE TITLE
Layer - when focus loops through layer the screen is scrolled down

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#7344]
### Is this something you or your team is interested in contributing a pull request towards?
Yes

### Expected Behavior
Moving focus in Layer should not cause the screen behind the Layer to scroll

### Actual Behavior
When tabbing through the focusable items in a Layer when focus loops back up to the first element the screen behind the Layer scrolls down

### URL, screen shot, or Codepen exhibiting the issue

https://github.com/user-attachments/assets/c474d34e-972f-4dd4-97b2-2792a7e0efd1

### Steps to Reproduce

This issue can be seen with the stable branch of grommet on the Design System site Layer example

### Your Environment

- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by vijaykr338** [comment]
I'd like to be assigned on this
