### ISSUE TITLE
Incorrect use of oneOf propType in the Menu component

### ISSUE THREAD

**Issue by jameswyse** [grommet/grommet#735]
I started getting the following warning in my console after upgrading to React 15.3.0:

```
Warning: Invalid argument supplied to oneOf, expected an instance of array.
```

The stacktrace was useless but I tracked it down to the Grommet `Menu` component. See [Menu.js:522](https://github.com/grommet/grommet/blob/master/src/js/components/Menu.js#L522) - it should be `PropTypes.oneOf(['expand'])` 😄 

Codepen: http://codepen.io/anon/pen/JKBkKy?editors=1111

**Comment by alansouzati** [comment]
Thanks for reporting this. Fixed by @digital-flowers at https://github.com/grommet/grommet/commit/1a0de326ffd60a6e7fbcaafd1db3e9f9eecb06d2.

This will be part of the upcoming release of Grommet.
