### ISSUE TITLE
Whitespaces are removed in the List children components

### ISSUE THREAD

**Issue by withpublic** [grommet/grommet#7362]
I have a TipTap editor as a children elements of the List component. It has an option to edit text. After I have upgraded Grommet, I suddenly noticed that when editing text, my whitespaces are removed. I did some researching and I found out that the reason is the following code which was introduced in newer version of Grommet. It was not in the 2.34.2 version.

```
	<Container {...containterProps}>
				<Keyboard
					onEnter={onSelectOption}
					onSpace={(event) => {
						event.preventDefault();
						onSelectOption(event);
					}}
```
Should onSpace method be in the List component? If it is included and the default behavior is prevented, then why onSelectOption did not contain the replacement for the default behavior?

**Comment by SaunakNandi** [comment]
"Perhaps we could add a check to see if the onClickItem prop is defined before running the prevent default or onSelectOption code."

I didn't understand what logic you were providing. @jcfilben

**Comment by jcfilben** [comment]
We only need to run `event.preventDefault` if `onClickItem` is defined
