### ISSUE TITLE
DataTable - Customized Header ( input ) acting as button when sort is used

### ISSUE THREAD

**Issue by zlobjul** [grommet/grommet#7371]
### Expected Behavior

If the header is customized , being a form field, input or date and the column is sortable , I want to have an option to use only the sort button sorting the column data , not the whole header acting as a button. 

### Actual Behavior

Clicking inside the form field , input or date field is sorting the column content , when sorting attribute is on . 

![image](https://github.com/user-attachments/assets/c753ebcb-3616-4eb4-8d20-a90529f0e98e)

### URL, screen shot, or Codepen exhibiting the issue

https://codesandbox.io/p/sandbox/grommet-v2-template-forked-26dnvq

### Your Environment

- Grommet version: 
 "grommet": "^2.40.1",
    "grommet-icons": "^4.12.1",
    "grommet-theme-hpe": "^4.2.0",

**Comment by jcfilben** [comment]
Hi @zlobjul I don't think the DataTable header is intended to support interactive elements within the header cell which is why the entire cell is clickable when the column is sortable
