### ISSUE TITLE
Search placeholder text is not shown in the SelectMultiple component

### ISSUE THREAD

**Issue by SagarTrimukhe** [grommet/grommet#7403]
### Expected Behavior
If the search placeholder text is passed to the SelectMultiple component, it should be shown.

### Actual Behavior
Even after passing the placeholder text, it is not visible. 
![image](https://github.com/user-attachments/assets/aa594409-4bfa-44b5-931e-9e53236e7f16)

### URL, screen shot, or Codepen exhibiting the issue
https://codesandbox.io/p/sandbox/grommet-v2-template-forked-rt6rzq?file=%2Findex.js%3A49%2C13&workspaceId=1db81884-81d8-45ad-928a-95ece9a44785

### Your Environment

- Grommet version: 2.37.0
- Browser Name and version: Google Chrome
- Operating System and version (desktop or mobile): MacOS

**Comment by jcfilben** [comment]
Hi @SagarTrimukhe the search field in the messages prop is used for the aria-label of the search component. There is not currently a messages prop for the search placeholder text

**Comment by SagarTrimukhe** [comment]
Closing the issue as 'searchPlaceHolder' prop is available to set the search text input placeholder
