### ISSUE TITLE
Using any text input within the `List` component means the space bar doesn't work

### ISSUE THREAD

**Issue by freshollie** [grommet/grommet#7414]
### Expected Behavior

Pressing space in a form within the `List` component should provide space. If you are using the ordering options from the list then I guess space has to be captured, but this feels too broad.

### Actual Behavior

The space key is captured by the parent `List` component and so the input is lost

### URL, screen shot, or Codepen exhibiting the issue

Commit which causes this.
https://github.com/grommet/grommet/commit/e3f45c2ab8936c5e663ba6ff066799c44616efbb#diff-ee3146f8c73eb2bd1a1428687a1146a43c49566dac00cc69fff1df8df50446f7R313

https://codesandbox.io/p/sandbox/grommet-v2-template-forked-gm4zqz?file=%2Findex.js%3A25%2C1

**Comment by MikeKingdom** [comment]
We should evaluate each of the keyboard handlers in List.js (onUp, onDown, onEnter, and onSpace.) Most only mess with the event (like event.preventDefault()) if `onClickItem` or `onOrder` are defined. The problem situation in this does event.preventDefault() whether or not `onClickItem` is specified.
