### ISSUE TITLE
Clock component to support timezones (Enhancement)

### ISSUE THREAD

**Issue by morelattes** [grommet/grommet#7417]
### Expected Behavior

To be able to configure <Clock /> component by timezone.

### Actual Behavior

The <Clock /> now picks up only browser/system time.

**Comment by MikeKingdom** [comment]
@morelattes You can set the initial time on Clock to whatever you want (and it will run from there.) So really all you need is the current offset from timezone you want:
```jsx
    <Clock type="digital" time={
      new Date().toISOString().replace('Z', '+08:00')
    } />
```
You can use one of the various timezone packages out there to pick your timezone.

**Comment by jcfilben** [comment]
Closing, see Mike's response above ^
