### ISSUE TITLE
New Charts browser specific render issues

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#742]
The new Charts component seems to render well in Safari however in Chrome and Firefox there are rendering issues. My current implementation of the component uses the full true property which may be contributing to the rendering issues. The components not rendering correctly in my current scenario are the Axis component and the Area component. The Axis does not render to scale with the chart and upon hover when the chart redraws it gradually loses height.
 
Below is a screen shot displaying the rendering issues:
![screen shot 2016-08-03 at 7 21 10 pm](https://cloud.githubusercontent.com/assets/5983843/17385421/971af8b8-59b0-11e6-9f5f-7353ffc267f9.png)

The current implementation uses the following code:
```
<Chart vertical={true} full={true}>
  <Base height="medium" width="full" />
  <Layers>
    <Area values={VALUES} colorIndex="graph-2" activeIndex={this.state.index} />
    <Area values={VALUES_2} colorIndex="graph-3" activeIndex={this.state.index} />
    <HotSpots count={VALUES.length}
      activeIndex={this.state.index}
      onActive={(index) => this.setState({
      index: (undefined === index ? (VALUES.length - 1) : index)
      })} />
    </Layers>
    <Axis ticks={true} count={10} labels={[
      {"index": 9, "label": 2014},
      {"index": 6, "label": 2010},
      {"index": 0, "label": 2000}
      ]} />
</Chart>
```

I have a [demo](http://162.243.249.132:8070/) posted for testing purposes.

**Comment by ericsoderberghp** [comment]
Chrome and Firefox issue should be fixed now.
Updated Axis documentation to indicate how to manage count and labels.
http://grommet.github.io/docs/chart-axis
