### ISSUE TITLE
Meter component flashes continueously

### ISSUE THREAD

**Issue by songhaifeng** [grommet/grommet#743]
Meter component flashes continueously when item name length is large

### Expected Behavior

Meter component should have a fixed width for total number shown beside bar.

### Actual Behavior

When I have three items with different length of name in Meter, the meter will flash continuously quickly with mouse hovering over a certain place.

### URL, screen shot, or Codepen exhibiting the issue
![barmeter](https://cloud.githubusercontent.com/assets/16793801/17388686/543625ec-5a30-11e6-90bd-54d471a32864.gif)

### Steps to Reproduce
To reproduce: see the dynamic gif

### Your Environment

* Grommet version: 0.6.7
* Browser Name and version: Chrome 51.0.2704.103
* Operating System and version (desktop or mobile): Windows 10

**Comment by ericsoderberghp** [comment]
Have you tried using the latest Meter patterns? http://grommet.github.io/docs/meter-examples/#17
Of note, we're recommending using a Value above the meter graphic and a Legend below, partly to avoid some of the layout issues you are reporting.

**Comment by songhaifeng** [comment]
Thanks for giving an approach to work around it.

**Comment by bryanjacquot** [comment]
The new Meter / Legend example is the recommended approach for handling this.  The latest Legend also handles right-aligning values properly.
