### ISSUE TITLE
Close Notification

### ISSUE THREAD

**Issue by bjackson** [grommet/grommet#750]
It might be helpful in some use cases to have an "x" displayed in the corner of a notification so that a user can acknowledge and close a notification.

**Comment by alansouzati** [comment]
Definitely an interesting enhancement to the Notification component. Would you be willing to submit a pull request for that? 😄

**Comment by bjackson** [comment]
I'm no CSS expert, but I'd be happy to help.

@phuson are you already on the case?

**Comment by phuson** [comment]
@bjackson Yup, I will hopefully have the PR ready by the end of today or at the latest, Monday.

**Comment by bryanjacquot** [comment]
https://github.com/grommet/grommet/pull/779

**Comment by bjackson** [comment]
Awesome! Thank you so much!
