### ISSUE TITLE
Icons within Form Fields are not properly aligned.

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet#752]
### Expected Behavior
Icons for within Form Fields such as SearchInput, Calendar, and DateTime should be vertically centered.

### Actual Behavior
Icons are aligned close to the top of the text input boxes.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/6393696/17498303/c7a798ac-5d83-11e6-94e5-5f7f148d6e97.png)

![image](https://cloud.githubusercontent.com/assets/6393696/17498306/d346f838-5d83-11e6-8572-23a0a8224566.png)

![image](https://cloud.githubusercontent.com/assets/6393696/17498315/dce7bf9e-5d83-11e6-824a-e37874d7b5c1.png)

### Steps to Reproduce
Look at components on docs site.

### Your Environment

* Grommet version: latest stable
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): OS X

**Comment by alansouzati** [comment]
Fixed
