### ISSUE TITLE
IE does not support fetch API. 

### ISSUE THREAD

**Issue by huangshif** [grommet/grommet#754]
It is recommend to use `fetch` API in document of `Rest` module, and `get`... in `Rest` are marked as deprecated methods, but `fetch` API is not supported by IE.

does grommet add a polyfill for this API? or I need to do it by myself?

**Comment by alansouzati** [comment]
You need to add a polyfill yourself. We are using https://www.npmjs.com/package/whatwg-fetch.

The blog currently uses it:

https://github.com/grommet/grommet-blog/search?utf8=✓&q=whatwg-fetch&type=Code
