### ISSUE TITLE
Support flex-shrink property with Box component

### ISSUE THREAD

**Issue by nickjvm** [grommet/grommet#759]
### Expected Behavior
Either `Box` component should support a `shrink` prop type, or `Box`es that have `full="horizontal|vertical"` and `justify="center"` should have a `flex-shrink: 0` CSS property defined.

### Actual Behavior
When using the `Box` component, sometimes the container will shrink to fit the window, rather than fitting the content. View codepen below with preview pane height about 600px. Notice that the Layer heading is cut off and cannot be scrolled to

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/nickjvm/pen/WxYqRV?editors=0110

### Environment
Windows 7, Chrome

**Comment by alansouzati** [comment]
Good find. it seems to me it is only a problem with justify center. So I believe

```
.grommetux-box--justify-center {
  flex-shrink: 0;
}
```

is sufficient.

Would you be willing to send a pr to fix that?

**Comment by nickjvm** [comment]
@alansouzati can do!
