### ISSUE TITLE
Chart component breaks and asks for a required prop `series`

### ISSUE THREAD

**Issue by athmangude** [grommet/grommet#762]
### Expected Behavior

The `Chart` component is expected to render a chart

### Actual Behavior

The `Chart` component breaks with
`warning.js:44Warning: Failed prop type: Required prop `series` was not specified in 'Chart'.`

### URL, screen shot, or Codepen exhibiting the issue
[Here is a Codepen](http://codepen.io/athmangude/pen/WxLGjR?editors=1011)

### Your Environment

* Grommet version: 0.6.10
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Mac OSX Yosemite

**Comment by karatechops** [comment]
The codepen doesn't appear to be working however just invoking <Chart> in the codepen is most likely calling the old Chart component. You may be importing the old charts in your project component . Your import should look like the following:
`import Chart from 'grommet/components/chart/Chart';`

If I understand the new Charts components correctly it does not require the series prop any longer but will require a values prop which contains an array. If you are using some of the Meter components I believe they still use the series syntax.

**Comment by athmangude** [comment]
@karatechops Is v`0.6.10` the latest?. Cuz it looks like the package on NPM is not updated.

*The `components/chart/` folder is missing*
<img width="829" alt="screen shot 2016-08-11 at 2 12 37 pm" src="https://cloud.githubusercontent.com/assets/2655082/17586970/c8a0e474-5fcd-11e6-8201-85795893b129.png">

**Comment by karatechops** [comment]
Try uninstalling your current grommet install and using this dependency in your package.json. I've had issues with just pulling directly from npm as well. 
`"grommet": "https://github.com/grommet/grommet/tarball/stable",`

**Comment by alansouzati** [comment]
Correct the new charts is only available inside the grommet stable for now.

I will soon release Grommet 0.6.11 with the new components.

Checkout this wiki page if you are interested in learning more about stable: https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F.

We are working on a fix to the site to tell which component and properties are available in the latest release.

**Comment by athmangude** [comment]
Thanks guys I got it working with the tarball
