### ISSUE TITLE
Forward arguments in the constructor

### ISSUE THREAD

**Issue by voodooattack** [grommet/grommet#766]
Grommet does not work with react-apollo's server-side rendering because of apollostack/react-apollo#132

### Expected Behavior
Grommet should forward props and context to React.Component in the constructor.
```js
  constructor(props, context) {
    super(props, context);
    this._onResize = this._onResize.bind(this);
  }
```

### Actual Behavior
No arguments are forwarded.
```js
  constructor() {
    super();
    this._onResize = this._onResize.bind(this);
  }
```

### Your Environment
* Grommet version: 0.6.10

**Comment by alansouzati** [comment]
Interesting, thanks for reporting this.

Does this mean that all ES6 Components, even if no constructor is defined, one should be added with at least this:

```javascript
  constructor(props, context) {
    super(props, context);
  }
```

or if you don't declare it is fine?

**Comment by voodooattack** [comment]
@alansouzati You're welcome. 

Components with no constructor are fine from what I've seen.

**Comment by luisrudge** [comment]
Components with no constructor don't need to forward params

**Comment by alansouzati** [comment]
Fixed folks. https://github.com/grommet/grommet/commit/0133a6c0846baec4581320def59acc88135c8225

Thanks for reporting.

**Comment by alansouzati** [comment]
It should be soon available in Grommet stable branch. If you want to use it check this wiki page:

https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F

**Comment by voodooattack** [comment]
Excellent, thank you for the swift solution!
