### ISSUE TITLE
Status icon component doesn't detect background color and doesn't allow inverting colors

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet#767]
### Expected Behavior

When attempting to use the Status component inside a colored box similar to the Notification component, there's no way to invert the color of the icon so it is visible against a background of the same color as the icon.
### Actual Behavior

When including a status icon within a critical color box, the icon color should be inverted, similar to how the Notification component turns the icon white when used over a status-colored banner.
### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/grommet/pen/bZOWKK?editors=0010
### Steps to Reproduce
1.  Create Box with `colorIndex=critical`
2.  Inside the box, place a critical Status icon

**Comment by bryanjacquot** [comment]
Closing until we find a need for this.

**Comment by nikooiko** [comment]
Well i kinda face this problem now. Is there any workaround to solve this?

**Comment by tracybarmore** [comment]
The above codepen is no longer working. Can you give us a codepen or screenshot to look at? Thanks!

**Comment by nikooiko** [comment]
```
<Box
  align='center' direction='column' pad='small'
  colorIndex='ok' flex={true}
>
  <Value
    icon={<Status value='ok' size={iconSize} />}
    label='Offline' value={100} size={valueSize}
  />
</Box>
```
[icon-background-color](https://cloud.githubusercontent.com/assets/9281494/21865517/15da9434-d84f-11e6-9368-6df47a1e8758.png)

I'm sorry, right now can't create a codepen. I'll post one later if i find the time for it.

**Comment by tracybarmore** [comment]
linking with grommet/grommet-design#31

**Comment by Kiho** [comment]
Is there way to disable this behavior or change threshold?
I like to show colored status icon on grey background but I can't find out a way to do it.
