### ISSUE TITLE
Form component should compatible with inline/horizontal FormFields.

### ISSUE THREAD

**Issue by jainvabhi** [grommet/grommet#768]
FormField are generating as a block level, its should be have an option to display inline/horizontal FormField: 
![horizontal_form_fields](https://cloud.githubusercontent.com/assets/2681175/17595476/d3208ce6-600a-11e6-9526-d84bfacb6778.png)

### Expected Behavior
Should have the option to generate the Form with 100% width and display FormFields inline with custom width option. 

### Actual Behavior
Grommet Form component don't have any option to display FormFields vertically/horizontally, its just display all the FormField blocks with 100% width.

**Comment by alansouzati** [comment]
Im not sure this is a Grommet pattern we want to support. @bryanjacquot any inputs here?

**Comment by bryanjacquot** [comment]
The grommet form patterns are designed as they are for a reason.  They have a clean way of displaying help tips, as well as validation messages.  They are also based on research showing in-field labels are very efficient for users to scan and use.  There are several issues the the proposed designs:

- Once a value is selected, or if a default value is provided, there's no way to know what the field is. (e.g. the Select Order Type field).

- If there's a validation error in the From "Ship date range" field, where does the validation message appear?   

- With side-by-side fields, what is the responsive behavior on a phone in portrait landscape?

Thanks for the suggestion, but these suggestions have flaws that the existing Grommet forms were specifically designed to overcome.
