### ISSUE TITLE
SVG and Image component should have the option for custom size height/width

### ISSUE THREAD

**Issue by jainvabhi** [grommet/grommet#769]
### Expected Behavior
To get the brand logo or any other svg icon or image presentation on the web it should have the option for custom sizes.

### Actual Behavior
SVG component generated with Square sizes using existing size attribute "small|medium|large|xlarge|huge". 

Image component also have fixed size options with "small|medium|large|thumb".

**Comment by bryanjacquot** [comment]
The [SVGImage](http://grommet.github.io/docs/icon) component provides the ability to specify the [viewBox](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) attribute to size arbitrary SVG icons.

The build-in Grommet icons are sized based on standard size increments that align with line height, fonts, and padding as discussed here: http://grommet.github.io/docs/padding.  If you have a need for a custom size icon, please provide more information as to what you're trying to achieve.

**Comment by jainvabhi** [comment]
@bryanjacquot How should i include the logo svg if I have the logo with custom sizes like 65x50 or 150x50 etc... in grommet we don't have any option even with using Image or SVG both. 

![dotajain](https://cloud.githubusercontent.com/assets/2681175/17641512/eba52722-6140-11e6-8c00-caa924d9db43.png)

In that case I have to create a custom css for the logo to overwrite the existing grommet css.
