### ISSUE TITLE
Checkbox is not centered

### ISSUE THREAD

**Issue by luisrudge** [grommet/grommet#770]
### Expected Behavior
Checkmark inside the checkbox is not centered

### Actual Behavior
Checkmark inside the checkbox should be centered

### URL, screen shot, or Codepen exhibiting the issue
http://grommet.github.io/docs/check-box
![image](https://cloud.githubusercontent.com/assets/941075/17598353/7a658208-5fd0-11e6-8dc0-31cc101b4d82.png)

### Your Environment

* Grommet version: docs
* Browser Name and version: chrome and Edge

**Comment by alansouzati** [comment]
Thanks for reporting.

Fixed in https://github.com/grommet/grommet/commit/861f32be721ba9b0e2df8485e0c4ace68b8eb4bc

**Comment by luisrudge** [comment]
Cool! Thanks! <3

**Comment by alansouzati** [comment]
de nada 😆

**Comment by luisrudge** [comment]
oh! a fellow Brazilian!

**Comment by alansouzati** [comment]
Sim! Glad to see the 🇧🇷community using Grommet more and more 👍
