### ISSUE TITLE
Tip component is getting cropped

### ISSUE THREAD

**Issue by alansouzati** [grommet/grommet#774]
In the first load of the tip component it is rendering cropped. If you resize the browser the issue goes away

### Expected Behavior
Tip should not crop

### Actual Behavior
Tip is cropping in the first load

### URL, screen shot, or Codepen exhibiting the issue

![screen shot 2016-08-12 at 10 30 20 am](https://cloud.githubusercontent.com/assets/1207250/17631173/cfd206ce-6077-11e6-903f-a12c237ed7a0.png)

### Your Environment
* Grommet version: Stable
* Browser Name and version: Any
* Operating System and version (desktop or mobile): Any

**Comment by bryanjacquot** [comment]
When the Tip is opened on a phone or small browser window (and the window is hard reloaded) the tip starts above the component and when the user scrolls down the page, the tip drops below the component but the carrot doesn't move accordingly.
