### ISSUE TITLE
Investigate automated test frameworks and develop testing strategy

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet#776]

**Comment by bryanjacquot** [comment]
Results from initial discussion
* We'll use Jest for simple components and components without intricate interaction.
 * Still evaluating Jest for component lifecycle methods
 * Will give us visibility to the DOM
 * Will allow for rapid test creation and updating
* We'll use Enzyme for more complex components that require mounting and have interesting interactions.
 * This will enable us to interact with the DOM.
 * This will allow us to assert on expect component behavior and handling of state.
* Still evaluating strategies for end-to-end testing using something Selenium or even manual tests.

**Comment by RyanCCollins** [comment]
As noted, I would like to contribute to writing some unit tests.  I will stay tuned for an announcement regarding the new setup.  Thanks!

**Comment by bryanjacquot** [comment]
@RyanCCollins thanks for your offer to help write tests.  Here's the promised announcement about the test framework.  The code has been promoted to the stable branch.

https://blog.grommet.io/post/2016/09/01/how-we-landed-on-jest-snapshot-testing-for-javascript

There are some tests already written, but lots of room for contributions:
https://github.com/grommet/grommet/tree/master/__tests__/components

**Comment by alansouzati** [comment]
@RyanCCollins if you can create one issue per test that you are writing that would be great. This way we would avoid writing the same test together!
