### ISSUE TITLE
Meter component's alignment is off by few pixels.

### ISSUE THREAD

**Issue by chandrakantnitt** [grommet/grommet#780]
Meter component's alignment is off by few pixels.

### Expected Behavior

Meter component should start without any padding.

### Actual Behavior

The meter component's alignment is off by few pixels

### URL, screen shot, or Codepen exhibiting the issue
http://grommet.github.io/docs/chart-examples#13
For above link one can notice that the meter component's alignment is off by few pixels for the record year 2013. Here is the screenshot for same.
<img width="363" alt="meter issue" src="https://cloud.githubusercontent.com/assets/4144400/17706546/16227494-63fa-11e6-9ea9-67f16aac83b9.png">

### Steps to Reproduce
 1. Open http://grommet.github.io/docs/chart-examples#13
 2. Check the meter component in the chart for year 2013
 3. A gap appears for the meter component

### Your Environment

* Grommet version: latest which is used on the grommet.github.io for http://grommet.github.io/docs/chart-examples#13
* Browser Name and version: chrome 52.0.2743.116 m
* Operating System and version (desktop or mobile): Windows 8.1 desktop

**Comment by chandrakantnitt** [comment]
@alansouzati - is the issue I raised and this one same https://github.com/grommet/grommet/issues/789 ? It looks same to me.

**Comment by alansouzati** [comment]
Fixed
