### ISSUE TITLE
Improve active form field feedback

### ISSUE THREAD

**Issue by gustahrodrigues** [grommet/grommet#788]
We are using Grommet in a project at HPE. We've received a feedback from a final user that the input text are simple boxes with a very thin border. The active field is being highlighted, but it is very subtle. It needs to be more obvious to the user what the active field is. Perhaps changing the form field background also would help.
### Expected Behavior

We need to improve the user feedback for the active form field
### Actual Behavior

We are just changing the border color from a very thin border.

**Comment by bryanjacquot** [comment]
We will address this suggestion with the following two adjustments
. Slightly increase stroke for form field with focus
. Align the general focus indicator to align with the new form focus indicator

The result will be aligned focus indication within and outside forms that is slightly stronger than the current form, and slightly more subtle than the general focus indicator.

**Comment by gustahrodrigues** [comment]
Guys, 

Do you have a deadline for that improvement? Or Can you have me a guide for it be implemented locally?

My users and I are looking forward to it.

Thanks!

**Comment by L0ZZI** [comment]
We have an approved design in place, but not implemented yet? We. don't have it aligned with a release just yet. Our soonest window for delivering the change is 1.1.0 scheduled for December 1st.
