### ISSUE TITLE
Gap in the circle Meter component

### ISSUE THREAD

**Issue by coltonw** [grommet/grommet#789]
### Expected Behavior
The circle should be perfectly filled all the way around

### Actual Behavior
There is a small gap between the third and fourth segment of the circle

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/coltonw/pen/pbBgPJ?editors=1010#0

### Your Environment
* Grommet version: master circo August 18, 2016
* Browser Name and version: Chrome 52.0.2743.116 (64-bit)
* Operating System and version (desktop or mobile): OS X El Capitan

**Comment by alansouzati** [comment]
I've updated the codepen since the Grommet core now requires react-with-addons.

http://codepen.io/alansouzati/pen/vXOxvB?editors=1010#0

Problem is still happening
