### ISSUE TITLE
layer scrolling UX

### ISSUE THREAD

**Issue by acornejo** [grommet/grommet#792]
Using layers on mobiles results in a non usable experience, since the layer doesn't hide the content behind it, instead both are visible side-by-side and require scrolling.

### Expected Behavior
The topmost layer should be the only one visible, if the layers underneeth are visible they should be partially hidden by a backdrop that prevents scrolling.

Here is a video of the problem, taken while using the ferret grommet app on mobile.

https://www.youtube.com/watch?v=Qw7BF-WR8_k

This issue is similar to the one described in #699 where I posted a different video. I decided to post this as a different bug, since I am not sure that fixing one of them will fix the other (for instance, the scroll to top suggestion will clearly not solve the issue described here).

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/1c348ff8f1946d98a9e4046b42677357845bf277
