### ISSUE TITLE
search bar UX on mobile

### ISSUE THREAD

**Issue by acornejo** [grommet/grommet#794]
The search bar on mobile is very difficult to use.

### Expected Behavior
When clicking on the search icon I would expect the input to appear in place and be focused and ready for text entry.

### Actual Behavior
Instead, half an input box is shown, which doesn't have keyboard focus. When manually giving focus to this input box the full input box appears in a different location.

### URL, screen shot, or Codepen exhibiting the issue
Video taken from the ferret app:

https://www.youtube.com/watch?v=tj5L2L9zFe4

**Comment by alansouzati** [comment]
I cannot reproduce it using the latest grommet, see this codepen:

http://codepen.io/alansouzati/pen/NAVoEA?editors=0010#0

**Comment by alansouzati** [comment]
Feel free to reopen this issue if you can reproduce it using the latest grommet
