### ISSUE TITLE
Infinite scroll issue : onMore event keeps triggering for the Tiles (on the Layer component) unless enough data is loaded to fit the screen

### ISSUE THREAD

**Issue by chandrakantnitt** [grommet/grommet#799]
onMore event keeps triggering for the Tiles component  (placed on the Layer component) unless enough data is loaded to fit the screen.
Let's say we have a total of 100 records. the screen can fit 50 records. And we would like to get the 10 records per chunk onMore event. So in this case there are two issues : 

1. The onMore is triggered 5 times with the the page load (without doing any mouse wheel operation). 
2. Then if user tried to perform a scroll operation the onMore event is not triggered at all. 

### Expected Behavior

onMore should be triggered on scroll (using mouse wheel or the scroll control). 

### Actual Behavior

onMore event keeps triggering for the Tiles component  (placed on the Layer component) unless the enough data is loaded to fit the screen.
There are total of 100 records to be displayed on the screen (consider at a time 50 records can be fit on the screen). And 10 records per chunk has to be loaded onMore event. When the page is loaded then onMore is triggered 5 times automatically (without doing any mouse wheel operation). After that if user tried to perform a scroll operation the onMore event is not triggered at all. 

### URL, screen shot, or Codepen exhibiting the issue
Here is the codepen for the onMore issue
http://codepen.io/chandrakantnitt/pen/rLbWLz?editors=0010

### Steps to Reproduce
 1. Open he codepen link
 2. One can see the issue there in the view section

### Your Environment

* Grommet version: Latest
* Browser Name and version: Chrome 52+
* Operating System and version (desktop or mobile): Win 8.1

**Comment by chandrakantnitt** [comment]
@alansouzati

**Comment by alansouzati** [comment]
Thanks for reporting this @chandrakantnitt, we will soon work on a fix for this

**Comment by epilande** [comment]
Updated CodePen with react-with-addons http://codepen.io/epilande/pen/gwrGGy?editors=0110
