### ISSUE TITLE
Consistent component structure

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet#801]
- [ ] Use of classNames instead of array.join()
- [ ] Assign local constants at the top of functions instead of this.props
- [ ] Use const when possible instead of let
- [ ] Make sure propTypes are alphabetized
- [ ] Put this.props.className last in className
- [ ] Use `undefined` instead of `null`

**Comment by karatechops** [comment]
In reference to PR #921, should we add use `undefined` instead of `null`?

**Comment by ericsoderberghp** [comment]
Added.

**Comment by ericsoderberghp** [comment]
Still needed:

- [ ] Layer

**Comment by ericsoderberghp** [comment]
Most of this has been done now. Any remaining items will be handled on a case by case basis.
