### ISSUE TITLE
Icon cursor

### ISSUE THREAD

**Issue by tomtosi** [grommet/grommet#803]
### Expected Behavior
When hovering over the icon the cursor should NOT change to a pointer (hand) if icon has no action assigned to it.

### Actual Behavior
When hovering over an icon that is NOT assigned any action, the cursor changes to a pointer (hand).

### Steps to Reproduce
 1. Navigate to: http://grommet.github.io/hpe/docs/icon 
 2. Hover over icons on the page
 3. 

### Your Environment

* Grommet version:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by bryanjacquot** [comment]
Fixed by https://github.com/grommet/grommet/pull/826
