### ISSUE TITLE
Legend of old chart is displayed different

### ISSUE THREAD

**Issue by ShimiSun** [grommet/grommet#804]
Filing this issue after discussing with Alan.
I wasn't sure if it's a defect, but even if the legend should now be displayed on the right side instead of the bottom of the chart, the alignment doesn't look good.

### Expected Behavior

Legend of old Chart (Chart V1) should be presented on the bottom of the chart

### Actual Behavior
After updating to new Grommet release, the chart's legend is being rendered on the right hand side of the chart instead of the bottom of the chart.
even if it should be on the right side it needs to be aligned better. (see screenshot)

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/6320236/17950205/f64e00a2-6a16-11e6-8d50-5f8ef62604d0.png)

### Steps to Reproduce
 1. create an old chart with legend and observe
 2. 
 3. 

### Your Environment

* Grommet version: 0.6.11
* Browser Name and version: Chrome 
* Operating System and version (desktop or mobile):WIN desktop

**Comment by ericsoderberghp** [comment]
We will be closing this issue when we release 1.0.0 as the .v1 chart interface will be removed then.
