### ISSUE TITLE
onMore callback on grommet table is not getting triggered on using browser scroll bar

### ISSUE THREAD

**Issue by vaibhavbhargav** [grommet/grommet#806]
grommet table onMore callback attribute is not triggered if we did not put into split tag.

### Expected Behavior
onMore callback should be triggered when we scroll down using browser scroll bar.

### Actual Behavior
onMore callback is not getting triggered if we use grommet table without split tag.
if we use split tag then at scrolling onMore callback is getting triggered

### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/anon/pen/QEXjkm

### Steps to Reproduce
 1. scroll down using scroll bar browser is not alerting 'hi'
 2. if we add split tag before table then while scrolling it alerts 'hi'

**Comment by bryanjacquot** [comment]
This appears to be related to #799

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/03c5c2911256143f41f78ccf365241b27c4b2b3c
