### ISSUE TITLE
Have not good display when use float number to create meter

### ISSUE THREAD

**Issue by RodHPE** [grommet/grommet#807]
when the meter  series value which type is float  that have not good display with multi-decimal.

### Expected Behavior
we expect that we can define the decimal counts or to calculate the 'total' by developer self.

### Actual Behavior
the 'total' has too many decimal counts.

![image](https://cloud.githubusercontent.com/assets/20080920/17996329/a0112e14-6b9a-11e6-9ed0-7284b04ff25e.png)

### Steps to Reproduce
  use this data to reproduce.
 <Meter stacked={true}  series={[
       {"label": "Gen 7", "value": 40.59, "colorIndex": "graph-1"},
  {"label": "Gen 8", "value": 50.99, "colorIndex": "graph-2"}]} max={{value: 100, label: 'hello'}}/>

**Comment by RodHPE** [comment]
by the way, can you give me a hand? I know where the issue is, but need you to fix it. Thanks.

**Comment by christinHP** [comment]
Javascript use IEEE754 to calculate float and int number. Sometimes it’s hard to use binary to express a float number very exactly. 

For example, input below expression in browser console:
0.1+(0.2+0.3);  // 0.6
(0.1+0.2)+0.3;  // 0.6000000000000001

4.54+5.03;  // 9.57
4.47 + 5.09;  // 9.559999999999999

My solution to fix make the Meter support float number.

Change grommet/src/js/components/Meter.js
From:
value: function _seriesTotal(series) {
  var total = 0;
  series.some(function (item) {
    total += item.value;
  });
  return total;
}

To:
value: function _seriesTotal(series) {
  var values = [];
  series.forEach(function(item) {
    var r1;
    try{
      r1 = item.value.toString().split(".")[1].length
    } catch(e) {
      r1=0
    }
    values.push(r1);
  });

  var m = Math.pow(10, Math.max.apply(null, values));
  var sum = 0;

  series.forEach(function(item) {
    sum += item.value * m;
  });
  return sum = sum / m;
}

**Comment by bryanjacquot** [comment]
@christinHP a Pull Request with this suggestion would be appreciated.

**Comment by bryanjacquot** [comment]
If you'd like to submit a pull request, this video is a good overview for contributing to Grommet.  https://vimeo.com/129681048

**Comment by alansouzati** [comment]
indeed this sounds like a great contribution

**Comment by bryanjacquot** [comment]
Fixed in https://github.com/grommet/grommet/pull/815
