### ISSUE TITLE
Please add WebJars 

### ISSUE THREAD

**Issue by rboorgapally** [grommet/grommet#808]
### Expected Behavior
I am trying to use grommet in play framework 2.5 and expect to find webjar on the official webjars site

### Actual Behavior
I can't find webjar for grommet. So I have to work around by installing npm and resorting to messy path configurations in play framework

**Comment by bryanjacquot** [comment]
@rboorgapally thanks for the suggestion.  We'd welcome a PR for this, or it may be a packaging exercise for the NPM webjars.

**Comment by alansouzati** [comment]
I also see this a separate project like `grommet-webjars`. If you are willing to create it we would be happy to spread the word about it, but we don't have expertise/resources to add support for Play Framework.
