### ISSUE TITLE
Notification component paced in the footer with float={true} attribute causes Close button to disappear

### ISSUE THREAD

**Issue by chandrakantnitt** [grommet/grommet#811]
When notification component paced in the footer with float={true} causes the close button to disappear from the screen viewport (looks like it is out of the screen viewport). 
### Expected Behavior

Notification component placed in Footer component (with float={true}) should have Close button visible and functional if closer={true} and onClose={...} provided.
### Actual Behavior

Close button disappeard from the screen viewport even though closer={true} and onClose={...} provided for notification component.
### URL, screen shot, or Codepen exhibiting the issue
Here is the code pen for same.
http://codepen.io/chandrakantnitt/pen/XKvkYr

### Steps to Reproduce
 1. Go to http://codepen.io/chandrakantnitt/pen/XKvkYr
 2. Let the page to be loaded
 3. Notification appears on the page load - however the close button is absent

### Your Environment

* Grommet version: Latest
* Browser Name and version: Chome 52
* Operating System and version (desktop or mobile): Win 8.1 / Win 7

**Comment by chandrakantnitt** [comment]
@alansouzati

**Comment by alansouzati** [comment]
Thanks for reporting this.

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/8b0ff95a87685de8dd0c9af2487566ad682db81e
