### ISSUE TITLE
Legend value font size is not correct in case of single legend

### ISSUE THREAD

**Issue by vaibhavbhargav** [grommet/grommet#813]
we are using legend tag having single value and observed that in case of single legend element font size of legend value is large.

### Expected Behavior
legend tag should render the legend value's font size for single legend  same as in case of multiple legends.

### Actual Behavior
When Legend tag is used with single legend then it renders the value in large font.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/anon/pen/yaBOGZ

### Steps to Reproduce
 1. While using the Legend tag, pass series array of length 1 in series attribute.
let eventSeriesIssue = [ {'label': 'Critical', 'value':'1000', 'colorIndex':'critical'}];
<Legend  series={eventSeriesIssue} />

**Comment by HeidiTosi** [comment]
I am seeing the same issue. I added an extra legend line item to the code which fixed the font size without displaying the extra legend line in the display. 
![legend-2itemscoded](https://cloud.githubusercontent.com/assets/17186165/18318963/b8404b7c-74f1-11e6-8a73-1c70ba8bc1dc.png)

Without the second legend line, the count font is larger.
![legend-itemcoded](https://cloud.githubusercontent.com/assets/17186165/18318971/c31a3af8-74f1-11e6-8940-419e6fb0e682.png)

Example code when it appears correct:
  render: function () {
    return (
      <Tiles fill={true}>
        <Tile align="start">
<Legend series={[
  {
    "event": "Critical",  
    "label": "Critical",
    "value": 0,
    "colorIndex": "error",
    "onClick": "..."
  },
                {
    "event": "Critical",    
    "label": "Critical",
    "value": 0,
    "colorIndex": "error",
    "onClick": "..."
  },
]} />
        </Tile>
      </Tiles>

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/ea15e139bfbbc7aa2bf609f9fd71d48f59cf92f2
