### ISSUE TITLE
Main menu usability?

### ISSUE THREAD

**Issue by mattfarina** [grommet/grommet#82]
When the main menu comes in from the side it's triggered by clicking on the logo. This is different from using something like a hamburger icon to trigger the main menu. My question, is using the logo as a method to trigger the menu finable for most users?

_Note, I understand the ideal is to have the menu not be collapsed like this. [Luke Wroblewski wrote about just this earlier this year](http://www.lukew.com/ff/entry.asp?1945)._

Hamburger menus aren't intuitive to most users. This caused AWS to put the word Menu next to theirs and when you visit the site the first time there is even a pop-up noting what's in the Menu.
![fullscreen_7_10_15__10_13_am](https://cloud.githubusercontent.com/assets/62991/8620261/6b8ce1cc-26ec-11e5-9cac-54ed3b909bc2.png)

Given that the hamburger menu isn't obvious, how is the logo obvious when it's historical trigger is the home page/screen?

Can we get validation of the current pattern or change the pattern?

**Comment by bryanjacquot** [comment]
We've conducted a round of usability testing on this issue, and users were able to utilize the main menu without an issue.  We'll continue to watch this, but for now we believe the approach is acceptable.
