### ISSUE TITLE
Typescript bindings

### ISSUE THREAD

**Issue by Vaevictus** [grommet/grommet#820]
Hi,

I'm interested in this library and wondering if typescript bindings are planned for the future? nothing on the definitelytyped repo thus far.

Cheers

**Comment by alansouzati** [comment]
Thanks for your question. We don't have near term plans for adding binding to Typescript. We see this as a great project in github. If you are willing to create it we would definitely spread the word about it. Maybe `grommet-typescript`?

We currently don't use typescript internally and we don't have the expertise to create and maintain such a project.

**Comment by RyanCCollins** [comment]
@Vaevictus 

Sorry to unearth a dead thread, but wanted to mention that I made [TS bindings](https://github.com/RyanCCollins/grommet-typescript) for the latest v. of Grommet recently.  I am working on writing the tests and would like to test them out a bit more myself before I publish to DefinitelyTyped. 

Cheers!

**Comment by edude03** [comment]
Off topic, but @RyanCCollins I'd like to help test / improve the typings as I'm using TS + grommet in a project right now but I can't seem to figure out the right stanza to import them. 

I thought it would be `import App from 'grommet-typescript'` or something similar but I haven't gotten it to work. Any advice?

**Comment by RyanCCollins** [comment]
Hey @edude03! 

I will make an example project using the ts bindings with grommet.  Give me a few hours.

**Comment by RyanCCollins** [comment]
@edude03, I updated the exports for the grommet-typescript definitions and added them to my [React / TypeScript boilerplate project](https://github.com/RyanCCollins/scalable-react-ts-boilerplate/tree/grommet) on a separate branch.

Let me paste in some code and a giphy to demonstrate the usage.

Since the grommet types are not on DefinitelyTyped yet, I included them in a folder in my project and set the directory under then `include` configuration option in my tsconfig.json file

```
{
  "compilerOptions": {
    "baseUrl": "src",
    "module": "es6",
    "target": "es6",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": false,
    "sourceMap": true,
    "outDir": "build/src",
    "jsx": "preserve",
    "allowJs": true
  },
  "include": [
    "src/**/*",
    "config/types/*.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

Then, I can import the grommet modules into my App/index.tsx container.
```
import GrommetApp from 'grommet/components/App';
```

And here is the result (typed grommet components, 🎉 ):
![gif](http://g.recordit.co/pCLxFspwe2.gif)

**Comment by arlair** [comment]
@RyanCCollins Nice work. I tried this out, but my config compiles to ES5 at the moment, which then gets imported by Babel in a Webpack build in another project.

To generate code that runs correctly I seem to need to use:

    import * as Header from 'grommet/components/Header';

which generates ES5:

    var Header = require("grommet/components/Header");

However, with this I get compile errors based on the types.

I tried compiling the source from your project:

    import GrommetApp from 'grommet/components/App';

generates ES6:

    import GrommetApp from 'grommet/components/App';

but for my ES5 version using Header it generates:

    var Header_1 = require("grommet/components/Header");
    ...
    React.createElement(Header_1.default

where `default` does not exist and errors at runtime.

I'm not quite sure what the correct solution is as TypeScript imports have confused me many times. Imports seem a bit contentious in regards to what Babel vs TypeScript does and what is correct in the JavaScript specification as can be seen in this answer and the linked answer here: http://stackoverflow.com/questions/35706164/typescript-import-as-vs-import-require

**Comment by edude03** [comment]
@arlair I think the solution is to enable "AllowSyntheticDefaultImports" then use the `import Header from ....` format. That's what I did anyway

**Comment by edude03** [comment]
@RyanCCollins Thanks!!! I got it working with a little finagling, however, I'm having an issue with `react-redux`

I want to render a select right, and so I use MapStateToProps with connect, like so

```

import Select from 'grommet/components/select';

const MapStateToProps = ({ schedule }): => {
    let options = values(SCHEDULE)
            .filter(isNumber)
            .map(v => (  {value: v, label: SCHEDULE[v] } ))
    
    return {
        value: {value: schedule, label: SCHEDULE[schedule] },
        options: options
    }
}

const MapDispatchToActions = (dispatch) => {
    return {
        onChange: (input)=> dispatch(setPaymentSchedule(input.value.value))
    }
}


export default connect(MapStateToProps, MapDispatchToActions)(Select)
``` 

which makes TS upset because Select takes GrommetCustomTypes.SelectProps not just <any> old props ;P

So to get it to work I had to change 

```
interface SelectProps extends React.Props<Select> 
```

to 
```
export interface SelectProps extends React.Props<Select>
```

and change 
```
const MapStateToProps = ({ payment_schedule }) =>
``

to
```
import { SelectProps } from 'grommet'
const MapStateToProps = ({ payment_schedule }): SelectProps => 
```

It's not too bad of a fix, but I'm wondering if I/we should export all the interfaces or if there is a better way. Thoughts?

**Comment by RyanCCollins** [comment]
Hey all! 

I appreciate your comments and help to improve these. I'd love for your imtpovements to be submit with a PR to My repo. Eventually I will submit it to the definitely typed repo once all the kinks are ironed out and your assistance in getting it there is very much appreciated.

**Comment by RyanCCollins** [comment]
@edude03 have you made any progress with the fixes for the bindings by any chance?  I may revisit them soon and would like to get them into the DefinitelyTyped repo.

**Comment by dgennetten** [comment]
...and it would be great if one of you guys would do a write-up on using TypeScript with Grommet...

**Comment by RyanCCollins** [comment]
Hey l

**Comment by ProTip** [comment]
Does anyone have advice for getting the css to load? I keep getting the following:

```
ERROR in ./src/index.tsx
Module not found: Error: Can't resolve 'grommet/scss/vanilla/index' in '[path]/src'
```

**Comment by lorem--ipsum** [comment]
Hey @RyanCCollins I can't find the typings anywhere, it looks like the repo is no longer accessible. Any chance you could publish those types again ? Thanks !

**Comment by Kitanotori** [comment]
@RyanCCollins Can't get the typings working. Webpack keeps throwing similar error for each imported component: `TS2604: JSX element type 'Button' does not have any construct or call signatures.`

Temporary "solution" I could come up with was to change the definition from

```ts
declare module "grommet/components/Button" {
  export default Grommet.Button;
}
```
to

```ts
declare module "grommet/components/Button" {
  const x: any;
  export = x;
  // export default Grommet.Button;
}
```
, effectively making the definitions useless.
