### ISSUE TITLE
Meter have blank piece circle  when the series array have a zero value

### ISSUE THREAD

**Issue by RodHPE** [grommet/grommet#821]
As title,  one of  series array have a value is 0,  which have a blank piece circle.

### Expected Behavior
has no blank circle

### Actual Behavior
Meter have a piece blank

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/20080920/18263272/4bf2faac-743b-11e6-8784-6bd1cb9697f5.png)

<Meter type='circle' size='small' stacked={true}  legend={true} series={[
       {label: 'Allocated (TiB) ', colorIndex: 'accent-2', 'value': 0},
	   {label: 'Free (TiB) ', colorIndex: 'accent-1', value: 3}
       ]} max={3}/>

**Comment by RodHPE** [comment]
![image](https://cloud.githubusercontent.com/assets/20080920/18263303/9c981726-743b-11e6-9727-1408122138f0.png)

**Comment by alansouzati** [comment]
Thanks for reporting this. Closing as a duplicated of https://github.com/grommet/grommet/issues/789
