### ISSUE TITLE
The Anchor's primary option is wrong, the text color will be black or green, by random.

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#822]
We use "primary" option, but the text color sometimes is black, sometimes is green, by random. This behavior is wrong, the issue can be appeared in Win7, Win10, Ubuntu.

<Anchor primary={true} href={`https://${applianceIP}/#/xxx`} target="_blank">'Open in OneView'</Anchor>

Black:
![image](https://cloud.githubusercontent.com/assets/16797825/18270123/f0299f0a-745d-11e6-875e-af997d32d4da.png)

Green:
![image](https://cloud.githubusercontent.com/assets/16797825/18270131/fe4d7d90-745d-11e6-9e18-1e24c68b9086.png)

**Comment by bryanjacquot** [comment]
@christinHP thanks for reporting.  This is a dup of https://github.com/grommet/grommet-docs/issues/77.  It's not random behavior, it's based on whether the link has been visited, which is incorrect.
