### ISSUE TITLE
Totals and labels appearing wider than bar and circle meters

### ISSUE THREAD

**Issue by HeidiTosi** [grommet/grommet#829]
The totals, counts, and labels on the meters appear to be expanding wider than the widgets themselves. This may be the result of another fix that may have been implemented as early as yesterday.
Example of issue:
![currentbarmeter](https://cloud.githubusercontent.com/assets/17186165/18319588/502d66ac-74f4-11e6-8607-7779bc615dbc.png)

Expected display:
![expectedbarmeter](https://cloud.githubusercontent.com/assets/17186165/18319593/56bee8e2-74f4-11e6-9b60-15fb4acd7c34.png)

### Your Environment

* Grommet version: Current
* Browser Name and version: Chrome

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/b7c45bfd89b6dc96611db065797268bba5ce783a
