### ISSUE TITLE
Table.js get error  _onResize when  scrollable is false

### ISSUE THREAD

**Issue by simpleofac** [grommet/grommet#83]
when scrollable is false, mirror is null, 

var mirrorElement = this.refs.mirror.getDOMNode(); has below error. 
Uncaught TypeError: Cannot read property 'getDOMNode' of undefinedTable.js:73 _alignMirrorTable.js:57 _onResize

**Comment by bryanjacquot** [comment]
This has been addressed in the recent versions of Grommet.
