### ISSUE TITLE
App is not working at all in IE 11

### ISSUE THREAD

**Issue by mars76** [grommet/grommet#838]
Hi All,

  I have developed an app using Grommet and it is working fine in Firefox and Chrome. In IE11 it is showing a blank page.

  Here is what we are seeing in the IE Developer tools console

  DOM7011: the code on this page disabled back and forward caching. For more information, see http://go.microsoft.com/fwlink/?LinkID=291337
  File: inprivate_win7.htm

### Your Environment

* Grommet version:0.6.11
* Browser Name and version: IE 11
* Operating System and version (desktop or mobile): Desktop Windows 7

**Comment by mars76** [comment]
It looks like the gstatic fonts are coming with the response header 

cache-control:max-age=0

https://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGLlcMrNrsnL9dgADnXgYJjs.ttf

https://fonts.gstatic.com/s/sourcesanspro/v9/ODelI1aHBYDBqgeIAH2zlEY6Fu39Tt9XkmtSosaMoEA.ttf

https://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGPS42wKzre0cxmO5m5GyTsY.ttf

And that's the reason why IE 11 is showing a blank page.

For the time being the following resolved the Issue:

Tools > Compatibility View settings > Uncheck the option "Display intranet sites in Compatibility View"

Thanks

**Comment by bryanjacquot** [comment]
@mars76 Grommet is not supported in IE with Compatibility View enabled.  You can view the browser support matrix here: http://grommet.github.io/docs/browser-support
