### ISSUE TITLE
when installing via npm, there's no "vanilla" themed css

### ISSUE THREAD

**Issue by luisrudge** [grommet/grommet#848]
![image](https://cloud.githubusercontent.com/assets/941075/18412232/d17b1480-775f-11e6-98b7-2931026ba4a0.png)

There's a .min.css file for every theme, but the default `grommet.min.css` is not the same as vanilla, since it doesn't have  the button hover effects:

![grommet](https://cloud.githubusercontent.com/assets/941075/18412254/372ff692-7760-11e6-82c3-66089d07afec.gif)

**Comment by bryanjacquot** [comment]
Thanks for catching this @luisrudge.  We'll be updating the grommet.min.css with the vanilla theme as we don't have a need for the unthemed grommet.min.css.

**Comment by luisrudge** [comment]
cool 👍

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/27965dad3a9e64ad911e2ba8d9b9f2a6575cc36f

It will be soon available in the stable branch and in the upcoming 0.6.12 release.
