### ISSUE TITLE
microdata properties

### ISSUE THREAD

**Issue by mattfarina** [grommet/grommet#85]
It would be useful to support microdata so things like schema.org could be integrated. [React itself supports microdata properties](https://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes).

Consider this a feature request that I may get to or others may get to first.

**Comment by bryanjacquot** [comment]
@mattfarina, we will start with the basic structural and typographic components.  Our strategy will be to pass any properties that components don't natively understand on to the underlying DOM element.  Once we get these components updated, we can explore enhancing other components on a case-by-case basis.

- [ ]  Anchor
- [ ] Article
- [ ]  Box
- [ ]  Button
- [ ]  Footer
- [ ]  Header
- [ ]  Heading
- [ ]  Image
- [ ]  List
- [ ]  Menu
- [ ]  Paragraph
- [ ]  Section
- [ ]  Sidebar
- [ ]  Table
- [ ]  Title

**Comment by ericsoderberghp** [comment]
Finished over quite a few changes in the last few days.
