### ISSUE TITLE
Documentation: Use of capitals in text

### ISSUE THREAD

**Issue by gilphilbert** [grommet/grommet#851]
The page Writing Style page in the documentation (http://grommet.github.io/docs/writing-style) includes the following bullet point under "Don'ts":

- Do not use UPPERCASE in text or exclamation points!!!!

However, the Best Practices page (http://grommet.github.io/docs/best-practices) then includes a whole page where every title is in block capitals. I suspect this is the use of Labels, which includes an optional _uppercase_ argument.

These two appear to conflict.

This bullet point also includes two statements that should be separate bullet points

### Expected Behavior
The bullet points should read:
- Do not use UPPERCASE in paragraphs
- Do not use exclamation points!!!! 

### Actual Behavior
- Do not use UPPERCASE in text or exclamation points!!!!

### Steps to Reproduce
View documentation

**Comment by alansouzati** [comment]
I believe the pattern is not to user uppercase in the middle of a sentence. Heading elements are ok to be uppercase.

I like the idea of moving the don't to separate bullets points. Would you be willing to submit a pull request for this? Please use the grommet-docs project for that.

https://github.com/grommet/grommet-docs

Feel free to reopen the issue if you feel this is still unclear to you.
