### ISSUE TITLE
When installing via npm, there's no Pulse (or Hotspot) component

### ISSUE THREAD

**Issue by tomers** [grommet/grommet#853]
I am using the following packages:

- grommet@0.6.11
- grommet-toolbox@0.2.12
- grommet-icon-loader@0.2.13

I tried to use the Pulse component (http://grommet.github.io/docs/pulse), but it seems to be missing from the NPM package.

The Pulse component was created in this commit (Hotspot converted to Pulse icon): https://github.com/grommet/grommet/commit/4d6f8aa32c33fe533d4599eefef80412391d4b08, which happens just after the upgrading of the package version to 0.6.11: https://github.com/grommet/grommet/commit/36ed276f1df69cdc1ee0c8a7714bdaf382c9fa0c

In the NPM package I could not find Pulse, nor Hotspot.

Please advise.
Thanks

**Comment by alansouzati** [comment]
Thanks for reporting this. As for now, it is only available in the stable branch. It will be soon part of the upcoming 0.6.12 release.

https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F

refer to the link above for instructions on how to switch to stable.

We are working on updating the docs page to inform which components are not available in the latest official release.
