### ISSUE TITLE
Window scrolls while Layer is active.

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet#854]
When a Layer component is active and a user scrolls down the browser window will scroll as well. Let's investigate a better method of controlling the window scroll state.

**Comment by alansouzati** [comment]
I tried reproducing it here: https://grommet.github.io/docs/layer

But i could not, can you add the steps to reproduce?

**Comment by karatechops** [comment]
Here is a [codepen](http://codepen.io/karatechops/pen/rrBoWv?editors=0010) displaying the behavior.

**Comment by alansouzati** [comment]
weird let me try to reproduce it locally.

**Comment by karatechops** [comment]
I added a commented out proposed fix to the [code pen's SCSS](http://codepen.io/karatechops/pen/rrBoWv?editors=0110).

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/867a9b643ea1fad5cb3520d2f7b33f520a3a8593
