### ISSUE TITLE
Meter type circle not showing curve correctly

### ISSUE THREAD

**Issue by tobias-flitsch** [grommet/grommet#857]
The Meter component, when supplying a series will render the cure inverse when using imbalanced values. Applies to the Meter component of type `circle`.

### Expected Behavior
The Meter component should render a plain circle. 

### Actual Behavior
The last curve / series is rendered with an inverse curve.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/tobias-flitsch/pen/amNBRR?editors=0010

![image](https://cloud.githubusercontent.com/assets/4466053/18523842/dd77e4d0-7a6a-11e6-8e09-0d5313e02ea8.png)

### Steps to Reproduce
 1. Create Meter component with an imbalanced series, 4000 entries, 10 entries, 5 entries. 
 2. Use Meter of type circle and set `stacked` to `true`

### Your Environment

* Grommet version: 0.6.11
* Browser Name and version: chrome 52.0.2743.116 (Official Build) m (32-bit)
* Operating System and version (desktop or mobile): Windows 10 (desktop)

**Comment by alansouzati** [comment]
This has been fixed by this:

https://github.com/grommet/grommet/commit/f15c609326a543d354251b5b357b8468db6b632a
