### ISSUE TITLE
Title text clipping

### ISSUE THREAD

**Issue by apihlaja** [grommet/grommet#865]
### Expected Behavior
Title component should render short word without clipping.

### Actual Behavior
`g` clips due to combination of line-height and overflow settings.

### Screen shot

![grommet-gg](https://cloud.githubusercontent.com/assets/8148584/18587410/92414864-7c2a-11e6-8e44-23187b5469f9.png)

### Steps to Reproduce
 1. Edit Hello World to render `<App><Title>gg</Title></App>` ([Codepen](http://codepen.io/anon/pen/JRKbvk))

### Your Environment

* Grommet version: latest stable (a6d063e653d8cce07ef7a19049b909fdd2abde39)
* Browser Name and version: Google Chrome 53.0.2785.116 m, Firefox 48.0.2
* Operating System and version (desktop or mobile): Windows 10

**Comment by apihlaja** [comment]
It seems Ferret don't suffer from this. It uses Metric font which has smaller `g` so it fits, even with line-height of 1. For example, default font (Source Sans Pro) or Arial needs more (1.5?).

Not sure what would be proper fix. Normally, g overflows but Title has `overflow: hidden` to enable text-overflow. Maybe overflow settings can be adjusted somehow. Other option would be to increase line-height. Doing it for title only don't behave nicely when used as in Ferret. Increasing line-height of Title and Header to 34px or 1.5 seems to work, at least with my header setup.

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/3bdaef704d2ab28955f6a3669544dd61070534f2
