### ISSUE TITLE
NumberInput stepUp() and stepDown() do not cause react to update

### ISSUE THREAD

**Issue by ajwinkworth** [grommet/grommet#868]
In a NumberInput element if you are to set the value via code or even set the value to a constant number then the element can not be updated via the text input but can be changed with the buttons up and down. I have worked out that the stepUp() and stepDown() do not cause react to update. Using React.forceUpdate() below the stepUp() and stepDown() calls does fix the issue. I do not know if this is intended, a grommet bug, a react bug, or a chrome bug?

I have also noticed that the NumberInput uses parseInt in its workaround for IE. This seems like an issue because the NumberInput & step can be a float?

I would issue a pull request but I do not know if it is appropriate to work around?
### Expected Behavior

The NumberInout up and down buttons should cause react to update
### Actual Behavior

The Buttons do not cause any update/checking of values etc

http://codepen.io/anon/pen/rrLvPa?&editors=0010
### Steps to Reproduce
1. Load the codepen in Chrome
2. push up and down buttons... see value change
3. type anything in to the box and see the value snap back to the fixed value
### Your Environment
- Grommet version:
- Browser Name and version: Google Chrome 53, MS Edge
- Operating System and version (desktop or mobile): Win10 desktop

**Comment by epilande** [comment]
Hi @ajwinkworth when setting the `value` prop you must provide an `onChange` handler to the NumberInput component. Another option would be to use `defaultValue` instead of `value`. I've forked your CodePen & added examples of both solutions https://codepen.io/epilande/pen/BLQJxw?editors=0010

For more info:
- https://facebook.github.io/react/docs/forms.html#controlled-components
- https://facebook.github.io/react/docs/forms.html#default-value

**Comment by ajwinkworth** [comment]
Hi @epilande My issue is actually more complex then the one I posted. When trying to find the simplest example of the issue I reduced the issue to my codepen. I may have inadvertently simplified to a completely different  issue which has to do with not having the onChange but with similar effect. 

 I have a onChange handler that dispatches a redux action that is handled in a reducer. The reducer calculates various things and then will set the redux state. The state is then mapped to the control via React.Redux connect. The issue I seem to be having is if reducer is picking a value that does not match the value set by the + - buttons isn't reflected until you manually type into the box.

I have removed my workaround and posted a video:
[Video showing Issue](https://youtu.be/8ejjhBVdEVo)

**Comment by epilande** [comment]
@ajwinkworth thanks for the video. It's still hard to tell what's the problem without seeing the code. Hmm is there any internal state with the containing component? I notice when updating `Pour Height`, `Form Height` is also updated, but when updating `Form Height`, `Pour Height` is not updated, is `Form Height`'s `value` set to the same `value` as `Pour Height`? Do they have the same `onChange` function? 

If you're handling this via state, do you need to update state in response to a prop change? https://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops

**Comment by ajwinkworth** [comment]
On the right hand side you can see that the state is loaded into the value prop/attribute. The "value" does not change but the what is written on the component does change. I believe this is because the stepUp() and stepDown() functions are not causing react to update correctly for some reason? If you forceUpdate() react when calling stepUp() & stepDown() then the problem goes away, but this quick fix seems too hacky to pull request? All of my components are "dumb" only showing the values from the props. The state is passed in via React-Redux containerization. 

As a side note the IE work around in the same NumberInput uses parseInt() which if you use a step that is not a integer seems to cause strange step issues. I would suggest Number() as a possible solution?

**Comment by epilande** [comment]
Hi @ajwinkworth I'm not able to reproduce this issue. I've created a new [CodePen](http://codepen.io/epilande/pen/qaRdZP?editors=0010) with react redux & tried to reproduce what was happening in the video, but no luck. Am I missing something? If you could fork the CodePen & set it up to have the same issue, that would be very helpful. http://codepen.io/epilande/pen/qaRdZP?editors=0010

As for `parseInt` can you elaborate on what strange step issues are happening?

**Comment by ajwinkworth** [comment]
Hi @epilande. Attached is the codepen which is pretty close to my code. Based on the code the second input should not be able to be less the the first input. If you manually type in the numbers then this is always true. If you press the up and down button on the second input (in chrome) then you can actually get the NumberInput control to show something different then what its value prop has as a value.

http://codepen.io/ajwinkworth/pen/ampRgp

If you want to see the possible parseInt() error then you need to load your http://codepen.io/epilande/pen/qaRdZP?editors=0010 in Edge or IE and then press the up and down buttons. If you press + first then you will jump up 0.1 with the first press but the next press does nothing... and if you then press - button the value will jump down 1 and not 0.1. I think that this is because the step={0.1} is not a int its a float. You could use parseFloat but my current understanding is that Number() may be better.

**Comment by epilande** [comment]
Ah I see the problem now. Currently the way `NumberInput` is built the `+` & `-` calls the `_onAdd` & `_onSubtract` functions which changes the input value regardless of the `onChange`. The `onChange` is basically a callback after the value has already changed. One way to achieve the functionality you've stated would be to set the `min` prop to the first input value. I've updated the CodePen to have that functionality http://codepen.io/epilande/pen/qaRdZP?editors=0010

**Comment by alansouzati** [comment]
Is this still an issue?

**Comment by ajwinkworth** [comment]
I believe it is an issue as it breaks flux 1 way updates by updating the value on the screen separate to the value in the prop. The way this works at the moment is surprising. Code changes could make it "non-surprising" and make it compatable with Flux 1 way updates. When I get some spare time I might make a pull request with changes so that it can be discussed?

**Comment by tracybarmore** [comment]
Hi @ajwinkworth. Apologies for the delayed response here. We absolutely love pull requests, so please send one our way when you get the chance.

**Comment by dgennetten** [comment]
I'm not sure this is an issue.  I cannot reproduce the error and in fact in the grommet.io example, it works fine.

The codepen provided, however, has two issues which could be contributing to the author's position: 1) prop `step` is provided as type `string` when it should be `number`; and  2) there is no `onChange` handler, hence the control will render a read-only field!

**Comment by dgennetten** [comment]
I don't believe this is an issue. I cannot reproduce the error and in fact in the grommet.io example, it works fine.

The codepen provided, however, has two issues which could be contributing to the author's position: 1) prop step is provided as type string when it should be number; and 2) there is no onChange handler, hence the control will render a read-only field!
