### ISSUE TITLE
Better support for localization in DateTime component

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#872]
DateTime only supports English month names.  The ability to change the names should be added for localization purposes.  Further, the format of the placeholder shouldn't have to match the format used in the Moment library.  For example, showing MMM Do YY to the user causes confusion, but that format is proper for Moment.
### Expected Behavior

DateTime should automatically check the local and format itself accordingly.
### Actual Behavior

DateTime is tied to English month names and the **_placeholder_** matches the Moment js format.
### Your Environment
- Grommet version: Stable
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Win10

**Comment by ericsoderberghp** [comment]
See also issue #289.

**Comment by codingInSpace** [comment]
To add further light on the issue, another problem is the limit to display Sunday as first day of the week. Could this perhaps be implemented as a prop?

Right now with grommet 1.3.4 I'm getting Sunday as first weekday in the top row with weekdays, but Monday as first weekday in the actual dates. So for instance, 1st of May is shown in the Sun column, when it is actually Monday.

**Comment by codingInSpace** [comment]
Actually I just realized that may be a separate issue? Or there's a smaller bug. The dates are wrong on initially clicking up the drop, but changing dates between months adjusts them.   

First click, dates are offset  
![date1](https://cloud.githubusercontent.com/assets/6057381/24881233/74782cf2-1e3d-11e7-9635-8b604e1aa9d4.png)

  
Change to 1st May, dates are correct  
![date2](https://cloud.githubusercontent.com/assets/6057381/24881230/6edfcbd8-1e3d-11e7-91fb-745f879b124c.png)

Clicking back to April and the dates remain correct, until closing the drop and opening it again.

**Comment by alansouzati** [comment]
we will be redesigning the DateTime component for Grommet 2.0. This issue will be part of this work.

**Comment by Waize** [comment]
@alansouzati is there any release-date(range) for 2.0?

**Comment by Primajin** [comment]
Great, may I wish also for two features:

- Possibility to set first day of week (https://en.wikipedia.org/wiki/Week#Week_numbering --> ISO-8601)
- Set a time difference (user will input local day and time, but value will be UTC/Zulu)

**Comment by alansouzati** [comment]
@Waize we don't have a specific date yet. but I want to get an alpha version out in the next month or so 👍 

@Primajin interesting requests. We will try to incorporate them in the next version of DateTime, thanks for bringing this up.

**Comment by raphi011** [comment]
It would be great if the next DateTime component would allow custom placeholders instead of the fixed format

**Comment by Primajin** [comment]
There is another thing, grommet seems to only use the **presentational date** (even in the onChange event arguments?), rather expose a real Date object and then only _display_ the formatted one, but store a "real" date internally. We would like to have the user pick a date, but then actually send an IsoString to the backend. That way automatic localization and even time difference could be achievable, because that is then only presentation.

**Comment by kevingrady** [comment]
And the **Notification** component of Grommet has the same issue. The date could not be localized.

**Comment by rbalaga** [comment]
may be we can override the **_renderDrop** function in **DateTime** component in parent component to display customized **DateTimeDrop** component.
a little bit of idea is presented here. 
https://rbalaga.github.io/2020/02/09/override-child-methods-from-parent/
