### ISSUE TITLE
Box with full={true} attribute gets the size of whole window, ignoring header and footer size

### ISSUE THREAD

**Issue by tomers** [grommet/grommet#874]
I am trying to implement sticky footer, by wrapping the TodoAppDashboard component in a Box component that has full={true} property (some code removed for brevity):

```
<App>
  <Header/>
  <Box full={true}>
    <TodoAppDashboard />
  </Box>
  <Footer/>
</App>
```

### Expected Behavior
I expect to see the following things in the browser window:
1. Header at top
2. The TODO app component
3. Footer at the bottom

This is based on the assumption that the box height will be calculated by the equation: '''Screen.height - Header.height - Footer.height'''

### Actual Behavior

I see all the components as expected, except that the height TODO app component is higher than expected. It seems as if the value is taken from '''Screen.height''', ignoring '''Header.height''' and '''Footer.height'''.

### Steps to Reproduce
 1. Generate sample app (grommet new sample-app)
 2. Surround the TodoAppDashboard component with Box that has the full={true} propery.
```
<Box full={true}>
  <TodoAppDashboard />
</Box>
```
 3. Start the app (gulp dev) and open the browser

### Your Environment

* Grommet version: 0.1.5
* Browser Name and version: Firefox 48.0 and Google Chrome 53.0.2785.113 (64-bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04 desktop (updated), x64

**Comment by alansouzati** [comment]
Full will use the entire viewport width as described in here: 

https://grommet.github.io/docs/box

> Whether the width and/or height should take the full viewport size.

Are you looking for a floating footer? Always visible the the bottom of a view port?

If yes, we support it:

`<Footer float={true} fixed={true}/>`

**Comment by alansouzati** [comment]
My assumption is that you are looking for something more like this:

http://codepen.io/alansouzati/pen/JRbEyB?editors=0010

Please feel free to reopen this issue if you still think this is wrong.

**Comment by tomers** [comment]
Thanks Alan! That is exactly what I was looking for.

**Comment by tomers** [comment]
I would like to reopen this issue. I am not sure whether this is a Grommet bug, or is it just me having trouble finding the right way to change the footer in the sample-app into a sticky footer.

I tried Alan's suggestion and it worked initially, but then I created more content in the main box by rendering multiple instances of TodoAppDashboard component, and it didn't go well. I expect to have these component rendered as expected, and then in the bottom to have the footer. Alternatively, I could do with a floating footer with a scrollable area between the header and the floating footer that renders the inner components successfully.
However, what I got is the header and footer properly rendered in their expected location, but the main components being shrinked to accommodate all of them in the box. See screenshot:

![screenshot_20160921_093150](https://cloud.githubusercontent.com/assets/83443/18700208/ac33c38e-7fde-11e6-97c3-fd252f1a00e3.png)

Source code:

```
class Main extends Component {
  render () {
    return (
      <App centered={false}>
        <Box full={true}>
          <Header direction="row" justify="between" large={true}
            pad={{horizontal: 'medium'}}>
            <Title>Sample App</Title>
          </Header>
          <Box flex={true}>
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
          </Box>
          <Footer primary={true} appCentered={true} direction="column"
            align="center" pad="small" colorIndex="grey-1">
            <p>
              Build your ideas with <a href="http://grommet.io" target="_blank">Grommet</a>!
            </p>
          </Footer>
        </Box>
      </App>
    );
  }
};

let element = document.getElementById('content');
ReactDOM.render(React.createElement(Main), element);

document.body.classList.remove('loading');
```

Thanks

**Comment by alansouzati** [comment]
Can you try flex={false} in the root Box component for TodoAppDashboard?

**Comment by tomers** [comment]
@alansouzati, your suggestions works in Firefox, but does not work in Chrome.
Is the following code is the change that you suggested?

```
class Main extends Component {
  render () {
    return (
      <App centered={false}>
        <Box full={true} flex={false}>
          <Header direction="row" justify="between" large={true}
            pad={{horizontal: 'medium'}}>
            <Title>Sample App</Title>
          </Header>
          <Box flex={true}>
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
            <TodoAppDashboard />
          </Box>
          <Footer primary={true} appCentered={true} direction="column"
            align="center" pad="small" colorIndex="grey-1">
            <p>
              Build your ideas with <a href="http://grommet.io" target="_blank">Grommet</a>!
            </p>
          </Footer>
        </Box>
      </App>
    );
  }
};
```

I also tried the following variation which does not work:

class Main extends Component {
  render () {
    return (
      <App centered={false}>
        <Box full={true}>
          <Header direction="row" justify="between" large={true}
            pad={{horizontal: 'medium'}}>
            <Title>Sample App</Title>
          </Header>
          <Box flex={false}>
            {/* only one component */}
            <TodoAppDashboard />
          </Box>
          <Footer primary={true} appCentered={true} direction="column"
            align="center" pad="small" colorIndex="grey-1">
            <p>
              Build your ideas with <a href="http://grommet.io" target="_blank">Grommet</a>!
            </p>
          </Footer>
        </Box>
      </App>
    );
  }
};

**Comment by alansouzati** [comment]
it works for me.

 I've created a codepen to illustrate it:

http://codepen.io/alansouzati/pen/amwvBd?editors=0010

Could you please validate it? Are you using the latest grommet?

**Comment by dhampik** [comment]
I guess when people want to have sticky footer, they usually mean a footer that is stuck at the bottom when there is not much content on the page and pushed down with content when the content is big enough.
A lot of ways how to implement the sticky footer can be found at [CSS-Tricks](https://css-tricks.com/couple-takes-sticky-footer/).

In case if anyone looking for a real sticky footer sample for grommet - [here it is](https://codepen.io/dhampik/pen/LjqpdY)!
@alansouzati, maybe you can propose a more elegant solution without using custom css?
