### ISSUE TITLE
Header tag is not allowing underline on anchor tag while hovering

### ISSUE THREAD

**Issue by vaibhavbhargav** [grommet/grommet#883]
We need to have some anchor tag in header tag(with fixed property set to true), Header tag is not allowing underline on anchor tag while hovering.

### Expected Behavior
Header tag is not allowing underline on anchor tag while hovering.  

### Actual Behavior
Header tag should not enforce removing underline on anchor tag while hovering.  

### URL, screen shot, or Codepen exhibiting the issue

https://codepen.io/vaibhavbhargav/pen/ZpKzVg

### Steps to Reproduce
 1. Use Anchor tag component within Header tag.

### Your Environment

* Grommet version: latest
* Browser Name and version:Chrome
* Operating System and version (desktop or mobile):desktop

**Comment by bryanjacquot** [comment]
This has been resolved.  The following CodePen was forked from yours with the theme changed to the HPE theme: https://codepen.io/grommet/pen/kkyvjx

**Comment by bryanjacquot** [comment]
Fixed in https://github.com/grommet/grommet/commit/0ff8904867d9aa3a4529257b4bd055b2c73b3d7c
