### ISSUE TITLE
Search Input component does not replace the highlighted auto suggest text in the search input box - while using arrow keys

### ISSUE THREAD

**Issue by eniyan** [grommet/grommet#884]
**STEPS to Reproduce:**
In the grommet.io site: 
1) Go to Search Input Component Example.
2) Click on search box
3) Press down arrow key

**Actual Behavior:**
When a user clicks the down arrow, the highlight moves from "one", "two","three" and so on.. However, the text in the search input box remains as "one" 

**Expected Behavior**
The text inside the "Search box" should be replaced by the highlighted auto suggest text when the user uses down/up arrow key. 
For Example in the above scenario, User should see "One", "Two", "Three".. and so on.. inside the text box, while clicking the down arrow.

**Comment by alansouzati** [comment]
After brainstorming with @ericsoderberghp we've raised few UX concerns when we replace the value when pressing up/down.

As an example: 

Let's say we have the following suggestions: "Tomorrow, Arrow, Sparrow, Row"

Then you type: "row"

You press up/down to check the suggestions, if you replace the value, how would you go back to "row" in the example of selecting "tomorrow".

For now, we believe that the currently implementation (press enter to select) is good enough. I propose we postpone improvements to this after 1.0.0.

**Comment by bryanjacquot** [comment]
Agree, replacing the value has issues when the field is editable.  We're going to keep the current behavior.  If you need the behavior described in the Expected behavior, consider a traditional `<select>` control.

**Comment by eniyan** [comment]
@alansouzati 
In the above example: Pressing down arrow replaces the text, Once you reach the last one, further pressing the down arrow key brings the text 'row' 
Please see google behaviour on chrome.
