### ISSUE TITLE
Not good dispaly whe using meter sample #11

### ISSUE THREAD

**Issue by RodHPE** [grommet/grommet#885]
Use meter #11 in our project, but the display is not the same as sample
https://grommet.github.io/hpe/docs/meter/examples/#11
I try many times to draw the UI using Meter, Box, Label..... across all attributes but failed.
why the sample appearance have aligned? 
### Expected Behavior
appearance  as sample

### Actual Behavior
 UI appearance   not  as sample

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/20080920/18824694/a08c1d4e-83f6-11e6-92b6-669e1c820418.png)

Sample UI.
![image](https://cloud.githubusercontent.com/assets/20080920/18824891/0b578496-83f8-11e6-902e-32d92a681ae5.png)

### Your Environment

* Grommet version: 0.6.11
* Browser Name and version:  chrom
* Operating System and version (desktop or mobile): Linux

**Comment by bryanjacquot** [comment]
Here is a CodePen with the desired layout: http://codepen.io/grommet/pen/WGjddx?editors=0011

**Comment by RodHPE** [comment]
Looks good. thank you!
