### ISSUE TITLE
When removing the left child in a Split component, the right child will unmount and remount.

### ISSUE THREAD

**Issue by heyjared** [grommet/grommet#886]
For example, in the ferret app:
```
      <App centered={false}>
        <Split flex="right" onResponsive={this._onResponsive} priority="left">
          {pane1}
          {pane2}
        </Split>
      </App>
```

When `pane1` changes between NavSidebar and null, `pane2` will unmount and remount.

### Expected Behavior

`pane2` should be unaffected and should not run `componentDidMount` a second time. I did not experience this in grommet@0.6.11

### Actual Behavior

`pane2` unmounts and remounts, calling `componentDidMount`. If async operations like data fetching are inside `componentDidMount`, they will be executed.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/anon/pen/wzdKQL?editors=0011

### Steps to Reproduce
 1. Click to view the console.
 2. Click Right button. `componentDidMount` runs for the Right component.
 3. Click Right button again. `componentDidMount` runs for the Right component again.

### Your Environment

* Grommet version: 0.6.12
* Browser Name and version: Chrome 53
* Operating System and version (desktop or mobile): MacOS 10.12

**Comment by alansouzati** [comment]
Fixed https://github.com/grommet/grommet/commit/1746fcd7f4fcbce4aade4f72bf62d65fb02ca1f3
