### ISSUE TITLE
No css applied to components

### ISSUE THREAD

**Issue by simran66** [grommet/grommet#887]
No CSS classes applied to the components. Here's how my component looks like:

```
import React, {PropTypes}  from 'react';
import {Header, Title, Menu, Anchor, Navbar} from 'grommet';
const TopHeader = (props) => {
  return(
    <Menu inline={true} direction="row" size="large">
      <Anchor href="#" className="active">
        First action
      </Anchor>
      <Anchor href="#">
        Second action
      </Anchor>
      <Anchor href="#">
        Third action
      </Anchor>
    </Menu>
  );
}

export default TopHeader;


```

output:

Plain html components:

![noclasses](https://cloud.githubusercontent.com/assets/4191009/18841653/0a073cc0-8430-11e6-9c28-0503ae5fec6d.png)

**Comment by alansouzati** [comment]
Are you including the styles either as minified css in your html or using SCSS?

You can check [grommet-standalone](https://github.com/grommet/grommet-standalone) for an example for the minimum set of requirements for Grommet to work.

Also be careful with imports like this: `import {Header, Title, Menu, Anchor, Navbar} from 'grommet';` it will increase your bundle size significantly as your bundle size will include all the components inside grommet and filter it down to `Header, Title, Menu, Anchor, Navbar`.

The recommendation is to use the following syntax:

```
import Header from 'grommet/components/Header';
import Title from 'grommet/components/Title';
...
```

**Comment by alansouzati** [comment]
Are you still facing this issue?

**Comment by alansouzati** [comment]
Closing the issue for now. please re-open if you are still experiencing this issue.
