### ISSUE TITLE
The layout for addControl in Index is wrong

### ISSUE THREAD

**Issue by christinHP** [grommet/grommet#893]
OVGD uses grommet-index/components/Index.js

While change the OVGD layout, small and small, the icon from addControl will be overlap with filter icon.

![1](https://cloud.githubusercontent.com/assets/16797825/18906262/62b8b438-8599-11e6-8e46-1e469237fd3b.PNG)

**Comment by bryanjacquot** [comment]
@christinHP can you submit this issue against the grommet-index project?  https://github.com/grommet/grommet-index/issues

**Comment by ericsoderberghp** [comment]
This has been replaced by grommet-index issue #71.
