### ISSUE TITLE
Optimize use of svg icons to be size intelligent

### ISSUE THREAD

**Issue by bryanjacquot** [grommet/grommet#897]

**Comment by L0ZZI** [comment]
Assuming you're not asking for responsive icons...We're enhancing the icon sizes to align better across controls which includes enhancement to the "small" size and colorIndex implementation. Covered in, https://github.com/grommet/grommet-design/issues/33

**Comment by L0ZZI** [comment]
Design has been proposed. Revising Icon Component implementation coming in  issue #1144.
