### ISSUE TITLE
Using dropalign causes the text menu label to repeat

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#900]
If dropalign on a Menu is used, then clicking on the menu will cause the Menu label itself to be displayed along with the other menu times.

### Expected Behavior

Only show the child Menu items.

### Actual Behavior

The menu label itself and the menu items are displayed.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/14231471/18942189/df75e86a-85cb-11e6-8bca-1e8a1113dfa3.png)

http://codepen.io/mcwagner10/pen/KgmZbG

### Steps to Reproduce
 1. Make a menu using drop align
 2. Add children to Menu
 3. Click Menu

### Your Environment

* Grommet version: Stable
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Win10

**Comment by epilande** [comment]
Hi @mcwagner10 your CodePen link has changed to a different example which doesn't show the dropAlign issue. I've tried to reproduce the screenshot above but it's working as expected. http://codepen.io/epilande/pen/RGxbKY?editors=1010

If I missed something, please edit the CodePen

**Comment by bryanjacquot** [comment]
@epilande the issue is still present in your code pen, but is a bit different than the original submission:
![image](https://cloud.githubusercontent.com/assets/6393696/19199752/d323f184-8c82-11e6-88e9-3ff266653505.png)

**Comment by bryanjacquot** [comment]
This has been resolved.
