### ISSUE TITLE
(Button) disabled attribute.

### ISSUE THREAD

**Issue by svnlto** [grommet/grommet#901]
Summary here: https://github.com/grommet/grommet/pull/218/commits/1d5e962b3fc254b52c80656dec4c9c2d752e0fb5#r81080069

### Expected Behavior
Be able to set disabled attribute manually.

### Actual Behavior
Needs handler function.

### Your Environment
* Grommet version: 0.6.12
* Browser Name and version: any
* Operating System and version (desktop or mobile): any

**Comment by bryanjacquot** [comment]
This can be done by not having an onClick handler on the button.

**Comment by svnlto** [comment]
Ok, what's the best way of assigning a handler function dynamically..?

**Comment by alansouzati** [comment]
How about? 
`var handler = shouldDisabledButton ? undefined : () => { alert('hi'); }`

**Comment by svnlto** [comment]
Makes sense. I obviously wasn't thinking that far. Thanks.

**Comment by reflog** [comment]
doesn't work when type="submit"

**Comment by mvanlonden** [comment]
Oh wait @reflog that's actually a feature. Now you don't need an `onClick` to disable a submit button. You can just conditionally set the type
