### ISSUE TITLE
Select shows tiny scrollbar in Edge and IE browsers

### ISSUE THREAD

**Issue by dgennetten** [grommet/grommet#903]
### Steps to Reproduce
 1.  Using Edge or IE, click or hover in Select component
 2. Observe appearance of tiny scrollbar. 
 3. 

### Your Environment

* Grommet version:  https://grommet.github.io/docs/select/examples
* Browser Name and version:  latest Edge & IE
* Operating System and version (desktop or mobile):  Win10

**Comment by bryanjacquot** [comment]
![image](https://cloud.githubusercontent.com/assets/6393696/19007763/ecf87e7c-8723-11e6-8e3b-8d076e8fcbff.png)
