### ISSUE TITLE
Latest on npm does not include components/TextInput.js

### ISSUE THREAD

**Issue by leonp1991** [grommet/grommet#904]
Currently when you run `npm i -S grommet` the package does not include components/TextInput.js (checked node_modules) as suggested in the docs.

### Expected Behavior
`import TextInput from 'grommet/components/TextInput';` should import the TextInput Component.

### Actual Behavior
Webpack cannot resolve module 

### Screenshot
http://i.imgur.com/nvAykSS.png

### Steps to Reproduce
 1.  install latest npm package into a project.
 2. import TextInput component.
 3. watch it fail :(.

### Your Environment
node@6.4.0, grommet@latest, webpack@1.13.2, OSX

**Comment by leonp1991** [comment]
If people are getting this issue a temporary fix is to download the TextInput.js file from github and put it in node_modules/gromet/components.

**Comment by leonp1991** [comment]
To avoid this I assume you could install a different version. Or you can copy the source, transpile it, then put it in node_modules/grommet/components.

**Comment by alansouzati** [comment]
This is a recently added component, sorry the docs does not report anything about it.

If you want to access this component now you can use the stable branch:

https://github.com/grommet/grommet/wiki/What-is-grommet-stable-and-how-to-use-it%3F

We will soon be releasing Grommet 1.0.0 and this will be part of an official release.
