### ISSUE TITLE
DateTime cannot easily change month value

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#905]
When clicking on the arrow to change the month, the selection panel disappears.

### Expected Behavior

Allow user to cycle through all months without having to constantly re-open the calendar.

### Actual Behavior

Calendar disappears when clicking the arrow next to month.

### URL, screen shot, or Codepen exhibiting the issue
http://codepen.io/mcwagner10/pen/vXmAEE

### Steps to Reproduce
 1. See CodePen

### Your Environment

* Grommet version: Stable
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Win10

**Comment by bryanjacquot** [comment]
This example also exhibits the problem: https://grommet.github.io/docs/date-time/examples#3

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/7720a32eb4127a738281da47223ac66194babe0d
