### ISSUE TITLE
Scrollbar missing on the logon page

### ISSUE THREAD

**Issue by Deklin** [grommet/grommet#91]
When using <Logon or <LogonForm, there is no scrollbar present.

**Comment by bryanjacquot** [comment]
Hey @Deklin, could you provide some more information about this issue?  In what cases do you need a scrollbar on a login page?  That component has been designed to respond to any screen size without requiring a scroll bar.

**Comment by ericsoderberghp** [comment]
There's a problem in that resizing the Login page doesn't provide scrolling/responsiveness when it should. You can see this here if you resize your browser window: http://grommet.io/medium-app/login

**Comment by Deklin** [comment]
Thanks Eric (this is Steve Btw) 

Bryan;
What Eric said is the same issue we have. On the logon page we need to add footer information about product version # etc. That is scrolling off screen and no scrollbar is appearing. Even without that if the size is too small no scroll appears.

**Comment by ivandurst** [comment]
Thanks @Deklin. This is fixed in https://github.com/grommet/grommet/pull/211.
