### ISSUE TITLE
Missing Icon ZoomOut

### ISSUE THREAD

**Issue by highPriestLOL** [grommet/grommet#913]
The ZoomOut Component does not exist in the  /grommet/components/icons/base/ZoomOut.js

### URL, screen shot, or Codepen exhibiting the issue

https://grommet.github.io/docs/icon

### Steps to Reproduce
 1. Attempt to `import ZoomOut from 'grommet/components/icons/base/ZoomOut';`
 2. N/A
 3. N/A

### Your Environment

* Grommet version: 0.6.9
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Archlinux

**Comment by bryanjacquot** [comment]
https://github.com/grommet/grommet/commit/69b0d4e9eee3a0bde6b18986b809b8a6cdfb4d5f
