### ISSUE TITLE
The name and/or id elements can not be added to login button for test automation

### ISSUE THREAD

**Issue by pgoodrich7** [grommet/grommet#92]
The login page form has the following: "<button class="button button--primary login-form__submit" data-reactid=".0.$=10:0.1.0.4">Log In</button>" but developer can not add a name or id so can be used for test automation.  The class element could be used but has potential for changes and not fun to find a specific one in the list each time.

**Comment by Deklin** [comment]
It would be helpful if each grommet component had a data-debug-id field for test automation to use for testing.

**Comment by pgoodrich7** [comment]
The data-debug-id could be used if static and include a unique id to component but I have not seen this used consistently by developers.  Sometimes this id is of a dynamic object id which is not helpful since we can not know beforehand.

**Comment by bryanjacquot** [comment]
Much of this will be handled by the resolution of https://github.com/grommet/grommet/issues/85.  We will use this issue to track the specifics of LoginForm since that is not one of the initial components we'll be addressing.

**Comment by alansouzati** [comment]
The recommendation is to use query selector to grab the elements without the need for the id.

https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector

For example:

```
  document.querySelector('.my-login-form button');
```

We avoid adding ids inside these components to not face issues with duplicated id in the DOM. LoginForm is a higher-level component which will most likely end up moving to `grommet-addons`.

**Comment by Deklin** [comment]
Just a note this isn't recommend for TA scenarios. Class names are much more volatile than named locators per selenium guidelines, especially as dom structure changes during refactoring. Class names are low on the list of recommendations to use. 
https://mestachs.wordpress.com/2012/08/13/selenium-best-practices/

ID is one option, another option is data-ta-id to give it a named locator

e.g.
data-ta-id="login" 

data-ta-id="username" or data-ta-id="username_input"

**Comment by alansouzati** [comment]
I see your point, but I don't think this is a good idea for production build either. In this case you are adding debugging information that will be most likely present in your production site (increasing the bundle size).

In the case of a LoginForm, the data-ta-id would need to be bundled with it which can lead to side effects like two login forms in a page warning about duplicated ids.

We talked a lot about this in a recent meeting with the Grommet team. If you want to add the id for LoginForm, our current recommendation is to copy it from the Grommet source and move it to your project. As I said, these high-level components will be soon moved to grommet-addons.

**Comment by Deklin** [comment]
@alansouzati thanks for the update and consideration
