### ISSUE TITLE
Selected item from the main menu is cut in half

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#93]
This issue is found on  Samsung S4 (horizontal direction), and desktop with browser set to phone size:

![phone-selecteditem](https://cloud.githubusercontent.com/assets/13039669/8789254/cc76e756-2ef5-11e5-8255-3a2e2986f002.jpg)

**Comment by bryanjacquot** [comment]
@tran2519 can you verify this issue is resolved on http://ferret.grommet.io
