### ISSUE TITLE
DateTime widget revert back to Calendar only trying to toggle time with short browser

### ISSUE THREAD

**Issue by yleigh** [grommet/grommet#939]
With short browser height (I have browser debugger opened.), the DateTime widget on grommet.io is shown with the time piece hidden. I can scrollbar to show the time piece. But if I try to toggle time by '-' or '+', the DataTime will revert back to only showing the Calendar piece.

### Expected Behavior
Should be able to toggle time on DateTime widget without revert back to show Calendar piece only.

### Actual Behavior
See above description.

![calendarwidget](https://cloud.githubusercontent.com/assets/9558295/19158473/def0d6b6-8bb6-11e6-8a46-0c868ae3b301.PNG)
![calendarwidgettimeshown](https://cloud.githubusercontent.com/assets/9558295/19158498/f6f69fde-8bb6-11e6-94fe-1fba6b81f247.PNG)

### Steps to Reproduce
 1. open https://grommet.github.io/docs/date-time
 2. F12 open browser debugger and adjust to show DateTime widget as shown in attached, with time piece hidden and scrollbar shown
 3. Scrollbar down to show the time piece as shown in 2nd attachment
 4. click on '-' or '+' to adjust time, DateTime will revert back to only showing Calendar piece.

### Your Environment
Windows 10, Chrome Version 53.0.2785.143 m (64-bit)

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/42b19a553bdf46ac49b87663f70b950d161fe4eb
