### ISSUE TITLE
General Sticker Sheet Updates

### ISSUE THREAD

**Issue by L0ZZI** [grommet/grommet#940]
Sticker Sheet 1.0 Work

General:
- [ ] Separate Light and Dark Themes into 2 pages
- [ ] Convert Components into Embedded Symbols, Text Styles, and Color Palettes 

HPE Specific:
- [x] Add CaaS Header
- [x] Add CaaS Footer

Tweaks:
- [x] Adjust App Header to include Search
- [ ] Sidebar Contrast/Selection Tweaks
- [x] Remove Breadcrumb, Pagination, Icon-bar, and Toolbar
- [x] Update Status Icons
- [x] Input: Update Select, Text Input, Date Time, Dropdown Menu Shadow Removal
- [x] Remove Image Size Placeholders

Add:
- [x] Accordion
- [x] Card
- [x] Carousel
- [x] Hero
- [x] Label
- [x] List
- [x] Menu
- [x] Notification
- [ ] Quote
- [x] Tip
- [x] Toast
- [x] Value
- [x] Danger Button (Red)
- [x] Video
- [ ] Layer
- [ ] Login
- [ ] Text Color

Review:
- [x] Pulse: Style doesn’t align?
- [x] Spinning: Revise to be more Grommet like?

**Comment by tracybarmore** [comment]
Old Card. Closing to open individual new cards.
