### ISSUE TITLE
Circle meter looks broken if any series value has 0

### ISSUE THREAD

**Issue by coltonw** [grommet/grommet#948]
### Expected Behavior

Circle meter should treat a 0 as not taking up any space in the circle.
### Actual Behavior

The 0 value causes the circle to have a huge empty gap in the circle with no value.
### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/coltonw/pen/LRQgER?editors=1010#0
### Steps to Reproduce
1. Create a circle meter with a 0 as one of the values.
### Your Environment

- Grommet version: 0.6.12
- Browser Name and version: Chrome 53.0.2785.143 (64-bit)
- Operating System and version (desktop or mobile): OS X El Capitan

**Comment by coltonw** [comment]
The possibly obvious workaround of deleting the value from the series is a problem because the index is important when you are using a meter with a Legend where you care about the activeIndex.

**Comment by ericsoderberghp** [comment]
I'm not sure how the 0 is taking up any space. The large grey arc is the underlying track that the segment values are drawn in. If you set `max={10}`, it will be removed as the total will now be 5+4+1=10 instead of the default max value of 100.

**Comment by ericsoderberghp** [comment]
We believe it is working correctly. Since we haven't received any further comment, we are closing the issue.

**Comment by coltonw** [comment]
Just to close on this since I had never replied, I was confused by the default max of 100 because in most cases for us we were much larger than that and the meter will adapt to having a number much larger than the max and will look fine in that case.
