### ISSUE TITLE
NumberInput removes input when trying to enter in a Letter

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet#951]
If I enter in numbers as values and then type a Letter, no letter is displayed and my number value is deleted.

https://grommet.github.io/hpe/docs/number-input

### Your Environment
* Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-07 at 2 37 02 pm](https://cloud.githubusercontent.com/assets/13038855/19206118/9bfa40aa-8c9b-11e6-9f2e-7af020de38e1.png)

**Comment by ericsoderberghp** [comment]
Fixed in latest grommet and grommet-docs.
