### ISSUE TITLE
ESC key doesn't dismiss Layer

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet#952]
Layer doesn't dismiss on when hitting ESC key.

https://grommet.github.io/hpe/docs/layer/examples#1

### Your Environment
* Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/6439dbdc1482e93813bcbe234f3d011a61a86339
