### ISSUE TITLE
Search suggestions, resource type is not right aligned

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet#953]
In mobile, search suggestions, resource type isn't right aligned. 

### Your Environment
* Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-07 at 4 49 51 pm](https://cloud.githubusercontent.com/assets/13038855/19208402/53eb472e-8cae-11e6-9813-9b2231c96819.png)

**Comment by ericsoderberghp** [comment]
Mostly fixed in the HC380 repository by making suggestion responsive. But, also allowed suggestions to take full width on palm. Commit aff00f418049356ffe52e647b25242a2ef2e91c1.
