### ISSUE TITLE
Search result panel (1) and the detail panel (2) should be in sync

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#96]
If the result panel is empty, the detail panel should also be empty (or displaying text 'No details').
If the result is not empty, then one item in the result set should be selected by default, and the detailed panel  should show related info.

![image](https://cloud.githubusercontent.com/assets/13039669/8789759/bae64dd8-2efa-11e5-817b-b0ba382d1ad2.png)

**Comment by bryanjacquot** [comment]
This is an issue with Ferret, not core grommet.
