### ISSUE TITLE
Tiles size prop ignored

### ISSUE THREAD

**Issue by nickjvm** [grommet/grommet#961]
### Expected Behavior

Specifying a size on the `Tiles` component should propogate down to the individual tile children.

``` jsx
<Tiles size="medium">
   <Tile>First</Tile>
   <Tile>Second</Tile>
   <Tile>Third</Tile>
</Tiles>
```
### Actual Behavior

Currently, size is ignored unless specified on the individual Tiles, like so:

``` jsx
<Tiles>
   <Tile size="medium">First</Tile>
   <Tile size="medium">Second</Tile>
   <Tile size="medium">Third</Tile>
</Tiles>
```
### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/nickjvm/pen/ZpojmZ?editors=0010
### Your Environment

- Grommet version: 1.0.0

**Comment by ericsoderberghp** [comment]
I think this was an intentional part of the 1.0  changes to put sizing at the Tile level. Looks like we forgot to deprecate/remove the `size` property on Tiles.

**Comment by ericsoderberghp** [comment]
Apologies for not deprecating this. We are not planning to add it back. You can control the size via the `basis` property.
