### ISSUE TITLE
Select component: Cannot read property 'select' of undefined

### ISSUE THREAD

**Issue by nickjvm** [grommet/grommet#965]
### Actual Behavior

Console error upon opening Select dropdown 
```
Select.js?af20:92 Uncaught TypeError: Cannot read property 'select' of undefinedcomponentDidUpdate 
   @ Select.js?af20:92(anonymous function) 
```
### URL, screen shot, or Codepen exhibiting the issue
https://grommet.github.io/hpe/docs/select

### Steps to Reproduce
 1. Click arrow to open dropdown
 2. Observe error in console

### Your Environment

* Grommet version: 1.0.0 
* Browser Name and version: Chrome Beta
* Operating System and version (desktop or mobile): OS X

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/d71b59ab4c7296195e469dc57e7ef66a43bbbfb9
