### ISSUE TITLE
Table is non-responsive at most widths

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#967]
The Table component does turn snap to mobile mode at 720px thereby allowing strange looking tables.

### Expected Behavior

Table should respond to a 720px and below window width.

### Actual Behavior

Table doesn't become responsive until much smaller (around 300px, sometimes not at all).

### URL, screen shot, or Codepen exhibiting the issue

http://codepen.io/mcwagner10/pen/vXjKzv?editors=0010
![image](https://cloud.githubusercontent.com/assets/14231471/19327942/61c660dc-9086-11e6-8918-31a437e3a790.png)

### Steps to Reproduce
 1. Make a table
 2. Shrink window to about 350px.
 3. Notice table is not suited for mobile.

### Your Environment

* Grommet version: 1.0.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Win10

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/0c86ea4f0054eebfc96150bd41bbe06333fb38d2
