### ISSUE TITLE
Headline should use variables for font size

### ISSUE THREAD

**Issue by zhangtreefish** [grommet/grommet#969]
As a developer I wish to enjoy the responsiveness of the headline component in heading components. So instead it will be awesome if headline can be tailor-made to specific starting fonts, and all starting fonts stay responsive to device sizes.

### Expected Behavior
I would like to set headline to font size of h1, which assumes  the size of h1 on large screens and h2 on phone screens.

### Actual Behavior
If I use the default  size(medium) of headline, the size responds to device; But the medium is too large for my purpose. when I set size to small, not much visible change between large screen and phone screen. 

### URL, screen shot, or Codepen exhibiting the issue

[HeadlineSizeSmallNotVeryResponsive.docx](https://github.com/grommet/grommet/files/525750/HeadlineSizeSmallNotVeryResponsive.docx)

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version:
       `
         from package.json:
        "grommet": "https://github.com/udacityalumni/grommet/tarball/stable",
        "grommet-udacity": "0.1.4",
        `
* Browser Name and version: google chrome
* Operating System and version (desktop or mobile): Windows 10 desktop

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/21b39cbd189048a7bb21bd7c8d05635cf05bd2c6

**Comment by zhangtreefish** [comment]
I wonder if the commit messages ought to be 'Changed Headline to adjust h1 and h2 font sizes when mobile'?
