### ISSUE TITLE
Search box covers the main icon

### ISSUE THREAD

**Issue by tran2519** [grommet/grommet#97]
This issue is seen on phone (both horizontal and vertical mode), or desktop browser set to phone size.

The main menu icon is seen at first:

![image](https://cloud.githubusercontent.com/assets/13039669/8789875/d77d6cb4-2efb-11e5-9063-ad44224c84c0.png)

When clicking on the search box, the main menu icon is no longer visible:
![image](https://cloud.githubusercontent.com/assets/13039669/8789888/ef622a54-2efb-11e5-831c-fe73bd07d9a3.png)

**Comment by bryanjacquot** [comment]
This is the designed behavior with the Ferret implement.  This was by design to put focus on search while on a small screen.
