### ISSUE TITLE
Heading to support responsive mode

### ISSUE THREAD

**Issue by zhangtreefish** [grommet/grommet#970]
Headings are useful, coming in their wide range of sizes. They would be even more awesome if their font sizes respond to device screen sizes.

### Expected Behavior
As a developer I would like to use a heading that appears smaller at phone screens out of necessity, and larger at big screens for aesthetic proportion.

### Actual Behavior
Headings currently do not respond to device screen sizes. For example, h1 and h2 tags appear alarmingly large on phone screens.

### Steps to Reproduce
 1. 
 2. 
 3. 

### Your Environment

* Grommet version: (from package.json) 
    "grommet": "https://github.com/udacityalumni/grommet/tarball/stable",
    "grommet-udacity": "0.1.4",
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): desktop, Windows 10

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/21b39cbd189048a7bb21bd7c8d05635cf05bd2c6
