### ISSUE TITLE
selected boolean property on TableRow and ListItem

### ISSUE THREAD

**Issue by arlair** [grommet/grommet#973]
The documentation for [TableRow]() and [ListItem](https://grommet.github.io/docs/list) both list a selected property.

> selected    true|false
> Whether this item is currently selected.
> 

The current post 1.0.0 code does not seem to define selected:
[TableRow](https://github.com/grommet/grommet/blob/6c603ab4959239970075d1b397dcd9269660b2bd/src/js/components/TableRow.js)
[ListItem](https://github.com/grommet/grommet/blob/6c603ab4959239970075d1b397dcd9269660b2bd/src/js/components/ListItem.js)

Am I missing something about how this works or is the documentation wrong? Thanks.

**Comment by arlair** [comment]
Oh, I see it seems it was deprecated in 0.6.2 and maybe removed now.

**Comment by alansouzati** [comment]
Thanks for pointing this out @arlair, the selected property has been moved up to the List and Table levels, but we forgot to remove it from the docs. I've fixed it in this commit:  https://github.com/grommet/grommet-docs/commit/2f3995e84be470233abde3167abe2e0556c60fe4

**Comment by arlair** [comment]
Just some feedback on the API/documentation. I had tried using the selected on the table and did not understand it/could not figure out how to use it. I ended up using onSelect to get the knowledge of selected back into the TableRow.

**Comment by zalmoxisus** [comment]
@alansouzati, I'm also confused about this change. I  used to use it like so:

```jsx
<List>
{channels && channels.map(channel => (
  <ListItem selected={channel.id === selectedId}>{channel.name}</ListItem>
))}
</List>
```

Finding the index of the channel by id to pass to List component doesn't seem optimal. So, I'll still probably pass to `ListItem` and go with a `className` to emulate `selected` behaviour, though keeping the `selected` prop for `ListItem` would be useful.

**Comment by alansouzati** [comment]
How about ?

```
<List selected={selectedId}>
{channels && channels.map(channel => (
  <ListItem>{channel.name}</ListItem>
))}
</List>
```

**Comment by zalmoxisus** [comment]
@alansouzati, I guess it will not work with the current API, `selected` should be just the index.

Not sure how we can implement that internally to pass ListItem's id. In case of Select we just pass ids as option's values, but here not sure we want to add a `value` prop for ListItem.

**Comment by alansouzati** [comment]
I'm not sure I understand the issue, I'm sorry about this @zalmoxisus.

Can you create a codepen illustrating your issue?

**Comment by zalmoxisus** [comment]
@alansouzati, sure.

Here's the old implementation with the deprecated ListItem's `selected` prop: http://codepen.io/anon/pen/pEYvQx.

Here's the desired implementation which wouldn't work: http://codepen.io/anon/pen/VKRYom.

Thanks for looking into it!

**Comment by zalmoxisus** [comment]
Here's how we could still use it without the deprecated `selected` prop: http://codepen.io/anon/pen/ALwvKA, though it would be better to still have that prop back.

**Comment by alansouzati** [comment]
The codepen you provided was not using the latest grommet bits.

http://codepen.io/grommet/pen/zKbvLW?editors=1010

I was able to make it work with this new pen using the latest grommet files.

**Comment by zalmoxisus** [comment]
@alansouzati, sorry for misunderstanding, but you use ListItem's index not the channel id. As I stated before:
> Traversing the array of objects twice, in order to find the index of the channel by id, to pass to List component doesn't seem optimal.

Unless you have a better solution than me to find `selectedChannel` by `selectedId`.

**Comment by alansouzati** [comment]
I'm hoping you are maintaining the selected element in your React state? Otherwise how would you know which element is selected in the first place?

http://codepen.io/alansouzati/pen/wzOQvO?editors=0010

I've created another codepen that illustrates how to use onSelect function from List.

**Comment by zalmoxisus** [comment]
@alansouzati, I'm maintaining it in Redux store and, yes, storing the index there could be a solution, but some channels can be removed or added in the meantime. Don't want to take too much of your time. Just wanted to point out that deprecated `selected` prop could still be useful.

**Comment by ericsoderberghp** [comment]
I would rather keep the selection as part of the container. But, I see the desire to not have to maintain/derive the index on the caller’s side. What makes it complicated is then what to pass back to the caller from the List onSelect function. We have no other means of identifying than index.

Perhaps what some people might want is the ability to manage the selection state entirely on their end and just use the per-item selected property for visual styling. The trick with that is there are lots of nuances with mouse and keyboard combinations for multi-select that I don’t see callers wanting to deal with.

**Comment by zalmoxisus** [comment]
@ericsoderberghp, I see. However, there are even more nuances the dev should take into account when maintaining the selected index for dynamic elements (like removing, adding, reordering elements).

It would be rather useful to have the same API here as for `Select` component, e.g.:
```jsx
<List
  value={this.state.selectedId}
  onSelect={(index, value) => this.setState({ selectedId: value })}
>
  {channels && channels.map(channel => (
    <ListItem
      value={channel.id}
      key={channel.id}
    >{channel.title}</ListItem>
  ))}
</List>
```
