### ISSUE TITLE
IE11 clips button inside a footer

### ISSUE THREAD

**Issue by tobinford** [grommet/grommet#974]
In IE11, buttons inside a footer component are being clipped.

### Expected Behavior

Buttons should be shown at the correct height.

### Actual Behavior

Only the top of the button is shown.

### URL, screen shot, or Codepen exhibiting the issue
![image](https://cloud.githubusercontent.com/assets/18707033/19397093/8c4dce52-9203-11e6-907a-bec1403bebec.png)

Probably happening from code in _objects.footer.scss:

.#{$grommet-namespace}footer {
  min-height: $footer-height;
  width: 100%;

  // Height is needed to coerce IE11 into aligning center even though
  // this is ignored by min-height. (Also needed on header--large and
  // header--small.) We need to subtract 1 unit in order to allow
  // min-height to keep the header height dynamic.
  @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    height: $footer-height - 1;
  }
}

### Steps to Reproduce
 1. Create a Form with a footer that contains a button
 2. 
 3. 

### Your Environment

* Grommet version: 1.0.0
* Browser Name and version: IE11
* Operating System and version (desktop or mobile): Windows 7 desktop

**Comment by epilande** [comment]
Hi @tobinford, we can fix this by wrapping the Button in a Menu component. 

```javascript
<Footer>
  <Menu>
    <Button label="Submit" primary={true} />
  </Menu>
</Footer>
```

**Comment by nickjvm** [comment]
@epilande That seems like a little bit of a hack, since the footer isn't really a menu. 

https://github.com/grommet/grommet/blob/master/src/scss/grommet-core/_objects.footer.scss#L12
By default, The footer `box-sizing` is `border-box`. so maybe in this IE11 case, we need to set `box-sizing: content-box` in addition to forcing a height?

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/83586e008ec4f02b79eaba62562046338bb1a7a0
