### ISSUE TITLE
Arrow overlaps with Formfield content

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#976]
When there's an option with a long name in a field field, the caret overlaps the text at some widths.

### Expected Behavior

User should always be able to view the label.

### Actual Behavior

The label gets truncated.

### URL, screen shot, or Codepen exhibiting the issue

![image](https://cloud.githubusercontent.com/assets/14231471/19399450/72736c82-9206-11e6-8221-89048405b8aa.png)

http://codepen.io/mcwagner10/pen/KgmZbG
![image](https://cloud.githubusercontent.com/assets/14231471/19398624/5b370ba4-9202-11e6-81e4-5665c29a2099.png)

### Steps to Reproduce
 1. See codepen

### Your Environment

* Grommet version: 1.0.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Win10

**Comment by ericsoderberghp** [comment]
Fixed in e2d956272e9c82750656b325ab3837d65a21ffad.
