### ISSUE TITLE
When clicking "NOW" on DateTime component, the pop-up remains

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#978]
When clicking "NOW" on DateTime component, the pop-up remains.  Having this feature is especially important if the user is only selecting a date (as opposed to a time).

### Expected Behavior

Pop-up should close when user selects "now".  The current date (and time is applicable) should be put into the input.

### Actual Behavior

The window remains even if the time component of DateTime is not used.

### URL, screen shot, or Codepen exhibiting the issue

https://grommet.github.io/docs/date-time/examples#3

### Steps to Reproduce
 1. See example

### Your Environment

* Grommet version: 1.0.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Win10

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/commit/42b19a553bdf46ac49b87663f70b950d161fe4eb
