### ISSUE TITLE
Menu component dropAlign

### ISSUE THREAD

**Issue by fullc0ntr0l** [grommet/grommet#981]
First my intention was to hide the line showed up over the icon space when the menu is expanded. The reason is that if I have another Button or other Component on the left side and the actual menu have `dropAlign={{"right": "right"}}` , its covered by the actual menu when I expand it. You can see that here : [Here second menu covers first menu icon](https://codepen.io/anon/pen/XjPwbz?&editors=0010) . First menu icon is covered when second menu is expanded.
### Expected Behavior

When expanded  I expect to see only menu anchors without first component (the copy of the Actions icon). That should work with `dropAlign={{"top": "bottom"}}` but there is the issue explained here. Also that refers to bottom: top, right: left, left: right
### Actual Behavior

First of all it copy the actual icon and append it to the list of anchors. When I click on the second copied Icon the menu is closed, but when I click on the original icon it hangs there opened forever. In the dev tools Elements tab you can see that the actual behavior creates new dublicate nodes of that Menu.
[Here is the issue codepen](https://codepen.io/anon/pen/WGgBvA?&editors=0010)
### Your Environment

- Grommet version: v1.0.0
- Browser Name and version: Chrome 53.0.2785.143
- Operating System and version (desktop or mobile): Windows 7 Ultimate x64

**Comment by tracybarmore** [comment]
Reproduced issue: https://codepen.io/tracybarmore/pen/VmKGVG?&editors=0010.

**Comment by ericsoderberghp** [comment]
When the `dropAlign` causes the drop down to be placed such that it doesn't eclipse the control, we should not be replicating the control inside the drop down. Also, we should ensure that the original control is styled in a way to indicate that it is active.

**Comment by tracybarmore** [comment]
Hi @fullc0ntr0l, thanks for all your collaboration with us. We will be cleaning up our backlog first week of January 2017 by closing unresponsive issues that haven't been active for at least 30 days.

If you would like this issue to remain open in our backlog, please comment to let us know. Thanks!

**Comment by fullc0ntr0l** [comment]
Well this is still not resolved, why should you close it?

**Comment by tracybarmore** [comment]
Backlog Grooming Jan 4, 2017 - Not resolved, remaining in backlog.

**Comment by tracybarmore** [comment]
Linking with #1208
