### ISSUE TITLE
Exception thrown when using MarkerLabel

### ISSUE THREAD

**Issue by guilhermerotta** [grommet/grommet#982]
### Expected Behavior

N/A
### Actual Behavior

The following exception is being thrown when using MarkerLabel on a Chart, no matter what component or HTML tag is used to create the label:

> warning.js?8a56:36 Warning: Unknown prop `announce` on <label> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in label (created by Label)
    in Label (created by SearchTimeline)
    in div (created by MarkerLabel)
    in div (created by MarkerLabel)
    in MarkerLabel (created by SearchTimeline)
    in div (created by Chart)
    in Chart (created by SearchTimeline)
...

### Your Environment

* Grommet version: 1.0.0
* Browser Name and version: Chrome 53.0.2785.143 m (64-bit)
* Operating System and version (desktop or mobile): Windows 10 64bit

**Comment by guilhermerotta** [comment]
CodePen: http://codepen.io/anon/pen/ZprgZQ?editors=0011

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet/commit/a3fe6d88fca005ce4770f2254dd2aa5042b16103
