### ISSUE TITLE
Graph colors look identical

### ISSUE THREAD

**Issue by coltonw** [grommet/grommet#983]
### Expected Behavior

I would expect to be able to distinguish at a glance different bands on a series meter using the included grommet graph colors.
### Actual Behavior

Instead, the colors look nearly identical unless you are looking at them super carefully.
### URL, screen shot, or Codepen exhibiting the issue

This graph sample shows the problem really well:
https://grommet.github.io/hpe/docs/meter/examples#19
### Your Environment

- Grommet version: 1.0.0

**Comment by L0ZZI** [comment]
Thanks Will! We are investigating and will enhancing Grommet's color implementation and documentation. This requires and evaluation of all themes so there is some design investigation needed before we can change the dev side.\

**Comment by tracybarmore** [comment]
linking with grommet/grommet-design#31

**Comment by tracybarmore** [comment]
This issue will be completed with #1166

**Comment by cherih** [comment]
The color study is done and the changes are planned for 2.0.

Need Chris Lozzi to provide a link to the color study results.

**Comment by L0ZZI** [comment]
Colors can now be chosen for specific need in v2, http://v2.grommet.io
The accessibility impacts are now on the developer/designer to ensure good contrast and readability.
