### ISSUE TITLE
<Select> defaultValue not working

### ISSUE THREAD

**Issue by stefanheine** [grommet/grommet#986]
### Expected Behavior

according to the documentation, I should be able to use 'defaultValue' in Select, but this is not working.
### Actual Behavior

my 'defaultValue' setting is ignored.
### URL, screen shot, or Codepen exhibiting the issue

```
                  <Select options={[
                    {value: 'Low', label: 'Low'},
                    {value: 'Medium', label: 'Medium'},
                    {value: 'High', label: 'High'},
                    {value: 'Very High', label: 'Very High'},
                    {value: 'Critical', label: 'Critical'}]}
                    onChange={this.handleSelectSeverity}
                    value={this.state.formData.severity}
                    placeholder='Pick severity'
                    defaultValue={{value: 'Medium', label: 'Medium'}}
                  />
```
### Your Environment
- Grommet version: 1.0.0
- Browser Name and version: Chrome
- Operating System and version (desktop or mobile): Linux

**Comment by ericsoderberghp** [comment]
Thanks for reporting this. Since it wasn't doing anything, and since you can control the component's chosen option via the `value` property, we've removed `defaultValue` from the documentation.
