### ISSUE TITLE
placeHolder not working as expected

### ISSUE THREAD

**Issue by stefanheine** [grommet/grommet#987]
### Expected Behavior
according to the documentation I should be able to use 'placeHolder' in TextInput and Select, but I need to spell this 'placeholder' instead.

### Actual Behavior
warning.js:36 Warning: Unknown DOM property placeHolder. Did you mean placeholder?

### URL, screen shot, or Codepen exhibiting the issue
                    <TextInput
                       onDOMChange={this.handleInputSummary}
                       placeHolder='Type oneliner summary'
                       />

### Your Environment
* Grommet version: 1.0.0
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Linux

**Comment by davidcalhoun** [comment]
Thanks for submitting this issue!  I created a CodePen and verified it's a problem with just TextInput - it seems to work fine on Select.  I'm getting a PR in to fix this soon.  :)

http://codepen.io/franksvalli/pen/bwOzqJ

<img width="968" alt="screen shot 2016-10-21 at 8 51 53 pm" src="https://cloud.githubusercontent.com/assets/120596/19616761/89ebc4fc-97d0-11e6-8cff-78200d215e95.png">
