### ISSUE TITLE
Sidebar does not fix Header neither Footer.

### ISSUE THREAD

**Issue by MarcoMedrano** [grommet/grommet#991]
Hi there, I am trying to set a fixed Header and Footer in a Sidebar. From documentation I got this:
https://grommet.github.io/docs/sidebar

> fixed      true|false
> Whether any contained Header and Footer should be fixed to the top and bottom.
### Expected Behavior

Header and Footer should stay on top and bottom when **scroll** appears.
### Actual Behavior

They move together the scroll.
### Note

As side note, I can make the header fixed={true} and it stays top, but if there is background color the header is overlayed with a white color.
### Your Environment
- Grommet version: 1.0.0
- Browser Name and version: chrome 53.0.2785.143 m
- Operating System and version (desktop or mobile): Windows 10

**Comment by ericblade** [comment]
As far as I can tell, neither Header nor Footer fixed or float are working correctly.

**Comment by ericsoderberghp** [comment]
Fixed. http://codepen.io/grommet/pen/rWWyOV?editors=0010

**Comment by MarcoMedrano** [comment]
It looks great! I will try it.
Thanks!

**Comment by MarcoMedrano** [comment]
Seems this bug is happening again http://codepen.io/grommet/pen/rWWyOV?editors=0010

**Comment by mvanlonden** [comment]
`Header`'s fixed prop works great on desktop but isn't working on mobile 😕
