### ISSUE TITLE
Menu goes offscreen

### ISSUE THREAD

**Issue by mcwagner10** [grommet/grommet#993]
If there's a "end" aligned menu and the menu items are longer than the menu title, then the drop down appears off screen.
### Expected Behavior

Menu should align itself to ensure that no horizontal scroll bar is shown.
### Actual Behavior

Horizontal scroll bar is shown.
### URL, screen shot, or Codepen exhibiting the issue

![image](https://cloud.githubusercontent.com/assets/14231471/19552240/df6a3986-9663-11e6-8e44-ef576a89d668.png)

### Steps to Reproduce
1. Make "end" aligned menu
2. Change menu label to something short such as "help"
3. Make menu items that are long such as "Quickstart Guide"
4. Notice horizontal scroll.
### Your Environment

- Grommet version: Stable
- Browser Name and version: Chrome 
- Operating System and version (desktop or mobile): Win10

**Comment by davidcalhoun** [comment]
Can't seem to reproduce this - I tried in this Codepen: http://codepen.io/franksvalli/pen/kkqKAy?editors=0010.  Could you fork that Codepen and try to make the markup as close as possible to yours?

Tried it in Chrome 54 in Windows 10:
![993](https://cloud.githubusercontent.com/assets/120596/19709087/9a29018a-9ad8-11e6-938f-c096d207a4ed.png)

**Comment by mcwagner10** [comment]
Thanks for the response.  Here's a sample.  Two issues:

http://codepen.io/mcwagner10/pen/MjNNEa

- One menu covers up another menu
- Menu goes out of bounds

**Comment by ericsoderberghp** [comment]
Typically, when a Menu is on the right side we align the drop with the right edge of the control via `dropAlign={{ right: 'right' }}`.

**Comment by ericsoderberghp** [comment]
Per prior comment, you need to set the `dropAlign` property.
