### ISSUE TITLE
Using Toast without App Component

### ISSUE THREAD

**Issue by joachimhb** [grommet/grommet#995]
### Expected Behavior
No exception

### Actual Behavior
Throws exception 'Cannot read property 'setAttribute' of null(…)'

There is somewhere a function **announce** that queries for a div with class 'grommetux-app__announcer' and then executes setAttribute on it, but as it's null...

### Steps to Reproduce
 1. Show a Toast without App (missing div with class 'grommetux-app__announcer')
 
### Your Environment
* Grommet version: 1.0.0
* Browser Name and version: I guess all...
* Operating System and version (desktop or mobile): I guess all...

**Comment by alansouzati** [comment]
Thanks for this issue.

I think I can fix this warning, but any reason why not using a Grommet App component?

It is really important for accessibility reasons, if you use Toast without the enclosing App component, users with disabilities will not be able to hear the content that came in a floating container.

See this: https://grommet.github.io/docs/announcer

**Comment by joachimhb** [comment]
Hi Alan,
thanks for your fast answer.
Currently im restructuring an angular app, so rewriting low to mid-level components into react while still having a surrounding angular app because i cant do it with a big bang approach.
But anyway, i would still fix this by having an if around the announcer variable, because imo the components should not have any hard crashing dependency to any other component, at least not without any mentioning in the docs :-)
Thanks and regards,
Joachim
Am 20.10.2016 6:55 nachm. schrieb Alan Souza <notifications@github.com>:Thanks for this issue.

I think I can fix this warning, but any reason why not using a Grommet App component?

It is really important for accessibility reasons, if you use Toast without the enclosing App component, users with disabilities will not be able to hear the content that came in a floating container.

See this: https://grommet.github.io/docs/announcer

**Comment by alansouzati** [comment]
makes sense. are you up for a pull request to add that check in ?

**Comment by joachimhb** [comment]
Yes, will do so tomorrow.
Am 25.10.2016 8:59 nachm. schrieb Alan Souza <notifications@github.com>:makes sense. are you up for a pull request to add that check in ?
